{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd1","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"}],"title":"TravelDocumentType.td1","roleHeading":"Case"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/td1"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td1"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td1"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"url":"\/documentation\/dotdocument\/traveldocumenttype","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"title":"TravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/td1":{"url":"\/documentation\/dotdocument\/traveldocumenttype\/td1","navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}],"abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/td1","title":"TravelDocumentType.td1","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTTravelDocumentTypeTd1"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"DOTTravelDocumentTypeTd1","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace"},{"value":"DOTTravelDocumentTypeTd1","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType~1td1\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType~1td1\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd1"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"}]}]}