{"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/hash","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"platforms":[{"unavailable":false,"beta":false,"name":"iOS","deprecated":false,"introducedAt":"13.0"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation(py)hash"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/hash":{"abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/hash","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.9.0"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"title":"MachineReadableZoneInformation"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"hash","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1hash\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation","op":"replace"},{"op":"replace","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}