{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/y","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/pointint\/y"]},{"paths":["\/documentation\/dotpalmcore\/pointint\/y"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Y coordinate."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)y","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","navigatorTitle":[{"text":"y","kind":"identifier"}],"title":"y"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PointInt":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"title":"PointInt","kind":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotpalmcore\/pointint","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointInt/y":{"kind":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointInt\/y","url":"\/documentation\/dotpalmcore\/pointint\/y","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"y","kind":"identifier"}],"title":"y"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"y"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"y","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"y"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/title"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1y\/title","value":"y","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointInt~1y\/fragments","value":[{"kind":"identifier","text":"y"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}