{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc"]},{"paths":["\/documentation\/dotnfc"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"DotNfc","title":"DotNfc","modules":[{"name":"DotNfc"}],"roleHeading":"Framework","role":"collection","symbolKind":"module"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc"},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"],"title":"Global components"},{"title":"Non-UI components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"],"title":"NFC protocols"},{"title":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/Image","doc:\/\/DotNfc\/documentation\/DotNfc\/ImagePropertiesAnalyzerFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"],"title":"Protocols"},{"title":"Enumerations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"]}],"kind":"symbol","primaryContentSections":[{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"DotNfc provides a component for NFC reading which is easy to integrate into an iOS application. Supported documents are those which implement Machine Readable Travel Document (MRTD) standards as specified by International Civil Aviation Organization (ICAO).","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[[]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"version: 8.8.0","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/Localization":{"url":"\/documentation\/dotnfc\/localization","title":"Localization","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"url":"\/documentation\/dotnfc\/intervalfloat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Logger":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"url":"\/documentation\/dotnfc\/logger","title":"Logger"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"title":"Td1MachineReadableZone","url":"\/documentation\/dotnfc\/td1machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"navigatorTitle":[{"text":"DataAuthenticationStatus","kind":"identifier"}],"title":"DataAuthenticationStatus","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","url":"\/documentation\/dotnfc\/dataauthenticationstatus","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}],"abstract":[{"text":"Authentication status of the data and protocol used for that purpose.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"kind":"symbol","title":"ChipAuthenticationStatus","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"type":"topic","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","url":"\/documentation\/dotnfc\/chipauthenticationstatus","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationStatus"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"title":"MachineReadableZone","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"},"doc://DotNfc/documentation/DotNfc/DotSerializationVersionString":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSerializationVersionString","url":"\/documentation\/dotnfc\/dotserializationversionstring","title":"DotSerializationVersionString","type":"topic","fragments":[{"text":"DotSerializationVersionString","kind":"identifier"}],"abstract":[{"text":"Project version string for DotSerialization.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentCommonsVersionString":{"fragments":[{"kind":"identifier","text":"DotDocumentCommonsVersionString"}],"url":"\/documentation\/dotnfc\/dotdocumentcommonsversionstring","abstract":[{"type":"text","text":"Project version string for DotDocumentCommons."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentCommonsVersionString","role":"symbol","kind":"symbol","title":"DotDocumentCommonsVersionString","type":"topic"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"title":"PointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","title":"MrzElementWithCheckDigit","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"navigatorTitle":[{"text":"DebugEvent","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/debugevent","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DebugEvent"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","title":"DebugEvent","role":"symbol"},"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"url":"\/documentation\/dotnfc\/loggerloglevel","title":"LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"navigatorTitle":[{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"kind":"symbol","title":"TravelDocumentReaderPassword","abstract":[{"type":"text","text":"Password for accessing the chip."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","type":"topic"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentAccessControlError":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentaccesscontrolerror","role":"symbol","type":"topic","title":"DOTNNfcTravelDocumentAccessControlError","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentAccessControlError","abstract":[{"type":"text","text":"If access to the chip data is denied either by PACE or BAC protocol."}],"fragments":[{"text":"DOTNNfcTravelDocumentAccessControlError","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/CIImageFactory":{"kind":"symbol","title":"CIImageFactory","url":"\/documentation\/dotnfc\/ciimagefactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotLibrary":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","abstract":[],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"kind":"symbol","title":"DotLibrary","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/dotlibrary"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"url":"\/documentation\/dotnfc\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ImageSize"},"doc://DotNfc/documentation/DotNfc/CGImageFactory":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory","title":"CGImageFactory","kind":"symbol","url":"\/documentation\/dotnfc\/cgimagefactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Corners":{"kind":"symbol","title":"Corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"type":"topic","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","url":"\/documentation\/dotnfc\/corners","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"title":"NfcTravelDocumentReader","role":"symbol"},"doc://DotNfc/documentation/DotNfc/IntervalDouble":{"url":"\/documentation\/dotnfc\/intervaldouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Protocol for authentication of the chip.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","title":"ChipAuthenticationStatus.AuthenticationProtocol"},"doc://DotNfc/documentation/DotNfc/DotSerializationVersionNumber":{"url":"\/documentation\/dotnfc\/dotserializationversionnumber","abstract":[{"type":"text","text":"Project version number for DotSerialization."}],"fragments":[{"text":"DotSerializationVersionNumber","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSerializationVersionNumber","role":"symbol","kind":"symbol","type":"topic","title":"DotSerializationVersionNumber"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper":{"navigatorTitle":[{"text":"TravelDocumentReaderPasswordWrapper","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"type":"topic","title":"TravelDocumentReaderPasswordWrapper","abstract":[],"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper","role":"symbol"},"doc://DotNfc/documentation/DotNfc/BgrRawImageFactory":{"kind":"symbol","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}],"type":"topic","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory","url":"\/documentation\/dotnfc\/bgrrawimagefactory","title":"BgrRawImageFactory"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid","role":"symbol","title":"DotLibraryId","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzDate":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","title":"MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"url":"\/documentation\/dotnfc\/mrzdate","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDate"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotnfc\/rectangledouble","kind":"symbol","title":"RectangleDouble"},"doc://DotNfc/documentation/DotNfc/DotNfcVersionString":{"kind":"symbol","url":"\/documentation\/dotnfc\/dotnfcversionstring","fragments":[{"text":"DotNfcVersionString","kind":"identifier"}],"title":"DotNfcVersionString","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcVersionString","abstract":[{"text":"Project version string for DotNfc.","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"title":"DotSdkConfiguration","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/dotsdkconfiguration"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"url":"\/documentation\/dotnfc\/authenticationstatus","role":"symbol","title":"AuthenticationStatus","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of data and chip."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationStatus"}],"navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentType":{"url":"\/documentation\/dotnfc\/traveldocumenttype","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType","title":"TravelDocumentType","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}]},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentNotConnectedError":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"If NFC reading fails due to an NFC tag connection failure."}],"fragments":[{"text":"DOTNNfcTravelDocumentNotConnectedError","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentNotConnectedError","title":"DOTNNfcTravelDocumentNotConnectedError","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentnotconnectederror"},"doc://DotNfc/documentation/DotNfc/DotDocumentCommonsVersionNumber":{"url":"\/documentation\/dotnfc\/dotdocumentcommonsversionnumber","type":"topic","title":"DotDocumentCommonsVersionNumber","abstract":[{"type":"text","text":"Project version number for DotDocumentCommons."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentCommonsVersionNumber","role":"symbol","fragments":[{"text":"DotDocumentCommonsVersionNumber","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","kind":"symbol","title":"MrzElement","type":"topic","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","url":"\/documentation\/dotnfc\/mrzelement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/BgrRawImage":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrrawimage","role":"symbol","kind":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"title":"BgrRawImage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotCoreVersionString":{"url":"\/documentation\/dotnfc\/dotcoreversionstring","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotCoreVersionString","title":"DotCoreVersionString","kind":"symbol","fragments":[{"kind":"identifier","text":"DotCoreVersionString"}],"role":"symbol","abstract":[{"type":"text","text":"Project version string for DotCore."}]},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibrary"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary","title":"DotNfcLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotNfc","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid","title":"Lds1ElementaryFileId","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotNfcVersionNumber":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcVersionNumber","url":"\/documentation\/dotnfc\/dotnfcversionnumber","type":"topic","abstract":[{"type":"text","text":"Project version number for DotNfc."}],"role":"symbol","kind":"symbol","title":"DotNfcVersionNumber","fragments":[{"text":"DotNfcVersionNumber","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic","title":"TravelDocument","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"abstract":[{"text":"Supported image formats.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","type":"topic","role":"symbol","title":"ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotnfc\/imageformat","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzNameElement":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/mrznameelement","title":"MrzNameElement"},"doc://DotNfc/documentation/DotNfc/DotSdk":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","title":"DotSdk","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotnfc\/dotsdk"},"doc://DotNfc/documentation/DotNfc/DotCoreVersionNumber":{"kind":"symbol","role":"symbol","type":"topic","title":"DotCoreVersionNumber","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotCoreVersionNumber","abstract":[{"type":"text","text":"Project version number for DotCore."}],"fragments":[{"kind":"identifier","text":"DotCoreVersionNumber"}],"url":"\/documentation\/dotnfc\/dotcoreversionnumber"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderError":{"kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"If reading fails due to any other reason.","type":"text"}],"fragments":[{"text":"DOTNNfcTravelDocumentReaderError","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderError","title":"DOTNNfcTravelDocumentReaderError","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreadererror"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"abstract":[],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol","title":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","role":"symbol","type":"topic","title":"DOTNNfcTravelDocumentReaderConfiguration","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration","fragments":[{"text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Configuration options for "},{"type":"text","text":"NfcTravelDocumentReader"},{"type":"text","text":"."}]},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"url":"\/documentation\/dotnfc\/debuginfo","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","type":"topic","title":"DebugInfo","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugInfo"}],"navigatorTitle":[{"kind":"identifier","text":"DebugInfo"}]},"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","url":"\/documentation\/dotnfc\/nameofholder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NameOfHolder","kind":"identifier"}],"abstract":[{"type":"text","text":"Name of travel document holder."}],"type":"topic","role":"symbol","title":"NameOfHolder","navigatorTitle":[{"text":"NameOfHolder","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusProtocol":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusProtocol","kind":"symbol","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatusprotocol","type":"topic","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"role":"symbol","fragments":[{"text":"DOTNChipAuthenticationStatusProtocol","kind":"identifier"}],"title":"DOTNChipAuthenticationStatusProtocol"},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","url":"\/documentation\/dotnfc\/td3machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"type":"topic","title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusStatus":{"type":"topic","kind":"symbol","title":"DOTNChipAuthenticationStatusStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus","fragments":[{"text":"DOTNChipAuthenticationStatusStatus","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Authentication status of the chip."}],"url":"\/documentation\/dotnfc\/dotnchipauthenticationstatusstatus"},"doc://DotNfc/documentation/DotNfc/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotnfc\/image","kind":"symbol","abstract":[{"type":"text","text":"Raw image data representation."}]},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentChipAuthenticationError":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentchipauthenticationerror","fragments":[{"text":"DOTNNfcTravelDocumentChipAuthenticationError","kind":"identifier"}],"title":"DOTNNfcTravelDocumentChipAuthenticationError","abstract":[{"type":"text","text":"If authentication of the chip using the Chip Authentication protocol fails. Secure connection was not established."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentChipAuthenticationError"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"url":"\/documentation\/dotnfc\/accesscontrolprotocol","role":"symbol","title":"AccessControlProtocol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","abstract":[{"type":"text","text":"Access Control protocol."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentTypeWrapper":{"role":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","title":"TravelDocumentTypeWrapper","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocumenttypewrapper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.8.0"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfigurationPollingOption":{"abstract":[{"type":"text","text":"Polling option specifies which travel documents can be detected."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfigurationPollingOption","title":"DOTNNfcTravelDocumentReaderConfigurationPollingOption","type":"topic","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfigurationpollingoption","kind":"symbol","role":"symbol","fragments":[{"text":"DOTNNfcTravelDocumentReaderConfigurationPollingOption","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/FlatTagStructureParser":{"abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"code":"OptionalDetails.content","type":"codeVoice"},{"type":"text","text":" of some documents."}],"navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser","type":"topic","url":"\/documentation\/dotnfc\/flattagstructureparser","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FlatTagStructureParser"}],"title":"FlatTagStructureParser","role":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","type":"topic","kind":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"role":"symbol","title":"BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotnfc\/bgrarawimage"},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory":{"type":"topic","url":"\/documentation\/dotnfc\/bgrarawimagefactory","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","title":"BgraRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"type":"topic","title":"MrzDateElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusWrappedProtocol":{"type":"topic","fragments":[{"text":"DOTNChipAuthenticationStatusWrappedProtocol","kind":"identifier"}],"title":"DOTNChipAuthenticationStatusWrappedProtocol","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatuswrappedprotocol","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"text","text":"AuthenticationProtocol"},{"text":".","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol"},"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusProtocol":{"type":"topic","url":"\/documentation\/dotnfc\/dotndataauthenticationstatusprotocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","title":"DOTNDataAuthenticationStatusProtocol","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTNDataAuthenticationStatusProtocol"}],"role":"symbol","abstract":[{"type":"text","text":"Protocol for authentication of the data."}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"url":"\/documentation\/dotnfc\/mrzcheckdigit","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic","title":"MrzCheckDigit","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}],"abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusStatus":{"role":"symbol","url":"\/documentation\/dotnfc\/dotndataauthenticationstatusstatus","fragments":[{"kind":"identifier","text":"DOTNDataAuthenticationStatusStatus"}],"abstract":[{"text":"Authentication status of the data.","type":"text"}],"title":"DOTNDataAuthenticationStatusStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ImagePropertiesAnalyzerFactory":{"navigatorTitle":[{"text":"ImagePropertiesAnalyzerFactory","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePropertiesAnalyzerFactory","kind":"identifier"}],"title":"ImagePropertiesAnalyzerFactory","url":"\/documentation\/dotnfc\/imagepropertiesanalyzerfactory","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImagePropertiesAnalyzerFactory"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper":{"title":"AccessControlProtocolWrapper","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"type":"topic","abstract":[{"text":"Access Control protocol wrapper.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdkError":{"url":"\/documentation\/dotnfc\/dotsdkerror","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkError","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkError","title":"DotSdkError"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"title":"MrzStringPosition","url":"\/documentation\/dotnfc\/mrzstringposition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","kind":"symbol","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/WrappedFloat":{"navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat","abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"title":"WrappedFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedFloat"}],"url":"\/documentation\/dotnfc\/wrappedfloat","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","title":"WrappedDouble","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble","url":"\/documentation\/dotnfc\/wrappeddouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":[{"title":"Global components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"]},{"title":"Non-UI components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/FlatTagStructureParser"]},{"title":"NFC protocols","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"]},{"title":"Classes","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImage","doc:\/\/DotNfc\/documentation\/DotNfc\/BgrRawImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/CIImageFactory","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentAccessControlError","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentChipAuthenticationError","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentNotConnectedError","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderError","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/Image","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"],"title":"Protocols"},{"title":"Variables","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotCoreVersionNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/DotCoreVersionString","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentCommonsVersionNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentCommonsVersionString","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcVersionNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcVersionString","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSerializationVersionNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSerializationVersionString"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfigurationPollingOption","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentType"],"title":"Enumerations"}],"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTNLocalization"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTNLogger","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTNLogger"}],"op":"replace"},{"value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace","value":"DOTNDataAuthenticationStatus"},{"value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","op":"replace"},{"op":"replace","value":"DOTNChipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"op":"replace","value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","op":"replace"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title","value":"DOTNDebugEvent"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","value":[{"text":"DOTNDebugEvent","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","value":"DOTNTravelDocumentReaderPassword"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}]},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalDouble\/fragments","op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/title","value":"DOTNTravelDocumentReaderPasswordWrapper"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/fragments"},{"op":"replace","value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title","value":"DOTMrzDate"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}]},{"op":"replace","value":"DOTNAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","op":"replace"},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace"},{"value":"DotNfcLibrary","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title"},{"value":[{"text":"DotNfcLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments"},{"value":"DOTNLds1ElementaryFileId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace"},{"value":"DOTNImageFormat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","value":[{"text":"DOTNImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/title","op":"replace","value":"DOTMrzNameElement"},{"value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","op":"replace","value":"DOTNDebugInfo"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"kind":"identifier","text":"DOTNDebugInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title","value":"DOTNNameOfHolder"},{"value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","value":"DOTTd3MachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace"},{"value":"DOTNImage","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"kind":"identifier","text":"DOTNImage"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace","value":"DOTNAccessControlProtocol"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"op":"replace","value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/fragments"},{"value":"DOTNFlatTagStructureParser","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments","value":[{"text":"DOTNFlatTagStructureParser","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments"},{"value":"DOTBgraRawImageFactory","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/title","op":"replace"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","op":"replace","value":"DOTNAccessControlProtocolWrapper"},{"op":"replace","value":[{"text":"DOTNAccessControlProtocolWrapper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","op":"replace","value":"DOTMrzStringPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]},{"op":"replace","value":"DOTWrappedFloat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace"},{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/fragments","op":"replace"}]}]}