{"variants":[{"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"description","externalID":"s:11DotDocument7BarcodeC17DetectionPositionC11descriptionSSvp","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the barcode in the image."}],"url":"\/documentation\/dotdocument\/barcode\/detectionposition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","kind":"symbol","type":"topic","title":"Barcode.DetectionPosition"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/description":{"abstract":[],"title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/description","type":"topic","url":"\/documentation\/dotdocument\/barcode\/detectionposition\/description","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/Barcode":{"abstract":[{"type":"text","text":"Result of barcode detection process."}],"url":"\/documentation\/dotdocument\/barcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","kind":"symbol","type":"topic","title":"Barcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","op":"replace","value":"DOTDBarcode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDBarcode"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDBarcode"}]}]}]}