{"abstract":[{"type":"text","text":"Top left corner point."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/topleft"]}],"metadata":{"title":"topLeft","modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument7BarcodeC17DetectionPositionC7topLeft0A4Core11PointDoubleCvp","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topLeft","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the barcode in the image."}],"url":"\/documentation\/dotdocument\/barcode\/detectionposition","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","kind":"symbol","type":"topic","title":"Barcode.DetectionPosition"},"doc://DotDocument/documentation/DotDocument/Barcode":{"abstract":[{"type":"text","text":"Result of barcode detection process."}],"url":"\/documentation\/dotdocument\/barcode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","kind":"symbol","type":"topic","title":"Barcode"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/topLeft":{"abstract":[{"type":"text","text":"Top left corner point."}],"title":"topLeft","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/topLeft","type":"topic","url":"\/documentation\/dotdocument\/barcode\/detectionposition\/topleft","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"doc://DotDocument/documentation/DotDocument/PointDouble":{"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"title":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"type":"topic","url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","op":"replace","value":"DOTDBarcode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","op":"replace","value":[{"text":"DOTDBarcode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]}]}]}