{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"kind":"text","text":"?"}],"externalID":"s:14DotFaceCommons03AnyB21AutoCaptureControllerC9imageSize0A4Core05ImageI0CSgvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"title":"imageSize"},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyFaceAutoCaptureController\/imageSize","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyFaceAutoCaptureController"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/anyfaceautocapturecontroller\/imagesize"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/AnyFaceAutoCaptureController":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"AnyFaceAutoCaptureController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyFaceAutoCaptureController","url":"\/documentation\/dotfacelite\/anyfaceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnyFaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"AnyFaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/AnyFaceAutoCaptureController/imageSize":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[],"title":"imageSize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AnyFaceAutoCaptureController\/imageSize","url":"\/documentation\/dotfacelite\/anyfaceautocapturecontroller\/imagesize","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","url":"\/documentation\/dotfacelite\/imagesize","kind":"symbol","type":"topic","title":"ImageSize"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]}]}]}