{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error\/LocalizedError-Implementations"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"title":"errorDescription","extendedModule":"DotCore","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:6DotNfc0aB7LibraryC5ErrorO","roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotnfclibrary\/error\/errordescription"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error\/errorDescription"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/Error":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"DotNfcLibrary.Error","role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary\/error","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/Error/errorDescription":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error\/errorDescription","type":"topic","url":"\/documentation\/dotnfc\/dotnfclibrary\/error\/errordescription","title":"errorDescription","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary\/Error\/LocalizedError-Implementations","role":"collectionGroup","url":"\/documentation\/dotnfc\/dotnfclibrary\/error\/localizederror-implementations"},"doc://DotNfc/documentation/DotNfc/DotNfcLibrary":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibrary"}],"title":"DotNfcLibrary","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibrary","kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotnfclibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library initialization."}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibrary"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/title","value":"DotNfcLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments","value":[{"text":"DotNfcLibrary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibrary\/navigatorTitle","value":[{"kind":"identifier","text":"DotNfcLibrary"}]}]}]}