{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"init(image:face:deviceTiltAngles:validatorIdentifiers:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"TiltAngles"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection(im)initWithImage:face:deviceTiltAngles:validatorIdentifiers:","role":"symbol","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","text":"FaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","text":"Face"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","text":"TiltAngles"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","abstract":[{"text":"Detected face.","type":"text"}],"title":"DOTFLFaceDetectorFace","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","fragments":[{"text":"DOTFLFaceDetectorFace","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection/init(image:face:deviceTiltAngles:validatorIdentifiers:)":{"navigatorTitle":[{"text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)","abstract":[],"title":"init(image:face:deviceTiltAngles:validatorIdentifiers:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"title":"TiltAngles","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"text":"Also see ","type":"text"},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference"},{"text":".","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/tiltangles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","title":"Sensor Coordinate System"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"title":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"navigatorTitle":[{"kind":"identifier","text":"Face"}],"url":"\/documentation\/dotfacelite\/facedetector\/face","title":"FaceDetector.Face","abstract":[{"text":"Detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"title":"Image","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfacelite\/image"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLFaceDetectorFace","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTTiltAngles","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceTiltAngles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"validatorIdentifiers","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/title","value":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}]}]}