{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},{"text":".","kind":"text"},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"title":"init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection(im)initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","symbolKind":"init","navigatorTitle":[{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/init(bgrarawimage:face:devicetiltangles:validatoridentifiers:)"]},{"paths":["\/documentation\/dotfacelite\/faceautocapturedetection\/init(bgrarawimage:face:devicetiltangles:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)":{"url":"\/documentation\/dotfacelite\/faceautocapturedetection\/init(bgrarawimage:face:devicetiltangles:validatoridentifiers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"text":".","kind":"text"},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"kind":"symbol","abstract":[],"type":"topic","title":"init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection\/init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)","navigatorTitle":[{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector\/face","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Face"}],"title":"FaceDetector.Face"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"type":"topic","abstract":[{"type":"text","text":"Detected face."}],"fragments":[{"text":"DOTFLFaceDetectorFace","kind":"identifier"}],"title":"DOTFLFaceDetectorFace","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 8.15.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/tiltangles","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"title":"TiltAngles"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","title":"BgraRawImage","role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"title":"FaceAutoCaptureDetection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"title":"FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFLFaceDetectorFace","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace"},{"kind":"text","text":" *) "},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceTiltAngles:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTTiltAngles","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"kind":"text","text":" *) "},{"text":"deviceTiltAngles","kind":"internalParam"},{"kind":"text","text":" "},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validatorIdentifiers"},{"text":";","kind":"text"}]}]}},{"value":"DOTFLMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"op":"replace","value":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection~1init(bgraRawImage:face:deviceTiltAngles:validatorIdentifiers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBgraRawImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}]},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments"}]}]}