{"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/backgroundUniformity","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"backgroundUniformity","kind":"identifier"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"roleHeading":"Case","symbolKind":"case","title":"DotFaceModuleId.backgroundUniformity","role":"symbol","externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdBackgroundUniformity","modules":[{"name":"DotFaceCore"}]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId":{"role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemoduleid","title":"DotFaceModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId/backgroundUniformity":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"abstract":[],"title":"DotFaceModuleId.backgroundUniformity","type":"topic","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/backgrounduniformity","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/backgroundUniformity","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdBackgroundUniformity","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1backgroundUniformity\/title","value":"DotFaceModuleIdBackgroundUniformity","op":"replace"},{"value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1backgroundUniformity\/fragments"}]}]}