{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionFast"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdDetectionFast","title":"DotFaceModuleId.detectionFast","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/detectionfast"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/detectionfast"]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionFast"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionFast","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId":{"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleId","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"kind":"symbol","title":"DotFaceModuleId","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.0.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId/detectionFast":{"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/detectionfast","abstract":[],"navigatorTitle":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}],"kind":"symbol","title":"DotFaceModuleId.detectionFast","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/detectionFast"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DotFaceModuleIdDetectionFast","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionFast\/title","value":"DotFaceModuleIdDetectionFast"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1detectionFast\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}