{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"metadata":{"title":"DotFaceModuleId.expressionNeutral","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdExpressionNeutral","symbolKind":"case","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/expressionNeutral"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/expressionneutral"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/expressionneutral"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"kind":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","type":"topic","title":"DotFaceModuleId"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/expressionNeutral":{"title":"DotFaceModuleId.expressionNeutral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"expressionNeutral","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/expressionneutral","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/expressionNeutral","kind":"symbol","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DotFaceModuleIdExpressionNeutral","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1expressionNeutral\/title","op":"replace","value":"DotFaceModuleIdExpressionNeutral"},{"op":"replace","value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1expressionNeutral\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}