{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLiveness"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/eyegazeliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/eyegazeliveness"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/eyeGazeLiveness"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","title":"DotFaceModuleId.eyeGazeLiveness","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdEyeGazeLiveness","symbolKind":"case","roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/eyeGazeLiveness":{"url":"\/documentation\/dotfacecore\/dotfacemoduleid\/eyegazeliveness","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/eyeGazeLiveness","navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","title":"DotFaceModuleId.eyeGazeLiveness","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"kind":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","type":"topic","title":"DotFaceModuleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleIdEyeGazeLiveness"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1eyeGazeLiveness\/title","op":"replace","value":"DotFaceModuleIdEyeGazeLiveness"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1eyeGazeLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments"}]}]}