{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdVerification","symbolKind":"case","role":"symbol","roleHeading":"Case","title":"DotFaceModuleId.verification","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/verification"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/verification"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/verification"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId/verification":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId\/verification","kind":"symbol","abstract":[],"title":"DotFaceModuleId.verification","type":"topic","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/verification","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verification"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleId":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","type":"topic","kind":"symbol","role":"symbol","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DotFaceModuleIdVerification","path":"\/metadata\/title","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1verification\/title","value":"DotFaceModuleIdVerification"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId~1verification\/fragments","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}