{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory"]]},"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/cgimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(bgraRawImage:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"bgraRawImage"}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","title":"create(bgraRawImage:)","externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgraRawImage:","symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Type Method"},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/CGImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"url":"\/documentation\/dotnfc\/cgimagefactory","title":"CGImageFactory","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimage","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","type":"topic","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}]},"doc://DotNfc/documentation/DotNfc/CGImageFactory/create(bgraRawImage:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"kind":"symbol","title":"create(bgraRawImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"url":"\/documentation\/dotnfc\/cgimagefactory\/create(bgrarawimage:)","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CGImageFactory\/create(bgraRawImage:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"text":" *) ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:"}],"op":"replace"}]}]}