{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/y","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt"]]},"kind":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/pointint\/y"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/pointint\/y"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"y","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"y","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)y","roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://DotNfc/documentation/DotNfc/PointInt":{"kind":"symbol","type":"topic","title":"PointInt","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointInt","kind":"identifier"}],"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/pointint"},"doc://DotNfc/documentation/DotNfc/PointInt/y":{"url":"\/documentation\/dotnfc\/pointint\/y","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"y","kind":"identifier"}],"kind":"symbol","title":"y","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/y","role":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"y","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"y","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"text":"y","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"value":"DOTPointInt","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/fragments","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/navigatorTitle","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1y\/fragments","value":[{"kind":"identifier","text":"y"}]}]}]}