{"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"smileLivenessViewControllerViewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"smileLivenessViewControllerViewDidAppear:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate(im)smileLivenessViewControllerViewDidAppear:","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidAppear(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"type":"text","text":"UI Smile Liveness component."}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"title":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewControllerViewDidAppear(_:)":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontrollerviewdidappear(_:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewControllerViewDidAppear(_:)","type":"topic","kind":"symbol","title":"smileLivenessViewControllerViewDidAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"smileLivenessViewControllerViewDidAppear:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"role":"symbol","abstract":[{"type":"text","text":"Implement this delegate to the handle smile liveness events."}],"title":"SmileLivenessViewControllerDelegate","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"smileLivenessViewControllerViewDidAppear:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"smileLivenessViewControllerViewDidAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFSmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace","value":"DOTFSmileLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidAppear(_:)\/title","value":"smileLivenessViewControllerViewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewControllerViewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewControllerViewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title","value":"DOTFSmileLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments","value":[{"text":"DOTFSmileLivenessViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFSmileLivenessViewControllerDelegate","kind":"identifier"}]}]}]}