{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"smileLivenessViewController:processed:","kind":"identifier"}],"title":"smileLivenessViewController(_:processed:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"smileLivenessViewController"},{"text":"(","kind":"text"},{"text":"SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFSmileLivenessViewControllerDelegate(im)smileLivenessViewController:processed:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:processed:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileLivenessViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","kind":"typeIdentifier","text":"SmileLivenessViewController"},{"kind":"text","text":", "},{"text":"processed","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","kind":"typeIdentifier","text":"FaceAutoCaptureDetection"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontroller(_:processed:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"title":"FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate/smileLivenessViewController(_:processed:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate\/smileLivenessViewController(_:processed:)","abstract":[{"text":"Tells the delegate that the new detection was processed.","type":"text"}],"navigatorTitle":[{"text":"smileLivenessViewController:processed:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate\/smilelivenessviewcontroller(_:processed:)","title":"smileLivenessViewController(_:processed:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"smileLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"SmileLivenessViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontrollerdelegate","title":"SmileLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to the handle smile liveness events."}],"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewControllerDelegate"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewControllerDelegate","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"smileLivenessViewController:processed:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"smileLivenessViewController:processed:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"smileLivenessViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController","text":"DOTFSmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":" ","kind":"text"},{"text":"processed:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","kind":"typeIdentifier","text":"DOTFFaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"value":"smileLivenessViewController:processed:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:processed:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate~1smileLivenessViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"smileLivenessViewController:processed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/title","value":"DOTFSmileLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}