{"variants":[{"paths":["\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"camera","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"camera","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"camera","externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration(py)camera","role":"symbol"},"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Default is:","type":"text"},{"text":" ","type":"text"},{"text":"\\code","type":"text"},{"text":" ","type":"text"},{"text":".init(cameraFacing: .front)","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},{"text":" * ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\Endcode"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/camera"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","title":"DOTFBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","fragments":[{"text":"DOTFBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration/camera":{"fragments":[{"text":"camera","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/camera","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/camera","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"type":"topic","title":"camera","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}