{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/capturemode"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration(py)captureMode","navigatorTitle":[{"text":"captureMode","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"captureMode","kind":"identifier"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"captureMode"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/captureMode"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration"]]},"abstract":[{"type":"text","text":"Capture mode. Default value is "},{"type":"text","text":".autoCapture"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration/captureMode":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/capturemode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/captureMode","fragments":[{"text":"captureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode. Default value is "},{"type":"text","text":".autoCapture"},{"type":"text","text":"."}],"type":"topic","role":"symbol","title":"captureMode"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"role":"symbol","url":"\/documentation\/dotfacecore\/capturemode","type":"topic","abstract":[{"type":"text","text":"Capture mode."}],"navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"title":"CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","title":"DOTFBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","fragments":[{"text":"DOTFBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}