{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/common"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" * ","kind":"text"},{"text":"common","kind":"identifier"},{"text":";","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/common"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"common"}],"title":"common","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"common"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration(py)common"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration/common":{"type":"topic","fragments":[{"text":"common","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration\/common","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"title":"common","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration\/common","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","fragments":[{"text":"DOTFBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","title":"DOTFBaseFaceAutoCaptureConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","title":"CommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/commonconfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"}]}]}