{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"text":" format as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"title":"createBgraRawImage(bgrRawImage:)","role":"symbol","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithBgrRawImage:","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(bgrrawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(bgrrawimage:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with a "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format. Terminates if the passed image is not in the correct format."}]}],"name":"bgrRawImage"}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgraRawImage(bgrRawImage:)":{"title":"createBgraRawImage(bgrRawImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"url":"\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(bgrrawimage:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","type":"topic","navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"type":"topic","abstract":[],"title":"Image","kind":"symbol","url":"\/documentation\/dotfacecore\/image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory":{"type":"topic","abstract":[{"type":"text","text":"Create "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"title":"ImageFactory","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","url":"\/documentation\/dotfacecore\/imagefactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"}]}]}