{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/back"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/camerafacing\/back"]},{"paths":["\/documentation\/dotpalmcore\/camerafacing\/back"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing@DOTCameraFacingBack","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"symbolKind":"case","role":"symbol","title":"CameraFacing.back","navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"roleHeading":"Case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Back facing camera."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotpalmcore\/camerafacing","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","title":"CameraFacing","type":"topic","role":"symbol","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/back":{"abstract":[{"text":"Back facing camera.","type":"text"}],"role":"symbol","title":"CameraFacing.back","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/back","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/back","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DOTCameraFacingBack","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraFacingBack"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCameraFacingBack","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1back\/title","value":"DOTCameraFacingBack"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1back\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacingBack"}]}]}]}