{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"]]},"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/!=(_:_:)"],"anchor":"Operators"}],"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/camerafacing\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"Equatable Implementations","modules":[{"name":"DotPalmCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/!=(_:_:)":{"title":"!=(_:_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/!=(_:_:)","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing\/!=(_:_:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","url":"\/documentation\/dotpalmcore\/camerafacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}