{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/camerafacing\/front"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/camerafacing\/front"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"front","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"CameraFacing.front","role":"symbol","symbolKind":"case","externalID":"c:@M@DotCamera@E@DOTCameraFacing@DOTCameraFacingFront","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"text":"Front facing camera.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/front","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/front":{"title":"CameraFacing.front","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/front","role":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing\/front","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"front","kind":"identifier"}],"navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}],"abstract":[{"text":"Front facing camera.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","url":"\/documentation\/dotpalmcore\/camerafacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTCameraFacingFront"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTCameraFacingFront","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1front\/title","op":"replace","value":"DOTCameraFacingFront"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1front\/fragments","op":"replace","value":[{"text":"DOTCameraFacingFront","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}