{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/camerafacing\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/init(rawValue:)"},"metadata":{"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(rawValue:)","modules":[{"name":"DotPalmCore"}],"externalID":"s:9DotCamera0B6FacingO8rawValueACSgSi_tcfc","roleHeading":"Initializer"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/init(rawValue:)":{"abstract":[],"url":"\/documentation\/dotpalmcore\/camerafacing\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/init(rawValue:)"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","url":"\/documentation\/dotpalmcore\/camerafacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","title":"CameraFacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}