{"metadata":{"externalID":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC8DefaultsV45minValidSamplesInRowToStartCandidateSelectionSivpZ","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/Defaults"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/Defaults\/minValidSamplesInRowToStartCandidateSelection","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/defaults\/minvalidsamplesinrowtostartcandidateselection"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class/Defaults":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureController.Configuration.Defaults","abstract":[],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/defaults"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureController.Configuration","abstract":[{"text":"Configuration of the fingers auto capture non-UI component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class/Defaults/minValidSamplesInRowToStartCandidateSelection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class\/Defaults\/minValidSamplesInRowToStartCandidateSelection","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"minValidSamplesInRowToStartCandidateSelection","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class\/defaults\/minvalidsamplesinrowtostartcandidateselection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}