{"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nameofholder\/init(primaryidentifier:secondaryidentifier:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nameofholder\/init(primaryidentifier:secondaryidentifier:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/init(primaryIdentifier:secondaryIdentifier:)"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder"]]},"metadata":{"platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false,"beta":false}],"modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","navigatorTitle":[{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder(im)initWithPrimaryIdentifier:secondaryIdentifier:","symbolKind":"init","title":"init(primaryIdentifier:secondaryIdentifier:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"secondaryIdentifier","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"secondaryIdentifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"url":"\/documentation\/dotnfc\/nameofholder","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NameOfHolder","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"abstract":[{"type":"text","text":"Name of travel document holder."}],"title":"NameOfHolder"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/init(primaryIdentifier:secondaryIdentifier:)":{"type":"topic","title":"init(primaryIdentifier:secondaryIdentifier:)","url":"\/documentation\/dotnfc\/nameofholder\/init(primaryidentifier:secondaryidentifier:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/init(primaryIdentifier:secondaryIdentifier:)","navigatorTitle":[{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"primaryIdentifier","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithPrimaryIdentifier:secondaryIdentifier:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPrimaryIdentifier:secondaryIdentifier:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPrimaryIdentifier:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"primaryIdentifier","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryIdentifier:"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"secondaryIdentifier","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title","value":"DOTNNameOfHolder","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNameOfHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1init(primaryIdentifier:secondaryIdentifier:)\/title","value":"initWithPrimaryIdentifier:secondaryIdentifier:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1init(primaryIdentifier:secondaryIdentifier:)\/fragments","op":"replace"}]}]}