{"variants":[{"paths":["\/documentation\/dotdocument\/image\/bytes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/image\/bytes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Image"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/Image"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Image"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"lazy"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/bytes","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"symbolKind":"property","title":"bytes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage(py)bytes"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Raw image data."}],"references":{"doc://DotDocument/documentation/DotDocument/Image/bytes":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image\/bytes","role":"symbol","abstract":[{"text":"Raw image data.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/image\/bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"title":"bytes","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"title":"Image","url":"\/documentation\/dotdocument\/image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","type":"topic","abstract":[],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"role":"symbol","title":"DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"bytes","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"bytes"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1bytes\/title","op":"replace","value":"bytes"},{"value":[{"text":"bytes","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image~1bytes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","op":"replace","value":"DOTImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}