{"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/hash(into:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotNfc@E@DOTNAccessControlProtocol","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/hash(into:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"title":"hash(into:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/hash(into:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/accesscontrolprotocol\/hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/rawrepresentable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/RawRepresentable-Implementations","kind":"article","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","title":"AccessControlProtocol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"abstract":[{"text":"Access Control protocol.","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","op":"replace"},{"value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}