{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pace"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/pace"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/pace"]}],"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"case","navigatorTitle":[{"text":"DOTNAccessControlProtocolPace","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pace","kind":"identifier"}],"title":"AccessControlProtocol.pace","externalID":"c:@M@DotNfc@E@DOTNAccessControlProtocol@DOTNAccessControlProtocolPace","roleHeading":"Case","role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"]]},"abstract":[{"type":"text","text":"Password Authenticated Connection Establishment"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/pace"},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"title":"AccessControlProtocol","abstract":[{"type":"text","text":"Access Control protocol."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","url":"\/documentation\/dotnfc\/accesscontrolprotocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/pace":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/pace","role":"symbol","abstract":[{"type":"text","text":"Password Authenticated Connection Establishment"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol\/pace","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pace","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DOTNAccessControlProtocolPace","kind":"identifier"}],"title":"AccessControlProtocol.pace"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTNAccessControlProtocolPace","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTNAccessControlProtocolPace","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTNAccessControlProtocolPace","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNAccessControlProtocol","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title"},{"value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments"},{"value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle"},{"value":"DOTNAccessControlProtocolPace","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1pace\/title"},{"value":[{"text":"DOTNAccessControlProtocolPace","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1pace\/fragments"}]}]}