{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"errorDescription","symbolKind":"property","extendedModule":"DotCore","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}],"externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:11DotPalmCore0B8DetectorC5ErrorO"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/errorDescription"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/error\/errordescription"]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.errorDescription"},{"type":"text","text":"."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"type":"topic","kind":"symbol","title":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmDetector","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error/errorDescription":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/error\/errordescription","abstract":[],"title":"errorDescription","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error\/errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Error":{"title":"PalmDetector.Error","abstract":[],"url":"\/documentation\/dotpalmcore\/palmdetector\/error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Error","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","title":"DotPalmCore","abstract":[{"type":"text","text":"version: 9.2.3"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace"}]}]}