{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedFloat\/value"},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","title":"value","navigatorTitle":[{"text":"value","kind":"identifier"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(py)value","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/wrappedfloat\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/wrappedfloat\/value"]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedFloat"]]},"references":{"doc://DotDocument/documentation/DotDocument/WrappedFloat/value":{"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"kind":"identifier","text":"value"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedFloat\/value","type":"topic","title":"value","url":"\/documentation\/dotdocument\/wrappedfloat\/value","abstract":[]},"doc://DotDocument/documentation/DotDocument/WrappedFloat":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedFloat","url":"\/documentation\/dotdocument\/wrappedfloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"role":"symbol","title":"WrappedFloat","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.6.1"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"value"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"value"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedFloat~1value\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedFloat~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"},{"value":"DOTWrappedFloat","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedFloat\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedFloat\/fragments"}]}]}