{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/validate(fingersAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/validate(fingersautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/validate(fingersautocaptureframeparameters:)"]}],"abstract":[{"type":"text","text":"Validate current frame parameters."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator(im)validateWithFingersAutoCaptureFrameParameters:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true,"title":"validate(fingersAutoCaptureFrameParameters:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Current frame parameters.","type":"text"}],"type":"paragraph"}],"name":"fingersAutoCaptureFrameParameters"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" for the failed validation and ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" for the successful validation.","type":"text"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator/validate(fingersAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/validate(fingersAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","text":"FingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","title":"validate(fingersAutoCaptureFrameParameters:)","abstract":[{"text":"Validate current frame parameters.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/validate(fingersautocaptureframeparameters:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected fingers."}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}],"navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithFingersAutoCaptureFrameParameters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","text":"DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Current frame parameters."}],"type":"paragraph"}],"name":"fingersAutoCaptureFrameParameters"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for the failed validation and ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" for the successful validation.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","value":"validateWithFingersAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}]}]}]}