{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"issuingAuthority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateOfIssue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"otherPersonDetails"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"endorsementsOrObservations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"taxOrExitRequirements"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"personalizationTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"personalizationDeviceSerialNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"dateOfIssue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"otherPersonDetails","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?, ","kind":"text"},{"text":"endorsementsOrObservations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"taxOrExitRequirements","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"personalizationTime","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"title":"init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","symbolKind":"init","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(im)initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:otherpersondetails:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:otherpersondetails:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dateOfIssue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"otherPersonDetails","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"endorsementsOrObservations","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"taxOrExitRequirements","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"personalizationTime","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:otherpersondetails:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)","title":"init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","abstract":[]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","title":"TravelDocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalDocumentDetails":{"title":"AdditionalDocumentDetails","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalDocumentDetails","url":"\/documentation\/dotnfc\/additionaldocumentdetails","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"navigatorTitle":[{"kind":"identifier","text":"AdditionalDocumentDetails"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithIssuingAuthority:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"issuingAuthority","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dateOfIssue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dateOfIssue","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"otherPersonDetails:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"otherPersonDetails","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"endorsementsOrObservations:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"endorsementsOrObservations","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"taxOrExitRequirements:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"taxOrExitRequirements","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"personalizationTime:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"personalizationTime","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"personalizationDeviceSerialNumber:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/title","value":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithIssuingAuthority:dateOfIssue:otherPersonDetails:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title","value":"DOTNAdditionalDocumentDetails"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/navigatorTitle","value":[{"text":"DOTNAdditionalDocumentDetails","kind":"identifier"}]}]}]}