{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/!=(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"op","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","modules":[{"relatedModules":["Swift"],"name":"DotFingersCore"}],"extendedModule":"Swift","role":"symbol","roleHeading":"Operator"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotpalmmoduleid\/!=(_:_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId":{"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId","title":"DotPalmModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/!=(_:_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/!=(_:_:)","title":"!=(_:_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/navigatorTitle","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}