{"metadata":{"externalID":"s:7DotCore0A12PalmModuleIdO8rawValueACSgSi_tcfc","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotFingersCore"}],"title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/init(rawValue:)"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotpalmmoduleid\/init(rawvalue:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId":{"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId","title":"DotPalmModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}