{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/capturemode"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration"]]},"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC11captureMode0aF00fK0Ovp","title":"captureMode","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"type":"codeVoice","code":".autoCapture"},{"text":".","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/captureMode":{"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/capturemode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","title":"captureMode","type":"topic","abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"code":".autoCapture","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","role":"symbol","type":"topic","title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing high quality face images with customizable UI.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","role":"symbol","title":"BaseFaceAutoCaptureViewController.Configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"abstract":[{"text":"Capture mode.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","url":"\/documentation\/dotfacecore\/capturemode","role":"symbol","type":"topic","title":"CaptureMode","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","op":"replace","value":"DOTCaptureMode"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}