{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV","symbolKind":"struct","title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"roleHeading":"Structure","modules":[{"name":"DotFaceCore"}]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/faceSizeRatioInterval","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection"],"generated":true,"title":"Type Properties","anchor":"Type-Properties"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing high quality face images with customizable UI.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","abstract":[],"title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/faceSizeRatioInterval":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/faceSizeRatioInterval","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"}],"title":"faceSizeRatioInterval","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/facesizeratiointerval","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/captureMode":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"CaptureMode","kind":"typeIdentifier"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode","title":"captureMode"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/minValidSamplesInRowToStartCandidateSelection":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection","abstract":[],"title":"minValidSamplesInRowToStartCandidateSelection","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/candidateSelectionDurationMillis":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","role":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/candidateselectiondurationmillis","type":"topic","abstract":[],"kind":"symbol","title":"candidateSelectionDurationMillis"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"title":"BaseFaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace"}]}]}