{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:facelibrarycomponent:qualityattributethresholds:capturemode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"CommonConfiguration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"camera"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","text":"CameraConfiguration"},{"text":" = .init(facing: .front), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"text":" = try! .init(\n                faceSizeRatioInterval: Defaults.faceSizeRatioInterval,\n                query: .init()\n            ), ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"},{"text":" = .Presets.passiveLiveness.build(), ","kind":"text"},{"text":"captureMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"text":" = Defaults.captureMode)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC6common6camera04autoF020faceLibraryComponent26qualityAttributeThresholds11captureModeAE0aC006CommonI0C_0aF006CameraI0CAO0efI0CAA0bnoI0CAA0bef7QualityqR0CAO0fT0Otcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceLibraryComponent","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"captureMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceCore"}],"title":"init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","type":"topic","kind":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)":{"title":"init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:faceLibraryComponent:qualityAttributeThresholds:captureMode:)","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:facelibrarycomponent:qualityattributethresholds:capturemode:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"kind":"text","text":")"}],"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","role":"symbol","type":"topic","title":"BaseFaceAutoCaptureViewController","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"abstract":[{"text":"UI component for capturing high quality face images with customizable UI.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"title":"AutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"role":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for face library components.","type":"text"}],"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","title":"FaceLibraryComponentConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"type":"topic","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"type":"text","text":"Common configuration for all components."}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","role":"symbol","title":"BaseFaceAutoCaptureViewController.Configuration","type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"abstract":[{"text":"Capture mode.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","url":"\/documentation\/dotfacecore\/capturemode","role":"symbol","type":"topic","title":"CaptureMode","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","value":"DOTFBaseFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace"}]}]}