{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersOnly"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersOnly"}],"title":"PlaceholderType.cornersOnly","roleHeading":"Case","externalID":"c:@M@DotDocument@E@DOTDPlaceholderType@DOTDPlaceholderTypeCornersOnly","symbolKind":"case","modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornersOnly"}]},"abstract":[{"text":"Placeholder with corners only.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornersOnly"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/placeholdertype\/cornersonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/placeholdertype\/cornersonly"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/PlaceholderType/cornersOnly":{"role":"symbol","kind":"symbol","title":"PlaceholderType.cornersOnly","url":"\/documentation\/dotdocument\/placeholdertype\/cornersonly","abstract":[{"type":"text","text":"Placeholder with corners only."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersOnly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornersOnly","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DOTDPlaceholderTypeCornersOnly","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"url":"\/documentation\/dotdocument\/placeholdertype","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","title":"PlaceholderType","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"type":"topic","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTDPlaceholderTypeCornersOnly","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDPlaceholderTypeCornersOnly","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTDPlaceholderTypeCornersOnly","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersOnly\/title","value":"DOTDPlaceholderTypeCornersOnly","op":"replace"},{"op":"replace","value":[{"text":"DOTDPlaceholderTypeCornersOnly","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersOnly\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType"},{"value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments"}]}]}