{"metadata":{"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg3"}],"role":"symbol","roleHeading":"Case","title":"Lds1ElementaryFileId.dg3","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}],"modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"deprecated":false,"introducedAt":"13.0","name":"iOS"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg3"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg3"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg3"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg3"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"File identifier for data group 3. Data group 3 contains finger print data.","type":"text"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId":{"type":"topic","title":"Lds1ElementaryFileId","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.2.1"}],"role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Lds1ElementaryFileId/dg3":{"role":"symbol","type":"topic","title":"Lds1ElementaryFileId.dg3","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg3","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg3","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg3"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}],"kind":"symbol","abstract":[{"text":"File identifier for data group 3. Data group 3 contains finger print data.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg3","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","op":"replace","value":"DOTNLds1ElementaryFileId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg3","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg3\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg3\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}