{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagesize\/from(cgsize:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize\/from(cgsize:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","text":"ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize\/from(cgSize:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"from(cgSize:)","modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize"}],"externalID":"c:@CM@DotDocument@objc(cs)DOTImageSize(cm)fromCgSize:","symbolKind":"method","navigatorTitle":[{"text":"fromCgSize:","kind":"identifier"}]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageSize":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"role":"symbol","title":"ImageSize","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","kind":"symbol","url":"\/documentation\/dotdocument\/imagesize","abstract":[{"type":"text","text":"Image size in pixels."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageSize/from(cgSize:)":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize\/from(cgSize:)","url":"\/documentation\/dotdocument\/imagesize\/from(cgsize:)","title":"from(cgSize:)","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"fromCgSize:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fromCgSize:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","text":"DOTImageSize","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromCgSize:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgSize"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"value":"fromCgSize:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize~1from(cgSize:)\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromCgSize:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize~1from(cgSize:)\/fragments"}]}]}