{"metadata":{"externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:11DotDocument0B8DetectorC5ErrorO","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Method","extendedModule":"DotCore","modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"title":"composeWithInternalError()","symbolKind":"method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/DotSdkError-Implementations"]]},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/error\/composewithinternalerror()"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error/composeWithInternalError()":{"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/error\/composewithinternalerror()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/composeWithInternalError()","title":"composeWithInternalError()"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error/DotSdkError-Implementations":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/DotSdkError-Implementations","kind":"article","type":"topic","abstract":[],"title":"DotSdkError Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/documentdetector\/error\/dotsdkerror-implementations"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/error","kind":"symbol","abstract":[],"title":"DocumentDetector.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"role":"symbol","title":"DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}]}]}