{"abstract":[{"text":"Bottom left corner point.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/corners\/bottomleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners\/bottomleft"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"bottomLeft","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)bottomLeft","navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomLeft","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/pointdouble","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/bottomLeft":{"title":"bottomLeft","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/corners\/bottomleft","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomLeft","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"role":"symbol","navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"abstract":[{"type":"text","text":"Bottom left corner point."}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/corners","title":"Corners","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"bottomLeft","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"bottomLeft"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPointDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/navigatorTitle","op":"replace"},{"value":"bottomLeft","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomLeft\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bottomLeft"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomLeft\/fragments","op":"replace"},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}