{"variants":[{"paths":["\/documentation\/dotpalmcore\/corners\/init(topleft:topright:bottomright:bottomleft:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners\/init(topleft:topright:bottomright:bottomleft:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTCorners(im)initWithTopLeft:topRight:bottomRight:bottomLeft:","symbolKind":"init"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners"]]},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PointDouble":{"url":"\/documentation\/dotpalmcore\/pointdouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble","type":"topic","kind":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/Corners":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"url":"\/documentation\/dotpalmcore\/corners","title":"Corners"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","role":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/corners\/init(topleft:topright:bottomright:bottomleft:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithTopLeft:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"topLeft"},{"kind":"text","text":" "},{"text":"topRight:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","text":"DOTPointDouble"},{"kind":"text","text":" *) "},{"text":"topRight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottomRight:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble"},{"kind":"text","text":" *) "},{"text":"bottomRight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottomLeft:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PointDouble","text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPointDouble"},{"text":" *) ","kind":"text"},{"text":"bottomLeft","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PointDouble\/fragments","op":"replace"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}