{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Corners","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"}],"extendedModule":"DotCore","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)mirrored","role":"symbol","roleHeading":"Instance Method","title":"mirrored()","symbolKind":"method"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/corners\/mirrored()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners\/mirrored()"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/mirrored()"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/mirrored()":{"navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"url":"\/documentation\/dotpalmcore\/corners\/mirrored()","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/mirrored()","role":"symbol","abstract":[],"kind":"symbol","title":"mirrored()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","type":"topic","title":"Corners","role":"symbol","url":"\/documentation\/dotpalmcore\/corners","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"mirrored"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"mirrored","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","text":"DOTCorners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"kind":"text","text":" *) "},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"mirrored","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1mirrored()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"mirrored"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1mirrored()\/fragments"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}