{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"defaultThreshold","externalID":"c:@M@DotPalmCore@objc(cs)DOTPTemplateExtractionQualityTooLowValidator(cpy)defaultThreshold","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/defaultThreshold"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/defaultthreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/defaultthreshold"]}],"abstract":[{"text":"Default threshold.","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator/defaultThreshold":{"title":"defaultThreshold","abstract":[{"type":"text","text":"Default threshold."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/defaultThreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/defaultthreshold","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateExtractionQualityTooLowValidator"}],"type":"topic","abstract":[{"type":"text","text":"Validate minimum template extraction quality of the detected palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"TemplateExtractionQualityTooLowValidator"}],"title":"TemplateExtractionQualityTooLowValidator","url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"defaultThreshold","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"defaultThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1defaultThreshold\/title","op":"replace"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1defaultThreshold\/fragments","op":"replace"},{"value":"DOTPTemplateExtractionQualityTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/navigatorTitle","op":"replace"}]}]}