{"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"metadata":{"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"title":"init(threshold:)","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","externalID":"c:@M@DotPalmCore@objc(cs)DOTPTemplateExtractionQualityTooLowValidator(im)initWithThreshold:error:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init(threshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init(threshold:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/init(threshold:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator/init(threshold:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithThreshold:error:"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init(threshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(threshold:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator","abstract":[{"text":"Validate minimum template extraction quality of the detected palm.","type":"text"}],"title":"TemplateExtractionQualityTooLowValidator","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","navigatorTitle":[{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithThreshold:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"threshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1init(threshold:)\/title","op":"replace","value":"initWithThreshold:error:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1init(threshold:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title","op":"replace","value":"DOTPTemplateExtractionQualityTooLowValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPTemplateExtractionQualityTooLowValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}]}]}]}