{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPTemplateExtractionQualityTooLowValidator(im)init","roleHeading":"Initializer"},"abstract":[{"type":"text","text":"Initialize with default threshold."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/init()","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"title":"TemplateExtractionQualityTooLowValidator","role":"symbol","abstract":[{"text":"Validate minimum template extraction quality of the detected palm.","type":"text"}],"navigatorTitle":[{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator/init()":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","type":"topic","abstract":[{"type":"text","text":"Initialize with default threshold."}],"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator\/init()"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPTemplateExtractionQualityTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPTemplateExtractionQualityTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPTemplateExtractionQualityTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}