{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"camera","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration(py)camera","fragments":[{"text":"camera","kind":"identifier"}],"title":"camera","modules":[{"name":"DotFaceCore"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/camera"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"camera","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\Endcode"}]}]}],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Default is:","type":"text"},{"text":" ","type":"text"},{"text":"\\code","type":"text"},{"text":" ","type":"text"},{"text":".init(cameraFacing: .front)","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","fragments":[{"kind":"identifier","text":"DOTFMultiRangeLivenessConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","type":"topic","title":"DOTFMultiRangeLivenessConfiguration","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","title":"CameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration/camera":{"fragments":[{"text":"camera","kind":"identifier"}],"title":"camera","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/camera","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Default is:","type":"text"},{"text":" ","type":"text"},{"text":"\\code","type":"text"},{"text":" ","type":"text"},{"text":".init(cameraFacing: .front)","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/camera","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}