{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","text":"DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"faceLibraryComponent","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\Endcode"}]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/faceLibraryComponent","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Configuration for face library components."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init("},{"type":"text","text":" "},{"type":"text","text":"faceSizeRatioInterval: .init(min: 0.1, max: 0.4),"},{"type":"text","text":" "},{"type":"text","text":"query: .init()"},{"type":"text","text":" "},{"type":"text","text":")"}],"kind":"symbol","metadata":{"title":"faceLibraryComponent","role":"symbol","navigatorTitle":[{"text":"faceLibraryComponent","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration(py)faceLibraryComponent","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"faceLibraryComponent"}],"symbolKind":"property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/facelibrarycomponent"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration/faceLibraryComponent":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/faceLibraryComponent","url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/facelibrarycomponent","abstract":[{"type":"text","text":"Configuration for face library components."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init("},{"type":"text","text":" "},{"type":"text","text":"faceSizeRatioInterval: .init(min: 0.1, max: 0.4),"},{"type":"text","text":" "},{"type":"text","text":"query: .init()"},{"type":"text","text":" "},{"type":"text","text":")"}],"type":"topic","role":"symbol","kind":"symbol","title":"faceLibraryComponent","fragments":[{"kind":"identifier","text":"faceLibraryComponent"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","type":"topic","title":"DOTFMultiRangeLivenessConfiguration","abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFMultiRangeLivenessConfiguration"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"type":"topic","title":"FaceLibraryComponentConfiguration","abstract":[{"type":"text","text":"Configuration for face library components."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFFaceLibraryComponentConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","op":"replace"}]}]}