{"sections":[],"metadata":{"title":"detection","roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult(py)detection","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"detection"}]},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/detection"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"type":"topic","title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of the image processing during the face auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"abstract":[{"text":"The result returned from the processing of one image during the face auto capture process.","type":"text"}],"fragments":[{"text":"DOTFLFaceAutoCaptureControllerProcessingResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult","title":"DOTFLFaceAutoCaptureControllerProcessingResult","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult/detection":{"title":"detection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/detection","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/detection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace"}]}]}