{"metadata":{"title":"result","navigatorTitle":[{"text":"result","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"identifier","text":"result"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerProcessingResult(py)result","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"DOTFLFaceAutoCaptureResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"result"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/result","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/result"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult":{"abstract":[{"text":"The result returned from the processing of one image during the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult","fragments":[{"text":"DOTFLFaceAutoCaptureControllerProcessingResult","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult","title":"DOTFLFaceAutoCaptureControllerProcessingResult","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","role":"symbol","title":"FaceAutoCaptureResult","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerProcessingResult/result":{"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerprocessingresult\/result","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerProcessingResult\/result","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"result"}],"role":"symbol","title":"result"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}