{"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Running state."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)"],"generated":true,"anchor":"Initializers"},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/detection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/hash","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/phase","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/preview","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/result"]},{"anchor":"Instance-Methods","title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/isEqual(_:)"]}],"metadata":{"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"Running"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Running"}],"roleHeading":"Class","externalID":"s:11DotDocument0B18AutoCaptureUiStateC7RunningC","modules":[{"name":"DotDocument"}],"role":"symbol","title":"DocumentAutoCaptureUiState.Running"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDDocumentAutoCaptureUiStateRunning) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"This state is active after the ","type":"text"},{"code":"start()","type":"codeVoice"},{"text":" method is called and before the process finishes.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/running"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running","abstract":[{"text":"Running state.","type":"text"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running","navigatorTitle":[{"text":"Running","kind":"identifier"}],"title":"DocumentAutoCaptureUiState.Running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/description":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/description","abstract":[],"title":"description","type":"topic","role":"symbol"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/isEqual(_:)":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/isequal(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/isEqual(_:)","abstract":[],"title":"isEqual(_:)","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"url":"\/documentation\/dotdocument\/documentautocaptureuistate","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureUiState"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"DocumentAutoCaptureUiState","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/init(preview:phase:detection:result:)":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/init(preview:phase:detection:result:)","abstract":[],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)","title":"init(preview:phase:detection:result:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/result":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/result","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DocumentAutoCaptureResult","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/result","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"code":"null","type":"codeVoice"},{"type":"text","text":"."}],"title":"result","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/phase":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/phase","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase","text":"DocumentAutoCapturePhase","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B16AutoCapturePhaseO7WrappedC","text":"Wrapped","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/phase","abstract":[{"text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"title":"phase","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/detection":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/detection","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DocumentAutoCaptureDetection","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/detection","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"title":"detection","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/hash":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/hash","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/hash","abstract":[],"title":"hash","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Running/preview":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/running\/preview","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Running\/preview","abstract":[{"text":"Preview information.","type":"text"}],"title":"preview","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","op":"replace","value":"DOTDDocumentAutoCaptureUiState"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}]}]}]}