{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds"},{"kind":"text","text":" = QualityAttributeThresholdPresets.standard.build(), "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode"},{"kind":"text","text":" = Defaults.validationMode, "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isMrzReadingEnabled, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(qualityattributethresholds:validationmode:ismrzreadingenabled:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(qualityattributethresholds:validationmode:ismrzreadingenabled:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"title":"init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(im)initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDQualityAttributeThresholds":{"role":"symbol","title":"DOTDQualityAttributeThresholds","fragments":[{"kind":"identifier","text":"DOTDQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdqualityattributethresholds"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"role":"symbol","title":"ValidationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"role":"symbol","title":"init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validationMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/init(qualityattributethresholds:validationmode:ismrzreadingenabled:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotdocument\/camerafacing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithQualityAttributeThresholds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDQualityAttributeThresholds","text":"DOTDQualityAttributeThresholds"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"DOTDValidationMode"},{"kind":"text","text":")"},{"kind":"internalParam","text":"validationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"isMrzReadingEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isMrzReadingEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing","text":"DOTCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/title","value":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration~1init(qualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithQualityAttributeThresholds:validationMode:isMrzReadingEnabled:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}