{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"title":"description","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat(py)description","role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"DotFaceLite"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/description"},"variants":[{"paths":["\/documentation\/dotfacelite\/wrappedfloat\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/wrappedfloat\/description"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat/description":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/description","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacelite\/wrappedfloat\/description","role":"symbol","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat":{"title":"WrappedFloat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WrappedFloat","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"url":"\/documentation\/dotfacelite\/wrappedfloat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}]}]}},{"value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1description\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","op":"replace"}]}]}