{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Temporary property for the legacy way of liveness evaluation on DIS. Only 'content' property should be used for server-side evaluation."}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerBgrRawImages","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerBgrRawImages"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessResult"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Array of images for each corner."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerbgrrawimages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerbgrrawimages"]}],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult(py)cornerBgrRawImages","symbolKind":"property","roleHeading":"Instance Property","platforms":[],"title":"cornerBgrRawImages","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerBgrRawImages"},{"kind":"text","text":": ["},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"cornerBgrRawImages"}]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessResult":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessResult","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"EyeGazeLivenessResult","navigatorTitle":[{"text":"EyeGazeLivenessResult","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessResult","url":"\/documentation\/dotfacecore\/eyegazelivenessresult","type":"topic","abstract":[{"type":"text","text":"The final result of the eye gaze liveness process."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"title":"BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessResult/cornerBgrRawImages":{"navigatorTitle":[{"kind":"identifier","text":"cornerBgrRawImages"}],"deprecated":true,"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerBgrRawImages","title":"cornerBgrRawImages","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerbgrrawimages","abstract":[{"type":"text","text":"Array of images for each corner."}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerBgrRawImages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"cornerBgrRawImages","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"cornerBgrRawImages","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTBgrRawImage *>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cornerBgrRawImages"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFEyeGazeLivenessResult","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/fragments","op":"replace"},{"value":"cornerBgrRawImages","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerBgrRawImages\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerBgrRawImages\/fragments","value":[{"text":"cornerBgrRawImages","kind":"identifier"}],"op":"replace"}]}]}