{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerimages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerimages"]}],"abstract":[{"type":"text","text":"Array of images for each corner."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerImages"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult(py)cornerImages","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"platforms":[{"message":"Temporary property for the legacy way of liveness evaluation on DIS. Only 'content' property should be used for server-side evaluation.","beta":false,"unavailable":false,"deprecated":true}],"navigatorTitle":[{"kind":"identifier","text":"cornerImages"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"cornerImages","kind":"identifier"},{"kind":"text","text":": ["},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"]","kind":"text"}],"title":"cornerImages"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerImages","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","text":"Image"},{"kind":"text","text":"]"}],"languages":["swift"]}],"kind":"declarations"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Temporary property for the legacy way of liveness evaluation on DIS. Only 'content' property should be used for server-side evaluation."}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image":{"url":"\/documentation\/dotfacecore\/image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","title":"Image","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/cornerImages":{"deprecated":true,"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/cornerImages","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/cornerimages","role":"symbol","navigatorTitle":[{"text":"cornerImages","kind":"identifier"}],"abstract":[{"text":"Array of images for each corner.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornerImages","kind":"identifier"},{"text":": [","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"title":"cornerImages"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","url":"\/documentation\/dotfacecore\/eyegazelivenessresult","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessResult"}],"type":"topic","title":"EyeGazeLivenessResult","abstract":[{"text":"The final result of the eye gaze liveness process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessResult"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"beta":false,"unavailable":false,"deprecated":true}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"cornerImages","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"cornerImages"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DOTImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cornerImages"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":[{"inlineContent":[{"text":"Temporary property for the legacy way of liveness evaluation on DIS. Only 'content' property should be used for server-side evaluation.","type":"text"}],"type":"paragraph"}],"op":"replace","path":"\/deprecationSummary"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"value":"cornerImages","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerImages\/title"},{"value":[{"kind":"identifier","text":"cornerImages"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1cornerImages\/fragments"},{"value":"DOTFEyeGazeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}