{"abstract":[{"type":"text","text":"Detected face in the image."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult(py)face","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"}],"title":"face","navigatorTitle":[{"kind":"identifier","text":"face"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/face","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/face"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult":{"url":"\/documentation\/dotfacecore\/eyegazelivenessresult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessResult"}],"role":"symbol","abstract":[{"type":"text","text":"The final result of the eye gaze liveness process."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessResult"}],"title":"EyeGazeLivenessResult"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/face":{"title":"face","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/face","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"}],"role":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"face"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/face"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.15.0"}],"title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Face","kind":"identifier"}],"title":"FaceDetector.Face"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"title":"Face","url":"\/documentation\/dotfacecore\/face","fragments":[{"kind":"identifier","text":"Face"}],"role":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}],"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"face","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"face","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","text":"Face","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title","value":"DOTFEyeGazeLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1face\/title","value":"face"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1face\/fragments","value":[{"kind":"identifier","text":"face"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}