{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"score","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cornerImages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"])","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/init(image:face:content:score:cornerimages:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessresult\/init(image:face:content:score:cornerimages:)"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithImage:face:content:score:cornerImages:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessResult(im)initWithImage:face:content:score:cornerImages:","role":"symbol","roleHeading":"Initializer","symbolKind":"init","title":"init(image:face:content:score:cornerImages:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"score","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"cornerImages","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/init(image:face:content:score:cornerImages:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Face":{"url":"\/documentation\/dotfacecore\/face","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","type":"topic","title":"Face","kind":"symbol","fragments":[{"kind":"identifier","text":"Face"}],"abstract":[{"type":"text","text":"Detected face in the image."}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessResult"}],"title":"EyeGazeLivenessResult","url":"\/documentation\/dotfacecore\/eyegazelivenessresult","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult","abstract":[{"type":"text","text":"The final result of the eye gaze liveness process."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessResult"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"url":"\/documentation\/dotfacecore\/facedetector","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"type":"topic","title":"FaceDetector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}]},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"url":"\/documentation\/dotfacecore\/image","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"type":"topic","title":"Image","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"url":"\/documentation\/dotfacecore\/facedetector\/face","title":"FaceDetector.Face","navigatorTitle":[{"kind":"identifier","text":"Face"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessResult/init(image:face:content:score:cornerImages:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessresult\/init(image:face:content:score:cornerimages:)","abstract":[],"navigatorTitle":[{"text":"initWithImage:face:content:score:cornerImages:","kind":"identifier"}],"title":"init(image:face:content:score:cornerImages:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessResult\/init(image:face:content:score:cornerImages:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"score"},{"kind":"text","text":": "},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"cornerImages","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"])","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithImage:face:content:score:cornerImages:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:content:score:cornerImages:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"score:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"score","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cornerImages:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<DOTImage *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cornerImages","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFEyeGazeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult\/navigatorTitle"},{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle"},{"value":"initWithImage:face:content:score:cornerImages:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1init(image:face:content:score:cornerImages:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:content:score:cornerImages:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessResult~1init(image:face:content:score:cornerImages:)\/fragments"}]}]}