{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rightEyeInnerCorner","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier","text":"FaceKeypoint"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","abstract":[{"type":"text","text":"Right eye inner corner."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyeinnercorner"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyeinnercorner"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeInnerCorner"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)rightEyeInnerCorner","title":"rightEyeInnerCorner","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeInnerCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"rightEyeInnerCorner"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeInnerCorner":{"navigatorTitle":[{"text":"rightEyeInnerCorner","kind":"identifier"}],"type":"topic","kind":"symbol","title":"rightEyeInnerCorner","abstract":[{"type":"text","text":"Right eye inner corner."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rightEyeInnerCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeInnerCorner","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyeinnercorner"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"role":"symbol","title":"FaceKeypoints","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","abstract":[{"type":"text","text":"Face Keypoints evaluation result. Holds evaluated facial keypoints."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceKeypoints","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","role":"symbol","abstract":[{"type":"text","text":"Face Keypoint"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoint","title":"FaceKeypoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceKeypoint"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"rightEyeInnerCorner"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"rightEyeInnerCorner","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint"},{"kind":"text","text":" * "},{"kind":"identifier","text":"rightEyeInnerCorner"}],"languages":["occ"]}]}},{"op":"replace","value":"rightEyeInnerCorner","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeInnerCorner\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeInnerCorner\/fragments","value":[{"text":"rightEyeInnerCorner","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","op":"replace","value":"DOTFFaceKeypoints"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"value":"DOTFFaceKeypoint","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}