{"sections":[],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory\/create(bgraRawImage:ciContext:)"},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Type Method","title":"create(bgraRawImage:ciContext:)","externalID":"c:@M@DotFaceCore@objc(cs)DOTCIImageFactory(cm)createWithBgraRawImage:ciContext:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"CIContext.","type":"text"}],"type":"paragraph"}],"name":"ciContext"}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" instance."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:cicontext:)"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/bgrarawimage","title":"BgraRawImage"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CIImageFactory/create(bgraRawImage:ciContext:)":{"url":"\/documentation\/dotfacecore\/ciimagefactory\/create(bgrarawimage:cicontext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory\/create(bgraRawImage:ciContext:)","title":"create(bgraRawImage:ciContext:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CIImageFactory":{"title":"CIImageFactory","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CIImageFactory","url":"\/documentation\/dotfacecore\/ciimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","value":"createWithBgraRawImage:ciContext:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:ciContext:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"value":"createWithBgraRawImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory~1create(bgraRawImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory~1create(bgraRawImage:ciContext:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CIImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}