{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/idle\/init(preview:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle\/init(preview:)"},"metadata":{"title":"init(preview:)","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"text":"DocumentAutoCapturePreview","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","externalID":"s:11DotDocument0B18AutoCaptureUiStateC4IdleC7previewAeA0bcD7PreviewC_tcfc"},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"url":"\/documentation\/dotdocument\/documentautocaptureuistate","type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"title":"DocumentAutoCaptureUiState","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"title":"DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Idle/init(preview:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle\/init(preview:)","title":"init(preview:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview"},{"text":")","kind":"text"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/idle\/init(preview:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Idle":{"title":"DocumentAutoCaptureUiState.Idle","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle","type":"topic","navigatorTitle":[{"text":"Idle","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureuistate\/idle","abstract":[{"type":"text","text":"Idle state."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","value":"DOTDDocumentAutoCaptureUiState","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","value":"DOTDDocumentAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}