{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/facing","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/previewScaleType"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isEqual(_:)"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]}],"kind":"declarations"}],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/previewScaleType":{"abstract":[{"text":"Preview scale type. Default is ","type":"text"},{"type":"codeVoice","code":".fit"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/previewScaleType","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration\/previewscaletype","kind":"symbol","title":"previewScaleType","navigatorTitle":[{"text":"previewScaleType","kind":"identifier"}]},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"title":"CameraConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isPreviewVisible":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isPreviewVisible"}],"title":"isPreviewVisible","url":"\/documentation\/dotfacecore\/cameraconfiguration\/ispreviewvisible","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isPreviewVisible","abstract":[{"type":"text","text":"Use this flag to show\/hide camera preview. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/facing":{"navigatorTitle":[{"text":"facing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration\/facing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"kind":"symbol","abstract":[{"text":"Front or back camera facing.","type":"text"}],"role":"symbol","type":"topic","title":"facing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/facing"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isEqual(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration\/isequal(_:)","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","title":"hash","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/hash","role":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration\/hash","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/description"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isTorchEnabled":{"url":"\/documentation\/dotfacecore\/cameraconfiguration\/istorchenabled","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Use this flag to turn the torch on\/off during the capture process."},{"type":"text","text":" "},{"type":"text","text":"Torch will be turned on only if "},{"type":"codeVoice","code":"facing"},{"type":"text","text":" property is set to "},{"type":"codeVoice","code":".back"},{"type":"text","text":". Default is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isTorchEnabled","title":"isTorchEnabled"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isVideoCaptureEnabled":{"url":"\/documentation\/dotfacecore\/cameraconfiguration\/isvideocaptureenabled","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isVideoCaptureEnabled","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isVideoCaptureEnabled"}],"abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"title":"isVideoCaptureEnabled","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)":{"role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"type":"topic","title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","kind":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"facing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/facing","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/previewScaleType"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1previewScaleType\/title","value":"previewScaleType","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1previewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"previewScaleType"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isPreviewVisible\/title","op":"replace","value":"isPreviewVisible"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isPreviewVisible\/fragments","op":"replace","value":[{"kind":"identifier","text":"isPreviewVisible"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1facing\/title","op":"replace","value":"facing"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1facing\/fragments","op":"replace","value":[{"kind":"identifier","text":"facing"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isTorchEnabled\/title","op":"replace","value":"isTorchEnabled"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isTorchEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isTorchEnabled"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isVideoCaptureEnabled\/title","op":"replace","value":"isVideoCaptureEnabled"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","op":"replace","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/title","op":"replace","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}]}]}]}