{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory"},"kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"sections":[],"seeAlsoSections":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"anchor":"Converting-images"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"platforms":["iOS"]}]}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"anchor":"Type-Methods","generated":true}],"variants":[{"paths":["\/documentation\/dotfacecore\/imagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/imagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory","roleHeading":"Class","title":"ImageFactory","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"url":"\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"type":"topic","title":"createBgraRawImage(ciImage:ciContext:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}]},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"kind":"symbol","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/ciimagefactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/CGImageFactory":{"kind":"symbol","title":"CGImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/cgimagefactory"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"title":"Image","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/image"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory":{"abstract":[{"type":"text","text":"Create "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"kind":"symbol","title":"ImageFactory","url":"\/documentation\/dotfacecore\/imagefactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgrRawImage(cgImage:)":{"title":"createBgrRawImage(cgImage:)","role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(cgImage:)","url":"\/documentation\/dotfacecore\/imagefactory\/createbgrrawimage(cgimage:)","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"url":"\/documentation\/dotfacecore\/imagefactory\/createbgrrawimage(ciimage:cicontext:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","type":"topic","title":"createBgrRawImage(ciImage:ciContext:)","role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"navigatorTitle":[{"text":"createBgrRawImageWithCiImage:ciContext:","kind":"identifier"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgraRawImage(cgImage:)":{"title":"createBgraRawImage(cgImage:)","role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(cgImage:)","url":"\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(cgimage:)","type":"topic"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFactory/createBgraRawImage(bgrRawImage:)":{"kind":"symbol","navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"title":"createBgraRawImage(bgrRawImage:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object with "},{"code":".rawBgr","type":"codeVoice"},{"type":"text","text":" format as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object with "},{"code":".rawBgra","type":"codeVoice"},{"type":"text","text":" format."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/imagefactory\/createbgrarawimage(bgrrawimage:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"anchor":"Type-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CGImageFactory","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"],"title":"Converting images","generated":true,"anchor":"Converting-images"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CGImageFactory\/navigatorTitle","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(cgImage:)\/title","value":"createBgrRawImageWithCgImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title","value":"createBgrRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(cgImage:)\/title","value":"createBgraRawImageWithCgImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}]}]}]}