{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"generated":true,"anchor":"Validators","title":"Validators"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init(minConfidenceThreshold:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/minConfidenceThreshold"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/validate(faceAutoCaptureFrameParameters:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/defaultMinConfidenceThreshold"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceNotDetectedValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceNotDetectedValidator","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceNotDetectedValidator","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"roleHeading":"Class","navigatorTitle":[{"text":"FaceNotDetectedValidator","kind":"identifier"}],"role":"symbol","symbolKind":"class","title":"FaceNotDetectedValidator"},"abstract":[{"text":"Validates confidence of the detected face.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facenotdetectedvalidator"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/validate(faceAutoCaptureFrameParameters:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Validate confidence of the detected face."}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/validate(faceautocaptureframeparameters:)","navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"validate(faceAutoCaptureFrameParameters:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/validate(faceAutoCaptureFrameParameters:)"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/dependencyIdentifiers","type":"topic","title":"dependencyIdentifiers","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/dependencyidentifiers"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","title":"SizeTooSmallValidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","navigatorTitle":[{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","kind":"symbol","abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"title":"FaceOutOfBoundsValidator","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/init(minConfidenceThreshold:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(minConfidenceThreshold:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/init(minconfidencethreshold:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init(minConfidenceThreshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/minConfidenceThreshold":{"role":"symbol","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/minconfidencethreshold","abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"title":"minConfidenceThreshold","kind":"symbol","navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/minConfidenceThreshold"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"kind":"symbol","title":"FaceAutoCaptureDetectionValidator","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetectionValidator"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected face."}],"navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/init()":{"type":"topic","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init()","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 8.17.1","type":"text"}],"title":"DotFaceLite","role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"title":"BrightnessTooHighValidator","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","kind":"symbol"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/defaultMinConfidenceThreshold":{"abstract":[{"type":"text","text":"Default threshold value."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/defaultminconfidencethreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/defaultMinConfidenceThreshold","kind":"symbol","title":"defaultMinConfidenceThreshold"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator/identifier":{"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator\/identifier","role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/identifier","kind":"symbol","title":"identifier"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator","role":"symbol","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}]},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"role":"symbol","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","title":"BrightnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"abstract":[{"type":"text","text":"Validates confidence of the detected face."}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","kind":"symbol","title":"FaceNotDetectedValidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLFaceNotDetectedValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/minConfidenceThreshold"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/init(minConfidenceThreshold:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator\/defaultMinConfidenceThreshold"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"anchor":"Validators","title":"Validators","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1validate(faceAutoCaptureFrameParameters:)\/title","value":"validateWithFaceAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","value":"DOTFLSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init(minConfidenceThreshold:)\/title","value":"initWithMinConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init(minConfidenceThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1minConfidenceThreshold\/title","value":"minConfidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1minConfidenceThreshold\/fragments","value":[{"kind":"identifier","text":"minConfidenceThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","value":"DOTFLFaceAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetectionValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","value":"DOTFLBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1defaultMinConfidenceThreshold\/title","value":"defaultMinConfidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments","value":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/navigatorTitle","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","value":"DOTFLFaceNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/navigatorTitle","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}