{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/equatable-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"]]},"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/!=(_:_:)"],"title":"Operators"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"sections":[],"kind":"article","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/!=(_:_:)":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/!=(_:_:)","title":"!=(_:_:)","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/!=(_:_:)","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle"}]}]}