{"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/errormessage"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"errorMessage","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO12errorMessageSSvp","symbolKind":"property"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.errorMessage"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/errorMessage","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/errorMessage":{"abstract":[],"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/errormessage","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"errorMessage","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/errorMessage"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"}]}]}