{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"metadata":{"title":"recoverySuggestion","platforms":[{"introducedAt":"8.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"8.0","name":"iPadOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"10.10","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"9.0","name":"tvOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"2.0","name":"watchOS","unavailable":false,"beta":false,"deprecated":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","symbolKind":"property","modules":[{"name":"DotFingersCore","relatedModules":["Foundation"]}],"extendedModule":"Foundation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration/Error/recoverySuggestion":{"title":"recoverySuggestion","kind":"symbol","url":"\/documentation\/dotfingerscore\/autocaptureconfiguration\/error\/recoverysuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration\/Error\/recoverySuggestion"},"doc://DotFingersCore/documentation/DotFingersCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/AutoCaptureConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}