{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NameOfHolder"]]},"variants":[{"paths":["\/documentation\/dotnfc\/nameofholder\/secondaryidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nameofholder\/secondaryidentifier"]}],"metadata":{"title":"secondaryIdentifier","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder(py)secondaryIdentifier","navigatorTitle":[{"text":"secondaryIdentifier","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"secondaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","roleHeading":"Instance Property","platforms":[{"name":"iOS","introducedAt":"13.0","deprecated":false,"beta":false,"unavailable":false}],"modules":[{"name":"DotNfc"}]},"abstract":[{"text":"Secondary identifier, usually represents given names.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NameOfHolder\/secondaryIdentifier","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NameOfHolder":{"navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Name of travel document holder."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NameOfHolder"}],"url":"\/documentation\/dotnfc\/nameofholder","title":"NameOfHolder","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NameOfHolder"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NameOfHolder/secondaryIdentifier":{"kind":"symbol","navigatorTitle":[{"text":"secondaryIdentifier","kind":"identifier"}],"abstract":[{"text":"Secondary identifier, usually represents given names.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/nameofholder\/secondaryidentifier","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NameOfHolder\/secondaryIdentifier","title":"secondaryIdentifier","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"secondaryIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"text":"version: 8.3.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"secondaryIdentifier"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"secondaryIdentifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"secondaryIdentifier","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NameOfHolder\/title","value":"DOTNNameOfHolder"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NameOfHolder\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNameOfHolder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NameOfHolder~1secondaryIdentifier\/title","value":"secondaryIdentifier"},{"value":[{"text":"secondaryIdentifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NameOfHolder~1secondaryIdentifier\/fragments","op":"replace"}]}]}