{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"type":"text","text":"."}],"metadata":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::s:6DotNfc24ChipAuthenticationStatusC0D8ProtocolO","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"relatedModules":["Swift"],"name":"DotNfc"}],"role":"symbol","title":"hash(into:)","roleHeading":"Instance Method"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/hash(into:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/hash(into:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/hash(into:)":{"title":"hash(into:)","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/hash(into:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/hash(into:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChipAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","kind":"symbol","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"title":"ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"abstract":[{"text":"Protocol for authentication of the chip.","type":"text"}],"navigatorTitle":[{"text":"AuthenticationProtocol","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","role":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNChipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","op":"replace"},{"value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","op":"replace"},{"value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","op":"replace"}]}]}