{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC20backgroundUniformityAA0ac10Backgroundh6ModuleE0CSgvp","title":"backgroundUniformity","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class/backgroundUniformity":{"title":"backgroundUniformity","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class","title":"DotFaceLibraryConfiguration.Modules"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Face library configuration."}],"role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceBackgroundUniformityModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceBackgroundUniformityModuleConfiguration","title":"DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacebackgrounduniformitymoduleconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}