{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateFaceQuality"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/detectedface\/evaluatefacequality()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/detectedface\/evaluatefacequality()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace\/evaluateFaceQuality()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Evaluation of all available face quality attributes."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateFaceQuality"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"}],"title":"evaluateFaceQuality()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace(im)evaluateFaceQualityAndReturnError:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"evaluateFaceQualityAndReturnError:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace"],["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace":{"role":"symbol","title":"DetectedFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectedFace"}],"abstract":[{"type":"text","text":"Result of face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectedFace"}],"url":"\/documentation\/dotfacecore\/detectedface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace/evaluateFaceQuality()":{"role":"symbol","title":"evaluateFaceQuality()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateFaceQuality"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality"}],"abstract":[{"type":"text","text":"Evaluation of all available face quality attributes."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace\/evaluateFaceQuality()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"evaluateFaceQualityAndReturnError:"}],"url":"\/documentation\/dotfacecore\/detectedface\/evaluatefacequality()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"role":"symbol","title":"FaceQuality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacecore\/facequality"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"evaluateFaceQualityAndReturnError:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"evaluateFaceQualityAndReturnError:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"DOTFFaceQuality"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"evaluateFaceQualityAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/title","value":"DOTFDetectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/fragments","value":[{"kind":"identifier","text":"DOTFDetectedFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace~1evaluateFaceQuality()\/title","value":"evaluateFaceQualityAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace~1evaluateFaceQuality()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"evaluateFaceQualityAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQuality"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}