{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/barcode","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentmoduleid\/barcode"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentmoduleid\/barcode"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId"]]},"metadata":{"navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode","symbolKind":"case","roleHeading":"Case","title":"DotDocumentModuleId.barcode","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid","abstract":[{"type":"codeVoice","code":"DotDocument"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId","title":"DotDocumentModuleId","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/barcode":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/barcode","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/barcode","title":"DotDocumentModuleId.barcode","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotDocumentModuleIdBarcode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/fragments","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/navigatorTitle","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId~1barcode\/title","value":"DotDocumentModuleIdBarcode"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId~1barcode\/fragments","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}]}]}]}