{"abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"FingersAutoCaptureViewController"},{"text":".","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"title":"init(configuration:style:)","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureViewController(im)initWithConfiguration:style:","symbolKind":"init"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"},{"text":" = .init(), ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class"},{"text":" = .init())","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"type":"text","text":"Configure the capture process."}],"type":"paragraph"}]},{"name":"style","content":[{"inlineContent":[{"type":"text","text":"Customize user interface."}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/init(configuration:style:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureStyle":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureStyle","type":"topic","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureStyle"}],"title":"DOTFGFingersAutoCaptureStyle","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturestyle","kind":"symbol","abstract":[{"type":"text","text":"Customization options for the fingers auto capture user interface."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/init(configuration:style:)":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"code":"FingersAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"title":"init(configuration:style:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/init(configuration:style:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","type":"topic","title":"FingersAutoCaptureViewController","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewController"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Fingers Auto Capture component."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration","title":"DOTFGFingersAutoCaptureConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureConfiguration"}],"kind":"symbol","abstract":[{"text":"Configuration options for the UI Fingers Auto Capture component.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Style-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Style","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the fingers auto capture user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:style:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCaptureStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureStyle","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureStyle"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the capture process."}]}]},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title","value":"DOTFGFingersAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}