{"metadata":{"title":"init(image:face:content:)","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult(im)initWithImage:face:content:","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithImage:face:content:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/init(image:face:content:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureresult\/init(image:face:content:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureresult\/init(image:face:content:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"title":"FaceAutoCaptureResult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureresult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","fragments":[{"kind":"identifier","text":"Face"}],"type":"topic","title":"Face","abstract":[{"type":"text","text":"Detected face in the image."}],"role":"symbol","url":"\/documentation\/dotfacecore\/face","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/face","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","navigatorTitle":[{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","type":"topic","url":"\/documentation\/dotfacecore\/image"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","url":"\/documentation\/dotfacecore\/facedetector"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/init(image:face:content:)":{"role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureresult\/init(image:face:content:)","type":"topic","title":"init(image:face:content:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithImage:face:content:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/init(image:face:content:)","kind":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithImage:face:content:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:content:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Face","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title","op":"replace","value":"DOTFFaceAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments","op":"replace","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace"},{"value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1init(image:face:content:)\/title","value":"initWithImage:face:content:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1init(image:face:content:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:face:content:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}