{"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"s:11DotPalmCore15HandOrientationO11descriptionSSvp"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/description","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handorientation\/description"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation\/description","kind":"symbol","abstract":[],"title":"description","url":"\/documentation\/dotpalmcore\/handorientation\/description","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandOrientation":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandOrientation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandOrientation"}],"abstract":[{"type":"text","text":"Represents the orientation of a hand when detecting palm."}],"type":"topic","title":"HandOrientation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HandOrientation"}],"url":"\/documentation\/dotpalmcore\/handorientation"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/title","op":"replace","value":"DOTPHandOrientation"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/fragments","op":"replace","value":[{"text":"DOTPHandOrientation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandOrientation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPHandOrientation"}]}]}]}