{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/hash","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/mrzstringposition\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzstringposition\/hash"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","title":"hash","role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(py)hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"DotNfc"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"kind":"symbol","sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"role":"symbol","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","url":"\/documentation\/dotnfc\/mrzstringposition","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"kind":"symbol","title":"MrzStringPosition","type":"topic"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition/hash":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/hash","url":"\/documentation\/dotnfc\/mrzstringposition\/hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","title":"hash","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments"},{"value":"hash","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1hash\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}