{"variants":[{"paths":["\/documentation\/dotnfc\/mrzstringposition\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrzstringposition\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition"]]},"sections":[],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition(im)isEqual:","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","role":"symbol","title":"isEqual(_:)","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/isEqual(_:)"},"references":{"doc://DotNfc/documentation/DotNfc/MrzStringPosition/isEqual(_:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/mrzstringposition\/isequal(_:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition\/isEqual(_:)","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"url":"\/documentation\/dotnfc\/mrzstringposition","role":"symbol","kind":"symbol","title":"MrzStringPosition","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","op":"replace","value":"DOTMrzStringPosition"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]}]}]}