{"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"startIndex","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"startIndex","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTMrzStringPosition(py)startIndex","symbolKind":"property","modules":[{"name":"DotNfc"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzstringposition\/startindex"]},{"paths":["\/documentation\/dotnfc\/mrzstringposition\/startindex"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"An index of the first character in the MRZ line."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition\/startIndex"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzStringPosition/startIndex":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition\/startIndex","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startIndex"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"An index of the first character in the MRZ line."}],"type":"topic","title":"startIndex","navigatorTitle":[{"kind":"identifier","text":"startIndex"}],"url":"\/documentation\/dotnfc\/mrzstringposition\/startindex"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzStringPosition":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzStringPosition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"type":"topic","title":"MrzStringPosition","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotnfc\/mrzstringposition"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.2.1"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"startIndex","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"startIndex","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"startIndex","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"startIndex","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition~1startIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition~1startIndex\/fragments","value":[{"kind":"identifier","text":"startIndex"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition\/title","value":"DOTMrzStringPosition","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}