{"abstract":[{"text":"Libraries configuration.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","text":"Libraries"}],"title":"libraries","externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Libraries","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdk\/configuration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration\/libraries","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Configuration/libraries":{"url":"\/documentation\/dotfingerscore\/dotsdk\/configuration\/libraries","abstract":[{"type":"text","text":"Libraries configuration."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier"}],"title":"libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration\/libraries"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"title":"Libraries","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Configuration":{"role":"symbol","title":"DotSdk.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/configuration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle"},{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle"}]}]}