{"kind":"article","sections":[],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/Equatable-Implementations"},"variants":[{"paths":["\/documentation\/dotpalmcore\/imageformat\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotPalmCore"}],"title":"Equatable Implementations","role":"collectionGroup"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","role":"symbol","abstract":[{"type":"text","text":"Supported image formats."}],"title":"ImageFormat","url":"\/documentation\/dotpalmcore\/imageformat","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/!=(_:_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/!=(_:_:)","role":"symbol","abstract":[],"title":"!=(_:_:)","url":"\/documentation\/dotpalmcore\/imageformat\/!=(_:_:)","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTImageFormat","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}