{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingersmoduleid\/detection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingersmoduleid\/detection"]}],"metadata":{"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdDetection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"title":"DotFingersModuleId.detection","role":"symbol","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/detection","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId":{"url":"\/documentation\/dotfacecore\/dotfingersmoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"title":"DotFingersModuleId","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersModuleId/detection":{"url":"\/documentation\/dotfacecore\/dotfingersmoduleid\/detection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"title":"DotFingersModuleId.detection","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersModuleId\/detection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DotFingersModuleIdDetection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/title","op":"replace","value":"DotFingersModuleId"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/fragments","op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1detection\/title","op":"replace","value":"DotFingersModuleIdDetection"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersModuleId~1detection\/fragments","op":"replace","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]}]}]}