{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateExtractionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmquality\/templateextractionquality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmquality\/templateextractionquality"]}],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality(py)templateExtractionQuality","title":"templateExtractionQuality","symbolKind":"property","navigatorTitle":[{"text":"templateExtractionQuality","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateExtractionQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/templateExtractionQuality"},"abstract":[{"type":"text","text":"Quality for the template extraction. Value in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"type":"text","text":"."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/templateExtractionQuality":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templateExtractionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"templateExtractionQuality","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/templateExtractionQuality","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmquality\/templateextractionquality","abstract":[{"type":"text","text":"Quality for the template extraction. Value in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"type":"text","text":"."}],"title":"templateExtractionQuality"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"navigatorTitle":[{"text":"PalmQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm quality."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"title":"PalmQuality","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmquality"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"templateExtractionQuality","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"templateExtractionQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"templateExtractionQuality"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"templateExtractionQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1templateExtractionQuality\/title"},{"value":[{"text":"templateExtractionQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1templateExtractionQuality\/fragments"},{"value":"DOTPPalmQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title"},{"value":[{"text":"DOTPPalmQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments"},{"value":[{"text":"DOTPPalmQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}