{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"yaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/init(roll:yaw:pitch:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"roll","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"yaw","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRoll:yaw:pitch:"}],"title":"init(roll:yaw:pitch:)","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose(im)initWithRoll:yaw:pitch:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headpose\/init(roll:yaw:pitch:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headpose\/init(roll:yaw:pitch:)"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPose"}],"url":"\/documentation\/dotfacecore\/headpose","title":"HeadPose","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"role":"symbol","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"title":"HeadPoseAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposeattribute","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose/init(roll:yaw:pitch:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"roll"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"yaw"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/init(roll:yaw:pitch:)","navigatorTitle":[{"text":"initWithRoll:yaw:pitch:","kind":"identifier"}],"role":"symbol","title":"init(roll:yaw:pitch:)","abstract":[],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/headpose\/init(roll:yaw:pitch:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithRoll:yaw:pitch:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithRoll:yaw:pitch:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithRoll:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"roll","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"yaw:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"yaw","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"pitch:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"DOTFHeadPoseAttribute","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFHeadPose"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1init(roll:yaw:pitch:)\/title","value":"initWithRoll:yaw:pitch:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1init(roll:yaw:pitch:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRoll:yaw:pitch:"}]}]}]}