{"metadata":{"title":"init(bytesPointer:size:)","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(im)initWithBytesPointer:size:","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"kind":"text","text":">, "},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"text":")","kind":"text"}],"roleHeading":"Initializer"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Do not use this, use "},{"code":"BgraRawImageFactory","type":"codeVoice"},{"text":" to create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimage\/init(bytespointer:size:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimage\/init(bytespointer:size:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/init(bytesPointer:size:)","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/init(bytesPointer:size:)":{"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"text":" to create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage\/init(bytespointer:size:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/init(bytesPointer:size:)","title":"init(bytesPointer:size:)"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","url":"\/documentation\/dotpalmcore\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"role":"symbol","title":"ImageSize","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","title":"PalmDetector","role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","title":"BgraRawImage","role":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithBytesPointer:size:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBytesPointer:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@uint8_t","text":"uint8_t","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"text":"size:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1init(bytesPointer:size:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithBytesPointer:size:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title","value":"DOTImageSize"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments"},{"op":"replace","value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"}]}]}