{"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/delegate"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"title":"delegate","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(py)delegate","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate","text":"MagnifEyeLivenessViewControllerDelegate"},{"kind":"text","text":"?"}]},"sections":[],"abstract":[{"text":"Set this delegate to handle the MagnifEye liveness events.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/delegate","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"weak","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate","text":"MagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"},{"kind":"text","text":"?"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"title":"MagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.15.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the MagnifEye liveness events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","role":"symbol","title":"MagnifEyeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/delegate":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/delegate","abstract":[{"text":"Set this delegate to handle the MagnifEye liveness events.","type":"text"}],"type":"topic","title":"delegate","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"delegate"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate","text":"MagnifEyeLivenessViewControllerDelegate"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/delegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Qo@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate","kind":"typeIdentifier","text":"id<DOTFLMagnifEyeLivenessViewControllerDelegate>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"delegate"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFLMagnifEyeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFLMagnifEyeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1delegate\/title","op":"replace","value":"delegate"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"}]}]}