{"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfacematchingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfacematchingenabled"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"isFaceMatchingEnabled","roleHeading":"Instance Property","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceMatchingEnabled","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"type":"topic","required":true,"title":"isFaceMatchingEnabled","abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfacematchingenabled","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.7.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"title":"DotSdkLicenseProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","type":"topic","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isFaceMatchingEnabled"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isFaceMatchingEnabled","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"isFaceMatchingEnabled","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]}]}