{"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFingersEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","title":"isFingersEnabled","roleHeading":"Instance Property","navigatorTitle":[{"text":"isFingersEnabled","kind":"identifier"}],"required":true,"modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFingersEnabled"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFingersEnabled","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfingersenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfingersenabled"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"abstract":[],"role":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFingersEnabled":{"required":true,"navigatorTitle":[{"text":"isFingersEnabled","kind":"identifier"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFingersEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfingersenabled","type":"topic","title":"isFingersEnabled"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isFingersEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isFingersEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments"},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/navigatorTitle"},{"value":"isFingersEnabled","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/title"},{"value":[{"text":"isFingersEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}