{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"title":"isNfcEnabled","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isNfcEnabled","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isNfcEnabled","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isnfcenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isnfcenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isNfcEnabled":{"abstract":[],"required":true,"title":"isNfcEnabled","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isNfcEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isnfcenabled","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","abstract":[],"type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isNfcEnabled"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","op":"replace","value":"isNfcEnabled"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/navigatorTitle","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}