{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"},{"kind":"text","text":" = .left)"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholder\/visible\/init(type:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore11PlaceholderC7VisibleC4typeAeA0D4TypeO_tcfc","title":"init(type:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible\/init(type:)"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"type":"topic","abstract":[{"type":"text","text":"Placeholder."}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotpalmcore\/placeholder","kind":"symbol","title":"Placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Visible/init(type:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible\/init(type:)","type":"topic","role":"symbol","title":"init(type:)","url":"\/documentation\/dotpalmcore\/placeholder\/visible\/init(type:)","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"PlaceholderType"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Visible":{"url":"\/documentation\/dotpalmcore\/placeholder\/visible","abstract":[{"text":"Visible placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"kind":"symbol","title":"Placeholder.Visible","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"url":"\/documentation\/dotpalmcore\/placeholdertype","abstract":[{"type":"text","text":"Type of placeholder."}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"kind":"symbol","title":"PlaceholderType","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","op":"replace","value":"DOTPPlaceholder"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title","op":"replace","value":"DOTPPlaceholderType"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","op":"replace","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTPPlaceholderType"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}