{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error"]]},"metadata":{"symbolKind":"case","role":"symbol","modules":[{"name":"DotNfc"}],"title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","roleHeading":"Case","externalID":"s:7DotCore0A3SdkC5ErrorO42transactionCountingTokenVerificationFailedyAEsAD_p_tcAEmF","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenVerificationFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":")"}]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","role":"symbol","url":"\/documentation\/dotnfc\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","abstract":[],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdk":{"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotnfc\/dotsdk","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","title":"DotSdk","kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/DotSdk/Error":{"title":"DotSdk.Error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotsdk\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/Error","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}]}]}]}