{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/nationality","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/nationality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/nationality"]}],"sections":[],"metadata":{"symbolKind":"property","title":"nationality","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)nationality","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"}],"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone","type":"topic","title":"Td3MachineReadableZone","kind":"symbol","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzElement":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","role":"symbol","title":"MrzElement","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/mrzelement","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/nationality":{"type":"topic","url":"\/documentation\/dotnfc\/td3machinereadablezone\/nationality","navigatorTitle":[{"text":"nationality","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/nationality","kind":"symbol","title":"nationality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"nationality"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"nationality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"text":" * ","kind":"text"},{"text":"nationality","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/navigatorTitle","op":"replace"},{"value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle","value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1nationality\/title","value":"nationality","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1nationality\/fragments","value":[{"text":"nationality","kind":"identifier"}],"op":"replace"}]}]}