{"metadata":{"title":"camera","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"camera"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration(py)camera","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","fragments":[{"text":"camera","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/camera"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTCameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"},{"text":" * ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"type":"text","text":"\\Endcode"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"]]},"kind":"symbol","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/camera"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration/camera":{"title":"camera","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration\/camera","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration\/camera","fragments":[{"kind":"identifier","text":"camera"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","url":"\/documentation\/dotfacelite\/cameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"title":"DOTFLMultiRangeLivenessConfiguration","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","fragments":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessConfiguration"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}