{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceLiteEnabled","interfaceLanguage":"swift"},"metadata":{"title":"isFaceLiteEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DotSdkLicenseProxy(py)isFaceLiteEnabled","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"modules":[{"name":"DotDocument"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceliteenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceliteenabled"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkLicenseProxyProtocol.isFaceLiteEnabled","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceLiteEnabled":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceLiteEnabled","title":"isFaceLiteEnabled","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceliteenabled"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","kind":"symbol","title":"DotSdkLicenseProxy","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isFaceLiteEnabled"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceLiteEnabled"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]}]}]}