{"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEnabled","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy"]]},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"property","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DotSdkLicenseProxy(py)isFaceEnabled","roleHeading":"Instance Property","role":"symbol","title":"isFaceEnabled"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isFaceEnabled","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceenabled"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","kind":"symbol","title":"DotSdkLicenseProxy","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy/isFaceEnabled":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxy\/isfaceenabled","type":"topic","role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy\/isFaceEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isFaceEnabled","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"isFaceEnabled","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFaceEnabled"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","op":"replace","value":"DotSdkLicenseProxy"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments"},{"value":"isFaceEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy~1isFaceEnabled\/fragments","value":[{"text":"isFaceEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}