{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/rectangledouble\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/rectangledouble\/description"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)description","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble\/description","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble/description":{"role":"symbol","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/rectangledouble\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble\/description","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}