{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/init"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"symbolKind":"method","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)init"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Document library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","url":"\/documentation\/dotnfc","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/init":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/init","kind":"symbol","role":"symbol","type":"topic","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"}]}]}