{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTLoggerLogLevel) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"LoggerLogLevel","symbolKind":"enum","role":"symbol","externalID":"c:@M@DotDocument@E@DOTLoggerLogLevel","modules":[{"name":"DotDocument"}],"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Available log levels.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH","doc:\/\/com.innovatrics.dot.document\/SY"],"kind":"relationships"}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/debug","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/error","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/info","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/none","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/warning"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/init(rawValue:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/description"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/RawRepresentable-Implementations"]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/loggerloglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/loggerloglevel"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/none":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/none","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"kind":"symbol","title":"LoggerLogLevel.none","url":"\/documentation\/dotdocument\/loggerloglevel\/none","role":"symbol","type":"topic","abstract":[{"text":"Disables logging.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/init(rawValue:)","url":"\/documentation\/dotdocument\/loggerloglevel\/init(rawvalue:)","kind":"symbol","abstract":[],"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/RawRepresentable-Implementations":{"url":"\/documentation\/dotdocument\/loggerloglevel\/rawrepresentable-implementations","title":"RawRepresentable Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/RawRepresentable-Implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/warning":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/warning","title":"LoggerLogLevel.warning","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel\/warning","abstract":[{"text":"Logs unexpected events which indicate malfunction.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel":{"type":"topic","abstract":[{"type":"text","text":"Available log levels."}],"kind":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel","title":"LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/dotdocument\/loggerloglevel\/equatable-implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/Equatable-Implementations"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/info":{"type":"topic","abstract":[{"type":"text","text":"Logs informative events."}],"kind":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel\/info","title":"LoggerLogLevel.info","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"info","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/info","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/description":{"kind":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel\/description","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/description"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/debug":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"title":"LoggerLogLevel.debug","abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"url":"\/documentation\/dotdocument\/loggerloglevel\/debug","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/debug","role":"symbol"},"doc://com.innovatrics.dot.document/SY":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/error":{"title":"LoggerLogLevel.error","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/error","url":"\/documentation\/dotdocument\/loggerloglevel\/error","type":"topic","kind":"symbol","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/debug","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/error","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/info","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/none","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/warning"]}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTLoggerLogLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1none\/title","value":"DOTLoggerLogLevelNone"},{"op":"replace","value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1none\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1warning\/title","value":"DOTLoggerLogLevelWarning"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1warning\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1info\/fragments","value":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1debug\/title","value":"DOTLoggerLogLevelDebug","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1debug\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1error\/fragments"}]}]}