{"metadata":{"roleHeading":"Type Method","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalFloat","text":"IntervalFloat"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method","title":"validate(value:interval:)","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTValidationFloat(cm)validateWithValue:interval:error:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalFloat","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalFloat","text":"IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/validationfloat\/validate(value:interval:)"]},{"paths":["\/documentation\/dotnfc\/validationfloat\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationFloat"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationFloat\/validate(value:interval:)"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationFloat/validate(value:interval:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationFloat\/validate(value:interval:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"text":"IntervalFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalFloat"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"validate(value:interval:)","url":"\/documentation\/dotnfc\/validationfloat\/validate(value:interval:)","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ValidationFloat":{"title":"ValidationFloat","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ValidationFloat","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationFloat"}],"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ValidationFloat","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/validationfloat","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/IntervalFloat":{"kind":"symbol","url":"\/documentation\/dotnfc\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalFloat","title":"IntervalFloat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"validateWithValue:interval:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"validateWithValue:interval:error:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"validateWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":" "},{"text":"interval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTIntervalFloat","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/IntervalFloat"},{"kind":"text","text":" *) "},{"text":"interval","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationFloat~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationFloat~1validate(value:interval:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"op":"replace"},{"value":"DOTValidationFloat","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationFloat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ValidationFloat\/fragments","value":[{"kind":"identifier","text":"DOTValidationFloat"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]}]}]}