{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/init(moduleCategory:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/moduleCategory"],"title":"Instance Properties"}],"metadata":{"navigatorTitle":[{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"DotFaceModuleCategoryWrapper","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"sections":[],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"DotFaceModuleCategory"},{"text":" value for Objective-C support.","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper":{"navigatorTitle":[{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"title":"DotFaceModuleCategoryWrapper","abstract":[{"type":"text","text":"Wrapped "},{"code":"DotFaceModuleCategory","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper/init(moduleCategory:)":{"navigatorTitle":[{"text":"initWithModuleCategory:","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/init(moduleCategory:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"moduleCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","text":"DotFaceModuleCategory","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(moduleCategory:)","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/init(modulecategory:)","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/description","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper/moduleCategory":{"navigatorTitle":[{"text":"moduleCategory","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/moduleCategory","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleCategory","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory"}],"title":"moduleCategory","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/modulecategory","type":"topic"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"DotFaceModuleCategoryWrapper","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleCategoryWrapper","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/moduleCategory"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/init(moduleCategory:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleCategoryWrapper","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/fragments"},{"value":"initWithModuleCategory:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1init(moduleCategory:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1init(moduleCategory:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithModuleCategory:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"value":"moduleCategory","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1moduleCategory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1moduleCategory\/fragments","value":[{"kind":"identifier","text":"moduleCategory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}