{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","interfaceLanguage":"swift"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","roleHeading":"Class"},"sections":[],"seeAlsoSections":[{"title":"UI components","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSCoding","doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/s8SendableP","doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFFaceAutoCaptureViewController) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"type":"heading","anchor":"overview","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This component requires the ","type":"text"},{"type":"codeVoice","code":"DotFaceDetection*"},{"type":"text","text":" module to be active."},{"type":"text","text":" "},{"text":"If you want to evaluate background uniformity during the face auto capture process, you will need the ","type":"text"},{"type":"codeVoice","code":"DotFaceBackgroundUniformity"},{"text":" module to be active.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you want to evaluate face mask during the face auto capture process, you will need the "},{"code":"DotFaceDetectionBalanced","type":"codeVoice"},{"text":" module to be active.","type":"text"}]}],"kind":"content"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class"],"title":"Style and configuration"},{"title":"Delegate","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]},{"title":"Face auto capture result","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/init(configuration:style:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/style-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"kind":"symbol","title":"FaceAutoCaptureResult","url":"\/documentation\/dotfacecore\/faceautocaptureresult","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The final result of the face auto capture process."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewDidDisappear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"type":"topic","title":"viewDidDisappear(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewdiddisappear(_:)"},"doc://DotFaceCore/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewWillAppear(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewwillappear(_:)","title":"viewWillAppear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/stopAsync(onStopped:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/stopasync(onstopped:)","abstract":[{"text":"Stop the face auto capture process asynchronously. The ","type":"text"},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAsync","kind":"identifier"},{"kind":"text","text":"("},{"text":"onStopped","kind":"externalParam"},{"kind":"text","text":": () -> "},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"stopAsync(onStopped:)","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(pl)UIStateRestoring":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIStateRestoring","type":"unresolvable","title":"UIKit.UIStateRestoring"},"doc://DotFaceCore/objc(pl)NSExtensionRequestHandling":{"title":"Foundation.NSExtensionRequestHandling","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSExtensionRequestHandling"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/objc(pl)UITraitEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UITraitEnvironment","type":"unresolvable","title":"UIKit.UITraitEnvironment"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"title":"DetectionPosition","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"url":"\/documentation\/dotfacecore\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The position of the detected face in the image."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"type":"topic","abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"role":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"title":"EyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/delegate":{"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate","text":"FaceAutoCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/delegate","title":"delegate","type":"topic","abstract":[{"type":"text","text":"Set this delegate to handle the face auto capture events."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/delegate"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/style-swift.property":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/style-swift.property","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.property","abstract":[{"type":"text","text":"Current style."}],"role":"symbol","navigatorTitle":[{"text":"style","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"}],"title":"style","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection","title":"FaceAutoCaptureDetection","role":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"type":"topic","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewDidLayoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"type":"topic","title":"viewDidLayoutSubviews()","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewdidlayoutsubviews()"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"kind":"symbol","deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"text":"UI component for capturing face images.","type":"text"}],"title":"FaceSimpleCaptureViewController","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","abstract":[{"type":"text","text":"Request capture of the next detection."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestCapture","kind":"identifier"},{"kind":"text","text":"("},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"requestCapture(isFacePresenceRequired:)","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFaceCore/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","kind":"symbol","title":"FaceAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"},"doc://DotFaceCore/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/configuration-swift.property":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/configuration-swift.property","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.property","abstract":[{"type":"text","text":"Current configuration."}],"role":"symbol","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"}],"title":"configuration","type":"topic","kind":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/5UIKit23UITraitChangeObservableP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/init(configuration:style:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"Style","preciseIdentifier":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"FaceAutoCaptureViewController"},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"type":"topic","title":"init(configuration:style:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/init(configuration:style:)"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewDidLoad()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLoad()","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewdidload()","abstract":[],"role":"symbol","navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}],"title":"viewDidLoad()","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(pl)NSCoding":{"title":"Foundation.NSCoding","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSCoding"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewWillDisappear(_:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewwilldisappear(_:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"viewWillDisappear(_:)","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(cs)UIViewController":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)UIViewController","type":"unresolvable","title":"UIViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/start()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/start()","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/start()","abstract":[{"type":"text","text":"Start the face auto capture process."}],"role":"symbol","navigatorTitle":[{"text":"start","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"()"}],"title":"start()","type":"topic","kind":"symbol"},"doc://DotFaceCore/objc(pl)UIFocusEnvironment":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIFocusEnvironment","title":"UIKit.UIFocusEnvironment","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewWillTransition(to:with:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewwilltransition(to:with:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewWillTransitionToSize:withTransitionCoordinator:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"viewWillTransition(to:with:)","type":"topic","kind":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/viewDidAppear(_:)":{"abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidAppear(_:)","kind":"symbol","title":"viewDidAppear(_:)","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/viewdidappear(_:)","role":"symbol"},"doc://DotFaceCore/objc(pl)UIContentContainer":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","role":"symbol","title":"FaceAutoCaptureViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Style-swift.class":{"title":"FaceAutoCaptureViewController.Style","role":"symbol","abstract":[{"text":"Customization options for the face auto capture user interface.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.class","navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://DotFaceCore/s8SendableP":{"identifier":"doc:\/\/DotFaceCore\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"],"title":"Delegate"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"title":"Face auto capture result"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/delegate","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/style-swift.property"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/init(configuration:style:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/start()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)UIViewController"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"],"generated":true,"title":"UI components"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":" : "},{"text":"UIViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title","value":"DOTFFaceAutoCaptureResult","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillAppear(_:)\/title","op":"replace","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}]},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/title","value":"stopAsyncOnStopped:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"stopAsyncOnStopped:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/fragments"},{"value":"DOTFMultiRangeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title","value":"DOTDetectionPosition"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1delegate\/title","value":"delegate","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1delegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1style-swift.property\/title","value":"style"},{"value":[{"kind":"identifier","text":"style"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1style-swift.property\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","value":"DOTFFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","op":"replace","value":"DOTFMagnifEyeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace","value":"DOTFSmileLivenessViewController"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","value":"viewDidLayoutSubviews","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidLayoutSubviews()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace","value":"DOTFFaceSimpleCaptureViewController"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","value":"requestCaptureWithIsFacePresenceRequired:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1configuration-swift.property\/fragments","op":"replace","value":[{"text":"configuration","kind":"identifier"}]},{"value":"initWithConfiguration:style:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1init(configuration:style:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1init(configuration:style:)\/fragments","op":"replace"},{"op":"replace","value":"viewDidLoad","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidLoad()\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidLoad()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace"},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","op":"replace"},{"op":"replace","value":"start","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1start()\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"start"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1start()\/fragments","op":"replace"},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillTransition(to:with:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidAppear(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1viewDidAppear(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}