{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory"]]},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"object."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrrawimagefactory\/create(cgimage:)"]},{"paths":["\/documentation\/dotdocument\/bgrrawimagefactory\/create(cgimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTBgrRawImageFactory(cm)createWithCgImage:","role":"symbol","modules":[{"name":"DotDocument"}],"title":"create(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}],"roleHeading":"Type Method","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","text":"BgrRawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}]}],"name":"cgImage"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory\/create(cgImage:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage":{"type":"topic","title":"BgrRawImage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","kind":"symbol","url":"\/documentation\/dotdocument\/bgrrawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImageFactory/create(cgImage:)":{"navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory\/create(cgImage:)","type":"topic","title":"create(cgImage:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":"object.","type":"text"}],"url":"\/documentation\/dotdocument\/bgrrawimagefactory\/create(cgimage:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImageFactory":{"type":"topic","title":"BgrRawImageFactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory","kind":"symbol","url":"\/documentation\/dotdocument\/bgrrawimagefactory"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithCgImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"text":" *) ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithCgImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory~1create(cgImage:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/fragments"}]}]}