{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage"}],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"ciImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}],"name":"ciContext"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrrawimagefactory\/create(ciimage:cicontext:)"]},{"paths":["\/documentation\/dotdocument\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"title":"create(ciImage:ciContext:)","externalID":"c:@M@DotDocument@objc(cs)DOTBgrRawImageFactory(cm)createWithCiImage:ciContext:","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage"}],"symbolKind":"method","roleHeading":"Type Method"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImageFactory/create(ciImage:ciContext:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory\/create(ciImage:ciContext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/bgrrawimagefactory\/create(ciimage:cicontext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}],"role":"symbol","title":"create(ciImage:ciContext:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","type":"topic","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.4.1"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImageFactory":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}],"kind":"symbol","title":"BgrRawImageFactory","url":"\/documentation\/dotdocument\/bgrrawimagefactory","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bgrrawimage","title":"BgrRawImage"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"DOTBgrRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCiImage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":" *) "},{"text":"ciContext","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"createWithCiImage:ciContext:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/title","op":"replace","value":"DOTBgrRawImageFactory"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/fragments","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}