{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper\/travelDocumentType","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"}],"title":"travelDocumentType","symbolKind":"property","role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper(py)travelDocumentType"},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttypewrapper\/traveldocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/traveldocumenttypewrapper\/traveldocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"type":"topic","title":"TravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.16.0"}],"type":"topic","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"url":"\/documentation\/dotdocument\/traveldocumenttype","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"type":"topic","title":"TravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper/travelDocumentType":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"travelDocumentType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentType","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper\/travelDocumentType","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper\/traveldocumenttype","navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"type":"topic","role":"symbol","abstract":[],"title":"travelDocumentType"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"travelDocumentType","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"travelDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTTravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace","value":"DOTTravelDocumentType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace"},{"value":"travelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper~1travelDocumentType\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper~1travelDocumentType\/fragments","value":[{"text":"travelDocumentType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}