{"kind":"symbol","metadata":{"role":"symbol","title":"LoggerLogLevel.debug","roleHeading":"Case","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"externalID":"c:@M@DotDocument@E@DOTLoggerLogLevel@DOTLoggerLogLevelDebug","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/loggerloglevel\/debug"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/loggerloglevel\/debug"]}],"abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/debug"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"debug"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel"]]},"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel/debug":{"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel\/debug","abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"title":"LoggerLogLevel.debug","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel\/debug","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel":{"url":"\/documentation\/dotdocument\/loggerloglevel","role":"symbol","kind":"symbol","title":"LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelDebug"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1debug\/title","op":"replace","value":"DOTLoggerLogLevelDebug"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel~1debug\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}]}]}