{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/none","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"roleHeading":"Case","title":"LoggerLogLevel.none","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelNone"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/loggerloglevel\/none"]},{"paths":["\/documentation\/dotdocument\/loggerloglevel\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel"]]},"abstract":[{"text":"Disables logging.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel":{"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}],"url":"\/documentation\/dotdocument\/loggerloglevel","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"type":"topic","title":"LoggerLogLevel"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel/none":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/none","role":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/loggerloglevel\/none","kind":"symbol","type":"topic","title":"LoggerLogLevel.none","abstract":[{"type":"text","text":"Disables logging."}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTLoggerLogLevelNone","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","value":"DOTLoggerLogLevelNone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1none\/title"},{"value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1none\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}