{"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BarcodeValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"}],"title":"barcodeValidation","symbolKind":"property","externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC17barcodeValidationAA07BarcodeJ0Ovp"},"kind":"symbol","sections":[],"abstract":[{"text":"Specify barcode validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcodeValidation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","text":"BarcodeValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/barcodeValidation","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/barcodevalidation"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"url":"\/documentation\/dotdocument\/barcodevalidation","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","abstract":[{"type":"text","text":"Mode of barcode validation."}],"title":"BarcodeValidation","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/barcodeValidation":{"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/barcodevalidation","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcodeValidation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BarcodeValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/barcodeValidation","abstract":[{"text":"Specify barcode validation. Default is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"title":"barcodeValidation","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"title":"BaseDocumentAutoCaptureViewController","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"BaseDocumentAutoCaptureViewController.Configuration","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","value":"DOTDBarcodeValidation","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBarcodeValidation"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"}]}]}