{"metadata":{"role":"collectionGroup","title":"DotSdkError Implementations","roleHeading":"API Collection","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error"]]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error\/composeWithInternalError()"],"anchor":"Instance-Methods","title":"Instance Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/error\/dotsdkerror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 9.1.1","type":"text"}],"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"FaceAutoCaptureController.Error","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/error","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Error/composeWithInternalError()":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Error\/composeWithInternalError()","type":"topic","kind":"symbol","title":"composeWithInternalError()","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/error\/composewithinternalerror()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"patch":[{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}