{"abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/result","interfaceLanguage":"occ"},"metadata":{"symbolKind":"property","role":"symbol","title":"result","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"result"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiStateRunning(py)result","navigatorTitle":[{"text":"result","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"DOTFLFaceAutoCaptureResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"result"},{"kind":"text","text":";"}]}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/result"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","url":"\/documentation\/dotfacelite\/faceautocaptureresult","title":"FaceAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning","title":"DOTFLFaceAutoCaptureUiStateRunning","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiStateRunning"}],"abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureUiStateRunning/result":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureUiStateRunning\/result","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureuistaterunning\/result","title":"result","fragments":[{"kind":"identifier","text":"result"}],"abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}],"op":"replace"}]}]}