{"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minsharpness:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"minSharpness:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"DOTWrappedDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"minSharpness"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minSharpness:error:"},"metadata":{"title":"minSharpness:error:","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minSharpness:error:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder(im)minSharpness:error:","navigatorTitle":[{"text":"minSharpness:error:","kind":"identifier"}],"role":"symbol"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder/minSharpness:error:":{"navigatorTitle":[{"text":"minSharpness:error:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minSharpness:error:","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minsharpness:error:","title":"minSharpness:error:","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"minSharpness:error:"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"url":"\/documentation\/dotdocument\/wrappeddouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","title":"WrappedDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder":{"role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder","title":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","fragments":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle"}]}]}