{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"minSize:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"DOTWrappedDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"minSize"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minSize:error:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minsize:error:"]}],"sections":[],"kind":"symbol","metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"text":"minSize:error:","kind":"identifier"}],"role":"symbol","title":"minSize:error:","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder(im)minSize:error:","fragments":[{"text":"- ","kind":"text"},{"text":"minSize:error:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotDocument"}]},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder/minSize:error:":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minSize:error:","title":"minSize:error:","kind":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minsize:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minSize:error:"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minSize:error:"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","title":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"}],"abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/wrappeddouble","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","title":"WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value for Objective-C support.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]}]}]}