{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/warning"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"externalID":"c:@M@DotFaceLite@E@DOTLoggerLogLevel@DOTLoggerLogLevelWarning","title":"LoggerLogLevel.warning","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warning"}],"modules":[{"name":"DotFaceLite"}]},"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"warning","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/loggerloglevel\/warning"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel/warning":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel\/warning","role":"symbol","abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/loggerloglevel\/warning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warning"}],"title":"LoggerLogLevel.warning"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/LoggerLogLevel":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/loggerloglevel","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.3.1","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTLoggerLogLevelWarning"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTLoggerLogLevelWarning","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1warning\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}]}]}