{"sections":[],"abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".back"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/camerafacing"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC12cameraFacing0A6Camera0jI0Ovp","title":"cameraFacing","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/cameraFacing":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/cameraFacing","kind":"symbol","title":"cameraFacing","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/camerafacing","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".back"},{"type":"text","text":"."}]},"doc://DotDocument/documentation/DotDocument/CameraFacing":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerafacing","title":"CameraFacing"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"title":"DocumentAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"title":"DocumentAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]}]}]}