{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagesize\/calculatewidthtoheightratio()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imagesize\/calculatewidthtoheightratio()"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculateWidthToHeightRatio()","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculateWidthToHeightRatio","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"title":"calculateWidthToHeightRatio()"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/calculateWidthToHeightRatio()":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagesize\/calculatewidthtoheightratio()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculateWidthToHeightRatio()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"title":"calculateWidthToHeightRatio()"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagesize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"title":"ImageSize"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"calculateWidthToHeightRatio","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculateWidthToHeightRatio()\/title","value":"calculateWidthToHeightRatio","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculateWidthToHeightRatio()\/fragments"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments"}]}]}