{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/from(cgSize:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize"]]},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Type Method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") -> ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"title":"from(cgSize:)","externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(cm)fromCgSize:","symbolKind":"method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagesize\/from(cgsize:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imagesize\/from(cgsize:)"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/from(cgSize:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/from(cgSize:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/imagesize\/from(cgsize:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"title":"from(cgSize:)"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"role":"symbol","url":"\/documentation\/dotfacelite\/imagesize","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.14.0"}],"title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"fromCgSize:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgSize:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","text":"DOTImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"fromCgSize:"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cgSize","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"fromCgSize:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1from(cgSize:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1from(cgSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"}]}]}