{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholderdiametertoshortersideratio:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholderdiametertoshortersideratio:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(im)initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:","title":"init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","role":"symbol","symbolKind":"init","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","role":"symbol","type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","kind":"symbol","title":"FaceAutoCapturePreview","navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholderdiametertoshortersideratio:)","title":"init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderDiameterToShorterSideRatio"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithCameraImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","preciseIdentifier":"c:objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"cameraImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detectionArea:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectionArea","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)\/title","value":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}