{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)"},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmOutOfBoundsValidator(im)initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"symbolKind":"init","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"]]},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","abstract":[{"type":"text","text":"version: 8.7.1"}],"kind":"symbol","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:)":{"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"type":"topic","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"PalmOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"navigatorTitle":[{"kind":"identifier","text":"PalmOutOfBoundsValidator"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","value":"DOTPPalmOutOfBoundsValidator"},{"value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments"}]}]}