{"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/detectionposition\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/detectionposition\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/mirrored()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"extendedModule":"DotDocument","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"title":"mirrored()","externalID":"c:@CM@DotDocument@objc(cs)DOTDDetectionPosition(im)mirrored"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"DetectionPosition","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"url":"\/documentation\/dotdocument\/detectionposition","title":"DetectionPosition","abstract":[{"text":"Position of the document card in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DetectionPosition/mirrored()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition\/mirrored()","title":"mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/detectionposition\/mirrored()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"mirrored"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTDDetectionPosition","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"text":" *) ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","op":"replace","value":"DOTDDetectionPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1mirrored()\/title","op":"replace","value":"mirrored"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition~1mirrored()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]}]}]}