{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg8"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg8"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg8"]}],"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg8","kind":"identifier"}],"role":"symbol","title":"Lds1ElementaryFileId.dg8","roleHeading":"Case","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg8"}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg8"},"kind":"symbol","abstract":[{"text":"File identifier for data group 8. Data group 8 contains data features.","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg8","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg8":{"abstract":[{"type":"text","text":"File identifier for data group 8. Data group 8 contains data features."}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8","kind":"identifier"}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg8","kind":"identifier"}],"title":"Lds1ElementaryFileId.dg8","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg8","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg8","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","navigatorTitle":[{"kind":"identifier","text":"Lds1ElementaryFileId"}],"type":"topic","role":"symbol","abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"kind":"symbol","title":"Lds1ElementaryFileId","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLds1ElementaryFileIdDg8"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg8"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg8"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg8\/title","value":"DOTNLds1ElementaryFileIdDg8"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg8\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg8"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}