{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdimageperspectivewarper\/init"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDImagePerspectiveWarper\/init"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper"]]},"metadata":{"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper(im)init","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotDocument"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"url":"\/documentation\/dotdocument\/imageperspectivewarper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","kind":"symbol","title":"ImagePerspectiveWarper","navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDImagePerspectiveWarper/init":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDImagePerspectiveWarper\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/dotdimageperspectivewarper\/init","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDImagePerspectiveWarper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace"},{"value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]}]}]}