{"metadata":{"role":"symbol","title":"LoggerLogLevel.warning","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelWarning","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"roleHeading":"Case"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/warning","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/warning"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/warning"]}],"abstract":[{"text":"Logs unexpected events which indicate malfunction.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"text":"Available log levels.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/loggerloglevel"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/warning":{"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"role":"symbol","title":"LoggerLogLevel.warning","abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"url":"\/documentation\/dotfacecore\/loggerloglevel\/warning","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/warning","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTLoggerLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1warning\/title","value":"DOTLoggerLogLevelWarning","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1warning\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}