{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/cgSize","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"cgSize","kind":"identifier"}],"extendedModule":"DotCore","title":"cgSize","externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(py)cgSize","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagesize\/cgsize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imagesize\/cgsize"]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/ImageSize/cgSize":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/cgSize","url":"\/documentation\/dotdocument\/imagesize\/cgsize","type":"topic","kind":"symbol","title":"cgSize","navigatorTitle":[{"text":"cgSize","kind":"identifier"}],"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageSize":{"url":"\/documentation\/dotdocument\/imagesize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","type":"topic","abstract":[{"type":"text","text":"Image size in pixels."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"cgSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"cgSize","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"}],"languages":["occ"]}]}},{"value":"cgSize","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1cgSize\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1cgSize\/fragments","value":[{"kind":"identifier","text":"cgSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}