{"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)initWithWidth:height:","symbolKind":"init","title":"init(width:height:)","navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"role":"symbol"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"]]},"variants":[{"paths":["\/documentation\/dotdocument\/imagesize\/init(width:height:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imagesize\/init(width:height:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/init(width:height:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/ImageSize":{"title":"ImageSize","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotdocument\/imagesize","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/ImageSize/init(width:height:)":{"url":"\/documentation\/dotdocument\/imagesize\/init(width:height:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"abstract":[],"kind":"symbol","type":"topic","title":"init(width:height:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize\/init(width:height:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithWidth:height:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithWidth:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"width"},{"kind":"text","text":" "},{"kind":"identifier","text":"height:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"height"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle","op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1init(width:height:)\/title","op":"replace","value":"initWithWidth:height:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize~1init(width:height:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithWidth:height:","kind":"identifier"}]}]}]}