{"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFill","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}],"title":"CameraPreviewScaleType.fill","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fill"}]}],"kind":"declarations"}],"abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fill"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/camerapreviewscaletype\/fill"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/camerapreviewscaletype\/fill"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType":{"url":"\/documentation\/dotfingerscore\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/fill":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/fill","abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fill","title":"CameraPreviewScaleType.fill","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFill","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/navigatorTitle","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fill\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fill\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}