{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"controller"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController","text":"DocumentAutoCaptureController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}],"role":"symbol","title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotDocument@objc(pl)DOTDocumentAutoCaptureControllerDelegate(im)documentAutoCaptureControllerCandidateSelectionStarted:","required":true,"modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate":{"role":"symbol","title":"DocumentAutoCaptureControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the document auto capture events."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerDelegate"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerDelegate/documentAutoCaptureControllerCandidateSelectionStarted(_:)":{"navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}],"role":"symbol","title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerDelegate\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontrollerdelegate\/documentautocapturecontrollercandidateselectionstarted(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController","text":"DOTDocumentAutoCaptureController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"controller"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate\/title","value":"DOTDocumentAutoCaptureControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerDelegate~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}