{"variants":[{"paths":["\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/camera","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"camera"},{"kind":"text","text":";"}],"languages":["occ"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\Endcode"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration"]]},"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration(py)camera","navigatorTitle":[{"text":"camera","kind":"identifier"}],"title":"camera","fragments":[{"kind":"identifier","text":"camera"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"fragments":[{"text":"DOTFSmileLivenessConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","title":"DOTFSmileLivenessConfiguration","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Smile Liveness component."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration/camera":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/camera","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/camera","title":"camera","type":"topic","fragments":[{"kind":"identifier","text":"camera"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","title":"CameraConfiguration","url":"\/documentation\/dotfacecore\/cameraconfiguration","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}