{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/machineReadableZone"},"kind":"symbol","metadata":{"title":"machineReadableZone","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"s:11DotDocument9MrzReaderC6ResultC19machineReadableZone0aB7Commons07MachinegH0CSgvp","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotDocument"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/result\/machinereadablezone"]}],"sections":[],"abstract":[{"text":"Parsed MRZ.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"]]},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"abstract":[{"type":"text","text":"MRZ reading result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"title":"MrzReader.Result","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","type":"topic","url":"\/documentation\/dotdocument\/mrzreader\/result","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Result"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/machineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/machineReadableZone","type":"topic","abstract":[{"type":"text","text":"Parsed MRZ."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"machineReadableZone","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/result\/machinereadablezone","title":"machineReadableZone"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","title":"MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","type":"topic","title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader"}},"variantOverrides":[{"patch":[{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/navigatorTitle"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}