{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:fingers:"}],"symbolKind":"init","title":"init(document:face:faceLite:nfc:palm:fingers:)","externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:fingers:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fingers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","modules":[{"name":"DotNfc"}]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:fingers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"fingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","kind":"typeIdentifier","text":"DotFingersLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration"},{"kind":"text","text":"? = nil)"}]}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceLiteLibraryConfiguration":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","url":"\/documentation\/dotnfc\/dotfacelitelibraryconfiguration","abstract":[{"type":"text","text":"Face Lite library configuration."}],"title":"DotFaceLiteLibraryConfiguration","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","type":"topic","abstract":[{"text":"Face library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Libraries":{"url":"\/documentation\/dotnfc\/libraries","kind":"symbol","abstract":[{"type":"text","text":"Container for library configurations."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"title":"Libraries","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Libraries/init(document:face:faceLite:nfc:palm:fingers:)":{"title":"init(document:face:faceLite:nfc:palm:fingers:)","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:fingers:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:fingers:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fingers","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","text":"DotFingersLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:fingers:","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration":{"url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration","kind":"symbol","abstract":[{"type":"text","text":"NFC library configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"title":"DotNfcLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"title":"DotPalmLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"abstract":[{"type":"text","text":"Fingers library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","title":"DotFingersLibraryConfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:fingers:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocument:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLite"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFingersLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fingers"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/title","value":"DotFaceLiteLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/title","value":"initWithDocument:face:faceLite:nfc:palm:fingers:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:fingers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:fingers:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}