{"metadata":{"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"symbolKind":"init","title":"init(document:face:faceLite:nfc:palm:)","roleHeading":"Initializer","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?)"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLiteLibraryConfiguration":{"url":"\/documentation\/dotnfc\/dotfacelitelibraryconfiguration","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","title":"DotFaceLiteLibraryConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face Lite library configuration."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"abstract":[{"text":"Document library configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","abstract":[{"type":"text","text":"NFC library configuration."}],"navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"title":"DotNfcLibraryConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/Libraries/init(document:face:faceLite:nfc:palm:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"nfc"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"abstract":[],"kind":"symbol","title":"init(document:face:faceLite:nfc:palm:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/init(document:face:faceLite:nfc:palm:)","type":"topic","url":"\/documentation\/dotnfc\/libraries\/init(document:face:facelite:nfc:palm:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"kind":"symbol","title":"Libraries","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotnfc\/libraries","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"type":"topic","title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","abstract":[{"text":"Face library configuration.","type":"text"}],"title":"DotFaceLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","role":"symbol","type":"topic","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceLite:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"faceLite","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceLiteLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle"}]}]}