{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)Libraries(py)nfc","symbolKind":"property","roleHeading":"Instance Property","title":"nfc","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"nfc","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/libraries\/nfc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/libraries\/nfc"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/nfc"},"abstract":[{"text":"NFC library configuration.","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration","type":"topic","abstract":[{"text":"NFC library configuration.","type":"text"}],"role":"symbol","title":"DotNfcLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Libraries/nfc":{"title":"nfc","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotnfc\/libraries\/nfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/nfc","role":"symbol","type":"topic","abstract":[{"text":"NFC library configuration.","type":"text"}],"navigatorTitle":[{"text":"nfc","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Libraries":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"title":"Libraries","role":"symbol","url":"\/documentation\/dotnfc\/libraries","kind":"symbol","abstract":[{"type":"text","text":"Container for library configurations."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Libraries"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"nfc","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"nfc"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration"},{"text":" * ","kind":"text"},{"text":"nfc","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotNfcLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/title"},{"value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1nfc\/title","op":"replace","value":"nfc"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1nfc\/fragments","op":"replace","value":[{"text":"nfc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","op":"replace","value":"Libraries"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle"}]}]}