{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:quality:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"kind":"symbol","metadata":{"symbolKind":"init","externalID":"s:11DotDocument0B8DetectorC0B0C17detectionPosition10confidence18widthToHeightRatio7qualityAeA09DetectionE0C_S2dAA0B7QualityCtcfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality","kind":"typeIdentifier","text":"DocumentQuality"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotDocument"}],"title":"init(detectionPosition:confidence:widthToHeightRatio:quality:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/document\/init(detectionposition:confidence:widthtoheightratio:quality:)"]}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"abstract":[{"type":"text","text":"Document quality."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","type":"topic","url":"\/documentation\/dotdocument\/documentquality","title":"DocumentQuality","kind":"symbol","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/init(detectionPosition:confidence:widthToHeightRatio:quality:)":{"kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionPosition"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"quality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality"},{"text":")","kind":"text"}],"url":"\/documentation\/dotdocument\/documentdetector\/document\/init(detectionposition:confidence:widthtoheightratio:quality:)","abstract":[],"title":"init(detectionPosition:confidence:widthToHeightRatio:quality:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:quality:)"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"abstract":[{"text":"Position of the document card in the image.","type":"text"}],"url":"\/documentation\/dotdocument\/detectionposition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","kind":"symbol","title":"DetectionPosition","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"title":"DocumentDetector","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"role":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/documentdetector\/document","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","navigatorTitle":[{"kind":"identifier","text":"Document"}],"type":"topic","title":"DocumentDetector.Document","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title","value":"DOTDDocumentQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}