{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/deinitialize()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(im)deinitializeAndReturnError:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"title":"deinitialize()","role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/deinitialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Deinitialize library."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"name":"Throws","content":[{"inlineContent":[{"text":"Throws an error if the ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" library fails to deinitialize."}],"type":"paragraph"}],"style":"note","type":"aside"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentLibrary","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","title":"DotDocumentLibrary"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/deinitialize()":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/deinitialize()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize library."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"type":"topic","title":"deinitialize()","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"deinitializeAndReturnError:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotDocumentLibrary","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title"},{"op":"replace","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1deinitialize()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}]}]}]}