{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:imageParameters:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"position"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTDetectionPosition"},{"kind":"text","text":", "},{"text":"imageParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageParameters","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B8DetectorC0B0C10confidence8position15imageParametersAESd_AA17DetectionPositionCAA05ImageH0Ctcfc","title":"init(confidence:position:imageParameters:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/face\/init(confidence:position:imageparameters:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTDetectionPosition","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","text":"ImageParameters"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageparameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","title":"ImageParameters","abstract":[{"text":"Parameters of the image which was used for the face detection.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"url":"\/documentation\/dotfacelite\/facedetector\/face","kind":"symbol","title":"FaceDetector.Face","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face","type":"topic","navigatorTitle":[{"text":"Face","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DetectionPosition":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"The position of the detected face in the image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","url":"\/documentation\/dotfacelite\/detectionposition","title":"DetectionPosition","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Face/init(confidence:position:imageParameters:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTDetectionPosition","text":"DetectionPosition"},{"kind":"text","text":", "},{"text":"imageParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/facedetector\/face\/init(confidence:position:imageparameters:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face\/init(confidence:position:imageParameters:)","role":"symbol","title":"init(confidence:position:imageParameters:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/title","value":"DOTFLImageParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/fragments","op":"replace","value":[{"text":"DOTFLImageParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTDetectionPosition","kind":"identifier"}]}]}]}