{"kind":"symbol","metadata":{"title":"verification","role":"symbol","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)verification","navigatorTitle":[{"kind":"identifier","text":"verification"}],"fragments":[{"kind":"identifier","text":"verification"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/verification"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/verification"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules/verification":{"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules\/verification","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules\/verification","kind":"symbol","title":"verification","type":"topic","fragments":[{"text":"verification","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfigurationModules":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfigurationmodules","title":"DotFaceLibraryConfigurationModules"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face verification module."}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration","title":"DotFaceVerificationModuleConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}