{"sections":[],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","title":"primaryIdentifier","navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(py)primaryIdentifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Primary identifier usually represents surname."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"MrzElement"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/primaryidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznameelement\/primaryidentifier"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/primaryIdentifier","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement","kind":"symbol","title":"MrzElement"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"url":"\/documentation\/dotdocument\/mrznameelement","role":"symbol","title":"MrzNameElement","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzNameElement/primaryIdentifier":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement\/primaryIdentifier","navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrznameelement\/primaryidentifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Primary identifier usually represents surname."}],"title":"primaryIdentifier"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"primaryIdentifier","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"primaryIdentifier","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"DOTMrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":" * ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTMrzElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElement"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/navigatorTitle","op":"replace"},{"value":"DOTMrzNameElement","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/navigatorTitle","op":"replace"},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace"},{"value":"primaryIdentifier","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1primaryIdentifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"primaryIdentifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement~1primaryIdentifier\/fragments","op":"replace"}]}]}