{"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"title":"dependencyIdentifiers","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersNotDetectedValidator(py)dependencyIdentifiers","symbolKind":"property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/dependencyidentifiers"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator/dependencyIdentifiers":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/dependencyIdentifiers","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/dependencyidentifiers","kind":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"role":"symbol","title":"FingersNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"FingersNotDetectedValidator"}],"abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersNotDetectedValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1dependencyIdentifiers\/title"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTFGFingersNotDetectedValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}