{"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(image:document:content:travelDocumentType:machineReadableZone:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/content","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/image","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/machineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/travelDocumentType"],"title":"Instance Properties","anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"roleHeading":"Class","modules":[{"name":"DotDocument"}],"title":"DocumentAutoCaptureResult","symbolKind":"class","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"],"generated":true,"anchor":"Document-auto-capture-process","title":"Document auto capture process"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDDocumentAutoCaptureResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"references":{"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/machineReadableZone":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureresult\/machinereadablezone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/machineReadableZone","navigatorTitle":[{"kind":"identifier","text":"machineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"machineReadableZone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"},{"kind":"text","text":"?"}],"title":"machineReadableZone"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/travelDocumentType":{"title":"travelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/travelDocumentType","type":"topic","navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult\/traveldocumenttype","abstract":[{"text":"Resolved travel document type.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"text":"?","kind":"text"}]},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"title":"DocumentAutoCaptureDetection","url":"\/documentation\/dotdocument\/documentautocapturedetection","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/content":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"title":"content","url":"\/documentation\/dotdocument\/documentautocaptureresult\/content","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/content","abstract":[{"type":"text","text":"Binary content for server-side evaluation."}],"navigatorTitle":[{"kind":"identifier","text":"content"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/init(image:document:content:travelDocumentType:machineReadableZone:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"},{"kind":"text","text":"?)"}],"title":"init(image:document:content:travelDocumentType:machineReadableZone:)","url":"\/documentation\/dotdocument\/documentautocaptureresult\/init(image:document:content:traveldocumenttype:machinereadablezone:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(image:document:content:travelDocumentType:machineReadableZone:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:document:content:travelDocumentType:machineReadableZone:"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description","url":"\/documentation\/dotdocument\/documentautocaptureresult\/description","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/document":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":"?"}],"title":"document","url":"\/documentation\/dotdocument\/documentautocaptureresult\/document","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/document","abstract":[{"type":"text","text":"The result of the document detection. Might be "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" only if "},{"type":"codeVoice","code":"DocumentAutoCaptureViewController\/requestCapture()"},{"type":"text","text":" was used to get the result."}],"navigatorTitle":[{"kind":"identifier","text":"document"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"title":"DocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureResult"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/image":{"title":"image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/image","type":"topic","navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult\/image","abstract":[{"type":"text","text":"Document image."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"title":"DocumentAutoCaptureFrameParameters","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}]},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTDDocumentAutoCaptureResult","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/content","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/document","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/image","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/machineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/travelDocumentType"],"title":"Instance Properties","anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(image:document:content:travelDocumentType:machineReadableZone:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"],"title":"Document auto capture process","anchor":"Document-auto-capture-process"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"machineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1machineReadableZone\/title"},{"value":[{"text":"machineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1machineReadableZone\/fragments"},{"value":"travelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1travelDocumentType\/title"},{"value":[{"text":"travelDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1travelDocumentType\/fragments"},{"value":"DOTDDocumentAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/navigatorTitle"},{"value":"content","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1content\/title"},{"value":[{"text":"content","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1content\/fragments"},{"value":"initWithImage:document:content:travelDocumentType:machineReadableZone:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(image:document:content:travelDocumentType:machineReadableZone:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithImage:document:content:travelDocumentType:machineReadableZone:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(image:document:content:travelDocumentType:machineReadableZone:)\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1description\/fragments"},{"value":"document","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1document\/title"},{"value":[{"text":"document","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1document\/fragments"},{"value":"DOTDDocumentAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle"},{"value":"image","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1image\/title"},{"value":[{"text":"image","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1image\/fragments"},{"value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle"}]}]}