{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships"}],"metadata":{"title":"DotFingersModuleId","roleHeading":"Enumeration","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"symbolKind":"enum","role":"symbol","externalID":"c:@M@DotCore@E@DotFingersModuleId"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/detection","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/transformation"],"anchor":"Enumeration-Cases","generated":true},{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/init(rawValue:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/description"],"anchor":"Instance-Properties","generated":true},{"title":"Default Implementations","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfingersmoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfingersmoduleid"]}],"references":{"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId":{"type":"topic","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"title":"DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId","kind":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingersmoduleid","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/description":{"type":"topic","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/description","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/description","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/detection":{"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/detection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/detection","role":"symbol","kind":"symbol","type":"topic","abstract":[],"title":"DotFingersModuleId.detection"},"doc://DotDocument/SY":{"identifier":"doc:\/\/DotDocument\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/RawRepresentable-Implementations":{"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/rawrepresentable-implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/RawRepresentable-Implementations"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/Equatable-Implementations":{"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/equatable-implementations","type":"topic","abstract":[],"kind":"article","role":"collectionGroup","title":"Equatable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/Equatable-Implementations"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/transformation":{"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/transformation","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/transformation","navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"title":"DotFingersModuleId.transformation","abstract":[]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/init(rawValue:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/init(rawvalue:)","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFingersModuleId","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DotFingersModuleId","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/detection","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/transformation"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFingersModuleId","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/title"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/navigatorTitle"},{"value":"DotFingersModuleIdDetection","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1detection\/title"},{"value":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1detection\/fragments"},{"value":"DotFingersModuleIdTransformation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1transformation\/title"},{"value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId~1transformation\/fragments"}]}]}