{"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","title":"DotFingersTransformationModuleConfiguration","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","title":"Conforms To"}],"kind":"symbol","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"references":{"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration":{"title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration","type":"topic","navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFingersTransformationModuleConfiguration/init":{"url":"\/documentation\/dotdocument\/dotfingerstransformationmoduleconfiguration\/init","abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/objc(cs)NSObject":{"identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotDocument/SQ":{"identifier":"doc:\/\/DotDocument\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersTransformationModuleConfiguration\/init"],"anchor":"Instance-Methods"}],"op":"add","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFingersTransformationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersTransformationModuleConfiguration\/navigatorTitle"}]}]}