{"kind":"symbol","metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceModule","title":"DotFaceModule","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"roleHeading":"Protocol"},"sections":[],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/dependencies","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/modelsUrl","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/moduleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/versionName"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodule"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodule"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"],"title":"DotFace modularization"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/moduleId":{"required":true,"title":"moduleId","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleId"},{"text":": ","kind":"text"},{"text":"DotFaceModuleId","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleId","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"moduleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/moduleId","url":"\/documentation\/dotfacecore\/dotfacemodule\/moduleid"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/dependencies":{"required":true,"kind":"symbol","abstract":[],"title":"dependencies","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencies"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper","text":"DotFaceModuleCategoryWrapper","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"dependencies"}],"url":"\/documentation\/dotfacecore\/dotfacemodule\/dependencies","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/dependencies"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/versionName":{"required":true,"title":"versionName","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/versionName","url":"\/documentation\/dotfacecore\/dotfacemodule\/versionname"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/modelsUrl":{"required":true,"kind":"symbol","abstract":[],"title":"modelsUrl","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modelsUrl","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"}],"type":"topic","navigatorTitle":[{"text":"modelsUrl","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodule\/modelsurl","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/modelsUrl"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","url":"\/documentation\/dotfacecore\/dotfacemoduleid","title":"DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","title":"DotFaceModuleCategory","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleCategory","kind":"identifier"}],"type":"topic","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" module category."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","title":"DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"type":"topic","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFaceModule","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"op":"replace","value":[{"text":"DotFaceModule","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/dependencies","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/modelsUrl","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/moduleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/versionName"]}],"op":"replace"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"],"generated":true,"title":"DotFace modularization"}]},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceModule","kind":"identifier"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"moduleId","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1moduleId\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1moduleId\/fragments","value":[{"text":"moduleId","kind":"identifier"}]},{"op":"replace","value":"dependencies","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1dependencies\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1dependencies\/fragments","value":[{"text":"dependencies","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1versionName\/title","op":"replace","value":"versionName"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1versionName\/fragments","op":"replace","value":[{"text":"versionName","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1modelsUrl\/title","op":"replace","value":"modelsUrl"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1modelsUrl\/fragments","value":[{"kind":"identifier","text":"modelsUrl"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}]},{"op":"replace","value":"DotFaceModule","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace","value":[{"text":"DotFaceModule","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}