{"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTLoggerLogLevel) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Available log levels."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"metadata":{"title":"LoggerLogLevel","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerLogLevel"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/debug","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/info","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/none","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/warning"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/init(rawValue:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/description"],"title":"Instance Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/none":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/none","abstract":[{"text":"Disables logging.","type":"text"}],"role":"symbol","kind":"symbol","title":"LoggerLogLevel.none","type":"topic","url":"\/documentation\/dotfacecore\/loggerloglevel\/none","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"none","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/RawRepresentable-Implementations":{"kind":"article","type":"topic","role":"collectionGroup","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","url":"\/documentation\/dotfacecore\/loggerloglevel\/rawrepresentable-implementations","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/debug":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/debug","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"url":"\/documentation\/dotfacecore\/loggerloglevel\/debug","kind":"symbol","title":"LoggerLogLevel.debug"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/init(rawValue:)":{"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/dotfacecore\/loggerloglevel\/init(rawvalue:)","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/init(rawValue:)"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/info":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/info","title":"LoggerLogLevel.info","type":"topic","navigatorTitle":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"abstract":[{"type":"text","text":"Logs informative events."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/loggerloglevel\/info","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/Equatable-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/dotfacecore\/loggerloglevel\/equatable-implementations"},"doc://DotFaceCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFaceCore\/SY","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/description":{"url":"\/documentation\/dotfacecore\/loggerloglevel\/description","role":"symbol","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","kind":"symbol","abstract":[]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/warning":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/warning","title":"LoggerLogLevel.warning","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"abstract":[{"text":"Logs unexpected events which indicate malfunction.","type":"text"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/loggerloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warning"}]},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","url":"\/documentation\/dotfacecore\/loggerloglevel","title":"LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","abstract":[{"text":"Available log levels.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/error":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"url":"\/documentation\/dotfacecore\/loggerloglevel\/error","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"type":"topic","role":"symbol","title":"LoggerLogLevel.error","kind":"symbol","navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/debug","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/info","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/none","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/warning"],"title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTLoggerLogLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1none\/title","value":"DOTLoggerLogLevelNone"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1none\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelNone"}]},{"value":"DOTLoggerLogLevelDebug","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1debug\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1debug\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}]},{"value":"DOTLoggerLogLevelInfo","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1info\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1info\/fragments","value":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"op":"replace"},{"value":"DOTLoggerLogLevelWarning","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1warning\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1warning\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","value":"DOTLoggerLogLevelError","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1error\/title"},{"value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel~1error\/fragments"}]}]}