{"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"td3","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@M@DotDocumentCommons@E@DOTTravelDocumentType@DOTTravelDocumentTypeTd3","modules":[{"name":"DotDocument"}],"role":"symbol","title":"TravelDocumentType.td3"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/td3"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td3"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/td3"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td3","kind":"identifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"references":{"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/traveldocumenttype","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"title":"TravelDocumentType","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.4.1"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/td3":{"kind":"symbol","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"td3","kind":"identifier"}],"navigatorTitle":[{"text":"DOTTravelDocumentTypeTd3","kind":"identifier"}],"title":"TravelDocumentType.td3","url":"\/documentation\/dotdocument\/traveldocumenttype\/td3","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/td3"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTTravelDocumentTypeTd3"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace","value":"DOTTravelDocumentType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/navigatorTitle","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType~1td3\/title","op":"replace","value":"DOTTravelDocumentTypeTd3"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType~1td3\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeTd3"}]}]}]}