{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration\/init","interfaceLanguage":"occ"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceExpressionNeutralModuleConfiguration/init":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"init","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration\/init","url":"\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceExpressionNeutralModuleConfiguration":{"abstract":[{"text":"Face expression neutral module.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceExpressionNeutralModuleConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotfaceexpressionneutralmoduleconfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]}]}]}