{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Type of finger to validate.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/fingertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/fingertype"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"]]},"sections":[],"metadata":{"title":"fingerType","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator(py)fingerType","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"FingerType"}],"navigatorTitle":[{"kind":"identifier","text":"fingerType"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/fingerType","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/fingerType":{"title":"fingerType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingerType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fingerType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of finger to validate."}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/fingertype","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/fingerType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"fingerType","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"fingerType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"DOTFGFingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerType"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle"},{"value":"DOTFGFingerType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"},{"value":"fingerType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1fingerType\/title"},{"value":[{"kind":"identifier","text":"fingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1fingerType\/fragments"}]}]}