{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"fingerType","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","text":"FingerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"text":", ","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" = SharpnessTooLowValidator.defaultThreshold, ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" = FingersNotDetectedValidator.defaultMinConfidenceThreshold) ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/init(fingertype:threshold:minconfidencethreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/init(fingertype:threshold:minconfidencethreshold:)"]}],"metadata":{"title":"init(fingerType:threshold:minConfidenceThreshold:)","roleHeading":"Initializer","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator(im)initWithFingerType:threshold:minConfidenceThreshold:error:","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"fingerType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType"},{"text":", ","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithFingerType:threshold:minConfidenceThreshold:error:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"init"},"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/init(fingerType:threshold:minConfidenceThreshold:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/init(fingerType:threshold:minConfidenceThreshold:)":{"title":"init(fingerType:threshold:minConfidenceThreshold:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/init(fingertype:threshold:minconfidencethreshold:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"fingerType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","navigatorTitle":[{"text":"initWithFingerType:threshold:minConfidenceThreshold:error:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/init(fingerType:threshold:minConfidenceThreshold:)"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithFingerType:threshold:minConfidenceThreshold:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFingerType:threshold:minConfidenceThreshold:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithFingerType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"},{"text":") ","kind":"text"},{"text":"fingerType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"threshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"threshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"minConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1init(fingerType:threshold:minConfidenceThreshold:)\/title","value":"initWithFingerType:threshold:minConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1init(fingerType:threshold:minConfidenceThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFingerType:threshold:minConfidenceThreshold:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","value":"DOTFGSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}]}]}]}