{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/threshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/threshold"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Current minimal accepted sharpness."}],"metadata":{"title":"threshold","navigatorTitle":[{"kind":"identifier","text":"threshold"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator(py)threshold","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/threshold","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/threshold":{"type":"topic","kind":"symbol","title":"threshold","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/threshold","abstract":[{"text":"Current minimal accepted sharpness.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"threshold","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/threshold"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"threshold","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"threshold"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"threshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1threshold\/title"},{"op":"replace","value":[{"kind":"identifier","text":"threshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1threshold\/fragments"},{"op":"replace","value":"DOTFGSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle"}]}]}