{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for blurry fingers."}],"type":"paragraph"}],"kind":"content"}],"abstract":[{"text":"Validate sharpness of the detected fingers.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/validate(fingersautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/validate(fingersautocaptureframeparameters:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"]]},"sections":[],"metadata":{"title":"validate(fingersAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator(im)validateWithFingersAutoCaptureFrameParameters:","symbolKind":"method","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/validate(fingersAutoCaptureFrameParameters:)":{"title":"validate(fingersAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"abstract":[{"text":"Validate sharpness of the detected fingers.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/validate(fingersautocaptureframeparameters:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"title":"FingersAutoCaptureFrameParameters","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information from the detection process about the detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"validateWithFingersAutoCaptureFrameParameters:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","text":"DOTFGFingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"text":"Frame parameters to validate.","type":"text"}]}]}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" for blurry fingers."}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","value":"DOTFGSharpnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","value":"validateWithFingersAutoCaptureFrameParameters:","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"}]}]}