{"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/month","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"month","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzdate\/month"]},{"paths":["\/documentation\/dotnfc\/mrzdate\/month"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(py)month","title":"month","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"month","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"month"}],"symbolKind":"property","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate"]]},"references":{"doc://DotNfc/documentation/DotNfc/MrzDate/month":{"title":"month","navigatorTitle":[{"text":"month","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzdate\/month","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/month","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"month"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/MrzDate":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol","title":"MrzDate","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"url":"\/documentation\/dotnfc\/mrzdate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"month","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"month","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"month"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1month\/title","value":"month"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1month\/fragments","value":[{"kind":"identifier","text":"month"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title","value":"DOTMrzDate","op":"replace"},{"value":[{"text":"DOTMrzDate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","op":"replace"}]}]}