{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/year","interfaceLanguage":"swift"},"metadata":{"title":"year","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(py)year","navigatorTitle":[{"kind":"identifier","text":"year"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"year"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","modules":[{"name":"DotNfc"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"year"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzdate\/year"]},{"paths":["\/documentation\/dotnfc\/mrzdate\/year"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/MrzDate":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","type":"topic","url":"\/documentation\/dotnfc\/mrzdate","navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDate","kind":"identifier"}],"title":"MrzDate"},"doc://DotNfc/documentation/DotNfc/MrzDate/year":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"year","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotnfc\/mrzdate\/year","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"year"}],"title":"year","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/year","abstract":[],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"year","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"year","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":" ","kind":"text"},{"text":"year","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DOTMrzDate","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1year\/title","value":"year","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1year\/fragments","value":[{"kind":"identifier","text":"year"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}