{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(sample:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Process an input sample and update the state."}],"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"processWithSample:error:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureController(im)processWithSample:error:","symbolKind":"method","title":"process(sample:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Sample","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC6SampleC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"ProcessingResult","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample","text":"Sample","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC6SampleC","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult"}]}]},{"kind":"parameters","parameters":[{"name":"sample","content":[{"type":"paragraph","inlineContent":[{"text":"Input sample. Terminates if ","type":"text"},{"type":"codeVoice","code":"sample.image"},{"text":" property is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}]}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"text":"The result of processing of the input sample.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"style":"note","name":"Throws","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Throws an error if you call this method after the document auto capture process has finished."}],"type":"paragraph"}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(sample:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(sample:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample":{"abstract":[{"text":"The data sample captured at specific time which serves as an input for the document auto capture process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","title":"DOTDDocumentAutoCaptureControllerSample","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureControllerSample","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}],"title":"DocumentAutoCaptureController.Sample","navigatorTitle":[{"text":"Sample","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/process(sample:)":{"abstract":[{"type":"text","text":"Process an input sample and update the state."}],"navigatorTitle":[{"kind":"identifier","text":"processWithSample:error:"}],"title":"process(sample:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC6SampleC","kind":"typeIdentifier","text":"Sample"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotDocument0B21AutoCaptureControllerC16ProcessingResultC","kind":"typeIdentifier","text":"ProcessingResult"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(sample:)","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/process(sample:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/processingresult","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/ProcessingResult","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"title":"DocumentAutoCaptureController.ProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the document auto capture process.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult":{"role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult","type":"topic","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerProcessingResult"}],"kind":"symbol","title":"DOTDDocumentAutoCaptureControllerProcessingResult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"processWithSample:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithSample:error:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerProcessingResult","text":"DOTDDocumentAutoCaptureControllerProcessingResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"processWithSample:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerSample","text":"DOTDDocumentAutoCaptureControllerSample"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sample"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input sample. Terminates if ","type":"text"},{"type":"codeVoice","code":"sample.image"},{"text":" property is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}],"type":"paragraph"}],"name":"sample"},{"content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"The result of processing of the input sample."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"processWithSample:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(sample:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(sample:)\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"}]}]}