{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":")"}],"title":"process(bgraRawImage:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController(im)processWithBgraRawImage:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"processWithBgraRawImage:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/process(bgraRawImage:)":{"role":"symbol","title":"process(bgraRawImage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/process(bgraRawImage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"processWithBgraRawImage:"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/process(bgrarawimage:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"processWithBgraRawImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithBgraRawImage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"processWithBgraRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:)\/title","value":"processWithBgraRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController~1process(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"processWithBgraRawImage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}