{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"TravelDocumentReaderPassword","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"activeAuthenticationChallenge","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"? = nil)"}]}],"kind":"declarations"},{"parameters":[{"name":"password","content":[{"inlineContent":[{"text":"Password for accessing the chip.","type":"text"}],"type":"paragraph"}]},{"name":"activeAuthenticationChallenge","content":[{"inlineContent":[{"type":"text","text":"Random 8 bytes. If the Active Authentication challenge is set,"},{"type":"text","text":" "},{"type":"text","text":"Active Authentication protocol will be used for the authentication of the chip (if supported by the chip)."},{"type":"text","text":" "},{"type":"text","text":"Response (signature) will be returned in the result of the read operation. This response should be validated"},{"type":"text","text":" "},{"type":"text","text":"by the application server to verify the authenticity of the chip. In case when the Active Authentication"},{"type":"text","text":" "},{"type":"text","text":"protocol is not supported by the chip, the chip will be authenticated the same way as if the argument"},{"type":"text","text":" "},{"type":"codeVoice","code":"activeAuthenticationChallenge"},{"type":"text","text":" is not set."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"inlineContent":[{"text":"You can handle success or failure of NFC reading by implementing the delegate methods.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"readWithPassword:activeAuthenticationChallenge:","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReader(im)readWithPassword:activeAuthenticationChallenge:","modules":[{"name":"DotNfc"}],"title":"read(password:activeAuthenticationChallenge:)","roleHeading":"Instance Method","symbolKind":"method","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"13.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"13.0"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"password","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"TravelDocumentReaderPassword","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"activeAuthenticationChallenge","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/read(password:activeauthenticationchallenge:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/read(password:activeauthenticationchallenge:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(password:activeAuthenticationChallenge:)"},"abstract":[{"text":"Read passport using NFC password.","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/read(password:activeAuthenticationChallenge:)":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"readWithPassword:activeAuthenticationChallenge:"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/read(password:activeauthenticationchallenge:)","title":"read(password:activeAuthenticationChallenge:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/read(password:activeAuthenticationChallenge:)","abstract":[{"type":"text","text":"Read passport using NFC password."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"password"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","kind":"typeIdentifier","text":"TravelDocumentReaderPassword"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationChallenge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?)"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","type":"topic","abstract":[{"type":"text","text":"Password for accessing the chip."}],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPassword"}],"title":"TravelDocumentReaderPassword"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"readWithPassword:activeAuthenticationChallenge:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"readWithPassword:activeAuthenticationChallenge:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"readWithPassword:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotNfc@objc(pl)DOTNTravelDocumentReaderPassword","text":"id<DOTNTravelDocumentReaderPassword>"},{"kind":"text","text":") "},{"kind":"internalParam","text":"password"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationChallenge:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"activeAuthenticationChallenge"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Password for accessing the chip.","type":"text"}]}],"name":"password"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Random 8 bytes. If the Active Authentication challenge is set,","type":"text"},{"text":" ","type":"text"},{"text":"Active Authentication protocol will be used for the authentication of the chip (if supported by the chip).","type":"text"},{"text":" ","type":"text"},{"text":"Response (signature) will be returned in the result of the read operation. This response should be validated","type":"text"},{"text":" ","type":"text"},{"text":"by the application server to verify the authenticity of the chip. In case when the Active Authentication","type":"text"},{"text":" ","type":"text"},{"text":"protocol is not supported by the chip, the chip will be authenticated the same way as if the argument","type":"text"},{"text":" ","type":"text"},{"code":"activeAuthenticationChallenge","type":"codeVoice"},{"text":" is not set.","type":"text"}]}],"name":"activeAuthenticationChallenge"}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(password:activeAuthenticationChallenge:)\/title","value":"readWithPassword:activeAuthenticationChallenge:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithPassword:activeAuthenticationChallenge:"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader~1read(password:activeAuthenticationChallenge:)\/fragments","op":"replace"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"},{"value":"DOTNTravelDocumentReaderPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","op":"replace"},{"value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/navigatorTitle","op":"replace"}]}]}