{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","metadata":{"externalID":"s:11DotDocument11PlaceholderC6HiddenC4hashSivp","title":"hash","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden\/hash","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/placeholder\/hidden\/hash"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/Placeholder/Hidden/hash":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden\/hash","title":"hash","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/placeholder\/hidden\/hash","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Placeholder":{"kind":"symbol","abstract":[{"text":"Placeholder.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","url":"\/documentation\/dotdocument\/placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","title":"Placeholder"},"doc://DotDocument/documentation/DotDocument/Placeholder/Hidden":{"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/placeholder\/hidden","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"abstract":[{"text":"Hidden placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Hidden","role":"symbol","title":"Placeholder.Hidden","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTDPlaceholder","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDPlaceholder"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments","op":"replace"},{"value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}