{"kind":"symbol","metadata":{"title":"detection","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(py)detection","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"detection"}],"fragments":[{"kind":"identifier","text":"detection"}],"role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules\/detection"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"abstract":[{"text":"Palm library module configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules","type":"topic","title":"DotPalmLibraryConfigurationModules","url":"\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"abstract":[{"text":"Palm detection module configuration.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","type":"topic","title":"DotPalmDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfigurationModules/detection":{"fragments":[{"kind":"identifier","text":"detection"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules\/detection","type":"topic","title":"detection","url":"\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules\/detection","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}]}]}