{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(multiRangeLivenessViewControllerViewWillAppear:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessViewControllerViewWillAppear:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"multiRangeLivenessViewControllerViewWillAppear:","kind":"identifier"}],"title":"multiRangeLivenessViewControllerViewWillAppear(_:)"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillAppear(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwillappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwillappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate","type":"topic","title":"MultiRangeLivenessViewControllerDelegate","navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate","abstract":[{"text":"Implement this delegate to handle the Multi-Range Liveness events.","type":"text"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillAppear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillAppear:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwillappear(_:)","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillAppear(_:)","type":"topic","abstract":[],"role":"symbol","title":"multiRangeLivenessViewControllerViewWillAppear(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","type":"topic","title":"MultiRangeLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"multiRangeLivenessViewControllerViewWillAppear:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillAppear:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillAppear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"DOTFMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/title","value":"DOTFMultiRangeLivenessViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewControllerDelegate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillAppear(_:)\/title","value":"multiRangeLivenessViewControllerViewWillAppear:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillAppear:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}