{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate"]]},"metadata":{"symbolKind":"method","role":"symbol","title":"multiRangeLivenessViewControllerNoCameraPermission(_:)","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"multiRangeLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessViewControllerNoCameraPermission:","roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(multiRangeLivenessViewControllerNoCameraPermission:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","title":"MultiRangeLivenessViewControllerDelegate","kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate","navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"type":"topic","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"symbol","title":"MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerNoCameraPermission(_:)":{"kind":"symbol","title":"multiRangeLivenessViewControllerNoCameraPermission(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)","navigatorTitle":[{"text":"multiRangeLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"multiRangeLivenessViewControllerNoCameraPermission:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"multiRangeLivenessViewControllerNoCameraPermission:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"DOTFMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFMultiRangeLivenessViewControllerDelegate"},{"value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFMultiRangeLivenessViewController"},{"value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments"},{"value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/title","value":"multiRangeLivenessViewControllerNoCameraPermission:"},{"value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/fragments"}]}]}