{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(multiRangeLivenessViewController:processed:) ","kind":"text"},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"multiRangeLivenessViewController"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:processed:)","interfaceLanguage":"swift"},"metadata":{"title":"multiRangeLivenessViewController(_:processed:)","externalID":"c:@M@DotFaceCore@objc(pl)DOTFMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessViewController:processed:","navigatorTitle":[{"text":"multiRangeLivenessViewController:processed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","kind":"typeIdentifier","text":"MultiRangeLivenessViewController"},{"kind":"text","text":", "},{"text":"processed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}]},"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)"]},{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection","abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureDetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate":{"role":"symbol","title":"MultiRangeLivenessViewControllerDelegate","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate","navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"abstract":[{"text":"Implement this delegate to handle the Multi-Range Liveness events.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"UI component for capturing images suitable for Multi-Range Liveness evaluation.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","title":"MultiRangeLivenessViewController","navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewController(_:processed:)":{"kind":"symbol","type":"topic","title":"multiRangeLivenessViewController(_:processed:)","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessViewController:processed:"}],"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:processed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:processed:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.17.0","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"multiRangeLivenessViewController:processed:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessViewController:processed:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"multiRangeLivenessViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","text":"DOTFMultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"processed:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","text":"DOTFFaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"DOTFFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"value":"DOTFMultiRangeLivenessViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/title"},{"value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}]},{"value":"multiRangeLivenessViewController:processed:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:processed:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"multiRangeLivenessViewController:processed:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:processed:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}