{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","title":"multiRangeLivenessViewControllerViewDidLoad(_:)","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","kind":"typeIdentifier","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"multiRangeLivenessViewControllerViewDidLoad:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMultiRangeLivenessViewControllerDelegate(im)multiRangeLivenessViewControllerViewDidLoad:"},"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidload(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLoad(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(multiRangeLivenessViewControllerViewDidLoad:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"text":"MultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidLoad(_:)":{"title":"multiRangeLivenessViewControllerViewDidLoad(_:)","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidload(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"MultiRangeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLoad(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad:"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"title":"MultiRangeLivenessViewController","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontrollerdelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"title":"MultiRangeLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewControllerDelegate","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"multiRangeLivenessViewControllerViewDidLoad:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","kind":"typeIdentifier","text":"DOTFMultiRangeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLoad(_:)\/title","value":"multiRangeLivenessViewControllerViewDidLoad:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLoad(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidLoad:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/title","value":"DOTFMultiRangeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}