{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","text":"CameraPreviewScaleType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV22cameraPreviewScaleType0A6Camera0nklM0OvpZ","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"title":"cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"}],"roleHeading":"Type Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/Defaults":{"title":"FaceAutoCaptureViewController.Configuration.Defaults","kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.6.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"title":"CameraPreviewScaleType"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/Defaults/cameraPreviewScaleType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/cameraPreviewScaleType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/camerapreviewscaletype","abstract":[],"role":"symbol","title":"cameraPreviewScaleType"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace","value":"DOTFLFaceAutoCaptureViewController"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace"}]}]}