{"abstract":[{"text":"Stop the palm auto capture process.","type":"text"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"stop()","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController(im)stop","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"stop","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/stop()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/stop()"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/stop()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"title":"BasePalmAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/stop()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/stop()","navigatorTitle":[{"text":"stop","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"abstract":[{"type":"text","text":"Stop the palm auto capture process."}],"role":"symbol","title":"stop()","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/stop()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"stop","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"stop","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPBasePalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"stop","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1stop()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stop","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController~1stop()\/fragments"}]}]}