{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/defaultthreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/defaultthreshold"]}],"metadata":{"symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSharpnessTooLowValidator(cpy)defaultThreshold","navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"role":"symbol","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"title":"defaultThreshold","modules":[{"name":"DotFaceLite"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Default threshold value.","type":"text"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/defaultThreshold","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/defaultThreshold":{"kind":"symbol","abstract":[{"type":"text","text":"Default threshold value."}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"title":"defaultThreshold","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/defaultThreshold","type":"topic","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/defaultthreshold","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","title":"FaceAutoCaptureController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 8.6.0","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"title":"SharpnessTooLowValidator","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"defaultThreshold","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"value":[{"kind":"identifier","text":"defaultThreshold"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1defaultThreshold\/fragments","op":"replace"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}]}]}]}