{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","roleHeading":"Type Property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentOutOfBoundsValidator(cpy)defaultMinCornerDistanceToImageShorterSideRatioThreshold","symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator"]]},"abstract":[{"text":"Default threshold is 0.03.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold","abstract":[{"type":"text","text":"Default threshold is 0.03."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"type":"topic","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","type":"topic","title":"DocumentOutOfBoundsValidator","abstract":[{"text":"Validate if the detected document is within the bounds of the image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","value":"DOTDDocumentOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}