{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator"]]},"sections":[],"metadata":{"title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentOutOfBoundsValidator(im)initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","symbolKind":"init","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)"},"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"title":"DocumentOutOfBoundsValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:)":{"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","role":"symbol","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}]},{"op":"replace","value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/navigatorTitle"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/fragments"}]}]}