{"abstract":[{"type":"text","text":"Current minimal distance between detected document corner and image edge to image shorter side ratio threshold."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold"]}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentOutOfBoundsValidator(py)minCornerDistanceToImageShorterSideRatioThreshold","title":"minCornerDistanceToImageShorterSideRatioThreshold","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","role":"symbol","type":"topic","title":"DocumentOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentoutofboundsvalidator"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator/minCornerDistanceToImageShorterSideRatioThreshold":{"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"type":"topic","abstract":[{"type":"text","text":"Current minimal distance between detected document corner and image edge to image shorter side ratio threshold."}],"kind":"symbol","title":"minCornerDistanceToImageShorterSideRatioThreshold"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"minCornerDistanceToImageShorterSideRatioThreshold","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments"},{"value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/navigatorTitle"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"},{"value":"minCornerDistanceToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/title"},{"value":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/fragments"}]}]}