{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"init(rawValue:)","modules":[{"name":"DotDocument"}],"externalID":"s:18DotDocumentCommons06TravelB4TypeO8rawValueACSgSi_tcfc","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/init(rawvalue:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/init(rawValue:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"kind":"symbol","title":"TravelDocumentType","url":"\/documentation\/dotdocument\/traveldocumenttype","role":"symbol","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/init(rawValue:)","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace","value":"DOTTravelDocumentType"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentType"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}]}]}