{"metadata":{"externalID":"s:14DotFingersCore11PlaceholderC7VisibleC4hashSivp","symbolKind":"property","roleHeading":"Instance Property","title":"hash","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/hash","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholder\/visible\/hash"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/dotfingerscore\/placeholder\/visible\/hash","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/hash","title":"hash","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotfingerscore\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible","title":"Placeholder.Visible","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/placeholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title","value":"DOTFGPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments","value":[{"text":"DOTFGPlaceholder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle","value":[{"text":"DOTFGPlaceholder","kind":"identifier"}]}]}]}