{"metadata":{"externalID":"s:14DotFingersCore11PlaceholderC7VisibleC7isEqualySbypSgF","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFingersCore"}],"title":"isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/isEqual(_:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholder\/visible\/isequal(_:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotfingerscore\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible","title":"Placeholder.Visible","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfingerscore\/placeholder\/visible\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/placeholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGPlaceholder","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle"}]}]}