{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sharpness"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/init(brightness:sharpness:)","interfaceLanguage":"swift"},"metadata":{"title":"init(brightness:sharpness:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sharpness","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBrightness:sharpness:"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality(im)initWithBrightness:sharpness:","role":"symbol","roleHeading":"Initializer"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmimagequality\/init(brightness:sharpness:)"]},{"paths":["\/documentation\/dotpalmcore\/palmimagequality\/init(brightness:sharpness:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality/init(brightness:sharpness:)":{"role":"symbol","navigatorTitle":[{"text":"initWithBrightness:sharpness:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"url":"\/documentation\/dotpalmcore\/palmimagequality\/init(brightness:sharpness:)","abstract":[],"kind":"symbol","title":"init(brightness:sharpness:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality\/init(brightness:sharpness:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmImageQuality":{"role":"symbol","navigatorTitle":[{"text":"PalmImageQuality","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmImageQuality"}],"abstract":[{"text":"Palm image quality.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmimagequality","kind":"symbol","title":"PalmImageQuality","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmImageQuality","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithBrightness:sharpness:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithBrightness:sharpness:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBrightness:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1init(brightness:sharpness:)\/title","value":"initWithBrightness:sharpness:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBrightness:sharpness:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality~1init(brightness:sharpness:)\/fragments"},{"value":"DOTPPalmImageQuality","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/title"},{"value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/fragments"},{"value":[{"text":"DOTPPalmImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmImageQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}