{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPreview:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DOTDDocumentAutoCapturePreview"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"preview"},{"kind":"text","text":";"}]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/initWithPreview:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/initwithpreview:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"initWithPreview:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:"}],"symbolKind":"method","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateIdle(im)initWithPreview:","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","title":"DocumentAutoCapturePreview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePreview"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturepreview"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"text":"This state is active either:","type":"text"}],"role":"symbol","title":"DOTDDocumentAutoCaptureUiStateIdle","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiStateIdle"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/initWithPreview:":{"kind":"symbol","abstract":[],"title":"initWithPreview:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/initwithpreview:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/initWithPreview:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","value":"DOTDDocumentAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}