{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/preview","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/preview"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"preview","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureUiStateIdle(py)preview","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"preview","fragments":[{"kind":"identifier","text":"preview"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DOTDDocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Preview information.","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"title":"DOTDDocumentAutoCaptureUiStateIdle","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle","fragments":[{"text":"DOTDDocumentAutoCaptureUiStateIdle","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"title":"DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","kind":"symbol","role":"symbol","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureUiStateIdle/preview":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureuistateidle\/preview","role":"symbol","fragments":[{"kind":"identifier","text":"preview"}],"title":"preview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureUiStateIdle\/preview","abstract":[{"text":"Preview information.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title","value":"DOTDDocumentAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}