{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/initialize(configuration:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"]]},"sections":[],"abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/initialize(configuration:)"]},{"paths":["\/documentation\/dotfacelite\/dotsdk\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}]},{"parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}],"type":"paragraph"},{"style":"note","type":"aside","name":"Throws","content":[{"inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" fails to decode provided license or if any "},{"code":"DotLibrary","type":"codeVoice"},{"text":" fails to initialize.","type":"text"}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","title":"initialize(configuration:)","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)initializeWithConfiguration:error:","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"symbolKind":"method","modules":[{"name":"DotFaceLite"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/initialize(configuration:)":{"url":"\/documentation\/dotfacelite\/dotsdk\/initialize(configuration:)","type":"topic","kind":"symbol","title":"initialize(configuration:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"abstract":[{"text":"Initialize ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" with configuration.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration":{"url":"\/documentation\/dotfacelite\/dotsdkconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}],"title":"DotSdkConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","title":"DotSdk","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","kind":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithConfiguration:error:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithConfiguration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"value":"initializeWithConfiguration:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1initialize(configuration:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1initialize(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}