{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/versionName","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/versionname"]},{"paths":["\/documentation\/dotfacelite\/dotsdk\/versionname"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"codeVoice","code":"DotSdk"},{"text":" version.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotSdk(py)versionName","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"versionName"}],"modules":[{"name":"DotFaceLite"}],"title":"versionName","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"url":"\/documentation\/dotfacelite\/dotsdk","role":"symbol","title":"DotSdk","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","kind":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/versionName":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/versionName","role":"symbol","title":"versionName","navigatorTitle":[{"kind":"identifier","text":"versionName"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotSdk"},{"text":" version.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotsdk\/versionname"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"versionName","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"versionName"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"versionName"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdk"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1versionName\/title","value":"versionName","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk~1versionName\/fragments","value":[{"text":"versionName","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}