{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/isEqual(_:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debugevent\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debugevent\/isequal(_:)"]}],"metadata":{"symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugEvent(im)isEqual:","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Method","title":"isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/DebugEvent/isEqual(_:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent\/isEqual(_:)","role":"symbol","abstract":[],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotnfc\/debugevent\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)"},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugEvent"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"DebugEvent","kind":"identifier"}],"title":"DebugEvent","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","role":"symbol","url":"\/documentation\/dotnfc\/debugevent"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"isEqual:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title","op":"replace","value":"DOTNDebugEvent"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","value":[{"text":"DOTNDebugEvent","kind":"identifier"}]}]}]}