{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/init(left:top:right:bottom:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/bottom","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/cgRect","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/height","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/left","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/origin","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/right","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/top","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/width","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/widthToHeightRatio"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/from(cgRect:)"],"generated":true,"anchor":"Type-Methods"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTRectangleInt) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt","symbolKind":"class","roleHeading":"Class","title":"RectangleInt"},"variants":[{"paths":["\/documentation\/dotfacelite\/rectangleint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/rectangleint"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/right":{"url":"\/documentation\/dotfacelite\/rectangleint\/right","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/right","type":"topic","abstract":[{"type":"text","text":"Right edge."}],"navigatorTitle":[{"kind":"identifier","text":"right"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","title":"right","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/hash":{"url":"\/documentation\/dotfacelite\/rectangleint\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/hash","type":"topic","title":"hash","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/height":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"height","url":"\/documentation\/dotfacelite\/rectangleint\/height","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/height","navigatorTitle":[{"kind":"identifier","text":"height"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/from(cgRect:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/rectangleint\/from(cgrect:)","role":"symbol","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt","kind":"typeIdentifier"}],"type":"topic","title":"from(cgRect:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/from(cgRect:)"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/widthToHeightRatio":{"url":"\/documentation\/dotfacelite\/rectangleint\/widthtoheightratio","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/widthToHeightRatio","kind":"symbol","navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"widthToHeightRatio"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/width":{"title":"width","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/width","url":"\/documentation\/dotfacelite\/rectangleint\/width","navigatorTitle":[{"kind":"identifier","text":"width"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/origin":{"type":"topic","title":"origin","url":"\/documentation\/dotfacelite\/rectangleint\/origin","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/origin","navigatorTitle":[{"kind":"identifier","text":"origin"}],"kind":"symbol","abstract":[],"role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/init(left:top:right:bottom:)":{"abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"title":"init(left:top:right:bottom:)","navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/rectangleint\/init(left:top:right:bottom:)","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/init(left:top:right:bottom:)"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/bottom":{"type":"topic","title":"bottom","url":"\/documentation\/dotfacelite\/rectangleint\/bottom","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/bottom","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"kind":"symbol","abstract":[{"type":"text","text":"Bottom edge."}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/cgRect":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/cgRect","abstract":[],"url":"\/documentation\/dotfacelite\/rectangleint\/cgrect","type":"topic","role":"symbol","kind":"symbol","title":"cgRect","navigatorTitle":[{"text":"cgRect","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/top":{"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"top","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/top","url":"\/documentation\/dotfacelite\/rectangleint\/top","abstract":[{"text":"Top edge.","type":"text"}],"navigatorTitle":[{"text":"top","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/description":{"url":"\/documentation\/dotfacelite\/rectangleint\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","type":"topic","kind":"symbol","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/left":{"url":"\/documentation\/dotfacelite\/rectangleint\/left","type":"topic","role":"symbol","kind":"symbol","title":"left","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[{"text":"Left edge.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/left","navigatorTitle":[{"kind":"identifier","text":"left"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/rectangleint","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/RectangleInt/isEqual(_:)":{"title":"isEqual(_:)","url":"\/documentation\/dotfacelite\/rectangleint\/isequal(_:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/isEqual(_:)"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/bottom","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/cgRect","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/height","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/left","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/origin","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/right","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/top","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/width","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/widthToHeightRatio"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleInt\/from(cgRect:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTRectangleInt"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1right\/title","value":"right"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1right\/fragments","value":[{"kind":"identifier","text":"right"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1height\/fragments","value":[{"text":"height","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1from(cgRect:)\/title","value":"fromCgRect:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1from(cgRect:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1widthToHeightRatio\/title","value":"widthToHeightRatio"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1widthToHeightRatio\/fragments","value":[{"text":"widthToHeightRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1width\/title","value":"width"},{"value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1width\/fragments","op":"replace"},{"value":"origin","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1origin\/title","op":"replace"},{"value":[{"kind":"identifier","text":"origin"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1origin\/fragments","op":"replace"},{"value":"initWithLeft:top:right:bottom:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1init(left:top:right:bottom:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1init(left:top:right:bottom:)\/fragments","op":"replace"},{"value":"bottom","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1bottom\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bottom"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1bottom\/fragments","op":"replace"},{"value":"cgRect","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1cgRect\/title","op":"replace"},{"value":[{"text":"cgRect","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1cgRect\/fragments","op":"replace"},{"value":"top","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1top\/title","op":"replace"},{"value":[{"kind":"identifier","text":"top"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1top\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1description\/fragments","op":"replace"},{"value":"left","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1left\/title","op":"replace"},{"value":[{"text":"left","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1left\/fragments","op":"replace"},{"value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/fragments","op":"replace"},{"value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt\/navigatorTitle","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleInt~1isEqual(_:)\/fragments","op":"replace"}]}]}