{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]},{"paths":["\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCiImage:ciContext:","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":") -> "},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Type Method","title":"createBgraRawImage(ciImage:ciContext:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}]}]},{"name":"ciContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","url":"\/documentation\/dotdocument\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"createBgraRawImage(ciImage:ciContext:)"},"doc://DotDocument/documentation/DotDocument/Image":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"symbol","title":"Image","type":"topic","url":"\/documentation\/dotdocument\/image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}]},"doc://DotDocument/documentation/DotDocument/ImageFactory":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFactory","kind":"symbol","title":"ImageFactory","url":"\/documentation\/dotdocument\/imagefactory","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createBgraRawImageWithCiImage:ciContext:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createBgraRawImageWithCiImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ciImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"ciContext","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"createBgraRawImageWithCiImage:ciContext:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","op":"replace"},{"op":"replace","value":"DOTImageFactory","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFactory\/navigatorTitle"}]}]}