{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/init(machineReadableZone:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/init(machinereadablezone:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/init(machinereadablezone:)"]}],"metadata":{"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"},{"kind":"text","text":")"}],"title":"init(machineReadableZone:)","navigatorTitle":[{"text":"initWithMachineReadableZone:","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNMachineReadableZoneInformation(im)initWithMachineReadableZone:"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation":{"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZoneInformation","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZoneInformation","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation","title":"MachineReadableZoneInformation","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotnfc\/machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","title":"MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/MachineReadableZoneInformation/init(machineReadableZone:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithMachineReadableZone:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/init(machineReadableZone:)","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/init(machinereadablezone:)","role":"symbol","title":"init(machineReadableZone:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithMachineReadableZone:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMachineReadableZone:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMachineReadableZone:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"DOTMachineReadableZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"machineReadableZone"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTNMachineReadableZoneInformation","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/navigatorTitle","value":[{"text":"DOTNMachineReadableZoneInformation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title","value":"DOTMachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/navigatorTitle","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1init(machineReadableZone:)\/title","value":"initWithMachineReadableZone:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1init(machineReadableZone:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMachineReadableZone:","kind":"identifier"}],"op":"replace"}]}]}