{"abstract":[{"text":"Left eye center.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeCenter"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)leftEyeCenter","title":"leftEyeCenter","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"leftEyeCenter","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"leftEyeCenter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/lefteyecenter"]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/lefteyecenter"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","title":"FaceKeypoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face Keypoint"}],"url":"\/documentation\/dotfacecore\/facekeypoint"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/leftEyeCenter":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/leftEyeCenter","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"leftEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"FaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"leftEyeCenter","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facekeypoints\/lefteyecenter","type":"topic","title":"leftEyeCenter","kind":"symbol","abstract":[{"type":"text","text":"Left eye center."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","role":"symbol","type":"topic","title":"FaceKeypoints","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"leftEyeCenter","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"leftEyeCenter","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","text":"DOTFFaceKeypoint"},{"kind":"text","text":" * "},{"kind":"identifier","text":"leftEyeCenter"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","op":"replace","value":"DOTFFaceKeypoint"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeCenter\/title","value":"leftEyeCenter"},{"value":[{"text":"leftEyeCenter","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1leftEyeCenter\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","value":"DOTFFaceKeypoints"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/navigatorTitle","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}