{"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","title":"minConfidence","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC13minConfidenceAA13WrappedDoubleCSgvp","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidence"},{"text":": ","kind":"text"},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/WrappedDouble"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minConfidence","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Minimal valid confidence of the detected palm.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low confidence."},{"text":" ","type":"text"},{"type":"text","text":"Vaue 1.0 represents high confidence."}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minconfidence"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"type":"topic","title":"PalmAutoCaptureViewController.Configuration","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/WrappedDouble":{"type":"topic","url":"\/documentation\/dotpalmcore\/wrappeddouble","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/WrappedDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value for Objective-C support.","type":"text"}],"title":"WrappedDouble"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/minConfidence":{"kind":"symbol","role":"symbol","title":"minConfidence","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minconfidence","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minConfidence","abstract":[{"type":"text","text":"Minimal valid confidence of the detected palm."},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents low confidence."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high confidence."}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","kind":"symbol","title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}