{"seeAlsoSections":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"title":"DotFaceLibrary","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}]},"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"topicSections":[{"title":"Configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"]},{"title":"Delegate","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate"]},{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/Result"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/isInitialized","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/licenseId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/setDelegate(_:queue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/shared","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/versionName"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacelibrary"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary"}],"abstract":[{"type":"text","text":"Shared singleton instance."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shared"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/shared"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Localization":{"role":"symbol","title":"Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfacecore\/localization"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/setDelegate(_:queue:)":{"role":"symbol","title":"setDelegate(_:queue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceLibraryDelegate","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceLibraryDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set delegate and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":" on which you want to recieve the delegate callbacks. "},{"type":"codeVoice","code":"DotFaceLibrary"},{"type":"text","text":" will hold weak reference to "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"queue"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/setDelegate(_:queue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setDelegate:queue:"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/setdelegate(_:queue:)"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/isInitialized":{"role":"symbol","title":"isInitialized","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Flag describing initialization state of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."},{"type":"text","text":" "},{"type":"text","text":"It is safe to access this property only after you have received the delegate callback notifying you that the initialization\/deinitialization process has finished."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/isInitialized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isInitialized"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/isinitialized"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/deinitialize()":{"role":"symbol","title":"deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"This method will deinitialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework and free up allocated memory asynchronously. This method will call delegate callback after it has finished."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/deinitialize()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deinitialize"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/deinitialize()"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","title":"DotFaceLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/licenseId":{"role":"symbol","title":"licenseId","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"License ID used for generating license file."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/licenseId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"licenseId"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/licenseid"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/Result":{"role":"symbol","title":"DotFaceLibrary.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the initialization and deinitialization of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/result"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryDelegate":{"role":"symbol","title":"DotFaceLibraryDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle initialization and deinitialization events of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}],"url":"\/documentation\/dotfacecore\/dotfacelibrarydelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Logger":{"role":"symbol","title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotfacecore\/logger"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/initialize(configuration:)":{"role":"symbol","title":"initialize(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method will initialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework asynchronously and it will call delegate callback after it has finished."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/initialize(configuration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/initialize(configuration:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/versionName":{"role":"symbol","title":"versionName","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Version of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/versionName","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"versionName"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/versionname"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework will be initialized."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceLibrary"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"]},{"title":"Delegate","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibraryDelegate"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/isInitialized","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/licenseId"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/setDelegate(_:queue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/shared","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/versionName"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Logger","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Localization"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1shared\/title","value":"shared"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization\/title","value":"DOTFLocalization"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTFLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1setDelegate(_:queue:)\/title","value":"setDelegate:queue:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1setDelegate(_:queue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDelegate:queue:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1isInitialized\/title","value":"isInitialized"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1isInitialized\/fragments","value":[{"kind":"identifier","text":"isInitialized"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1deinitialize()\/title","value":"deinitialize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitialize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1licenseId\/title","value":"licenseId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1licenseId\/fragments","value":[{"kind":"identifier","text":"licenseId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/title","value":"DotFaceLibraryDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryDelegate\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Logger\/title","value":"DOTFLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTFLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1initialize(configuration:)\/title","value":"initializeWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1initialize(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1versionName\/title","value":"versionName"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1versionName\/fragments","value":[{"kind":"identifier","text":"versionName"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}