{"metadata":{"externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"title":"barcode","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","title":"barcode","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","title":"DotDocumentBarcodeModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments"},{"value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"value":"DotDocumentBarcodeModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/title"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}