{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAeA0ac13BarcodeModuleE0CSg_tcfc","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"title":"init(barcode:)","role":"symbol","roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","title":"init(barcode:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","title":"DotDocumentBarcodeModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]}]}]}