{"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"article","topicSections":[{"anchor":"Operators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/!=(_:_:)"],"generated":true,"title":"Operators"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/Equatable-Implementations"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/!=(_:_:)":{"title":"!=(_:_:)","url":"\/documentation\/dotdocument\/traveldocumenttype\/!=(_:_:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/!=(_:_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"title":"TravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"role":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}]}},"variantOverrides":[{"patch":[{"value":"DOTTravelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments"},{"value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/navigatorTitle"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}