{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"extendedModule":"Swift","role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotDocumentCommons@E@DOTTravelDocumentType","roleHeading":"Instance Property","symbolKind":"property","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"DotDocument"}]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hashValue","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations"]]},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"title":"TravelDocumentType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"role":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/dotdocument\/traveldocumenttype\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/hashValue":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotdocument\/traveldocumenttype\/hashvalue","role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hashValue","title":"hashValue"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/navigatorTitle","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}