{"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"RawRepresentable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/RawRepresentable-Implementations"},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hashValue"],"generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hash(into:)"],"generated":true}],"sections":[],"kind":"article","references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.8.0"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/hashValue":{"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype\/hashvalue","title":"hashValue","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hashValue"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"title":"TravelDocumentType","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Travel document type according to ICAO Doc 9303 specification.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttype"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/hash(into:)","abstract":[],"url":"\/documentation\/dotdocument\/traveldocumenttype\/hash(into:)","role":"symbol","title":"hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzreader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"role":"symbol","title":"MrzReader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTTravelDocumentType","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"}]}]}