{"metadata":{"role":"symbol","title":"widthToHeightRatio","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"externalID":"s:18DotDocumentCommons06TravelB4TypeO18widthToHeightRatioSdvp"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/widthtoheightratio"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/widthToHeightRatio","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"kind":"symbol","title":"MrzReader"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotDocument","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/widthToHeightRatio":{"role":"symbol","title":"widthToHeightRatio","url":"\/documentation\/dotdocument\/traveldocumenttype\/widthtoheightratio","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/widthToHeightRatio","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"type":"topic","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"url":"\/documentation\/dotdocument\/traveldocumenttype","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"kind":"symbol","title":"TravelDocumentType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments"}]}]}