{"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"metadata":{"required":true,"roleHeading":"Instance Method","navigatorTitle":[{"text":"magnifEyeLivenessViewController:processed:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"magnifEyeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","kind":"typeIdentifier","text":"MagnifEyeLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessViewController:processed:","symbolKind":"method","title":"magnifEyeLivenessViewController(_:processed:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:processed:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(magnifEyeLivenessViewController:processed:) "},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewController"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"detection"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)"]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"title":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"kind":"symbol","type":"topic","abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewController(_:processed:)":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:processed:)","role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessViewController:processed:"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:processed:)","title":"magnifEyeLivenessViewController(_:processed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewController"},{"kind":"text","text":"("},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"processed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","kind":"typeIdentifier"},{"kind":"text","text":")"}],"required":true,"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the MagnifEye liveness events."}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewControllerDelegate","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontrollerdelegate","title":"MagnifEyeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"magnifEyeLivenessViewController:processed:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"magnifEyeLivenessViewController:processed:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"magnifEyeLivenessViewController:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessViewController","text":"DOTFMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"processed:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"DOTFFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"value":"DOTFFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:processed:)\/title","op":"replace","value":"magnifEyeLivenessViewController:processed:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"magnifEyeLivenessViewController:processed:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/title","value":"DOTFMagnifEyeLivenessViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewControllerDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}