{"abstract":[{"text":"The library identifier.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/id"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"text":"DotLibraryId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/id","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"title":"id","externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(py)id","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotLibraryId":{"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","title":"DotLibraryId","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/id":{"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/id","title":"id","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/id","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"The library identifier."}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibrary"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" library initialization."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotDocumentLibrary","kind":"identifier"}],"title":"DotDocumentLibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"id","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"id","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibraryId\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title","op":"replace","value":"DotDocumentLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibrary"}]}]}]}