{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLFaceAutoCaptureFrameParameters) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Information from the detection process about the detected face."}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","title":"FaceAutoCaptureFrameParameters","role":"symbol","symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"modules":[{"name":"DotFaceLite"}]},"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],"generated":true,"title":"Face auto capture process"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(detectionAreaImageSize:face:deviceTiltAngles:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/deviceTiltAngles","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/face"]}],"references":{"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DetectionPosition":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/detectionposition","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","title":"DetectionPosition","kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/description":{"title":"description","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/description","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"title":"FaceAutoCaptureDetection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/deviceTiltAngles":{"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/devicetiltangles","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"deviceTiltAngles","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"TiltAngles"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/deviceTiltAngles","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"deviceTiltAngles","kind":"identifier"}],"title":"deviceTiltAngles"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/face":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/face","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/face","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face"},{"text":"?","kind":"text"}],"title":"face","navigatorTitle":[{"text":"face","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection result."}]},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"title":"FaceAutoCaptureFrameParameters","navigatorTitle":[{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected face."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/init(detectionAreaImageSize:face:deviceTiltAngles:)":{"type":"topic","title":"init(detectionAreaImageSize:face:deviceTiltAngles:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(detectionAreaImageSize:face:deviceTiltAngles:)","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(detectionareaimagesize:face:devicetiltangles:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"detectionAreaImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"kind":"text","text":"."},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"TiltAngles"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:"}]},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/detectionAreaImageSize":{"type":"topic","title":"detectionAreaImageSize","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/detectionAreaImageSize","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/detectionareaimagesize","abstract":[{"type":"text","text":"Image size of the detection area."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"text":"ImageSize","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"detectionAreaImageSize","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureResult":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","title":"FaceAutoCaptureResult"},"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLFaceAutoCaptureFrameParameters"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/deviceTiltAngles","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/face"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(detectionAreaImageSize:face:deviceTiltAngles:)"]}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DetectionPosition","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],"generated":true,"title":"Face auto capture process"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDetectionPosition","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DetectionPosition\/fragments","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1description\/fragments"},{"value":"DOTFLFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1deviceTiltAngles\/title","value":"deviceTiltAngles"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1deviceTiltAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"deviceTiltAngles"}]},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","value":"face","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1face\/title"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1face\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","value":"DOTFLFaceAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(detectionAreaImageSize:face:deviceTiltAngles:)\/title","value":"initWithDetectionAreaImageSize:face:deviceTiltAngles:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(detectionAreaImageSize:face:deviceTiltAngles:)\/fragments"},{"value":"detectionAreaImageSize","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1detectionAreaImageSize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"detectionAreaImageSize"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1detectionAreaImageSize\/fragments"},{"value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}