{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitch"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/tiltangles\/pitch"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/tiltangles\/pitch"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/pitch","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"pitch","kind":"identifier"}],"role":"symbol","symbolKind":"property","title":"pitch","roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTTiltAngles(py)pitch"},"sections":[],"abstract":[{"type":"text","text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles/pitch":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"pitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"kind":"symbol","title":"pitch","url":"\/documentation\/dotdocument\/tiltangles\/pitch","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles\/pitch","abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"pitch"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles":{"url":"\/documentation\/dotdocument\/tiltangles","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"type":"topic","title":"TiltAngles","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","role":"collection","abstract":[{"text":"version: 8.2.1","type":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"pitch","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"pitch","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":" "},{"text":"pitch","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"pitch","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1pitch\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles~1pitch\/fragments","value":[{"text":"pitch","kind":"identifier"}],"op":"replace"},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}