{"abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier","text":"DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"query","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"DOTCameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"symbolKind":"method","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"IntervalDouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"type":"topic","fragments":[{"kind":"identifier","text":"DOTFSmileLivenessConfiguration"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","title":"DOTFSmileLivenessConfiguration","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","type":"topic","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"kind":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFSmileLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","type":"topic","title":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"op":"replace"},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}