{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(py)hash","symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/wrappeddouble\/hash"]},{"paths":["\/documentation\/dotfingerscore\/wrappeddouble\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/hash","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappeddouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}]},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/hash":{"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/wrappeddouble\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/hash","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/navigatorTitle"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1hash\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1hash\/fragments"}]}]}