{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/image","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Sample image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier"}]}]}],"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"image","role":"symbol","externalID":"s:11DotDocument0B21AutoCaptureControllerC6SampleC5image0A4Core5ImageCvp","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/image"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample":{"type":"topic","title":"DocumentAutoCaptureController.Sample","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sample"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Sample"}],"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample/image":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/image","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/image","title":"image","kind":"symbol","abstract":[{"type":"text","text":"Sample image."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Image":{"url":"\/documentation\/dotdocument\/image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","title":"Image","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"}]}]}