{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/init(bgraRawImage:timestampMillis:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/init(bgrarawimage:timestampmillis:)"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument0B21AutoCaptureControllerC6SampleC12bgraRawImage15timestampMillisAE0A4Core04BgrahI0C_Sitcfc","symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(bgraRawImage:timestampMillis:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample/init(bgraRawImage:timestampMillis:)":{"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/init(bgrarawimage:timestampmillis:)","title":"init(bgraRawImage:timestampMillis:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/init(bgraRawImage:timestampMillis:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"text":"timestampMillis","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample":{"role":"symbol","abstract":[{"text":"The data sample captured at specific time which serves as an input for the document auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Sample"}],"title":"DocumentAutoCaptureController.Sample","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Sample"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"url":"\/documentation\/dotdocument\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}