{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/init(value:)"},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(im)initWithValue:","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"role":"symbol","symbolKind":"init","title":"init(value:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/wrappedfloat\/init(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/wrappedfloat\/init(value:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/WrappedFloat/init(value:)":{"url":"\/documentation\/dotnfc\/wrappedfloat\/init(value:)","type":"topic","title":"init(value:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat\/init(value:)","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/WrappedFloat":{"kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedFloat","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"url":"\/documentation\/dotnfc\/wrappedfloat","type":"topic","role":"symbol","title":"WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithValue:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat~1init(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}