{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/hash"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)hash","title":"hash","modules":[{"name":"DotFaceLite"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/corners\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/corners\/hash"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Corners":{"abstract":[{"type":"text","text":"Four detected corners in an image."}],"title":"Corners","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotfacelite\/corners"},"doc://DotFaceLite/documentation/DotFaceLite/Corners/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Corners\/hash","url":"\/documentation\/dotfacelite\/corners\/hash","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/title","value":"DOTCorners","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Corners~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}