{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td2:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/init(lines:td2:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td2:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithLines:td2:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(lines:td2:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":")"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(im)initWithLines:td2:"},"references":{"doc://DotDocument/documentation/DotDocument/MachineReadableZone/init(lines:td2:)":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone\/init(lines:td2:)","kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone\/init(lines:td2:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLines:td2:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier","text":"Td2MachineReadableZone"},{"kind":"text","text":")"}],"title":"init(lines:td2:)","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"title":"Td2MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"title":"MachineReadableZone","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithLines:td2:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLines:td2:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lines"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","text":"DOTTd2MachineReadableZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"td2"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithLines:td2:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td2:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLines:td2:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone~1init(lines:td2:)\/fragments"},{"value":"DOTTd2MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/navigatorTitle"},{"op":"replace","value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}