{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/init(image:document:content:traveldocumenttype:machinereadablezone:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/init(image:document:content:traveldocumenttype:machinereadablezone:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"text":"Document","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"? = nil, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(image:document:content:travelDocumentType:machineReadableZone:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult(im)initWithImage:document:content:travelDocumentType:machineReadableZone:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithImage:document:content:travelDocumentType:machineReadableZone:","kind":"identifier"}],"title":"init(image:document:content:travelDocumentType:machineReadableZone:)","symbolKind":"init"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult/init(image:document:content:travelDocumentType:machineReadableZone:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?)"}],"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/documentautocaptureresult\/init(image:document:content:traveldocumenttype:machinereadablezone:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(image:document:content:travelDocumentType:machineReadableZone:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:document:content:travelDocumentType:machineReadableZone:"}],"title":"init(image:document:content:travelDocumentType:machineReadableZone:)"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"type":"topic","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"url":"\/documentation\/dotdocument\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","title":"DocumentAutoCaptureResult","url":"\/documentation\/dotdocument\/documentautocaptureresult"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"type":"topic","kind":"symbol","title":"DocumentDetector.Document","url":"\/documentation\/dotdocument\/documentdetector\/document","navigatorTitle":[{"text":"Document","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},"doc://DotDocument/documentation/DotDocument/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"title":"TravelDocumentTypeWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"kind":"symbol","title":"DOTDDocumentDetectorDocument","abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithImage:document:content:travelDocumentType:machineReadableZone:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:document:content:travelDocumentType:machineReadableZone:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"document:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTDDocumentDetectorDocument","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument"},{"text":" *) ","kind":"text"},{"text":"document","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"travelDocumentType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper"},{"text":" *) ","kind":"text"},{"text":"travelDocumentType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"machineReadableZone:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTMachineReadableZone"},{"text":" *) ","kind":"text"},{"text":"machineReadableZone","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(image:document:content:travelDocumentType:machineReadableZone:)\/title","op":"replace","value":"initWithImage:document:content:travelDocumentType:machineReadableZone:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(image:document:content:travelDocumentType:machineReadableZone:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:document:content:travelDocumentType:machineReadableZone:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace","value":"DOTDDocumentAutoCaptureResult"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","op":"replace","value":"DOTImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace","value":"DOTTravelDocumentTypeWrapper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}