{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","text":"RectangleInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"variants":[{"paths":["\/documentation\/dotnfc\/rectangleint\/from(cgrect:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/rectangleint\/from(cgrect:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/from(cgRect:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(cm)fromCgRect:","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"RectangleInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt"}],"role":"symbol","navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}],"roleHeading":"Type Method","title":"from(cgRect:)","extendedModule":"DotCore"},"references":{"doc://DotNfc/documentation/DotNfc/RectangleInt/from(cgRect:)":{"url":"\/documentation\/dotnfc\/rectangleint\/from(cgrect:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/from(cgRect:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"text":"RectangleInt","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt"}],"abstract":[],"title":"from(cgRect:)","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleInt":{"url":"\/documentation\/dotnfc\/rectangleint","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"title":"RectangleInt","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"fromCgRect:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"DOTRectangleInt","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"fromCgRect:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cgRect"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1from(cgRect:)\/title","op":"replace","value":"fromCgRect:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1from(cgRect:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle"}]}]}