{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"title":"right","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(py)right","navigatorTitle":[{"text":"right","kind":"identifier"}],"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}]},"kind":"symbol","abstract":[{"text":"Right edge.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangleint\/right"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangleint\/right"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/right","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/RectangleInt/right":{"navigatorTitle":[{"kind":"identifier","text":"right"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/right","title":"right","abstract":[{"type":"text","text":"Right edge."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","url":"\/documentation\/dotnfc\/rectangleint\/right","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleInt":{"url":"\/documentation\/dotnfc\/rectangleint","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}],"title":"RectangleInt","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"right"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"right","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1right\/title","value":"right"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1right\/fragments","value":[{"kind":"identifier","text":"right"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}]}]}]}