{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"]]},"sections":[],"metadata":{"role":"symbol","title":"td2","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"td2"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(py)td2","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier","text":"Td2MachineReadableZone"},{"kind":"text","text":"?"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezone\/td2"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezone\/td2"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td2"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"td2"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"typeIdentifier","text":"Td2MachineReadableZone"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Parsed MRZ of TD2."}],"references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","url":"\/documentation\/dotnfc\/td2machinereadablezone","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/td2":{"kind":"symbol","role":"symbol","title":"td2","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezone\/td2","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/td2","abstract":[{"type":"text","text":"Parsed MRZ of TD2."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Td2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"td2","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"kind":"symbol","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","title":"MachineReadableZone","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"td2"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"td2"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"typeIdentifier","text":"DOTTd2MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":" * "},{"kind":"identifier","text":"td2"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace","value":"DOTTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td2\/title","value":"td2"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1td2\/fragments","value":[{"kind":"identifier","text":"td2"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]}]}]}