{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"metadata":{"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)nationality","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"nationality"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"title":"nationality"},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/nationality","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/nationality"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/nationality"]}],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.10.0"}]},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/nationality":{"navigatorTitle":[{"text":"nationality","kind":"identifier"}],"type":"topic","title":"nationality","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td2machinereadablezone\/nationality","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/nationality","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","kind":"symbol","title":"Td2MachineReadableZone","url":"\/documentation\/dotnfc\/td2machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc/MrzElement":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/mrzelement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","title":"MrzElement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"nationality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"nationality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","text":"DOTMrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":" * "},{"text":"nationality","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"nationality","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1nationality\/title"},{"value":[{"text":"nationality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1nationality\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","op":"replace","value":"DOTTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments"}]}]}