{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFSegmentCorner) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corner"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/segment\/corner"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s12CaseIterableP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Segment corner position."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corner"}],"title":"Segment.Corner","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"s:11DotFaceCore7SegmentC6CornerO","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"Corner"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/bottomLeft","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/bottomRight","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/topLeft","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/topRight"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/bottomRight":{"role":"symbol","title":"Segment.Corner.bottomRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/bottomRight","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/bottomright"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/bottomLeft":{"role":"symbol","title":"Segment.Corner.bottomLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/bottomLeft","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/bottomleft"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner":{"role":"symbol","title":"Segment.Corner","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corner"}],"abstract":[{"type":"text","text":"Segment corner position."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corner"}],"url":"\/documentation\/dotfacecore\/segment\/corner"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/init(rawvalue:)"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/equatable-implementations"},"doc://com.innovatrics.dot.face.core/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s12CaseIterableP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/topLeft":{"role":"symbol","title":"Segment.Corner.topLeft","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/topLeft","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/topleft"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment":{"role":"symbol","title":"Segment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Segment"}],"abstract":[{"type":"text","text":"Eye gaze liveness segment representing the position on the screen which should be watched by the user for the specified duration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Segment"}],"url":"\/documentation\/dotfacecore\/segment"},"doc://com.innovatrics.dot.face.core/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment/Corner/topRight":{"role":"symbol","title":"Segment.Corner.topRight","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment\/Corner\/topRight","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/segment\/corner\/topright"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/title","value":"DOTFSegment"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/fragments","value":[{"kind":"identifier","text":"DOTFSegment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}