{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary"]]},"abstract":[{"text":"Verify that library is initialized.","type":"text"}],"kind":"symbol","metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary(im)verifyIsActiveAndReturnError:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"verifyIsActive()"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"verifyIsActive","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/verifyisactive()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/verifyisactive()"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibrary","type":"topic","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library initialization."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary","title":"DotFaceLibrary","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/verifyIsActive()":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"verifyIsActive()","url":"\/documentation\/dotfacecore\/dotfacelibrary\/verifyisactive()","type":"topic","abstract":[{"text":"Verify that library is initialized.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/verifyIsActive()"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"verifyIsActiveAndReturnError:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"verifyIsActiveAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibrary"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1verifyIsActive()\/title","value":"verifyIsActiveAndReturnError:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1verifyIsActive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}