{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble\/init(value:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble"]]},"variants":[{"paths":["\/documentation\/dotnfc\/wrappeddouble\/init(value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/wrappeddouble\/init(value:)"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble(im)initWithValue:","navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"role":"symbol","modules":[{"name":"DotNfc"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(value:)"},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/WrappedDouble":{"url":"\/documentation\/dotnfc\/wrappeddouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","title":"WrappedDouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}]},"doc://DotNfc/documentation/DotNfc/WrappedDouble/init(value:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/wrappeddouble\/init(value:)","title":"init(value:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/WrappedDouble\/init(value:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithValue:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithValue:"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","value":"initWithValue:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble~1init(value:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1WrappedDouble~1init(value:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}