{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/nfc"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"text":" identifier.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/nfc"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotlibraryid\/nfc"]}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc"}],"title":"DotLibraryId.nfc","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdNfc","symbolKind":"case","modules":[{"name":"DotNfc"}],"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdNfc"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/DotLibraryId/nfc":{"title":"DotLibraryId.nfc","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"url":"\/documentation\/dotnfc\/dotlibraryid\/nfc","navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/nfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"title":"DotLibraryId","url":"\/documentation\/dotnfc\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotLibraryIdNfc","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryIdNfc"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DotLibraryIdNfc","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1nfc\/title","op":"replace","value":"DotLibraryIdNfc"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1nfc\/fragments","op":"replace","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]}]}]}