{"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCameraConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/cameraconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/cameraconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/facing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/previewScaleType"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isEqual(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"metadata":{"title":"CameraConfiguration","modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","symbolKind":"class"},"references":{"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"title":"init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","url":"\/documentation\/dotfacelite\/cameraconfiguration\/init(facing:previewscaletype:istorchenabled:isvideocaptureenabled:ispreviewvisible:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"facing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"previewScaleType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","url":"\/documentation\/dotfacelite\/cameraconfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/isPreviewVisible":{"title":"isPreviewVisible","url":"\/documentation\/dotfacelite\/cameraconfiguration\/ispreviewvisible","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isPreviewVisible","role":"symbol","type":"topic","navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Use this flag to show\/hide camera preview. Default is "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/description":{"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","url":"\/documentation\/dotfacelite\/cameraconfiguration\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/isTorchEnabled":{"role":"symbol","url":"\/documentation\/dotfacelite\/cameraconfiguration\/istorchenabled","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isTorchEnabled","abstract":[{"type":"text","text":"Use this flag to turn the torch on\/off during the capture process."},{"text":" ","type":"text"},{"text":"Torch will be turned on only if ","type":"text"},{"type":"codeVoice","code":"facing"},{"text":" property is set to ","type":"text"},{"type":"codeVoice","code":".back"},{"text":". Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}],"title":"isTorchEnabled"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/hash":{"role":"symbol","url":"\/documentation\/dotfacelite\/cameraconfiguration\/hash","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/facing":{"role":"symbol","url":"\/documentation\/dotfacelite\/cameraconfiguration\/facing","kind":"symbol","abstract":[{"text":"Front or back camera facing.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/facing","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"facing","kind":"identifier"}],"title":"facing"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/isVideoCaptureEnabled":{"title":"isVideoCaptureEnabled","navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"text":" ","type":"text"},{"text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.","type":"text"},{"text":" ","type":"text"},{"text":"The captured video is included exclusively in the binary content of the result. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isVideoCaptureEnabled","url":"\/documentation\/dotfacelite\/cameraconfiguration\/isvideocaptureenabled","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/previewScaleType":{"role":"symbol","url":"\/documentation\/dotfacelite\/cameraconfiguration\/previewscaletype","kind":"symbol","abstract":[{"text":"Preview scale type. Default is ","type":"text"},{"code":".fit","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/previewScaleType","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"previewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"previewScaleType","kind":"identifier"}],"title":"previewScaleType"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/isEqual(_:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isEqual(_:)","type":"topic","kind":"symbol","role":"symbol","title":"isEqual(_:)","abstract":[],"url":"\/documentation\/dotfacelite\/cameraconfiguration\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/facing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isPreviewVisible","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isTorchEnabled","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isVideoCaptureEnabled","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/previewScaleType"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTCameraConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/title","op":"replace","value":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithFacing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1init(facing:previewScaleType:isTorchEnabled:isVideoCaptureEnabled:isPreviewVisible:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isPreviewVisible\/title","op":"replace","value":"isPreviewVisible"},{"value":[{"text":"isPreviewVisible","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isPreviewVisible\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1description\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isTorchEnabled\/title","op":"replace","value":"isTorchEnabled"},{"value":[{"text":"isTorchEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isTorchEnabled\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1hash\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1facing\/title","op":"replace","value":"facing"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1facing\/fragments","op":"replace","value":[{"kind":"identifier","text":"facing"}]},{"value":"isVideoCaptureEnabled","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isVideoCaptureEnabled\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","op":"replace","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}]},{"op":"replace","value":"previewScaleType","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1previewScaleType\/title"},{"value":[{"kind":"identifier","text":"previewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1previewScaleType\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isEqual(_:)\/fragments"}]}]}