{"metadata":{"title":"DotDocumentBarcodeModuleConfiguration","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"kind":"symbol","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration"},"sections":[],"references":{"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration":{"title":"DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration/init":{"url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration\/init","title":"init","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration\/init","role":"symbol","type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DotDocumentBarcodeModuleConfiguration"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration\/init"],"anchor":"Instance-Methods","generated":true}],"path":"\/topicSections","op":"add"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace","value":"DotDocumentBarcodeModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}