{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacemoduleid\/passiveliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Case","title":"DotFaceModuleId.passiveLiveness","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"passiveLiveness","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"externalID":"c:@M@DotFaceCore@E@DotFaceModuleId@DotFaceModuleIdPassiveLiveness"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/passiveLiveness"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"passiveLiveness"}],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemoduleid","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleId"}],"title":"DotFaceModuleId","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId/passiveLiveness":{"title":"DotFaceModuleId.passiveLiveness","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId\/passiveLiveness","url":"\/documentation\/dotfacecore\/dotfacemoduleid\/passiveliveness","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"passiveLiveness","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1passiveLiveness\/title","op":"replace","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId~1passiveLiveness\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}]}]}]}