{"abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"property","roleHeading":"Type Property","title":"localizationDictionary","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLocalization(cpy)localizationDictionary","platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","beta":false}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You also need to set "},{"code":"useLocalizationDictionary","type":"codeVoice"},{"text":" flag to ","type":"text"},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]}],"name":"Note","style":"note","type":"aside"}],"kind":"content"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/localizationDictionary","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/localization\/localizationdictionary"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/localization\/localizationdictionary"]}],"references":{"doc://DotNfc/documentation/DotNfc/Localization/localizationDictionary":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}],"abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"url":"\/documentation\/dotnfc\/localization\/localizationdictionary","title":"localizationDictionary","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/localizationDictionary","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Localization":{"role":"symbol","title":"Localization","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/localization","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"localizationDictionary"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"localizationDictionary"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" * "},{"text":"localizationDictionary","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"op":"replace","value":[{"kind":"identifier","text":"localizationDictionary"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1localizationDictionary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"text":"DOTNLocalization","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}