{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:challengesequence:isdetectionlayervisible:error:"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","text":"DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"text":" ","kind":"text"},{"text":"camera:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","text":"DOTFFaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLibraryComponent"},{"text":" ","kind":"text"},{"text":"challengeSequence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTWrappedMultiRangeLivenessChallengeItem *>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"challengeSequence"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessConfiguration(im)initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","symbolKind":"method","title":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","navigatorTitle":[{"text":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"title":"CameraConfiguration","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"type":"topic","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"url":"\/documentation\/dotfacecore\/cameraconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","abstract":[{"type":"text","text":"Configuration for face library components."}],"role":"symbol","title":"FaceLibraryComponentConfiguration","type":"topic","navigatorTitle":[{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","url":"\/documentation\/dotfacecore\/commonconfiguration","title":"CommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"type":"text","text":"Common configuration for all components."}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration/initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:":{"abstract":[{"type":"text","text":"Create the Multi-Range Liveness configuration."}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","kind":"identifier"}],"title":"initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","role":"symbol","url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration\/initwithcommon:camera:facelibrarycomponent:challengesequence:isdetectionlayervisible:error:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration\/initWithCommon:camera:faceLibraryComponent:challengeSequence:isDetectionLayerVisible:error:","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMultiRangeLivenessConfiguration":{"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"fragments":[{"text":"DOTFMultiRangeLivenessConfiguration","kind":"identifier"}],"kind":"symbol","title":"DOTFMultiRangeLivenessConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/dotfmultirangelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMultiRangeLivenessConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle"},{"value":"DOTFFaceLibraryComponentConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title"},{"value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle"},{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle"}]}]}