{"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"symbolKind":"property","title":"bottomRight","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)bottomRight","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomRight"},"abstract":[{"type":"text","text":"Bottom right corner point."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"PointDouble","kind":"typeIdentifier"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/corners\/bottomright"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/corners\/bottomright"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"references":{"doc://DotDocument/documentation/DotDocument/Corners":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/corners","title":"Corners","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corners"}]},"doc://DotDocument/documentation/DotDocument/PointDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"role":"symbol","title":"PointDouble","type":"topic","url":"\/documentation\/dotdocument\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Corners/bottomRight":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"url":"\/documentation\/dotdocument\/corners\/bottomright","title":"bottomRight","type":"topic","abstract":[{"type":"text","text":"Bottom right corner point."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/bottomRight"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bottomRight","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"bottomRight","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"bottomRight","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","op":"replace"},{"value":"bottomRight","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomRight\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1bottomRight\/fragments","value":[{"text":"bottomRight","kind":"identifier"}]}]}]}