{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"]]},"metadata":{"externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureDetectionValidator(im)validateWithPalmAutoCaptureFrameParameters:","title":"validate(palmAutoCaptureFrameParameters:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotPalmCore"}],"required":true,"navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Validate current frame parameters."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/validate(palmAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Current frame parameters."}],"type":"paragraph"}],"name":"palmAutoCaptureFrameParameters"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":" for the failed validation and "},{"type":"codeVoice","code":"true"},{"type":"text","text":" for the successful validation."}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/validate(palmautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/validate(palmautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"title":"PalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","abstract":[{"text":"Information from the detection process about the detected palm.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"kind":"symbol","title":"PalmAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}],"navigatorTitle":[{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator/validate(palmAutoCaptureFrameParameters:)":{"required":true,"abstract":[{"type":"text","text":"Validate current frame parameters."}],"role":"symbol","title":"validate(palmAutoCaptureFrameParameters:)","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/validate(palmautocaptureframeparameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/validate(palmAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DOTPPalmAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","value":"DOTPPalmAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","op":"replace","value":"DOTPPalmAutoCaptureDetectionValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetectionValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1validate(palmAutoCaptureFrameParameters:)\/title","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"op":"replace"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}