{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/Error-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"Error.localizedDescription","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotNfc","relatedModules":["Swift"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"localizedDescription","extendedModule":"Swift","platforms":[{"unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iOS"},{"deprecated":false,"introducedAt":"10.10","unavailable":false,"beta":false,"name":"macOS"},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"name":"watchOS","unavailable":false,"beta":false,"introducedAt":"2.0"}],"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:6DotNfc27MachineReadableZonePasswordC5ErrorO","symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/localizedDescription","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword","title":"MachineReadableZonePassword","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZonePassword"}],"abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/Error-Implementations":{"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/error-implementations","title":"Error Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/Error-Implementations","abstract":[]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/localizedDescription":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizeddescription","title":"localizedDescription","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/localizedDescription","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","title":"MachineReadableZonePassword.Error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace"}]}]}