{"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/placeholderdiametertoshortersideratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocapturepreview\/placeholderdiametertoshortersideratio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview(py)placeholderDiameterToShorterSideRatio","title":"placeholderDiameterToShorterSideRatio","navigatorTitle":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Property"},"sections":[],"abstract":[{"type":"text","text":"A value defined relative to the container shorter side that represents the placeholder diameter."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview/placeholderDiameterToShorterSideRatio":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/dotfacecore\/faceautocapturepreview\/placeholderdiametertoshortersideratio","type":"topic","title":"placeholderDiameterToShorterSideRatio","kind":"symbol","abstract":[{"text":"A value defined relative to the container shorter side that represents the placeholder diameter.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview":{"role":"symbol","title":"FaceAutoCapturePreview","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","type":"topic","navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturepreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"placeholderDiameterToShorterSideRatio"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/title","op":"replace","value":"placeholderDiameterToShorterSideRatio"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/fragments","op":"replace","value":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/fragments","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}]}]}]}