{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/imageparameters\/init(sharpness:brightness:)"]},{"paths":["\/documentation\/dotfacelite\/imageparameters\/init(sharpness:brightness:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"ImageParameters"},{"text":" with normalized values in range [0, 1.0].","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters(im)initWithSharpness:brightness:","roleHeading":"Initializer","title":"init(sharpness:brightness:)","symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithSharpness:brightness:","kind":"identifier"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters\/init(sharpness:brightness:)"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"url":"\/documentation\/dotfacelite\/facedetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters":{"url":"\/documentation\/dotfacelite\/imageparameters","role":"symbol","abstract":[{"type":"text","text":"Parameters of the image which was used for the face detection."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","type":"topic","title":"ImageParameters"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters/init(sharpness:brightness:)":{"navigatorTitle":[{"text":"initWithSharpness:brightness:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"ImageParameters"},{"text":" with normalized values in range [0, 1.0].","type":"text"}],"url":"\/documentation\/dotfacelite\/imageparameters\/init(sharpness:brightness:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters\/init(sharpness:brightness:)","title":"init(sharpness:brightness:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sharpness","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSharpness:brightness:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithSharpness:brightness:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"kind":"text","text":" "},{"text":"brightness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":") "},{"text":"brightness","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/title","op":"replace","value":"DOTFLImageParameters"},{"op":"replace","value":[{"text":"DOTFLImageParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters~1init(sharpness:brightness:)\/title","value":"initWithSharpness:brightness:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSharpness:brightness:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters~1init(sharpness:brightness:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}