{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"? = nil)"}]}]}],"kind":"symbol","metadata":{"title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","roleHeading":"Initializer","symbolKind":"init","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detection17expressionNeutral20backgroundUniformity15eyeGazeLiveness07passiveN012verificationAeA0ac15DetectionModuleE0C_AA0ac10ExpressionirE0CSgAA0ac10BackgroundkrE0CSgAA0ac3EyemnrE0CSgAA0ac7PassivenrE0CSgAA0ac12VerificationrE0CSgtcfc","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"detection","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"eyeGazeLiveness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?, ","kind":"text"},{"text":"passiveLiveness","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face detection module configuration."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceExpressionNeutralModuleConfiguration":{"kind":"symbol","title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotfingerscore\/dotfaceexpressionneutralmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceBackgroundUniformityModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfacebackgrounduniformitymoduleconfiguration","abstract":[{"type":"text","text":"Face background uniformity module."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"title":"DotFaceBackgroundUniformityModuleConfiguration","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFacePassiveLivenessModuleConfiguration":{"title":"DotFacePassiveLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face passive liveness module."}],"url":"\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceVerificationModuleConfiguration":{"title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face verification module."}],"url":"\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration":{"role":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle"},{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"},{"value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"}]}]}