{"metadata":{"title":"verification","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC12verificationAA0ac18VerificationModuleE0CSgvp","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?"}]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/verification"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"role":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/verification":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/verification","abstract":[],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"text":"?","kind":"text"}],"title":"verification","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceVerificationModuleConfiguration":{"title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face verification module."}],"url":"\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","title":"DotFaceLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}