{"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Default is:","type":"text"},{"text":" ","type":"text"},{"text":"\\code","type":"text"},{"text":" ","type":"text"},{"text":".init(cameraFacing: .front)","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/camera"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"camera"},{"kind":"text","text":";"}]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"\\Endcode","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"metadata":{"navigatorTitle":[{"text":"camera","kind":"identifier"}],"title":"camera","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(py)camera","roleHeading":"Instance Property","fragments":[{"text":"camera","kind":"identifier"}],"role":"symbol"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/camera":{"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"text":".init(cameraFacing: .front)","type":"text"}],"title":"camera","type":"topic","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/camera","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/camera","kind":"symbol","role":"symbol","fragments":[{"text":"camera","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","type":"topic","abstract":[{"text":"Configuration options for the UI MagnifEye Liveness component.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}],"title":"DOTFLMagnifEyeLivenessConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"url":"\/documentation\/dotfacelite\/cameraconfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","title":"CameraConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments"},{"value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle"}]}]}