{"sections":[],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration"]}],"metadata":{"roleHeading":"Class","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationFast","navigatorTitle":[{"text":"DotFaceDetectionModuleConfigurationFast","kind":"identifier"}],"fragments":[{"text":"DotFaceDetectionModuleConfigurationFast","kind":"identifier"}],"role":"symbol","symbolKind":"class","title":"DotFaceDetectionModuleConfigurationFast"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"text":"Face detection fast module.","type":"text"}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast\/init"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfacedetectionmoduleconfigurationfast"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationFast"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"role":"symbol","abstract":[{"type":"text","text":"Face detection module configuration."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","type":"topic","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfigurationFast/init":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast\/init","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfigurationfast\/init","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfigurationFast":{"role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationFast"}],"abstract":[{"text":"Face detection fast module.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfigurationfast","title":"DotFaceDetectionModuleConfigurationFast","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfigurationFast","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}