{"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/com","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg1","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg10","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg11","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg12","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg13","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg14","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg15","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg16","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg2","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg3","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg4","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg5","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg7","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg8","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg9","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/sod"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/description"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Identifier of the LDS1 Elementary File.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNLds1ElementaryFileId) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Overview","anchor":"overview","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"More details about Elementary Files can be found in "},{"type":"reference","isActive":true,"identifier":"https:\/\/www.icao.int\/publications\/pages\/publication.aspx?docnum=9303"},{"type":"text","text":","},{"type":"text","text":" "},{"type":"text","text":"Chapter 4. LDS1 eMRTD Application."}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId","modules":[{"name":"DotNfc"}],"roleHeading":"Enumeration","title":"Lds1ElementaryFileId","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"role":"symbol"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg3":{"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg3","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg3","type":"topic","title":"Lds1ElementaryFileId.dg3","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg3"}],"abstract":[{"text":"File identifier for data group 3. Data group 3 contains finger print data.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg7":{"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg7","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg7"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg7"}],"abstract":[{"text":"File identifier for data group 7. Data group 7 contains displayed signature.","type":"text"}],"title":"Lds1ElementaryFileId.dg7","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg7"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"kind":"article","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/equatable-implementations","title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/Equatable-Implementations"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg8":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg8","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg8","title":"Lds1ElementaryFileId.dg8","abstract":[{"type":"text","text":"File identifier for data group 8. Data group 8 contains data features."}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg8","kind":"identifier"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg8","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg1":{"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg1","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg1","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg1"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}],"abstract":[{"text":"File identifier for data group 1. Data group 1 contains the MRZ.","type":"text"}],"title":"Lds1ElementaryFileId.dg1"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg13":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg13"}],"title":"Lds1ElementaryFileId.dg13","type":"topic","abstract":[{"text":"File identifier for data group 13. Data group 13 contains optional details.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg13","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg13","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg13"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/sod":{"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/sod","title":"Lds1ElementaryFileId.sod","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/sod","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sod"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdSod"}],"abstract":[{"text":"The security document.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg14":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg14"}],"title":"Lds1ElementaryFileId.dg14","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg14","abstract":[{"text":"File identifier for data group 14. Data group 14 contains security information.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg14"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg14","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg10":{"abstract":[{"type":"text","text":"File identifier for data group 10. Data group 10 contains substance features."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg10","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Lds1ElementaryFileId.dg10","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg10","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg10","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg10","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/com":{"abstract":[{"type":"text","text":"The data group presence list."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/com","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdCom"}],"role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/com","title":"Lds1ElementaryFileId.com","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"com"}],"kind":"symbol"},"doc://DotNfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/RawRepresentable-Implementations":{"abstract":[],"type":"topic","role":"collectionGroup","kind":"article","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/RawRepresentable-Implementations","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/rawrepresentable-implementations"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg2":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg2","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg2","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg2","role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg2","abstract":[{"type":"text","text":"File identifier for data group 2. Data group 2 contains face image data."}],"kind":"symbol","title":"Lds1ElementaryFileId.dg2"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg11":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg11"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg11"}],"role":"symbol","abstract":[{"text":"File identifier for data group 11. Data group 11 contains additional personal details.","type":"text"}],"kind":"symbol","title":"Lds1ElementaryFileId.dg11","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg11","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg11"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg15":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg15","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg15"}],"abstract":[{"text":"File identifier for data group 15. Data group 15 contains the public key used for Active Authentication.","type":"text"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg15","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg15"}],"title":"Lds1ElementaryFileId.dg15","type":"topic"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg9":{"role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg9","kind":"symbol","navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg9","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg9","abstract":[{"type":"text","text":"File identifier for data group 9. Data group 9 contains structure features."}],"type":"topic","title":"Lds1ElementaryFileId.dg9","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg9","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg12":{"title":"Lds1ElementaryFileId.dg12","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg12","navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg12"}],"abstract":[{"text":"File identifier for data group 12. Data group 12 contains additional document details.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg12"}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg12","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg5":{"kind":"symbol","abstract":[{"text":"File identifier for data group 5. Data group 5 contains displayed portrait.","type":"text"}],"title":"Lds1ElementaryFileId.dg5","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg5","kind":"identifier"}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg5","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg5","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg5","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/init(rawValue:)":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/init(rawvalue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/description","role":"symbol","kind":"symbol","abstract":[],"title":"description"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"role":"symbol","title":"Lds1ElementaryFileId","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","url":"\/documentation\/dotnfc\/lds1elementaryfileid","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Lds1ElementaryFileId","kind":"identifier"}],"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}]},"https://www.icao.int/publications/pages/publication.aspx?docnum=9303":{"url":"https:\/\/www.icao.int\/publications\/pages\/publication.aspx?docnum=9303","titleInlineContent":[{"type":"text","text":"Doc 9303 Part 10: Logical Data Structure (LDS) for Storage of Biometrics and Other Data in the Contactless Integrated Circuit (IC)"}],"type":"link","identifier":"https:\/\/www.icao.int\/publications\/pages\/publication.aspx?docnum=9303","title":"Doc 9303 Part 10: Logical Data Structure (LDS) for Storage of Biometrics and Other Data in the Contactless Integrated Circuit (IC)"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg4":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg4","kind":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg4","type":"topic","title":"Lds1ElementaryFileId.dg4","abstract":[{"type":"text","text":"File identifier for data group 4. Data group 4 contains iris data."}],"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg4","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg16":{"navigatorTitle":[{"text":"DOTNLds1ElementaryFileIdDg16","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg16","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg16","kind":"identifier"}],"title":"Lds1ElementaryFileId.dg16","url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg16","kind":"symbol","abstract":[{"type":"text","text":"File identifier for data group 16. Data group 16 contains person(s) to notify."}]},"doc://DotNfc/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileId"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/com","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg1","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg10","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg11","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg12","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg13","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg14","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg15","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg16","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg2","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg3","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg4","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg5","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg7","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg8","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg9","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/sod"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNLds1ElementaryFileId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg3\/title","value":"DOTNLds1ElementaryFileIdDg3","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg3\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg3"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg7\/title","value":"DOTNLds1ElementaryFileIdDg7","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg7\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg7","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg8\/title","value":"DOTNLds1ElementaryFileIdDg8","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg8\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg8"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg1\/title","value":"DOTNLds1ElementaryFileIdDg1","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg1\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg1"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg13\/title","value":"DOTNLds1ElementaryFileIdDg13","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg13\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg13","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1sod\/title","value":"DOTNLds1ElementaryFileIdSod","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1sod\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdSod","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg14\/title","value":"DOTNLds1ElementaryFileIdDg14","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg14\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg14"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg10\/title","value":"DOTNLds1ElementaryFileIdDg10","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg10\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg10","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1com\/title","value":"DOTNLds1ElementaryFileIdCom","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1com\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdCom"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg2\/title","value":"DOTNLds1ElementaryFileIdDg2","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg2\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg2","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg11\/title","value":"DOTNLds1ElementaryFileIdDg11","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg11\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg11","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg15\/title","value":"DOTNLds1ElementaryFileIdDg15","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg15\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg15"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg9\/title","value":"DOTNLds1ElementaryFileIdDg9","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg9\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg9"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg12\/title","value":"DOTNLds1ElementaryFileIdDg12","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg12\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg12","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg5\/title","value":"DOTNLds1ElementaryFileIdDg5","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg5\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg5"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","value":"DOTNLds1ElementaryFileId","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/navigatorTitle","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg4\/title","value":"DOTNLds1ElementaryFileIdDg4","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg4\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg4","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg16\/title","value":"DOTNLds1ElementaryFileIdDg16","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg16\/fragments","value":[{"text":"DOTNLds1ElementaryFileIdDg16","kind":"identifier"}],"op":"replace"}]}]}