{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/description","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","externalID":"s:14DotFaceCommons0B16AutoCapturePhaseO11descriptionSSvp","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/description","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/description","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"title":"FaceAutoCapturePhase","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title","value":"DOTFaceAutoCapturePhase","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace"}]}]}