{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"symbolKind":"case","roleHeading":"Case","title":"FaceAutoCapturePhase.preCandidateSelection","externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase@DOTFaceAutoCapturePhasePreCandidateSelection","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}]},"abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/precandidateselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/precandidateselection"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/preCandidateSelection","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"title":"FaceAutoCapturePhase","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase","abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/preCandidateSelection":{"navigatorTitle":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/precandidateselection","title":"FaceAutoCapturePhase.preCandidateSelection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/preCandidateSelection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTFaceAutoCapturePhasePreCandidateSelection"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"DOTFaceAutoCapturePhase","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title"},{"op":"replace","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1preCandidateSelection\/title","value":"DOTFaceAutoCapturePhasePreCandidateSelection"},{"op":"replace","value":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1preCandidateSelection\/fragments"}]}]}