{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocument","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/traveldocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/traveldocument"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"travelDocument"}],"role":"symbol","title":"travelDocument","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocument","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderResult(py)travelDocument"},"kind":"symbol","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/travelDocument","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/travelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"travelDocument","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","text":"TravelDocument","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"travelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/traveldocument","title":"travelDocument","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/travelDocument","role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"title":"NfcTravelDocumentReaderResult","abstract":[{"type":"text","text":"Result of the NFC Travel Document Reader component."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"travelDocument","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"travelDocument"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNTravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"travelDocument","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1travelDocument\/title","op":"replace","value":"travelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1travelDocument\/fragments","op":"replace","value":[{"text":"travelDocument","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title","op":"replace","value":"DOTNNfcTravelDocumentReaderResult"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/navigatorTitle","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}]}]}]}