{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation"]]},"metadata":{"modules":[{"name":"DotDocument"}],"title":"MrzValidation.validateIfPresent","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"validateIfPresent","kind":"identifier"}],"navigatorTitle":[{"text":"DOTDMrzValidationValidateIfPresent","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@DotDocument@E@DOTDMrzValidation@DOTDMrzValidationValidateIfPresent","symbolKind":"case"},"abstract":[{"type":"text","text":"MRZ is validated only if it is present."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"validateIfPresent","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzvalidation\/validateifpresent"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzvalidation\/validateifpresent"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation\/validateIfPresent","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation/validateIfPresent":{"url":"\/documentation\/dotdocument\/mrzvalidation\/validateifpresent","abstract":[{"text":"MRZ is validated only if it is present.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"validateIfPresent","kind":"identifier"}],"title":"MrzValidation.validateIfPresent","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation\/validateIfPresent","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTDMrzValidationValidateIfPresent"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation":{"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"title":"MrzValidation","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","kind":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDMrzValidationValidateIfPresent","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"text":"DOTDMrzValidationValidateIfPresent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTDMrzValidationValidateIfPresent"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"DOTDMrzValidationValidateIfPresent","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation~1validateIfPresent\/title"},{"op":"replace","value":[{"text":"DOTDMrzValidationValidateIfPresent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation~1validateIfPresent\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/fragments"}]}]}