{"abstract":[{"type":"text","text":"Initialize with default threshold."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/init()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooHighValidator(im)init","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/init()"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator\/init()","role":"symbol","title":"init()","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/init()"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"init","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1init()\/fragments","op":"replace"},{"value":"DOTFLBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","op":"replace"},{"value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle","op":"replace"}]}]}