{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/validate(faceAutoCaptureFrameParameters:)"},"metadata":{"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooHighValidator(im)validateWithFaceAutoCaptureFrameParameters:","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"title":"validate(faceAutoCaptureFrameParameters:)"},"sections":[],"abstract":[{"text":"Validate brightness of the detected face.","type":"text"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"faceAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"Returns ","type":"text"},{"code":"false","type":"codeVoice"},{"text":" for bright face.","type":"text"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/validate(faceautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoohighvalidator\/validate(faceautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}]},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator/validate(faceAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator\/validate(faceautocaptureframeparameters:)","abstract":[{"text":"Validate brightness of the detected face.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator\/validate(faceAutoCaptureFrameParameters:)","title":"validate(faceAutoCaptureFrameParameters:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"title":"FaceAutoCaptureFrameParameters","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"validateWithFaceAutoCaptureFrameParameters:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","text":"DOTFLFaceAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceAutoCaptureFrameParameters"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}],"name":"faceAutoCaptureFrameParameters"}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" for bright face."}],"type":"paragraph"}],"kind":"content"}},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"},{"value":"DOTFLBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/navigatorTitle"},{"op":"replace","value":"validateWithFaceAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1validate(faceAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"DOTFLFaceAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}