{"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotSdk(im)deinitializeAndReturnError:","title":"deinitialize()","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","abstract":[{"type":"text","text":"Deinitialize "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"This method should be called on the background thread. If no DOT UI components are processing camera images, deinitialization proceeds without waiting for UI work (note: deinitialization itself is synchronous and may still take some time). If UI components are actively processing images, this method blocks until that processing finishes and then completes deinitialization."}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Throws an error if "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" fails to deinitialize."}]}],"type":"aside","style":"note","name":"Throws"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/deinitialize()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/deinitialize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdk\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/deinitialize()":{"url":"\/documentation\/dotfacecore\/dotsdk\/deinitialize()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","title":"deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"deinitializeAndReturnError:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"deinitializeAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1deinitialize()\/title","value":"deinitializeAndReturnError:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}