{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk\/getLibrary(libraryId:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/getlibrary(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLibrary"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"getLibrary"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","role":"symbol","title":"getLibrary(libraryId:)","externalID":"s:11DotFaceCore0A3SdkC10getLibrary9libraryIdAA0aF0_pSgAA0afH0O_tF","roleHeading":"Instance Method"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibraryId":{"title":"DotLibraryId","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibraryId"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotlibraryid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","role":"symbol","title":"DotLibrary","url":"\/documentation\/dotfacecore\/dotlibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdk/getLibrary(libraryId:)":{"role":"symbol","title":"getLibrary(libraryId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"getLibrary","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"?","kind":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk\/getLibrary(libraryId:)","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdk\/getlibrary(libraryid:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdk":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk","url":"\/documentation\/dotfacecore\/dotsdk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"patch":[{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}],"op":"replace"},{"value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/title","op":"replace"},{"op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/fragments"},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}