{"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/isinitialized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdk\/isinitialized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isInitialized"},"abstract":[{"type":"text","text":"Flag to determine if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" is initialized."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Instance Property","title":"isInitialized","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isInitialized"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotSdk(py)isInitialized","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/isInitialized":{"url":"\/documentation\/dotfacecore\/dotsdk\/isinitialized","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInitialized","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isInitialized","navigatorTitle":[{"text":"isInitialized","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/isInitialized","abstract":[{"type":"text","text":"Flag to determine if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" is initialized."}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"title":"DotSdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isInitialized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isInitialized"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isInitialized\/title","value":"isInitialized"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1isInitialized\/fragments","value":[{"kind":"identifier","text":"isInitialized"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}