{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/shared","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"title":"shared","roleHeading":"Type Property","externalID":"c:@M@DotCore@objc(cs)DotSdk(cpy)shared","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk"}],"navigatorTitle":[{"text":"shared","kind":"identifier"}],"role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdk\/shared"]}],"abstract":[{"text":"Shared singleton instance.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/shared":{"abstract":[{"type":"text","text":"Shared singleton instance."}],"title":"shared","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk"}],"url":"\/documentation\/dotfacecore\/dotsdk\/shared","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/shared","type":"topic","role":"symbol","navigatorTitle":[{"text":"shared","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"shared","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"shared","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"shared","kind":"identifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","op":"replace","value":"DotSdk"},{"value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","op":"replace"},{"value":"shared","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1shared\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk~1shared\/fragments","op":"replace","value":[{"kind":"identifier","text":"shared"}]}]}]}