{"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/maxHotspotsScore:error:","interfaceLanguage":"occ"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maxHotspotsScore:error:"}],"navigatorTitle":[{"text":"maxHotspotsScore:error:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"method","roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder(im)maxHotspotsScore:error:","title":"maxHotspotsScore:error:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/maxhotspotsscore:error:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"maxHotspotsScore:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTWrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" *) ","kind":"text"},{"text":"maxHotspotsScore","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder":{"url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","abstract":[],"type":"topic","title":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","role":"symbol"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"url":"\/documentation\/dotdocument\/wrappeddouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","kind":"symbol","title":"WrappedDouble","type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder/maxHotspotsScore:error:":{"url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/maxhotspotsscore:error:","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/maxHotspotsScore:error:","title":"maxHotspotsScore:error:","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"maxHotspotsScore:error:","kind":"identifier"}],"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"maxHotspotsScore:error:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]}]}]}