{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible\/initWithType:","interfaceLanguage":"occ"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"method","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithType:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDPlaceholderVisible(im)initWithType:","roleHeading":"Instance Method","title":"initWithType:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible"]]},"variants":[{"paths":["\/documentation\/dotdocument\/dotdplaceholdervisible\/initwithtype:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","text":"DOTDPlaceholderType","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"type","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","title":"PlaceholderType","abstract":[{"type":"text","text":"Type of placeholder."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholdertype","role":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderVisible/initWithType:":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"type":"topic","title":"initWithType:","url":"\/documentation\/dotdocument\/dotdplaceholdervisible\/initwithtype:","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible\/initWithType:","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithType:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDPlaceholderVisible":{"title":"DOTDPlaceholderVisible","url":"\/documentation\/dotdocument\/dotdplaceholdervisible","role":"symbol","fragments":[{"text":"DOTDPlaceholderVisible","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Visible placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDPlaceholderVisible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"op":"replace"}]}]}