{"variants":[{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)dateOfBirth","symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}],"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"title":"dateOfBirth","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfBirth"},"references":{"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","role":"symbol","kind":"symbol","title":"Td3MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"url":"\/documentation\/dotnfc\/td3machinereadablezone"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.10.0"}]},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/dateOfBirth":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/dateOfBirth","abstract":[],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/dateofbirth","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dateOfBirth","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}],"title":"dateOfBirth","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"title":"MrzDateElementWithCheckDigit","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"dateOfBirth","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"dateOfBirth"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]},{"op":"replace","value":"dateOfBirth","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfBirth\/title"},{"value":[{"text":"dateOfBirth","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1dateOfBirth\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}