{"abstract":[{"text":"Captured face image.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult\/bgraRawImage"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgraRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult"]]},"sections":[],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bgraRawImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessResult(py)bgraRawImage","title":"bgraRawImage","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"bgraRawImage"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessresult\/bgrarawimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessresult\/bgrarawimage"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"url":"\/documentation\/dotfacelite\/bgrarawimage","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","title":"BgraRawImage"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessResult/bgraRawImage":{"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bgraRawImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"title":"bgraRawImage","navigatorTitle":[{"kind":"identifier","text":"bgraRawImage"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult\/bgraRawImage","type":"topic","abstract":[{"type":"text","text":"Captured face image."}],"url":"\/documentation\/dotfacelite\/multirangelivenessresult\/bgrarawimage"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessResult":{"abstract":[{"type":"text","text":"The final result of the Multi-Range Liveness process."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MultiRangeLivenessResult"}],"title":"MultiRangeLivenessResult","navigatorTitle":[{"text":"MultiRangeLivenessResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessResult","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessresult","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.16.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"bgraRawImage","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bgraRawImage"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTBgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":" * ","kind":"text"},{"text":"bgraRawImage","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"value":"bgraRawImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult~1bgraRawImage\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult~1bgraRawImage\/fragments","value":[{"text":"bgraRawImage","kind":"identifier"}]},{"op":"replace","value":"DOTFLMultiRangeLivenessResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult\/title"},{"value":[{"text":"DOTFLMultiRangeLivenessResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessResult\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}