{"abstract":[{"text":"Create palm auto capture controller configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"},{"text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","text":"PalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"},{"text":"], ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},{"text":"? = nil) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:detectionArea:)"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"kind":"symbol","metadata":{"role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","text":"PalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":"?) ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC6common04autoE010validators13detectionAreaAE0aC006CommonG0C_0aE00deG0CSayAA0bdE24FrameParametersValidator_pGAJ15RectangleDoubleCSgtKcfc","title":"init(common:autoCapture:validators:detectionArea:)","roleHeading":"Initializer","modules":[{"name":"DotPalmCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:detectionarea:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","title":"PalmAutoCaptureFrameParametersValidator"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"title":"RectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/init(common:autoCapture:validators:detectionArea:)":{"abstract":[{"text":"Create palm auto capture controller configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:validators:detectionArea:)","title":"init(common:autoCapture:validators:detectionArea:)","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/init(common:autocapture:validators:detectionarea:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"CommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier","text":"AutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","kind":"typeIdentifier","text":"PalmAutoCaptureFrameParametersValidator"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"url":"\/documentation\/dotpalmcore\/commonconfiguration","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","title":"CommonConfiguration","kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","type":"topic","title":"PalmAutoCaptureController.Configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title","value":"DOTPPalmAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","op":"replace"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}