{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/accesscontrolerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/accesscontrolerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/accessControlError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Failed access control indicates that you have invalid NFC key."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}],"role":"symbol","title":"NfcTravelDocumentReaderErrorType.accessControlError","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlError"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTNfcTravelDocumentReaderErrorType@DOTNfcTravelDocumentReaderErrorTypeAccessControlError","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 2.3.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"abstract":[{"type":"text","text":"NFC reading error type."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/accessControlError":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType.accessControlError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"accessControlError"}],"abstract":[{"type":"text","text":"Failed access control indicates that you have invalid NFC key."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/accessControlError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/accesscontrolerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/title","value":"DOTNfcTravelDocumentReaderErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1accessControlError\/title","value":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1accessControlError\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReaderErrorTypeAccessControlError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}