{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidActiveAuthenticationChallengeSize"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/invalidactiveauthenticationchallengesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/invalidactiveauthenticationchallengesize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/invalidActiveAuthenticationChallengeSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error denoting that Active Authentication challenge size is not exactly 8 bytes long."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"}],"role":"symbol","title":"NfcTravelDocumentReaderErrorType.invalidActiveAuthenticationChallengeSize","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidActiveAuthenticationChallengeSize"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTNNfcTravelDocumentReaderErrorType@DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"abstract":[{"type":"text","text":"NFC reading error type."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/invalidActiveAuthenticationChallengeSize":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType.invalidActiveAuthenticationChallengeSize","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidActiveAuthenticationChallengeSize"}],"abstract":[{"type":"text","text":"An error denoting that Active Authentication challenge size is not exactly 8 bytes long."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/invalidActiveAuthenticationChallengeSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/invalidactiveauthenticationchallengesize"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/title","value":"DOTNNfcTravelDocumentReaderErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1invalidActiveAuthenticationChallengeSize\/title","value":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1invalidActiveAuthenticationChallengeSize\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeInvalidActiveAuthenticationChallengeSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}