{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readingError"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/readingerror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/readingerror"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/readingError","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An error encountered during the NFC reading process."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"}],"role":"symbol","title":"NfcTravelDocumentReaderErrorType.readingError","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readingError"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTNNfcTravelDocumentReaderErrorType@DOTNNfcTravelDocumentReaderErrorTypeReadingError","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"abstract":[{"type":"text","text":"NFC reading error type."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderErrorType"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderErrorType/readingError":{"role":"symbol","title":"NfcTravelDocumentReaderErrorType.readingError","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"readingError"}],"abstract":[{"type":"text","text":"An error encountered during the NFC reading process."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderErrorType\/readingError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererrortype\/readingerror"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/title","value":"DOTNNfcTravelDocumentReaderErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1readingError\/title","value":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderErrorType~1readingError\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderErrorTypeReadingError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}