{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/init(modules:)"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"title":"init(modules:)","roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(im)initWithModules:","modules":[{"name":"DotPalmCore"}],"symbolKind":"init"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","title":"DotPalmLibraryConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules":{"role":"symbol","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules","type":"topic","kind":"symbol","title":"DotPalmLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class","kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/init(modules:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/init(modules:)","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/init(modules:)","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"title":"init(modules:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithModules:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title"},{"value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle"},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1init(modules:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1init(modules:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}