{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"}],"languages":["swift"]}]},{"parameters":[{"name":"ciImage","content":[{"inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"type":"paragraph"}]},{"name":"ciContext","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrarawimagefactory\/create(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrarawimagefactory\/create(ciimage:cicontext:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(ciImage:ciContext:)"},"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCiImage:ciContext:","title":"create(ciImage:ciContext:)","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}]},"references":{"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"url":"\/documentation\/dotnfc\/bgrarawimage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","kind":"symbol","title":"BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"url":"\/documentation\/dotnfc\/bgrarawimagefactory","role":"symbol","kind":"symbol","type":"topic","title":"BgraRawImageFactory","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImageFactory/create(ciImage:ciContext:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"url":"\/documentation\/dotnfc\/bgrarawimagefactory\/create(ciimage:cicontext:)","role":"symbol","kind":"symbol","type":"topic","title":"create(ciImage:ciContext:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImageFactory\/create(ciImage:ciContext:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"createWithCiImage:ciContext:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCiImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"text":"ciImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"kind":"text","text":"("},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/title","op":"replace","value":"DOTBgraRawImageFactory"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}]}]}]}