{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrarawimage\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrarawimage\/size"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage\/size"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)size","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"symbolKind":"property","title":"size","modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"_RawImage.size"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/ImageSize":{"abstract":[{"text":"Image size in pixels.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","url":"\/documentation\/dotdocument\/imagesize","title":"ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"type":"topic","title":"MrzReader"},"doc://DotDocument/documentation/DotDocument/BgraRawImage/size":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage\/size","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/bgrarawimage\/size","title":"size","role":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"role":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","kind":"symbol","title":"BgraRawImage"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","title":"DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector","type":"topic","kind":"symbol","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"size","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","kind":"typeIdentifier","text":"DOTImageSize"},{"kind":"text","text":" * "},{"text":"size","kind":"identifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage~1size\/title","op":"replace","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage~1size\/fragments","value":[{"text":"size","kind":"identifier"}]},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}]}]}