{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/hash","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/wrappedfloat\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/wrappedfloat\/hash"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(py)hash","title":"hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/hash":{"title":"hash","kind":"symbol","url":"\/documentation\/dotfingerscore\/wrappedfloat\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/hash"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"title":"WrappedFloat","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappedfloat","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1hash\/fragments"},{"value":"DOTWrappedFloat","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/navigatorTitle"}]}]}