{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/little"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/little"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/little"]}],"abstract":[{"text":"Image of the little finger, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not provided.","type":"text"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages(py)little","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?","kind":"text"}],"title":"little","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"little"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?","kind":"text"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","kind":"symbol","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"title":"FingerprintImages","type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerprintImages","kind":"identifier"}],"navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/little":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"little"}],"url":"\/documentation\/dotfingerscore\/fingerprintimages\/little","abstract":[{"type":"text","text":"Image of the little finger, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the finger was not provided."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/little","title":"little","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"little","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"little"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"little"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"DOTFGFingerprintImages","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1little\/title","value":"little"},{"value":[{"kind":"identifier","text":"little"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1little\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}