{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/ring"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ring","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages(py)ring","title":"ring","navigatorTitle":[{"kind":"identifier","text":"ring"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}]}]}],"abstract":[{"text":"Image of the ring finger, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not provided.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/ring"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerprintimages\/ring"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","kind":"symbol","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"title":"FingerprintImages","type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerprintImages","kind":"identifier"}],"navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/ring":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/ring","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ring","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"ring","abstract":[{"text":"Image of the ring finger, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the finger was not provided."}],"navigatorTitle":[{"kind":"identifier","text":"ring"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/ring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"ring","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"ring","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" * ","kind":"text"},{"text":"ring","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFGFingerprintImages","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title","op":"replace"},{"value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","op":"replace"},{"value":"ring","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1ring\/title","op":"replace"},{"value":[{"text":"ring","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1ring\/fragments","op":"replace"}]}]}