{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules\/barcode"]}],"metadata":{"symbolKind":"property","title":"barcode","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"text":"barcode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"barcode"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules\/barcode"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules/barcode":{"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules\/barcode","title":"barcode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules\/barcode","fragments":[{"kind":"identifier","text":"barcode"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules":{"kind":"symbol","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","title":"DotDocumentLibraryConfigurationModules","role":"symbol","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentBarcodeModuleConfiguration":{"title":"DotDocumentBarcodeModuleConfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotdocumentbarcodemoduleconfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}