{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration"]]},"abstract":[{"type":"text","text":"Face library module configuration."}],"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","role":"symbol","roleHeading":"Class","title":"DotFaceLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DotFaceLibraryConfigurationModules) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class"]}],"sections":[],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","title":"eyeGazeLiveness","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face library configuration."}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/detection","kind":"symbol","title":"detection","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/backgroundUniformity":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","title":"backgroundUniformity","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/expressionNeutral":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/expressionNeutral","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"title":"expressionNeutral","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/expressionneutral"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class":{"type":"topic","title":"DotFaceLibraryConfiguration.Modules","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Face library module configuration.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/passiveLiveness":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"kind":"symbol","title":"passiveLiveness","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/verification":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"verification","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/verification","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/verification","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expressionNeutral"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"passiveLiveness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"verification"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","text":"DotFaceVerificationModuleConfiguration"},{"kind":"text","text":"?)"}],"kind":"symbol","type":"topic","title":"init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/init(detection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:)","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class\/init(detection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}]}