{"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone(py)td1","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"td1","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":"?"}],"title":"td1"},"variants":[{"paths":["\/documentation\/dotdocument\/machinereadablezone\/td1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/td1"]}],"abstract":[{"type":"text","text":"Parsed MRZ of TD1."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"td1"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone","text":"Td1MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td1"},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"title":"MachineReadableZone","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"url":"\/documentation\/dotdocument\/machinereadablezone","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"url":"\/documentation\/dotdocument\/td1machinereadablezone","title":"Td1MachineReadableZone","kind":"symbol","type":"topic","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"role":"symbol","title":"MrzReader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone/td1":{"title":"td1","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td1","url":"\/documentation\/dotdocument\/machinereadablezone\/td1","abstract":[{"text":"Parsed MRZ of TD1.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone","kind":"typeIdentifier","text":"Td1MachineReadableZone"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"td1","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"td1"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"td1"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone","text":"DOTTd1MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone"},{"kind":"text","text":" * "},{"kind":"identifier","text":"td1"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td1\/title","op":"replace","value":"td1"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td1\/fragments","op":"replace","value":[{"text":"td1","kind":"identifier"}]}]}]}