{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"td2","navigatorTitle":[{"kind":"identifier","text":"td2"}],"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone(py)td2","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td2"},{"text":": ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":"?"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td2","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","kind":"typeIdentifier","text":"Td2MachineReadableZone"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/td2"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/machinereadablezone\/td2"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td2","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone"]]},"abstract":[{"type":"text","text":"Parsed MRZ of TD2."}],"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone/td2":{"abstract":[{"type":"text","text":"Parsed MRZ of TD2."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td2"},{"kind":"text","text":": "},{"text":"Td2MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"text":"td2","kind":"identifier"}],"role":"symbol","title":"td2","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone\/td2","url":"\/documentation\/dotdocument\/machinereadablezone\/td2","kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","title":"Td2MachineReadableZone","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"type":"topic","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","url":"\/documentation\/dotdocument\/machinereadablezone","kind":"symbol","role":"symbol","title":"MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"td2","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"td2"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","text":"DOTTd2MachineReadableZone"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"td2"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"td2","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td2\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone~1td2\/fragments","value":[{"kind":"identifier","text":"td2"}]},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace","value":"DOTTd2MachineReadableZone"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments"}]}]}