{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"positions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"MrzStringPosition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)"},"metadata":{"symbolKind":"init","modules":[{"name":"DotNfc"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"checkDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit(im)initWithValue:positions:checkDigit:","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:"}],"roleHeading":"Initializer","role":"symbol","title":"init(value:positions:checkDigit:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}],"role":"symbol","title":"MrzElementWithCheckDigit"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"title":"MrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","url":"\/documentation\/dotnfc\/mrzcheckdigit","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/init(value:positions:checkDigit:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"positions","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/init(value:positions:checkDigit:)","navigatorTitle":[{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/init(value:positions:checkdigit:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"init(value:positions:checkDigit:)"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"title":"MrzStringPosition","role":"symbol","url":"\/documentation\/dotnfc\/mrzstringposition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithValue:positions:checkDigit:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"positions:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<DOTMrzStringPosition *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"positions","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"checkDigit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"checkDigit","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title"},{"op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments"},{"op":"replace","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/navigatorTitle"},{"op":"replace","value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title"},{"op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments"},{"op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle"},{"op":"replace","value":"initWithValue:positions:checkDigit:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1init(value:positions:checkDigit:)\/fragments"},{"op":"replace","value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments"},{"op":"replace","value":[{"text":"DOTMrzStringPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}