{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/stopasync(onstopped:)"]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/stopasync(onstopped:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"abstract":[{"text":"Stop the face auto capture process asynchronously. The ","type":"text"},{"code":"onStopped","type":"codeVoice"},{"text":" callback is called after the process has stopped.","type":"text"}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stopAsync"},{"text":"(","kind":"text"},{"text":"onStopped","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"attribute","text":"@escaping"},{"text":" () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onStopped"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","title":"stopAsync(onStopped:)","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController(im)stopAsyncOnStopped:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stopAsyncOnStopped:"}]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.3.1"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/stopAsync(onStopped:)":{"type":"topic","abstract":[{"text":"Stop the face auto capture process asynchronously. The ","type":"text"},{"code":"onStopped","type":"codeVoice"},{"text":" callback is called after the process has stopped.","type":"text"}],"navigatorTitle":[{"text":"stopAsyncOnStopped:","kind":"identifier"}],"title":"stopAsync(onStopped:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/stopasync(onstopped:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onStopped"},{"text":": () -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"stopAsyncOnStopped:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"stopAsyncOnStopped:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"stopAsyncOnStopped:"},{"kind":"text","text":"("},{"text":"void (^)(void)","kind":"typeIdentifier","preciseIdentifier":"c:BFv()"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"onStopped"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"stopAsyncOnStopped:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"stopAsyncOnStopped:","kind":"identifier"}]},{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]}]}]}