{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/init(glasses:mask:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/wearables\/init(glasses:mask:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/wearables\/init(glasses:mask:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"glasses"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","kind":"typeIdentifier","text":"Glasses","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses"},{"kind":"text","text":"? = nil, "},{"text":"mask","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearables(im)initWithGlasses:mask:","navigatorTitle":[{"text":"initWithGlasses:mask:","kind":"identifier"}],"roleHeading":"Initializer","title":"init(glasses:mask:)","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"glasses","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"Glasses","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mask"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?)"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/init(glasses:mask:)":{"type":"topic","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithGlasses:mask:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"glasses"},{"kind":"text","text":": "},{"text":"Glasses","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(glasses:mask:)","role":"symbol","url":"\/documentation\/dotfacecore\/wearables\/init(glasses:mask:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/init(glasses:mask:)"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"role":"symbol","type":"topic","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"url":"\/documentation\/dotfacecore\/wearables","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","title":"Wearables","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"abstract":[{"type":"text","text":"Face attribute for the glasses."}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/glasses","title":"Glasses","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","navigatorTitle":[{"text":"Glasses","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAttribute"}],"role":"symbol","title":"FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithGlasses:mask:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithGlasses:mask:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithGlasses:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","text":"DOTFGlasses","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"glasses","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask:"},{"kind":"text","text":"("},{"text":"DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"mask"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","value":"initWithGlasses:mask:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1init(glasses:mask:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1init(glasses:mask:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithGlasses:mask:","kind":"identifier"}]},{"op":"replace","value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"text":"DOTFWearables","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFGlasses","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title"},{"value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]}]}]}