{"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"init(imageQuality:headPose:wearables:expression:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","text":"FaceImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headPose"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","text":"HeadPose"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wearables"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","text":"Wearables"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expression"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression","text":"Expression"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality(im)initWithImageQuality:headPose:wearables:expression:","roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","kind":"typeIdentifier","text":"FaceImageQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headPose"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","kind":"typeIdentifier","text":"HeadPose","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wearables"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","kind":"typeIdentifier","text":"Wearables","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"expression"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","text":"Expression","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/init(imageQuality:headPose:wearables:expression:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequality\/init(imagequality:headpose:wearables:expression:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequality\/init(imagequality:headpose:wearables:expression:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality/init(imageQuality:headPose:wearables:expression:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","kind":"typeIdentifier","text":"FaceImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"headPose"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","kind":"typeIdentifier","text":"HeadPose"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wearables"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","kind":"typeIdentifier","text":"Wearables"},{"kind":"text","text":", "},{"kind":"externalParam","text":"expression"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression","kind":"typeIdentifier","text":"Expression"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality\/init(imageQuality:headPose:wearables:expression:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/facequality\/init(imagequality:headpose:wearables:expression:)","title":"init(imageQuality:headPose:wearables:expression:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"url":"\/documentation\/dotfacecore\/facequality","title":"FaceQuality","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/expression","title":"Expression","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","kind":"symbol","abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"url":"\/documentation\/dotfacecore\/headpose","title":"HeadPose","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"url":"\/documentation\/dotfacecore\/wearables","title":"Wearables","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequality","title":"FaceImageQuality","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithImageQuality:headPose:wearables:expression:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:headPose:wearables:expression:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceImageQuality","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageQuality"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headPose:"},{"text":"(","kind":"text"},{"text":"DOTFHeadPose","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose"},{"text":" *) ","kind":"text"},{"text":"headPose","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"wearables:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFWearables","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWearables","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables"},{"text":" *) ","kind":"text"},{"text":"wearables","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expression:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFExpression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpression","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"},{"text":" *) ","kind":"text"},{"text":"expression","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1init(imageQuality:headPose:wearables:expression:)\/title","value":"initWithImageQuality:headPose:wearables:expression:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality~1init(imageQuality:headPose:wearables:expression:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:headPose:wearables:expression:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","value":"DOTFFaceQuality"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle"},{"value":"DOTFExpression","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title"},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments"},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle"},{"value":"DOTFHeadPose","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"value":[{"kind":"identifier","text":"DOTFHeadPose"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle"},{"value":"DOTFWearables","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments"},{"value":[{"text":"DOTFWearables","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle"},{"value":"DOTFFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}