{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)"},"metadata":{"symbolKind":"init","title":"init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"placeholderNormalizedRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxPenaltyThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDoesNotFitPlaceholderValidator(im)initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","navigatorTitle":[{"text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]]},"abstract":[{"text":"Initialize with custom penalty threshold and normalized placeholder rectangle.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"placeholderNormalizedRectangle"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"maxPenaltyThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":" = DocumentDoesNotFitPlaceholderValidator.defaultMaxPenaltyThreshold) ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"placeholderNormalizedRectangle","content":[{"inlineContent":[{"text":"Normalized placeholder rectangle.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Maximal accepted penalty in range [0, 1.0]."}]}],"name":"maxPenaltyThreshold"}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/init(placeholdernormalizedrectangle:maxpenaltythreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/init(placeholdernormalizedrectangle:maxpenaltythreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"placeholderNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"maxPenaltyThreshold"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator\/init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator\/init(placeholdernormalizedrectangle:maxpenaltythreshold:)","role":"symbol","type":"topic","title":"init(placeholderNormalizedRectangle:maxPenaltyThreshold:)","abstract":[{"type":"text","text":"Initialize with custom penalty threshold and normalized placeholder rectangle."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"title":"DocumentDoesNotFitPlaceholderValidator","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDoesNotFitPlaceholderValidator"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"type":"topic","url":"\/documentation\/dotdocument\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","title":"DocumentAutoCaptureController","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPlaceholderNormalizedRectangle:"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placeholderNormalizedRectangle"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxPenaltyThreshold:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"maxPenaltyThreshold"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1init(placeholderNormalizedRectangle:maxPenaltyThreshold:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithPlaceholderNormalizedRectangle:maxPenaltyThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator~1init(placeholderNormalizedRectangle:maxPenaltyThreshold:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","op":"replace","value":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}