{"kind":"symbol","metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"dateOfIssue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"endorsementsOrObservations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"taxOrExitRequirements"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"personalizationTime","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"13.0","name":"iOS","beta":false}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalDocumentDetails(im)initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","role":"symbol","roleHeading":"Initializer","title":"init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","navigatorTitle":[{"text":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}],"modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails"]]},"variants":[{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"issuingAuthority"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"dateOfIssue"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"endorsementsOrObservations","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"taxOrExitRequirements","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"personalizationTime","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalDocumentDetails/init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails\/init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","navigatorTitle":[{"kind":"identifier","text":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"issuingAuthority","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"dateOfIssue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"endorsementsOrObservations","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"taxOrExitRequirements"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"personalizationTime"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails\/init(issuingauthority:dateofissue:endorsementsorobservations:taxorexitrequirements:personalizationtime:personalizationdeviceserialnumber:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"title":"NfcTravelDocumentReader","type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","abstract":[{"text":"Result of NFC reading.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalDocumentDetails":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalDocumentDetails","abstract":[{"type":"text","text":"Contents of DG12 - Additional document details."}],"navigatorTitle":[{"text":"AdditionalDocumentDetails","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalDocumentDetails"}],"role":"symbol","url":"\/documentation\/dotnfc\/additionaldocumentdetails","kind":"symbol","title":"AdditionalDocumentDetails","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithIssuingAuthority:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"issuingAuthority","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dateOfIssue:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dateOfIssue","kind":"internalParam"},{"kind":"text","text":" "},{"text":"endorsementsOrObservations:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"endorsementsOrObservations"},{"text":" ","kind":"text"},{"kind":"identifier","text":"taxOrExitRequirements:"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"taxOrExitRequirements","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"personalizationTime:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"personalizationTime"},{"text":" ","kind":"text"},{"kind":"identifier","text":"personalizationDeviceSerialNumber:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"personalizationDeviceSerialNumber","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/title","value":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails~1init(issuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithIssuingAuthority:dateOfIssue:endorsementsOrObservations:taxOrExitRequirements:personalizationTime:personalizationDeviceSerialNumber:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"value":"DOTNAdditionalDocumentDetails","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/title"},{"value":[{"kind":"identifier","text":"DOTNAdditionalDocumentDetails"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalDocumentDetails\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}