{"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)detection","title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"detection","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/detection"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration","role":"symbol","title":"DotFaceDetectionModuleConfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/detection":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/detection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/detection","kind":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"detection"}],"title":"detection","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"title":"DotFaceLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]}]}]}