{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration\/init"},"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Instance Method","title":"init","role":"symbol"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotfaceverificationmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceVerificationModuleConfiguration":{"kind":"symbol","abstract":[{"text":"Face verification module.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration","title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/dotfaceverificationmoduleconfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFaceVerificationModuleConfiguration/init":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotdocument\/dotfaceverificationmoduleconfiguration\/init","abstract":[],"type":"topic","title":"init"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}