{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHD"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreset\/fullhd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreset\/fullhd"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/fullHD","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Outputs Full HD (1920x1080) video frames and enables Full HD (1920x1080) photo capture."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHD"}],"title":"CameraPreset.fullHD","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotDocument@E@DOTDCameraPreset@DOTDCameraPresetFullHD","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/fullHD":{"role":"symbol","title":"CameraPreset.fullHD","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullHD"}],"abstract":[{"type":"text","text":"Outputs Full HD (1920x1080) video frames and enables Full HD (1920x1080) photo capture."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/fullHD","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}],"url":"\/documentation\/dotdocument\/camerapreset\/fullhd"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset":{"role":"symbol","title":"CameraPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}],"url":"\/documentation\/dotdocument\/camerapreset"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDCameraPresetFullHD"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1fullHD\/title","value":"DOTDCameraPresetFullHD"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1fullHD\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetFullHD"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}