{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/camerapreset\/hd"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/camerapreset\/hd"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/hd","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Outputs HD (1280x720) video frames and enables HD (1280x720) photo capture."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hd"}],"title":"CameraPreset.hd","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotDocument@E@DOTDCameraPreset@DOTDCameraPresetHd","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetHd"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset":{"role":"symbol","title":"CameraPreset","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreset"}],"abstract":[{"type":"text","text":"Camera preset and video frame resolution."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreset"}],"url":"\/documentation\/dotdocument\/camerapreset"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreset/hd":{"role":"symbol","title":"CameraPreset.hd","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"hd"}],"abstract":[{"type":"text","text":"Outputs HD (1280x720) video frames and enables HD (1280x720) photo capture."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreset\/hd","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTDCameraPresetHd"}],"url":"\/documentation\/dotdocument\/camerapreset\/hd"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTDCameraPresetHd"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetHd"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTDCameraPresetHd"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/title","value":"DOTDCameraPreset"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPreset"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1hd\/title","value":"DOTDCameraPresetHd"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreset~1hd\/fragments","value":[{"kind":"identifier","text":"DOTDCameraPresetHd"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}