{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","symbolKind":"method","role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","text":"Libraries","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","interfaceLanguage":"occ"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration":{"url":"\/documentation\/dotfacecore\/dotsdkconfiguration","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"title":"DotSdkConfiguration","abstract":[{"type":"text","text":"The "},{"type":"text","text":"DotSdk"},{"type":"text","text":" configuration."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"url":"\/documentation\/dotfacecore\/libraries","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"title":"Libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"url":"\/documentation\/dotfacecore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","type":"topic","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle"}]}]}