{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration\/Balanced"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedCAEycfc","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration\/balanced\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration/Balanced":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration\/Balanced","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration.Balanced","navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration\/balanced","kind":"symbol","abstract":[{"type":"text","text":"Face detection balanced module."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration/Balanced/init()":{"role":"symbol","title":"init()","url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration\/balanced\/init()","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face detection module configuration."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/title"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}]}]}