{"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture:"},{"text":"(","kind":"text"},{"text":"DOTAutoCaptureConfiguration","preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"autoCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:qualityAttributeThresholds:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration"]]},"abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration/initWithCommon:camera:autoCapture:qualityAttributeThresholds:":{"title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration":{"url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"DOTPBasePalmAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTPBasePalmAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"title":"PalmAutoCaptureQualityAttributeThresholds","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/commonconfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"role":"symbol","abstract":[{"text":"Common configuration for all components.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]}]}]}