{"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@E@DotFaceModuleCategory@DotFaceModuleCategoryDetection","symbolKind":"case","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DotFaceModuleCategoryDetection","kind":"identifier"}],"roleHeading":"Case","title":"DotFaceModuleCategory.detection","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/detection"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategory\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/detection"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detection"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"text":"version: 8.13.0","type":"text"}],"role":"collection","type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory","navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" module category."}],"title":"DotFaceModuleCategory","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleCategory"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategory/detection":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detection"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategory\/detection","navigatorTitle":[{"text":"DotFaceModuleCategoryDetection","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodulecategory\/detection","title":"DotFaceModuleCategory.detection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","value":"DotFaceModuleCategoryDetection","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategoryDetection"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleCategoryDetection","kind":"identifier"}]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","value":"DotFaceModuleCategory","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"op":"replace"},{"value":"DotFaceModuleCategoryDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1detection\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategory~1detection\/fragments","value":[{"text":"DotFaceModuleCategoryDetection","kind":"identifier"}],"op":"replace"}]}]}