{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/from(cgpoint:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble\/from(cgpoint:)"]}],"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(cm)fromCgPoint:","role":"symbol","navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"title":"from(cgPoint:)","extendedModule":"DotCore","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/from(cgPoint:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/PointDouble/from(cgPoint:)":{"url":"\/documentation\/dotnfc\/pointdouble\/from(cgpoint:)","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/from(cgPoint:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"title":"from(cgPoint:)","role":"symbol","navigatorTitle":[{"text":"fromCgPoint:","kind":"identifier"}],"abstract":[]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/PointDouble":{"url":"\/documentation\/dotnfc\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"type":"topic","title":"PointDouble","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","kind":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"fromCgPoint:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cgPoint","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1from(cgPoint:)\/title","op":"replace","value":"fromCgPoint:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1from(cgPoint:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]}]}]}