{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","interfaceLanguage":"occ"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","modules":[{"name":"DotPalmCore"}],"symbolKind":"method","title":"initWithLicenseBytes:libraries:transactionCountingToken:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"licenseBytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","kind":"typeIdentifier","text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"libraries"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"abstract":[{"text":"Container for library configurations.","type":"text"}],"title":"Libraries","navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"url":"\/documentation\/dotpalmcore\/libraries","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","kind":"symbol","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}],"title":"DotSdkConfiguration","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"abstract":[],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle"}]}]}