{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration"]]},"abstract":[{"type":"text","text":"List of "},{"type":"codeVoice","code":"DotSdk"},{"text":" libraries to use.","type":"text"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"libraries","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(py)libraries","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"kind":"text","text":"]"}],"role":"symbol","navigatorTitle":[{"text":"libraries","kind":"identifier"}],"title":"libraries"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/libraries","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"abstract":[],"title":"DotLibrary","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","title":"DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"type":"topic","title":"DotSdkConfiguration","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration/libraries":{"type":"topic","abstract":[{"text":"List of ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" libraries to use."}],"navigatorTitle":[{"text":"libraries","kind":"identifier"}],"kind":"symbol","title":"libraries","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"]","kind":"text"}],"url":"\/documentation\/dotpalmcore\/dotsdkconfiguration\/libraries","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration\/libraries"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"libraries"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"libraries","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<id<DotLibrary>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"libraries","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibrary"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/title","value":"DotSdkConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/fragments","op":"replace"},{"value":"libraries","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1libraries\/title"},{"value":[{"kind":"identifier","text":"libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration~1libraries\/fragments"}]}]}