{"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/description"],"generated":true,"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/CustomStringConvertible-Implementations"},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"CustomStringConvertible Implementations","role":"collectionGroup","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZonePassword"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/description":{"title":"description","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/description","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"title":"MachineReadableZonePassword.Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]}]}]}