{"metadata":{"symbolKind":"property","title":"description","roleHeading":"Instance Property","extendedModule":"DotCore","externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:6DotNfc27MachineReadableZonePasswordC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.description","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/description":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/description","role":"symbol","title":"description","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/description","type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"title":"MachineReadableZonePassword","abstract":[{"type":"text","text":"Password from Machine Readable Zone."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"MachineReadableZonePassword.Error","abstract":[],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"op":"replace","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"op":"replace","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}