{"metadata":{"roleHeading":"Instance Property","symbolKind":"property","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"8.0","unavailable":false,"beta":false},{"beta":false,"unavailable":false,"name":"macOS","deprecated":false,"introducedAt":"10.10"},{"introducedAt":"9.0","unavailable":false,"beta":false,"deprecated":false,"name":"tvOS"},{"name":"watchOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"2.0"}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:6DotNfc27MachineReadableZonePasswordC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"extendedModule":"Foundation","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/failureReason"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/failurereason"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZonePassword/Error/LocalizedError-Implementations":{"abstract":[],"kind":"article","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizederror-implementations","role":"collectionGroup"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"title":"MachineReadableZonePassword.Error","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZonePassword":{"title":"MachineReadableZonePassword","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword","abstract":[{"type":"text","text":"Password from Machine Readable Zone."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZonePassword/Error/failureReason":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"failureReason"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/failureReason","type":"topic","abstract":[],"title":"failureReason","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/failurereason","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"op":"replace","value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}]}]}]}