{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddocumentnumber(internalerror:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDocumentNumber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"modules":[{"name":"DotNfc"}],"externalID":"s:6DotNfc27MachineReadableZonePasswordC5ErrorO21invalidDocumentNumberyAEsAD_p_tcAEmF","title":"MachineReadableZonePassword.Error.invalidDocumentNumber(internalError:)","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDocumentNumber"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"role":"symbol","symbolKind":"case"},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDocumentNumber(internalError:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword","kind":"symbol","title":"MachineReadableZonePassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/invalidDocumentNumber(internalError:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddocumentnumber(internalerror:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDocumentNumber(internalError:)","type":"topic","title":"MachineReadableZonePassword.Error.invalidDocumentNumber(internalError:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDocumentNumber","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"title":"NfcTravelDocumentReader","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","type":"topic","title":"MachineReadableZonePassword.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}