{"metadata":{"role":"collectionGroup","title":"LocalizedError Implementations","modules":[{"name":"DotNfc"}]},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorDescription","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/failureReason","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/helpAnchor","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/recoverySuggestion"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/localizederror-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/LocalizedError-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"kind":"article","references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/recoverySuggestion":{"type":"topic","title":"recoverySuggestion","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/recoverysuggestion","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/recoverySuggestion"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/errorDescription":{"title":"errorDescription","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/errorDescription","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/errordescription","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/helpAnchor":{"abstract":[],"title":"helpAnchor","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/helpAnchor","kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/helpanchor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZonePassword"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZonePassword"}],"abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/failureReason":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/failureReason","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"abstract":[],"title":"failureReason","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/failurereason"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"title":"MachineReadableZonePassword.Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}]}]}