{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble"},{"text":" = Defaults.faceSizeRatioInterval, ","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isDetectionLayerVisible, ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isVideoCaptureEnabled, ","kind":"text"},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","text":"CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","text":"CameraPreviewScaleType","kind":"typeIdentifier"},{"text":" = Defaults.cameraPreviewScaleType, ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = Defaults.isCameraPreviewVisible)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"text":", ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"title":"init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","role":"symbol","roleHeading":"Initializer","externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC12sessionToken21faceSizeRatioInterval5query23isDetectionLayerVisible0P12TorchEnabled0p12VideoCaptureU012cameraFacing0X16PreviewScaleType0p6CamerazS0AESSSg_0aC00N6DoubleCAA0bQ5QueryCS3b0A6Camera06CameraY0OAU06CameraZ9ScaleTypeOSbtcfc","symbolKind":"init","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"sections":[],"abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"text":": ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":", "},{"text":"isCameraPreviewVisible","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Create the smile liveness configuration."}],"type":"topic","role":"symbol","title":"init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:)"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol","title":"SmileLivenessViewController.Configuration","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"role":"symbol","title":"IntervalDouble","type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","role":"symbol","title":"FaceDetectionQuery","url":"\/documentation\/dotfacecore\/facedetectionquery","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"role":"symbol","type":"topic","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing","url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","type":"topic","title":"SmileLivenessViewController","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}