{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled"]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DotSdkLicenseProxy(py)isFaceEyeGazeLivenessScoreEnabled","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"symbolKind":"property","title":"isFaceEyeGazeLivenessScoreEnabled"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isFaceEyeGazeLivenessScoreEnabled","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy":{"title":"DotSdkLicenseProxy","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","abstract":[],"title":"isFaceEyeGazeLivenessScoreEnabled"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotSdkLicenseProxy","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/title"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/fragments","op":"replace"},{"value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}