{"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"],"title":"Converting images","generated":true,"anchor":"Converting-images"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"title":"Image"},"sections":[],"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/init(format:bytes:size:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/bytes","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/format","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/size"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotfacelite\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"navigatorTitle":[{"kind":"identifier","text":"Image"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"type":"topic","abstract":[],"title":"Image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","kind":"symbol","url":"\/documentation\/dotfacelite\/image","role":"symbol"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/Image/size":{"role":"symbol","abstract":[{"text":"Image size.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"navigatorTitle":[{"kind":"identifier","text":"size"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/size","url":"\/documentation\/dotfacelite\/image\/size","kind":"symbol","type":"topic","title":"size"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory":{"role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","url":"\/documentation\/dotfacelite\/imagefactory","kind":"symbol","type":"topic","title":"ImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory":{"role":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","url":"\/documentation\/dotfacelite\/cgimagefactory","kind":"symbol","type":"topic","title":"CGImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/Image/bytes":{"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/bytes","type":"topic","abstract":[{"text":"Raw image data.","type":"text"}],"kind":"symbol","title":"bytes","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"}],"url":"\/documentation\/dotfacelite\/image\/bytes"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/Image/init(format:bytes:size:)":{"url":"\/documentation\/dotfacelite\/image\/init(format:bytes:size:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/init(format:bytes:size:)","kind":"symbol","abstract":[],"title":"init(format:bytes:size:)"},"doc://DotFaceLite/documentation/DotFaceLite/Image/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","abstract":[],"title":"description","kind":"symbol","url":"\/documentation\/dotfacelite\/image\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/description","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory":{"url":"\/documentation\/dotfacelite\/ciimagefactory","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory","kind":"symbol","navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":".","type":"text"}],"title":"CIImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/Image/format":{"navigatorTitle":[{"text":"format","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/format","type":"topic","abstract":[{"text":"Format of the stored image","type":"text"}],"kind":"symbol","title":"format","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/image\/format"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/bytes","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/format","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image\/size"],"generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"],"anchor":"Converting-images","generated":true,"title":"Converting images"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1size\/title","value":"size","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1size\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/title","value":"DOTImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/navigatorTitle","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1bytes\/title","value":"bytes","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1format\/title","op":"replace","value":"format"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image~1format\/fragments","op":"replace","value":[{"kind":"identifier","text":"format"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}