{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration\/init"},"metadata":{"title":"init","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration(im)init","roleHeading":"Instance Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration/init":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration\/init","abstract":[],"title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFacePassiveLivenessModuleConfiguration":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFacePassiveLivenessModuleConfiguration","abstract":[{"type":"text","text":"Face passive liveness module."}],"title":"DotFacePassiveLivenessModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacepassivelivenessmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration","op":"replace"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}