{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/confidencethreshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/confidencethreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator\/confidenceThreshold","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"confidenceThreshold","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentNotDetectedValidator(py)confidenceThreshold","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"confidenceThreshold"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator/confidenceThreshold":{"role":"symbol","title":"confidenceThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator\/confidenceThreshold","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"confidenceThreshold"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/confidencethreshold"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentNotDetectedValidator":{"role":"symbol","title":"DocumentNotDetectedValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"abstract":[{"type":"text","text":"Defines a confidence threshold for document detection."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"confidenceThreshold"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"confidenceThreshold"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidenceThreshold"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator~1confidenceThreshold\/title","value":"confidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator~1confidenceThreshold\/fragments","value":[{"kind":"identifier","text":"confidenceThreshold"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDocumentNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTDocumentNotDetectedValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}