{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult\/detection","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The result of processing image during the fingers auto capture process.","type":"text"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureControllerProcessingResult(py)detection","symbolKind":"property","fragments":[{"kind":"identifier","text":"detection"}],"title":"detection","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"detection"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","text":"DOTFGFingersAutoCaptureDetection"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerProcessingResult":{"fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureControllerProcessingResult"}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult","title":"DOTFGFingersAutoCaptureControllerProcessingResult","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureControllerProcessingResult/detection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureControllerProcessingResult\/detection","fragments":[{"text":"detection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"detection","abstract":[{"type":"text","text":"The result of processing image during the fingers auto capture process."}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturecontrollerprocessingresult\/detection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}