{"kind":"symbol","metadata":{"roleHeading":"Initializer","symbolKind":"init","title":"init(rawLines:travelDocumentType:machineReadableZone:error:)","externalID":"s:11DotDocument9MrzReaderC6ResultC8rawLines06travelB4Type19machineReadableZone5errorAESaySSG_0aB7Commons06TravelbI7WrapperCSgAK07MachinekL0CSgAC12ReadingErrorCSgtcfc","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"rawLines","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"text":"travelDocumentType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone"},{"kind":"text","text":"?, "},{"text":"error","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ReadingError","preciseIdentifier":"s:11DotDocument9MrzReaderC12ReadingErrorC","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"DotDocument"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/mrzreader\/result\/init(rawlines:traveldocumenttype:machinereadablezone:error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawLines"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?, "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ReadingError","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","preciseIdentifier":"s:11DotDocument9MrzReaderC12ReadingErrorC"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/init(rawLines:travelDocumentType:machineReadableZone:error:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","kind":"symbol","title":"TravelDocumentTypeWrapper","role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/init(rawLines:travelDocumentType:machineReadableZone:error:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?, "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ReadingError","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument9MrzReaderC12ReadingErrorC"},{"text":"?)","kind":"text"}],"abstract":[],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/result\/init(rawlines:traveldocumenttype:machinereadablezone:error:)","title":"init(rawLines:travelDocumentType:machineReadableZone:error:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/init(rawLines:travelDocumentType:machineReadableZone:error:)"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/mrzreader\/result","title":"MrzReader.Result","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ReadingError"}],"abstract":[{"type":"text","text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"ReadingError","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader\/readingerror","title":"MrzReader.ReadingError","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/machinereadablezone","title":"MachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]}]}]}