{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/detectionAreaImageSize","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/detectionareaimagesize"]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/detectionareaimagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Image size of the detection area."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"detectionAreaImageSize","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(py)detectionAreaImageSize","navigatorTitle":[{"kind":"identifier","text":"detectionAreaImageSize"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/detectionAreaImageSize":{"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/detectionAreaImageSize","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/detectionareaimagesize","title":"detectionAreaImageSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"detectionAreaImageSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"detectionAreaImageSize"}],"abstract":[{"type":"text","text":"Image size of the detection area."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","title":"FaceAutoCaptureFrameParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","navigatorTitle":[{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Information from the detection process about the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/imagesize","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","title":"ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.13.0"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectionAreaImageSize","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectionAreaImageSize"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"DOTImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":" * ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1detectionAreaImageSize\/title","value":"detectionAreaImageSize","op":"replace"},{"value":[{"kind":"identifier","text":"detectionAreaImageSize"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1detectionAreaImageSize\/fragments","op":"replace"},{"op":"replace","value":"DOTFLFaceAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}