{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face","text":"Face","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles"},{"text":"?)","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(face:devicetiltangles:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(face:devicetiltangles:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(im)initWithFace:deviceTiltAngles:","navigatorTitle":[{"text":"initWithFace:deviceTiltAngles:","kind":"identifier"}],"title":"init(face:deviceTiltAngles:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"text":"?)","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(face:deviceTiltAngles:)"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/TiltAngles":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/tiltangles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"title":"TiltAngles"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Face":{"navigatorTitle":[{"text":"Face","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Detected face.","type":"text"}],"title":"FaceDetector.Face","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector\/face","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/init(face:deviceTiltAngles:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(face:deviceTiltAngles:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"init(face:deviceTiltAngles:)","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(face:devicetiltangles:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFace:deviceTiltAngles:"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"title":"DOTFLFaceDetectorFace","kind":"symbol","type":"topic","fragments":[{"text":"DOTFLFaceDetectorFace","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflfacedetectorface","abstract":[{"type":"text","text":"Detected face."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"title":"FaceAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.4.1"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithFace:deviceTiltAngles:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithFace:deviceTiltAngles:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithFace:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","text":"DOTFLFaceDetectorFace"},{"kind":"text","text":" *) "},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deviceTiltAngles:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","text":"DOTTiltAngles","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"deviceTiltAngles","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"value":"initWithFace:deviceTiltAngles:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(face:deviceTiltAngles:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(face:deviceTiltAngles:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFace:deviceTiltAngles:"}],"op":"replace"},{"value":"DOTFLFaceAutoCaptureFrameParameters","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTFLFaceAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}