{"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"TiltAngles"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","kind":"identifier"}],"title":"init(detectionAreaImageSize:face:deviceTiltAngles:)","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(im)initWithDetectionAreaImageSize:face:deviceTiltAngles:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":", "},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","text":"TiltAngles"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(detectionareaimagesize:face:devicetiltangles:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(detectionareaimagesize:face:devicetiltangles:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(detectionAreaImageSize:face:deviceTiltAngles:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"type":"topic","navigatorTitle":[{"text":"Face","kind":"identifier"}],"title":"FaceDetector.Face","abstract":[{"text":"Detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector\/face"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/init(detectionAreaImageSize:face:deviceTiltAngles:)":{"kind":"symbol","type":"topic","title":"init(detectionAreaImageSize:face:deviceTiltAngles:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","text":"FaceDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"TiltAngles","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/init(detectionareaimagesize:face:devicetiltangles:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/init(detectionAreaImageSize:face:deviceTiltAngles:)","navigatorTitle":[{"text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","abstract":[{"text":"Information from the detection process about the detected face.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureFrameParameters"}],"title":"FaceAutoCaptureFrameParameters"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","url":"\/documentation\/dotfacelite\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"title":"ImageSize"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"type":"topic","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"type":"topic","title":"FaceAutoCaptureController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"title":"TiltAngles","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","url":"\/documentation\/dotfacelite\/tiltangles","abstract":[{"text":"Tilt angles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"type":"topic","title":"DOTFLFaceDetectorFace","abstract":[{"text":"Detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorFace"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetectionAreaImageSize:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"DOTImageSize"},{"kind":"text","text":" *) "},{"text":"detectionAreaImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace","text":"DOTFLFaceDetectorFace"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"text":"deviceTiltAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTTiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles"},{"kind":"text","text":" *) "},{"text":"deviceTiltAngles","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(detectionAreaImageSize:face:deviceTiltAngles:)\/title","value":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDetectionAreaImageSize:face:deviceTiltAngles:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1init(detectionAreaImageSize:face:deviceTiltAngles:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","value":"DOTFLFaceAutoCaptureFrameParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","op":"replace","value":"DOTFLFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","op":"replace"},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","op":"replace","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}