{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rebased","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/rectangledouble\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/rectangledouble\/rebased(parentrectangle:)"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/rebased(parentRectangle:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"title":"rebased(parentRectangle:)","modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(im)rebasedWithParentRectangle:"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","title":"RectangleDouble","role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble/rebased(parentRectangle:)":{"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"title":"rebased(parentRectangle:)","url":"\/documentation\/dotpalmcore\/rectangledouble\/rebased(parentrectangle:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble\/rebased(parentRectangle:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"rebasedWithParentRectangle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1rebased(parentRectangle:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]}]}]}