{"sections":[],"abstract":[{"type":"text","text":"Current configuration."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.property"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/configuration-swift.property","interfaceLanguage":"swift"},"metadata":{"title":"configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(py)configuration","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","title":"DocumentAutoCaptureViewController.Configuration","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/configuration-swift.property":{"role":"symbol","title":"configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/configuration-swift.property","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.property","type":"topic","abstract":[{"text":"Current configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.9.0","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"title":"DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"title":"DOTDDocumentAutoCaptureConfiguration","url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","value":"configuration","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"configuration"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTDDocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"configuration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1configuration-swift.property\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1configuration-swift.property\/fragments","value":[{"kind":"identifier","text":"configuration"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}