{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration","text":"DocumentAutoCaptureConfiguration"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle","text":"DocumentAutoCaptureStyle"},{"kind":"text","text":" = .init()) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DocumentAutoCaptureViewController"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New instance of "},{"type":"codeVoice","code":"DocumentAutoCaptureViewController"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the document auto capture process."}]}]},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/create(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/create(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/create(configuration:style:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"DocumentAutoCaptureViewController"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureStyle","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"}],"title":"create(configuration:style:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(cm)createWithConfiguration:style:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:style:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/create(configuration:style:)":{"role":"symbol","title":"create(configuration:style:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureStyle","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"DocumentAutoCaptureViewController"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/create(configuration:style:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithConfiguration:style:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/create(configuration:style:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureStyle":{"role":"symbol","title":"DocumentAutoCaptureStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureStyle"}],"abstract":[{"type":"text","text":"Customization options for the document auto capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureStyle"}],"url":"\/documentation\/dotdocument\/documentautocapturestyle"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithConfiguration:style:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:style:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController","text":"DOTDDocumentAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration","text":"DOTDDocumentAutoCaptureConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"style:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureStyle","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle","text":"DOTDDocumentAutoCaptureStyle"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1create(configuration:style:)\/title","value":"createWithConfiguration:style:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1create(configuration:style:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithConfiguration:style:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureStyle\/title","value":"DOTDDocumentAutoCaptureStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureStyle\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureStyle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}