{"kind":"symbol","metadata":{"symbolKind":"property","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(py)delegate","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"roleHeading":"Instance Property","role":"symbol"},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/delegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"weak","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate","text":"DocumentAutoCaptureViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"abstract":[{"type":"text","text":"Set this delegate to handle the document auto capture events."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/delegate"]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"title":"DocumentAutoCaptureViewController","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"role":"symbol","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewControllerDelegate":{"title":"DocumentAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewControllerDelegate","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontrollerdelegate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewControllerDelegate","abstract":[{"text":"Implement this delegate to handle the document auto capture events.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewControllerDelegate"}],"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/delegate":{"title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate","text":"DocumentAutoCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/delegate","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/delegate","abstract":[{"text":"Set this delegate to handle the document auto capture events.","type":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"delegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"delegate","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"weak"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureViewControllerDelegate","text":"id<DOTDDocumentAutoCaptureViewControllerDelegate>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"delegate"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"value":"DOTDDocumentAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1delegate\/title","op":"replace","value":"delegate"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}]}]}]}