{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/initwithnibname:bundle:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/initWithNibName:bundle:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"title":"initWithNibName:bundle:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureViewController(im)initWithNibName:bundle:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/initwithnibname:bundle:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}