{"sections":[],"abstract":[{"type":"text","text":"Start the document auto capture process."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/start()"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(im)start","roleHeading":"Instance Method","title":"start()","navigatorTitle":[{"kind":"identifier","text":"start"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/start()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/start()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/start()":{"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/start()","kind":"symbol","abstract":[{"text":"Start the document auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"title":"start()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/start()","navigatorTitle":[{"kind":"identifier","text":"start"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"kind":"symbol","type":"topic","title":"DocumentAutoCaptureViewController","role":"symbol","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"start","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"start","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"start","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1start()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1start()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}