{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Current style."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(py)style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC","text":"Style"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"style","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"title":"style","symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/style-swift.property","interfaceLanguage":"swift"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class":{"title":"DocumentAutoCaptureViewController.Style","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}],"kind":"symbol","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureStyle":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureStyle"}],"title":"DOTDDocumentAutoCaptureStyle","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureStyle","url":"\/documentation\/dotdocument\/dotddocumentautocapturestyle","kind":"symbol","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/style-swift.property":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"style"}],"abstract":[{"type":"text","text":"Current style."}],"title":"style","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.property","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/style-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"abstract":[{"text":"UI Document Auto Capture component","type":"text"},{"text":" ","type":"text"},{"text":"A visual component for capturing good quality document images suitable for optical character recognition. This component provides an UI.","type":"text"},{"text":" ","type":"text"},{"text":"It includes a placeholder for the document, a detection layer that displays the tracking rectangle and an instruction.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"style","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTDDocumentAutoCaptureStyle","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureStyle","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureStyle"},{"text":" * ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1style-swift.property\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]}]}]}