{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidDisappear(_:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdiddisappear(_:)"]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","externalID":"c:@CM@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(im)viewDidDisappear:","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"modules":[{"name":"DotDocument"}],"symbolKind":"method","title":"viewDidDisappear(_:)"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/viewDidDisappear(_:)":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/viewDidDisappear(_:)","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/viewdiddisappear(_:)","kind":"symbol","title":"viewDidDisappear(_:)","abstract":[]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","title":"DocumentAutoCaptureViewController","kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"viewDidDisappear:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidDisappear:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidDisappear(_:)\/title","value":"viewDidDisappear:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1viewDidDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace","value":"DOTDDocumentAutoCaptureViewController"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}