{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/detection"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","kind":"typeIdentifier","text":"DOTFGFingersAutoCaptureDetection"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detection"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/detection"]}],"metadata":{"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateRunning(py)detection","modules":[{"name":"DotFingersCore"}],"navigatorTitle":[{"text":"detection","kind":"identifier"}],"title":"detection","symbolKind":"property","role":"symbol","fragments":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property"},"kind":"symbol","abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning/detection":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/detection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/detection","title":"detection","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"kind":"symbol","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning","title":"DOTFGFingersAutoCaptureUiStateRunning","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning","abstract":[{"text":"Running state.","type":"text"},{"type":"text","text":" "},{"text":"This state is active after the ","type":"text"},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"role":"symbol","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateRunning","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"kind":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","op":"replace","value":"DOTFGFingersAutoCaptureDetection"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}