{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/hash"},"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"title":"hash","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC4hashSivp","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholder\/visible\/hash"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible/hash":{"title":"hash","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/hash","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/placeholder\/visible\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"url":"\/documentation\/dotfacelite\/placeholder","type":"topic","abstract":[{"type":"text","text":"Placeholder."}],"role":"symbol","title":"Placeholder","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Placeholder"}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"title":"Placeholder.Visible","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","abstract":[{"type":"text","text":"Visible placeholder."}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/placeholder\/visible","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title"},{"value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments"},{"value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle"}]}]}