{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholder\/visible\/isequal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"]]},"kind":"symbol","metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC7isEqualySbypSgF","title":"isEqual(_:)","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/isEqual(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotfacelite\/placeholder","role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"abstract":[{"text":"Placeholder.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible/isEqual(_:)":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/placeholder\/visible\/isequal(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/isEqual(_:)","type":"topic","title":"isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"url":"\/documentation\/dotfacelite\/placeholder\/visible","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"Visible","kind":"identifier"}],"abstract":[{"type":"text","text":"Visible placeholder."}],"title":"Placeholder.Visible"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","value":"DOTPlaceholder"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","value":[{"text":"DOTPlaceholder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}