{"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults"],"title":"Structures","generated":true,"anchor":"Structures"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:captureMode:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/autoCapture","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/camera","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/common","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"]]},"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLBaseFaceAutoCaptureConfiguration) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"BaseFaceAutoCaptureViewController.Configuration","extendedModule":"DotFaceLite","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","roleHeading":"Class","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/init(common:camera:autoCapture:qualityAttributeThresholds:captureMode:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:captureMode:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"camera","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"captureMode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:qualityattributethresholds:capturemode:)","title":"init(common:camera:autoCapture:qualityAttributeThresholds:captureMode:)","abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/autoCapture":{"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"kind":"symbol","title":"autoCapture","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/autoCapture","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/autocapture","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"code":".standard","type":"codeVoice"},{"type":"text","text":" preset."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/qualityattributethresholds","title":"qualityAttributeThresholds"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/defaults","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"abstract":[],"title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/camera":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/camera","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/camera","title":"camera","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"kind":"symbol","type":"topic","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/common":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/common","title":"common","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/common","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}]},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/description":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/description","title":"description","role":"symbol","kind":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/init()":{"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/init()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/init()","role":"symbol","type":"topic","title":"init()","kind":"symbol","abstract":[{"text":"Create the face auto capture configuration with default values.","type":"text"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"title":"BaseFaceAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/captureMode":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/captureMode","kind":"symbol","role":"symbol","title":"captureMode","abstract":[{"text":"Capture mode. Default value is ","type":"text"},{"code":".autoCapture","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/capturemode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier","text":"CaptureMode"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"}]}]}