{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Create new ","type":"text"},{"code":"BaseFaceAutoCaptureViewController","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/create(baseConfiguration:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"baseConfiguration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":" = .init()) -> ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"baseConfiguration","content":[{"inlineContent":[{"text":"Configure the capture process.","type":"text"}],"type":"paragraph"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"createWithBaseConfiguration:"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController(cm)createWithBaseConfiguration:","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController"}],"role":"symbol","title":"create(baseConfiguration:)"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"role":"symbol","title":"BaseFaceAutoCaptureViewController.Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","title":"BaseFaceAutoCaptureViewController","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/create(baseConfiguration:)":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"baseConfiguration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"text":") -> ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController"}],"abstract":[{"text":"Create new ","type":"text"},{"code":"BaseFaceAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/create(baseconfiguration:)","navigatorTitle":[{"text":"createWithBaseConfiguration:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/create(baseConfiguration:)","role":"symbol","title":"create(baseConfiguration:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"type":"topic","fragments":[{"text":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","role":"symbol","title":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"createWithBaseConfiguration:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"createWithBaseConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"baseConfiguration","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"baseConfiguration","content":[{"type":"paragraph","inlineContent":[{"text":"Configure the capture process.","type":"text"}]}]}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"DOTFLBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"createWithBaseConfiguration:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1create(baseConfiguration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1create(baseConfiguration:)\/fragments"}]}]}