{"sections":[],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController(im)start","symbolKind":"method","title":"start()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"start"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/start()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Start the face auto capture process."}],"variants":[{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/start()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/start()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/start()":{"title":"start()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/start()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"start"}],"abstract":[{"type":"text","text":"Start the face auto capture process."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/start()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"kind":"text","text":"()"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"title":"BaseFaceAutoCaptureViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","navigatorTitle":[{"text":"BaseFaceAutoCaptureViewController","kind":"identifier"}],"type":"topic","abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"start","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"start","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1start()\/title","value":"start","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController~1start()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"start","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","value":"DOTFLBaseFaceAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}