{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/init(modules:)"]},{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/init(modules:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","text":"DotFaceModule","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier","text":"DotFaceModule"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"title":"DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","abstract":[{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" feature module."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotFaceModule","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","title":"DotFaceLibraryConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibrary","title":"DotFaceLibrary","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibrary"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"kind":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library initialization."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/init(modules:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/init(modules:)","title":"init(modules:)","kind":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modules"},{"text":": [","kind":"text"},{"text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/init(modules:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithModules:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"initWithModules:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithModules:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotFaceModule>>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"value":[{"kind":"identifier","text":"DotFaceModule"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"value":"DotFaceLibrary","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibrary"}]},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1init(modules:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}