{"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"],"title":"Type Methods"}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}],"title":"BezierPathFactory","modules":[{"name":"DotNfc"}],"roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTBezierPathFactory","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTBezierPathFactory) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BezierPathFactory"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bezierpathfactory"]},{"paths":["\/documentation\/dotnfc\/bezierpathfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"references":{"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","url":"\/documentation\/dotnfc\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","role":"symbol","navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"title":"createDetectionPath(corners:cornerRadius:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"corners"},{"text":": ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}],"title":"BezierPathFactory","url":"\/documentation\/dotnfc\/bezierpathfactory","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory","navigatorTitle":[{"text":"BezierPathFactory","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","url":"\/documentation\/dotnfc\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","role":"symbol","navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"title":"createPlaceholderPath(rect:cornerRadius:)","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPath"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTBezierPathFactory","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTBezierPathFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","op":"replace","value":"createDetectionPathWithCorners:cornerRadius:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/title","op":"replace","value":"DOTBezierPathFactory"},{"value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/fragments"},{"value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"op":"replace"}]}]}