{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result"]]},"metadata":{"title":"score","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"externalID":"s:11DotFaceCore0B7MatcherC6ResultC5scoreSdvp","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceCore"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result\/score","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facematcher\/result\/score"]}],"abstract":[{"text":"Face matching score.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Result":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"text":"Result","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}],"abstract":[{"text":"Face matcher result.","type":"text"}],"url":"\/documentation\/dotfacecore\/facematcher\/result","title":"FaceMatcher.Result"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Result/score":{"title":"score","type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/result\/score","kind":"symbol","abstract":[{"text":"Face matching score.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result\/score"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"type":"topic","navigatorTitle":[{"text":"FaceMatcher","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/facematcher","abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"title":"FaceMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFFaceMatcher","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title"},{"value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle"}]}]}