{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wrappedfloat\/init(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedfloat\/init(value:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/init(value:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"kind":"text","text":")"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(im)initWithValue:","symbolKind":"init","title":"init(value:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":" value for Objective-C support.","type":"text"}],"kind":"symbol","title":"WrappedFloat","type":"topic","url":"\/documentation\/dotfacecore\/wrappedfloat","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"role":"collection","title":"DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat/init(value:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"init(value:)","type":"topic","url":"\/documentation\/dotfacecore\/wrappedfloat\/init(value:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat\/init(value:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithValue:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/title","value":"DOTWrappedFloat","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat~1init(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}