{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedFloat\/isEqual(_:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedFloat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wrappedfloat\/isequal(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wrappedfloat\/isequal(_:)"]}],"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTWrappedFloat(im)isEqual:","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isEqual(_:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedFloat/isEqual(_:)":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedFloat\/isEqual(_:)","title":"isEqual(_:)","url":"\/documentation\/dotfacecore\/wrappedfloat\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedFloat":{"abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedFloat","title":"WrappedFloat","url":"\/documentation\/dotfacecore\/wrappedfloat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedFloat"}],"navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedFloat~1isEqual(_:)\/title","value":"isEqual:"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedFloat~1isEqual(_:)\/fragments"},{"op":"replace","value":"DOTWrappedFloat","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedFloat\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedFloat\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}