{"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"]]},"kind":"symbol","sections":[],"metadata":{"title":"init()","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator(im)init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init()","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init()"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"type":"text","text":"version: 8.15.2"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/init()":{"title":"init()","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init()","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments"},{"value":"init","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}]}]}