{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Builder for ","type":"text"},{"code":"FingersAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"title":"FingersAutoCaptureQualityAttributeThresholds.Builder","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"externalID":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","symbolKind":"class","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingersAutoCaptureQualityAttributeThresholdsBuilder) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/init()"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/build()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/fingers(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/minFingerCount(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/init()":{"title":"init()","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/init()"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder":{"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder","abstract":[{"text":"Builder for ","type":"text"},{"code":"FingersAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Builder","kind":"identifier"}],"navigatorTitle":[{"text":"Builder","kind":"identifier"}],"title":"FingersAutoCaptureQualityAttributeThresholds.Builder","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/sizeInterval(_:)":{"role":"symbol","title":"sizeInterval(_:)","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/sizeinterval(_:)","abstract":[{"text":"Set the size interval threshold.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier","text":"Builder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/sizeInterval(_:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/minConfidence(_:)":{"type":"topic","kind":"symbol","title":"minConfidence(_:)","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/minconfidence(_:)","abstract":[{"text":"Set the minimum confidence threshold. Default is 0.6.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/minConfidence(_:)"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/fingers(_:)":{"role":"symbol","title":"fingers(_:)","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/fingers(_:)","abstract":[{"text":"Set the per-finger sharpness thresholds.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"},{"kind":"text","text":"("},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC0B0C","kind":"typeIdentifier","text":"Fingers"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier","text":"Builder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/fingers(_:)","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/minFingerCount(_:)":{"role":"symbol","title":"minFingerCount(_:)","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/minfingercount(_:)","abstract":[{"text":"Set the minimum finger count threshold. Default is 4.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFingerCount"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier","text":"Builder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/minFingerCount(_:)","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder/build()":{"role":"symbol","title":"build()","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder\/build()","abstract":[{"text":"Build the ","type":"text"},{"code":"FingersAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"build"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder\/build()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}]}]}]}