{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"kind":"text","text":"?"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/sizeinterval"]},{"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/sizeinterval"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"sizeInterval","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds(py)sizeInterval","roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"sizeInterval","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"property"},"abstract":[{"type":"text","text":"Valid fingers size interval."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/sizeInterval","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfingerscore\/intervaldouble","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/sizeInterval":{"kind":"symbol","title":"sizeInterval","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/sizeinterval","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"sizeInterval","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Valid fingers size interval."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/sizeInterval"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sizeInterval","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"sizeInterval"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"DOTIntervalDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/navigatorTitle"},{"value":"sizeInterval","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1sizeInterval\/title"},{"value":[{"kind":"identifier","text":"sizeInterval"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1sizeInterval\/fragments"}]}]}