{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfingersmoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingersmoduleid"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"kind":"relationships","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"metadata":{"title":"DotFingersModuleId","role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotFingersModuleId","symbolKind":"enum","roleHeading":"Enumeration"},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/detection","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/transformation"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/init(rawValue:)"],"generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/description"],"generated":true,"title":"Instance Properties"},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/RawRepresentable-Implementations"},"doc://DotNfc/SY":{"identifier":"doc:\/\/DotNfc\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/init(rawValue:)":{"title":"init(rawValue:)","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/init(rawValue:)"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article","abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/equatable-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/Equatable-Implementations"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/detection":{"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/detection","url":"\/documentation\/dotnfc\/dotfingersmoduleid\/detection","title":"DotFingersModuleId.detection","type":"topic"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/transformation":{"title":"DotFingersModuleId.transformation","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/transformation","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/transformation"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId":{"url":"\/documentation\/dotnfc\/dotfingersmoduleid","type":"topic","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"role":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId","kind":"symbol","title":"DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotFingersModuleId/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotfingersmoduleid\/description","type":"topic","title":"description","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/detection","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersModuleId\/transformation"],"generated":true,"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1detection\/title","value":"DotFingersModuleIdDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1detection\/fragments","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1transformation\/title","value":"DotFingersModuleIdTransformation"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId~1transformation\/fragments","value":[{"text":"DotFingersModuleIdTransformation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]}]}]}