{"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class"],"generated":true,"anchor":"Classes","title":"Classes"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/init(modules:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/modules-swift.property"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"metadata":{"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"modules":[{"name":"DotNfc"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotfingerslibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"Fingers library configuration."}],"references":{"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/modules-swift.property":{"type":"topic","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.property","navigatorTitle":[{"text":"modules","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Module configuration.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/modules-swift.property","kind":"symbol","title":"modules","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/init(modules:)":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"kind":"symbol","title":"init(modules:)","url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/init(modules:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers library configuration.","type":"text"}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration","type":"topic","title":"DotFingersLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/DotFingersLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/Modules-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Fingers library module configuration."}],"url":"\/documentation\/dotnfc\/dotfingerslibraryconfiguration\/modules-swift.class","type":"topic","title":"DotFingersLibraryConfiguration.Modules","kind":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}]},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersLibraryConfiguration\/init(modules:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1modules-swift.property\/title","value":"modules","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments","value":[{"kind":"identifier","text":"modules"}],"op":"replace"},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1init(modules:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration~1init(modules:)\/fragments"},{"value":"DotFingersLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersLibraryConfiguration\/navigatorTitle"}]}]}