{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","title":"brightness","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality(py)brightness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"brightness"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/brightness","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentimagequality\/brightness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentimagequality\/brightness"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"]]},"abstract":[{"text":"Brightness value in range [0, 1.0].","type":"text"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentImageQuality/brightness":{"url":"\/documentation\/dotdocument\/documentimagequality\/brightness","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","abstract":[{"type":"text","text":"Brightness value in range [0, 1.0]."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality\/brightness","navigatorTitle":[{"text":"brightness","kind":"identifier"}],"kind":"symbol","title":"brightness"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"abstract":[{"type":"text","text":"Document image quality."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentImageQuality"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","title":"DocumentImageQuality","url":"\/documentation\/dotdocument\/documentimagequality","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentImageQuality"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"brightness","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"brightness"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"brightness","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1brightness\/title"},{"op":"replace","value":[{"text":"brightness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality~1brightness\/fragments"},{"op":"replace","value":"DOTDDocumentImageQuality","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentImageQuality"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle"}]}]}