{"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:"},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:"}],"role":"symbol","symbolKind":"method","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","navigatorTitle":[{"kind":"identifier","text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","modules":[{"name":"DotDocument"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" *) ","kind":"text"},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"camera:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"camera","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration","text":"DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"autoCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validationMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","text":"DOTDValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validationMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mrzValidation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","text":"DOTDMrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"mrzValidation","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"references":{"doc://DotDocument/documentation/DotDocument/ValidationMode":{"url":"\/documentation\/dotdocument\/validationmode","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationMode","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"title":"ValidationMode","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","abstract":[]},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","kind":"identifier"}],"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:","kind":"symbol","navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","kind":"identifier"}],"title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"url":"\/documentation\/dotdocument\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"type":"topic","title":"CommonConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","title":"DocumentAutoCaptureQualityAttributeThresholds","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}],"type":"topic","title":"DOTDBaseDocumentAutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","kind":"symbol","title":"MrzValidation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzvalidation","abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"role":"symbol","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDValidationMode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","op":"replace"},{"value":[{"text":"DOTDValidationMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle","op":"replace"},{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","op":"replace"},{"value":"DOTDDocumentAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"},{"value":"DOTDMrzValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","op":"replace"},{"value":[{"text":"DOTDMrzValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzValidation"}]}]}]}