{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureDetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmAutoCaptureResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"metadata":{"roleHeading":"Initializer","title":"init(detection:result:phase:)","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC9detection6result5phaseAeA0bdE9DetectionC_AA0bdeH0CSgAA0bdE5PhaseOtcfc","modules":[{"name":"DotPalmCore"}],"symbolKind":"init","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection","text":"PalmAutoCaptureDetection","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","text":"PalmAutoCaptureResult","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/init(detection:result:phase:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","title":"PalmAutoCaptureDetection","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult/init(detection:result:phase:)":{"type":"topic","title":"init(detection:result:phase:)","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult\/init(detection:result:phase:)","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult\/init(detection:result:phase:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection","kind":"typeIdentifier","text":"PalmAutoCaptureDetection"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","kind":"typeIdentifier","text":"PalmAutoCaptureResult"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","kind":"typeIdentifier","text":"PalmAutoCapturePhase"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePhase"}],"title":"PalmAutoCapturePhase","url":"\/documentation\/dotpalmcore\/palmautocapturephase","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePhase"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","abstract":[{"type":"text","text":"Phase of the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureResult","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","title":"PalmAutoCaptureResult","kind":"symbol","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","type":"topic","title":"PalmAutoCaptureController","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"abstract":[{"type":"text","text":"The result returned from the processing of one image during the palm auto capture process."}],"navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","title":"PalmAutoCaptureController.ProcessingResult","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTPPalmAutoCaptureDetection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCapturePhase","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCaptureResult","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}