{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/camerafacing"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/cameraFacing","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Specify camera facing. Default is ","type":"text"},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"title":"cameraFacing","externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC12cameraFacing0A6Camera0kJ0Ovp","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/cameraFacing":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Specify camera facing. Default is "},{"type":"codeVoice","code":".front"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/cameraFacing","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"title":"cameraFacing","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/camerafacing"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"title":"SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the smile liveness process.","type":"text"}],"title":"SmileLivenessViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","role":"symbol","url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}]}]}