{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/common"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/common","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC6common0aC006CommonH0Cvp","title":"common","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"}]},"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the UI Smile Liveness component.","type":"text"}],"title":"SmileLivenessViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","url":"\/documentation\/dotfacecore\/commonconfiguration","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/common":{"role":"symbol","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"type":"codeVoice","code":".init()"},{"text":".","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/common","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/common","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration"}],"title":"common","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SmileLivenessViewController","abstract":[{"type":"text","text":"UI Smile Liveness component."}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}