{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLibraryComponent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is:","type":"text"}]},{"type":"codeListing","syntax":null,"code":[".init(","    faceSizeRatioInterval: .init(min: 0.1, max: 0.3),","    query: .init()",")"]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/facelibrarycomponent"]}],"abstract":[{"type":"text","text":"Configuration for face library components."}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceLibraryComponentConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"}],"roleHeading":"Instance Property","symbolKind":"property","title":"faceLibraryComponent","modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC20faceLibraryComponentAA0bjkH0Cvp","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/faceLibraryComponent","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"SmileLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the UI Smile Liveness component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/faceLibraryComponent":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/facelibrarycomponent","type":"topic","abstract":[{"type":"text","text":"Configuration for face library components."}],"role":"symbol","kind":"symbol","title":"faceLibraryComponent","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/faceLibraryComponent"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","kind":"symbol","title":"FaceLibraryComponentConfiguration","role":"symbol","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"abstract":[{"text":"Configuration for face library components.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"type":"topic","title":"SmileLivenessViewController","role":"symbol","abstract":[{"type":"text","text":"UI Smile Liveness component."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","op":"replace","value":"DOTFFaceLibraryComponentConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace","value":"DOTFSmileLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]}]}]}