{"abstract":[{"text":"Create the smile liveness configuration.","type":"text"}],"metadata":{"title":"init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"sessionToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"text":", ","kind":"text"},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC12sessionToken21faceSizeRatioInterval5query23isDetectionLayerVisible0P12TorchEnabled0p12VideoCaptureU012cameraFacing0X16PreviewScaleTypeAESSSg_0aC00N6DoubleCAA0bQ5QueryCS3b0A6Camera06CameraY0OAT06CameraZ9ScaleTypeOtcfc","roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"symbolKind":"init","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"kind":"text","text":" = Defaults.faceSizeRatioInterval, "},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":" = .init(), "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"text":"isTorchEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = Defaults.isTorchEnabled, ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.isVideoCaptureEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing"},{"text":" = Defaults.cameraFacing, ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"text":" = Defaults.cameraPreviewScaleType)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","title":"CameraPreviewScaleType","kind":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)":{"title":"init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:query:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"query","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","text":"FaceDetectionQuery"},{"kind":"text","text":", "},{"text":"isDetectionLayerVisible","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cameraPreviewScaleType","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"CameraPreviewScaleType"},{"kind":"text","text":")"}],"abstract":[{"text":"Create the smile liveness configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:query:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:)","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","title":"SmileLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.8.0","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","type":"topic","role":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","title":"IntervalDouble"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetectionQuery"}],"url":"\/documentation\/dotfacecore\/facedetectionquery","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","title":"FaceDetectionQuery"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"FaceDetectionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"}]}]}