{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/query"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/query"},"kind":"symbol","abstract":[{"type":"text","text":"Query for additional evaluation of face auto capture result."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC5queryAA0B14DetectionQueryCvp","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","kind":"typeIdentifier"}],"title":"query","symbolKind":"property"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration options for the smile liveness process.","type":"text"}],"title":"SmileLivenessViewController.Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"title":"SmileLivenessViewController","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"abstract":[{"type":"text","text":"Face detection query. It allows additional processing beyond basic face detection."}],"title":"FaceDetectionQuery","kind":"symbol","navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","role":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class/query":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Query for additional evaluation of face auto capture result."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class\/query","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"query","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery"}],"title":"query","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class\/query"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","value":"FaceDetectionQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"kind":"identifier","text":"FaceDetectionQuery"}]}]}]}