{"seeAlsoSections":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"title":"QualityAttribute","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFQualityAttribute","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}]},"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/init(id:targetRange:strictRange:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/id","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/strictRange","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/targetRange"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/isEqual(_:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/Error"]}],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityattribute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityattribute"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFQualityAttribute) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"You can use this class to customize the ranges of quality attributes which are checked during the face auto capture process."},{"type":"text","text":" "},{"type":"text","text":"The result of the face auto capture process is guaranteed to satisfy "},{"type":"codeVoice","code":"targetRange"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"strictRange"},{"type":"text","text":" will be satisfied at least once (by at least one video frame) during the face auto capture process, but the result may not satisfy "},{"type":"codeVoice","code":"strictRange"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"strictRange"},{"type":"text","text":" must be entirely contained in "},{"type":"codeVoice","code":"targetRange"},{"type":"text","text":"."}]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/id":{"role":"symbol","title":"id","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId"}],"abstract":[{"type":"text","text":"Quality attribute id."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/id","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"qualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/id"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/isequal(_:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IcaoQualityProvider":{"role":"symbol","title":"IcaoQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IcaoQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for ICAO evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IcaoQualityProvider"}],"url":"\/documentation\/dotfacecore\/icaoqualityprovider"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/Error":{"role":"symbol","title":"QualityAttribute.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/error"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/hash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/hash"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/targetRange":{"role":"symbol","title":"targetRange","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"targetRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"}],"abstract":[{"type":"text","text":"The quality attribute of the face auto capture result must be in "},{"type":"codeVoice","code":"targetRange"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/targetRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"targetRange"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/targetrange"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DefaultQualityAttributeRegistry":{"role":"symbol","title":"DefaultQualityAttributeRegistry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"abstract":[{"type":"text","text":"This class contains default "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" for every "},{"type":"codeVoice","code":"QualityAttributeId"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"url":"\/documentation\/dotfacecore\/defaultqualityattributeregistry"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/init(id:targetRange:strictRange:)":{"role":"symbol","title":"init(id:targetRange:strictRange:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFQualityAttributeId"},{"kind":"text","text":", "},{"kind":"externalParam","text":"targetRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":", "},{"kind":"externalParam","text":"strictRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/init(id:targetRange:strictRange:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/init(id:targetrange:strictrange:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/PassiveLivenessQualityProvider":{"role":"symbol","title":"PassiveLivenessQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for passive liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"url":"\/documentation\/dotfacecore\/passivelivenessqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute/strictRange":{"role":"symbol","title":"strictRange","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"strictRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ValueRange","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFValueRange"}],"abstract":[{"type":"text","text":"The quality attribute of the face auto capture detection must be in the "},{"type":"codeVoice","code":"strictRange"},{"type":"text","text":" at least once during the face auto capture process."},{"type":"text","text":" "},{"type":"text","text":"However, the quality attribute of the face auto capture result may not be in "},{"type":"codeVoice","code":"strictRange"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/strictRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"strictRange"}],"url":"\/documentation\/dotfacecore\/qualityattribute\/strictrange"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider":{"role":"symbol","title":"MatchingQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MatchingQualityProvider"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider":{"role":"symbol","title":"QualityProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}],"url":"\/documentation\/dotfacecore\/qualityprovider"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFQualityAttribute"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttribute"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFQualityAttribute"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/hash","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/id","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/strictRange","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/targetRange"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/init(id:targetRange:strictRange:)","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFQualityAttribute"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1id\/title","value":"qualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1id\/fragments","value":[{"kind":"identifier","text":"qualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/title","value":"DOTFIcaoQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFIcaoQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTFQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1targetRange\/title","value":"targetRange"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1targetRange\/fragments","value":[{"kind":"identifier","text":"targetRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/title","value":"DOTFDefaultQualityAttributeRegistry"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/fragments","value":[{"kind":"identifier","text":"DOTFDefaultQualityAttributeRegistry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1init(id:targetRange:strictRange:)\/title","value":"initWithId:targetRange:strictRange:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1init(id:targetRange:strictRange:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithId:targetRange:strictRange:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/title","value":"DOTFPassiveLivenessQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFPassiveLivenessQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1strictRange\/title","value":"strictRange"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute~1strictRange\/fragments","value":[{"kind":"identifier","text":"strictRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/title","value":"DOTFMatchingQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFMatchingQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTFQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTFQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/title","value":"DOTFQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTFQualityProvider"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}