{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class\/backgroundColor","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Background color of top level view."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC5StyleC15backgroundColorSo7UIColorCvp","modules":[{"name":"DotFaceCore"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"symbolKind":"property","title":"backgroundColor"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.class\/backgroundcolor"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Style-swift.class/backgroundColor":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class\/backgroundColor","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.class\/backgroundcolor","title":"backgroundColor","type":"topic","abstract":[{"text":"Background color of top level view.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","role":"symbol","abstract":[{"type":"text","text":"UI Face Auto Capture component."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Style-swift.class":{"kind":"symbol","title":"FaceAutoCaptureViewController.Style","abstract":[{"text":"Customization options for the face auto capture user interface.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Style-swift.class","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/style-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Style","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}