{"abstract":[{"type":"text","text":"The controller requests a photo capture with depth. Respond by calling "},{"type":"codeVoice","code":"FingersAutoCaptureController.captured(sample:)"},{"type":"text","text":"."}],"metadata":{"title":"FingersAutoCaptureEvent.captureDepth","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotFingersCore@E@DOTFGFingersAutoCaptureEvent@DOTFGFingersAutoCaptureEventCaptureDepth","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDepth"}],"navigatorTitle":[{"text":"DOTFGFingersAutoCaptureEventCaptureDepth","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDepth"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureevent\/capturedepth"]},{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureevent\/capturedepth"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent\/captureDepth"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent/captureDepth":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent\/captureDepth","title":"FingersAutoCaptureEvent.captureDepth","url":"\/documentation\/dotfingerscore\/fingersautocaptureevent\/capturedepth","abstract":[{"text":"The controller requests a photo capture with depth. Respond by calling ","type":"text"},{"code":"FingersAutoCaptureController.captured(sample:)","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureDepth"}],"navigatorTitle":[{"text":"DOTFGFingersAutoCaptureEventCaptureDepth","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent":{"role":"symbol","title":"FingersAutoCaptureEvent","type":"topic","abstract":[{"type":"text","text":"An event emitted during the fingers auto capture process."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureEvent","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCaptureEvent","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureevent","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFGFingersAutoCaptureEventCaptureDepth","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEventCaptureDepth"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DOTFGFingersAutoCaptureEventCaptureDepth","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"DOTFGFingersAutoCaptureEventCaptureDepth","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent~1captureDepth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEventCaptureDepth"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent~1captureDepth\/fragments"},{"op":"replace","value":"DOTFGFingersAutoCaptureEvent","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEvent"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureEvent"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/navigatorTitle"}]}]}