{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/helpAnchor","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFingersCore","relatedModules":["Foundation"]}],"role":"symbol","title":"helpAnchor","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:7DotCore0A3SdkC5ErrorO","extendedModule":"Foundation","platforms":[{"name":"iOS","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false},{"beta":false,"deprecated":false,"name":"iPadOS","unavailable":false,"introducedAt":"8.0"},{"name":"Mac Catalyst","unavailable":false,"introducedAt":"8.0","beta":false,"deprecated":false},{"beta":false,"deprecated":false,"name":"macOS","unavailable":false,"introducedAt":"10.10"},{"beta":false,"deprecated":false,"name":"tvOS","unavailable":false,"introducedAt":"9.0"},{"beta":false,"deprecated":false,"name":"watchOS","unavailable":false,"introducedAt":"2.0"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdk\/error\/helpanchor"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/helpAnchor":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol","role":"symbol","title":"helpAnchor","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/helpanchor"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotfingerscore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of IDV libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFingers"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","title":"DotSdk","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/error","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error","title":"DotSdk.Error","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}