{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Format of the stored image","type":"text"}],"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"format","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTImage(py)format","title":"format","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"format","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","kind":"typeIdentifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/image\/format"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/image\/format"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/format"},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"role":"symbol","url":"\/documentation\/dotpalmcore\/imageformat","kind":"symbol","title":"ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","type":"topic","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"Supported image formats."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"kind":"symbol","type":"topic","title":"PalmDetector","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector"},"doc://DotPalmCore/documentation/DotPalmCore/Image/format":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"format"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"}],"title":"format","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/format","url":"\/documentation\/dotpalmcore\/image\/format","abstract":[{"text":"Format of the stored image","type":"text"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"title":"Image","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Image"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"format","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"format"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","text":"DOTImageFormat"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","op":"replace"},{"value":"format","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1format\/title","op":"replace"},{"value":[{"text":"format","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1format\/fragments","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","op":"replace"}]}]}