{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/capturemode\/autocapture"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/capturemode\/autocapture"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"metadata":{"title":"CaptureMode.autoCapture","roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeAutoCapture","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/autoCapture"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"inlineContent":[{"text":"Once specified count of consecutive valid frames have been acquired,","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"the candidate selection process is triggered and continues for specified time in milliseconds."},{"type":"text","text":" "},{"text":"During this period, the system analyzes the pool of valid images to determine the most suitable result image.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"type":"topic","url":"\/documentation\/dotfacecore\/capturemode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","kind":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"title":"CaptureMode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode/autoCapture":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode\/autoCapture","url":"\/documentation\/dotfacecore\/capturemode\/autocapture","kind":"symbol","abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"title":"CaptureMode.autoCapture","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTCaptureModeAutoCapture"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode~1autoCapture\/title","value":"DOTCaptureModeAutoCapture"},{"value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode~1autoCapture\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}