{"schemaVersion":{"patch":0,"major":0,"minor":3},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"],"title":"DotPalm modularization","generated":true}],"kind":"symbol","metadata":{"externalID":"c:@M@DotPalmCore@objc(pl)DotPalmModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotPalmModule","kind":"identifier"}],"symbolKind":"protocol","roleHeading":"Protocol","title":"DotPalmModule","navigatorTitle":[{"kind":"identifier","text":"DotPalmModule"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule\/moduleId"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"sections":[],"abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotPalmModule","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmmodule"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotpalmmodule"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.1","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule/moduleId":{"title":"moduleId","role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmodule\/moduleid","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule\/moduleId","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"moduleId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotPalmModuleId","kind":"typeIdentifier","text":"DotPalmModuleId"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule":{"title":"DotPalmModule","role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmodule","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmModule"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModule"}],"abstract":[{"code":"DotPalm","type":"codeVoice"},{"text":" feature module.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"title":"DotPalmModuleId","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"DotPalmModule","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotPalmModule","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModule"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule\/moduleId"]}],"op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"],"title":"DotPalm modularization","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModule","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule~1moduleId\/title","value":"moduleId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule~1moduleId\/fragments","value":[{"kind":"identifier","text":"moduleId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/title","value":"DotPalmModule"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/fragments","value":[{"kind":"identifier","text":"DotPalmModule"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","op":"replace","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}