{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/init(phase:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/phase"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPPalmAutoCapturePhaseWrapped) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"PalmAutoCapturePhase.Wrapped","externalID":"s:11DotPalmCore0B16AutoCapturePhaseO7WrappedC","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"role":"symbol","roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped"},"references":{"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped/init(phase:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped\/init(phase:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/init(phase:)","title":"init(phase:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCapturePhase","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped/phase":{"role":"symbol","title":"phase","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped\/phase","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"PalmAutoCapturePhase"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped\/phase","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","title":"PalmAutoCapturePhase","url":"\/documentation\/dotpalmcore\/palmautocapturephase","abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePhase"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped","kind":"symbol","title":"PalmAutoCapturePhase.Wrapped","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped","type":"topic","role":"symbol"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTPPalmAutoCapturePhase","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}