{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC","text":"Result"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","text":"Result"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of MRZ reading."}]}]},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image to perform the MRZ reading on."}]}]},{"name":"documentDetectorResult","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detection result for the document present in the image."}]}]},{"name":"travelDocumentType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify travel document type to improve MRZ reading accuracy. If travel document type is unknown, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:documentdetectorresult:traveldocumenttype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:documentdetectorresult:traveldocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:documentDetectorResult:travelDocumentType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Read MRZ in an image and return the result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC"}],"title":"read(bgraRawImage:documentDetectorResult:travelDocumentType:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzReader(im)readWithBgraRawImage:documentDetectorResult:travelDocumentType:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/Result":{"role":"symbol","title":"MrzReader.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/mrzreader\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.4.2"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"role":"symbol","title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorResult":{"role":"symbol","title":"DOTDDocumentDetectorResult","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorResult"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentdetectorresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result":{"role":"symbol","title":"DocumentDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/documentdetector\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDMrzReaderResult":{"role":"symbol","title":"DOTDMrzReaderResult","fragments":[{"kind":"identifier","text":"DOTDMrzReaderResult"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdmrzreaderresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/read(bgraRawImage:documentDetectorResult:travelDocumentType:)":{"role":"symbol","title":"read(bgraRawImage:documentDetectorResult:travelDocumentType:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC"}],"abstract":[{"type":"text","text":"Read MRZ in an image and return the result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:documentDetectorResult:travelDocumentType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"}],"url":"\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:documentdetectorresult:traveldocumenttype:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzReaderResult","text":"DOTDMrzReaderResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"readWithBgraRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentDetectorResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorResult","text":"DOTDDocumentDetectorResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentDetectorResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper","text":"DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"travelDocumentType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTDTravelDocumentTypeWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTDTravelDocumentTypeWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:documentDetectorResult:travelDocumentType:)\/title","value":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:documentDetectorResult:travelDocumentType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithBgraRawImage:documentDetectorResult:travelDocumentType:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}