{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory\/create(image:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithImage:","symbolKind":"method","roleHeading":"Type Method","role":"symbol","title":"create(image:)"},"variants":[{"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(image:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://DotDocument/documentation/DotDocument/CGImageFactory/create(image:)":{"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/cgimagefactory\/create(image:)","title":"create(image:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory\/create(image:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/Image":{"title":"Image","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","abstract":[],"url":"\/documentation\/dotdocument\/image","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}]},"doc://DotDocument/documentation/DotDocument/CGImageFactory":{"url":"\/documentation\/dotdocument\/cgimagefactory","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CGImageFactory","type":"topic","title":"CGImageFactory","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@CGImage","text":"CGImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input image as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"image"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" instance.","type":"text"}]}]}},{"value":"createWithImage:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory~1create(image:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory~1create(image:)\/fragments"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/title"},{"value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CGImageFactory\/navigatorTitle"}]}]}