{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"type":"paragraph"}],"name":"bgraRawImage"}]},{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"kind":"symbol","metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"title":"create(bgraRawImage:)","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","externalID":"c:@M@DotDocument@objc(cs)DOTCGImageFactory(cm)createWithBgraRawImage:","symbolKind":"method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(bgrarawimage:)"]},{"paths":["\/documentation\/dotdocument\/cgimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory\/create(bgraRawImage:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory":{"type":"topic","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"CGImageFactory","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","url":"\/documentation\/dotdocument\/cgimagefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory/create(bgraRawImage:)":{"url":"\/documentation\/dotdocument\/cgimagefactory\/create(bgrarawimage:)","type":"topic","role":"symbol","title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory\/create(bgraRawImage:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","type":"topic","kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"title":"BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithBgraRawImage:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@S@CGImage","text":"CGImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/title"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory~1create(bgraRawImage:)\/fragments"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments"}]}]}