{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/passiveLiveness","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacemoduleid\/passiveliveness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacemoduleid\/passiveliveness"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"languages":["swift"]}]}],"metadata":{"title":"DotFaceModuleId.passiveLiveness","roleHeading":"Case","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdPassiveLiveness","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId","url":"\/documentation\/dotfacelite\/dotfacemoduleid","title":"DotFaceModuleId","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/passiveLiveness":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/passiveLiveness","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/passiveliveness","type":"topic","abstract":[],"kind":"symbol","title":"DotFaceModuleId.passiveLiveness","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1passiveLiveness\/title","value":"DotFaceModuleIdPassiveLiveness"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1passiveLiveness\/fragments","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}]}]}]}