{"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)hash","title":"hash","roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/hash"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/hash":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/hash","role":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone\/hash","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"role":"symbol","title":"Td3MachineReadableZone","type":"topic","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"hash","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1hash\/fragments","op":"replace"},{"value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","op":"replace"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/navigatorTitle","op":"replace"},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace"}]}]}