{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage(py)bgrRawImage","navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"bgrRawImage","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimage\/bgrrawimage"]},{"paths":["\/documentation\/dotfacecore\/faceimage\/bgrrawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Raw face image."}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bgrRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/bgrRawImage"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"navigatorTitle":[{"text":"FaceImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimage","title":"FaceImage","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImage","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","url":"\/documentation\/dotfacecore\/bgrrawimage"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/bgrRawImage":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bgrRawImage"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/bgrRawImage","title":"bgrRawImage","abstract":[{"text":"Raw face image.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceimage\/bgrrawimage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgrRawImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"role":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"bgrRawImage","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"bgrRawImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bgrRawImage"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title","op":"replace","value":"DOTFFaceImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImage"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"value":"bgrRawImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1bgrRawImage\/title","op":"replace"},{"value":[{"text":"bgrRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1bgrRawImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","op":"replace","value":"DOTFFaceDetector"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}