{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Property","title":"image","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"image"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage(py)image"},"variants":[{"paths":["\/documentation\/dotfacecore\/faceimage\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimage\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/image"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Raw face image."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier","text":"Image"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImage/image":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage\/image","url":"\/documentation\/dotfacecore\/faceimage\/image","navigatorTitle":[{"kind":"identifier","text":"image"}],"type":"topic","title":"image","abstract":[{"type":"text","text":"Raw face image."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"url":"\/documentation\/dotfacecore\/faceimage","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImage"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","title":"FaceImage","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"url":"\/documentation\/dotfacecore\/image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","title":"Image","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"image","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"image","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"image"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage~1image\/fragments"},{"op":"replace","value":"DOTFFaceImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}