{"abstract":[{"type":"text","text":"Create face image from raw image and face size interval."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceimage\/init(bgrrawimage:facesizeratiointerval:)"]},{"paths":["\/documentation\/dotfacecore\/faceimage\/init(bgrrawimage:facesizeratiointerval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage\/init(bgrRawImage:faceSizeRatioInterval:)"},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage(im)initWithBgrRawImage:faceSizeRatioInterval:error:","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"init","navigatorTitle":[{"text":"initWithBgrRawImage:faceSizeRatioInterval:error:","kind":"identifier"}],"title":"init(bgrRawImage:faceSizeRatioInterval:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","text":"BgrRawImage"},{"text":", ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Raw image.","type":"text"}]}],"name":"bgrRawImage"},{"name":"faceSizeRatioInterval","content":[{"type":"paragraph","inlineContent":[{"text":"Face size interval as a ratio to shorter image side. This defines size of searched face in the image.","type":"text"},{"type":"text","text":" "},{"text":"Valid values are in interval [0.0, 1.0].","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"faceSizeRatioInterval.min"},{"text":" Must be greater than or equal to minimal valid face size, which depends on the active detection module.","type":"text"}]}]}]},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"text":"New face image object.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","title":"IntervalDouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgrRawImage":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","type":"topic","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImage/init(bgrRawImage:faceSizeRatioInterval:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage\/init(bgrRawImage:faceSizeRatioInterval:)","abstract":[{"type":"text","text":"Create face image from raw image and face size interval."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimage\/init(bgrrawimage:facesizeratiointerval:)","title":"init(bgrRawImage:faceSizeRatioInterval:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBgrRawImage:faceSizeRatioInterval:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceSizeRatioInterval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImage":{"title":"FaceImage","url":"\/documentation\/dotfacecore\/faceimage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImage"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage","navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"initWithBgrRawImage:faceSizeRatioInterval:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgrRawImage:faceSizeRatioInterval:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBgrRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":" *) "},{"text":"bgrRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSizeRatioInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble"},{"text":" *) ","kind":"text"},{"text":"faceSizeRatioInterval","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/title","op":"replace","value":"DOTBgrRawImage"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage~1init(bgrRawImage:faceSizeRatioInterval:)\/title","value":"initWithBgrRawImage:faceSizeRatioInterval:error:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage~1init(bgrRawImage:faceSizeRatioInterval:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBgrRawImage:faceSizeRatioInterval:error:","kind":"identifier"}]},{"value":"DOTFFaceImage","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage\/fragments","op":"replace","value":[{"text":"DOTFFaceImage","kind":"identifier"}]}]}]}