{"sections":[],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTValidationFloat(cm)validateWithValue:interval:error:","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","text":"IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"title":"validate(value:interval:)","roleHeading":"Type Method","symbolKind":"method","modules":[{"name":"DotDocument"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/validationfloat\/validate(value:interval:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/validationfloat\/validate(value:interval:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"IntervalFloat","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat\/validate(value:interval:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationFloat":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationFloat","kind":"identifier"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationFloat"}],"title":"ValidationFloat","url":"\/documentation\/dotdocument\/validationfloat","abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/intervalfloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationFloat/validate(value:interval:)":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat\/validate(value:interval:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","text":"IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"title":"validate(value:interval:)","url":"\/documentation\/dotdocument\/validationfloat\/validate(value:interval:)","abstract":[],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"validateWithValue:interval:error:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"validateWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"interval:"},{"text":"(","kind":"text"},{"text":"DOTIntervalFloat","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interval"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]}},{"value":"DOTValidationFloat","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTValidationFloat"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat~1validate(value:interval:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}