{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)"],"anchor":"Initializers","generated":true},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"],"anchor":"Instance-Properties","generated":true}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"symbolKind":"class","externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","title":"DotPalmLibraryConfiguration.Modules","roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotPalmLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}]}],"abstract":[{"text":"Palm library module configuration.","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","title":"detection","abstract":[],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"title":"init(detection:)","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"text":"Palm library module configuration.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class","kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"title":"DotPalmLibraryConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]}]}]}