{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundles:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundles:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundles:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Transform four finger images into fingerprint images.","type":"text"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerToFingerprintTransformer(im)transformWithFingerBundles:error:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingerBundles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"FingerprintImages","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages"}],"title":"transform(fingerBundles:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"transformWithFingerBundles:error:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingerBundles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"FingerprintImages","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fingerBundles","content":[{"type":"paragraph","inlineContent":[{"text":"Bundles of the finger images with detection data. Terminates if any image is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"The resulting fingerprint images.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}],"type":"paragraph"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error if ","type":"text"},{"type":"codeVoice","code":"FingerToFingerprintTransformer"},{"text":" fails to execute the transformation.","type":"text"}]}],"style":"note","name":"Throws","type":"aside"}],"kind":"content"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/transform(fingerBundles:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"kind":"text","text":"("},{"text":"fingerBundles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"FingerprintImages","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages"}],"navigatorTitle":[{"text":"transformWithFingerBundles:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundles:)","abstract":[{"text":"Transform four finger images into fingerprint images.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundles:)","title":"transform(fingerBundles:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","kind":"symbol","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"title":"FingerprintImages","type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerprintImages","kind":"identifier"}],"navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"kind":"symbol","role":"symbol","title":"FingerToFingerprintTransformer","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"url":"\/documentation\/dotfingerscore\/fingerbundles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles","title":"FingerBundles","role":"symbol","abstract":[{"text":"Bundles of finger images with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"transformWithFingerBundles:error:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transformWithFingerBundles:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTFGFingerprintImages","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"},{"text":" *) ","kind":"text"},{"text":"transformWithFingerBundles:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles","kind":"typeIdentifier","text":"DOTFGFingerBundles","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"fingerBundles"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Bundles of the finger images with detection data. Terminates if any image is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}],"name":"fingerBundles"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if no error occurred. If you are not interested in the error information, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" for this parameter."}]}],"name":"error"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The resulting fingerprint images.","type":"text"},{"text":" On failure, this method returns ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":".","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"transformWithFingerBundles:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundles:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"transformWithFingerBundles:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundles:)\/fragments"},{"op":"replace","value":"DOTFGFingerprintImages","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle"},{"op":"replace","value":"DOTFGFingerToFingerprintTransformer","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle"},{"op":"replace","value":"DOTFGFingerBundles","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}