{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement"]]},"variants":[{"paths":["\/documentation\/dotnfc\/mrznameelement\/primaryidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrznameelement\/primaryidentifier"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Primary identifier usually represents surname.","type":"text"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"primaryIdentifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"title":"primaryIdentifier","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement(py)primaryIdentifier","navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement\/primaryIdentifier","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/MrzNameElement":{"type":"topic","url":"\/documentation\/dotnfc\/mrznameelement","title":"MrzNameElement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement","abstract":[{"type":"text","text":"A Machine Readable Zone name element."}]},"doc://DotNfc/documentation/DotNfc/MrzNameElement/primaryIdentifier":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzNameElement\/primaryIdentifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"primaryIdentifier"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"primaryIdentifier","kind":"identifier"}],"title":"primaryIdentifier","url":"\/documentation\/dotnfc\/mrznameelement\/primaryidentifier","type":"topic","abstract":[{"type":"text","text":"Primary identifier usually represents surname."}],"role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"type":"topic","url":"\/documentation\/dotnfc\/mrzelement","title":"MrzElement","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"primaryIdentifier","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"primaryIdentifier","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"},{"kind":"text","text":" * "},{"text":"primaryIdentifier","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement~1primaryIdentifier\/title","op":"replace","value":"primaryIdentifier"},{"value":[{"kind":"identifier","text":"primaryIdentifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzNameElement~1primaryIdentifier\/fragments","op":"replace"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]}]}]}