{"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/mrznameelement\/secondaryidentifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrznameelement\/secondaryidentifier"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement"]]},"abstract":[{"text":"Secondary identifier usually represents given names.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/secondaryIdentifier"},"metadata":{"modules":[{"name":"DotNfc"}],"symbolKind":"property","title":"secondaryIdentifier","externalID":"c:@M@DotNfc@objc(cs)DOTMrzNameElement(py)secondaryIdentifier","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"secondaryIdentifier","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"secondaryIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":"?","kind":"text"}]},"kind":"symbol","references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","url":"\/documentation\/dotnfc\/mrznameelement","kind":"symbol","abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"title":"MrzNameElement","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"type":"topic","url":"\/documentation\/dotnfc\/mrzelement","title":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement/secondaryIdentifier":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement\/secondaryIdentifier","url":"\/documentation\/dotnfc\/mrznameelement\/secondaryidentifier","kind":"symbol","abstract":[{"type":"text","text":"Secondary identifier usually represents given names."}],"title":"secondaryIdentifier","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"secondaryIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"secondaryIdentifier"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"secondaryIdentifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"secondaryIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"DOTMrzNameElement","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzElement"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1secondaryIdentifier\/title","value":"secondaryIdentifier"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement~1secondaryIdentifier\/fragments","op":"replace","value":[{"text":"secondaryIdentifier","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}