{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property","title":"detection","fragments":[{"kind":"identifier","text":"detection"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)detection"},"variants":[{"paths":["\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules/detection":{"url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules\/detection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules\/detection","abstract":[],"title":"detection","fragments":[{"text":"detection","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","title":"DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotFingersLibraryConfigurationModules":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Fingers library module configuration."}],"fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersLibraryConfigurationModules","title":"DotFingersLibraryConfigurationModules","url":"\/documentation\/dotdocument\/dotfingerslibraryconfigurationmodules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}]}]}