{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"class","title":"BgraRawImage","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"title":"Converting images","generated":true}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/init(bytesPointer:size:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointer","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/size"],"title":"Instance Properties"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgraRawImage) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/bgrarawimage"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimage"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/size":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/bgrarawimage\/size","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/size","title":"size","kind":"symbol","navigatorTitle":[{"text":"size","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/bytesPointerPacked":{"kind":"symbol","title":"bytesPointerPacked","url":"\/documentation\/dotpalmcore\/bgrarawimage\/bytespointerpacked","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointerPacked","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointerPacked"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt32","kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage","type":"topic","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","title":"BgraRawImage","kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/cgimagefactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","title":"CGImageFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}]},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"title":"BgraRawImageFactory","role":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/init(bytesPointer:size:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/init(bytesPointer:size:)","url":"\/documentation\/dotpalmcore\/bgrarawimage\/init(bytespointer:size:)","type":"topic","abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"title":"init(bytesPointer:size:)","kind":"symbol"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/bytes":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytes","url":"\/documentation\/dotpalmcore\/bgrarawimage\/bytes","role":"symbol","type":"topic","abstract":[],"title":"bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/@M@DotCore@objc(pl)_RawImage":{"identifier":"doc:\/\/DotPalmCore\/@M@DotCore@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"title":"PalmDetector","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage/bytesPointer":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointer"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"title":"bytesPointer","type":"topic","navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointer","url":"\/documentation\/dotpalmcore\/bgrarawimage\/bytespointer"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","role":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/ciimagefactory"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTBgraRawImage","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointer","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/bytesPointerPacked","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/size"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage\/init(bytesPointer:size:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotPalmCore\/@M@DotCore@objc(pl)_RawImage"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"title":"Converting images"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTBgraRawImage","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1size\/title","value":"size"},{"value":[{"kind":"identifier","text":"size"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1size\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointerPacked\/title","value":"bytesPointerPacked"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointerPacked\/fragments","value":[{"kind":"identifier","text":"bytesPointerPacked"}],"op":"replace"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1init(bytesPointer:size:)\/fragments"},{"value":"bytes","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytes\/title","op":"replace"},{"value":[{"text":"bytes","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytes\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":"bytesPointer","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointer\/title"},{"value":[{"text":"bytesPointer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage~1bytesPointer\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}