{"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTPPlaceholderType) ","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlaceholderType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"enum","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"title":"PlaceholderType","externalID":"c:@M@DotPalmCore@E@DOTPPlaceholderType","role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"Represents the type of placeholder used in palm auto-capture UI."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/right"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/description"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype"]}],"references":{"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/dotpalmcore\/placeholdertype\/init(rawvalue:)"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/Equatable-Implementations":{"type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","url":"\/documentation\/dotpalmcore\/placeholdertype\/equatable-implementations"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"text":"Represents the type of placeholder used in palm auto-capture UI.","type":"text"}],"title":"PlaceholderType","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/placeholdertype"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article","type":"topic","role":"collectionGroup","url":"\/documentation\/dotpalmcore\/placeholdertype\/rawrepresentable-implementations"},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/description":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/placeholdertype\/description","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/description","title":"description"},"doc://DotPalmCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/left":{"url":"\/documentation\/dotpalmcore\/placeholdertype\/left","kind":"symbol","title":"PlaceholderType.left","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTPPlaceholderTypeLeft"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/left","abstract":[{"text":"Left palm placeholder.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"type":"topic"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/right":{"abstract":[{"text":"Right palm placeholder.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTPPlaceholderTypeRight"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/right","role":"symbol","url":"\/documentation\/dotpalmcore\/placeholdertype\/right","title":"PlaceholderType.right","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTPPlaceholderType","op":"replace"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTPPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPlaceholderType"}]},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/right"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTPPlaceholderType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title","value":"DOTPPlaceholderType"},{"value":[{"kind":"identifier","text":"DOTPPlaceholderType"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1left\/title","value":"DOTPPlaceholderTypeLeft"},{"op":"replace","value":[{"text":"DOTPPlaceholderTypeLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1left\/fragments"},{"op":"replace","value":"DOTPPlaceholderTypeRight","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1right\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPlaceholderTypeRight"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1right\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}