{"metadata":{"navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(im)initWithPitch:","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"init(pitch:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles\/init(pitch:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/tiltangles\/init(pitch:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/tiltangles\/init(pitch:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","title":"Sensor Coordinate System","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFingersCore/documentation/DotFingersCore/TiltAngles/init(pitch:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/tiltangles\/init(pitch:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles\/init(pitch:)","title":"init(pitch:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/TiltAngles":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/TiltAngles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"TiltAngles","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"text":"Also see ","type":"text"},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/tiltangles"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithPitch:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithPitch:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"float","preciseIdentifier":"c:f"},{"kind":"text","text":") "},{"kind":"internalParam","text":"pitch"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"initWithPitch:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles~1init(pitch:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles~1init(pitch:)\/fragments","op":"replace"},{"value":"DOTTiltAngles","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/title","op":"replace"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/fragments","op":"replace"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1TiltAngles\/navigatorTitle","op":"replace"}]}]}