{"abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"ImageParameters"},{"type":"text","text":" with normalized values in range [0, 1.0]."}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters(im)initWithSharpness:brightness:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightness"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(sharpness:brightness:)","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSharpness:brightness:"}],"roleHeading":"Initializer"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imageparameters\/init(sharpness:brightness:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageparameters\/init(sharpness:brightness:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters\/init(sharpness:brightness:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters/init(sharpness:brightness:)":{"url":"\/documentation\/dotpalmcore\/imageparameters\/init(sharpness:brightness:)","type":"topic","title":"init(sharpness:brightness:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters\/init(sharpness:brightness:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sharpness"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"brightness"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"ImageParameters"},{"type":"text","text":" with normalized values in range [0, 1.0]."}],"navigatorTitle":[{"text":"initWithSharpness:brightness:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"title":"PalmDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmDetector","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"type":"topic","url":"\/documentation\/dotpalmcore\/imageparameters","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"title":"ImageParameters"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithSharpness:brightness:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSharpness:brightness:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"kind":"text","text":" "},{"text":"brightness:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"brightness","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters~1init(sharpness:brightness:)\/title","value":"initWithSharpness:brightness:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSharpness:brightness:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters~1init(sharpness:brightness:)\/fragments"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","value":"DOTPImageParameters","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}