{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/logger\/error(_:file:function:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/logger\/error(_:file:function:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/error(_:file:function:)"},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"error:file:function:"}],"role":"symbol","roleHeading":"Type Method","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPLogger(cm)error:file:function:","title":"error(_:file:function:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? = nil, "},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" = "},{"kind":"keyword","text":"#file"},{"kind":"text","text":", "},{"text":"function","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" = ","kind":"text"},{"kind":"keyword","text":"#function"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Logger":{"url":"\/documentation\/dotpalmcore\/logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","role":"symbol","title":"Logger"},"doc://DotPalmCore/documentation/DotPalmCore/Logger/error(_:file:function:)":{"navigatorTitle":[{"kind":"identifier","text":"error:file:function:"}],"title":"error(_:file:function:)","url":"\/documentation\/dotpalmcore\/logger\/error(_:file:function:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger\/error(_:file:function:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"error:file:function:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:file:function:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"message","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"file:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"file"},{"kind":"text","text":" "},{"text":"function:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"function"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/title","op":"replace","value":"DOTPLogger"},{"op":"replace","value":[{"text":"DOTPLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/fragments"},{"value":"error:file:function:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1error(_:file:function:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:file:function:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger~1error(_:file:function:)\/fragments"}]}]}