{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureresult\/face"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureresult\/face"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","title":"face","navigatorTitle":[{"text":"face","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult(py)face","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"symbolKind":"property","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult\/face","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Detected face in the image. Might be "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" only if "},{"type":"reference","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","isActive":true},{"type":"text","text":" was used to get the result."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"],["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","title":"FaceAutoCaptureResult","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceDetectorFace":{"fragments":[{"kind":"identifier","text":"DOTFLFaceDetectorFace"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfacedetectorface","kind":"symbol","title":"DOTFLFaceDetectorFace","type":"topic","abstract":[{"type":"text","text":"Detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","title":"requestCapture(isFacePresenceRequired:)","kind":"symbol","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"title":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacelite\/facedetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"kind":"symbol","title":"FaceDetector.Face","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"url":"\/documentation\/dotfacelite\/facedetector\/face","abstract":[{"text":"Detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult/face":{"url":"\/documentation\/dotfacelite\/faceautocaptureresult\/face","title":"face","kind":"symbol","abstract":[{"text":"Detected face in the image. Might be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" only if "},{"isActive":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","type":"reference"},{"text":" was used to get the result.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult\/face","role":"symbol","type":"topic","navigatorTitle":[{"text":"face","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"face","kind":"identifier"},{"kind":"text","text":": "},{"text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B8DetectorC0B0C"},{"text":"?","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.8.0"}],"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"face"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"face","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTFLFaceDetectorFace","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceDetectorFace","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetectorFace"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"face"}]}],"kind":"declarations"}},{"value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"},{"value":"requestCaptureWithIsFacePresenceRequired:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult~1face\/title","value":"face"},{"op":"replace","value":[{"text":"face","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult~1face\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}