{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/init(documentnumber:dateofexpiry:dateofbirth:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfckey\/init(documentnumber:dateofexpiry:dateofbirth:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/init(documentNumber:dateOfExpiry:dateOfBirth:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey"]]},"metadata":{"role":"symbol","symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcKey(im)initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:","platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.0"}],"title":"init(documentNumber:dateOfExpiry:dateOfBirth:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Initializer"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcKey":{"deprecated":true,"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcKey"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey","kind":"symbol","abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/NfcKey/init(documentNumber:dateOfExpiry:dateOfBirth:)":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/init(documentNumber:dateOfExpiry:dateOfBirth:)","deprecated":true,"url":"\/documentation\/dotnfc\/nfckey\/init(documentnumber:dateofexpiry:dateofbirth:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"kind":"symbol","title":"init(documentNumber:dateOfExpiry:dateOfBirth:)","abstract":[],"navigatorTitle":[{"text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentNumber:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentNumber"},{"text":" ","kind":"text"},{"text":"dateOfExpiry:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"dateOfExpiry","kind":"internalParam"},{"kind":"text","text":" "},{"text":"dateOfBirth:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"dateOfBirth","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"op":"replace","value":[{"text":"DOTNNfcKey","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1init(documentNumber:dateOfExpiry:dateOfBirth:)\/title","value":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1init(documentNumber:dateOfExpiry:dateOfBirth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentNumber:dateOfExpiry:dateOfBirth:error:"}]}]}]}