{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType"]]},"abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"type":"text","text":" "},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"type":"text","text":" case) during an auto capture process."}],"metadata":{"title":"CameraPreviewScaleType.fill","navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"fill","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","symbolKind":"case","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFill","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype\/fill"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype\/fill"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fill","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType/fill":{"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"text":" ","type":"text"},{"type":"text","text":"This configuration may produce images with lower resolution (compared to "},{"type":"codeVoice","code":"fit"},{"type":"text","text":" case) during an auto capture process."}],"title":"CameraPreviewScaleType.fill","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fill","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fill","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/fill","role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraPreviewScaleType":{"kind":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraPreviewScaleType","type":"topic","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"DOTCameraPreviewScaleTypeFill","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fill\/title","value":"DOTCameraPreviewScaleTypeFill","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fill\/fragments","op":"replace","value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}