{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype\/fit"]},{"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype\/fit"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"title":"CameraPreviewScaleType.fit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType@DOTCameraPreviewScaleTypeFit","role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fit"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType"]]},"abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"type":"text","text":" "},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}],"languages":["swift"]}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"role":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype","kind":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","type":"topic","title":"CameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.0.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/fit":{"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}],"abstract":[{"text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds.","type":"text"},{"type":"text","text":" "},{"text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fit","title":"CameraPreviewScaleType.fit","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/fit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTCameraPreviewScaleTypeFit","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fit\/title","op":"replace","value":"DOTCameraPreviewScaleTypeFit"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fit\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]}]}]}