{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/TransitionType-swift.enum","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO","text":"TransitionType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/transitiontype-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/transitiontype-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/transitionType-swift.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Transition type. Default is "},{"type":"codeVoice","code":".move"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransitionType","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO"}],"title":"transitionType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(py)transitionType","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"transitionType"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration":{"role":"symbol","title":"EyeGazeLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessConfiguration"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration/transitionType-swift.property":{"role":"symbol","title":"transitionType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TransitionType","preciseIdentifier":"s:11DotFaceCore28EyeGazeLivenessConfigurationC14TransitionTypeO"}],"abstract":[{"type":"text","text":"Transition type. Default is "},{"type":"codeVoice","code":".move"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/transitionType-swift.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transitionType"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/transitiontype-swift.property"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessConfiguration/TransitionType-swift.enum":{"role":"symbol","title":"EyeGazeLivenessConfiguration.TransitionType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"TransitionType"}],"abstract":[{"type":"text","text":"Eye gaze liveness available transition types."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessConfiguration\/TransitionType-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TransitionType"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessconfiguration\/transitiontype-swift.enum"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"role":"symbol","title":"DOTFEyeGazeLivenessTransitionType","fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessTransitionType"}],"abstract":[{"type":"text","text":"Eye gaze liveness available transition types."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"transitionType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"transitionType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType","text":"DOTFEyeGazeLivenessTransitionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"transitionType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/title","value":"DOTFEyeGazeLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration~1transitionType-swift.property\/title","value":"transitionType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessConfiguration~1transitionType-swift.property\/fragments","value":[{"kind":"identifier","text":"transitionType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}