{"metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp","symbolKind":"property","title":"barcode","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","title":"barcode","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/Modules-swift.class":{"title":"DotDocumentLibraryConfiguration.Modules","abstract":[{"text":"Document library module configuration.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","type":"topic","title":"DotDocumentBarcodeModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration","role":"symbol","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}]}]}