{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"init(barcode:)","modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?)","kind":"text"}],"role":"symbol","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAeA0ac13BarcodeModuleE0CSg_tcfc","symbolKind":"init"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/Modules-swift.class":{"title":"DotDocumentLibraryConfiguration.Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"text":"Document library module configuration.","type":"text"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration":{"title":"DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"title":"init(barcode:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfiguration","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Document library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace","value":"DotDocumentBarcodeModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/title","op":"replace","value":"DotDocumentLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}