{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/hash"]}],"metadata":{"title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(py)hash","roleHeading":"Instance Property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/hash"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","type":"topic","role":"symbol","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"title":"MrzDateElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit/hash":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/hash","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"title":"hash","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"hash"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1hash\/title","value":"hash"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1hash\/fragments"}]}]}