{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"positions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"text":"], ","kind":"text"},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"date","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","text":"MrzDate","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)"]},{"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]]},"metadata":{"roleHeading":"Initializer","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(im)initWithValue:positions:checkDigit:date:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"text":"positions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition"},{"kind":"text","text":"], "},{"text":"checkDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"text":", ","kind":"text"},{"text":"date","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(value:positions:checkDigit:date:)","modules":[{"name":"DotNfc"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/MrzDate":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","kind":"symbol","title":"MrzDate","url":"\/documentation\/dotnfc\/mrzdate","abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}]},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"title":"MrzDateElementWithCheckDigit","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"role":"symbol","abstract":[{"text":"A position of a string in Machine Readable Zone.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","url":"\/documentation\/dotnfc\/mrzstringposition","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"kind":"symbol","title":"MrzStringPosition","type":"topic"},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}],"url":"\/documentation\/dotnfc\/mrzcheckdigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"type":"topic","title":"MrzCheckDigit","role":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit/init(value:positions:checkDigit:date:)":{"title":"init(value:positions:checkDigit:date:)","role":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/init(value:positions:checkDigit:date:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"checkDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"date"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","text":"MrzDate","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithValue:positions:checkDigit:date:","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/init(value:positions:checkdigit:date:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithValue:positions:checkDigit:date:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:positions:checkDigit:date:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"value","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"positions:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSArray<DOTMrzStringPosition *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"positions"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit:"},{"text":"(","kind":"text"},{"text":"DOTMrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":" *) ","kind":"text"},{"text":"checkDigit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"date:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","text":"DOTMrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"date","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title","value":"DOTMrzDate"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]},{"value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/title","op":"replace","value":"initWithValue:positions:checkDigit:date:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1init(value:positions:checkDigit:date:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:checkDigit:date:"}],"op":"replace"}]}]}