{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules"]]},"sections":[],"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","role":"symbol","title":"initWithDetection:","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"text":"initWithDetection:","kind":"identifier"}],"roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotpalmlibraryconfigurationmodules\/initwithdetection:"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules\/initWithDetection:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfigurationModules":{"kind":"symbol","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfigurationmodules","title":"DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules","abstract":[{"type":"text","text":"Palm library module configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotpalmdetectionmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"title":"DotPalmDetectionModuleConfiguration","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfigurationModules/initWithDetection:":{"title":"initWithDetection:","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfigurationmodules\/initwithdetection:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithDetection:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules\/initWithDetection:"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DotPalmDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}