{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(image:document:travelDocumentType:)","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader\/read(image:document:traveldocumenttype:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzreader\/read(image:document:traveldocumenttype:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"read","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image"},{"text":", ","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"text":"Image to perform the MRZ reading on. Terminates if ","type":"text"},{"code":"image","type":"codeVoice"},{"text":" is not in ","type":"text"},{"code":".rawBgra","type":"codeVoice"},{"text":" format.","type":"text"}],"type":"paragraph"}]},{"name":"document","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Detection result for the document present in the image."}]}]},{"name":"travelDocumentType","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Specify travel document type to improve MRZ reading accuracy. If travel document type is unknown, pass "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The result of MRZ reading.","type":"text"}]}]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"text":".","kind":"text"},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","kind":"typeIdentifier"}],"symbolKind":"method","role":"symbol","title":"read(image:document:travelDocumentType:)","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzReader(im)readWithImage:document:travelDocumentType:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"readWithImage:document:travelDocumentType:","kind":"identifier"}],"roleHeading":"Instance Method"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Read MRZ in an image and return the result.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","title":"DOTDDocumentDetectorDocument","role":"symbol","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","navigatorTitle":[{"kind":"identifier","text":"Document"}],"url":"\/documentation\/dotdocument\/documentdetector\/document","kind":"symbol","title":"DocumentDetector.Document","abstract":[{"text":"Result of the document detection process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader/read(image:document:travelDocumentType:)":{"title":"read(image:document:travelDocumentType:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(image:document:travelDocumentType:)","abstract":[{"text":"Read MRZ in an image and return the result.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"readWithImage:document:travelDocumentType:"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/read(image:document:traveldocumenttype:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?) -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"title":"DocumentDetector","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"title":"TravelDocumentTypeWrapper","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","abstract":[{"text":"Wrapped ","type":"text"},{"code":"TravelDocumentType","type":"codeVoice"},{"text":" for Objective-C support.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"navigatorTitle":[{"kind":"identifier","text":"Result"}],"role":"symbol","title":"MrzReader.Result","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","url":"\/documentation\/dotdocument\/mrzreader\/result","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Image":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotdocument\/image","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"type":"topic","role":"symbol","title":"Image"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}]},"doc://DotDocument/documentation/DotDocument/DOTDMrzReaderResult":{"url":"\/documentation\/dotdocument\/dotdmrzreaderresult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReaderResult","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DOTDMrzReaderResult"}],"title":"DOTDMrzReaderResult","abstract":[{"text":"MRZ reading result.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"readWithImage:document:travelDocumentType:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithImage:document:travelDocumentType:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReaderResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzReaderResult","text":"DOTDMrzReaderResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"readWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"document:"},{"kind":"text","text":"("},{"text":"DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"travelDocumentType"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"Image to perform the MRZ reading on. Terminates if "},{"type":"codeVoice","code":"image"},{"type":"text","text":" is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"paragraph"}]},{"name":"document","content":[{"type":"paragraph","inlineContent":[{"text":"Detection result for the document present in the image.","type":"text"}]}]},{"name":"travelDocumentType","content":[{"inlineContent":[{"type":"text","text":"Specify travel document type to improve MRZ reading accuracy. If travel document type is unknown, pass "},{"code":"nil","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The result of MRZ reading."}]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(image:document:travelDocumentType:)\/title","op":"replace","value":"readWithImage:document:travelDocumentType:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(image:document:travelDocumentType:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithImage:document:travelDocumentType:"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","op":"replace","value":"DOTTravelDocumentTypeWrapper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","op":"replace","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title","op":"replace","value":"DOTImage"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}