{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DotSdkLicenseProxy","roleHeading":"Class","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"sections":[],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/licenseBytes"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/licenseBytes":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/licenseBytes","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/licensebytes","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"title":"licenseBytes","role":"symbol","navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFaceMatchingEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfacematchingenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isFaceMatchingEnabled","role":"symbol","navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","role":"symbol","title":"DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","type":"topic","kind":"symbol","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFaceLiteEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceLiteEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"role":"symbol","title":"isFaceLiteEnabled","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceliteenabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isFaceEyeGazeLivenessScoreEnabled","role":"symbol","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","abstract":[],"title":"isRealTimeTransactionReportingEnabled","type":"topic","navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy":{"kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy","type":"topic","title":"DotSdkLicenseProxy","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isDocumentEnabled":{"kind":"symbol","navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isDocumentEnabled","type":"topic","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isdocumentenabled","abstract":[],"title":"isDocumentEnabled","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isNfcEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isnfcenabled","title":"isNfcEnabled","navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isNfcEnabled","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFaceEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEnabled","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfaceenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isFaceEnabled","role":"symbol","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isEvaluation":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isEvaluation","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isevaluation","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEvaluation","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isEvaluation","role":"symbol","navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"kind":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isfacepassivelivenessenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isFacePassiveLivenessEnabled","role":"symbol","navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotSdkLicenseProxy"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/licenseBytes"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"value":[{"text":"licenseBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1licenseBytes\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title","op":"replace","value":"isFaceMatchingEnabled"},{"value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments","op":"replace"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","op":"replace","value":"isFaceLiteEnabled"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title","op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled"},{"value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isDocumentEnabled\/title","value":"isDocumentEnabled"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isDocumentEnabled\/fragments","op":"replace","value":[{"text":"isDocumentEnabled","kind":"identifier"}]},{"op":"replace","value":"isNfcEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isNfcEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEnabled\/title","value":"isFaceEnabled"},{"op":"replace","value":[{"kind":"identifier","text":"isFaceEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFaceEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isEvaluation\/title","value":"isEvaluation"},{"value":[{"text":"isEvaluation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isEvaluation\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title","op":"replace","value":"isFacePassiveLivenessEnabled"},{"value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments"}]}]}