{"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/init(feature:point:score:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/feature","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/point","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/score"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"Face feature point contains face feature, point and score.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFFaceFeaturePoint) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceFeaturePoint","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"class","role":"symbol","title":"FaceFeaturePoint","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceFeaturePoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceFeaturePoint","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceFeaturePoint","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facefeaturepoint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facefeaturepoint"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint"},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/init(feature:point:score:)":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/init(feature:point:score:)","title":"init(feature:point:score:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"feature","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature","kind":"typeIdentifier","text":"FaceFeature"},{"kind":"text","text":", "},{"kind":"externalParam","text":"point"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"score","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithFeature:point:score:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facefeaturepoint\/init(feature:point:score:)","abstract":[]},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/point":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"point"}],"type":"topic","url":"\/documentation\/dotfacecore\/facefeaturepoint\/point","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"point"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/point","title":"point","abstract":[{"type":"text","text":"Position point of the face feature."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/description":{"url":"\/documentation\/dotfacecore\/facefeaturepoint\/description","role":"symbol","title":"description","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/description","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/score":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/score","url":"\/documentation\/dotfacecore\/facefeaturepoint\/score","role":"symbol","abstract":[{"type":"text","text":"Score of the face feature."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"navigatorTitle":[{"text":"score","kind":"identifier"}],"title":"score"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facefeaturepoint","abstract":[{"text":"Face feature point contains face feature, point and score.","type":"text"}],"role":"symbol","title":"FaceFeaturePoint","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceFeaturePoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceFeaturePoint","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceFeaturePoint/feature":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facefeaturepoint\/feature","abstract":[{"type":"text","text":"Face feature."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/feature","title":"feature","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"feature","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceFeature","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFFaceFeature"}],"navigatorTitle":[{"text":"feature","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFFaceFeaturePoint"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFFaceFeaturePoint","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFFaceFeaturePoint","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/feature","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/point","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/score"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceFeaturePoint\/init(feature:point:score:)"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFFaceFeaturePoint"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1init(feature:point:score:)\/title","op":"replace","value":"initWithFeature:point:score:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1init(feature:point:score:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFeature:point:score:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1point\/title","op":"replace","value":"point"},{"value":[{"text":"point","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1point\/fragments","op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1score\/title","value":"score"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1score\/fragments","value":[{"text":"score","kind":"identifier"}],"op":"replace"},{"value":"DOTFFaceFeaturePoint","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceFeaturePoint"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1feature\/title","op":"replace","value":"feature"},{"value":[{"text":"feature","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceFeaturePoint~1feature\/fragments","op":"replace"}]}]}