{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"abstract":[{"text":"Common configuration for all UI components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/common"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC6common0aC006CommonI0Cvp","modules":[{"name":"DotFaceCore"}],"title":"common","platforms":[]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/common"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CommonConfiguration":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"url":"\/documentation\/dotfacecore\/commonconfiguration","abstract":[{"type":"text","text":"Common configuration for all components."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CommonConfiguration","title":"CommonConfiguration","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"type":"topic","title":"MagnifEyeLivenessViewController.Configuration","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"deprecated":true,"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"title":"MagnifEyeLivenessViewController","role":"symbol","type":"topic","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class/common":{"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/common","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/common","title":"common","abstract":[{"type":"text","text":"Common configuration for all UI components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}]}]}]}