{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration\/libraries"},"metadata":{"fragments":[{"kind":"identifier","text":"libraries"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"libraries","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(py)libraries","navigatorTitle":[{"text":"libraries","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries","text":"Libraries"},{"kind":"text","text":" * "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"abstract":[{"text":"Libraries configuration.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdkconfiguration\/libraries"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkConfiguration/libraries":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration\/libraries","fragments":[{"text":"libraries","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"libraries","abstract":[{"text":"Libraries configuration.","type":"text"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotsdkconfiguration\/libraries"},"doc://DotFingersCore/documentation/DotFingersCore/Libraries":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Libraries","title":"Libraries","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkConfiguration":{"fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotsdkconfiguration","abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkConfiguration","title":"DotSdkConfiguration","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"Libraries","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Libraries\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}