{"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/sample\/bgrarawimage"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample"]]},"abstract":[{"type":"text","text":"Sample image."}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample\/bgraRawImage","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bgraRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"title":"bgraRawImage","roleHeading":"Instance Property","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC6SampleC12bgraRawImage0aC004BgraiJ0Cvp"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Sample":{"title":"PalmAutoCaptureController.Sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the palm auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Sample"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Sample"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/sample","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage","type":"topic","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","title":"BgraRawImage","kind":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Sample/bgraRawImage":{"abstract":[{"text":"Sample image.","type":"text"}],"title":"bgraRawImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgraRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample\/bgraRawImage","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/sample\/bgrarawimage","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"type":"topic","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"title":"PalmAutoCaptureController","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}