{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/DotSdkError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkError.composeWithInternalError()","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"extendedModule":"DotCore","symbolKind":"method","title":"composeWithInternalError()","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:6DotNfc27MachineReadableZonePasswordC5ErrorO","modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/composewithinternalerror()"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/composeWithInternalError()"},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","role":"symbol","navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"type":"topic","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"title":"MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/composeWithInternalError()":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/composewithinternalerror()","title":"composeWithInternalError()","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/composeWithInternalError()"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","role":"symbol","title":"MachineReadableZonePassword.Error","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/DotSdkError-Implementations":{"type":"topic","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/dotsdkerror-implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","role":"collectionGroup","kind":"article","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","title":"NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTNMachineReadableZonePassword","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title"},{"value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}