{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Detected position of the finger."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerdetector\/finger\/position"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger"]]},"kind":"symbol","sections":[],"metadata":{"title":"position","externalID":"s:14DotFingersCore14FingerDetectorC0D0C8positionAA17DetectionPositionCvp","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger\/position","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger/position":{"title":"position","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"abstract":[{"type":"text","text":"Detected position of the finger."}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger\/position","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger\/position"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFGFingerDetector","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerDetector"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","value":"DOTFGDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}