{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerdetector\/finger\/type"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Type of the detected finger."}],"metadata":{"title":"type","externalID":"s:14DotFingersCore14FingerDetectorC0D0C4typeAA0D4TypeOvp","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","text":"FingerType"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger\/type","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger/type":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger\/type","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerType","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier"}],"title":"type","url":"\/documentation\/dotfingerscore\/fingerdetector\/finger\/type","kind":"symbol","abstract":[{"type":"text","text":"Type of the detected finger."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"text":"DOTFGFingerType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]}]}]}