{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/dotsdkerror-implementations"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"DotSdkError Implementations"},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/errorDescription"],"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/composeWithInternalError()"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","title":"FingerToFingerprintTransformer","navigatorTitle":[{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error":{"type":"topic","title":"FingerToFingerprintTransformer.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error/composeWithInternalError()":{"role":"symbol","title":"composeWithInternalError()","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/composewithinternalerror()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/composeWithInternalError()","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error/errorDescription":{"title":"errorDescription","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/errordescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/errorDescription"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error/description":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/description","title":"description","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/description","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingerToFingerprintTransformer","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle"}]}]}