{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/failurereason"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"metadata":{"title":"failureReason","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"10.10","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:14DotFingersCore30FingerToFingerprintTransformerC5ErrorO","symbolKind":"property","extendedModule":"Foundation","modules":[{"name":"DotFingersCore","relatedModules":["Foundation"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/failureReason","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","title":"FingerToFingerprintTransformer","navigatorTitle":[{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerToFingerprintTransformer","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error/failureReason":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error\/failurereason","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"title":"failureReason","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error\/failureReason"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error":{"type":"topic","title":"FingerToFingerprintTransformer.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFGFingerToFingerprintTransformer","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}