{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class\/instructionCandidateSelectionTextColor","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC38instructionCandidateSelectionTextColorSo7UIColorCvp","roleHeading":"Instance Property","title":"instructionCandidateSelectionTextColor","role":"symbol"},"abstract":[{"type":"text","text":"Instruction label text color during candidate selection phase."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class\/instructioncandidateselectiontextcolor"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","abstract":[{"text":"UI Document Auto Capture component","type":"text"},{"text":" ","type":"text"},{"text":"A visual component for capturing good quality document images suitable for optical character recognition. This component provides an UI.","type":"text"},{"text":" ","type":"text"},{"text":"It includes a placeholder for the document, a detection layer that displays the tracking rectangle and an instruction.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","role":"symbol","title":"DocumentAutoCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class/instructionCandidateSelectionTextColor":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class\/instructioncandidateselectiontextcolor","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class\/instructionCandidateSelectionTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","title":"instructionCandidateSelectionTextColor","abstract":[{"type":"text","text":"Instruction label text color during candidate selection phase."}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}