{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class\/instructiontextcolor"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","externalID":"s:11DotDocument0B25AutoCaptureViewControllerC5StyleC20instructionTextColorSo7UIColorCvp","symbolKind":"property","title":"instructionTextColor"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","abstract":[{"text":"Instruction label text color.","type":"text"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class\/instructionTextColor","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","title":"DocumentAutoCaptureViewController","abstract":[{"text":"UI Document Auto Capture component","type":"text"},{"text":" ","type":"text"},{"text":"A visual component for capturing good quality document images suitable for optical character recognition. This component provides an UI.","type":"text"},{"text":" ","type":"text"},{"text":"It includes a placeholder for the document, a detection layer that displays the tracking rectangle and an instruction.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class/instructionTextColor":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class\/instructiontextcolor","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class\/instructionTextColor","abstract":[{"text":"Instruction label text color.","type":"text"}],"role":"symbol","title":"instructionTextColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionTextColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Style-swift.class":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the document auto capture user interface.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Style-swift.class","role":"symbol","title":"DocumentAutoCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/navigatorTitle"}]}]}