{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"role":"symbol","navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"roleHeading":"Class","externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedC","title":"DotFaceDetectionModuleConfiguration.Balanced","modules":[{"name":"DotFaceCore"}]},"abstract":[{"type":"text","text":"Face detection balanced module."}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"],"anchor":"Initializers"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DotFaceDetectionModuleConfigurationBalanced) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration\/balanced"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotFaceCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration/Balanced":{"title":"DotFaceDetectionModuleConfiguration.Balanced","abstract":[{"text":"Face detection balanced module.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration\/balanced","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Balanced"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Balanced"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration/Balanced/init()":{"title":"init()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration\/balanced\/init()","abstract":[]}},"variantOverrides":[{"patch":[{"value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}