{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]]},"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"title":"isDocumentEnabled","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isDocumentEnabled"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isdocumentenabled"]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isdocumentenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","kind":"symbol","title":"DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isdocumentenabled","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","type":"topic","kind":"symbol","required":true,"title":"isDocumentEnabled","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isDocumentEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isDocumentEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/navigatorTitle"},{"value":"isDocumentEnabled","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments","value":[{"text":"isDocumentEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}