{"metadata":{"symbolKind":"property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"required":true,"title":"isFaceEyeGazeLivenessScoreEnabled","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","abstract":[],"type":"topic","required":true,"title":"isFaceEyeGazeLivenessScoreEnabled"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.8.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title","op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments"}]}]}