{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(faceLiteAutoCaptureViewControllerCandidateSelectionStarted:) "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollercandidateselectionstarted(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerCandidateSelectionStarted(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController"},{"kind":"text","text":")"}],"title":"faceAutoCaptureViewControllerCandidateSelectionStarted(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate(im)faceLiteAutoCaptureViewControllerCandidateSelectionStarted:","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 5.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FaceAutoCaptureViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerCandidateSelectionStarted(_:)":{"role":"symbol","title":"faceAutoCaptureViewControllerCandidateSelectionStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerCandidateSelectionStarted(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollercandidateselectionstarted(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"DOTFLFaceAutoCaptureViewController"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFLFaceAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewControllerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerCandidateSelectionStarted(_:)\/title","value":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerCandidateSelectionStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerCandidateSelectionStarted:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}