{"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class\/init()"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class"]]},"kind":"symbol","metadata":{"externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleCAEycfc","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"title":"init()","platforms":[]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","role":"symbol","title":"MagnifEyeLivenessViewController","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class\/init()","type":"topic","deprecated":true,"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class\/init()","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class":{"kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class","type":"topic","abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"title":"MagnifEyeLivenessViewController.Style","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class"}},"variantOverrides":[{"patch":[{"value":"DOTFLMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}