{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/loggerloglevel\/equatable-implementations"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"article","metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/Equatable-Implementations"},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel/!=(_:_:)":{"title":"!=(_:_:)","url":"\/documentation\/dotfacecore\/loggerloglevel\/!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel\/!=(_:_:)","role":"symbol","kind":"symbol","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.4.0"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"type":"topic","url":"\/documentation\/dotfacecore\/loggerloglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerLogLevel"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","title":"LoggerLogLevel","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"abstract":[{"text":"Available log levels.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}