{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceAutoCaptureViewControllerDelegate(im)faceAutoCaptureViewControllerViewDidLayoutSubviews:","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","kind":"typeIdentifier","text":"FaceAutoCaptureViewController"},{"text":")","kind":"text"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"faceAutoCaptureViewControllerViewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidlayoutsubviews(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidlayoutsubviews(_:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"text":"version: 8.13.0","type":"text"}],"role":"collection","type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate":{"role":"symbol","kind":"symbol","title":"FaceAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)":{"title":"faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)","navigatorTitle":[{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollerviewdidlayoutsubviews(_:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"faceAutoCaptureViewControllerViewDidLayoutSubviews:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTFFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/title"},{"value":[{"text":"DOTFFaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/title","op":"replace","value":"faceAutoCaptureViewControllerViewDidLayoutSubviews:"},{"value":[{"kind":"text","text":"- "},{"text":"faceAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","op":"replace"},{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}