{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.recoverySuggestion","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/intervalfloat\/error\/recoverysuggestion"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/LocalizedError-Implementations"]]},"metadata":{"externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","symbolKind":"property","modules":[{"name":"DotFaceLite","relatedModules":["Foundation"]}],"platforms":[{"deprecated":false,"unavailable":false,"name":"iOS","beta":false,"introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"8.0"},{"deprecated":false,"unavailable":false,"name":"macOS","beta":false,"introducedAt":"10.10"},{"deprecated":false,"unavailable":false,"name":"tvOS","beta":false,"introducedAt":"9.0"},{"deprecated":false,"unavailable":false,"name":"watchOS","beta":false,"introducedAt":"2.0"}],"role":"symbol","roleHeading":"Instance Property","title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"extendedModule":"Foundation"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.2.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat":{"url":"\/documentation\/dotfacelite\/intervalfloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalFloat","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error":{"abstract":[],"title":"IntervalFloat.Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacelite\/intervalfloat\/error","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/recoverySuggestion":{"url":"\/documentation\/dotfacelite\/intervalfloat\/error\/recoverysuggestion","kind":"symbol","title":"recoverySuggestion","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/recoverySuggestion"},"doc://DotFaceLite/documentation/DotFaceLite/IntervalFloat/Error/LocalizedError-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"kind":"article","url":"\/documentation\/dotfacelite\/intervalfloat\/error\/localizederror-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalFloat\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalFloat\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}