{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureController(im)initWithConfiguration:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(configuration:)"},"sections":[],"abstract":[{"text":"Create new instance of ","type":"text"},{"code":"FaceAutoCaptureController","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/init(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/init(configuration:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/init(configuration:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","text":"Configuration"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","title":"FaceAutoCaptureController.Configuration","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"role":"symbol","fragments":[{"text":"DOTFLFaceAutoCaptureControllerConfiguration","kind":"identifier"}],"title":"DOTFLFaceAutoCaptureControllerConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"type":"topic","title":"FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/init(configuration:)":{"abstract":[{"text":"Create new instance of ","type":"text"},{"type":"codeVoice","code":"FaceAutoCaptureController"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/init(configuration:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithConfiguration:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/init(configuration:)","title":"init(configuration:)"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 8.8.0","type":"text"}],"type":"topic","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfiguration:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureControllerConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1init(configuration:)\/title","value":"initWithConfiguration:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController~1init(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}],"op":"replace"}]}]}