{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:finished:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:finished:)"]}],"abstract":[{"type":"text","text":"Tells the delegate that the MagnifEye liveness has finished with a result. This callback is called after the component has stopped."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:finished:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(magnifEyeLivenessLiteViewController:finished:) ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"text":" ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult","text":"MagnifEyeLivenessResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"]]},"metadata":{"required":true,"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult","text":"MagnifEyeLivenessResult"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"method","roleHeading":"Instance Method","platforms":[{"beta":false,"deprecated":true,"message":"Use MultiRangeLivenessViewController instead.","unavailable":false}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate(im)magnifEyeLivenessLiteViewController:finished:","title":"magnifEyeLivenessViewController(_:finished:)","navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:finished:"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessResult":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"abstract":[{"text":"The final result of the MagnifEye liveness process.","type":"text"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessresult","navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult","role":"symbol","title":"MagnifEyeLivenessResult","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewController(_:finished:)":{"abstract":[{"text":"Tells the delegate that the MagnifEye liveness has finished with a result. This callback is called after the component has stopped.","type":"text"}],"kind":"symbol","required":true,"title":"magnifEyeLivenessViewController(_:finished:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult"},{"text":")","kind":"text"}],"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:finished:)","navigatorTitle":[{"text":"magnifEyeLivenessLiteViewController:finished:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:finished:)","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"deprecated":true,"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","role":"symbol","title":"MagnifEyeLivenessViewControllerDelegate","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":[{"beta":false,"unavailable":false,"deprecated":true}],"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"magnifEyeLivenessLiteViewController:finished:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:finished:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"DOTFLMagnifEyeLivenessViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"finished:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult","text":"DOTFLMagnifEyeLivenessResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessResult"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"path":"\/deprecationSummary","op":"replace"},{"value":"DOTFLMagnifEyeLivenessResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessResult"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessResult"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessResult\/navigatorTitle","op":"replace"},{"value":"DOTFLMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace"},{"value":"magnifEyeLivenessLiteViewController:finished:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:finished:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewController:finished:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:finished:)\/fragments","op":"replace"},{"value":"DOTFLMagnifEyeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}