{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"neutralExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DetectedFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smileExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DetectedFace"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/init(neutralexpressionface:smileexpressionface:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/init(neutralexpressionface:smileexpressionface:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessResult\/init(neutralExpressionFace:smileExpressionFace:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"neutralExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smileExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":")"}],"title":"init(neutralExpressionFace:smileExpressionFace:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessResult(im)initWithNeutralExpressionFace:smileExpressionFace:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNeutralExpressionFace:smileExpressionFace:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessResult"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","title":"SmileLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessResult":{"role":"symbol","title":"SmileLivenessResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessResult"}],"abstract":[{"type":"text","text":"The result of smile liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessResult"}],"url":"\/documentation\/dotfacecore\/smilelivenessresult"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace":{"role":"symbol","title":"DetectedFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectedFace"}],"abstract":[{"type":"text","text":"Result of face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectedFace"}],"url":"\/documentation\/dotfacecore\/detectedface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SmileLivenessResult/init(neutralExpressionFace:smileExpressionFace:)":{"role":"symbol","title":"init(neutralExpressionFace:smileExpressionFace:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"neutralExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"smileExpressionFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SmileLivenessResult\/init(neutralExpressionFace:smileExpressionFace:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNeutralExpressionFace:smileExpressionFace:"}],"url":"\/documentation\/dotfacecore\/smilelivenessresult\/init(neutralexpressionface:smileexpressionface:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithNeutralExpressionFace:smileExpressionFace:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNeutralExpressionFace:smileExpressionFace:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNeutralExpressionFace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DOTFDetectedFace"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"neutralExpressionFace"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileExpressionFace:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DOTFDetectedFace"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"smileExpressionFace"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessResult\/title","value":"DOTFSmileLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/title","value":"DOTFDetectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/fragments","value":[{"kind":"identifier","text":"DOTFDetectedFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessResult~1init(neutralExpressionFace:smileExpressionFace:)\/title","value":"initWithNeutralExpressionFace:smileExpressionFace:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SmileLivenessResult~1init(neutralExpressionFace:smileExpressionFace:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNeutralExpressionFace:smileExpressionFace:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}