{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/compositecheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td3machinereadablezone\/compositecheckdigit"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/compositeCheckDigit"},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"compositeCheckDigit","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)compositeCheckDigit","symbolKind":"property","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone/compositeCheckDigit":{"kind":"symbol","role":"symbol","title":"compositeCheckDigit","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone\/compositeCheckDigit","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/td3machinereadablezone\/compositecheckdigit","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}]},"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"kind":"symbol","role":"symbol","title":"MrzCheckDigit","type":"topic","url":"\/documentation\/dotnfc\/mrzcheckdigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzCheckDigit"}],"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}]},"doc://DotNfc/documentation/DotNfc/Td3MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"kind":"symbol","url":"\/documentation\/dotnfc\/td3machinereadablezone","role":"symbol","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"title":"Td3MachineReadableZone","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td3MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"compositeCheckDigit","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","text":"DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"compositeCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1compositeCheckDigit\/title","op":"replace"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone~1compositeCheckDigit\/fragments","op":"replace"},{"value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","op":"replace"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","op":"replace"},{"value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","op":"replace"},{"value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","op":"replace"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace"},{"value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td3MachineReadableZone\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}