{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries"}],"title":"libraries"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdk\/configuration\/libraries"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration\/libraries","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Libraries configuration."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Libraries":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/libraries","role":"symbol","title":"Libraries","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"abstract":[{"type":"text","text":"Container for library configurations."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Configuration":{"title":"DotSdk.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotsdk\/configuration"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotsdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","title":"DotSdk","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","role":"symbol","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Configuration/libraries":{"url":"\/documentation\/dotfacecore\/dotsdk\/configuration\/libraries","title":"libraries","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Libraries","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration\/libraries","abstract":[{"type":"text","text":"Libraries configuration."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"Libraries","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/title","op":"replace"},{"value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Libraries\/navigatorTitle","op":"replace"},{"value":"DotSdk","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","op":"replace"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}