{"abstract":[{"type":"text","text":"Specify barcode validation. Default is "},{"type":"text","text":".none"},{"type":"text","text":"."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/barcodeValidation"},"metadata":{"fragments":[{"text":"barcodeValidation","kind":"identifier"}],"navigatorTitle":[{"text":"barcodeValidation","kind":"identifier"}],"title":"barcodeValidation","symbolKind":"property","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(py)barcodeValidation","roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"DOTDBarcodeValidation","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"barcodeValidation","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/barcodevalidation"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/barcodeValidation":{"kind":"symbol","abstract":[{"type":"text","text":"Specify barcode validation. Default is "},{"type":"text","text":".none"},{"type":"text","text":"."}],"fragments":[{"text":"barcodeValidation","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/barcodevalidation","type":"topic","role":"symbol","title":"barcodeValidation","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/barcodeValidation"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"abstract":[{"type":"text","text":"Mode of barcode validation."}],"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"type":"topic","url":"\/documentation\/dotdocument\/barcodevalidation","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","title":"BarcodeValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","role":"symbol","kind":"symbol","title":"DOTDBaseDocumentAutoCaptureConfiguration","fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDBarcodeValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","op":"replace"},{"value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","op":"replace"},{"value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","op":"replace"}]}]}