{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/maxhotspotsscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/maxhotspotsscore"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Maximal valid hotspots score of the detected document.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low hotspots occurrence.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high hotspots occurrence.","type":"text"}],"metadata":{"title":"maxHotspotsScore","roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds(py)maxHotspotsScore","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"maxHotspotsScore"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxHotspotsScore","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"DotDocument"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/maxHotspotsScore"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble"},{"kind":"text","text":"?"}]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/maxHotspotsScore":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxHotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Maximal valid hotspots score of the detected document."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low hotspots occurrence."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents high hotspots occurrence."}],"url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/maxhotspotsscore","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/maxHotspotsScore","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"maxHotspotsScore","kind":"identifier"}],"title":"maxHotspotsScore"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"url":"\/documentation\/dotdocument\/wrappeddouble","kind":"symbol","title":"WrappedDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","title":"DocumentAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxHotspotsScore"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxHotspotsScore"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","text":"DOTWrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" * ","kind":"text"},{"text":"maxHotspotsScore","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds~1maxHotspotsScore\/title","value":"maxHotspotsScore"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds~1maxHotspotsScore\/fragments","value":[{"text":"maxHotspotsScore","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}