{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/minsharpness"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/minsharpness"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/minSharpness","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","title":"minSharpness","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds(py)minSharpness","navigatorTitle":[{"text":"minSharpness","kind":"identifier"}],"role":"symbol"},"sections":[],"abstract":[{"text":"Minimal valid sharpness of the detected document.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents blurry document.","type":"text"},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents sharp document.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"kind":"symbol","title":"DocumentAutoCaptureQualityAttributeThresholds","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"text":" ","type":"text"},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/minSharpness":{"type":"topic","title":"minSharpness","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/minsharpness","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/minSharpness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minSharpness"}],"abstract":[{"text":"Minimal valid sharpness of the detected document.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents blurry document.","type":"text"},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents sharp document.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"url":"\/documentation\/dotdocument\/wrappeddouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","title":"WrappedDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"minSharpness","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"minSharpness"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTWrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" * ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds~1minSharpness\/title","value":"minSharpness","op":"replace"},{"op":"replace","value":[{"text":"minSharpness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds~1minSharpness\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}