{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Wrapped","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureResult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"text":"?)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/init(preview:phase:detection:result:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"role":"symbol","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview"},{"kind":"text","text":", "},{"kind":"externalParam","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult","text":"FaceAutoCaptureResult"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","title":"init(preview:phase:detection:result:)","externalID":"s:11DotFaceCore0B18AutoCaptureUiStateC7RunningC7preview5phase9detection6resultAE0aB7Commons0bdE7PreviewC_AJ0bdE5PhaseO7WrappedCSgAA0bdE9DetectionCSgAA0bdE6ResultCSgtcfc","modules":[{"name":"DotFaceCore"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"role":"symbol","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"title":"FaceAutoCaptureUiState","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePreview":{"navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"title":"FaceAutoCapturePreview","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePreview","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfacecore\/faceautocapturepreview"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running/init(preview:phase:detection:result:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview"},{"text":", ","kind":"text"},{"text":"phase","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"},{"text":".","kind":"text"},{"text":"Wrapped","kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC"},{"text":"?, ","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"text":"?, ","kind":"text"},{"text":"result","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"text":"?)","kind":"text"}],"title":"init(preview:phase:detection:result:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running\/init(preview:phase:detection:result:)","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running\/init(preview:phase:detection:result:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Wrapped":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","title":"FaceAutoCapturePhase.Wrapped","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"url":"\/documentation\/dotfacecore\/faceautocapturephase\/wrapped","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureUiState/Running":{"abstract":[{"text":"Running state.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureuistate\/running","title":"FaceAutoCaptureUiState.Running","navigatorTitle":[{"text":"Running","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureUiState\/Running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCapturePhase","url":"\/documentation\/dotfacecore\/faceautocapturephase","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"title":"FaceAutoCaptureResult","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureresult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureUiState\/navigatorTitle"},{"value":"DOTFaceAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/fragments"},{"value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePreview\/navigatorTitle"},{"value":"DOTFaceAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle"},{"value":"DOTFFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle"},{"value":"DOTFFaceAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title"},{"value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}