{"abstract":[{"text":"Module configuration.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/modules-swift.property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(py)modules","title":"modules","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"platforms":["iOS"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"title":"DotPalmLibraryConfiguration","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/modules-swift.property":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/modules-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier"}],"type":"topic","abstract":[{"text":"Module configuration.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.property","role":"symbol","title":"modules","navigatorTitle":[{"text":"modules","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfigurationModules":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules","kind":"symbol","role":"symbol","type":"topic","title":"DotPalmLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotfacecore\/dotpalmlibraryconfigurationmodules","abstract":[{"text":"Palm library module configuration.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"modules","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfigurationModules"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration~1modules-swift.property\/title","value":"modules","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration~1modules-swift.property\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}