{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/phase"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Current phase of the fingers auto capture process.","type":"text"}],"metadata":{"title":"phase","symbolKind":"property","externalID":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC5phaseAA0bdE5PhaseOvp","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","kind":"typeIdentifier","text":"FingersAutoCapturePhase"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCapturePhase","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/phase","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"role":"symbol","title":"FingersAutoCaptureController.ProcessingResult","navigatorTitle":[{"text":"ProcessingResult","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult/phase":{"role":"symbol","title":"phase","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult\/phase","abstract":[{"type":"text","text":"Current phase of the fingers auto capture process."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","text":"FingersAutoCapturePhase","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult\/phase","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"role":"symbol","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"text":"Phase of the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePhase","kind":"identifier"}],"title":"FingersAutoCapturePhase","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle"},{"value":"DOTFGFingersAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle"}]}]}