{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"barcode","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp","role":"symbol","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"title":"DotDocumentLibraryConfiguration.Modules","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"text":"Document library module configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"barcode","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"url":"\/documentation\/dotfacecore\/dotdocumentbarcodemoduleconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol","title":"DotDocumentBarcodeModuleConfiguration","type":"topic","role":"symbol","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"title":"DotDocumentLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","role":"symbol","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"}]}]}