{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAeA0ac13BarcodeModuleE0CSg_tcfc","title":"init(barcode:)","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"title":"DotDocumentLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentBarcodeModuleConfiguration":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentBarcodeModuleConfiguration","title":"DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotfacecore\/dotdocumentbarcodemoduleconfiguration","kind":"symbol","type":"topic","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","title":"init(barcode:)","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Document library module configuration."}],"title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class"}},"variantOverrides":[{"patch":[{"value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}