{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute\/init(angle:preconditionsMet:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"title":"init(angle:preconditionsMet:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"angle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"preconditionsMet"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithAngle:preconditionsMet:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute(im)initWithAngle:preconditionsMet:","modules":[{"name":"DotFaceCore"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"angle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"preconditionsMet","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/headposeattribute\/init(angle:preconditionsmet:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/init(angle:preconditionsmet:)"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute/init(angle:preconditionsMet:)":{"title":"init(angle:preconditionsMet:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"initWithAngle:preconditionsMet:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute\/init(angle:preconditionsMet:)","type":"topic","url":"\/documentation\/dotfacecore\/headposeattribute\/init(angle:preconditionsmet:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"angle"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"preconditionsMet"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"role":"symbol","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"title":"HeadPoseAttribute","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithAngle:preconditionsMet:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAngle:preconditionsMet:"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithAngle:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"kind":"internalParam","text":"angle"},{"text":" ","kind":"text"},{"text":"preconditionsMet:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"preconditionsMet","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute~1init(angle:preconditionsMet:)\/title","op":"replace","value":"initWithAngle:preconditionsMet:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute~1init(angle:preconditionsMet:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAngle:preconditionsMet:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}