{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"preconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"In case this flag is set to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":", the resulting angle is not reliable.","type":"text"}]}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/preconditionsMet","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"text":" when the preconditions for the evaluation of this head pose attribute were met. If the preconditions were not met, this is ","type":"text"},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"preconditionsMet","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preconditionsMet"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute(py)preconditionsMet","navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/headposeattribute\/preconditionsmet"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/preconditionsmet"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"title":"HeadPoseAttribute","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"url":"\/documentation\/dotfacecore\/headposeattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/preconditionsMet":{"url":"\/documentation\/dotfacecore\/headposeattribute\/preconditionsmet","role":"symbol","title":"preconditionsMet","abstract":[{"type":"text","text":"This is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this head pose attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"preconditionsMet","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/preconditionsMet","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"preconditionsMet","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"preconditionsMet","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"preconditionsMet","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"value":"preconditionsMet","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1preconditionsMet\/title"},{"value":[{"text":"preconditionsMet","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1preconditionsMet\/fragments"}]}]}