{"metadata":{"title":"description","symbolKind":"property","role":"symbol","externalID":"s:11DotPalmCore0B8DetectorC0B0C11descriptionSSvp","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm\/description"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm"]]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","type":"topic","title":"PalmDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"kind":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","title":"PalmDetector.Palm","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","abstract":[{"type":"text","text":"Result of the palm detection process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/description":{"title":"description","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/description","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","op":"replace"}]}]}