{"metadata":{"externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC7isEqualySbypSgF","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Method","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","title":"isEqual(_:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/isEqual(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/placeholder\/visible\/isequal(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/placeholder\/visible\/isequal(_:)","kind":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/placeholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","title":"Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible":{"role":"symbol","title":"Placeholder.Visible","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"navigatorTitle":[{"text":"Visible","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholder\/visible","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible","abstract":[{"text":"Visible placeholder.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","op":"replace","value":"DOTPlaceholder"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}]}]}]}