{"metadata":{"externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC4typeAA0D4TypeOvp","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType"}],"symbolKind":"property","title":"type"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"]]},"kind":"symbol","abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"code":".circle","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/type"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/placeholder\/visible\/type"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PlaceholderType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible/type":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/type","type":"topic","title":"type","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/placeholder\/visible\/type","kind":"symbol","abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"code":".circle","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible":{"role":"symbol","title":"Placeholder.Visible","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"navigatorTitle":[{"text":"Visible","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholder\/visible","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible","abstract":[{"text":"Visible placeholder.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","title":"PlaceholderType","type":"topic","abstract":[{"text":"Type of placeholder.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/placeholdertype","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/placeholder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","title":"Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPlaceholderType","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","op":"replace"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","op":"replace"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","op":"replace"},{"value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","op":"replace"},{"value":[{"text":"DOTPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","op":"replace"}]}]}