{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults"]]},"variants":[{"paths":["\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/validationmode"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:11DotDocument04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV14validationModeAA010ValidationK0OvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"}],"role":"symbol","title":"validationMode","roleHeading":"Type Property","modules":[{"name":"DotDocument"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/validationMode","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults/validationMode":{"type":"topic","title":"validationMode","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults\/validationmode","role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validationMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"ValidationMode","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults\/validationMode","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration/Defaults":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration\/Defaults","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration\/defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"title":"BaseDocumentAutoCaptureViewController.Configuration.Defaults","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController/Configuration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController\/Configuration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"role":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"BaseDocumentAutoCaptureViewController.Configuration","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","title":"ValidationMode","abstract":[],"url":"\/documentation\/dotdocument\/validationmode","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}]},"doc://DotDocument/documentation/DotDocument/BaseDocumentAutoCaptureViewController":{"type":"topic","title":"BaseDocumentAutoCaptureViewController","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/basedocumentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BaseDocumentAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing document images with customizable UI."}],"navigatorTitle":[{"kind":"identifier","text":"BaseDocumentAutoCaptureViewController"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDocumentAutoCaptureViewController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle","value":[{"text":"DOTDValidationMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/title","value":"DOTDBaseDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BaseDocumentAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureViewController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}