{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/CustomStringConvertible-Implementations"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"extendedModule":"DotCore","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","roleHeading":"Instance Property","role":"symbol","modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/description"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/description":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/description","title":"description","abstract":[],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/description"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","title":"CardAccessNumberPassword.Error","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"type":"topic","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"title":"NfcTravelDocumentReader","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","role":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/CustomStringConvertible-Implementations","role":"collectionGroup","title":"CustomStringConvertible Implementations","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/customstringconvertible-implementations","type":"topic","kind":"article","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"kind":"symbol","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CardAccessNumberPassword","kind":"identifier"}],"abstract":[{"text":"Card Access Number as a password.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","title":"CardAccessNumberPassword","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace"}]}]}