{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","text":"PlaceholderType"},{"kind":"text","text":")"}],"role":"symbol","roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"title":"init(type:)","externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC4typeAeA0D4TypeO_tcfc","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","text":"PlaceholderType"},{"kind":"text","text":" = .circle)"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/init(type:)"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/placeholder\/visible\/init(type:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible":{"url":"\/documentation\/dotfacecore\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"title":"Placeholder.Visible","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Visible","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder":{"url":"\/documentation\/dotfacecore\/placeholder","abstract":[{"type":"text","text":"Placeholder."}],"title":"Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of placeholder."}],"url":"\/documentation\/dotfacecore\/placeholdertype","title":"PlaceholderType","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType"},"doc://DotFaceCore/documentation/DotFaceCore/Placeholder/Visible/init(type:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier","text":"PlaceholderType"},{"kind":"text","text":")"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Placeholder\/Visible\/init(type:)","url":"\/documentation\/dotfacecore\/placeholder\/visible\/init(type:)","title":"init(type:)","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/title","value":"DOTPlaceholder","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","value":"DOTPlaceholderType","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}