{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/init(bgrarawimage:document:traveldocumenttype:machinereadablezone:validatoridentifiers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/init(bgrarawimage:document:traveldocumenttype:machinereadablezone:validatoridentifiers:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage"},{"text":", ","kind":"text"},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Document","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone"},{"kind":"text","text":"?, "},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"text":"machineReadableZone","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"kind":"text","text":"?, "},{"text":"validatorIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"symbolKind":"init","roleHeading":"Initializer","title":"init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)","role":"symbol","navigatorTitle":[{"text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(im)initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"title":"DocumentDetector","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","url":"\/documentation\/dotdocument\/documentdetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetection","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"kind":"symbol","title":"DocumentAutoCaptureDetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)":{"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"document","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"text":"Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"text":": ","kind":"text"},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"])","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)","abstract":[],"url":"\/documentation\/dotdocument\/documentautocapturedetection\/init(bgrarawimage:document:traveldocumenttype:machinereadablezone:validatoridentifiers:)","role":"symbol","navigatorTitle":[{"text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:","kind":"identifier"}],"title":"init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"abstract":[{"type":"text","text":"Wrapped "},{"code":"TravelDocumentType","type":"codeVoice"},{"text":" for Objective-C support.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"title":"TravelDocumentTypeWrapper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"title":"DocumentAutoCaptureController","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic"},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"type":"topic","title":"MachineReadableZone","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"title":"DocumentDetector.Document","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","role":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/document","navigatorTitle":[{"kind":"identifier","text":"Document"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"abstract":[{"text":"Result of the document detection process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","type":"topic","title":"DOTDDocumentDetectorDocument","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithBgraRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"document:"},{"kind":"text","text":"("},{"text":"DOTDDocumentDetectorDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"document"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType:"},{"text":"(","kind":"text"},{"text":"DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":" *) "},{"text":"travelDocumentType","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone:"},{"kind":"text","text":"("},{"text":"DOTMachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTMachineReadableZone"},{"kind":"text","text":" *) "},{"text":"machineReadableZone","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"text":"validatorIdentifiers","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","value":"DOTDDocumentAutoCaptureDetection","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"text":"DOTDDocumentAutoCaptureDetection","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)\/title","op":"replace","value":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1init(bgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgraRawImage:document:travelDocumentType:machineReadableZone:validatorIdentifiers:"}]},{"op":"replace","value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}