{"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"typeIdentifier","text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"], "},{"text":"transactionCountingToken","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transactionCountingToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"]},{"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration/init(licenseBytes:libraries:transactionCountingToken:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/init(licenseBytes:libraries:transactionCountingToken:)","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:transactioncountingtoken:)","type":"topic","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"transactionCountingToken"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?)","kind":"text"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"kind":"symbol","title":"DotSdkConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkConfiguration"}],"type":"topic","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotfacelite\/dotsdkconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"symbol","url":"\/documentation\/dotfacelite\/dotlibrary","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"abstract":[],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithLicenseBytes:libraries:transactionCountingToken:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithLicenseBytes:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transactionCountingToken:"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"transactionCountingToken"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/title","value":"initWithLicenseBytes:libraries:transactionCountingToken:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration~1init(licenseBytes:libraries:transactionCountingToken:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}]},{"op":"replace","value":"DotSdkConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/fragments"},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]}]}]}