{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:)"]},{"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/init(licenseBytes:libraries:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","roleHeading":"Initializer","title":"init(licenseBytes:libraries:)","symbolKind":"init","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"text":"])","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"title":"DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibrary","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration":{"url":"\/documentation\/dotfacelite\/dotsdkconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","type":"topic","title":"DotSdkConfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration/init(licenseBytes:libraries:)":{"url":"\/documentation\/dotfacelite\/dotsdkconfiguration\/init(licensebytes:libraries:)","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/init(licenseBytes:libraries:)","type":"topic","title":"init(licenseBytes:libraries:)","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"text":"])","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.14.0"}],"title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLicenseBytes:libraries:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"libraries","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/title","op":"replace","value":"DotSdkConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/title","op":"replace","value":"initWithLicenseBytes:libraries:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}]}]}]}