{"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries"},{"text":" *) ","kind":"text"},{"text":"libraries","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"transactionCountingToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transactionCountingToken","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"initWithLicenseBytes:libraries:transactionCountingToken:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:transactionCountingToken:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:transactionCountingToken:"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration/initWithLicenseBytes:libraries:transactionCountingToken:":{"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotfacelite\/dotsdkconfiguration\/initwithlicensebytes:libraries:transactioncountingtoken:","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/initWithLicenseBytes:libraries:transactionCountingToken:","title":"initWithLicenseBytes:libraries:transactionCountingToken:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:transactionCountingToken:"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration":{"url":"\/documentation\/dotfacelite\/dotsdkconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","kind":"symbol","type":"topic","abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}],"title":"DotSdkConfiguration","role":"symbol","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"url":"\/documentation\/dotfacelite\/libraries","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"title":"Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle"}]}]}