{"variants":[{"paths":["\/documentation\/dotpalmcore\/commonconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/commonconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"metadata":{"title":"hash","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration(py)hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/hash","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration/hash":{"abstract":[],"title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/commonconfiguration\/hash","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/commonconfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"role":"symbol","abstract":[{"text":"Common configuration for all components.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hash"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]}]}]}