{"kind":"symbol","abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"text":".fit","type":"text"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"fragments":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"title":"cameraPreviewScaleType","roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration(py)cameraPreviewScaleType"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/cameraPreviewScaleType","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","kind":"typeIdentifier","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/camerapreviewscaletype"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","kind":"symbol","title":"DOTFLFaceAutoCaptureConfiguration","fragments":[{"text":"DOTFLFaceAutoCaptureConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration/cameraPreviewScaleType":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/cameraPreviewScaleType","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/camerapreviewscaletype","kind":"symbol","fragments":[{"text":"cameraPreviewScaleType","kind":"identifier"}],"abstract":[{"text":"Specify camera preview scale type. Default is ","type":"text"},{"text":".fit","type":"text"},{"text":".","type":"text"}],"role":"symbol","title":"cameraPreviewScaleType"}},"variantOverrides":[{"patch":[{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}