{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBaseConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFLBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"baseConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTPlaceholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placeholder"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"]]},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration(im)initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","navigatorTitle":[{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}],"title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"title":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"symbol","fragments":[{"text":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Face Auto Capture component."}],"title":"DOTFLFaceAutoCaptureConfiguration","kind":"symbol","fragments":[{"text":"DOTFLFaceAutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"abstract":[{"type":"text","text":"Placeholder."}],"type":"topic","url":"\/documentation\/dotfacelite\/placeholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","title":"Placeholder","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:","navigatorTitle":[{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","value":"DOTPlaceholder","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"op":"replace"}]}]}