{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerap-3mcui"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","symbolKind":"method","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFLQualityAttributeThresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"minValidFramesInRowToStartCandidateSelection:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":" "},{"text":"candidateSelectionDurationMillis:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"text":" ","kind":"text"},{"text":"captureMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","text":"DOTCaptureMode"},{"text":") ","kind":"text"},{"text":"captureMode","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaceholderVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isPlaceholderVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled:"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraFacing:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isCameraPreviewVisible"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLQualityAttributeThresholds":{"fragments":[{"kind":"identifier","text":"DOTFLQualityAttributeThresholds"}],"url":"\/documentation\/dotfacelite\/dotflqualityattributethresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","type":"topic","role":"symbol","title":"DOTFLQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"url":"\/documentation\/dotfacelite\/capturemode","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"role":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"title":"CaptureMode","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerap-3mcui","kind":"symbol","title":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","kind":"identifier"}],"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:error:","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","title":"DOTFLFaceAutoCaptureConfiguration","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","type":"topic","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureConfiguration"}],"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"title":"CameraFacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"value":"DOTCameraPreviewScaleType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}