{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td1:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"text":"td1","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","text":"Td1MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td1:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td1:)"]}],"metadata":{"symbolKind":"init","modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMachineReadableZone(im)initWithLines:td1:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td1:"}],"title":"init(lines:td1:)"},"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZone":{"type":"topic","title":"MachineReadableZone","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotnfc\/machinereadablezone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZone/init(lines:td1:)":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithLines:td1:"}],"title":"init(lines:td1:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"td1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td1:)","url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td1:)","type":"topic","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","kind":"symbol","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"title":"Td1MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLines:td1:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLines:td1:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"lines"},{"kind":"text","text":" "},{"kind":"identifier","text":"td1:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","text":"DOTTd1MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"td1"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/title","value":"DOTMachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td1:)\/title","value":"initWithLines:td1:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td1:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td1:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace"}]}]}