{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/libraries\/facelite"]},{"paths":["\/documentation\/dotnfc\/libraries\/facelite"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Face Lite library configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","title":"faceLite","externalID":"c:@M@DotCore@objc(cs)Libraries(py)faceLite","modules":[{"name":"DotNfc"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"faceLite"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/faceLite","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.4.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Libraries/faceLite":{"role":"symbol","title":"faceLite","abstract":[{"type":"text","text":"Face Lite library configuration."}],"url":"\/documentation\/dotnfc\/libraries\/facelite","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite"},{"kind":"text","text":": "},{"text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration"},{"text":"?","kind":"text"}],"kind":"symbol","navigatorTitle":[{"text":"faceLite","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/faceLite"},"doc://DotNfc/documentation/DotNfc/DotFaceLiteLibraryConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","abstract":[{"type":"text","text":"Face Lite library configuration."}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelitelibraryconfiguration","title":"DotFaceLiteLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Libraries":{"type":"topic","title":"Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Container for library configurations."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","url":"\/documentation\/dotnfc\/libraries","navigatorTitle":[{"kind":"identifier","text":"Libraries"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"faceLite","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"faceLite","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"faceLite"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1faceLite\/title","value":"faceLite"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1faceLite\/fragments","value":[{"kind":"identifier","text":"faceLite"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/title","value":"DotFaceLiteLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","value":[{"kind":"identifier","text":"Libraries"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]}]}]}