{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/hash"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode","doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition"]]},"metadata":{"symbolKind":"property","externalID":"s:11DotDocument7BarcodeC17DetectionPositionC4hashSivp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","role":"symbol","title":"hash","modules":[{"name":"DotDocument"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/barcode\/detectionposition\/hash"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/Barcode":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Barcode"}],"navigatorTitle":[{"kind":"identifier","text":"Barcode"}],"url":"\/documentation\/dotdocument\/barcode","abstract":[{"type":"text","text":"Result of barcode detection process."}],"title":"Barcode","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the barcode in the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition","type":"topic","url":"\/documentation\/dotdocument\/barcode\/detectionposition","title":"Barcode.DetectionPosition","kind":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/Barcode/DetectionPosition/hash":{"url":"\/documentation\/dotdocument\/barcode\/detectionposition\/hash","abstract":[],"role":"symbol","title":"hash","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Barcode\/DetectionPosition\/hash","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/title","op":"replace","value":"DOTDBarcode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/fragments","value":[{"kind":"identifier","text":"DOTDBarcode"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Barcode\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDBarcode"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}