{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/requestcapture()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/requestcapture()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestCapture"}],"symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureViewController(im)requestCapture","title":"requestCapture()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestCapture","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/requestCapture()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/requestCapture()":{"abstract":[{"type":"text","text":"Request capture of the next detection."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"requestCapture"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/requestcapture()","title":"requestCapture()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/requestCapture()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"()"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"type":"topic","role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","kind":"symbol","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"requestCapture"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"requestCapture","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1requestCapture()\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1requestCapture()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestCapture"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}]}]}]}