{"metadata":{"symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"}],"roleHeading":"Instance Property","title":"detection","role":"symbol","externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotnfc\/dotpalmdetectionmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmDetectionModuleConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"kind":"symbol","title":"DotPalmDetectionModuleConfiguration","type":"topic","abstract":[{"text":"Palm detection module configuration.","type":"text"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","title":"DotNfc","abstract":[{"text":"version: 9.1.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"type":"topic","title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class","title":"DotPalmLibraryConfiguration.Modules","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"}],"abstract":[],"url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","title":"detection"}},"variantOverrides":[{"patch":[{"value":"DotPalmDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmDetectionModuleConfiguration\/navigatorTitle"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments"},{"value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}