{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class\/instructionbackgroundcolor"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Instruction background color."}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class\/instructionBackgroundColor","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC26instructionBackgroundColorSo7UIColorCvp","platforms":[{"deprecated":true,"unavailable":false,"message":"Use MultiRangeLivenessViewController instead.","beta":false}],"role":"symbol","title":"instructionBackgroundColor"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class":{"deprecated":true,"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the MagnifEye liveness user interface.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Style"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","role":"symbol","title":"MagnifEyeLivenessViewController.Style","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class/instructionBackgroundColor":{"abstract":[{"text":"Instruction background color.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class\/instructionBackgroundColor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"instructionBackgroundColor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class\/instructionbackgroundcolor","deprecated":true,"title":"instructionBackgroundColor","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}