{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles"]]},"variants":[{"paths":["\/documentation\/dotdocument\/tiltangles\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/tiltangles\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(py)description","symbolKind":"property","role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument/TiltAngles":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles","url":"\/documentation\/dotdocument\/tiltangles","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"TiltAngles"},"doc://DotDocument/documentation/DotDocument/TiltAngles/description":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles\/description","url":"\/documentation\/dotdocument\/tiltangles\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"description"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"type":"link","title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}