{"seeAlsoSections":[{"title":"MRZ reading output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithChecksum"}],"title":"MrzElementWithChecksum","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzElementWithChecksum","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElementWithChecksum"}]},"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with checksum validity flag."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/init(value:positions:hasValidChecksum:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hasValidChecksum","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/isEqual(_:)"]}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzelementwithchecksum"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzelementwithchecksum"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDMrzElementWithChecksum) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithChecksum"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithChecksum":{"role":"symbol","title":"MrzDateElementWithChecksum","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithChecksum"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithChecksum"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithChecksum"}],"url":"\/documentation\/dotdocument\/mrzdateelementwithchecksum"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/isEqual(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/isequal(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/hasValidChecksum":{"role":"symbol","title":"hasValidChecksum","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Checksum validity flag."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hasValidChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hasValidChecksum"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/hasvalidchecksum"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/hash":{"role":"symbol","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hash","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/hash"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum":{"role":"symbol","title":"MrzElementWithChecksum","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElementWithChecksum"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with checksum validity flag."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElementWithChecksum"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.4.2"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"role":"symbol","title":"MrzElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDate":{"role":"symbol","title":"MrzDate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"url":"\/documentation\/dotdocument\/mrzdate"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"role":"symbol","title":"Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"role":"symbol","title":"MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone name element with primary and secondary elements."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"url":"\/documentation\/dotdocument\/mrznameelement"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzStringPosition":{"role":"symbol","title":"MrzStringPosition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzStringPosition"}],"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}],"url":"\/documentation\/dotdocument\/mrzstringposition"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"role":"symbol","title":"Td1MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"role":"symbol","title":"MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"role":"symbol","title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td3machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/description"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElementWithChecksum/init(value:positions:hasValidChecksum:)":{"role":"symbol","title":"init(value:positions:hasValidChecksum:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"MrzStringPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzStringPosition"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"hasValidChecksum"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/init(value:positions:hasValidChecksum:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}],"url":"\/documentation\/dotdocument\/mrzelementwithchecksum\/init(value:positions:hasvalidchecksum:)"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTDMrzElementWithChecksum"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElementWithChecksum"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDMrzElementWithChecksum"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hasValidChecksum","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/hash"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/init(value:positions:hasValidChecksum:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElementWithChecksum\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"MRZ reading output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithChecksum","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTDMrzElementWithChecksum"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzElement","text":"DOTDMrzElement"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithChecksum\/title","value":"DOTDMrzDateElementWithChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithChecksum\/fragments","value":[{"kind":"identifier","text":"DOTDMrzDateElementWithChecksum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1hasValidChecksum\/title","value":"hasValidChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1hasValidChecksum\/fragments","value":[{"kind":"identifier","text":"hasValidChecksum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/title","value":"DOTDMrzElementWithChecksum"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElementWithChecksum"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTDMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/title","value":"DOTDMrzDate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTDMrzDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTDTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTDMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNameElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTDMrzStringPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"kind":"identifier","text":"DOTDMrzStringPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTDTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDTd1MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTDMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDMachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","value":"DOTDTd3MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDTd3MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1init(value:positions:hasValidChecksum:)\/title","value":"initWithValue:positions:hasValidChecksum:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElementWithChecksum~1init(value:positions:hasValidChecksum:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:positions:hasValidChecksum:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}