{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"roleHeading":"Instance Property","title":"dependencyIdentifiers","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator(py)dependencyIdentifiers","role":"symbol","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/dependencyIdentifiers"},"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/dependencyIdentifiers":{"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/dependencyIdentifiers","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/dependencyidentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"type":"topic","title":"dependencyIdentifiers","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"type":"topic","title":"BrightnessTooLowValidator","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"dependencyIdentifiers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSSet<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}