{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/detection"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"DotFingersModuleId.detection","externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdDetection","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid\/detection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid\/detection"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/detection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/detection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId.detection","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/detection"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotFingersModuleIdDetection"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFingersModuleIdDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1detection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1detection\/fragments"},{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/title"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/navigatorTitle"}]}]}