{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/RawRepresentable-Implementations"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/hashValue"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/hash(into:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/hashValue":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"hashValue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/hashvalue"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/hash(into:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/hash(into:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}