{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"]},{"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"metadata":{"required":true,"title":"isFaceEyeGazeLivenessScoreEnabled","role":"symbol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceEyeGazeLivenessScoreEnabled","modules":[{"name":"DotNfc"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"roleHeading":"Instance Property"},"references":{"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"abstract":[],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"required":true,"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","title":"isFaceEyeGazeLivenessScoreEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","type":"topic","url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.7.0"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}