{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/errorDescription"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"errorDescription","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:11DotDocument0B8DetectorC5ErrorO","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","extendedModule":"DotCore","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/LocalizedError-Implementations"]]},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/error\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error/errorDescription":{"url":"\/documentation\/dotdocument\/documentdetector\/error\/errordescription","title":"errorDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/errorDescription","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error/LocalizedError-Implementations":{"kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/error\/localizederror-implementations","abstract":[]},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"DocumentDetector.Error","kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"title":"DocumentDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle"}]}]}