{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/description"},"kind":"symbol","metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark(py)description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","platforms":[{"unavailable":false,"name":"iOS","beta":false,"introducedAt":"13.0","deprecated":false}],"title":"description","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","type":"topic","url":"\/documentation\/dotnfc\/traveldocument","abstract":[{"text":"Result of NFC reading.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/description":{"abstract":[],"role":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/description","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/description","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"navigatorTitle":[{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","type":"topic","role":"symbol","title":"DisplayedSignatureOrUsualMark","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"description"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"value":"DOTNDisplayedSignatureOrUsualMark","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}]}]}]}