{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/init(displayedSignatureOrUsualMarkImage:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark"]]},"metadata":{"platforms":[{"name":"iOS","unavailable":false,"beta":false,"introducedAt":"13.0","deprecated":false}],"roleHeading":"Initializer","title":"init(displayedSignatureOrUsualMarkImage:)","externalID":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark(im)initWithDisplayedSignatureOrUsualMarkImage:","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"init","navigatorTitle":[{"text":"initWithDisplayedSignatureOrUsualMarkImage:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"displayedSignatureOrUsualMarkImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage","text":"Image"},{"kind":"text","text":"?)"}]},"variants":[{"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/init(displayedsignatureorusualmarkimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/init(displayedsignatureorusualmarkimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"displayedSignatureOrUsualMarkImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"Image","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/Image":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","url":"\/documentation\/dotnfc\/image","kind":"symbol","navigatorTitle":[{"text":"Image","kind":"identifier"}],"title":"Image","abstract":[{"type":"text","text":"Raw image data representation."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/init(displayedSignatureOrUsualMarkImage:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/init(displayedSignatureOrUsualMarkImage:)","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/init(displayedsignatureorusualmarkimage:)","kind":"symbol","navigatorTitle":[{"text":"initWithDisplayedSignatureOrUsualMarkImage:","kind":"identifier"}],"title":"init(displayedSignatureOrUsualMarkImage:)","abstract":[],"role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"displayedSignatureOrUsualMarkImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage"},{"text":"?)","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"type":"text","text":"version: 8.11.0"}],"role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"navigatorTitle":[{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"type":"topic","role":"symbol","title":"DisplayedSignatureOrUsualMark","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DisplayedSignatureOrUsualMark"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","kind":"symbol","url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithDisplayedSignatureOrUsualMarkImage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithDisplayedSignatureOrUsualMarkImage:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDisplayedSignatureOrUsualMarkImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTNImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},{"kind":"text","text":" *) "},{"text":"displayedSignatureOrUsualMarkImage","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","op":"replace","value":"DOTNImage"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"text":"DOTNImage","kind":"identifier"}]},{"value":"initWithDisplayedSignatureOrUsualMarkImage:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1init(displayedSignatureOrUsualMarkImage:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDisplayedSignatureOrUsualMarkImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1init(displayedSignatureOrUsualMarkImage:)\/fragments"},{"value":"DOTNTravelDocument","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title"},{"value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments"}]}]}