{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","text":"Status","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum"},{"text":", ","kind":"text"},{"text":"wrappedProtocol","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","text":"WrappedProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activeAuthenticationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?)"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:activeauthenticationresponse:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:activeauthenticationresponse:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:activeAuthenticationResponse:)"},"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","text":"Status"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","text":"WrappedProtocol"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"activeAuthenticationResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?)"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(im)initWithStatus:wrappedProtocol:activeAuthenticationResponse:","title":"init(status:wrappedProtocol:activeAuthenticationResponse:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"iPadOS","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false},{"name":"Mac Catalyst","beta":false,"unavailable":false,"introducedAt":"13.0","deprecated":false}]},"references":{"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/init(status:wrappedProtocol:activeAuthenticationResponse:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"status","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Status","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O"},{"text":", ","kind":"text"},{"text":"wrappedProtocol","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"WrappedProtocol","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC"},{"text":"?, ","kind":"text"},{"text":"activeAuthenticationResponse","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:activeAuthenticationResponse:)","kind":"symbol","title":"init(status:wrappedProtocol:activeAuthenticationResponse:)","role":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:activeauthenticationresponse:)"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"type":"topic","role":"symbol","title":"ChipAuthenticationStatus","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"navigatorTitle":[{"text":"Status","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum","abstract":[{"text":"Authentication status of the chip.","type":"text"}],"role":"symbol","title":"ChipAuthenticationStatus.Status","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol":{"title":"ChipAuthenticationStatus.WrappedProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedProtocol"}],"type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedProtocol"}],"abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"code":"AuthenticationProtocol","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusWrappedProtocol":{"title":"DOTNChipAuthenticationStatusWrappedProtocol","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatuswrappedprotocol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","type":"topic","kind":"symbol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"text":"AuthenticationProtocol","type":"text"},{"text":".","type":"text"}],"fragments":[{"text":"DOTNChipAuthenticationStatusWrappedProtocol","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusStatus":{"type":"topic","abstract":[{"type":"text","text":"Authentication status of the chip."}],"role":"symbol","title":"DOTNChipAuthenticationStatusStatus","fragments":[{"text":"DOTNChipAuthenticationStatusStatus","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatusstatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTNChipAuthenticationStatusStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTNChipAuthenticationStatusStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus"},{"kind":"text","text":") "},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"text":"wrappedProtocol:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTNChipAuthenticationStatusWrappedProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatusWrappedProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol"},{"text":" *) ","kind":"text"},{"text":"wrappedProtocol","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"activeAuthenticationResponse:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"activeAuthenticationResponse"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:activeAuthenticationResponse:)\/title","value":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:activeAuthenticationResponse:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithStatus:wrappedProtocol:activeAuthenticationResponse:","kind":"identifier"}],"op":"replace"},{"value":"DOTNChipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","op":"replace"},{"value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","op":"replace"}]}]}