{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdiddisappear(_:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"faceSimpleCaptureViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"title":"faceSimpleCaptureViewControllerViewDidDisappear(_:)","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate(im)faceSimpleCaptureViewControllerViewDidDisappear:","symbolKind":"method","required":true,"role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceSimpleCaptureViewControllerViewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidDisappear(_:)"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"deprecated":true,"kind":"symbol","title":"FaceSimpleCaptureViewController","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidDisappear(_:)":{"abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}],"title":"faceSimpleCaptureViewControllerViewDidDisappear(_:)","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdiddisappear(_:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidDisappear(_:)","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"navigatorTitle":[{"text":"FaceSimpleCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","role":"symbol","title":"FaceSimpleCaptureViewControllerDelegate","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"type":"topic","abstract":[{"type":"text","text":"Implement this delegate to handle the face simple capture events."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"faceSimpleCaptureViewControllerViewDidDisappear:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFFaceSimpleCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"value":"faceSimpleCaptureViewControllerViewDidDisappear:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidDisappear(_:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidDisappear:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title","value":"DOTFFaceSimpleCaptureViewControllerDelegate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFFaceSimpleCaptureViewControllerDelegate","kind":"identifier"}]}]}]}