{"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidload(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidload(_:)"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLoad(_:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate"]]},"sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate(im)faceSimpleCaptureViewControllerViewDidLoad:","roleHeading":"Instance Method","role":"symbol","required":true,"modules":[{"name":"DotFaceCore"}],"title":"faceSimpleCaptureViewControllerViewDidLoad(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","text":"FaceSimpleCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"faceSimpleCaptureViewControllerViewDidLoad:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier","text":"FaceSimpleCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","title":"FaceSimpleCaptureViewControllerDelegate","kind":"symbol","abstract":[{"type":"text","text":"Implement this delegate to handle the face simple capture events."}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotFaceCore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing face images."}],"kind":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate/faceSimpleCaptureViewControllerViewDidLoad(_:)":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate\/faceSimpleCaptureViewControllerViewDidLoad(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad"},{"text":"(","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"faceSimpleCaptureViewControllerViewDidLoad:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate\/facesimplecaptureviewcontrollerviewdidload(_:)","title":"faceSimpleCaptureViewControllerViewDidLoad(_:)","kind":"symbol","abstract":[],"required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"faceSimpleCaptureViewControllerViewDidLoad:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"faceSimpleCaptureViewControllerViewDidLoad:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"faceSimpleCaptureViewControllerViewDidLoad:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController","kind":"typeIdentifier","text":"DOTFFaceSimpleCaptureViewController","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTFFaceSimpleCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewControllerDelegate"}]},{"value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLoad(_:)\/title","value":"faceSimpleCaptureViewControllerViewDidLoad:"},{"value":[{"kind":"text","text":"- "},{"text":"faceSimpleCaptureViewControllerViewDidLoad:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate~1faceSimpleCaptureViewControllerViewDidLoad(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}