{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/deinitialize()","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacelibrary\/deinitialize()"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibrary(im)deinitializeAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"title":"deinitialize()","role":"symbol"},"abstract":[{"text":"Deinitialize library.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary/deinitialize()":{"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize library."}],"url":"\/documentation\/dotfacecore\/dotfacelibrary\/deinitialize()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"deinitialize()","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary","title":"DotFaceLibrary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibrary","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceLibrary"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"deinitializeAndReturnError:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]}},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1deinitialize()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace"},{"value":"DotFaceLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibrary"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}