{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/style-swift.class\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-16pbs"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC5StyleC15backgroundColor15instructionFont0k4TextJ00k18CandidateSelectionmJ00k10BackgroundJ00knopJ0011placeholderJ00qnoJ0014detectionLayerJ0AESo7UIColorC_So6UIFontCA7Ptcfc","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"instructionFont"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionBackgroundColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":")"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"backgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = PreviewViewStyle.Defaults.backgroundColor, ","kind":"text"},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"text":" = InstructionCandidateSelectionStyle.Defaults.font, ","kind":"text"},{"text":"instructionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" = InstructionCandidateSelectionStyle.Defaults.textColor, ","kind":"text"},{"kind":"externalParam","text":"instructionCandidateSelectionTextColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":" = InstructionCandidateSelectionStyle.Defaults.candidateSelectionTextColor, ","kind":"text"},{"kind":"externalParam","text":"instructionBackgroundColor"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"kind":"text","text":" = InstructionCandidateSelectionStyle.Defaults.backgroundColor, "},{"text":"instructionCandidateSelectionBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = InstructionCandidateSelectionStyle.Defaults.candidateSelectionBackgroundColor, ","kind":"text"},{"text":"placeholderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = PlaceholderCandidateSelectionStyle.Defaults.color, ","kind":"text"},{"text":"placeholderCandidateSelectionColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = PlaceholderCandidateSelectionStyle.Defaults.candidateSelectionColor, ","kind":"text"},{"text":"detectionLayerColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier"},{"text":" = PreviewViewStyle.Defaults.detectionLayerColor)","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Style-swift.class/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)":{"title":"init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class\/init(backgroundColor:instructionFont:instructionTextColor:instructionCandidateSelectionTextColor:instructionBackgroundColor:instructionCandidateSelectionBackgroundColor:placeholderColor:placeholderCandidateSelectionColor:detectionLayerColor:)","role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"backgroundColor"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIFont","text":"UIFont"},{"kind":"text","text":", "},{"text":"instructionTextColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionCandidateSelectionTextColor","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"text":"instructionBackgroundColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":", "},{"text":"placeholderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionLayerColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":")"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/style-swift.class\/init(backgroundcolor:instructionfont:instructiontextcolor:instructioncandidateselectiontextcolor:instructionbackgroundcolor:instructioncandidateselectionbackgroundcolor:placeholdercolor:placeholdercandidateselectioncolor:detectionlayercolor-16pbs","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","type":"topic","abstract":[{"text":"UI Palm Auto Capture component.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureViewController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Style-swift.class":{"title":"PalmAutoCaptureViewController.Style","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"abstract":[{"text":"Customization options for the palm auto capture user interface.","type":"text"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/style-swift.class","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Style-swift.class","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","op":"replace"}]}]}