{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateRunning(im)initWithPreview:phase:detection:result:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithPreview:phase:detection:result:"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCapturePreview","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"},{"text":" *) ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCapturePhaseWrapped","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTPPalmAutoCapturePhaseWrapped"},{"text":" *) ","kind":"text"},{"text":"phase","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCaptureDetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCaptureResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/initwithpreview:phase:detection:result:"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning"]]},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"type":"topic","title":"PalmAutoCaptureResult","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning":{"type":"topic","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"title":"DOTPPalmAutoCaptureUiStateRunning","role":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureUiStateRunning","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"title":"PalmAutoCapturePreview","url":"\/documentation\/dotpalmcore\/palmautocapturepreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePreview"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePreview"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","title":"PalmAutoCaptureDetection","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"role":"symbol","kind":"symbol","abstract":[{"text":"The result of processing video frame during the palm auto capture process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","kind":"symbol","title":"initWithPreview:phase:detection:result:","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/initwithpreview:phase:detection:result:","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","value":"DOTPPalmAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","value":"DOTPPalmAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","value":"DOTPPalmAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}]}]}]}