{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/preview"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/preview"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"type":"text","text":"Preview information."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPPalmAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"},{"text":" * ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":";","kind":"text"}]}]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateRunning(py)preview","title":"preview","navigatorTitle":[{"kind":"identifier","text":"preview"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"preview"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/preview":{"kind":"symbol","role":"symbol","title":"preview","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/preview","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/preview","abstract":[{"text":"Preview information.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"preview"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning","type":"topic","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateRunning"}],"title":"DOTPPalmAutoCaptureUiStateRunning","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"url":"\/documentation\/dotpalmcore\/palmautocapturepreview","title":"PalmAutoCapturePreview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePreview"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePreview"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPalmAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle"}]}]}