{"metadata":{"role":"symbol","title":"init(min:max:)","roleHeading":"Initializer","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFValueRange(im)initWithMin:max:error:"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"text":"max","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/valuerange\/init(min:max:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/valuerange\/init(min:max:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/init(min:max:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/init(min:max:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/init(min:max:)","type":"topic","url":"\/documentation\/dotfacecore\/valuerange\/init(min:max:)","kind":"symbol","title":"init(min:max:)","role":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValueRange","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ValueRange"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","url":"\/documentation\/dotfacecore\/valuerange","type":"topic","title":"ValueRange","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Representation of "},{"code":"Double","type":"codeVoice"},{"text":" range, compatible with Objective-C.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithMin:max:error:","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMin:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"min","kind":"internalParam"},{"kind":"text","text":" "},{"text":"max:","kind":"identifier"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"max","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1init(min:max:)\/title","value":"initWithMin:max:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1init(min:max:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMin:max:error:"}]},{"op":"replace","value":"DOTFValueRange","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title"},{"value":[{"kind":"identifier","text":"DOTFValueRange"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}