{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isDetectionLayerVisible, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","text":"CameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"CameraPreviewScaleType"},{"kind":"text","text":" = Defaults.cameraPreviewScaleType)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/init(sessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/init(sessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(im)initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessConfiguration":{"role":"symbol","title":"MagnifEyeLivenessConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessConfiguration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacelite\/camerafacing"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessConfiguration/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)":{"role":"symbol","title":"init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessConfiguration\/init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessconfiguration\/init(sessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.4.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"isTorchEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","text":"DOTCameraFacing"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration\/title","value":"DOTFLMagnifEyeLivenessConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration~1init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/title","value":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessConfiguration~1init(sessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}