{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/activeAuthenticationChallenge"},"variants":[{"paths":["\/documentation\/dotnfc\/debuginfo\/activeauthenticationchallenge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/debuginfo\/activeauthenticationchallenge"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"metadata":{"role":"symbol","symbolKind":"property","platforms":[{"name":"iOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"13.0"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationChallenge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"activeAuthenticationChallenge"}],"title":"activeAuthenticationChallenge","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)activeAuthenticationChallenge","roleHeading":"Instance Property"},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"activeAuthenticationChallenge"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/DebugInfo/activeAuthenticationChallenge":{"title":"activeAuthenticationChallenge","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"activeAuthenticationChallenge"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"activeAuthenticationChallenge","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/debuginfo\/activeauthenticationchallenge","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/activeAuthenticationChallenge","abstract":[]},"doc://DotNfc/documentation/DotNfc/DebugInfo":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DebugInfo","kind":"identifier"}],"navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/debuginfo","title":"DebugInfo"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.15.2","type":"text"}],"role":"collection","type":"topic","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"activeAuthenticationChallenge"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"activeAuthenticationChallenge"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData","text":"NSData"},{"text":" * ","kind":"text"},{"text":"activeAuthenticationChallenge","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1activeAuthenticationChallenge\/title","value":"activeAuthenticationChallenge"},{"op":"replace","value":[{"kind":"identifier","text":"activeAuthenticationChallenge"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1activeAuthenticationChallenge\/fragments"},{"value":"DOTNDebugInfo","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"}]}]}