{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"events","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugEvent","kind":"typeIdentifier","text":"DebugEvent"},{"kind":"text","text":"]"}]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/debuginfo\/events"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/events"]}],"kind":"symbol","sections":[],"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)events","title":"events","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugEvent","text":"DebugEvent"},{"text":"]","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"events","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/events","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/DebugInfo":{"title":"DebugInfo","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugInfo"}],"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DebugInfo"}],"url":"\/documentation\/dotnfc\/debuginfo"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/DebugInfo/events":{"abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"events"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DebugEvent","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugEvent"},{"kind":"text","text":"]"}],"kind":"symbol","title":"events","url":"\/documentation\/dotnfc\/debuginfo\/events","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/events","navigatorTitle":[{"kind":"identifier","text":"events"}]},"doc://DotNfc/documentation/DotNfc/DebugEvent":{"abstract":[],"title":"DebugEvent","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugEvent","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugEvent","kind":"identifier"}],"url":"\/documentation\/dotnfc\/debugevent","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DebugEvent","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"events"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"events"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTNDebugEvent *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"events"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNDebugInfo"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1events\/title","value":"events"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1events\/fragments","value":[{"text":"events","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/title","op":"replace","value":"DOTNDebugEvent"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNDebugEvent"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugEvent\/navigatorTitle","value":[{"text":"DOTNDebugEvent","kind":"identifier"}]}]}]}