{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/nfcKey","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nfcKey","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","kind":"typeIdentifier","text":"NfcKey"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"platforms":[{"deprecated":false,"name":"iOS","beta":false,"introducedAt":"13.0","unavailable":false}],"title":"nfcKey","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)nfcKey","symbolKind":"property","navigatorTitle":[{"text":"nfcKey","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nfcKey"},{"text":": ","kind":"text"},{"text":"NfcKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"text":"?","kind":"text"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/nfckey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/nfckey"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo","title":"DebugInfo","role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/debuginfo","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DebugInfo"}],"navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"url":"\/documentation\/dotnfc\/nfckey","abstract":[{"text":"NFC key created from document number, date of expiry and date of birth.","type":"text"}],"navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcKey"}],"title":"NfcKey"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DebugInfo/nfcKey":{"abstract":[],"kind":"symbol","title":"nfcKey","navigatorTitle":[{"kind":"identifier","text":"nfcKey"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nfcKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NfcKey","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"text":"?","kind":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/debuginfo\/nfckey","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DebugInfo\/nfcKey"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"nfcKey","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"nfcKey","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","text":"DOTNNfcKey"},{"kind":"text","text":" * "},{"text":"nfcKey","kind":"identifier"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"},{"value":"DOTNNfcKey","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","op":"replace"},{"value":[{"text":"DOTNNfcKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1nfcKey\/title","op":"replace","value":"nfcKey"},{"value":[{"text":"nfcKey","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DebugInfo~1nfcKey\/fragments"}]}]}