{"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"password","kind":"identifier"},{"text":": ","kind":"text"},{"text":"TravelDocumentReaderPasswordWrapper","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"text":"password","kind":"identifier"}],"roleHeading":"Instance Property","title":"password","externalID":"c:@M@DotNfc@objc(cs)DOTNDebugInfo(py)password","role":"symbol","modules":[{"name":"DotNfc"}]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper","kind":"typeIdentifier","text":"TravelDocumentReaderPasswordWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/password"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/debuginfo\/password"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/debuginfo\/password"]}],"references":{"doc://DotNfc/documentation/DotNfc/DebugInfo":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DebugInfo","kind":"identifier"}],"navigatorTitle":[{"text":"DebugInfo","kind":"identifier"}],"url":"\/documentation\/dotnfc\/debuginfo","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo","title":"DebugInfo","type":"topic","abstract":[],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPasswordWrapper":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentReaderPasswordWrapper"}],"url":"\/documentation\/dotnfc\/traveldocumentreaderpasswordwrapper","title":"TravelDocumentReaderPasswordWrapper","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"reference","isActive":true,"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DebugInfo/password":{"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"password"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper","text":"TravelDocumentReaderPasswordWrapper"},{"kind":"text","text":"?"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/debuginfo\/password","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DebugInfo\/password","title":"password"},"doc://DotNfc/documentation/DotNfc/TravelDocumentReaderPassword":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumentreaderpassword","navigatorTitle":[{"text":"TravelDocumentReaderPassword","kind":"identifier"}],"abstract":[{"type":"text","text":"Password for accessing the chip."}],"title":"TravelDocumentReaderPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPassword","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"password","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"password","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTNTravelDocumentReaderPasswordWrapper","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocumentReaderPasswordWrapper","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocumentReaderPasswordWrapper","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"password","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/title","value":"DOTNDebugInfo","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/fragments","value":[{"text":"DOTNDebugInfo","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNDebugInfo"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/title","value":"DOTNTravelDocumentReaderPasswordWrapper","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/fragments","value":[{"text":"DOTNTravelDocumentReaderPasswordWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPasswordWrapper\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPasswordWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1password\/title","value":"password","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DebugInfo~1password\/fragments","value":[{"text":"password","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/title","value":"DOTNTravelDocumentReaderPassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/fragments","value":[{"text":"DOTNTravelDocumentReaderPassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocumentReaderPassword\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocumentReaderPassword"}],"op":"replace"}]}]}