{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minTemplateExtractionQuality:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTWrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minTemplateExtractionQuality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minTemplateExtractionQuality:error:"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/mintemplateextractionquality:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"minTemplateExtractionQuality:error:","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"minTemplateExtractionQuality:error:","kind":"identifier"}],"navigatorTitle":[{"text":"minTemplateExtractionQuality:error:","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder(im)minTemplateExtractionQuality:error:","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder/minTemplateExtractionQuality:error:":{"title":"minTemplateExtractionQuality:error:","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minTemplateExtractionQuality:error:","navigatorTitle":[{"text":"minTemplateExtractionQuality:error:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/mintemplateextractionquality:error:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"minTemplateExtractionQuality:error:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"role":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotpalmcore\/wrappeddouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","title":"WrappedDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","role":"symbol","abstract":[],"title":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}