{"abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"type":"codeVoice","code":"null"},{"text":".","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running"]]},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier","text":"FaceAutoCaptureDetection"},{"kind":"text","text":"?"}],"title":"detection","externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC7RunningC9detectionAA0bdE9DetectionCSgvp","role":"symbol","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/detection"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/detection"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"kind":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","title":"FaceAutoCaptureUiState","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running":{"type":"topic","title":"FaceAutoCaptureUiState.Running","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running","navigatorTitle":[{"kind":"identifier","text":"Running"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Running"}],"abstract":[{"type":"text","text":"Running state."}],"kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"kind":"symbol","title":"FaceAutoCaptureDetection","url":"\/documentation\/dotfacelite\/faceautocapturedetection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running/detection":{"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/detection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/detection","abstract":[{"text":"Detection information. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"detection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFLFaceAutoCaptureUiState","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle"},{"op":"replace","value":"DOTFLFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}