{"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/phase","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/phase"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","text":"FaceAutoCapturePhase","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped","text":"Wrapped","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"type":"codeVoice","code":"null"},{"type":"text","text":"."}],"metadata":{"title":"phase","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?"}],"externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC7RunningC5phase0aB7Commons0bdE5PhaseO7WrappedCSgvp","role":"symbol"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacelite\/faceautocaptureuistate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/Wrapped":{"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"url":"\/documentation\/dotfacelite\/faceautocapturephase\/wrapped","abstract":[],"title":"FaceAutoCapturePhase.Wrapped","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running/phase":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/phase","title":"phase","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/phase","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"phase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC","text":"Wrapped"},{"kind":"text","text":"?"}],"role":"symbol","abstract":[{"text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be ","type":"text"},{"code":"null","type":"codeVoice"},{"text":".","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running":{"type":"topic","title":"FaceAutoCaptureUiState.Running","abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Running"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"title":"FaceAutoCapturePhase","url":"\/documentation\/dotfacelite\/faceautocapturephase","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFLFaceAutoCaptureUiState","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle"},{"value":"DOTFaceAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle"}]}]}