{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/preview"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/preview"]}],"metadata":{"title":"preview","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC7RunningC7preview0aB7Commons0bdE7PreviewCvp","roleHeading":"Instance Property"},"abstract":[{"type":"text","text":"Preview information."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","text":"FaceAutoCapturePreview"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"type":"topic","title":"FaceAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePreview"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCapturePreview","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running/preview":{"title":"preview","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running\/preview","abstract":[{"type":"text","text":"Preview information."}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running\/preview","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","text":"FaceAutoCapturePreview"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"FaceAutoCaptureUiState","url":"\/documentation\/dotfacelite\/faceautocaptureuistate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureUiState"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Running":{"type":"topic","title":"FaceAutoCaptureUiState.Running","abstract":[{"type":"text","text":"Running state."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Running","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Running"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/running","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title","value":"DOTFaceAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","value":"DOTFLFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}]}]}]}