{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration"},{"text":"? = nil, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:)"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)Libraries(im)initWithDocument:face:faceLite:nfc:palm:","roleHeading":"Initializer","title":"init(document:face:faceLite:nfc:palm:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","text":"DotDocumentLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"faceLite","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","text":"DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","text":"DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"modules":[{"name":"DotPalmCore"}],"symbolKind":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/Libraries/init(document:face:faceLite:nfc:palm:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"faceLite"},{"text":": ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"nfc","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotNfcLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries\/init(document:face:faceLite:nfc:palm:)","navigatorTitle":[{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/libraries\/init(document:face:facelite:nfc:palm:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","title":"init(document:face:faceLite:nfc:palm:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","kind":"symbol","title":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Libraries":{"url":"\/documentation\/dotpalmcore\/libraries","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"kind":"symbol","title":"Libraries","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotNfcLibraryConfiguration":{"title":"DotNfcLibraryConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"abstract":[{"type":"text","text":"NFC library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotnfclibraryconfiguration","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLiteLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","title":"DotFaceLiteLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotfacelitelibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Face Lite library configuration.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"title":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","title":"DotPalmLibraryConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithDocument:face:faceLite:nfc:palm:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocument:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","kind":"typeIdentifier","text":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"kind":"identifier","text":"face:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"face"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLite:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration","kind":"typeIdentifier","text":"DotFaceLiteLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLiteLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceLite"},{"kind":"text","text":" "},{"kind":"identifier","text":"nfc:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration","kind":"typeIdentifier","text":"DotNfcLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotNfcLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nfc"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"palm"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithDocument:face:faceLite:nfc:palm:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocument:face:faceLite:nfc:palm:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries~1init(document:face:faceLite:nfc:palm:)\/fragments"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/fragments"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Libraries\/navigatorTitle"},{"op":"replace","value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotNfcLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceLiteLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLiteLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle"}]}]}