{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(py)common","navigatorTitle":[{"kind":"identifier","text":"common"}],"modules":[{"name":"DotDocument"}],"role":"symbol","fragments":[{"kind":"identifier","text":"common"}],"symbolKind":"property","roleHeading":"Instance Property","title":"common"},"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/common"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/common"},"references":{"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"title":"CommonConfiguration","url":"\/documentation\/dotdocument\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Common configuration for all components."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","type":"topic","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","title":"DOTDBaseDocumentAutoCaptureConfiguration","fragments":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/common":{"fragments":[{"text":"common","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"role":"symbol","title":"common","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/common","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/common","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]}]}]}