{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(py)mrzValidation","fragments":[{"text":"mrzValidation","kind":"identifier"}],"symbolKind":"property","title":"mrzValidation","navigatorTitle":[{"kind":"identifier","text":"mrzValidation"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDMrzValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"text":" ","kind":"text"},{"text":"mrzValidation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/mrzvalidation"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Specify MRZ validation. Default is "},{"type":"text","text":".none"},{"type":"text","text":"."}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/mrzValidation","interfaceLanguage":"occ"},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"type":"topic","title":"MrzValidation","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}]},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/mrzValidation":{"title":"mrzValidation","kind":"symbol","type":"topic","abstract":[{"text":"Specify MRZ validation. Default is ","type":"text"},{"text":".none","type":"text"},{"text":".","type":"text"}],"fragments":[{"kind":"identifier","text":"mrzValidation"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/mrzvalidation","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/mrzValidation"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","type":"topic","fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDMrzValidation","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title"},{"value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments"},{"value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle"}]}]}