{"metadata":{"title":"validationMode","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(py)validationMode","symbolKind":"property","fragments":[{"text":"validationMode","kind":"identifier"}],"navigatorTitle":[{"text":"validationMode","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/validationMode"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"abstract":[{"type":"text","text":"Specify validation mode. Default is "},{"type":"text","text":".standard"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"DOTDValidationMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"validationMode"},{"kind":"text","text":";"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/validationmode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/ValidationMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","abstract":[],"url":"\/documentation\/dotdocument\/validationmode","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"kind":"symbol","title":"ValidationMode","type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTDBaseDocumentAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/validationMode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/validationMode","abstract":[{"type":"text","text":"Specify validation mode. Default is "},{"type":"text","text":".standard"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/validationmode","role":"symbol","fragments":[{"text":"validationMode","kind":"identifier"}],"type":"topic","title":"validationMode"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDValidationMode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDValidationMode"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}