{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholder\/visible\/description"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/description"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"description","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"externalID":"s:14DotFaceCommons11PlaceholderC7VisibleC11descriptionSSvp","symbolKind":"property"},"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"abstract":[{"type":"text","text":"Visible placeholder."}],"title":"Placeholder.Visible","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotfacelite\/placeholder\/visible"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible/description":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible\/description","url":"\/documentation\/dotfacelite\/placeholder\/visible\/description","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"abstract":[{"type":"text","text":"Placeholder."}],"title":"Placeholder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"url":"\/documentation\/dotfacelite\/placeholder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title","value":"DOTPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle","value":[{"text":"DOTPlaceholder","kind":"identifier"}]}]}]}