{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/from(rectangle:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Method","modules":[{"name":"DotDocument"}],"symbolKind":"method","navigatorTitle":[{"text":"fromRectangle:","kind":"identifier"}],"role":"symbol","title":"from(rectangle:)","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(cm)fromRectangle:","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/corners\/from(rectangle:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/corners\/from(rectangle:)"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","title":"DotDocument","kind":"symbol","abstract":[{"text":"version: 8.14.1","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","url":"\/documentation\/dotdocument\/rectangledouble","kind":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","type":"topic"},"doc://DotDocument/documentation/DotDocument/Corners/from(rectangle:)":{"url":"\/documentation\/dotdocument\/corners\/from(rectangle:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/from(rectangle:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"title":"from(rectangle:)","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Corners":{"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Four detected corners in an image."}],"title":"Corners","url":"\/documentation\/dotdocument\/corners","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"fromRectangle:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","text":"DOTCorners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"kind":"text","text":" *) "},{"text":"fromRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"text":"rectangle","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1from(rectangle:)\/title","value":"fromRectangle:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1from(rectangle:)\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","op":"replace","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]}]}]}