{"metadata":{"roleHeading":"API Collection","role":"collectionGroup","modules":[{"name":"DotPalmCore"}],"title":"CustomStringConvertible Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/error\/customstringconvertible-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Error"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Error\/description"]}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Error\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/Error/description":{"title":"description","role":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/error\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Error\/description"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"type":"topic","abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/Error":{"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/error","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/Error","abstract":[],"title":"PalmAutoCaptureViewController.Configuration.Error","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","title":"PalmAutoCaptureViewController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]}]}]}