{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk\/initialize(configuration:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkConfiguration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotSdkConfiguration"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"inlineContent":[{"type":"text","text":"This method should be called on the background thread."}],"type":"paragraph"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdk\/initialize(configuration:)"]},{"paths":["\/documentation\/dotfacecore\/dotsdk\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DotSdk(im)initializeWithConfiguration:error:","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotSdkConfiguration","text":"DotSdkConfiguration"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"title":"initialize(configuration:)"},"kind":"symbol","sections":[],"abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdk":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk","title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdk/initialize(configuration:)":{"url":"\/documentation\/dotfacecore\/dotsdk\/initialize(configuration:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" with configuration."}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotSdkConfiguration","text":"DotSdkConfiguration","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdk\/initialize(configuration:)","title":"initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkConfiguration":{"navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkConfiguration"}],"url":"\/documentation\/dotfacecore\/dotsdkconfiguration","title":"DotSdkConfiguration"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithConfiguration:error:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithConfiguration:"},{"text":"(","kind":"text"},{"text":"DotSdkConfiguration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotSdkConfiguration","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk\/title"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk\/fragments"},{"value":"initializeWithConfiguration:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk~1initialize(configuration:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdk~1initialize(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration\/title","op":"replace","value":"DotSdkConfiguration"},{"op":"replace","value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}