{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum\/notSupported","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"No such protocol supported by the chip."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum\/notsupported"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"externalID":"s:6DotNfc24ChipAuthenticationStatusC0E0O12notSupportedyA2EmF","title":"ChipAuthenticationStatus.Status.notSupported","roleHeading":"Case","symbolKind":"case","modules":[{"name":"DotNfc"}]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"title":"ChipAuthenticationStatus.Status","type":"topic","abstract":[{"text":"Authentication status of the chip.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"navigatorTitle":[{"kind":"identifier","text":"Status"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"title":"ChipAuthenticationStatus","url":"\/documentation\/dotnfc\/chipauthenticationstatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum/notSupported":{"role":"symbol","abstract":[{"text":"No such protocol supported by the chip.","type":"text"}],"kind":"symbol","title":"ChipAuthenticationStatus.Status.notSupported","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum\/notsupported","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"notSupported","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum\/notSupported"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}