{"metadata":{"externalID":"s:14DotFingersCore0B21AutoCaptureControllerC6SampleC5image15timestampMillisAE0aC05ImageC_Sitcfc","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"init(image:timestampMillis:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"},{"text":", ","kind":"text"},{"text":"timestampMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample\/init(image:timestampMillis:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample\/init(image:timestampmillis:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample/init(image:timestampMillis:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample\/init(image:timestampMillis:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"timestampMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"init(image:timestampMillis:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample\/init(image:timestampmillis:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","title":"FingersAutoCaptureController.Sample","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","value":"DOTFGFingersAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]}]}]}