{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration\/init"]}],"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration(im)init","roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","symbolKind":"method","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration\/init","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","title":"init","url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration\/init","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","title":"DotPalmDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}