{"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(im)verifyIsActiveAndReturnError:","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"symbolKind":"method","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","title":"verifyIsActive()"},"abstract":[{"type":"text","text":"Verify that library is initialized."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"verifyIsActive","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/verifyisactive()"]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary":{"role":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" library initialization."}],"kind":"symbol","title":"DotDocumentLibrary","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotDocumentLibrary","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/verifyIsActive()":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/verifyisactive()","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/verifyIsActive()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}],"type":"topic","title":"verifyIsActive()","abstract":[{"type":"text","text":"Verify that library is initialized."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"verifyIsActiveAndReturnError:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary","op":"replace"},{"value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/fragments"},{"value":"verifyIsActiveAndReturnError:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1verifyIsActive()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1verifyIsActive()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]}]}]}