{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidappear(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewDidAppear(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidAppear","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","role":"symbol","extendedModule":"DotPalmCore","modules":[{"name":"DotPalmCore"}],"externalID":"c:@CM@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)viewDidAppear:","navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"title":"viewDidAppear(_:)","symbolKind":"method"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"title":"PalmAutoCaptureViewController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"text":"version: 8.6.1","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/viewDidAppear(_:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewDidAppear(_:)","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewdidappear(_:)","type":"topic","navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"title":"viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"viewDidAppear:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]},{"value":"viewDidAppear:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewDidAppear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewDidAppear:","kind":"identifier"}]}]}]}