{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/telephone","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/telephone"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/telephone"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Telephone","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"telephone"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"telephone","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)telephone","title":"telephone","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"telephone","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"references":{"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/telephone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/telephone","kind":"symbol","title":"telephone","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"telephone","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"type":"topic","navigatorTitle":[{"text":"telephone","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/telephone","abstract":[{"text":"Telephone","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"url":"\/documentation\/dotnfc\/additionalpersonaldetails","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"title":"AdditionalPersonalDetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AdditionalPersonalDetails"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"telephone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"telephone","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"telephone"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1telephone\/title","op":"replace","value":"telephone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1telephone\/fragments","value":[{"text":"telephone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","value":"DOTNAdditionalPersonalDetails"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/navigatorTitle","op":"replace","value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}