{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/valuerange\/status\/toolow"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooLow"},"metadata":{"symbolKind":"case","externalID":"s:11DotFaceCore10ValueRangeC6StatusO6tooLowyA2EmF","title":"ValueRange.Status.tooLow","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tooLow","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Case","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooLow"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status/tooLow":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status\/tooLow","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tooLow"}],"title":"ValueRange.Status.tooLow","url":"\/documentation\/dotfacecore\/valuerange\/status\/toolow","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"url":"\/documentation\/dotfacecore\/valuerange\/status","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Status","kind":"identifier"}],"role":"symbol","title":"ValueRange.Status","abstract":[{"type":"text","text":"Status of a value with respect to a range."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"type":"topic","title":"ValueRange","kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange","abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"ValueRange","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValueRange","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFValueRange","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title"},{"value":[{"kind":"identifier","text":"DOTFValueRange"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments"},{"value":[{"kind":"identifier","text":"DOTFValueRange"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle"}]}]}