{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Libraries configuration."}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration\/libraries","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","metadata":{"externalID":"s:7DotCore0A3SdkC13ConfigurationC9librariesAA9LibrariesCvp","title":"libraries","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdk\/configuration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotdocument\/libraries","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","abstract":[{"type":"text","text":"Container for library configurations."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotSdk/Configuration/libraries":{"type":"topic","abstract":[{"type":"text","text":"Libraries configuration."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration\/libraries","title":"libraries","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Libraries","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"}],"url":"\/documentation\/dotdocument\/dotsdk\/configuration\/libraries","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdk":{"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdk","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk","role":"symbol","kind":"symbol","title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotSdk/Configuration":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotsdk\/configuration","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdk\/Configuration","role":"symbol","kind":"symbol","title":"DotSdk.Configuration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"}},"variantOverrides":[{"patch":[{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments"},{"value":[{"text":"Libraries","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle"},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/title"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/fragments"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdk\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}