{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzDate","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"date","kind":"identifier"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(py)date","title":"date","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"date"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","kind":"typeIdentifier","text":"MrzDate"}],"role":"symbol"},"abstract":[{"text":"Parsed date.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/date"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/date"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/date"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/MrzDate":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"url":"\/documentation\/dotnfc\/mrzdate","title":"MrzDate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit/date":{"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"date","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"date","kind":"identifier"}],"abstract":[{"text":"Parsed date.","type":"text"}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/date","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/date","title":"date"},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","title":"MrzDateElementWithCheckDigit","type":"topic","abstract":[{"text":"A ","type":"text"},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"text":" with parsed ","type":"text"},{"code":"Date","type":"codeVoice"},{"text":" value.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"date"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"date","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTMrzDate","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate"},{"text":" * ","kind":"text"},{"text":"date","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title","op":"replace","value":"DOTMrzDate"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"op":"replace","value":[{"text":"DOTMrzDate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1date\/title","op":"replace","value":"date"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1date\/fragments","op":"replace","value":[{"text":"date","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]}]}]}