{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}]}],"kind":"declarations"},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once specified count of consecutive valid frames have been acquired,"},{"type":"text","text":" "},{"type":"text","text":"the candidate selection process is triggered and continues for specified time in milliseconds."},{"type":"text","text":" "},{"type":"text","text":"During this period, the system analyzes the pool of valid images to determine the most suitable result image."}]}],"kind":"content"}],"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"metadata":{"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeAutoCapture","role":"symbol","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"title":"CaptureMode.autoCapture","modules":[{"name":"DotFaceLite"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/autoCapture"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/capturemode\/autocapture"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/capturemode\/autocapture"]}],"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"type":"topic","abstract":[{"text":"Capture mode.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/capturemode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/autoCapture":{"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/capturemode\/autocapture","title":"CaptureMode.autoCapture","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/autoCapture","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTCaptureModeAutoCapture","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCaptureMode","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1autoCapture\/title","op":"replace","value":"DOTCaptureModeAutoCapture"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1autoCapture\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}