{"kind":"symbol","metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(py)configuration","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC","text":"Configuration"}],"role":"symbol","title":"configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Current configuration."}],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/configuration-swift.property","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/configuration-swift.property":{"title":"configuration","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/configuration-swift.property","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.property","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"role":"symbol","title":"MagnifEyeLivenessViewController","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","kind":"symbol","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","role":"symbol","fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}],"title":"DOTFLMagnifEyeLivenessConfiguration","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the MagnifEye liveness process."}],"kind":"symbol","title":"MagnifEyeLivenessViewController.Configuration","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"configuration","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","text":"DOTFLMagnifEyeLivenessConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"value":[{"kind":"identifier","text":"configuration"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1configuration-swift.property\/fragments"},{"value":"DOTFLMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","op":"replace"},{"value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}