{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC","text":"Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"typeIdentifier"},{"kind":"text","text":" = .init(), "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","text":"Style","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","kind":"typeIdentifier"},{"text":" = .init())","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the MagnifEye liveness process."}]}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}],"name":"style"}]}],"sections":[],"abstract":[{"type":"text","text":"Create new "},{"code":"MagnifEyeLivenessViewController","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/init(configuration:style:)","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/init(configuration:style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/init(configuration:style:)"]}],"metadata":{"platforms":[{"unavailable":false,"beta":false,"deprecated":true,"message":"Use MultiRangeLivenessViewController instead."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC"},{"kind":"text","text":")"}],"role":"symbol","title":"init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"symbolKind":"init","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(im)initWithConfiguration:style:"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Configuration-swift.class","abstract":[{"text":"Configuration options for the UI MagnifEye Liveness component.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"title":"MagnifEyeLivenessViewController.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"deprecated":true,"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/configuration-swift.class","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}],"kind":"symbol","title":"DOTFLMagnifEyeLivenessConfiguration","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","abstract":[{"text":"UI MagnifEye Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"kind":"symbol","title":"MagnifEyeLivenessViewController","role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"type":"topic","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/init(configuration:style:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Create new "},{"code":"MagnifEyeLivenessViewController","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/init(configuration:style:)","title":"init(configuration:style:)","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/init(configuration:style:)","deprecated":true,"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the MagnifEye liveness user interface.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"kind":"symbol","title":"MagnifEyeLivenessViewController.Style","role":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"type":"topic","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessStyle":{"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessstyle","abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessStyle","fragments":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"}],"kind":"symbol","title":"DOTFLMagnifEyeLivenessStyle","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[{"deprecated":true,"beta":false,"unavailable":false}],"op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration","kind":"typeIdentifier","text":"DOTFLMagnifEyeLivenessConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"style:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle","kind":"typeIdentifier","text":"DOTFLMagnifEyeLivenessStyle","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessStyle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"style"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the MagnifEye liveness process."}]}]},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/deprecationSummary","value":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}