{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle","text":"MagnifEyeLivenessStyle"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current style."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MagnifEyeLivenessStyle","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle"}],"title":"style","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(py)style","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"style"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessStyle":{"role":"symbol","title":"MagnifEyeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessstyle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.0.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/style":{"role":"symbol","title":"style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MagnifEyeLivenessStyle","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Current style."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"style"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessStyle","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle","text":"DOTFLMagnifEyeLivenessStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"style"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle\/title","value":"DOTFLMagnifEyeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style\/title","value":"style"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style\/fragments","value":[{"kind":"identifier","text":"style"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}