{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style-swift.property","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"title":"style","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(py)style","roleHeading":"Instance Property","navigatorTitle":[{"text":"style","kind":"identifier"}],"role":"symbol"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","text":"Style","kind":"typeIdentifier"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.property"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"abstract":[{"text":"Current style.","type":"text"}],"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","abstract":[{"text":"UI component for capturing images suitable for MagnifEye liveness evaluation.","type":"text"}],"role":"symbol","title":"MagnifEyeLivenessViewController","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/Style-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/Style-swift.class","abstract":[{"text":"Customization options for the MagnifEye liveness user interface.","type":"text"}],"title":"MagnifEyeLivenessViewController.Style","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.class","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/MagnifEyeLivenessViewController/style-swift.property":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite31MagnifEyeLivenessViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/style-swift.property","title":"style","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/style-swift.property","role":"symbol","navigatorTitle":[{"text":"style","kind":"identifier"}],"abstract":[{"text":"Current style.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"text":"version: 8.2.1","type":"text"}],"role":"collection","title":"DotFaceLite","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessStyle":{"title":"DOTFLMagnifEyeLivenessStyle","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessstyle","kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessStyle","fragments":[{"text":"DOTFLMagnifEyeLivenessStyle","kind":"identifier"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"style","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"style","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTFLMagnifEyeLivenessStyle","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessStyle","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessStyle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"style"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewController"}],"op":"replace"},{"op":"replace","value":"style","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style-swift.property\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1style-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"style"}]}]}]}