{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidlayoutsubviews()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidlayoutsubviews()"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":"()","kind":"text"}]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"viewDidLayoutSubviews()","role":"symbol","modules":[{"name":"DotFaceLite"}],"extendedModule":"DotFaceLite","platforms":[{"message":"Use MultiRangeLivenessViewController instead.","unavailable":false,"beta":false,"deprecated":true}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"externalID":"c:@CM@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController(im)viewDidLayoutSubviews","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","interfaceLanguage":"swift"},"kind":"symbol","deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"title":"MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController/viewDidLayoutSubviews()":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController\/viewDidLayoutSubviews()","type":"topic","title":"viewDidLayoutSubviews()","deprecated":true,"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"abstract":[],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller\/viewdidlayoutsubviews()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"unavailable":false,"beta":false,"deprecated":true}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title","value":"DOTFLMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController~1viewDidLayoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}]}]}]}