{"metadata":{"navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTBezierPathFactory(cm)createPlaceholderPathWithRect:cornerRadius:","title":"createPlaceholderPath(rect:cornerRadius:)","modules":[{"name":"DotNfc"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPlaceholderPath"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rect","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}]}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory":{"role":"symbol","title":"BezierPathFactory","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bezierpathfactory","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","url":"\/documentation\/dotnfc\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"title":"createPlaceholderPath(rect:cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createPlaceholderPathWithRect:cornerRadius:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"createPlaceholderPathWithRect:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTBezierPathFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}]},{"value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]}]}]}