{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotNfc"}],"title":"createDetectionPath(corners:cornerRadius:)","roleHeading":"Type Method","navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Corners","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:cornerRadius:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"role":"symbol","title":"createDetectionPath(corners:cornerRadius:)","navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners","text":"Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"kind":"symbol","url":"\/documentation\/dotnfc\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners":{"role":"symbol","kind":"symbol","title":"Corners","abstract":[{"type":"text","text":"Four detected corners in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/corners"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BezierPathFactory":{"role":"symbol","title":"BezierPathFactory","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bezierpathfactory","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BezierPathFactory","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"value":"createDetectionPathWithCorners:cornerRadius:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"text":"createDetectionPathWithCorners:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTCorners","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"corners"},{"text":" ","kind":"text"},{"text":"cornerRadius:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/title"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/title","value":"DOTBezierPathFactory"},{"value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BezierPathFactory\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}