{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/result","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","text":"DOTFFaceAutoCaptureResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"result"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning"]]},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"result","fragments":[{"kind":"identifier","text":"result"}],"navigatorTitle":[{"text":"result","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiStateRunning(py)result","symbolKind":"property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/result"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","fragments":[{"text":"DOTFFaceAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFFaceAutoCaptureUiStateRunning","type":"topic","abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureResult"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotFaceCore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/result":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/result","fragments":[{"kind":"identifier","text":"result"}],"abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/result","title":"result"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title","value":"DOTFFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}