{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/rectangleint\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/rectangleint\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Method","title":"isEqual(_:)","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt(im)isEqual:","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/isEqual(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/isEqual(_:)":{"type":"topic","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/isEqual(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/isequal(_:)","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotfingerscore\/rectangleint","kind":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1isEqual(_:)\/fragments"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/title"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}