{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/rectangleint\/width"]},{"paths":["\/documentation\/dotfingerscore\/rectangleint\/width"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"width","navigatorTitle":[{"text":"width","kind":"identifier"}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)width","symbolKind":"property","extendedModule":"DotCore","modules":[{"name":"DotFingersCore","relatedModules":["DotCore"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Instance Property","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/width","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/width":{"type":"topic","title":"width","navigatorTitle":[{"kind":"identifier","text":"width"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/width","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/width","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotfingerscore\/rectangleint","kind":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"width","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1width\/title"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1width\/fragments"},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}