{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/initWithBgraRawImage:timestampMillis:deviceTiltAngles:","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTBgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"timestampMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"timestampMillis"},{"kind":"text","text":" "},{"text":"deviceTiltAngles:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTTiltAngles","kind":"typeIdentifier","text":"DOTTiltAngles","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"deviceTiltAngles"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerSample(im)initWithBgraRawImage:timestampMillis:deviceTiltAngles:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","title":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:","fragments":[{"kind":"text","text":"- "},{"text":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/initwithbgrarawimage:timestampmillis:devicetiltangles:"]}],"sections":[],"references":{"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/TiltAngles":{"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"title":"TiltAngles","url":"\/documentation\/dotfacelite\/tiltangles","abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"text":".","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/TiltAngles","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample/initWithBgraRawImage:timestampMillis:deviceTiltAngles:":{"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/initwithbgrarawimage:timestampmillis:devicetiltangles:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/initWithBgraRawImage:timestampMillis:deviceTiltAngles:","title":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:","fragments":[{"kind":"text","text":"- "},{"text":"initWithBgraRawImage:timestampMillis:deviceTiltAngles:","kind":"identifier"}],"abstract":[],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample":{"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample","kind":"symbol","title":"DOTFLFaceAutoCaptureControllerSample","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","fragments":[{"text":"DOTFLFaceAutoCaptureControllerSample","kind":"identifier"}],"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the face auto capture process."}],"role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/title","value":"DOTTiltAngles"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}