{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBezierPathFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DotPalmCore@objc(cs)DOTBezierPathFactory","symbolKind":"class","modules":[{"name":"DotPalmCore"}],"title":"BezierPathFactory","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BezierPathFactory","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"],"title":"Type Methods"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"],"kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bezierpathfactory"]},{"paths":["\/documentation\/dotpalmcore\/bezierpathfactory"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.palm.core/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH"},"doc://com.innovatrics.dot.palm.core/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","title":"createDetectionPath(corners:cornerRadius:)","type":"topic"},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"url":"\/documentation\/dotpalmcore\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPlaceholderPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","type":"topic","abstract":[],"title":"createPlaceholderPath(rect:cornerRadius:)","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"kind":"symbol"},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory":{"url":"\/documentation\/dotpalmcore\/bezierpathfactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory","type":"topic","abstract":[],"title":"BezierPathFactory","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTBezierPathFactory"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBezierPathFactory"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"op":"replace","value":"createPlaceholderPathWithRect:cornerRadius:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/title","value":"DOTBezierPathFactory"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]}]}]}