{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotlibrary"]}],"relationshipsSections":[{"title":"Conforming Types","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary"],"kind":"relationships","type":"conformingTypes"}],"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"title":"DotLibrary","role":"symbol","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"externalID":"c:@M@DotPalmCore@objc(pl)DotLibrary","symbolKind":"protocol","modules":[{"name":"DotPalmCore"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/id"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/initialize(license:)"]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary","title":"DotPalmLibrary","type":"topic","url":"\/documentation\/dotpalmcore\/dotpalmlibrary","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmLibrary","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library initialization."}],"role":"symbol","navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary/deinitialize()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary\/deinitialize()","role":"symbol","abstract":[],"required":true,"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/deinitialize()","title":"deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary/initialize(license:)":{"title":"initialize(license:)","required":true,"role":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary\/initialize(license:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/initialize(license:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary":{"title":"DotLibrary","role":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary/id":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotlibrary\/id","role":"symbol","abstract":[],"required":true,"title":"id","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/id","type":"topic","navigatorTitle":[{"kind":"identifier","text":"id"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"op":"replace","value":"DotLibrary","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotLibrary","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/id"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary\/initialize(license:)"]}]},{"op":"replace","value":[{"title":"Conforming Types","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary"],"kind":"relationships","type":"conformingTypes"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DotPalmLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary\/title"},{"value":[{"text":"DotPalmLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1deinitialize()\/fragments","op":"replace"},{"value":"initializeWithLicense:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1initialize(license:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1initialize(license:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/fragments","op":"replace"},{"value":"id","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1id\/title","op":"replace"},{"value":[{"kind":"identifier","text":"id"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary~1id\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}