{"metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotPalmCore@objc(cs)DotSdkLicenseProxy","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"title":"DotSdkLicenseProxy"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"],"type":"conformsTo"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxy"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isPalmEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/licenseBytes"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isDocumentEnabled":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isDocumentEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isdocumentenabled","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"title":"isDocumentEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceLiteEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceliteenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"title":"isFaceLiteEnabled"},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"title":"isFaceEyeGazeLivenessScoreEnabled"},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isNfcEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isNfcEnabled","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isnfcenabled","title":"isNfcEnabled","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.palm.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isPalmEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isPalmEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/ispalmenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPalmEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"title":"isPalmEnabled"},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfaceenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"title":"isFaceEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"title":"isRealTimeTransactionReportingEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/licenseBytes":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/licenseBytes","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/licensebytes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"title":"licenseBytes"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isEvaluation":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isEvaluation","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isevaluation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"title":"isEvaluation"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacepassivelivenessenabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"title":"isFacePassiveLivenessEnabled"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotSdkLicenseProxy/isFaceMatchingEnabled":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxy\/isfacematchingenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"title":"isFaceMatchingEnabled"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DotSdkLicenseProxy"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isPalmEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxy\/licenseBytes"],"title":"Instance Properties"}]},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"value":"isDocumentEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isDocumentEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isDocumentEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isDocumentEnabled"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title","value":"isFaceLiteEnabled"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","op":"replace"},{"op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isNfcEnabled\/title","op":"replace","value":"isNfcEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isPalmEnabled\/title","value":"isPalmEnabled"},{"op":"replace","value":[{"text":"isPalmEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isPalmEnabled\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEnabled\/title","op":"replace","value":"isFaceEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceEnabled\/fragments","value":[{"text":"isFaceEnabled","kind":"identifier"}]},{"value":"isRealTimeTransactionReportingEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace","value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1licenseBytes\/title","op":"replace","value":"licenseBytes"},{"value":[{"text":"licenseBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1licenseBytes\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"op":"replace","value":"isEvaluation","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isEvaluation\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isEvaluation\/fragments","value":[{"text":"isEvaluation","kind":"identifier"}],"op":"replace"},{"value":"isFacePassiveLivenessEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments","op":"replace","value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title","value":"isFaceMatchingEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"op":"replace"}]}]}