{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/init(pitch:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/description","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/pitch"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTTiltAngles) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/tiltangles"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/tiltangles"]}],"metadata":{"title":"TiltAngles","roleHeading":"Class","externalID":"c:@M@DotPalmCore@objc(cs)DOTTiltAngles","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"]}],"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Tilt angles.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/TiltAngles/init(pitch:)":{"title":"init(pitch:)","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/init(pitch:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/tiltangles\/init(pitch:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"pitch"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"initWithPitch:","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","title":"Sensor Coordinate System","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/TiltAngles/pitch":{"title":"pitch","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/pitch","kind":"symbol","url":"\/documentation\/dotpalmcore\/tiltangles\/pitch","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitch","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"pitch","kind":"identifier"}],"abstract":[{"text":"Represents value of angle between Z-axis and plane parallel to the ground in degrees.","type":"text"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/TiltAngles/description":{"title":"description","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/description","kind":"symbol","url":"\/documentation\/dotpalmcore\/tiltangles\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/TiltAngles":{"title":"TiltAngles","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles","kind":"symbol","url":"\/documentation\/dotpalmcore\/tiltangles","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TiltAngles"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"text":"Also see ","type":"text"},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTTiltAngles","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/description","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/pitch"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/TiltAngles\/init(pitch:)"]}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTTiltAngles","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1init(pitch:)\/title","value":"initWithPitch:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1init(pitch:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1pitch\/title","value":"pitch"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1pitch\/fragments","value":[{"kind":"identifier","text":"pitch"}]},{"value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1description\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}