{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/shorterSide","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shorterSide","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"]]},"metadata":{"roleHeading":"Instance Property","externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(py)shorterSide","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"extendedModule":"DotCore","role":"symbol","title":"shorterSide","modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imagesize\/shorterside"]},{"paths":["\/documentation\/dotpalmcore\/imagesize\/shorterside"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/shorterSide":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/shorterSide","url":"\/documentation\/dotpalmcore\/imagesize\/shorterside","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"kind":"symbol","title":"shorterSide","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"title":"ImageSize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","abstract":[{"type":"text","text":"Image size in pixels."}],"url":"\/documentation\/dotpalmcore\/imagesize","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"shorterSide","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"shorterSide","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"shorterSide","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1shorterSide\/title"},{"value":[{"text":"shorterSide","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1shorterSide\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title","value":"DOTImageSize","op":"replace"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments"}]}]}