{"abstract":[{"type":"text","text":"Captured face image."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/image"},"metadata":{"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessResult(py)image","title":"image","role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"image"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Image":{"type":"topic","abstract":[],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/image","title":"Image","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessResult":{"kind":"symbol","title":"MagnifEyeLivenessResult","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"navigatorTitle":[{"text":"MagnifEyeLivenessResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessResult/image":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Captured face image."}],"title":"image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/image","url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/image","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"deprecated":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"title":"MagnifEyeLivenessViewController","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"image","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"image","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"value":"DOTFMagnifEyeLivenessResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/title"},{"value":[{"text":"DOTFMagnifEyeLivenessResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/fragments"},{"value":[{"text":"DOTFMagnifEyeLivenessResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/navigatorTitle"},{"value":"image","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1image\/title"},{"value":[{"text":"image","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1image\/fragments"},{"value":"DOTFMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle"}]}]}