{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DetectedFace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult\/detectedface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessresult\/detectedface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/detectedFace","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detected face."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"}],"title":"detectedFace","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessResult(py)detectedFace","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"detectedFace"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult":{"role":"symbol","title":"MagnifEyeLivenessResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"abstract":[{"type":"text","text":"The final result of the MagnifEye liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessResult"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessresult"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessResult/detectedFace":{"role":"symbol","title":"detectedFace","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectedFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace"}],"abstract":[{"type":"text","text":"Detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessResult\/detectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectedFace"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessresult\/detectedface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DetectedFace":{"role":"symbol","title":"DetectedFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectedFace"}],"abstract":[{"type":"text","text":"Result of face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DetectedFace"}],"url":"\/documentation\/dotfacecore\/detectedface"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"detectedFace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"detectedFace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DetectedFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFDetectedFace","text":"DOTFDetectedFace"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectedFace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/title","value":"DOTFMagnifEyeLivenessResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1detectedFace\/title","value":"detectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessResult~1detectedFace\/fragments","value":[{"kind":"identifier","text":"detectedFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/title","value":"DOTFDetectedFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DetectedFace\/fragments","value":[{"kind":"identifier","text":"DOTFDetectedFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}