{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration(im)initWithModules:faceDetectionConfidenceThreshold:error:","symbolKind":"init","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"title":"init(modules:faceDetectionConfidenceThreshold:)"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" = 0.06) ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DotFaceLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","abstract":[{"text":"Face library configuration.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"navigatorTitle":[{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","role":"symbol","title":"init(modules:faceDetectionConfidenceThreshold:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"kind":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules","type":"topic","role":"symbol","title":"DotFaceLibraryConfigurationModules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration/Modules-swift.class":{"title":"DotFaceLibraryConfiguration.Modules","type":"topic","url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"abstract":[{"type":"text","text":"Face library module configuration."}],"kind":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration\/Modules-swift.class","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","text":"DotFaceLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"initWithModules:faceDetectionConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments"}]}]}