{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFaceAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTFaceAutoCapturePreview"},{"text":" *) ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFaceAutoCapturePhaseWrapped","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTFaceAutoCapturePhaseWrapped"},{"text":" *) ","kind":"text"},{"text":"phase","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceAutoCaptureResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/initwithpreview:phase:detection:result:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning"]]},"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureUiStateRunning(im)initWithPreview:phase:detection:result:","title":"initWithPreview:phase:detection:result:","role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureDetection","role":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacecore\/faceautocapturedetection"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning":{"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning","type":"topic","role":"symbol","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"DOTFFaceAutoCaptureUiStateRunning"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning","title":"DOTFFaceAutoCaptureUiStateRunning"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureresult","type":"topic","title":"FaceAutoCaptureResult"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}],"type":"topic","title":"initWithPreview:phase:detection:result:","abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocaptureuistaterunning\/initwithpreview:phase:detection:result:","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithPreview:phase:detection:result:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle"},{"op":"replace","value":"DOTFFaceAutoCaptureResult","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/navigatorTitle"}]}]}