{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/intervaldouble\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"DotCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO","title":"composeWithInternalError()","role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","title":"IntervalDouble.Error","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"title":"IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/composeWithInternalError()":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/composeWithInternalError()","title":"composeWithInternalError()","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error\/composewithinternalerror()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle"}]}]}