{"metadata":{"extendedModule":"Foundation","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"failureReason","platforms":[{"name":"iOS","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false},{"name":"macOS","deprecated":false,"introducedAt":"10.10","beta":false,"unavailable":false},{"name":"tvOS","deprecated":false,"introducedAt":"9.0","beta":false,"unavailable":false},{"name":"watchOS","deprecated":false,"introducedAt":"2.0","beta":false,"unavailable":false}],"modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/error\/failurereason"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/failureReason","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","title":"IntervalDouble.Error","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/LocalizedError-Implementations":{"url":"\/documentation\/dotdocument\/intervaldouble\/error\/localizederror-implementations","role":"collectionGroup","kind":"article","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/failureReason":{"title":"failureReason","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/failureReason","url":"\/documentation\/dotdocument\/intervaldouble\/error\/failurereason","type":"topic","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle"}]}]}