{"metadata":{"modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"roleHeading":"Instance Property","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"Mac Catalyst","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"macOS","introducedAt":"10.10","deprecated":false,"unavailable":false,"beta":false},{"name":"tvOS","introducedAt":"9.0","deprecated":false,"unavailable":false,"beta":false},{"name":"watchOS","introducedAt":"2.0","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"property","extendedModule":"Foundation","role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/intervaldouble\/error\/helpanchor"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.helpAnchor"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/helpAnchor"},"references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","url":"\/documentation\/dotdocument\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error","title":"IntervalDouble.Error","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/helpAnchor":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error\/helpanchor","title":"helpAnchor","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/helpAnchor"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","abstract":[],"role":"collectionGroup","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/LocalizedError-Implementations","url":"\/documentation\/dotdocument\/intervaldouble\/error\/localizederror-implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}