{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/error\/localizeddescription"]}],"metadata":{"title":"localizedDescription","symbolKind":"property","roleHeading":"Instance Property","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst","introducedAt":"8.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"macOS","introducedAt":"10.10"},{"unavailable":false,"deprecated":false,"beta":false,"name":"tvOS","introducedAt":"9.0"},{"unavailable":false,"deprecated":false,"beta":false,"name":"watchOS","introducedAt":"2.0"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO","role":"symbol","extendedModule":"Swift","modules":[{"name":"DotDocument","relatedModules":["Swift"]}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/localizedDescription"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Error-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"Error.localizedDescription"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/localizedDescription":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/localizedDescription","kind":"symbol","abstract":[],"title":"localizedDescription","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/error\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error","url":"\/documentation\/dotdocument\/intervaldouble\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol","abstract":[],"title":"IntervalDouble.Error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotdocument\/intervaldouble","role":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","title":"IntervalDouble"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/Error/Error-Implementations":{"kind":"article","role":"collectionGroup","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/Error\/Error-Implementations","url":"\/documentation\/dotdocument\/intervaldouble\/error\/error-implementations","abstract":[],"title":"Error Implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}