{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/common","interfaceLanguage":"swift"},"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"common","role":"symbol","externalID":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC6common0aC006CommonI0Cvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/common"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"role":"symbol","title":"BasePalmAutoCaptureViewController","abstract":[{"text":"UI component for capturing palm images with customizable UI.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","url":"\/documentation\/dotpalmcore\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","title":"BasePalmAutoCaptureViewController.Configuration","role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/common":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/common","title":"common","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/common","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPBasePalmAutoCaptureViewController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","op":"replace"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","op":"replace"}]}]}