{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"},"metadata":{"roleHeading":"Initializer","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAeA0ac13BarcodeModuleE0CSg_tcfc","modules":[{"name":"DotNfc"}],"role":"symbol","title":"init(barcode:)","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class":{"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Document library module configuration."}],"title":"DotDocumentLibraryConfiguration.Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"kind":"symbol","type":"topic","title":"init(barcode:)","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Document library configuration."}],"role":"symbol","title":"DotDocumentLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"type":"topic","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"title":"DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}]}]}