{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"preview"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle\/preview"]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateIdle(py)preview","title":"preview","role":"symbol","navigatorTitle":[{"text":"preview","kind":"identifier"}],"fragments":[{"text":"preview","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"Preview information.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle\/preview","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"title":"FingersAutoCapturePreview","navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","kind":"symbol","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateIdle":{"kind":"symbol","title":"DOTFGFingersAutoCaptureUiStateIdle","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateIdle","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateIdle/preview":{"role":"symbol","title":"preview","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle\/preview","abstract":[{"text":"Preview information.","type":"text"}],"fragments":[{"text":"preview","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle\/preview","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCapturePreview","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle"}]}]}