{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration\/init"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration(im)init","modules":[{"name":"DotPalmCore"}],"title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersDetectionModuleConfiguration/init":{"title":"init","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration\/init","url":"\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration\/init","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersDetectionModuleConfiguration":{"title":"DotFingersDetectionModuleConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration","type":"topic","abstract":[{"text":"Fingers detection module configuration.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/title","op":"replace","value":"DotFingersDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}