{"metadata":{"externalID":"c:@CM@DotFaceCore@objc(cs)DOTFMultiRangeLivenessViewController(im)viewWillDisappear:","role":"symbol","title":"viewWillDisappear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"extendedModule":"DotFaceCore","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/viewWillDisappear(_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/viewwilldisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/viewWillDisappear(_:)":{"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/viewwilldisappear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/viewWillDisappear(_:)","title":"viewWillDisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"role":"symbol","title":"MultiRangeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessViewController"}],"type":"topic","abstract":[{"text":"UI component for capturing images suitable for Multi-Range Liveness evaluation.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"viewWillDisappear:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1viewWillDisappear(_:)\/title","op":"replace","value":"viewWillDisappear:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController~1viewWillDisappear(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","op":"replace","value":"DOTFMultiRangeLivenessViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","op":"replace","value":[{"text":"DOTFMultiRangeLivenessViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}