{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/description"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/description","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocolWrapper"]]},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":[{"deprecated":false,"introducedAt":"13.0","beta":false,"name":"iOS","unavailable":false}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper(py)description","title":"description"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocolWrapper":{"title":"AccessControlProtocolWrapper","abstract":[{"text":"Access Control protocol wrapper.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocolWrapper"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"kind":"symbol","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.5.0"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AccessControlProtocolWrapper/description":{"abstract":[],"title":"description","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/description","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/description"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","op":"replace","value":"DOTNAccessControlProtocolWrapper"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments","value":[{"kind":"identifier","text":"DOTNAccessControlProtocolWrapper"}],"op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}