{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/init(accessControlProtocol:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNAccessControlProtocolWrapper(im)initWithAccessControlProtocol:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"accessControlProtocol","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","text":"AccessControlProtocol","kind":"typeIdentifier"},{"kind":"text","text":")"}],"modules":[{"name":"DotNfc"}],"title":"init(accessControlProtocol:)","platforms":[{"introducedAt":"13.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false}],"navigatorTitle":[{"text":"initWithAccessControlProtocol:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","symbolKind":"init"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/init(accesscontrolprotocol:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/init(accesscontrolprotocol:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"accessControlProtocol","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","text":"AccessControlProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper"]]},"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper/init(accessControlProtocol:)":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"accessControlProtocol"},{"kind":"text","text":": "},{"text":"AccessControlProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol"},{"text":")","kind":"text"}],"type":"topic","title":"init(accessControlProtocol:)","navigatorTitle":[{"text":"initWithAccessControlProtocol:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper\/init(accesscontrolprotocol:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper\/init(accessControlProtocol:)","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Access Control protocol."}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"AccessControlProtocol","kind":"identifier"}],"url":"\/documentation\/dotnfc\/accesscontrolprotocol","navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"title":"AccessControlProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocolWrapper":{"navigatorTitle":[{"text":"AccessControlProtocolWrapper","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Access Control protocol wrapper.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocolWrapper"}],"title":"AccessControlProtocolWrapper","url":"\/documentation\/dotnfc\/accesscontrolprotocolwrapper","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocolWrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithAccessControlProtocol:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAccessControlProtocol:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithAccessControlProtocol:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNAccessControlProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTNAccessControlProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"accessControlProtocol"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"initWithAccessControlProtocol:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1init(accessControlProtocol:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper~1init(accessControlProtocol:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAccessControlProtocol:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace","value":"DOTNAccessControlProtocol"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","op":"replace","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/title","value":"DOTNAccessControlProtocolWrapper","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocolWrapper\/fragments","value":[{"kind":"identifier","text":"DOTNAccessControlProtocolWrapper"}],"op":"replace"}]}]}