{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithAuthorityCertificatesUrl:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"authorityCertificatesUrl"},{"kind":"text","text":" "},{"kind":"identifier","text":"_debugInfoEnabled:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"_debugInfoEnabled"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderconfiguration\/initwithauthoritycertificatesurl:_debuginfoenabled:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration\/initWithAuthorityCertificatesUrl:_debugInfoEnabled:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:"}],"title":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration(im)initWithAuthorityCertificatesUrl:_debugInfoEnabled:","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderConfiguration/initWithAuthorityCertificatesUrl:_debugInfoEnabled:":{"role":"symbol","title":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration\/initWithAuthorityCertificatesUrl:_debugInfoEnabled:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAuthorityCertificatesUrl:_debugInfoEnabled:"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderconfiguration\/initwithauthoritycertificatesurl:_debuginfoenabled:"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderConfiguration":{"role":"symbol","title":"NfcTravelDocumentReaderConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderConfiguration"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderconfiguration"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.0.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderConfiguration\/title","value":"DOTNNfcTravelDocumentReaderConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}