{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(image:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}]}],"name":"image"}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/cgimagefactory\/create(image:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/cgimagefactory\/create(image:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithImage:","modules":[{"name":"DotPalmCore"}],"roleHeading":"Type Method","title":"create(image:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"symbolKind":"method","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}]},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"role":"symbol","title":"Image","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","type":"topic","url":"\/documentation\/dotpalmcore\/image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory/create(image:)":{"url":"\/documentation\/dotpalmcore\/cgimagefactory\/create(image:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(image:)","kind":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"navigatorTitle":[{"kind":"identifier","text":"createWithImage:"}],"role":"symbol","title":"create(image:)","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"title":"CGImageFactory","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/cgimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"type":"text","text":"Input image as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"type":"paragraph"}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" instance."}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(image:)\/title","value":"createWithImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(image:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/navigatorTitle","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}