{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"title":"init(modules:)","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)initWithModules:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Modules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"kind":"text","text":" = .init())"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/init(modules:)"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotDocumentLibraryConfiguration.Modules","type":"topic","abstract":[{"text":"Document library module configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/init(modules:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"title":"init(modules:)","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/init(modules:)","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/init(modules:)","role":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules","abstract":[{"text":"Document library module configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotdocumentlibraryconfigurationmodules","role":"symbol","kind":"symbol","title":"DotDocumentLibraryConfigurationModules","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"title":"DotDocumentLibraryConfiguration","type":"topic","abstract":[{"text":"Document library configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.1"}],"url":"\/documentation\/dotdocument","role":"collection","type":"topic","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithModules:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules","text":"DotDocumentLibraryConfigurationModules","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"value":"initWithModules:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration~1init(modules:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithModules:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]}]}]}