{"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode"],"generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotDocumentLibraryConfigurationModules) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","role":"symbol","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Class","symbolKind":"class","title":"DotDocumentLibraryConfiguration.Modules","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration"]]},"abstract":[{"text":"Document library module configuration.","type":"text"}],"references":{"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","type":"topic","kind":"symbol","title":"init(barcode:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","abstract":[{"text":"Document library module configuration.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","title":"barcode","kind":"symbol","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle"}]}]}