{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners(im)initWithTopLeft:topRight:bottomRight:bottomLeft:","symbolKind":"init","role":"symbol","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"title":"init(topLeft:topRight:bottomRight:bottomLeft:)"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"topLeft"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"kind":"text","text":", "},{"text":"bottomLeft","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/corners\/init(topleft:topright:bottomright:bottomleft:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/corners\/init(topleft:topright:bottomright:bottomleft:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/Corners":{"title":"Corners","kind":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"url":"\/documentation\/dotdocument\/corners","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","role":"symbol","url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"role":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","url":"\/documentation\/dotdocument\/corners\/init(topleft:topright:bottomright:bottomleft:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithTopLeft:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"topLeft","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"kind":"text","text":" *) "},{"text":"topRight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottomRight:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bottomRight"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bottomLeft"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]}]}]}