{"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topLeft","title":"topLeft","navigatorTitle":[{"text":"topLeft","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topLeft","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/corners\/topleft"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/corners\/topleft"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"}]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Top left corner point."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/PointDouble":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"title":"PointDouble","url":"\/documentation\/dotdocument\/pointdouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Corners":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","url":"\/documentation\/dotdocument\/corners","title":"Corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Corners/topLeft":{"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/topLeft","abstract":[{"text":"Top left corner point.","type":"text"}],"title":"topLeft","url":"\/documentation\/dotdocument\/corners\/topleft","navigatorTitle":[{"kind":"identifier","text":"topLeft"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.0"}],"type":"topic","title":"DotDocument"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"topLeft"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"topLeft","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"topLeft","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","op":"replace","value":"DOTCorners"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topLeft\/title","op":"replace","value":"topLeft"},{"value":[{"kind":"identifier","text":"topLeft"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1topLeft\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}