{"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/!=(_:_:)"],"title":"Operators","anchor":"Operators","generated":true}],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmmoduleid\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/Equatable-Implementations"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/!=(_:_:)":{"kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/!=(_:_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/!=(_:_:)","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"type":"topic","role":"symbol","title":"DotPalmModuleId","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","op":"replace"},{"value":[{"text":"DotPalmModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/navigatorTitle","op":"replace"}]}]}