{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FlatTagStructureParser","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)FlatTagStructureParser","navigatorTitle":[{"kind":"identifier","text":"FlatTagStructureParser"}],"title":"FlatTagStructureParser","modules":[{"name":"DotNfc"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","platforms":[{"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false,"unavailable":false}]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/parse(value:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error"],"title":"Enumerations"}],"seeAlsoSections":[{"title":"Non-UI components","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/flattagstructureparser"]},{"paths":["\/documentation\/dotnfc\/flattagstructureparser"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FlatTagStructureParser","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse "},{"code":"OptionalDetails.content","type":"codeVoice"},{"text":" of some documents.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"references":{"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/FlatTagStructureParser/Error":{"role":"symbol","type":"topic","title":"FlatTagStructureParser.Error","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/flattagstructureparser\/error","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/FlatTagStructureParser/parse(value:)":{"role":"symbol","type":"topic","title":"parse(value:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/parse(value:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"parse","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"parseWithValue:error:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/flattagstructureparser\/parse(value:)","abstract":[{"text":"Parse flat tag structure and return (tag, value) pairs as a dictionary.","type":"text"}]},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/FlatTagStructureParser":{"role":"symbol","type":"topic","title":"FlatTagStructureParser","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FlatTagStructureParser","kind":"identifier"}],"navigatorTitle":[{"text":"FlatTagStructureParser","kind":"identifier"}],"url":"\/documentation\/dotnfc\/flattagstructureparser","abstract":[{"text":"This class can parse input data as a flat tag structure which can be present in Data Groups. For example, this class should be able to parse ","type":"text"},{"type":"codeVoice","code":"OptionalDetails.content"},{"text":" of some documents.","type":"text"}]},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/FlatTagStructureParser/init":{"abstract":[],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotnfc\/flattagstructureparser\/init","title":"init","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/platforms","value":[]},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"FlatTagStructureParser","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"FlatTagStructureParser"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"FlatTagStructureParser"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/init","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/FlatTagStructureParser\/parse(value:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Non-UI components","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"FlatTagStructureParser","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"parseWithValue:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1FlatTagStructureParser~1parse(value:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1FlatTagStructureParser~1parse(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"parseWithValue:error:","kind":"identifier"}]},{"value":"FlatTagStructureParser","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1FlatTagStructureParser\/title","op":"replace"},{"op":"replace","value":[{"text":"FlatTagStructureParser","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1FlatTagStructureParser\/fragments"},{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]}]}]}