{"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/wrappeddouble"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/wrappeddouble"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"]}],"abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"metadata":{"roleHeading":"Class","modules":[{"name":"DotNfc"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"title":"WrappedDouble","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"externalID":"c:@M@DotNfc@objc(cs)DOTWrappedDouble","role":"symbol"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/init(value:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/isEqual(_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTWrappedDouble) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble":{"url":"\/documentation\/dotnfc\/wrappeddouble","title":"WrappedDouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"WrappedDouble","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble/init(value:)":{"title":"init(value:)","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/init(value:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/wrappeddouble\/init(value:)","role":"symbol"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble/hash":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"hash","url":"\/documentation\/dotnfc\/wrappeddouble\/hash","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble/description":{"title":"description","url":"\/documentation\/dotnfc\/wrappeddouble\/description","kind":"symbol","abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/description"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble/isEqual(_:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","url":"\/documentation\/dotnfc\/wrappeddouble\/isequal(_:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/WrappedDouble/value":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"value","url":"\/documentation\/dotnfc\/wrappeddouble\/value","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"DOTWrappedDouble","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/value"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/init(value:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/WrappedDouble\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTWrappedDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble\/fragments"},{"op":"replace","value":"initWithValue:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1init(value:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1init(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithValue:"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1hash\/title","value":"hash","op":"replace"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1hash\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"value":"value","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1value\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1WrappedDouble~1value\/fragments","value":[{"text":"value","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}