{"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/traveldocumenttype\/scale"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"scale","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/scale"},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"externalID":"s:18DotDocumentCommons06TravelB4TypeO5scaleSdvp","title":"scale","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument/TravelDocumentType/scale":{"type":"topic","url":"\/documentation\/dotdocument\/traveldocumenttype\/scale","kind":"symbol","title":"scale","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/scale","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"url":"\/documentation\/dotdocument\/traveldocumenttype","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","role":"symbol","kind":"symbol","title":"TravelDocumentType"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace","value":"DOTTravelDocumentType"},{"op":"replace","value":[{"text":"DOTTravelDocumentType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}