{"variants":[{"paths":["\/documentation\/dotfacecore\/intervalfloat\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"sections":[],"metadata":{"externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"role":"symbol","extendedModule":"DotCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"composeWithInternalError()"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"type":"text","text":"."}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error/composeWithInternalError()":{"url":"\/documentation\/dotfacecore\/intervalfloat\/error\/composewithinternalerror()","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error\/composeWithInternalError()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic","title":"composeWithInternalError()"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"IntervalFloat.Error","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/intervalfloat\/error"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"title":"IntervalFloat","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacecore\/intervalfloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}