{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibraryid"]},{"paths":["\/documentation\/dotfacelite\/dotlibraryid"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"DotLibraryId","symbolKind":"enum","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"externalID":"c:@M@DotCore@E@DotLibraryId"},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/document","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/face","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/faceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/nfc","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/palm"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/description"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/RawRepresentable-Implementations"],"title":"Default Implementations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/face":{"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"}],"type":"topic","kind":"symbol","title":"DotLibraryId.face","url":"\/documentation\/dotfacelite\/dotlibraryid\/face","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/face","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid","title":"DotLibraryId","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/RawRepresentable-Implementations":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/RawRepresentable-Implementations"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/palm":{"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibraryid\/palm","kind":"symbol","abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"title":"DotLibraryId.palm","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/palm","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/faceLite":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid\/facelite","title":"DotLibraryId.faceLite","role":"symbol","abstract":[{"code":"DotFaceLiteLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"faceLite","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/faceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/nfc":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid\/nfc","title":"DotLibraryId.nfc","role":"symbol","abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"text":" identifier.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"nfc","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdNfc"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/nfc"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/document":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid\/document","title":"DotLibraryId.document","role":"symbol","abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/document"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/description":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibraryid\/description","title":"description","role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/description"},"doc://DotFaceLite/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SY"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/dotlibraryid\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/init(rawValue:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/Equatable-Implementations":{"role":"collectionGroup","type":"topic","kind":"article","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/Equatable-Implementations","url":"\/documentation\/dotfacelite\/dotlibraryid\/equatable-implementations","abstract":[],"title":"Equatable Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryId"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/document","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/face","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/faceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/nfc","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/palm"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"value":"DotLibraryIdFace","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1face\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1face\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"value":"DotLibraryIdPalm","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1palm\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1palm\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1faceLite\/fragments","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]},{"op":"replace","value":"DotLibraryIdNfc","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1nfc\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1nfc\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdNfc"}]},{"op":"replace","value":"DotLibraryIdDocument","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1document\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1document\/fragments","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}