{"metadata":{"title":"facing","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)facing","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"role":"symbol","navigatorTitle":[{"text":"facing","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Front or back camera facing.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/facing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/facing"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/facing"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/facing":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/facing","title":"facing","url":"\/documentation\/dotfacecore\/cameraconfiguration\/facing","abstract":[{"type":"text","text":"Front or back camera facing."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"facing","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"symbol","title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"title":"CameraConfiguration","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"facing","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"facing"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"DOTCameraFacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1facing\/title","value":"facing","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1facing\/fragments","value":[{"kind":"identifier","text":"facing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"}]}]}