{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(im)isEqual:","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isEqual(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"url":"\/documentation\/dotfacecore\/cameraconfiguration","role":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"symbol","title":"CameraConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isEqual(_:)":{"title":"isEqual(_:)","type":"topic","kind":"symbol","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isEqual(_:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"isEqual:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace"}]}]}