{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/ispreviewvisible"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/ispreviewvisible"]}],"abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isPreviewVisible","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"isPreviewVisible","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"isPreviewVisible"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isPreviewVisible","roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isPreviewVisible":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/cameraconfiguration\/ispreviewvisible","abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isPreviewVisible","title":"isPreviewVisible","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"role":"symbol","title":"CameraConfiguration","kind":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isPreviewVisible"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isPreviewVisible","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isPreviewVisible\/title","value":"isPreviewVisible"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isPreviewVisible\/fragments","value":[{"text":"isPreviewVisible","kind":"identifier"}]},{"op":"replace","value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle"}]}]}