{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isVideoCaptureEnabled"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/isvideocaptureenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/cameraconfiguration\/isvideocaptureenabled"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"isVideoCaptureEnabled","role":"symbol","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isVideoCaptureEnabled","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"]]},"abstract":[{"text":"Use this flag to enable\/disable video capture.","type":"text"},{"text":" ","type":"text"},{"text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.","type":"text"},{"text":" ","type":"text"},{"text":"The captured video is included exclusively in the binary content of the result. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"role":"symbol","url":"\/documentation\/dotfacecore\/cameraconfiguration","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration/isVideoCaptureEnabled":{"abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","url":"\/documentation\/dotfacecore\/cameraconfiguration\/isvideocaptureenabled","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration\/isVideoCaptureEnabled","title":"isVideoCaptureEnabled","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isVideoCaptureEnabled"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"isVideoCaptureEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isVideoCaptureEnabled\/title","value":"isVideoCaptureEnabled","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"op":"replace"}]}]}