{"metadata":{"externalID":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV45minValidSamplesInRowToStartCandidateSelectionSivpZ","symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/Defaults/minValidSamplesInRowToStartCandidateSelection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults\/minValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"minValidSamplesInRowToStartCandidateSelection","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/defaults\/minvalidsamplesinrowtostartcandidateselection"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing fingers images with customizable UI.","type":"text"}],"title":"BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/Defaults":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/defaults","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults","title":"BaseFingersAutoCaptureViewController.Configuration.Defaults","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}]}]}]}