{"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocapturequalityattributethresholdsfinger\/initwithminsharpness:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger"]]},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger(im)initWithMinSharpness:","role":"symbol","title":"initWithMinSharpness:","navigatorTitle":[{"text":"initWithMinSharpness:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithMinSharpness:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithMinSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble","text":"DOTWrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":" *) ","kind":"text"},{"text":"minSharpness","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger\/initWithMinSharpness:","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger/initWithMinSharpness:":{"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturequalityattributethresholdsfinger\/initwithminsharpness:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinSharpness:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinSharpness:"}],"title":"initWithMinSharpness:","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger\/initWithMinSharpness:"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappeddouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger":{"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocapturequalityattributethresholdsfinger","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger"}],"title":"DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureQualityAttributeThresholdsFinger"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/fragments","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}