{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/faceLibraryComponent","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","text":"FaceLibraryComponentConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"Default is:"}],"type":"paragraph"},{"syntax":null,"type":"codeListing","code":[".init(","    faceSizeRatioInterval: .init(min: 0.1, max: 0.3),","    query: .init()",")"]}]}],"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"faceLibraryComponent","role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","platforms":[{"message":"Use MultiRangeLivenessViewController instead.","deprecated":true,"unavailable":false,"beta":false}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLibraryComponent","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration"}],"externalID":"s:11DotFaceCore31MagnifEyeLivenessViewControllerC13ConfigurationC20faceLibraryComponentAA0bklI0Cvp"},"abstract":[{"type":"text","text":"Configuration for face library components."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/facelibrarycomponent"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class","kind":"symbol","title":"MagnifEyeLivenessViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","abstract":[{"text":"Configuration for face library components.","type":"text"}],"title":"FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceLibraryComponentConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController/Configuration-swift.class/faceLibraryComponent":{"title":"faceLibraryComponent","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController\/Configuration-swift.class\/faceLibraryComponent","deprecated":true,"type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller\/configuration-swift.class\/facelibrarycomponent","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceLibraryComponent"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceLibraryComponentConfiguration","text":"FaceLibraryComponentConfiguration"}],"abstract":[{"type":"text","text":"Configuration for face library components."}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","type":"topic","deprecated":true,"abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title","value":"DOTFFaceLibraryComponentConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments","value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle","op":"replace"}]}]}