{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":" = .init(), "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC","text":"Style","kind":"typeIdentifier"},{"text":" = .init())","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Configure the face simple capture process."}]}],"name":"configuration"},{"name":"style","content":[{"inlineContent":[{"type":"text","text":"Customize user interface."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New instance of "},{"code":"FaceSimpleCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}]}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/init(configuration:style:)","interfaceLanguage":"swift"},"abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"FaceSimpleCaptureViewController"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(im)initWithConfiguration:style:","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"roleHeading":"Initializer","role":"symbol","title":"init(configuration:style:)","symbolKind":"init","platforms":[]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"title":"FaceSimpleCaptureViewController.Configuration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/init(configuration:style:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/init(configuration:style:)","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"code":"FaceSimpleCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"deprecated":true,"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"style"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC","kind":"typeIdentifier","text":"Style"},{"kind":"text","text":")"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceSimpleCaptureConfiguration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"url":"\/documentation\/dotfacecore\/dotffacesimplecaptureconfiguration","role":"symbol","title":"DOTFFaceSimpleCaptureConfiguration","fragments":[{"text":"DOTFFaceSimpleCaptureConfiguration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/Style-swift.class":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","kind":"symbol","type":"topic","title":"FaceSimpleCaptureViewController.Style","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.class","role":"symbol","abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"deprecated":true,"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"kind":"symbol","role":"symbol","title":"FaceSimpleCaptureViewController"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceSimpleCaptureStyle":{"role":"symbol","abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureStyle","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureStyle"}],"type":"topic","title":"DOTFFaceSimpleCaptureStyle","url":"\/documentation\/dotfacecore\/dotffacesimplecapturestyle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithConfiguration:style:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTFFaceSimpleCaptureConfiguration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureStyle","text":"DOTFFaceSimpleCaptureStyle","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1init(configuration:style:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1init(configuration:style:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController","op":"replace"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace"}]}]}