{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}]}]}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotDocument"}],"title":"DotFaceModuleId.detectionFast","symbolKind":"case","role":"symbol","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdDetectionFast","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}]},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/detectionfast"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/detectionfast"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionFast","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/detectionFast":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionFast","kind":"identifier"}],"title":"DotFaceModuleId.detectionFast","url":"\/documentation\/dotdocument\/dotfacemoduleid\/detectionfast","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/detectionFast","abstract":[],"navigatorTitle":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"url":"\/documentation\/dotdocument\/dotfacemoduleid","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdDetectionFast","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleIdDetectionFast","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionFast\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1detectionFast\/fragments"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}