{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/verification"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotfacemoduleid\/verification"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/verification","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdVerification","title":"DotFaceModuleId.verification","modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceModuleId/verification":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId\/verification","title":"DotFaceModuleId.verification","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"url":"\/documentation\/dotdocument\/dotfacemoduleid\/verification"},"doc://DotDocument/documentation/DotDocument/DotFaceModuleId":{"url":"\/documentation\/dotdocument\/dotfacemoduleid","abstract":[{"code":"DotFace","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdVerification","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleIdVerification","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1verification\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId~1verification\/fragments"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceModuleId\/navigatorTitle"}]}]}