{"sections":[],"metadata":{"symbolKind":"typealias","externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC12BaseDefaultsa","title":"PalmAutoCaptureViewController.Configuration.BaseDefaults","modules":[{"name":"DotPalmCore"}],"roleHeading":"Type Alias","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDefaults"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseDefaults"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/BaseDefaults"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/basedefaults"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BaseDefaults","kind":"identifier"},{"text":" = ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureViewController","text":"BasePalmAutoCaptureViewController","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults","preciseIdentifier":"s:11DotPalmCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV","text":"Defaults","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration/Defaults":{"title":"BasePalmAutoCaptureViewController.Configuration.Defaults","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration\/defaults","role":"symbol","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration\/Defaults"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI Palm Auto Capture component."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","kind":"symbol","title":"PalmAutoCaptureViewController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the UI Palm Auto Capture component.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","role":"symbol","title":"PalmAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController/Configuration":{"abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController\/Configuration","url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller\/configuration","role":"symbol","title":"BasePalmAutoCaptureViewController.Configuration"},"doc://DotPalmCore/documentation/DotPalmCore/BasePalmAutoCaptureViewController":{"kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing palm images with customizable UI."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BasePalmAutoCaptureViewController","title":"BasePalmAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BasePalmAutoCaptureViewController"}],"url":"\/documentation\/dotpalmcore\/basepalmautocaptureviewcontroller"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/BaseDefaults":{"type":"topic","title":"PalmAutoCaptureViewController.Configuration.BaseDefaults","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/basedefaults","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/BaseDefaults","navigatorTitle":[{"kind":"identifier","text":"BaseDefaults"}],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseDefaults"}]}},"variantOverrides":[{"patch":[{"value":"DOTPPalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle"},{"value":"DOTPBasePalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTPBasePalmAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/fragments"},{"value":[{"text":"DOTPBasePalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BasePalmAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}