{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible\/type","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"PlaceholderType"}],"modules":[{"name":"DotPalmCore"}],"title":"type","role":"symbol","externalID":"s:11DotPalmCore11PlaceholderC7VisibleC4typeAA0D4TypeOvp","roleHeading":"Instance Property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholder\/visible\/type"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"PlaceholderType"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible"]]},"abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"codeVoice","code":".left"},{"type":"text","text":"."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"url":"\/documentation\/dotpalmcore\/placeholder","role":"symbol","title":"Placeholder","type":"topic","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Visible/type":{"url":"\/documentation\/dotpalmcore\/placeholder\/visible\/type","title":"type","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"code":".left","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPlaceholderType","text":"PlaceholderType"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible\/type"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Visible":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/placeholder\/visible","title":"Placeholder.Visible","abstract":[{"type":"text","text":"Visible placeholder."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"navigatorTitle":[{"text":"Visible","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Visible","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"title":"PlaceholderType","url":"\/documentation\/dotpalmcore\/placeholdertype","role":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of placeholder."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title"},{"value":[{"text":"DOTPPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments"},{"value":[{"text":"DOTPPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle"},{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"value":[{"text":"DOTPPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments"},{"value":[{"text":"DOTPPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/navigatorTitle"}]}]}