{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"travelDocumentType","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(py)travelDocumentType","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"travelDocumentType","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Resolved travel document type."}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/traveldocumenttype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/traveldocumenttype"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"travelDocumentType","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","text":"TravelDocumentTypeWrapper"},{"text":"?","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/travelDocumentType","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/travelDocumentType":{"type":"topic","title":"travelDocumentType","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"travelDocumentType"}],"abstract":[{"type":"text","text":"Resolved travel document type."}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/traveldocumenttype","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/travelDocumentType","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"travelDocumentType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","kind":"symbol","title":"TravelDocumentTypeWrapper","role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"title":"DocumentAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"travelDocumentType"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"travelDocumentType"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper","text":"DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"travelDocumentType"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"travelDocumentType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1travelDocumentType\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1travelDocumentType\/fragments","value":[{"text":"travelDocumentType","kind":"identifier"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper","op":"replace"},{"value":[{"text":"DOTTravelDocumentTypeWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}