{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/init(modules:)"},"metadata":{"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}],"title":"init(modules:)","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(im)initWithModules:","symbolKind":"init","modules":[{"name":"DotFaceLite"}],"roleHeading":"Initializer"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"text":")","kind":"text"}]}]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/init(modules:)"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/init(modules:)":{"abstract":[],"title":"init(modules:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/init(modules:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/init(modules:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration":{"abstract":[{"type":"text","text":"Palm library configuration."}],"title":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfiguration.Modules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfiguration\/Modules-swift.class","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfiguration\/modules-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules":{"abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfigurationModules","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModules:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithModules:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules"},{"text":" *) ","kind":"text"},{"text":"modules","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithModules:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration~1init(modules:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration~1init(modules:)\/fragments"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmLibraryConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}