{"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"typeIdentifier","text":"DOTDDocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"result"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentAutoCaptureControllerPhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDDocumentAutoCaptureControllerPhase","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerPhase"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"phase"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult\/initwithdetection:result:phase:"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerProcessingResult(im)initWithDetection:result:phase:","roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"title":"initWithDetection:result:phase:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:phase:"}],"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:phase:"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult":{"kind":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureControllerProcessingResult","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult","abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","title":"DOTDDocumentAutoCaptureControllerProcessingResult","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"title":"DocumentAutoCaptureDetection","url":"\/documentation\/dotdocument\/documentautocapturedetection","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult/initWithDetection:result:phase:":{"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithDetection:result:phase:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult\/initwithdetection:result:phase:","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:phase:"}],"title":"initWithDetection:result:phase:","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureResult":{"title":"DocumentAutoCaptureResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureResult","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureresult","type":"topic","navigatorTitle":[{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureResult","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerPhase":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerPhase","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Phase of the document auto capture process.","type":"text"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerphase","fragments":[{"text":"DOTDDocumentAutoCaptureControllerPhase","kind":"identifier"}],"title":"DOTDDocumentAutoCaptureControllerPhase"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCaptureDetection","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"op":"replace"},{"value":"DOTDDocumentAutoCaptureResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments"}]}]}