{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage\/size"},"metadata":{"navigatorTitle":[{"text":"size","kind":"identifier"}],"title":"size","roleHeading":"Instance Property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTBgraRawImage(py)size","modules":[{"name":"DotNfc"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","text":"ImageSize","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrarawimage\/size"]},{"paths":["\/documentation\/dotnfc\/bgrarawimage\/size"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Image size.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage","title":"BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"role":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotnfc\/bgrarawimage"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagesize","kind":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"title":"ImageSize"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgraRawImage/size":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgraRawImage\/size","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","text":"ImageSize"}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimage\/size","abstract":[{"text":"Image size.","type":"text"}],"title":"size","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"size","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"size","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"DOTImageSize"},{"kind":"text","text":" * "},{"text":"size","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage\/fragments","op":"replace"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"value":"size","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage~1size\/title"},{"op":"replace","value":[{"text":"size","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgraRawImage~1size\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}