{"metadata":{"externalID":"s:7DotCore0A3SdkC13ConfigurationC24transactionCountingTokenSSSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"transactionCountingToken","role":"symbol"},"abstract":[{"type":"text","text":"Transaction counting token."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/configuration\/transactioncountingtoken"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration"]]},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration\/transactionCountingToken"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Configuration/transactionCountingToken":{"title":"transactionCountingToken","url":"\/documentation\/dotfacecore\/dotsdk\/configuration\/transactioncountingtoken","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingToken","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Transaction counting token."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration\/transactionCountingToken","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/dotsdk"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Configuration":{"kind":"symbol","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Configuration","title":"DotSdk.Configuration","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdk\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}