{"metadata":{"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedCAEycfc","role":"symbol","symbolKind":"init","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/balanced\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"title":"DotFaceDetectionModuleConfiguration","type":"topic","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Balanced/init()":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/balanced\/init()","title":"init()"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Balanced":{"kind":"symbol","abstract":[{"text":"Face detection balanced module.","type":"text"}],"title":"DotFaceDetectionModuleConfiguration.Balanced","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Balanced","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/balanced"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle"}]}]}