{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"localizedDescription","modules":[{"relatedModules":["Swift"],"name":"DotFingersCore"}],"externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:7DotCore14IntervalDoubleC5ErrorO","platforms":[{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"iPadOS","beta":false},{"deprecated":false,"introducedAt":"8.0","unavailable":false,"name":"Mac Catalyst","beta":false},{"deprecated":false,"introducedAt":"10.10","unavailable":false,"name":"macOS","beta":false},{"deprecated":false,"introducedAt":"9.0","unavailable":false,"name":"tvOS","beta":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS","beta":false}],"role":"symbol","extendedModule":"Swift","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/localizedDescription","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/intervaldouble\/error\/localizeddescription"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"IntervalDouble.Error","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotfingerscore\/intervaldouble\/error"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotfingerscore\/intervaldouble","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble","title":"IntervalDouble","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/IntervalDouble/Error/localizedDescription":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/IntervalDouble\/Error\/localizedDescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"localizedDescription","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/intervaldouble\/error\/localizeddescription"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/title"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/fragments"},{"value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1IntervalDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}