{"sections":[],"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotFaceLite"}],"role":"collectionGroup","title":"RawRepresentable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/hashValue"],"generated":true},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/hash(into:)"],"generated":true}],"variants":[{"paths":["\/documentation\/dotfacelite\/imageformat\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"type":"topic","url":"\/documentation\/dotfacelite\/imageformat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"title":"ImageFormat"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/hash(into:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"hash(into:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/hash(into:)","type":"topic","url":"\/documentation\/dotfacelite\/imageformat\/hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]}},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/hashValue":{"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"url":"\/documentation\/dotfacelite\/imageformat\/hashvalue","title":"hashValue","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/hashValue","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments","op":"replace"},{"value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}