{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModuleId"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Enumeration","modules":[{"name":"DotPalmCore"}],"title":"DotPalmModuleId","externalID":"c:@M@DotPalmCore@E@DotPalmModuleId","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"symbolKind":"enum"},"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"DotPalm modularization","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule"],"generated":true}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/detection"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/init(rawValue:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmmoduleid"]},{"paths":["\/documentation\/dotpalmcore\/dotpalmmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"},"abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/description":{"type":"topic","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/description","title":"description","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/Equatable-Implementations":{"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/equatable-implementations","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmModule"}],"title":"DotPalmModule","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module."}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModule"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmodule","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"type":"topic","kind":"article","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/detection":{"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/detection","abstract":[],"title":"DotPalmModuleId.detection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/detection","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"title":"DotPalmModuleId","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModuleId"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId/init(rawValue:)":{"url":"\/documentation\/dotpalmcore\/dotpalmmoduleid\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DotPalmModuleId","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId\/detection"],"title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule"],"title":"DotPalm modularization","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/title","value":"DotPalmModule"},{"value":[{"text":"DotPalmModule","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/fragments","op":"replace"},{"value":"DotPalmModuleIdDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId~1detection\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId~1detection\/fragments","value":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"op":"replace"},{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]}]}]}