{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"sections":[],"metadata":{"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"symbolKind":"class","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotSdk","roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}]},"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdk"]},{"paths":["\/documentation\/dotpalmcore\/dotsdk"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/bundleId","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isInitialized","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/versionName"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/deinitialize()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/shared"]},{"title":"Enumerations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error"]}],"references":{"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/versionName":{"url":"\/documentation\/dotpalmcore\/dotsdk\/versionname","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"versionName","abstract":[{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" version."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/versionName"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"DotSdk.Error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdk\/error","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/initialize(configuration:)":{"title":"initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/initialize(configuration:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/initialize(configuration:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration","text":"DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/isInitialized":{"url":"\/documentation\/dotpalmcore\/dotsdk\/isinitialized","abstract":[{"type":"text","text":"Flag to determine if "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" is initialized."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isInitialized","title":"isInitialized","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isInitialized","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"isInitialized"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/isLibraryActive(libraryId:)":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"title":"isLibraryActive(libraryId:)","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isLibraryActive(libraryId:)","url":"\/documentation\/dotpalmcore\/dotsdk\/islibraryactive(libraryid:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/shared":{"title":"shared","navigatorTitle":[{"text":"shared","kind":"identifier"}],"abstract":[{"type":"text","text":"Shared singleton instance."}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/shared","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/deinitialize()":{"title":"deinitialize()","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/deinitialize()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/bundleId":{"title":"bundleId","navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"type":"topic","abstract":[{"text":"Application Bundle ID.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdk\/bundleid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/bundleId","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bundleId","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"kind":"symbol","type":"topic","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"title":"DotSdk","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","url":"\/documentation\/dotpalmcore\/dotsdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DotSdk","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/bundleId","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isInitialized","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/versionName"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/deinitialize()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/isLibraryActive(libraryId:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/shared"]}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"versionName","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1versionName\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1versionName\/fragments","value":[{"kind":"identifier","text":"versionName"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1initialize(configuration:)\/title","value":"initializeWithConfiguration:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1initialize(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isInitialized\/title","value":"isInitialized","op":"replace"},{"value":[{"text":"isInitialized","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isInitialized\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isLibraryActive(libraryId:)\/title","value":"isLibraryActiveWithLibraryId:"},{"value":[{"text":"- ","kind":"text"},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1isLibraryActive(libraryId:)\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1shared\/title","value":"shared","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1shared\/fragments","value":[{"kind":"identifier","text":"shared"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1deinitialize()\/title","value":"deinitializeAndReturnError:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1deinitialize()\/fragments","op":"replace"},{"op":"replace","value":"bundleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1bundleId\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1bundleId\/fragments","value":[{"kind":"identifier","text":"bundleId"}]},{"value":"DotSdk","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}