{"metadata":{"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init","modules":[{"name":"DotNfc"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceLiteLibraryConfiguration(im)init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotfacelitelibraryconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotFaceLiteLibraryConfiguration/init":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotfacelitelibraryconfiguration\/init","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration\/init"},"doc://DotNfc/documentation/DotNfc/DotFaceLiteLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotfacelitelibraryconfiguration","type":"topic","title":"DotFaceLiteLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLiteLibraryConfiguration","abstract":[{"text":"Face Lite library configuration.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceLiteLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceLiteLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLiteLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLiteLibraryConfiguration\/navigatorTitle"}]}]}