{"metadata":{"role":"symbol","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"title":"CaptureMode.autoCapture","roleHeading":"Case","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeAutoCapture","symbolKind":"case","modules":[{"name":"DotPalmCore"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/autoCapture","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Once specified count of consecutive valid frames have been acquired,"},{"type":"text","text":" "},{"type":"text","text":"the candidate selection process is triggered and continues for specified time in milliseconds."},{"type":"text","text":" "},{"text":"During this period, the system analyzes the pool of valid images to determine the most suitable result image.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/capturemode\/autocapture"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/capturemode\/autocapture"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/autoCapture":{"kind":"symbol","title":"CaptureMode.autoCapture","navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/capturemode\/autocapture","abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"autoCapture"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/autoCapture"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode":{"type":"topic","abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotpalmcore\/capturemode","navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"title":"CaptureMode"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTCaptureModeAutoCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTCaptureModeAutoCapture","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1autoCapture\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1autoCapture\/fragments","value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"op":"replace"},{"op":"replace","value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/title"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/fragments"}]}]}