{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]]},"abstract":[{"text":"Face attribute score.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"score"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The score is reliable only if the "},{"code":"preconditionsMet","type":"codeVoice"},{"type":"text","text":" flag is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/glasses\/score"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/glasses\/score"]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFGlasses(py)score","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"score","kind":"identifier"}],"title":"score","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses\/score","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/glasses","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Glasses","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Glasses","kind":"identifier"}],"title":"Glasses"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses/score":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses\/score","title":"score","url":"\/documentation\/dotfacecore\/glasses\/score","kind":"symbol","type":"topic","abstract":[{"text":"Face attribute score.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"score","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"score","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"score","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"kind":"identifier","text":"DOTFGlasses"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses~1score\/title","value":"score","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"score"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses~1score\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}