{"metadata":{"fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"backgroundUniformity","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"backgroundUniformity"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/backgrounduniformity"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/backgroundUniformity","interfaceLanguage":"occ"},"references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"kind":"symbol","title":"DotFaceLibraryConfigurationModules","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules/backgroundUniformity":{"fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"abstract":[],"role":"symbol","title":"backgroundUniformity","kind":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/backgrounduniformity","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/backgroundUniformity"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"type":"text","text":"Face background uniformity module."}],"url":"\/documentation\/dotdocument\/dotfacebackgrounduniformitymoduleconfiguration","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"title":"DotFaceBackgroundUniformityModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}