{"sections":[],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTRectangleDouble) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"languages":["swift"]}]}],"seeAlsoSections":[{"generated":true,"title":"Face detection output","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"]]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/rectangledouble"]},{"paths":["\/documentation\/dotfacelite\/rectangledouble"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/init(left:top:right:bottom:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/width"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/fullRectangle"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/from(cgRect:)"],"title":"Type Methods"}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"roleHeading":"Class","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble":{"type":"topic","title":"RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/width":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/width","kind":"symbol","title":"width","type":"topic","role":"symbol","navigatorTitle":[{"text":"width","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/rectangledouble\/width"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/from(cgRect:)":{"type":"topic","title":"from(cgRect:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/from(cgRect:)","url":"\/documentation\/dotfacelite\/rectangledouble\/from(cgrect:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgRect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"fromCgRect:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/mirrored()":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/mirrored()","role":"symbol","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/mirrored()","abstract":[],"title":"mirrored()"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/left":{"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/left","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"left"}],"abstract":[{"text":"Left edge.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/left","title":"left"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/hash":{"url":"\/documentation\/dotfacelite\/rectangledouble\/hash","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/hash","kind":"symbol","role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"url":"\/documentation\/dotfacelite\/facedetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/bottom":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottom"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/bottom","role":"symbol","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"abstract":[{"text":"Bottom edge.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/bottom","title":"bottom"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/rebased(parentRectangle:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/rebased(parentrectangle:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/rebased(parentRectangle:)","abstract":[],"title":"rebased(parentRectangle:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/right":{"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/right","role":"symbol","navigatorTitle":[{"text":"right","kind":"identifier"}],"abstract":[{"text":"Right edge.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/right","title":"right"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/description":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/description","abstract":[],"title":"description"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/points":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"points","kind":"identifier"},{"kind":"text","text":": ["},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/points","role":"symbol","navigatorTitle":[{"text":"points","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/points","title":"points"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/isEqual(_:)":{"kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/isequal(_:)","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/isEqual(_:)","abstract":[],"title":"isEqual(_:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/init(left:top:right:bottom:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"abstract":[],"title":"init(left:top:right:bottom:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/init(left:top:right:bottom:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"left","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/init(left:top:right:bottom:)"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/cgRect":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"text":"CGRect","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/cgrect","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/cgRect","kind":"symbol","type":"topic","role":"symbol","title":"cgRect","navigatorTitle":[{"text":"cgRect","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/fullRectangle":{"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble\/fullrectangle","role":"symbol","navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/fullRectangle","title":"fullRectangle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/top":{"url":"\/documentation\/dotfacelite\/rectangledouble\/top","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"top","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/top","navigatorTitle":[{"text":"top","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Top edge."}],"title":"top","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters":{"url":"\/documentation\/dotfacelite\/imageparameters","role":"symbol","abstract":[{"type":"text","text":"Parameters of the image which was used for the face detection."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","type":"topic","title":"ImageParameters"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble/height":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/height","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"height","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"kind":"symbol","type":"topic","abstract":[],"title":"height","url":"\/documentation\/dotfacelite\/rectangledouble\/height"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTRectangleDouble","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/bottom","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/cgRect","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/hash","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/height","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/left","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/points","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/right","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/top","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/init(left:top:right:bottom:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/mirrored()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/fullRectangle"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble\/from(cgRect:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"]}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face detection output","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTRectangleDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"value":"width","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1width\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1width\/fragments","value":[{"text":"width","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1from(cgRect:)\/title","value":"fromCgRect:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1from(cgRect:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"fromCgRect:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1mirrored()\/title","value":"mirrored"},{"value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1mirrored()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1left\/title","value":"left","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1left\/fragments","value":[{"text":"left","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1hash\/title","value":"hash","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1hash\/fragments","op":"replace"},{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"bottom","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1bottom\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1bottom\/fragments","op":"replace","value":[{"text":"bottom","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1rebased(parentRectangle:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1right\/title","value":"right"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1right\/fragments","op":"replace","value":[{"kind":"identifier","text":"right"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1points\/title","value":"points","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1points\/fragments","value":[{"text":"points","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1init(left:top:right:bottom:)\/title","value":"initWithLeft:top:right:bottom:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1init(left:top:right:bottom:)\/fragments","op":"replace"},{"value":"cgRect","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1cgRect\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cgRect"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1cgRect\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1fullRectangle\/title","value":"fullRectangle"},{"value":[{"text":"fullRectangle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1fullRectangle\/fragments"},{"value":"top","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1top\/title"},{"value":[{"kind":"identifier","text":"top"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1top\/fragments"},{"op":"replace","value":"DOTFLImageParameters","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/fragments","op":"replace","value":[{"text":"DOTFLImageParameters","kind":"identifier"}]},{"value":"height","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1height\/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble~1height\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}