{"metadata":{"role":"symbol","navigatorTitle":[{"text":"angle","kind":"identifier"}],"title":"angle","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute(py)angle","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"angle"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/angle"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"angle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The angle is reliable only if the ","type":"text"},{"type":"codeVoice","code":"preconditionsMet"},{"type":"text","text":" flag is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":"."}]}]}],"abstract":[{"text":"Head pose attribute angle.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/angle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/angle"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseAttribute"}],"type":"topic","title":"HeadPoseAttribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute/angle":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute\/angle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"angle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"abstract":[{"text":"Head pose attribute angle.","type":"text"}],"type":"topic","title":"angle","kind":"symbol","url":"\/documentation\/dotfacecore\/headposeattribute\/angle","role":"symbol","navigatorTitle":[{"text":"angle","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"text":"version: 8.4.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"angle","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"angle"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"angle"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1angle\/title","value":"angle","op":"replace"},{"value":[{"text":"angle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute~1angle\/fragments"}]}]}