{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/major"},"sections":[],"metadata":{"title":"major","symbolKind":"property","roleHeading":"Instance Property","externalID":"s:11DotFaceCore8TemplateC7VersionC5majorSivp","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"major","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/template\/version-swift.class\/major"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"major","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"navigatorTitle":[{"text":"Template","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Template","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Face template."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/template","title":"Template","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","type":"topic","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class/major":{"title":"major","abstract":[],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"major"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","url":"\/documentation\/dotfacecore\/template\/version-swift.class\/major","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class\/major","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TemplateMatcher"}],"type":"topic","title":"TemplateMatcher","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/templatematcher","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template/Version-swift.class":{"navigatorTitle":[{"kind":"identifier","text":"Version"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Version","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Template compatibility version."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/template\/version-swift.class","title":"Template.Version","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template\/Version-swift.class"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"value":[{"text":"DOTFTemplate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments"},{"value":"DOTFTemplateMatcher","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}