{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/camerafacing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/camerafacing"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"topicSections":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/back","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/front"]},{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/init(rawValue:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/native"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/RawRepresentable-Implementations"]}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@DotCamera@E@DOTCameraFacing","role":"symbol","title":"CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraFacing) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFingersCore\/SY","type":"unresolvable"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/RawRepresentable-Implementations":{"kind":"article","type":"topic","title":"RawRepresentable Implementations","url":"\/documentation\/dotfingerscore\/camerafacing\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/RawRepresentable-Implementations"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/back":{"abstract":[{"type":"text","text":"Back facing camera."}],"url":"\/documentation\/dotfingerscore\/camerafacing\/back","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"title":"CameraFacing.back","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/back"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/description":{"title":"description","kind":"symbol","url":"\/documentation\/dotfingerscore\/camerafacing\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/description"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing":{"kind":"symbol","title":"CameraFacing","url":"\/documentation\/dotfingerscore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/native":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/native","title":"native","url":"\/documentation\/dotfingerscore\/camerafacing\/native","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AVCaptureDevice","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/init(rawValue:)":{"url":"\/documentation\/dotfingerscore\/camerafacing\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/init(rawValue:)"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/Equatable-Implementations":{"kind":"article","type":"topic","title":"Equatable Implementations","url":"\/documentation\/dotfingerscore\/camerafacing\/equatable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/Equatable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/front":{"type":"topic","kind":"symbol","title":"CameraFacing.front","url":"\/documentation\/dotfingerscore\/camerafacing\/front","abstract":[{"text":"Front facing camera.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"front","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/front"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTCameraFacing","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/back","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/front"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCameraFacing"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCameraFacingBack","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing~1back\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing~1back\/fragments"},{"op":"replace","value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/navigatorTitle"},{"op":"replace","value":"DOTCameraFacingFront","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing~1front\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing~1front\/fragments"}]}]}