{"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/autoCapture","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/waitForRequest"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/init(rawValue:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/description"]},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCaptureMode) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/capturemode"]},{"paths":["\/documentation\/dotfingerscore\/capturemode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureMode"}],"roleHeading":"Enumeration","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode","symbolKind":"enum","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"references":{"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/waitForRequest":{"url":"\/documentation\/dotfingerscore\/capturemode\/waitforrequest","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"title":"CaptureMode.waitForRequest","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/waitForRequest"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode":{"url":"\/documentation\/dotfingerscore\/capturemode","abstract":[{"text":"Capture mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode"},"doc://DotFingersCore/SY":{"identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/dotfingerscore\/capturemode\/rawrepresentable-implementations","role":"collectionGroup","title":"RawRepresentable Implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/RawRepresentable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/autoCapture":{"abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"url":"\/documentation\/dotfingerscore\/capturemode\/autocapture","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"}],"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"title":"CaptureMode.autoCapture","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/autoCapture"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/description":{"url":"\/documentation\/dotfingerscore\/capturemode\/description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/description","title":"description","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/Equatable-Implementations":{"url":"\/documentation\/dotfingerscore\/capturemode\/equatable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/init(rawValue:)":{"url":"\/documentation\/dotfingerscore\/capturemode\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/init(rawValue:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/autoCapture","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/waitForRequest"],"title":"Enumeration Cases","generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCaptureMode"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1waitForRequest\/title","op":"replace","value":"DOTCaptureModeWaitForRequest"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1waitForRequest\/fragments","op":"replace","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/fragments"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/navigatorTitle","op":"replace"},{"value":"DOTCaptureModeAutoCapture","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1autoCapture\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1autoCapture\/fragments","value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}]}]}]}