{"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}],"seeAlsoSections":[{"title":"Converting images","anchor":"Converting-images","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/cgimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/cgimagefactory"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"title":"CGImageFactory","externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory","symbolKind":"class"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","sections":[],"topicSections":[{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory\/create(image:)"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCGImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}]}]}],"references":{"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CGImageFactory/create(image:)":{"url":"\/documentation\/dotfingerscore\/cgimagefactory\/create(image:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" object.","type":"text"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"}],"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"title":"create(image:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory\/create(image:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/CGImageFactory":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"title":"CGImageFactory","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"url":"\/documentation\/dotfingerscore\/cgimagefactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}]},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory":{"role":"symbol","title":"ImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","kind":"symbol"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/CIImageFactory":{"role":"symbol","title":"CIImageFactory","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfingerscore\/ciimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTCGImageFactory","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory\/create(image:)"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Converting-images","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"],"title":"Converting images"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCGImageFactory"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"createWithImage:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory~1create(image:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory~1create(image:)\/fragments"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTImageFactory","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTCIImageFactory","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle"}]}]}