{"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/init(jointTop:tip:jointBottom:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointBottom","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointTop","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/tip"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/calculateSizeToImageShorterSideRatio(imageSize:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/isEqual(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/mirrored()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/rebased(parentRectangle:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGDetectionPosition) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}]}]}],"abstract":[{"type":"text","text":"Position of the finger in the image."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/detectionposition"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/detectionposition"]}],"seeAlsoSections":[{"title":"Finger detection output","anchor":"Finger-detection-output","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","metadata":{"roleHeading":"Class","title":"DetectionPosition","symbolKind":"class","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/jointTop":{"type":"topic","title":"jointTop","navigatorTitle":[{"kind":"identifier","text":"jointTop"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointTop","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"jointTop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"url":"\/documentation\/dotfingerscore\/detectionposition\/jointtop","abstract":[{"type":"text","text":"Distal Interphalangeal Joint top point. Leftmost point for left hand or rightmost point for right hand."}],"role":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/isEqual(_:)":{"title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/isequal(_:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/isEqual(_:)"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/rebased(parentRectangle:)":{"title":"rebased(parentRectangle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/rebased(parentrectangle:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/rebased(parentRectangle:)"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/mirrored()":{"title":"mirrored()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/mirrored()","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/mirrored()"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/init(jointTop:tip:jointBottom:)":{"title":"init(jointTop:tip:jointBottom:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"jointTop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"tip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"jointBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithJointTop:tip:jointBottom:"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/init(jointtop:tip:jointbottom:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/init(jointTop:tip:jointBottom:)"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/calculateSizeToImageShorterSideRatio(imageSize:)":{"title":"calculateSizeToImageShorterSideRatio(imageSize:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateSizeToImageShorterSideRatio"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"calculateSizeToImageShorterSideRatioWithImageSize:"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/calculatesizetoimageshortersideratio(imagesize:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/calculateSizeToImageShorterSideRatio(imageSize:)"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/hash":{"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition\/hash","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/hash","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/description":{"title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/detectionposition\/description","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/description"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/tip":{"title":"tip","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"tip"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"tip"}],"abstract":[{"type":"text","text":"Fingertip point."}],"url":"\/documentation\/dotfingerscore\/detectionposition\/tip","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/tip"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition/jointBottom":{"title":"jointBottom","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"jointBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"jointBottom"}],"abstract":[{"type":"text","text":"Distal Interphalangeal Joint bottom point. Rightmost point for left hand or leftmost point for right hand."}],"url":"\/documentation\/dotfingerscore\/detectionposition\/jointbottom","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointBottom"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality":{"title":"FingerQuality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerQuality"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}],"abstract":[{"text":"Finger quality.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingerquality","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGDetectionPosition","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointBottom","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/jointTop","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/tip"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/calculateSizeToImageShorterSideRatio(imageSize:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/init(jointTop:tip:jointBottom:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/isEqual(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/mirrored()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition\/rebased(parentRectangle:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Finger detection output","generated":true,"anchor":"Finger-detection-output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFGDetectionPosition","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"jointTop","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1jointTop\/title"},{"op":"replace","value":[{"text":"jointTop","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1jointTop\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1isEqual(_:)\/fragments"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1rebased(parentRectangle:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1rebased(parentRectangle:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1mirrored()\/title","value":"mirrored"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1mirrored()\/fragments"},{"op":"replace","value":"initWithJointTop:tip:jointBottom:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1init(jointTop:tip:jointBottom:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithJointTop:tip:jointBottom:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1init(jointTop:tip:jointBottom:)\/fragments"},{"value":"calculateSizeToImageShorterSideRatioWithImageSize:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1calculateSizeToImageShorterSideRatio(imageSize:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateSizeToImageShorterSideRatioWithImageSize:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1calculateSizeToImageShorterSideRatio(imageSize:)\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1hash\/fragments"},{"op":"replace","value":"DOTFGFingerType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title"},{"op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","op":"replace"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1description\/fragments"},{"value":"tip","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1tip\/title"},{"value":[{"kind":"identifier","text":"tip"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1tip\/fragments"},{"value":"jointBottom","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1jointBottom\/title"},{"value":[{"kind":"identifier","text":"jointBottom"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition~1jointBottom\/fragments"},{"op":"replace","value":"DOTFGDetectionPosition","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"DOTFGFingerQuality","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerQuality"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerQuality"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/navigatorTitle"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]}]}]}