{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","title":"DotDocumentBarcodeModuleConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration":{"role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration/init":{"role":"symbol","title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration\/init","kind":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentBarcodeModuleConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration\/init"]}],"op":"add","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentBarcodeModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}]}]}