{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","externalID":"c:@M@DotCore@E@DotDocumentModuleId","symbolKind":"enum"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}]}]}],"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/barcode"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/equatable-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/Equatable-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId":{"type":"topic","title":"DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid","abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/init(rawValue:)":{"type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/init(rawvalue:)","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/barcode":{"title":"DotDocumentModuleId.barcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/barcode","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/barcode"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/RawRepresentable-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentModuleId/description":{"url":"\/documentation\/dotfingerscore\/dotdocumentmoduleid\/description","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentModuleId","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentModuleId\/barcode"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId\/navigatorTitle"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId~1barcode\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentModuleId~1barcode\/fragments"}]}]}