{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfigurationbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Face detection balanced module.","type":"text"}],"metadata":{"title":"DotFaceDetectionModuleConfigurationBalanced","navigatorTitle":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationBalanced","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"}]}],"kind":"declarations"}],"topicSections":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfigurationBalanced\/init"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfigurationBalanced"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Face detection module configuration."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfigurationBalanced":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfigurationBalanced","type":"topic","fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"title":"DotFaceDetectionModuleConfigurationBalanced","url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfigurationbalanced","kind":"symbol","abstract":[{"type":"text","text":"Face detection balanced module."}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfigurationBalanced/init":{"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfigurationbalanced\/init","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfigurationBalanced\/init"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}