{"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"title":"DotFaceVerificationModuleConfiguration","externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"abstract":[{"type":"text","text":"Face verification module."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceVerificationModuleConfiguration":{"title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face verification module."}],"url":"\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceVerificationModuleConfiguration/init":{"url":"\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration\/init","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration\/init"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":[{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration\/init"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/title","op":"replace","value":"DotFaceVerificationModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}