{"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotlibraryid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotlibraryid"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Enumeration","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","externalID":"c:@M@DotCore@E@DotLibraryId","symbolKind":"enum"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"sections":[],"kind":"symbol","topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/document","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/face","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/faceLite","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/fingers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/nfc","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/palm"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/faceLite":{"type":"topic","kind":"symbol","title":"DotLibraryId.faceLite","url":"\/documentation\/dotfingerscore\/dotlibraryid\/facelite","abstract":[{"type":"codeVoice","code":"DotFaceLiteLibrary"},{"type":"text","text":" identifier."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceLite","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/faceLite"},"doc://DotFingersCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId":{"kind":"symbol","title":"DotLibraryId","url":"\/documentation\/dotfingerscore\/dotlibraryid","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/nfc":{"type":"topic","kind":"symbol","title":"DotLibraryId.nfc","url":"\/documentation\/dotfingerscore\/dotlibraryid\/nfc","abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/nfc"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/document":{"title":"DotLibraryId.document","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdDocument","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotDocumentLibrary"},{"type":"text","text":" identifier."}],"url":"\/documentation\/dotfingerscore\/dotlibraryid\/document","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/document"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/fingers":{"type":"topic","kind":"symbol","title":"DotLibraryId.fingers","url":"\/documentation\/dotfingerscore\/dotlibraryid\/fingers","abstract":[{"type":"codeVoice","code":"DotFingersLibrary"},{"type":"text","text":" identifier."}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingers","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdFingers","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/fingers"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/description":{"type":"topic","kind":"symbol","title":"description","url":"\/documentation\/dotfingerscore\/dotlibraryid\/description","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/description"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/RawRepresentable-Implementations":{"type":"topic","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/dotfingerscore\/dotlibraryid\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/RawRepresentable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/face":{"abstract":[{"code":"DotFaceLibrary","type":"codeVoice"},{"type":"text","text":" identifier."}],"url":"\/documentation\/dotfingerscore\/dotlibraryid\/face","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdFace"}],"title":"DotLibraryId.face","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/face"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/palm":{"type":"topic","kind":"symbol","title":"DotLibraryId.palm","url":"\/documentation\/dotfingerscore\/dotlibraryid\/palm","abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/palm"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/Equatable-Implementations":{"type":"topic","kind":"article","title":"Equatable Implementations","url":"\/documentation\/dotfingerscore\/dotlibraryid\/equatable-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/Equatable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/DotLibraryId/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotfingerscore\/dotlibraryid\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/init(rawValue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/document","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/face","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/faceLite","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/fingers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/nfc","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotLibraryId\/palm"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1faceLite\/title","value":"DotLibraryIdFaceLite"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1faceLite\/fragments","value":[{"text":"DotLibraryIdFaceLite","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId\/navigatorTitle","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1nfc\/title","value":"DotLibraryIdNfc"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1nfc\/fragments","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1document\/title","value":"DotLibraryIdDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1document\/fragments","value":[{"text":"DotLibraryIdDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1fingers\/title","value":"DotLibraryIdFingers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1fingers\/fragments","value":[{"text":"DotLibraryIdFingers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1face\/title","value":"DotLibraryIdFace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1face\/fragments","value":[{"text":"DotLibraryIdFace","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1palm\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotLibraryId~1palm\/fragments","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}