{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotpalmmoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotpalmmoduleid"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@E@DotPalmModuleId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmModuleId"}],"title":"DotPalmModuleId","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleId"}],"symbolKind":"enum","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"}]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/detection"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/description"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/init(rawValue:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/description":{"role":"symbol","title":"description","url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/description","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/description","kind":"symbol"},"doc://DotFingersCore/SY":{"identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId":{"role":"symbol","title":"DotPalmModuleId","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid","abstract":[{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" feature module identifier."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/detection":{"role":"symbol","title":"DotPalmModuleId.detection","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}],"url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/detection","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detection"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/detection","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/rawrepresentable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/RawRepresentable-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmModuleId/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","url":"\/documentation\/dotfingerscore\/dotpalmmoduleid\/equatable-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/Equatable-Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmModuleId\/detection"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModuleId"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId~1detection\/title","value":"DotPalmModuleIdDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmModuleId~1detection\/fragments","value":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}