{"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFingersEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/licenseBytes"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"sections":[],"metadata":{"title":"DotSdkLicenseProxyProtocol","roleHeading":"Protocol","symbolKind":"protocol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/licenseBytes":{"title":"licenseBytes","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/licensebytes","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/licenseBytes"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"required":true,"title":"isFaceEyeGazeLivenessScoreEnabled","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isPalmEnabled":{"title":"isPalmEnabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isPalmEnabled","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/ispalmenabled","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFaceEnabled":{"title":"isFaceEnabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceenabled","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"title":"isFacePassiveLivenessEnabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"title":"isFaceLiteEnabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfaceliteenabled","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol","title":"DotSdkLicenseProxyProtocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"title":"isDocumentEnabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDocumentEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isdocumentenabled","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"title":"isFaceMatchingEnabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfacematchingenabled","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"role":"symbol","title":"isRealTimeTransactionReportingEnabled","navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isRealTimeAnalyticsReportingEnabled":{"role":"symbol","title":"isRealTimeAnalyticsReportingEnabled","navigatorTitle":[{"kind":"identifier","text":"isRealTimeAnalyticsReportingEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isrealtimeanalyticsreportingenabled","abstract":[],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRealTimeAnalyticsReportingEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isNfcEnabled":{"role":"symbol","title":"isNfcEnabled","navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isnfcenabled","abstract":[],"required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isFingersEnabled":{"role":"symbol","title":"isFingersEnabled","navigatorTitle":[{"kind":"identifier","text":"isFingersEnabled"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isfingersenabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFingersEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFingersEnabled","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkLicenseProxyProtocol/isEvaluation":{"role":"symbol","title":"isEvaluation","navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdklicenseproxyprotocol\/isevaluation","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isEvaluation","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isFingersEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeAnalyticsReportingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"licenseBytes","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/title"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments"},{"value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceEyeGazeLivenessScoreEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments"},{"value":"isPalmEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title"},{"value":[{"kind":"identifier","text":"isPalmEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments"},{"value":"isFaceEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments"},{"value":"isFacePassiveLivenessEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title"},{"value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments"},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceLiteEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/fragments"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"},{"value":"isDocumentEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title"},{"value":[{"kind":"identifier","text":"isDocumentEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments"},{"value":"isFaceMatchingEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title"},{"value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"},{"value":"isRealTimeTransactionReportingEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title"},{"value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments"},{"value":"isRealTimeAnalyticsReportingEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isRealTimeAnalyticsReportingEnabled\/title"},{"value":[{"kind":"identifier","text":"isRealTimeAnalyticsReportingEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isRealTimeAnalyticsReportingEnabled\/fragments"},{"value":"isNfcEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title"},{"value":[{"kind":"identifier","text":"isNfcEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments"},{"value":"isFingersEnabled","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/title"},{"value":[{"kind":"identifier","text":"isFingersEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/fragments"},{"value":"isEvaluation","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/title"},{"value":[{"kind":"identifier","text":"isEvaluation"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments"}]}]}