{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotsdk"]}],"topicSections":[{"title":"Classes","anchor":"Classes","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/bundleId","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isInitialized","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/versionName"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/deinitialize()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isLibraryActive(libraryId:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/shared"]},{"title":"Enumerations","anchor":"Enumerations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error"]}],"metadata":{"title":"DotSdk","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DotSdk","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFingers","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/versionName":{"title":"versionName","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/versionname","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"versionName"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"versionName"}],"type":"topic","abstract":[{"code":"DotSdk","type":"codeVoice"},{"text":" version.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/versionName"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/error","kind":"symbol","abstract":[]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/initialize(configuration:)":{"title":"initialize(configuration:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/initialize(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:7DotCore0A3SdkC13ConfigurationC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"type":"topic","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/initialize(configuration:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Configuration":{"role":"symbol","title":"DotSdk.Configuration","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/configuration","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Configuration","kind":"symbol"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":"."}]},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/deinitialize()":{"title":"deinitialize()","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"type":"topic","abstract":[{"type":"text","text":"Deinitialize "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/deinitialize()"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/shared":{"title":"shared","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/shared","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotSdk","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdk"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"shared"}],"type":"topic","abstract":[{"type":"text","text":"Shared singleton instance."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/shared"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/isLibraryActive(libraryId:)":{"title":"isLibraryActive(libraryId:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/islibraryactive(libraryid:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLibraryActive"},{"kind":"text","text":"("},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"type":"topic","abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isLibraryActive(libraryId:)"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/isInitialized":{"role":"symbol","title":"isInitialized","navigatorTitle":[{"kind":"identifier","text":"isInitialized"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/isinitialized","abstract":[{"type":"text","text":"Flag to determine if "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" is initialized."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isInitialized","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/bundleId":{"title":"bundleId","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bundleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"bundleId"}],"abstract":[{"type":"text","text":"Application Bundle ID."}],"url":"\/documentation\/dotfingerscore\/dotsdk\/bundleid","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/bundleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotSdk","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/bundleId","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isInitialized","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/versionName"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/deinitialize()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/initialize(configuration:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/isLibraryActive(libraryId:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/shared"],"anchor":"Type-Properties","title":"Type Properties"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"versionName","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1versionName\/title"},{"op":"replace","value":[{"kind":"identifier","text":"versionName"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1versionName\/fragments"},{"op":"replace","value":"initializeWithConfiguration:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1initialize(configuration:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1initialize(configuration:)\/fragments"},{"op":"replace","value":"DotSdk","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdk"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1deinitialize()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1deinitialize()\/fragments"},{"op":"replace","value":"shared","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1shared\/title"},{"op":"replace","value":[{"kind":"identifier","text":"shared"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1shared\/fragments"},{"op":"replace","value":"isLibraryActiveWithLibraryId:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1isLibraryActive(libraryId:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1isLibraryActive(libraryId:)\/fragments"},{"op":"replace","value":"isInitialized","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1isInitialized\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isInitialized"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1isInitialized\/fragments"},{"op":"replace","value":"bundleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1bundleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"bundleId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk~1bundleId\/fragments"}]}]}