{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingertype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingertype"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"]},{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/ring"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/init(rawValue:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/description"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/RawRepresentable-Implementations"],"generated":true}],"metadata":{"symbolKind":"enum","roleHeading":"Enumeration","externalID":"c:@M@DotFingersCore@E@DOTFGFingerType","role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Type of detected finger."}],"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/s12CaseIterableP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"kind":"relationships"}],"seeAlsoSections":[{"anchor":"Finger-detection-output","title":"Finger detection output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"],"generated":true}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingerType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType/index":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/index","title":"FingerType.index","url":"\/documentation\/dotfingerscore\/fingertype\/index","abstract":[{"text":"Index finger.","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"index","kind":"identifier"}],"navigatorTitle":[{"text":"DOTFGFingerTypeIndex","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/description":{"kind":"symbol","title":"description","url":"\/documentation\/dotfingerscore\/fingertype\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/description"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Wrapped":{"type":"topic","kind":"symbol","title":"FingerType.Wrapped","url":"\/documentation\/dotfingerscore\/fingertype\/wrapped","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Wrapped"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/little":{"title":"FingerType.little","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingertype\/little","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTFGFingerTypeLittle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Little finger."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/little"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/middle":{"title":"FingerType.middle","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingertype\/middle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTFGFingerTypeMiddle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Middle finger."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/middle"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality":{"title":"FingerQuality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerQuality"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}],"abstract":[{"text":"Finger quality.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingerquality","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/init(rawValue:)":{"type":"topic","kind":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotfingerscore\/fingertype\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/init(rawValue:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/fingertype\/equatable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/Equatable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/s12CaseIterableP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s12CaseIterableP","title":"Swift.CaseIterable"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/fingertype\/rawrepresentable-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/RawRepresentable-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/ring":{"role":"symbol","title":"FingerType.ring","navigatorTitle":[{"kind":"identifier","text":"DOTFGFingerTypeRing"}],"abstract":[{"text":"Ring finger.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingertype\/ring","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ring"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/ring","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFGFingerType","op":"replace","path":"\/metadata\/title"},{"value":"enum","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/ring"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Finger detection output","anchor":"Finger-detection-output","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingerType"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGFingerTypeIndex","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1index\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeIndex"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1index\/fragments"},{"value":"DOTFGDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"},{"value":"DOTFGFingerTypeLittle","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1little\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeLittle"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1little\/fragments"},{"value":"DOTFGFingerTypeMiddle","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1middle\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeMiddle"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1middle\/fragments"},{"value":"DOTFGFingerType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"},{"value":"DOTFGFingerQuality","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/navigatorTitle"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"},{"value":"DOTFGFingerTypeRing","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1ring\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeRing"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1ring\/fragments"}]}]}