{"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/init(imageQuality:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/imageQuality"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingerQuality) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerQuality","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Finger quality."}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingerquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingerquality"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"],"title":"Finger detection output","anchor":"Finger-detection-output","generated":true}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"sections":[],"metadata":{"roleHeading":"Class","title":"FingerQuality","symbolKind":"class","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerQuality","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/imageQuality":{"title":"imageQuality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerImageQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality"}],"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"abstract":[{"type":"text","text":"Image quality."}],"url":"\/documentation\/dotfingerscore\/fingerquality\/imagequality","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/imageQuality"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/hash":{"title":"hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/fingerquality\/hash","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/hash"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/Finger":{"role":"symbol","title":"FingerDetector.Finger","navigatorTitle":[{"kind":"identifier","text":"Finger"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/finger","abstract":[{"type":"text","text":"Result of the finger detection process."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Finger"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/Finger","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/isEqual(_:)":{"abstract":[],"url":"\/documentation\/dotfingerscore\/fingerquality\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"title":"isEqual(_:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/isEqual(_:)"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/init(imageQuality:)":{"title":"init(imageQuality:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"imageQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality","text":"FingerImageQuality","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithImageQuality:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/fingerquality\/init(imagequality:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/init(imageQuality:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality/description":{"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/fingerquality\/description","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/description"},"doc://DotFingersCore/documentation/DotFingersCore/FingerQuality":{"title":"FingerQuality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerQuality"}],"navigatorTitle":[{"text":"FingerQuality","kind":"identifier"}],"abstract":[{"text":"Finger quality.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingerquality","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGFingerQuality","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFGFingerQuality","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingerQuality","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/imageQuality"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/init(imageQuality:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerQuality\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"],"generated":true,"title":"Finger detection output","anchor":"Finger-detection-output"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingerQuality","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"imageQuality","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1imageQuality\/title"},{"op":"replace","value":[{"text":"imageQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1imageQuality\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1hash\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1isEqual(_:)\/fragments"},{"op":"replace","value":"DOTFGFingerType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title"},{"op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"},{"op":"replace","value":"initWithImageQuality:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1init(imageQuality:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithImageQuality:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1init(imageQuality:)\/fragments"},{"op":"replace","value":"DOTFGDetectionPosition","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"op":"replace","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"op":"replace","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality~1description\/fragments"},{"op":"replace","value":"DOTFGFingerQuality","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/title"},{"op":"replace","value":[{"text":"DOTFGFingerQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingerQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerQuality\/navigatorTitle"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}