{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"topicSections":[{"anchor":"Style-and-configuration","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"],"title":"Style and configuration"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate"],"title":"Delegate","anchor":"Delegate"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition"],"title":"Fingers auto capture result","anchor":"Fingers-auto-capture-result"},{"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/init(configuration:style:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/style-swift.property"],"title":"Instance Properties","generated":true}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureViewController","role":"symbol","title":"FingersAutoCaptureViewController","navigatorTitle":[{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewController"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"UI Fingers Auto Capture component.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSCoding","doc:\/\/DotFingersCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/s8SendableP","doc:\/\/DotFingersCore\/s16SendableMetatypeP","doc:\/\/DotFingersCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFingersCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFingersCore\/objc(pl)UIContentContainer","doc:\/\/DotFingersCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFingersCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFingersCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFingersCore\/objc(pl)UIStateRestoring","doc:\/\/DotFingersCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFingersCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFingersCore\/objc(pl)UIUserActivityRestoring"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFGFingersAutoCaptureViewController) ","kind":"text"},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewController"}]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A visual component for capturing good quality finger images. This component provides a UI."},{"type":"text","text":" "},{"type":"text","text":"It includes a placeholder for the fingers, a detection layer that displays the tracking rectangle and an instruction."}]},{"inlineContent":[{"text":"This component requires the ","type":"text"},{"code":"DotFingersDetection","type":"codeVoice"},{"text":" module to be active.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"role":"symbol","title":"FingersAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the fingers auto capture process."}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","kind":"symbol"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIFocusEnvironment"},"doc://DotFingersCore/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Configuration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the UI Fingers Auto Capture component."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Configuration-swift.class"},"doc://DotFingersCore/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/objc(pl)UIStateRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIStateRestoring","title":"UIKit.UIStateRestoring"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/init(configuration:style:)":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"code":"FingersAutoCaptureViewController","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"title":"init(configuration:style:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/init(configuration:style:)"},"doc://DotFingersCore/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIPasteConfigurationSupporting","title":"UIKit.UIPasteConfigurationSupporting"},"doc://DotFingersCore/s16SendableMetatypeP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"role":"symbol","title":"FingersAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/Style-swift.class":{"role":"symbol","title":"FingersAutoCaptureViewController.Style","navigatorTitle":[{"kind":"identifier","text":"Style"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the fingers auto capture user interface.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/Style-swift.class","kind":"symbol"},"doc://DotFingersCore/objc(pl)UIContentContainer":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIContentContainer","title":"UIKit.UIContentContainer"},"doc://DotFingersCore/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/configuration-swift.property":{"role":"symbol","title":"configuration","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/configuration-swift.property","abstract":[{"text":"Current configuration.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/configuration-swift.property","kind":"symbol"},"doc://DotFingersCore/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s8SendableP","title":"Swift.Sendable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController/style-swift.property":{"type":"topic","kind":"symbol","title":"style","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller\/style-swift.property","abstract":[{"type":"text","text":"Current style."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B25AutoCaptureViewControllerC5StyleC"}],"navigatorTitle":[{"text":"style","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/style-swift.property"},"doc://DotFingersCore/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"kind":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}]},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","type":"topic","title":"FingersAutoCaptureViewController","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewController"}],"kind":"symbol"},"doc://DotFingersCore/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions"},"doc://DotFingersCore/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTFGFingersAutoCaptureViewController","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate"],"title":"Delegate","anchor":"Delegate"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition"],"title":"Fingers auto capture result","anchor":"Fingers-auto-capture-result"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/style-swift.property"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController\/init(configuration:style:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"DOTFGBaseFingersAutoCaptureViewController"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","value":"DOTFGBaseFingersAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","value":"DOTFGDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1init(configuration:style:)\/title","value":"initWithConfiguration:style:","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:style:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title","value":"DOTFGFingersAutoCaptureViewControllerDelegate","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1style-swift.property\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","value":"DOTFGFingersAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title","value":"DOTFGFingersAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"op":"replace"}]}]}