{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingersAutoCaptureQualityAttributeThresholds) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Fingers-swift.class","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Presets"],"title":"Classes","anchor":"Classes","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/fingers-swift.property","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minFingerCount","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/sizeInterval"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"metadata":{"title":"FingersAutoCaptureQualityAttributeThresholds","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds","roleHeading":"Class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"symbolKind":"class","modules":[{"name":"DotFingersCore"}]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/minConfidence":{"kind":"symbol","title":"minConfidence","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/minconfidence","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidence","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"minConfidence","kind":"identifier"}],"type":"topic","abstract":[{"text":"Minimal valid confidence of the detected fingers.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low confidence.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high confidence.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minConfidence"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/sizeInterval":{"kind":"symbol","title":"sizeInterval","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/sizeinterval","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"sizeInterval","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Valid fingers size interval."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/sizeInterval"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Fingers-swift.class":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds.Fingers","navigatorTitle":[{"kind":"identifier","text":"Fingers"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.class","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Fingers-swift.class","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/isEqual(_:)":{"kind":"symbol","title":"isEqual(_:)","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/isEqual(_:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/description":{"title":"description","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/description"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Finger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Finger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Finger","kind":"identifier"}],"title":"FingersAutoCaptureQualityAttributeThresholds.Finger","navigatorTitle":[{"text":"Finger","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/finger","kind":"symbol","abstract":[]},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds":{"role":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the fingers auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Builder":{"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/builder","abstract":[{"text":"Builder for ","type":"text"},{"code":"FingersAutoCaptureQualityAttributeThresholds","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Builder","kind":"identifier"}],"navigatorTitle":[{"text":"Builder","kind":"identifier"}],"title":"FingersAutoCaptureQualityAttributeThresholds.Builder","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Builder"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/fingers-swift.property":{"abstract":[{"text":"Minimal valid sharpness of the detected fingers.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents blurry fingers.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents sharp fingers.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/fingers-swift.property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14DotFingersCore0B37AutoCaptureQualityAttributeThresholdsC0B0C","kind":"typeIdentifier","text":"Fingers"}],"navigatorTitle":[{"kind":"identifier","text":"fingers"}],"title":"fingers","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/fingers-swift.property"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/hash":{"kind":"symbol","title":"hash","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/hash"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/Presets":{"kind":"symbol","title":"FingersAutoCaptureQualityAttributeThresholds.Presets","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/presets","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Presets","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Presets","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the fingers auto capture result."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/Presets"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureQualityAttributeThresholds/minFingerCount":{"kind":"symbol","title":"minFingerCount","url":"\/documentation\/dotfingerscore\/fingersautocapturequalityattributethresholds\/minfingercount","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minFingerCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","navigatorTitle":[{"text":"minFingerCount","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Minimal valid count of detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minFingerCount"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingersAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/fingers-swift.property","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/minFingerCount","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/sizeInterval"]},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"anchor":"Instance-Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"minConfidence","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1minConfidence\/title"},{"op":"replace","value":[{"kind":"identifier","text":"minConfidence"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1minConfidence\/fragments"},{"value":"sizeInterval","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1sizeInterval\/title"},{"value":[{"kind":"identifier","text":"sizeInterval"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1sizeInterval\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1description\/fragments"},{"value":"DOTFGFingersAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"op":"replace","value":"fingers","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1fingers-swift.property\/title"},{"value":[{"kind":"identifier","text":"fingers"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1fingers-swift.property\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1hash\/fragments"},{"value":"minFingerCount","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1minFingerCount\/title"},{"value":[{"kind":"identifier","text":"minFingerCount"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureQualityAttributeThresholds~1minFingerCount\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}