{"abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"seeAlsoSections":[{"anchor":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"title":"Validators","generated":true}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersOutOfBoundsValidator","role":"symbol","title":"FingersOutOfBoundsValidator","navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"sections":[],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minConfidenceThreshold","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingersOutOfBoundsValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"role":"symbol","title":"FingerCountTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountTooLowValidator"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/identifier":{"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/identifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/identifier","title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/minConfidenceThreshold":{"abstract":[{"type":"text","text":"Minimum detection confidence threshold."}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/minconfidencethreshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"minConfidenceThreshold"}],"title":"minConfidenceThreshold","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minConfidenceThreshold"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"title":"FingersAutoCaptureFrameParametersValidator","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"type":"topic","title":"FingersOutOfBoundsValidator","navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersOutOfBoundsValidator"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"role":"symbol"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"abstract":[{"type":"text","text":"Default threshold."}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected fingers is too large."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"role":"symbol","title":"FingersNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"FingersNotDetectedValidator"}],"abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersNotDetectedValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/dependencyIdentifiers":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/dependencyIdentifiers","type":"topic","title":"dependencyIdentifiers","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/dependencyidentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","title":"init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:minconfidencethreshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/minCornerDistanceToImageShorterSideRatioThreshold":{"title":"minCornerDistanceToImageShorterSideRatioThreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"abstract":[{"type":"text","text":"Current minimal distance between detected finger corner and image edge to image shorter side ratio threshold."}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/validate(fingersAutoCaptureFrameParameters:)":{"title":"validate(fingersAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"abstract":[{"text":"Validate if the detected fingers are within the bounds of the image.","type":"text"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/validate(fingersautocaptureframeparameters:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/validate(fingersAutoCaptureFrameParameters:)"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator/init()":{"title":"init()","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init()"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountNotFourValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountNotFourValidator"}],"title":"FingerCountNotFourValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountNotFourValidator"}],"url":"\/documentation\/dotfingerscore\/fingercountnotfourvalidator","kind":"symbol","abstract":[{"type":"text","text":"Validate whether the count of detected fingers is four."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTFGFingersOutOfBoundsValidator","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minConfidenceThreshold","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"],"generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Validators","anchor":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"]}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","op":"replace","value":"DOTFGFingerCountTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","value":"DOTFGSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minConfidenceThreshold\/title","value":"minConfidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minConfidenceThreshold\/fragments","value":[{"text":"minConfidenceThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","value":"DOTFGSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"value":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace"},{"value":"DOTFGSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersNotDetectedValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","op":"replace"},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1dependencyIdentifiers\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)\/title","op":"replace","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:minConfidenceThreshold:error:"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/title","op":"replace","value":"minCornerDistanceToImageShorterSideRatioThreshold"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/fragments","op":"replace","value":[{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","value":"validateWithFingersAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/title","op":"replace","value":"DOTFGFingerCountNotFourValidator"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerCountNotFourValidator"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTFGFingerCountNotFourValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}