{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"metadata":{"title":"ImageSize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize","symbolKind":"class","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"roleHeading":"Class","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/init(width:height:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/cgSize","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/height","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/longerSide","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/shorterSide","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/width"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/isEqual(_:)"],"generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/from(cgSize:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTImageSize) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/imagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/imagesize"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Image size in pixels."}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/hash":{"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/imagesize\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/hash","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/longerSide":{"role":"symbol","title":"longerSide","navigatorTitle":[{"text":"longerSide","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/imagesize\/longerside","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"longerSide"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/longerSide","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/from(cgSize:)":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/from(cgSize:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}],"title":"from(cgSize:)","navigatorTitle":[{"kind":"identifier","text":"fromCgSize:"}],"url":"\/documentation\/dotfingerscore\/imagesize\/from(cgsize:)","kind":"symbol","abstract":[]},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagesize\/isequal(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/isEqual(_:)","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/height":{"role":"symbol","title":"height","type":"topic","abstract":[{"type":"text","text":"Image height in pixels."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"height","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagesize\/height","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/height"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/description":{"role":"symbol","title":"description","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfingerscore\/imagesize\/description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/description"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotfingerscore\/imagesize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}]},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/calculatePixelCount()":{"role":"symbol","title":"calculatePixelCount()","navigatorTitle":[{"text":"calculatePixelCount","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagesize\/calculatepixelcount()","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculatePixelCount()","kind":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/calculateWidthToHeightRatio()":{"title":"calculateWidthToHeightRatio()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"url":"\/documentation\/dotfingerscore\/imagesize\/calculatewidthtoheightratio()","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculateWidthToHeightRatio()"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/cgSize":{"role":"symbol","title":"cgSize","navigatorTitle":[{"kind":"identifier","text":"cgSize"}],"url":"\/documentation\/dotfingerscore\/imagesize\/cgsize","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/cgSize","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/init(width:height:)":{"role":"symbol","title":"init(width:height:)","navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:"}],"url":"\/documentation\/dotfingerscore\/imagesize\/init(width:height:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"height"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/init(width:height:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/shorterSide":{"role":"symbol","title":"shorterSide","navigatorTitle":[{"kind":"identifier","text":"shorterSide"}],"url":"\/documentation\/dotfingerscore\/imagesize\/shorterside","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shorterSide"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/shorterSide","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/width":{"role":"symbol","title":"width","navigatorTitle":[{"text":"width","kind":"identifier"}],"abstract":[{"type":"text","text":"Image width in pixels."}],"url":"\/documentation\/dotfingerscore\/imagesize\/width","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/width","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/cgSize","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/height","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/longerSide","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/shorterSide","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/width"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculatePixelCount()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/init(width:height:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/isEqual(_:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/from(cgSize:)"],"title":"Type Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageSize","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1longerSide\/title","value":"longerSide"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1longerSide\/fragments","value":[{"kind":"identifier","text":"longerSide"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1from(cgSize:)\/title","value":"fromCgSize:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1from(cgSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1height\/title","value":"height"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1height\/fragments","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculatePixelCount()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculatePixelCount"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculateWidthToHeightRatio()\/title","value":"calculateWidthToHeightRatio"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculateWidthToHeightRatio()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1cgSize\/title","value":"cgSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1cgSize\/fragments","value":[{"kind":"identifier","text":"cgSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1init(width:height:)\/title","value":"initWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1init(width:height:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithWidth:height:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1shorterSide\/title","value":"shorterSide"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1shorterSide\/fragments","value":[{"text":"shorterSide","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1width\/title","value":"width"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1width\/fragments","value":[{"text":"width","kind":"identifier"}]}]}]}