{"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"],"title":"Converting images","anchor":"Converting-images","generated":true}],"variants":[{"paths":["\/documentation\/dotfingerscore\/imagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/imagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"ImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory","symbolKind":"class","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"topicSections":[{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"],"generated":true}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}]}]}],"references":{"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory/createBgrRawImage(cgImage:)":{"title":"createBgrRawImage(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"url":"\/documentation\/dotfingerscore\/imagefactory\/createbgrrawimage(cgimage:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(cgImage:)"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory/createBgraRawImage(cgImage:)":{"role":"symbol","title":"createBgraRawImage(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"url":"\/documentation\/dotfingerscore\/imagefactory\/createbgrarawimage(cgimage:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(cgImage:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CGImageFactory":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"title":"CGImageFactory","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"url":"\/documentation\/dotfingerscore\/cgimagefactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory/createBgraRawImage(bgrRawImage:)":{"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"text":" object with ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"type":"text","text":" format as an "},{"code":"Image","type":"codeVoice"},{"text":" object with ","type":"text"},{"code":".rawBgra","type":"codeVoice"},{"text":" format.","type":"text"}],"url":"\/documentation\/dotfingerscore\/imagefactory\/createbgrarawimage(bgrrawimage:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"title":"createBgraRawImage(bgrRawImage:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory":{"role":"symbol","title":"ImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/CIImageFactory":{"role":"symbol","title":"CIImageFactory","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfingerscore\/ciimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgrRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"title":"createBgrRawImage(ciImage:ciContext:)","navigatorTitle":[{"text":"createBgrRawImageWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/imagefactory\/createbgrrawimage(ciimage:cicontext:)","kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}]},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"title":"createBgraRawImage(ciImage:ciContext:)","kind":"symbol","url":"\/documentation\/dotfingerscore\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as an "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTImageFactory","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Type Methods","anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Converting images","anchor":"Converting-images","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFactory"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createBgrRawImageWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgrRawImage(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments"},{"value":"createBgraRawImageWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCgImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/navigatorTitle"},{"value":"createBgraRawImageWithBgrRawImage:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments"},{"value":"DOTImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/navigatorTitle"},{"value":"DOTCIImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/fragments"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/navigatorTitle"},{"value":"createBgrRawImageWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle"},{"value":"createBgraRawImageWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments"}]}]}