{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/localization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/localization"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"topicSections":[{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/bundle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/localizationDictionary","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/useLocalizationDictionary"],"generated":true}],"metadata":{"symbolKind":"class","roleHeading":"Class","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLocalization","role":"symbol","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"kind":"relationships"}],"seeAlsoSections":[{"anchor":"Global-components","title":"Global components","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGLocalization) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGLocalization/init":{"title":"init","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotfglocalization\/init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGLocalization\/init"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/Logger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"title":"Logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/logger","kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/Localization/useLocalizationDictionary":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/useLocalizationDictionary","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"useLocalizationDictionary","navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"url":"\/documentation\/dotfingerscore\/localization\/uselocalizationdictionary","kind":"symbol","abstract":[{"text":"If you set this to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":", ","type":"text"},{"type":"codeVoice","code":"localizationDictionary"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}]},"doc://DotFingersCore/documentation/DotFingersCore/Localization/bundle":{"title":"bundle","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bundle","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"navigatorTitle":[{"kind":"identifier","text":"bundle"}],"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"code":"Bundle.main","type":"codeVoice"},{"text":".","type":"text"}],"url":"\/documentation\/dotfingerscore\/localization\/bundle","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/bundle"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/Localization/localizationDictionary":{"type":"topic","title":"localizationDictionary","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/localizationDictionary","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}],"url":"\/documentation\/dotfingerscore\/localization\/localizationdictionary","abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"role":"symbol"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Localization":{"type":"topic","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfingerscore\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"role":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGLocalization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFGLocalization"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGLocalization"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGLocalization\/init"],"title":"Instance Methods","generated":true},{"anchor":"Type-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/bundle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/localizationDictionary","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/useLocalizationDictionary"],"title":"Type Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Global-components","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger"],"title":"Global components","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGLocalization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/title","value":"DOTFGLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTFGLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1useLocalizationDictionary\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1bundle\/title","value":"bundle"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1bundle\/fragments","value":[{"kind":"identifier","text":"bundle"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1localizationDictionary\/fragments","value":[{"kind":"identifier","text":"localizationDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/title","value":"DOTFGLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTFGLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGLocalization"}]}]}]}