{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Available log levels.","type":"text"}],"metadata":{"title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel","symbolKind":"enum","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTLoggerLogLevel) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/debug","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/error","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/info","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/none","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/warning"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/error":{"role":"symbol","title":"LoggerLogLevel.error","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/error","kind":"symbol"},"doc://DotFingersCore/SY":{"identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/none":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/none","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"none","kind":"identifier"}],"title":"LoggerLogLevel.none","navigatorTitle":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/none","kind":"symbol","abstract":[{"type":"text","text":"Disables logging."}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/debug":{"role":"symbol","title":"LoggerLogLevel.debug","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/debug","abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/debug","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/info":{"role":"symbol","title":"LoggerLogLevel.info","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/info","abstract":[{"text":"Logs informative events.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/info","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotfingerscore\/loggerloglevel\/init(rawvalue:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/init(rawValue:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/warning":{"role":"symbol","title":"LoggerLogLevel.warning","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/warning","kind":"symbol"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/description":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description","url":"\/documentation\/dotfingerscore\/loggerloglevel\/description","kind":"symbol","abstract":[]},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/rawrepresentable-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/RawRepresentable-Implementations","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/equatable-implementations","type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/Equatable-Implementations","kind":"article"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTLoggerLogLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/debug","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/error","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/info","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/none","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/warning"],"generated":true}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTLoggerLogLevel","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1error\/fragments","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1none\/title","value":"DOTLoggerLogLevelNone","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1none\/fragments","value":[{"text":"DOTLoggerLogLevelNone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1debug\/title","value":"DOTLoggerLogLevelDebug","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1debug\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1info\/title","value":"DOTLoggerLogLevelInfo","op":"replace"},{"value":[{"text":"DOTLoggerLogLevelInfo","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1info\/fragments","op":"replace"},{"value":"DOTLoggerLogLevelWarning","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1warning\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1warning\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}