{"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/init(left:top:right:bottom:)"],"generated":true},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/bottom","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/cgRect","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/height","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/left","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/origin","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/right","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/top","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/width","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/widthToHeightRatio"],"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/isEqual(_:)"]},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/from(cgRect:)"],"anchor":"Type-Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTRectangleInt) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/rectangleint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/rectangleint"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"metadata":{"roleHeading":"Class","modules":[{"name":"DotFingersCore"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","symbolKind":"class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"url":"\/documentation\/dotfingerscore\/rectangleint","kind":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/description":{"url":"\/documentation\/dotfingerscore\/rectangleint\/description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/description","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/init(left:top:right:bottom:)":{"url":"\/documentation\/dotfingerscore\/rectangleint\/init(left:top:right:bottom:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/init(left:top:right:bottom:)","title":"init(left:top:right:bottom:)","navigatorTitle":[{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}],"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/right":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/right","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"right","navigatorTitle":[{"kind":"identifier","text":"right"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/right","kind":"symbol","abstract":[{"type":"text","text":"Right edge."}]},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/bottom":{"url":"\/documentation\/dotfingerscore\/rectangleint\/bottom","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/bottom","title":"bottom","navigatorTitle":[{"kind":"identifier","text":"bottom"}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"kind":"symbol","abstract":[{"type":"text","text":"Bottom edge."}]},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/left":{"type":"topic","title":"left","navigatorTitle":[{"kind":"identifier","text":"left"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/left","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/left","abstract":[{"type":"text","text":"Left edge."}],"role":"symbol"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/cgRect":{"type":"topic","title":"cgRect","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/cgRect","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/cgrect","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/top":{"type":"topic","title":"top","navigatorTitle":[{"text":"top","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/top","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/top","abstract":[{"type":"text","text":"Top edge."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/widthToHeightRatio":{"type":"topic","title":"widthToHeightRatio","navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/widthToHeightRatio","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/widthtoheightratio","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/origin":{"type":"topic","title":"origin","navigatorTitle":[{"kind":"identifier","text":"origin"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/origin","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","kind":"typeIdentifier","text":"PointInt"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/origin","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/width":{"type":"topic","title":"width","navigatorTitle":[{"kind":"identifier","text":"width"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/width","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/width","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/height":{"type":"topic","title":"height","navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/height","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/height","abstract":[],"role":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/isEqual(_:)":{"type":"topic","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/isEqual(_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/isequal(_:)","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/hash":{"type":"topic","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/hash","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfingerscore\/rectangleint\/hash","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleInt/from(cgRect:)":{"url":"\/documentation\/dotfingerscore\/rectangleint\/from(cgrect:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/from(cgRect:)","title":"from(cgRect:)","navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt"}],"kind":"symbol","abstract":[]},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTRectangleInt"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/bottom","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/cgRect","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/height","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/left","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/origin","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/right","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/top","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/width","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/widthToHeightRatio"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/isEqual(_:)"],"anchor":"Instance-Methods"},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleInt\/from(cgRect:)"],"anchor":"Type-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTRectangleInt"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/title","value":"DOTRectangleInt"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1init(left:top:right:bottom:)\/title","value":"initWithLeft:top:right:bottom:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1init(left:top:right:bottom:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1right\/title","value":"right"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1right\/fragments","value":[{"text":"right","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1bottom\/title","value":"bottom"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1bottom\/fragments","value":[{"text":"bottom","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1left\/title","value":"left"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1left\/fragments","value":[{"text":"left","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1cgRect\/title","value":"cgRect"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1cgRect\/fragments","value":[{"text":"cgRect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1top\/title","value":"top"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1top\/fragments","value":[{"kind":"identifier","text":"top"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1widthToHeightRatio\/title","value":"widthToHeightRatio"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1widthToHeightRatio\/fragments","value":[{"kind":"identifier","text":"widthToHeightRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1origin\/title","value":"origin"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1origin\/fragments","op":"replace","value":[{"kind":"identifier","text":"origin"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1width\/title","op":"replace","value":"width"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1width\/fragments","op":"replace","value":[{"kind":"identifier","text":"width"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1height\/title","op":"replace","value":"height"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1height\/fragments","op":"replace","value":[{"kind":"identifier","text":"height"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1isEqual(_:)\/title","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1from(cgRect:)\/title","op":"replace","value":"fromCgRect:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleInt~1from(cgRect:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}]}]}]}