{"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGSizeTooLargeValidator) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"platforms":["iOS"]}]}],"abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sizetoolargevalidator"]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"anchor":"Validators","title":"Validators"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"sections":[],"metadata":{"title":"SizeTooLargeValidator","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSizeTooLargeValidator","symbolKind":"class","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"roleHeading":"Class","role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/maxDetectionSizeToImageShorterSideRatioThreshold":{"title":"maxDetectionSizeToImageShorterSideRatioThreshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}],"abstract":[{"type":"text","text":"Current maximal detection size to image shorter side ratio threshold."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/validate(fingersAutoCaptureFrameParameters:)":{"title":"validate(fingersAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","text":"FingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"abstract":[{"type":"text","text":"Validate size of the detected fingers."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/validate(fingersautocaptureframeparameters:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/validate(fingersAutoCaptureFrameParameters:)"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/init(maxDetectionSizeToImageShorterSideRatioThreshold:)":{"title":"init(maxDetectionSizeToImageShorterSideRatioThreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/init(maxdetectionsizetoimageshortersideratiothreshold:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/identifier":{"title":"identifier","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/identifier","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/identifier"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"title":"FingersAutoCaptureFrameParametersValidator","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountNotFourValidator":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountNotFourValidator"}],"title":"FingerCountNotFourValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountNotFourValidator"}],"url":"\/documentation\/dotfingerscore\/fingercountnotfourvalidator","kind":"symbol","abstract":[{"type":"text","text":"Validate whether the count of detected fingers is four."}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/defaultMaxDetectionSizeToImageShorterSideRatioThreshold":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold","kind":"symbol","abstract":[{"type":"text","text":"Default threshold."}]},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"title":"SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected fingers is too large."}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"role":"symbol","title":"FingerCountTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"FingerCountTooLowValidator"}],"url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerCountTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","kind":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"type":"topic","title":"FingersOutOfBoundsValidator","navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersOutOfBoundsValidator"}],"url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/dependencyidentifiers","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/dependencyIdentifiers"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator/init()":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfingerscore\/sizetoolargevalidator\/init()","kind":"symbol","abstract":[{"type":"text","text":"Initialize with default threshold."}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"role":"symbol","title":"FingersNotDetectedValidator","navigatorTitle":[{"kind":"identifier","text":"FingersNotDetectedValidator"}],"abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersNotDetectedValidator"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGSizeTooLargeValidator","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}]},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"replace","value":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"anchor":"Validators"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"maxDetectionSizeToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/title"},{"value":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/fragments","op":"replace"},{"op":"replace","value":"validateWithFingersAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1validate(fingersAutoCaptureFrameParameters:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","op":"replace"},{"value":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/fragments","op":"replace"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1identifier\/title"},{"op":"replace","value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1identifier\/fragments"},{"value":"DOTFGFingersAutoCaptureFrameParametersValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle"},{"op":"replace","value":"DOTFGFingerCountNotFourValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/title"},{"op":"replace","value":[{"text":"DOTFGFingerCountNotFourValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingerCountNotFourValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/navigatorTitle"},{"op":"replace","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/title"},{"value":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/fragments","op":"replace"},{"value":"DOTFGSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerCountTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTFGSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments"},{"value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGSizeTooSmallValidator","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title"},{"value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments"},{"value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator~1init()\/fragments","op":"replace"},{"value":"DOTFGFingersNotDetectedValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle"}]}]}