{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/wrappeddouble"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/wrappeddouble"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"metadata":{"title":"WrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTWrappedDouble","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"roleHeading":"Class","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTWrappedDouble) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/init(value:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/value"],"anchor":"Instance-Properties"},{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/isEqual(_:)"],"anchor":"Instance-Methods"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappeddouble","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/init(value:)":{"role":"symbol","title":"init(value:)","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/wrappeddouble\/init(value:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/init(value:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/description":{"url":"\/documentation\/dotfingerscore\/wrappeddouble\/description","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/description"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/isEqual(_:)":{"role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotfingerscore\/wrappeddouble\/isequal(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/isEqual(_:)","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/value":{"abstract":[],"url":"\/documentation\/dotfingerscore\/wrappeddouble\/value","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"title":"value","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/value"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedDouble/hash":{"role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/wrappeddouble\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/hash","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTWrappedDouble"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/value"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/init(value:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedDouble\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTWrappedDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1init(value:)\/title","op":"replace","value":"initWithValue:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1init(value:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithValue:"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1value\/title","op":"replace","value":"value"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1value\/fragments","op":"replace","value":[{"kind":"identifier","text":"value"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedDouble~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}