{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/rawLines","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawLines"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rawLines","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult(py)rawLines","title":"rawLines","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"rawLines","kind":"identifier"}]},"abstract":[{"text":"Lines of text recognized by OCR of the document.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/rawlines"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrzrecognitionresult\/rawlines"]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"navigatorTitle":[{"text":"MrzRecognitionResult","kind":"identifier"}],"type":"topic","role":"symbol","title":"MrzRecognitionResult","abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"url":"\/documentation\/dotdocument\/mrzrecognitionresult","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzRecognitionResult","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult/rawLines":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult\/rawLines","url":"\/documentation\/dotdocument\/mrzrecognitionresult\/rawlines","role":"symbol","navigatorTitle":[{"text":"rawLines","kind":"identifier"}],"abstract":[{"type":"text","text":"Lines of text recognized by OCR of the document."}],"title":"rawLines","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rawLines"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"rawLines","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"rawLines"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"text":"rawLines","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title","value":"DOTDMrzRecognitionResult","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1rawLines\/title","op":"replace","value":"rawLines"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult~1rawLines\/fragments","value":[{"text":"rawLines","kind":"identifier"}],"op":"replace"}]}]}