{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPDetectionPosition) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Position of the palm in the image."}],"metadata":{"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"class","title":"DetectionPosition","externalID":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/detectionposition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/detectionposition"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomRight","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topRight"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/rebased(parentRectangle:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/from(rectangle:)"],"title":"Type Methods","generated":true}],"seeAlsoSections":[{"anchor":"Palm-auto-capture-process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],"title":"Palm auto capture process","generated":true}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/isEqual(_:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/isEqual(_:)","url":"\/documentation\/dotpalmcore\/detectionposition\/isequal(_:)","kind":"symbol","type":"topic","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"type":"topic","title":"PalmAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected palm.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"type":"topic","title":"PalmAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/description":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/description","url":"\/documentation\/dotpalmcore\/detectionposition\/description","title":"description","kind":"symbol","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/topLeft":{"abstract":[{"type":"text","text":"Top left corner point."}],"title":"topLeft","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topLeft","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"topLeft"}],"url":"\/documentation\/dotpalmcore\/detectionposition\/topleft"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the palm in the image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/detectionposition","title":"DetectionPosition","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"role":"symbol"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/topRight":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topRight","type":"topic","abstract":[{"type":"text","text":"Top right corner point."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition\/topright","title":"topRight","navigatorTitle":[{"kind":"identifier","text":"topRight"}]},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/hash":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/hash","url":"\/documentation\/dotpalmcore\/detectionposition\/hash","kind":"symbol","type":"topic","title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/bottomRight":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition\/bottomright","abstract":[{"type":"text","text":"Bottom right corner point."}],"title":"bottomRight","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomRight"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/points":{"type":"topic","title":"points","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/points","url":"\/documentation\/dotpalmcore\/detectionposition\/points","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"points"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/mirrored()":{"type":"topic","title":"mirrored()","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","text":"DetectionPosition"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/mirrored()","url":"\/documentation\/dotpalmcore\/detectionposition\/mirrored()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"mirrored"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/rebased(parentRectangle:)":{"type":"topic","title":"rebased(parentRectangle:)","abstract":[],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/rebased(parentRectangle:)","url":"\/documentation\/dotpalmcore\/detectionposition\/rebased(parentrectangle:)","kind":"symbol","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/from(rectangle:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/from(rectangle:)","url":"\/documentation\/dotpalmcore\/detectionposition\/from(rectangle:)","type":"topic","kind":"symbol","title":"from(rectangle:)","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"type":"topic","title":"PalmAutoCaptureResult","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","navigatorTitle":[{"text":"PalmAutoCaptureResult","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/bottomLeft":{"abstract":[{"text":"Bottom left corner point.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomLeft","kind":"symbol","type":"topic","title":"bottomLeft","url":"\/documentation\/dotpalmcore\/detectionposition\/bottomleft","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition/init(topLeft:topRight:bottomRight:bottomLeft:)":{"type":"topic","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","url":"\/documentation\/dotpalmcore\/detectionposition\/init(topleft:topright:bottomright:bottomleft:)","kind":"symbol","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/bottomRight","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/topRight"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/rebased(parentRectangle:)"],"title":"Instance Methods","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition\/from(rectangle:)"],"title":"Type Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"anchor":"Palm-auto-capture-process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],"title":"Palm auto capture process","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPDetectionPosition","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1isEqual(_:)\/fragments"},{"value":"DOTPPalmAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle"},{"value":"DOTPPalmAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1description\/title"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1description\/fragments"},{"value":"topLeft","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topLeft\/title"},{"value":[{"kind":"identifier","text":"topLeft"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topLeft\/fragments"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/navigatorTitle"},{"value":"topRight","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topRight\/title"},{"value":[{"kind":"identifier","text":"topRight"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1topRight\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1hash\/fragments"},{"value":"bottomRight","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomRight\/title"},{"value":[{"kind":"identifier","text":"bottomRight"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomRight\/fragments"},{"value":"points","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1points\/title"},{"value":[{"kind":"identifier","text":"points"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1points\/fragments"},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1mirrored()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1mirrored()\/fragments"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1rebased(parentRectangle:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1rebased(parentRectangle:)\/fragments"},{"value":"fromRectangle:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1from(rectangle:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1from(rectangle:)\/fragments"},{"value":"DOTPPalmAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle"},{"value":"bottomLeft","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomLeft\/title"},{"value":[{"kind":"identifier","text":"bottomLeft"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1bottomLeft\/fragments"},{"value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}