{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPLocalization) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Localization","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"class","title":"Localization","externalID":"c:@M@DotPalmCore@objc(cs)DOTPLocalization","navigatorTitle":[{"kind":"identifier","text":"Localization"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/localization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/localization"]}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/bundle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/localizationDictionary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/useLocalizationDictionary"],"generated":true,"anchor":"Type-Properties"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger"],"generated":true,"title":"Global components","anchor":"Global-components"}],"references":{"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPLocalization/init":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPLocalization\/init","url":"\/documentation\/dotpalmcore\/dotplocalization\/init","type":"topic","kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Localization/useLocalizationDictionary":{"abstract":[{"text":"If you set this to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/useLocalizationDictionary","url":"\/documentation\/dotpalmcore\/localization\/uselocalizationdictionary","title":"useLocalizationDictionary","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/Localization":{"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"kind":"symbol","title":"Localization","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/localization"},"doc://DotPalmCore/documentation/DotPalmCore/Logger":{"type":"topic","title":"Logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","kind":"symbol","url":"\/documentation\/dotpalmcore\/logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/Localization/localizationDictionary":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/localizationDictionary","role":"symbol","url":"\/documentation\/dotpalmcore\/localization\/localizationdictionary","title":"localizationDictionary","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/Localization/bundle":{"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"code":"Bundle.main","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/bundle","url":"\/documentation\/dotpalmcore\/localization\/bundle","kind":"symbol","title":"bundle","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bundle"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPLocalization","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTPLocalization"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTPLocalization"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPLocalization\/init"],"generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/bundle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/localizationDictionary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization\/useLocalizationDictionary"],"generated":true,"anchor":"Type-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Global components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger"],"generated":true,"anchor":"Global-components"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPLocalization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"useLocalizationDictionary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1useLocalizationDictionary\/title"},{"value":[{"kind":"identifier","text":"useLocalizationDictionary"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1useLocalizationDictionary\/fragments"},{"value":"DOTPLocalization","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/title"},{"value":[{"kind":"identifier","text":"DOTPLocalization"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/fragments"},{"value":[{"kind":"identifier","text":"DOTPLocalization"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/navigatorTitle"},{"value":"DOTPLogger","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/title"},{"value":[{"kind":"identifier","text":"DOTPLogger"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/fragments"},{"value":[{"kind":"identifier","text":"DOTPLogger"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/navigatorTitle"},{"value":"localizationDictionary","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1localizationDictionary\/title"},{"value":[{"kind":"identifier","text":"localizationDictionary"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1localizationDictionary\/fragments"},{"value":"bundle","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1bundle\/title"},{"value":[{"kind":"identifier","text":"bundle"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization~1bundle\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}