{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"type"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholderVisible(py)type","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"type"}],"title":"type"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotplaceholdervisible\/type"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible\/type","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"text":".circle","type":"text"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier","text":"DOTPlaceholderType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible"]]},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderVisible/type":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible\/type","title":"type","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"text","text":".circle"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/dotplaceholdervisible\/type","fragments":[{"kind":"identifier","text":"type"}],"role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTPlaceholderVisible":{"kind":"symbol","fragments":[{"kind":"identifier","text":"DOTPlaceholderVisible"}],"title":"DOTPlaceholderVisible","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTPlaceholderVisible","url":"\/documentation\/dotfacecore\/dotplaceholdervisible"},"doc://DotFaceCore/documentation/DotFaceCore/PlaceholderType":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PlaceholderType","title":"PlaceholderType","url":"\/documentation\/dotfacecore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}