{"abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"metadata":{"roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel","kind":"typeIdentifier"}],"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"title":"logLevel","externalID":"c:@M@DotNfc@objc(cs)DOTNLogger(cpy)logLevel","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/logger\/loglevel"]},{"paths":["\/documentation\/dotnfc\/logger\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Logger"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger\/logLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/LoggerLogLevel":{"abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"title":"LoggerLogLevel","url":"\/documentation\/dotnfc\/loggerloglevel","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Logger":{"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Logger"}],"title":"Logger","url":"\/documentation\/dotnfc\/logger","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","role":"symbol"},"doc://DotNfc/documentation/DotNfc/Logger/logLevel":{"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/dotnfc\/logger\/loglevel","title":"logLevel","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger\/logLevel","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"logLevel","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"logLevel","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/LoggerLogLevel","text":"DOTLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/title","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/fragments","op":"replace"},{"value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1LoggerLogLevel\/navigatorTitle","op":"replace"},{"value":"DOTNLogger","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/title","op":"replace"},{"value":[{"text":"DOTNLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/fragments","op":"replace"},{"value":[{"text":"DOTNLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/navigatorTitle","op":"replace"},{"value":"logLevel","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger~1logLevel\/title","op":"replace"},{"value":[{"text":"logLevel","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger~1logLevel\/fragments","op":"replace"}]}]}