{"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"detectionArea","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration(py)detectionArea","navigatorTitle":[{"kind":"identifier","text":"detectionArea"}],"fragments":[{"kind":"identifier","text":"detectionArea"}]},"abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the face detection.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" * ","kind":"text"},{"text":"detectionArea","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration\/detectionarea"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration\/detectionArea","interfaceLanguage":"occ"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/rectangledouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"title":"RectangleDouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration/detectionArea":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration\/detectionArea","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration\/detectionarea","fragments":[{"text":"detectionArea","kind":"identifier"}],"title":"detectionArea","kind":"symbol","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the face detection."}],"type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerConfiguration":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollerconfiguration","abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"role":"symbol","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerConfiguration","title":"DOTFLFaceAutoCaptureControllerConfiguration"}},"variantOverrides":[{"patch":[{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}