{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Detected face in the image. Might be ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" only if ","type":"text"},{"type":"reference","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","isActive":true},{"type":"text","text":" was used to get the result."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/face","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","text":"FaceDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureResult(py)face","title":"face","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureresult\/face"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceautocaptureresult\/face"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","abstract":[{"type":"text","text":"Request capture of the next detection."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestCapture"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","title":"requestCapture(isFacePresenceRequired:)","navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"title":"FaceDetector.Face","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/face","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","abstract":[{"text":"Detected face in the image.","type":"text"}],"navigatorTitle":[{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.12.1"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureresult","abstract":[{"type":"text","text":"The final result of the face auto capture process."}],"title":"FaceAutoCaptureResult","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureResult/face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureResult\/face","abstract":[{"text":"Detected face in the image. Might be ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" only if "},{"type":"reference","isActive":true,"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)"},{"type":"text","text":" was used to get the result."}],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","text":"Face","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacecore\/faceautocaptureresult\/face","title":"face","navigatorTitle":[{"kind":"identifier","text":"face"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","title":"FaceAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facedetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","role":"symbol","url":"\/documentation\/dotfacecore\/face","abstract":[{"type":"text","text":"Detected face in the image."}],"title":"Face","type":"topic","kind":"symbol","fragments":[{"text":"Face","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"face","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"face","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"Face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"requestCaptureWithIsFacePresenceRequired:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments"},{"value":"DOTFFaceAutoCaptureResult","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult\/fragments","value":[{"text":"DOTFFaceAutoCaptureResult","kind":"identifier"}]},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1face\/title"},{"value":[{"kind":"identifier","text":"face"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureResult~1face\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}