{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/deviceTiltAngles"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/devicetiltangles"]}],"metadata":{"fragments":[{"text":"deviceTiltAngles","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","title":"deviceTiltAngles","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"deviceTiltAngles"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerSample(py)deviceTiltAngles"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","text":"DOTTiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"deviceTiltAngles","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"url":"\/documentation\/dotfacelite\/tiltangles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","type":"topic","kind":"symbol","title":"TiltAngles","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample":{"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerSample"}],"title":"DOTFLFaceAutoCaptureControllerSample","type":"topic","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample","role":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link","title":"Sensor Coordinate System","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample/deviceTiltAngles":{"role":"symbol","type":"topic","fragments":[{"text":"deviceTiltAngles","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/devicetiltangles","kind":"symbol","title":"deviceTiltAngles","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/deviceTiltAngles"}},"variantOverrides":[{"patch":[{"value":"DOTTiltAngles","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title"},{"value":[{"text":"DOTTiltAngles","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments"},{"value":[{"kind":"identifier","text":"DOTTiltAngles"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}