{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"image","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"abstract":[{"text":"Sample image.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/image","interfaceLanguage":"occ"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"image","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerSample(py)image","roleHeading":"Instance Property","title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}],"symbolKind":"property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample/image":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/image","fragments":[{"kind":"identifier","text":"image"}],"title":"image","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/image","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Sample image."}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerSample"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample","title":"DOTFLFaceAutoCaptureControllerSample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the face auto capture process.","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"title":"Image","type":"topic","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","url":"\/documentation\/dotfacelite\/image","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}