{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/initWithImage:timestampMillis:deviceTiltAngles:"},"sections":[],"metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerSample(im)initWithImage:timestampMillis:deviceTiltAngles:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:timestampMillis:deviceTiltAngles:"}],"title":"initWithImage:timestampMillis:deviceTiltAngles:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:timestampMillis:deviceTiltAngles:"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"timestampMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"timestampMillis","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","text":"DOTTiltAngles","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"deviceTiltAngles","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/initwithimage:timestampmillis:devicetiltangles:"]}],"kind":"symbol","references":{"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","titleInlineContent":[{"text":"Sensor Coordinate System","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample/initWithImage:timestampMillis:deviceTiltAngles:":{"role":"symbol","type":"topic","fragments":[{"text":"- ","kind":"text"},{"text":"initWithImage:timestampMillis:deviceTiltAngles:","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample\/initwithimage:timestampmillis:devicetiltangles:","navigatorTitle":[{"text":"initWithImage:timestampMillis:deviceTiltAngles:","kind":"identifier"}],"title":"initWithImage:timestampMillis:deviceTiltAngles:","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample\/initWithImage:timestampMillis:deviceTiltAngles:"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"role":"symbol","title":"Image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureControllerSample":{"fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerSample"}],"title":"DOTFLFaceAutoCaptureControllerSample","type":"topic","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the face auto capture process."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureControllerSample","url":"\/documentation\/dotfacelite\/dotflfaceautocapturecontrollersample","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/TiltAngles":{"url":"\/documentation\/dotfacelite\/tiltangles","navigatorTitle":[{"text":"TiltAngles","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/TiltAngles","type":"topic","kind":"symbol","title":"TiltAngles","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","isActive":true},{"type":"text","text":"."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TiltAngles","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","op":"replace","value":"DOTImage"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/title","op":"replace","value":"DOTTiltAngles"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1TiltAngles\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}