{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/moduleCategory","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"moduleCategory","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory","text":"DotFaceModuleCategory","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","kind":"typeIdentifier"}],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper(py)moduleCategory","roleHeading":"Instance Property","title":"moduleCategory","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleCategory"},{"text":": ","kind":"text"},{"text":"DotFaceModuleCategory","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"moduleCategory"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/modulecategory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/modulecategory"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.0.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleCategory":{"abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" module category.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotFaceModuleCategory","kind":"identifier"}],"title":"DotFaceModuleCategory","role":"symbol","type":"topic","navigatorTitle":[{"text":"DotFaceModuleCategory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodulecategory","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleCategoryWrapper/moduleCategory":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper\/moduleCategory","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleCategory"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","text":"DotFaceModuleCategory","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"moduleCategory"}],"title":"moduleCategory","url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper\/modulecategory"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModuleCategoryWrapper":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"DotFaceModuleCategory"},{"text":" value for Objective-C support.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"title":"DotFaceModuleCategoryWrapper","url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"moduleCategory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"moduleCategory","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModuleCategory","text":"DotFaceModuleCategory","preciseIdentifier":"c:@M@DotFaceCore@E@DotFaceModuleCategory","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"moduleCategory","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory\/title","op":"replace","value":"DotFaceModuleCategory"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategory\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategory"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1moduleCategory\/title","value":"moduleCategory","op":"replace"},{"value":[{"text":"moduleCategory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper~1moduleCategory\/fragments","op":"replace"},{"value":"DotFaceModuleCategoryWrapper","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/fragments"}]}]}