{"kind":"symbol","abstract":[{"text":"Placeholder type. Default is ","type":"text"},{"text":".circle","type":"text"},{"text":".","type":"text"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible\/type"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible"]]},"metadata":{"navigatorTitle":[{"text":"type","kind":"identifier"}],"title":"type","externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholderVisible(py)type","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"type","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFaceCommons@E@DOTPlaceholderType","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","text":"DOTPlaceholderType"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotplaceholdervisible\/type"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTPlaceholderVisible":{"url":"\/documentation\/dotfacelite\/dotplaceholdervisible","title":"DOTPlaceholderVisible","type":"topic","fragments":[{"text":"DOTPlaceholderVisible","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible","abstract":[{"text":"Visible placeholder.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","abstract":[{"type":"text","text":"Type of placeholder."}],"title":"PlaceholderType","kind":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DOTPlaceholderVisible/type":{"url":"\/documentation\/dotfacelite\/dotplaceholdervisible\/type","title":"type","type":"topic","fragments":[{"kind":"identifier","text":"type"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible\/type","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"text","text":".circle"},{"type":"text","text":"."}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}