{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/valuerange\/resolvestatus(value:)"]},{"paths":["\/documentation\/dotfacecore\/valuerange\/resolvestatus(value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"resolveStatus(value:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"resolveStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Status","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore10ValueRangeC6StatusO"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"text":"resolveStatusWithValue:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFValueRange(im)resolveStatusWithValue:"},"sections":[],"abstract":[{"type":"text","text":"Checks the status of "},{"code":"value","type":"codeVoice"},{"type":"text","text":" with respect to this range."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/resolveStatus(value:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"resolveStatus","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore10ValueRangeC6StatusO","text":"Status"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","title":"ValueRange","abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"text":" range, compatible with Objective-C.","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/valuerange","kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValueRange","kind":"identifier"}],"navigatorTitle":[{"text":"ValueRange","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFValueRangeStatus":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFValueRangeStatus","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFValueRangeStatus"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotfvaluerangestatus","title":"DOTFValueRangeStatus","abstract":[{"type":"text","text":"Status of a value with respect to a range."}]},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/resolveStatus(value:)":{"url":"\/documentation\/dotfacecore\/valuerange\/resolvestatus(value:)","abstract":[{"type":"text","text":"Checks the status of "},{"code":"value","type":"codeVoice"},{"type":"text","text":" with respect to this range."}],"navigatorTitle":[{"text":"resolveStatusWithValue:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"resolveStatus","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:11DotFaceCore10ValueRangeC6StatusO"}],"type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/resolveStatus(value:)","title":"resolveStatus(value:)"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Status":{"url":"\/documentation\/dotfacecore\/valuerange\/status","title":"ValueRange.Status","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Status","type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Status","kind":"identifier"}],"navigatorTitle":[{"text":"Status","kind":"identifier"}],"abstract":[{"type":"text","text":"Status of a value with respect to a range."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"resolveStatusWithValue:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"resolveStatusWithValue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFValueRangeStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFValueRangeStatus","text":"DOTFValueRangeStatus"},{"kind":"text","text":") "},{"kind":"identifier","text":"resolveStatusWithValue:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title","op":"replace","value":"DOTFValueRange"},{"value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1resolveStatus(value:)\/title","value":"resolveStatusWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange~1resolveStatus(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"resolveStatusWithValue:","kind":"identifier"}]}]}]}