{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration"]]},"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithSessionToken:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"qualityAttributeThresholds:"},{"text":"(","kind":"text"},{"text":"DOTFLQualityAttributeThresholds","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"qualityAttributeThresholds"},{"text":" ","kind":"text"},{"text":"captureMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","text":"DOTCaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"},{"kind":"text","text":") "},{"text":"captureMode","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isPlaceholderVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isPlaceholderVisible"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"isTorchEnabled"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isVideoCaptureEnabled"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isCameraPreviewVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isCameraPreviewVisible","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","interfaceLanguage":"occ"},"metadata":{"title":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","role":"symbol","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLQualityAttributeThresholds":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"url":"\/documentation\/dotfacelite\/dotflqualityattributethresholds","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLQualityAttributeThresholds","title":"DOTFLQualityAttributeThresholds","role":"symbol","fragments":[{"text":"DOTFLQualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"url":"\/documentation\/dotfacelite\/camerafacing","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration","title":"DOTFLFaceAutoCaptureConfiguration","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:":{"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:capturemode:isplaceholdervisible:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"title":"initWithSessionToken:qualityAttributeThresholds:captureMode:isPlaceholderVisible:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"kind":"symbol","title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"url":"\/documentation\/dotfacelite\/capturemode","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","abstract":[{"type":"text","text":"Capture mode."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","type":"topic","title":"CameraPreviewScaleType","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","op":"replace","value":"DOTCaptureMode"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}