{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Palm library configuration.","type":"text"}],"metadata":{"symbolKind":"property","title":"palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)Libraries(py)palm","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/libraries\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/libraries\/palm"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/palm","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/Libraries/palm":{"url":"\/documentation\/dotdocument\/libraries\/palm","type":"topic","navigatorTitle":[{"text":"palm","kind":"identifier"}],"title":"palm","kind":"symbol","abstract":[{"text":"Palm library configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/palm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"type":"topic","title":"DotPalmLibraryConfiguration","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration"},"doc://DotDocument/documentation/DotDocument/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","url":"\/documentation\/dotdocument\/libraries","role":"symbol","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"title":"Libraries","type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"palm","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"palm"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"palm"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"palm","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1palm\/title"},{"op":"replace","value":[{"kind":"identifier","text":"palm"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1palm\/fragments"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"Libraries","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title"},{"op":"replace","value":[{"text":"Libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle"}]}]}