{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/description"]}],"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit(py)description","navigatorTitle":[{"kind":"identifier","text":"description"}],"modules":[{"name":"DotNfc"}],"role":"symbol","roleHeading":"Instance Property"},"references":{"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit/description":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit\/description","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit\/description","abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"title":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/navigatorTitle","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}