{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"modules":[{"name":"DotNfc"}],"externalID":"s:6DotNfc24ChipAuthenticationStatusC0D8ProtocolO","symbolKind":"enum","role":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/activeAuthentication","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/chipAuthentication","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/paceChipAuthenticationMapping"]},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/init(rawValue:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/description"]},{"anchor":"Default-Implementations","generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"]}],"seeAlsoSections":[{"anchor":"NFC-protocols","generated":true,"title":"NFC protocols","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNChipAuthenticationStatusProtocol) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationProtocol","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"url":"\/documentation\/dotnfc\/accesscontrolprotocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","abstract":[{"type":"text","text":"Access Control protocol."}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AccessControlProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"AccessControlProtocol","kind":"identifier"}],"title":"AccessControlProtocol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum":{"navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"kind":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum","abstract":[{"type":"text","text":"Protocol for authentication of the chip."}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"},"doc://DotNfc/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"url":"\/documentation\/dotnfc\/dataauthenticationstatus","abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"kind":"symbol","title":"DataAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/paceChipAuthenticationMapping":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"paceChipAuthenticationMapping"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/paceChipAuthenticationMapping","abstract":[{"type":"text","text":"PACE access protocol with Chip Authentication Mapping. This protocol has top priority."}],"title":"ChipAuthenticationStatus.AuthenticationProtocol.paceChipAuthenticationMapping","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/pacechipauthenticationmapping"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/description":{"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/description","title":"description","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/description"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/init(rawValue:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/init(rawValue:)","kind":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/init(rawvalue:)","role":"symbol","abstract":[],"title":"init(rawValue:)"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"title":"ChipAuthenticationStatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"abstract":[{"type":"text","text":"Authentication status of data and chip."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","url":"\/documentation\/dotnfc\/authenticationstatus","role":"symbol","navigatorTitle":[{"text":"AuthenticationStatus","kind":"identifier"}],"title":"AuthenticationStatus","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/activeAuthentication":{"type":"topic","abstract":[{"type":"text","text":"Active Authentication protocol. Used if neither PACE-CAM nor Chip Authentication protocol is supported."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/activeauthentication","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/activeAuthentication","role":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol.activeAuthentication","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"activeAuthentication","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/chipAuthentication":{"type":"topic","abstract":[{"type":"text","text":"Chip Authentication protocol. Used if PACE-CAM is not supported."}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/chipauthentication","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/chipAuthentication","role":"symbol","title":"ChipAuthenticationStatus.AuthenticationProtocol.chipAuthentication","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"chipAuthentication"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/AuthenticationProtocol-swift.enum/Equatable-Implementations":{"kind":"article","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/AuthenticationProtocol-swift.enum\/Equatable-Implementations","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.enum\/equatable-implementations","role":"collectionGroup","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","value":"DOTNAccessControlProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","value":"DOTNDataAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title","value":"DOTNAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}]}]}]}