{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"description","platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"name":"iOS","deprecated":false}],"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(py)description"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"references":{"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"url":"\/documentation\/dotnfc\/chipauthenticationstatus","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","title":"ChipAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/description":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/description","title":"description","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.15.1"}],"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"description","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}]},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1description\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}