{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","text":"Status"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","text":"WrappedProtocol"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithStatus:wrappedProtocol:"}],"role":"symbol","title":"init(status:wrappedProtocol:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(im)initWithStatus:wrappedProtocol:","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.4.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus":{"role":"symbol","title":"ChipAuthenticationStatus","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus/init(status:wrappedProtocol:)":{"role":"symbol","title":"init(status:wrappedProtocol:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"status"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O"},{"kind":"text","text":", "},{"kind":"externalParam","text":"wrappedProtocol"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/init(status:wrappedProtocol:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStatus:wrappedProtocol:"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/init(status:wrappedprotocol:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol":{"role":"symbol","title":"ChipAuthenticationStatus.WrappedProtocol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedProtocol"}],"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"AuthenticationProtocol"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedProtocol"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DOTNChipAuthenticationStatusStatus":{"role":"symbol","title":"DOTNChipAuthenticationStatusStatus","fragments":[{"kind":"identifier","text":"DOTNChipAuthenticationStatusStatus"}],"abstract":[{"type":"text","text":"Authentication status of the chip."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatusstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DOTNChipAuthenticationStatusWrappedProtocol":{"role":"symbol","title":"DOTNChipAuthenticationStatusWrappedProtocol","fragments":[{"kind":"identifier","text":"DOTNChipAuthenticationStatusWrappedProtocol"}],"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"text","text":"AuthenticationProtocol"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatuswrappedprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"role":"symbol","title":"ChipAuthenticationStatus.Status","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Status"}],"abstract":[{"type":"text","text":"Authentication status of the chip."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Status"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithStatus:wrappedProtocol:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:wrappedProtocol:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithStatus:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTNChipAuthenticationStatusStatus","text":"DOTNChipAuthenticationStatusStatus"},{"kind":"text","text":")"},{"kind":"internalParam","text":"status"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrappedProtocol:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatusWrappedProtocol","text":"DOTNChipAuthenticationStatusWrappedProtocol"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"wrappedProtocol"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:)\/title","value":"initWithStatus:wrappedProtocol:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1init(status:wrappedProtocol:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatus:wrappedProtocol:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}