{"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(py)status","symbolKind":"property","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","title":"status","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Status","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O"}],"navigatorTitle":[{"kind":"identifier","text":"status"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Status","kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.property"]}],"abstract":[{"text":"Status of the authentication process.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/status-swift.property"},"references":{"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"ChipAuthenticationStatus","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ChipAuthenticationStatus","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","kind":"symbol","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"title":"ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/Status-swift.enum":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"Status","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/Status-swift.enum","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Status","kind":"identifier"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.enum","kind":"symbol","abstract":[{"type":"text","text":"Authentication status of the chip."}],"title":"ChipAuthenticationStatus.Status"},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusStatus":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatusstatus","role":"symbol","abstract":[{"text":"Authentication status of the chip.","type":"text"}],"title":"DOTNChipAuthenticationStatusStatus","fragments":[{"kind":"identifier","text":"DOTNChipAuthenticationStatusStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/status-swift.property":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}],"type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/status-swift.property","role":"symbol","abstract":[{"text":"Status of the authentication process.","type":"text"}],"title":"status","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC0E0O","kind":"typeIdentifier","text":"Status"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/status-swift.property"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"status"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNChipAuthenticationStatusStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTNChipAuthenticationStatusStatus","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusStatus"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1status-swift.property\/title","op":"replace","value":"status"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1status-swift.property\/fragments","op":"replace","value":[{"kind":"identifier","text":"status"}]}]}]}