{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator"]]},"abstract":[{"type":"text","text":"Current minimal accepted sharpness."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/threshold"},"variants":[{"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/threshold"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/threshold"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSharpnessTooLowValidator(py)threshold","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"role":"symbol","title":"threshold","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/threshold":{"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/threshold","type":"topic","role":"symbol","title":"threshold","abstract":[{"text":"Current minimal accepted sharpness.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/threshold"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.1"}],"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","role":"symbol","title":"FaceAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"threshold","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"threshold"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"}],"languages":["occ"]}]}},{"value":"threshold","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1threshold\/title"},{"value":[{"text":"threshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1threshold\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}