{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"barcode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules\/initWithBarcode:"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:"]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithBarcode:","externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(im)initWithBarcode:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentBarcodeModuleConfiguration":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotdocumentbarcodemoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"role":"symbol","title":"DotDocumentBarcodeModuleConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfigurationModules":{"url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules","type":"topic","kind":"symbol","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"role":"symbol","title":"DotDocumentLibraryConfigurationModules"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentLibraryConfigurationModules/initWithBarcode:":{"navigatorTitle":[{"text":"initWithBarcode:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentLibraryConfigurationModules\/initWithBarcode:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBarcode:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotdocumentlibraryconfigurationmodules\/initwithbarcode:","title":"initWithBarcode:","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"}]}]}