{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/RawRepresentable-Implementations"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"DotNfc"}],"role":"collectionGroup"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hashValue"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hash(into:)"],"anchor":"Instance-Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imageformat\/rawrepresentable-implementations"]}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat"]]},"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat/hashValue":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hashValue","type":"topic","abstract":[],"title":"hashValue","role":"symbol","url":"\/documentation\/dotnfc\/imageformat\/hashvalue","kind":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]}},"doc://DotNfc/documentation/DotNfc/ImageFormat":{"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","abstract":[{"type":"text","text":"Supported image formats."}],"type":"topic","title":"ImageFormat","role":"symbol","url":"\/documentation\/dotnfc\/imageformat","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageFormat/hash(into:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/imageformat\/hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat\/hash(into:)","type":"topic","kind":"symbol","title":"hash(into:)"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTImageFormat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments"},{"op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle"}]}]}