{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/description"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/customstringconvertible-implementations"]}],"metadata":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","roleHeading":"API Collection","modules":[{"name":"DotNfc"}]},"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/description","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/description","role":"symbol","title":"description"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","kind":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"title":"CardAccessNumberPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","abstract":[],"type":"topic","title":"CardAccessNumberPassword.Error","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNCardAccessNumberPassword","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle"},{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle"}]}]}