{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/composeWithInternalError()"],"generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/dotsdkerror-implementations"]}],"metadata":{"modules":[{"name":"DotNfc"}],"role":"collectionGroup","title":"DotSdkError Implementations"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/DotSdkError-Implementations"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"article","sections":[],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/composeWithInternalError()":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/composeWithInternalError()","title":"composeWithInternalError()","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/composewithinternalerror()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"CardAccessNumberPassword.Error","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 8.15.1"}],"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"title":"CardAccessNumberPassword","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardAccessNumberPassword"}],"abstract":[{"type":"text","text":"Card Access Number as a password."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcTravelDocumentReader","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"op":"replace"}]}]}