{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"sections":[],"metadata":{"role":"collectionGroup","title":"Error Implementations","modules":[{"name":"DotNfc"}],"roleHeading":"API Collection"},"topicSections":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/localizedDescription"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/Error-Implementations","interfaceLanguage":"swift"},"kind":"article","references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"role":"symbol","title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","title":"CardAccessNumberPassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardAccessNumberPassword"}],"kind":"symbol","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","title":"CardAccessNumberPassword.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/localizedDescription":{"abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/localizedDescription","role":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/localizeddescription","title":"localizedDescription","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"op":"replace"}]}]}