{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.helpAnchor","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/helpanchor"]}],"metadata":{"extendedModule":"Foundation","title":"helpAnchor","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"platforms":[{"unavailable":false,"name":"iOS","introducedAt":"8.0","beta":false,"deprecated":false},{"unavailable":false,"name":"iPadOS","introducedAt":"8.0","beta":false,"deprecated":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"8.0","beta":false,"deprecated":false},{"unavailable":false,"name":"macOS","introducedAt":"10.10","beta":false,"deprecated":false},{"unavailable":false,"name":"tvOS","introducedAt":"9.0","beta":false,"deprecated":false},{"unavailable":false,"name":"watchOS","introducedAt":"2.0","beta":false,"deprecated":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","role":"symbol"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/helpAnchor"},"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","type":"topic","title":"CardAccessNumberPassword.Error","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/helpAnchor":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","title":"helpAnchor","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/helpAnchor","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/helpanchor","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","type":"topic","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"role":"symbol","title":"CardAccessNumberPassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title"},{"op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}