{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCardAccessNumber"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/invalidCardAccessNumber","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCardAccessNumber"}],"title":"CardAccessNumberPassword.Error.invalidCardAccessNumber","role":"symbol","externalID":"s:6DotNfc24CardAccessNumberPasswordC5ErrorO07invalidcdE0yA2EmF","symbolKind":"case"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/invalidcardaccessnumber"]}],"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","abstract":[{"type":"text","text":"Card Access Number as a password."}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","kind":"symbol","title":"CardAccessNumberPassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/invalidCardAccessNumber":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/invalidcardaccessnumber","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCardAccessNumber","kind":"identifier"}],"kind":"symbol","title":"CardAccessNumberPassword.Error.invalidCardAccessNumber","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/invalidCardAccessNumber","role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","abstract":[],"title":"CardAccessNumberPassword.Error","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNCardAccessNumberPassword","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle"}]}]}