{"topicSections":[{"anchor":"Operators","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/!=(_:_:)"],"title":"Operators"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotPalmCore"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/!=(_:_:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/!=(_:_:)","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid","title":"DotDocumentModuleId","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace"}]}]}