{"metadata":{"title":"fullFrontalImage","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullFrontalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore0B8DetectorC0B0C16fullFrontalImage0aC00G0CSgvp","role":"symbol"},"abstract":[{"type":"text","text":"ICAO full frontal face image. This is evaluated only if it is specified in "},{"type":"codeVoice","code":"FaceDetectionQuery"},{"type":"text","text":"."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/fullfrontalimage"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/fullFrontalImage","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullFrontalImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/fullFrontalImage":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fullFrontalImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/fullFrontalImage","url":"\/documentation\/dotfacecore\/facedetector\/face\/fullfrontalimage","abstract":[{"text":"ICAO full frontal face image. This is evaluated only if it is specified in ","type":"text"},{"type":"codeVoice","code":"FaceDetectionQuery"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","title":"fullFrontalImage"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"type":"topic","title":"Image","url":"\/documentation\/dotfacecore\/image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"type":"topic","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"title":"FaceDetector.Face","url":"\/documentation\/dotfacecore\/facedetector\/face","abstract":[{"text":"Detected face in the image.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Face"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle"}]}]}