{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/placeholder\/hidden\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden"]]},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden\/description"},"metadata":{"externalID":"s:14DotFaceCommons11PlaceholderC6HiddenC11descriptionSSvp","role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Hidden":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"title":"Placeholder.Hidden","url":"\/documentation\/dotfacelite\/placeholder\/hidden","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"abstract":[{"type":"text","text":"Hidden placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","title":"Placeholder","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Hidden/description":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","url":"\/documentation\/dotfacelite\/placeholder\/hidden\/description","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden\/description"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPlaceholder","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPlaceholder"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle"}]}]}