{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"languages":["swift"]}]},{"parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]},{"name":"ciContext","content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","symbolKind":"method","role":"symbol","roleHeading":"Type Method","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCiImage:ciContext:","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}]},"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrarawimagefactory\/create(ciimage:cicontext:)"]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(ciImage:ciContext:)","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"title":"BgraRawImage","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory":{"type":"topic","title":"BgraRawImageFactory","url":"\/documentation\/dotdocument\/bgrarawimagefactory","kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}]},"doc://DotDocument/documentation/DotDocument/BgraRawImageFactory/create(ciImage:ciContext:)":{"role":"symbol","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimagefactory\/create(ciimage:cicontext:)","type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImageFactory\/create(ciImage:ciContext:)","title":"create(ciImage:ciContext:)"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"createWithCiImage:ciContext:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithCiImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":" *) ","kind":"text"},{"text":"ciContext","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/title","op":"replace","value":"DOTBgraRawImageFactory"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory\/fragments"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]}]}]}