{"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/init(modules:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/init(modules:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"},{"kind":"text","text":" = .init())"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"role":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration(im)initWithModules:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"roleHeading":"Initializer","title":"init(modules:)","symbolKind":"init"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration":{"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration","kind":"symbol","title":"DotDocumentLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/init(modules:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/init(modules:)","title":"init(modules:)","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/init(modules:)","kind":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Document library module configuration.","type":"text"}],"type":"topic","title":"DotDocumentLibraryConfiguration.Modules","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfiguration\/modules-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotDocumentLibraryConfigurationModules":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","url":"\/documentation\/dotfacecore\/dotdocumentlibraryconfigurationmodules","abstract":[{"text":"Document library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"identifier","text":"DotDocumentLibraryConfigurationModules"}],"title":"DotDocumentLibraryConfigurationModules","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModules:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotDocumentLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules","kind":"typeIdentifier","text":"DotDocumentLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modules"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"initWithModules:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration~1init(modules:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotDocumentLibraryConfiguration~1init(modules:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}