{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithNibName:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibNameOrNil"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"nibBundleOrNil"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/initwithnibname:bundle:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/initWithNibName:bundle:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"title":"initWithNibName:bundle:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(im)initWithNibName:bundle:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/initWithNibName:bundle:":{"role":"symbol","title":"initWithNibName:bundle:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithNibName:bundle:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/initWithNibName:bundle:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithNibName:bundle:"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/initwithnibname:bundle:"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"role":"symbol","title":"FaceSimpleCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}