{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)description","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/description","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/description"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration/description":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/description","role":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"description","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCameraConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/navigatorTitle"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1description\/fragments"}]}]}