{"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isPreviewVisible","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"isPreviewVisible","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"isPreviewVisible"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPreviewVisible"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/isPreviewVisible","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/ispreviewvisible"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/ispreviewvisible"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration/isPreviewVisible":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration\/ispreviewvisible","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPreviewVisible","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isPreviewVisible","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/isPreviewVisible","role":"symbol","abstract":[{"text":"Use this flag to show\/hide camera preview. Default is ","type":"text"},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"isPreviewVisible","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isPreviewVisible"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"isPreviewVisible"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isPreviewVisible"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/navigatorTitle","op":"replace"},{"value":"isPreviewVisible","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1isPreviewVisible\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isPreviewVisible"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1isPreviewVisible\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}