{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Use this flag to turn the torch on\/off during the capture process."},{"type":"text","text":" "},{"type":"text","text":"Torch will be turned on only if "},{"type":"codeVoice","code":"facing"},{"type":"text","text":" property is set to "},{"type":"codeVoice","code":".back"},{"type":"text","text":". Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"metadata":{"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isTorchEnabled","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isTorchEnabled","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/isTorchEnabled","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/istorchenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/cameraconfiguration\/istorchenabled"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraConfiguration/isTorchEnabled":{"url":"\/documentation\/dotfingerscore\/cameraconfiguration\/istorchenabled","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isTorchEnabled","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraConfiguration\/isTorchEnabled","role":"symbol","abstract":[{"text":"Use this flag to turn the torch on\/off during the capture process.","type":"text"},{"text":" ","type":"text"},{"text":"Torch will be turned on only if ","type":"text"},{"type":"codeVoice","code":"facing"},{"text":" property is set to ","type":"text"},{"type":"codeVoice","code":".back"},{"text":". Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"isTorchEnabled","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"isTorchEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"isTorchEnabled","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isTorchEnabled","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/fragments","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration\/navigatorTitle","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1isTorchEnabled\/title","value":"isTorchEnabled"},{"op":"replace","value":[{"kind":"identifier","text":"isTorchEnabled"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraConfiguration~1isTorchEnabled\/fragments"}]}]}