{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC","text":"QualityAttributeThresholds"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minConfidence"},{"type":"text","text":" value is 0.15."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"sizeInterval"},{"type":"text","text":" value is [0.16, 0.2]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minSharpness"},{"type":"text","text":" value is 0.2832."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"pitchAngleInterval"},{"type":"text","text":" value is [-6, 2]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"yawAngleInterval"},{"type":"text","text":" value is [-4, 4]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"brightnessInterval"},{"type":"text","text":" value is [0.25, 0.75]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"contrastInterval"},{"type":"text","text":" value is [0.25, 0.75]."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minUniqueIntensityLevels"},{"type":"text","text":" value is 0.5."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minBackgroundUniformity"},{"type":"text","text":" value is 0.505."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minMouthStatusScore"},{"type":"text","text":" value is 0.5."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"minEyesStatusScore"},{"type":"text","text":" value is 0.475."}]},{"type":"paragraph","inlineContent":[{"type":"codeVoice","code":"maxDevicePitchAngle"},{"type":"text","text":" value is 20."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholdpresets\/icao"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholdPresets\/icao","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Builder for "},{"type":"codeVoice","code":"QualityAttributeThresholds"},{"type":"text","text":" recommended for ICAO quality face capture."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"title":"icao","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore0B24AutoCaptureConfigurationC32QualityAttributeThresholdPresetsC4icaoAC0gH10ThresholdsC7BuilderCvpZ","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholdPresets"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.2.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholdPresets":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholdPresets","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholdPresets"}],"abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholdPresets","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholdPresets"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholdpresets"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds.Builder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureConfiguration/QualityAttributeThresholdPresets/icao":{"role":"symbol","title":"icao","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"icao"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"QualityAttributeThresholds","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotFaceCore0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"abstract":[{"type":"text","text":"Builder for "},{"type":"codeVoice","code":"QualityAttributeThresholds"},{"type":"text","text":" recommended for ICAO quality face capture."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureConfiguration\/QualityAttributeThresholdPresets\/icao","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureconfiguration\/qualityattributethresholdpresets\/icao"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/title","value":"DOTFFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}