{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/expressionNeutral","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdExpressionNeutral","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotPalmCore"}],"title":"DotFaceModuleId.expressionNeutral","navigatorTitle":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/expressionneutral"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid\/expressionneutral"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expressionNeutral","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","title":"DotFaceModuleId","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/expressionNeutral":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/expressionNeutral","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/expressionneutral","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"title":"DotFaceModuleId.expressionNeutral"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceModuleIdExpressionNeutral","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1expressionNeutral\/title","value":"DotFaceModuleIdExpressionNeutral"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1expressionNeutral\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}]}]}]}