{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preCandidateSelection"}]}]}],"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"externalID":"c:@M@DotDocument@E@DOTDDocumentAutoCapturePhase@DOTDDocumentAutoCapturePhasePreCandidateSelection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preCandidateSelection"}],"roleHeading":"Case","role":"symbol","title":"DocumentAutoCapturePhase.preCandidateSelection","modules":[{"name":"DotDocument"}]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturephase\/precandidateselection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturephase\/precandidateselection"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Pre-candidate selection is running.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/preCandidateSelection","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase":{"abstract":[{"type":"text","text":"Phase of the document auto capture process."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturephase","title":"DocumentAutoCapturePhase","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCapturePhase"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePhase/preCandidateSelection":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePhase\/preCandidateSelection","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"preCandidateSelection","kind":"identifier"}],"navigatorTitle":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturephase\/precandidateselection","abstract":[{"text":"Pre-candidate selection is running.","type":"text"}],"title":"DocumentAutoCapturePhase.preCandidateSelection","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTDDocumentAutoCapturePhasePreCandidateSelection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"DOTDDocumentAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/title","op":"replace","value":"DOTDDocumentAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCapturePhase","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1preCandidateSelection\/title","op":"replace","value":"DOTDDocumentAutoCapturePhasePreCandidateSelection"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePhase~1preCandidateSelection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePhasePreCandidateSelection"}]}]}]}