{"variants":[{"paths":["\/documentation\/dotfacecore\/headpose\/yaw"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headpose\/yaw"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"yaw"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","kind":"typeIdentifier","text":"HeadPoseAttribute"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/yaw"},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"yaw","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPose(py)yaw","navigatorTitle":[{"text":"yaw","kind":"identifier"}],"symbolKind":"property","title":"yaw"},"abstract":[{"type":"text","text":"Head pose yaw."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 8.12.1"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose/yaw":{"title":"yaw","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"yaw","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","text":"HeadPoseAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"yaw"}],"abstract":[{"text":"Head pose yaw.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose\/yaw","url":"\/documentation\/dotfacecore\/headpose\/yaw"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"url":"\/documentation\/dotfacecore\/headpose","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","title":"HeadPose","role":"symbol","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"url":"\/documentation\/dotfacecore\/headposeattribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","title":"HeadPoseAttribute","role":"symbol","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"yaw","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"yaw","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","kind":"typeIdentifier","text":"DOTFHeadPoseAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"yaw"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1yaw\/title","op":"replace","value":"yaw"},{"op":"replace","value":[{"text":"yaw","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose~1yaw\/fragments"},{"op":"replace","value":"DOTFHeadPose","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title"},{"value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}