{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/cgPoint","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble"]]},"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgPoint","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGPoint","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint"}],"externalID":"c:@CM@DotCore@objc(cs)DOTPointDouble(py)cgPoint","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"title":"cgPoint"},"variants":[{"paths":["\/documentation\/dotpalmcore\/pointdouble\/cgpoint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/pointdouble\/cgpoint"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/cgPoint":{"title":"cgPoint","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/cgPoint","abstract":[],"url":"\/documentation\/dotpalmcore\/pointdouble\/cgpoint","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cgPoint"}]},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","type":"topic","url":"\/documentation\/dotpalmcore\/pointdouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"cgPoint"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"cgPoint"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgPoint"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"cgPoint","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1cgPoint\/title"},{"value":[{"kind":"identifier","text":"cgPoint"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1cgPoint\/fragments"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]}]}]}