{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"sections":[],"metadata":{"roleHeading":"Framework","role":"collection","externalID":"DotPalmCore","symbolKind":"module","title":"DotPalmCore","modules":[{"name":"DotPalmCore"}]},"kind":"symbol","abstract":[{"type":"text","text":"version: 8.10.0"}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"],"title":"DotPalm modularization"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"],"title":"Global components"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"],"title":"UI components"},{"title":"Non-UI components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]},{"title":"Converting images","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]},{"title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DefaultTimedCaptureEvaluator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImagePropertiesAnalyzerFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/InstructionCandidateSelectionStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/InstructionStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderCandidateSelectionStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PreviewViewStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"]},{"title":"Protocols","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TimedCaptureEvaluator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/VideoRecordingHandler"]},{"title":"Enumerations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore"]}],"hierarchy":{"paths":[[]]},"primaryContentSections":[{"content":[{"anchor":"overview","type":"heading","text":"Overview","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"DotPalmCore is a part of DotPalm framework group which provides components for palm capture and related functionalities which are easy to integrate into an iOS application."}]}],"kind":"content"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerSample":{"kind":"symbol","type":"topic","role":"symbol","title":"DOTPPalmAutoCaptureControllerSample","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerSample"}],"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollersample"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","title":"DotPalmLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotPalm"},{"text":" library initialization.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibrary"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"role":"symbol","title":"DOTPPalmAutoCaptureConfiguration","fragments":[{"text":"DOTPPalmAutoCaptureConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotCoreVersionNumber":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCoreVersionNumber","title":"DotCoreVersionNumber","url":"\/documentation\/dotpalmcore\/dotcoreversionnumber","role":"symbol","fragments":[{"text":"DotCoreVersionNumber","kind":"identifier"}],"abstract":[{"text":"Project version number for DotCore.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholdPresets":{"role":"symbol","url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholdpresets","title":"DOTPQualityAttributeThresholdPresets","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholdPresets","fragments":[{"kind":"identifier","text":"DOTPQualityAttributeThresholdPresets"}],"abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the palm auto capture result."}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"url":"\/documentation\/dotpalmcore\/ciimagefactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"kind":"symbol","title":"CIImageFactory","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","title":"PalmAutoCaptureViewController","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller"},"doc://DotPalmCore/documentation/DotPalmCore/DotCaptureVersionString":{"title":"DotCaptureVersionString","kind":"symbol","role":"symbol","abstract":[{"text":"Project version string for DotCapture.","type":"text"}],"fragments":[{"kind":"identifier","text":"DotCaptureVersionString"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCaptureVersionString","type":"topic","url":"\/documentation\/dotpalmcore\/dotcaptureversionstring"},"doc://DotPalmCore/documentation/DotPalmCore/Localization":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization","title":"Localization","role":"symbol","abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/localization","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"kind":"symbol","title":"BgraRawImageFactory","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderStyle":{"role":"symbol","navigatorTitle":[{"text":"PlaceholderStyle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PlaceholderStyle","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderStyle","url":"\/documentation\/dotpalmcore\/placeholderstyle","kind":"symbol","title":"PlaceholderStyle","abstract":[],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"abstract":[{"type":"text","text":"Available log levels."}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","role":"symbol","type":"topic","title":"LoggerLogLevel"},"doc://DotPalmCore/documentation/DotPalmCore/DotCaptureVersionNumber":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCaptureVersionNumber","url":"\/documentation\/dotpalmcore\/dotcaptureversionnumber","abstract":[{"text":"Project version number for DotCapture.","type":"text"}],"role":"symbol","fragments":[{"text":"DotCaptureVersionNumber","kind":"identifier"}],"kind":"symbol","title":"DotCaptureVersionNumber","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkError":{"type":"topic","title":"DotSdkError","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError","url":"\/documentation\/dotpalmcore\/dotsdkerror"},"doc://DotPalmCore/documentation/DotPalmCore/DotSerializationVersionNumber":{"abstract":[{"type":"text","text":"Project version number for DotSerialization."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSerializationVersionNumber","type":"topic","kind":"symbol","fragments":[{"text":"DotSerializationVersionNumber","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotserializationversionnumber","role":"symbol","title":"DotSerializationVersionNumber"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","abstract":[{"text":"Capture mode.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","url":"\/documentation\/dotpalmcore\/capturemode","navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Logger":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","title":"Logger","role":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotpalmcore\/logger","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library. This class specifies how the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library will be initialized."}],"role":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholdsBuilder":{"fragments":[{"text":"DOTPQualityAttributeThresholdsBuilder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholdsBuilder","type":"topic","title":"DOTPQualityAttributeThresholdsBuilder","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholdsbuilder"},"doc://DotPalmCore/documentation/DotPalmCore/InstructionCandidateSelectionStyle":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/InstructionCandidateSelectionStyle","url":"\/documentation\/dotpalmcore\/instructioncandidateselectionstyle","title":"InstructionCandidateSelectionStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"InstructionCandidateSelectionStyle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InstructionCandidateSelectionStyle"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPQualityAttributeThresholds":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the palm auto capture result.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpqualityattributethresholds","role":"symbol","fragments":[{"kind":"identifier","text":"DOTPQualityAttributeThresholds"}],"kind":"symbol","title":"DOTPQualityAttributeThresholds","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","url":"\/documentation\/dotpalmcore\/cgimagefactory","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","title":"CGImageFactory","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PreviewViewStyle":{"type":"topic","navigatorTitle":[{"text":"PreviewViewStyle","kind":"identifier"}],"kind":"symbol","title":"PreviewViewStyle","url":"\/documentation\/dotpalmcore\/previewviewstyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PreviewViewStyle","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PreviewViewStyle","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureStyle":{"title":"DOTPPalmAutoCaptureStyle","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureStyle","abstract":[{"type":"text","text":"Customization options for the palm auto capture user interface."}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturestyle","fragments":[{"text":"DOTPPalmAutoCaptureStyle","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase","kind":"symbol","abstract":[{"type":"text","text":"Phase of the palm auto capture process."}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"role":"symbol","title":"PalmAutoCapturePhase","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory":{"abstract":[{"text":"Create ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory","title":"BgrRawImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/TimedCaptureEvaluator":{"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TimedCaptureEvaluator"}],"title":"TimedCaptureEvaluator","navigatorTitle":[{"kind":"identifier","text":"TimedCaptureEvaluator"}],"url":"\/documentation\/dotpalmcore\/timedcaptureevaluator","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TimedCaptureEvaluator","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"url":"\/documentation\/dotpalmcore\/dotlibraryid","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"title":"DotLibraryId"},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"url":"\/documentation\/dotpalmcore\/corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","title":"Corners","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"title":"BgrRawImage","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"url":"\/documentation\/dotpalmcore\/bgrrawimage","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModuleId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId","url":"\/documentation\/dotpalmcore\/dotpalmmoduleid","title":"DotPalmModuleId","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/camerafacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","title":"CameraFacing","type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImagePropertiesAnalyzerFactory":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImagePropertiesAnalyzerFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImagePropertiesAnalyzerFactory"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/imagepropertiesanalyzerfactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImagePropertiesAnalyzerFactory","title":"ImagePropertiesAnalyzerFactory","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","title":"DotSdkConfiguration","role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"kind":"symbol"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","title":"Sensor Coordinate System","type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotPalmCore/documentation/DotPalmCore/CameraPreviewScaleType":{"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","url":"\/documentation\/dotpalmcore\/camerapreviewscaletype"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerConfiguration":{"role":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerConfiguration"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerconfiguration","title":"DOTPPalmAutoCaptureControllerConfiguration","abstract":[{"type":"text","text":"Configuration of the palm auto capture non-UI component."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"title":"DotSdkLicenseProxyProtocol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotCameraVersionNumber":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCameraVersionNumber","title":"DotCameraVersionNumber","url":"\/documentation\/dotpalmcore\/dotcameraversionnumber","role":"symbol","fragments":[{"text":"DotCameraVersionNumber","kind":"identifier"}],"abstract":[{"type":"text","text":"Project version number for DotCamera."}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat":{"title":"WrappedFloat","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/wrappedfloat","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"url":"\/documentation\/dotpalmcore\/wrappeddouble","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","kind":"symbol","type":"topic","title":"WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibrary":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotlibrary","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"title":"ImageSize","url":"\/documentation\/dotpalmcore\/imagesize","role":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/TiltAngles":{"url":"\/documentation\/dotpalmcore\/tiltangles","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"kind":"symbol","abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"text":"Also see ","type":"text"},{"isActive":true,"type":"reference","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles","type":"topic","title":"TiltAngles","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/InstructionStyle":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/InstructionStyle","url":"\/documentation\/dotpalmcore\/instructionstyle","title":"InstructionStyle","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"InstructionStyle","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"InstructionStyle"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSerializationVersionString":{"fragments":[{"kind":"identifier","text":"DotSerializationVersionString"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSerializationVersionString","title":"DotSerializationVersionString","abstract":[{"text":"Project version string for DotSerialization.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotserializationversionstring","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","title":"DOTPPalmDetectorPalm"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmCoreVersionNumber":{"abstract":[{"type":"text","text":"Project version number for DotPalmCore."}],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DotPalmCoreVersionNumber"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmCoreVersionNumber","title":"DotPalmCoreVersionNumber","url":"\/documentation\/dotpalmcore\/dotpalmcoreversionnumber"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotsdk","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/VideoRecordingHandler":{"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"VideoRecordingHandler","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/VideoRecordingHandler","navigatorTitle":[{"kind":"identifier","text":"VideoRecordingHandler"}],"url":"\/documentation\/dotpalmcore\/videorecordinghandler","type":"topic","role":"symbol","title":"VideoRecordingHandler","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotCameraVersionString":{"kind":"symbol","abstract":[{"type":"text","text":"Project version string for DotCamera."}],"fragments":[{"kind":"identifier","text":"DotCameraVersionString"}],"title":"DotCameraVersionString","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCameraVersionString","url":"\/documentation\/dotpalmcore\/dotcameraversionstring","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"type":"topic","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","role":"symbol","title":"PointDouble","url":"\/documentation\/dotpalmcore\/pointdouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"type":"topic","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"url":"\/documentation\/dotpalmcore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"type":"topic","title":"IntervalDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult":{"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureControllerProcessingResult"}],"title":"DOTPPalmAutoCaptureControllerProcessingResult","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","kind":"symbol","type":"topic","abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","kind":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage","title":"BgraRawImage"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmModule":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmModule"}],"navigatorTitle":[{"text":"DotPalmModule","kind":"identifier"}],"title":"DotPalmModule","url":"\/documentation\/dotpalmcore\/dotpalmmodule","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module."}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderCandidateSelectionStyle":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlaceholderCandidateSelectionStyle"}],"url":"\/documentation\/dotpalmcore\/placeholdercandidateselectionstyle","navigatorTitle":[{"kind":"identifier","text":"PlaceholderCandidateSelectionStyle"}],"title":"PlaceholderCandidateSelectionStyle","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderCandidateSelectionStyle","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotCoreVersionString":{"abstract":[{"text":"Project version string for DotCore.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCoreVersionString","url":"\/documentation\/dotpalmcore\/dotcoreversionstring","role":"symbol","kind":"symbol","fragments":[{"text":"DotCoreVersionString","kind":"identifier"}],"title":"DotCoreVersionString","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat","title":"IntervalFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/DefaultTimedCaptureEvaluator":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DefaultTimedCaptureEvaluator","title":"DefaultTimedCaptureEvaluator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DefaultTimedCaptureEvaluator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/defaulttimedcaptureevaluator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DefaultTimedCaptureEvaluator"}],"type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmCoreVersionString":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotpalmcoreversionstring","title":"DotPalmCoreVersionString","role":"symbol","fragments":[{"text":"DotPalmCoreVersionString","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmCoreVersionString","kind":"symbol","abstract":[{"type":"text","text":"Project version string for DotPalmCore."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":[{"title":"DotPalm modularization","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModule","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmModuleId"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Logger","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Localization"],"title":"Global components"},{"title":"UI components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]},{"title":"Non-UI components","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]},{"title":"Converting images","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]},{"title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerSample","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureStyle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholdPresets","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholds","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPQualityAttributeThresholdsBuilder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TiltAngles","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"]},{"title":"Protocols","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibrary","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"]},{"title":"Variables","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCameraVersionNumber","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCameraVersionString","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCaptureVersionNumber","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCaptureVersionString","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCoreVersionNumber","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotCoreVersionString","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmCoreVersionNumber","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmCoreVersionString","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSerializationVersionNumber","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSerializationVersionString"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraPreviewScaleType","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"],"title":"Enumerations"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","value":"DotPalmLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","op":"replace","value":[{"text":"DotPalmLibrary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/title","value":"DOTPLocalization","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPLocalization"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Localization\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/title","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/fragments"},{"value":"DOTPLogger","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Logger\/fragments","value":[{"text":"DOTPLogger","kind":"identifier"}],"op":"replace"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"value":"DOTPPalmAutoCapturePhase","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title","value":"DOTCorners","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"value":"DotPalmModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModuleId\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments"},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/fragments","value":[{"text":"DotSdkConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibrary\/fragments","op":"replace"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/title","value":"DOTTiltAngles","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"text":"DOTPPalmDetector","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"value":"DotPalmModule","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmModule\/fragments","op":"replace","value":[{"text":"DotPalmModule","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}