{"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxDevicePitchAngle:error:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"maxDevicePitchAngle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","text":"DOTWrappedFloat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"maxDevicePitchAngle"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/maxdevicepitchangle:error:"]}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder(im)maxDevicePitchAngle:error:","navigatorTitle":[{"text":"maxDevicePitchAngle:error:","kind":"identifier"}],"title":"maxDevicePitchAngle:error:","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"maxDevicePitchAngle:error:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/WrappedFloat":{"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"url":"\/documentation\/dotfacelite\/wrappedfloat","type":"topic","title":"WrappedFloat","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder/maxDevicePitchAngle:error:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"maxDevicePitchAngle:error:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxDevicePitchAngle:error:","kind":"symbol","title":"maxDevicePitchAngle:error:","abstract":[],"url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/maxdevicepitchangle:error:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"maxDevicePitchAngle:error:"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.1.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder":{"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","title":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTWrappedFloat","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/title"},{"op":"replace","value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/fragments"},{"op":"replace","value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/navigatorTitle"}]}]}