{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/sizeinterval:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder(im)sizeInterval:error:","roleHeading":"Instance Method","symbolKind":"method","role":"symbol","title":"sizeInterval:error:","navigatorTitle":[{"text":"sizeInterval:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"sizeInterval:error:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sizeInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sizeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder":{"abstract":[],"type":"topic","title":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","fragments":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder/sizeInterval:error:":{"abstract":[],"type":"topic","title":"sizeInterval:error:","navigatorTitle":[{"text":"sizeInterval:error:","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/sizeinterval:error:","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:","fragments":[{"text":"- ","kind":"text"},{"text":"sizeInterval:error:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/IntervalDouble":{"type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/intervaldouble","title":"IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/fragments"},{"op":"replace","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1IntervalDouble\/navigatorTitle"}]}]}