{"variants":[{"paths":["\/documentation\/dotfacelite\/imageparameters\/brightness"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imageparameters\/brightness"]}],"metadata":{"title":"brightness","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters(py)brightness","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters\/brightness","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}],"kind":"declarations"}],"abstract":[{"text":"Overall brightness of the face in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness.","type":"text"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageParameters/brightness":{"kind":"symbol","title":"brightness","url":"\/documentation\/dotfacelite\/imageparameters\/brightness","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters\/brightness","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"abstract":[{"text":"Overall brightness of the face in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageParameters":{"url":"\/documentation\/dotfacelite\/imageparameters","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"abstract":[{"text":"Parameters of the image which was used for the face detection.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageParameters","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","type":"topic","url":"\/documentation\/dotfacelite\/facedetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"brightness","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"brightness"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"brightness","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters~1brightness\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters~1brightness\/fragments","value":[{"text":"brightness","kind":"identifier"}]},{"op":"replace","value":"DOTFLImageParameters","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLImageParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}]}]}]}