{"abstract":[{"type":"text","text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to "},{"type":"codeVoice","code":"0"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"candidateSelectionDurationMillis","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)candidateSelectionDurationMillis","roleHeading":"Instance Property","navigatorTitle":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/candidateSelectionDurationMillis"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/candidateselectiondurationmillis"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/candidateselectiondurationmillis"]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/candidateSelectionDurationMillis":{"abstract":[{"text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to ","type":"text"},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}],"title":"candidateSelectionDurationMillis","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","type":"topic","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/candidateselectiondurationmillis","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"title":"AutoCaptureConfiguration","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","op":"add","value":null},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"candidateSelectionDurationMillis","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/title","op":"replace","value":"candidateSelectionDurationMillis"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/fragments","op":"replace","value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}]},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle"}]}]}