{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/hash"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"hash"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/hash","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","kind":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"title":"AutoCaptureConfiguration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/hash":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/hash","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"title":"hash"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"hash","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1hash\/title"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1hash\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}