{"metadata":{"role":"symbol","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(im)initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","navigatorTitle":[{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","symbolKind":"init","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"}],"title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration for auto capture components."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/title","op":"replace","value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}