{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/LocalizedError-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.helpAnchor","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/intervalfloat\/error\/helpanchor"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"platforms":[{"name":"iOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0"},{"name":"iPadOS","unavailable":false,"beta":false,"deprecated":false,"introducedAt":"8.0"},{"beta":false,"introducedAt":"8.0","name":"Mac Catalyst","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"10.10","name":"macOS","deprecated":false,"unavailable":false},{"beta":false,"introducedAt":"9.0","name":"tvOS","deprecated":false,"unavailable":false},{"name":"watchOS","unavailable":false,"introducedAt":"2.0","deprecated":false,"beta":false}],"roleHeading":"Instance Property","extendedModule":"Foundation","modules":[{"name":"DotPalmCore","relatedModules":["Foundation"]}],"externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","title":"helpAnchor","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/helpAnchor","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","title":"IntervalFloat.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/intervalfloat\/error","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/helpAnchor":{"url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/helpanchor","kind":"symbol","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/helpAnchor","type":"topic","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/LocalizedError-Implementations":{"kind":"article","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/LocalizedError-Implementations","url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/localizederror-implementations","title":"LocalizedError Implementations","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","title":"IntervalFloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","url":"\/documentation\/dotpalmcore\/intervalfloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle"}]}]}