{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/ciimagefactory\/create(image:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory\/create(image:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"Image","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}],"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}]}]}]},{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithImage:","title":"create(image:)","modules":[{"name":"DotFaceCore"}],"symbolKind":"method","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}]},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory":{"type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"title":"CIImageFactory","kind":"symbol","url":"\/documentation\/dotfacecore\/ciimagefactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/CIImageFactory/create(image:)":{"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CIImageFactory\/create(image:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" object.","type":"text"}],"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/ciimagefactory\/create(image:)","title":"create(image:)","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"type":"topic","abstract":[],"title":"Image","kind":"symbol","url":"\/documentation\/dotfacecore\/image","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createWithImage:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithImage:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithImage:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory~1create(image:)\/title","value":"createWithImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CIImageFactory~1create(image:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}