{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"metadata":{"roleHeading":"Instance Method","modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"title":"mirrored()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"symbolKind":"method","extendedModule":"DotCore","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)mirrored","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/mirrored()"},"variants":[{"paths":["\/documentation\/dotdocument\/corners\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/corners\/mirrored()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/Corners":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotdocument\/corners","type":"topic","title":"Corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}]},"doc://DotDocument/documentation/DotDocument/Corners/mirrored()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"mirrored()","abstract":[],"url":"\/documentation\/dotdocument\/corners\/mirrored()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/mirrored()"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"mirrored","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"DOTCorners"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"mirrored"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","value":"mirrored","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1mirrored()\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"mirrored"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1mirrored()\/fragments"}]}]}