{"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","title":"LocalizedError Implementations","role":"collectionGroup"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/failureReason","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/helpAnchor","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/recoverySuggestion"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/LocalizedError-Implementations"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/localizederror-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error"]]},"references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/failureReason":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/failureReason","abstract":[],"title":"failureReason","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/failurereason"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"title":"NfcTravelDocumentReader","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/recoverySuggestion":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/recoverysuggestion","role":"symbol","title":"recoverySuggestion","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/helpAnchor":{"kind":"symbol","title":"helpAnchor","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/helpAnchor","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/helpanchor"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","abstract":[],"title":"CardAccessNumberPassword.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"title":"CardAccessNumberPassword","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CardAccessNumberPassword"}],"navigatorTitle":[{"kind":"identifier","text":"CardAccessNumberPassword"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNCardAccessNumberPassword"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle"}]}]}