{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/defaults\/camerafacing"]}],"metadata":{"modules":[{"name":"DotFaceCore"}],"title":"cameraFacing","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"cameraFacing","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing"}],"roleHeading":"Type Property","platforms":[],"role":"symbol","externalID":"s:11DotFaceCore0B27SimpleCaptureViewControllerC13ConfigurationC8DefaultsV12cameraFacing0A6Camera0lK0OvpZ"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/Defaults"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/Defaults\/cameraFacing","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class/Defaults":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"role":"symbol","title":"FaceSimpleCaptureViewController.Configuration.Defaults","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/Defaults","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/defaults","kind":"symbol","deprecated":true,"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"kind":"symbol","deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","title":"FaceSimpleCaptureViewController","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class":{"abstract":[{"type":"text","text":"Configuration options for the face simple capture process."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class","role":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class","deprecated":true,"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","title":"FaceSimpleCaptureViewController.Configuration"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 8.15.2","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Configuration-swift.class/Defaults/cameraFacing":{"title":"cameraFacing","kind":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/configuration-swift.class\/defaults\/camerafacing","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Configuration-swift.class\/Defaults\/cameraFacing","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraFacing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"deprecated":true,"type":"topic","abstract":[],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraFacing","title":"CameraFacing","url":"\/documentation\/dotfacecore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraFacing\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}