{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segmentDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment","text":"Segment"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/segmentsgenerator\/generate(segmentcount:segmentdurationmillis:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/segmentsgenerator\/generate(segmentcount:segmentdurationmillis:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator\/generate(segmentCount:segmentDurationMillis:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}],"role":"symbol","title":"generate(segmentCount:segmentDurationMillis:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segmentDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment"},{"kind":"text","text":"]"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFSegmentsGenerator(im)generateWithSegmentCount:segmentDurationMillis:","required":true,"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SegmentsGenerator/generate(segmentCount:segmentDurationMillis:)":{"navigatorTitle":[{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}],"role":"symbol","title":"generate(segmentCount:segmentDurationMillis:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"segmentCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"segmentDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","text":"Segment","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSegment"},{"kind":"text","text":"]"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator\/generate(segmentCount:segmentDurationMillis:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/segmentsgenerator\/generate(segmentcount:segmentdurationmillis:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Segment":{"role":"symbol","title":"Segment","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Segment"}],"abstract":[{"type":"text","text":"Eye gaze liveness segment representing the position on the screen which should be watched by the user for the specified duration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Segment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Segment"}],"url":"\/documentation\/dotfacecore\/segment"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/SegmentsGenerator":{"role":"symbol","title":"SegmentsGenerator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SegmentsGenerator"}],"abstract":[{"type":"text","text":"Generates segments for the eye gaze liveness process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/SegmentsGenerator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SegmentsGenerator"}],"url":"\/documentation\/dotfacecore\/segmentsgenerator"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"role":"symbol","title":"EyeGazeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 6.2.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"generateWithSegmentCount:segmentDurationMillis:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSArray<DOTFSegment *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"generateWithSegmentCount:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"segmentCount"},{"kind":"text","text":" "},{"kind":"identifier","text":"segmentDurationMillis:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"segmentDurationMillis"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator~1generate(segmentCount:segmentDurationMillis:)\/title","value":"generateWithSegmentCount:segmentDurationMillis:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator~1generate(segmentCount:segmentDurationMillis:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"generateWithSegmentCount:segmentDurationMillis:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/title","value":"DOTFSegment"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Segment\/fragments","value":[{"kind":"identifier","text":"DOTFSegment"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator\/title","value":"DOTFSegmentsGenerator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1SegmentsGenerator\/fragments","value":[{"kind":"identifier","text":"DOTFSegmentsGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}