{"kind":"article","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/Equatable-Implementations"},"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/!=(_:_:)"],"generated":true}],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotfacemoduleid\/equatable-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId"]]},"references":{"doc://DotNfc/documentation/DotNfc/DotFaceModuleId":{"url":"\/documentation\/dotnfc\/dotfacemoduleid","kind":"symbol","type":"topic","title":"DotFaceModuleId","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceModuleId/!=(_:_:)":{"kind":"symbol","type":"topic","title":"!=(_:_:)","url":"\/documentation\/dotnfc\/dotfacemoduleid\/!=(_:_:)","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceModuleId\/!=(_:_:)"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceModuleId\/navigatorTitle"}]}]}