{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory\/create(image:)"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"createWithImage:"}],"externalID":"c:@M@DotCore@objc(cs)DOTCIImageFactory(cm)createWithImage:","symbolKind":"method","roleHeading":"Type Method","modules":[{"name":"DotFingersCore"}],"title":"create(image:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"image"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Input image as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object.","type":"text"}],"type":"paragraph"}],"name":"image"}]},{"kind":"content","content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" instance.","type":"text"}]}]}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/ciimagefactory\/create(image:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/ciimagefactory\/create(image:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/CIImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfingerscore\/ciimagefactory","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory","title":"CIImageFactory","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CIImageFactory/create(image:)":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"}],"navigatorTitle":[{"text":"createWithImage:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/ciimagefactory\/create(image:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory\/create(image:)","title":"create(image:)","role":"symbol","type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createWithImage:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTCIImageFactory","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/title"},{"op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/fragments"},{"op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle"},{"value":"createWithImage:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory~1create(image:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory~1create(image:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithImage:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}