{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/composeWithInternalError()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"type":"text","text":"."}],"metadata":{"title":"composeWithInternalError()","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","symbolKind":"method","extendedModule":"DotCore","roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]}],"kind":"declarations"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"title":"AutoCaptureConfiguration","url":"\/documentation\/dotdocument\/autocaptureconfiguration","role":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/composeWithInternalError()":{"url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/composewithinternalerror()","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/composeWithInternalError()","abstract":[],"title":"composeWithInternalError()","role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/DotSdkError-Implementations":{"kind":"article","type":"topic","title":"DotSdkError Implementations","role":"collectionGroup","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/dotsdkerror-implementations","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","abstract":[]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","title":"AutoCaptureConfiguration.Error","abstract":[],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}