{"sections":[],"metadata":{"externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","extendedModule":"DotCore","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.description"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/error\/description"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","title":"AutoCaptureConfiguration.Error","role":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","title":"AutoCaptureConfiguration","role":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/description":{"title":"description","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/description","kind":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTAutoCaptureConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}