{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.failureReason"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/error\/failurereason"]}],"metadata":{"title":"failureReason","externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","extendedModule":"Foundation","symbolKind":"property","modules":[{"relatedModules":["Foundation"],"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"8.0","name":"iOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"8.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"8.0","name":"Mac Catalyst"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"10.10","name":"macOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"9.0","name":"tvOS"},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"2.0","name":"watchOS"}],"roleHeading":"Instance Property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/failureReason"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","role":"collectionGroup","type":"topic","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations","kind":"article","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/localizederror-implementations"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","title":"AutoCaptureConfiguration.Error","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"title":"AutoCaptureConfiguration","url":"\/documentation\/dotdocument\/autocaptureconfiguration","role":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/failureReason":{"abstract":[],"kind":"symbol","title":"failureReason","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/failureReason","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/failurereason"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.1.1"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}