{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"symbolKind":"case","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","roleHeading":"Case","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCandidateSelectionDurationMillis"}],"externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO39invalidCandidateSelectionDurationMillisyA2EmF","role":"symbol"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"role":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error":{"type":"topic","title":"AutoCaptureConfiguration.Error","kind":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[]},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"role":"symbol","url":"\/documentation\/dotdocument\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]}]}]}