{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"inlineContent":[{"text":"The process remains in a waiting state until the ","type":"text"},{"type":"codeVoice","code":"requestCapture()"},{"text":" call is invoked, signaling the request of the capture event.","type":"text"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeWaitForRequest","modules":[{"name":"DotFaceLite"}],"title":"CaptureMode.waitForRequest","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"symbolKind":"case","roleHeading":"Case"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/waitForRequest"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Wait for request mode (manual mode).","type":"text"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"type":"topic","url":"\/documentation\/dotfacelite\/capturemode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"title":"CaptureMode","abstract":[{"text":"Capture mode.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode/waitForRequest":{"role":"symbol","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode\/waitForRequest","url":"\/documentation\/dotfacelite\/capturemode\/waitforrequest","kind":"symbol","type":"topic","title":"CaptureMode.waitForRequest"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTCaptureModeWaitForRequest"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCaptureMode","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1waitForRequest\/title","value":"DOTCaptureModeWaitForRequest","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode~1waitForRequest\/fragments"}]}]}