{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/errorDescription"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Instance Property","title":"errorDescription","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"s:11DotDocument9MrzReaderC12ReadingErrorC16errorDescriptionSSSgvp"},"variants":[{"paths":["\/documentation\/dotdocument\/mrzreader\/readingerror\/errordescription"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 9.1.1","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument","role":"collection","title":"DotDocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}]},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ReadingError","kind":"identifier"}],"navigatorTitle":[{"text":"ReadingError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful."}],"title":"MrzReader.ReadingError","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/readingerror"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError/errorDescription":{"abstract":[],"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError\/errorDescription","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/readingerror\/errordescription","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}