{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytesPointerPacked","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointerPacked"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"bytesPointerPacked","symbolKind":"property","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointerPacked"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt32","preciseIdentifier":"s:s6UInt32V","kind":"typeIdentifier"},{"text":"> { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrarawimage\/bytespointerpacked"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrarawimage\/bytespointerpacked"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointerPacked"},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"kind":"symbol","type":"topic","title":"DotNfc","url":"\/documentation\/dotnfc","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","role":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","kind":"symbol","url":"\/documentation\/dotnfc\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://DotNfc/documentation/DotNfc/BgraRawImage/bytesPointerPacked":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s6UInt32V","text":"UInt32","kind":"typeIdentifier"},{"text":">","kind":"text"}],"abstract":[],"type":"topic","role":"symbol","navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"url":"\/documentation\/dotnfc\/bgrarawimage\/bytespointerpacked","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointerPacked","title":"bytesPointerPacked","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bytesPointerPacked"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"bytesPointerPacked"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"uint32_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@uint32_t"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bytesPointerPacked"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointerPacked\/title","op":"replace","value":"bytesPointerPacked"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointerPacked\/fragments","value":[{"kind":"identifier","text":"bytesPointerPacked"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}