{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules"]]},"metadata":{"title":"eyeGazeLiveness","roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)eyeGazeLiveness","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"navigatorTitle":[{"kind":"identifier","text":"eyeGazeLiveness"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" * "},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/eyegazeliveness"]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules/eyeGazeLiveness":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","type":"topic","fragments":[{"kind":"identifier","text":"eyeGazeLiveness"}],"title":"eyeGazeLiveness","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/eyegazeliveness","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"role":"symbol","title":"DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration":{"role":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}