{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/passiveLiveness","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)passiveLiveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}],"title":"passiveLiveness","roleHeading":"Instance Property","navigatorTitle":[{"text":"passiveLiveness","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/passiveliveness"]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules/passiveLiveness":{"title":"passiveLiveness","fragments":[{"text":"passiveLiveness","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/passiveliveness","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/passiveLiveness"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"role":"symbol","title":"DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFacePassiveLivenessModuleConfiguration":{"title":"DotFacePassiveLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face passive liveness module."}],"url":"\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFacePassiveLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"}]}]}