{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/errorDescription","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/LocalizedError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"type":"text","text":"."}],"sections":[],"metadata":{"title":"errorDescription","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorDescription"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"extendedModule":"DotCore","role":"symbol","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"roleHeading":"Instance Property","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:6DotNfc24CardAccessNumberPasswordC5ErrorO"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/errordescription"]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"role":"symbol","title":"CardAccessNumberPassword.Error"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","role":"symbol","abstract":[{"text":"Card Access Number as a password.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"title":"CardAccessNumberPassword","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/LocalizedError-Implementations":{"kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/localizederror-implementations"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword/Error/errorDescription":{"title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword\/Error\/errorDescription","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/cardaccessnumberpassword\/error\/errordescription"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title"},{"op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}