{"abstract":[{"type":"text","text":"Left edge."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/left"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/left"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"left","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)left","role":"symbol","navigatorTitle":[{"text":"left","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/left"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/RectangleDouble/left":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"left","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Left edge.","type":"text"}],"title":"left","url":"\/documentation\/dotnfc\/rectangledouble\/left","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/left"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","role":"collection","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotnfc\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"role":"symbol","title":"RectangleDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"left","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"left"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1left\/title","value":"left","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1left\/fragments","value":[{"text":"left","kind":"identifier"}],"op":"replace"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/navigatorTitle"}]}]}