{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/points"]},{"paths":["\/documentation\/dotnfc\/rectangledouble\/points"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"kind":"text","text":"] { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble"]]},"metadata":{"symbolKind":"property","title":"points","externalID":"c:@CM@DotNfc@objc(cs)DOTRectangleDouble(py)points","navigatorTitle":[{"kind":"identifier","text":"points"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property"},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble\/points","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble":{"title":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/RectangleDouble/points":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble\/points","kind":"symbol","title":"points","url":"\/documentation\/dotnfc\/rectangledouble\/points","type":"topic","navigatorTitle":[{"text":"points","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"role":"symbol","abstract":[]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/RectangleDouble":{"url":"\/documentation\/dotnfc\/rectangledouble","type":"topic","title":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"points"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"points"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTPointDouble *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"points"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble~1points\/title","value":"points"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble~1points\/fragments","value":[{"text":"points","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}