{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/rebased(parentRectangle:)"},"sections":[],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"symbolKind":"method","title":"rebased(parentRectangle:)","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(im)rebasedWithParentRectangle:","extendedModule":"DotCore","roleHeading":"Instance Method","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/rebased(parentrectangle:)"]},{"paths":["\/documentation\/dotnfc\/rectangledouble\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"]]},"references":{"doc://DotNfc/documentation/DotNfc/RectangleDouble/rebased(parentRectangle:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"abstract":[],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble\/rebased(parentRectangle:)","title":"rebased(parentRectangle:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/rectangledouble\/rebased(parentrectangle:)"},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotnfc\/rectangledouble","kind":"symbol","title":"RectangleDouble"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.8.0"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble"},{"text":" *) ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"text":"parentRectangle","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"rebasedWithParentRectangle:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1rebased(parentRectangle:)\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"op":"replace"},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}