{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/tiltangles\/init(pitch:)"]},{"paths":["\/documentation\/dotdocument\/tiltangles\/init(pitch:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"pitch","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPitch:"}],"role":"symbol","symbolKind":"init","externalID":"c:@M@DotCapture@objc(cs)DOTTiltAngles(im)initWithPitch:","title":"init(pitch:)","modules":[{"name":"DotDocument"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles\/init(pitch:)"},"references":{"doc://DotDocument/documentation/DotDocument/TiltAngles":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TiltAngles","kind":"identifier"}],"abstract":[{"type":"text","text":"Tilt angles."},{"text":" ","type":"text"},{"text":"Also see ","type":"text"},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference"},{"text":".","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/tiltangles","role":"symbol","title":"TiltAngles","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}]},"doc://DotDocument/documentation/DotDocument/TiltAngles/init(pitch:)":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithPitch:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TiltAngles\/init(pitch:)","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/tiltangles\/init(pitch:)","title":"init(pitch:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"pitch","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"link","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.6.1"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","value":"initWithPitch:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"float","preciseIdentifier":"c:f","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"pitch","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"DOTTiltAngles","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles\/fragments","value":[{"text":"DOTTiltAngles","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles~1init(pitch:)\/title","op":"replace","value":"initWithPitch:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithPitch:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TiltAngles~1init(pitch:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}