{"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/init(width:height:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/cgSize","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/height","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/shorterSide","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/width"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculatePixelCount()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/isEqual(_:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/from(cgSize:)"],"title":"Type Methods"}],"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"title":"Conforms To"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"class","role":"symbol","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTImageSize","roleHeading":"Class","title":"ImageSize","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTImageSize) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"Image size in pixels."}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/imagesize"]},{"paths":["\/documentation\/dotnfc\/imagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/width":{"role":"symbol","abstract":[{"type":"text","text":"Image width in pixels."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"width"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/width","url":"\/documentation\/dotnfc\/imagesize\/width","kind":"symbol","type":"topic","title":"width"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/shorterSide":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shorterSide","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"navigatorTitle":[{"text":"shorterSide","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/shorterSide","url":"\/documentation\/dotnfc\/imagesize\/shorterside","kind":"symbol","type":"topic","title":"shorterSide"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/calculateWidthToHeightRatio()":{"role":"symbol","abstract":[{"text":"Calculate width to height ratio.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculateWidthToHeightRatio()","url":"\/documentation\/dotnfc\/imagesize\/calculatewidthtoheightratio()","kind":"symbol","type":"topic","title":"calculateWidthToHeightRatio()"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/from(cgSize:)":{"role":"symbol","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTImageSize"}],"navigatorTitle":[{"text":"fromCgSize:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/from(cgSize:)","url":"\/documentation\/dotnfc\/imagesize\/from(cgsize:)","kind":"symbol","type":"topic","title":"from(cgSize:)"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/height":{"role":"symbol","abstract":[{"type":"text","text":"Image height in pixels."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"height"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/height","url":"\/documentation\/dotnfc\/imagesize\/height","kind":"symbol","type":"topic","title":"height"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/calculatePixelCount()":{"role":"symbol","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"calculatePixelCount","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculatePixelCount()","url":"\/documentation\/dotnfc\/imagesize\/calculatepixelcount()","kind":"symbol","type":"topic","title":"calculatePixelCount()"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/description":{"role":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/description","url":"\/documentation\/dotnfc\/imagesize\/description","kind":"symbol","type":"topic","title":"description"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize":{"role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize","url":"\/documentation\/dotnfc\/imagesize","kind":"symbol","type":"topic","title":"ImageSize"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/init(width:height:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/init(width:height:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"height"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/imagesize\/init(width:height:)","type":"topic","abstract":[],"title":"init(width:height:)","navigatorTitle":[{"kind":"identifier","text":"initWithWidth:height:"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/cgSize":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/cgSize","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgSize","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"url":"\/documentation\/dotnfc\/imagesize\/cgsize","type":"topic","abstract":[],"title":"cgSize","navigatorTitle":[{"text":"cgSize","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/hash":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotnfc\/imagesize\/hash","type":"topic","abstract":[],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ImageSize/isEqual(_:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/imagesize\/isequal(_:)","type":"topic","abstract":[],"title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/cgSize","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/height","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/shorterSide","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/width"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculatePixelCount()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/init(width:height:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/isEqual(_:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ImageSize\/from(cgSize:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageSize"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1width\/title","value":"width"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1width\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"shorterSide","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1shorterSide\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1shorterSide\/fragments","value":[{"text":"shorterSide","kind":"identifier"}],"op":"replace"},{"value":"calculateWidthToHeightRatio","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculateWidthToHeightRatio()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculateWidthToHeightRatio()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"value":"fromCgSize:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1from(cgSize:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1from(cgSize:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]},{"op":"replace","value":"height","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1height\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1height\/fragments","op":"replace","value":[{"kind":"identifier","text":"height"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1calculatePixelCount()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1description\/title","op":"replace","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1description\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1init(width:height:)\/title","value":"initWithWidth:height:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1init(width:height:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithWidth:height:"}],"op":"replace"},{"value":"cgSize","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1cgSize\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1cgSize\/fragments","op":"replace","value":[{"text":"cgSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1hash\/title","value":"hash","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1hash\/fragments","op":"replace"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1isEqual(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ImageSize~1isEqual(_:)\/fragments","op":"replace"}]}]}