{"sections":[],"abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/logLevel"]},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/debug(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/error(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/info(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/warning(_:file:function:)"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization"],"generated":true,"title":"Global components"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNLogger) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/logger"]},{"paths":["\/documentation\/dotnfc\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"metadata":{"roleHeading":"Class","externalID":"c:@M@DotNfc@objc(cs)DOTNLogger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"class","title":"Logger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"platforms":[{"beta":false,"name":"iOS","introducedAt":"13.0","deprecated":false,"unavailable":false}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/logLevel":{"url":"\/documentation\/dotnfc\/logger\/loglevel","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"code":".none","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/logLevel","title":"logLevel","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LoggerLogLevel","preciseIdentifier":"c:@M@DotNfc@E@DOTLoggerLogLevel"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Localization":{"role":"symbol","url":"\/documentation\/dotnfc\/localization","title":"Localization","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Localization"}],"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/info(_:file:function:)":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"info"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"role":"symbol","title":"info(_:file:function:)","abstract":[],"kind":"symbol","url":"\/documentation\/dotnfc\/logger\/info(_:file:function:)","navigatorTitle":[{"text":"info:file:function:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/info(_:file:function:)","type":"topic"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/error(_:file:function:)":{"url":"\/documentation\/dotnfc\/logger\/error(_:file:function:)","abstract":[],"role":"symbol","navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/error(_:file:function:)","title":"error(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"function","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/debug(_:file:function:)":{"navigatorTitle":[{"text":"debug:file:function:","kind":"identifier"}],"url":"\/documentation\/dotnfc\/logger\/debug(_:file:function:)","type":"topic","abstract":[],"title":"debug(_:file:function:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/debug(_:file:function:)"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger":{"title":"Logger","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotnfc\/logger","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Logger","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/DotNfcLibrary":{"kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotnfc\/dotnfclibrary","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary","type":"topic","title":"DotNfcLibrary","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotNfcLibrary"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Logger/warning(_:file:function:)":{"url":"\/documentation\/dotnfc\/logger\/warning(_:file:function:)","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"warning:file:function:"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/warning(_:file:function:)","title":"warning(_:file:function:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"file"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTNLogger"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLogger"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTNLogger"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/logLevel"],"title":"Type Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/debug(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/error(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/info(_:file:function:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Logger\/warning(_:file:function:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/DotNfcLibrary","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTNLogger","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"logLevel","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1logLevel\/title","op":"replace"},{"value":[{"kind":"identifier","text":"logLevel"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1logLevel\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"text":"DOTNLocalization","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1info(_:file:function:)\/title","value":"info:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1info(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"info:file:function:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1error(_:file:function:)\/title","value":"error:file:function:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1error(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"error:file:function:","kind":"identifier"}]},{"value":"debug:file:function:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1debug(_:file:function:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"debug:file:function:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1debug(_:file:function:)\/fragments"},{"op":"replace","value":"DOTNLogger","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNLogger"}]},{"value":"DotNfcLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/title"},{"value":[{"kind":"identifier","text":"DotNfcLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1DotNfcLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1warning(_:file:function:)\/title","value":"warning:file:function:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Logger~1warning(_:file:function:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"warning:file:function:","kind":"identifier"}],"op":"replace"}]}]}