{"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/init(x:y:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/cgPoint","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/x","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/y"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/mirrored()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/from(cgPoint:)"],"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/pointdouble"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/pointdouble"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTPointDouble) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTPointDouble"},"references":{"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/isEqual(_:)":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/isequal(_:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/isEqual(_:)","title":"isEqual(_:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/y":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/y","title":"y","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/y","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"kind":"symbol","abstract":[{"type":"text","text":"Y coordinate."}],"navigatorTitle":[{"text":"y","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/rebased(parentRectangle:)":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/rebased(parentrectangle:)","title":"rebased(parentRectangle:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/rebased(parentRectangle:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/x":{"navigatorTitle":[{"kind":"identifier","text":"x"}],"title":"x","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"X coordinate."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/x","url":"\/documentation\/dotnfc\/pointdouble\/x","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble":{"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotnfc\/pointdouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","abstract":[{"text":"version: 8.5.0","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/mirrored()":{"title":"mirrored()","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/mirrored()","navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/mirrored()","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/hash":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/hash","title":"hash","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}]},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/init(x:y:)":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/init(x:y:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/init(x:y:)","title":"init(x:y:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/cgPoint":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/cgPoint","kind":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/cgpoint","type":"topic","abstract":[],"title":"cgPoint"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/description":{"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/description","title":"description","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble/from(cgPoint:)":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/from(cgPoint:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"}],"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble\/from(cgpoint:)","kind":"symbol","title":"from(cgPoint:)","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"abstract":[],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPointDouble","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/cgPoint","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/hash","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/x","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/y"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/init(x:y:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/mirrored()","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble\/from(cgPoint:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTPointDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1y\/title","op":"replace","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1y\/fragments","value":[{"text":"y","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1rebased(parentRectangle:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1x\/title","op":"replace","value":"x"},{"value":[{"text":"x","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1x\/fragments"},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1mirrored()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1mirrored()\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1hash\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"value":"initWithX:y:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1init(x:y:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1init(x:y:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithX:y:"}]},{"value":"cgPoint","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1cgPoint\/title"},{"value":[{"text":"cgPoint","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1cgPoint\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1description\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble~1from(cgPoint:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}