{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/detectionareaimagesize"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/detectionareaimagesize"]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"detectionAreaImageSize","kind":"identifier"}],"title":"detectionAreaImageSize","roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(py)detectionAreaImageSize","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/detectionAreaImageSize","interfaceLanguage":"swift"},"abstract":[{"text":"Image size of the detection area.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/detectionAreaImageSize":{"navigatorTitle":[{"kind":"identifier","text":"detectionAreaImageSize"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/detectionareaimagesize","title":"detectionAreaImageSize","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/detectionAreaImageSize","abstract":[{"type":"text","text":"Image size of the detection area."}],"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","title":"DocumentAutoCaptureFrameParameters","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}]},"doc://DotDocument/documentation/DotDocument/ImageSize":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","title":"ImageSize","role":"symbol","url":"\/documentation\/dotdocument\/imagesize","kind":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectionAreaImageSize","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"detectionAreaImageSize","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","text":"DOTImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":" * ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"},{"value":"detectionAreaImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1detectionAreaImageSize\/title"},{"value":[{"text":"detectionAreaImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1detectionAreaImageSize\/fragments"},{"value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle"},{"value":"DOTImageSize","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments"},{"value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}