{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/document"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/document"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","text":"Document"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/document","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detected document, or "},{"code":"nil","type":"codeVoice"},{"text":" if the document was not detected in the image.","type":"text"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":"?"}],"title":"document","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(py)document","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"document","kind":"identifier"}]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector\/document","title":"DocumentDetector.Document","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Result of the document detection process."}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureController","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"type":"topic","kind":"symbol","role":"symbol","title":"DOTDDocumentDetectorDocument","abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"kind":"symbol","type":"topic","title":"DocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/document":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"document","abstract":[{"type":"text","text":"Detected document, or "},{"type":"codeVoice","code":"nil"},{"text":" if the document was not detected in the image.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/document","navigatorTitle":[{"kind":"identifier","text":"document"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/document"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector","type":"topic","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"document"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"document","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"document"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"value":"document","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1document\/title"},{"value":[{"kind":"identifier","text":"document"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1document\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}