{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"text":".","kind":"text"},{"kind":"typeIdentifier","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"?, "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"mrzRecognitionResult","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","symbolKind":"init","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(im)initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","title":"init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:"}],"roleHeading":"Initializer"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},{"kind":"text","text":"."},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"mrzRecognitionResult"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"role":"symbol","title":"DOTDDocumentDetectorDocument","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorDocument"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","type":"topic","kind":"symbol","abstract":[{"text":"Result of the document detection process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(detectionareaimagesize:document:traveldocumenttype:mrzrecognitionresult:)","navigatorTitle":[{"text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":", ","kind":"text"},{"text":"document","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"text":"Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"mrzRecognitionResult","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult"},{"text":"?)","kind":"text"}],"role":"symbol","title":"init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)","type":"topic"},"doc://DotDocument/documentation/DotDocument/TravelDocumentTypeWrapper":{"title":"TravelDocumentTypeWrapper","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentTypeWrapper","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImageSize":{"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/imagesize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","title":"ImageSize"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","title":"DocumentDetector.Document","url":"\/documentation\/dotdocument\/documentdetector\/document","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Document","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Result of the document detection process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.15.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","kind":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","abstract":[{"text":"Information from the detection process about the detected document.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"role":"symbol","title":"DocumentAutoCaptureFrameParameters","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","url":"\/documentation\/dotdocument\/mrzrecognitionresult","title":"MrzRecognitionResult","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzRecognitionResult","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"MrzRecognitionResult","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetectionAreaImageSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"DOTImageSize","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageSize"},{"kind":"text","text":" *) "},{"text":"detectionAreaImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"document:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTDDocumentDetectorDocument","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"kind":"text","text":" "},{"text":"travelDocumentType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTTravelDocumentTypeWrapper","preciseIdentifier":"c:objc(cs)DOTTravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"travelDocumentType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mrzRecognitionResult:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","text":"DOTDMrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"mrzRecognitionResult","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(detectionAreaImageSize:document:travelDocumentType:mrzRecognitionResult:)\/fragments","op":"replace"},{"value":"DOTTravelDocumentTypeWrapper","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageSize\/fragments","op":"replace"},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace"},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title","op":"replace","value":"DOTDMrzRecognitionResult"},{"op":"replace","value":[{"text":"DOTDMrzRecognitionResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments"}]}]}