{"sections":[],"metadata":{"title":"mrzRecognitionResult","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mrzRecognitionResult"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","kind":"typeIdentifier","text":"MrzRecognitionResult"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"mrzRecognitionResult"}],"symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(py)mrzRecognitionResult"},"abstract":[{"type":"text","text":"Result of MRZ recognition."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/mrzRecognitionResult"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult","text":"MrzRecognitionResult","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/mrzrecognitionresult"]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/mrzrecognitionresult"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters/mrzRecognitionResult":{"abstract":[{"type":"text","text":"Result of MRZ recognition."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mrzRecognitionResult","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzRecognitionResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"mrzRecognitionResult","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/mrzRecognitionResult","role":"symbol","type":"topic","title":"mrzRecognitionResult","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/mrzrecognitionresult"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"title":"DocumentAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzRecognitionResult":{"abstract":[{"text":"The result of using OCR on the MRZ text.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzRecognitionResult"}],"navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","role":"symbol","type":"topic","title":"MrzRecognitionResult","kind":"symbol","url":"\/documentation\/dotdocument\/mrzrecognitionresult"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"mrzRecognitionResult","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"mrzRecognitionResult"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTDMrzRecognitionResult","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzRecognitionResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMrzRecognitionResult"},{"kind":"text","text":" * "},{"kind":"identifier","text":"mrzRecognitionResult"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"mrzRecognitionResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1mrzRecognitionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"mrzRecognitionResult"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1mrzRecognitionResult\/fragments"},{"op":"replace","value":"DOTDDocumentAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle"},{"op":"replace","value":"DOTDMrzRecognitionResult","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzRecognitionResult\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}