{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/debug"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/debug"]}],"metadata":{"title":"LoggerLogLevel.debug","roleHeading":"Case","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelDebug","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debug","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"Logs events suitable for debugging purposes."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/debug","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/debug":{"role":"symbol","title":"LoggerLogLevel.debug","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelDebug"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/debug","abstract":[{"text":"Logs events suitable for debugging purposes.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/debug","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTLoggerLogLevelDebug","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1debug\/title","value":"DOTLoggerLogLevelDebug","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1debug\/fragments","value":[{"text":"DOTLoggerLogLevelDebug","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}