{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/description"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/description"]}],"metadata":{"title":"description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore14LoggerLogLevelO11descriptionSSvp","symbolKind":"property","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"type":"text","text":"."}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/description":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description","url":"\/documentation\/dotfingerscore\/loggerloglevel\/description","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}]}]}