{"abstract":[{"text":"Logs informative events.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"title":"LoggerLogLevel.info","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelInfo","symbolKind":"case"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/info"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/info"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/info","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/info":{"role":"symbol","title":"LoggerLogLevel.info","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/info","abstract":[{"text":"Logs informative events.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"info"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/info","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTLoggerLogLevelInfo","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTLoggerLogLevelInfo","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1info\/title"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelInfo"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1info\/fragments"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}