{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/warning"]},{"paths":["\/documentation\/dotfingerscore\/loggerloglevel\/warning"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"metadata":{"title":"LoggerLogLevel.warning","navigatorTitle":[{"text":"DOTLoggerLogLevelWarning","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelWarning","symbolKind":"case","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"roleHeading":"Case","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/warning","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel/warning":{"role":"symbol","title":"LoggerLogLevel.warning","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"abstract":[{"type":"text","text":"Logs unexpected events which indicate malfunction."}],"url":"\/documentation\/dotfingerscore\/loggerloglevel\/warning","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel\/warning","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTLoggerLogLevelWarning","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTLoggerLogLevel","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle"},{"value":"DOTLoggerLogLevelWarning","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1warning\/title"},{"value":[{"kind":"identifier","text":"DOTLoggerLogLevelWarning"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel~1warning\/fragments"}]}]}