{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview\/cameraImage"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturepreview\/cameraimage"]},{"paths":["\/documentation\/dotpalmcore\/palmautocapturepreview\/cameraimage"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"For example, ","type":"text"},{"code":"RectangleDouble(left=0.0, top=0.25, right=1.0, bottom=0.75)","type":"codeVoice"},{"text":" means that the ","type":"text"},{"code":"cameraImage","type":"codeVoice"},{"text":" is positioned in the full width of the container,","type":"text"},{"text":" ","type":"text"},{"text":"but the height is shorter than the container height. This is typical for scale type ","type":"text"},{"code":"CameraPreviewScaleType.fit","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}],"kind":"content"}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview(py)cameraImage","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"cameraImage"}],"title":"cameraImage"},"abstract":[{"type":"text","text":"A rectangular region defined relative to the container where the camera image is displayed in the container."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/rectangledouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturepreview","title":"PalmAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview/cameraImage":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview\/cameraImage","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"abstract":[{"text":"A rectangular region defined relative to the container where the camera image is displayed in the container.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocapturepreview\/cameraimage","title":"cameraImage","type":"topic","navigatorTitle":[{"text":"cameraImage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cameraImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"cameraImage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cameraImage"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","op":"replace","value":"DOTPPalmAutoCapturePreview"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview~1cameraImage\/title","op":"replace","value":"cameraImage"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview~1cameraImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"cameraImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}