{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/defaultthreshold"]},{"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/defaultthreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/defaultThreshold","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"symbolKind":"property","role":"symbol","title":"defaultThreshold","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBrightnessTooHighValidator(cpy)defaultThreshold","roleHeading":"Type Property","navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Default threshold.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected palm."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/defaultThreshold":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/defaultThreshold","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/defaultthreshold","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"role":"symbol","title":"defaultThreshold","abstract":[{"text":"Default threshold.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"defaultThreshold","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"DOTPBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"value":"defaultThreshold","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1defaultThreshold\/title"},{"value":[{"kind":"identifier","text":"defaultThreshold"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1defaultThreshold\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}