{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebackgrounduniformity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebackgrounduniformity"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Background uniformity evaluation flag.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"evaluateBackgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"title":"evaluateBackgroundUniformity","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery(py)evaluateBackgroundUniformity","modules":[{"name":"DotFaceCore"}],"role":"symbol","navigatorTitle":[{"text":"evaluateBackgroundUniformity","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateBackgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBackgroundUniformity"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery/evaluateBackgroundUniformity":{"url":"\/documentation\/dotfacecore\/faceimagequalityquery\/evaluatebackgrounduniformity","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery\/evaluateBackgroundUniformity","title":"evaluateBackgroundUniformity","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluateBackgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"evaluateBackgroundUniformity","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Background uniformity evaluation flag.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/faceimagequalityquery","type":"topic","title":"FaceImageQualityQuery","abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"evaluateBackgroundUniformity"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"evaluateBackgroundUniformity"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateBackgroundUniformity"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBackgroundUniformity\/title","value":"evaluateBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery~1evaluateBackgroundUniformity\/fragments","value":[{"text":"evaluateBackgroundUniformity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]}]}]}