{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/balanced"]}],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Balanced","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face detection balanced module."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFaceDetectionModuleConfigurationBalanced) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Balanced\/init()"]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC8BalancedC","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"navigatorTitle":[{"text":"Balanced","kind":"identifier"}],"title":"DotFaceDetectionModuleConfiguration.Balanced"},"references":{"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration/Balanced/init()":{"role":"symbol","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/balanced\/init()","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Balanced\/init()","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.4.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"title":"DotFaceDetectionModuleConfiguration","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","role":"symbol","type":"topic","navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face detection module configuration."}]},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration/Balanced":{"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration\/balanced","type":"topic","abstract":[{"type":"text","text":"Face detection balanced module."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration\/Balanced","role":"symbol","title":"DotFaceDetectionModuleConfiguration.Balanced","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Balanced","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Balanced","kind":"identifier"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}]}]}