{"variants":[{"paths":["\/documentation\/dotfacecore\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgra"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}]}]},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"The 4 bytes of color image pixel:","type":"text"}]},{"type":"unorderedList","items":[{"content":[{"inlineContent":[{"type":"text","text":"0th byte: BB - blue"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"1st byte: GG - green","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"2nd byte: RR - red","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"3rd byte: 0  - alpha"}],"type":"paragraph"}]}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"case","roleHeading":"Case","title":"ImageFormat.rawBgra","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgra","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"role":"symbol","abstract":[{"type":"text","text":"Supported image formats."}],"title":"ImageFormat","type":"topic","url":"\/documentation\/dotfacecore\/imageformat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/rawBgra":{"url":"\/documentation\/dotfacecore\/imageformat\/rawbgra","title":"ImageFormat.rawBgra","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgra","role":"symbol","abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTImageFormatRawBgra","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title","value":"DOTImageFormat","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgra\/title","value":"DOTImageFormatRawBgra","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgra\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}