{"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?)"}],"title":"init(barcode:)","role":"symbol","symbolKind":"init","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAeA0ac13BarcodeModuleE0CSg_tcfc"},"references":{"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration":{"role":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration","type":"topic","title":"DotDocumentLibraryConfiguration","abstract":[{"text":"Document library configuration.","type":"text"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class":{"abstract":[{"type":"text","text":"Document library module configuration."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"title":"DotDocumentLibraryConfiguration.Modules","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotDocumentBarcodeModuleConfiguration":{"url":"\/documentation\/dotdocument\/dotdocumentbarcodemoduleconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentBarcodeModuleConfiguration","title":"DotDocumentBarcodeModuleConfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibraryConfiguration/Modules-swift.class/init(barcode:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibraryConfiguration\/Modules-swift.class\/init(barcode:)","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibraryconfiguration\/modules-swift.class\/init(barcode:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"barcode","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"abstract":[],"title":"init(barcode:)"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/fragments","value":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}