{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","title":"bundle","navigatorTitle":[{"kind":"identifier","text":"bundle"}],"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bundle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"Bundle"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLocalization(cpy)bundle","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/bundle","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/localization\/bundle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/localization\/bundle"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically "},{"code":"Bundle.main","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.0.2"}],"url":"\/documentation\/dotfacecore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Localization/bundle":{"kind":"symbol","role":"symbol","title":"bundle","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/bundle","url":"\/documentation\/dotfacecore\/localization\/bundle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"}],"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"code":"Bundle.main","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"bundle","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Localization":{"kind":"symbol","role":"symbol","title":"Localization","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization","url":"\/documentation\/dotfacecore\/localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"bundle","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bundle"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier","text":"NSBundle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bundle"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1bundle\/title","value":"bundle","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1bundle\/fragments","value":[{"text":"bundle","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/title","value":"DOTFLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTFLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/navigatorTitle","value":[{"text":"DOTFLocalization","kind":"identifier"}]}]}]}