{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"You also need to set "},{"type":"codeVoice","code":"useLocalizationDictionary"},{"type":"text","text":" flag to "},{"type":"codeVoice","code":"true"},{"text":".","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note","type":"aside"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/localizationDictionary"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLocalization(cpy)localizationDictionary","symbolKind":"property","title":"localizationDictionary","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"localizationDictionary","kind":"identifier"}]},"abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/localization\/localizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/localization\/localizationdictionary"]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/Localization/localizationDictionary":{"type":"topic","url":"\/documentation\/dotfacecore\/localization\/localizationdictionary","abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization\/localizationDictionary","kind":"symbol","title":"localizationDictionary","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}]},"doc://DotFaceCore/documentation/DotFaceCore/Localization":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfacecore\/localization","title":"Localization","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"localizationDictionary","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"localizationDictionary"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"localizationDictionary","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1localizationDictionary\/title"},{"op":"replace","value":[{"kind":"identifier","text":"localizationDictionary"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization~1localizationDictionary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/title","value":"DOTFLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTFLocalization"}]},{"value":[{"text":"DOTFLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Localization\/navigatorTitle"}]}]}