{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid\/backgrounduniformity"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId"]]},"kind":"symbol","metadata":{"symbolKind":"case","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotFaceModuleId@DotFaceModuleIdBackgroundUniformity","role":"symbol","title":"DotFaceModuleId.backgroundUniformity","navigatorTitle":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}]},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/backgroundUniformity","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/backgroundUniformity":{"role":"symbol","title":"DotFaceModuleId.backgroundUniformity","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/backgrounduniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/backgroundUniformity","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId":{"type":"topic","kind":"symbol","title":"DotFaceModuleId","url":"\/documentation\/dotfingerscore\/dotfacemoduleid","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleIdBackgroundUniformity","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleIdBackgroundUniformity","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1backgroundUniformity\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1backgroundUniformity\/fragments"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}