{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/Equatable-Implementations"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"kind":"article","topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/!=(_:_:)"],"generated":true,"title":"Operators","anchor":"Operators"}],"metadata":{"roleHeading":"API Collection","modules":[{"name":"DotPalmCore"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/capturemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/!=(_:_:)":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/!=(_:_:)","kind":"symbol","title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/capturemode\/!=(_:_:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode":{"type":"topic","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","kind":"symbol","title":"CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotpalmcore\/capturemode","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCaptureMode","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/title"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/fragments"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/navigatorTitle"}]}]}