{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"abstract":[{"type":"text","text":"Generates corners for the eye gaze liveness process."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFEyeGazeLivenessCornersGenerator) ","kind":"text"},{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessCornersGenerator"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator\/generate(count:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"EyeGazeLivenessCornersGenerator","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCornersGenerator"}],"roleHeading":"Protocol","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessCornersGenerator","role":"symbol","symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/RandomEyeGazeLivenessCornersGenerator":{"navigatorTitle":[{"kind":"identifier","text":"RandomEyeGazeLivenessCornersGenerator"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator","abstract":[{"text":"Generates random corners for the eye gaze liveness process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator","title":"RandomEyeGazeLivenessCornersGenerator"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCornersGenerator/generate(count:)":{"url":"\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator\/generate(count:)","required":true,"navigatorTitle":[{"text":"generateWithCount:","kind":"identifier"}],"title":"generate(count:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator\/generate(count:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":") -> ["},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessCornersGenerator":{"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessCornersGenerator"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator","abstract":[{"type":"text","text":"Generates corners for the eye gaze liveness process."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessCornersGenerator","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenesscornersgenerator","title":"EyeGazeLivenessCornersGenerator"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.9.0","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"DOTFEyeGazeLivenessCornersGenerator","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessCornersGenerator"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessCornersGenerator\/generate(count:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator"],"title":"Conforming Types","type":"conformingTypes"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFEyeGazeLivenessCornersGenerator"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFRandomEyeGazeLivenessCornersGenerator","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/fragments","value":[{"text":"DOTFRandomEyeGazeLivenessCornersGenerator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator~1generate(count:)\/title","value":"generateWithCount:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator~1generate(count:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"generateWithCount:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/title","value":"DOTFEyeGazeLivenessCornersGenerator"},{"value":[{"text":"DOTFEyeGazeLivenessCornersGenerator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessCornersGenerator\/fragments"}]}]}