{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidDisappear(_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":")","kind":"text"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewDidDisappear:","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"platforms":[],"externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewControllerViewDidDisappear:","title":"eyeGazeLivenessViewControllerViewDidDisappear(_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdiddisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdiddisappear(_:)"]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"text":": ","kind":"text"},{"text":"EyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","deprecated":true,"kind":"symbol","abstract":[{"text":"UI Eye Gaze Liveness component.","type":"text"}],"title":"EyeGazeLivenessViewController","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewControllerViewDidDisappear(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLivenessViewControllerViewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewControllerViewDidDisappear(_:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"eyeGazeLivenessViewControllerViewDidDisappear:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontrollerviewdiddisappear(_:)","type":"topic","title":"eyeGazeLivenessViewControllerViewDidDisappear(_:)","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"title":"EyeGazeLivenessViewControllerDelegate","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"deprecated":true}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"eyeGazeLivenessViewControllerViewDidDisappear:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidDisappear:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"DOTFEyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFEyeGazeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle","op":"replace"},{"value":"eyeGazeLivenessViewControllerViewDidDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewControllerViewDidDisappear:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewControllerViewDidDisappear(_:)\/fragments","op":"replace"},{"value":"DOTFEyeGazeLivenessViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title","op":"replace"},{"value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","op":"replace"},{"value":[{"text":"DOTFEyeGazeLivenessViewControllerDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}