{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/facedetector\/init()"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/init()","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector"]]},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceDetector(im)init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","title":"init()","modules":[{"name":"DotFaceLite"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/facedetector","abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","title":"FaceDetector","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/init()":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/init()","kind":"symbol","type":"topic","title":"init()","url":"\/documentation\/dotfacelite\/facedetector\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace"}]}]}