{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails"]]},"metadata":{"platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"13.0","beta":false}],"title":"description","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails(py)description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails\/description"},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/optionaldetails\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/optionaldetails\/description"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails/description":{"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotnfc\/optionaldetails\/description","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"abstract":[],"title":"description","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","type":"topic","title":"TravelDocument","role":"symbol","abstract":[{"type":"text","text":"Result of NFC reading."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/OptionalDetails":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"OptionalDetails","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/OptionalDetails","role":"symbol","navigatorTitle":[{"text":"OptionalDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/optionaldetails","type":"topic","title":"OptionalDetails","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","role":"symbol","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","title":"NfcTravelDocumentReader","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"},{"value":"DOTNOptionalDetails","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/title"},{"value":[{"text":"DOTNOptionalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1OptionalDetails\/fragments"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}