{"sections":[],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"platforms":[{"name":"iOS","deprecated":false,"beta":false,"introducedAt":"13.0","unavailable":false}],"title":"init(content:)","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithContent:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNOptionalDetails(im)initWithContent:","modules":[{"name":"DotNfc"}],"symbolKind":"init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/optionaldetails\/init(content:)"]},{"paths":["\/documentation\/dotnfc\/optionaldetails\/init(content:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/init(content:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/OptionalDetails/init(content:)":{"abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"content"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails\/init(content:)","url":"\/documentation\/dotnfc\/optionaldetails\/init(content:)","kind":"symbol","title":"init(content:)","navigatorTitle":[{"kind":"identifier","text":"initWithContent:"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"type":"topic","title":"TravelDocument","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","role":"symbol","url":"\/documentation\/dotnfc\/traveldocument"},"doc://DotNfc/documentation/DotNfc/OptionalDetails":{"type":"topic","abstract":[{"type":"text","text":"Contents of DG13 - Optional details."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"OptionalDetails","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/OptionalDetails","url":"\/documentation\/dotnfc\/optionaldetails","kind":"symbol","title":"OptionalDetails","navigatorTitle":[{"kind":"identifier","text":"OptionalDetails"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithContent:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithContent:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithContent:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"content"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"initWithContent:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1init(content:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails~1init(content:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithContent:","kind":"identifier"}],"op":"replace"},{"value":"DOTNTravelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/title","value":"DOTNOptionalDetails"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1OptionalDetails\/fragments","op":"replace","value":[{"text":"DOTNOptionalDetails","kind":"identifier"}]}]}]}