{"metadata":{"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)mouthRightCorner","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"mouthRightCorner"}],"title":"mouthRightCorner","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthRightCorner"},{"kind":"text","text":": "},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthrightcorner"]},{"paths":["\/documentation\/dotfacecore\/facekeypoints\/mouthrightcorner"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"abstract":[{"text":"Right corner of the mouth.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthRightCorner"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouthRightCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/mouthRightCorner":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/mouthRightCorner","kind":"symbol","navigatorTitle":[{"text":"mouthRightCorner","kind":"identifier"}],"title":"mouthRightCorner","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"mouthRightCorner","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"abstract":[{"text":"Right corner of the mouth.","type":"text"}],"url":"\/documentation\/dotfacecore\/facekeypoints\/mouthrightcorner","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","title":"FaceKeypoints","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"kind":"symbol","title":"FaceKeypoint","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","url":"\/documentation\/dotfacecore\/facekeypoint","abstract":[{"text":"Face Keypoint","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceKeypoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"mouthRightCorner","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"mouthRightCorner","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"mouthRightCorner"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthRightCorner\/title","op":"replace","value":"mouthRightCorner"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1mouthRightCorner\/fragments","value":[{"kind":"identifier","text":"mouthRightCorner"}]},{"op":"replace","value":"DOTFFaceKeypoints","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","op":"replace","value":"DOTFFaceKeypoint"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}