{"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"rightEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"rightEyeCenter","kind":"identifier"}],"symbolKind":"property","title":"rightEyeCenter","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints(py)rightEyeCenter"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeCenter","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Right eye center.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyecenter"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facekeypoints\/righteyecenter"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"FaceKeypoint"},{"text":"?","kind":"text"}]}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints/rightEyeCenter":{"kind":"symbol","title":"rightEyeCenter","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints\/rightEyeCenter","url":"\/documentation\/dotfacecore\/facekeypoints\/righteyecenter","abstract":[{"type":"text","text":"Right eye center."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"rightEyeCenter","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceKeypoint","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"rightEyeCenter","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"kind":"symbol","title":"FaceKeypoint","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","url":"\/documentation\/dotfacecore\/facekeypoint","abstract":[{"text":"Face Keypoint","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceKeypoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceKeypoints","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","navigatorTitle":[{"text":"FaceKeypoints","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facekeypoints","title":"FaceKeypoints","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"rightEyeCenter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"rightEyeCenter"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","text":"DOTFFaceKeypoint"},{"text":" * ","kind":"text"},{"text":"rightEyeCenter","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeCenter\/title","value":"rightEyeCenter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints~1rightEyeCenter\/fragments","value":[{"kind":"identifier","text":"rightEyeCenter"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","op":"replace","value":"DOTFFaceKeypoint"},{"op":"replace","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title","value":"DOTFFaceKeypoints"},{"value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace"}]}]}