{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDMrzReader) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzReader","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"modules":[{"name":"DotDocument"}],"role":"symbol","title":"MrzReader"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/mrzreader"]},{"paths":["\/documentation\/dotdocument\/mrzreader"],"traits":[{"interfaceLanguage":"occ"}]}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"],"title":"Non-UI components"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"],"title":"MRZ reading input"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"],"title":"Classes"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:document:travelDocumentType:)"],"title":"Instance Methods"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader/read(bgraRawImage:document:travelDocumentType:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentTypeWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTTravelDocumentTypeWrapper"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:11DotDocument9MrzReaderC6ResultC","kind":"typeIdentifier","text":"Result"}],"title":"read(bgraRawImage:document:travelDocumentType:)","navigatorTitle":[{"text":"readWithBgraRawImage:document:travelDocumentType:","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:document:travelDocumentType:)","url":"\/documentation\/dotdocument\/mrzreader\/read(bgrarawimage:document:traveldocumenttype:)","role":"symbol","abstract":[{"type":"text","text":"Read MRZ in an image and return the result."}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzElement":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","title":"MrzElement","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzelement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"type":"topic","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"abstract":[{"type":"text","text":"A "},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}],"title":"MrzElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"title":"DocumentDetector.Document","navigatorTitle":[{"text":"Document","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","url":"\/documentation\/dotdocument\/documentdetector\/document","role":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}],"type":"topic","kind":"symbol"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"kind":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"role":"symbol"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","title":"Td3MachineReadableZone","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td3MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"type":"topic","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}]},"doc://DotDocument/s7CVarArgP":{"identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzStringPosition":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition","url":"\/documentation\/dotdocument\/mrzstringposition","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"kind":"symbol","title":"MrzStringPosition"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNameElement","kind":"identifier"}],"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrznameelement","title":"MrzNameElement"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","role":"symbol","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","type":"topic","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","kind":"symbol"},"doc://DotDocument/SH":{"identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Result"}],"title":"MrzReader.Result","navigatorTitle":[{"kind":"identifier","text":"Result"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","url":"\/documentation\/dotdocument\/mrzreader\/result","role":"symbol","abstract":[{"type":"text","text":"MRZ reading result."}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DOTDMrzReader/init":{"kind":"symbol","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReader\/init","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotdmrzreader\/init","type":"topic"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone","role":"symbol","title":"Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"kind":"symbol","title":"TravelDocumentType","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocumentType","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentType"}],"url":"\/documentation\/dotdocument\/traveldocumenttype","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"title":"DocumentDetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","url":"\/documentation\/dotdocument\/documentdetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"type":"topic","role":"symbol"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/MrzReader/ReadingError":{"type":"topic","title":"MrzReader.ReadingError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ReadingError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/readingerror","abstract":[{"text":"Thrown if travel document type resolution, text recognition, or text parsing are unsuccessful.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/ReadingError","navigatorTitle":[{"text":"ReadingError","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"type":"topic","kind":"symbol","title":"ImagePerspectiveWarper","url":"\/documentation\/dotdocument\/imageperspectivewarper","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","role":"symbol","abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}]},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/ImageParametersAnalyzer":{"title":"ImageParametersAnalyzer","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/imageparametersanalyzer","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageParametersAnalyzer"}],"navigatorTitle":[{"text":"ImageParametersAnalyzer","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can analyze image parameters."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"A "},{"code":"MrzElementWithCheckDigit","type":"codeVoice"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"title":"MrzDateElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}]},"doc://DotDocument/documentation/DotDocument/MachineReadableZone":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}],"title":"MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone"},"doc://DotDocument/documentation/DotDocument/Td1MachineReadableZone":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","type":"topic","kind":"symbol","title":"Td1MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzDate":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","url":"\/documentation\/dotdocument\/mrzdate","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDate"}],"navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"kind":"symbol","title":"MrzDate"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"MRZ reading input","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td1MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDate","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzStringPosition"],"title":"MRZ reading output"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDMrzReader\/init","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/read(bgraRawImage:document:travelDocumentType:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"],"title":"Non-UI components","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDMrzReader","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"readWithBgraRawImage:document:travelDocumentType:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:document:travelDocumentType:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"readWithBgraRawImage:document:travelDocumentType:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader~1read(bgraRawImage:document:travelDocumentType:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"value":[{"kind":"identifier","text":"DOTMrzElement"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/title","value":"DOTMrzStringPosition"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzStringPosition\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"text":"DOTMrzNameElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","value":"DOTTravelDocumentType","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTravelDocumentType"}]},{"value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","value":"DOTDImageParametersAnalyzer","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}]},{"value":"DOTMachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/title","op":"replace","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/title","value":"DOTMrzDate"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTMrzDate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}