{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/!=(_:_:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/placeholdertype\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/Equatable-Implementations"]]},"metadata":{"symbolKind":"op","extendedModule":"Swift","roleHeading":"Operator","modules":[{"name":"DotPalmCore","relatedModules":["Swift"]}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol","title":"!=(_:_:)","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotPalmCore@E@DOTPPlaceholderType"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/Equatable-Implementations","url":"\/documentation\/dotpalmcore\/placeholdertype\/equatable-implementations","title":"Equatable Implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","title":"PlaceholderType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/placeholdertype","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/!=(_:_:)":{"type":"topic","title":"!=(_:_:)","abstract":[],"url":"\/documentation\/dotpalmcore\/placeholdertype\/!=(_:_:)","role":"symbol","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/!=(_:_:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title","value":"DOTPPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPlaceholderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}