{"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/left","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Left palm placeholder."}],"metadata":{"symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"}],"externalID":"c:@M@DotPalmCore@E@DOTPPlaceholderType@DOTPPlaceholderTypeLeft","title":"PlaceholderType.left","roleHeading":"Case","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"DOTPPlaceholderTypeLeft","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype\/left"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype\/left"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"abstract":[{"type":"text","text":"Represents the type of placeholder used in palm auto-capture UI."}],"type":"topic","role":"symbol","title":"PlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotpalmcore\/placeholdertype","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/left":{"kind":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"}],"url":"\/documentation\/dotpalmcore\/placeholdertype\/left","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/left","title":"PlaceholderType.left","navigatorTitle":[{"text":"DOTPPlaceholderTypeLeft","kind":"identifier"}],"abstract":[{"text":"Left palm placeholder.","type":"text"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTPPlaceholderTypeLeft"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPPlaceholderTypeLeft","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTPPlaceholderTypeLeft"}],"languages":["occ"]}]},"op":"replace"},{"value":"DOTPPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title"},{"op":"replace","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1left\/title","value":"DOTPPlaceholderTypeLeft"},{"value":[{"text":"DOTPPlaceholderTypeLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1left\/fragments"}]}]}