{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}]}]}],"abstract":[{"type":"text","text":"Right palm placeholder."}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"PlaceholderType.right","navigatorTitle":[{"kind":"identifier","text":"DOTPPlaceholderTypeRight"}],"externalID":"c:@M@DotPalmCore@E@DOTPPlaceholderType@DOTPPlaceholderTypeRight","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"symbolKind":"case"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/right","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype\/right"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/placeholdertype\/right"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType/right":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType\/right","role":"symbol","type":"topic","title":"PlaceholderType.right","navigatorTitle":[{"text":"DOTPPlaceholderTypeRight","kind":"identifier"}],"abstract":[{"text":"Right palm placeholder.","type":"text"}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/placeholdertype\/right"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PlaceholderType":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PlaceholderType","role":"symbol","abstract":[{"text":"Represents the type of placeholder used in palm auto-capture UI.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/placeholdertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"PlaceholderType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"kind":"symbol","title":"PlaceholderType"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTPPlaceholderTypeRight"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPPlaceholderTypeRight","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTPPlaceholderTypeRight"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPlaceholderTypeRight","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1right\/title"},{"value":[{"text":"DOTPPlaceholderTypeRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType~1right\/fragments"},{"value":"DOTPPlaceholderType","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PlaceholderType\/fragments","value":[{"text":"DOTPPlaceholderType","kind":"identifier"}]}]}]}