{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/init(bgraRawImage:palm:validatorIdentifiers:)"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"palm","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier","text":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","text":"Palm","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/init(bgrarawimage:palm:validatoridentifiers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/init(bgrarawimage:palm:validatoridentifiers:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"palm","kind":"externalParam"},{"kind":"text","text":": "},{"text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:palm:validatorIdentifiers:"}],"title":"init(bgraRawImage:palm:validatorIdentifiers:)","modules":[{"name":"DotPalmCore"}],"roleHeading":"Initializer","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection(im)initWithBgraRawImage:palm:validatorIdentifiers:","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"title":"PalmDetector.Palm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","abstract":[{"type":"text","text":"Result of the palm detection process."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Palm","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"title":"PalmDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","title":"BgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","role":"symbol","title":"PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","role":"symbol","title":"PalmAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","title":"PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"title":"DOTPPalmDetectorPalm","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","type":"topic","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection/init(bgraRawImage:palm:validatorIdentifiers:)":{"title":"init(bgraRawImage:palm:validatorIdentifiers:)","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetection\/init(bgrarawimage:palm:validatoridentifiers:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:palm:validatorIdentifiers:"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"palm"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Palm"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validatorIdentifiers"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"])","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/init(bgraRawImage:palm:validatorIdentifiers:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithBgraRawImage:palm:validatorIdentifiers:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgraRawImage:palm:validatorIdentifiers:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","text":"DOTBgraRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"palm:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm","kind":"typeIdentifier","text":"DOTPPalmDetectorPalm","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"},{"kind":"text","text":" *) "},{"text":"palm","kind":"internalParam"},{"kind":"text","text":" "},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<NSString *>"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validatorIdentifiers"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController"},{"value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments"},{"value":"DOTPPalmAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","value":"initWithBgraRawImage:palm:validatorIdentifiers:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1init(bgraRawImage:palm:validatorIdentifiers:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBgraRawImage:palm:validatorIdentifiers:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1init(bgraRawImage:palm:validatorIdentifiers:)\/fragments"}]}]}