{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper","kind":"typeIdentifier"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone"},{"text":"? = nil)","kind":"text"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)"},"metadata":{"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult(im)initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"text":"machineReadableZone","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone"},{"text":"?)","kind":"text"}],"title":"init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)","symbolKind":"init","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/init(bgrarawimage:document:content:traveldocumenttype:machinereadablezone:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocaptureresult\/init(bgrarawimage:document:content:traveldocumenttype:machinereadablezone:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureResult":{"url":"\/documentation\/dotdocument\/documentautocaptureresult","role":"symbol","abstract":[{"text":"The final result of the document auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureResult","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"title":"DocumentAutoCaptureResult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureResult/init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"document"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"text":"?, ","kind":"text"},{"text":"content","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"machineReadableZone"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone","text":"MachineReadableZone","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult\/init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)","abstract":[],"url":"\/documentation\/dotdocument\/documentautocaptureresult\/init(bgrarawimage:document:content:traveldocumenttype:machinereadablezone:)","navigatorTitle":[{"kind":"identifier","text":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:"}],"title":"init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage","role":"symbol","title":"BgraRawImage","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorDocument":{"type":"topic","role":"symbol","fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","title":"DOTDDocumentDetectorDocument","kind":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol","title":"DocumentAutoCaptureController","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"role":"symbol","title":"TravelDocumentTypeWrapper","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"symbol","url":"\/documentation\/dotdocument\/traveldocumenttypewrapper","abstract":[{"type":"text","text":"Wrapped "},{"code":"TravelDocumentType","type":"codeVoice"},{"type":"text","text":" for Objective-C support."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"url":"\/documentation\/dotdocument\/documentdetector","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Document":{"kind":"symbol","navigatorTitle":[{"text":"Document","kind":"identifier"}],"type":"topic","title":"DocumentDetector.Document","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"url":"\/documentation\/dotdocument\/documentdetector\/document","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"url":"\/documentation\/dotdocument\/machinereadablezone","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","title":"MachineReadableZone","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithBgraRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"document:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","text":"DOTDDocumentDetectorDocument"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"document"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSData","preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"kind":"text","text":" "},{"text":"travelDocumentType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTTravelDocumentTypeWrapper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTTravelDocumentTypeWrapper"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"travelDocumentType"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone:"},{"text":"(","kind":"text"},{"text":"DOTMachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMachineReadableZone","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"machineReadableZone","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","value":"DOTDDocumentAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"text":"DOTDDocumentAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)\/title","value":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBgraRawImage:document:content:travelDocumentType:machineReadableZone:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult~1init(bgraRawImage:document:content:travelDocumentType:machineReadableZone:)\/fragments"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTTravelDocumentTypeWrapper"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","value":"DOTMachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"text":"DOTMachineReadableZone","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}