{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nameofholder\/primaryidentifier"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nameofholder\/primaryidentifier"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder"]]},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"primaryIdentifier"}],"modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder(py)primaryIdentifier","title":"primaryIdentifier","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","platforms":[{"deprecated":false,"introducedAt":"13.0","name":"iOS","beta":false,"unavailable":false}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"primaryIdentifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"abstract":[{"text":"Primary identifier, usually represents surname.","type":"text"}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/primaryIdentifier","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"primaryIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/primaryIdentifier":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"primaryIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"primaryIdentifier"}],"type":"topic","kind":"symbol","title":"primaryIdentifier","abstract":[{"type":"text","text":"Primary identifier, usually represents surname."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/primaryIdentifier","url":"\/documentation\/dotnfc\/nameofholder\/primaryidentifier"},"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NameOfHolder","kind":"identifier"}],"abstract":[{"text":"Name of travel document holder.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"title":"NameOfHolder","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","role":"symbol","url":"\/documentation\/dotnfc\/nameofholder"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"primaryIdentifier","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"primaryIdentifier","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"primaryIdentifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"primaryIdentifier","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1primaryIdentifier\/title"},{"value":[{"text":"primaryIdentifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1primaryIdentifier\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title","op":"replace","value":"DOTNNameOfHolder"},{"value":[{"text":"DOTNNameOfHolder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}