{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Positions of the element.","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement\/positions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","title":"positions","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement(py)positions","symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"positions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","text":"MrzStringPosition"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"positions","kind":"identifier"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/mrzelement\/positions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelement\/positions"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"positions","kind":"identifier"},{"text":": [","kind":"text"},{"text":"MrzStringPosition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/MrzElement/positions":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"positions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzStringPosition","kind":"typeIdentifier","text":"MrzStringPosition"},{"kind":"text","text":"]"}],"url":"\/documentation\/dotnfc\/mrzelement\/positions","abstract":[{"text":"Positions of the element.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"positions"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement\/positions","title":"positions"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/MrzElement":{"url":"\/documentation\/dotnfc\/mrzelement","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"title":"MrzElement","type":"topic"},"doc://DotNfc/documentation/DotNfc/MrzStringPosition":{"title":"MrzStringPosition","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzStringPosition","navigatorTitle":[{"text":"MrzStringPosition","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzStringPosition","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrzstringposition"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"positions","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"positions"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTMrzStringPosition *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"positions"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"positions","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement~1positions\/title","op":"replace"},{"value":[{"kind":"identifier","text":"positions"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement~1positions\/fragments","op":"replace"},{"value":"DOTMrzElement","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElement"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle","op":"replace"},{"value":"DOTMrzStringPosition","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzStringPosition"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzStringPosition\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}