{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Polling option specifies which travel documents can be detected."}],"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/experimental","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/standard"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/description"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true,"title":"Default Implementations"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PollingOption"}],"title":"NfcTravelDocumentReader.Configuration.PollingOption","roleHeading":"Enumeration","externalID":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13PollingOptionO","symbolKind":"enum","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollingOption","kind":"identifier"}],"modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTNNfcTravelDocumentReaderConfigurationPollingOption) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PollingOption"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"title":"NfcTravelDocumentReader.Configuration","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for "},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/RawRepresentable-Implementations","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/rawrepresentable-implementations","kind":"article","role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/Equatable-Implementations":{"type":"topic","abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/Equatable-Implementations","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/equatable-implementations","kind":"article","role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/init(rawValue:)":{"type":"topic","abstract":[],"title":"init(rawValue:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/init(rawValue:)","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/init(rawvalue:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/SY":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SY","title":"Swift.RawRepresentable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/description":{"type":"topic","abstract":[],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/description","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/description","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/experimental":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/experimental","kind":"symbol","title":"NfcTravelDocumentReader.Configuration.PollingOption.experimental","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Experimental polling option which supports detection of newer "},{"code":"PACE","type":"codeVoice"},{"type":"text","text":" only travel documents."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"experimental","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/experimental"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum","kind":"symbol","title":"NfcTravelDocumentReader.Configuration.PollingOption","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PollingOption","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"PollingOption","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum","abstract":[{"text":"Polling option specifies which travel documents can be detected.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","type":"topic","title":"NfcTravelDocumentReader","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/standard":{"type":"topic","abstract":[{"type":"text","text":"Standard polling option which supports detection of almost all travel documents."}],"title":"NfcTravelDocumentReader.Configuration.PollingOption.standard","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/standard","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/standard","kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}]},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/SH":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","op":"replace"}]}]}