{"metadata":{"role":"symbol","symbolKind":"property","roleHeading":"Instance Property","title":"bytesPointer","navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"UInt8","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(py)bytesPointer","modules":[{"name":"DotFaceLite"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/bgrrawimage\/bytespointer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/bgrrawimage\/bytespointer"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointer"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"kind":"text","text":">"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage\/bytesPointer"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.12.0"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BgrRawImage":{"title":"BgrRawImage","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"url":"\/documentation\/dotfacelite\/bgrrawimage","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BgrRawImage/bytesPointer":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytesPointer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt8","preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier"},{"text":">","kind":"text"}],"url":"\/documentation\/dotfacelite\/bgrrawimage\/bytespointer","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"title":"bytesPointer","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage\/bytesPointer","type":"topic","abstract":[],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"bytesPointer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"bytesPointer","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bytesPointer"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTBgrRawImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage~1bytesPointer\/title","value":"bytesPointer","op":"replace"},{"op":"replace","value":[{"text":"bytesPointer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage~1bytesPointer\/fragments"}]}]}