{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage"]]},"metadata":{"title":"bytes","role":"symbol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage(py)bytes"},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Raw image data."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytes"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/bgrrawimage\/bytes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/bgrrawimage\/bytes"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","title":"DotFaceLite","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.4.1"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage/bytes":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"url":"\/documentation\/dotfacelite\/bgrrawimage\/bytes","kind":"symbol","abstract":[{"text":"Raw image data.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytes","type":"topic","title":"bytes"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrrawimage","kind":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","type":"topic","title":"BgrRawImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bytes","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readwrite","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"bytes","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytes\/title","op":"replace","value":"bytes"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","op":"replace"}]}]}