{"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrrawimage\/size"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bgrrawimage\/size"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","text":"ImageSize"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage\/size"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage"]]},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"size","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"title":"size","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImage(py)size","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"_RawImage.size","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 8.15.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/imagesize","title":"ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgrRawImage/size":{"title":"size","navigatorTitle":[{"kind":"identifier","text":"size"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage\/size","url":"\/documentation\/dotfacelite\/bgrrawimage\/size","role":"symbol","abstract":[],"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgrRawImage":{"title":"BgrRawImage","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgrRawImage","url":"\/documentation\/dotfacelite\/bgrrawimage","role":"symbol","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"size"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","text":"DOTImageSize"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"size"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage~1size\/title","value":"size","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage~1size\/fragments","value":[{"text":"size","kind":"identifier"}],"op":"replace"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgrRawImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}