{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"title":"description","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)description","role":"symbol","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/imagesize\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/imagesize\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"]]},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/ImageSize/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize\/description","url":"\/documentation\/dotnfc\/imagesize\/description","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"title":"ImageSize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","type":"topic","url":"\/documentation\/dotnfc\/imagesize"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"description"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/navigatorTitle","op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}