{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration"]]},"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"}],"title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureConfiguration(im)initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","text":"DOTDQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validationMode:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DOTDValidationMode","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"validationMode"},{"text":" ","kind":"text"},{"text":"mrzValidation:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","text":"DOTDMrzValidation","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation"},{"kind":"text","text":") "},{"text":"mrzValidation","kind":"internalParam"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"kind":"text","text":" "},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType"},{"text":") ","kind":"text"},{"text":"cameraPreviewScaleType","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholderType:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","text":"DOTDPlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"},{"text":") ","kind":"text"},{"text":"placeholderType","kind":"internalParam"},{"kind":"text","text":";"}]}]}],"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:placeholdertype:"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDQualityAttributeThresholds":{"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","url":"\/documentation\/dotdocument\/dotdqualityattributethresholds","role":"symbol","fragments":[{"text":"DOTDQualityAttributeThresholds","kind":"identifier"}],"title":"DOTDQualityAttributeThresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:":{"url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration\/initwithsessiontoken:qualityattributethresholds:validationmode:mrzvalidation:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:placeholdertype:","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","kind":"identifier"}],"abstract":[{"text":"Create the document auto capture configuration.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration\/initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","type":"topic","title":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:qualityAttributeThresholds:validationMode:mrzValidation:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:placeholderType:"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"abstract":[],"kind":"symbol","title":"ValidationMode","url":"\/documentation\/dotdocument\/validationmode","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"ValidationMode","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","navigatorTitle":[{"text":"ValidationMode","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation":{"abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrzvalidation","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"title":"MrzValidation","role":"symbol","navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraFacing":{"type":"topic","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","url":"\/documentation\/dotdocument\/camerafacing"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PlaceholderType":{"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"role":"symbol","abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"type":"topic","url":"\/documentation\/dotdocument\/placeholdertype","title":"PlaceholderType","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureConfiguration":{"type":"topic","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"kind":"symbol","title":"DOTDDocumentAutoCaptureConfiguration","url":"\/documentation\/dotdocument\/dotddocumentautocaptureconfiguration","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureConfiguration"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureConfiguration","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/camerapreviewscaletype","title":"CameraPreviewScaleType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"url":"\/documentation\/dotdocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"text":"DOTDValidationMode","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"value":[{"kind":"identifier","text":"DOTDMrzValidation"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/title","op":"replace","value":"DOTDPlaceholderType"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"op":"replace"},{"value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]}]}]}