{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/camera","interfaceLanguage":"occ"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"camera"}],"modules":[{"name":"DotFaceCore"}],"title":"camera","fragments":[{"kind":"identifier","text":"camera"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(py)camera"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"camera"},{"kind":"text","text":";"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"\\endcodeThis component does not have camera preview, therefore these properties are ignored: ","type":"text"},{"text":"previewScaleType","type":"text"},{"text":", ","type":"text"},{"text":"isPreviewVisible","type":"text"},{"text":".","type":"text"}]}],"kind":"content"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","title":"DOTFEyeGazeLivenessConfiguration","kind":"symbol","abstract":[{"text":"Configuration options for the UI Eye Gaze Liveness component.","type":"text"}],"role":"symbol","fragments":[{"text":"DOTFEyeGazeLivenessConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"role":"symbol","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"title":"CameraConfiguration","url":"\/documentation\/dotfacecore\/cameraconfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/camera":{"fragments":[{"text":"camera","kind":"identifier"}],"title":"camera","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/camera","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"},{"text":" ","type":"text"},{"text":"Default is:","type":"text"},{"text":" ","type":"text"},{"text":"\\code","type":"text"},{"text":" ","type":"text"},{"text":".init(cameraFacing: .front)","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/camera","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}