{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/bgraRawImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample"]]},"abstract":[{"text":"Sample image.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"symbolKind":"property","externalID":"s:11DotDocument0B21AutoCaptureControllerC6SampleC12bgraRawImage0A4Core04BgrahI0Cvp","modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property","title":"bgraRawImage"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/bgrarawimage"]}],"references":{"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample":{"abstract":[{"text":"The data sample captured at specific time which serves as an input for the document auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Sample"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample","kind":"symbol","title":"DocumentAutoCaptureController.Sample","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Sample/bgraRawImage":{"kind":"symbol","abstract":[{"type":"text","text":"Sample image."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Sample\/bgraRawImage","title":"bgraRawImage","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/sample\/bgrarawimage","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","kind":"symbol","title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/BgraRawImage":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgraRawImage","url":"\/documentation\/dotdocument\/bgrarawimage","title":"BgraRawImage","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgraRawImage\/fragments"}]}]}