{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/composeWithInternalError()"],"generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/error\/dotsdkerror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error"]]},"metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"DotSdkError Implementations","modules":[{"name":"DotPalmCore"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error/composeWithInternalError()":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error\/composeWithInternalError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","title":"composeWithInternalError()","url":"\/documentation\/dotpalmcore\/dotsdk\/error\/composewithinternalerror()","abstract":[],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/Error":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/Error","url":"\/documentation\/dotpalmcore\/dotsdk\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"DotSdk.Error","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"url":"\/documentation\/dotpalmcore\/dotsdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotNfc","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","value":"DotSdk","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}