{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionimage"]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessResult(py)smileExpressionImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileExpressionImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"}],"title":"smileExpressionImage","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","navigatorTitle":[{"text":"smileExpressionImage","kind":"identifier"}],"platforms":[{"deprecated":true,"unavailable":false,"beta":false,"message":"Temporary property for liveness evaluation on the device. Use `content` for evaluation on DIS."}],"roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileExpressionImage","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Smile expression face image.","type":"text"}],"kind":"symbol","deprecationSummary":[{"inlineContent":[{"text":"Temporary property for liveness evaluation on the device. Use `content` for evaluation on DIS.","type":"text"}],"type":"paragraph"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult"]]},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionImage","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult":{"url":"\/documentation\/dotfacecore\/smilelivenessresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessResult"}],"title":"SmileLivenessResult","type":"topic","kind":"symbol","abstract":[{"text":"The result of smile liveness process.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessResult"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/smileExpressionImage":{"url":"\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionimage","deprecated":true,"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"smileExpressionImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"title":"smileExpressionImage","type":"topic","kind":"symbol","abstract":[{"text":"Smile expression face image.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"smileExpressionImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionImage"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"type":"topic","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","url":"\/documentation\/dotfacecore\/image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"}],"title":"Image","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":[{"unavailable":false,"beta":false,"deprecated":true}],"path":"\/metadata\/platforms","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"smileExpressionImage","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"smileExpressionImage","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" * ","kind":"text"},{"text":"smileExpressionImage","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":[{"type":"paragraph","inlineContent":[{"text":"Temporary property for liveness evaluation on the device. Use `content` for evaluation on DIS.","type":"text"}]}],"path":"\/deprecationSummary","op":"replace"},{"value":"DOTFSmileLivenessResult","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/title","op":"replace"},{"value":[{"text":"DOTFSmileLivenessResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/fragments","op":"replace"},{"value":[{"text":"DOTFSmileLivenessResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/navigatorTitle","op":"replace"},{"value":"smileExpressionImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionImage\/title","op":"replace"},{"value":[{"text":"smileExpressionImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionImage\/fragments","op":"replace"},{"value":"DOTImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","op":"replace"},{"value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","op":"replace"}]}]}