{"metadata":{"symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"moduleId","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceModule(py)moduleId","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotFaceModuleId","kind":"typeIdentifier","text":"DotFaceModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"moduleId"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DotFaceModuleId","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","text":"DotFaceModuleId"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacemodule\/moduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacemodule\/moduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/moduleId","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/moduleId":{"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/moduleId","title":"moduleId","required":true,"url":"\/documentation\/dotfacecore\/dotfacemodule\/moduleid","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceModuleId","preciseIdentifier":"c:@M@DotCore@E@DotFaceModuleId"}],"navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModule"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","url":"\/documentation\/dotfacecore\/dotfacemodule","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module.","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceModule"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleId":{"title":"DotFaceModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfacemoduleid","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"moduleId","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"moduleId"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DotFaceModuleId","kind":"typeIdentifier","text":"DotFaceModuleId","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleId"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1moduleId\/title","value":"moduleId","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1moduleId\/fragments","value":[{"text":"moduleId","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"text":"DotFaceModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","value":[{"text":"DotFaceModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/title","value":"DotFaceModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleId\/navigatorTitle","value":[{"text":"DotFaceModuleId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}