{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection(im)initWithImage:face:deviceTiltAngles:validatorIdentifiers:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Face","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"deviceTiltAngles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"])"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(image:face:deviceTiltAngles:validatorIdentifiers:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}],"modules":[{"name":"DotFaceCore"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"],["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceDetector","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","text":"Face","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles","text":"TiltAngles","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TiltAngles":{"navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"role":"symbol","url":"\/documentation\/dotfacecore\/tiltangles","type":"topic","abstract":[{"text":"Tilt angles.","type":"text"},{"text":" ","type":"text"},{"text":"Also see ","type":"text"},{"isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","type":"reference"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TiltAngles"}],"title":"TiltAngles","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"title":"FaceAutoCaptureDetection","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","url":"\/documentation\/dotfacecore\/image","role":"symbol","type":"topic","abstract":[]},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"type":"topic","kind":"symbol","abstract":[{"text":"UI Smile Liveness component.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/Face":{"kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"url":"\/documentation\/dotfacecore\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","type":"topic","role":"symbol","title":"Face","fragments":[{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","navigatorTitle":[{"text":"Face","kind":"identifier"}],"type":"topic","role":"symbol","title":"FaceDetector.Face","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"title":"MagnifEyeLivenessViewController","deprecated":true,"type":"topic","abstract":[{"type":"text","text":"UI MagnifEye Liveness component."}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection/init(image:face:deviceTiltAngles:validatorIdentifiers:)":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection\/init(image:face:deviceTiltAngles:validatorIdentifiers:)","title":"init(image:face:deviceTiltAngles:validatorIdentifiers:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"face","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector"},{"text":".","kind":"text"},{"text":"Face","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"deviceTiltAngles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TiltAngles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"navigatorTitle":[{"text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection\/init(image:face:devicetiltangles:validatoridentifiers:)","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"text":"UI Face Auto Capture component.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacecore\/facedetector","title":"FaceDetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"face:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Face","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)Face","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"},{"text":" *) ","kind":"text"},{"text":"face","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"deviceTiltAngles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTTiltAngles","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTTiltAngles","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TiltAngles"},{"text":" *) ","kind":"text"},{"text":"deviceTiltAngles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"validatorIdentifiers","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTTiltAngles","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTiltAngles"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/fragments"},{"op":"replace","value":[{"text":"DOTTiltAngles","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TiltAngles\/navigatorTitle"},{"op":"replace","value":"DOTFFaceAutoCaptureDetection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle"},{"op":"replace","value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle"},{"op":"replace","value":"DOTFMagnifEyeLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFMagnifEyeLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/navigatorTitle"},{"op":"replace","value":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:face:deviceTiltAngles:validatorIdentifiers:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection~1init(image:face:deviceTiltAngles:validatorIdentifiers:)\/fragments"},{"op":"replace","value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"text":"DOTFFaceDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}