{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"dotFace"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace","text":"DotFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace","text":"DotFace"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/Result","preciseIdentifier":"s:11DotFaceCore0aB0C6ResultC","text":"Result"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacedelegate\/dotfacedeinitializationfinished(_:result:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacedelegate\/dotfacedeinitializationfinished(_:result:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceDeinitializationFinished(_:result:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}],"role":"symbol","title":"dotFaceDeinitializationFinished(_:result:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB0C6ResultC"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceDelegate(im)dotFaceDeinitializationFinished:result:","required":true,"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryDelegate instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace":{"deprecated":true,"role":"symbol","title":"DotFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFace"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFace"}],"url":"\/documentation\/dotfacecore\/dotface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace/Result":{"deprecated":true,"role":"symbol","title":"DotFace.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacecore\/dotface\/result"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceDelegate":{"deprecated":true,"role":"symbol","title":"DotFaceDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDelegate"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceDelegate"}],"url":"\/documentation\/dotfacecore\/dotfacedelegate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceResult":{"role":"symbol","title":"DotFaceResult","fragments":[{"kind":"identifier","text":"DotFaceResult"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceResult","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotfaceresult"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceDelegate/dotFaceDeinitializationFinished(_:result:)":{"navigatorTitle":[{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}],"deprecated":true,"role":"symbol","title":"dotFaceDeinitializationFinished(_:result:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"dotFaceDeinitializationFinished"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":", "},{"kind":"externalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0aB0C6ResultC"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceDelegate\/dotFaceDeinitializationFinished(_:result:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/dotfacedelegate\/dotfacedeinitializationfinished(_:result:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"dotFaceDeinitializationFinished:result:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"dotFaceDeinitializationFinished:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFace","text":"DotFace"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"dotFace"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceResult","text":"DotFaceResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"result"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/title","value":"DotFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/fragments","value":[{"kind":"identifier","text":"DotFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate\/title","value":"DotFaceDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate\/fragments","value":[{"kind":"identifier","text":"DotFaceDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceDeinitializationFinished(_:result:)\/title","value":"dotFaceDeinitializationFinished:result:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceDelegate~1dotFaceDeinitializationFinished(_:result:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"dotFaceDeinitializationFinished:result:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}