{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/isEqual(_:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDate(im)isEqual:","symbolKind":"method","roleHeading":"Instance Method","title":"isEqual(_:)","role":"symbol","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/mrzdate\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/mrzdate\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzDate/isEqual(_:)":{"title":"isEqual(_:)","url":"\/documentation\/dotnfc\/mrzdate\/isequal(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/MrzDate":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzDate","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzDate"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzDate"}],"title":"MrzDate","type":"topic","abstract":[{"type":"text","text":"Date parsed from Machine Readable Zone."}],"url":"\/documentation\/dotnfc\/mrzdate"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"isEqual:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/title","value":"DOTMrzDate","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/fragments","value":[{"kind":"identifier","text":"DOTMrzDate"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzDate\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}