{"kind":"symbol","metadata":{"title":"hashValue","extendedModule":"Swift","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"roleHeading":"Instance Property","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DotPalmModuleId","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"DotFaceLite","relatedModules":["Swift"]}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotpalmmoduleid\/hashvalue"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/hashValue","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"text":".","type":"text"}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId":{"kind":"symbol","title":"DotPalmModuleId","url":"\/documentation\/dotfacelite\/dotpalmmoduleid","type":"topic","abstract":[{"type":"codeVoice","code":"DotPalm"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId","role":"symbol","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/RawRepresentable-Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/hashValue":{"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/hashValue","title":"hashValue","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/hashvalue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}