{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/id"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibrary(py)id","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}],"title":"id","symbolKind":"property","role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"id"}]},"abstract":[{"text":"The library identifier.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/id"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/id"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibrary"}],"title":"DotPalmLibrary","url":"\/documentation\/dotpalmcore\/dotpalmlibrary","kind":"symbol","role":"symbol","type":"topic","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":" library initialization.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotPalmLibrary","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/id":{"title":"id","abstract":[{"type":"text","text":"The library identifier."}],"type":"topic","navigatorTitle":[{"text":"id","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/id","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/id","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotlibraryid"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.8.0","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"id"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"id"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","value":"DotPalmLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments","value":[{"kind":"identifier","text":"DotPalmLibrary"}],"op":"replace"},{"value":"id","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1id\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1id\/fragments","value":[{"kind":"identifier","text":"id"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments","value":[{"text":"DotLibraryId","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}