{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/deinitialize()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotPalmCore"}],"title":"deinitialize()","externalID":"c:@M@DotCore@objc(cs)DotSdk(im)deinitializeAndReturnError:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdk\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdk\/deinitialize()"]}],"sections":[],"abstract":[{"text":"Deinitialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This method should be called on the background thread."}]}],"kind":"content"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/deinitialize()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/deinitialize()","role":"symbol","type":"topic","title":"deinitialize()","url":"\/documentation\/dotpalmcore\/dotsdk\/deinitialize()","abstract":[{"type":"text","text":"Deinitialize "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.11.0","type":"text"}],"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"url":"\/documentation\/dotpalmcore\/dotsdk","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","type":"topic","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"deinitializeAndReturnError:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1deinitialize()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1deinitialize()\/fragments","op":"replace"},{"value":"DotSdk","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","op":"replace"},{"op":"replace","value":[{"text":"DotSdk","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}