{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/identifier","interfaceLanguage":"swift"},"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/identifier"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmOutOfBoundsValidator(py)identifier","title":"identifier","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/identifier":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/identifier","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/identifier","title":"identifier","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"identifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","op":"replace","value":"DOTPPalmOutOfBoundsValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1identifier\/title","op":"replace","value":"identifier"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1identifier\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]}]}]}