{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lostFace"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate\/lostface"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate\/lostface"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lostFace","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lostFace"}],"title":"EyeGazeLivenessState.lostFace","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCore@E@DOTEyeGazeLivenessState@DOTEyeGazeLivenessStateLostFace","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTEyeGazeLivenessStateLostFace"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState":{"role":"symbol","title":"EyeGazeLivenessState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessState"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/lostFace":{"role":"symbol","title":"EyeGazeLivenessState.lostFace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lostFace"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lostFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTEyeGazeLivenessStateLostFace"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/lostface"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTEyeGazeLivenessStateLostFace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTEyeGazeLivenessStateLostFace"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTEyeGazeLivenessStateLostFace"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/title","value":"DOTEyeGazeLivenessState"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/fragments","value":[{"kind":"identifier","text":"DOTEyeGazeLivenessState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lostFace\/title","value":"DOTEyeGazeLivenessStateLostFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lostFace\/fragments","value":[{"kind":"identifier","text":"DOTEyeGazeLivenessStateLostFace"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}