{"variants":[{"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/checkdigit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/mrzelementwithcheckdigit\/checkdigit"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}]}],"kind":"declarations"}],"abstract":[{"text":"An object with check digit value and checksum validity flag.","type":"text"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit(py)checkDigit","navigatorTitle":[{"text":"checkDigit","kind":"identifier"}],"title":"checkDigit"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/checkDigit","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotNfc/documentation/DotNfc/MrzCheckDigit":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"url":"\/documentation\/dotnfc\/mrzcheckdigit","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","type":"topic","kind":"symbol","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"title":"MrzCheckDigit"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit/checkDigit":{"navigatorTitle":[{"text":"checkDigit","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"checkDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit\/checkDigit","type":"topic","title":"checkDigit","abstract":[{"text":"An object with check digit value and checksum validity flag.","type":"text"}],"role":"symbol","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit\/checkdigit","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/MrzElementWithCheckDigit":{"abstract":[{"text":"A ","type":"text"},{"code":"MrzElement","type":"codeVoice"},{"text":" with check digit and checksum validitity information.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"checkDigit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"checkDigit","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzCheckDigit","kind":"typeIdentifier","text":"DOTMrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzCheckDigit\/navigatorTitle","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1checkDigit\/title","value":"checkDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit~1checkDigit\/fragments","value":[{"text":"checkDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/navigatorTitle","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}