{"primaryContentSections":[{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"DotDocument provides components for document capture and related functionalities which are easy to integrate into an iOS application."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"version: 7.5.0"}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"DotDocument","title":"DotDocument","symbolKind":"module","role":"collection","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[[]]},"topicSections":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization"]},{"title":"UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]},{"title":"Non-UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]},{"title":"Converting images","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"]},{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedFloat"]},{"title":"Protocols","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode"]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImageFactory":{"role":"symbol","title":"BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"url":"\/documentation\/dotdocument\/bgrarawimagefactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/WrappedDouble":{"role":"symbol","title":"WrappedDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotdocument\/wrappeddouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/SharpnessTooLowValidator":{"role":"symbol","title":"SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CGImageFactory":{"role":"symbol","title":"CGImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"url":"\/documentation\/dotdocument\/cgimagefactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzValidation":{"role":"symbol","title":"MrzValidation","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzValidation"}],"abstract":[{"type":"text","text":"Mode of MRZ (Machine Readable Zone) validation."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzValidation"}],"url":"\/documentation\/dotdocument\/mrzvalidation"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationDouble":{"role":"symbol","title":"ValidationDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationDouble"}],"abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationDouble"}],"url":"\/documentation\/dotdocument\/validationdouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotdocument\/rectangledouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"role":"symbol","title":"DotSdkLicenseProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentVersionString":{"role":"symbol","title":"DotDocumentVersionString","fragments":[{"kind":"identifier","text":"DotDocumentVersionString"}],"abstract":[{"type":"text","text":"Project version string for DotDocument."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentVersionString","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentversionstring"},"doc://com.innovatrics.dot.document/documentation/DotDocument/SizeTooSmallValidator":{"role":"symbol","title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"type":"text","text":"Validate size of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotdocument\/sizetoosmallvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureControllerPhase":{"role":"symbol","title":"DOTDDocumentAutoCaptureControllerPhase","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerPhase"}],"abstract":[{"type":"text","text":"Phase of the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerPhase","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerphase"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImage":{"role":"symbol","title":"BgrRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"url":"\/documentation\/dotdocument\/bgrrawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibrary":{"role":"symbol","title":"DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"url":"\/documentation\/dotdocument\/dotlibrary"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooLowValidator":{"role":"symbol","title":"BrightnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TiltAngles":{"role":"symbol","title":"TiltAngles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TiltAngles"}],"abstract":[{"type":"text","text":"Tilt angles."},{"type":"text","text":" "},{"type":"text","text":"Also see "},{"type":"reference","isActive":true,"identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TiltAngles"}],"url":"\/documentation\/dotdocument\/tiltangles"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgrRawImageFactory":{"role":"symbol","title":"BgrRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"url":"\/documentation\/dotdocument\/bgrrawimagefactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CIImageFactory":{"role":"symbol","title":"CIImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotdocument\/ciimagefactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationMode":{"role":"symbol","title":"ValidationMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraFacing":{"role":"symbol","title":"CameraFacing","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotdocument\/camerafacing"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureControllerSample":{"role":"symbol","title":"DOTDDocumentAutoCaptureControllerSample","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerSample"}],"abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollersample"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentVersionNumber":{"role":"symbol","title":"DotDocumentVersionNumber","fragments":[{"kind":"identifier","text":"DotDocumentVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for DotDocument."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdocumentversionnumber"},"https://developer.apple.com/documentation/coremotion/getting_raw_accelerometer_events":{"title":"Sensor Coordinate System","titleInlineContent":[{"type":"text","text":"Sensor Coordinate System"}],"type":"link","identifier":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events","url":"https:\/\/developer.apple.com\/documentation\/coremotion\/getting_raw_accelerometer_events"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdk":{"role":"symbol","title":"DotSdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"url":"\/documentation\/dotdocument\/dotsdk"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PlaceholderType":{"role":"symbol","title":"PlaceholderType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"abstract":[{"type":"text","text":"Represents the type of placeholder used in document auto-capture UI."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotdocument\/placeholdertype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger":{"role":"symbol","title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotdocument\/logger"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory":{"role":"symbol","title":"BezierPathFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"url":"\/documentation\/dotdocument\/bezierpathfactory"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper":{"role":"symbol","title":"ImagePerspectiveWarper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzRecognitionResult":{"role":"symbol","title":"MrzRecognitionResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzRecognitionResult"}],"abstract":[{"type":"text","text":"The result of using OCR on the MRZ text."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzRecognitionResult"}],"url":"\/documentation\/dotdocument\/mrzrecognitionresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkLicenseProxy":{"role":"symbol","title":"DotSdkLicenseProxy","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxy"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary":{"role":"symbol","title":"DotDocumentLibrary","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibrary"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" library initialization."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibrary"}],"url":"\/documentation\/dotdocument\/dotdocumentlibrary"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"role":"symbol","title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"role":"symbol","title":"PointDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"url":"\/documentation\/dotdocument\/pointdouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParameters":{"role":"symbol","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotdocument\/imageparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDQualityAttributeThresholds":{"role":"symbol","title":"DOTDQualityAttributeThresholds","fragments":[{"kind":"identifier","text":"DOTDQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdqualityattributethresholds"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel":{"role":"symbol","title":"LoggerLogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotdocument\/loggerloglevel"},"doc://com.innovatrics.dot.document/documentation/DotDocument/WrappedFloat":{"role":"symbol","title":"WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"url":"\/documentation\/dotdocument\/wrappedfloat"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BrightnessTooHighValidator":{"role":"symbol","title":"BrightnessTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/HotspotsScoreTooHighValidator":{"role":"symbol","title":"HotspotsScoreTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParametersAnalyzer":{"role":"symbol","title":"ImageParametersAnalyzer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParametersAnalyzer"}],"abstract":[{"type":"text","text":"Stateless class which can analyze image parameters."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageParametersAnalyzer"}],"url":"\/documentation\/dotdocument\/imageparametersanalyzer"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Localization":{"role":"symbol","title":"Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotdocument\/localization"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDQualityAttributeThresholdPresets":{"role":"symbol","title":"DOTDQualityAttributeThresholdPresets","fragments":[{"kind":"identifier","text":"DOTDQualityAttributeThresholdPresets"}],"abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholdPresets","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdqualityattributethresholdpresets"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorResult":{"role":"symbol","title":"DOTDDocumentDetectorResult","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorResult"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentdetectorresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult":{"role":"symbol","title":"DOTDDocumentAutoCaptureControllerProcessingResult","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotSdkConfiguration":{"role":"symbol","title":"DotSdkConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"url":"\/documentation\/dotdocument\/dotsdkconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDQualityAttributeThresholdsBuilder":{"role":"symbol","title":"DOTDQualityAttributeThresholdsBuilder","fragments":[{"kind":"identifier","text":"DOTDQualityAttributeThresholdsBuilder"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholdsBuilder","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdqualityattributethresholdsbuilder"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDMrzReaderResult":{"role":"symbol","title":"DOTDMrzReaderResult","fragments":[{"kind":"identifier","text":"DOTDMrzReaderResult"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdmrzreaderresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator":{"role":"symbol","title":"MrzNotPresentValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotPresentValidator"}],"abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzNotPresentValidator"}],"url":"\/documentation\/dotdocument\/mrznotpresentvalidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ValidationFloat":{"role":"symbol","title":"ValidationFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationFloat"}],"abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ValidationFloat"}],"url":"\/documentation\/dotdocument\/validationfloat"},"doc://com.innovatrics.dot.document/documentation/DotDocument/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotdocument\/camerapreviewscaletype"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalDouble":{"role":"symbol","title":"IntervalDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"url":"\/documentation\/dotdocument\/intervaldouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat":{"role":"symbol","title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"url":"\/documentation\/dotdocument\/intervalfloat"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotLibraryId":{"role":"symbol","title":"DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library identifier."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"url":"\/documentation\/dotdocument\/dotlibraryid"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageSize":{"role":"symbol","title":"ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotdocument\/imagesize"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Localization"]},{"title":"UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]},{"title":"Non-UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]},{"title":"Converting images","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CGImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CIImageFactory"]},{"title":"Classes","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImage","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgrRawImageFactory","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerSample","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDMrzReaderResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholdPresets","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholds","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDQualityAttributeThresholdsBuilder","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdk","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxy","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageSize","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzRecognitionResult","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TiltAngles","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationFloat","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedDouble","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/WrappedFloat"]},{"title":"Protocols","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibrary","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol"]},{"title":"Variables","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentVersionNumber","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentVersionString"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraFacing","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/CameraPreviewScaleType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerPhase","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotLibraryId","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzValidation","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PlaceholderType","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ValidationMode"]}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"kind":"identifier","text":"DOTDMrzValidation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble\/title","value":"DOTValidationDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationDouble\/fragments","value":[{"kind":"identifier","text":"DOTValidationDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/title","value":"DOTTiltAngles"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TiltAngles\/fragments","value":[{"kind":"identifier","text":"DOTTiltAngles"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgrRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"kind":"identifier","text":"DOTDValidationMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/title","value":"DOTDLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTDLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/title","value":"DOTBezierPathFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/fragments","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzRecognitionResult\/title","value":"DOTDMrzRecognitionResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzRecognitionResult\/fragments","value":[{"kind":"identifier","text":"DOTDMrzRecognitionResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/title","value":"DotDocumentLibrary"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTDTravelDocumentTypeWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTDTravelDocumentTypeWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTDImageParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1WrappedFloat\/fragments","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title","value":"DOTDHotspotsScoreTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/title","value":"DOTDImageParametersAnalyzer"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/title","value":"DOTDLocalization"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTDLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/title","value":"DOTDMrzNotPresentValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotPresentValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/title","value":"DOTValidationFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ValidationFloat\/fragments","value":[{"kind":"identifier","text":"DOTValidationFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}