{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDateOfExpiry"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfExpiry"},"metadata":{"symbolKind":"case","modules":[{"name":"DotNfc"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDateOfExpiry","kind":"identifier"}],"externalID":"s:6DotNfc27MachineReadableZonePasswordC5ErrorO19invalidDateOfExpiryyA2EmF","roleHeading":"Case","role":"symbol","title":"MachineReadableZonePassword.Error.invalidDateOfExpiry"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error"]]},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddateofexpiry"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error","title":"MachineReadableZonePassword.Error","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"url":"\/documentation\/dotnfc\/machinereadablezonepassword","title":"MachineReadableZonePassword","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword/Error/invalidDateOfExpiry":{"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidDateOfExpiry","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword\/Error\/invalidDateOfExpiry","url":"\/documentation\/dotnfc\/machinereadablezonepassword\/error\/invaliddateofexpiry","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"MachineReadableZonePassword.Error.invalidDateOfExpiry"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNMachineReadableZonePassword"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}