{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"circle","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"circle"}],"navigatorTitle":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"roleHeading":"Case","title":"PlaceholderType.circle","symbolKind":"case","role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceCommons@E@DOTPlaceholderType@DOTPlaceholderTypeCircle"},"variants":[{"paths":["\/documentation\/dotfacelite\/placeholdertype\/circle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/placeholdertype\/circle"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"text":"Circular placeholder.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/circle"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/circle":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/circle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"circle"}],"abstract":[{"type":"text","text":"Circular placeholder."}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTPlaceholderTypeCircle"}],"title":"PlaceholderType.circle","role":"symbol","url":"\/documentation\/dotfacelite\/placeholdertype\/circle"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"kind":"symbol","url":"\/documentation\/dotfacelite\/placeholdertype","abstract":[{"type":"text","text":"Type of placeholder."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","title":"PlaceholderType","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPlaceholderTypeCircle","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholderTypeCircle"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType~1circle\/title","value":"DOTPlaceholderTypeCircle","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType~1circle\/fragments","value":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title","value":"DOTPlaceholderType","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}