{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/Equatable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType"]]},"kind":"article","topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/!=(_:_:)"],"anchor":"Operators","generated":true,"title":"Operators"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"DotFaceLite"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholdertype\/equatable-implementations"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","role":"symbol","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/placeholdertype","title":"PlaceholderType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/!=(_:_:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/!=(_:_:)","url":"\/documentation\/dotfacelite\/placeholdertype\/!=(_:_:)","kind":"symbol","abstract":[],"title":"!=(_:_:)","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title","value":"DOTPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle","value":[{"text":"DOTPlaceholderType","kind":"identifier"}]}]}]}