{"metadata":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"roleHeading":"Initializer","title":"init(rawValue:)","externalID":"s:14DotFaceCommons15PlaceholderTypeO8rawValueACSgSi_tcfc","modules":[{"name":"DotFaceLite"}],"symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholdertype\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/init(rawValue:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/init(rawValue:)":{"title":"init(rawValue:)","type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/placeholdertype\/init(rawvalue:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/init(rawValue:)","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"title":"PlaceholderType","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype","abstract":[{"type":"text","text":"Type of placeholder."}]}},"variantOverrides":[{"patch":[{"value":"DOTPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}