{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculatePixelCount","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"calculatePixelCount()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculatePixelCount()"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/imagesize\/calculatepixelcount()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/imagesize\/calculatepixelcount()"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/calculatePixelCount()":{"url":"\/documentation\/dotfingerscore\/imagesize\/calculatepixelcount()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/calculatePixelCount()","title":"calculatePixelCount()","role":"symbol","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize":{"url":"\/documentation\/dotfingerscore\/imagesize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"calculatePixelCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"calculatePixelCount"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1calculatePixelCount()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}