{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/cgSize"},"variants":[{"paths":["\/documentation\/dotfingerscore\/imagesize\/cgsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/imagesize\/cgsize"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFingersCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTImageSize(py)cgSize","extendedModule":"DotCore","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"cgSize","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"cgSize","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/ImageSize":{"url":"\/documentation\/dotfingerscore\/imagesize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/cgSize":{"url":"\/documentation\/dotfingerscore\/imagesize\/cgsize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"title":"cgSize","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/cgSize","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"cgSize"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"cgSize","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"cgSize"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" ","kind":"text"},{"text":"cgSize","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTImageSize","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageSize"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/navigatorTitle","op":"replace"},{"value":"cgSize","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1cgSize\/title","op":"replace"},{"value":[{"kind":"identifier","text":"cgSize"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1cgSize\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}