{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"description"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageSize(py)description","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"title":"description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/description","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/imagesize\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/imagesize\/description"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/ImageSize":{"url":"\/documentation\/dotfingerscore\/imagesize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","role":"symbol","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize/description":{"url":"\/documentation\/dotfingerscore\/imagesize\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize\/description","title":"description","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"description","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageSize","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/title"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}