{"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeOutsideOfDocumentValidator(im)init","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","title":"init","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeOutsideOfDocumentValidator\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbarcodeoutsideofdocumentvalidator\/init"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/BarcodeOutsideOfDocumentValidator":{"navigatorTitle":[{"text":"BarcodeOutsideOfDocumentValidator","kind":"identifier"}],"title":"BarcodeOutsideOfDocumentValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeOutsideOfDocumentValidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeOutsideOfDocumentValidator"}],"abstract":[{"type":"text","text":"Validate if barcode is inside detected document bounds."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/barcodeoutsideofdocumentvalidator"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeOutsideOfDocumentValidator/init":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"kind":"symbol","type":"topic","title":"init","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeOutsideOfDocumentValidator\/init","abstract":[],"role":"symbol","url":"\/documentation\/dotdocument\/dotdbarcodeoutsideofdocumentvalidator\/init","navigatorTitle":[{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"patch":[{"value":"DOTDBarcodeOutsideOfDocumentValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/title"},{"value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/fragments"},{"value":[{"text":"DOTDBarcodeOutsideOfDocumentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeOutsideOfDocumentValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}