{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFacePassiveLivenessModuleProtocol"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(pl)DotFacePassiveLivenessModuleProtocol","title":"DotFacePassiveLivenessModuleProtocol","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}],"roleHeading":"Protocol","symbolKind":"protocol","role":"symbol"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"type":"inheritsFrom","title":"Inherits From"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacepassivelivenessmoduleprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfacepassivelivenessmoduleprotocol"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodule","type":"topic","title":"DotFaceModule","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFacePassiveLivenessModuleProtocol":{"navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}],"url":"\/documentation\/dotfacecore\/dotfacepassivelivenessmoduleprotocol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFacePassiveLivenessModuleProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleProtocol","kind":"identifier"}],"type":"topic","title":"DotFacePassiveLivenessModuleProtocol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"DotFacePassiveLivenessModuleProtocol"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","op":"replace","value":"DotFaceModule"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleProtocol\/title","op":"replace","value":"DotFacePassiveLivenessModuleProtocol"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleProtocol"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}