{"sections":[],"metadata":{"navigatorTitle":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"title":"DotFaceDetectionModuleProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(pl)DotFaceDetectionModuleProtocol","modules":[{"name":"DotFaceCore"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleProtocol","interfaceLanguage":"swift"},"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfacedetectionmoduleprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleProtocol":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleprotocol","type":"topic","title":"DotFaceDetectionModuleProtocol","abstract":[],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacemodule","type":"topic","title":"DotFaceModule","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"DotFaceDetectionModuleProtocol","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","text":"DotFaceModule","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"},{"text":">","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleProtocol\/title","value":"DotFaceDetectionModuleProtocol","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleProtocol\/fragments","value":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleProtocol\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"text":"DotFaceModule","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/navigatorTitle","value":[{"text":"DotFaceModule","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}