{"abstract":[{"type":"text","text":"Supported image formats."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg2000","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgr","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgra"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/description"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/SY"],"type":"conformsTo","kind":"relationships"}],"metadata":{"externalID":"c:@M@DotCore@E@DOTImageFormat","title":"ImageFormat","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTImageFormat) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/imageformat"]},{"paths":["\/documentation\/dotfacecore\/imageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfacecore\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"title":"ImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/jpeg2000":{"title":"ImageFormat.jpeg2000","role":"symbol","abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg2000"}],"url":"\/documentation\/dotfacecore\/imageformat\/jpeg2000","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg2000","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/RawRepresentable-Implementations":{"url":"\/documentation\/dotfacecore\/imageformat\/rawrepresentable-implementations","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","title":"RawRepresentable Implementations","abstract":[],"kind":"article"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/rawBgra":{"url":"\/documentation\/dotfacecore\/imageformat\/rawbgra","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgra","title":"ImageFormat.rawBgra","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgra"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"kind":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","url":"\/documentation\/dotfacecore\/imageformat\/description","type":"topic","title":"description","abstract":[],"kind":"symbol"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/jpeg":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg","title":"ImageFormat.jpeg","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"JPEG compressed image format"}],"url":"\/documentation\/dotfacecore\/imageformat\/jpeg"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/rawBgr":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgr","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}],"url":"\/documentation\/dotfacecore\/imageformat\/rawbgr","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"title":"ImageFormat.rawBgr","navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/Equatable-Implementations":{"kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotfacecore\/imageformat\/equatable-implementations"},"doc://DotFaceCore/documentation/DotFaceCore/ImageFormat/init(rawValue:)":{"url":"\/documentation\/dotfacecore\/imageformat\/init(rawvalue:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/init(rawValue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","abstract":[],"title":"init(rawValue:)","kind":"symbol"},"doc://DotFaceCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFaceCore\/SY","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/jpeg2000","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgr","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ImageFormat\/rawBgra"],"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFormat"},{"kind":"text","text":" : "},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg2000\/title","value":"DOTImageFormatJpeg2000","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg2000\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgra\/title","value":"DOTImageFormatRawBgra","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgra\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg\/title","value":"DOTImageFormatJpeg","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1jpeg\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgr\/title","value":"DOTImageFormatRawBgr","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ImageFormat~1rawBgr\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"op":"replace"}]}]}