{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionImage"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFSmileLivenessResult) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessResult","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessresult"]}],"metadata":{"roleHeading":"Class","navigatorTitle":[{"text":"SmileLivenessResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessResult","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessResult","title":"SmileLivenessResult"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"],"generated":true,"title":"Smile liveness result","anchor":"Smile-liveness-result"}],"kind":"symbol","abstract":[{"text":"The result of smile liveness process.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"url":"\/documentation\/dotfacecore\/detectionposition"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/smileExpressionImage":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionImage","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"smileExpressionImage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"navigatorTitle":[{"text":"smileExpressionImage","kind":"identifier"}],"deprecated":true,"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessresult\/smileexpressionimage","type":"topic","title":"smileExpressionImage","abstract":[{"text":"Smile expression face image.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/image":{"navigatorTitle":[{"kind":"identifier","text":"image"}],"title":"image","type":"topic","abstract":[{"text":"Face image.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/image","kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessresult\/image","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessresult\/description","type":"topic","title":"description","abstract":[],"kind":"symbol"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/content":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/content","kind":"symbol","role":"symbol","type":"topic","title":"content","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"content","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessresult\/content","abstract":[{"text":"Binary content for server-side evaluation.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult/face":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/face","title":"face","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceDetector","kind":"typeIdentifier","text":"FaceDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotFaceCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Face"}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"type":"topic","role":"symbol","abstract":[{"text":"Face with neutral face expression.","type":"text"}],"url":"\/documentation\/dotfacecore\/smilelivenessresult\/face"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"url":"\/documentation\/dotfacecore\/faceautocapturedetection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","title":"FaceAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"The result of processing video frame during the face auto capture process.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessResult","kind":"identifier"}],"navigatorTitle":[{"text":"SmileLivenessResult","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessresult","type":"topic","title":"SmileLivenessResult","abstract":[{"text":"The result of smile liveness process.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTFSmileLivenessResult","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFSmileLivenessResult","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFSmileLivenessResult","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/content","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/face","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/image","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessResult\/smileExpressionImage"],"anchor":"Instance-Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Smile liveness result","anchor":"Smile-liveness-result","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTFSmileLivenessResult","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title"},{"value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments"},{"op":"replace","value":[{"text":"DOTDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/navigatorTitle"},{"value":"smileExpressionImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionImage\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1smileExpressionImage\/fragments","value":[{"text":"smileExpressionImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1description\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1content\/title","value":"content"},{"value":[{"text":"content","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1content\/fragments"},{"value":"face","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1face\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult~1face\/fragments","value":[{"text":"face","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title","op":"replace","value":"DOTFFaceAutoCaptureDetection"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/navigatorTitle"},{"op":"replace","value":"DOTFSmileLivenessResult","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFSmileLivenessResult"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessResult\/navigatorTitle","value":[{"text":"DOTFSmileLivenessResult","kind":"identifier"}],"op":"replace"}]}]}