{"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"max"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Initializer","symbolKind":"init","role":"symbol","modules":[{"name":"DotNfc"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"min"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(im)initWithMin:max:error:","title":"init(min:max:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/intervalfloat\/init(min:max:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/init(min:max:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/init(min:max:)"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"]]},"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat/init(min:max:)":{"title":"init(min:max:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"max"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotnfc\/intervalfloat\/init(min:max:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithMin:max:error:"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/init(min:max:)","type":"topic","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"title":"IntervalFloat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"initWithMin:max:error:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithMin:max:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithMin:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"text":") ","kind":"text"},{"text":"min","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"max:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":") "},{"text":"max","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1init(min:max:)\/title","value":"initWithMin:max:error:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1init(min:max:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace"}]}]}