{"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"]]},"abstract":[{"text":"Maximal interval value.","type":"text"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/max","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/max"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/max"]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)max","title":"max","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"max","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotNfc"}],"role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"title":"IntervalFloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","kind":"symbol","url":"\/documentation\/dotnfc\/intervalfloat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/max":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/max","title":"max","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"max"}],"role":"symbol","abstract":[{"text":"Maximal interval value.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/max"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"max"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"max","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"DOTIntervalFloat","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle"},{"op":"replace","value":"max","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1max\/title"},{"op":"replace","value":[{"text":"max","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1max\/fragments"}]}]}