{"metadata":{"title":"init(licenseBytes:libraries:)","modules":[{"name":"DotFaceCore"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","symbolKind":"init","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary","text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"])"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/init(licenseBytes:libraries:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:)"]},{"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration/init(licenseBytes:libraries:)":{"url":"\/documentation\/dotfacecore\/dotsdkconfiguration\/init(licensebytes:libraries:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration\/init(licenseBytes:libraries:)","role":"symbol","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"abstract":[],"title":"init(licenseBytes:libraries:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkConfiguration":{"url":"\/documentation\/dotfacecore\/dotsdkconfiguration","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkConfiguration","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}],"abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"title":"DotSdkConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotLibrary":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotlibrary","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotLibrary","abstract":[],"title":"DotLibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithLicenseBytes:libraries:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries:"},{"kind":"text","text":"("},{"text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"libraries"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/title","value":"initWithLicenseBytes:libraries:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLicenseBytes:libraries:"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration\/title","op":"replace","value":"DotSdkConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkConfiguration\/fragments"},{"value":"DotLibrary","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/title"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotLibrary\/fragments","op":"replace"}]}]}