{"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","text":"DotLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"libraries","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"libraries"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotSdkConfiguration(py)libraries","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","title":"libraries"},"abstract":[{"type":"text","text":"List of "},{"code":"DotSdk","type":"codeVoice"},{"text":" libraries to use.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration\/libraries"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"title":"DotFaceCore","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkConfiguration/libraries":{"title":"libraries","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration\/libraries","abstract":[{"text":"List of ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" libraries to use."}],"kind":"symbol","navigatorTitle":[{"text":"libraries","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdkconfiguration\/libraries","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"libraries","kind":"identifier"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotLibrary","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotLibrary"},{"kind":"text","text":"]"}],"type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotLibrary":{"url":"\/documentation\/dotfacecore\/dotlibrary","abstract":[],"title":"DotLibrary","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkConfiguration":{"type":"topic","role":"symbol","title":"DotSdkConfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkConfiguration","url":"\/documentation\/dotfacecore\/dotsdkconfiguration","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"libraries"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"libraries","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"libraries"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration~1libraries\/title","value":"libraries","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration~1libraries\/fragments","value":[{"kind":"identifier","text":"libraries"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibrary"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration\/title","value":"DotSdkConfiguration"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkConfiguration\/fragments"}]}]}