{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"kind":"symbol","sections":[],"metadata":{"symbolKind":"method","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(im)initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","navigatorTitle":[{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}],"title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","kind":"identifier"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"kind":"text","text":" "},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isTorchEnabled:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraFacing","text":"DOTCameraFacing","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cameraPreviewScaleType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotFaceLite@E@DOTCameraPreviewScaleType","text":"DOTCameraPreviewScaleType","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:":{"type":"topic","abstract":[{"text":"Create the MagnifEye liveness configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:camerafacing:camerapreviewscaletype:","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"}],"title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:cameraFacing:cameraPreviewScaleType:"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.3.2"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraFacing":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraFacing","title":"CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/camerafacing","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CameraPreviewScaleType":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"type":"topic","title":"CameraPreviewScaleType","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CameraPreviewScaleType"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","title":"DOTFLMagnifEyeLivenessConfiguration","abstract":[{"text":"Configuration options for the MagnifEye liveness process.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessConfiguration"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"op":"replace","value":"DOTCameraPreviewScaleType","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}