{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery(im)initWithEyes:evaluateMouth:","roleHeading":"Initializer","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"title":"init(eyes:evaluateMouth:)","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateMouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:evaluateMouth:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"eyes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"EyesExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","kind":"typeIdentifier"},{"text":" = EyesExpressionQuery(), ","kind":"text"},{"text":"evaluateMouth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" = false)","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/expressionquery\/init(eyes:evaluatemouth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/expressionquery\/init(eyes:evaluatemouth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/expressionquery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","title":"ExpressionQuery","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}]},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery/init(eyes:evaluateMouth:)":{"abstract":[],"title":"init(eyes:evaluateMouth:)","role":"symbol","url":"\/documentation\/dotfacecore\/expressionquery\/init(eyes:evaluatemouth:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:evaluateMouth:)","navigatorTitle":[{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluateMouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"kind":"symbol","title":"EyesExpressionQuery","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","url":"\/documentation\/dotfacecore\/eyesexpressionquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithEyes:evaluateMouth:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEyes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTFEyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyes"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateMouth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluateMouth"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title"},{"op":"replace","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/navigatorTitle"},{"op":"replace","value":"initWithEyes:evaluateMouth:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:evaluateMouth:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEyes:evaluateMouth:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:evaluateMouth:)\/fragments"},{"op":"replace","value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/navigatorTitle"}]}]}