{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"widthToHeightRatio"}],"modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","symbolKind":"property","title":"widthToHeightRatio","extendedModule":"DotCore","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)widthToHeightRatio","roleHeading":"Instance Property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"widthToHeightRatio","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/widthToHeightRatio","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/rectangleint\/widthtoheightratio"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangleint\/widthtoheightratio"]}],"references":{"doc://DotNfc/documentation/DotNfc/RectangleInt":{"type":"topic","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"title":"RectangleInt","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","kind":"symbol","url":"\/documentation\/dotnfc\/rectangleint","navigatorTitle":[{"text":"RectangleInt","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/RectangleInt/widthToHeightRatio":{"role":"symbol","url":"\/documentation\/dotnfc\/rectangleint\/widthtoheightratio","kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"widthToHeightRatio","navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/widthToHeightRatio","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","title":"DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 9.4.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"widthToHeightRatio","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"widthToHeightRatio"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title","value":"DOTRectangleInt","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1widthToHeightRatio\/title","value":"widthToHeightRatio","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1widthToHeightRatio\/fragments","value":[{"kind":"identifier","text":"widthToHeightRatio"}],"op":"replace"}]}]}