{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC","text":"Result"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The detection result that contains "},{"type":"codeVoice","code":"confidence"},{"type":"text","text":", "},{"type":"codeVoice","code":"corners"},{"type":"text","text":" and "},{"type":"codeVoice","code":"widthHeightRatio"},{"type":"text","text":"."}]}]},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image on which is performed the detection."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Detect document in an image and return the detection result."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"}],"title":"detect(bgraRawImage:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector(im)detectWithBgraRawImage:error:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"detectWithBgraRawImage:error:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"role":"symbol","title":"BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotdocument\/bgrarawimage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/detect(bgraRawImage:)":{"role":"symbol","title":"detect(bgraRawImage:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"}],"abstract":[{"type":"text","text":"Detect document in an image and return the detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectWithBgraRawImage:error:"}],"url":"\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorResult":{"role":"symbol","title":"DOTDDocumentDetectorResult","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorResult"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentdetectorresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.3"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result":{"role":"symbol","title":"DocumentDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/documentdetector\/result"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"detectWithBgraRawImage:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectWithBgraRawImage:error:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorResult","text":"DOTDDocumentDetectorResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"detectWithBgraRawImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *)"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:)\/title","value":"detectWithBgraRawImage:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"detectWithBgraRawImage:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}