{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/detect(image:limit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentdetector\/detect(image:limit:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" = 1) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","text":"Document","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"]"}]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The image on which the detection is performed. Terminates if "},{"type":"codeVoice","code":"image"},{"type":"text","text":" is not in "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"type":"paragraph"}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"Limit the number of documents to detect. Currently, it is supported to detect only one document."}],"type":"paragraph"}],"name":"limit"}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"Array of detected documents.","type":"text"}],"type":"paragraph"}],"kind":"content"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}],"type":"paragraph"},{"content":[{"inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"DocumentDetector"},{"type":"text","text":" fails to execute document detection."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Throws"}],"kind":"content"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/detect(image:limit:)","interfaceLanguage":"swift"},"metadata":{"title":"detect(image:limit:)","symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotDocument"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector(im)detectWithImage:limit:error:","navigatorTitle":[{"text":"detectWithImage:limit:error:","kind":"identifier"}],"role":"symbol"},"sections":[],"abstract":[{"text":"Detect documents in an image.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"role":"symbol","url":"\/documentation\/dotdocument\/documentdetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/detect(image:limit:)":{"navigatorTitle":[{"kind":"identifier","text":"detectWithImage:limit:error:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/detect(image:limit:)","url":"\/documentation\/dotdocument\/documentdetector\/detect(image:limit:)","title":"detect(image:limit:)","kind":"symbol","abstract":[{"text":"Detect documents in an image.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Image":{"url":"\/documentation\/dotdocument\/image","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","title":"Image","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"role":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/document","navigatorTitle":[{"text":"Document","kind":"identifier"}],"title":"DocumentDetector.Document","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"detectWithImage:limit:error:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<DOTDDocumentDetectorDocument *>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"limit:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image on which the detection is performed. Terminates if ","type":"text"},{"type":"codeVoice","code":"image"},{"text":" is not in ","type":"text"},{"type":"codeVoice","code":".rawBgra"},{"text":" format.","type":"text"}]}]},{"name":"limit","content":[{"type":"paragraph","inlineContent":[{"text":"Limit the number of documents to detect. Currently, it is supported to detect only one document.","type":"text"}]}]},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"On output, a pointer to an error object that describes why the method failed, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"Array of detected documents."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}],"type":"paragraph"}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle"},{"value":"detectWithImage:limit:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector~1detect(image:limit:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"detectWithImage:limit:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector~1detect(image:limit:)\/fragments"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/title"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/fragments"},{"value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Image\/navigatorTitle"}]}]}