{"sections":[],"metadata":{"title":"detect(bgraRawImage:limit:)","modules":[{"name":"DotDocument"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector(im)detectWithBgraRawImage:limit:error:","navigatorTitle":[{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detect","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier","text":"Document"},{"kind":"text","text":"]"}],"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:limit:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"detect","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","text":"Document"},{"text":"]","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"bgraRawImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Image on which is performed the detection."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Limit the number of documents to detect. Currently is supported to detect only one document.","type":"text"}]}],"name":"limit"}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Array of detected documents."}],"type":"paragraph"}]}],"kind":"symbol","abstract":[{"text":"Detect document in an image.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:limit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:limit:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.3.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/BgraRawImage":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/bgrarawimage","title":"BgraRawImage"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"title":"DocumentDetector","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/detect(bgraRawImage:limit:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"text":"Document","kind":"typeIdentifier","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"text":"]","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"Detect document in an image."}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/detect(bgrarawimage:limit:)","kind":"symbol","title":"detect(bgraRawImage:limit:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/detect(bgraRawImage:limit:)","navigatorTitle":[{"kind":"identifier","text":"detectWithBgraRawImage:limit:error:"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Document":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Document","type":"topic","abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector\/document","title":"DocumentDetector.Document","navigatorTitle":[{"text":"Document","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"detectWithBgraRawImage:limit:error:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"detectWithBgraRawImage:limit:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTDDocumentDetectorDocument *>"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"detectWithBgraRawImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BgraRawImage","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"text":"bgraRawImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"limit:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"limit"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"value":"detectWithBgraRawImage:limit:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:limit:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector~1detect(bgraRawImage:limit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}