{"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"kind":"relationships"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"title":"DocumentDetector.Document","modules":[{"name":"DotDocument"}],"symbolKind":"class","externalID":"s:11DotDocument0B8DetectorC0B0C","role":"symbol","navigatorTitle":[{"text":"Document","kind":"identifier"}],"roleHeading":"Class"},"seeAlsoSections":[{"generated":true,"title":"Document detection output","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTDDocumentDetectorDocument) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/confidence","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/description","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/detectionPosition","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/imageParameters","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/widthToHeightRatio"],"title":"Instance Properties"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/document"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Result of the document detection process."}],"sections":[],"kind":"symbol","references":{"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/confidence":{"title":"confidence","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document\/confidence","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidence"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Document detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/confidence"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/detectionPosition":{"type":"topic","title":"detectionPosition","url":"\/documentation\/dotdocument\/documentdetector\/document\/detectionposition","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition"}],"kind":"symbol","abstract":[{"type":"text","text":"Detected corners of the document card."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/detectionPosition"},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"ObjectiveC.NSObject"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"title":"DocumentDetector","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}]},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/description":{"type":"topic","title":"description","url":"\/documentation\/dotdocument\/documentdetector\/document\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/description"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"title":"DocumentDetector.Document","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Document"}],"kind":"symbol","abstract":[{"type":"text","text":"Result of the document detection process."}],"role":"symbol","navigatorTitle":[{"text":"Document","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/widthToHeightRatio":{"title":"widthToHeightRatio","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document\/widthtoheightratio","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"widthToHeightRatio","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Detected width to height ratio of the document."}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/widthToHeightRatio"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)":{"type":"topic","title":"init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)","url":"\/documentation\/dotdocument\/documentdetector\/document\/init(detectionposition:confidence:widthtoheightratio:imageparameters:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"detectionPosition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","text":"DetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"text":"widthToHeightRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"imageParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"ImageParameters","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/init(detectionPosition:confidence:widthToHeightRatio:imageParameters:)"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"title":"MrzReader"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/imageParameters":{"title":"imageParameters","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document\/imageparameters","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageParameters"},{"text":": ","kind":"text"},{"text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","kind":"typeIdentifier"}],"kind":"symbol","abstract":[{"text":"Image parameters calculated from area of the detected document.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/imageParameters"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"type":"topic","title":"DetectionPosition","url":"\/documentation\/dotdocument\/detectionposition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"kind":"symbol","abstract":[{"text":"Position of the document card in the image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDDocumentDetector","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":"DOTDDetectionPosition","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDetectionPosition"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}