{"seeAlsoSections":[{"title":"Document detection output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Corners"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"title":"DocumentDetector.Result","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"s:11DotDocument0B8DetectorC6ResultC","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"Result"}]},"abstract":[{"type":"text","text":"Result of the document detection process."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector"],["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/init(confidence:widthToHeightRatio:corners:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/confidence","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/corners","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/widthToHeightRatio"]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/result"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTDDocumentDetectorResult) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result":{"role":"symbol","title":"DocumentDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/documentdetector\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result/init(confidence:widthToHeightRatio:corners:)":{"role":"symbol","title":"init(confidence:widthToHeightRatio:corners:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/init(confidence:widthToHeightRatio:corners:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/result\/init(confidence:widthtoheightratio:corners:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Corners":{"role":"symbol","title":"Corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Corners","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotdocument\/corners"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result/corners":{"role":"symbol","title":"corners","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"corners"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTCorners"}],"abstract":[{"type":"text","text":"Detected corner points."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/corners","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/result\/corners"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/result\/description"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result/confidence":{"role":"symbol","title":"confidence","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Document detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/confidence","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/result\/confidence"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result/widthToHeightRatio":{"role":"symbol","title":"widthToHeightRatio","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTWrappedDouble"}],"abstract":[{"type":"text","text":"Detected width to height ratio of the document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result\/widthToHeightRatio","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/result\/widthtoheightratio"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.2"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}