{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/Equatable-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/!=(_:_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/camerafacing\/!=(_:_:)"]}],"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCamera@E@DOTCameraFacing","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"roleHeading":"Operator","modules":[{"name":"DotFaceLite","relatedModules":["Swift"]}],"title":"!=(_:_:)","extendedModule":"Swift","role":"symbol"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing/!=(_:_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","title":"!=(_:_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/!=(_:_:)","url":"\/documentation\/dotfacelite\/camerafacing\/!=(_:_:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing/Equatable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotfacelite\/camerafacing\/equatable-implementations","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"kind":"symbol","title":"CameraFacing","url":"\/documentation\/dotfacelite\/camerafacing","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments"},{"value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/navigatorTitle"}]}]}