{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/camerafacing\/front"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/camerafacing\/front"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/front"},"sections":[],"metadata":{"title":"CameraFacing.front","modules":[{"name":"DotFaceLite"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing@DOTCameraFacingFront","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"DOTCameraFacingFront","kind":"identifier"}]},"kind":"symbol","abstract":[{"text":"Front facing camera.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing/front":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing\/front","title":"CameraFacing.front","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/camerafacing\/front","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"role":"symbol","abstract":[{"type":"text","text":"Front facing camera."}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"title":"CameraFacing","role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTCameraFacingFront","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTCameraFacingFront"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCameraFacingFront","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing~1front\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacingFront"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing~1front\/fragments","op":"replace"},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/navigatorTitle","op":"replace"}]}]}