{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel"]]},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"roleHeading":"Case","title":"LoggerLogLevel.error","externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelError"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Logs failed operations and other errors."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/loggerloglevel\/error"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel/error":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel\/error","navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"type":"topic","title":"LoggerLogLevel.error","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel\/error","abstract":[{"type":"text","text":"Logs failed operations and other errors."}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/LoggerLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/loggerloglevel","navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/LoggerLogLevel","title":"LoggerLogLevel","abstract":[{"type":"text","text":"Available log levels."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DOTLoggerLogLevelError","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","value":"DOTLoggerLogLevelError","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1error\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel~1error\/fragments","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/title","op":"replace","value":"DOTLoggerLogLevel"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}],"op":"replace"}]}]}