{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","text":"Configuration","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC","text":"Style","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Style-swift.class"},{"kind":"text","text":" = .init())"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"Configure the eye gaze liveness process.","type":"text"}],"type":"paragraph"}],"name":"configuration"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Customize user interface.","type":"text"}]}],"name":"style"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New instance of "},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"text":".","type":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/init(configuration:style:)"},"abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"init(configuration:style:)","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController(im)initWithConfiguration:style:","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC"},{"text":")","kind":"text"}],"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"role":"symbol","symbolKind":"init"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/init(configuration:style:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"title":"EyeGazeLivenessViewController","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","role":"symbol","abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Style-swift.class":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Style","kind":"identifier"}],"type":"topic","title":"EyeGazeLivenessViewController.Style","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Style-swift.class","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the eye gaze liveness user interface.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"type":"topic","abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"title":"EyeGazeLivenessViewController.Configuration","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessStyle":{"title":"DOTFEyeGazeLivenessStyle","type":"topic","abstract":[{"text":"Customization options for the eye gaze liveness user interface.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStyle"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessStyle","kind":"symbol","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessstyle","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"title":"DOTFEyeGazeLivenessConfiguration","url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","type":"topic","abstract":[{"text":"Configuration options for the eye gaze liveness process.","type":"text"}],"fragments":[{"text":"DOTFEyeGazeLivenessConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/init(configuration:style:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"title":"init(configuration:style:)","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/init(configuration:style:)","abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessViewController"},{"text":".","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/init(configuration:style:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC5StyleC"},{"text":")","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfiguration:style:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:style:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","text":"DOTFEyeGazeLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":" "},{"kind":"identifier","text":"style:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessStyle","text":"DOTFEyeGazeLivenessStyle","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessStyle"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"style"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]},{"value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1init(configuration:style:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController~1init(configuration:style:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:style:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}