{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}]}],"kind":"declarations"}],"metadata":{"externalID":"s:11DotDocument0B37AutoCaptureQualityAttributeThresholdsC7BuilderCAEycfc","modules":[{"name":"DotDocument"}],"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"roleHeading":"Initializer","title":"init()","role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder\/init()"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/Builder/init()":{"role":"symbol","kind":"symbol","title":"init()","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder\/init()","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder\/init()"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"kind":"symbol","title":"DocumentAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the document auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds/Builder":{"title":"DocumentAutoCaptureQualityAttributeThresholds.Builder","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds\/Builder","abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds\/builder","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}