{"sections":[],"kind":"symbol","metadata":{"title":"isEqual(_:)","role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"externalID":"c:@M@DotCore@objc(cs)DOTCorners(im)isEqual:","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/isEqual(_:)"},"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/corners\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/corners\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/Corners":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","kind":"symbol","title":"Corners","url":"\/documentation\/dotnfc\/corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Corners/isEqual(_:)":{"abstract":[],"kind":"symbol","title":"isEqual(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/isEqual(_:)","url":"\/documentation\/dotnfc\/corners\/isequal(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","op":"replace","value":"DOTCorners"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}