{"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/description","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/CustomStringConvertible-Implementations"]]},"metadata":{"externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:6DotNfc0B3KeyC5ErrorO","symbolKind":"property","extendedModule":"DotCore","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"roleHeading":"Instance Property","title":"description"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotNfc/documentation/DotNfc/NfcKey/Error/description":{"url":"\/documentation\/dotnfc\/nfckey\/error\/description","type":"topic","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","title":"description"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/CustomStringConvertible-Implementations":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/CustomStringConvertible-Implementations","url":"\/documentation\/dotnfc\/nfckey\/error\/customstringconvertible-implementations","title":"CustomStringConvertible Implementations","role":"collectionGroup","abstract":[],"kind":"article"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.1","type":"text"}],"title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcKey":{"title":"NfcKey","kind":"symbol","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfckey","type":"topic","abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"deprecated":true},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","url":"\/documentation\/dotnfc\/nfckey\/error","abstract":[],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"deprecated":true,"navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","title":"NfcKey.Error","type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","kind":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"text":"DOTNNfcKey","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}