{"sections":[],"abstract":[{"type":"text","text":"Face Keypoint"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To"}],"metadata":{"roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotFaceCore"}],"title":"FaceKeypoint","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoint","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceKeypoint"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceKeypoint"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFFaceKeypoint) "},{"kind":"attribute","text":"@objcMembers"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facekeypoint"]},{"paths":["\/documentation\/dotfacecore\/facekeypoint"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/init(position:score:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/position","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/score"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint":{"url":"\/documentation\/dotfacecore\/facekeypoint","title":"FaceKeypoint","abstract":[{"type":"text","text":"Face Keypoint"}],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceKeypoint","kind":"identifier"}],"navigatorTitle":[{"text":"FaceKeypoint","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint"},"doc://DotFaceCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/init(position:score:)":{"url":"\/documentation\/dotfacecore\/facekeypoint\/init(position:score:)","title":"init(position:score:)","abstract":[],"type":"topic","role":"symbol","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"score","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":"?)","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/init(position:score:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/description":{"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoint\/description","title":"description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/description","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/position":{"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoint\/position","title":"position","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/position","kind":"symbol","abstract":[{"type":"text","text":"Keypoint position."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"position","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"kind":"identifier","text":"position"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoint/score":{"type":"topic","url":"\/documentation\/dotfacecore\/facekeypoint\/score","title":"score","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/score","kind":"symbol","abstract":[{"type":"text","text":"Optional keypoint detection score."}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTFFaceKeypoint","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceKeypoint"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoint\/position"],"title":"Instance Properties"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceKeypoint","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/title","value":"DOTFFaceKeypoint"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoint","kind":"identifier"}]},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint~1description\/title"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint~1description\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint~1position\/title","op":"replace","value":"position"},{"value":[{"text":"position","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoint~1position\/fragments","op":"replace"}]}]}