{"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"],"title":"Non-UI components"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFFaceMatcher) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceMatcher","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This component requires permission in DotFace license and ","type":"text"},{"type":"codeVoice","code":"DotFaceVerification"},{"text":" module to be active.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facematcher"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facematcher"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcher","title":"FaceMatcher"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"abstract":[{"text":"Stateless class which can match face images and templates.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result"],"title":"Classes"},{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/init()"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceFaceImage:probeFaceImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplate:probeFaceImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplateBytes:probeFaceImage:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"],"title":"Enumerations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"kind":"relationships"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TemplateMatcher","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"title":"TemplateMatcher"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/match(referenceTemplateBytes:probeFaceImage:)":{"url":"\/documentation\/dotfacecore\/facematcher\/match(referencetemplatebytes:probefaceimage:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"match","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"referenceTemplateBytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"probeFaceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","kind":"typeIdentifier","text":"Result"}],"role":"symbol","kind":"symbol","title":"match(referenceTemplateBytes:probeFaceImage:)","navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceTemplateBytes:probeFaceImage:error:"}],"type":"topic","abstract":[{"text":"Match face image against reference face image.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplateBytes:probeFaceImage:)"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Matching errors."}],"type":"topic","title":"FaceMatcher.Error","url":"\/documentation\/dotfacecore\/facematcher\/error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Error"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/init()":{"url":"\/documentation\/dotfacecore\/facematcher\/init()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"title":"init()","role":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/init()"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.14.0"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Result":{"navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacecore\/facematcher\/result","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}],"abstract":[{"text":"Face matcher result.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","title":"FaceMatcher.Result","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/match(referenceFaceImage:probeFaceImage:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceFaceImage:probeFaceImage:)","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/match(referencefaceimage:probefaceimage:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceFaceImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","kind":"typeIdentifier","text":"FaceImage"},{"text":", ","kind":"text"},{"text":"probeFaceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC"}],"title":"match(referenceFaceImage:probeFaceImage:)","navigatorTitle":[{"text":"matchWithReferenceFaceImage:probeFaceImage:error:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Match face image against reference face image.","type":"text"}]},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"role":"symbol","url":"\/documentation\/dotfacecore\/facedetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect faces in an image.","type":"text"}],"title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","type":"topic","kind":"symbol"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceMatcher"}],"navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match face images and templates."}],"type":"topic","title":"FaceMatcher","url":"\/documentation\/dotfacecore\/facematcher","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/match(referenceTemplate:probeFaceImage:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplate:probeFaceImage:)","title":"match(referenceTemplate:probeFaceImage:)","url":"\/documentation\/dotfacecore\/facematcher\/match(referencetemplate:probefaceimage:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeFaceImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","kind":"typeIdentifier","text":"FaceImage"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","text":"Result"}],"abstract":[{"text":"Match face image against reference face image.","type":"text"}],"navigatorTitle":[{"text":"matchWithReferenceTemplate:probeFaceImage:error:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"DOTFFaceMatcher","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/init()","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceFaceImage:probeFaceImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplate:probeFaceImage:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplateBytes:probeFaceImage:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher"],"generated":true,"title":"Non-UI components"}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFFaceMatcher","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher"},{"value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","op":"replace"},{"value":"matchWithReferenceTemplateBytes:probeFaceImage:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplateBytes:probeFaceImage:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplateBytes:probeFaceImage:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplateBytes:probeFaceImage:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1init()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace"},{"value":"matchWithReferenceFaceImage:probeFaceImage:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceFaceImage:probeFaceImage:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceFaceImage:probeFaceImage:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceFaceImage:probeFaceImage:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"value":"DOTFFaceMatcher","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title"},{"value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplate:probeFaceImage:)\/title","value":"matchWithReferenceTemplate:probeFaceImage:error:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplate:probeFaceImage:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplate:probeFaceImage:)\/fragments"}]}]}