{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/common"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/common"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","text":"DOTCommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration(py)common","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"common","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"identifier","text":"common"}],"title":"common"},"references":{"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"url":"\/documentation\/dotdocument\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","title":"CommonConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration":{"title":"DOTDDocumentAutoCaptureControllerConfiguration","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","fragments":[{"text":"DOTDDocumentAutoCaptureControllerConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration/common":{"role":"symbol","type":"topic","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"text":"common","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/common","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/common","title":"common"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle"}]}]}