{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/detectionArea","interfaceLanguage":"occ"},"kind":"symbol","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the document detection."}],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/detectionarea"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"detectionArea"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration(py)detectionArea","modules":[{"name":"DotDocument"}],"fragments":[{"text":"detectionArea","kind":"identifier"}],"navigatorTitle":[{"text":"detectionArea","kind":"identifier"}],"title":"detectionArea","symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration","kind":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureControllerConfiguration","kind":"identifier"}],"type":"topic","title":"DOTDDocumentAutoCaptureControllerConfiguration","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration/detectionArea":{"role":"symbol","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/detectionarea","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/detectionArea","fragments":[{"text":"detectionArea","kind":"identifier"}],"type":"topic","kind":"symbol","title":"detectionArea","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the document detection."}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}