{"abstract":[{"type":"text","text":"Create document auto capture controller configuration."}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:validators:detectionArea:error:","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTAutoCaptureConfiguration","preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"autoCapture"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<id<DOTDDocumentAutoCaptureFrameParametersValidator>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"validators"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detectionArea"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/initwithcommon:autocapture:validators:detectionarea:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration"]]},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration(im)initWithCommon:autoCapture:validators:detectionArea:error:","navigatorTitle":[{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}],"role":"symbol","symbolKind":"method","modules":[{"name":"DotDocument"}],"title":"initWithCommon:autoCapture:validators:detectionArea:error:"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"url":"\/documentation\/dotdocument\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","title":"CommonConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration":{"title":"DOTDDocumentAutoCaptureControllerConfiguration","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration","fragments":[{"text":"DOTDDocumentAutoCaptureControllerConfiguration","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}]},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureControllerConfiguration/initWithCommon:autoCapture:validators:detectionArea:error:":{"type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerconfiguration\/initwithcommon:autocapture:validators:detectionarea:error:","title":"initWithCommon:autoCapture:validators:detectionArea:error:","navigatorTitle":[{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerConfiguration\/initWithCommon:autoCapture:validators:detectionArea:error:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:autoCapture:validators:detectionArea:error:","kind":"identifier"}],"abstract":[{"text":"Create document auto capture controller configuration.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"title":"RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","role":"symbol","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}