{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/description"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid\/description"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"CustomStringConvertible.description","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A12FaceModuleIdO11descriptionSSvp","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"description","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId":{"url":"\/documentation\/dotfingerscore\/dotfacemoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId","title":"DotFaceModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceModuleId","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/title"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/navigatorTitle"}]}]}