{"metadata":{"modules":[{"name":"DotFingersCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"RawRepresentable Implementations"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/hashValue"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/hash(into:)"],"generated":true,"title":"Instance Methods"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid\/rawrepresentable-implementations"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/hash(into:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"hash(into:)","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/hash(into:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId":{"url":"\/documentation\/dotfingerscore\/dotfacemoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId","title":"DotFaceModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/hashValue":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"hashValue","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/hashvalue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}