{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgplaceholdervisible\/initwithtype:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholderVisible(im)initWithType:","title":"initWithType:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithType:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithType:"}],"modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithType:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGPlaceholderType","kind":"typeIdentifier","text":"DOTFGPlaceholderType","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"type"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible\/initWithType:"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"type":"topic","kind":"symbol","title":"PlaceholderType","url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderVisible":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible","type":"topic","fragments":[{"kind":"identifier","text":"DOTFGPlaceholderVisible"}],"title":"DOTFGPlaceholderVisible","url":"\/documentation\/dotfingerscore\/dotfgplaceholdervisible","kind":"symbol","abstract":[{"type":"text","text":"Visible placeholder."}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderVisible/initWithType:":{"role":"symbol","title":"initWithType:","navigatorTitle":[{"text":"initWithType:","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotfgplaceholdervisible\/initwithtype:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithType:"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible\/initWithType:","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGPlaceholderType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTFGPlaceholderType"}]},{"value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle"}]}]}