{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/othernames"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/othernames"]}],"metadata":{"platforms":[{"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false}],"title":"otherNames","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"otherNames","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)otherNames","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"otherNames"}],"modules":[{"name":"DotNfc"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherNames","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"abstract":[{"type":"text","text":"Other names."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"otherNames"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/otherNames":{"abstract":[{"type":"text","text":"Other names."}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/othernames","title":"otherNames","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"otherNames","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"]?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/otherNames","kind":"symbol","navigatorTitle":[{"text":"otherNames","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/additionalpersonaldetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"role":"symbol","title":"AdditionalPersonalDetails","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"otherNames","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"otherNames"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSString *>"},{"kind":"text","text":" * "},{"text":"otherNames","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"otherNames","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherNames\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1otherNames\/fragments","value":[{"text":"otherNames","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"value":"DOTNAdditionalPersonalDetails","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"}]}]}