{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/init(preview:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","text":"PalmAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/init(preview:)"},"metadata":{"externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC4IdleC7previewAeA0bdE7PreviewC_tcfc","roleHeading":"Initializer","symbolKind":"init","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"preview","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"PalmAutoCapturePreview","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(preview:)","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle","title":"PalmAutoCaptureUiState.Idle","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","abstract":[{"type":"text","text":"Idle state."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Idle"}],"navigatorTitle":[{"kind":"identifier","text":"Idle"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle/init(preview:)":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/init(preview:)","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/init(preview:)","kind":"symbol","title":"init(preview:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"PalmAutoCapturePreview"},{"kind":"text","text":")"}],"abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturepreview","title":"PalmAutoCapturePreview","role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"role":"symbol","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"title":"PalmAutoCaptureUiState","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","value":"DOTPPalmAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","value":"DOTPPalmAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace"}]}]}