{"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/preview"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC4IdleC7previewAA0bdE7PreviewCvp","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","title":"preview","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Preview information.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/preview","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePreview":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturepreview","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCapturePreview","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePreview","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePreview","abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"type":"topic","title":"PalmAutoCapturePreview"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle/preview":{"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCapturePreview","text":"PalmAutoCapturePreview","kind":"typeIdentifier"}],"title":"preview","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/preview","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/preview","abstract":[{"type":"text","text":"Preview information."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"title":"PalmAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"navigatorTitle":[{"text":"Idle","kind":"identifier"}],"title":"PalmAutoCaptureUiState.Idle","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle","abstract":[{"type":"text","text":"Idle state."}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/title","value":"DOTPPalmAutoCapturePreview","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/fragments","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTPPalmAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","value":"DOTPPalmAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}