{"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]},{"paths":["\/documentation\/dotpalmcore\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory"]]},"sections":[],"metadata":{"symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"roleHeading":"Type Method","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTBezierPathFactory(cm)createPlaceholderPathWithRect:cornerRadius:","title":"createPlaceholderPath(rect:cornerRadius:)","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"text":": ","kind":"text"},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}]},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"type":"topic","title":"createPlaceholderPath(rect:cornerRadius:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"abstract":[],"role":"symbol","navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","url":"\/documentation\/dotpalmcore\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory":{"title":"BezierPathFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/bezierpathfactory","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"createPlaceholderPathWithRect:cornerRadius:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"},{"text":" *) ","kind":"text"},{"text":"createPlaceholderPathWithRect:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"rect","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornerRadius:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"op":"replace"},{"value":"DOTBezierPathFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/title"},{"value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/fragments","op":"replace"}]}]}