{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"createDetectionPath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTCorners","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"corners"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"role":"symbol","symbolKind":"method","modules":[{"name":"DotPalmCore"}],"title":"createDetectionPath(corners:cornerRadius:)","externalID":"c:@M@DotPalmCore@objc(cs)DOTBezierPathFactory(cm)createDetectionPathWithCorners:cornerRadius:","roleHeading":"Type Method"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)"]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory":{"title":"BezierPathFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/bezierpathfactory","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/Corners":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"url":"\/documentation\/dotpalmcore\/corners","title":"Corners"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"type":"topic","title":"createDetectionPath(corners:cornerRadius:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createDetectionPath"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTCorners","text":"Corners"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","url":"\/documentation\/dotpalmcore\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","kind":"symbol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"createDetectionPathWithCorners:cornerRadius:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"},{"kind":"text","text":" *) "},{"text":"createDetectionPathWithCorners:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCorners","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTCorners","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Corners"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"corners"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cornerRadius:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"text":"cornerRadius","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/title","value":"DOTBezierPathFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBezierPathFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners\/title","value":"DOTCorners"},{"op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Corners\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title","value":"createDetectionPathWithCorners:cornerRadius:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}]}]}]}