{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"title":"Validators","generated":true}],"variants":[{"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator"]}],"abstract":[{"type":"text","text":"Validate size of the detected face."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTFLSizeTooSmallValidator) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init(minDetectionSizeToImageShorterSideRatioThreshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/identifier","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SizeTooSmallValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooSmallValidator","symbolKind":"class","modules":[{"name":"DotFaceLite"}],"title":"SizeTooSmallValidator","roleHeading":"Class"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/identifier":{"role":"symbol","title":"identifier","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/identifier","type":"topic","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/identifier"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureController","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooLargeValidator":{"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","abstract":[{"type":"text","text":"Validate size of the detected face."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/dependencyIdentifiers":{"role":"symbol","title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/dependencyIdentifiers","type":"topic","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/dependencyidentifiers"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooHighValidator":{"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"title":"BrightnessTooHighValidator","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/init(minDetectionSizeToImageShorterSideRatioThreshold:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"navigatorTitle":[{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(minDetectionSizeToImageShorterSideRatioThreshold:)","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/init(mindetectionsizetoimageshortersideratiothreshold:)","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init(minDetectionSizeToImageShorterSideRatioThreshold:)","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"title":"FaceOutOfBoundsValidator","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","abstract":[{"type":"text","text":"Validate if the detected face is within the specified bounds."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/defaultMinDetectionSizeToImageShorterSideRatioThreshold":{"navigatorTitle":[{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"}],"kind":"symbol","title":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold","role":"symbol","abstract":[{"type":"text","text":"Default threshold value."}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/defaultmindetectionsizetoimageshortersideratiothreshold","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/minDetectionSizeToImageShorterSideRatioThreshold":{"navigatorTitle":[{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"}],"type":"topic","title":"minDetectionSizeToImageShorterSideRatioThreshold","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/mindetectionsizetoimageshortersideratiothreshold","abstract":[{"type":"text","text":"Current minimal accepted size."}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BrightnessTooLowValidator":{"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator":{"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"title":"SizeTooSmallValidator","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","abstract":[{"type":"text","text":"Validate size of the detected face."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/init()":{"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"role":"symbol","title":"init()","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/init()","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init()","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceNotDetectedValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceNotDetectedValidator","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","title":"FaceNotDetectedValidator","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Validates confidence of the detected face."}]},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/validate(faceAutoCaptureFrameParameters:)":{"role":"symbol","title":"validate(faceAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/validate(faceAutoCaptureFrameParameters:)","type":"topic","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/validate(faceautocaptureframeparameters:)"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"title":"FaceAutoCaptureDetectionValidator","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","navigatorTitle":[{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLSizeTooSmallValidator"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/dependencyIdentifiers","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/identifier","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/minDetectionSizeToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init(minDetectionSizeToImageShorterSideRatioThreshold:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/defaultMinDetectionSizeToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"]}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"title":"Validators","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1identifier\/title","value":"identifier","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1identifier\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace"},{"value":"DOTFLSizeTooLargeValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","value":"DOTFLBrightnessTooHighValidator"},{"value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","op":"replace"},{"value":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init(minDetectionSizeToImageShorterSideRatioThreshold:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init(minDetectionSizeToImageShorterSideRatioThreshold:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","op":"replace","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}]},{"value":"defaultMinDetectionSizeToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1defaultMinDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"kind":"identifier","text":"defaultMinDetectionSizeToImageShorterSideRatioThreshold"}],"op":"replace"},{"op":"replace","value":"minDetectionSizeToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1minDetectionSizeToImageShorterSideRatioThreshold\/fragments","value":[{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"op":"replace"},{"value":"DOTFLSizeTooSmallValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title","value":"DOTFLSharpnessTooLowValidator"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init()\/title","value":"init","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","value":"DOTFLFaceNotDetectedValidator","op":"replace"},{"op":"replace","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1validate(faceAutoCaptureFrameParameters:)\/title","value":"validateWithFaceAutoCaptureFrameParameters:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}]},{"op":"replace","value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments","op":"replace"}]}]}