{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters\/brightness"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/imageparameters\/brightness"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageparameters\/brightness"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"symbolKind":"property","title":"brightness","role":"symbol","roleHeading":"Instance Property","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"brightness","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters(py)brightness"},"abstract":[{"text":"Overall brightness of the palm in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imageparameters","kind":"symbol","title":"ImageParameters","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters/brightness":{"role":"symbol","abstract":[{"type":"text","text":"Overall brightness of the palm in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness."}],"title":"brightness","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters\/brightness","url":"\/documentation\/dotpalmcore\/imageparameters\/brightness","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","title":"PalmDetector","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"brightness"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"brightness","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"brightness"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","op":"replace","value":"DOTPImageParameters"},{"value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments"},{"op":"replace","value":"brightness","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters~1brightness\/title"},{"value":[{"text":"brightness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters~1brightness\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}