{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentImageQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/imageQuality","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"property","title":"imageQuality","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentImageQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"}],"navigatorTitle":[{"kind":"identifier","text":"imageQuality"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality(py)imageQuality","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/dotdocument\/documentquality\/imagequality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentquality\/imagequality"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Image quality."}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"abstract":[{"type":"text","text":"Document quality."}],"navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DocumentQuality","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","url":"\/documentation\/dotdocument\/documentquality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentQuality/imageQuality":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DocumentImageQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/imageQuality","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/documentquality\/imagequality","type":"topic","abstract":[{"text":"Image quality.","type":"text"}],"title":"imageQuality"},"doc://DotDocument/documentation/DotDocument/DocumentImageQuality":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","abstract":[{"type":"text","text":"Document image quality."}],"type":"topic","role":"symbol","kind":"symbol","title":"DocumentImageQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentImageQuality","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentImageQuality","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentimagequality"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"imageQuality","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"imageQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTDDocumentImageQuality","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentImageQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentImageQuality"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageQuality"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentQuality","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title"},{"value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments"},{"value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle"},{"value":"imageQuality","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1imageQuality\/title"},{"value":[{"text":"imageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1imageQuality\/fragments"},{"value":"DOTDDocumentImageQuality","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/title"},{"value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/fragments"},{"value":[{"text":"DOTDDocumentImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentImageQuality\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}