{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"configuration"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController(py)configuration","title":"configuration","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"property"},"abstract":[{"text":"Current configuration.","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/configuration-swift.property","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController"]]},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"abstract":[{"text":"UI Multi-Range Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","type":"topic","title":"MultiRangeLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessConfiguration":{"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration","type":"topic","title":"DOTFLMultiRangeLivenessConfiguration","fragments":[{"text":"DOTFLMultiRangeLivenessConfiguration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessconfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Configuration-swift.class":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the UI Multi-Range Liveness component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Configuration-swift.class","type":"topic","title":"MultiRangeLivenessViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.class","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/configuration-swift.property":{"title":"configuration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"configuration"}],"abstract":[{"text":"Current configuration.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC13ConfigurationC"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/configuration-swift.property","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/configuration-swift.property"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"configuration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessConfiguration","text":"DOTFLMultiRangeLivenessConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessConfiguration"},{"text":" * ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"text":"DOTFLMultiRangeLivenessViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1configuration-swift.property\/fragments","value":[{"text":"configuration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}