{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Style-swift.class","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC5StyleC","text":"Style"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.property"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC5StyleC","text":"Style"}],"navigatorTitle":[{"text":"style","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController(py)style","title":"style","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"abstract":[{"type":"text","text":"Current style."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/style-swift.property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController":{"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for Multi-Range Liveness evaluation."}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/Style-swift.class":{"kind":"symbol","title":"MultiRangeLivenessViewController.Style","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.class","abstract":[{"text":"Customization options for the Multi-Range Liveness user interface.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/Style-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Style"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewController/style-swift.property":{"abstract":[{"type":"text","text":"Current style."}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontroller\/style-swift.property","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewController\/style-swift.property","role":"symbol","navigatorTitle":[{"text":"style","kind":"identifier"}],"title":"style","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Style","preciseIdentifier":"s:11DotFaceLite32MultiRangeLivenessViewControllerC5StyleC"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMultiRangeLivenessStyle":{"kind":"symbol","title":"DOTFLMultiRangeLivenessStyle","url":"\/documentation\/dotfacelite\/dotflmultirangelivenessstyle","abstract":[{"text":"Customization options for the Multi-Range Liveness user interface.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessStyle","fragments":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessStyle"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"style","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"style","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFLMultiRangeLivenessStyle","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMultiRangeLivenessStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessStyle"},{"text":" * ","kind":"text"},{"text":"style","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/title","value":"DOTFLMultiRangeLivenessViewController","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController\/fragments"},{"value":"style","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1style-swift.property\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}]}]}]}