{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"minSharpness:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"minSharpness"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minSharpness:error:"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder(im)minSharpness:error:","title":"minSharpness:error:","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"minSharpness:error:"}],"symbolKind":"method"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/minsharpness:error:"]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minSharpness:error:"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder/minSharpness:error:":{"role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"minSharpness:error:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/minsharpness:error:","title":"minSharpness:error:","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/minSharpness:error:","navigatorTitle":[{"text":"minSharpness:error:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder":{"role":"symbol","title":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder","fragments":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/WrappedDouble":{"title":"WrappedDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/wrappeddouble","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value for Objective-C support.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedDouble","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}