{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/sizeinterval:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeInterval:error:"}],"symbolKind":"method","title":"sizeInterval:error:","modules":[{"name":"DotPalmCore"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder(im)sizeInterval:error:","navigatorTitle":[{"kind":"identifier","text":"sizeInterval:error:"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"sizeInterval:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"DOTIntervalDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sizeInterval"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder":{"role":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"}],"kind":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder","title":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder/sizeInterval:error:":{"title":"sizeInterval:error:","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/sizeinterval:error:","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"sizeInterval:error:"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/sizeInterval:error:","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sizeInterval:error:"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","title":"IntervalDouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/intervaldouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title","op":"replace","value":"DOTIntervalDouble"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}