{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","interfaceLanguage":"swift"},"metadata":{"title":"init(detection:)","modules":[{"name":"DotDocument"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAeA0ac15DetectionModuleE0C_tcfc"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","title":"init(detection:)","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration":{"type":"topic","url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"title":"DotPalmDetectionModuleConfiguration"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"title":"DotPalmLibraryConfiguration.Modules","url":"\/documentation\/dotdocument\/dotpalmlibraryconfiguration\/modules-swift.class","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}]}]}]}