{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"extendedModule":"Swift","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::s:6DotNfc24DataAuthenticationStatusC0D8ProtocolO","roleHeading":"Instance Method","title":"hash(into:)","conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"relatedModules":["Swift"],"name":"DotNfc"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/hash(into:)","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","url":"\/documentation\/dotnfc\/dataauthenticationstatus","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"type":"topic","title":"DataAuthenticationStatus","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DataAuthenticationStatus"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/hash(into:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/hash(into:)","role":"symbol","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/hash(into:)","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum\/RawRepresentable-Implementations","kind":"article","title":"RawRepresentable Implementations","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum\/rawrepresentable-implementations","abstract":[],"type":"topic","role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/AuthenticationProtocol-swift.enum":{"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/dataauthenticationstatus\/authenticationprotocol-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AuthenticationProtocol"}],"abstract":[{"type":"text","text":"Protocol for authentication of the data."}],"navigatorTitle":[{"kind":"identifier","text":"AuthenticationProtocol"}],"title":"DataAuthenticationStatus.AuthenticationProtocol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/AuthenticationProtocol-swift.enum"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","value":"DOTNDataAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/navigatorTitle","value":[{"text":"DOTNDataAuthenticationStatus","kind":"identifier"}]}]}]}