{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/description","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"property","roleHeading":"Instance Property","title":"description","externalID":"s:11DotFaceLite0B18AutoCaptureUiStateC12InitializingC11descriptionSSvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing":{"url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing","title":"FaceAutoCaptureUiState.Initializing","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"navigatorTitle":[{"kind":"identifier","text":"Initializing"}],"abstract":[{"text":"Initializing state.","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"role":"symbol","title":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureuistate"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState/Initializing/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState\/Initializing\/description","type":"topic","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[],"title":"description","url":"\/documentation\/dotfacelite\/faceautocaptureuistate\/initializing\/description"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","value":"DOTFLFaceAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}]}]}]}