{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/bottomRight"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"bottomRight","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"}],"modules":[{"name":"DotNfc"}],"title":"bottomRight","externalID":"c:@M@DotNfc@objc(cs)DOTCorners(py)bottomRight","roleHeading":"Instance Property"},"variants":[{"paths":["\/documentation\/dotnfc\/corners\/bottomright"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/corners\/bottomright"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners"]]},"abstract":[{"text":"Bottom right corner point.","type":"text"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners/bottomRight":{"url":"\/documentation\/dotnfc\/corners\/bottomright","navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"abstract":[{"text":"Bottom right corner point.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"type":"topic","title":"bottomRight","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/bottomRight","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.1.0","type":"text"}],"title":"DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble":{"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","url":"\/documentation\/dotnfc\/pointdouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"kind":"symbol","title":"PointDouble"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners":{"role":"symbol","kind":"symbol","title":"Corners","abstract":[{"type":"text","text":"Four detected corners in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/corners"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bottomRight","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bottomRight"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"bottomRight"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1bottomRight\/title","value":"bottomRight"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1bottomRight\/fragments","value":[{"text":"bottomRight","kind":"identifier"}]},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/title","op":"replace","value":"DOTCorners"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace"}]}]}