{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"sections":[],"metadata":{"role":"symbol","title":"init(detection:)","modules":[{"name":"DotPalmCore"}],"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAeA0ac15DetectionModuleE0C_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detection","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"init","roleHeading":"Initializer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration":{"role":"symbol","title":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","abstract":[{"type":"text","text":"Palm detection module configuration."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"role":"symbol","title":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","abstract":[{"text":"Palm library configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class":{"role":"symbol","title":"DotPalmLibraryConfiguration.Modules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Palm library module configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class/init(detection:)":{"role":"symbol","title":"init(detection:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/init(detection:)","abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class\/init(detection:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"kind":"text","text":")"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","op":"replace","value":"DotPalmLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]}]}]}