{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/displayedsignatureorusualmarkimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/displayedsignatureorusualmark\/displayedsignatureorusualmarkimage"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"abstract":[{"text":"Image of a signature of document holder.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayedSignatureOrUsualMarkImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"displayedSignatureOrUsualMarkImage"}],"roleHeading":"Instance Property","externalID":"c:@M@DotNfc@objc(cs)DOTNDisplayedSignatureOrUsualMark(py)displayedSignatureOrUsualMarkImage","modules":[{"name":"DotNfc"}],"role":"symbol","title":"displayedSignatureOrUsualMarkImage","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/displayedSignatureOrUsualMarkImage"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/Image":{"type":"topic","role":"symbol","title":"Image","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark":{"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark","navigatorTitle":[{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"title":"DisplayedSignatureOrUsualMark","kind":"symbol","abstract":[{"text":"Contents of DG7 - Displayed signature or usual mark.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DisplayedSignatureOrUsualMark","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark","type":"topic"},"doc://DotNfc/documentation/DotNfc/DisplayedSignatureOrUsualMark/displayedSignatureOrUsualMarkImage":{"navigatorTitle":[{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"}],"url":"\/documentation\/dotnfc\/displayedsignatureorusualmark\/displayedsignatureorusualmarkimage","abstract":[{"text":"Image of a signature of document holder.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DisplayedSignatureOrUsualMark\/displayedSignatureOrUsualMarkImage","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"displayedSignatureOrUsualMarkImage","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic","title":"TravelDocument","abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"displayedSignatureOrUsualMarkImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":" * "},{"kind":"identifier","text":"displayedSignatureOrUsualMarkImage"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/title","value":"DOTNDisplayedSignatureOrUsualMark"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/fragments","value":[{"text":"DOTNDisplayedSignatureOrUsualMark","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNDisplayedSignatureOrUsualMark"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1displayedSignatureOrUsualMarkImage\/title","value":"displayedSignatureOrUsualMarkImage"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DisplayedSignatureOrUsualMark~1displayedSignatureOrUsualMarkImage\/fragments","value":[{"text":"displayedSignatureOrUsualMarkImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}