{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/maxShadow(_:)"},"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC9maxShadowyAE0aC013WrappedDoubleCSgKF","title":"maxShadow(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxShadow"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Builder","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@discardableResult","kind":"attribute"},{"text":" ","kind":"text"},{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxShadow","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"maxShadow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC","kind":"typeIdentifier","text":"Builder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder\/maxshadow(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"title":"WrappedDouble","role":"symbol","url":"\/documentation\/dotfacecore\/wrappeddouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder":{"abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"title":"FaceAutoCaptureQualityAttributeThresholds.Builder","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/Builder/maxShadow(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxShadow","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?) ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","text":"Builder","preciseIdentifier":"s:11DotFaceCore0B37AutoCaptureQualityAttributeThresholdsC7BuilderC"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/Builder\/maxShadow(_:)","kind":"symbol","type":"topic","title":"maxShadow(_:)","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/builder\/maxshadow(_:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"role":"symbol","type":"topic","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle","op":"replace"},{"value":"DOTFFaceAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}