{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"title":"init(rawValue:)","externalID":"s:9DotCamera0B6FacingO8rawValueACSgSi_tcfc","symbolKind":"init"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing"]]},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/camerafacing\/init(rawvalue:)"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/init(rawValue:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing/init(rawValue:)":{"url":"\/documentation\/dotfingerscore\/camerafacing\/init(rawvalue:)","abstract":[],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing\/init(rawValue:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/CameraFacing":{"kind":"symbol","title":"CameraFacing","url":"\/documentation\/dotfingerscore\/camerafacing","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraFacing"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/title","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraFacing\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraFacing"}]}]}]}