{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration\/init"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"sections":[],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration(im)init","modules":[{"name":"DotDocument"}],"symbolKind":"method","title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration":{"title":"DotPalmDetectionModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Palm detection module configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration"},"doc://DotDocument/documentation/DotDocument/DotPalmDetectionModuleConfiguration/init":{"url":"\/documentation\/dotdocument\/dotpalmdetectionmoduleconfiguration\/init","kind":"symbol","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotPalmDetectionModuleConfiguration\/init","abstract":[],"type":"topic","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/title","op":"replace","value":"DotPalmDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotPalmDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]}]}]}