{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSCoding","doc:\/\/DotFingersCore\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFingersCore\/objc(pl)UIAppearanceContainer","doc:\/\/DotFingersCore\/objc(pl)UIContentContainer","doc:\/\/DotFingersCore\/objc(pl)UIFocusEnvironment","doc:\/\/DotFingersCore\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFingersCore\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFingersCore\/objc(pl)UIStateRestoring","doc:\/\/DotFingersCore\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFingersCore\/objc(pl)UITraitEnvironment","doc:\/\/DotFingersCore\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGBaseFingersAutoCaptureViewController) "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"type":"heading","anchor":"overview"},{"inlineContent":[{"type":"text","text":"This component requires the "},{"type":"codeVoice","code":"DotFingersDetection"},{"type":"text","text":" module to be active."}],"type":"paragraph"}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"UI component for capturing fingers images with customizable UI.","type":"text"}],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","modules":[{"name":"DotFingersCore"}],"roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"BaseFingersAutoCaptureViewController","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration"],"generated":true,"title":"Classes"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/baseConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/delegate"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/requestCapture()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/start()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/stop()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillTransition(to:with:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/create(baseConfiguration:)"],"generated":true,"title":"Type Methods"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewWillDisappear(_:)":{"type":"topic","abstract":[],"title":"viewWillDisappear(_:)","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewwilldisappear(_:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillDisappear(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}]},"doc://DotFingersCore/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewController":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureViewController","abstract":[{"type":"text","text":"UI Fingers Auto Capture component."}],"navigatorTitle":[{"text":"FingersAutoCaptureViewController","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontroller"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/baseConfiguration":{"type":"topic","title":"baseConfiguration","abstract":[{"type":"text","text":"Current configuration."}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/baseconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/baseConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"baseConfiguration"}]},"doc://DotFingersCore/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSCoding","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewDidLayoutSubviews()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLayoutSubviews"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidLayoutSubviews"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdidlayoutsubviews()","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLayoutSubviews()","title":"viewDidLayoutSubviews()","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewWillAppear(_:)":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewwillappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillAppear(_:)","title":"viewWillAppear(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewWillAppear:"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/delegate":{"type":"topic","abstract":[{"text":"Set this delegate to handle the fingers auto capture events.","type":"text"}],"title":"delegate","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/delegate","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/delegate","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureViewControllerDelegate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewDidDisappear(_:)":{"type":"topic","abstract":[],"title":"viewDidDisappear(_:)","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdiddisappear(_:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidDisappear(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}]},"doc://DotFingersCore/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/requestCapture()":{"type":"topic","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"title":"requestCapture()","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/requestcapture()","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/requestCapture()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"requestCapture","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"requestCapture","kind":"identifier"}]},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/DotFingersCore\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://DotFingersCore/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIActivityItemsConfigurationProviding","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewWillTransition(to:with:)":{"type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewwilltransition(to:with:)","abstract":[],"title":"viewWillTransition(to:with:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillTransition(to:with:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},"doc://DotFingersCore/objc(pl)NSExtensionRequestHandling":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling","type":"unresolvable"},"doc://DotFingersCore/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIContentContainer","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/start()":{"type":"topic","abstract":[{"type":"text","text":"Start the fingers auto capture process."}],"title":"start()","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/start()","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/start()","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"start","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"start","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewDidLoad()":{"type":"topic","abstract":[],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdidload()","title":"viewDidLoad()","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLoad()","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidLoad","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"viewDidLoad","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/create(baseConfiguration:)":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"createWithBaseConfiguration:"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/create(baseconfiguration:)","abstract":[{"text":"Create new ","type":"text"},{"type":"codeVoice","code":"BaseFingersAutoCaptureViewController"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/create(baseConfiguration:)","title":"create(baseConfiguration:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/5UIKit23UITraitChangeObservableP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/5UIKit23UITraitChangeObservableP","title":"UIKit.UITraitChangeObservable"},"doc://DotFingersCore/objc(cs)UIViewController":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)UIViewController","title":"UIViewController","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController","type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"kind":"symbol","abstract":[{"text":"UI component for capturing fingers images with customizable UI.","type":"text"}],"title":"BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)UIResponderStandardEditActions","title":"UIKit.UIResponderStandardEditActions","type":"unresolvable"},"doc://DotFingersCore/objc(pl)UIStateRestoring":{"title":"UIKit.UIStateRestoring","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIStateRestoring","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/DotFingersCore\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewDidAppear(_:)":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdidappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidAppear(_:)","title":"viewDidAppear(_:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"viewDidAppear:"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/stop()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stop"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/stop()","type":"topic","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/stop()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"stop"}],"kind":"symbol","abstract":[{"type":"text","text":"Stop the fingers auto capture process."}],"title":"stop()"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/baseConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/delegate"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/requestCapture()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/start()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/stop()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/create(baseConfiguration:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)UIViewController"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewController"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGBaseFingersAutoCaptureViewController","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","op":"replace"},{"op":"replace","value":"DOTFGFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"baseConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1baseConfiguration\/title","op":"replace"},{"value":[{"text":"baseConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1baseConfiguration\/fragments","op":"replace"},{"value":"viewDidLayoutSubviews","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidLayoutSubviews()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments","op":"replace"},{"value":"viewWillAppear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillAppear(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillAppear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillAppear(_:)\/fragments","op":"replace"},{"value":"delegate","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1delegate\/title","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1delegate\/fragments","op":"replace"},{"value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidDisappear(_:)\/fragments","op":"replace"},{"value":"requestCapture","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1requestCapture()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1requestCapture()\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillTransition(to:with:)\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"value":"start","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1start()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"start"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1start()\/fragments","op":"replace"},{"value":"viewDidLoad","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidLoad()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidLoad"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidLoad()\/fragments","op":"replace"},{"value":"createWithBaseConfiguration:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1create(baseConfiguration:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBaseConfiguration:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1create(baseConfiguration:)\/fragments"},{"op":"replace","value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1stop()\/title","value":"stop"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1stop()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stop"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}