{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fill","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fit"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/native"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"CameraPreviewScaleType","externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"roleHeading":"Enumeration","symbolKind":"enum"},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCameraPreviewScaleType) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/camerapreviewscaletype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/camerapreviewscaletype"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/description"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/rawrepresentable-implementations"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType":{"url":"\/documentation\/dotfingerscore\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraPreviewScaleType","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType","title":"CameraPreviewScaleType","role":"symbol","abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/fill":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/fill","abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fill","title":"CameraPreviewScaleType.fill","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/fit":{"url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/fit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fit","title":"CameraPreviewScaleType.fit","role":"symbol","abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"text":" ","type":"text"},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/native":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/native","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVLayerVideoGravity","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity"}],"kind":"symbol","role":"symbol","title":"native","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/native"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/Equatable-Implementations":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/equatable-implementations"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CameraPreviewScaleType/init(rawValue:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/camerapreviewscaletype\/init(rawvalue:)"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fill","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CameraPreviewScaleType\/fit"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCameraPreviewScaleType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType\/navigatorTitle","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}]},{"value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fill\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fill\/fragments","op":"replace"},{"value":"DOTCameraPreviewScaleTypeFit","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CameraPreviewScaleType~1fit\/fragments","op":"replace"}]}]}