{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration"]}],"abstract":[{"text":"Document library configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfiguration","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"title":"DotDocumentLibraryConfiguration","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Classes","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"],"title":"Classes"},{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/init(modules:)"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration","title":"DotDocumentLibraryConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","title":"DotDocumentLibraryConfiguration.Modules","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/modules-swift.property":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/modules-swift.property","abstract":[{"type":"text","text":"Module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/modules-swift.property","title":"modules","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfiguration/init(modules:)":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfiguration\/init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/init(modules:)","title":"init(modules:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/modules-swift.property"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfiguration\/init(modules:)"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/title","value":"DotDocumentLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration~1modules-swift.property\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration~1modules-swift.property\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentLibraryConfiguration~1init(modules:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}]}]}]}