{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"metadata":{"symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"}],"title":"DotFingersModuleId","externalID":"c:@M@DotCore@E@DotFingersModuleId","modules":[{"name":"DotFingersCore"}],"roleHeading":"Enumeration","role":"symbol","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/detection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/transformation"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmoduleid"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/transformation":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/transformation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId.transformation","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/transformation"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/detection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/detection","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId.detection","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/detection"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/init(rawValue:)":{"url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/RawRepresentable-Implementations":{"type":"topic","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/Equatable-Implementations":{"type":"topic","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/equatable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/Equatable-Implementations","kind":"article","role":"collectionGroup"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFingersModuleId","abstract":[{"type":"codeVoice","code":"DotFingers"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmoduleid"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModuleId/description":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfingerscore\/dotfingersmoduleid\/description","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/description","title":"description","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFingersModuleId","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/detection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModuleId\/transformation"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModuleId"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFingersModuleIdTransformation","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1transformation\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdTransformation"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1transformation\/fragments"},{"op":"replace","value":"DotFingersModuleIdDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1detection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId~1detection\/fragments"},{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModuleId\/navigatorTitle"}]}]}