{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden","interfaceLanguage":"occ"},"topicSections":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/hash"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/init","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/isEqual:"],"title":"Instance Methods"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"DOTFGPlaceholderHidden"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholderHidden","title":"DOTFGPlaceholderHidden","navigatorTitle":[{"kind":"identifier","text":"DOTFGPlaceholderHidden"}],"roleHeading":"Class","symbolKind":"class"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder"],"title":"Inherits From"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGPlaceholderHidden"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder","kind":"typeIdentifier","text":"DOTFGPlaceholder","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder"}],"languages":["occ"]}]}],"abstract":[{"type":"text","text":"Hidden placeholder."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgplaceholderhidden"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/description","fragments":[{"text":"description","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden\/description"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden","fragments":[{"text":"DOTFGPlaceholderHidden","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DOTFGPlaceholderHidden","abstract":[{"type":"text","text":"Hidden placeholder."}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/placeholder"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden/isEqual:":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"isEqual:","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden\/isequal:"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden/init":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"init","abstract":[],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden\/init"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden/hash":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden\/hash","fragments":[{"text":"hash","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"hash","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden\/hash"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGPlaceholder","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle","op":"replace"}]}]}