{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule\/moduleId"],"anchor":"Instance-Properties","title":"Instance Properties"}],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModule","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(pl)DotFingersModule","title":"DotFingersModule","navigatorTitle":[{"kind":"identifier","text":"DotFingersModule"}],"roleHeading":"Protocol","symbolKind":"protocol"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModule","kind":"identifier"}],"languages":["swift"]}]}],"abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmodule"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfingersmodule"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModule":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModule"}],"kind":"symbol","role":"symbol","title":"DotFingersModule","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersModule"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmodule"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersModule/moduleId":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule\/moduleId","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"moduleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersModuleId","preciseIdentifier":"c:@M@DotCore@E@DotFingersModuleId"}],"kind":"symbol","role":"symbol","title":"moduleId","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"moduleId"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingersmodule\/moduleid"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFingersModule","path":"\/metadata\/title","op":"replace"},{"value":"protocol","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotFingersModule","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DotFingersModule","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersModule\/moduleId"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersModule"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFingersModule","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/title","op":"replace"},{"value":[{"text":"DotFingersModule","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/fragments","op":"replace"},{"value":[{"text":"DotFingersModule","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule\/navigatorTitle","op":"replace"},{"value":"moduleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule~1moduleId\/title","op":"replace"},{"value":[{"text":"moduleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersModule~1moduleId\/fragments","op":"replace"}]}]}