{"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"DotFaceModuleId","externalID":"c:@M@DotCore@E@DotFaceModuleId","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"roleHeading":"Enumeration","symbolKind":"enum"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId"},"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/verification"],"generated":true,"title":"Enumeration Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/description"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/detectionBalanced":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/detectionbalanced","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionBalanced","title":"DotFaceModuleId.detectionBalanced","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId":{"url":"\/documentation\/dotfingerscore\/dotfacemoduleid","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId","title":"DotFaceModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/backgroundUniformity":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/backgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"kind":"symbol","role":"symbol","title":"DotFaceModuleId.backgroundUniformity","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/backgrounduniformity"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/expressionNeutral":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/expressionNeutral","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}],"kind":"symbol","role":"symbol","title":"DotFaceModuleId.expressionNeutral","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/expressionneutral"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/eyeGazeLiveness":{"type":"topic","title":"DotFaceModuleId.eyeGazeLiveness","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/eyegazeliveness","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/eyeGazeLiveness","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFingersCore\/SY"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/init(rawValue:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/init(rawvalue:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/detectionFast":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionFast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}],"kind":"symbol","role":"symbol","title":"DotFaceModuleId.detectionFast","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/detectionfast"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/verification":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/verification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"kind":"symbol","role":"symbol","title":"DotFaceModuleId.verification","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/verification"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/passiveLiveness":{"title":"DotFaceModuleId.passiveLiveness","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/passiveLiveness","abstract":[],"role":"symbol","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/passiveliveness","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"passiveLiveness","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/RawRepresentable-Implementations","kind":"article","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/rawrepresentable-implementations"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/description"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceModuleId/Equatable-Implementations":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/Equatable-Implementations","kind":"article","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacemoduleid\/equatable-implementations"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotFaceModuleId","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceModuleId\/verification"],"generated":true}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1detectionBalanced\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1detectionBalanced\/fragments","op":"replace"},{"value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/title","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/fragments","op":"replace"},{"value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId\/navigatorTitle","op":"replace"},{"value":"DotFaceModuleIdBackgroundUniformity","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1backgroundUniformity\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1backgroundUniformity\/fragments","op":"replace"},{"value":"DotFaceModuleIdExpressionNeutral","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1expressionNeutral\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1expressionNeutral\/fragments","op":"replace"},{"value":"DotFaceModuleIdEyeGazeLiveness","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1eyeGazeLiveness\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1eyeGazeLiveness\/fragments","op":"replace"},{"value":"DotFaceModuleIdDetectionFast","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1detectionFast\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1detectionFast\/fragments","op":"replace"},{"value":"DotFaceModuleIdVerification","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1verification\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1verification\/fragments","op":"replace"},{"value":"DotFaceModuleIdPassiveLiveness","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1passiveLiveness\/title","op":"replace"},{"value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceModuleId~1passiveLiveness\/fragments","op":"replace"}]}]}