{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingerToFingerprintTransformer) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"This component requires the ","type":"text"},{"type":"codeVoice","code":"DotFingersTransformation"},{"text":" module to be active.","type":"text"}],"type":"paragraph"}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"],"title":"Non-UI components","anchor":"Non-UI-components","generated":true}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer"]},{"paths":["\/documentation\/dotfingerscore\/fingertofingerprinttransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Stateless class which transforms detected finger images into fingerprint images."}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerToFingerprintTransformer","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"title":"FingerToFingerprintTransformer","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"FingerToFingerprintTransformer","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","topicSections":[{"title":"Transformation input","anchor":"Transformation-input","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"]},{"anchor":"Transformation-output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"],"title":"Transformation output"},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/init()"]},{"generated":true,"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundle:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundles:)"]},{"generated":true,"title":"Enumerations","anchor":"Enumerations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error"]}],"references":{"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/init()":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"title":"init()","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/init()","role":"symbol","abstract":[{"type":"text","text":"Create the finger to fingerprint transformer."}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","kind":"symbol","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"title":"FingerprintImages","type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerprintImages","kind":"identifier"}],"navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/transform(fingerBundle:)":{"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundle:)","abstract":[{"type":"text","text":"Transform a single finger image into a fingerprint image."}],"title":"transform(fingerBundle:)","type":"topic","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundle:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"transform"},{"kind":"text","text":"("},{"text":"fingerBundle","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"navigatorTitle":[{"text":"transformWithFingerBundle:error:","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"url":"\/documentation\/dotfingerscore\/fingerbundles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles","title":"FingerBundles","role":"symbol","abstract":[{"text":"Bundles of finger images with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect fingers in an image.","type":"text"}],"title":"FingerDetector","type":"topic","url":"\/documentation\/dotfingerscore\/fingerdetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerDetector"}],"navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}]},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"url":"\/documentation\/dotfingerscore\/fingerbundle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundle"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","title":"FingerBundle","role":"symbol","abstract":[{"text":"Bundle of a finger image with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundle"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/transform(fingerBundles:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transform","kind":"identifier"},{"kind":"text","text":"("},{"text":"fingerBundles","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerBundles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"FingerprintImages","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages"}],"navigatorTitle":[{"text":"transformWithFingerBundles:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/transform(fingerbundles:)","abstract":[{"text":"Transform four finger images into fingerprint images.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundles:)","title":"transform(fingerBundles:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer/Error":{"url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer\/error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/Error","title":"FingerToFingerprintTransformer.Error","role":"symbol","abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"kind":"symbol","role":"symbol","title":"FingerToFingerprintTransformer","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGFingerToFingerprintTransformer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"anchor":"Transformation-input","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"],"title":"Transformation input"},{"anchor":"Transformation-output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages"],"title":"Transformation output"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundle:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer\/transform(fingerBundles:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"],"title":"Non-UI components","anchor":"Non-UI-components","generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFGFingerToFingerprintTransformer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1init()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1init()\/fragments","op":"replace"},{"op":"replace","value":"DOTFGFingerprintImages","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerprintImages"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle","op":"replace"},{"value":"transformWithFingerBundle:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundle:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"transformWithFingerBundle:error:","kind":"identifier"}]},{"value":"DOTFGFingerBundles","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments","value":[{"text":"DOTFGFingerBundles","kind":"identifier"}]},{"value":[{"text":"DOTFGFingerBundles","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerDetector","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerDetector"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerDetector"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle"},{"op":"replace","value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerBundle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle"},{"op":"replace","value":"transformWithFingerBundles:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundles:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"transformWithFingerBundles:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer~1transform(fingerBundles:)\/fragments"},{"op":"replace","value":"DOTFGFingerToFingerprintTransformer","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title"},{"op":"replace","value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments"},{"op":"replace","value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle"}]}]}