{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/identifier"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/validate(fingersAutoCaptureFrameParameters:)"],"generated":true,"title":"Instance Methods"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureFrameParametersValidator","navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"roleHeading":"Protocol","symbolKind":"protocol"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"seeAlsoSections":[{"anchor":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"generated":true,"title":"Validators"}],"abstract":[{"text":"Use this protocol to create fingers validators.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingersAutoCaptureFrameParametersValidator) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"navigatorTitle":[{"text":"FingerCountTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","title":"FingerCountTooLowValidator","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","title":"SizeTooSmallValidator","role":"symbol","abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator/identifier":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","role":"symbol","title":"identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/identifier"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator/dependencyIdentifiers":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/dependencyIdentifiers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"kind":"symbol","role":"symbol","title":"dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/dependencyidentifiers"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}],"navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator/validate(fingersAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/validate(fingersAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","text":"FingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","title":"validate(fingersAutoCaptureFrameParameters:)","abstract":[{"text":"Validate current frame parameters.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"required":true,"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator\/validate(fingersautocaptureframeparameters:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountNotFourValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountNotFourValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingerCountNotFourValidator","abstract":[{"text":"Validate whether the count of detected fingers is four.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerCountNotFourValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercountnotfourvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol","role":"symbol","title":"SharpnessTooLowValidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"kind":"symbol","role":"symbol","title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FingersNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","title":"FingersNotDetectedValidator","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/identifier"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator\/validate(fingersAutoCaptureFrameParameters:)"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator"],"type":"conformingTypes"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Validators","title":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","value":"DOTFGFingerCountTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","value":"DOTFGSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","value":"DOTFGFingersAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","value":"validateWithFingersAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/title","value":"DOTFGFingerCountNotFourValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerCountNotFourValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerCountNotFourValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","value":"DOTFGFingersOutOfBoundsValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","value":"DOTFGSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","value":"DOTFGSizeTooLargeValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","value":"DOTFGFingersNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}