{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/init(index:middle:ring:little:)"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/ring"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/isEqual(_:)"],"generated":true,"title":"Instance Methods"}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Fingers"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingers","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFingersCore"}],"title":"Fingers","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Fingers","kind":"identifier"}]},"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingers) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Detected fingers.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingers"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/Fingers/isEqual(_:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingers\/isequal(_:)"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/little":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/little","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"little"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"little","abstract":[{"text":"Little finger detection result, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" if the finger was not detected in the image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"little"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingers\/little"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"navigatorTitle":[{"kind":"identifier","text":"Fingers"}],"url":"\/documentation\/dotfingerscore\/fingers","abstract":[{"text":"Detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers","title":"Fingers","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/index":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"index"}],"url":"\/documentation\/dotfingerscore\/fingers\/index","abstract":[{"text":"Index finger detection result, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/index","title":"index","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfingerscore\/fingers\/hash","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/hash","title":"hash","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/middle":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"middle"}],"url":"\/documentation\/dotfingerscore\/fingers\/middle","abstract":[{"text":"Middle finger detection result, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/middle","title":"middle","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/init(index:middle:ring:little:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"middle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"ring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"little"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithIndex:middle:ring:little:"}],"url":"\/documentation\/dotfingerscore\/fingers\/init(index:middle:ring:little:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/init(index:middle:ring:little:)","title":"init(index:middle:ring:little:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/ring":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"ring"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"ring"}],"url":"\/documentation\/dotfingerscore\/fingers\/ring","abstract":[{"text":"Ring finger detection result, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/ring","title":"ring","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/Fingers/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingers\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGFingers","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingers"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingers"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/ring"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/init(index:middle:ring:little:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers\/isEqual(_:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingers"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1isEqual(_:)\/fragments"},{"op":"replace","value":"little","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1little\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1little\/fragments","value":[{"text":"little","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/title","value":"DOTFGFingers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/fragments","value":[{"text":"DOTFGFingers","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingers"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/navigatorTitle"},{"op":"replace","value":"index","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1index\/title"},{"value":[{"text":"index","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1index\/fragments","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1hash\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1hash\/fragments"},{"value":"middle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1middle\/title","op":"replace"},{"value":[{"text":"middle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1middle\/fragments","op":"replace"},{"value":"initWithIndex:middle:ring:little:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1init(index:middle:ring:little:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithIndex:middle:ring:little:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1init(index:middle:ring:little:)\/fragments","op":"replace"},{"value":"ring","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1ring\/title","op":"replace"},{"value":[{"text":"ring","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1ring\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers~1description\/fragments","op":"replace"}]}]}