{"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingerImageQuality) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerImageQuality","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerimagequality"]},{"paths":["\/documentation\/dotfingerscore\/fingerimagequality"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Image quality attributes for finger detection.","type":"text"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerImageQuality","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerImageQuality"}],"title":"FingerImageQuality","role":"symbol","roleHeading":"Class","navigatorTitle":[{"text":"FingerImageQuality","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/init(sharpness:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/sharpness"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/isEqual(_:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality/sharpness":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sharpness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sharpness","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerimagequality\/sharpness","abstract":[{"type":"text","text":"Image sharpness in range [0, 1.0]. Where 0 means blurry and 1.0 means sharp."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/sharpness","title":"sharpness","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality/hash":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"hash","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerimagequality\/hash"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfingerscore\/fingerimagequality\/description","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/description","title":"description","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality/init(sharpness:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithSharpness:"}],"url":"\/documentation\/dotfingerscore\/fingerimagequality\/init(sharpness:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/init(sharpness:)","title":"init(sharpness:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality/isEqual(_:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerimagequality\/isequal(_:)"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingerImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerImageQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FingerImageQuality"}],"url":"\/documentation\/dotfingerscore\/fingerimagequality","abstract":[{"type":"text","text":"Image quality attributes for finger detection."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality","title":"FingerImageQuality","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGFingerImageQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFGFingerImageQuality","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFGFingerImageQuality","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/sharpness"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/init(sharpness:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerImageQuality\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingerImageQuality"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1sharpness\/title","value":"sharpness"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1sharpness\/fragments","value":[{"text":"sharpness","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1init(sharpness:)\/title","value":"initWithSharpness:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1init(sharpness:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSharpness:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/title","value":"DOTFGFingerImageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/fragments","value":[{"text":"DOTFGFingerImageQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerImageQuality\/navigatorTitle","value":[{"text":"DOTFGFingerImageQuality","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}