{"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingerprintImages) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerprintImages"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"metadata":{"symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerprintImages"}],"title":"FingerprintImages","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerprintImages","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/init(index:middle:ring:little:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/ring"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/isEqual(_:)"],"title":"Instance Methods","generated":true}],"seeAlsoSections":[{"anchor":"Transformation-output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"],"title":"Transformation output","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerprintimages"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerprintimages"]}],"references":{"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/index":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/index","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"index","abstract":[{"text":"Image of the index finger, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not provided.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"index"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/index"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages","kind":"symbol","abstract":[{"text":"Fingerprint images of four fingers.","type":"text"}],"title":"FingerprintImages","type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerprintImages","kind":"identifier"}],"navigatorTitle":[{"text":"FingerprintImages","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/little":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"little"}],"url":"\/documentation\/dotfingerscore\/fingerprintimages\/little","abstract":[{"type":"text","text":"Image of the little finger, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the finger was not provided."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/little","title":"little","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/init(index:middle:ring:little:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/init(index:middle:ring:little:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"index"},{"kind":"text","text":": "},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?, ","kind":"text"},{"text":"middle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"ring","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"little","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(index:middle:ring:little:)","abstract":[],"navigatorTitle":[{"text":"initWithIndex:middle:ring:little:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/init(index:middle:ring:little:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/isEqual(_:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","role":"symbol","title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/isequal(_:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/middle":{"url":"\/documentation\/dotfingerscore\/fingerprintimages\/middle","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/middle","title":"middle","role":"symbol","abstract":[{"type":"text","text":"Image of the middle finger, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the finger was not provided."}],"navigatorTitle":[{"kind":"identifier","text":"middle"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/description":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/description"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/hash":{"url":"\/documentation\/dotfingerscore\/fingerprintimages\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"hash","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/hash","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerprintImages/ring":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/ring","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"ring","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"ring","abstract":[{"text":"Image of the ring finger, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the finger was not provided."}],"navigatorTitle":[{"kind":"identifier","text":"ring"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerprintimages\/ring"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGFingerprintImages"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/index","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/little","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/middle","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/ring"],"title":"Instance Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/init(index:middle:ring:little:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerprintImages\/isEqual(_:)"],"title":"Instance Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Transformation-output","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"],"title":"Transformation output","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingerprintImages","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1index\/title","value":"index"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1index\/fragments","value":[{"text":"index","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/title","value":"DOTFGFingerprintImages"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/fragments","value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages\/navigatorTitle","value":[{"text":"DOTFGFingerprintImages","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1little\/title","value":"little"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1little\/fragments","value":[{"text":"little","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1init(index:middle:ring:little:)\/title","value":"initWithIndex:middle:ring:little:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1init(index:middle:ring:little:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithIndex:middle:ring:little:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1middle\/title","value":"middle"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1middle\/fragments","value":[{"text":"middle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1ring\/title","value":"ring"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerprintImages~1ring\/fragments","value":[{"text":"ring","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}