{"metadata":{"navigatorTitle":[{"text":"FingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(pl)DOTFGFingersAutoCaptureViewControllerDelegate","symbolKind":"protocol","roleHeading":"Protocol","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"FingersAutoCaptureViewControllerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:finished:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillTransition(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingersAutoCaptureViewControllerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"Implement this delegate to handle the fingers auto capture events.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewWillDisappear(_:)":{"type":"topic","abstract":[],"title":"fingersAutoCaptureViewControllerViewWillDisappear(_:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwilldisappear(_:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillDisappear(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"fingersAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewController(_:finished:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureResult","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewController:finished:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontroller(_:finished:)","abstract":[{"text":"Tells the delegate that the fingers auto capture component has finished with a result. This callback is called after the component has stopped.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:finished:)","required":true,"title":"fingersAutoCaptureViewController(_:finished:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidLayoutSubviews:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewdidlayoutsubviews(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)","title":"fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewDidDisappear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidDisappear:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewdiddisappear(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidDisappear(_:)","title":"fingersAutoCaptureViewControllerViewDidDisappear(_:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewWillTransition(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"fingersAutoCaptureViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillTransition:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwilltransition(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillTransition(_:)","title":"fingersAutoCaptureViewControllerViewWillTransition(_:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewDidLoad(_:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLoad(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidLoad"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"fingersAutoCaptureViewControllerViewDidLoad(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidLoad:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewdidload(_:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerNoCameraPermission(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BaseFingersAutoCaptureViewController","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollernocamerapermission(_:)","abstract":[{"text":"Tells the delegate that you have no permission for camera usage.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerNoCameraPermission(_:)","title":"fingersAutoCaptureViewControllerNoCameraPermission(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureViewControllerDelegate"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the fingers auto capture events."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate","title":"FingersAutoCaptureViewControllerDelegate","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewDidAppear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidAppear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController","text":"BaseFingersAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidAppear:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewdidappear(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidAppear(_:)","title":"fingersAutoCaptureViewControllerViewDidAppear(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewControllerViewWillAppear(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillAppear"},{"kind":"text","text":"("},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"fingersAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontrollerviewwillappear(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillAppear(_:)","title":"fingersAutoCaptureViewControllerViewWillAppear(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureViewControllerDelegate/fingersAutoCaptureViewController(_:uiStateUpdated:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:uiStateUpdated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fingersAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFingersAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiState"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"fingersAutoCaptureViewController(_:uiStateUpdated:)","abstract":[{"text":"Tells the delegate that the UI state was updated.","type":"text"}],"navigatorTitle":[{"text":"fingersAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureviewcontrollerdelegate\/fingersautocaptureviewcontroller(_:uistateupdated:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGFingersAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:finished:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewController(_:uiStateUpdated:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerNoCameraPermission(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewDidLoad(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillAppear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillDisappear(_:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureViewControllerDelegate\/fingersAutoCaptureViewControllerViewWillTransition(_:)"],"title":"Instance Methods"}]},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillDisappear(_:)\/title","value":"fingersAutoCaptureViewControllerViewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:finished:)\/title","value":"fingersAutoCaptureViewController:finished:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:finished:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewController:finished:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/title","value":"fingersAutoCaptureViewControllerViewDidLayoutSubviews:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidLayoutSubviews(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewDidLayoutSubviews:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidDisappear(_:)\/title","value":"fingersAutoCaptureViewControllerViewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidDisappear:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillTransition(_:)\/title","value":"fingersAutoCaptureViewControllerViewWillTransition:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillTransition(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewWillTransition:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidLoad(_:)\/title","value":"fingersAutoCaptureViewControllerViewDidLoad:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidLoad(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"fingersAutoCaptureViewControllerViewDidLoad:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerNoCameraPermission(_:)\/title","value":"fingersAutoCaptureViewControllerNoCameraPermission:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerNoCameraPermission(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"fingersAutoCaptureViewControllerNoCameraPermission:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/title","value":"DOTFGFingersAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFGFingersAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureViewControllerDelegate"}]},{"value":"fingersAutoCaptureViewControllerViewDidAppear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidAppear(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewDidAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewDidAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillAppear(_:)\/title","value":"fingersAutoCaptureViewControllerViewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewControllerViewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewControllerViewWillAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:uiStateUpdated:)\/title","value":"fingersAutoCaptureViewController:uiStateUpdated:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureViewControllerDelegate~1fingersAutoCaptureViewController(_:uiStateUpdated:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"fingersAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}