{"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/s12CaseIterableP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGFingersAutoCapturePhase) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"seeAlsoSections":[{"generated":true,"anchor":"Fingers-auto-capture-process","title":"Fingers auto capture process","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocapturephase"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCapturePhase","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@E@DOTFGFingersAutoCapturePhase","title":"FingersAutoCapturePhase","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"roleHeading":"Enumeration","symbolKind":"enum"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped"]},{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/candidateSelection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/preCandidateSelection"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/RawRepresentable-Implementations"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","title":"FingersAutoCapturePhase","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","title":"FingersAutoCaptureController.Sample","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/preCandidateSelection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/preCandidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCapturePhase.preCandidateSelection","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"navigatorTitle":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/precandidateselection"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/description":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/description","title":"description","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected fingers."}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"code":".captureDepth","type":"codeVoice"},{"text":" event during the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","title":"FingersAutoCaptureController.PhotoSample","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/s12CaseIterableP":{"title":"Swift.CaseIterable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s12CaseIterableP"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/Wrapped":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Wrapped","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"kind":"symbol","role":"symbol","title":"FingersAutoCapturePhase.Wrapped","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/wrapped"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/init(rawValue:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(rawValue:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/init(rawvalue:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/Equatable-Implementations":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/equatable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","title":"FingersAutoCaptureResult","role":"symbol","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DetectionPosition","abstract":[{"text":"Position of the finger in the image.","type":"text"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/detectionposition"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent","title":"FingersAutoCaptureEvent","role":"symbol","abstract":[{"text":"An event emitted during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","title":"FingersAutoCaptureController.ProcessingResult","role":"symbol","abstract":[{"text":"The result returned from the processing of one image during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/candidateSelection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/candidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersAutoCapturePhase.candidateSelection","abstract":[{"type":"text","text":"Candidate selection is running."}],"navigatorTitle":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhaseCandidateSelection"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/candidateselection"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase/RawRepresentable-Implementations":{"url":"\/documentation\/dotfingerscore\/fingersautocapturephase\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/RawRepresentable-Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"DOTFGFingersAutoCapturePhase","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePhase"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/candidateSelection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase\/preCandidateSelection"],"anchor":"Enumeration-Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"],"title":"Fingers auto capture process","generated":true,"anchor":"Fingers-auto-capture-process"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","value":"DOTFGFingersAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","value":"DOTFGFingersAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1preCandidateSelection\/title","value":"DOTFGFingersAutoCapturePhasePreCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1preCandidateSelection\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhasePreCandidateSelection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","value":"DOTFGDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/title","value":"DOTFGFingersAutoCaptureEvent"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/fragments","value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1candidateSelection\/title","value":"DOTFGFingersAutoCapturePhaseCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase~1candidateSelection\/fragments","value":[{"text":"DOTFGFingersAutoCapturePhaseCandidateSelection","kind":"identifier"}]}]}]}