{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/init(image:pixelsPerInch:finger:)"],"generated":true,"title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/pixelsPerInch"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/isEqual(_:)"],"generated":true,"title":"Instance Methods"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundle"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"FingerBundle","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","navigatorTitle":[{"kind":"identifier","text":"FingerBundle"}],"roleHeading":"Class","symbolKind":"class"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"anchor":"Transformation-input","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"],"generated":true,"title":"Transformation input"}],"abstract":[{"text":"Bundle of a finger image with detection data.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGFingerBundle) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundle"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerbundle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerbundle"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"url":"\/documentation\/dotfingerscore\/fingerbundle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundle"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","title":"FingerBundle","role":"symbol","abstract":[{"text":"Bundle of a finger image with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundle"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/init(image:pixelsPerInch:finger:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"pixelsPerInch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"finger","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FingerDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"text":".","kind":"text"},{"text":"Finger","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithImage:pixelsPerInch:finger:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle\/init(image:pixelsperinch:finger:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/init(image:pixelsPerInch:finger:)","title":"init(image:pixelsPerInch:finger:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"url":"\/documentation\/dotfingerscore\/fingerbundles","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles","title":"FingerBundles","role":"symbol","abstract":[{"text":"Bundles of finger images with detection data.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/hash":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"hash","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingerbundle\/hash"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/image":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"}],"navigatorTitle":[{"kind":"identifier","text":"image"}],"url":"\/documentation\/dotfingerscore\/fingerbundle\/image","abstract":[{"text":"Image.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/image","title":"image","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/pixelsPerInch":{"type":"topic","url":"\/documentation\/dotfingerscore\/fingerbundle\/pixelsperinch","abstract":[{"type":"text","text":"Pixels per inch in the region of the image where the finger was detected."}],"title":"pixelsPerInch","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/pixelsPerInch","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"pixelsPerInch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"pixelsPerInch"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/finger":{"url":"\/documentation\/dotfingerscore\/fingerbundle\/finger","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"finger"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerDetector","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Finger","preciseIdentifier":"s:14DotFingersCore14FingerDetectorC0D0C"}],"title":"finger","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/finger","role":"symbol","abstract":[{"text":"The result of the finger detection.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"finger"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfingerscore\/fingerbundle\/description","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/description","title":"description","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGFingerBundle","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/finger","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/image","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/pixelsPerInch"],"generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/init(image:pixelsPerInch:finger:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle\/isEqual(_:)"],"generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","value":[{"anchor":"Transformation-input","title":"Transformation input","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"],"generated":true}],"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingerBundle"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFGFingerBundle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title","op":"replace"},{"value":[{"text":"DOTFGFingerBundle","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1isEqual(_:)\/fragments","op":"replace"},{"value":"initWithImage:pixelsPerInch:finger:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1init(image:pixelsPerInch:finger:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:pixelsPerInch:finger:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1init(image:pixelsPerInch:finger:)\/fragments","op":"replace"},{"value":"DOTFGFingerBundles","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1hash\/fragments","op":"replace"},{"value":"image","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1image\/title","op":"replace"},{"value":[{"kind":"identifier","text":"image"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1image\/fragments","op":"replace"},{"value":"pixelsPerInch","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1pixelsPerInch\/title","op":"replace"},{"value":[{"kind":"identifier","text":"pixelsPerInch"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1pixelsPerInch\/fragments","op":"replace"},{"value":"finger","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1finger\/title","op":"replace"},{"value":[{"kind":"identifier","text":"finger"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1finger\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle~1description\/fragments","op":"replace"}]}]}