{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController"},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class"],"anchor":"Configuration","title":"Configuration"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"],"anchor":"Fingers-auto-capture-process","title":"Fingers auto capture process"},{"anchor":"Validators","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"title":"Validators"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/init(configuration:)"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/configuration-swift.property"],"generated":true,"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/captured(sample:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/process(sample:)"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error"],"anchor":"Enumerations","title":"Enumerations"}],"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureController","title":"FingersAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"roleHeading":"Class","symbolKind":"class"},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer"],"anchor":"Non-UI-components","title":"Non-UI components"}],"abstract":[{"text":"Non-UI component for the fingers auto capture process.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFGFingersAutoCaptureController) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureController"}]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"This component requires the ","type":"text"},{"type":"codeVoice","code":"DotFingersDetection"},{"text":" module to be active.","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturecontroller"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/captured(sample:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/captured(sample:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"captured"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PhotoSample","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC11PhotoSampleC"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","role":"symbol","title":"captured(sample:)","abstract":[{"text":"Process a captured photo sample with depth in response to a ","type":"text"},{"type":"codeVoice","code":".captureDepth"},{"text":" event and update the state.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"capturedWithSample:error:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/captured(sample:)"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"navigatorTitle":[{"text":"FingerCountTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","title":"FingerCountTooLowValidator","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Error":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Error","title":"FingersAutoCaptureController.Error","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected fingers."}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"kind":"symbol","role":"symbol","title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountNotFourValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountNotFourValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingerCountNotFourValidator","abstract":[{"text":"Validate whether the count of detected fingers is four.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerCountNotFourValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercountnotfourvalidator"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/init(configuration:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/init(configuration:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol","title":"init(configuration:)","abstract":[{"text":"Create new instance of ","type":"text"},{"type":"codeVoice","code":"FingersAutoCaptureController"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/init(configuration:)"},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DetectionPosition","abstract":[{"text":"Position of the finger in the image.","type":"text"}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/detectionposition"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Configuration-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureController.Configuration","abstract":[{"text":"Configuration of the fingers auto capture non-UI component.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/PhotoSample":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PhotoSample"}],"navigatorTitle":[{"kind":"identifier","text":"PhotoSample"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/photosample","abstract":[{"type":"text","text":"The photo-capture sample, supplied in response to a "},{"code":".captureDepth","type":"codeVoice"},{"text":" event during the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/PhotoSample","title":"FingersAutoCaptureController.PhotoSample","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/processingresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProcessingResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/ProcessingResult","title":"FingersAutoCaptureController.ProcessingResult","role":"symbol","abstract":[{"text":"The result returned from the processing of one image during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol","role":"symbol","title":"SharpnessTooLowValidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","kind":"symbol","abstract":[{"text":"Stateless class which can detect fingers in an image.","type":"text"}],"title":"FingerDetector","type":"topic","url":"\/documentation\/dotfingerscore\/fingerdetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerDetector"}],"navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}]},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","title":"SizeTooSmallValidator","role":"symbol","abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/Sample":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"navigatorTitle":[{"text":"Sample","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/sample","abstract":[{"text":"The data sample captured at specific time which serves as an input for the fingers auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/Sample","title":"FingersAutoCaptureController.Sample","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","title":"FingersAutoCaptureResult","role":"symbol","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureEvent":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureevent","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent","title":"FingersAutoCaptureEvent","role":"symbol","abstract":[{"text":"An event emitted during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureEvent"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureController"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureController"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller","abstract":[{"type":"text","text":"Non-UI component for the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController","title":"FingersAutoCaptureController","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}],"navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePhase":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCapturePhase"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCapturePhase"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturephase","abstract":[{"type":"text","text":"Phase of the fingers auto capture process."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","title":"FingersAutoCapturePhase","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP"},"doc://DotFingersCore/documentation/DotFingersCore/FingerToFingerprintTransformer":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"kind":"symbol","role":"symbol","title":"FingerToFingerprintTransformer","abstract":[{"text":"Stateless class which transforms detected finger images into fingerprint images.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerToFingerprintTransformer"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingertofingerprinttransformer"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/configuration-swift.property":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC13ConfigurationC"}],"navigatorTitle":[{"text":"configuration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/configuration-swift.property","abstract":[{"text":"Current configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/configuration-swift.property","title":"configuration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureController/process(sample:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"process"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sample"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC6SampleC","text":"Sample"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"ProcessingResult","kind":"typeIdentifier","preciseIdentifier":"s:14DotFingersCore0B21AutoCaptureControllerC16ProcessingResultC"}],"navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturecontroller\/process(sample:)","abstract":[{"type":"text","text":"Process an input sample and update the state."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/process(sample:)","title":"process(sample:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FingersNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","title":"FingersNotDetectedValidator","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGFingersAutoCaptureController","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePhase","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureEvent"],"title":"Fingers auto capture process","anchor":"Fingers-auto-capture-process"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"title":"Validators","anchor":"Validators"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/configuration-swift.property"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/captured(sample:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/init(configuration:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureController\/process(sample:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerToFingerprintTransformer"],"title":"Non-UI components","generated":true,"anchor":"Non-UI-components"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGFingersAutoCaptureController"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"capturedWithSample:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1captured(sample:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"capturedWithSample:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1captured(sample:)\/fragments","op":"replace"},{"value":"DOTFGFingerCountTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerCountTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","op":"replace"},{"value":"DOTFGSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","op":"replace"},{"value":[{"text":"DOTFGSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerCountNotFourValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingerCountNotFourValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerCountNotFourValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/navigatorTitle","op":"replace"},{"value":"initWithConfiguration:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1init(configuration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithConfiguration:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1init(configuration:)\/fragments","op":"replace"},{"value":"DOTFGDetectionPosition","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title","op":"replace"},{"value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments","op":"replace"},{"value":[{"text":"DOTFGDetectionPosition","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersOutOfBoundsValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerDetector","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","op":"replace"},{"value":[{"text":"DOTFGFingerDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","op":"replace"},{"value":"DOTFGSizeTooSmallValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","op":"replace"},{"value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureResult","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureDetection","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureEvent","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureEvent","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureEvent\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCapturePhase","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/title","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCapturePhase","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePhase\/navigatorTitle","op":"replace"},{"value":"DOTFGFingerToFingerprintTransformer","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/title","op":"replace"},{"value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingerToFingerprintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerToFingerprintTransformer\/navigatorTitle","op":"replace"},{"value":"configuration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1configuration-swift.property\/title","op":"replace"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1configuration-swift.property\/fragments","op":"replace"},{"value":"processWithSample:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1process(sample:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureController~1process(sample:)\/fragments","op":"replace"},{"value":"DOTFGFingersNotDetectedValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","op":"replace"},{"value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","op":"replace"}]}]}