{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Image"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"Image","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/init(format:bytes:size:)"]},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/bytes","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/format","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/size"],"anchor":"Instance-Properties","title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"type":"conformsTo","title":"Conforms To"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","interfaceLanguage":"swift"},"sections":[],"seeAlsoSections":[{"anchor":"Converting-images","title":"Converting images","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"],"generated":true}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/image"]}],"references":{"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/documentation/DotFingersCore/Image/format":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"format"}],"url":"\/documentation\/dotfingerscore\/image\/format","abstract":[{"type":"text","text":"Format of the stored image"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/format","title":"format","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Image/size":{"url":"\/documentation\/dotfingerscore\/image\/size","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"}],"title":"size","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/size","role":"symbol","abstract":[{"type":"text","text":"Image size."}],"navigatorTitle":[{"text":"size","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image/init(format:bytes:size:)":{"url":"\/documentation\/dotfingerscore\/image\/init(format:bytes:size:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/init(format:bytes:size:)","title":"init(format:bytes:size:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Image/bytes":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"url":"\/documentation\/dotfingerscore\/image\/bytes","abstract":[{"text":"Raw image data.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/bytes","title":"bytes","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"navigatorTitle":[{"text":"Image","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image","title":"Image","type":"topic","abstract":[],"role":"symbol"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/CIImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfingerscore\/ciimagefactory","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory","title":"CIImageFactory","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFactory":{"url":"\/documentation\/dotfingerscore\/imagefactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","title":"ImageFactory","role":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"text":" from iOS native image types.","type":"text"}],"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/Image/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/image\/description","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/description","title":"description","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore/CGImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/cgimagefactory","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","title":"CGImageFactory","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/bytes","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/format","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image\/size"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Converting-images","title":"Converting images","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CGImageFactory","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CIImageFactory"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1format\/title","value":"format"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1format\/fragments","value":[{"kind":"identifier","text":"format"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CGImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]}]}]}