{"metadata":{"navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTImageFormat","symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg2000","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgr","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgra"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","title":"Default Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFormat) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"languages":["swift"]}]}],"abstract":[{"text":"Supported image formats.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/imageformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/imageformat"]}],"references":{"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfingerscore\/imageformat","abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat","title":"ImageFormat","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfingerscore\/imageformat\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/description":{"url":"\/documentation\/dotfingerscore\/imageformat\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/description","title":"description","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/RawRepresentable-Implementations":{"url":"\/documentation\/dotfingerscore\/imageformat\/rawrepresentable-implementations","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/rawBgra":{"url":"\/documentation\/dotfingerscore\/imageformat\/rawbgra","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"title":"ImageFormat.rawBgra","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgra","role":"symbol","abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/jpeg2000":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"url":"\/documentation\/dotfingerscore\/imageformat\/jpeg2000","abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg2000","title":"ImageFormat.jpeg2000","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/jpeg":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"url":"\/documentation\/dotfingerscore\/imageformat\/jpeg","abstract":[{"type":"text","text":"JPEG compressed image format"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg","title":"ImageFormat.jpeg","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/rawBgr":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawBgr"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"url":"\/documentation\/dotfingerscore\/imageformat\/rawbgr","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgr","title":"ImageFormat.rawBgr","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable"},"doc://DotFingersCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFingersCore/documentation/DotFingersCore/ImageFormat/Equatable-Implementations":{"url":"\/documentation\/dotfingerscore\/imageformat\/equatable-implementations","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","type":"topic","kind":"article"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTImageFormat","path":"\/metadata\/title","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/jpeg2000","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgr","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageFormat\/rawBgra"],"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"path":"\/topicSections","op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFormat"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat\/navigatorTitle","op":"replace"},{"value":"DOTImageFormatRawBgra","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1rawBgra\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1rawBgra\/fragments","op":"replace"},{"value":"DOTImageFormatJpeg2000","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1jpeg2000\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1jpeg2000\/fragments","op":"replace"},{"value":"DOTImageFormatJpeg","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1jpeg\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1jpeg\/fragments","op":"replace"},{"value":"DOTImageFormatRawBgr","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1rawBgr\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgr"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageFormat~1rawBgr\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}