{"metadata":{"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLogger","title":"Logger","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"modules":[{"name":"DotFingersCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/logLevel"],"anchor":"Type-Properties"},{"generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/debug(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/error(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/info(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/warning(_:file:function:)"],"anchor":"Type-Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGLogger) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger","interfaceLanguage":"swift"},"sections":[],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization"],"generated":true,"title":"Global components","anchor":"Global-components"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/logger"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/Logger/info(_:file:function:)":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"info:file:function:"}],"url":"\/documentation\/dotfingerscore\/logger\/info(_:file:function:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/info(_:file:function:)","title":"info(_:file:function:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/Localization":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfingerscore\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","title":"Localization","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Logger":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger","url":"\/documentation\/dotfingerscore\/logger","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"title":"Logger"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Logger/warning(_:file:function:)":{"type":"topic","url":"\/documentation\/dotfingerscore\/logger\/warning(_:file:function:)","abstract":[],"title":"warning(_:file:function:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/warning(_:file:function:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"warning","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"warning:file:function:","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/Logger/logLevel":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/dotfingerscore\/logger\/loglevel","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/logLevel","title":"logLevel","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/Logger/debug(_:file:function:)":{"type":"topic","url":"\/documentation\/dotfingerscore\/logger\/debug(_:file:function:)","abstract":[],"title":"debug(_:file:function:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/debug(_:file:function:)","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"debug","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"debug:file:function:"}]},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/Logger/error(_:file:function:)":{"navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/error(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","title":"error(_:file:function:)","url":"\/documentation\/dotfingerscore\/logger\/error(_:file:function:)","abstract":[],"role":"symbol"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTFGLogger","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGLogger"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFGLogger","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/logLevel"],"title":"Type Properties"},{"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/debug(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/error(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/info(_:file:function:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/warning(_:file:function:)"],"generated":true}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Global-components","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization"],"title":"Global components"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFGLogger","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1info(_:file:function:)\/title","value":"info:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1info(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"info:file:function:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/title","value":"DOTFGLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/fragments","value":[{"text":"DOTFGLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/navigatorTitle","value":[{"text":"DOTFGLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/title","value":"DOTFGLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/fragments","value":[{"text":"DOTFGLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/navigatorTitle","value":[{"text":"DOTFGLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1warning(_:file:function:)\/title","value":"warning:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1warning(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"warning:file:function:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1logLevel\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1logLevel\/fragments","value":[{"text":"logLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1debug(_:file:function:)\/title","value":"debug:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1debug(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"debug:file:function:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1error(_:file:function:)\/title","value":"error:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1error(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"error:file:function:","kind":"identifier"}]}]}]}