{"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH","doc:\/\/DotFingersCore\/SY"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGPlaceholderType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/placeholdertype"]}],"abstract":[{"type":"text","text":"Type of placeholder."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@E@DOTFGPlaceholderType","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}]},"kind":"symbol","topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/left","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/right"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/init(rawValue:)"],"generated":true},{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/description"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/Equatable-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/Equatable-Implementations":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/equatable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/Equatable-Implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/init(rawValue:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfingerscore\/placeholdertype\/init(rawvalue:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlaceholderType"}],"navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"url":"\/documentation\/dotfingerscore\/placeholdertype","abstract":[{"text":"Type of placeholder.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType","title":"PlaceholderType","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/RawRepresentable-Implementations":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/rawrepresentable-implementations","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"type":"topic","kind":"article"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/left":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/left","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"left"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/left","title":"PlaceholderType.left","role":"symbol","abstract":[{"type":"text","text":"Left hand fingers placeholder."}],"navigatorTitle":[{"text":"DOTFGPlaceholderTypeLeft","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/description":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/description","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/PlaceholderType/right":{"url":"\/documentation\/dotfingerscore\/placeholdertype\/right","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/right","title":"PlaceholderType.right","role":"symbol","abstract":[{"type":"text","text":"Right hand fingers placeholder."}],"navigatorTitle":[{"text":"DOTFGPlaceholderTypeRight","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SY","title":"Swift.RawRepresentable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFGPlaceholderType","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/left","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/PlaceholderType\/right"],"title":"Enumeration Cases","generated":true}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGPlaceholderType"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFGPlaceholderType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/title"},{"op":"replace","value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/fragments"},{"op":"replace","value":[{"text":"DOTFGPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType\/navigatorTitle"},{"op":"replace","value":"DOTFGPlaceholderTypeLeft","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1left\/title"},{"op":"replace","value":[{"text":"DOTFGPlaceholderTypeLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1left\/fragments"},{"op":"replace","value":"DOTFGPlaceholderTypeRight","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1right\/title"},{"op":"replace","value":[{"text":"DOTFGPlaceholderTypeRight","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1PlaceholderType~1right\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}