{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder"},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"],"title":"Classes","generated":true,"anchor":"Classes"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFingersCore"}],"title":"Placeholder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Placeholder","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible"],"title":"Inherited By","kind":"relationships","type":"inheritedBy"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGPlaceholder) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"languages":["swift"]}]}],"abstract":[{"text":"Placeholder.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/placeholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/placeholder"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Visible":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"navigatorTitle":[{"kind":"identifier","text":"Visible"}],"url":"\/documentation\/dotfingerscore\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Visible","title":"Placeholder.Visible","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderHidden":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden","fragments":[{"text":"DOTFGPlaceholderHidden","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DOTFGPlaceholderHidden","abstract":[{"type":"text","text":"Hidden placeholder."}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholderhidden"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SH"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholder/init":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholder\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"init","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgplaceholder\/init"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Placeholder","abstract":[{"text":"Placeholder.","type":"text"}],"navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/placeholder"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder/Hidden":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder\/Hidden","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"Placeholder.Hidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/placeholder\/hidden"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGPlaceholderVisible":{"fragments":[{"kind":"identifier","text":"DOTFGPlaceholderVisible"}],"url":"\/documentation\/dotfingerscore\/dotfgplaceholdervisible","abstract":[{"text":"Visible placeholder.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible","title":"DOTFGPlaceholderVisible","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTFGPlaceholder","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTFGPlaceholder","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholder\/init"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderHidden","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGPlaceholderVisible"],"title":"Inherited By"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFGPlaceholder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title","value":"DOTFGPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGPlaceholder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}