{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFGSharpnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"title":"Validators","generated":true,"anchor":"Validators"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"]}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected fingers."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGSharpnessTooLowValidator","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"title":"SharpnessTooLowValidator","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}]},"kind":"symbol","topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/init(fingerType:threshold:minConfidenceThreshold:)"],"anchor":"Initializers","title":"Initializers"},{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/fingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/minConfidenceThreshold","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/threshold"],"generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/defaultThreshold"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FingersNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","title":"FingersNotDetectedValidator","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingersAutoCaptureFrameParametersValidator"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create fingers validators."}],"navigatorTitle":[{"text":"FingersAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparametersvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"kind":"symbol","role":"symbol","title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected fingers is too large.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sizetoolargevalidator"},"doc://DotFingersCore/documentation/DotFingersCore/FingersOutOfBoundsValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingersOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected fingers are within the bounds of the image."}],"navigatorTitle":[{"text":"FingersOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersoutofboundsvalidator"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"kind":"symbol","role":"symbol","title":"SharpnessTooLowValidator","abstract":[{"text":"Validate minimum sharpness of the detected fingers.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/fingerType":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"fingerType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","text":"FingerType"}],"navigatorTitle":[{"text":"fingerType","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/fingertype","abstract":[{"text":"Type of finger to validate.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/fingerType","title":"fingerType","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/minConfidenceThreshold":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/minconfidencethreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/minConfidenceThreshold","title":"minConfidenceThreshold","role":"symbol","abstract":[{"type":"text","text":"Minimum detection confidence threshold."}],"navigatorTitle":[{"text":"minConfidenceThreshold","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/dependencyIdentifiers":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/dependencyidentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"dependencyIdentifiers","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/dependencyIdentifiers","role":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountTooLowValidator":{"navigatorTitle":[{"text":"FingerCountTooLowValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum count of detected fingers."}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercounttoolowvalidator","title":"FingerCountTooLowValidator","role":"symbol"},"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/SQ"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/threshold":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/threshold","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"threshold","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/threshold","role":"symbol","abstract":[{"text":"Current minimal accepted sharpness.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/init(fingerType:threshold:minConfidenceThreshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingerType"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@E@DOTFGFingerType","kind":"typeIdentifier","text":"FingerType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"threshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithFingerType:threshold:minConfidenceThreshold:error:"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/init(fingertype:threshold:minconfidencethreshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/init(fingerType:threshold:minConfidenceThreshold:)","title":"init(fingerType:threshold:minConfidenceThreshold:)","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/defaultThreshold":{"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/defaultthreshold","abstract":[{"type":"text","text":"Default threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/defaultThreshold","title":"defaultThreshold","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerCountNotFourValidator":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingerCountNotFourValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"FingerCountNotFourValidator","abstract":[{"text":"Validate whether the count of detected fingers is four.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingerCountNotFourValidator"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingercountnotfourvalidator"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/identifier":{"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/identifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/identifier","title":"identifier","role":"symbol","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFingersCore/documentation/DotFingersCore/SizeTooSmallValidator":{"url":"\/documentation\/dotfingerscore\/sizetoosmallvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","title":"SizeTooSmallValidator","role":"symbol","abstract":[{"text":"Validate whether the size of the detected fingers is too small.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/SharpnessTooLowValidator/validate(fingersAutoCaptureFrameParameters:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"url":"\/documentation\/dotfingerscore\/sharpnesstoolowvalidator\/validate(fingersautocaptureframeparameters:)","abstract":[{"type":"text","text":"Validate sharpness of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)","title":"validate(fingersAutoCaptureFrameParameters:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFGSharpnessTooLowValidator"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/fingerType","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/identifier","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/minConfidenceThreshold","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/threshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/init(fingerType:threshold:minConfidenceThreshold:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/validate(fingersAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SharpnessTooLowValidator\/defaultThreshold"],"generated":true,"title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParametersValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersOutOfBoundsValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooLargeValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/SizeTooSmallValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountTooLowValidator","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerCountNotFourValidator"],"title":"Validators","anchor":"Validators","generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFGSharpnessTooLowValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"DOTFGFingersNotDetectedValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParametersValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGFingersOutOfBoundsValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersOutOfBoundsValidator\/navigatorTitle","op":"replace"},{"value":"DOTFGSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator\/navigatorTitle","op":"replace"},{"value":"fingerType","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1fingerType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"fingerType"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1fingerType\/fragments","op":"replace"},{"value":"minConfidenceThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1minConfidenceThreshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minConfidenceThreshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1minConfidenceThreshold\/fragments","op":"replace"},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1dependencyIdentifiers\/title","op":"replace"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1dependencyIdentifiers\/fragments","op":"replace"},{"value":"DOTFGFingerCountTooLowValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountTooLowValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountTooLowValidator\/navigatorTitle","op":"replace"},{"value":"threshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1threshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"threshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1threshold\/fragments","op":"replace"},{"value":"initWithFingerType:threshold:minConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1init(fingerType:threshold:minConfidenceThreshold:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFingerType:threshold:minConfidenceThreshold:error:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1init(fingerType:threshold:minConfidenceThreshold:)\/fragments","op":"replace"},{"value":"defaultThreshold","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1defaultThreshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"defaultThreshold"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1defaultThreshold\/fragments","op":"replace"},{"value":"DOTFGFingerCountNotFourValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountNotFourValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingerCountNotFourValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerCountNotFourValidator\/navigatorTitle","op":"replace"},{"value":"identifier","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1identifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1identifier\/fragments","op":"replace"},{"value":"DOTFGSizeTooSmallValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace"},{"value":"validateWithFingersAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1SharpnessTooLowValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments","op":"replace"}]}]}