{"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTWrappedFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfingerscore\/wrappedfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/wrappedfloat"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"title":"WrappedFloat","role":"symbol","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore"]]},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/init(value:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/value"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"references":{"doc://DotFingersCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/wrappedfloat\/isequal(_:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedFloat"}],"kind":"symbol","role":"symbol","title":"WrappedFloat","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":" value for Objective-C support.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}],"type":"topic","url":"\/documentation\/dotfingerscore\/wrappedfloat"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotfingerscore\/wrappedfloat\/hash","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/hash","title":"hash","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/init(value:)":{"url":"\/documentation\/dotfingerscore\/wrappedfloat\/init(value:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"},{"kind":"text","text":")"}],"title":"init(value:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/init(value:)","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithValue:"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/description":{"url":"\/documentation\/dotfingerscore\/wrappedfloat\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/description","role":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/WrappedFloat/value":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/value","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"kind":"symbol","role":"symbol","title":"value","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"value"}],"type":"topic","url":"\/documentation\/dotfingerscore\/wrappedfloat\/value"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFingersCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFingersCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable"},"doc://DotFingersCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/hash","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/value"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/init(value:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/WrappedFloat\/isEqual(_:)"],"title":"Instance Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"],"title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTWrappedFloat","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat\/navigatorTitle","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1init(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1value\/title","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1WrappedFloat~1value\/fragments","value":[{"text":"value","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}