{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/score","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceattribute\/score"]},{"paths":["\/documentation\/dotfacecore\/faceattribute\/score"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"score","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"inlineContent":[{"type":"text","text":"The score is reliable only if the "},{"code":"preconditionsMet","type":"codeVoice"},{"type":"text","text":" flag is set to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}]}],"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute(py)score","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"score","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"score","kind":"identifier"}],"title":"score","role":"symbol"},"abstract":[{"text":"Face attribute score.","type":"text"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"title":"FaceAttribute","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/score":{"navigatorTitle":[{"text":"score","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute\/score","role":"symbol","title":"score","abstract":[{"type":"text","text":"Face attribute score."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/score","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"score"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"score"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"score"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"op":"replace","value":"score","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1score\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1score\/fragments","op":"replace","value":[{"text":"score","kind":"identifier"}]}]}]}