{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotlibrary\/deinitialize()"]},{"paths":["\/documentation\/dotdocument\/dotlibrary\/deinitialize()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary"]]},"sections":[],"metadata":{"externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)deinitializeAndReturnError:","required":true,"title":"deinitialize()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/deinitialize()"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotLibrary/deinitialize()":{"title":"deinitialize()","required":true,"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/deinitialize()","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"url":"\/documentation\/dotdocument\/dotlibrary\/deinitialize()"},"doc://DotDocument/documentation/DotDocument/DotLibrary":{"title":"DotLibrary","kind":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotlibrary"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.15.0","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"deinitializeAndReturnError:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1deinitialize()\/title","value":"deinitializeAndReturnError:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1deinitialize()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments"}]}]}