{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"initWithDetectionPosition:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","kind":"typeIdentifier","text":"DOTPDetectionPosition","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"kind":"text","text":" *) "},{"text":"detectionPosition","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"confidence:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"confidence","kind":"internalParam"},{"kind":"text","text":" "},{"text":"imageParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","text":"DOTPImageParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageParameters"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionPosition:confidence:imageParameters:"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionPosition:confidence:imageParameters:"}],"roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm(im)initWithDetectionPosition:confidence:imageParameters:","title":"initWithDetectionPosition:confidence:imageParameters:"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:imageParameters:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:imageparameters:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","role":"symbol","title":"DOTPPalmDetectorPalm","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Result of the palm detection process."}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"title":"DetectionPosition","abstract":[{"text":"Position of the palm in the image.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/detectionposition"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm/initWithDetectionPosition:confidence:imageParameters:":{"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDetectionPosition:confidence:imageParameters:"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm\/initwithdetectionposition:confidence:imageparameters:","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionPosition:confidence:imageParameters:"}],"title":"initWithDetectionPosition:confidence:imageParameters:","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm\/initWithDetectionPosition:confidence:imageParameters:"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"url":"\/documentation\/dotpalmcore\/imageparameters","role":"symbol","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageParameters"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","title":"ImageParameters"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","op":"replace","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title","value":"DOTPImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}]}]}]}