{"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/intervalfloat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/intervalfloat"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalFloat"}],"symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotDocument"}],"title":"IntervalFloat","externalID":"c:@M@DotDocument@objc(cs)DOTIntervalFloat","role":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTIntervalFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/init(min:max:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/max","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/min"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/Error"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/min":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/min","url":"\/documentation\/dotdocument\/intervalfloat\/min","role":"symbol","kind":"symbol","title":"min","abstract":[{"text":"Minimal interval value.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"min","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"navigatorTitle":[{"text":"min","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/max":{"abstract":[{"type":"text","text":"Maximal interval value."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/max","url":"\/documentation\/dotdocument\/intervalfloat\/max","role":"symbol","kind":"symbol","title":"max","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"navigatorTitle":[{"kind":"identifier","text":"max"}],"type":"topic"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/hash","url":"\/documentation\/dotdocument\/intervalfloat\/hash","kind":"symbol","title":"hash","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/isEqual(_:)":{"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/isEqual(_:)","url":"\/documentation\/dotdocument\/intervalfloat\/isequal(_:)","role":"symbol","kind":"symbol","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/description":{"abstract":[],"url":"\/documentation\/dotdocument\/intervalfloat\/description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/description","role":"symbol","kind":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/Error":{"url":"\/documentation\/dotdocument\/intervalfloat\/error","role":"symbol","title":"IntervalFloat.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/Error","abstract":[]},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat":{"url":"\/documentation\/dotdocument\/intervalfloat","role":"symbol","title":"IntervalFloat","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/IntervalFloat/init(min:max:)":{"navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"min","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"text":", ","kind":"text"},{"text":"max","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/init(min:max:)","url":"\/documentation\/dotdocument\/intervalfloat\/init(min:max:)","title":"init(min:max:)","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.document/SH":{"identifier":"doc:\/\/com.innovatrics.dot.document\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTIntervalFloat","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/max","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/min"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/init(min:max:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/IntervalFloat\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTIntervalFloat","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1min\/title","value":"min"},{"value":[{"text":"min","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1min\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1max\/title","value":"max","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1max\/fragments","op":"replace","value":[{"text":"max","kind":"identifier"}]},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1hash\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1hash\/fragments","op":"replace","value":[{"kind":"identifier","text":"hash"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1isEqual(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1description\/title","op":"replace","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1description\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"value":"initWithMin:max:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1init(min:max:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMin:max:error:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1IntervalFloat~1init(min:max:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}