{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/description","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/imageformat\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"title":"description","role":"symbol","symbolKind":"property","externalID":"s:7DotCore11ImageFormatO11descriptionSSvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property"},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/description":{"url":"\/documentation\/dotfacelite\/imageformat\/description","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/description","kind":"symbol","title":"description","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"type":"topic","abstract":[{"type":"text","text":"Supported image formats."}],"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfacelite\/imageformat","title":"ImageFormat"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}]}]}]}