{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","interfaceLanguage":"occ"},"abstract":[{"type":"text","text":"Create the palm auto capture configuration."}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(im)initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","navigatorTitle":[{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithBaseConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPBasePalmAutoCaptureConfiguration","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"baseConfiguration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isDetectionLayerVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"isDetectionLayerVisible","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholder:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","text":"DOTPPlaceholder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","type":"topic","kind":"symbol","role":"symbol","title":"Placeholder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}],"abstract":[{"text":"Placeholder.","type":"text"}],"url":"\/documentation\/dotpalmcore\/placeholder","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration","type":"topic","title":"DOTPBasePalmAutoCaptureConfiguration","fragments":[{"text":"DOTPBasePalmAutoCaptureConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration options for the palm auto capture process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","role":"symbol","abstract":[{"type":"text","text":"Configuration options for the UI Palm Auto Capture component."}],"title":"DOTPPalmAutoCaptureConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","role":"symbol","abstract":[{"text":"Create the palm auto capture configuration.","type":"text"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:","navigatorTitle":[{"kind":"identifier","text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}],"title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title"},{"value":[{"text":"DOTPPlaceholder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle"}]}]}