{"kind":"symbol","abstract":[{"type":"text","text":"Specify the placeholder. Default is "},{"type":"text","text":".Visible"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPPlaceholder","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPlaceholder","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder"},{"text":" * ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":";","kind":"text"}]}]}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"kind":"identifier","text":"placeholder"}],"navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","title":"placeholder","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureConfiguration(py)placeholder"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/placeholder","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/placeholder"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration/placeholder":{"abstract":[{"text":"Specify the placeholder. Default is ","type":"text"},{"text":".Visible","type":"text"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration\/placeholder","type":"topic","role":"symbol","kind":"symbol","title":"placeholder","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration\/placeholder","fragments":[{"kind":"identifier","text":"placeholder"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureConfiguration":{"abstract":[{"text":"Configuration options for the UI Palm Auto Capture component.","type":"text"}],"type":"topic","title":"DOTPPalmAutoCaptureConfiguration","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureconfiguration","fragments":[{"text":"DOTPPalmAutoCaptureConfiguration","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"url":"\/documentation\/dotpalmcore\/placeholder","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"kind":"symbol","title":"Placeholder","abstract":[{"type":"text","text":"Placeholder."}],"navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTPPlaceholder","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPlaceholder"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","op":"replace"}]}]}