{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculateWidthToHeightRatio()"},"abstract":[{"type":"text","text":"Calculate width to height ratio."}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"symbolKind":"method","modules":[{"name":"DotPalmCore"}],"role":"symbol","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DOTImageSize(im)calculateWidthToHeightRatio","title":"calculateWidthToHeightRatio()"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":"() -> ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/imagesize\/calculatewidthtoheightratio()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imagesize\/calculatewidthtoheightratio()"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageSize":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"abstract":[{"type":"text","text":"Image size in pixels."}],"title":"ImageSize","url":"\/documentation\/dotpalmcore\/imagesize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/ImageSize/calculateWidthToHeightRatio()":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageSize\/calculateWidthToHeightRatio()","abstract":[{"type":"text","text":"Calculate width to height ratio."}],"url":"\/documentation\/dotpalmcore\/imagesize\/calculatewidthtoheightratio()","title":"calculateWidthToHeightRatio()"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"calculateWidthToHeightRatio","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize\/fragments"},{"value":"calculateWidthToHeightRatio","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculateWidthToHeightRatio()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"calculateWidthToHeightRatio"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageSize~1calculateWidthToHeightRatio()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}