{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/description","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"metadata":{"externalID":"s:11DotPalmCore0B18AutoCaptureUiStateC4IdleC11descriptionSSvp","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol","title":"description","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/description"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle/description":{"abstract":[],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle\/description","kind":"symbol","title":"description","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"title":"PalmAutoCaptureUiState","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","title":"PalmAutoCaptureUiState.Idle","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Idle"}],"navigatorTitle":[{"kind":"identifier","text":"Idle"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle","abstract":[{"type":"text","text":"Idle state."}],"type":"topic","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTPPalmAutoCaptureUiState","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle"}]}]}