{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgRect","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/cgRect","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"extendedModule":"DotCore","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)cgRect","title":"cgRect","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/cgrect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/cgrect"]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble/cgRect":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/cgRect","title":"cgRect","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"}],"url":"\/documentation\/dotfacecore\/rectangledouble\/cgrect","navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.17.1","type":"text"}],"type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/rectangledouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"RectangleDouble"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cgRect"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cgRect"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier","text":"CGRect"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1cgRect\/title","value":"cgRect"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1cgRect\/fragments","value":[{"text":"cgRect","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/navigatorTitle","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}