{"variants":[{"paths":["\/documentation\/dotfacecore\/expression\/mouth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/expression\/mouth"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Mouth expression.","type":"text"}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpression(py)mouth","navigatorTitle":[{"text":"mouth","kind":"identifier"}],"title":"mouth","symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"mouth","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/mouth"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Expression/mouth":{"title":"mouth","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mouth","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/mouth","url":"\/documentation\/dotfacecore\/expression\/mouth","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Mouth expression."}],"navigatorTitle":[{"text":"mouth","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","role":"symbol","url":"\/documentation\/dotfacecore\/expression","title":"Expression","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"navigatorTitle":[{"text":"Expression","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"role":"symbol","title":"FaceAttribute","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"url":"\/documentation\/dotfacecore\/faceattribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"mouth"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"mouth","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFFaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},{"kind":"text","text":" * "},{"text":"mouth","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"mouth","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1mouth\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1mouth\/fragments","value":[{"kind":"identifier","text":"mouth"}],"op":"replace"},{"op":"replace","value":"DOTFExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]}]}]}