{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"title":"BgraRawImageFactory","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"role":"symbol"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"generated":true,"title":"Converting images"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBgraRawImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrarawimagefactory"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"role":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","kind":"symbol","url":"\/documentation\/dotpalmcore\/ciimagefactory","title":"CIImageFactory"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","title":"BgraRawImage","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrarawimage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"title":"CGImageFactory","role":"symbol","url":"\/documentation\/dotpalmcore\/cgimagefactory","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory/create(cgImage:)":{"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(cgimage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"title":"create(cgImage:)","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"title":"BgraRawImageFactory","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory/create(ciImage:ciContext:)":{"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory\/create(ciimage:cicontext:)","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"title":"create(ciImage:ciContext:)","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(ciImage:ciContext:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTBgraRawImageFactory"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}]},{"value":[{"title":"Converting images","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTBgraRawImageFactory","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCIImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(cgImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCgImage:"}],"op":"replace"},{"value":"DOTBgraRawImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","op":"replace","value":"createWithCiImage:ciContext:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"op":"replace"}]}]}