{"metadata":{"role":"symbol","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"title":"BgrRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}],"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory","symbolKind":"class"},"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory"]},{"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTBgrRawImageFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory/create(ciImage:ciContext:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(ciImage:ciContext:)","role":"symbol","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"type":"topic","title":"create(ciImage:ciContext:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(ciimage:cicontext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory/create(cgImage:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(cgImage:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as a "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(cgimage:)","kind":"symbol","title":"create(cgImage:)","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}],"role":"symbol","type":"topic","abstract":[{"text":"Create ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"url":"\/documentation\/dotpalmcore\/bgrrawimagefactory","kind":"symbol","title":"BgrRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgrRawImageFactory"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTBgrRawImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"op":"replace"},{"value":"createWithCgImage:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(cgImage:)\/title","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(cgImage:)\/fragments","op":"replace"},{"op":"replace","value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/fragments","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace"}]}]}