{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"topicSections":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/back","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/front"]},{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/init(rawValue:)"]},{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/native"]},{"anchor":"Default-Implementations","title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCameraFacing) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"externalID":"c:@M@DotCamera@E@DOTCameraFacing","title":"CameraFacing","roleHeading":"Enumeration","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"symbolKind":"enum"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/camerafacing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/camerafacing"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing"},"references":{"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/init(rawValue:)":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/init(rawvalue:)","title":"init(rawValue:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/init(rawValue:)"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/front":{"role":"symbol","abstract":[{"text":"Front facing camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"front"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/front","title":"CameraFacing.front","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/front","navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingFront"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/RawRepresentable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/dotpalmcore\/camerafacing\/rawrepresentable-implementations","title":"RawRepresentable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/RawRepresentable-Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/native":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/native","title":"native","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/native"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/description":{"role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/description","title":"description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/description"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"url":"\/documentation\/dotpalmcore\/camerafacing\/equatable-implementations","title":"Equatable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/Equatable-Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"role":"symbol","url":"\/documentation\/dotpalmcore\/camerafacing","kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","type":"topic","abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"title":"CameraFacing"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing/back":{"role":"symbol","abstract":[{"text":"Back facing camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"back"}],"url":"\/documentation\/dotpalmcore\/camerafacing\/back","title":"CameraFacing.back","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/back","navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}]},"doc://DotPalmCore/SY":{"identifier":"doc:\/\/DotPalmCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DOTCameraFacing"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCameraFacing","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/back","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing\/front"]}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCameraFacing"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1front\/title","op":"replace","value":"DOTCameraFacingFront"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1front\/fragments","op":"replace","value":[{"text":"DOTCameraFacingFront","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title","value":"DOTCameraFacing","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1back\/title","value":"DOTCameraFacingBack","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing~1back\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}