{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory","title":"CGImageFactory","symbolKind":"class","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cgimagefactory"]},{"paths":["\/documentation\/dotpalmcore\/cgimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgraRawImage:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCGImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"title":"Converting images","generated":true}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"url":"\/documentation\/dotpalmcore\/ciimagefactory","abstract":[{"text":"Create ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"title":"CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CIImageFactory"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"url":"\/documentation\/dotpalmcore\/cgimagefactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"kind":"symbol","title":"CGImageFactory","type":"topic","role":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory/create(bgraRawImage:)":{"role":"symbol","url":"\/documentation\/dotpalmcore\/cgimagefactory\/create(bgrarawimage:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"createWithBgraRawImage:"}],"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgraRawImage:)","title":"create(bgraRawImage:)"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImageFactory":{"role":"symbol","title":"BgraRawImageFactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/bgrarawimagefactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory/create(bgrRawImage:)":{"kind":"symbol","role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"type":"topic","navigatorTitle":[{"text":"createWithBgrRawImage:","kind":"identifier"}],"title":"create(bgrRawImage:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgrRawImage:)","url":"\/documentation\/dotpalmcore\/cgimagefactory\/create(bgrrawimage:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","title":"DotPalmCore","abstract":[{"text":"version: 8.15.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCGImageFactory"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory\/create(bgraRawImage:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Converting images","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"]}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCGImageFactory"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory","op":"replace"},{"value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(bgraRawImage:)\/title","value":"createWithBgraRawImage:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithBgraRawImage:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/title","op":"replace","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImageFactory\/fragments","op":"replace","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(bgrRawImage:)\/title","value":"createWithBgrRawImage:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory~1create(bgrRawImage:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgrRawImage:"}]}]}]}