{"metadata":{"externalID":"c:@M@DotCore@E@DotDocumentModuleId","symbolKind":"enum","navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"role":"symbol","roleHeading":"Enumeration","title":"DotDocumentModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId"},"sections":[],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/barcode"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/barcode":{"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/barcode","navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/barcode","type":"topic","role":"symbol","title":"DotDocumentModuleId.barcode","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/init(rawValue:)":{"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/init(rawValue:)","type":"topic","role":"symbol","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/Equatable-Implementations":{"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/equatable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/Equatable-Implementations","type":"topic","role":"collectionGroup","title":"Equatable Implementations","kind":"article","abstract":[]},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/RawRepresentable-Implementations":{"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/RawRepresentable-Implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","abstract":[]},"doc://DotPalmCore/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/description":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/description","title":"description","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId":{"navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"kind":"symbol","title":"DotDocumentModuleId","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId","abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/barcode"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId~1barcode\/title","value":"DotDocumentModuleIdBarcode"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId~1barcode\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/title","value":"DotDocumentModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]}]}]}