{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","interfaceLanguage":"swift"},"abstract":[{"text":"Face library configuration.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","topicSections":[{"title":"Classes","generated":true,"anchor":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/modules-swift.property"]}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"title":"DotFaceLibraryConfiguration","roleHeading":"Class","role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration"]},{"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration":{"kind":"symbol","role":"symbol","abstract":[{"text":"Face library configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration","title":"DotFaceLibraryConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/init(modules:)":{"type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:)","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/init(modules:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"kind":"symbol","title":"init(modules:)","role":"symbol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/modules-swift.property":{"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Module configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/modules-swift.property","navigatorTitle":[{"text":"modules","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Modules","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.property","title":"modules"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","role":"symbol","navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","type":"topic","title":"faceDetectionConfidenceThreshold","kind":"symbol","abstract":[{"type":"text","text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval "},{"type":"codeVoice","code":"[0.0, 1.0]"},{"type":"text","text":". Default value is "},{"type":"codeVoice","code":"0.06"},{"type":"text","text":"."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/Modules-swift.class":{"kind":"symbol","role":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/modules-swift.class","title":"DotFaceLibraryConfiguration.Modules"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"kind":"symbol","role":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","navigatorTitle":[{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"},{"text":", ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","title":"init(modules:faceDetectionConfidenceThreshold:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/modules-swift.property"],"title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"title":"Instance Methods","anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1modules-swift.property\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","value":[{"text":"modules","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title","value":"faceDetectionConfidenceThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments","value":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title","value":"initWithModules:faceDetectionConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:faceDetectionConfidenceThreshold:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}