{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"roleHeading":"Class","role":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","symbolKind":"class","navigatorTitle":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationBalanced","fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["occ"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfigurationbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration"]}],"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced\/init"]}],"abstract":[{"type":"text","text":"Face detection balanced module."}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfigurationBalanced":{"type":"topic","role":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfigurationbalanced","abstract":[{"text":"Face detection balanced module.","type":"text"}],"kind":"symbol","fragments":[{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"kind":"symbol","abstract":[{"text":"Face detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfiguration","type":"topic","title":"DotFaceDetectionModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceDetectionModuleConfigurationBalanced/init":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfacedetectionmoduleconfigurationbalanced\/init","kind":"symbol","title":"init","role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceDetectionModuleConfigurationBalanced\/init"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/title","op":"replace","value":"DotFaceDetectionModuleConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}