{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary","doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"]}],"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library initialization."}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibrary","title":"DotPalmLibrary","roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"seeAlsoSections":[{"title":"Global components","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Logger","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Localization"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmLibrary","kind":"identifier"}],"platforms":["iOS"]}]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/init(configuration:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/configuration","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/initialize(license:)"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/Error"]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/configuration":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/configuration","kind":"symbol","type":"topic","title":"configuration","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"configuration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration"}],"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":" configuration."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/configuration","navigatorTitle":[{"kind":"identifier","text":"configuration"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/Localization":{"title":"Localization","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotpalmcore\/localization","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Localization"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/init(configuration:)":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/init(configuration:)","type":"topic","kind":"symbol","title":"init(configuration:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotPalmLibraryConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":")"}],"abstract":[{"text":"Init ","type":"text"},{"code":"DotPalmLibrary","type":"codeVoice"},{"type":"text","text":"."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/init(configuration:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/deinitialize()":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/deinitialize()","kind":"symbol","type":"topic","title":"deinitialize()","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Deinitialize library."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/deinitialize()","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/Error":{"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/error","kind":"symbol","title":"DotPalmLibrary.Error","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/Error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/Logger":{"title":"Logger","url":"\/documentation\/dotpalmcore\/logger","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Logger","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Logger","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/initialize(license:)":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/initialize(license:)","type":"topic","kind":"symbol","title":"initialize(license:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Initialize library with license.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/initialize(license:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}]},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.palm.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary/id":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/id","type":"topic","kind":"symbol","title":"id","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotPalmCore@E@DotLibraryId","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The library identifier."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/id","navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotLibrary":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotlibrary","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/DotPalmLibrary":{"title":"DotPalmLibrary","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibrary","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibrary"}],"abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DotPalmLibrary","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmLibrary"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibrary"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/configuration","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/id"]},{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/deinitialize()","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/init(configuration:)","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotPalmLibrary\/initialize(license:)"],"title":"Instance Methods"}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"title":"Inherits From"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/DotLibrary"],"kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"title":"Global components","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Logger","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/Localization"],"generated":true}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibrary"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1configuration\/title","value":"configuration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1configuration\/fragments","value":[{"kind":"identifier","text":"configuration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Localization\/title","value":"DOTPLocalization"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTPLocalization"}]},{"value":"initWithConfiguration:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1init(configuration:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1init(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithConfiguration:","kind":"identifier"}],"op":"replace"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1deinitialize()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1deinitialize()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Logger\/title","value":"DOTPLogger"},{"value":[{"text":"DOTPLogger","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1Logger\/fragments","op":"replace"},{"value":"initializeWithLicense:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1initialize(license:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1initialize(license:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1id\/title","value":"id","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary~1id\/fragments","value":[{"text":"id","kind":"identifier"}]},{"op":"replace","value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/title"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotLibrary\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary\/title","value":"DotPalmLibrary"},{"op":"replace","value":[{"text":"DotPalmLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}