{"abstract":[{"text":"Configuration of the ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":" library. This class specifies how the ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" library will be initialized."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo"}],"metadata":{"roleHeading":"Class","title":"DotPalmLibraryConfiguration","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol"},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/init(modules:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/modules":{"kind":"symbol","abstract":[{"text":"List of modules to load during initialization.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DotPalmModule","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotPalmModule"},{"kind":"text","text":"]"}],"title":"modules","type":"topic","navigatorTitle":[{"text":"modules","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"kind":"symbol","abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotPalm"},{"text":" library. This class specifies how the ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":" library will be initialized."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","type":"topic","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/init(modules:)":{"title":"init(modules:)","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/init(modules:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(pl)DotPalmModule","text":"DotPalmModule","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/init(modules:)"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.12.0","type":"text"}],"title":"DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DotPalmLibraryConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/init(modules:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules\/title","value":"modules"},{"value":[{"text":"modules","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithModules:"}]}]}]}