{"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@E@DOTPHandPosition","title":"HandPosition","role":"symbol","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPHandPosition) ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"HandPosition","kind":"identifier"}]}]}],"sections":[],"abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/handposition"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/handposition"]}],"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/right"]},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/init(rawValue:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/description"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"},"references":{"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"type":"topic","url":"\/documentation\/dotpalmcore\/handposition","title":"HandPosition","role":"symbol","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/left":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"left"}],"kind":"symbol","title":"HandPosition.left","abstract":[{"type":"text","text":"Left hand."}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/left","url":"\/documentation\/dotpalmcore\/handposition\/left","navigatorTitle":[{"kind":"identifier","text":"DOTPHandPositionLeft"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SY":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY","title":"Swift.RawRepresentable"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/dotpalmcore\/handposition\/rawrepresentable-implementations","abstract":[],"kind":"article","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/init(rawValue:)":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/handposition\/init(rawvalue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/description":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"description","url":"\/documentation\/dotpalmcore\/handposition\/description","abstract":[],"type":"topic","role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/Equatable-Implementations":{"kind":"article","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/Equatable-Implementations","url":"\/documentation\/dotpalmcore\/handposition\/equatable-implementations"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/right":{"navigatorTitle":[{"kind":"identifier","text":"DOTPHandPositionRight"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/handposition\/right","abstract":[{"type":"text","text":"Right hand."}],"title":"HandPosition.right","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/right"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTPHandPosition"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPHandPosition"}]},{"path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/left","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/right"]}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPHandPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","value":"DOTPHandPosition","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPHandPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1left\/title","value":"DOTPHandPositionLeft"},{"value":[{"kind":"identifier","text":"DOTPHandPositionLeft"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1left\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1right\/title","op":"replace","value":"DOTPHandPositionRight"},{"value":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1right\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}