{"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"Image","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"externalID":"c:@M@DotCore@objc(cs)DOTImage","title":"Image"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"generated":true,"anchor":"Converting-images","title":"Converting images"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/image"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/image"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/init(format:bytes:size:)"],"generated":true,"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/format","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/size"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImage) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"title":"PalmDetector","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/Image/init(format:bytes:size:)":{"kind":"symbol","abstract":[],"title":"init(format:bytes:size:)","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/init(format:bytes:size:)","role":"symbol","url":"\/documentation\/dotpalmcore\/image\/init(format:bytes:size:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":")","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/Image/bytes":{"role":"symbol","url":"\/documentation\/dotpalmcore\/image\/bytes","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/bytes","abstract":[{"type":"text","text":"Raw image data."}],"kind":"symbol","title":"bytes","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Image/description":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/description","url":"\/documentation\/dotpalmcore\/image\/description","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/CIImageFactory":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/ciimagefactory","kind":"symbol","title":"CIImageFactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Image/format":{"title":"format","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"}],"url":"\/documentation\/dotpalmcore\/image\/format","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/format","kind":"symbol","abstract":[{"type":"text","text":"Format of the stored image"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"format"}]},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","title":"Image","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/image"},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFactory":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"title":"ImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/imagefactory"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/Image/size":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/size","abstract":[{"type":"text","text":"Image size."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/image\/size","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"}],"type":"topic","title":"size"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotPalmCore","role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CGImageFactory":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"title":"CGImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","url":"\/documentation\/dotpalmcore\/cgimagefactory","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTImage"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/bytes","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/format","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image\/size"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CGImageFactory","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CIImageFactory"],"anchor":"Converting-images"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImage","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace","value":"DOTPPalmDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1bytes\/title","value":"bytes"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/title","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CIImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCIImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1format\/title","value":"format"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1format\/fragments","value":[{"text":"format","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/title","value":"DOTCGImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CGImageFactory\/navigatorTitle","value":[{"text":"DOTCGImageFactory","kind":"identifier"}]}]}]}