{"variants":[{"paths":["\/documentation\/dotpalmcore\/imageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/imageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Supported image formats."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"externalID":"c:@M@DotCore@E@DOTImageFormat","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"symbolKind":"enum","roleHeading":"Enumeration","modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"topicSections":[{"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg2000","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgr","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgra"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/RawRepresentable-Implementations"]}],"sections":[],"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTImageFormat) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"type":"topic","abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","url":"\/documentation\/dotpalmcore\/imageformat"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/Equatable-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/Equatable-Implementations","url":"\/documentation\/dotpalmcore\/imageformat\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/rawBgr":{"kind":"symbol","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgr","navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"title":"ImageFormat.rawBgr","url":"\/documentation\/dotpalmcore\/imageformat\/rawbgr"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/init(rawValue:)":{"kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/init(rawValue:)","url":"\/documentation\/dotpalmcore\/imageformat\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/description":{"title":"description","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/imageformat\/description","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/jpeg2000":{"url":"\/documentation\/dotpalmcore\/imageformat\/jpeg2000","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg2000","abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"role":"symbol","kind":"symbol","title":"ImageFormat.jpeg2000"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/RawRepresentable-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/RawRepresentable-Implementations","url":"\/documentation\/dotpalmcore\/imageformat\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"kind":"article","type":"topic"},"doc://DotPalmCore/SY":{"identifier":"doc:\/\/DotPalmCore\/SY","title":"Swift.RawRepresentable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/rawBgra":{"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgra","title":"ImageFormat.rawBgra","url":"\/documentation\/dotpalmcore\/imageformat\/rawbgra","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/jpeg":{"navigatorTitle":[{"text":"DOTImageFormatJpeg","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg","title":"ImageFormat.jpeg","url":"\/documentation\/dotpalmcore\/imageformat\/jpeg","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg","kind":"identifier"}],"abstract":[{"type":"text","text":"JPEG compressed image format"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTImageFormat","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg2000","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgr","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgra"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFormat"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTImageFormat","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","op":"replace"},{"value":"DOTImageFormatRawBgr","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgr\/title"},{"value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgr\/fragments"},{"value":"DOTImageFormatJpeg2000","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg2000\/title"},{"value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg2000\/fragments"},{"value":"DOTImageFormatRawBgra","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgra\/title"},{"value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgra\/fragments"},{"value":"DOTImageFormatJpeg","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg\/title"},{"value":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}