{"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"metadata":{"title":"ImageParameters","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector\/Palm","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/RectangleDouble"],"generated":true,"title":"Palm detection output"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPImageParameters) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageParameters"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/imageparameters"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageparameters"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/init(sharpness:brightness:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/brightness","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/description","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/hash","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/sharpness"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/isEqual(_:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters"},"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/init(sharpness:brightness:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/init(sharpness:brightness:)","abstract":[{"text":"Initialize ","type":"text"},{"code":"ImageParameters","type":"codeVoice"},{"text":" with normalized values in range [0, 1.0].","type":"text"}],"navigatorTitle":[{"text":"initWithSharpness:brightness:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imageparameters\/init(sharpness:brightness:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":", ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(sharpness:brightness:)"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/sharpness":{"abstract":[{"type":"text","text":"Overall sharpness of the palm in range [0, 1.0]. Where 0 means low sharpness and 1.0 means high sharpness."}],"url":"\/documentation\/dotpalmcore\/imageparameters\/sharpness","kind":"symbol","title":"sharpness","type":"topic","navigatorTitle":[{"text":"sharpness","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/sharpness","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/hash":{"url":"\/documentation\/dotpalmcore\/imageparameters\/hash","abstract":[],"kind":"symbol","type":"topic","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://com.innovatrics.dot.palm.core/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH"},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmDetector/Palm":{"navigatorTitle":[{"kind":"identifier","text":"Palm"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector\/Palm","title":"PalmDetector.Palm","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}]},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.palm.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/RectangleDouble":{"title":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/RectangleDouble","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/brightness":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"brightness","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"title":"brightness","type":"topic","url":"\/documentation\/dotpalmcore\/imageparameters\/brightness","abstract":[{"type":"text","text":"Overall brightness of the palm in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness."}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/brightness"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/description":{"abstract":[],"url":"\/documentation\/dotpalmcore\/imageparameters\/description","kind":"symbol","title":"description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/description","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/PalmDetector":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmDetector","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters","url":"\/documentation\/dotpalmcore\/imageparameters","title":"ImageParameters","type":"topic","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}]},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ImageParameters/isEqual(_:)":{"title":"isEqual(_:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotpalmcore\/imageparameters\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/isEqual(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPImageParameters","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPImageParameters","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/brightness","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/description","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/hash","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/sharpness"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/init(sharpness:brightness:)","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ImageParameters\/isEqual(_:)"],"title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/RectangleDouble"],"generated":true,"title":"Palm detection output"}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTPImageParameters"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"initWithSharpness:brightness:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1init(sharpness:brightness:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1init(sharpness:brightness:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSharpness:brightness:","kind":"identifier"}],"op":"replace"},{"value":"sharpness","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1sharpness\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1sharpness\/fragments","value":[{"kind":"identifier","text":"sharpness"}]},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1RectangleDouble\/fragments"},{"op":"replace","value":"brightness","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1brightness\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1brightness\/fragments","value":[{"kind":"identifier","text":"brightness"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1description\/title","value":"description","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1description\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace"},{"value":"DOTPImageParameters","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters\/fragments","value":[{"text":"DOTPImageParameters","kind":"identifier"}]},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ImageParameters~1isEqual(_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}