{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/init(detectionAreaImageSize:palm:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/palm"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/isEqual(_:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"seeAlsoSections":[{"title":"Palm auto capture process","generated":true,"anchor":"Palm-auto-capture-process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"},"metadata":{"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"title":"PalmAutoCaptureFrameParameters","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","role":"symbol","roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureFrameParameters) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparameters"]}],"references":{"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"title":"PalmAutoCaptureDetection","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"symbol","abstract":[{"text":"The result of processing video frame during the palm auto capture process.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the palm in the image."}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","url":"\/documentation\/dotpalmcore\/detectionposition","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/palm":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier","text":"PalmDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Palm"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/palm","title":"palm","abstract":[{"type":"text","text":"Detected palm, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the palm was not detected in the image."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/palm","navigatorTitle":[{"kind":"identifier","text":"palm"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"navigatorTitle":[{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","kind":"symbol","title":"PalmAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","role":"symbol"},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/hash":{"title":"hash","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/hash","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/hash","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/isEqual(_:)":{"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/isEqual(_:)","abstract":[],"title":"isEqual(_:)","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/isequal(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/detectionAreaImageSize":{"navigatorTitle":[{"text":"detectionAreaImageSize","kind":"identifier"}],"title":"detectionAreaImageSize","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/detectionareaimagesize","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionAreaImageSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/detectionAreaImageSize","abstract":[{"type":"text","text":"Image size of the detection area."}]},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/description":{"kind":"symbol","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"role":"symbol","title":"description","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/description"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters/init(detectionAreaImageSize:palm:)":{"type":"topic","title":"init(detectionAreaImageSize:palm:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionAreaImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?)","kind":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters\/init(detectionareaimagesize:palm:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/init(detectionAreaImageSize:palm:)","abstract":[],"navigatorTitle":[{"text":"initWithDetectionAreaImageSize:palm:","kind":"identifier"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","title":"PalmAutoCaptureResult"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"DOTPPalmAutoCaptureFrameParameters","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/detectionAreaImageSize","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/palm"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/init(detectionAreaImageSize:palm:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"anchor":"Palm-auto-capture-process","title":"Palm auto capture process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],"generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPalmAutoCaptureDetection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1palm\/title","value":"palm"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1palm\/fragments","value":[{"kind":"identifier","text":"palm"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","value":"DOTPPalmAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1isEqual(_:)\/fragments"},{"op":"replace","value":"detectionAreaImageSize","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1detectionAreaImageSize\/title"},{"op":"replace","value":[{"kind":"identifier","text":"detectionAreaImageSize"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1detectionAreaImageSize\/fragments"},{"op":"replace","value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1description\/title"},{"op":"replace","value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1description\/fragments"},{"op":"replace","value":"initWithDetectionAreaImageSize:palm:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1init(detectionAreaImageSize:palm:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionAreaImageSize:palm:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters~1init(detectionAreaImageSize:palm:)\/fragments"},{"op":"replace","value":"DOTPPalmAutoCaptureResult","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle"}]}]}