{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"PalmAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}],"symbolKind":"protocol","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureDetectionValidator","roleHeading":"Protocol","role":"symbol"},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/validate(palmAutoCaptureFrameParameters:)"]}],"seeAlsoSections":[{"title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTPPalmAutoCaptureDetectionValidator) "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"],"type":"conformingTypes","title":"Conforming Types"}],"abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"title":"BrightnessTooHighValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","title":"SizeTooLargeValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator/dependencyIdentifiers":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/dependencyidentifiers","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/dependencyIdentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"required":true,"title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","type":"topic","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","kind":"symbol","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected palm."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator/identifier":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/identifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"required":true,"title":"identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"title":"TemplateExtractionQualityTooLowValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","type":"topic","url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Validate minimum template extraction quality of the detected palm."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","title":"BrightnessTooLowValidator","type":"topic","kind":"symbol","abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","role":"symbol","title":"PalmNotDetectedValidator","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmNotDetectedValidator"}],"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator/validate(palmAutoCaptureFrameParameters:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/validate(palmAutoCaptureFrameParameters:)","type":"topic","navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator\/validate(palmautocaptureframeparameters:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"kind":"symbol","title":"validate(palmAutoCaptureFrameParameters:)","required":true,"abstract":[{"type":"text","text":"Validate current frame parameters."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","title":"PalmAutoCaptureDetectionValidator","type":"topic","kind":"symbol","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"title":"SizeTooSmallValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"type":"topic","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTPPalmAutoCaptureDetectionValidator"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetectionValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/identifier"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator\/validate(palmAutoCaptureFrameParameters:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"],"type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","value":[{"generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators"}],"op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"value":"DOTPBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}]},{"value":"DOTPSizeTooLargeValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","value":"DOTPSharpnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1identifier\/title","op":"replace","value":"identifier"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1identifier\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title","value":"DOTPTemplateExtractionQualityTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments","value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}]},{"value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","op":"replace","value":"DOTPPalmNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}]},{"op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","value":"DOTPPalmAutoCaptureDetectionValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","value":"DOTPPalmOutOfBoundsValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}]}]}]}