{"kind":"symbol","metadata":{"title":"PalmAutoCaptureFrameParametersValidator","symbolKind":"protocol","externalID":"c:@M@DotPalmCore@objc(pl)DOTPPalmAutoCaptureFrameParametersValidator","modules":[{"name":"DotPalmCore"}],"roleHeading":"Protocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureFrameParametersValidator) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParametersValidator"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator"]}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/identifier"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/validate(palmAutoCaptureFrameParameters:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"seeAlsoSections":[{"anchor":"Validators","title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"generated":true}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"role":"symbol","kind":"symbol","type":"topic","title":"SizeTooLargeValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"title":"PalmAutoCaptureFrameParametersValidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","title":"SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"kind":"symbol","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","type":"topic","title":"PalmAutoCaptureController","kind":"symbol","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmNotDetectedValidator"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","navigatorTitle":[{"kind":"identifier","text":"PalmNotDetectedValidator"}],"title":"PalmNotDetectedValidator","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","kind":"symbol","role":"symbol","abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator/identifier":{"role":"symbol","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"title":"identifier","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/identifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/identifier","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"required":true},"doc://DotPalmCore/documentation/DotPalmCore/TemplateExtractionQualityTooLowValidator":{"url":"\/documentation\/dotpalmcore\/templateextractionqualitytoolowvalidator","abstract":[{"text":"Validate minimum template extraction quality of the detected palm.","type":"text"}],"title":"TemplateExtractionQualityTooLowValidator","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator","navigatorTitle":[{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateExtractionQualityTooLowValidator","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator/validate(palmAutoCaptureFrameParameters:)":{"title":"validate(palmAutoCaptureFrameParameters:)","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/validate(palmautocaptureframeparameters:)","kind":"symbol","type":"topic","required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"text":"Validate current frame parameters.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"title":"BrightnessTooLowValidator","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","type":"topic","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"title":"BrightnessTooHighValidator"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"title":"SharpnessTooLowValidator","kind":"symbol","abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator/dependencyIdentifiers":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"type":"topic","required":true,"url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/dependencyIdentifiers","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPPalmAutoCaptureFrameParametersValidator","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/identifier"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator\/validate(palmAutoCaptureFrameParameters:)"],"anchor":"Instance-Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"value":[{"type":"conformingTypes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/TemplateExtractionQualityTooLowValidator"],"kind":"relationships","title":"Conforming Types"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"generated":true,"title":"Validators","anchor":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPSizeTooLargeValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title","op":"replace","value":"DOTPPalmAutoCaptureFrameParametersValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"},{"value":"DOTPPalmNotDetectedValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title"},{"value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle"},{"value":"DOTPPalmOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1identifier\/title"},{"value":[{"text":"identifier","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1identifier\/fragments"},{"value":"DOTPTemplateExtractionQualityTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/title"},{"value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/fragments"},{"value":[{"text":"DOTPTemplateExtractionQualityTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1TemplateExtractionQualityTooLowValidator\/navigatorTitle"},{"value":"validateWithPalmAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments"},{"value":"DOTPBrightnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title"},{"value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/navigatorTitle"},{"value":"DOTPBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/navigatorTitle"},{"value":"DOTPSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title"},{"value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/title"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator~1dependencyIdentifiers\/fragments"}]}]}