{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPPalmAutoCapturePhase) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped"],"title":"Classes","generated":true,"anchor":"Classes"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/candidateSelection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/preCandidateSelection"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},"kind":"symbol","abstract":[{"type":"text","text":"Phase of the palm auto capture process."}],"metadata":{"symbolKind":"enum","externalID":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCapturePhase"}],"roleHeading":"Enumeration","role":"symbol","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCapturePhase"}],"title":"PalmAutoCapturePhase"},"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/s12CaseIterableP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/candidateSelection":{"navigatorTitle":[{"text":"DOTPPalmAutoCapturePhaseCandidateSelection","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/candidateSelection","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/candidateselection","type":"topic","abstract":[{"text":"Candidate selection is running.","type":"text"}],"title":"PalmAutoCapturePhase.candidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/init(rawValue:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ"},"doc://DotPalmCore/s12CaseIterableP":{"identifier":"doc:\/\/DotPalmCore\/s12CaseIterableP","type":"unresolvable","title":"Swift.CaseIterable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","type":"topic","title":"PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Wrapped":{"type":"topic","title":"PalmAutoCapturePhase.Wrapped","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Wrapped","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/wrapped","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/preCandidateSelection":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/precandidateselection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/preCandidateSelection","kind":"symbol","title":"PalmAutoCapturePhase.preCandidateSelection","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhasePreCandidateSelection"}],"abstract":[{"type":"text","text":"Pre-candidate selection is running."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/Equatable-Implementations":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/equatable-implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/Equatable-Implementations","abstract":[],"type":"topic","title":"Equatable Implementations","role":"collectionGroup","kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/description":{"title":"description","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SY"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/RawRepresentable-Implementations":{"kind":"article","abstract":[],"role":"collectionGroup","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/RawRepresentable-Implementations"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DOTPPalmAutoCapturePhase"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/candidateSelection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/preCandidateSelection"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1candidateSelection\/title","op":"replace","value":"DOTPPalmAutoCapturePhaseCandidateSelection"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1candidateSelection\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhaseCandidateSelection"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace","value":"DOTPPalmAutoCapturePhase"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1preCandidateSelection\/title","op":"replace","value":"DOTPPalmAutoCapturePhasePreCandidateSelection"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1preCandidateSelection\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCapturePhasePreCandidateSelection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}