{"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"kind":"symbol","metadata":{"symbolKind":"class","roleHeading":"Class","title":"PalmAutoCaptureQualityAttributeThresholds","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","modules":[{"name":"DotPalmCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureQualityAttributeThresholds) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets"],"anchor":"Classes","title":"Classes","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/brightnessInterval","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minSharpness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minTemplateExtractionQuality","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/sizeInterval"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/minTemplateExtractionQuality":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minTemplateExtractionQuality","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/mintemplateextractionquality","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minTemplateExtractionQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"minTemplateExtractionQuality","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Minimal valid template extraction quality of the detected palm.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low template extraction quality.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high template extraction quality.","type":"text"}],"title":"minTemplateExtractionQuality"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/description","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/description","title":"description","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/hash":{"type":"topic","abstract":[],"title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/hash","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/isEqual(_:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/isequal(_:)","title":"isEqual(_:)","abstract":[]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Builder":{"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Builder"}],"title":"PalmAutoCaptureQualityAttributeThresholds.Builder","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Builder","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/builder"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/brightnessInterval":{"title":"brightnessInterval","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightnessInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/brightnessInterval","navigatorTitle":[{"kind":"identifier","text":"brightnessInterval"}],"abstract":[{"type":"text","text":"Valid interval of brightness of the detected palm."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low brightness."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents high brightness."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/brightnessinterval"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"title":"PalmAutoCaptureQualityAttributeThresholds"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/minConfidence":{"title":"minConfidence","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minConfidence"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minConfidence","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/minconfidence","role":"symbol","type":"topic","abstract":[{"text":"Minimal valid confidence of the detected palm.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low confidence.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high confidence.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minConfidence"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/minSharpness":{"abstract":[{"type":"text","text":"Minimal valid sharpness of the detected palm."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents blurry palm."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents sharp palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minSharpness","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minSharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/minsharpness","title":"minSharpness","navigatorTitle":[{"kind":"identifier","text":"minSharpness"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/Presets":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/presets","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Presets"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Presets"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/Presets","abstract":[{"type":"text","text":"Presets for the quality attributes thresholds of the palm auto capture result."}],"title":"PalmAutoCaptureQualityAttributeThresholds.Presets"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds/sizeInterval":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds\/sizeinterval","abstract":[{"text":"Valid palm size interval. Values greater than or equal to ","type":"text"},{"code":"0.0","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"sizeInterval"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"sizeInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/sizeInterval","title":"sizeInterval","type":"topic"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPPalmAutoCaptureQualityAttributeThresholds","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureQualityAttributeThresholds"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/brightnessInterval","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minConfidence","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minSharpness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/minTemplateExtractionQuality","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/sizeInterval"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"path":"\/relationshipsSections","op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"minTemplateExtractionQuality","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minTemplateExtractionQuality\/title","op":"replace"},{"value":[{"text":"minTemplateExtractionQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minTemplateExtractionQuality\/fragments","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1description\/fragments","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1hash\/title","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1hash\/fragments","op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1isEqual(_:)\/fragments","op":"replace"},{"value":"brightnessInterval","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1brightnessInterval\/title","op":"replace"},{"value":[{"kind":"identifier","text":"brightnessInterval"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1brightnessInterval\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"},{"value":"minConfidence","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minConfidence\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minConfidence"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minConfidence\/fragments","op":"replace"},{"value":"minSharpness","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minSharpness\/title","op":"replace"},{"value":[{"kind":"identifier","text":"minSharpness"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1minSharpness\/fragments","op":"replace"},{"value":"sizeInterval","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1sizeInterval\/title","op":"replace"},{"value":[{"text":"sizeInterval","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds~1sizeInterval\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}