{"abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"sections":[],"topicSections":[{"generated":true,"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Initializing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocaptureuistate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"type":"inheritedBy","kind":"relationships","title":"Inherited By","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Initializing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","interfaceLanguage":"swift"},"metadata":{"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","title":"PalmAutoCaptureUiState"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureUiState) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateIdle":{"title":"DOTPPalmAutoCaptureUiStateIdle","kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateIdle"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateidle","type":"topic","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Running":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Running","kind":"identifier"}],"navigatorTitle":[{"text":"Running","kind":"identifier"}],"title":"PalmAutoCaptureUiState.Running","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Running","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/running","abstract":[{"text":"Running state.","type":"text"}]},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateInitializing":{"role":"symbol","title":"DOTPPalmAutoCaptureUiStateInitializing","type":"topic","abstract":[{"text":"Initializing state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active right after the component is created for a short period of time.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistateinitializing","fragments":[{"text":"DOTPPalmAutoCaptureUiStateInitializing","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateInitializing"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning":{"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","title":"DOTPPalmAutoCaptureUiStateRunning","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"text":" method is called and before the process finishes.","type":"text"}],"role":"symbol","kind":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureUiStateRunning","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiState/init":{"role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistate\/init","title":"init","type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiState\/init","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Idle":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"navigatorTitle":[{"text":"Idle","kind":"identifier"}],"title":"PalmAutoCaptureUiState.Idle","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Idle","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/idle","abstract":[{"type":"text","text":"Idle state."}]},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"title":"PalmAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureUiState"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState/Initializing":{"title":"PalmAutoCaptureUiState.Initializing","role":"symbol","abstract":[{"text":"Initializing state.","type":"text"}],"navigatorTitle":[{"text":"Initializing","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate\/initializing","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState\/Initializing","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Initializing","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPPalmAutoCaptureUiState","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiState\/init"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateIdle","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateInitializing","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","value":"DOTPPalmAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}