{"kind":"symbol","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmNotDetectedValidator) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator"},"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init(minConfidenceThreshold:)"],"title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/minConfidenceThreshold"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"title":"Type Properties","generated":true,"anchor":"Type-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/defaultMinConfidenceThreshold"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmNotDetectedValidator"}],"title":"PalmNotDetectedValidator","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmNotDetectedValidator","modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"role":"symbol"},"seeAlsoSections":[{"anchor":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators","generated":true}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmnotdetectedvalidator"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate minimum sharpness of the detected palm."}],"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/init(minConfidenceThreshold:)":{"kind":"symbol","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/init(minconfidencethreshold:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init(minConfidenceThreshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(minConfidenceThreshold:)","navigatorTitle":[{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","title":"SizeTooSmallValidator","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"kind":"symbol","type":"topic"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/minConfidenceThreshold":{"kind":"symbol","type":"topic","abstract":[{"text":"Current minimal accepted confidence.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/minConfidenceThreshold","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/minconfidencethreshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"title":"minConfidenceThreshold","navigatorTitle":[{"kind":"identifier","text":"minConfidenceThreshold"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/init()":{"type":"topic","kind":"symbol","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/init()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/defaultMinConfidenceThreshold":{"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/defaultminconfidencethreshold","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMinConfidenceThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/defaultMinConfidenceThreshold","abstract":[{"type":"text","text":"Default threshold."}],"role":"symbol","kind":"symbol","title":"defaultMinConfidenceThreshold"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"title":"PalmNotDetectedValidator","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/identifier":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/identifier","title":"identifier","kind":"symbol","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/identifier"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"role":"symbol","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"navigatorTitle":[{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"type":"topic","title":"PalmOutOfBoundsValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/validate(palmAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/validate(palmautocaptureframeparameters:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate confidence of the detected palm."}],"role":"symbol","kind":"symbol","title":"validate(palmAutoCaptureFrameParameters:)"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"type":"topic","title":"BrightnessTooHighValidator","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","role":"symbol"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator/dependencyIdentifiers":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator\/dependencyidentifiers"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"title":"PalmAutoCaptureFrameParametersValidator","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"type":"topic","abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"title":"BrightnessTooLowValidator","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPPalmNotDetectedValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/minConfidenceThreshold"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/init(minConfidenceThreshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"anchor":"Type-Properties","generated":true,"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator\/defaultMinConfidenceThreshold"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"anchor":"Validators","generated":true,"title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","value":"DOTPSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}]},{"value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle"},{"op":"replace","value":"initWithMinConfidenceThreshold:error:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1init(minConfidenceThreshold:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1init(minConfidenceThreshold:)\/fragments"},{"op":"replace","value":"DOTPSizeTooSmallValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title"},{"value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments"},{"value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle"},{"value":"minConfidenceThreshold","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1minConfidenceThreshold\/title"},{"value":[{"kind":"identifier","text":"minConfidenceThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1minConfidenceThreshold\/fragments"},{"value":"init","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1init()\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1init()\/fragments"},{"op":"replace","value":"defaultMinConfidenceThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1defaultMinConfidenceThreshold\/title"},{"op":"replace","value":[{"kind":"identifier","text":"defaultMinConfidenceThreshold"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments"},{"op":"replace","value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1identifier\/title","value":"identifier"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"op":"replace","value":"DOTPPalmOutOfBoundsValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}]},{"value":"validateWithPalmAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments"},{"value":"DOTPSizeTooLargeValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle"},{"value":"DOTPBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/navigatorTitle"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1dependencyIdentifiers\/title"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator~1dependencyIdentifiers\/fragments"},{"value":"DOTPPalmAutoCaptureFrameParametersValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle"},{"value":"DOTPBrightnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}