{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTPPalmOutOfBoundsValidator) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmoutofboundsvalidator"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"generated":true,"title":"Validators"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"],"title":"Type Properties"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator"},"metadata":{"symbolKind":"class","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmOutOfBoundsValidator","roleHeading":"Class","title":"PalmOutOfBoundsValidator","modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"title":"BrightnessTooLowValidator","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected palm."}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"type":"topic","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","kind":"symbol","role":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected palm."}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"kind":"symbol"},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/defaultMinCornerDistanceToImageShorterSideRatioThreshold":{"title":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"symbol","abstract":[{"type":"text","text":"Default threshold."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold","type":"topic","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"navigatorTitle":[{"kind":"identifier","text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/defaultmincornerdistancetoimageshortersideratiothreshold"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/minCornerDistanceToImageShorterSideRatioThreshold":{"abstract":[{"type":"text","text":"Current minimal distance between detected palm corner and image edge to image shorter side ratio threshold."}],"kind":"symbol","title":"minCornerDistanceToImageShorterSideRatioThreshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/mincornerdistancetoimageshortersideratiothreshold"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/validate(palmAutoCaptureFrameParameters:)":{"title":"validate(palmAutoCaptureFrameParameters:)","kind":"symbol","abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/validate(palmAutoCaptureFrameParameters:)","type":"topic","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/validate(palmautocaptureframeparameters:)"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"type":"topic","title":"PalmNotDetectedValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"title":"BrightnessTooHighValidator","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected palm."}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/identifier":{"abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","title":"identifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/identifier","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/identifier"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"title":"PalmOutOfBoundsValidator","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.13.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"title":"PalmAutoCaptureDetectionValidator","role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/dependencyIdentifiers","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/dependencyidentifiers"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"type":"topic","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol","role":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/init()":{"title":"init()","kind":"symbol","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init()","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/init()"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator/init(minCornerDistanceToImageShorterSideRatioThreshold:)":{"title":"init(minCornerDistanceToImageShorterSideRatioThreshold:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"minCornerDistanceToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"}],"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator\/init(mincornerdistancetoimageshortersideratiothreshold:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTPPalmOutOfBoundsValidator","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/minCornerDistanceToImageShorterSideRatioThreshold"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/init(minCornerDistanceToImageShorterSideRatioThreshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/validate(palmAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator\/defaultMinCornerDistanceToImageShorterSideRatioThreshold"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"],"kind":"relationships","title":"Conforms To"}]},{"op":"replace","value":[{"title":"Validators","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace","value":"DOTPBrightnessTooLowValidator"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace","value":"DOTPSizeTooSmallValidator"},{"value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments"},{"value":"DOTPSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace","value":"DOTPSizeTooLargeValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/title","value":"defaultMinCornerDistanceToImageShorterSideRatioThreshold"},{"value":[{"text":"defaultMinCornerDistanceToImageShorterSideRatioThreshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1defaultMinCornerDistanceToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"minCornerDistanceToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/title"},{"value":[{"kind":"identifier","text":"minCornerDistanceToImageShorterSideRatioThreshold"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1minCornerDistanceToImageShorterSideRatioThreshold\/fragments"},{"value":"validateWithPalmAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},{"value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","op":"replace","value":"DOTPBrightnessTooHighValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"},{"value":"identifier","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1identifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","value":"DOTPPalmOutOfBoundsValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","value":"DOTPPalmAutoCaptureDetectionValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureDetectionValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init()\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/title","value":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator~1init(minCornerDistanceToImageShorterSideRatioThreshold:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinCornerDistanceToImageShorterSideRatioThreshold:error:"}],"op":"replace"}]}]}