{"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"],"generated":true,"title":"Palm auto capture process","anchor":"Palm-auto-capture-process"}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/init(image:palm:content:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/content","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/image","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/palm"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmAutoCaptureResult) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocaptureresult"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"],["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","symbolKind":"class","roleHeading":"Class","role":"symbol","title":"PalmAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"modules":[{"name":"DotPalmCore"}]},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"title":"PalmAutoCaptureDetection","navigatorTitle":[{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"symbol","abstract":[{"text":"The result of processing video frame during the palm auto capture process.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureDetection","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/init(image:palm:content:)":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/init(image:palm:content:)","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/init(image:palm:content:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","text":"PalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"type":"topic","title":"init(image:palm:content:)","navigatorTitle":[{"kind":"identifier","text":"initWithImage:palm:content:"}],"abstract":[]},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"navigatorTitle":[{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","kind":"symbol","title":"PalmAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/content":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/content","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/content","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"type":"topic","title":"content","navigatorTitle":[{"text":"content","kind":"identifier"}],"abstract":[{"text":"Binary content for server-side evaluation.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/image":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/image","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"title":"image","navigatorTitle":[{"text":"image","kind":"identifier"}],"abstract":[{"text":"Detection image.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/image"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/description":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/description","url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/description","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","title":"PalmAutoCaptureResult"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"abstract":[{"type":"text","text":"Position of the palm in the image."}],"navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","url":"\/documentation\/dotpalmcore\/detectionposition","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult/palm":{"url":"\/documentation\/dotpalmcore\/palmautocaptureresult\/palm","abstract":[{"text":"The result of the palm detection. Might be ","type":"text"},{"code":"nil","type":"codeVoice"},{"text":" only if ","type":"text"},{"code":"PalmAutoCaptureViewController\/requestCapture()","type":"codeVoice"},{"text":" was used to get the result.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"palm"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/palm","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"type":"topic","title":"palm"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"title":"PalmAutoCaptureViewController","role":"symbol","abstract":[{"type":"text","text":"UI Palm Auto Capture component."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","type":"topic","kind":"symbol"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTPPalmAutoCaptureResult","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/content","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/image","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/palm"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult\/init(image:palm:content:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}],"op":"replace"},{"path":"\/seeAlsoSections","value":[{"anchor":"Palm-auto-capture-process","generated":true,"title":"Palm auto capture process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters"]}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","value":"DOTPPalmAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1init(image:palm:content:)\/title","value":"initWithImage:palm:content:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1init(image:palm:content:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithImage:palm:content:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title","value":"DOTPPalmAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParameters"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1content\/title","value":"content","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1content\/fragments","value":[{"text":"content","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1image\/title","value":"image","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1image\/fragments","value":[{"text":"image","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","value":"DOTPPalmAutoCaptureResult","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title","value":"DOTPDetectionPosition","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1palm\/title","value":"palm","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult~1palm\/fragments","value":[{"kind":"identifier","text":"palm"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","value":"DOTPPalmAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureViewController"}],"op":"replace"}]}]}