{"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init(threshold:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/threshold"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/defaultThreshold"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSharpnessTooLowValidator","title":"SharpnessTooLowValidator","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"symbolKind":"class"},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPSharpnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"content","content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"To use this validator also following validators must be applied: ","type":"text"},{"code":"PalmOutOfBoundsValidator","type":"codeVoice"},{"text":".","type":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sharpnesstoolowvalidator"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators","anchor":"Validators","generated":true}],"references":{"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/defaultThreshold":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","abstract":[{"text":"Default threshold.","type":"text"}],"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/defaultthreshold","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/defaultThreshold","title":"defaultThreshold","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"abstract":[{"type":"text","text":"Validate maximum brightness of the detected palm."}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"title":"PalmOutOfBoundsValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmOutOfBoundsValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/identifier":{"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/identifier","title":"identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"kind":"symbol","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"title":"SizeTooLargeValidator","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected palm."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"title":"SharpnessTooLowValidator","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/init(threshold:)":{"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init(threshold:)","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/init(threshold:)","kind":"symbol","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"title":"init(threshold:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/dependencyIdentifiers":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/dependencyIdentifiers"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/threshold":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/threshold","abstract":[{"text":"Current minimal accepted sharpness.","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"threshold","kind":"symbol","navigatorTitle":[{"text":"threshold","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/threshold"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init()","kind":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/init()","title":"init()","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"kind":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected palm."}],"type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"type":"topic","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}],"title":"SizeTooSmallValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"role":"symbol","title":"PalmNotDetectedValidator","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","type":"topic","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator/validate(palmAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator\/validate(palmautocaptureframeparameters:)","title":"validate(palmAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate sharpness of the detected palm."}],"role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}]},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","navigatorTitle":[{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"title":"PalmAutoCaptureFrameParametersValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPSharpnessTooLowValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/threshold"],"generated":true,"title":"Instance Properties"},{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/init(threshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)"],"generated":true,"title":"Instance Methods"},{"anchor":"Type-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator\/defaultThreshold"],"generated":true,"title":"Type Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"],"title":"Conforms To"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"anchor":"Validators","title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPSharpnessTooLowValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"value":[{"kind":"identifier","text":"defaultThreshold"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1defaultThreshold\/fragments","op":"replace"},{"value":"DOTPBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","op":"replace"},{"value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/navigatorTitle","op":"replace"},{"value":"DOTPPalmOutOfBoundsValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1identifier\/title","op":"replace","value":"identifier"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1identifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace","value":"DOTPSizeTooLargeValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","op":"replace","value":"DOTPSharpnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init(threshold:)\/title","op":"replace","value":"initWithThreshold:error:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init(threshold:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithThreshold:error:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1threshold\/title","op":"replace","value":"threshold"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1threshold\/fragments","op":"replace","value":[{"kind":"identifier","text":"threshold"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace","value":"DOTPBrightnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","op":"replace","value":"DOTPPalmNotDetectedValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1validate(palmAutoCaptureFrameParameters:)\/title","op":"replace","value":"validateWithPalmAutoCaptureFrameParameters:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title","op":"replace","value":"DOTPPalmAutoCaptureFrameParametersValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureFrameParametersValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}]}]}]}