{"abstract":[{"text":"Validate if a value belongs to an interval.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.palm.core\/SQ","doc:\/\/com.innovatrics.dot.palm.core\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/validationfloat"]},{"paths":["\/documentation\/dotpalmcore\/validationfloat"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat\/validate(value:interval:)"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTValidationFloat) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationFloat"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore"]]},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat","interfaceLanguage":"swift"},"metadata":{"symbolKind":"class","navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTValidationFloat","title":"ValidationFloat","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationFloat","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}]},"doc://com.innovatrics.dot.palm.core/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.palm.core/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationFloat/validate(value:interval:)":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat\/validate(value:interval:)","title":"validate(value:interval:)","role":"symbol","type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalFloat","text":"IntervalFloat"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"url":"\/documentation\/dotpalmcore\/validationfloat\/validate(value:interval:)"},"doc://com.innovatrics.dot.palm.core/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.palm.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.palm.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.palm.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationFloat":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationFloat","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"title":"ValidationFloat","type":"topic","abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"url":"\/documentation\/dotpalmcore\/validationfloat","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat"},"doc://com.innovatrics.dot.palm.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTValidationFloat","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTValidationFloat"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTValidationFloat"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat\/validate(value:interval:)"]}],"path":"\/topicSections","op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.palm.core\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTValidationFloat","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat~1validate(value:interval:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat\/title","op":"replace","value":"DOTValidationFloat"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat\/fragments","op":"replace","value":[{"text":"DOTValidationFloat","kind":"identifier"}]}]}]}