{"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"detection","externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)detection","symbolKind":"property","fragments":[{"text":"detection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"detection"}]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/detection"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/detection"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules/detection":{"kind":"symbol","abstract":[],"fragments":[{"text":"detection","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/detection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/detection","role":"symbol","title":"detection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules","role":"symbol","title":"DotFingersLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersDetectionModuleConfiguration":{"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}]}]}