{"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"transformation"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","interfaceLanguage":"occ"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(im)initWithDetection:transformation:","symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:transformation:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"title":"initWithDetection:transformation:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"text":"initWithDetection:transformation:","kind":"identifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersTransformationModuleConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules/initWithDetection:transformation:":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:transformation:"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:transformation:"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/initwithdetection:transformation:","abstract":[],"kind":"symbol","title":"initWithDetection:transformation:","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/initWithDetection:transformation:","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules","role":"symbol","title":"DotFingersLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersDetectionModuleConfiguration":{"role":"symbol","navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersDetectionModuleConfiguration","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}]}]}