{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"transformation","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/transformation","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/transformation"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"transformation","roleHeading":"Instance Property","fragments":[{"text":"transformation","kind":"identifier"}],"navigatorTitle":[{"text":"transformation","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules(py)transformation","role":"symbol","symbolKind":"property"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules/transformation":{"title":"transformation","kind":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules\/transformation","url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules\/transformation","role":"symbol","fragments":[{"text":"transformation","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersTransformationModuleConfiguration":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotpalmcore\/dotfingerstransformationmoduleconfiguration","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"kind":"symbol","title":"DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersTransformationModuleConfiguration","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersLibraryConfigurationModules":{"kind":"symbol","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotfingerslibraryconfigurationmodules","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersLibraryConfigurationModules","role":"symbol","title":"DotFingersLibraryConfigurationModules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}