{"metadata":{"symbolKind":"init","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithLines:td3:","kind":"identifier"}],"title":"init(lines:td3:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"lines","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"], ","kind":"text"},{"text":"td3","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone"},{"text":")","kind":"text"}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone(im)initWithLines:td3:","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td3"},{"kind":"text","text":": "},{"text":"Td3MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone"},{"text":")","kind":"text"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td3:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td3:)"]},{"paths":["\/documentation\/dotnfc\/machinereadablezone\/init(lines:td3:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"title":"Td3MachineReadableZone","url":"\/documentation\/dotnfc\/td3machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone":{"url":"\/documentation\/dotnfc\/machinereadablezone","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MachineReadableZone","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone/init(lines:td3:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"lines"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"td3"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Td3MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone"},{"text":")","kind":"text"}],"title":"init(lines:td3:)","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/init(lines:td3:)","url":"\/documentation\/dotnfc\/machinereadablezone\/init(lines:td3:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithLines:td3:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithLines:td3:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLines:td3:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithLines:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"lines","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td3:"},{"kind":"text","text":"("},{"text":"DOTTd3MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone"},{"text":" *) ","kind":"text"},{"text":"td3","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td3:)\/title","value":"initWithLines:td3:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1init(lines:td3:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLines:td3:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}