{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadow","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Face image shadow."}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shadow"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"text":"?","kind":"text"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality(py)shadow","navigatorTitle":[{"text":"shadow","kind":"identifier"}],"roleHeading":"Instance Property","title":"shadow","role":"symbol","modules":[{"name":"DotFaceCore"}],"symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/shadow","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequality\/shadow"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequality\/shadow"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/shadow":{"title":"shadow","navigatorTitle":[{"kind":"identifier","text":"shadow"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shadow","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"text":"?","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/shadow","url":"\/documentation\/dotfacecore\/faceimagequality\/shadow","abstract":[{"text":"Face image shadow.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","title":"FaceAttribute","role":"symbol","type":"topic","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceattribute"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","kind":"symbol","title":"FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"shadow","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"shadow","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFFaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"shadow"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"shadow","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1shadow\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1shadow\/fragments","op":"replace","value":[{"text":"shadow","kind":"identifier"}]},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceImageQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}