{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration(im)init","title":"init","role":"symbol"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration/init":{"role":"symbol","kind":"symbol","abstract":[],"title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration\/init"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration":{"abstract":[{"text":"Face verification module.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"title":"DotFaceVerificationModuleConfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}]}]}