{"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/customstringconvertible-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/CustomStringConvertible-Implementations","interfaceLanguage":"swift"},"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error"]]},"metadata":{"role":"collectionGroup","title":"CustomStringConvertible Implementations","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/description"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error":{"abstract":[],"title":"DotFaceLibraryConfiguration.Error","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}],"title":"DotFaceLibrary","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibrary"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","url":"\/documentation\/dotfacecore\/dotfacelibrary","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/description":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/description","kind":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/description"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library will be initialized."}],"title":"DotFaceLibraryConfiguration","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","op":"replace","value":[{"text":"DotFaceLibrary","kind":"identifier"}]},{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","op":"replace"}]}]}