{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/defaults\/maxhotspotsscore"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Defaults\/maxHotspotsScore","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"maxHotspotsScore","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"s:11DotDocument0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC8DefaultsV16maxHotspotsScoreSdvpZ","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Defaults"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Defaults":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/defaults"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Defaults/maxHotspotsScore":{"role":"symbol","title":"maxHotspotsScore","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxHotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Defaults\/maxHotspotsScore","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class\/defaults\/maxhotspotsscore"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.1"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}