{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"]]},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DotFingersLibraryConfiguration(py)modules","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC"}],"title":"modules","navigatorTitle":[{"kind":"identifier","text":"modules"}]},"abstract":[{"type":"text","text":"Module configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","text":"Modules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.property"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/modules-swift.property"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/modules-swift.property":{"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}],"title":"modules","abstract":[{"text":"Module configuration.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"modules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/modules-swift.property"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfigurationModules":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfigurationmodules","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules","kind":"symbol","title":"DotFingersLibraryConfigurationModules","fragments":[{"text":"DotFingersLibraryConfigurationModules","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"abstract":[{"text":"Fingers library configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"modules","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfigurationModules","text":"DotFingersLibraryConfigurationModules"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modules"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1modules-swift.property\/title","value":"modules","op":"replace"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration~1modules-swift.property\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}