{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"]]},"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Modules"}],"title":"DotFingersLibraryConfiguration.Modules","modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"roleHeading":"Class"},"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DotFingersLibraryConfigurationModules) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class"]}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"],"title":"Initializers","anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation"],"title":"Instance Properties","anchor":"Instance-Properties"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"abstract":[{"text":"Fingers library configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","title":"detection","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?)"}],"title":"init(detection:transformation:)","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","kind":"symbol","title":"transformation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title","op":"replace","value":"DotFingersLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}