{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"faceAspects","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","text":"FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/faceaspects"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol","title":"faceAspects","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"faceAspects","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects"}],"externalID":"s:11DotFaceCore0B8DetectorC0B0C11faceAspectsAA0bF0Cvp"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/faceAspects","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face aspects."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacecore\/facedetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"type":"topic","role":"symbol","title":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"url":"\/documentation\/dotfacecore\/faceaspects","title":"FaceAspects","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/faceAspects":{"type":"topic","url":"\/documentation\/dotfacecore\/facedetector\/face\/faceaspects","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"faceAspects","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","text":"FaceAspects","kind":"typeIdentifier"}],"kind":"symbol","title":"faceAspects","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/faceAspects","abstract":[{"text":"Face aspects.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFFaceDetector","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"op":"replace","value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"op":"replace","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"}]}]}