{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"position"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","kind":"typeIdentifier","text":"DetectionPosition","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceAspects"},{"text":": ","kind":"text"},{"text":"FaceAspects","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality"},{"kind":"text","text":", "},{"text":"faceKeypoints","kind":"externalParam"},{"kind":"text","text":": "},{"text":"FaceKeypoints","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"passiveLivenessFaceAttribute","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"},{"text":"?, ","kind":"text"},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","text":"BgrRawImage"},{"text":"?, ","kind":"text"},{"text":"template","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template"},{"kind":"text","text":"?)"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:faceaspects:facequality:facekeypoints:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:)"]}],"metadata":{"roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"title":"init(confidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","externalID":"s:11DotFaceCore0B8DetectorC0B0C10confidence8position11faceAspects0G7Quality0G9Keypoints015passiveLivenessB9Attribute22fullFrontalBgrRawImage8templateAESd_0aB7Commons17DetectionPositionCAA0bH0CAA0bI0CAA0bJ0CAA0bM0CSg0aC00pqR0CSgAA8TemplateCSgtcfc","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"confidence","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition"},{"text":", ","kind":"text"},{"text":"faceAspects","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects","kind":"typeIdentifier","text":"FaceAspects"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"faceKeypoints"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints","text":"FaceKeypoints"},{"kind":"text","text":", "},{"kind":"externalParam","text":"passiveLivenessFaceAttribute"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"template"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template"},{"kind":"text","text":"?)"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DetectionPosition":{"title":"DetectionPosition","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/detectionposition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"text":"The position of the detected face in the image.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DetectionPosition"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}],"url":"\/documentation\/dotfacecore\/faceattribute","kind":"symbol","title":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAttribute"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/facequality","title":"FaceQuality","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","role":"collection","title":"DotFaceCore","url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceKeypoints":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceKeypoints"}],"navigatorTitle":[{"kind":"identifier","text":"FaceKeypoints"}],"abstract":[{"text":"Face Keypoints evaluation result. Holds evaluated facial keypoints.","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facekeypoints","title":"FaceKeypoints","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceKeypoints","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Template"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"abstract":[{"type":"text","text":"Face template."}],"type":"topic","url":"\/documentation\/dotfacecore\/template","title":"Template","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"abstract":[{"type":"text","text":"Detected face in the image."}],"title":"FaceDetector.Face","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Face"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"url":"\/documentation\/dotfacecore\/facedetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"type":"topic","role":"symbol","title":"FaceDetector","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetector"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrrawimage","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"kind":"symbol","type":"topic","title":"BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/init(confidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/facedetector\/face\/init(confidence:position:faceaspects:facequality:facekeypoints:passivelivenessfaceattribute:fullfrontalbgrrawimage:template:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"confidence"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"position","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCommons@objc(cs)DOTDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceAspects"},{"text":": ","kind":"text"},{"text":"FaceAspects","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAspects"},{"text":", ","kind":"text"},{"text":"faceQuality","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQuality","text":"FaceQuality","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"faceKeypoints","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceKeypoints","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceKeypoints"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"passiveLivenessFaceAttribute"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"kind":"text","text":"?, "},{"text":"fullFrontalBgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"template"},{"kind":"text","text":": "},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"kind":"text","text":"?)"}],"title":"init(confidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/init(confidence:position:faceAspects:faceQuality:faceKeypoints:passiveLivenessFaceAttribute:fullFrontalBgrRawImage:template:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"abstract":[{"type":"text","text":"Face aspects represent various static properties of the face."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAspects"}],"url":"\/documentation\/dotfacecore\/faceaspects","title":"FaceAspects","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DetectionPosition\/fragments","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace","value":"DOTFFaceQuality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace","value":[{"text":"DOTFFaceQuality","kind":"identifier"}]},{"value":"DOTFFaceKeypoints","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceKeypoints\/fragments","op":"replace","value":[{"text":"DOTFFaceKeypoints","kind":"identifier"}]},{"value":"DOTFTemplate","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector","op":"replace"},{"value":[{"text":"DOTFFaceDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAspects"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments"}]}]}