{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/passiveLivenessFaceAttribute"},"abstract":[{"text":"Passive liveness. This is evaluated only if it is specified in ","type":"text"},{"type":"codeVoice","code":"FaceDetectionQuery"},{"text":".","type":"text"}],"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","externalID":"s:11DotFaceCore0B8DetectorC0B0C015passiveLivenessB9AttributeAA0bG0CSgvp","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLivenessFaceAttribute","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","title":"passiveLivenessFaceAttribute"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLivenessFaceAttribute","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetector\/face\/passivelivenessfaceattribute"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face":{"navigatorTitle":[{"kind":"identifier","text":"Face"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"role":"symbol","title":"FaceDetector.Face","abstract":[{"text":"Detected face in the image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facedetector\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"url":"\/documentation\/dotfacecore\/faceattribute","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"title":"FaceAttribute","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector/Face/passiveLivenessFaceAttribute":{"url":"\/documentation\/dotfacecore\/facedetector\/face\/passivelivenessfaceattribute","abstract":[{"text":"Passive liveness. This is evaluated only if it is specified in ","type":"text"},{"code":"FaceDetectionQuery","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLivenessFaceAttribute","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"kind":"symbol","title":"passiveLivenessFaceAttribute","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector\/Face\/passiveLivenessFaceAttribute"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetector":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"kind":"symbol","title":"FaceDetector","url":"\/documentation\/dotfacecore\/facedetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetector"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle"},{"value":"DOTFFaceDetector","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetector\/navigatorTitle"}]}]}