{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","text":"DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC","text":"Result"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"ImageParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone","text":"MachineReadableZone"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(documentdetectorresult:imageparameters:traveldocumenttype:machinereadablezone:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(documentdetectorresult:imageparameters:traveldocumenttype:machinereadablezone:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?)"}],"title":"init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters(im)initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"role":"symbol","title":"DocumentAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected document and the image parameters."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParameters":{"role":"symbol","title":"ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotdocument\/imageparameters"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector/Result":{"role":"symbol","title":"DocumentDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/documentdetector\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters/init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)":{"role":"symbol","title":"init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentDetectorResult"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotDocument0B8DetectorC6ResultC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters\/init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters\/init(documentdetectorresult:imageparameters:traveldocumenttype:machinereadablezone:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentDetectorResult":{"role":"symbol","title":"DOTDDocumentDetectorResult","fragments":[{"kind":"identifier","text":"DOTDDocumentDetectorResult"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentdetectorresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"role":"symbol","title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","title":"DocumentDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"role":"symbol","title":"MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentDetectorResult:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentDetectorResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorResult","text":"DOTDDocumentDetectorResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"documentDetectorResult"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"DOTDImageParameters"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageParameters"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocumentType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper","text":"DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"travelDocumentType"},{"kind":"text","text":" "},{"kind":"identifier","text":"machineReadableZone:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone","text":"DOTDMachineReadableZone"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"machineReadableZone"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTDImageParameters"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)\/title","value":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters~1init(documentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentDetectorResult:imageParameters:travelDocumentType:machineReadableZone:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTDTravelDocumentTypeWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTDTravelDocumentTypeWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTDMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDMachineReadableZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}