{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules\/detection"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"identifier","text":"detection"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(py)detection"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules\/detection","interfaceLanguage":"occ"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules/detection":{"type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"detection"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules\/detection","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules\/detection","kind":"symbol","role":"symbol","title":"detection"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules":{"kind":"symbol","abstract":[{"type":"text","text":"Palm library module configuration."}],"fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"title":"DotPalmLibraryConfigurationModules","type":"topic","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmDetectionModuleConfiguration":{"title":"DotPalmDetectionModuleConfiguration","role":"symbol","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmDetectionModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotpalmdetectionmoduleconfiguration","abstract":[{"text":"Palm detection module configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}]}]}]}