{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/mineyesstatusscore"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"kind":"symbol","abstract":[{"text":"Minimal valid eyes status score of the detected face.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"text":"Vaue 1.0 represents face with eyes opened.","type":"text"}],"metadata":{"externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC18minEyesStatusScore0aC013WrappedDoubleCSgvp","roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","title":"minEyesStatusScore","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minEyesStatusScore","kind":"identifier"},{"kind":"text","text":": "},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"text":": ","kind":"text"},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"role":"symbol","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/minEyesStatusScore":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/mineyesstatusscore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minEyesStatusScore","abstract":[{"text":"Minimal valid eyes status score of the detected face.","type":"text"},{"type":"text","text":" "},{"text":"Value 0.0 represents face with eyes closed.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"minEyesStatusScore","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"text":"?","kind":"text"}],"kind":"symbol","title":"minEyesStatusScore","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"type":"topic","title":"FaceAutoCaptureViewController"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"WrappedDouble","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value for Objective-C support.","type":"text"}],"title":"WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","title":"FaceAutoCaptureViewController.Configuration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments"},{"value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]}]}]}