{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/loggerloglevel\/error"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/loggerloglevel\/error"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/error"},"metadata":{"externalID":"c:@M@DotCore@E@DOTLoggerLogLevel@DOTLoggerLogLevelError","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error"}],"navigatorTitle":[{"kind":"identifier","text":"DOTLoggerLogLevelError"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Case","title":"LoggerLogLevel.error"},"kind":"symbol","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel/error":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel\/error","url":"\/documentation\/dotdocument\/loggerloglevel\/error","abstract":[{"text":"Logs failed operations and other errors.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"}],"navigatorTitle":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"LoggerLogLevel.error"},"doc://DotDocument/documentation/DotDocument/LoggerLogLevel":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/LoggerLogLevel","url":"\/documentation\/dotdocument\/loggerloglevel","abstract":[{"text":"Available log levels.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"type":"topic","kind":"symbol","role":"symbol","title":"LoggerLogLevel"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTLoggerLogLevelError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1error\/title","value":"DOTLoggerLogLevelError"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel~1error\/fragments","value":[{"text":"DOTLoggerLogLevelError","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/fragments","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1LoggerLogLevel\/navigatorTitle","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]}]}]}