{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"two","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/two"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/two"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/two"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem"]]},"metadata":{"externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem@DOTMultiRangeLivenessChallengeItemTwo","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"two","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"title":"MultiRangeLivenessChallengeItem.two","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemTwo","kind":"identifier"}],"symbolKind":"case"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem/two":{"url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem\/two","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem\/two","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"two"}],"kind":"symbol","title":"MultiRangeLivenessChallengeItem.two","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemTwo"}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessChallengeItem":{"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"title":"MultiRangeLivenessChallengeItem","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessChallengeItem","type":"topic","abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenesschallengeitem","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItemTwo"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemTwo"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"DOTMultiRangeLivenessChallengeItemTwo","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1two\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItemTwo"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem~1two\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItemTwo","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/title","op":"replace","value":"DOTMultiRangeLivenessChallengeItem"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/fragments","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessChallengeItem\/navigatorTitle","op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}