{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Instance Method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration(im)init","title":"init","navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotNfc"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration\/init"]}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","url":"\/documentation\/dotnfc","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration":{"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration","title":"DotFingersDetectionModuleConfiguration","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFingersDetectionModuleConfiguration/init":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFingersDetectionModuleConfiguration\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init","url":"\/documentation\/dotnfc\/dotfingersdetectionmoduleconfiguration\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}