{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/description","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureframeparameters\/description"]}],"kind":"symbol","sections":[],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters(py)description","role":"symbol","title":"description","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.13.0","type":"text"}],"type":"topic","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"title":"FaceAutoCaptureController","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters":{"title":"FaceAutoCaptureFrameParameters","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}],"abstract":[{"type":"text","text":"Information from the detection process about the detected face."}],"navigatorTitle":[{"text":"FaceAutoCaptureFrameParameters","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParameters/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"title":"description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParameters\/description","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureframeparameters\/description","role":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}]}]},"op":"replace"},{"value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/title","value":"DOTFLFaceAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParameters"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1description\/title","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParameters~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}