{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/init(value:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"init","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"roleHeading":"Initializer","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTWrappedFloat(im)initWithValue:","title":"init(value:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceLite"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/wrappedfloat\/init(value:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/wrappedfloat\/init(value:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat":{"abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/wrappedfloat","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat","title":"WrappedFloat","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedFloat"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.0"}],"role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/WrappedFloat/init(value:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/WrappedFloat\/init(value:)","url":"\/documentation\/dotfacelite\/wrappedfloat\/init(value:)","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"role":"symbol","type":"topic","title":"init(value:)","kind":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithValue:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithValue:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:f","kind":"typeIdentifier","text":"float"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"value"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/title","value":"DOTWrappedFloat","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTWrappedFloat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1WrappedFloat~1init(value:)\/fragments"}]}]}