{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/localization\/bundle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/localization\/bundle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Type Property","role":"symbol","platforms":[{"introducedAt":"13.0","deprecated":false,"name":"iOS","unavailable":false,"beta":false}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNLocalization(cpy)bundle","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"}],"navigatorTitle":[{"kind":"identifier","text":"bundle"}],"title":"bundle","modules":[{"name":"DotNfc"}]},"abstract":[{"text":"Bundle used to localize strings.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"bundle","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/bundle","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/Localization":{"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"url":"\/documentation\/dotnfc\/localization","title":"Localization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Localization"}]},"doc://DotNfc/documentation/DotNfc/Localization/bundle":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"bundle"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/bundle","url":"\/documentation\/dotnfc\/localization\/bundle","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bundle","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle"}],"abstract":[{"type":"text","text":"Bundle used to localize strings."}],"title":"bundle","type":"topic","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"text":"version: 8.8.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"bundle"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"bundle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSBundle","text":"NSBundle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bundle"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"text":"DOTNLocalization","kind":"identifier"}],"op":"replace"},{"value":"bundle","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1bundle\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1bundle\/fragments","op":"replace","value":[{"text":"bundle","kind":"identifier"}]}]}]}