{"sections":[],"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"relatedModules":["Swift"],"name":"DotPalmCore"}],"title":"hashValue","extendedModule":"Swift","symbolKind":"property","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotPalmCore@E@DOTPHandPosition"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/hashValue","interfaceLanguage":"swift"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handposition\/hashvalue"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","title":"DotPalmCore","role":"collection","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/RawRepresentable-Implementations":{"kind":"article","url":"\/documentation\/dotpalmcore\/handposition\/rawrepresentable-implementations","title":"RawRepresentable Implementations","type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","url":"\/documentation\/dotpalmcore\/handposition","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"HandPosition"}],"navigatorTitle":[{"kind":"identifier","text":"HandPosition"}],"title":"HandPosition","abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}]},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/hashValue":{"url":"\/documentation\/dotpalmcore\/handposition\/hashvalue","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/hashValue","abstract":[],"title":"hashValue","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","value":"DOTPHandPosition"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPHandPosition"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}