{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/hash(into:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"title":"hash(into:)","modules":[{"name":"DotPalmCore","relatedModules":["Swift"]}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotPalmCore@E@DOTPHandPosition","extendedModule":"Swift","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/handposition\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"text":".","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"url":"\/documentation\/dotpalmcore\/handposition","type":"topic","abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"title":"HandPosition","role":"symbol","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/RawRepresentable-Implementations":{"url":"\/documentation\/dotpalmcore\/handposition\/rawrepresentable-implementations","title":"RawRepresentable Implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/RawRepresentable-Implementations","abstract":[],"type":"topic","kind":"article","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"title":"DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/hash(into:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"hash(into:)","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/hash(into:)","role":"symbol","url":"\/documentation\/dotpalmcore\/handposition\/hash(into:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","value":"DOTPHandPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","value":[{"kind":"identifier","text":"DOTPHandPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPHandPosition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}