{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"metadata":{"externalID":"s:11DotPalmCore12HandPositionO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer","title":"init(rawValue:)","modules":[{"name":"DotPalmCore"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handposition\/init(rawvalue:)"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/handposition","abstract":[{"type":"text","text":"Represents the position of a hand when detecting palm."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"title":"HandPosition","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/init(rawValue:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/init(rawValue:)","type":"topic","url":"\/documentation\/dotpalmcore\/handposition\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"title":"init(rawValue:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title","value":"DOTPHandPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments","value":[{"text":"DOTPHandPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle","value":[{"text":"DOTPHandPosition","kind":"identifier"}]}]}]}