{"metadata":{"externalID":"c:@M@DotPalmCore@E@DOTPHandPosition@DOTPHandPositionRight","navigatorTitle":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"symbolKind":"case","modules":[{"name":"DotPalmCore"}],"title":"HandPosition.right","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/handposition\/right"]},{"paths":["\/documentation\/dotpalmcore\/handposition\/right"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"right","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/right"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"text":"Right hand.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/HandPosition/right":{"navigatorTitle":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"kind":"symbol","title":"HandPosition.right","url":"\/documentation\/dotpalmcore\/handposition\/right","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition\/right","abstract":[{"type":"text","text":"Right hand."}],"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"right","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/HandPosition":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/HandPosition","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HandPosition","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/handposition","title":"HandPosition","role":"symbol","abstract":[{"text":"Represents the position of a hand when detecting palm.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"HandPosition","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPHandPositionRight","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPHandPositionRight","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1right\/title"},{"value":[{"text":"DOTPHandPositionRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition~1right\/fragments"},{"value":"DOTPHandPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/title"},{"value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/fragments"},{"value":[{"text":"DOTPHandPosition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1HandPosition\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}