{"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLocalization(im)init","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfllocalization\/init"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLLocalization\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLLocalization/init":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLLocalization\/init","title":"init","url":"\/documentation\/dotfacelite\/dotfllocalization\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","url":"\/documentation\/dotfacelite\/localization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"navigatorTitle":[{"text":"Localization","kind":"identifier"}],"role":"symbol","title":"Localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title","value":"DOTFLLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTFLLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/navigatorTitle","value":[{"text":"DOTFLLocalization","kind":"identifier"}]}]}]}