{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","interfaceLanguage":"occ"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/backgrounduniformity"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"backgroundUniformity","kind":"identifier"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","modules":[{"name":"DotPalmCore"}],"title":"backgroundUniformity","role":"symbol","fragments":[{"text":"backgroundUniformity","kind":"identifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","kind":"symbol","role":"symbol","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"title":"DotFaceLibraryConfigurationModules","type":"topic","abstract":[{"type":"text","text":"Face library module configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceBackgroundUniformityModuleConfiguration":{"abstract":[{"type":"text","text":"Face background uniformity module."}],"title":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceBackgroundUniformityModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacebackgrounduniformitymoduleconfiguration","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/backgroundUniformity":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/backgrounduniformity","title":"backgroundUniformity","fragments":[{"kind":"identifier","text":"backgroundUniformity"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","kind":"symbol","type":"topic","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceBackgroundUniformityModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}