{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"text":"expressionNeutral","kind":"identifier"}],"title":"expressionNeutral","role":"symbol","navigatorTitle":[{"text":"expressionNeutral","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)expressionNeutral","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/expressionneutral"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/expressionNeutral","interfaceLanguage":"occ"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceExpressionNeutralModuleConfiguration":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceExpressionNeutralModuleConfiguration","title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotpalmcore\/dotfaceexpressionneutralmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"title":"DotFaceLibraryConfigurationModules","role":"symbol","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/expressionNeutral":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/expressionneutral","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/expressionNeutral","type":"topic","fragments":[{"text":"expressionNeutral","kind":"identifier"}],"title":"expressionNeutral","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}