{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/passiveLiveness","interfaceLanguage":"occ"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/passiveliveness"]}],"sections":[],"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"passiveLiveness"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)passiveLiveness","symbolKind":"property","title":"passiveLiveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","text":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"passiveLiveness"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"DotFaceLibraryConfigurationModules","abstract":[{"type":"text","text":"Face library module configuration."}],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotFacePassiveLivenessModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"role":"symbol","abstract":[{"type":"text","text":"Face passive liveness module."}],"title":"DotFacePassiveLivenessModuleConfiguration","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacepassivelivenessmoduleconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFacePassiveLivenessModuleConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/passiveLiveness":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/passiveLiveness","role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/passiveliveness","title":"passiveLiveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/title","value":"DotFacePassiveLivenessModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"op":"replace"}]}]}