{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/verification"},"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"verification","kind":"identifier"}],"title":"verification","roleHeading":"Instance Property","navigatorTitle":[{"text":"verification","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)verification","symbolKind":"property"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/verification"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"verification"},{"kind":"text","text":";"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules":{"abstract":[{"text":"Face library module configuration.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules","title":"DotFaceLibraryConfigurationModules","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules","role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceVerificationModuleConfiguration":{"title":"DotFaceVerificationModuleConfiguration","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Face verification module.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotfaceverificationmoduleconfiguration","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceLibraryConfigurationModules/verification":{"url":"\/documentation\/dotpalmcore\/dotfacelibraryconfigurationmodules\/verification","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceLibraryConfigurationModules\/verification","title":"verification","fragments":[{"text":"verification","kind":"identifier"}],"role":"symbol","abstract":[],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/title","value":"DotFaceVerificationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/fragments","value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}