{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/common","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration"]]},"abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"codeVoice","code":".init()"},{"type":"text","text":"."}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:11DotFaceLite04BaseB25AutoCaptureViewControllerC13ConfigurationC6common0A4Core06CommonI0Cvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"common","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"CommonConfiguration","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","title":"common","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/common"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"role":"symbol","abstract":[{"type":"text","text":"UI component for capturing face images with customizable UI."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","kind":"symbol","type":"topic","title":"BaseFaceAutoCaptureViewController"},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"role":"symbol","title":"BaseFaceAutoCaptureViewController.Configuration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"kind":"symbol","type":"topic","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol","title":"CommonConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","url":"\/documentation\/dotfacelite\/commonconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController/Configuration/common":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"CommonConfiguration"}],"type":"topic","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"title":"common","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController\/Configuration\/common","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller\/configuration\/common","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DOTFLBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}