{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error"]]},"metadata":{"extendedModule":"Foundation","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"failureReason","symbolKind":"property","platforms":[{"name":"iOS","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"name":"iPadOS","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"name":"macOS","beta":false,"introducedAt":"10.10","deprecated":false,"unavailable":false},{"name":"tvOS","beta":false,"introducedAt":"9.0","deprecated":false,"unavailable":false},{"name":"watchOS","beta":false,"introducedAt":"2.0","deprecated":false,"unavailable":false}],"externalID":"s:10Foundation14LocalizedErrorPAAE13failureReasonSSSgvp::SYNTHESIZED::s:11DotDocument0B8DetectorC5ErrorO"},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/failureReason","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.failureReason","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/error\/failurereason"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error":{"title":"DocumentDetector.Error","url":"\/documentation\/dotdocument\/documentdetector\/error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"type":"topic","url":"\/documentation\/dotdocument\/documentdetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"role":"symbol","title":"DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Error/failureReason":{"url":"\/documentation\/dotdocument\/documentdetector\/error\/failurereason","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Error\/failureReason","abstract":[],"role":"symbol","title":"failureReason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace"}]}]}