{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTTravelDocumentType","text":"TravelDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentType"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper\/init(traveldocumenttype:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/traveldocumenttypewrapper\/init(traveldocumenttype:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper"]]},"sections":[],"kind":"symbol","metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTTravelDocumentTypeWrapper(im)initWithTravelDocumentType:","roleHeading":"Initializer","role":"symbol","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"travelDocumentType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTTravelDocumentType","text":"TravelDocumentType"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithTravelDocumentType:","kind":"identifier"}],"title":"init(travelDocumentType:)","modules":[{"name":"DotNfc"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/init(travelDocumentType:)","interfaceLanguage":"swift"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"text":"version: 8.4.1","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocumentTypeWrapper":{"url":"\/documentation\/dotnfc\/traveldocumenttypewrapper","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"type":"topic","navigatorTitle":[{"text":"TravelDocumentTypeWrapper","kind":"identifier"}],"title":"TravelDocumentTypeWrapper","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocumentType":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentType","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"role":"symbol","title":"TravelDocumentType","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentType"}],"url":"\/documentation\/dotnfc\/traveldocumenttype","navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocumentTypeWrapper/init(travelDocumentType:)":{"navigatorTitle":[{"text":"initWithTravelDocumentType:","kind":"identifier"}],"title":"init(travelDocumentType:)","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentTypeWrapper\/init(travelDocumentType:)","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/traveldocumenttypewrapper\/init(traveldocumenttype:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"travelDocumentType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocumentType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@E@DOTTravelDocumentType"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithTravelDocumentType:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithTravelDocumentType:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithTravelDocumentType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@E@DOTTravelDocumentType","text":"DOTTravelDocumentType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocumentType"},{"kind":"text","text":") "},{"text":"travelDocumentType","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"DOTTravelDocumentTypeWrapper","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocumentTypeWrapper"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentType\/title","value":"DOTTravelDocumentType"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentType\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/title","value":"initWithTravelDocumentType:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTravelDocumentType:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocumentTypeWrapper~1init(travelDocumentType:)\/fragments"}]}]}