{"topicSections":[{"title":"Operators","generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/!=(_:_:)"],"anchor":"Operators"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/Equatable-Implementations"},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"title":"Equatable Implementations","role":"collectionGroup","roleHeading":"API Collection","modules":[{"name":"DotNfc"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"]]},"kind":"article","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/error\/equatable-implementations"]}],"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"kind":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/!=(_:_:)":{"role":"symbol","abstract":[],"url":"\/documentation\/dotnfc\/intervalfloat\/error\/!=(_:_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/!=(_:_:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"!=(_:_:)"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/error","role":"symbol","abstract":[],"title":"IntervalFloat.Error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace"}]}]}