{"metadata":{"modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"roleHeading":"Instance Property","title":"errorDescription","role":"symbol","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"extendedModule":"DotCore","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/error\/errordescription"]}],"kind":"symbol","abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.errorDescription"},{"text":".","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/LocalizedError-Implementations"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/errorDescription"},"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error","abstract":[],"role":"symbol","title":"IntervalFloat.Error"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"url":"\/documentation\/dotnfc\/intervalfloat","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"title":"IntervalFloat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/LocalizedError-Implementations":{"kind":"article","title":"LocalizedError Implementations","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/LocalizedError-Implementations","type":"topic","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotnfc\/intervalfloat\/error\/localizederror-implementations"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.1.1"}]},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/errorDescription":{"role":"symbol","type":"topic","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/intervalfloat\/error\/errordescription","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/errorDescription"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]}]}]}