{"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/internalError","interfaceLanguage":"swift"},"metadata":{"role":"symbol","externalID":"s:7DotCore13IntervalFloatC5ErrorO08internalE0sAD_pSgvp","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotNfc"}],"title":"internalError","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"]]},"kind":"symbol","sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.internalError","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/intervalfloat\/error\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat\/error","role":"symbol","abstract":[],"title":"IntervalFloat.Error","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"kind":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotnfc\/intervalfloat","role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"},"doc://DotNfc/documentation/DotNfc/IntervalFloat/Error/internalError":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/Error\/internalError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"text":": Swift","kind":"text"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/dotnfc\/intervalfloat\/error\/internalerror","abstract":[],"title":"internalError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/navigatorTitle"}]}]}