{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle\/initWithPreview:","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle\/initwithpreview:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithPreview:"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateIdle(im)initWithPreview:","symbolKind":"method","roleHeading":"Instance Method","title":"initWithPreview:","modules":[{"name":"DotFingersCore"}],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview"},{"text":" *) ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateIdle":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateIdle","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DOTFGFingersAutoCaptureUiStateIdle","abstract":[{"type":"text","text":"Idle state."},{"type":"text","text":" "},{"type":"text","text":"This state is active either:"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"type":"topic","title":"FingersAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateIdle/initWithPreview:":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistateidle\/initwithpreview:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"}],"title":"initWithPreview:","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateIdle\/initWithPreview:","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithPreview:","kind":"identifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title","value":"DOTFGFingersAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}