{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration\/init"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotnfclibraryconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"method","title":"init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}]},"references":{"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"NFC library configuration."}],"role":"symbol","title":"DotNfcLibraryConfiguration","url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration"},"doc://DotNfc/documentation/DotNfc/DotNfcLibraryConfiguration/init":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotNfcLibraryConfiguration\/init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotnfclibraryconfiguration\/init","type":"topic","title":"init","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","url":"\/documentation\/dotnfc","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/title","value":"DotNfcLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotNfcLibraryConfiguration\/navigatorTitle","value":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}