{"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"required":true,"title":"initialize(license:)","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)initializeWithLicense:error:","role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/initialize(license:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"platforms":["iOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 8.14.1"}],"url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/DotLibrary":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary","title":"DotLibrary","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotLibrary/initialize(license:)":{"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary\/initialize(license:)","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotlibrary\/initialize(license:)","title":"initialize(license:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"required":true,"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"title":"DotSdkLicenseProxyProtocol","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","abstract":[],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initializeWithLicense:error:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithLicense:error:"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"initializeWithLicense:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"id<DotSdkLicenseProxyProtocol>"},{"text":" *) ","kind":"text"},{"text":"license","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary~1initialize(license:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]}]}