{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble"]]},"abstract":[{"type":"text","text":"Maximal interval value."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"max","kind":"identifier"}],"title":"max","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTIntervalDouble(py)max"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"max"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/max","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/max"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/intervaldouble\/max"]}],"references":{"doc://DotDocument/documentation/DotDocument/IntervalDouble":{"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotdocument\/intervaldouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"title":"IntervalDouble"},"doc://DotDocument/documentation/DotDocument/IntervalDouble/max":{"navigatorTitle":[{"text":"max","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"max","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalDouble\/max","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/intervaldouble\/max","abstract":[{"text":"Maximal interval value.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"max","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"max"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"max","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/title","value":"DOTIntervalDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble\/navigatorTitle","value":[{"text":"DOTIntervalDouble","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1max\/title","value":"max","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalDouble~1max\/fragments","value":[{"kind":"identifier","text":"max"}],"op":"replace"}]}]}