{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithCiImage:ciContext:","roleHeading":"Type Method","title":"createBgraRawImage(ciImage:ciContext:)","navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"symbolKind":"method"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(ciimage:cicontext:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory"]]},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"text":" object.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}]}],"name":"ciImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"CIContext."}]}],"name":"ciContext"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"title":"createBgraRawImage(ciImage:ciContext:)","type":"topic","url":"\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"title":"Image","type":"topic","navigatorTitle":[{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","url":"\/documentation\/dotfacelite\/image","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Image","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory":{"type":"topic","title":"ImageFactory","navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagefactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"DOTImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"ciContext:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title","value":"createBgraRawImageWithCiImage:ciContext:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTImageFactory"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFactory"}]}]}]}