{"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(bgrRawImage:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}],"role":"symbol","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DOTImageFactory(cm)createBgraRawImageWithBgrRawImage:","modules":[{"name":"DotFaceLite"}],"title":"createBgraRawImage(bgrRawImage:)","roleHeading":"Type Method"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(bgrrawimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(bgrrawimage:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},{"text":") -> ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with a ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"text":" format. Terminates if the passed image is not in the correct format.","type":"text"}]}],"name":"bgrRawImage"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"text":"New ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Image":{"kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"role":"symbol","title":"Image","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory":{"title":"ImageFactory","kind":"symbol","url":"\/documentation\/dotfacelite\/imagefactory","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","abstract":[{"text":"Create ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgraRawImage(bgrRawImage:)":{"title":"createBgraRawImage(bgrRawImage:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(bgrRawImage:)","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgr"},{"type":"text","text":" format as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object with "},{"type":"codeVoice","code":".rawBgra"},{"type":"text","text":" format."}],"url":"\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(bgrrawimage:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createBgraRawImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgrRawImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"Image"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createBgraRawImageWithBgrRawImage:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgrRawImage"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"bgrRawImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as an ","type":"text"},{"type":"codeVoice","code":"Image"},{"text":" object with a ","type":"text"},{"type":"codeVoice","code":".rawBgr"},{"text":" format. Terminates if the passed image is not in the correct format.","type":"text"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" instance."}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle","value":[{"text":"DOTImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/title","value":"DOTImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/fragments","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/navigatorTitle","value":[{"text":"DOTImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title","value":"createBgraRawImageWithBgrRawImage:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}