{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"abstract":[{"text":"Minimal valid sharpness of the detected document.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents blurry document."},{"type":"text","text":" "},{"text":"Vaue 1.0 represents sharp document.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"minSharpness","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minSharpness","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minsharpness"]}],"metadata":{"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","role":"symbol","title":"minSharpness","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"minSharpness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"text":"?","kind":"text"}],"externalID":"s:11DotDocument0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC12minSharpness0A4Core13WrappedDoubleCSgvp"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."}],"title":"DocumentAutoCaptureViewController.Configuration.QualityAttributeThresholds"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/minSharpness":{"title":"minSharpness","abstract":[{"text":"Minimal valid sharpness of the detected document.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents blurry document."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents sharp document."}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/minsharpness","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/minSharpness","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minSharpness"},{"text":": ","kind":"text"},{"text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController/Configuration-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/Configuration-swift.class","url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/configuration-swift.class","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"title":"DocumentAutoCaptureViewController.Configuration"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureViewController":{"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing document images using the placeholder.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"type":"topic","navigatorTitle":[{"text":"DocumentAutoCaptureViewController","kind":"identifier"}],"title":"DocumentAutoCaptureViewController"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","url":"\/documentation\/dotdocument\/wrappeddouble","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"type":"topic","title":"WrappedDouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}]},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"text":"version: 8.17.0","type":"text"}],"title":"DotDocument","type":"topic","kind":"symbol","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"}},"variantOverrides":[{"patch":[{"value":"DOTDDocumentAutoCaptureViewController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureViewController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","op":"replace","value":"DOTWrappedDouble"},{"value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}