{"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/maxDevicePitchAngle(_:)"},"metadata":{"symbolKind":"method","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxDevicePitchAngle","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","text":"WrappedFloat"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"title":"maxDevicePitchAngle(_:)","externalID":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC19maxDevicePitchAngleyAI0A4Core12WrappedFloatCSgKF","roleHeading":"Instance Method","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@discardableResult"},{"text":" ","kind":"text"},{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"internalParam"},{"kind":"text","text":": "},{"text":"WrappedFloat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"text":"Builder","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC"}],"languages":["swift"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/maxdevicepitchangle(_:)"]}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"kind":"symbol","type":"topic","title":"FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","role":"symbol","abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/WrappedFloat":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","url":"\/documentation\/dotfacelite\/wrappedfloat","abstract":[{"type":"text","text":"Wrapped "},{"code":"Float","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"title":"WrappedFloat","role":"symbol","type":"topic","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Builder","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds.Builder","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder","navigatorTitle":[{"text":"Builder","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"kind":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"kind":"symbol","navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","title":"FaceAutoCaptureViewController.Configuration.QualityAttributeThresholds","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/Builder/maxDevicePitchAngle(_:)":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/Builder\/maxDevicePitchAngle(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","text":"WrappedFloat","kind":"typeIdentifier"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC7BuilderC","text":"Builder","kind":"typeIdentifier"}],"type":"topic","title":"maxDevicePitchAngle(_:)","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/builder\/maxdevicepitchangle(_:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/title","value":"DOTWrappedFloat","op":"replace"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/fragments","op":"replace"}]}]}