{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"title":"init","roleHeading":"Instance Method","navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeNotPresentValidator(im)init","symbolKind":"method"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeNotPresentValidator\/init","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbarcodenotpresentvalidator\/init"]}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDBarcodeNotPresentValidator/init":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeNotPresentValidator\/init","url":"\/documentation\/dotdocument\/dotdbarcodenotpresentvalidator\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","type":"topic","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BarcodeNotPresentValidator":{"title":"BarcodeNotPresentValidator","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"role":"symbol","abstract":[{"text":"Validate if barcode is present.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeNotPresentValidator","navigatorTitle":[{"kind":"identifier","text":"BarcodeNotPresentValidator"}],"url":"\/documentation\/dotdocument\/barcodenotpresentvalidator","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDBarcodeNotPresentValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/title","op":"replace"},{"value":[{"text":"DOTDBarcodeNotPresentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/fragments","op":"replace"},{"value":[{"text":"DOTDBarcodeNotPresentValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeNotPresentValidator\/navigatorTitle","op":"replace"}]}]}