{"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/delegate"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"weak"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"delegate","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceSimpleCaptureViewControllerDelegate","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/delegate"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"abstract":[{"type":"text","text":"Set this delegate to handle the face simple capture events."}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"kind":"symbol","metadata":{"roleHeading":"Instance Property","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(py)delegate","title":"delegate","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceSimpleCaptureViewControllerDelegate","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"delegate"}],"platforms":[],"modules":[{"name":"DotFaceCore"}],"role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"deprecated":true,"title":"FaceSimpleCaptureViewController","type":"topic","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.6.0"}],"url":"\/documentation\/dotfacecore","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewControllerDelegate":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewControllerDelegate","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceSimpleCaptureViewControllerDelegate"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewControllerDelegate","kind":"symbol","deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontrollerdelegate","title":"FaceSimpleCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face simple capture events."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/delegate":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/delegate","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate","text":"FaceSimpleCaptureViewControllerDelegate","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Set this delegate to handle the face simple capture events.","type":"text"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"deprecated":true,"role":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/delegate","title":"delegate","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"delegate","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"delegate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"weak","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qo@M@DotFaceCore@objc(pl)DOTFFaceSimpleCaptureViewControllerDelegate","text":"id<DOTFFaceSimpleCaptureViewControllerDelegate>","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"delegate","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFFaceSimpleCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title"},{"value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","op":"replace"},{"value":"DOTFFaceSimpleCaptureViewControllerDelegate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceSimpleCaptureViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewControllerDelegate\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1delegate\/title","value":"delegate","op":"replace"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1delegate\/fragments","op":"replace"}]}]}