{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration(im)init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","title":"init","modules":[{"name":"DotNfc"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration\/init"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration\/init"},"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration/init":{"kind":"symbol","role":"symbol","title":"init","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration\/init"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","kind":"symbol","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration":{"kind":"symbol","role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace"}]}]}