{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expression"},{"kind":"text","text":": "},{"text":"ExpressionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Face expression query."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/expression"]},{"paths":["\/documentation\/dotfacecore\/facequalityquery\/expression"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"expression","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery"}],"navigatorTitle":[{"text":"expression","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"role":"symbol","title":"expression","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery(py)expression"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery\/expression","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery"]]},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","title":"ExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ExpressionQuery"}],"navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/expressionquery","abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery/expression":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery\/expression","title":"expression","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"expression","kind":"identifier"},{"kind":"text","text":": "},{"text":"ExpressionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery"}],"navigatorTitle":[{"text":"expression","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery\/expression","abstract":[{"text":"Face expression query.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","title":"FaceQualityQuery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}],"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"expression"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"expression"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","kind":"typeIdentifier","text":"DOTFExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery"},{"kind":"text","text":" * "},{"text":"expression","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"text":"DOTFExpressionQuery","kind":"identifier"}]},{"value":"expression","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery~1expression\/title"},{"op":"replace","value":[{"text":"expression","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery~1expression\/fragments"},{"op":"replace","value":"DOTFFaceQualityQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}