{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/position","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/position"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetectorFinger(py)position","role":"symbol","title":"position","navigatorTitle":[{"text":"position","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"position"}],"modules":[{"name":"DotFingersCore"}]},"abstract":[{"type":"text","text":"Detected position of the finger."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGDetectionPosition","text":"DOTFGDetectionPosition"},{"kind":"text","text":" * "},{"kind":"identifier","text":"position"},{"kind":"text","text":";"}]}]}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger/position":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger\/position","title":"position","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger\/position","abstract":[{"text":"Detected position of the finger.","type":"text"}],"role":"symbol","fragments":[{"text":"position","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingerDetectorFinger":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingerDetectorFinger","type":"topic","fragments":[{"text":"DOTFGFingerDetectorFinger","kind":"identifier"}],"title":"DOTFGFingerDetectorFinger","url":"\/documentation\/dotfingerscore\/dotfgfingerdetectorfinger","kind":"symbol","abstract":[{"type":"text","text":"Result of the finger detection process."}]},"doc://DotFingersCore/documentation/DotFingersCore/DetectionPosition":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DetectionPosition"}],"title":"DetectionPosition","navigatorTitle":[{"text":"DetectionPosition","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/detectionposition","kind":"symbol","abstract":[{"type":"text","text":"Position of the finger in the image."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/title"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGDetectionPosition"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DetectionPosition\/navigatorTitle"}]}]}