{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/isEqual(_:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/isequal(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:14DotFingersCore0B18AutoCaptureUiStateC12InitializingC7isEqualySbypSgF","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","role":"symbol","roleHeading":"Instance Method"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState":{"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureUiState"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureUiState"}],"abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"title":"FingersAutoCaptureUiState","url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate","type":"topic","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Initializing"}],"navigatorTitle":[{"kind":"identifier","text":"Initializing"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing","abstract":[{"text":"Initializing state.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing","title":"FingersAutoCaptureUiState.Initializing","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureUiState/Initializing/isEqual(_:)":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureuistate\/initializing\/isequal(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureUiState\/Initializing\/isEqual(_:)","title":"isEqual(_:)","role":"symbol","abstract":[],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/title","value":"DOTFGFingersAutoCaptureUiState"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/fragments","value":[{"text":"DOTFGFingersAutoCaptureUiState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureUiState","kind":"identifier"}]}]}]}