{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/capturemode"]}],"metadata":{"externalID":"s:11DotFaceCore0B25AutoCaptureViewControllerC13ConfigurationC8DefaultsV11captureModeAA0eK0OvpZ","roleHeading":"Type Property","title":"captureMode","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@E@DOTCaptureMode","kind":"typeIdentifier","text":"CaptureMode"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"captureMode"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCaptureMode","text":"CaptureMode"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/captureMode"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/Defaults/captureMode":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults\/captureMode","abstract":[],"title":"captureMode","type":"topic","url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults\/capturemode","kind":"symbol","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"captureMode","kind":"identifier"},{"kind":"text","text":": "},{"text":"CaptureMode","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCaptureMode","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class","title":"FaceAutoCaptureViewController.Configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images using the placeholder.","type":"text"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"title":"FaceAutoCaptureViewController","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController/Configuration-swift.class/Defaults":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController\/Configuration-swift.class\/Defaults","abstract":[],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller\/configuration-swift.class\/defaults","navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"title":"FaceAutoCaptureViewController.Configuration.Defaults","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureMode":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureMode","title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/capturemode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Capture mode."}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceAutoCaptureViewController","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/title","value":"DOTCaptureMode","op":"replace"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureMode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}