{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Instance Method","title":"validate(documentAutoCaptureFrameParameters:)","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentNotDetectedValidator(im)validateWithDocumentAutoCaptureFrameParameters:","symbolKind":"method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/validate(documentautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator\/validate(documentautocaptureframeparameters:)"]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"documentAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to indicate there was no suitable document detected in the image."}],"type":"paragraph"}]}],"abstract":[{"text":"Validate confidence of the detected document.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","title":"DocumentNotDetectedValidator","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/validate(documentAutoCaptureFrameParameters:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/validate(documentAutoCaptureFrameParameters:)","kind":"symbol","abstract":[{"type":"text","text":"Validate confidence of the detected document."}],"type":"topic","title":"validate(documentAutoCaptureFrameParameters:)","role":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/validate(documentautocaptureframeparameters:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"title":"DocumentAutoCaptureFrameParameters","type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 9.2.0"}],"kind":"symbol","type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"documentAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Frame parameters to validate."}],"type":"paragraph"}],"name":"documentAutoCaptureFrameParameters"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" to indicate there was no suitable document detected in the image."}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/navigatorTitle","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}