{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/hash","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/pointdouble\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/pointdouble\/hash"]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"modules":[{"name":"DotPalmCore"}],"title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)hash"},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PointDouble":{"url":"\/documentation\/dotpalmcore\/pointdouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble","role":"symbol","title":"PointDouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PointDouble/hash":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PointDouble\/hash","url":"\/documentation\/dotpalmcore\/pointdouble\/hash","title":"hash","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"hash","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPointDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/title","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/fragments","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble\/navigatorTitle","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PointDouble~1hash\/fragments","op":"replace"}]}]}