{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"]]},"topicSections":[{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/invalidFaceDetectionConfidenceThreshold"],"title":"Enumeration Cases"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/errorMessage","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/internalError"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/DotSdkError-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/Equatable-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/Error-Implementations","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/s5ErrorP","doc:\/\/DotFaceCore\/SH","doc:\/\/DotFaceCore\/s8SendableP"],"title":"Conforms To","type":"conformsTo"}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","interfaceLanguage":"swift"},"metadata":{"symbolKind":"enum","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"title":"DotFaceLibraryConfiguration.Error","externalID":"s:11DotFaceCore0aB20LibraryConfigurationC5ErrorO","roleHeading":"Enumeration"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotFaceCore\/s5ErrorP","type":"unresolvable"},"doc://DotFaceCore/s8SendableP":{"title":"Swift.Sendable","identifier":"doc:\/\/DotFaceCore\/s8SendableP","type":"unresolvable"},"doc://DotFaceCore/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","identifier":"doc:\/\/DotFaceCore\/10Foundation14LocalizedErrorP","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error":{"title":"DotFaceLibraryConfiguration.Error","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/Equatable-Implementations":{"title":"Equatable Implementations","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/equatable-implementations","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/Equatable-Implementations","kind":"article"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/invalidFaceDetectionConfidenceThreshold":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/invalidFaceDetectionConfidenceThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invalidFaceDetectionConfidenceThreshold","kind":"identifier"}],"title":"DotFaceLibraryConfiguration.Error.invalidFaceDetectionConfidenceThreshold","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/invalidfacedetectionconfidencethreshold","kind":"symbol","abstract":[],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/Error-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/Error-Implementations","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/error-implementations","role":"collectionGroup","title":"Error Implementations","kind":"article","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/DotSdkError-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/DotSdkError-Implementations","abstract":[],"kind":"article","title":"DotSdkError Implementations","type":"topic","role":"collectionGroup","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/dotsdkerror-implementations"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/errorMessage":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/errorMessage","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/errormessage","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"errorMessage","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"errorMessage","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotfacecore\/dotfacelibrary","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"type":"topic","title":"DotFaceLibrary","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Configuration of the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library will be initialized."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/CustomStringConvertible-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/CustomStringConvertible-Implementations","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/customstringconvertible-implementations","role":"collectionGroup","title":"CustomStringConvertible Implementations","kind":"article","type":"topic"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkError":{"abstract":[],"kind":"symbol","type":"topic","title":"DotSdkError","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotSdkError","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotsdkerror","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkError","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/LocalizedError-Implementations":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","abstract":[],"role":"collectionGroup","kind":"article","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/localizederror-implementations","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/internalError":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/internalError","title":"internalError","type":"topic","abstract":[],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/internalerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}]},"doc://DotFaceCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceLibrary","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"text":"DotFaceLibrary","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"}]}]}