{"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"metadata":{"navigatorTitle":[{"text":"modules","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","title":"modules","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"]"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceLibraryConfiguration(py)modules"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","text":"DotFaceModule"},{"text":"]","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules"]},{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/modules","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"title":"DotFaceLibrary","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","type":"topic","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacelibrary","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","abstract":[{"text":"Configuration of the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":" library. This class specifies how the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/modules":{"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"type":"topic","title":"modules","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": [","kind":"text"},{"text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"modules"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/modules","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/modules","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"role":"collection","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.10.0","type":"text"}],"url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule","kind":"symbol","title":"DotFaceModule","type":"topic","abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module.","type":"text"}],"role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModule","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodule","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"modules"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"modules","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<DotFaceModule>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"modules","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotFaceLibrary","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments","value":[{"text":"DotFaceLibrary","kind":"identifier"}]},{"value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments"},{"value":"modules","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1modules\/title","op":"replace"},{"value":[{"text":"modules","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration~1modules\/fragments"},{"op":"replace","value":"DotFaceModule","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModule"}]}]}]}