{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"topRight"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBarcodeDetectionPosition(py)topRight","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"topRight"}],"roleHeading":"Instance Property","title":"topRight"},"abstract":[{"text":"Top right corner point.","type":"text"}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition"]]},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topRight"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/topRight","interfaceLanguage":"occ"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdbarcodedetectionposition\/topright"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","type":"topic","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition":{"abstract":[{"text":"Position of the barcode in the image.","type":"text"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTDBarcodeDetectionPosition"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition","title":"DOTDBarcodeDetectionPosition"},"doc://DotDocument/documentation/DotDocument/DOTDBarcodeDetectionPosition/topRight":{"abstract":[{"type":"text","text":"Top right corner point."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdbarcodedetectionposition\/topright","kind":"symbol","fragments":[{"kind":"identifier","text":"topRight"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBarcodeDetectionPosition\/topRight","title":"topRight"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"title":"PointDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"type":"topic","url":"\/documentation\/dotdocument\/pointdouble","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]}]}]}