{"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(im)isEqual:","title":"isEqual(_:)","modules":[{"name":"DotDocument"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/isEqual(_:)","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","type":"topic","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/isEqual(_:)","kind":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/isequal(_:)","role":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","role":"symbol","title":"RectangleDouble","kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"isEqual:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isEqual:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1isEqual(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1isEqual(_:)\/fragments"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}