{"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/widthtoheightratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/widthtoheightratio"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/widthToHeightRatio","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"extendedModule":"DotCore","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(py)widthToHeightRatio","title":"widthToHeightRatio","modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"symbolKind":"property","roleHeading":"Instance Property"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"]]},"references":{"doc://DotDocument/documentation/DotDocument/RectangleDouble/widthToHeightRatio":{"navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble\/widthtoheightratio","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble\/widthToHeightRatio","role":"symbol","title":"widthToHeightRatio","kind":"symbol","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","role":"symbol","title":"RectangleDouble","kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"widthToHeightRatio","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"widthToHeightRatio"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"kind":"text","text":" "},{"kind":"identifier","text":"widthToHeightRatio"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1widthToHeightRatio\/title","value":"widthToHeightRatio","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble~1widthToHeightRatio\/fragments","value":[{"kind":"identifier","text":"widthToHeightRatio"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace"}]}]}