{"sections":[],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead.","type":"text"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"kind":"text","text":"()"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(im)requestCapture","navigatorTitle":[{"kind":"identifier","text":"requestCapture"}],"roleHeading":"Instance Method","title":"requestCapture()","symbolKind":"method","platforms":[],"modules":[{"name":"DotFaceCore"}],"role":"symbol"},"abstract":[{"type":"text","text":"Request face capture."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"()","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/requestCapture()"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/requestcapture()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/requestcapture()"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","title":"FaceSimpleCaptureViewController","type":"topic","deprecated":true,"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"abstract":[{"type":"text","text":"UI component for capturing face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","abstract":[{"text":"version: 8.4.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceSimpleCaptureViewController/requestCapture()":{"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/requestcapture()","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/requestCapture()","abstract":[{"type":"text","text":"Request face capture."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"requestCapture","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"requestCapture","kind":"identifier"}],"title":"requestCapture()","deprecated":true,"kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"requestCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestCapture"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"requestCapture"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title","value":"DOTFFaceSimpleCaptureViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1requestCapture()\/title","op":"replace","value":"requestCapture"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1requestCapture()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"requestCapture","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}