{"variants":[{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/invalidminvalidsamplesinrowtostartcandidateselection"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMinValidSamplesInRowToStartCandidateSelection"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error"]]},"metadata":{"roleHeading":"Case","title":"AutoCaptureConfiguration.Error.invalidMinValidSamplesInRowToStartCandidateSelection","role":"symbol","symbolKind":"case","modules":[{"name":"DotFaceLite"}],"externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO52invalidMinValidSamplesInRowToStartCandidateSelectionyA2EmF","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidMinValidSamplesInRowToStartCandidateSelection","kind":"identifier"}]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"role":"symbol","title":"AutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","url":"\/documentation\/dotfacelite\/autocaptureconfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error":{"abstract":[],"title":"AutoCaptureConfiguration.Error","type":"topic","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error/invalidMinValidSamplesInRowToStartCandidateSelection":{"role":"symbol","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidMinValidSamplesInRowToStartCandidateSelection","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error\/invalidminvalidsamplesinrowtostartcandidateselection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection","abstract":[],"title":"AutoCaptureConfiguration.Error.invalidMinValidSamplesInRowToStartCandidateSelection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle"}]}]}