{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfigurationModules\/barcode"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfigurationModules"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotDocumentLibraryConfigurationModules(py)barcode","fragments":[{"kind":"identifier","text":"barcode"}],"title":"barcode","roleHeading":"Instance Property","navigatorTitle":[{"text":"barcode","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotdocumentlibraryconfigurationmodules\/barcode"]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentBarcodeModuleConfiguration":{"role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"text":"Document barcode detection module configuration.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentBarcodeModuleConfiguration","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfigurationModules/barcode":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfigurationModules\/barcode","title":"barcode","url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfigurationmodules\/barcode","abstract":[],"role":"symbol","fragments":[{"kind":"identifier","text":"barcode"}],"kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotDocumentLibraryConfigurationModules":{"url":"\/documentation\/dotfingerscore\/dotdocumentlibraryconfigurationmodules","abstract":[{"type":"text","text":"Document library module configuration."}],"role":"symbol","fragments":[{"text":"DotDocumentLibraryConfigurationModules","kind":"identifier"}],"title":"DotDocumentLibraryConfigurationModules","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotDocumentLibraryConfigurationModules"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","op":"replace"}]}]}