{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/barcode","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode","title":"DotDocumentModuleId.barcode","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}],"role":"symbol","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"title":"DotDocumentModuleId","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/barcode":{"title":"DotDocumentModuleId.barcode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/barcode","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/barcode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/navigatorTitle"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId~1barcode\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId~1barcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}