{"metadata":{"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DotDocumentModuleId","extendedModule":"Swift","title":"hashValue","modules":[{"relatedModules":["Swift"],"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"RawRepresentable.hashValue"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid\/hashvalue"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/hashValue","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/hashValue":{"title":"hashValue","kind":"symbol","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/hashvalue","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/hashValue"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","title":"DotDocumentModuleId","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid","kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/title","value":"DotDocumentModuleId","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/fragments","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace"}]}]}