{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid\/hash(into:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"extendedModule":"Swift","title":"hash(into:)","symbolKind":"method","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"modules":[{"relatedModules":["Swift"],"name":"DotFaceLite"}],"role":"symbol","externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotCore@E@DotDocumentModuleId"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/RawRepresentable-Implementations"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/hash(into:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/RawRepresentable-Implementations":{"kind":"article","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/rawrepresentable-implementations","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/hash(into:)":{"abstract":[],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/hash(into:)","type":"topic","role":"symbol","title":"hash(into:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId":{"kind":"symbol","abstract":[{"type":"codeVoice","code":"DotDocument"},{"text":" feature module identifier.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"title":"DotDocumentModuleId","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid"}},"variantOverrides":[{"patch":[{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/title"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/fragments"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}