{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/init(rawValue:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid\/init(rawvalue:)"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Initializer","symbolKind":"init","externalID":"s:7DotCore0A16DocumentModuleIdO8rawValueACSgSi_tcfc"},"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId":{"abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid","title":"DotDocumentModuleId","role":"symbol","navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/init(rawValue:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/init(rawValue:)","type":"topic","title":"init(rawValue:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/init(rawvalue:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/navigatorTitle","op":"replace"}]}]}