{"metadata":{"symbolKind":"property","modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"extendedModule":"DotCore","title":"origin","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)origin"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/origin"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointInt","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/rectangleint\/origin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/rectangleint\/origin"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/RectangleInt/origin":{"url":"\/documentation\/dotnfc\/rectangleint\/origin","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/origin","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"PointInt","kind":"typeIdentifier"}],"abstract":[],"title":"origin","kind":"symbol","role":"symbol","type":"topic","navigatorTitle":[{"text":"origin","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/RectangleInt":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","title":"RectangleInt","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"kind":"symbol","url":"\/documentation\/dotnfc\/rectangleint","role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/PointInt":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"url":"\/documentation\/dotnfc\/pointint","type":"topic","title":"PointInt"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"origin","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"origin","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt","text":"DOTPointInt","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"origin","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1origin\/title","op":"replace","value":"origin"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1origin\/fragments","op":"replace","value":[{"text":"origin","kind":"identifier"}]},{"op":"replace","value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title"},{"op":"replace","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleInt"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle"},{"op":"replace","value":"DOTPointInt","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPointInt"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/navigatorTitle"}]}]}