{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt"]]},"metadata":{"symbolKind":"property","extendedModule":"DotCore","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"width"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"role":"symbol","title":"width","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"width"}],"modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleInt(py)width"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/width"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/rectangleint\/width"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/rectangleint\/width"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.0.1","type":"text"}],"url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleInt/width":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt\/width","role":"symbol","abstract":[],"navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/rectangleint\/width","kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/RectangleInt":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleInt","title":"RectangleInt","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"kind":"symbol","url":"\/documentation\/dotnfc\/rectangleint","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"width","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"width","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1width\/title","value":"width","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt~1width\/fragments","value":[{"kind":"identifier","text":"width"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/title","value":"DOTRectangleInt","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleInt\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}