{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingertype\/middle"]},{"paths":["\/documentation\/dotfingerscore\/fingertype\/middle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"FingerType.middle","externalID":"c:@M@DotFingersCore@E@DOTFGFingerType@DOTFGFingerTypeMiddle","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFGFingerTypeMiddle"}],"symbolKind":"case","modules":[{"name":"DotFingersCore"}]},"abstract":[{"text":"Middle finger.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/middle","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType/middle":{"title":"FingerType.middle","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingertype\/middle","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTFGFingerTypeMiddle","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Middle finger."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/middle"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFGFingerTypeMiddle","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeMiddle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTFGFingerTypeMiddle"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFGFingerTypeMiddle","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1middle\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerTypeMiddle"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType~1middle\/fragments"},{"value":"DOTFGFingerType","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGFingerType"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle"}]}]}