{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/RawRepresentable-Implementations"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType"]]},"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","modules":[{"name":"DotFingersCore"}],"role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/hashValue"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/hash(into:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingertype\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerType/hashValue":{"title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"url":"\/documentation\/dotfingerscore\/fingertype\/hashvalue","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/hashValue"},"doc://DotFingersCore/documentation/DotFingersCore/FingerType":{"role":"symbol","title":"FingerType","navigatorTitle":[{"kind":"identifier","text":"FingerType"}],"abstract":[{"type":"text","text":"Type of detected finger."}],"url":"\/documentation\/dotfingerscore\/fingertype","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerType"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerType/hash(into:)":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerType\/hash(into:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}],"title":"hash(into:)","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"url":"\/documentation\/dotfingerscore\/fingertype\/hash(into:)","kind":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/title","value":"DOTFGFingerType","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/fragments","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerType\/navigatorTitle","value":[{"text":"DOTFGFingerType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}],"op":"replace"}]}]}