{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/placeholder\/hidden\/hash"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden\/hash","interfaceLanguage":"swift"},"metadata":{"externalID":"s:11DotPalmCore11PlaceholderC6HiddenC4hashSivp","modules":[{"name":"DotPalmCore"}],"title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"property","roleHeading":"Instance Property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Hidden":{"url":"\/documentation\/dotpalmcore\/placeholder\/hidden","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden","title":"Placeholder.Hidden","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"abstract":[{"type":"text","text":"Hidden placeholder."}]},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder/Hidden/hash":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder\/Hidden\/hash","type":"topic","title":"hash","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotpalmcore\/placeholder\/hidden\/hash"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/Placeholder":{"title":"Placeholder","kind":"symbol","abstract":[{"type":"text","text":"Placeholder."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/placeholder","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/title","op":"replace","value":"DOTPPlaceholder"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/fragments","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Placeholder\/navigatorTitle","op":"replace","value":[{"text":"DOTPPlaceholder","kind":"identifier"}]}]}]}