{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotdocumentmoduleid\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/!=(_:_:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"op","roleHeading":"Operator","title":"!=(_:_:)","extendedModule":"Swift","role":"symbol","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotDocumentModuleId","modules":[{"name":"DotPalmCore","relatedModules":["Swift"]}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId/!=(_:_:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId\/!=(_:_:)","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid\/!=(_:_:)","type":"topic","kind":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentModuleId":{"abstract":[{"type":"codeVoice","code":"DotDocument"},{"text":" feature module identifier.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentModuleId","url":"\/documentation\/dotpalmcore\/dotdocumentmoduleid","type":"topic","kind":"symbol","title":"DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentModuleId\/navigatorTitle"}]}]}