{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Inherited from "},{"code":"DotSdkLicenseProxyProtocol.isRealTimeTransactionReportingEnabled","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled"]}],"kind":"symbol","metadata":{"title":"isRealTimeTransactionReportingEnabled","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DotSdkLicenseProxy(py)isRealTimeTransactionReportingEnabled","role":"symbol","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled"},"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy":{"title":"DotSdkLicenseProxy","kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"abstract":[],"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.2.0","type":"text"}],"role":"collection","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"title":"isRealTimeTransactionReportingEnabled","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isRealTimeTransactionReportingEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace","value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]}]}]}