{"metadata":{"navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DotSdkLicenseProxy(py)licenseBytes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"roleHeading":"Instance Property","modules":[{"name":"DotFaceCore"}],"title":"licenseBytes","symbolKind":"property","role":"symbol"},"kind":"symbol","abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkLicenseProxyProtocol.licenseBytes"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/licensebytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxy\/licensebytes"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/licenseBytes","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"title":"DotSdkLicenseProxy","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy","abstract":[]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotfacecore","type":"topic","title":"DotFaceCore","kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotSdkLicenseProxy/licenseBytes":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxy\/licensebytes","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotSdkLicenseProxy\/licenseBytes","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[],"type":"topic","navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}],"title":"licenseBytes"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"licenseBytes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"licenseBytes"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" * "},{"text":"licenseBytes","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"value":[{"text":"licenseBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotSdkLicenseProxy~1licenseBytes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}