{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/bac","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNAccessControlProtocolBac"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@DotNfc@E@DOTNAccessControlProtocol@DOTNAccessControlProtocolBac","title":"AccessControlProtocol.bac","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bac"}],"roleHeading":"Case","modules":[{"name":"DotNfc"}]},"kind":"symbol","abstract":[{"text":"Basic Access Control","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bac","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol"]]},"variants":[{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/bac"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/accesscontrolprotocol\/bac"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/AccessControlProtocol":{"title":"AccessControlProtocol","kind":"symbol","url":"\/documentation\/dotnfc\/accesscontrolprotocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol","navigatorTitle":[{"kind":"identifier","text":"AccessControlProtocol"}],"abstract":[{"type":"text","text":"Access Control protocol."}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"AccessControlProtocol"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/AccessControlProtocol/bac":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/accesscontrolprotocol\/bac","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AccessControlProtocol\/bac","role":"symbol","abstract":[{"type":"text","text":"Basic Access Control"}],"title":"AccessControlProtocol.bac","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bac"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNAccessControlProtocolBac"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTNAccessControlProtocolBac","path":"\/metadata\/title","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTNAccessControlProtocolBac","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTNAccessControlProtocolBac"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNAccessControlProtocol","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/title","op":"replace"},{"value":[{"text":"DOTNAccessControlProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNAccessControlProtocol"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol\/navigatorTitle","op":"replace"},{"value":"DOTNAccessControlProtocolBac","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1bac\/title","op":"replace"},{"value":[{"text":"DOTNAccessControlProtocolBac","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AccessControlProtocol~1bac\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}