{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel","text":"LoggerLogLevel"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/logLevel","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"title":"logLevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFLogger(cpy)logLevel","role":"symbol","roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","text":"LoggerLogLevel"}]},"variants":[{"paths":["\/documentation\/dotfacecore\/logger\/loglevel"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/logger\/loglevel"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger"]]},"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Logger":{"title":"Logger","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Logger","kind":"identifier"}],"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/logger"},"doc://DotFaceCore/documentation/DotFaceCore/LoggerLogLevel":{"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"LoggerLogLevel"}],"role":"symbol","title":"LoggerLogLevel","navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"abstract":[{"text":"Available log levels.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/loggerloglevel","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"},"doc://DotFaceCore/documentation/DotFaceCore/Logger/logLevel":{"url":"\/documentation\/dotfacecore\/logger\/loglevel","type":"topic","title":"logLevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Logger\/logLevel","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","text":"LoggerLogLevel"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTLoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/LoggerLogLevel"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger\/title","value":"DOTFLogger","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger\/fragments","value":[{"text":"DOTFLogger","kind":"identifier"}]},{"value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1LoggerLogLevel\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1logLevel\/title","value":"logLevel","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Logger~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}],"op":"replace"}]}]}