{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"]}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview(im)initWithCameraImage:detectionArea:placeholder:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":")","kind":"text"}],"title":"init(cameraImage:detectionArea:placeholder:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholder:"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"type":"topic","title":"FingersAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview/init(cameraImage:detectionArea:placeholder:)":{"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocapturepreview\/init(cameraimage:detectionarea:placeholder:)","title":"init(cameraImage:detectionArea:placeholder:)","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithCameraImage:detectionArea:placeholder:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCameraImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"text":"cameraImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea:"},{"kind":"text","text":"("},{"text":"DOTRectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"detectionArea"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placeholder"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFGFingersAutoCapturePreview","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle","op":"replace"},{"op":"replace","value":"initWithCameraImage:detectionArea:placeholder:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholder:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle","op":"replace"}]}]}