{"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview(py)placeholder","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"title":"placeholder","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"placeholder","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"}],"languages":["swift"],"platforms":["iOS"]}]}],"abstract":[{"text":"A rectangular region defined relative to the container that represents the placeholder position.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview\/placeholder","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/fingersautocapturepreview\/placeholder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingersautocapturepreview\/placeholder"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview/placeholder":{"navigatorTitle":[{"kind":"identifier","text":"placeholder"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview\/placeholder","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview\/placeholder","title":"placeholder","type":"topic","abstract":[{"text":"A rectangular region defined relative to the container that represents the placeholder position.","type":"text"}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"type":"topic","title":"FingersAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/RectangleDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfingerscore\/rectangledouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble","title":"RectangleDouble","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"placeholder","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"placeholder"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTRectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/RectangleDouble"},{"text":" * ","kind":"text"},{"text":"placeholder","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"placeholder","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview~1placeholder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"placeholder"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview~1placeholder\/fragments"},{"op":"replace","value":"DOTFGFingersAutoCapturePreview","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1RectangleDouble\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}