{"variants":[{"paths":["\/documentation\/dotdocument\/capturemode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/capturemode"]}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/autoCapture","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/waitForRequest"],"title":"Enumeration Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/description"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/Equatable-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"symbolKind":"enum","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode","title":"CaptureMode"},"relationshipsSections":[{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH","doc:\/\/DotDocument\/SY"],"kind":"relationships"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTCaptureMode) "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Capture mode."}],"references":{"doc://DotDocument/documentation/DotDocument/CaptureMode":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode","role":"symbol","title":"CaptureMode","url":"\/documentation\/dotdocument\/capturemode","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CaptureMode","kind":"identifier"}],"navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/CaptureMode/RawRepresentable-Implementations":{"url":"\/documentation\/dotdocument\/capturemode\/rawrepresentable-implementations","type":"topic","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/RawRepresentable-Implementations","kind":"article"},"doc://DotDocument/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotDocument\/SH","type":"unresolvable"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/CaptureMode/description":{"url":"\/documentation\/dotdocument\/capturemode\/description","type":"topic","role":"symbol","title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/description","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/CaptureMode/autoCapture":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/autoCapture","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"kind":"symbol","title":"CaptureMode.autoCapture","url":"\/documentation\/dotdocument\/capturemode\/autocapture","role":"symbol","abstract":[{"text":"Auto capture mode (automatic mode).","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CaptureMode/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/init(rawValue:)","title":"init(rawValue:)","kind":"symbol","url":"\/documentation\/dotdocument\/capturemode\/init(rawvalue:)","role":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"text":"version: 8.15.2","type":"text"}],"url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/CaptureMode/waitForRequest":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/waitForRequest","type":"topic","role":"symbol","title":"CaptureMode.waitForRequest","url":"\/documentation\/dotdocument\/capturemode\/waitforrequest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waitForRequest"}],"navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/CaptureMode/Equatable-Implementations":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/Equatable-Implementations","kind":"article","title":"Equatable Implementations","url":"\/documentation\/dotdocument\/capturemode\/equatable-implementations","role":"collectionGroup","abstract":[]},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SY"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureMode"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTCaptureMode"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/autoCapture","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/waitForRequest"],"title":"Enumeration Cases"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTCaptureMode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1autoCapture\/title","value":"DOTCaptureModeAutoCapture","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1autoCapture\/fragments","op":"replace","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}]},{"value":"DOTCaptureModeWaitForRequest","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1waitForRequest\/title"},{"value":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1waitForRequest\/fragments"}]}]}