{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTIntervalFloat) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"class","role":"symbol","title":"IntervalFloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/init(min:max:)"]},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/max","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/min"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/intervalfloat"]},{"paths":["\/documentation\/dotfacecore\/intervalfloat"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/init(min:max:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"min"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"max","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithMin:max:error:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/init(min:max:)","type":"topic","title":"init(min:max:)","url":"\/documentation\/dotfacecore\/intervalfloat\/init(min:max:)","role":"symbol"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/description":{"url":"\/documentation\/dotfacecore\/intervalfloat\/description","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/description","kind":"symbol","title":"description","abstract":[],"role":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/hash":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","role":"symbol","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/hash","abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/intervalfloat\/hash"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/max":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"max","kind":"identifier"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"kind":"symbol","role":"symbol","title":"max","navigatorTitle":[{"text":"max","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/max","type":"topic","abstract":[{"text":"Maximal interval value.","type":"text"}],"url":"\/documentation\/dotfacecore\/intervalfloat\/max"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/min":{"navigatorTitle":[{"text":"min","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/intervalfloat\/min","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/min","role":"symbol","type":"topic","title":"min","abstract":[{"type":"text","text":"Minimal interval value."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"min"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}]},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"kind":"symbol","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacecore\/intervalfloat","title":"IntervalFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"IntervalFloat","kind":"identifier"}]},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/isEqual(_:)","type":"topic","abstract":[],"url":"\/documentation\/dotfacecore\/intervalfloat\/isequal(_:)"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat/Error":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/Error","abstract":[],"url":"\/documentation\/dotfacecore\/intervalfloat\/error","title":"IntervalFloat.Error","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTIntervalFloat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/max","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/min"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/init(min:max:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat\/isEqual(_:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTIntervalFloat","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1init(min:max:)\/title","value":"initWithMin:max:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1init(min:max:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMin:max:error:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1hash\/title","op":"replace"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1max\/title","value":"max"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1max\/fragments","value":[{"kind":"identifier","text":"max"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1min\/title","value":"min","op":"replace"},{"value":[{"kind":"identifier","text":"min"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1min\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments","value":[{"kind":"identifier","text":"DOTIntervalFloat"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]}]}]}