{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus\/failed"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus\/failed"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/failed","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Travel document has not passed the Active Authentication."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusFailed"}],"role":"symbol","title":"ActiveAuthenticationStatus.failed","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus@DOTActiveAuthenticationStatusFailed","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/failed":{"role":"symbol","title":"ActiveAuthenticationStatus.failed","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failed"}],"abstract":[{"type":"text","text":"Travel document has not passed the Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/failed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusFailed"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus\/failed"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 2.3.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus":{"role":"symbol","title":"ActiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTActiveAuthenticationStatusFailed"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusFailed"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusFailed"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1failed\/title","value":"DOTActiveAuthenticationStatusFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1failed\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/title","value":"DOTActiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}