{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus\/notsupported"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/activeauthenticationstatus\/notsupported"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/notSupported","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Active Authentication is not supported for the travel document."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusNotSupported"}],"role":"symbol","title":"ActiveAuthenticationStatus.notSupported","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"symbolKind":"case","externalID":"c:@M@DotNfc@E@DOTActiveAuthenticationStatus@DOTActiveAuthenticationStatusNotSupported","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus/notSupported":{"role":"symbol","title":"ActiveAuthenticationStatus.notSupported","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notSupported"}],"abstract":[{"type":"text","text":"Active Authentication is not supported for the travel document."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus\/notSupported","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusNotSupported"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus\/notsupported"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/ActiveAuthenticationStatus":{"role":"symbol","title":"ActiveAuthenticationStatus","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"abstract":[{"type":"text","text":"The resulting status of Active Authentication."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/ActiveAuthenticationStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActiveAuthenticationStatus"}],"url":"\/documentation\/dotnfc\/activeauthenticationstatus"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 2.3.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTActiveAuthenticationStatusNotSupported"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusNotSupported"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusNotSupported"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1notSupported\/title","value":"DOTActiveAuthenticationStatusNotSupported"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus~1notSupported\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatusNotSupported"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/title","value":"DOTActiveAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1ActiveAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTActiveAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}