{"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTValidationFloat(cm)validateWithValue:interval:error:","navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"title":"validate(value:interval:)","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalFloat"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"symbolKind":"method","role":"symbol","roleHeading":"Type Method"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat\/validate(value:interval:)","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalFloat","text":"IntervalFloat"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/validationfloat\/validate(value:interval:)"]},{"paths":["\/documentation\/dotpalmcore\/validationfloat\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationFloat/validate(value:interval:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/validationfloat\/validate(value:interval:)","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"value"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"IntervalFloat","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat\/validate(value:interval:)","type":"topic","title":"validate(value:interval:)"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/IntervalFloat":{"navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"url":"\/documentation\/dotpalmcore\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"kind":"symbol","title":"IntervalFloat","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalFloat","type":"topic","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore/ValidationFloat":{"navigatorTitle":[{"kind":"identifier","text":"ValidationFloat"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/validationfloat","kind":"symbol","abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ValidationFloat","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/ValidationFloat","title":"ValidationFloat","type":"topic"},"doc://com.innovatrics.dot.palm.core/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.5.0"}],"url":"\/documentation\/dotpalmcore","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"op":"replace","value":"validateWithValue:interval:error:","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"validateWithValue:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"text":"interval:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.palm.core\/documentation\/DotPalmCore\/IntervalFloat","text":"DOTIntervalFloat","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTIntervalFloat"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"interval"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":"validateWithValue:interval:error:","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat~1validate(value:interval:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"validateWithValue:interval:error:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat~1validate(value:interval:)\/fragments","op":"replace"},{"value":"DOTIntervalFloat","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1IntervalFloat\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1IntervalFloat\/fragments"},{"value":"DOTValidationFloat","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat\/title"},{"value":[{"text":"DOTValidationFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.palm.core~1documentation~1DotPalmCore~1ValidationFloat\/fragments","op":"replace"}]}]}