{"sections":[],"metadata":{"title":"DotSdk.Error.failedToLoadSystemConstants","roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"externalID":"s:7DotCore0A3SdkC5ErrorO27failedToLoadSystemConstantsyA2EmF","modules":[{"name":"DotFaceCore"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/failedToLoadSystemConstants","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failedToLoadSystemConstants"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdk\/error\/failedtoloadsystemconstants"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error/failedToLoadSystemConstants":{"title":"DotSdk.Error.failedToLoadSystemConstants","role":"symbol","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/dotsdk\/error\/failedtoloadsystemconstants","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error\/failedToLoadSystemConstants"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.2.3","type":"text"}],"title":"DotFaceCore","role":"collection","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk/Error":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk\/Error","title":"DotSdk.Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotsdk\/error"},"doc://DotFaceCore/documentation/DotFaceCore/DotSdk":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdk","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotfacecore\/dotsdk","type":"topic","title":"DotSdk","abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/title"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/fragments"},{"value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdk\/navigatorTitle"}]}]}