{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/license"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/license"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/license","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Raw licensing data."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"license"}],"role":"symbol","title":"license","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration(py)license","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryConfiguration instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/license":{"deprecated":true,"role":"symbol","title":"license","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"license"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"}],"abstract":[{"type":"text","text":"Raw licensing data."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/license","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"license"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/license"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"license"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"license"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" * "},{"kind":"identifier","text":"license"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1license\/title","value":"license"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1license\/fragments","value":[{"kind":"identifier","text":"license"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}