{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule","text":"DotFaceModule"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/modules"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceconfiguration\/modules"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/modules","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"modules"}],"role":"symbol","title":"modules","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration(py)modules","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibraryConfiguration instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","title":"DotFaceModule","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModule"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceModule","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceModule"}],"url":"\/documentation\/dotfacecore\/dotfacemodule"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration/modules":{"deprecated":true,"role":"symbol","title":"modules","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DotFaceModule","preciseIdentifier":"c:@M@DotFaceCore@objc(pl)DotFaceModule"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"List of modules to load during initialization."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration\/modules","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"modules"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration\/modules"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"modules"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"modules"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<DotFaceModule>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"modules"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1modules\/title","value":"modules"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration~1modules\/fragments","value":[{"kind":"identifier","text":"modules"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}