{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"contrast"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"uniqueIntensityLevels"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"shadow"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"specularity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"? = nil)"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequality\/init(sharpness:brightness:contrast:uniqueintensitylevels:shadow:specularity:backgrounduniformity:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceimagequality\/init(sharpness:brightness:contrast:uniqueintensitylevels:shadow:specularity:backgrounduniformity:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"init","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sharpness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"contrast"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"uniqueIntensityLevels","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"shadow","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"specularity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)","role":"symbol","navigatorTitle":[{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality(im)initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","roleHeading":"Initializer"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"title":"FaceImageQuality","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequality","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","title":"FaceAttribute","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)":{"url":"\/documentation\/dotfacecore\/faceimagequality\/init(sharpness:brightness:contrast:uniqueintensitylevels:shadow:specularity:backgrounduniformity:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sharpness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"brightness","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"contrast","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"uniqueIntensityLevels","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"shadow","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"specularity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"backgroundUniformity","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)","kind":"symbol","title":"init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithSharpness:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFFaceAttribute","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":" *) ","kind":"text"},{"text":"sharpness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"brightness:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"brightness"},{"kind":"text","text":" "},{"kind":"identifier","text":"contrast:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"contrast"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueIntensityLevels:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"uniqueIntensityLevels"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadow:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"shadow"},{"kind":"text","text":" "},{"kind":"identifier","text":"specularity:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"specularity"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundUniformity"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFFaceImageQuality","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/navigatorTitle"},{"value":"DOTFFaceAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments"},{"value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle"},{"value":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithSharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1init(sharpness:brightness:contrast:uniqueIntensityLevels:shadow:specularity:backgroundUniformity:)\/fragments"}]}]}