{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Face image sharpness."}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/sharpness","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagequality\/sharpness"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceimagequality\/sharpness"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"title":"sharpness","roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQuality(py)sharpness","navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sharpness"},{"kind":"text","text":": "},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"text":"?","kind":"text"}],"symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"sharpness","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality/sharpness":{"abstract":[{"text":"Face image sharpness.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sharpness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/faceimagequality\/sharpness","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharpness"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality\/sharpness","title":"sharpness","kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"role":"symbol","abstract":[{"type":"text","text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality."}],"kind":"symbol","title":"FaceImageQuality","url":"\/documentation\/dotfacecore\/faceimagequality","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"title":"FaceAttribute","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"sharpness"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sharpness","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"DOTFFaceAttribute"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharpness"}]}]},"op":"replace"},{"value":"sharpness","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1sharpness\/title"},{"value":[{"kind":"identifier","text":"sharpness"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality~1sharpness\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace"}]}]}