{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone"]]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentCode","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/documentcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/td2machinereadablezone\/documentcode"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement"}],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)documentCode","role":"symbol","title":"documentCode","symbolKind":"property"},"references":{"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone/documentCode":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/td2machinereadablezone\/documentcode","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone\/documentCode","abstract":[],"navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"title":"documentCode"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","title":"DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td2MachineReadableZone":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td2MachineReadableZone","url":"\/documentation\/dotnfc\/td2machinereadablezone","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"kind":"symbol","title":"Td2MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}]},"doc://DotNfc/documentation/DotNfc/MrzElement":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElement","kind":"identifier"}],"title":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/mrzelement","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"documentCode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"documentCode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"DOTMrzElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"documentCode"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentCode\/title","value":"documentCode"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone~1documentCode\/fragments","value":[{"kind":"identifier","text":"documentCode"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td2MachineReadableZone\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzElement"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMrzElement"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}