{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/eyes","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyes"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","kind":"typeIdentifier","text":"EyesExpression"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpression(py)eyes","title":"eyes","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"eyes"}]},"abstract":[{"type":"text","text":"Eyes expression."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/expression\/eyes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/expression\/eyes"]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyes","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","text":"EyesExpression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"navigatorTitle":[{"kind":"identifier","text":"Expression"}],"title":"Expression","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","type":"topic","url":"\/documentation\/dotfacecore\/expression"},"doc://DotFaceCore/documentation/DotFaceCore/Expression/eyes":{"url":"\/documentation\/dotfacecore\/expression\/eyes","title":"eyes","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"eyes"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression\/eyes","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","text":"EyesExpression"}],"abstract":[{"text":"Eyes expression.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"url":"\/documentation\/dotfacecore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"url":"\/documentation\/dotfacecore\/eyesexpression","title":"EyesExpression","kind":"symbol","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"eyes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"eyes"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","text":"DOTFEyesExpression"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyes"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","op":"replace","value":"DOTFExpression"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","op":"replace","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle","op":"replace"},{"value":"eyes","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1eyes\/title","op":"replace"},{"value":[{"text":"eyes","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression~1eyes\/fragments","op":"replace"},{"value":"DOTFEyesExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","op":"replace"},{"value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFEyesExpression"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/navigatorTitle","op":"replace"}]}]}