{"topicSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadSystemConstants","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/initializationFailed(internalError:)","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/licenseDataNotSet","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/transactionCountingTokenIsNil","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/errorMessage","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/internalError"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/DotSdkError-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/Error-Implementations","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotsdk\/error"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError","doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/s5ErrorP","doc:\/\/DotFingersCore\/s8SendableP","doc:\/\/DotFingersCore\/s16SendableMetatypeP"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk"]]},"sections":[],"metadata":{"roleHeading":"Enumeration","title":"DotSdk.Error","symbolKind":"enum","externalID":"s:7DotCore0A3SdkC5ErrorO","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/DotSdkError-Implementations":{"title":"DotSdkError Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdk\/error\/dotsdkerror-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/DotSdkError-Implementations"},"doc://DotFingersCore/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/DotFingersCore\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"DotSdk.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk\/error","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/failedToLoadSystemConstants":{"type":"topic","kind":"symbol","title":"DotSdk.Error.failedToLoadSystemConstants","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/failedtoloadsystemconstants","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadSystemConstants","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadSystemConstants"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/transactionCountingTokenIsNil":{"title":"DotSdk.Error.transactionCountingTokenIsNil","kind":"symbol","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/transactioncountingtokenisnil","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"transactionCountingTokenIsNil"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/transactionCountingTokenIsNil"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdk\/error\/localizederror-implementations","type":"topic","kind":"article","role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/LocalizedError-Implementations"},"doc://DotFingersCore/s16SendableMetatypeP":{"identifier":"doc:\/\/DotFingersCore\/s16SendableMetatypeP","title":"Swift.SendableMetatype","type":"unresolvable"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/licenseDataNotSet":{"title":"DotSdk.Error.licenseDataNotSet","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseDataNotSet","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdk\/error\/licensedatanotset","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/licenseDataNotSet"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdkError":{"kind":"symbol","title":"DotSdkError","url":"\/documentation\/dotfingerscore\/dotsdkerror","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdkError"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/initializationFailed(internalError:)":{"title":"DotSdk.Error.initializationFailed(internalError:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initializationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"abstract":[],"url":"\/documentation\/dotfingerscore\/dotsdk\/error\/initializationfailed(internalerror:)","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/initializationFailed(internalError:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/transactionCountingTokenVerificationFailed(internalError:)":{"role":"symbol","title":"DotSdk.Error.transactionCountingTokenVerificationFailed(internalError:)","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/transactioncountingtokenverificationfailed(internalerror:)","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transactionCountingTokenVerificationFailed","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/transactionCountingTokenVerificationFailed(internalError:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/errorMessage":{"type":"topic","kind":"symbol","title":"errorMessage","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/errormessage","abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/errorMessage"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/Error-Implementations":{"type":"topic","kind":"article","title":"Error Implementations","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/error-implementations","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/Error-Implementations"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/failedToLoadLibrary(libraryId:)":{"type":"topic","kind":"symbol","title":"DotSdk.Error.failedToLoadLibrary(libraryId:)","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/failedtoloadlibrary(libraryid:)","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failedToLoadLibrary","kind":"identifier"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/failedToLoadLibrary(libraryId:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotsdk","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the initialization of IDV libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":"."}]},"doc://DotFingersCore/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/DotFingersCore\/s8SendableP"},"doc://DotFingersCore/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/DotFingersCore\/s5ErrorP"},"doc://DotFingersCore/documentation/DotFingersCore/DotSdk/Error/internalError":{"kind":"symbol","title":"internalError","url":"\/documentation\/dotfingerscore\/dotsdk\/error\/internalerror","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotSdk\/Error\/internalError"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}