{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper","text":"TravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone","text":"MachineReadableZone"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrzreader\/result\/init(traveldocumenttype:machinereadablezone:error:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result\/init(travelDocumentType:machineReadableZone:error:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"title":"init(travelDocumentType:machineReadableZone:error:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DotDocument9MrzReaderC6ResultC06travelB4Type19machineReadableZone5errorAeA06TravelbG7WrapperCSg_AA07MachineiJ0CSgs5Error_pSgtcfc","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/Result":{"role":"symbol","title":"MrzReader.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"MRZ reading result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotdocument\/mrzreader\/result"},"doc://com.innovatrics.dot.document/documentation/DotDocument/TravelDocumentTypeWrapper":{"role":"symbol","title":"TravelDocumentTypeWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"TravelDocumentType"},{"type":"text","text":" for Objective-C support."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/TravelDocumentTypeWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocumentTypeWrapper"}],"url":"\/documentation\/dotdocument\/traveldocumenttypewrapper"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"role":"symbol","title":"MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"url":"\/documentation\/dotdocument\/machinereadablezone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader/Result/init(travelDocumentType:machineReadableZone:error:)":{"role":"symbol","title":"init(travelDocumentType:machineReadableZone:error:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocumentType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocumentTypeWrapper","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDTravelDocumentTypeWrapper"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"machineReadableZone"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MachineReadableZone","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDMachineReadableZone"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader\/Result\/init(travelDocumentType:machineReadableZone:error:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzreader\/result\/init(traveldocumenttype:machinereadablezone:error:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"url":"\/documentation\/dotdocument\/mrzreader"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 6.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/title","value":"DOTDTravelDocumentTypeWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1TravelDocumentTypeWrapper\/fragments","value":[{"kind":"identifier","text":"DOTDTravelDocumentTypeWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTDMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTDMachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}