{"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Lines of text recognized by OCR of the document."}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/rawLines"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawLines","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzreader\/result\/rawlines"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawLines","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"modules":[{"name":"DotDocument"}],"externalID":"s:11DotDocument9MrzReaderC6ResultC8rawLinesSaySSGvp","title":"rawLines","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader/Result":{"abstract":[{"type":"text","text":"MRZ reading result."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"navigatorTitle":[{"kind":"identifier","text":"Result"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result","role":"symbol","title":"MrzReader.Result","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/result"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzReader/Result/rawLines":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"rawLines"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Lines of text recognized by OCR of the document."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader\/Result\/rawLines","title":"rawLines","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader\/result\/rawlines"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzReader","kind":"identifier"}]}]}]}