{"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/build"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method","title":"build","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder(im)build","navigatorTitle":[{"text":"build","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/build","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureQualityAttributeThresholds","text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"build"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureQualityAttributeThresholds":{"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotpalmcore\/palmautocapturequalityattributethresholds","kind":"symbol","type":"topic","title":"PalmAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureQualityAttributeThresholds"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder":{"type":"topic","title":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","abstract":[],"role":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder/build":{"type":"topic","title":"build","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"build","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureQualityAttributeThresholdsBuilder\/build","url":"\/documentation\/dotpalmcore\/dotppalmautocapturequalityattributethresholdsbuilder\/build","kind":"symbol","navigatorTitle":[{"text":"build","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTPPalmAutoCaptureQualityAttributeThresholds"},{"value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"}]}]}