{"variants":[{"paths":["\/documentation\/dotfacecore\/faceattribute\/arepreconditionsmet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceattribute\/arepreconditionsmet"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute(py)arePreconditionsMet","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"arePreconditionsMet","kind":"identifier"}],"title":"arePreconditionsMet","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/arePreconditionsMet","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"This is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"In case this flag is set to "},{"type":"codeVoice","code":"false"},{"type":"text","text":", the resulting score is not reliable."}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","type":"topic","title":"FaceAttribute"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/arePreconditionsMet":{"type":"topic","navigatorTitle":[{"text":"arePreconditionsMet","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute\/arepreconditionsmet","kind":"symbol","role":"symbol","abstract":[{"text":"This is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"arePreconditionsMet","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/arePreconditionsMet"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"arePreconditionsMet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"arePreconditionsMet"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1arePreconditionsMet\/title","value":"arePreconditionsMet","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1arePreconditionsMet\/fragments","value":[{"kind":"identifier","text":"arePreconditionsMet"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}