{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"You also need to set "},{"type":"codeVoice","code":"useLocalizationDictionary"},{"type":"text","text":" flag to "},{"type":"codeVoice","code":"true"},{"type":"text","text":"."}],"type":"paragraph"}],"style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/localization\/localizationdictionary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/localization\/localizationdictionary"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization"]]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/localizationDictionary","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"metadata":{"title":"localizationDictionary","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizationDictionary","kind":"identifier"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"]?","kind":"text"}],"roleHeading":"Type Property","symbolKind":"property","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLocalization(cpy)localizationDictionary","role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Localization":{"type":"topic","title":"Localization","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotfingerscore\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Localization/localizationDictionary":{"type":"topic","title":"localizationDictionary","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Localization\/localizationDictionary","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"]?"}],"url":"\/documentation\/dotfingerscore\/localization\/localizationdictionary","abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"localizationDictionary","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"localizationDictionary","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSDictionary","text":"NSDictionary<NSString *,NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFGLocalization","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/title"},{"op":"replace","value":[{"text":"DOTFGLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/fragments"},{"op":"replace","value":[{"text":"DOTFGLocalization","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization\/navigatorTitle"},{"op":"replace","value":"localizationDictionary","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1localizationDictionary\/title"},{"op":"replace","value":[{"text":"localizationDictionary","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Localization~1localizationDictionary\/fragments"}]}]}