{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/captureMode"},"sections":[],"abstract":[{"type":"text","text":"Capture mode. Default value is "},{"type":"text","text":".autoCapture"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"DOTCaptureMode","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/capturemode"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration(py)captureMode","fragments":[{"text":"captureMode","kind":"identifier"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"captureMode"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceLite"}],"title":"captureMode"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"title":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"symbol","fragments":[{"text":"DOTFLBaseFaceAutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration/captureMode":{"abstract":[{"type":"text","text":"Capture mode. Default value is "},{"type":"text","text":".autoCapture"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/captureMode","type":"topic","title":"captureMode","fragments":[{"text":"captureMode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/capturemode","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/capturemode","title":"CaptureMode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"text":"Capture mode.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.2.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite","kind":"symbol","url":"\/documentation\/dotfacelite","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","op":"replace"}]}]}