{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","interfaceLanguage":"occ"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCommon:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"common"},{"text":" ","kind":"text"},{"kind":"identifier","text":"camera:"},{"kind":"text","text":"("},{"text":"DOTCameraConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"camera"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"DOTAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"autoCapture"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"captureMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"DOTCaptureMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"captureMode","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","kind":"identifier"}],"roleHeading":"Instance Method","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Create the face auto capture configuration."}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:capturemode:"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","url":"\/documentation\/dotfacelite\/autocaptureconfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"title":"AutoCaptureConfiguration"},"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"abstract":[{"type":"text","text":"Common configuration for all components."}],"url":"\/documentation\/dotfacelite\/commonconfiguration","title":"CommonConfiguration","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration":{"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration","title":"DOTFLBaseFaceAutoCaptureConfiguration","url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFLBaseFaceAutoCaptureConfiguration"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","role":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CaptureMode":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CaptureMode","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/capturemode","role":"symbol","title":"CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLBaseFaceAutoCaptureConfiguration/initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","kind":"identifier"}],"abstract":[{"text":"Create the face auto capture configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotflbasefaceautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:capturemode:","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLBaseFaceAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:captureMode:","role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration","role":"symbol","title":"CameraConfiguration","navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title","op":"replace","value":"DOTCommonConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTFLFaceAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/title","op":"replace","value":"DOTCaptureMode"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/fragments","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CaptureMode\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCaptureMode"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]}]}]}