{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"title":"detection","roleHeading":"Instance Property","externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"abstract":[{"text":"Fingers library configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","title":"detection","url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersDetectionModuleConfiguration":{"abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingersdetectionmoduleconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersDetectionModuleConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFingersLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle"},{"value":"DotFingersDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle"}]}]}