{"variants":[{"paths":["\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC14transformationAA0ac20TransformationModuleE0CSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?","kind":"text"}],"title":"transformation"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"transformation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class/transformation":{"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class\/transformation","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/transformation","kind":"symbol","title":"transformation","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformation"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration/Modules-swift.class":{"abstract":[{"text":"Fingers library module configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration\/Modules-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersLibraryConfiguration":{"abstract":[{"text":"Fingers library configuration.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfingerslibraryconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersLibraryConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFingersTransformationModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfingerstransformationmoduleconfiguration","type":"topic","abstract":[{"text":"Fingers transformation module configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFingersTransformationModuleConfiguration","kind":"symbol","title":"DotFingersTransformationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/title","op":"replace"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFingersTransformationModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFingersTransformationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}