{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","kind":"typeIdentifier","text":"Corners"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(im)rebasedWithParentRectangle:","title":"rebased(parentRectangle:)","role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/rebased(parentRectangle:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/corners\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/corners\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}],"title":"Corners","url":"\/documentation\/dotfacecore\/corners","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","kind":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.14.1"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","url":"\/documentation\/dotfacecore\/rectangledouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","title":"RectangleDouble"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/rebased(parentRectangle:)":{"url":"\/documentation\/dotfacecore\/corners\/rebased(parentrectangle:)","type":"topic","title":"rebased(parentRectangle:)","abstract":[],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/rebased(parentRectangle:)","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"rebasedWithParentRectangle:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","kind":"typeIdentifier","text":"DOTCorners"},{"kind":"text","text":" *) "},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTRectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"parentRectangle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title","value":"DOTCorners"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments"},{"op":"replace","value":"rebasedWithParentRectangle:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1rebased(parentRectangle:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1rebased(parentRectangle:)\/fragments","op":"replace"}]}]}