{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init()","interfaceLanguage":"swift"},"metadata":{"title":"init()","modules":[{"name":"DotDocument"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDSharpnessTooLowValidator(im)init","navigatorTitle":[{"kind":"identifier","text":"init"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sharpnesstoolowvalidator\/init()"]}],"sections":[],"abstract":[{"type":"text","text":"Initialize with default threshold."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","title":"DocumentAutoCaptureController","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator/init()":{"title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator\/init()","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator\/init()"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"title":"SharpnessTooLowValidator","role":"symbol","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected document."}],"type":"topic","url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"SharpnessTooLowValidator"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"init","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator~1init()\/fragments"},{"op":"replace","value":"DOTDSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments"},{"op":"replace","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/navigatorTitle"}]}]}