{"variants":[{"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"roleHeading":"Enumeration","title":"AutoCaptureConfiguration.Error","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO","symbolKind":"enum"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/errorMessage","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/internalError"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Error-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"]]},"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError","doc:\/\/DotPalmCore\/10Foundation14LocalizedErrorP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/s5ErrorP","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/s8SendableP"],"kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"title":"AutoCaptureConfiguration.Error","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/LocalizedError-Implementations":{"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/localizederror-implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations","abstract":[],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","title":"DotPalmCore","role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/errorMessage":{"title":"errorMessage","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorMessage"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/errorMessage","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/errormessage"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/CustomStringConvertible-Implementations":{"abstract":[],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/customstringconvertible-implementations","role":"collectionGroup","title":"CustomStringConvertible Implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/CustomStringConvertible-Implementations"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/internalError":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/internalError","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/internalerror","title":"internalError","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/Equatable-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Equatable-Implementations","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/equatable-implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"kind":"article","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"role":"symbol","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"title":"AutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/Error-Implementations":{"title":"Error Implementations","type":"topic","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/Error-Implementations","role":"collectionGroup","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/error-implementations","kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/DotSdkError-Implementations":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/dotsdkerror-implementations","title":"DotSdkError Implementations","kind":"article","type":"topic","role":"collectionGroup","abstract":[]},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/s5ErrorP":{"title":"Swift.Error","identifier":"doc:\/\/DotPalmCore\/s5ErrorP","type":"unresolvable"},"doc://DotPalmCore/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s8SendableP"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkError":{"abstract":[],"kind":"symbol","title":"DotSdkError","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkError","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdkError","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotsdkerror","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkError"},"doc://DotPalmCore/10Foundation14LocalizedErrorP":{"title":"Foundation.LocalizedError","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/10Foundation14LocalizedErrorP"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidCandidateSelectionDurationMillis"}],"title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","kind":"symbol","type":"topic","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/Error/invalidMinValidSamplesInRowToStartCandidateSelection":{"kind":"symbol","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/error\/invalidminvalidsamplesinrowtostartcandidateselection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/Error\/invalidMinValidSamplesInRowToStartCandidateSelection","title":"AutoCaptureConfiguration.Error.invalidMinValidSamplesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidMinValidSamplesInRowToStartCandidateSelection"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}]}]}