{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing\/back","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Back facing camera.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"back","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/camerafacing\/back"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/camerafacing\/back"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTCameraFacingBack"}],"title":"CameraFacing.back","roleHeading":"Case","externalID":"c:@M@DotFaceCore@E@DOTCameraFacing@DOTCameraFacingBack","symbolKind":"case","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"back","kind":"identifier"}]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing/back":{"url":"\/documentation\/dotfacecore\/camerafacing\/back","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing\/back","title":"CameraFacing.back","abstract":[{"type":"text","text":"Back facing camera."}],"navigatorTitle":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"back"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.3.2","type":"text"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"title":"CameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","role":"symbol","url":"\/documentation\/dotfacecore\/camerafacing","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraFacingBack"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTCameraFacingBack"}]}],"kind":"declarations"}},{"value":"DOTCameraFacingBack","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing~1back\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing~1back\/fragments","value":[{"text":"DOTCameraFacingBack","kind":"identifier"}],"op":"replace"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","op":"replace","value":[{"text":"DOTCameraFacing","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}