{"metadata":{"symbolKind":"case","modules":[{"name":"DotFaceLite"}],"title":"DotPalmModuleId.detection","externalID":"c:@M@DotCore@E@DotPalmModuleId@DotPalmModuleIdDetection","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/detection","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotpalmmoduleid\/detection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotpalmmoduleid\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId/detection":{"role":"symbol","title":"DotPalmModuleId.detection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId\/detection","url":"\/documentation\/dotfacelite\/dotpalmmoduleid\/detection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmModuleId":{"kind":"symbol","title":"DotPalmModuleId","role":"symbol","navigatorTitle":[{"text":"DotPalmModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmModuleId","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotpalmmoduleid","type":"topic","abstract":[{"code":"DotPalm","type":"codeVoice"},{"type":"text","text":" feature module identifier."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotPalmModuleIdDetection"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotPalmModuleIdDetection"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId~1detection\/title","value":"DotPalmModuleIdDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId~1detection\/fragments","value":[{"text":"DotPalmModuleIdDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/title","value":"DotPalmModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/fragments","value":[{"text":"DotPalmModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmModuleId\/navigatorTitle","value":[{"kind":"identifier","text":"DotPalmModuleId"}]}]}]}