{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","text":"EyesExpressionQuery"},{"kind":"text","text":" = EyesExpressionQuery(), "},{"kind":"externalParam","text":"mouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" = false)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/expressionquery\/init(eyes:mouth:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/expressionquery\/init(eyes:mouth:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:mouth:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"title":"init(eyes:mouth:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpressionQuery(im)initWithEyes:mouth:","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEyes:mouth:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"role":"symbol","title":"ExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionQuery"}],"abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ExpressionQuery"}],"url":"\/documentation\/dotfacecore\/expressionquery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.5.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery/init(eyes:mouth:)":{"role":"symbol","title":"init(eyes:mouth:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mouth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery\/init(eyes:mouth:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithEyes:mouth:"}],"url":"\/documentation\/dotfacecore\/expressionquery\/init(eyes:mouth:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"role":"symbol","title":"EyesExpressionQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyesExpressionQuery"}],"abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithEyes:mouth:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEyes:mouth:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithEyes:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpressionQuery","text":"DOTFEyesExpressionQuery"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"eyes"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouth:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"mouth"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title","value":"DOTFExpressionQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:mouth:)\/title","value":"initWithEyes:mouth:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery~1init(eyes:mouth:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithEyes:mouth:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","value":"DOTFEyesExpressionQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}