{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults","interfaceLanguage":"swift"},"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/backgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/detectionLayerColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionBackgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionCandidateSelectionBackgroundColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionCandidateSelectionTextColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionFont","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionTextColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/overlayColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/placeholderCandidateSelectionColor","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/placeholderColor"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"title":"MagnifEyeLivenessStyle.Defaults","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"s:11DotFaceCore22MagnifEyeLivenessStyleC8DefaultsV","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"Defaults"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle":{"role":"symbol","title":"MagnifEyeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/placeholderColor":{"role":"symbol","title":"placeholderColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/placeholderColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/placeholdercolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults":{"role":"symbol","title":"MagnifEyeLivenessStyle.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/overlayColor":{"role":"symbol","title":"overlayColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"overlayColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/overlayColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/overlaycolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/instructionCandidateSelectionBackgroundColor":{"role":"symbol","title":"instructionCandidateSelectionBackgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionCandidateSelectionBackgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/instructioncandidateselectionbackgroundcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/detectionLayerColor":{"role":"symbol","title":"detectionLayerColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionLayerColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/detectionLayerColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/detectionlayercolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/instructionCandidateSelectionTextColor":{"role":"symbol","title":"instructionCandidateSelectionTextColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionCandidateSelectionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionCandidateSelectionTextColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/instructioncandidateselectiontextcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/instructionBackgroundColor":{"role":"symbol","title":"instructionBackgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionBackgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionBackgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/instructionbackgroundcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/instructionTextColor":{"role":"symbol","title":"instructionTextColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionTextColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/instructiontextcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/backgroundColor":{"role":"symbol","title":"backgroundColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/backgroundColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/backgroundcolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/placeholderCandidateSelectionColor":{"role":"symbol","title":"placeholderCandidateSelectionColor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholderCandidateSelectionColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/placeholderCandidateSelectionColor","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/placeholdercandidateselectioncolor"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/Defaults/instructionFont":{"role":"symbol","title":"instructionFont","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionFont"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIFont","preciseIdentifier":"c:objc(cs)UIFont"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/Defaults\/instructionFont","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/defaults\/instructionfont"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/title","value":"DOTFMagnifEyeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}