{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessstyle\/instructiontextcolor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/magnifeyelivenessstyle\/instructiontextcolor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/instructionTextColor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Instruction label text color."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"title":"instructionTextColor","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessStyle(py)instructionTextColor","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"instructionTextColor"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle":{"role":"symbol","title":"MagnifEyeLivenessStyle","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"abstract":[{"type":"text","text":"Customization options for the MagnifEye liveness user interface."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessStyle"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessViewController":{"role":"symbol","title":"MagnifEyeLivenessViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MagnifEyeLivenessStyle/instructionTextColor":{"role":"symbol","title":"instructionTextColor","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"instructionTextColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"}],"abstract":[{"type":"text","text":"Instruction label text color."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MagnifEyeLivenessStyle\/instructionTextColor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"instructionTextColor"}],"url":"\/documentation\/dotfacecore\/magnifeyelivenessstyle\/instructiontextcolor"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"instructionTextColor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"instructionTextColor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"instructionTextColor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/title","value":"DOTFMagnifEyeLivenessStyle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessStyle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/title","value":"DOTFMagnifEyeLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle~1instructionTextColor\/title","value":"instructionTextColor"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MagnifEyeLivenessStyle~1instructionTextColor\/fragments","value":[{"kind":"identifier","text":"instructionTextColor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}