{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/hash"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/pointdouble\/hash"]},{"paths":["\/documentation\/dotnfc\/pointdouble\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)hash","role":"symbol","modules":[{"name":"DotNfc"}],"title":"hash","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"roleHeading":"Instance Property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"text":"version: 8.17.0","type":"text"}],"role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/PointDouble/hash":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotnfc\/pointdouble\/hash","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble\/hash"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol","url":"\/documentation\/dotnfc\/pointdouble","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"kind":"text","text":" "},{"text":"hash","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1hash\/title","op":"replace","value":"hash"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","op":"replace","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPointDouble"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}