{"metadata":{"title":"FaceAutoCapturePhase.candidateSelection","symbolKind":"case","modules":[{"name":"DotFaceLite"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase@DOTFaceAutoCapturePhaseCandidateSelection"},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/candidateSelection","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"]]},"abstract":[{"text":"Candidate selection is running.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/candidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturephase\/candidateselection"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/candidateSelection":{"title":"FaceAutoCapturePhase.candidateSelection","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/candidateSelection","url":"\/documentation\/dotfacelite\/faceautocapturephase\/candidateselection","type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DOTFaceAutoCapturePhaseCandidateSelection","kind":"identifier"}],"abstract":[{"text":"Candidate selection is running.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturephase","title":"FaceAutoCapturePhase","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}],"role":"symbol","abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTFaceAutoCapturePhaseCandidateSelection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"DOTFaceAutoCapturePhaseCandidateSelection","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1candidateSelection\/title","value":"DOTFaceAutoCapturePhaseCandidateSelection","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1candidateSelection\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"op":"replace"},{"value":"DOTFaceAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title"},{"value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle"}]}]}