{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init(minDetectionSizeToImageShorterSideRatioThreshold:)"},"kind":"symbol","sections":[],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/init(mindetectionsizetoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoosmallvalidator\/init(mindetectionsizetoimageshortersideratiothreshold:)"]}],"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooSmallValidator(im)initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","role":"symbol","title":"init(minDetectionSizeToImageShorterSideRatioThreshold:)"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator/init(minDetectionSizeToImageShorterSideRatioThreshold:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator\/init(minDetectionSizeToImageShorterSideRatioThreshold:)","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator\/init(mindetectionsizetoimageshortersideratiothreshold:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minDetectionSizeToImageShorterSideRatioThreshold"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:"}],"title":"init(minDetectionSizeToImageShorterSideRatioThreshold:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/SizeTooSmallValidator":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/SizeTooSmallValidator","title":"SizeTooSmallValidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.4.0","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minDetectionSizeToImageShorterSideRatioThreshold","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init(minDetectionSizeToImageShorterSideRatioThreshold:)\/title","value":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithMinDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator~1init(minDetectionSizeToImageShorterSideRatioThreshold:)\/fragments"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTFLSizeTooSmallValidator","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}