{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/barcode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId"]]},"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotDocumentModuleId@DotDocumentModuleIdBarcode","title":"DotDocumentModuleId.barcode","role":"symbol","symbolKind":"case"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid\/barcode"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"role":"symbol","type":"topic","title":"DotDocumentModuleId","url":"\/documentation\/dotnfc\/dotdocumentmoduleid"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/barcode":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/barcode","navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/barcode","type":"topic","title":"DotDocumentModuleId.barcode","role":"symbol","abstract":[]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotDocumentModuleId","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/title"},{"value":[{"text":"DotDocumentModuleId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/fragments"},{"value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/navigatorTitle"},{"value":"DotDocumentModuleIdBarcode","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId~1barcode\/title"},{"value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId~1barcode\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}