{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId"]]},"kind":"article","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid\/equatable-implementations"]}],"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","generated":true,"anchor":"Operators","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/!=(_:_:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/!=(_:_:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/!=(_:_:)","kind":"symbol","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/!=(_:_:)","title":"!=(_:_:)"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotdocumentmoduleid","kind":"symbol","type":"topic","abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId","title":"DotDocumentModuleId"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentModuleId","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/navigatorTitle"}]}]}