{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"text":".","type":"text"}],"metadata":{"title":"init(rawValue:)","symbolKind":"init","externalID":"s:7DotCore0A16DocumentModuleIdO8rawValueACSgSi_tcfc","roleHeading":"Initializer","modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/init(rawValue:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid\/init(rawvalue:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId":{"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId","title":"DotDocumentModuleId","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotdocumentmoduleid","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","abstract":[{"text":"version: 9.2.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","role":"collection"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/init(rawValue:)":{"abstract":[],"role":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/init(rawValue:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}