{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration"]]},"metadata":{"modules":[{"name":"DotDocument"}],"symbolKind":"init","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(im)initWithLicenseBytes:libraries:","roleHeading":"Initializer","role":"symbol","title":"init(licenseBytes:libraries:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"licenseBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithLicenseBytes:libraries:"}]},"variants":[{"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary"},{"text":"])","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/DotLibrary":{"abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotLibrary","type":"topic","url":"\/documentation\/dotdocument\/dotlibrary","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"title":"DotLibrary","kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration":{"title":"DotSdkConfiguration","url":"\/documentation\/dotdocument\/dotsdkconfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotSdkConfiguration/init(licenseBytes:libraries:)":{"kind":"symbol","role":"symbol","abstract":[],"title":"init(licenseBytes:libraries:)","url":"\/documentation\/dotdocument\/dotsdkconfiguration\/init(licensebytes:libraries:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": ["},{"text":"DotLibrary","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkConfiguration\/init(licenseBytes:libraries:)","navigatorTitle":[{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","abstract":[{"text":"version: 8.7.0","type":"text"}],"url":"\/documentation\/dotdocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initWithLicenseBytes:libraries:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithLicenseBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"licenseBytes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"libraries:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"libraries"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotLibrary\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/title","op":"replace","value":"DotSdkConfiguration"},{"op":"replace","value":[{"text":"DotSdkConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/title","value":"initWithLicenseBytes:libraries:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkConfiguration~1init(licenseBytes:libraries:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithLicenseBytes:libraries:","kind":"identifier"}]}]}]}