{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdDetection","modules":[{"name":"DotPalmCore"}],"title":"DotFingersModuleId.detection","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"roleHeading":"Case","symbolKind":"case"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/detection"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId"]]},"sections":[],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId/detection":{"title":"DotFingersModuleId.detection","kind":"symbol","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId\/detection","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid\/detection","type":"topic","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotFingersModuleId":{"title":"DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfingersmoduleid","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFingersModuleId","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFingersModuleIdDetection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1detection\/title","op":"replace","value":"DotFingersModuleIdDetection"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId~1detection\/fragments","op":"replace","value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}]},{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/title"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"text":"DotFingersModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFingersModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}