{"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration":{"role":"symbol","url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration","navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"kind":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration/init":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init","type":"topic","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration\/init","kind":"symbol","role":"symbol","title":"init"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"op":"add","path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init"],"title":"Instance Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]}]}]}