{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/template"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/template"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Class","externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","title":"Template","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Template","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Face template."}],"topicSections":[{"generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/init(bytes:version:)"],"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/version"],"title":"Instance Properties"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFTemplate) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Overview","anchor":"overview","level":2},{"type":"paragraph","inlineContent":[{"text":"Template is a compact representation of detected face. It is used for matching or verification.","type":"text"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/Template/init(bytes:version:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/init(bytes:version:)","title":"init(bytes:version:)","abstract":[],"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"version","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/template\/init(bytes:version:)","navigatorTitle":[{"text":"initWithBytes:version:","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/SQ":{"identifier":"doc:\/\/DotFaceCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/Template/version":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/version","abstract":[{"type":"text","text":"Template version."}],"navigatorTitle":[{"text":"version","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}],"title":"version","type":"topic","url":"\/documentation\/dotfacecore\/template\/version","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","title":"Template","abstract":[{"type":"text","text":"Face template."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Template","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/template","navigatorTitle":[{"text":"Template","kind":"identifier"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/Template/bytes":{"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"title":"bytes","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/bytes","kind":"symbol","abstract":[{"text":"Template data.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/template\/bytes"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DOTFTemplate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/bytes","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/version"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template\/init(bytes:version:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFTemplate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1init(bytes:version:)\/title","op":"replace","value":"initWithBytes:version:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1init(bytes:version:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBytes:version:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1version\/title","op":"replace","value":"version"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1version\/fragments","op":"replace","value":[{"text":"version","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title","op":"replace","value":"DOTFTemplate"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1bytes\/title","op":"replace","value":"bytes"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template~1bytes\/fragments","op":"replace","value":[{"text":"bytes","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}