{"seeAlsoSections":[{"anchor":"Face-evaluation","generated":true,"title":"Face evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/wearables"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/wearables"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/init(glasses:mask:)"]},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/glasses","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/mask"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"kind":"symbol","metadata":{"symbolKind":"class","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFWearables","roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Wearables"}],"role":"symbol","title":"Wearables"},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFWearables) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}]}]}],"sections":[],"references":{"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","role":"symbol","navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"kind":"symbol","title":"FaceQualityQuery","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAspects":{"abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAspects","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","role":"symbol","navigatorTitle":[{"text":"FaceAspects","kind":"identifier"}],"kind":"symbol","title":"FaceAspects","type":"topic","url":"\/documentation\/dotfacecore\/faceaspects"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/mask":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/mask","type":"topic","abstract":[{"type":"text","text":"Face mask evaluation result."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"mask"}],"url":"\/documentation\/dotfacecore\/wearables\/mask","kind":"symbol","role":"symbol","title":"mask"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPose":{"abstract":[{"text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPose","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","role":"symbol","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"kind":"symbol","title":"HeadPose","type":"topic","url":"\/documentation\/dotfacecore\/headpose"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQuality":{"abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","role":"symbol","navigatorTitle":[{"text":"FaceImageQuality","kind":"identifier"}],"kind":"symbol","title":"FaceImageQuality","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequality"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","role":"symbol","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"kind":"symbol","title":"HeadPoseQuery","type":"topic","url":"\/documentation\/dotfacecore\/headposequery"},"doc://DotFaceCore/documentation/DotFaceCore/Expression":{"abstract":[{"text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Expression","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","role":"symbol","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"kind":"symbol","title":"Expression","type":"topic","url":"\/documentation\/dotfacecore\/expression"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/description":{"role":"symbol","url":"\/documentation\/dotfacecore\/wearables\/description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","abstract":[],"title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/description"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/init(glasses:mask:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/init(glasses:mask:)","type":"topic","abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"glasses"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"Glasses"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"mask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"initWithGlasses:mask:"}],"url":"\/documentation\/dotfacecore\/wearables\/init(glasses:mask:)","kind":"symbol","role":"symbol","title":"init(glasses:mask:)"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"abstract":[{"text":"Head pose attribute with angle value instead of score.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","role":"symbol","navigatorTitle":[{"text":"HeadPoseAttribute","kind":"identifier"}],"kind":"symbol","title":"HeadPoseAttribute","type":"topic","url":"\/documentation\/dotfacecore\/headposeattribute"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQuality":{"abstract":[{"text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceQuality","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","role":"symbol","navigatorTitle":[{"text":"FaceQuality","kind":"identifier"}],"kind":"symbol","title":"FaceQuality","type":"topic","url":"\/documentation\/dotfacecore\/facequality"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables/glasses":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/glasses","title":"glasses","kind":"symbol","abstract":[{"type":"text","text":"Glasses evaluation result."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"glasses"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFGlasses","text":"Glasses"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/dotfacecore\/wearables\/glasses","navigatorTitle":[{"kind":"identifier","text":"glasses"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Glasses":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses","type":"topic","title":"Glasses","role":"symbol","url":"\/documentation\/dotfacecore\/glasses","navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"abstract":[{"type":"text","text":"Face attribute for the glasses."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Glasses"}]},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"kind":"symbol","title":"FaceAttribute","type":"topic","url":"\/documentation\/dotfacecore\/faceattribute"},"doc://DotFaceCore/documentation/DotFaceCore/WearablesQuery":{"abstract":[{"text":"Wearables query specifies which wearables face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WearablesQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","role":"symbol","navigatorTitle":[{"text":"WearablesQuery","kind":"identifier"}],"kind":"symbol","title":"WearablesQuery","type":"topic","url":"\/documentation\/dotfacecore\/wearablesquery"},"doc://DotFaceCore/documentation/DotFaceCore/ExpressionQuery":{"abstract":[{"text":"Expression query specifies which face expression face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ExpressionQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","role":"symbol","navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"kind":"symbol","title":"ExpressionQuery","type":"topic","url":"\/documentation\/dotfacecore\/expressionquery"},"doc://DotFaceCore/documentation/DotFaceCore/Wearables":{"abstract":[{"text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wearables","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables","role":"symbol","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"kind":"symbol","title":"Wearables","type":"topic","url":"\/documentation\/dotfacecore\/wearables"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpressionQuery":{"abstract":[{"text":"Eyes expression query specifies which eye expression face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpressionQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","role":"symbol","navigatorTitle":[{"text":"EyesExpressionQuery","kind":"identifier"}],"kind":"symbol","title":"EyesExpressionQuery","type":"topic","url":"\/documentation\/dotfacecore\/eyesexpressionquery"},"doc://DotFaceCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SH","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/EyesExpression":{"abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyesExpression","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","role":"symbol","navigatorTitle":[{"text":"EyesExpression","kind":"identifier"}],"kind":"symbol","title":"EyesExpression","type":"topic","url":"\/documentation\/dotfacecore\/eyesexpression"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceImageQualityQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","role":"symbol","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"kind":"symbol","title":"FaceImageQualityQuery","type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFWearables"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFWearables","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFWearables"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/glasses","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/mask"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Wearables\/init(glasses:mask:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Face evaluation","anchor":"Face-evaluation","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPose","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Expression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Glasses"],"generated":true}]},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFWearables","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFFaceQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/title","value":"DOTFFaceAspects"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/fragments","value":[{"text":"DOTFFaceAspects","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAspects\/navigatorTitle","value":[{"text":"DOTFFaceAspects","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1mask\/title","value":"mask"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1mask\/fragments","value":[{"text":"mask","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/title","value":"DOTFHeadPose","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPose\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFHeadPose"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/title","value":"DOTFFaceImageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQuality\/navigatorTitle","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}]},{"value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace"},{"value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"op":"replace"},{"value":"DOTFExpression","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Expression\/navigatorTitle","value":[{"text":"DOTFExpression","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1init(glasses:mask:)\/title","value":"initWithGlasses:mask:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1init(glasses:mask:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithGlasses:mask:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title","value":"DOTFHeadPoseAttribute"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}]},{"value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle","op":"replace"},{"value":"DOTFFaceQuality","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace"},{"value":[{"text":"DOTFFaceQuality","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQuality\/navigatorTitle","op":"replace"},{"value":"glasses","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1glasses\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables~1glasses\/fragments","value":[{"text":"glasses","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/fragments","value":[{"text":"DOTFGlasses","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Glasses\/navigatorTitle","value":[{"text":"DOTFGlasses","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/title","value":"DOTFWearablesQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearablesQuery"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WearablesQuery\/navigatorTitle","op":"replace"},{"value":"DOTFExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}],"op":"replace"},{"value":[{"text":"DOTFExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ExpressionQuery\/navigatorTitle","op":"replace"},{"value":"DOTFWearables","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFWearables"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Wearables\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFWearables"}],"op":"replace"},{"value":"DOTFEyesExpressionQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/title","op":"replace"},{"value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpressionQuery\/navigatorTitle","value":[{"text":"DOTFEyesExpressionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/title","value":"DOTFEyesExpression","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/fragments","value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyesExpression\/navigatorTitle","value":[{"text":"DOTFEyesExpression","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/navigatorTitle","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}