{"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/fullRectangle","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@DotDocument@objc(cs)DOTRectangleDouble(cpy)fullRectangle","navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"extendedModule":"DotDocument","role":"symbol","title":"fullRectangle","modules":[{"name":"DotDocument"}],"symbolKind":"property","roleHeading":"Type Property"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/rectangledouble\/fullrectangle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/rectangledouble\/fullrectangle"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/rectangledouble","title":"RectangleDouble","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"kind":"symbol","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble/fullRectangle":{"type":"topic","abstract":[],"title":"fullRectangle","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble\/fullRectangle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"navigatorTitle":[{"text":"fullRectangle","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/rectangledouble\/fullrectangle"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"value":"fullRectangle","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fullRectangle","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"},{"kind":"text","text":" * "},{"text":"fullRectangle","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1fullRectangle\/title","value":"fullRectangle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble~1fullRectangle\/fragments","value":[{"text":"fullRectangle","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}