{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/composeWithInternalError()"},"kind":"symbol","metadata":{"symbolKind":"method","modules":[{"relatedModules":["DotCore"],"name":"DotDocument"}],"extendedModule":"DotCore","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","roleHeading":"Instance Method","title":"composeWithInternalError()","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:11DotDocument22ImagePerspectiveWarperC5ErrorO"},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.composeWithInternalError()","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/error\/composewithinternalerror()"]}],"references":{"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error/composeWithInternalError()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/composeWithInternalError()","role":"symbol","title":"composeWithInternalError()","url":"\/documentation\/dotdocument\/imageperspectivewarper\/error\/composewithinternalerror()"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"title":"ImagePerspectiveWarper","url":"\/documentation\/dotdocument\/imageperspectivewarper"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error":{"url":"\/documentation\/dotdocument\/imageperspectivewarper\/error","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error","kind":"symbol","role":"symbol","title":"ImagePerspectiveWarper.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Error"}]}},"variantOverrides":[{"patch":[{"value":"DOTDImagePerspectiveWarper","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}