{"variants":[{"paths":["\/documentation\/dotdocument\/imageperspectivewarper\/error\/localizeddescription"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error","doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/Error-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Error.localizedDescription"},{"type":"text","text":"."}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/localizedDescription"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"metadata":{"symbolKind":"property","title":"localizedDescription","role":"symbol","extendedModule":"Swift","roleHeading":"Instance Property","externalID":"s:s5ErrorP10FoundationE20localizedDescriptionSSvp::SYNTHESIZED::s:11DotDocument22ImagePerspectiveWarperC5ErrorO","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizedDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"DotDocument","relatedModules":["Swift"]}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"8.0","name":"iOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"8.0","name":"iPadOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"8.0","name":"Mac Catalyst","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"10.10","name":"macOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"9.0","name":"tvOS","beta":false},{"deprecated":false,"unavailable":false,"introducedAt":"2.0","name":"watchOS","beta":false}]},"references":{"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error/localizedDescription":{"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/imageperspectivewarper\/error\/localizeddescription","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"localizedDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/localizedDescription","title":"localizedDescription"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error/Error-Implementations":{"title":"Error Implementations","type":"topic","url":"\/documentation\/dotdocument\/imageperspectivewarper\/error\/error-implementations","kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error\/Error-Implementations"},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper/Error":{"url":"\/documentation\/dotdocument\/imageperspectivewarper\/error","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"ImagePerspectiveWarper.Error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper\/Error","role":"symbol","kind":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument/ImagePerspectiveWarper":{"abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"type":"topic","title":"ImagePerspectiveWarper","url":"\/documentation\/dotdocument\/imageperspectivewarper","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImagePerspectiveWarper"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","op":"replace","value":"DOTDImagePerspectiveWarper"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImagePerspectiveWarper\/navigatorTitle","op":"replace","value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}]}]}]}