{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"internalParam","text":"rhs"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/!=(_:_:)"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"Equatable.!=(_:_:)"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/Equatable-Implementations"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@M@DotCore@E@DotFaceModuleId","modules":[{"relatedModules":["Swift"],"name":"DotFaceLite"}],"extendedModule":"Swift","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"role":"symbol","symbolKind":"op","title":"!=(_:_:)","roleHeading":"Operator"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotfacemoduleid\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId":{"abstract":[{"type":"codeVoice","code":"DotFace"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotfacemoduleid","title":"DotFaceModuleId","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/Equatable-Implementations","title":"Equatable Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/equatable-implementations"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/!=(_:_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/!=(_:_:)","title":"!=(_:_:)","kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/!=(_:_:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/title","op":"replace","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/fragments","op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}