{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/localization\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization\/init","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotNfc@objc(cs)DOTNLocalization(im)init","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Localization/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotnfc\/localization\/init"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Localization":{"role":"symbol","title":"Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Localization","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"url":"\/documentation\/dotnfc\/localization"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"kind":"identifier","text":"DOTNLocalization"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}