{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCameraPreviewScaleType) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"languages":["swift"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype"]},{"paths":["\/documentation\/dotfacecore\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fill","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fit"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/native"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/RawRepresentable-Implementations"],"generated":true}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"metadata":{"title":"CameraPreviewScaleType","navigatorTitle":[{"text":"CameraPreviewScaleType","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotFaceCore@E@DOTCameraPreviewScaleType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"kind":"symbol","relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.1.0","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/RawRepresentable-Implementations","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/rawrepresentable-implementations","abstract":[],"role":"collectionGroup","title":"RawRepresentable Implementations","kind":"article","type":"topic"},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/Equatable-Implementations":{"title":"Equatable Implementations","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/Equatable-Implementations","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/equatable-implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/description":{"title":"description","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/description","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/description","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/fit":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fit","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fit"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/fit","title":"CameraPreviewScaleType.fit","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"text":" ","type":"text"},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}]},"doc://com.innovatrics.dot.face.core/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/fill":{"title":"CameraPreviewScaleType.fill","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fill","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/fill","abstract":[{"text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This configuration may produce images with lower resolution (compared to "},{"code":"fit","type":"codeVoice"},{"type":"text","text":" case) during an auto capture process."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fill"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/native":{"title":"native","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/native","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/native","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@AVLayerVideoGravity","kind":"typeIdentifier","text":"AVLayerVideoGravity"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"url":"\/documentation\/dotfacecore\/camerapreviewscaletype","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"CameraPreviewScaleType","kind":"identifier"}],"role":"symbol","title":"CameraPreviewScaleType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}]},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraPreviewScaleType/init(rawValue:)":{"title":"init(rawValue:)","url":"\/documentation\/dotfacecore\/camerapreviewscaletype\/init(rawvalue:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/init(rawValue:)","type":"topic","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTCameraPreviewScaleType"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fill","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraPreviewScaleType\/fit"],"title":"Enumeration Cases"}],"op":"replace"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCameraPreviewScaleType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fit\/title","value":"DOTCameraPreviewScaleTypeFit"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fit\/fragments"},{"op":"replace","value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fill\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType~1fill\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFill"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace"}]}]}