{"seeAlsoSections":[{"title":"Detected face evaluation","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"],"generated":true}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFExpression) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Expression"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFExpression","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotFaceCore"}],"title":"Expression"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression"},"abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/init(eyes:mouth:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/eyes","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/mouth"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/expression"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/expression"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"kind":"symbol","relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH"]}],"references":{"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPose":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPose"}],"url":"\/documentation\/dotfacecore\/headpose","role":"symbol","navigatorTitle":[{"text":"HeadPose","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Head pose evaluation result. Contains evaluated face attributes which represent the head pose of the detected face."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","kind":"symbol","title":"HeadPose"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Wearables":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wearables"}],"url":"\/documentation\/dotfacecore\/wearables","role":"symbol","navigatorTitle":[{"text":"Wearables","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Wearables evaluation result. Contains evaluated face attributes which represent the detected face wearables."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","kind":"symbol","title":"Wearables"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQualityQuery":{"navigatorTitle":[{"text":"FaceQualityQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequalityquery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","title":"FaceQualityQuery","kind":"symbol","abstract":[{"text":"Face quality query specifies which face quality face attributes should be evaluated.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceQualityQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/ExpressionQuery":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"ExpressionQuery"}],"url":"\/documentation\/dotfacecore\/expressionquery","role":"symbol","navigatorTitle":[{"text":"ExpressionQuery","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Expression query specifies which face expression face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","kind":"symbol","title":"ExpressionQuery"},"doc://com.innovatrics.dot.face.core/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facequality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}],"type":"topic","abstract":[{"type":"text","text":"Face quality evaluation result. Contains all the evaluated face attributes which together represent the face quality."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","kind":"symbol","title":"FaceQuality"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQuality":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceImageQuality","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceImageQuality"}],"type":"topic","abstract":[{"text":"Face image quality evaluation result. Contains all the evaluated face attributes which together represent the face image quality.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","kind":"symbol","title":"FaceImageQuality"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Glasses":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Glasses"}],"url":"\/documentation\/dotfacecore\/glasses","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Glasses"}],"type":"topic","abstract":[{"text":"Face attribute for the glasses.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses","kind":"symbol","title":"Glasses"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpression":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyesExpression","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyesexpression","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpression"}],"type":"topic","abstract":[{"text":"Eyes expression evaluation result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","kind":"symbol","title":"EyesExpression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseQuery":{"navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposequery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","title":"HeadPoseQuery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}]},"doc://com.innovatrics.dot.face.core/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Expression"}],"url":"\/documentation\/dotfacecore\/expression","role":"symbol","navigatorTitle":[{"text":"Expression","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face expression evaluation result. Contains evaluated face attributes which represent the face expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression","kind":"symbol","title":"Expression"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageQualityQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FaceImageQualityQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceimagequalityquery","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceImageQualityQuery","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Face image quality query specifies which face image quality face attributes should be evaluated.","type":"text"}],"title":"FaceImageQualityQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/HeadPoseAttribute":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseAttribute"}],"url":"\/documentation\/dotfacecore\/headposeattribute","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}],"type":"topic","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","kind":"symbol","title":"HeadPoseAttribute"},"doc://com.innovatrics.dot.face.core/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression/init(eyes:mouth:)":{"url":"\/documentation\/dotfacecore\/expression\/init(eyes:mouth:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/init(eyes:mouth:)","abstract":[],"type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"eyes"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","text":"EyesExpression","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"mouth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute","text":"FaceAttribute","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"init(eyes:mouth:)","role":"symbol","navigatorTitle":[{"text":"initWithEyes:mouth:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.1.0","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression/mouth":{"navigatorTitle":[{"text":"mouth","kind":"identifier"}],"type":"topic","role":"symbol","title":"mouth","abstract":[{"type":"text","text":"Mouth expression."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/mouth","url":"\/documentation\/dotfacecore\/expression\/mouth","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mouth"},{"text":": ","kind":"text"},{"text":"FaceAttribute","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAspects":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAspects"}],"url":"\/documentation\/dotfacecore\/faceaspects","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAspects"}],"type":"topic","abstract":[{"text":"Face aspects represent various static properties of the face.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","kind":"symbol","title":"FaceAspects"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WearablesQuery":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WearablesQuery"}],"url":"\/documentation\/dotfacecore\/wearablesquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WearablesQuery"}],"type":"topic","abstract":[{"type":"text","text":"Wearables query specifies which wearables face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","kind":"symbol","title":"WearablesQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyesExpressionQuery":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"EyesExpressionQuery"}],"url":"\/documentation\/dotfacecore\/eyesexpressionquery","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyesExpressionQuery"}],"type":"topic","abstract":[{"type":"text","text":"Eyes expression query specifies which eye expression face attributes should be evaluated."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","kind":"symbol","title":"EyesExpressionQuery"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression/description":{"title":"description","kind":"symbol","url":"\/documentation\/dotfacecore\/expression\/description","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/description"},"doc://com.innovatrics.dot.face.core/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Expression/eyes":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/eyes","url":"\/documentation\/dotfacecore\/expression\/eyes","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyesExpression","text":"EyesExpression","kind":"typeIdentifier"}],"type":"topic","title":"eyes","abstract":[{"text":"Eyes expression.","type":"text"}],"navigatorTitle":[{"text":"eyes","kind":"identifier"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAttribute":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"url":"\/documentation\/dotfacecore\/faceattribute","role":"symbol","navigatorTitle":[{"text":"FaceAttribute","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","kind":"symbol","title":"FaceAttribute"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","value":"DOTFExpression","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTFExpression","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFExpression","kind":"identifier"}],"op":"replace"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/description","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/eyes","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/mouth"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Expression\/init(eyes:mouth:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAspects","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQuality","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageQualityQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/HeadPoseQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpression","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyesExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/ExpressionQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Wearables","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WearablesQuery","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Glasses"],"title":"Detected face evaluation","generated":true}]},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFExpression"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/title","op":"replace","value":"DOTFHeadPose"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPose\/fragments","value":[{"text":"DOTFHeadPose","kind":"identifier"}]},{"op":"replace","value":"DOTFWearables","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Wearables\/fragments","value":[{"text":"DOTFWearables","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"value":"DOTFExpressionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1ExpressionQuery\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFExpressionQuery"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/title","op":"replace","value":"DOTFFaceQuality"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFFaceQuality"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceQuality\/fragments"},{"op":"replace","value":"DOTFFaceImageQuality","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQuality\/fragments","value":[{"text":"DOTFFaceImageQuality","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/title","value":"DOTFGlasses"},{"op":"replace","value":[{"text":"DOTFGlasses","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Glasses\/fragments"},{"value":"DOTFEyesExpression","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpression\/fragments","value":[{"text":"DOTFEyesExpression","kind":"identifier"}],"op":"replace"},{"value":"DOTFHeadPoseQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"kind":"identifier","text":"DOTFHeadPoseQuery"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/title","value":"DOTFExpression"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression\/fragments","value":[{"kind":"identifier","text":"DOTFExpression"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title","value":"DOTFFaceImageQualityQuery"},{"op":"replace","value":[{"text":"DOTFFaceImageQualityQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments"},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments","value":[{"text":"DOTFHeadPoseAttribute","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1init(eyes:mouth:)\/title","value":"initWithEyes:mouth:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithEyes:mouth:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1init(eyes:mouth:)\/fragments"},{"op":"replace","value":"mouth","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1mouth\/title"},{"op":"replace","value":[{"kind":"identifier","text":"mouth"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1mouth\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/title","op":"replace","value":"DOTFFaceAspects"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAspects\/fragments","op":"replace","value":[{"text":"DOTFFaceAspects","kind":"identifier"}]},{"value":"DOTFWearablesQuery","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WearablesQuery\/fragments","value":[{"text":"DOTFWearablesQuery","kind":"identifier"}],"op":"replace"},{"value":"DOTFEyesExpressionQuery","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/title"},{"value":[{"kind":"identifier","text":"DOTFEyesExpressionQuery"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyesExpressionQuery\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1description\/fragments","op":"replace"},{"op":"replace","value":"eyes","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1eyes\/title"},{"value":[{"text":"eyes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Expression~1eyes\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace","value":"DOTFFaceAttribute"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}