{"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/documentquality\/description"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentquality\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/description","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality(py)description","modules":[{"name":"DotDocument"}],"symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"text":"description","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentQuality/description":{"title":"description","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotdocument\/documentquality\/description","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"role":"symbol","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentquality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Document quality."}],"title":"DocumentQuality","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"description","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"description","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title","value":"DOTDDocumentQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentQuality"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle","value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace"}]}]}