{"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration"},"variants":[{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/autocaptureconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"AutoCaptureConfiguration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"symbolKind":"class","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","roleHeading":"Class"},"abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo"}],"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)"],"anchor":"Initializers","title":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/isEqual(_:)"],"anchor":"Instance-Methods"},{"title":"Enumerations","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error"],"anchor":"Enumerations"}],"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTAutoCaptureConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/minValidSamplesInRowToStartCandidateSelection":{"title":"minValidSamplesInRowToStartCandidateSelection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/minvalidsamplesinrowtostartcandidateselection","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection. Value must be greater than or equal to "},{"type":"codeVoice","code":"1"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"minValidSamplesInRowToStartCandidateSelection"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/init(minvalidsamplesinrowtostartcandidateselection:candidateselectiondurationmillis:)","title":"init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidSamplesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"role":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/Error":{"type":"topic","title":"AutoCaptureConfiguration.Error","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/Error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/error","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/isEqual(_:)":{"title":"isEqual(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/isEqual(_:)","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/isequal(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/hash":{"title":"hash","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/hash","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/hash","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/description":{"title":"description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/description","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/description","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration/candidateSelectionDurationMillis":{"title":"candidateSelectionDurationMillis","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","url":"\/documentation\/dotfacelite\/autocaptureconfiguration\/candidateselectiondurationmillis","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Duration of candidate selection phase in milliseconds. Value must be greater than or equal to "},{"code":"0","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTAutoCaptureConfiguration","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/candidateSelectionDurationMillis","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/minValidSamplesInRowToStartCandidateSelection"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTAutoCaptureConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"minValidSamplesInRowToStartCandidateSelection","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/title"},{"value":[{"text":"minValidSamplesInRowToStartCandidateSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1minValidSamplesInRowToStartCandidateSelection\/fragments"},{"value":"DOTAutoCaptureConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle"},{"value":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1init(minValidSamplesInRowToStartCandidateSelection:candidateSelectionDurationMillis:)\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1isEqual(_:)\/fragments"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1hash\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1description\/fragments"},{"value":"candidateSelectionDurationMillis","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/title"},{"value":[{"text":"candidateSelectionDurationMillis","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration~1candidateSelectionDurationMillis\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}