{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bezierpathfactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/bezierpathfactory"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"symbolKind":"class","modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","title":"BezierPathFactory","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTBezierPathFactory"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTBezierPathFactory) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BezierPathFactory"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory/createDetectionPath(corners:cornerRadius:)":{"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/bezierpathfactory\/createdetectionpath(corners:cornerradius:)","role":"symbol","type":"topic","title":"createDetectionPath(corners:cornerRadius:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"createDetectionPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createDetectionPathWithCorners:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory":{"url":"\/documentation\/dotfacelite\/bezierpathfactory","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory","type":"topic","navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"title":"BezierPathFactory","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"abstract":[]},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPlaceholderPath"},{"text":"(","kind":"text"},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath","text":"UIBezierPath"}],"navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","title":"createPlaceholderPath(rect:cornerRadius:)","url":"\/documentation\/dotfacelite\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"},"doc://com.innovatrics.dot.face.lite/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTBezierPathFactory","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createDetectionPath(corners:cornerRadius:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)"]}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTBezierPathFactory","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"createDetectionPathWithCorners:cornerRadius:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createDetectionPathWithCorners:cornerRadius:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createDetectionPath(corners:cornerRadius:)\/fragments","op":"replace"},{"value":"DOTBezierPathFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title","value":"createPlaceholderPathWithRect:cornerRadius:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}]}]}]}