{"seeAlsoSections":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CIImageFactory"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/bgrarawimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/bgrarawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTBgraRawImage) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","interfaceLanguage":"swift"},"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/init(bytesPointer:size:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointerPacked","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/size"],"title":"Instance Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","title":"BgraRawImage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage","symbolKind":"class"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"],["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector"]]},"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/bytesPointerPacked":{"url":"\/documentation\/dotfacelite\/bgrarawimage\/bytespointerpacked","title":"bytesPointerPacked","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointerPacked","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"bytesPointerPacked","kind":"identifier"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6UInt32V","text":"UInt32"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"bytesPointerPacked","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/bytesPointer":{"url":"\/documentation\/dotfacelite\/bgrarawimage\/bytespointer","title":"bytesPointer","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointer","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointer"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/bytes":{"abstract":[{"type":"text","text":"Raw image data."}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"title":"bytes","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage\/bytes","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytes","role":"symbol","type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/init(bytesPointer:size:)":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/init(bytesPointer:size:)","abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacelite\/bgrarawimage\/init(bytespointer:size:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"title":"init(bytesPointer:size:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CGImageFactory":{"url":"\/documentation\/dotfacelite\/cgimagefactory","title":"CGImageFactory","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CGImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage/size":{"abstract":[{"type":"text","text":"Image size."}],"role":"symbol","title":"size","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/size","navigatorTitle":[{"text":"size","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage\/size"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImageFactory":{"url":"\/documentation\/dotfacelite\/bgrarawimagefactory","title":"BgraRawImageFactory","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"role":"symbol","title":"FaceDetector"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.face.lite/@M@DotFaceLite@objc(pl)_RawImage":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/@M@DotFaceLite@objc(pl)_RawImage","type":"unresolvable","title":"_RawImage"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/CIImageFactory":{"url":"\/documentation\/dotfacelite\/ciimagefactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CIImageFactory","role":"symbol","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"kind":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"title":"BgraRawImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgraRawImage"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/bytesPointerPacked","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage\/init(bytesPointer:size:)"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/@M@DotFaceLite@objc(pl)_RawImage"]}],"path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImageFactory","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/CIImageFactory"],"title":"Converting images","generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgraRawImage"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]}},{"value":"bytesPointerPacked","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointerPacked\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointerPacked\/fragments","value":[{"text":"bytesPointerPacked","kind":"identifier"}]},{"value":"bytesPointer","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointer\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytesPointer\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"bytes","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1bytes\/fragments","value":[{"kind":"identifier","text":"bytes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1init(bytesPointer:size:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CGImageFactory\/title"},{"value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CGImageFactory\/fragments"},{"value":"size","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1size\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage~1size\/fragments","value":[{"kind":"identifier","text":"size"}],"op":"replace"},{"value":"DOTBgraRawImageFactory","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImageFactory\/fragments","op":"replace","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1CIImageFactory\/fragments","value":[{"text":"DOTCIImageFactory","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title","value":"DOTBgraRawImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}]}]}