{"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","type":"conformsTo"}],"metadata":{"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory","title":"BgraRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImageFactory"}],"symbolKind":"class"},"seeAlsoSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"],"title":"Converting images"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTBgraRawImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImageFactory"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory"]},{"paths":["\/documentation\/dotfacelite\/bgrarawimagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory/create(ciImage:ciContext:)":{"role":"symbol","abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(ciImage:ciContext:)","title":"create(ciImage:ciContext:)","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier","text":"CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrarawimagefactory\/create(ciimage:cicontext:)","navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}]},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory":{"navigatorTitle":[{"text":"CIImageFactory","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/ciimagefactory","title":"CIImageFactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" from ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" or ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory":{"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimagefactory","title":"BgraRawImageFactory","role":"symbol","abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory/create(cgImage:)":{"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage"}],"type":"topic","title":"create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(cgImage:)","role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimagefactory\/create(cgimage:)"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 8.6.0","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory":{"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"title":"CGImageFactory","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cgimagefactory","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"title":"BgraRawImage","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","type":"topic","kind":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgraRawImageFactory"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"replace","value":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"]}]},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTBgraRawImageFactory"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"createWithCiImage:ciContext:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/title","op":"replace","value":"DOTCIImageFactory"},{"value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createWithCgImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory~1create(cgImage:)\/fragments"},{"value":"DOTCGImageFactory","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/title"},{"value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/fragments"},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"}]}]}