{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/init(bytesPointer:size:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/size"]}],"variants":[{"paths":["\/documentation\/dotfacelite\/bgrrawimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/bgrrawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTBgrRawImage) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","role":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"title":"BgrRawImage","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTBgrRawImage"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"]}],"references":{"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage":{"title":"BgrRawImage","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage","role":"symbol","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrrawimage"},"doc://com.innovatrics.dot.face.lite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage/init(bytesPointer:size:)":{"abstract":[{"text":"Do not use this, use ","type":"text"},{"code":"BgrRawImageFactory","type":"codeVoice"},{"text":" to create ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":".","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrrawimage\/init(bytespointer:size:)","title":"init(bytesPointer:size:)","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"kind":"text","text":">, "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/init(bytesPointer:size:)"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage/bytes":{"abstract":[{"text":"Raw image data.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"bytes","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrrawimage\/bytes","title":"bytes","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytes"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage/size":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/size","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"size"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrrawimage\/size","title":"size","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"size","kind":"identifier"},{"text":": ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTImageSize"}],"abstract":[{"text":"Image size.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/@M@DotFaceLite@objc(pl)_RawImage":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/@M@DotFaceLite@objc(pl)_RawImage","title":"_RawImage","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","kind":"symbol","abstract":[{"text":"version: 8.3.1","type":"text"}]},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgrRawImage/bytesPointer":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytesPointer","role":"symbol","navigatorTitle":[{"text":"bytesPointer","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/bgrrawimage\/bytespointer","title":"bytesPointer","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:s5UInt8V","kind":"typeIdentifier","text":"UInt8"},{"kind":"text","text":">"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTBgrRawImage","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTBgrRawImage","kind":"identifier"}]},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytes","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/bytesPointer","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgrRawImage\/init(bytesPointer:size:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/@M@DotFaceLite@objc(pl)_RawImage"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTBgrRawImage","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1init(bytesPointer:size:)\/title","value":"initWithBytesPointer:size:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1init(bytesPointer:size:)\/fragments"},{"value":"bytes","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytes\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytes\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1size\/title","op":"replace","value":"size"},{"value":[{"text":"size","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1size\/fragments"},{"value":"bytesPointer","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytesPointer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgrRawImage~1bytesPointer\/fragments","value":[{"kind":"identifier","text":"bytesPointer"}]}]}]}