{"sections":[],"seeAlsoSections":[{"title":"Validators","anchor":"Validators","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"]}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"},"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init(threshold:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/threshold"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/defaultThreshold"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLBrightnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}]}]},{"content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"type":"paragraph","inlineContent":[{"text":"To use this validator also following validators must be applied: ","type":"text"},{"code":"FaceOutOfBoundsValidator","type":"codeVoice"},{"text":".","type":"text"}]}],"kind":"content"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"variants":[{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/brightnesstoolowvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"roleHeading":"Class","title":"BrightnessTooLowValidator","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLBrightnessTooLowValidator"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/dependencyIdentifiers":{"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","role":"symbol","title":"SizeTooSmallValidator","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"role":"symbol","title":"BrightnessTooLowValidator"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"role":"symbol","title":"SizeTooLargeValidator"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/identifier":{"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/identifier","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol","title":"identifier"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/init(threshold:)":{"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init(threshold:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init(threshold:)","title":"init(threshold:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"text":"Initialize with default threshold.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init()","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/init()","title":"init()","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"navigatorTitle":[{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","title":"FaceOutOfBoundsValidator","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected face."}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"role":"symbol","title":"SharpnessTooLowValidator"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/defaultThreshold":{"abstract":[{"text":"Default threshold value.","type":"text"}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/defaultthreshold","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/defaultThreshold","type":"topic","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"role":"symbol","title":"defaultThreshold"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/threshold":{"navigatorTitle":[{"text":"threshold","kind":"identifier"}],"abstract":[{"text":"Current minimal accepted brightness.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/threshold","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/threshold","title":"threshold","role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"role":"symbol","title":"BrightnessTooHighValidator"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","navigatorTitle":[{"text":"FaceNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceNotDetectedValidator","kind":"identifier"}],"abstract":[{"text":"Validates confidence of the detected face.","type":"text"}],"role":"symbol","title":"FaceNotDetectedValidator"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator":{"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureFrameParametersValidator"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"navigatorTitle":[{"text":"FaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","role":"symbol","title":"FaceAutoCaptureFrameParametersValidator","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator/validate(faceAutoCaptureFrameParameters:)":{"navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"abstract":[{"text":"Validate brightness of the detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator\/validate(faceautocaptureframeparameters:)","title":"validate(faceAutoCaptureFrameParameters:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLBrightnessTooLowValidator"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/threshold"],"anchor":"Instance-Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/init(threshold:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)"]},{"title":"Type Properties","anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator\/defaultThreshold"]}]},{"value":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"anchor":"Validators"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","op":"replace","value":"DOTFLSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","op":"replace","value":"DOTFLBrightnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}]},{"op":"replace","value":"DOTFLSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title"},{"op":"replace","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/navigatorTitle"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1identifier\/title"},{"op":"replace","value":[{"text":"identifier","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1identifier\/fragments"},{"value":"initWithThreshold:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init(threshold:)\/title","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init(threshold:)\/fragments"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title","value":"DOTFLFaceOutOfBoundsValidator"},{"op":"replace","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTFLFaceOutOfBoundsValidator","kind":"identifier"}]},{"op":"replace","value":"DOTFLSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1defaultThreshold\/title","op":"replace","value":"defaultThreshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1defaultThreshold\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}]},{"op":"replace","value":"threshold","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1threshold\/title"},{"op":"replace","value":[{"text":"threshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1threshold\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","value":"DOTFLBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments","value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/navigatorTitle","value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","value":"DOTFLFaceNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/title","value":"DOTFLFaceAutoCaptureFrameParametersValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParametersValidator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1validate(faceAutoCaptureFrameParameters:)\/title","value":"validateWithFaceAutoCaptureFrameParameters:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}