{"sections":[],"metadata":{"roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"externalID":"c:@M@DotCamera@E@DOTCameraPreviewScaleType","modules":[{"name":"DotFaceLite"}],"title":"CameraPreviewScaleType","symbolKind":"enum","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"role":"symbol"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fill","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fit"]},{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/native"]},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/RawRepresentable-Implementations"]}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/camerapreviewscaletype"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTCameraPreviewScaleType) ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotFaceLite\/SY"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/equatable-implementations","type":"topic","kind":"article","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/init(rawValue:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/init(rawValue:)","url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/init(rawvalue:)","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/fill":{"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fill","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/fill","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fill","title":"CameraPreviewScaleType.fill","abstract":[{"type":"text","text":"Entire preview layer is filled with video frame content. Video frame is centered and may extend beyond the preview layer bounds."},{"text":" ","type":"text"},{"text":"This configuration may produce images with lower resolution (compared to ","type":"text"},{"type":"codeVoice","code":"fit"},{"text":" case) during an auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"role":"symbol","title":"CameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraPreviewScaleType"}],"abstract":[{"type":"text","text":"Indicates how the layer displays video frames."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/native":{"type":"topic","url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/native","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"native","kind":"identifier"},{"kind":"text","text":": "},{"text":"AVLayerVideoGravity","kind":"typeIdentifier","preciseIdentifier":"c:@T@AVLayerVideoGravity"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/native","title":"native","abstract":[],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","role":"collectionGroup","abstract":[],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/rawrepresentable-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/RawRepresentable-Implementations","type":"topic","kind":"article"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/description":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/description","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/description","type":"topic","title":"description"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType/fit":{"role":"symbol","url":"\/documentation\/dotfacelite\/camerapreviewscaletype\/fit","abstract":[{"type":"text","text":"Entire video frame is displayed. Video frame is centered and fits within the preview layer bounds."},{"type":"text","text":" "},{"type":"text","text":"The preview layer may contain empty vertical or horizontal regions. This is recommended configuration, becuase it maximizes resolution of images captured during an auto capture process."}],"title":"CameraPreviewScaleType.fit","type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"fit","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fit","kind":"symbol","navigatorTitle":[{"text":"DOTCameraPreviewScaleTypeFit","kind":"identifier"}]},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTCameraPreviewScaleType","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"DOTCameraPreviewScaleType","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fill","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType\/fit"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTCameraPreviewScaleType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"DOTCameraPreviewScaleTypeFill","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fill\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fill\/fragments","value":[{"text":"DOTCameraPreviewScaleTypeFill","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","value":"DOTCameraPreviewScaleType"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fit\/title","value":"DOTCameraPreviewScaleTypeFit","op":"replace"},{"value":[{"kind":"identifier","text":"DOTCameraPreviewScaleTypeFit"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType~1fit\/fragments","op":"replace"}]}]}