{"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","interfaceLanguage":"swift"},"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"type":"conformsTo"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"Corners","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTCorners","role":"symbol","symbolKind":"class","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCorners) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/corners"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/corners"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"],"title":"Initializers"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomLeft","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomRight","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/hash","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/points","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topLeft","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topRight"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/mirrored()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/from(rectangle:)"],"title":"Type Methods"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/topLeft":{"title":"topLeft","kind":"symbol","abstract":[{"text":"Top left corner point.","type":"text"}],"url":"\/documentation\/dotfacelite\/corners\/topleft","type":"topic","navigatorTitle":[{"text":"topLeft","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topLeft","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/hash":{"title":"hash","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/corners\/hash","type":"topic","navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/hash","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/rebased(parentRectangle:)":{"title":"rebased(parentRectangle:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/corners\/rebased(parentrectangle:)","type":"topic","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/rebased(parentRectangle:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners"}]},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/mirrored()":{"url":"\/documentation\/dotfacelite\/corners\/mirrored()","kind":"symbol","title":"mirrored()","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/mirrored()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble"},{"text":")","kind":"text"}],"title":"init(topLeft:topRight:bottomRight:bottomLeft:)","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/corners\/init(topleft:topright:bottomright:bottomleft:)","type":"topic","role":"symbol","abstract":[],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/SH":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/bottomRight":{"title":"bottomRight","kind":"symbol","abstract":[{"text":"Bottom right corner point.","type":"text"}],"url":"\/documentation\/dotfacelite\/corners\/bottomright","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomRight","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bottomRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/description":{"title":"description","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/corners\/description","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/from(rectangle:)":{"title":"from(rectangle:)","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/corners\/from(rectangle:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/from(rectangle:)","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rectangle"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Corners","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTCorners","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/bottomLeft":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/corners\/bottomleft","title":"bottomLeft","abstract":[{"type":"text","text":"Bottom left corner point."}],"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomLeft"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/topRight":{"kind":"symbol","abstract":[{"text":"Top right corner point.","type":"text"}],"url":"\/documentation\/dotfacelite\/corners\/topright","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"role":"symbol","title":"topRight","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topRight","navigatorTitle":[{"kind":"identifier","text":"topRight"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/isEqual(_:)":{"title":"isEqual(_:)","abstract":[],"kind":"symbol","url":"\/documentation\/dotfacelite\/corners\/isequal(_:)","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/isEqual(_:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"role":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}],"url":"\/documentation\/dotfacelite\/corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"title":"Corners"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/Corners/points":{"title":"points","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/corners\/points","type":"topic","navigatorTitle":[{"text":"points","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/points","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"text":"PointDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"DOTCorners","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCorners","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomLeft","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/bottomRight","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/hash","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/points","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topLeft","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/topRight"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/isEqual(_:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/mirrored()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/rebased(parentRectangle:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/Corners\/from(rectangle:)"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"DOTCorners","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1topLeft\/title","op":"replace","value":"topLeft"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1topLeft\/fragments","op":"replace","value":[{"text":"topLeft","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1hash\/title","value":"hash"},{"op":"replace","value":[{"kind":"identifier","text":"hash"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1hash\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1rebased(parentRectangle:)\/fragments"},{"value":"mirrored","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1mirrored()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments"},{"value":"bottomRight","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomRight\/title"},{"value":[{"text":"bottomRight","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomRight\/fragments"},{"value":"description","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1description\/fragments"},{"value":"fromRectangle:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1from(rectangle:)\/title","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromRectangle:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1from(rectangle:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomLeft\/title","value":"bottomLeft"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1bottomLeft\/fragments","value":[{"kind":"identifier","text":"bottomLeft"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1topRight\/title","value":"topRight","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1topRight\/fragments","op":"replace","value":[{"text":"topRight","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1isEqual(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1isEqual(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/title","value":"DOTCorners","op":"replace"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1points\/title","value":"points"},{"value":[{"kind":"identifier","text":"points"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1Corners~1points\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}