{"abstract":[{"code":"DotDocument","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"type":"conformsTo","kind":"relationships"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotdocumentmoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Enumeration","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"title":"DotDocumentModuleId","navigatorTitle":[{"text":"DotDocumentModuleId","kind":"identifier"}],"symbolKind":"enum","externalID":"c:@M@DotCore@E@DotDocumentModuleId","role":"symbol"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"languages":["swift"]}],"kind":"declarations"}],"topicSections":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/barcode"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/init(rawValue:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/description"]},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/RawRepresentable-Implementations"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/Equatable-Implementations":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/equatable-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/Equatable-Implementations","title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/rawrepresentable-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/barcode":{"title":"DotDocumentModuleId.barcode","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/barcode","type":"topic","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/barcode","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"}]},"doc://DotFaceLite/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SY"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/description":{"abstract":[],"url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/description","title":"description","type":"topic","kind":"symbol","role":"symbol"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid\/init(rawvalue:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/init(rawValue:)","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotDocumentModuleId":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"abstract":[{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":" feature module identifier."}],"title":"DotDocumentModuleId","url":"\/documentation\/dotfacelite\/dotdocumentmoduleid","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"role":"symbol"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotDocumentModuleId\/barcode"],"generated":true,"title":"Enumeration Cases"}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId~1barcode\/title","op":"replace","value":"DotDocumentModuleIdBarcode"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId~1barcode\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleIdBarcode"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotDocumentModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotDocumentModuleId"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}