{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfigurationBalanced"},"abstract":[{"type":"text","text":"Face detection balanced module."}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration"]}],"metadata":{"roleHeading":"Class","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"title":"DotFaceDetectionModuleConfigurationBalanced","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfigurationBalanced","modules":[{"name":"DotFaceLite"}]},"kind":"symbol","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfigurationBalanced\/init"],"generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfigurationBalanced","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","kind":"typeIdentifier"}],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacedetectionmoduleconfigurationbalanced"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfiguration":{"type":"topic","role":"symbol","title":"DotFaceDetectionModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfiguration","kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfigurationBalanced":{"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfigurationbalanced","type":"topic","abstract":[{"text":"Face detection balanced module.","type":"text"}],"role":"symbol","kind":"symbol","title":"DotFaceDetectionModuleConfigurationBalanced","fragments":[{"kind":"identifier","text":"DotFaceDetectionModuleConfigurationBalanced"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfigurationBalanced"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceDetectionModuleConfigurationBalanced/init":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceDetectionModuleConfigurationBalanced\/init","kind":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"type":"topic","title":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotfacedetectionmoduleconfigurationbalanced\/init"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}