{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"title":"Conforms To"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"metadata":{"externalID":"c:@M@DotCore@E@DotFaceModuleId","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"enum","roleHeading":"Enumeration","title":"DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}]},"sections":[],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionFast","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/verification"],"generated":true,"title":"Enumeration Cases","anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/description"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/backgroundUniformity":{"navigatorTitle":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/backgroundUniformity","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/dotfacemoduleid\/backgrounduniformity","title":"DotFaceModuleId.backgroundUniformity","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/detectionFast":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/detectionfast","title":"DotFaceModuleId.detectionFast","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionFast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/RawRepresentable-Implementations":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/RawRepresentable-Implementations","kind":"article","abstract":[],"role":"collectionGroup","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/rawrepresentable-implementations","title":"RawRepresentable Implementations"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacemoduleid","title":"DotFaceModuleId","abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/verification":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/verification","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/verification","title":"DotFaceModuleId.verification","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verification","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/expressionNeutral":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"abstract":[],"title":"DotFaceModuleId.expressionNeutral","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/expressionNeutral","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}],"url":"\/documentation\/dotfacelite\/dotfacemoduleid\/expressionneutral"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/detectionBalanced":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/detectionbalanced","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionBalanced","title":"DotFaceModuleId.detectionBalanced","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detectionBalanced","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/Equatable-Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/equatable-implementations","kind":"article"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/init(rawValue:)":{"title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/init(rawValue:)","abstract":[],"url":"\/documentation\/dotfacelite\/dotfacemoduleid\/init(rawvalue:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/passiveLiveness":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/passiveLiveness","kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness"}],"type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/dotfacemoduleid\/passiveliveness","title":"DotFaceModuleId.passiveLiveness","role":"symbol"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/eyeGazeLiveness":{"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdEyeGazeLiveness"}],"url":"\/documentation\/dotfacelite\/dotfacemoduleid\/eyegazeliveness","kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/eyeGazeLiveness","title":"DotFaceModuleId.eyeGazeLiveness"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceModuleId/description":{"kind":"symbol","role":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/description","url":"\/documentation\/dotfacelite\/dotfacemoduleid\/description","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleId","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/detectionFast","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceModuleId\/verification"],"generated":true,"anchor":"Enumeration-Cases"}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotFaceModuleIdBackgroundUniformity","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1backgroundUniformity\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1backgroundUniformity\/fragments"},{"op":"replace","value":"DotFaceModuleIdDetectionFast","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1detectionFast\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1detectionFast\/fragments"},{"op":"replace","value":"DotFaceModuleId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/title"},{"op":"replace","value":[{"text":"DotFaceModuleId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId\/navigatorTitle"},{"op":"replace","value":"DotFaceModuleIdVerification","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1verification\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1verification\/fragments"},{"op":"replace","value":"DotFaceModuleIdExpressionNeutral","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1expressionNeutral\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1expressionNeutral\/fragments"},{"op":"replace","value":"DotFaceModuleIdDetectionBalanced","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1detectionBalanced\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1detectionBalanced\/fragments"},{"op":"replace","value":"DotFaceModuleIdPassiveLiveness","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1passiveLiveness\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleIdPassiveLiveness"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1passiveLiveness\/fragments"},{"op":"replace","value":"DotFaceModuleIdEyeGazeLiveness","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1eyeGazeLiveness\/title"},{"op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceModuleId~1eyeGazeLiveness\/fragments"}]}]}