{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelibraryconfiguration"]}],"abstract":[{"type":"text","text":"Face library configuration."}],"sections":[],"metadata":{"role":"symbol","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"topicSections":[{"generated":true,"title":"Classes","anchor":"Classes","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class"]},{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"]},{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/modules-swift.property"]}],"references":{"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/init(modules:)":{"abstract":[],"kind":"symbol","role":"symbol","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(modules:)","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/init(modules:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/faceDetectionConfidenceThreshold":{"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Face detection confidence threshold. Faces with a confidence lower than threshold are ignored. Value in interval "},{"code":"[0.0, 1.0]","type":"codeVoice"},{"type":"text","text":". Default value is "},{"code":"0.06","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/facedetectionconfidencethreshold","title":"faceDetectionConfidenceThreshold","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceDetectionConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"type":"text","text":"version: 9.0.1"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/init(modules:faceDetectionConfidenceThreshold:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/init(modules:facedetectionconfidencethreshold:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":", "},{"kind":"externalParam","text":"faceDetectionConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}],"type":"topic","abstract":[],"title":"init(modules:faceDetectionConfidenceThreshold:)"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration":{"abstract":[{"text":"Face library configuration.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration","kind":"symbol","title":"DotFaceLibraryConfiguration","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"type":"topic","abstract":[{"text":"Face library module configuration.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"title":"DotFaceLibraryConfiguration.Modules"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLibraryConfiguration/modules-swift.property":{"abstract":[{"type":"text","text":"Module configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/modules-swift.property","navigatorTitle":[{"text":"modules","kind":"identifier"}],"role":"symbol","title":"modules","kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC"}],"url":"\/documentation\/dotfacelite\/dotfacelibraryconfiguration\/modules-swift.property"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/faceDetectionConfidenceThreshold","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/modules-swift.property"],"anchor":"Instance-Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLibraryConfiguration\/init(modules:faceDetectionConfidenceThreshold:)"],"anchor":"Instance-Methods","generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":[{"type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1init(modules:)\/title","op":"replace","value":"initWithModules:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1init(modules:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/title","op":"replace","value":"faceDetectionConfidenceThreshold"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1faceDetectionConfidenceThreshold\/fragments","op":"replace","value":[{"text":"faceDetectionConfidenceThreshold","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/title","op":"replace","value":"initWithModules:faceDetectionConfidenceThreshold:error:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1init(modules:faceDetectionConfidenceThreshold:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:faceDetectionConfidenceThreshold:error:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1modules-swift.property\/title","op":"replace","value":"modules"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLibraryConfiguration~1modules-swift.property\/fragments","op":"replace","value":[{"text":"modules","kind":"identifier"}]}]}]}