{"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"},"sections":[],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotFaceLiteLibrary","symbolKind":"class","role":"symbol","title":"DotFaceLiteLibrary","navigatorTitle":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"roleHeading":"Class"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/init()"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/id"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/deinitialize()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/initialize(license:)"],"title":"Instance Methods"},{"title":"Enumerations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/Error"]}],"seeAlsoSections":[{"title":"Global components","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfacelitelibrary"]}],"abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":" library initialization."}],"references":{"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/init()":{"url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/init()","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/init()","title":"init()","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/Error":{"kind":"symbol","title":"DotFaceLiteLibrary.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"role":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/error","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/Error","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"type":"topic"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/id":{"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/id","role":"symbol","abstract":[{"type":"text","text":"The library identifier."}],"title":"id","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/id","navigatorTitle":[{"kind":"identifier","text":"id"}]},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/deinitialize()":{"kind":"symbol","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/deinitialize()","abstract":[{"text":"Deinitialize library.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/deinitialize()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"title":"deinitialize()"},"doc://DotFaceLite/documentation/DotFaceLite/Logger":{"navigatorTitle":[{"text":"Logger","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","title":"Logger","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Logger","kind":"identifier"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/logger"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 8.14.0"}],"title":"DotFaceLite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"title":"DotLibrary","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"abstract":[],"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibrary","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"symbol","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary":{"kind":"symbol","title":"DotFaceLiteLibrary","navigatorTitle":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFaceLite"},{"text":" library initialization.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"title":"Localization","url":"\/documentation\/dotfacelite\/localization","role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary/initialize(license:)":{"title":"initialize(license:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/initialize(license:)","role":"symbol","abstract":[{"text":"Initialize library with license.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotfacelitelibrary\/initialize(license:)"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DotFaceLiteLibrary","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLiteLibrary"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/id"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/deinitialize()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary\/initialize(license:)"],"title":"Instance Methods"}],"path":"\/topicSections"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"],"generated":true,"title":"Global components"}],"op":"replace"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibrary"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1init()\/title","op":"replace","value":"init"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1id\/fragments","value":[{"text":"id","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1deinitialize()\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}],"op":"replace"},{"op":"replace","value":"DOTFLLogger","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/fragments","op":"replace","value":[{"text":"DOTFLLogger","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DotFaceLiteLibrary","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title"},{"value":[{"kind":"identifier","text":"DotFaceLiteLibrary"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","op":"replace"},{"value":"DOTFLLocalization","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title"},{"value":[{"text":"DOTFLLocalization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary~1initialize(license:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initializeWithLicense:error:","kind":"identifier"}],"op":"replace"}]}]}