{"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/deinitialize()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/initialize(license:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotLibrary","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibrary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotlibrary"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"],"title":"Conforming Types","type":"conformingTypes"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary","symbolKind":"protocol","roleHeading":"Protocol"},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"text":"version: 8.12.1","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary/deinitialize()":{"required":true,"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibrary\/deinitialize()","role":"symbol","title":"deinitialize()","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/deinitialize()","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary/id":{"kind":"symbol","type":"topic","required":true,"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"id"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"id"}],"title":"id","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/id","url":"\/documentation\/dotfacelite\/dotlibrary\/id","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary/initialize(license:)":{"kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"required":true,"type":"topic","url":"\/documentation\/dotfacelite\/dotlibrary\/initialize(license:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/initialize(license:)","title":"initialize(license:)"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"url":"\/documentation\/dotfacelite\/dotlibrary","role":"symbol","title":"DotLibrary","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLiteLibrary","kind":"identifier"}],"title":"DotFaceLiteLibrary","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","url":"\/documentation\/dotfacelite\/dotfacelitelibrary","type":"topic","role":"symbol","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":" library initialization.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibrary"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotLibrary","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotLibrary"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/id"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/deinitialize()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/initialize(license:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibrary","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1deinitialize()\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1deinitialize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1id\/title","value":"id"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1id\/fragments","value":[{"kind":"identifier","text":"id"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1initialize(license:)\/title","op":"replace","value":"initializeWithLicense:error:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1initialize(license:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments","value":[{"kind":"identifier","text":"DotLibrary"}]},{"value":"DotFaceLiteLibrary","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]}]}]}