{"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(pl)DotSdkLicenseProxyProtocol","roleHeading":"Protocol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","title":"DotSdkLicenseProxyProtocol","symbolKind":"protocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"],"type":"conformingTypes","kind":"relationships","title":"Conforming Types"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"title":"DotSdkLicenseProxyProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","kind":"symbol","type":"topic","title":"isFacePassiveLivenessEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFacePassiveLivenessEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","role":"symbol","abstract":[],"required":true},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"kind":"symbol","title":"DotSdkLicenseProxy","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"title":"isFaceMatchingEnabled","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfacematchingenabled","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"abstract":[],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isFaceEyeGazeLivenessScoreEnabled","kind":"symbol","navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"abstract":[],"required":true,"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/licenseBytes":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"licenseBytes"}],"kind":"symbol","title":"licenseBytes","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/licenseBytes","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/licensebytes","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"licenseBytes"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"}],"required":true,"role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceLiteEnabled"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isFaceLiteEnabled","navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"abstract":[],"required":true,"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceliteenabled"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"abstract":[],"title":"isRealTimeTransactionReportingEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"type":"topic","required":true},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isFaceEnabled":{"required":true,"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isfaceenabled","kind":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isFaceEnabled"}],"role":"symbol","title":"isFaceEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isEvaluation":{"required":true,"type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEvaluation"}],"title":"isEvaluation","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isEvaluation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isEvaluation","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isevaluation","role":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isdocumentenabled","role":"symbol","title":"isDocumentEnabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDocumentEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"type":"topic","abstract":[],"required":true},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol/isNfcEnabled":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isNfcEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isNfcEnabled","abstract":[],"required":true,"role":"symbol","navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol\/isnfcenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isNfcEnabled","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"],"type":"conformingTypes","title":"Conforming Types"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title","value":"isFacePassiveLivenessEnabled","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments","value":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title","value":"DotSdkLicenseProxy","op":"replace"},{"value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments"},{"op":"replace","value":"isFaceMatchingEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"isFaceEyeGazeLivenessScoreEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments","value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"value":[{"kind":"identifier","text":"licenseBytes"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments","op":"replace"},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title"},{"value":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments"},{"value":"isRealTimeTransactionReportingEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title","value":"isFaceEnabled"},{"value":[{"kind":"identifier","text":"isFaceEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isEvaluation\/title","value":"isEvaluation"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments","value":[{"kind":"identifier","text":"isEvaluation"}],"op":"replace"},{"value":"isDocumentEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments","value":[{"text":"isDocumentEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","value":"isNfcEnabled","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments","value":[{"kind":"identifier","text":"isNfcEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}