{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(cs)DotSdkLicenseProxy","roleHeading":"Class","symbolKind":"class","title":"DotSdkLicenseProxy","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxy"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxy"}]},"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/licenseBytes"],"title":"Instance Properties"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy"]},{"paths":["\/documentation\/dotfacelite\/dotsdklicenseproxy"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceMatchingEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isFaceMatchingEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfacematchingenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceMatchingEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isNfcEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isNfcEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isnfcenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isNfcEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isNfcEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isNfcEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isEvaluation":{"abstract":[],"role":"symbol","type":"topic","title":"isEvaluation","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isevaluation","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isEvaluation","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEvaluation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 8.3.2"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceLiteEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isFaceLiteEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceliteenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceLiteEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceLiteEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","role":"symbol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"abstract":[]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isFaceEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFaceEyeGazeLivenessScoreEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isFaceEyeGazeLivenessScoreEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfaceeyegazelivenessscoreenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isDocumentEnabled":{"role":"symbol","title":"isDocumentEnabled","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isdocumentenabled","kind":"symbol","type":"topic","navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isDocumentEnabled","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/licenseBytes":{"abstract":[],"role":"symbol","type":"topic","title":"licenseBytes","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/licensebytes","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/licenseBytes","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isRealTimeTransactionReportingEnabled":{"abstract":[],"role":"symbol","type":"topic","title":"isRealTimeTransactionReportingEnabled","kind":"symbol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isrealtimetransactionreportingenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy":{"role":"symbol","title":"DotSdkLicenseProxy","url":"\/documentation\/dotfacelite\/dotsdklicenseproxy","kind":"symbol","type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxy","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdkLicenseProxy/isFacePassiveLivenessEnabled":{"type":"topic","role":"symbol","title":"isFacePassiveLivenessEnabled","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacelite\/dotsdklicenseproxy\/isfacepassivelivenessenabled","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"isFacePassiveLivenessEnabled"}]},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DotSdkLicenseProxy"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isDocumentEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isEvaluation","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceLiteEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFaceMatchingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isFacePassiveLivenessEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isNfcEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxy\/licenseBytes"]}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxy","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/title","op":"replace","value":"isFaceMatchingEnabled"},{"value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceMatchingEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isNfcEnabled\/title","value":"isNfcEnabled"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isNfcEnabled\/fragments","value":[{"text":"isNfcEnabled","kind":"identifier"}]},{"value":"isEvaluation","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isEvaluation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isEvaluation\/fragments","value":[{"text":"isEvaluation","kind":"identifier"}]},{"value":"isFaceLiteEnabled","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceLiteEnabled\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceLiteEnabled\/fragments","op":"replace","value":[{"text":"isFaceLiteEnabled","kind":"identifier"}]},{"value":"DotSdkLicenseProxyProtocol","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEnabled\/title","value":"isFaceEnabled"},{"value":[{"kind":"identifier","text":"isFaceEnabled"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEnabled\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/title","value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace"},{"value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFaceEyeGazeLivenessScoreEnabled\/fragments"},{"value":"isDocumentEnabled","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isDocumentEnabled\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isDocumentEnabled\/fragments","value":[{"kind":"identifier","text":"isDocumentEnabled"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1licenseBytes\/title","value":"licenseBytes","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1licenseBytes\/fragments","value":[{"kind":"identifier","text":"licenseBytes"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/title","op":"replace","value":"isRealTimeTransactionReportingEnabled"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isRealTimeTransactionReportingEnabled\/fragments","value":[{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"}],"op":"replace"},{"value":"DotSdkLicenseProxy","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy\/fragments","value":[{"text":"DotSdkLicenseProxy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/title","value":"isFacePassiveLivenessEnabled"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdkLicenseProxy~1isFacePassiveLivenessEnabled\/fragments","value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"op":"replace"}]}]}