{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLFaceAutoCaptureControllerConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"title":"FaceAutoCaptureControllerConfiguration","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureControllerConfiguration","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"topicSections":[{"title":"Structures","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Defaults"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/candidateSelectionDurationMillis","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/detectionNormalizedRectangle","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/minValidFramesInRowToStartCandidateSelection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/validators"]},{"title":"Enumerations","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error"]}],"references":{"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"role":"symbol","title":"FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller"},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)":{"role":"symbol","title":"init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/init(minvalidframesinrowtostartcandidateselection:candidateselectiondurationmillis:detectionnormalizedrectangle:validators:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Error":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/error"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/minValidFramesInRowToStartCandidateSelection":{"role":"symbol","title":"minValidFramesInRowToStartCandidateSelection","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minValidFramesInRowToStartCandidateSelection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Minimum number of valid frames in a row to start candidate selection. Default is 2."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/minValidFramesInRowToStartCandidateSelection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minValidFramesInRowToStartCandidateSelection"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/minvalidframesinrowtostartcandidateselection"},"doc://com.innovatrics.dot.face.lite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/detectionNormalizedRectangle":{"role":"symbol","title":"detectionNormalizedRectangle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the face detection."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/detectionNormalizedRectangle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"detectionNormalizedRectangle"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/detectionnormalizedrectangle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/Defaults":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration.Defaults","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/Defaults","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/defaults"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 6.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/description"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/candidateSelectionDurationMillis":{"role":"symbol","title":"candidateSelectionDurationMillis","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Duration of candidate selection phase. Default is 1000."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/candidateSelectionDurationMillis","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/candidateselectiondurationmillis"},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration/validators":{"role":"symbol","title":"validators","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FaceAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of validators which will be used to validate the face detection result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/validators","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validators"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration\/validators"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureControllerConfiguration":{"role":"symbol","title":"FaceAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the face auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontrollerconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLFaceAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/candidateSelectionDurationMillis","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/description","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/detectionNormalizedRectangle","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/minValidFramesInRowToStartCandidateSelection","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/validators"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureControllerConfiguration\/init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)\/title","value":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1init(minValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithMinValidFramesInRowToStartCandidateSelection:candidateSelectionDurationMillis:detectionNormalizedRectangle:validators:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1minValidFramesInRowToStartCandidateSelection\/title","value":"minValidFramesInRowToStartCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1minValidFramesInRowToStartCandidateSelection\/fragments","value":[{"kind":"identifier","text":"minValidFramesInRowToStartCandidateSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1detectionNormalizedRectangle\/title","value":"detectionNormalizedRectangle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1detectionNormalizedRectangle\/fragments","value":[{"kind":"identifier","text":"detectionNormalizedRectangle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1candidateSelectionDurationMillis\/title","value":"candidateSelectionDurationMillis"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1candidateSelectionDurationMillis\/fragments","value":[{"kind":"identifier","text":"candidateSelectionDurationMillis"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1validators\/title","value":"validators"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration~1validators\/fragments","value":[{"kind":"identifier","text":"validators"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/title","value":"DOTFLFaceAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureControllerConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}