{"metadata":{"role":"symbol","title":"FaceAutoCapturePhase","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Enumeration","externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCapturePhase"}]},"abstract":[{"type":"text","text":"Phase of the face auto capture process."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFaceAutoCapturePhase) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePhase"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"topicSections":[{"generated":true,"title":"Classes","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped"],"anchor":"Classes"},{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/candidateSelection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/preCandidateSelection"],"anchor":"Enumeration-Cases"},{"generated":true,"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/init(rawValue:)"],"anchor":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/description"],"anchor":"Instance-Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/s12CaseIterableP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"]}],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocapturephase"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/faceautocapturephase"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/candidateSelection":{"role":"symbol","abstract":[{"text":"Candidate selection is running.","type":"text"}],"kind":"symbol","title":"FaceAutoCapturePhase.candidateSelection","navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"url":"\/documentation\/dotfacelite\/faceautocapturephase\/candidateselection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/candidateSelection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/RawRepresentable-Implementations":{"abstract":[],"type":"topic","title":"RawRepresentable Implementations","role":"collectionGroup","url":"\/documentation\/dotfacelite\/faceautocapturephase\/rawrepresentable-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/RawRepresentable-Implementations","kind":"article"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/Equatable-Implementations":{"kind":"article","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Equatable-Implementations","type":"topic","title":"Equatable Implementations","url":"\/documentation\/dotfacelite\/faceautocapturephase\/equatable-implementations"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/Wrapped":{"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/Wrapped","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturephase\/wrapped","role":"symbol","kind":"symbol","title":"FaceAutoCapturePhase.Wrapped","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Wrapped"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/description":{"abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/description","url":"\/documentation\/dotfacelite\/faceautocapturephase\/description","kind":"symbol","title":"description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","title":"DotFaceLite"},"doc://DotFaceLite/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/DotFaceLite\/s12CaseIterableP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/preCandidateSelection":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/preCandidateSelection","type":"topic","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"role":"symbol","title":"FaceAutoCapturePhase.preCandidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preCandidateSelection","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DOTFaceAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturephase\/precandidateselection"},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturephase","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase","title":"FaceAutoCapturePhase","type":"topic","navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePhase/init(rawValue:)":{"abstract":[],"kind":"symbol","role":"symbol","title":"init(rawValue:)","url":"\/documentation\/dotfacelite\/faceautocapturephase\/init(rawvalue:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"type":"topic"},"doc://DotFaceLite/SY":{"identifier":"doc:\/\/DotFaceLite\/SY","type":"unresolvable","title":"Swift.RawRepresentable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTFaceAutoCapturePhase"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/candidateSelection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePhase\/preCandidateSelection"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFaceAutoCapturePhase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1candidateSelection\/title","value":"DOTFaceAutoCapturePhaseCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1candidateSelection\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1preCandidateSelection\/title","value":"DOTFaceAutoCapturePhasePreCandidateSelection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase~1preCandidateSelection\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhasePreCandidateSelection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/title","value":"DOTFaceAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]}]}]}