{"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"externalID":"c:@M@DotFaceCommons@objc(cs)DOTFaceAutoCapturePreview","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCapturePreview"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","title":"FaceAutoCapturePreview","symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFaceAutoCapturePreview) ","kind":"text"},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/cameraImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/detectionArea","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio"]},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/isEqual(_:)"]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocapturepreview"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo","kind":"relationships"}],"references":{"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/placeholderDiameterToShorterSideRatio":{"url":"\/documentation\/dotfacelite\/faceautocapturepreview\/placeholderdiametertoshortersideratio","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio","abstract":[{"type":"text","text":"A value defined relative to the container shorter side that represents the placeholder diameter."}],"title":"placeholderDiameterToShorterSideRatio","navigatorTitle":[{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/hash":{"type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturepreview\/hash","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/hash","title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/isEqual(_:)":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview\/isequal(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isEqual(_:)","abstract":[],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/cameraImage":{"type":"topic","abstract":[{"type":"text","text":"A rectangular region defined relative to the container where the camera image is displayed in the container."}],"url":"\/documentation\/dotfacelite\/faceautocapturepreview\/cameraimage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/cameraImage","title":"cameraImage","navigatorTitle":[{"text":"cameraImage","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cameraImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","role":"collection","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"text":"version: 9.5.0","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/detectionArea":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturepreview\/detectionarea","navigatorTitle":[{"text":"detectionArea","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/detectionArea","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionArea","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"}],"title":"detectionArea","abstract":[{"type":"text","text":"A rectangular region defined relative to the container that defines the portion of the camera image used for detection."}],"kind":"symbol"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)":{"type":"topic","abstract":[],"url":"\/documentation\/dotfacelite\/faceautocapturepreview\/init(cameraimage:detectionarea:placeholderdiametertoshortersideratio:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","title":"init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cameraImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"placeholderDiameterToShorterSideRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCapturePreview":{"url":"\/documentation\/dotfacelite\/faceautocapturepreview","type":"topic","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"title":"FaceAutoCapturePreview","navigatorTitle":[{"text":"FaceAutoCapturePreview","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePreview","kind":"identifier"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","value":"DOTFaceAutoCapturePreview","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePreview","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/cameraImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/detectionArea","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/placeholderDiameterToShorterSideRatio"],"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCapturePreview\/isEqual(_:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"op":"replace"},{"value":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFaceAutoCapturePreview","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/title","value":"placeholderDiameterToShorterSideRatio"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1placeholderDiameterToShorterSideRatio\/fragments","value":[{"kind":"identifier","text":"placeholderDiameterToShorterSideRatio"}]},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1hash\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1cameraImage\/title","value":"cameraImage"},{"value":[{"text":"cameraImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1cameraImage\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1detectionArea\/title","value":"detectionArea"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1detectionArea\/fragments","value":[{"kind":"identifier","text":"detectionArea"}]},{"value":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholderDiameterToShorterSideRatio:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview~1init(cameraImage:detectionArea:placeholderDiameterToShorterSideRatio:)\/fragments"},{"value":"DOTFaceAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/fragments"},{"value":[{"kind":"identifier","text":"DOTFaceAutoCapturePreview"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCapturePreview\/navigatorTitle"}]}]}