{"metadata":{"title":"FaceAutoCaptureViewController","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","interfaceLanguage":"swift"},"abstract":[{"text":"UI component for capturing face images using the placeholder.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"],"generated":true,"title":"UI components"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFLFaceAutoCaptureViewController) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"languages":["swift"]}]}],"kind":"symbol","relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)UIViewController"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSCoding","doc:\/\/DotFaceLite\/objc(pl)NSExtensionRequestHandling","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/DotFaceLite\/objc(pl)UIAppearanceContainer","doc:\/\/DotFaceLite\/objc(pl)UIContentContainer","doc:\/\/DotFaceLite\/objc(pl)UIFocusEnvironment","doc:\/\/DotFaceLite\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/DotFaceLite\/objc(pl)UIResponderStandardEditActions","doc:\/\/DotFaceLite\/objc(pl)UIStateRestoring","doc:\/\/DotFaceLite\/5UIKit23UITraitChangeObservableP","doc:\/\/DotFaceLite\/objc(pl)UITraitEnvironment","doc:\/\/DotFaceLite\/objc(pl)UIUserActivityRestoring"],"kind":"relationships"}],"topicSections":[{"title":"Style and configuration","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Style-swift.class","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class"]},{"title":"Delegate","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"],"title":"Face auto capture result"},{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/init(configuration:style:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/delegate","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/style-swift.property"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/start()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontroller"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.8.0"}],"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"url":"\/documentation\/dotfacelite\/faceautocaptureresult","abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"type":"topic","role":"symbol","title":"FaceAutoCaptureResult","navigatorTitle":[{"text":"FaceAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureResult","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetection":{"title":"FaceAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of the image processing during the face auto capture process.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","url":"\/documentation\/dotfacelite\/faceautocapturedetection","navigatorTitle":[{"text":"FaceAutoCaptureDetection","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewDidAppear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"viewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"viewDidAppear:","kind":"identifier"}],"abstract":[],"type":"topic","title":"viewDidAppear(_:)","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewdidappear(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewWillDisappear(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewwilldisappear(_:)","role":"symbol","title":"viewWillDisappear(_:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/requestCapture(isFacePresenceRequired:)":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/requestcapture(isfacepresencerequired:)","title":"requestCapture(isFacePresenceRequired:)","kind":"symbol","abstract":[{"text":"Request capture of the next detection.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"requestCaptureWithIsFacePresenceRequired:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"requestCapture"},{"text":"(","kind":"text"},{"text":"isFacePresenceRequired","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"doc://DotFaceLite/objc(cs)UIViewController":{"type":"unresolvable","title":"UIViewController","identifier":"doc:\/\/DotFaceLite\/objc(cs)UIViewController"},"doc://DotFaceLite/documentation/DotFaceLite/DetectionPosition":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"kind":"symbol","title":"DetectionPosition","url":"\/documentation\/dotfacelite\/detectionposition","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DetectionPosition","kind":"identifier"}],"abstract":[{"type":"text","text":"The position of the detected face in the image."}]},"doc://DotFaceLite/objc(pl)UIStateRestoring":{"type":"unresolvable","title":"UIKit.UIStateRestoring","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIStateRestoring"},"doc://DotFaceLite/objc(pl)NSExtensionRequestHandling":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSExtensionRequestHandling","title":"Foundation.NSExtensionRequestHandling"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewDidDisappear(_:)":{"role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"title":"viewDidDisappear(_:)","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewdiddisappear(_:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/start()":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"start"},{"text":"()","kind":"text"}],"title":"start()","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Start the face auto capture process."}],"navigatorTitle":[{"text":"start","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/start()","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/start()"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Configuration-swift.class":{"title":"FaceAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"role":"symbol","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Configuration-swift.class","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewWillTransition(to:with:)":{"navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"kind":"symbol","title":"viewWillTransition(to:with:)","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewwilltransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIViewControllerTransitionCoordinator","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","title":"FaceAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/style-swift.property":{"title":"style","kind":"symbol","navigatorTitle":[{"text":"style","kind":"identifier"}],"abstract":[{"text":"Current style.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/style-swift.property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/style-swift.property","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/Style-swift.class":{"abstract":[{"text":"Customization options for the face auto capture user interface.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/style-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Style","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Style"}],"title":"FaceAutoCaptureViewController.Style","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/Style-swift.class","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/init(configuration:style:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"style"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC5StyleC","kind":"typeIdentifier"},{"kind":"text","text":")"}],"title":"init(configuration:style:)","type":"topic","role":"symbol","abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"FaceAutoCaptureViewController"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/init(configuration:style:)","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/init(configuration:style:)"},"doc://DotFaceLite/objc(pl)UIAppearanceContainer":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIAppearanceContainer","title":"UIKit.UIAppearanceContainer"},"doc://DotFaceLite/objc(pl)UITraitEnvironment":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UITraitEnvironment","title":"UIKit.UITraitEnvironment"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/stopAsync(onStopped:)":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/stopasync(onstopped:)","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","abstract":[{"type":"text","text":"Stop the face auto capture process asynchronously. The "},{"type":"codeVoice","code":"onStopped"},{"text":" callback is called after the process has stopped.","type":"text"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"stopAsync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onStopped"},{"kind":"text","text":": () -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"stopAsync(onStopped:)","navigatorTitle":[{"kind":"identifier","text":"stopAsyncOnStopped:"}]},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/objc(pl)UIContentContainer":{"title":"UIKit.UIContentContainer","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIContentContainer"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewDidLoad()":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewdidload()","title":"viewDidLoad()","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLoad()","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"viewDidLoad"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidLoad"},{"text":"()","kind":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewWillAppear(_:)":{"title":"viewWillAppear(_:)","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewwillappear(_:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillAppear(_:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewController":{"kind":"symbol","abstract":[{"type":"text","text":"UI component for capturing images suitable for MagnifEye liveness evaluation."}],"title":"MagnifEyeLivenessViewController","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontroller","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MagnifEyeLivenessViewController","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/configuration-swift.property":{"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/configuration-swift.property","title":"configuration","kind":"symbol","abstract":[{"type":"text","text":"Current configuration."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/configuration-swift.property","role":"symbol","type":"topic","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"text":"Configuration","preciseIdentifier":"s:11DotFaceLite0B25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier"}]},"doc://DotFaceLite/objc(pl)NSCoding":{"title":"Foundation.NSCoding","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSCoding","type":"unresolvable"},"doc://DotFaceLite/objc(pl)UIUserActivityRestoring":{"title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIUserActivityRestoring","type":"unresolvable"},"doc://DotFaceLite/objc(pl)UIResponderStandardEditActions":{"title":"UIKit.UIResponderStandardEditActions","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIResponderStandardEditActions"},"doc://DotFaceLite/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIPasteConfigurationSupporting"},"doc://DotFaceLite/5UIKit23UITraitChangeObservableP":{"title":"UIKit.UITraitChangeObservable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/5UIKit23UITraitChangeObservableP"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/delegate":{"type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Set this delegate to handle the face auto capture events.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/delegate","title":"delegate","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"delegate","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate","text":"FaceAutoCaptureViewControllerDelegate","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/delegate"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController/viewDidLayoutSubviews()":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller\/viewdidlayoutsubviews()","title":"viewDidLayoutSubviews()","navigatorTitle":[{"text":"viewDidLayoutSubviews","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidLayoutSubviews","kind":"identifier"},{"kind":"text","text":"()"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceLite/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/DotFaceLite\/objc(pl)UIFocusEnvironment","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"value":[{"title":"Delegate","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetection","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DetectionPosition"],"title":"Face auto capture result"},{"title":"Instance Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/configuration-swift.property","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/delegate","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/style-swift.property"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/init(configuration:style:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/requestCapture(isFacePresenceRequired:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/start()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/stopAsync(onStopped:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLayoutSubviews()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewDidLoad()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController\/viewWillTransition(to:with:)"],"title":"Instance Methods"}],"path":"\/topicSections","op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)UIViewController"],"type":"inheritsFrom","kind":"relationships"}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"title":"UI components","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewController"],"generated":true}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments"},{"op":"replace","value":"DOTFLFaceAutoCaptureResult","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/title","value":"DOTFLFaceAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFLFaceAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidAppear(_:)\/title","value":"viewDidAppear:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidAppear(_:)\/fragments"},{"value":"viewWillDisappear:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillDisappear(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillDisappear(_:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/title","value":"requestCaptureWithIsFacePresenceRequired:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"requestCaptureWithIsFacePresenceRequired:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1requestCapture(isFacePresenceRequired:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/title","value":"DOTDetectionPosition","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDetectionPosition"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DetectionPosition\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidDisappear(_:)\/title","op":"replace","value":"viewDidDisappear:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidDisappear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1start()\/title","value":"start"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1start()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"start","kind":"identifier"}]},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillTransition(to:with:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFLFaceAutoCaptureViewControllerDelegate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewControllerDelegate"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1style-swift.property\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1style-swift.property\/fragments","value":[{"kind":"identifier","text":"style"}],"op":"replace"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1init(configuration:style:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1init(configuration:style:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace"},{"op":"replace","value":"stopAsyncOnStopped:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1stopAsync(onStopped:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAsyncOnStopped:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidLoad()\/title","value":"viewDidLoad","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"viewDidLoad","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidLoad()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillAppear(_:)\/title","value":"viewWillAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewWillAppear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewWillAppear:"}]},{"value":"DOTFLMagnifEyeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewController\/fragments","value":[{"text":"DOTFLMagnifEyeLivenessViewController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1configuration-swift.property\/title","value":"configuration"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1configuration-swift.property\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1delegate\/title","value":"delegate"},{"value":[{"kind":"identifier","text":"delegate"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1delegate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidLayoutSubviews()\/title","value":"viewDidLayoutSubviews"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController~1viewDidLayoutSubviews()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidLayoutSubviews"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}