{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory"},"metadata":{"roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTImageFactory","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFactory"}],"title":"ImageFactory"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFactory"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"]}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"seeAlsoSections":[{"anchor":"Converting-images","generated":true,"title":"Converting images","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"]}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagefactory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imagefactory"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgraRawImage(ciImage:ciContext:)":{"type":"topic","title":"createBgraRawImage(ciImage:ciContext:)","navigatorTitle":[{"text":"createBgraRawImageWithCiImage:ciContext:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(ciimage:cicontext:)","abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as an "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" object."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory":{"type":"topic","title":"CGImageFactory","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cgimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" from "},{"type":"codeVoice","code":"Image"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImageFactory","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/Image":{"navigatorTitle":[{"kind":"identifier","text":"Image"}],"abstract":[],"url":"\/documentation\/dotfacelite\/image","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","title":"Image","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}]},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgraRawImage(cgImage:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(cgImage:)","url":"\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(cgimage:)","role":"symbol","navigatorTitle":[{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"type":"topic","title":"createBgraRawImage(cgImage:)","kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgrRawImage(ciImage:ciContext:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","url":"\/documentation\/dotfacelite\/imagefactory\/createbgrrawimage(ciimage:cicontext:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"createBgrRawImageWithCiImage:ciContext:"}],"type":"topic","title":"createBgrRawImage(ciImage:ciContext:)","kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory":{"navigatorTitle":[{"text":"ImageFactory","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imagefactory","type":"topic","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"Image"},{"type":"text","text":" from iOS native image types."}],"title":"ImageFactory","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgrRawImage(cgImage:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgrRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"url":"\/documentation\/dotfacelite\/imagefactory\/createbgrrawimage(cgimage:)","type":"topic","navigatorTitle":[{"text":"createBgrRawImageWithCgImage:","kind":"identifier"}],"title":"createBgrRawImage(cgImage:)","role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(cgImage:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory":{"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CIImageFactory","kind":"identifier"}],"title":"CIImageFactory","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" from "},{"code":"Image","type":"codeVoice"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfacelite\/ciimagefactory","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFactory/createBgraRawImage(bgrRawImage:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(bgrRawImage:)","title":"createBgraRawImage(bgrRawImage:)","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/imagefactory\/createbgrarawimage(bgrrawimage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"createBgraRawImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bgrRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":") -> ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"}],"navigatorTitle":[{"text":"createBgraRawImageWithBgrRawImage:","kind":"identifier"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with ","type":"text"},{"code":".rawBgr","type":"codeVoice"},{"text":" format as an ","type":"text"},{"code":"Image","type":"codeVoice"},{"text":" object with ","type":"text"},{"code":".rawBgra","type":"codeVoice"},{"text":" format.","type":"text"}],"kind":"symbol"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageFactory","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgrRawImage(ciImage:ciContext:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(bgrRawImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(cgImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFactory\/createBgraRawImage(ciImage:ciContext:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"}],"path":"\/relationshipsSections"},{"op":"replace","value":[{"title":"Converting images","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Image","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"],"anchor":"Converting-images","generated":true}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFactory"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"createBgraRawImageWithCiImage:ciContext:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithCiImage:ciContext:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(ciImage:ciContext:)\/fragments"},{"op":"replace","value":"DOTCGImageFactory","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/navigatorTitle"},{"op":"replace","value":"DOTImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImage"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/fragments"},{"op":"replace","value":[{"text":"DOTImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Image\/navigatorTitle"},{"op":"replace","value":"createBgraRawImageWithCgImage:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(cgImage:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createBgraRawImageWithCgImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(cgImage:)\/fragments"},{"op":"replace","value":"createBgrRawImageWithCiImage:ciContext:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createBgrRawImageWithCiImage:ciContext:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(ciImage:ciContext:)\/fragments"},{"op":"replace","value":"DOTImageFactory","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/title"},{"op":"replace","value":[{"text":"DOTImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFactory"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory\/navigatorTitle"},{"op":"replace","value":"createBgrRawImageWithCgImage:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(cgImage:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgrRawImageWithCgImage:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgrRawImage(cgImage:)\/fragments"},{"op":"replace","value":"DOTCIImageFactory","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCIImageFactory"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/fragments"},{"op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/navigatorTitle"},{"op":"replace","value":"createBgraRawImageWithBgrRawImage:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createBgraRawImageWithBgrRawImage:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFactory~1createBgraRawImage(bgrRawImage:)\/fragments"}]}]}