{"sections":[],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat","externalID":"c:@M@DotCore@E@DOTImageFormat","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"roleHeading":"Enumeration","role":"symbol","symbolKind":"enum"},"variants":[{"paths":["\/documentation\/dotfacelite\/imageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTImageFormat) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat"},"topicSections":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg2000","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgr","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgra"],"anchor":"Enumeration-Cases"},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/init(rawValue:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/description"],"anchor":"Instance-Properties"},{"title":"Default Implementations","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/RawRepresentable-Implementations"],"anchor":"Default-Implementations"}],"abstract":[{"text":"Supported image formats.","type":"text"}],"references":{"doc://DotFaceLite/SY":{"identifier":"doc:\/\/DotFaceLite\/SY","type":"unresolvable","title":"Swift.RawRepresentable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat":{"navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"url":"\/documentation\/dotfacelite\/imageformat","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"type":"text","text":"Supported image formats."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat","type":"topic","title":"ImageFormat"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/jpeg2000":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg2000","url":"\/documentation\/dotfacelite\/imageformat\/jpeg2000","title":"ImageFormat.jpeg2000","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"abstract":[{"text":"JPEG2000 compressed image format","type":"text"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/description":{"title":"description","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/imageformat\/description","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/RawRepresentable-Implementations":{"role":"collectionGroup","url":"\/documentation\/dotfacelite\/imageformat\/rawrepresentable-implementations","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/RawRepresentable-Implementations","type":"topic","abstract":[],"kind":"article","title":"RawRepresentable Implementations"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/init(rawValue:)":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/init(rawValue:)","kind":"symbol","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/imageformat\/init(rawvalue:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/Equatable-Implementations","url":"\/documentation\/dotfacelite\/imageformat\/equatable-implementations","title":"Equatable Implementations","type":"topic","kind":"article","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/jpeg":{"type":"topic","kind":"symbol","abstract":[{"text":"JPEG compressed image format","type":"text"}],"title":"ImageFormat.jpeg","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"jpeg"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg"}],"url":"\/documentation\/dotfacelite\/imageformat\/jpeg","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/rawBgr":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgr","kind":"symbol","title":"ImageFormat.rawBgr","abstract":[{"text":"Image with 8-bit BGR color components with the values Blue, Green, and Red stored in 3 bytes.","type":"text"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgr","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageformat\/rawbgr","type":"topic","navigatorTitle":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageFormat/rawBgra":{"kind":"symbol","navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"type":"topic","title":"ImageFormat.rawBgra","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgra","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/imageformat\/rawbgra"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageFormat","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/jpeg2000","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgr","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageFormat\/rawBgra"]}],"path":"\/topicSections"},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTImageFormat"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTImageFormat","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg2000\/title","value":"DOTImageFormatJpeg2000"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg2000\/fragments","value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg\/title","value":"DOTImageFormatJpeg"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1jpeg\/fragments","value":[{"text":"DOTImageFormatJpeg","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgr\/title","value":"DOTImageFormatRawBgr"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgr\/fragments","value":[{"text":"DOTImageFormatRawBgr","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgra\/title","value":"DOTImageFormatRawBgra"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageFormat~1rawBgra\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}]}]}]}