{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize"},"abstract":[{"text":"Image size in pixels.","type":"text"}],"topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/init(width:height:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/cgSize","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/height","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/longerSide","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/shorterSide","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/width"]},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculatePixelCount()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods"},{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/from(cgSize:)"],"title":"Type Methods","anchor":"Type-Methods"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTImageSize) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/imagesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/imagesize"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTImageSize","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"symbolKind":"class","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"title":"ImageSize","modules":[{"name":"DotFaceLite"}],"role":"symbol"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/height":{"type":"topic","navigatorTitle":[{"text":"height","kind":"identifier"}],"title":"height","role":"symbol","abstract":[{"text":"Image height in pixels.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"height","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/height","url":"\/documentation\/dotfacelite\/imagesize\/height"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/width":{"type":"topic","navigatorTitle":[{"text":"width","kind":"identifier"}],"title":"width","role":"symbol","abstract":[{"text":"Image width in pixels.","type":"text"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/width","url":"\/documentation\/dotfacelite\/imagesize\/width"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/cgSize":{"type":"topic","title":"cgSize","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"abstract":[],"url":"\/documentation\/dotfacelite\/imagesize\/cgsize","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/cgSize","navigatorTitle":[{"kind":"identifier","text":"cgSize"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/hash":{"navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/hash","url":"\/documentation\/dotfacelite\/imagesize\/hash","abstract":[],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/init(width:height:)":{"type":"topic","navigatorTitle":[{"text":"initWithWidth:height:","kind":"identifier"}],"title":"init(width:height:)","role":"symbol","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"width","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"height","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/init(width:height:)","url":"\/documentation\/dotfacelite\/imagesize\/init(width:height:)"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/calculateWidthToHeightRatio()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"title":"calculateWidthToHeightRatio()","navigatorTitle":[{"text":"calculateWidthToHeightRatio","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculateWidthToHeightRatio()","url":"\/documentation\/dotfacelite\/imagesize\/calculatewidthtoheightratio()","kind":"symbol","role":"symbol","abstract":[{"text":"Calculate width to height ratio.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/isEqual(_:)":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/imagesize\/isequal(_:)","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/isEqual(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotfacelite\/imagesize\/description","type":"topic","kind":"symbol","abstract":[],"title":"description","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"description"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/description"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/shorterSide":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/imagesize\/shorterside","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/shorterSide","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shorterSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","title":"shorterSide","navigatorTitle":[{"text":"shorterSide","kind":"identifier"}]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/longerSide":{"abstract":[],"type":"topic","url":"\/documentation\/dotfacelite\/imagesize\/longerside","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/longerSide","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"longerSide","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","title":"longerSide","navigatorTitle":[{"text":"longerSide","kind":"identifier"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize":{"title":"ImageSize","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize","url":"\/documentation\/dotfacelite\/imagesize","abstract":[{"text":"Image size in pixels.","type":"text"}],"navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageSize","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/calculatePixelCount()":{"title":"calculatePixelCount()","abstract":[{"type":"text","text":"Calculate the number of pixels of the image."}],"url":"\/documentation\/dotfacelite\/imagesize\/calculatepixelcount()","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"calculatePixelCount"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculatePixelCount()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculatePixelCount"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}]},"doc://DotFaceLite/documentation/DotFaceLite/ImageSize/from(cgSize:)":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/from(cgSize:)","role":"symbol","title":"from(cgSize:)","kind":"symbol","url":"\/documentation\/dotfacelite\/imagesize\/from(cgsize:)","navigatorTitle":[{"text":"fromCgSize:","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") -> ","kind":"text"},{"text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageSize","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"DOTImageSize","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/cgSize","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/height","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/longerSide","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/shorterSide","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/width"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculatePixelCount()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/calculateWidthToHeightRatio()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/init(width:height:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/isEqual(_:)"]},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/ImageSize\/from(cgSize:)"]}],"path":"\/topicSections"},{"op":"replace","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTImageSize","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"height","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1height\/title"},{"op":"replace","value":[{"kind":"identifier","text":"height"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1height\/fragments"},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1width\/title"},{"op":"replace","value":[{"kind":"identifier","text":"width"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1width\/fragments"},{"op":"replace","value":"cgSize","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1cgSize\/title"},{"op":"replace","value":[{"text":"cgSize","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1cgSize\/fragments"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1hash\/title"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1init(width:height:)\/title","value":"initWithWidth:height:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1init(width:height:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithWidth:height:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculateWidthToHeightRatio()\/title","value":"calculateWidthToHeightRatio"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculateWidthToHeightRatio()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateWidthToHeightRatio","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1shorterSide\/title","value":"shorterSide"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1shorterSide\/fragments","value":[{"kind":"identifier","text":"shorterSide"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1longerSide\/title","value":"longerSide"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1longerSide\/fragments","value":[{"text":"longerSide","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/title","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculatePixelCount()\/title","value":"calculatePixelCount"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1calculatePixelCount()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculatePixelCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1from(cgSize:)\/title","value":"fromCgSize:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1ImageSize~1from(cgSize:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgSize:"}]}]}]}