{"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/localization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/localization"]}],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/bundle","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/localizationDictionary","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/useLocalizationDictionary"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLLocalization) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotFaceLite"}],"symbolKind":"class","title":"Localization","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLocalization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger"],"title":"Global components","anchor":"Global-components","generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"abstract":[{"text":"Class responsible for the localization of user interface strings.","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLLocalization/init":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLLocalization\/init","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"title":"init","navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotfllocalization\/init","kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Localization/bundle":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/bundle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"}],"abstract":[{"text":"Bundle used to localize strings. If you want to use your own localized strings, set this to your application bundle - typically ","type":"text"},{"code":"Bundle.main","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"bundle","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/localization\/bundle","title":"bundle","role":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Localization/localizationDictionary":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/localizationDictionary","navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"kind":"symbol","abstract":[{"text":"You can override default iOS localization mechanism by providing custom translation dictionary.","type":"text"}],"title":"localizationDictionary","url":"\/documentation\/dotfacelite\/localization\/localizationdictionary"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceLiteLibrary":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceLiteLibrary"}],"url":"\/documentation\/dotfacelite\/dotfacelitelibrary","kind":"symbol","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":" library initialization."}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLiteLibrary"}],"title":"DotFaceLiteLibrary","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"title":"Localization","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Localization"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/localization","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}]},"doc://DotFaceLite/documentation/DotFaceLite/Logger":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/logger","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"title":"Logger"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/Localization/useLocalizationDictionary":{"kind":"symbol","title":"useLocalizationDictionary","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/useLocalizationDictionary","type":"topic","url":"\/documentation\/dotfacelite\/localization\/uselocalizationdictionary","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"If you set this to "},{"code":"true","type":"codeVoice"},{"text":", ","type":"text"},{"code":"localizationDictionary","type":"codeVoice"},{"text":" will be used to localize strings. Default value is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFLLocalization","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTFLLocalization","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTFLLocalization","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLLocalization\/init"],"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/bundle","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/localizationDictionary","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization\/useLocalizationDictionary"],"anchor":"Type-Properties"}],"op":"replace","path":"\/topicSections"},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"title":"Global components","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceLiteLibrary","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger"],"generated":true,"anchor":"Global-components"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLLocalization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"bundle","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1bundle\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1bundle\/fragments","value":[{"kind":"identifier","text":"bundle"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1localizationDictionary\/fragments","value":[{"kind":"identifier","text":"localizationDictionary"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/title","value":"DotFaceLiteLibrary"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/fragments","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceLiteLibrary\/navigatorTitle","value":[{"text":"DotFaceLiteLibrary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title","value":"DOTFLLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments","value":[{"text":"DOTFLLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLLocalization"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/title","value":"DOTFLLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTFLLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/navigatorTitle","value":[{"text":"DOTFLLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization~1useLocalizationDictionary\/fragments","value":[{"kind":"identifier","text":"useLocalizationDictionary"}]}]}]}