{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLLogger","roleHeading":"Class","title":"Logger","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"symbolKind":"class"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger"},"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/logLevel"],"anchor":"Type-Properties","title":"Type Properties","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/debug(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/error(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/info(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/warning(_:file:function:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"],"anchor":"Global-components","title":"Global components","generated":true}],"variants":[{"paths":["\/documentation\/dotfacelite\/logger"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/logger"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLLogger) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/Logger/info(_:file:function:)":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/info(_:file:function:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"info","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"info(_:file:function:)","url":"\/documentation\/dotfacelite\/logger\/info(_:file:function:)","type":"topic","kind":"symbol","navigatorTitle":[{"text":"info:file:function:","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/Logger/debug(_:file:function:)":{"url":"\/documentation\/dotfacelite\/logger\/debug(_:file:function:)","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/debug(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"debug"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"debug(_:file:function:)","role":"symbol","navigatorTitle":[{"text":"debug:file:function:","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Logger/error(_:file:function:)":{"navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":")","kind":"text"}],"abstract":[],"title":"error(_:file:function:)","type":"topic","url":"\/documentation\/dotfacelite\/logger\/error(_:file:function:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/error(_:file:function:)","role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject"},"doc://DotFaceLite/documentation/DotFaceLite/Logger/logLevel":{"url":"\/documentation\/dotfacelite\/logger\/loglevel","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/logLevel","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","text":"LoggerLogLevel"}],"kind":"symbol","title":"logLevel","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Logger/warning(_:file:function:)":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/warning(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"warning"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"file"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":", "},{"kind":"externalParam","text":"function"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacelite\/logger\/warning(_:file:function:)","type":"topic","title":"warning(_:file:function:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"warning:file:function:"}],"abstract":[]},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP"},"doc://DotFaceLite/documentation/DotFaceLite/Logger":{"url":"\/documentation\/dotfacelite\/logger","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"kind":"symbol","title":"Logger","role":"symbol","navigatorTitle":[{"text":"Logger","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/Localization":{"url":"\/documentation\/dotfacelite\/localization","abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"kind":"symbol","title":"Localization","role":"symbol","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTFLLogger","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"DOTFLLogger"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLLogger"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/logLevel"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/debug(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/error(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/info(_:file:function:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Logger\/warning(_:file:function:)"],"generated":true,"anchor":"Type-Methods","title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Localization"],"generated":true,"anchor":"Global-components","title":"Global components"}],"op":"replace","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLLogger"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"info:file:function:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1info(_:file:function:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"info:file:function:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1info(_:file:function:)\/fragments"},{"value":"debug:file:function:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1debug(_:file:function:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"debug:file:function:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1debug(_:file:function:)\/fragments"},{"value":"error:file:function:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1error(_:file:function:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"error:file:function:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1error(_:file:function:)\/fragments"},{"value":"logLevel","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1logLevel\/title"},{"value":[{"kind":"identifier","text":"logLevel"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1logLevel\/fragments"},{"value":"warning:file:function:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1warning(_:file:function:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"warning:file:function:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger~1warning(_:file:function:)\/fragments"},{"value":"DOTFLLogger","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/title"},{"value":[{"kind":"identifier","text":"DOTFLLogger"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLLogger"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Logger\/navigatorTitle"},{"value":"DOTFLLocalization","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/title"},{"value":[{"kind":"identifier","text":"DOTFLLocalization"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLLocalization"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Localization\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}