{"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}],"type":"paragraph"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:finished:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillTransition(_:)"],"generated":true,"title":"Instance Methods"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLMagnifEyeLivenessViewControllerDelegate) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Implement this delegate to handle the MagnifEye liveness events."}],"metadata":{"platforms":[{"deprecated":true,"unavailable":false,"beta":false,"message":"Use MultiRangeLivenessViewController instead."}],"title":"MagnifEyeLivenessViewControllerDelegate","roleHeading":"Protocol","symbolKind":"protocol","modules":[{"name":"DotFaceLite"}],"navigatorTitle":[{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MagnifEyeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMagnifEyeLivenessViewControllerDelegate"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidlayoutsubviews(_:)","title":"magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLayoutSubviews"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewDidLayoutSubviews:"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","role":"symbol","abstract":[],"type":"topic","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate":{"navigatorTitle":[{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"abstract":[{"text":"Implement this delegate to handle the MagnifEye liveness events.","type":"text"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate","title":"MagnifEyeLivenessViewControllerDelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MagnifEyeLivenessViewControllerDelegate"}],"role":"symbol","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewWillAppear(_:)":{"navigatorTitle":[{"text":"magnifEyeLivenessLiteViewControllerViewWillAppear:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwillappear(_:)","abstract":[],"title":"magnifEyeLivenessViewControllerViewWillAppear(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillAppear(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController"},{"text":")","kind":"text"}],"role":"symbol","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidAppear(_:)":{"url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidappear(_:)","title":"magnifEyeLivenessViewControllerViewDidAppear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidAppear"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","kind":"symbol","role":"symbol","abstract":[],"type":"topic","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewWillTransition(_:)":{"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewWillTransition:"}],"abstract":[],"title":"magnifEyeLivenessViewControllerViewWillTransition(_:)","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilltransition(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillTransition(_:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewWillTransition"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"role":"symbol","deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerNoCameraPermission(_:)":{"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerNoCameraPermission(_:)","title":"magnifEyeLivenessViewControllerNoCameraPermission(_:)","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollernocamerapermission(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerNoCameraPermission:"}],"role":"symbol","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewController(_:finished:)":{"abstract":[{"type":"text","text":"Tells the delegate that the MagnifEye liveness has finished with a result. This callback is called after the component has stopped."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"magnifEyeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MagnifEyeLivenessViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"finished","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MagnifEyeLivenessResult","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessResult","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"magnifEyeLivenessViewController(_:finished:)","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:finished:)","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontroller(_:finished:)","navigatorTitle":[{"text":"magnifEyeLivenessLiteViewController:finished:","kind":"identifier"}],"deprecated":true},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewWillDisappear(_:)":{"title":"magnifEyeLivenessViewControllerViewWillDisappear(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillDisappear(_:)","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewwilldisappear(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:"}],"deprecated":true,"kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidLoad(_:)":{"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLoad(_:)","title":"magnifEyeLivenessViewControllerViewDidLoad(_:)","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdidload(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidLoad"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewDidLoad:"}],"role":"symbol","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MagnifEyeLivenessViewControllerDelegate/magnifEyeLivenessViewControllerViewDidDisappear(_:)":{"deprecated":true,"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidDisappear(_:)","title":"magnifEyeLivenessViewControllerViewDidDisappear(_:)","type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/magnifeyelivenessviewcontrollerdelegate\/magnifeyelivenessviewcontrollerviewdiddisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"magnifEyeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessViewController","text":"MagnifEyeLivenessViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewDidDisappear:"}],"role":"symbol","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"deprecated":true}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"DOTFLMagnifEyeLivenessViewControllerDelegate","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewController(_:finished:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MagnifEyeLivenessViewControllerDelegate\/magnifEyeLivenessViewControllerViewWillTransition(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/deprecationSummary","value":[{"type":"paragraph","inlineContent":[{"text":"Use MultiRangeLivenessViewController instead.","type":"text"}]}],"op":"replace"},{"value":"magnifEyeLivenessLiteViewControllerViewDidLayoutSubviews:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewDidLayoutSubviews:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments"},{"value":"DOTFLMagnifEyeLivenessViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLMagnifEyeLivenessViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate\/navigatorTitle"},{"value":"magnifEyeLivenessLiteViewControllerViewWillAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillAppear(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"magnifEyeLivenessLiteViewControllerViewWillAppear:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewDidAppear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidAppear(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"magnifEyeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillTransition(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewWillTransition:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillTransition(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerNoCameraPermission(_:)\/title","value":"magnifEyeLivenessLiteViewControllerNoCameraPermission:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerNoCameraPermission(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:finished:)\/title","value":"magnifEyeLivenessLiteViewController:finished:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewController(_:finished:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewController:finished:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillDisappear(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewWillDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewWillDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLoad(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewDidLoad:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidLoad(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerViewDidLoad:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidDisappear(_:)\/title","value":"magnifEyeLivenessLiteViewControllerViewDidDisappear:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MagnifEyeLivenessViewControllerDelegate~1magnifEyeLivenessViewControllerViewDidDisappear(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"magnifEyeLivenessLiteViewControllerViewDidDisappear:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}