{"metadata":{"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLMultiRangeLivenessViewControllerDelegate","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessViewControllerDelegate"}],"symbolKind":"protocol","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"roleHeading":"Protocol","role":"symbol","title":"MultiRangeLivenessViewControllerDelegate"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTFLMultiRangeLivenessViewControllerDelegate) ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:finished:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillTransition(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillTransition(_:)":{"navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillTransition(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilltransition(_:)","title":"multiRangeLivenessViewControllerViewWillTransition(_:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidAppear(_:)":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidappear(_:)","abstract":[],"navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidAppear(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"role":"symbol","title":"multiRangeLivenessViewControllerViewDidAppear(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidDisappear(_:)":{"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdiddisappear(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidDisappear:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidDisappear(_:)","role":"symbol","title":"multiRangeLivenessViewControllerViewDidDisappear(_:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidLoad(_:)":{"abstract":[],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidload(_:)","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidLoad:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLoad(_:)","type":"topic","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidLoad","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"role":"symbol","title":"multiRangeLivenessViewControllerViewDidLoad(_:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)":{"kind":"symbol","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewDidLayoutSubviews","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"title":"multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)","navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewDidLayoutSubviews:"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewdidlayoutsubviews(_:)","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillDisappear(_:)":{"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewControllerViewWillDisappear:"}],"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewControllerViewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwilldisappear(_:)","title":"multiRangeLivenessViewControllerViewWillDisappear(_:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewController(_:finished:)":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontroller(_:finished:)","abstract":[{"text":"Tells the delegate that the Multi-Range Liveness has finished with a result. This callback is called after the component has stopped.","type":"text"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"multiRangeLivenessLiteViewController:finished:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:finished:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"multiRangeLivenessViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","kind":"typeIdentifier","text":"MultiRangeLivenessViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessResult","kind":"typeIdentifier","text":"MultiRangeLivenessResult"},{"kind":"text","text":")"}],"role":"symbol","title":"multiRangeLivenessViewController(_:finished:)"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerViewWillAppear(_:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerViewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController"},{"text":")","kind":"text"}],"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollerviewwillappear(_:)","abstract":[],"navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerViewWillAppear:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillAppear(_:)","role":"symbol","title":"multiRangeLivenessViewControllerViewWillAppear(_:)","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate/multiRangeLivenessViewControllerNoCameraPermission(_:)":{"navigatorTitle":[{"text":"multiRangeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"}],"abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"multiRangeLivenessViewControllerNoCameraPermission","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLMultiRangeLivenessViewController","text":"MultiRangeLivenessViewController","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate\/multirangelivenessviewcontrollernocamerapermission(_:)","title":"multiRangeLivenessViewControllerNoCameraPermission(_:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessViewControllerDelegate":{"url":"\/documentation\/dotfacelite\/multirangelivenessviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the Multi-Range Liveness events."}],"navigatorTitle":[{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate","type":"topic","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewControllerDelegate","kind":"identifier"}],"role":"symbol","title":"MultiRangeLivenessViewControllerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"path":"\/metadata\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"path":"\/metadata\/symbolKind","op":"replace","value":"protocol"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewController(_:finished:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerNoCameraPermission(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewDidLoad(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillAppear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillDisappear(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessViewControllerDelegate\/multiRangeLivenessViewControllerViewWillTransition(_:)"]}]},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFLMultiRangeLivenessViewControllerDelegate"}]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillTransition(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewWillTransition:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillTransition(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewWillTransition:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidAppear(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewDidAppear:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewDidAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidDisappear(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewDidDisappear:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidDisappear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewDidDisappear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLoad(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewDidLoad:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLoad(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewDidLoad:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewDidLayoutSubviews:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewDidLayoutSubviews(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewDidLayoutSubviews:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillDisappear(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewWillDisappear:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillDisappear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewWillDisappear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:finished:)\/title","op":"replace","value":"multiRangeLivenessLiteViewController:finished:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewController(_:finished:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewController:finished:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillAppear(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerViewWillAppear:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerViewWillAppear(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerViewWillAppear:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/title","op":"replace","value":"multiRangeLivenessLiteViewControllerNoCameraPermission:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate~1multiRangeLivenessViewControllerNoCameraPermission(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"multiRangeLivenessLiteViewControllerNoCameraPermission:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/title","op":"replace","value":"DOTFLMultiRangeLivenessViewControllerDelegate"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/fragments","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessViewControllerDelegate\/navigatorTitle","op":"replace","value":[{"text":"DOTFLMultiRangeLivenessViewControllerDelegate","kind":"identifier"}]}]}]}