{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"externalID":"c:@M@DotFaceCommons@E@DOTMultiRangeLivenessChallengeItem","roleHeading":"Enumeration","title":"MultiRangeLivenessChallengeItem","navigatorTitle":[{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"symbolKind":"enum"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem"},"topicSections":[{"anchor":"Classes","title":"Classes","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped"],"generated":true},{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/five","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/four","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/one","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/three","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/two","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/zero"],"generated":true},{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/init(rawValue:)"],"generated":true},{"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/RawRepresentable-Implementations"],"generated":true}],"relationshipsSections":[{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"kind":"relationships"}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/multirangelivenesschallengeitem"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"abstract":[{"type":"text","text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTMultiRangeLivenessChallengeItem) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/RawRepresentable-Implementations":{"role":"collectionGroup","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/RawRepresentable-Implementations","title":"RawRepresentable Implementations","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/rawrepresentable-implementations","kind":"article","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem":{"type":"topic","title":"MultiRangeLivenessChallengeItem","navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessChallengeItem"}],"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessChallengeItem","kind":"identifier"}],"abstract":[{"text":"Multi-Range Liveness challenge item values are used to configure the Multi-Range Liveness process.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/zero":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/zero","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"zero","kind":"identifier"}],"title":"MultiRangeLivenessChallengeItem.zero","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/zero","kind":"symbol","navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemZero","kind":"identifier"}],"abstract":[]},"doc://DotFaceLite/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SY"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/three":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/three","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"three"}],"title":"MultiRangeLivenessChallengeItem.three","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/three","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemThree"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/five":{"navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemFive"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"five"}],"abstract":[],"title":"MultiRangeLivenessChallengeItem.five","type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/five","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/five","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/one":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/one","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"one","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/one","title":"MultiRangeLivenessChallengeItem.one","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemOne"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Wrapped":{"url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/wrapped","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"MultiRangeLivenessChallengeItem"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Wrapped","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Wrapped","kind":"identifier"}],"kind":"symbol","title":"MultiRangeLivenessChallengeItem.Wrapped","role":"symbol","navigatorTitle":[{"text":"Wrapped","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/init(rawValue:)":{"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/init(rawvalue:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/Equatable-Implementations":{"type":"topic","kind":"article","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/Equatable-Implementations","title":"Equatable Implementations","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/equatable-implementations","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/four":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/four","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"four"}],"title":"MultiRangeLivenessChallengeItem.four","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/four","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemFour"}],"abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/MultiRangeLivenessChallengeItem/two":{"navigatorTitle":[{"text":"DOTMultiRangeLivenessChallengeItemTwo","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/two","title":"MultiRangeLivenessChallengeItem.two","url":"\/documentation\/dotfacelite\/multirangelivenesschallengeitem\/two","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"two","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","title":"DotFaceLite","kind":"symbol","role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.3.0","type":"text"}]},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","value":"Enumeration","op":"replace"},{"path":"\/metadata\/title","value":"DOTMultiRangeLivenessChallengeItem","op":"replace"},{"path":"\/metadata\/symbolKind","value":"enum","op":"replace"},{"op":"replace","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/five","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/four","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/one","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/three","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/two","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/MultiRangeLivenessChallengeItem\/zero"],"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/title","value":"DOTMultiRangeLivenessChallengeItem","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItem","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem\/navigatorTitle","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItem"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1zero\/title","value":"DOTMultiRangeLivenessChallengeItemZero","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1zero\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemZero","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1three\/title","value":"DOTMultiRangeLivenessChallengeItemThree","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1three\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemThree","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1five\/title","value":"DOTMultiRangeLivenessChallengeItemFive","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1five\/fragments","value":[{"text":"DOTMultiRangeLivenessChallengeItemFive","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1one\/title","value":"DOTMultiRangeLivenessChallengeItemOne","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1one\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemOne"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1four\/title","value":"DOTMultiRangeLivenessChallengeItemFour","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1four\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemFour"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1two\/title","value":"DOTMultiRangeLivenessChallengeItemTwo","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1MultiRangeLivenessChallengeItem~1two\/fragments","value":[{"kind":"identifier","text":"DOTMultiRangeLivenessChallengeItemTwo"}],"op":"replace"}]}]}