{"metadata":{"externalID":"c:@M@DotFaceCommons@E@DOTPlaceholderType","navigatorTitle":[{"kind":"identifier","text":"PlaceholderType"}],"symbolKind":"enum","modules":[{"name":"DotFaceLite"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"roleHeading":"Enumeration","role":"symbol","title":"PlaceholderType"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPlaceholderType) ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"Type of placeholder."}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/circle"],"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/init(rawValue:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/description"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/Equatable-Implementations","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/RawRepresentable-Implementations"],"title":"Default Implementations","generated":true,"anchor":"Default-Implementations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholdertype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/placeholdertype"]}],"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH","doc:\/\/DotFaceLite\/SY"],"title":"Conforms To"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/Equatable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/circle":{"kind":"symbol","abstract":[{"text":"Circular placeholder.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"circle"}],"title":"PlaceholderType.circle","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/circle","navigatorTitle":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholdertype\/circle","type":"topic","role":"symbol"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType":{"title":"PlaceholderType","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType","navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholdertype","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"abstract":[{"type":"text","text":"Type of placeholder."}],"role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/description":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/placeholdertype\/description","abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/description","role":"symbol","title":"description","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/RawRepresentable-Implementations":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype\/rawrepresentable-implementations","title":"RawRepresentable Implementations","role":"collectionGroup"},"doc://DotFaceLite/SY":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SY","title":"Swift.RawRepresentable"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/PlaceholderType/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/placeholdertype\/init(rawvalue:)","title":"init(rawValue:)","role":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"value":"DOTPlaceholderType","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Enumeration Cases","generated":true,"anchor":"Enumeration-Cases","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PlaceholderType\/circle"]}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPlaceholderType","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPlaceholderTypeCircle","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType~1circle\/title"},{"value":[{"text":"DOTPlaceholderTypeCircle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType~1circle\/fragments"},{"value":"DOTPlaceholderType","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/title"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/fragments"},{"value":[{"text":"DOTPlaceholderType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PlaceholderType\/navigatorTitle"}]}]}