{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"abstract":[{"text":"Placeholder.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Classes","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"],"title":"Classes","generated":true}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible"],"type":"inheritedBy","title":"Inherited By"},{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo","title":"Conforms To"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPlaceholder) "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"title":"Placeholder","symbolKind":"class","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"roleHeading":"Class","role":"symbol","externalID":"c:@M@DotFaceCommons@objc(cs)DOTPlaceholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/placeholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/placeholder"]}],"references":{"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Visible":{"url":"\/documentation\/dotfacelite\/placeholder\/visible","abstract":[{"type":"text","text":"Visible placeholder."}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Visible"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Visible","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Visible"}],"title":"Placeholder.Visible"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder/Hidden":{"title":"Placeholder.Hidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hidden","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder\/Hidden","role":"symbol","navigatorTitle":[{"text":"Hidden","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/placeholder\/hidden"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/Placeholder":{"abstract":[{"text":"Placeholder.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Placeholder","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/placeholder","title":"Placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}]},"doc://DotFaceLite/documentation/DotFaceLite/DOTPlaceholder/init":{"type":"topic","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacelite\/dotplaceholder\/init","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholder\/init"},"doc://DotFaceLite/documentation/DotFaceLite/DOTPlaceholderVisible":{"type":"topic","title":"DOTPlaceholderVisible","fragments":[{"kind":"identifier","text":"DOTPlaceholderVisible"}],"url":"\/documentation\/dotfacelite\/dotplaceholdervisible","role":"symbol","abstract":[{"type":"text","text":"Visible placeholder."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DOTPlaceholderHidden":{"url":"\/documentation\/dotfacelite\/dotplaceholderhidden","abstract":[{"text":"Hidden placeholder.","type":"text"}],"type":"topic","fragments":[{"text":"DOTPlaceholderHidden","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderHidden","role":"symbol","title":"DOTPlaceholderHidden"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPlaceholder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPlaceholder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"op":"replace","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholder\/init"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderHidden","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTPlaceholderVisible"],"type":"inheritedBy","title":"Inherited By","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTPlaceholder"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/fragments","value":[{"text":"DOTPlaceholder","kind":"identifier"}]},{"op":"replace","value":[{"text":"DOTPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Placeholder\/navigatorTitle"}]}]}