{"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt"},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/init(x:y:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/cgPoint","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/x","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/y"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/isEqual(_:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/from(cgPoint:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTPointInt) "},{"text":"final","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PointInt","kind":"identifier"}]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/pointint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/pointint"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"sections":[],"metadata":{"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointInt"}],"title":"PointInt","role":"symbol","modules":[{"name":"DotFaceLite"}],"symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTPointInt"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/PointInt/x":{"role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/pointint\/x","navigatorTitle":[{"text":"x","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/x","title":"x","abstract":[{"type":"text","text":"X coordinate."}]},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/from(cgPoint:)":{"navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGPoint","text":"CGPoint"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"title":"from(cgPoint:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/from(cgPoint:)","url":"\/documentation\/dotfacelite\/pointint\/from(cgpoint:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt":{"navigatorTitle":[{"text":"PointInt","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Int"},{"text":" value type.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"title":"PointInt","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt","url":"\/documentation\/dotfacelite\/pointint","type":"topic"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/init(x:y:)":{"title":"init(x:y:)","role":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/pointint\/init(x:y:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/init(x:y:)","abstract":[]},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/description":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/description","url":"\/documentation\/dotfacelite\/pointint\/description","abstract":[],"title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/y":{"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/y","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[{"text":"Y coordinate.","type":"text"}],"title":"y","url":"\/documentation\/dotfacelite\/pointint\/y","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"y"}],"type":"topic"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/hash":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/hash","url":"\/documentation\/dotfacelite\/pointint\/hash","kind":"symbol","type":"topic","title":"hash","abstract":[],"role":"symbol"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.17.0"}]},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/cgPoint":{"navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier","text":"CGPoint"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/cgPoint","url":"\/documentation\/dotfacelite\/pointint\/cgpoint","abstract":[],"role":"symbol","kind":"symbol","title":"cgPoint","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/PointInt/isEqual(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"url":"\/documentation\/dotfacelite\/pointint\/isequal(_:)","title":"isEqual(_:)","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/isEqual(_:)","abstract":[],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"DOTPointInt","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTPointInt"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointInt"}]},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/cgPoint","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/x","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/y"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/init(x:y:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/isEqual(_:)"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/from(cgPoint:)"],"title":"Type Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPointInt","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"x","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1x\/title"},{"op":"replace","value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1x\/fragments"},{"value":"fromCgPoint:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1from(cgPoint:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1from(cgPoint:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"fromCgPoint:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/title","op":"replace","value":"DOTPointInt"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/fragments","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1init(x:y:)\/title","value":"initWithX:y:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithX:y:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1init(x:y:)\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1description\/title","op":"replace","value":"description"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1description\/fragments","op":"replace","value":[{"kind":"identifier","text":"description"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1y\/title","op":"replace","value":"y"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1y\/fragments","op":"replace","value":[{"text":"y","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1hash\/title","value":"hash","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"value":"cgPoint","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1cgPoint\/title"},{"value":[{"kind":"identifier","text":"cgPoint"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1cgPoint\/fragments"},{"value":"isEqual:","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1isEqual(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1isEqual(_:)\/fragments"}]}]}