{"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/init(x:y:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/cgPoint","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/x","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/y"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/isEqual(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/mirrored()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/rebased(parentRectangle:)"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/from(cgPoint:)"],"anchor":"Type-Methods","generated":true,"title":"Type Methods"}],"variants":[{"paths":["\/documentation\/dotfacelite\/pointdouble"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/pointdouble"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPointDouble) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"metadata":{"symbolKind":"class","roleHeading":"Class","title":"PointDouble","role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointDouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble"},"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/cgPoint":{"title":"cgPoint","abstract":[],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGPoint","preciseIdentifier":"c:@S@CGPoint","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/cgPoint","role":"symbol","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/pointdouble\/cgpoint"},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/y":{"title":"y","abstract":[{"type":"text","text":"Y coordinate."}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/y","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"y"}],"url":"\/documentation\/dotfacelite\/pointdouble\/y"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble":{"url":"\/documentation\/dotfacelite\/pointdouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"title":"PointDouble"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/isEqual(_:)":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/isEqual(_:)","title":"isEqual(_:)","url":"\/documentation\/dotfacelite\/pointdouble\/isequal(_:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/hash":{"type":"topic","title":"hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"url":"\/documentation\/dotfacelite\/pointdouble\/hash","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/hash"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/description":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/description","kind":"symbol","title":"description","url":"\/documentation\/dotfacelite\/pointdouble\/description","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/from(cgPoint:)":{"navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"url":"\/documentation\/dotfacelite\/pointdouble\/from(cgpoint:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cgPoint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGPoint","preciseIdentifier":"c:@S@CGPoint"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/from(cgPoint:)","kind":"symbol","type":"topic","title":"from(cgPoint:)","role":"symbol","abstract":[]},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/x":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/x","type":"topic","title":"x","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"X coordinate."}],"url":"\/documentation\/dotfacelite\/pointdouble\/x","role":"symbol","navigatorTitle":[{"text":"x","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/init(x:y:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"url":"\/documentation\/dotfacelite\/pointdouble\/init(x:y:)","abstract":[],"title":"init(x:y:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"kind":"text","text":")"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/init(x:y:)","kind":"symbol","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/mirrored()":{"url":"\/documentation\/dotfacelite\/pointdouble\/mirrored()","abstract":[],"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/mirrored()","role":"symbol","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"title":"mirrored()"},"doc://DotFaceLite/documentation/DotFaceLite/PointDouble/rebased(parentRectangle:)":{"navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"url":"\/documentation\/dotfacelite\/pointdouble\/rebased(parentrectangle:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/rebased(parentRectangle:)","type":"topic","kind":"symbol","title":"rebased(parentRectangle:)","role":"symbol","abstract":[]},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/cgPoint","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/description","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/hash","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/x","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/y"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/init(x:y:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/isEqual(_:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/mirrored()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/rebased(parentRectangle:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointDouble\/from(cgPoint:)"],"anchor":"Type-Methods","title":"Type Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPointDouble","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1cgPoint\/title","value":"cgPoint"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1cgPoint\/fragments","value":[{"text":"cgPoint","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1y\/title","value":"y"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1y\/fragments","value":[{"text":"y","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble\/navigatorTitle","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1from(cgPoint:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"fromCgPoint:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1x\/title","value":"x"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1x\/fragments","value":[{"text":"x","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1init(x:y:)\/title","value":"initWithX:y:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1init(x:y:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1mirrored()\/title","value":"mirrored"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointDouble~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"}]}]}]}