{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTFLSharpnessTooLowValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Overview","type":"heading","level":2,"anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this validator also following validators must be applied: "},{"type":"codeVoice","code":"FaceOutOfBoundsValidator"},{"text":".","type":"text"}]}]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/sharpnesstoolowvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"roleHeading":"Class","title":"SharpnessTooLowValidator","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"symbolKind":"class"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init(threshold:)"]},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/threshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/defaultThreshold"]}],"abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"title":"Validators","generated":true}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"title":"SharpnessTooLowValidator","type":"topic","abstract":[{"type":"text","text":"Validate minimum sharpness of the detected face."}],"url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"title":"FaceNotDetectedValidator","abstract":[{"text":"Validates confidence of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceNotDetectedValidator","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/validate(faceAutoCaptureFrameParameters:)":{"title":"validate(faceAutoCaptureFrameParameters:)","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/validate(faceautocaptureframeparameters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)","navigatorTitle":[{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate sharpness of the detected face."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/init(threshold:)":{"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"title":"init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/init(threshold:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init(threshold:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/threshold":{"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"title":"threshold","abstract":[{"type":"text","text":"Current minimal accepted sharpness."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/threshold","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/threshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","kind":"symbol","title":"BrightnessTooHighValidator","role":"symbol","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"title":"SizeTooSmallValidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.13.0"}],"role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/init()":{"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/init()","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceLite/SH":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"navigatorTitle":[{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"title":"FaceOutOfBoundsValidator","abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceOutOfBoundsValidator","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/dependencyIdentifiers":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/dependencyidentifiers","type":"topic","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/identifier":{"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"title":"identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/identifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/identifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator/defaultThreshold":{"navigatorTitle":[{"text":"defaultThreshold","kind":"identifier"}],"title":"defaultThreshold","abstract":[{"type":"text","text":"Default threshold value."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator\/defaultthreshold","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/defaultThreshold","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultThreshold","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"kind":"symbol","title":"BrightnessTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected face."}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"navigatorTitle":[{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"title":"FaceAutoCaptureDetectionValidator","abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"title":"FaceAutoCaptureController","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"kind":"symbol"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceLite/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotFaceLite/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable"},"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTFLSharpnessTooLowValidator","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/threshold"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/init(threshold:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/validate(faceAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator\/defaultThreshold"]}]},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"title":"Validators","generated":true}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTFLSharpnessTooLowValidator","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTFLSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title","value":"DOTFLFaceNotDetectedValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments","value":[{"text":"DOTFLFaceNotDetectedValidator","kind":"identifier"}]},{"op":"replace","value":"validateWithFaceAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1validate(faceAutoCaptureFrameParameters:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"validateWithFaceAutoCaptureFrameParameters:"}]},{"op":"replace","value":"initWithThreshold:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1init(threshold:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1init(threshold:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithThreshold:error:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1threshold\/title","value":"threshold"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1threshold\/fragments","value":[{"kind":"identifier","text":"threshold"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title","value":"DOTFLBrightnessTooHighValidator"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title","value":"DOTFLSizeTooSmallValidator"},{"value":[{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1init()\/title","value":"init","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"op":"replace"},{"value":"DOTFLFaceOutOfBoundsValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1dependencyIdentifiers\/fragments"},{"value":"identifier","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1identifier\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}]},{"op":"replace","value":"defaultThreshold","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1defaultThreshold\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator~1defaultThreshold\/fragments","value":[{"text":"defaultThreshold","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title","value":"DOTFLBrightnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments","value":[{"text":"DOTFLBrightnessTooLowValidator","kind":"identifier"}]},{"value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}]},{"value":"DOTFLSizeTooLargeValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title"},{"value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}