{"topicSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)"],"title":"Initializers","generated":true,"anchor":"Initializers"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/validate(faceAutoCaptureFrameParameters:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"abstract":[{"text":"Validate size of the detected face.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"type":"conformsTo"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFLSizeTooLargeValidator) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/sizetoolargevalidator"]}],"seeAlsoSections":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"title":"Validators","generated":true,"anchor":"Validators"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"class","title":"SizeTooLargeValidator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"roleHeading":"Class","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLSizeTooLargeValidator"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/maxDetectionSizeToImageShorterSideRatioThreshold":{"title":"maxDetectionSizeToImageShorterSideRatioThreshold","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold","abstract":[{"type":"text","text":"Current maximal accepted size."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/maxdetectionsizetoimageshortersideratiothreshold","navigatorTitle":[{"kind":"identifier","text":"maxDetectionSizeToImageShorterSideRatioThreshold"}]},"doc://DotFaceLite/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooHighValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoohighvalidator","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Validate maximum brightness of the detected face."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/identifier":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/identifier","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}]},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the face auto capture process."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureController"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller","role":"symbol","kind":"symbol","type":"topic","title":"FaceAutoCaptureController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureDetectionValidator":{"abstract":[{"text":"Use this protocol to create face validators.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","role":"symbol","kind":"symbol","type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturedetectionvalidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureDetectionValidator","kind":"identifier"}],"title":"FaceAutoCaptureDetectionValidator"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/init()":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"kind":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/init()","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init()","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"title":"init()"},"doc://DotFaceLite/documentation/DotFaceLite/SharpnessTooLowValidator":{"abstract":[{"text":"Validate minimum sharpness of the detected face.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","kind":"symbol","url":"\/documentation\/dotfacelite\/sharpnesstoolowvalidator","type":"topic","role":"symbol","title":"SharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooSmallValidator":{"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","title":"SizeTooSmallValidator","url":"\/documentation\/dotfacelite\/sizetoosmallvalidator","type":"topic","abstract":[{"type":"text","text":"Validate size of the detected face."}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/init(maxDetectionSizeToImageShorterSideRatioThreshold:)":{"navigatorTitle":[{"text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","title":"init(maxDetectionSizeToImageShorterSideRatioThreshold:)","role":"symbol","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/init(maxdetectionsizetoimageshortersideratiothreshold:)","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/dependencyIdentifiers":{"role":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/dependencyidentifiers","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/defaultMaxDetectionSizeToImageShorterSideRatioThreshold":{"abstract":[{"text":"Default threshold value.","type":"text"}],"title":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/defaultmaxdetectionsizetoimageshortersideratiothreshold","navigatorTitle":[{"kind":"identifier","text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold"}],"role":"symbol","kind":"symbol","type":"topic"},"doc://DotFaceLite/SH":{"identifier":"doc:\/\/DotFaceLite\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/FaceNotDetectedValidator":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceNotDetectedValidator"}],"navigatorTitle":[{"kind":"identifier","text":"FaceNotDetectedValidator"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","title":"FaceNotDetectedValidator","url":"\/documentation\/dotfacelite\/facenotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected face."}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator/validate(faceAutoCaptureFrameParameters:)":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"faceAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureFrameParameters","text":"FaceAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/validate(faceAutoCaptureFrameParameters:)","url":"\/documentation\/dotfacelite\/sizetoolargevalidator\/validate(faceautocaptureframeparameters:)","kind":"symbol","abstract":[{"type":"text","text":"Validate size of the detected face."}],"title":"validate(faceAutoCaptureFrameParameters:)","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceOutOfBoundsValidator":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceOutOfBoundsValidator"}],"abstract":[{"text":"Validate if the detected face is within the specified bounds.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceoutofboundsvalidator","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","title":"FaceOutOfBoundsValidator","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceOutOfBoundsValidator"}]},"doc://DotFaceLite/SQ":{"identifier":"doc:\/\/DotFaceLite\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/SizeTooLargeValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"url":"\/documentation\/dotfacelite\/sizetoolargevalidator","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"type":"topic","title":"SizeTooLargeValidator","abstract":[{"text":"Validate size of the detected face.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator"},"doc://DotFaceLite/documentation/DotFaceLite/BrightnessTooLowValidator":{"url":"\/documentation\/dotfacelite\/brightnesstoolowvalidator","abstract":[{"text":"Validate minimum brightness of the detected face.","type":"text"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}],"kind":"symbol","type":"topic","title":"BrightnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTFLSizeTooLargeValidator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/dependencyIdentifiers","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/identifier","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/maxDetectionSizeToImageShorterSideRatioThreshold"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init()","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/init(maxDetectionSizeToImageShorterSideRatioThreshold:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/validate(faceAutoCaptureFrameParameters:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooLargeValidator\/defaultMaxDetectionSizeToImageShorterSideRatioThreshold"],"anchor":"Type-Properties","title":"Type Properties","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator"]}]},{"op":"replace","value":[{"title":"Validators","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureDetectionValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceNotDetectedValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceOutOfBoundsValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SizeTooSmallValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/SharpnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooLowValidator","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BrightnessTooHighValidator"],"generated":true,"anchor":"Validators"}],"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"maxDetectionSizeToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/title"},{"op":"replace","value":[{"text":"maxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1maxDetectionSizeToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"DOTFLBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/title"},{"op":"replace","value":[{"text":"DOTFLBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooHighValidator\/navigatorTitle"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1identifier\/title"},{"op":"replace","value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1identifier\/fragments"},{"op":"replace","value":"DOTFLFaceAutoCaptureController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"},{"op":"replace","value":"DOTFLFaceAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/title"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFLFaceAutoCaptureDetectionValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureDetectionValidator\/navigatorTitle"},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init()\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init()\/fragments"},{"op":"replace","value":"DOTFLSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSharpnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SharpnessTooLowValidator\/navigatorTitle"},{"op":"replace","value":"DOTFLSizeTooSmallValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFLSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooSmallValidator\/navigatorTitle"},{"op":"replace","value":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithMaxDetectionSizeToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1init(maxDetectionSizeToImageShorterSideRatioThreshold:)\/fragments"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1dependencyIdentifiers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments"},{"op":"replace","value":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/title"},{"op":"replace","value":[{"text":"defaultMaxDetectionSizeToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1defaultMaxDetectionSizeToImageShorterSideRatioThreshold\/fragments"},{"op":"replace","value":"DOTFLFaceNotDetectedValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceNotDetectedValidator\/navigatorTitle"},{"op":"replace","value":"validateWithFaceAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1validate(faceAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"validateWithFaceAutoCaptureFrameParameters:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator~1validate(faceAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"DOTFLFaceOutOfBoundsValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceOutOfBoundsValidator\/navigatorTitle"},{"op":"replace","value":"DOTFLSizeTooLargeValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/fragments"},{"op":"replace","value":[{"text":"DOTFLSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1SizeTooLargeValidator\/navigatorTitle"},{"op":"replace","value":"DOTFLBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BrightnessTooLowValidator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}