{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/compositecheckdigit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/compositecheckdigit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"roleHeading":"Instance Property","title":"compositeCheckDigit","symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(py)compositeCheckDigit","modules":[{"name":"DotDocument"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/compositeCheckDigit"},"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","title":"MrzReader","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"role":"symbol","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"type":"topic","title":"MrzCheckDigit"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","title":"Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"kind":"symbol","role":"symbol"},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/compositeCheckDigit":{"url":"\/documentation\/dotdocument\/td3machinereadablezone\/compositecheckdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/compositeCheckDigit","abstract":[],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"type":"topic","kind":"symbol","title":"compositeCheckDigit"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"compositeCheckDigit","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"compositeCheckDigit"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","text":"DOTMrzCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"compositeCheckDigit"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"},{"op":"replace","value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title"},{"op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments"},{"op":"replace","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/navigatorTitle"},{"op":"replace","value":"DOTTd3MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/navigatorTitle"},{"op":"replace","value":"compositeCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1compositeCheckDigit\/title"},{"op":"replace","value":[{"text":"compositeCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1compositeCheckDigit\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}