{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/dateofbirth"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/dateofbirth"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfBirth","interfaceLanguage":"swift"},"metadata":{"title":"dateOfBirth","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd3MachineReadableZone(py)dateOfBirth","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"role":"symbol","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"}]}]}],"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone/dateOfBirth":{"role":"symbol","title":"dateOfBirth","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"}],"type":"topic","url":"\/documentation\/dotdocument\/td3machinereadablezone\/dateofbirth","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"dateOfBirth"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone\/dateOfBirth"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.3.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDateElementWithCheckDigit":{"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"type":"text","text":" value."}],"title":"MrzDateElementWithCheckDigit","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td3MachineReadableZone","kind":"identifier"}],"title":"Td3MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"dateOfBirth","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDateElementWithCheckDigit"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dateOfBirth"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"value":"dateOfBirth","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfBirth\/title"},{"value":[{"kind":"identifier","text":"dateOfBirth"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone~1dateOfBirth\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title","op":"replace","value":"DOTTd3MachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}]}]}]}