{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"}],"modules":[{"name":"DotDocument"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"kind":"text","text":", "},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd3MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"},"variants":[{"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"text":", ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"},{"text":", ","kind":"text"},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"sex"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone"]]},"references":{"doc://DotDocument/documentation/DotDocument/MrzElement":{"kind":"symbol","url":"\/documentation\/dotdocument\/mrzelement","title":"MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"text":"MrzElement","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)":{"kind":"symbol","title":"init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","url":"\/documentation\/dotdocument\/td3machinereadablezone\/init(documentcode:issuingstateororganization:name:passportnumber:nationality:dateofbirth:sex:dateofexpiry:personalnumberorotheroptionaldata:compositecheckdigit:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone\/init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"},{"text":", ","kind":"text"},{"text":"passportNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"personalNumberOrOtherOptionalData","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"kind":"text","text":")"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:"}],"type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"url":"\/documentation\/dotdocument\/mrzcheckdigit","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"symbol","title":"MrzCheckDigit","type":"topic","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","title":"MrzDateElementWithCheckDigit","kind":"symbol","url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"text":" with parsed ","type":"text"},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"role":"symbol","title":"MrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"symbol","type":"topic","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElement"},{"text":" with check digit and checksum validitity information.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 8.6.1"}],"type":"topic","title":"DotDocument","kind":"symbol","role":"collection"},"doc://DotDocument/documentation/DotDocument/MrzNameElement":{"url":"\/documentation\/dotdocument\/mrznameelement","navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNameElement"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"symbol","title":"MrzNameElement","type":"topic","abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Td3MachineReadableZone":{"navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td3MachineReadableZone","title":"Td3MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"text":") ","kind":"text"},{"text":"initWithDocumentCode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentCode"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"issuingStateOrOrganization"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNameElement","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"passportNumber:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"passportNumber"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","kind":"typeIdentifier","text":"DOTMrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"nationality"},{"kind":"text","text":" "},{"text":"dateOfBirth:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":" *) "},{"text":"dateOfBirth","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"sex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"sex","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"dateOfExpiry:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"text":"dateOfExpiry","kind":"internalParam"},{"kind":"text","text":" "},{"text":"personalNumberOrOtherOptionalData:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"personalNumberOrOtherOptionalData"},{"kind":"text","text":" "},{"kind":"identifier","text":"compositeCheckDigit:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DOTMrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit"},{"text":" *) ","kind":"text"},{"text":"compositeCheckDigit","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/title","op":"replace","value":"DOTMrzElement"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElement\/fragments"},{"value":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone~1init(documentCode:issuingStateOrOrganization:name:passportNumber:nationality:dateOfBirth:sex:dateOfExpiry:personalNumberOrOtherOptionalData:compositeCheckDigit:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","op":"replace","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","value":[{"text":"DOTMrzDateElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","value":"DOTMrzElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/title","value":"DOTMrzNameElement"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMrzNameElement"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNameElement\/fragments"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"op":"replace","value":[{"text":"DOTTd3MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"op":"replace","value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]}]}]}