{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"This is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when the preconditions for the evaluation of this head pose attribute were met. If the preconditions were not met, this is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"In case this flag is set to ","type":"text"},{"code":"false","type":"codeVoice"},{"text":", the resulting angle is not reliable.","type":"text"}]}],"kind":"content"}],"metadata":{"navigatorTitle":[{"text":"arePreconditionsMet","kind":"identifier"}],"title":"arePreconditionsMet","roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseAttribute(py)arePreconditionsMet","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"arePreconditionsMet","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute\/arePreconditionsMet"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/arepreconditionsmet"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headposeattribute\/arepreconditionsmet"]}],"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute/arePreconditionsMet":{"type":"topic","abstract":[{"type":"text","text":"This is set to "},{"code":"true","type":"codeVoice"},{"type":"text","text":" when the preconditions for the evaluation of this head pose attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"title":"arePreconditionsMet","kind":"symbol","url":"\/documentation\/dotfacecore\/headposeattribute\/arepreconditionsmet","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute\/arePreconditionsMet","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"arePreconditionsMet"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"arePreconditionsMet"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseAttribute":{"type":"topic","abstract":[{"type":"text","text":"Head pose attribute with angle value instead of score."}],"title":"HeadPoseAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseAttribute","url":"\/documentation\/dotfacecore\/headposeattribute","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"HeadPoseAttribute"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseAttribute"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"arePreconditionsMet"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"arePreconditionsMet","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"arePreconditionsMet"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"arePreconditionsMet","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute~1arePreconditionsMet\/title"},{"value":[{"kind":"identifier","text":"arePreconditionsMet"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute~1arePreconditionsMet\/fragments"},{"value":"DOTFHeadPoseAttribute","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/title"},{"value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/fragments"},{"value":[{"kind":"identifier","text":"DOTFHeadPoseAttribute"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseAttribute\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}