{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory","symbolKind":"class","navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"title":"CGImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Class"},"kind":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":" or ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":".","type":"text"}],"seeAlsoSections":[{"title":"Converting images","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"],"generated":true}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/cgimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/cgimagefactory"]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory","interfaceLanguage":"swift"},"sections":[],"topicSections":[{"title":"Type Methods","identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgraRawImage:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotFaceLite\/objc(pl)NSObject","doc:\/\/DotFaceLite\/s7CVarArgP","doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","doc:\/\/DotFaceLite\/SQ","doc:\/\/DotFaceLite\/SH"],"kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCGImageFactory) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImageFactory","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotFaceLite\/objc(pl)NSObject"},"doc://DotFaceLite/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotFaceLite\/SQ","type":"unresolvable"},"doc://DotFaceLite/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceLite\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimagefactory","kind":"symbol","title":"BgraRawImageFactory","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"abstract":[{"text":"Create ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/bgrarawimage","kind":"symbol","title":"BgraRawImage","type":"topic","role":"symbol","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CGImageFactory"}],"url":"\/documentation\/dotfacelite\/cgimagefactory","kind":"symbol","title":"CGImageFactory","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CGImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory"},"doc://DotFaceLite/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotFaceLite\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CIImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"CIImageFactory"}],"url":"\/documentation\/dotfacelite\/ciimagefactory","title":"CIImageFactory","kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CIImageFactory"}],"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" from "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"},"doc://DotFaceLite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotFaceLite\/SH","type":"unresolvable"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory/create(bgraRawImage:)":{"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" object."}],"kind":"symbol","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgraRawImage:)","title":"create(bgraRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"}],"role":"symbol","url":"\/documentation\/dotfacelite\/cgimagefactory\/create(bgrarawimage:)","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory/create(bgrRawImage:)":{"url":"\/documentation\/dotfacelite\/cgimagefactory\/create(bgrrawimage:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"createWithBgrRawImage:"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgrRawImage:)","title":"create(bgrRawImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgrRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"}],"role":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.7.0"}],"title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/s7CVarArgP":{"identifier":"doc:\/\/DotFaceLite\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceLite/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFaceLite\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTCGImageFactory","op":"replace","path":"\/metadata\/title"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCGImageFactory"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgrRawImage:)","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgraRawImage:)"],"title":"Type Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotFaceLite\/objc(cs)NSObject"]}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"Converting images","generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImageFactory","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CIImageFactory"]}],"op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTCGImageFactory"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgraRawImageFactory"}],"op":"replace"},{"op":"replace","value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTCGImageFactory"}]},{"op":"replace","value":"DOTCIImageFactory","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/title"},{"op":"replace","value":[{"text":"DOTCIImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CIImageFactory\/fragments"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgraRawImage:)\/title","op":"replace","value":"createWithBgraRawImage:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithBgraRawImage:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgrRawImage:)\/title","op":"replace","value":"createWithBgrRawImage:"},{"value":[{"text":"+ ","kind":"text"},{"text":"createWithBgrRawImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgrRawImage:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}