{"kind":"symbol","metadata":{"title":"dependencies","externalID":"c:@M@DotFaceCore@objc(pl)DotFaceModule(py)dependencies","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"dependencies","kind":"identifier"},{"kind":"text","text":": ["},{"text":"DotFaceModuleCategoryWrapper","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"dependencies","kind":"identifier"}],"required":true,"modules":[{"name":"DotFaceCore"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/dependencies","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"dependencies","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper","text":"DotFaceModuleCategoryWrapper","kind":"typeIdentifier"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacemodule\/dependencies"]},{"paths":["\/documentation\/dotfacecore\/dotfacemodule\/dependencies"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModuleCategoryWrapper":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModuleCategoryWrapper","url":"\/documentation\/dotfacecore\/dotfacemodulecategorywrapper","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"title":"DotFaceModuleCategoryWrapper","abstract":[{"text":"Wrapped ","type":"text"},{"type":"codeVoice","code":"DotFaceModuleCategory"},{"text":" value for Objective-C support.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule":{"role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DotFaceModule","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module."}],"type":"topic","kind":"symbol","title":"DotFaceModule","navigatorTitle":[{"text":"DotFaceModule","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacemodule","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceModule/dependencies":{"kind":"symbol","required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencies","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceModuleCategoryWrapper","text":"DotFaceModuleCategoryWrapper","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceModule\/dependencies","abstract":[],"role":"symbol","navigatorTitle":[{"text":"dependencies","kind":"identifier"}],"title":"dependencies","url":"\/documentation\/dotfacecore\/dotfacemodule\/dependencies"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"dependencies","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"dependencies"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSArray<DotFaceModuleCategoryWrapper *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dependencies"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFaceModuleCategoryWrapper","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModuleCategoryWrapper\/fragments","value":[{"kind":"identifier","text":"DotFaceModuleCategoryWrapper"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/title","value":"DotFaceModule","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule\/fragments","value":[{"kind":"identifier","text":"DotFaceModule"}],"op":"replace"},{"op":"replace","value":"dependencies","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1dependencies\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceModule~1dependencies\/fragments","value":[{"text":"dependencies","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}