{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"symbol","roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","kind":"identifier"}],"fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","kind":"identifier"}],"title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","externalID":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessConfiguration(im)initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:"},"kind":"symbol","abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:objectimage:objectimagesize:query:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithSessionToken:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"sessionToken","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"faceSizeRatioInterval:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"DOTIntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"faceSizeRatioInterval"},{"text":" ","kind":"text"},{"text":"isTorchEnabled:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isTorchEnabled"},{"kind":"text","text":" "},{"text":"cameraFacing:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","kind":"typeIdentifier","text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraFacing"},{"text":" ","kind":"text"},{"text":"transitionDurationMillis:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"transitionDurationMillis","kind":"internalParam"},{"kind":"text","text":" "},{"text":"transitionType:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType","preciseIdentifier":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessTransitionType","kind":"typeIdentifier","text":"DOTFEyeGazeLivenessTransitionType"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"transitionType"},{"kind":"text","text":" "},{"kind":"identifier","text":"corners:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>"},{"kind":"text","text":" *) "},{"text":"corners","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objectImage:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"objectImage"},{"text":" ","kind":"text"},{"kind":"identifier","text":"objectImageSize:"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"objectImageSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"query:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"query"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","interfaceLanguage":"occ"},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"text":"version: 8.1.0","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessTransitionType":{"type":"topic","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessTransitionType"}],"title":"DOTFEyeGazeLivenessTransitionType","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/dotfeyegazelivenesstransitiontype","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessTransitionType"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","title":"FaceDetectionQuery","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceDetectionQuery"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"url":"\/documentation\/dotfacecore\/camerafacing","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration":{"title":"DOTFEyeGazeLivenessConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFEyeGazeLivenessConfiguration"}],"abstract":[{"text":"Configuration options for the eye gaze liveness process.","type":"text"}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFEyeGazeLivenessConfiguration/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:":{"title":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","type":"topic","role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfeyegazelivenessconfiguration\/initwithsessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:objectimage:objectimagesize:query:error:","kind":"symbol","abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFEyeGazeLivenessConfiguration\/initWithSessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:error:"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments","value":[{"text":"DOTCameraFacing","kind":"identifier"}]},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"text":"DOTIntervalDouble","kind":"identifier"}]}]}]}