{"kind":"article","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId"]]},"metadata":{"title":"RawRepresentable Implementations","roleHeading":"API Collection","modules":[{"name":"DotDocument"}],"role":"collectionGroup"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotfingersmoduleid\/rawrepresentable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/hashValue"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/hash(into:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/DotFingersModuleId":{"type":"topic","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}],"title":"DotFingersModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId","kind":"symbol","abstract":[{"code":"DotFingers","type":"codeVoice"},{"text":" feature module identifier.","type":"text"}],"url":"\/documentation\/dotdocument\/dotfingersmoduleid","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/hash(into:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/hash(into:)","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/hash(into:)","title":"hash(into:)","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotFingersModuleId/hashValue":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/dotfingersmoduleid\/hashvalue","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersModuleId\/hashValue","title":"hashValue","abstract":[]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersModuleId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}