{"sections":[],"abstract":[{"type":"text","text":"Bottom edge."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottom","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/bottom"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/bottom"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/bottom","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTRectangleDouble(py)bottom","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"title":"bottom","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble/bottom":{"url":"\/documentation\/dotfacecore\/rectangledouble\/bottom","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottom","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/bottom","navigatorTitle":[{"text":"bottom","kind":"identifier"}],"title":"bottom","kind":"symbol","abstract":[{"type":"text","text":"Bottom edge."}]},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"url":"\/documentation\/dotfacecore\/rectangledouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"title":"RectangleDouble","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"bottom"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bottom"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottom"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"bottom","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1bottom\/title"},{"value":[{"kind":"identifier","text":"bottom"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1bottom\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments","op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}