{"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/fullRectangle","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(cpy)fullRectangle","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"fullRectangle"}],"title":"fullRectangle","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"role":"symbol","symbolKind":"property"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fullRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/rectangledouble\/fullrectangle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/rectangledouble\/fullrectangle"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble/fullRectangle":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fullRectangle"}],"title":"fullRectangle","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fullRectangle","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/fullRectangle","role":"symbol","url":"\/documentation\/dotfacecore\/rectangledouble\/fullrectangle","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"role":"symbol","url":"\/documentation\/dotfacecore\/rectangledouble","title":"RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"fullRectangle"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"fullRectangle","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"fullRectangle"}],"languages":["occ"]}]}},{"value":"fullRectangle","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1fullRectangle\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1fullRectangle\/fragments","value":[{"text":"fullRectangle","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title","value":"DOTRectangleDouble","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}