{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/zerorectangle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangledouble\/zerorectangle"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"}],"navigatorTitle":[{"kind":"identifier","text":"zeroRectangle"}],"extendedModule":"DotCore","title":"zeroRectangle","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"externalID":"c:@CM@DotCore@objc(cs)DOTRectangleDouble(cpy)zeroRectangle","roleHeading":"Type Property","role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/zeroRectangle"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble/zeroRectangle":{"abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}],"type":"topic","url":"\/documentation\/dotfacecore\/rectangledouble\/zerorectangle","navigatorTitle":[{"text":"zeroRectangle","kind":"identifier"}],"title":"zeroRectangle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble\/zeroRectangle","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleDouble":{"title":"RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/rectangledouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"zeroRectangle","path":"\/metadata\/title","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"zeroRectangle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"zeroRectangle"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"zeroRectangle","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1zeroRectangle\/title"},{"value":[{"kind":"identifier","text":"zeroRectangle"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble~1zeroRectangle\/fragments"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleDouble\/navigatorTitle"}]}]}