{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/error(_:file:function:)"},"variants":[{"paths":["\/documentation\/dotfingerscore\/logger\/error(_:file:function:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/logger\/error(_:file:function:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLogger(cm)error:file:function:","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"title":"error(_:file:function:)","role":"symbol","roleHeading":"Type Method","navigatorTitle":[{"kind":"identifier","text":"error:file:function:"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"message","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? = nil, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = ","kind":"text"},{"text":"#file","kind":"keyword"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":" = ","kind":"text"},{"text":"#function","kind":"keyword"},{"text":")","kind":"text"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/Logger":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger","url":"\/documentation\/dotfingerscore\/logger","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"title":"Logger"},"doc://DotFingersCore/documentation/DotFingersCore/Logger/error(_:file:function:)":{"navigatorTitle":[{"text":"error:file:function:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/error(_:file:function:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"file","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"text":"function","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"type":"topic","title":"error(_:file:function:)","url":"\/documentation\/dotfingerscore\/logger\/error(_:file:function:)","abstract":[],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"error:file:function:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"error:file:function:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"message"},{"kind":"text","text":" "},{"kind":"identifier","text":"file:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"file"},{"kind":"text","text":" "},{"kind":"identifier","text":"function:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"function"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/title","value":"DOTFGLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/fragments","value":[{"text":"DOTFGLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/navigatorTitle","value":[{"text":"DOTFGLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1error(_:file:function:)\/title","value":"error:file:function:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1error(_:file:function:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"error:file:function:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}