{"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGLogger(cpy)logLevel","title":"logLevel","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"roleHeading":"Type Property","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","text":"LoggerLogLevel","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/logLevel","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/logger\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/logger\/loglevel"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/Logger/logLevel":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/dotfingerscore\/logger\/loglevel","abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger\/logLevel","title":"logLevel","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/LoggerLogLevel":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LoggerLogLevel"}],"navigatorTitle":[{"kind":"identifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotfingerscore\/loggerloglevel","abstract":[{"text":"Available log levels.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","title":"LoggerLogLevel","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/Logger":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Logger","url":"\/documentation\/dotfingerscore\/logger","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"kind":"symbol","abstract":[{"text":"Static class responsible for generating logs. You can configure log level.","type":"text"}],"title":"Logger"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"text":") ","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@M@DotCore@E@DOTLoggerLogLevel","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/LoggerLogLevel","text":"DOTLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1logLevel\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/title","value":"DOTLoggerLogLevel"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/fragments","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1LoggerLogLevel\/navigatorTitle","value":[{"kind":"identifier","text":"DOTLoggerLogLevel"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/title","value":"DOTFGLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTFGLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Logger\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGLogger"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}