{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/LocalizedError-Implementations"]]},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"LocalizedError.errorDescription","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"title":"errorDescription","extendedModule":"DotCore","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"roleHeading":"Instance Property","externalID":"s:7DotCore0A8SdkErrorPAAE16errorDescriptionSSSgvp::SYNTHESIZED::s:11DotFaceCore15TemplateMatcherC5ErrorO","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/errorDescription","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/error\/errordescription"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"role":"symbol","kind":"symbol","abstract":[{"text":"Matching errors.","type":"text"}],"url":"\/documentation\/dotfacecore\/templatematcher\/error","title":"TemplateMatcher.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/errorDescription":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/errorDescription","url":"\/documentation\/dotfacecore\/templatematcher\/error\/errordescription","abstract":[],"role":"symbol","type":"topic","title":"errorDescription","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/LocalizedError-Implementations":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/LocalizedError-Implementations","abstract":[],"url":"\/documentation\/dotfacecore\/templatematcher\/error\/localizederror-implementations","title":"LocalizedError Implementations","role":"collectionGroup","kind":"article"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TemplateMatcher"}],"role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","title":"TemplateMatcher","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"navigatorTitle":[{"kind":"identifier","text":"TemplateMatcher"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/navigatorTitle","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}