{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/error\/localizederror-implementations"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/LocalizedError-Implementations"},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/failureReason","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/helpAnchor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"article","metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"API Collection","role":"collectionGroup","title":"LocalizedError Implementations"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.4.0"}],"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/failureReason":{"title":"failureReason","url":"\/documentation\/dotfacecore\/templatematcher\/error\/failurereason","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/failureReason","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","url":"\/documentation\/dotfacecore\/templatematcher\/error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[{"text":"Matching errors.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"title":"TemplateMatcher.Error"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/helpAnchor":{"title":"helpAnchor","url":"\/documentation\/dotfacecore\/templatematcher\/error\/helpanchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/helpAnchor","role":"symbol","abstract":[],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/recoverySuggestion":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/recoverySuggestion","url":"\/documentation\/dotfacecore\/templatematcher\/error\/recoverysuggestion","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"recoverySuggestion"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}],"type":"topic","title":"TemplateMatcher","abstract":[{"type":"text","text":"Stateless class which can match templates."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","value":"DOTFTemplateMatcher","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/navigatorTitle","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}]}]}]}