{"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/version(internalError:)","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"version","kind":"identifier"},{"text":"(","kind":"text"},{"text":"internalError","kind":"externalParam"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"abstract":[{"text":"Face template of this version is not supported.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfacecore\/templatematcher\/error\/version(internalerror:)"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"TemplateMatcher.Error.version(internalError:)","symbolKind":"case","externalID":"s:11DotFaceCore15TemplateMatcherC5ErrorO7versionyAEsAD_p_tcAEmF","roleHeading":"Case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"type":"text","text":"version: 9.1.0"}],"title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher","title":"TemplateMatcher","type":"topic","url":"\/documentation\/dotfacecore\/templatematcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can match templates."}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error":{"url":"\/documentation\/dotfacecore\/templatematcher\/error","title":"TemplateMatcher.Error","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Matching errors."}]},"doc://DotFaceCore/documentation/DotFaceCore/TemplateMatcher/Error/version(internalError:)":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"version"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[{"type":"text","text":"Face template of this version is not supported."}],"url":"\/documentation\/dotfacecore\/templatematcher\/error\/version(internalerror:)","role":"symbol","title":"TemplateMatcher.Error.version(internalError:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/TemplateMatcher\/Error\/version(internalError:)"}},"variantOverrides":[{"patch":[{"value":"DOTFTemplateMatcher","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFTemplateMatcher"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/fragments","op":"replace"},{"value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1TemplateMatcher\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}