{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection","text":"DOTDDocumentAutoCaptureDetection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":" "},{"kind":"identifier","text":"result:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureResult","text":"DOTDDocumentAutoCaptureResult"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"result"},{"kind":"text","text":" "},{"kind":"identifier","text":"events:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSSet<DOTDDocumentAutoCaptureControllerWrappedEvent *>","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"events"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult\/initwithdetection:result:events:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult\/initWithDetection:result:events:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:events:"}],"title":"initWithDetection:result:events:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerProcessingResult(im)initWithDetection:result:events:","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:events:"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult/initWithDetection:result:events:":{"role":"symbol","title":"initWithDetection:result:events:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:result:events:"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult\/initWithDetection:result:events:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:events:"}],"url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult\/initwithdetection:result:events:"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDDocumentAutoCaptureControllerProcessingResult":{"role":"symbol","title":"DOTDDocumentAutoCaptureControllerProcessingResult","fragments":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerProcessingResult"}],"abstract":[{"type":"text","text":"The result returned from the processing of one image during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDDocumentAutoCaptureControllerProcessingResult","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotddocumentautocapturecontrollerprocessingresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureResult":{"role":"symbol","title":"DocumentAutoCaptureResult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureResult","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureResult"}],"url":"\/documentation\/dotdocument\/documentautocaptureresult"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetection":{"role":"symbol","title":"DocumentAutoCaptureDetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetection","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetection"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/title","value":"DOTDDocumentAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","value":"DOTDDocumentAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}