{"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/bundle","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/localizationDictionary","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/useLocalizationDictionary"],"generated":true,"anchor":"Type-Properties"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNLocalization) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"metadata":{"navigatorTitle":[{"text":"Localization","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Localization"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNLocalization","role":"symbol","title":"Localization","symbolKind":"class"},"variants":[{"paths":["\/documentation\/dotnfc\/localization"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/localization"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"seeAlsoSections":[{"generated":true,"title":"Global components","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Logger"],"anchor":"Global-components"}],"references":{"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotNfc/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/documentation/DotNfc/Localization":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Localization","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the localization of user interface strings."}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization","type":"topic","title":"Localization","navigatorTitle":[{"text":"Localization","kind":"identifier"}],"url":"\/documentation\/dotnfc\/localization","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/Localization/useLocalizationDictionary":{"title":"useLocalizationDictionary","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"useLocalizationDictionary"}],"abstract":[{"type":"text","text":"If you set this to "},{"code":"true","type":"codeVoice"},{"type":"text","text":", "},{"code":"localizationDictionary","type":"codeVoice"},{"type":"text","text":" will be used to localize strings. Default value is "},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"type":"topic","url":"\/documentation\/dotnfc\/localization\/uselocalizationdictionary","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"useLocalizationDictionary"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/useLocalizationDictionary","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Localization/bundle":{"type":"topic","abstract":[{"type":"text","text":"Bundle used to localize strings."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/bundle","role":"symbol","navigatorTitle":[{"text":"bundle","kind":"identifier"}],"title":"bundle","url":"\/documentation\/dotnfc\/localization\/bundle","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bundle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle","kind":"typeIdentifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DOTNLocalization/init":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNLocalization\/init","url":"\/documentation\/dotnfc\/dotnlocalization\/init","type":"topic","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","title":"init","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Localization/localizationDictionary":{"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"localizationDictionary"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?"}],"url":"\/documentation\/dotnfc\/localization\/localizationdictionary","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/localizationDictionary","abstract":[{"type":"text","text":"You can override default iOS localization mechanism by providing custom translation dictionary."}],"navigatorTitle":[{"kind":"identifier","text":"localizationDictionary"}],"title":"localizationDictionary"},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/Logger":{"type":"topic","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Logger","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"title":"Logger","url":"\/documentation\/dotnfc\/logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTNLocalization"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTNLocalization","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTNLocalization","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNLocalization\/init"],"anchor":"Instance-Methods","title":"Instance Methods"},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/bundle","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/localizationDictionary","doc:\/\/DotNfc\/documentation\/DotNfc\/Localization\/useLocalizationDictionary"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Logger"],"generated":true,"anchor":"Global-components","title":"Global components"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNLocalization","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/title","value":"DOTNLocalization"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/fragments","value":[{"text":"DOTNLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization\/navigatorTitle","value":[{"text":"DOTNLocalization","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1useLocalizationDictionary\/title","value":"useLocalizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1useLocalizationDictionary\/fragments","value":[{"text":"useLocalizationDictionary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1bundle\/title","value":"bundle"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1bundle\/fragments","value":[{"text":"bundle","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1localizationDictionary\/title","value":"localizationDictionary"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Localization~1localizationDictionary\/fragments","value":[{"text":"localizationDictionary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/title","value":"DOTNLogger"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/fragments","value":[{"text":"DOTNLogger","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Logger\/navigatorTitle","value":[{"text":"DOTNLogger","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}