{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNNameOfHolder) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NameOfHolder","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nameofholder"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nameofholder"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","interfaceLanguage":"swift"},"metadata":{"title":"NameOfHolder","externalID":"c:@M@DotNfc@objc(cs)DOTNNameOfHolder","roleHeading":"Class","modules":[{"name":"DotNfc"}],"symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"NameOfHolder"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NameOfHolder","kind":"identifier"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/init(primaryIdentifier:secondaryIdentifier:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/primaryIdentifier","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/secondaryIdentifier"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/isEqual(_:)"],"generated":true,"anchor":"Instance-Methods"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"text":"Name of travel document holder.","type":"text"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"type":"conformsTo","title":"Conforms To"}],"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","title":"DotNfc","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection","type":"topic"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/init(primaryIdentifier:secondaryIdentifier:)":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"primaryIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"secondaryIdentifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"url":"\/documentation\/dotnfc\/nameofholder\/init(primaryidentifier:secondaryidentifier:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/init(primaryIdentifier:secondaryIdentifier:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}],"title":"init(primaryIdentifier:secondaryIdentifier:)"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject"},"doc://DotNfc/documentation/DotNfc/NameOfHolder":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NameOfHolder"}],"url":"\/documentation\/dotnfc\/nameofholder","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder","abstract":[{"type":"text","text":"Name of travel document holder."}],"navigatorTitle":[{"text":"NameOfHolder","kind":"identifier"}],"title":"NameOfHolder"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/primaryIdentifier":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"primaryIdentifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotnfc\/nameofholder\/primaryidentifier","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/primaryIdentifier","abstract":[{"text":"Primary identifier, usually represents surname.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"primaryIdentifier"}],"title":"primaryIdentifier"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/secondaryIdentifier":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"secondaryIdentifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"secondaryIdentifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/secondaryIdentifier","abstract":[{"type":"text","text":"Secondary identifier, usually represents given names."}],"url":"\/documentation\/dotnfc\/nameofholder\/secondaryidentifier","title":"secondaryIdentifier"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/description","url":"\/documentation\/dotnfc\/nameofholder\/description","kind":"symbol","type":"topic","navigatorTitle":[{"text":"description","kind":"identifier"}],"abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/NameOfHolder/isEqual(_:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/isEqual(_:)","type":"topic","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"url":"\/documentation\/dotnfc\/nameofholder\/isequal(_:)","role":"symbol"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTNNameOfHolder","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/primaryIdentifier","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/secondaryIdentifier"]},{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/init(primaryIdentifier:secondaryIdentifier:)","doc:\/\/DotNfc\/documentation\/DotNfc\/NameOfHolder\/isEqual(_:)"],"anchor":"Instance-Methods","title":"Instance Methods","generated":true}],"op":"replace"},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNNameOfHolder","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithPrimaryIdentifier:secondaryIdentifier:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1init(primaryIdentifier:secondaryIdentifier:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPrimaryIdentifier:secondaryIdentifier:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1init(primaryIdentifier:secondaryIdentifier:)\/fragments"},{"value":"DOTNNameOfHolder","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/title"},{"value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/fragments"},{"value":[{"kind":"identifier","text":"DOTNNameOfHolder"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder\/navigatorTitle"},{"value":"primaryIdentifier","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1primaryIdentifier\/title"},{"value":[{"kind":"identifier","text":"primaryIdentifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1primaryIdentifier\/fragments","op":"replace"},{"value":"secondaryIdentifier","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1secondaryIdentifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"secondaryIdentifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1secondaryIdentifier\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1description\/title"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1description\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NameOfHolder~1isEqual(_:)\/fragments"}]}]}