{"topicSections":[{"generated":true,"title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/init(travelDocument:content:)"],"anchor":"Initializers"},{"generated":true,"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/content","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/travelDocument"],"anchor":"Instance-Properties","title":"Instance Properties"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"},"relationshipsSections":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNNfcTravelDocumentReaderResult) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderResult"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"abstract":[{"type":"text","text":"Result of the NFC Travel Document Reader component."}],"metadata":{"navigatorTitle":[{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderResult","role":"symbol","title":"NfcTravelDocumentReaderResult","symbolKind":"class"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"seeAlsoSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"],"generated":true,"anchor":"NFC-reading","title":"NFC reading"}],"references":{"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/description":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/description","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"abstract":[],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/MachineReadableZonePassword":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}],"url":"\/documentation\/dotnfc\/machinereadablezonepassword","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"navigatorTitle":[{"text":"MachineReadableZonePassword","kind":"identifier"}],"title":"MachineReadableZonePassword"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/travelDocument":{"abstract":[{"type":"text","text":"Machine Readable Travel Document (eMRTD)."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"travelDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"}],"navigatorTitle":[{"kind":"identifier","text":"travelDocument"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/traveldocument","title":"travelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/travelDocument","kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/CardAccessNumberPassword":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CardAccessNumberPassword","kind":"identifier"}],"title":"CardAccessNumberPassword","url":"\/documentation\/dotnfc\/cardaccessnumberpassword","kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"abstract":[{"text":"Card Access Number as a password.","type":"text"}],"role":"symbol"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable"},"doc://DotNfc/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/init(travelDocument:content:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/init(traveldocument:content:)","role":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/init(travelDocument:content:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithTravelDocument:content:"}],"title":"init(travelDocument:content:)"},"doc://DotNfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error","title":"NfcTravelDocumentReader.Error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/content":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/content","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"content","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"content","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/content","type":"topic","abstract":[{"text":"Binary content for server-side evaluation.","type":"text"}],"title":"content"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","type":"topic","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"kind":"symbol","title":"NfcTravelDocumentReaderResult","abstract":[{"text":"Result of the NFC Travel Document Reader component.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTNNfcTravelDocumentReaderResult"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/content","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/travelDocument"],"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/init(travelDocument:content:)"]}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections","op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"NFC reading","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/DotNfc\/documentation\/DotNfc\/CardAccessNumberPassword"],"anchor":"NFC-reading"}]},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1description\/fragments","op":"replace"},{"value":"DOTNMachineReadableZonePassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","op":"replace"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","op":"replace"},{"value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MachineReadableZonePassword\/navigatorTitle","op":"replace"},{"value":"travelDocument","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1travelDocument\/title","op":"replace"},{"value":[{"text":"travelDocument","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1travelDocument\/fragments","op":"replace"},{"value":"DOTNCardAccessNumberPassword","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","op":"replace"},{"value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace"},{"value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CardAccessNumberPassword\/navigatorTitle","op":"replace"},{"value":"initWithTravelDocument:content:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1init(travelDocument:content:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1init(travelDocument:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTravelDocument:content:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1content\/title","value":"content"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1content\/fragments","value":[{"text":"content","kind":"identifier"}]},{"value":"DOTNNfcTravelDocumentReaderResult","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}