{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/optionaldata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/machinereadablezoneinformation\/optionaldata"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/optionalData","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Optional data."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"role":"symbol","title":"optionalData","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTMachineReadableZoneInformation(py)optionalData","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation/optionalData":{"role":"symbol","title":"optionalData","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Optional data."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation\/optionalData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation\/optionaldata"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 2.3.3"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZoneInformation":{"role":"symbol","title":"MachineReadableZoneInformation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZoneInformation"}],"abstract":[{"type":"text","text":"Contents of DG1 - Machine readable zone information."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZoneInformation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachineReadableZoneInformation"}],"url":"\/documentation\/dotnfc\/machinereadablezoneinformation"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"optionalData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"optionalData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<NSString *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"optionalData"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1optionalData\/title","value":"optionalData"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation~1optionalData\/fragments","value":[{"kind":"identifier","text":"optionalData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/title","value":"DOTMachineReadableZoneInformation"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZoneInformation\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZoneInformation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTTravelDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}