{"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"symbolKind":"property","title":"eyeGazeLiveness","externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15eyeGazeLivenessAA0ac3Eyehi6ModuleE0CSgvp"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness"},"variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"kind":"symbol","title":"DotFaceLibraryConfiguration.Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"role":"symbol","title":"eyeGazeLiveness","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","abstract":[]},"doc://DotNfc/documentation/DotNfc/DotFaceEyeGazeLivenessModuleConfiguration":{"title":"DotFaceEyeGazeLivenessModuleConfiguration","url":"\/documentation\/dotnfc\/dotfaceeyegazelivenessmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceEyeGazeLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"type":"topic","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments"},{"value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle"},{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"}]}]}