{"metadata":{"title":"passiveLiveness","role":"symbol","modules":[{"name":"DotNfc"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15passiveLivenessAA0ac7Passiveh6ModuleE0CSgvp","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class/passiveLiveness":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class\/passiveLiveness","kind":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class\/passiveliveness","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"passiveLiveness"},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration/Modules-swift.class":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"kind":"symbol","title":"DotFaceLibraryConfiguration.Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration\/Modules-swift.class","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Face library module configuration."}]},"doc://DotNfc/documentation/DotNfc/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceLibraryConfiguration","role":"symbol","url":"\/documentation\/dotnfc\/dotfacelibraryconfiguration","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFacePassiveLivenessModuleConfiguration":{"abstract":[{"text":"Face passive liveness module.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"title":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFacePassiveLivenessModuleConfiguration","url":"\/documentation\/dotnfc\/dotfacepassivelivenessmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"role":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace","value":"DotFacePassiveLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}]}]}]}