{"metadata":{"role":"symbol","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:11DotFaceCore0aB20LibraryConfigurationC5ErrorO","extendedModule":"DotCore","modules":[{"name":"DotFaceCore","relatedModules":["DotCore"]}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"composeWithInternalError()","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/DotSdkError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"text":".","type":"text"}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/composeWithInternalError()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/composewithinternalerror()"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","kind":"symbol","title":"DotFaceLibraryConfiguration.Error"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"abstract":[{"type":"text","text":"Configuration of the "},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library. This class specifies how the "},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"title":"DotFaceLibraryConfiguration","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}],"role":"collection","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/composeWithInternalError()":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"composeWithInternalError","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/composeWithInternalError()","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/composewithinternalerror()","role":"symbol","title":"composeWithInternalError()"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"text":" library initialization.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","url":"\/documentation\/dotfacecore\/dotfacelibrary","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}],"title":"DotFaceLibrary","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibrary","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/DotSdkError-Implementations":{"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/DotSdkError-Implementations","title":"DotSdkError Implementations","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/dotsdkerror-implementations","kind":"article","role":"collectionGroup"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace","value":"DotFaceLibrary"},{"value":[{"text":"DotFaceLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"}]}]}