{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFaceDetectionConfidenceThreshold"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/invalidFaceDetectionConfidenceThreshold","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","title":"DotFaceLibraryConfiguration.Error.invalidFaceDetectionConfidenceThreshold","modules":[{"name":"DotFaceCore"}],"symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidFaceDetectionConfidenceThreshold"}],"externalID":"s:11DotFaceCore0aB20LibraryConfigurationC5ErrorO07invalidB28DetectionConfidenceThresholdyA2EmF"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/invalidfacedetectionconfidencethreshold"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error","title":"DotFaceLibraryConfiguration.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","abstract":[],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibrary"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","type":"topic","navigatorTitle":[{"text":"DotFaceLibrary","kind":"identifier"}],"title":"DotFaceLibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" library initialization."}],"url":"\/documentation\/dotfacecore\/dotfacelibrary"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/invalidFaceDetectionConfidenceThreshold":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/invalidfacedetectionconfidencethreshold","title":"DotFaceLibraryConfiguration.Error.invalidFaceDetectionConfidenceThreshold","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/invalidFaceDetectionConfidenceThreshold","abstract":[],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidFaceDetectionConfidenceThreshold"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","title":"DotFaceLibraryConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","abstract":[{"type":"text","text":"Configuration of the "},{"code":"DotFace","type":"codeVoice"},{"text":" library. This class specifies how the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotFaceLibrary","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","op":"replace"},{"value":[{"text":"DotFaceLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title","op":"replace","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}