{"metadata":{"extendedModule":"DotCore","role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(py)points","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"points"}],"modules":[{"name":"DotDocument","relatedModules":["DotCore"]}],"symbolKind":"property","title":"points","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Corners"]]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/points"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":"] { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/corners\/points"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/corners\/points"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument/Corners":{"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"abstract":[{"text":"Four detected corners in an image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/corners","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners","title":"Corners","role":"symbol"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","type":"topic","url":"\/documentation\/dotdocument\/pointdouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/Corners/points":{"title":"points","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Corners\/points","role":"symbol","navigatorTitle":[{"text":"points","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/corners\/points","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"points","kind":"identifier"},{"text":": [","kind":"text"},{"text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"points"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"points"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<DOTPointDouble *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"text":"points","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCorners"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPointDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1points\/title","value":"points"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Corners~1points\/fragments","value":[{"text":"points","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}