{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImageFactory\/create(cgImage:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","text":"BgraRawImage"}]}]},{"parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" instance."}]}],"kind":"content"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CGImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrarawimagefactory\/create(cgimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/bgrarawimagefactory\/create(cgimage:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImageFactory"]]},"metadata":{"role":"symbol","symbolKind":"method","modules":[{"name":"DotFaceCore"}],"roleHeading":"Type Method","title":"create(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"cgImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":") -> "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCgImage:","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 8.12.0"}],"role":"collection","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImageFactory/create(cgImage:)":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"}],"url":"\/documentation\/dotfacecore\/bgrarawimagefactory\/create(cgimage:)","title":"create(cgImage:)","type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" as a "},{"code":"BgraRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImageFactory\/create(cgImage:)","navigatorTitle":[{"kind":"identifier","text":"createWithCgImage:"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImageFactory":{"abstract":[{"text":"Create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" from iOS native image types."}],"navigatorTitle":[{"text":"BgraRawImageFactory","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/bgrarawimagefactory","kind":"symbol","role":"symbol","type":"topic","title":"BgraRawImageFactory","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimage","kind":"symbol","title":"BgraRawImage","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"createWithCgImage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"createWithCgImage:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCgImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImageFactory~1create(cgImage:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImageFactory\/fragments","op":"replace","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}]}]}