{"metadata":{"modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isVideoCaptureEnabled","symbolKind":"property","navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","title":"isVideoCaptureEnabled"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Use this flag to enable\/disable video capture.","type":"text"},{"type":"text","text":" "},{"text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.","type":"text"},{"text":" ","type":"text"},{"text":"The captured video is included exclusively in the binary content of the result. Default is ","type":"text"},{"code":"false","type":"codeVoice"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isVideoCaptureEnabled","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/cameraconfiguration\/isvideocaptureenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/cameraconfiguration\/isvideocaptureenabled"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration"]]},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration":{"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/cameraconfiguration","title":"CameraConfiguration","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CameraConfiguration/isVideoCaptureEnabled":{"abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"type":"codeVoice","code":"false"},{"type":"text","text":"."}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"title":"isVideoCaptureEnabled","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraConfiguration\/isVideoCaptureEnabled","navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/cameraconfiguration\/isvideocaptureenabled","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isVideoCaptureEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/fragments","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DOTCameraConfiguration","kind":"identifier"}]},{"value":"isVideoCaptureEnabled","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isVideoCaptureEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","op":"replace","value":[{"text":"isVideoCaptureEnabled","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}