{"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}]}],"abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"title":"minEdgeLengthToImageShorterSideRatioThreshold","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooSmallValidator(py)minEdgeLengthToImageShorterSideRatioThreshold","role":"symbol","symbolKind":"property"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","kind":"symbol","type":"topic","abstract":[{"text":"version: 9.5.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"kind":"symbol","abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","role":"symbol","title":"SizeTooSmallValidator","navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator/minEdgeLengthToImageShorterSideRatioThreshold":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator\/minEdgeLengthToImageShorterSideRatioThreshold","role":"symbol","abstract":[{"text":"Current minimal edge length to image shorter side ratio threshold.","type":"text"}],"title":"minEdgeLengthToImageShorterSideRatioThreshold","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator\/minedgelengthtoimageshortersideratiothreshold","type":"topic","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"minEdgeLengthToImageShorterSideRatioThreshold","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPSizeTooSmallValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace"},{"value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace"},{"value":"minEdgeLengthToImageShorterSideRatioThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/title","op":"replace"},{"value":[{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator~1minEdgeLengthToImageShorterSideRatioThreshold\/fragments","op":"replace"}]}]}