{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters\/init(detectionAreaImageSize:fingers:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"]]},"metadata":{"symbolKind":"init","roleHeading":"Initializer","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters(im)initWithDetectionAreaImageSize:fingers:","role":"symbol","title":"init(detectionAreaImageSize:fingers:)","navigatorTitle":[{"text":"initWithDetectionAreaImageSize:fingers:","kind":"identifier"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingers","kind":"typeIdentifier","text":"Fingers"},{"kind":"text","text":")"}],"modules":[{"name":"DotFingersCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"detectionAreaImageSize"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","text":"ImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize"},{"kind":"text","text":", "},{"text":"fingers","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers","text":"Fingers","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingers"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparameters\/init(detectionareaimagesize:fingers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureframeparameters\/init(detectionareaimagesize:fingers:)"]}],"kind":"symbol","sections":[],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters/init(detectionAreaImageSize:fingers:)":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters\/init(detectionAreaImageSize:fingers:)","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detectionAreaImageSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier","text":"ImageSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"fingers"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingers","kind":"typeIdentifier","text":"Fingers"},{"kind":"text","text":")"}],"title":"init(detectionAreaImageSize:fingers:)","navigatorTitle":[{"kind":"identifier","text":"initWithDetectionAreaImageSize:fingers:"}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters\/init(detectionareaimagesize:fingers:)","kind":"symbol","abstract":[]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"title":"FingersAutoCaptureFrameParameters","kind":"symbol","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FingersAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"text":"Information from the detection process about the detected fingers.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},"doc://DotFingersCore/documentation/DotFingersCore/ImageSize":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"title":"ImageSize","navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"url":"\/documentation\/dotfingerscore\/imagesize","kind":"symbol","abstract":[{"type":"text","text":"Image size in pixels."}]},"doc://DotFingersCore/documentation/DotFingersCore/Fingers":{"url":"\/documentation\/dotfingerscore\/fingers","abstract":[{"type":"text","text":"Detected fingers."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Fingers"}],"navigatorTitle":[{"text":"Fingers","kind":"identifier"}],"title":"Fingers","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDetectionAreaImageSize:fingers:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDetectionAreaImageSize:fingers:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetectionAreaImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/ImageSize","text":"DOTImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectionAreaImageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fingers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingers","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingers","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Fingers"},{"text":" *) ","kind":"text"},{"text":"fingers","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters~1init(detectionAreaImageSize:fingers:)\/title","value":"initWithDetectionAreaImageSize:fingers:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters~1init(detectionAreaImageSize:fingers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetectionAreaImageSize:fingers:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title","value":"DOTFGFingersAutoCaptureFrameParameters"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle","op":"replace","value":[{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/fragments","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1ImageSize\/navigatorTitle","value":[{"text":"DOTImageSize","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/title","value":"DOTFGFingers"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/fragments","value":[{"text":"DOTFGFingers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Fingers\/navigatorTitle","value":[{"text":"DOTFGFingers","kind":"identifier"}]}]}]}