{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble"]]},"kind":"symbol","sections":[],"metadata":{"extendedModule":"DotNfc","externalID":"c:@CM@DotNfc@objc(cs)DOTRectangleDouble(im)mirrored","symbolKind":"method","roleHeading":"Instance Method","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","title":"mirrored()","modules":[{"name":"DotNfc"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"}]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble\/mirrored()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/rectangledouble\/mirrored()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/rectangledouble\/mirrored()"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.2.1"}],"role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/RectangleDouble":{"type":"topic","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","title":"RectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","url":"\/documentation\/dotnfc\/rectangledouble","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/RectangleDouble/mirrored()":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble\/mirrored()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"mirrored","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"mirrored"}],"type":"topic","role":"symbol","title":"mirrored()","url":"\/documentation\/dotnfc\/rectangledouble\/mirrored()","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"mirrored","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"mirrored","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/title"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble~1mirrored()\/title","value":"mirrored"},{"value":[{"kind":"text","text":"- "},{"text":"mirrored","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble~1mirrored()\/fragments","op":"replace"}]}]}