{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibrary\/deinitialize()"]}],"metadata":{"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"title":"deinitialize()","modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotPalmCore@objc(cs)DotPalmLibrary(im)deinitializeAndReturnError:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/deinitialize()"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"abstract":[{"text":"Deinitialize library.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary/deinitialize()":{"role":"symbol","title":"deinitialize()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"deinitialize"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"abstract":[{"type":"text","text":"Deinitialize library."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary\/deinitialize()","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpalmlibrary\/deinitialize()"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibrary":{"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotPalmLibrary","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibrary","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibrary","abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotPalm"},{"text":" library initialization.","type":"text"}],"navigatorTitle":[{"text":"DotPalmLibrary","kind":"identifier"}],"title":"DotPalmLibrary"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.7.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"deinitializeAndReturnError:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1deinitialize()\/title"},{"value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary~1deinitialize()\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/title","op":"replace","value":"DotPalmLibrary"},{"value":[{"text":"DotPalmLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibrary\/fragments"}]}]}