{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdk\/initialize(configuration:)"]},{"paths":["\/documentation\/dotpalmcore\/dotsdk\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)initializeWithConfiguration:error:","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"initialize(configuration:)","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:error:"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/initialize(configuration:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Initialize ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" with configuration."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","kind":"typeIdentifier","text":"DotSdkConfiguration"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"inlineContent":[{"text":"","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" configuration.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}]},{"style":"note","name":"Throws","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Throws an error if ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" fails to decode provided license or if any ","type":"text"},{"code":"DotLibrary","type":"codeVoice"},{"type":"text","text":" fails to initialize."}]}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"title":"DotSdk","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/initialize(configuration:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/initialize(configuration:)","role":"symbol","abstract":[{"text":"Initialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" with configuration."}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotsdk\/initialize(configuration:)","kind":"symbol","title":"initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdkconfiguration","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" configuration."}],"title":"DotSdkConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdkConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithConfiguration:error:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithConfiguration:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkConfiguration","text":"DotSdkConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotSdkConfiguration"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"DotSdk","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title"},{"value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1initialize(configuration:)\/title","value":"initializeWithConfiguration:error:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1initialize(configuration:)\/fragments"},{"op":"replace","value":"DotSdkConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkConfiguration\/fragments","value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"op":"replace"}]}]}