{"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdk\/versionname"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotsdk\/versionname"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/versionName","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" version."}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdk(py)versionName","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"symbolKind":"property","modules":[{"name":"DotPalmCore"}],"title":"versionName","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdk":{"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotsdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotFaceLite","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotNfc","type":"codeVoice"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"title":"DotSdk","role":"symbol","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdk/versionName":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdk\/versionName","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"url":"\/documentation\/dotpalmcore\/dotsdk\/versionname","title":"versionName","role":"symbol","abstract":[{"code":"DotSdk","type":"codeVoice"},{"text":" version.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"versionName","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"versionName"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"versionName","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"versionName","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/title","op":"replace","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk\/navigatorTitle","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1versionName\/title","op":"replace","value":"versionName"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdk~1versionName\/fragments","op":"replace","value":[{"text":"versionName","kind":"identifier"}]}]}]}