{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomLeft","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Bottom left corner point."}],"metadata":{"navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"modules":[{"name":"DotFaceCore"}],"title":"bottomLeft","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)bottomLeft","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/corners\/bottomleft"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/corners\/bottomleft"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Corners":{"url":"\/documentation\/dotfacecore\/corners","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"title":"Corners","role":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners","type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"text":"version: 8.13.0","type":"text"}],"role":"collection","type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/Corners/bottomLeft":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"title":"bottomLeft","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Corners\/bottomLeft","abstract":[{"text":"Bottom left corner point.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/corners\/bottomleft","navigatorTitle":[{"text":"bottomLeft","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/PointDouble":{"url":"\/documentation\/dotfacecore\/pointdouble","title":"PointDouble","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bottomLeft","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":" * ","kind":"text"},{"text":"bottomLeft","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners\/fragments","value":[{"kind":"identifier","text":"DOTCorners"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomLeft\/title","value":"bottomLeft","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Corners~1bottomLeft\/fragments","op":"replace","value":[{"kind":"identifier","text":"bottomLeft"}]},{"value":"DOTPointDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/title"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1PointDouble\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}