{"metadata":{"roleHeading":"Instance Property","title":"detection","navigatorTitle":[{"text":"detection","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(py)detection","fragments":[{"text":"detection","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"property"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules\/detection"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules","abstract":[{"text":"Palm library module configuration.","type":"text"}],"fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"type":"topic","role":"symbol","title":"DotPalmLibraryConfigurationModules","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules/detection":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules\/detection","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules\/detection","type":"topic","title":"detection","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","title":"DotFaceLite","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"text":"version: 9.2.0","type":"text"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"title":"DotPalmDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm detection module configuration."}],"url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration"}},"variantOverrides":[{"patch":[{"value":"DotPalmDetectionModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/fragments"},{"value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}