{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules\/initWithDetection:","interfaceLanguage":"occ"},"metadata":{"title":"initWithDetection:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules(im)initWithDetection:","roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"symbolKind":"method","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules"]]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules\/initwithdetection:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules","abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmDetectionModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotpalmdetectionmoduleconfiguration","abstract":[{"type":"text","text":"Palm detection module configuration."}],"title":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmDetectionModuleConfiguration","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotPalmLibraryConfigurationModules/initWithDetection:":{"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotPalmLibraryConfigurationModules\/initWithDetection:","abstract":[],"title":"initWithDetection:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/dotpalmlibraryconfigurationmodules\/initwithdetection:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 9.2.2"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}