{"metadata":{"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderConfiguration(py)common","fragments":[{"text":"common","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"common","kind":"identifier"}],"roleHeading":"Instance Property","title":"common"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration\/common"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration\/common"},"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"common"},{"kind":"text","text":";"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration"]]},"references":{"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration/common":{"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration\/common","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration\/common","fragments":[{"text":"common","kind":"identifier"}],"title":"common"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration","title":"CommonConfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/commonconfiguration","navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/DOTNNfcTravelDocumentReaderConfiguration":{"title":"DOTNNfcTravelDocumentReaderConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNNfcTravelDocumentReaderConfiguration","fragments":[{"text":"DOTNNfcTravelDocumentReaderConfiguration","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotnnfctraveldocumentreaderconfiguration","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for "},{"type":"text","text":"NfcTravelDocumentReader"},{"type":"text","text":"."}],"type":"topic"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","type":"topic","url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTCommonConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/title"},{"op":"replace","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}