{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class"]]},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble"},{"text":", ","kind":"text"},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cameraFacing"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing","text":"CameraFacing"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"transitionDurationMillis"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"transitionType"},{"text":": ","kind":"text"},{"text":"TransitionType","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"kind":"text","text":", "},{"text":"corners","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"objectImage"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"text":"objectImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"query"},{"kind":"text","text":": "},{"text":"FaceDetectionQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"symbolKind":"init","title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:)","roleHeading":"Initializer","modules":[{"name":"DotFaceCore"}],"externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC12sessionToken21faceSizeRatioInterval14isTorchEnabled12cameraFacing24transitionDurationMillis0U4Type7corners11objectImage0z5ImageM05queryAESSSg_AA0O6DoubleCSbAA06CameraT0OSiAE010TransitionX0OSayAA07WrappeddeF6CornerCGSo7UIImageCSgSo6CGSizeVAA0B14DetectionQueryCtKcfc","role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:objectimage:objectimagesize:query:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Create the eye gaze liveness configuration."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"? = nil, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":" = Defaults.faceSizeRatioInterval, "},{"kind":"externalParam","text":"isTorchEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" = Defaults.isTorchEnabled, "},{"kind":"externalParam","text":"cameraFacing"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":" = Defaults.cameraFacing, "},{"text":"transitionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" = Defaults.transitionDurationMillis, ","kind":"text"},{"text":"transitionType","kind":"externalParam"},{"kind":"text","text":": "},{"text":"TransitionType","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"kind":"text","text":" = Defaults.transitionType, "},{"kind":"externalParam","text":"corners"},{"kind":"text","text":": ["},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"},{"kind":"text","text":"], "},{"text":"objectImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"? = nil, ","kind":"text"},{"kind":"externalParam","text":"objectImageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":" = Defaults.objectImageSize, ","kind":"text"},{"kind":"externalParam","text":"query"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","text":"FaceDetectionQuery"},{"kind":"text","text":" = .init()) "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"sections":[],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/TransitionType-swift.enum":{"title":"EyeGazeLivenessViewController.Configuration.TransitionType","navigatorTitle":[{"text":"TransitionType","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/transitiontype-swift.enum","role":"symbol","abstract":[{"type":"text","text":"Eye gaze liveness available corner transition types."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/TransitionType-swift.enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TransitionType"}],"type":"topic","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","type":"topic","abstract":[{"type":"text","text":"version: 8.0.0"}],"role":"collection","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","role":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","type":"topic","kind":"symbol","abstract":[{"text":"UI component for evaluating liveness by tracking eye gaze.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"title":"EyeGazeLivenessViewController"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","type":"topic","kind":"symbol","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the eye gaze liveness process."}],"title":"EyeGazeLivenessViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetectionQuery":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetectionQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/facedetectionquery","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"FaceDetectionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"title":"FaceDetectionQuery","type":"topic","abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"type":"topic","title":"WrappedEyeGazeLivenessCorner","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedEyeGazeLivenessCorner"}],"url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"code":"EyeGazeLivenessCorner","type":"codeVoice"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IntervalDouble":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IntervalDouble","kind":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/intervaldouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"role":"symbol","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"type":"topic","title":"IntervalDouble"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CameraFacing":{"kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/camerafacing","abstract":[{"type":"text","text":"Facing of the camera on the device."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"title":"CameraFacing","role":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:)":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/init(sessiontoken:facesizeratiointerval:istorchenabled:camerafacing:transitiondurationmillis:transitiontype:corners:objectimage:objectimagesize:query:)","abstract":[{"text":"Create the eye gaze liveness configuration.","type":"text"}],"title":"init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:)","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/init(sessionToken:faceSizeRatioInterval:isTorchEnabled:cameraFacing:transitionDurationMillis:transitionType:corners:objectImage:objectImageSize:query:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?, "},{"text":"faceSizeRatioInterval","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"isTorchEnabled","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"cameraFacing","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CameraFacing","preciseIdentifier":"c:@M@DotFaceCore@E@DOTCameraFacing"},{"kind":"text","text":", "},{"text":"transitionDurationMillis","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"transitionType","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TransitionType","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC14TransitionTypeO"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"corners"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"objectImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"objectImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"text":"query","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery","text":"FaceDetectionQuery","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","value":"DOTFWrappedEyeGazeLivenessCorner","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFWrappedEyeGazeLivenessCorner"}]},{"value":"DOTIntervalDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"op":"replace"},{"value":"DOTCameraFacing","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CameraFacing\/fragments"}]}]}