{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration(py)hash","title":"hash","roleHeading":"Instance Property","navigatorTitle":[{"text":"hash","kind":"identifier"}],"symbolKind":"property"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/autocaptureconfiguration\/hash"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/hash"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"title":"AutoCaptureConfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/AutoCaptureConfiguration/hash":{"title":"hash","role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"hash"}],"url":"\/documentation\/dotpalmcore\/autocaptureconfiguration\/hash","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/AutoCaptureConfiguration\/hash","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"hash","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/fragments","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1AutoCaptureConfiguration~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"}]}]}