{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcher(im)matchWithReferenceTemplateBytes:probeFaceImage:error:","roleHeading":"Instance Method","title":"match(referenceTemplateBytes:probeFaceImage:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplateBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeFaceImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","text":"Result","kind":"typeIdentifier"}],"symbolKind":"method","navigatorTitle":[{"text":"matchWithReferenceTemplateBytes:probeFaceImage:error:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}]},"abstract":[{"type":"text","text":"Match face image against reference template."}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplateBytes:probeFaceImage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"referenceTemplateBytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"text":"probeFaceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher\/Result","kind":"typeIdentifier","text":"Result","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"referenceTemplateBytes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Reference template as "},{"type":"codeVoice","code":"Data"},{"type":"text","text":"."}]}]},{"name":"probeFaceImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Face image."}]}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"text":"Result with matching score.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencetemplatebytes:probefaceimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencetemplatebytes:probefaceimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceMatcher/match(referenceTemplateBytes:probeFaceImage:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplateBytes:probeFaceImage:)","title":"match(referenceTemplateBytes:probeFaceImage:)","type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/match(referencetemplatebytes:probefaceimage:)","kind":"symbol","abstract":[{"text":"Match face image against reference template.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplateBytes"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeFaceImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","kind":"typeIdentifier","text":"Result"}],"navigatorTitle":[{"text":"matchWithReferenceTemplateBytes:probeFaceImage:error:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceMatcher/Result":{"url":"\/documentation\/dotfacecore\/facematcher\/result","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher\/Result","title":"FaceMatcher.Result","abstract":[{"type":"text","text":"Face matcher result."}],"navigatorTitle":[{"kind":"identifier","text":"Result"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceMatcher":{"url":"\/documentation\/dotfacecore\/facematcher","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceMatcher"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceMatcher","title":"FaceMatcher","abstract":[{"type":"text","text":"Stateless class which can match face images and templates."}],"navigatorTitle":[{"text":"FaceMatcher","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFFaceMatcherResult":{"url":"\/documentation\/dotfacecore\/dotffacematcherresult","role":"symbol","fragments":[{"text":"DOTFFaceMatcherResult","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","title":"DOTFFaceMatcherResult","abstract":[{"type":"text","text":"Face matcher result."}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","title":"DotFaceCore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImage":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage","title":"FaceImage","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceImage"}],"abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"url":"\/documentation\/dotfacecore\/faceimage","navigatorTitle":[{"kind":"identifier","text":"FaceImage"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"matchWithReferenceTemplateBytes:probeFaceImage:error:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchWithReferenceTemplateBytes:probeFaceImage:error:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"DOTFFaceMatcherResult","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcherResult"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"matchWithReferenceTemplateBytes:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"referenceTemplateBytes"},{"kind":"text","text":" "},{"kind":"identifier","text":"probeFaceImage:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImage","kind":"typeIdentifier","text":"DOTFFaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"probeFaceImage"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplateBytes:probeFaceImage:)\/title","op":"replace","value":"matchWithReferenceTemplateBytes:probeFaceImage:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplateBytes:probeFaceImage:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplateBytes:probeFaceImage:error:","kind":"identifier"}]},{"op":"replace","value":"DOTFFaceMatcher","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceMatcher\/title"},{"value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceMatcher\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage\/title","op":"replace","value":"DOTFFaceImage"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImage\/fragments","value":[{"text":"DOTFFaceImage","kind":"identifier"}]}]}]}