{"metadata":{"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":", ","kind":"text"},{"text":"probeFaceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcher(im)matchWithReferenceTemplate:probeFaceImage:error:","navigatorTitle":[{"text":"matchWithReferenceTemplate:probeFaceImage:error:","kind":"identifier"}],"title":"match(referenceTemplate:probeFaceImage:)","symbolKind":"method","modules":[{"name":"DotFaceCore"}]},"kind":"symbol","abstract":[{"text":"Match face image against reference face image.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"probeFaceImage"},{"text":": ","kind":"text"},{"text":"FaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","text":"Result","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"referenceTemplate","content":[{"inlineContent":[{"type":"text","text":"Reference template."}],"type":"paragraph"}]},{"name":"probeFaceImage","content":[{"inlineContent":[{"text":"Probe face image.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"Result with matching score.","type":"text"}]}]},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"aside","style":"note","name":"Throws","content":[{"inlineContent":[{"text":"Throws an error if ","type":"text"},{"type":"codeVoice","code":"FaceMatcher"},{"text":" fails to execute face matching.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplate:probeFaceImage:)"},"variants":[{"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencetemplate:probefaceimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencetemplate:probefaceimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Result":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","abstract":[{"type":"text","text":"Face matcher result."}],"title":"FaceMatcher.Result","url":"\/documentation\/dotfacecore\/facematcher\/result","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Result"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceMatcherResult":{"type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFFaceMatcherResult"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","abstract":[{"text":"Face matcher result.","type":"text"}],"title":"DOTFFaceMatcherResult","url":"\/documentation\/dotfacecore\/dotffacematcherresult","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImage"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","title":"FaceImage","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceimage","navigatorTitle":[{"kind":"identifier","text":"FaceImage"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/match(referenceTemplate:probeFaceImage:)":{"abstract":[{"type":"text","text":"Match face image against reference face image."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"match"},{"kind":"text","text":"("},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeFaceImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","kind":"typeIdentifier","text":"Result"}],"type":"topic","url":"\/documentation\/dotfacecore\/facematcher\/match(referencetemplate:probefaceimage:)","navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceTemplate:probeFaceImage:error:"}],"title":"match(referenceTemplate:probeFaceImage:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceTemplate:probeFaceImage:)","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/Template":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","role":"symbol","url":"\/documentation\/dotfacecore\/template","abstract":[{"text":"Face template.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"title":"Template","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","kind":"symbol","title":"FaceMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"FaceMatcher","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/facematcher","type":"topic","abstract":[{"type":"text","text":"Stateless class which can match face images and templates."}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"matchWithReferenceTemplate:probeFaceImage:error:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceTemplate:probeFaceImage:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcherResult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","kind":"typeIdentifier","text":"DOTFFaceMatcherResult"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"matchWithReferenceTemplate:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Template","text":"DOTFTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":" *) ","kind":"text"},{"text":"referenceTemplate","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"probeFaceImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"probeFaceImage","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Reference template.","type":"text"}]}],"name":"referenceTemplate"},{"content":[{"inlineContent":[{"type":"text","text":"Probe face image."}],"type":"paragraph"}],"name":"probeFaceImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"On output, a pointer to an error object that describes why the method failed, or "},{"type":"codeVoice","code":"nil"},{"text":" if no error occurred. If you are not interested in the error information, pass ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" for this parameter.","type":"text"}]}],"name":"error"}]},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Result with matching score."},{"type":"text","text":" On failure, this method returns "},{"type":"codeVoice","code":"nil"},{"type":"text","text":"."}]}]},"op":"replace"},{"op":"replace","value":"DOTFFaceImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplate:probeFaceImage:)\/title","value":"matchWithReferenceTemplate:probeFaceImage:error:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceTemplate:probeFaceImage:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceTemplate:probeFaceImage:)\/fragments"},{"op":"replace","value":"DOTFTemplate","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/title"},{"op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Template\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFTemplate"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments","value":[{"kind":"identifier","text":"DOTFFaceMatcher"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/navigatorTitle","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}