{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/traveldocumenttype\/numberoflines"]}],"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","externalID":"s:18DotDocumentCommons06TravelB4TypeO13numberOfLinesSivp","modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"numberOfLines","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"numberOfLines","roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/numberOfLines"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"numberOfLines"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","title":"MrzReader","navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","role":"collection","abstract":[{"text":"version: 8.14.0","type":"text"}]},"doc://DotDocument/documentation/DotDocument/TravelDocumentType/numberOfLines":{"url":"\/documentation\/dotdocument\/traveldocumenttype\/numberoflines","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType\/numberOfLines","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"numberOfLines","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"title":"numberOfLines","type":"topic"},"doc://DotDocument/documentation/DotDocument/TravelDocumentType":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"TravelDocumentType"}],"navigatorTitle":[{"text":"TravelDocumentType","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Travel document type according to ICAO Doc 9303 specification."}],"url":"\/documentation\/dotdocument\/traveldocumenttype","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/TravelDocumentType","title":"TravelDocumentType","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader","op":"replace"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"value":"DOTTravelDocumentType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTravelDocumentType"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1TravelDocumentType\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}