{"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","kind":"typeIdentifier","text":"FaceQualityQuery"}],"title":"quality","externalID":"c:@M@DotFaceCore@objc(cs)FaceDetectionQuery(py)quality","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"quality"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/quality","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","text":"FaceQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/quality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facedetectionquery\/quality"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Face image quality query."}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"title":"FaceQualityQuery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"url":"\/documentation\/dotfacecore\/facequalityquery","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery/quality":{"navigatorTitle":[{"kind":"identifier","text":"quality"}],"url":"\/documentation\/dotfacecore\/facedetectionquery\/quality","title":"quality","type":"topic","abstract":[{"text":"Face image quality query.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery","kind":"typeIdentifier","text":"FaceQualityQuery"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery\/quality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceDetectionQuery":{"abstract":[{"text":"Face detection query. It allows additional processing beyond basic face detection.","type":"text"}],"url":"\/documentation\/dotfacecore\/facedetectionquery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetectionQuery","kind":"identifier"}],"navigatorTitle":[{"text":"FaceDetectionQuery","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceDetectionQuery","title":"FaceDetectionQuery","kind":"symbol","role":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","abstract":[{"text":"version: 9.1.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"quality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"quality","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFFaceQualityQuery","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery"},{"text":" * ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1quality\/title","op":"replace","value":"quality"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery~1quality\/fragments","op":"replace","value":[{"kind":"identifier","text":"quality"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/title","op":"replace","value":"FaceDetectionQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/fragments","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceDetectionQuery\/navigatorTitle","op":"replace","value":[{"text":"FaceDetectionQuery","kind":"identifier"}]}]}]}