{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/internalError"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.internalError"},{"type":"text","text":"."}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"metadata":{"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"externalID":"s:7DotCore0A3SdkC5ErrorO08internalD0sAD_pSgvp","title":"internalError","symbolKind":"property","modules":[{"name":"DotFaceLite"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk\/error\/internalerror"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"abstract":[{"type":"text","text":"Class responsible for the initialization of DOT libraries - "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotPalm"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","url":"\/documentation\/dotfacelite\/dotsdk","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdk"}],"type":"topic","kind":"symbol","title":"DotSdk","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotSdk"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error/internalError":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotsdk\/error\/internalerror","title":"internalError","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error\/internalError","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Error":{"abstract":[],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Error","url":"\/documentation\/dotfacelite\/dotsdk\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","title":"DotSdk.Error","role":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}]}]}]}