{"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC13detectionArea0aC015RectangleDoubleCSgvp","symbolKind":"property","title":"detectionArea","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?"}]},"kind":"symbol","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the palm detection."}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/detectionArea","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/detectionarea"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/detectionArea":{"role":"symbol","type":"topic","title":"detectionArea","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/detectionarea","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the palm detection."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/detectionArea","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea"},{"kind":"text","text":": "},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"role":"symbol","abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"kind":"symbol","title":"PalmAutoCaptureController.Configuration","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","url":"\/documentation\/dotpalmcore\/rectangledouble","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"kind":"symbol","title":"PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/navigatorTitle","op":"replace"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle"}]}]}