{"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionNormalizedRectangle"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","title":"detectionNormalizedRectangle","symbolKind":"property","externalID":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC28detectionNormalizedRectangle0aC00J6DoubleCSgvp"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"detectionNormalizedRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/detectionnormalizedrectangle"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/detectionNormalizedRectangle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the palm detection."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.8.0"}],"role":"collection","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","title":"PalmAutoCaptureController.Configuration","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Configuration of the palm auto capture non-UI component."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"type":"topic","title":"RectangleDouble","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/rectangledouble"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class/detectionNormalizedRectangle":{"abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the palm detection."}],"title":"detectionNormalizedRectangle","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class\/detectionnormalizedrectangle","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class\/detectionNormalizedRectangle","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","value":"DOTPPalmAutoCaptureController","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments","value":[{"text":"DOTRectangleDouble","kind":"identifier"}]}]}]}