{"sections":[],"kind":"article","topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/composeWithInternalError()"],"generated":true}],"metadata":{"role":"collectionGroup","title":"DotSdkError Implementations","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/dotsdkerror-implementations"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/DotSdkError-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibrary":{"title":"DotFaceLibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"code":"DotFace","type":"codeVoice"},{"type":"text","text":" library initialization."}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibrary","type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibrary","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibrary"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibrary"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration":{"type":"topic","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration","title":"DotFaceLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration of the "},{"code":"DotFace","type":"codeVoice"},{"text":" library. This class specifies how the ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":" library will be initialized.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"DotFaceLibraryConfiguration.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error","type":"topic","role":"symbol","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfiguration/Error/composeWithInternalError()":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfiguration\/Error\/composeWithInternalError()","url":"\/documentation\/dotfacecore\/dotfacelibraryconfiguration\/error\/composewithinternalerror()","abstract":[],"role":"symbol","type":"topic","kind":"symbol","title":"composeWithInternalError()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/title","value":"DotFaceLibrary","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceLibrary"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibrary\/fragments"},{"op":"replace","value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}