{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/logger\/loglevel"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/logger\/loglevel"]}],"metadata":{"title":"logLevel","modules":[{"name":"DotDocument"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDLogger(cpy)logLevel","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTLoggerLogLevel","text":"LoggerLogLevel"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/logLevel","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"logLevel","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","text":"LoggerLogLevel","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTLoggerLogLevel"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"code":".none","type":"codeVoice"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger/logLevel":{"navigatorTitle":[{"text":"logLevel","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/logLevel","abstract":[{"text":"Log level currently in use. Default value is ","type":"text"},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"title":"logLevel","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTLoggerLogLevel","kind":"typeIdentifier","text":"LoggerLogLevel"}],"url":"\/documentation\/dotdocument\/logger\/loglevel","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/LoggerLogLevel":{"title":"LoggerLogLevel","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"LoggerLogLevel","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/loggerloglevel","kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","abstract":[{"text":"Available log levels.","type":"text"}],"navigatorTitle":[{"text":"LoggerLogLevel","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger":{"url":"\/documentation\/dotdocument\/logger","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Logger"}],"navigatorTitle":[{"kind":"identifier","text":"Logger"}],"type":"topic","abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"role":"symbol","title":"Logger","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"path":"\/metadata\/title","value":"logLevel","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"logLevel"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":", "},{"text":"unsafe_unretained","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTLoggerLogLevel","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/LoggerLogLevel","preciseIdentifier":"c:@M@DotDocument@E@DOTLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"}]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger~1logLevel\/title","value":"logLevel","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger~1logLevel\/fragments","value":[{"kind":"identifier","text":"logLevel"}],"op":"replace"},{"op":"replace","value":"DOTLoggerLogLevel","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1LoggerLogLevel\/fragments","op":"replace","value":[{"text":"DOTLoggerLogLevel","kind":"identifier"}]},{"value":"DOTDLogger","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/title"},{"value":[{"kind":"identifier","text":"DOTDLogger"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/fragments","op":"replace"}]}]}