{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/LogLevel-swift.enum","preciseIdentifier":"s:11DotDocument6LoggerC8LogLevelO","text":"LogLevel"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/logger\/loglevel-swift.type.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/logger\/loglevel-swift.type.property"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/logLevel-swift.type.property","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"s:11DotDocument6LoggerC8LogLevelO"}],"title":"logLevel","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDLogger(cpy)logLevel","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"logLevel"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.1.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger":{"role":"symbol","title":"Logger","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Logger"}],"abstract":[{"type":"text","text":"Static class responsible for generating logs. You can configure log level."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Logger"}],"url":"\/documentation\/dotdocument\/logger"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger/logLevel-swift.type.property":{"role":"symbol","title":"logLevel","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"LogLevel","preciseIdentifier":"s:11DotDocument6LoggerC8LogLevelO"}],"abstract":[{"type":"text","text":"Log level currently in use. Default value is "},{"type":"codeVoice","code":".none"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/logLevel-swift.type.property","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"logLevel"}],"url":"\/documentation\/dotdocument\/logger\/loglevel-swift.type.property"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Logger/LogLevel-swift.enum":{"role":"symbol","title":"Logger.LogLevel","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"LogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Logger\/LogLevel-swift.enum","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LogLevel"}],"url":"\/documentation\/dotdocument\/logger\/loglevel-swift.enum"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDLoggerLogLevel":{"role":"symbol","title":"DOTDLoggerLogLevel","fragments":[{"kind":"identifier","text":"DOTDLoggerLogLevel"}],"abstract":[{"type":"text","text":"Available log levels."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDLoggerLogLevel","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotdloggerloglevel"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"logLevel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"logLevel"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDLoggerLogLevel","preciseIdentifier":"c:@M@DotDocument@E@DOTDLoggerLogLevel","text":"DOTDLoggerLogLevel"},{"kind":"text","text":" "},{"kind":"identifier","text":"logLevel"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/title","value":"DOTDLogger"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger\/fragments","value":[{"kind":"identifier","text":"DOTDLogger"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger~1logLevel-swift.type.property\/title","value":"logLevel"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Logger~1logLevel-swift.type.property\/fragments","value":[{"kind":"identifier","text":"logLevel"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}