{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/wrapped\/phase"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"roleHeading":"Instance Property","externalID":"s:14DotFaceCommons0B16AutoCapturePhaseO7WrappedC5phaseACvp","title":"phase","role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"}],"modules":[{"name":"DotFaceCore"}]},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceAutoCapturePhase","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase"}]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped\/phase"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","title":"FaceAutoCapturePhase","url":"\/documentation\/dotfacecore\/faceautocapturephase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Wrapped":{"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Wrapped"}],"title":"FaceAutoCapturePhase.Wrapped","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturephase\/wrapped","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"Wrapped"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/Wrapped/phase":{"role":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"phase","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase","text":"FaceAutoCapturePhase"}],"title":"phase","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturephase\/wrapped\/phase","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/Wrapped\/phase","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","role":"collection"}},"variantOverrides":[{"patch":[{"value":"DOTFaceAutoCapturePhase","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}