{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone"]},{"paths":["\/documentation\/dotnfc\/td1machinereadablezone"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(DOTTd1MachineReadableZone) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"metadata":{"role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"title":"Td1MachineReadableZone","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone","symbolKind":"class","navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)"],"title":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/compositeCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentCode","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/name","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/nationality","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/optionalData","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/sex"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/isEqual(_:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"title":"Td1MachineReadableZone","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.15.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/documentCode":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentCode","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"documentCode"},{"text":": ","kind":"text"},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"abstract":[],"title":"documentCode","navigatorTitle":[{"text":"documentCode","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/documentcode"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/optionalData":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/optionalData","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionalData","kind":"identifier"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":"]"}],"abstract":[],"title":"optionalData","navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/optionaldata"},"doc://DotNfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotNfc\/objc(cs)NSObject"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/dateOfBirth":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfBirth","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dateOfBirth","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"abstract":[],"title":"dateOfBirth","navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/dateofbirth"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentCode"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"documentNumber","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"sex","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":"], "},{"text":"compositeCheckDigit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}],"abstract":[],"title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/hash":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/hash","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"title":"hash","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/hash"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/nationality":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/nationality","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"abstract":[],"title":"nationality","navigatorTitle":[{"kind":"identifier","text":"nationality"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/nationality"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/dateOfExpiry":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfExpiry","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit"}],"abstract":[],"title":"dateOfExpiry","navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/dateofexpiry"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/sex":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/sex","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sex"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}],"abstract":[],"title":"sex","navigatorTitle":[{"kind":"identifier","text":"sex"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/sex"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP"},"doc://DotNfc/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotNfc\/objc(pl)NSObject"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/isEqual(_:)":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/isequal(_:)"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/name":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/name","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzNameElement","text":"MrzNameElement"}],"abstract":[],"title":"name","navigatorTitle":[{"kind":"identifier","text":"name"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/name"},"doc://DotNfc/s7CVarArgP":{"identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/description":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/description"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/documentNumber":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentNumber","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"}],"abstract":[],"title":"documentNumber","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/documentnumber"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/issuingStateOrOrganization":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotnfc\/td1machinereadablezone\/issuingstateororganization","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"title":"issuingStateOrOrganization","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/issuingStateOrOrganization","role":"symbol"},"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/compositeCheckDigit":{"type":"topic","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/compositeCheckDigit","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"compositeCheckDigit","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"abstract":[],"title":"compositeCheckDigit","navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"kind":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone\/compositecheckdigit"},"doc://DotNfc/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTTd1MachineReadableZone"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/compositeCheckDigit","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfBirth","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/dateOfExpiry","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentCode","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/documentNumber","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/issuingStateOrOrganization","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/name","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/nationality","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/optionalData","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/sex"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/isEqual(_:)"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTTd1MachineReadableZone"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","op":"replace","value":"DOTTd1MachineReadableZone"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentCode\/title","value":"documentCode"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentCode\/fragments","value":[{"kind":"identifier","text":"documentCode"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1optionalData\/title","value":"optionalData","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1optionalData\/fragments","value":[{"text":"optionalData","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfBirth\/title","op":"replace","value":"dateOfBirth"},{"op":"replace","value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfBirth\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}]},{"value":"nationality","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1nationality\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1nationality\/fragments","value":[{"kind":"identifier","text":"nationality"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfExpiry\/title","op":"replace","value":"dateOfExpiry"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1dateOfExpiry\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1sex\/title","op":"replace","value":"sex"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1sex\/fragments","value":[{"text":"sex","kind":"identifier"}],"op":"replace"},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1isEqual(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isEqual:"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1isEqual(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1name\/title","value":"name"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1name\/fragments","value":[{"text":"name","kind":"identifier"}]},{"value":"description","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1description\/title","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1description\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentNumber\/title","value":"documentNumber","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1documentNumber\/fragments","value":[{"text":"documentNumber","kind":"identifier"}]},{"value":"issuingStateOrOrganization","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1issuingStateOrOrganization\/title"},{"value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1issuingStateOrOrganization\/fragments"},{"value":"compositeCheckDigit","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1compositeCheckDigit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1compositeCheckDigit\/fragments","value":[{"kind":"identifier","text":"compositeCheckDigit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}