{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isVideoCaptureEnabled"},"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isVideoCaptureEnabled","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)isVideoCaptureEnabled"},"variants":[{"paths":["\/documentation\/dotdocument\/cameraconfiguration\/isvideocaptureenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/cameraconfiguration\/isvideocaptureenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"isVideoCaptureEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration"]]},"abstract":[{"text":"Use this flag to enable\/disable video capture.","type":"text"},{"text":" ","type":"text"},{"text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session.","type":"text"},{"text":" ","type":"text"},{"text":"The captured video is included exclusively in the binary content of the result. Default is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}],"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CameraConfiguration":{"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration","type":"topic","url":"\/documentation\/dotdocument\/cameraconfiguration","title":"CameraConfiguration","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CameraConfiguration/isVideoCaptureEnabled":{"kind":"symbol","type":"topic","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isVideoCaptureEnabled","kind":"identifier"}],"url":"\/documentation\/dotdocument\/cameraconfiguration\/isvideocaptureenabled","abstract":[{"type":"text","text":"Use this flag to enable\/disable video capture."},{"type":"text","text":" "},{"type":"text","text":"When enabled, the recording duration is limited to a maximum of 8 seconds, corresponding to the end of the processing session."},{"type":"text","text":" "},{"type":"text","text":"The captured video is included exclusively in the binary content of the result. Default is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"title":"isVideoCaptureEnabled","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraConfiguration\/isVideoCaptureEnabled"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isVideoCaptureEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"isVideoCaptureEnabled"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/title","op":"replace","value":"DOTCameraConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isVideoCaptureEnabled\/title","op":"replace","value":"isVideoCaptureEnabled"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraConfiguration~1isVideoCaptureEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isVideoCaptureEnabled"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}