{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholder\/visible\/type"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/type"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Placeholder type. Default is "},{"type":"codeVoice","code":".cornersOnly"},{"type":"text","text":"."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"type","symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PlaceholderType","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType"}],"externalID":"s:11DotDocument11PlaceholderC7VisibleC4typeAA0C4TypeOvp","roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","abstract":[{"type":"text","text":"version: 9.2.0"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible":{"abstract":[{"type":"text","text":"Visible placeholder."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible","title":"Placeholder.Visible","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Visible","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholder\/visible","role":"symbol","navigatorTitle":[{"text":"Visible","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Placeholder":{"title":"Placeholder","kind":"symbol","navigatorTitle":[{"text":"Placeholder","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholder","type":"topic","abstract":[{"type":"text","text":"Placeholder."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Placeholder","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Placeholder/Visible/type":{"type":"topic","url":"\/documentation\/dotdocument\/placeholder\/visible\/type","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Placeholder\/Visible\/type","abstract":[{"type":"text","text":"Placeholder type. Default is "},{"code":".cornersOnly","type":"codeVoice"},{"type":"text","text":"."}],"title":"type","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"type","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDPlaceholderType","text":"PlaceholderType","kind":"typeIdentifier"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"role":"symbol","title":"PlaceholderType","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","abstract":[{"text":"Type of placeholder.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"url":"\/documentation\/dotdocument\/placeholdertype","kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTDPlaceholder","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/title"},{"op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/fragments"},{"op":"replace","value":[{"text":"DOTDPlaceholder","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Placeholder\/navigatorTitle"},{"op":"replace","value":"DOTDPlaceholderType","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments"},{"op":"replace","value":[{"text":"DOTDPlaceholderType","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}