{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureconfiguration\/error\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error\/Equatable-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error\/!=(_:_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"Equatable Implementations"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Error":{"role":"symbol","title":"DocumentAutoCaptureConfiguration.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/error"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration/Error/!=(_:_:)":{"role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"kind":"text","text":" "},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration\/Error\/!=(_:_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureconfiguration\/error\/!=(_:_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureConfiguration":{"role":"symbol","title":"DocumentAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocaptureconfiguration"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/title","value":"DOTDocumentAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}