{"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)"},"sections":[],"kind":"symbol","metadata":{"roleHeading":"Initializer","modules":[{"name":"DotDocument"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"}],"title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator(im)initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minEdgeLengthToImageShorterSideRatioThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)"]},{"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/SizeTooSmallValidator":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator","url":"\/documentation\/dotdocument\/sizetoosmallvalidator","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/SizeTooSmallValidator/init(minEdgeLengthToImageShorterSideRatioThreshold:)":{"abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/SizeTooSmallValidator\/init(minEdgeLengthToImageShorterSideRatioThreshold:)","title":"init(minEdgeLengthToImageShorterSideRatioThreshold:)","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/init(minedgelengthtoimageshortersideratiothreshold:)","navigatorTitle":[{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:d","kind":"typeIdentifier","text":"double"},{"kind":"text","text":") "},{"kind":"internalParam","text":"minEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDSizeTooSmallValidator","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTDSizeTooSmallValidator","kind":"identifier"}]},{"value":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithMinEdgeLengthToImageShorterSideRatioThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1SizeTooSmallValidator~1init(minEdgeLengthToImageShorterSideRatioThreshold:)\/fragments"}]}]}