{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/init(x:y:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(x:y:)","externalID":"c:@M@DotCore@objc(cs)DOTPointInt(im)initWithX:y:","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}]},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt"]]},"variants":[{"paths":["\/documentation\/dotnfc\/pointint\/init(x:y:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/pointint\/init(x:y:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/PointInt":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"url":"\/documentation\/dotnfc\/pointint","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt","title":"PointInt"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","role":"collection","title":"DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.17.1","type":"text"}]},"doc://DotNfc/documentation/DotNfc/PointInt/init(x:y:)":{"type":"topic","url":"\/documentation\/dotnfc\/pointint\/init(x:y:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointInt\/init(x:y:)","title":"init(x:y:)","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initWithX:y:"}],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":", "},{"kind":"externalParam","text":"y"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithX:y:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithX:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"kind":"text","text":") "},{"kind":"internalParam","text":"x"},{"kind":"text","text":" "},{"kind":"identifier","text":"y:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"y","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPointInt","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/title","op":"replace"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/fragments","op":"replace"},{"value":[{"text":"DOTPointInt","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt\/navigatorTitle"},{"value":"initWithX:y:","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1init(x:y:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointInt~1init(x:y:)\/fragments"}]}]}