{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"createPlaceholderPath","kind":"identifier"},{"kind":"text","text":"("},{"text":"rect","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPath"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"text":"CGRect","preciseIdentifier":"c:@S@CGRect","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"cornerRadius"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":") -> ","kind":"text"},{"text":"UIBezierPath","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIBezierPath"}],"externalID":"c:@M@DotDocument@objc(cs)DOTBezierPathFactory(cm)createPlaceholderPathWithRect:cornerRadius:","title":"createPlaceholderPath(rect:cornerRadius:)","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory":{"navigatorTitle":[{"kind":"identifier","text":"BezierPathFactory"}],"url":"\/documentation\/dotdocument\/bezierpathfactory","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BezierPathFactory","kind":"identifier"}],"abstract":[],"title":"BezierPathFactory","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory","type":"topic","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/BezierPathFactory/createPlaceholderPath(rect:cornerRadius:)":{"navigatorTitle":[{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/bezierpathfactory\/createplaceholderpath(rect:cornerradius:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"createPlaceholderPath"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGRect","text":"CGRect"},{"text":", ","kind":"text"},{"text":"cornerRadius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIBezierPath","kind":"typeIdentifier","text":"UIBezierPath"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/BezierPathFactory\/createPlaceholderPath(rect:cornerRadius:)","title":"createPlaceholderPath(rect:cornerRadius:)","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","value":"createPlaceholderPathWithRect:cornerRadius:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createPlaceholderPathWithRect:cornerRadius:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIBezierPath","preciseIdentifier":"c:objc(cs)UIBezierPath"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"createPlaceholderPathWithRect:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"rect"},{"kind":"text","text":" "},{"text":"cornerRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"text":") ","kind":"text"},{"text":"cornerRadius","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/title","value":"DOTBezierPathFactory","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory\/fragments","value":[{"text":"DOTBezierPathFactory","kind":"identifier"}]},{"value":"createPlaceholderPathWithRect:cornerRadius:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"createPlaceholderPathWithRect:cornerRadius:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1BezierPathFactory~1createPlaceholderPath(rect:cornerRadius:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}