{"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotNfc\/objc(pl)NSObject","doc:\/\/DotNfc\/s7CVarArgP","doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/dotnfc\/commonconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/commonconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Common configuration for all components.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTCommonConfiguration) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"CommonConfiguration","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","modules":[{"name":"DotNfc"}],"symbolKind":"class","role":"symbol","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CommonConfiguration"}],"navigatorTitle":[{"text":"CommonConfiguration","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"topicSections":[{"anchor":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/init(sessionToken:)"],"title":"Initializers","generated":true},{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/sessionToken"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/isEqual(_:)"]}],"references":{"doc://DotNfc/SH":{"identifier":"doc:\/\/DotNfc\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/init(sessionToken:)":{"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/commonconfiguration\/init(sessiontoken:)","title":"init(sessionToken:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:"}],"abstract":[],"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"sessionToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/init(sessionToken:)"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/hash":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/hash","url":"\/documentation\/dotnfc\/commonconfiguration\/hash","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","role":"symbol","abstract":[],"navigatorTitle":[{"text":"hash","kind":"identifier"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration","kind":"symbol","title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"url":"\/documentation\/dotnfc\/commonconfiguration","abstract":[{"type":"text","text":"Common configuration for all components."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/isEqual(_:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/isEqual(_:)","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/commonconfiguration\/isequal(_:)","abstract":[],"role":"symbol","title":"isEqual(_:)"},"doc://DotNfc/objc(pl)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotNfc/SQ":{"identifier":"doc:\/\/DotNfc\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotNfc/objc(cs)NSObject":{"identifier":"doc:\/\/DotNfc\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotNfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotNfc/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotNfc\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/description":{"navigatorTitle":[{"text":"description","kind":"identifier"}],"type":"topic","abstract":[],"title":"description","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/description","url":"\/documentation\/dotnfc\/commonconfiguration\/description","kind":"symbol","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://DotNfc/documentation/DotNfc/CommonConfiguration/sessionToken":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionToken","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/sessionToken","navigatorTitle":[{"text":"sessionToken","kind":"identifier"}],"url":"\/documentation\/dotnfc\/commonconfiguration\/sessiontoken","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Session token provided by DIS (Digital Identity Service). Set the session token if the result should be posted to DIS for evaluation. Default is "},{"code":"nil","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","title":"sessionToken"},"doc://DotNfc/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotNfc\/s7CVarArgP","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/description","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/hash","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/sessionToken"]},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/init(sessionToken:)","doc:\/\/DotNfc\/documentation\/DotNfc\/CommonConfiguration\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotNfc\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCommonConfiguration"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1init(sessionToken:)\/title","value":"initWithSessionToken:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1init(sessionToken:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1hash\/title","value":"hash"},{"op":"replace","value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1hash\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"value":"isEqual:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1isEqual(_:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1sessionToken\/title","value":"sessionToken"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1CommonConfiguration~1sessionToken\/fragments","value":[{"text":"sessionToken","kind":"identifier"}]}]}]}