{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/DotNfc\/s23CustomStringConvertibleP","doc:\/\/DotNfc\/SQ","doc:\/\/DotNfc\/SH","doc:\/\/DotNfc\/SY"],"type":"conformsTo"}],"topicSections":[{"generated":true,"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/barcode"]},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/init(rawValue:)"]},{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/description"]},{"generated":true,"anchor":"Default-Implementations","title":"Default Implementations","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/Equatable-Implementations","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/RawRepresentable-Implementations"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId"},"abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotdocumentmoduleid"]}],"metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"}],"title":"DotDocumentModuleId","symbolKind":"enum","externalID":"c:@M@DotCore@E@DotDocumentModuleId","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Enumeration","role":"symbol"},"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/description":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/description","type":"topic","title":"description","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/description","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId":{"title":"DotDocumentModuleId","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentModuleId"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentModuleId"}],"abstract":[{"code":"DotDocument","type":"codeVoice"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotnfc\/dotdocumentmoduleid","role":"symbol"},"doc://DotNfc/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/DotNfc\/SY"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/barcode":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/barcode","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/barcode","type":"topic","navigatorTitle":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}],"title":"DotDocumentModuleId.barcode","abstract":[],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/RawRepresentable-Implementations":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/rawrepresentable-implementations","type":"topic","title":"RawRepresentable Implementations","kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/RawRepresentable-Implementations","abstract":[],"role":"collectionGroup"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/Equatable-Implementations":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/equatable-implementations","type":"topic","title":"Equatable Implementations","kind":"article","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/Equatable-Implementations","abstract":[],"role":"collectionGroup"},"doc://DotNfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotNfc\/s23CustomStringConvertibleP"},"doc://DotNfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotNfc\/SQ"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/DotDocumentModuleId/init(rawValue:)":{"url":"\/documentation\/dotnfc\/dotdocumentmoduleid\/init(rawvalue:)","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/init(rawValue:)","type":"topic","title":"init(rawValue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotNfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotNfc\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"path":"\/metadata\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/metadata\/symbolKind","op":"replace","value":"enum"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","title":"Enumeration Cases","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentModuleId\/barcode"],"generated":true}]},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentModuleId","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/title","op":"replace","value":"DotDocumentModuleId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/fragments","op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId\/navigatorTitle","op":"replace","value":[{"text":"DotDocumentModuleId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId~1barcode\/title","op":"replace","value":"DotDocumentModuleIdBarcode"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentModuleId~1barcode\/fragments","op":"replace","value":[{"text":"DotDocumentModuleIdBarcode","kind":"identifier"}]}]}]}