{"metadata":{"externalID":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatus(py)authenticationProtocol","modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","title":"authenticationProtocol","role":"symbol","navigatorTitle":[{"text":"authenticationProtocol","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.property"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"]]},"sections":[],"abstract":[{"type":"text","text":"Protocol used for that purpose."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"authenticationProtocol"},{"kind":"text","text":": "},{"preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","kind":"typeIdentifier","text":"WrappedProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol"},{"kind":"text","text":"?"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/authenticationProtocol-swift.property"},"references":{"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol":{"navigatorTitle":[{"text":"WrappedProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol","abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"AuthenticationProtocol"},{"type":"text","text":"."}],"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedProtocol","kind":"identifier"}],"type":"topic","title":"ChipAuthenticationStatus.WrappedProtocol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/authenticationProtocol-swift.property":{"navigatorTitle":[{"text":"authenticationProtocol","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/authenticationProtocol-swift.property","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/authenticationprotocol-swift.property","abstract":[{"type":"text","text":"Protocol used for that purpose."}],"role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"authenticationProtocol","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedProtocol","preciseIdentifier":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","title":"authenticationProtocol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"title":"ChipAuthenticationStatus","role":"symbol","abstract":[{"text":"Authentication status of the chip and protocol used for that purpose.","type":"text"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus"},"doc://DotNfc/documentation/DotNfc/DOTNChipAuthenticationStatusWrappedProtocol":{"abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"text","text":"AuthenticationProtocol"},{"type":"text","text":"."}],"fragments":[{"text":"DOTNChipAuthenticationStatusWrappedProtocol","kind":"identifier"}],"type":"topic","title":"DOTNChipAuthenticationStatusWrappedProtocol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/dotnchipauthenticationstatuswrappedprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"authenticationProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"authenticationProtocol","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNChipAuthenticationStatusWrappedProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNChipAuthenticationStatusWrappedProtocol","text":"DOTNChipAuthenticationStatusWrappedProtocol"},{"kind":"text","text":" * "},{"kind":"identifier","text":"authenticationProtocol"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1authenticationProtocol-swift.property\/title","value":"authenticationProtocol"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus~1authenticationProtocol-swift.property\/fragments","value":[{"kind":"identifier","text":"authenticationProtocol"}]},{"op":"replace","value":"DOTNChipAuthenticationStatus","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title"},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle"}]}]}