{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC20backgroundUniformityAA0ac10Backgroundh6ModuleE0CSgvp","role":"symbol","title":"backgroundUniformity","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":"?"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","title":"DotFaceLibraryConfiguration.Modules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"url":"\/documentation\/dotfingerscore\/dotfacebackgrounduniformitymoduleconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/backgroundUniformity":{"type":"topic","title":"backgroundUniformity","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/backgrounduniformity","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/backgroundUniformity","kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"backgroundUniformity","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}