{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/detection"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"}],"title":"detection","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/detection":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/detection","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/detection","title":"detection","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","title":"DotFaceLibraryConfiguration.Modules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]}]}]}