{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A24FaceLibraryConfigurationC7ModulesC15eyeGazeLivenessAA0ac3Eyehi6ModuleE0CSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?","kind":"text"}],"title":"eyeGazeLiveness","role":"symbol","roleHeading":"Instance Property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class","title":"DotFaceLibraryConfiguration.Modules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration","title":"DotFaceLibraryConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face library configuration."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfiguration/Modules-swift.class/eyeGazeLiveness":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfiguration\/Modules-swift.class\/eyeGazeLiveness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":"?"}],"kind":"symbol","role":"symbol","title":"eyeGazeLiveness","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfiguration\/modules-swift.class\/eyegazeliveness"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/fragments","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]}]}]}