{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"]]},"abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"text":" identifier.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}]}]}],"metadata":{"role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"nfc","kind":"identifier"}],"navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdNfc","title":"DotLibraryId.nfc","symbolKind":"case","modules":[{"name":"DotFaceLite"}]},"variants":[{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/nfc"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotlibraryid\/nfc"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/nfc","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","url":"\/documentation\/dotfacelite\/dotlibraryid","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId/nfc":{"navigatorTitle":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"title":"DotLibraryId.nfc","abstract":[{"type":"codeVoice","code":"DotNfcLibrary"},{"type":"text","text":" identifier."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"nfc","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId\/nfc","url":"\/documentation\/dotfacelite\/dotlibraryid\/nfc","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 9.2.3"}],"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotLibraryIdNfc","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/navigatorTitle"},{"op":"replace","value":"DotLibraryIdNfc","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1nfc\/title"},{"op":"replace","value":[{"text":"DotLibraryIdNfc","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId~1nfc\/fragments"}]}]}