{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult"]]},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureresult\/init(requestcaptureimage:fingerbundles:content:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersautocaptureresult\/init(requestcaptureimage:fingerbundles:content:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"title":"init(requestCaptureImage:fingerBundles:content:)","navigatorTitle":[{"kind":"identifier","text":"initWithRequestCaptureImage:fingerBundles:content:"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult(im)initWithRequestCaptureImage:fingerBundles:content:","symbolKind":"init","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"requestCaptureImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"fingerBundles"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles","kind":"typeIdentifier","text":"FingerBundles"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"roleHeading":"Initializer","role":"symbol"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestCaptureImage"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fingerBundles"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles","kind":"typeIdentifier","text":"FingerBundles"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult\/init(requestCaptureImage:fingerBundles:content:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult/init(requestCaptureImage:fingerBundles:content:)":{"kind":"symbol","title":"init(requestCaptureImage:fingerBundles:content:)","url":"\/documentation\/dotfingerscore\/fingersautocaptureresult\/init(requestcaptureimage:fingerbundles:content:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requestCaptureImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fingerBundles"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingerBundles","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithRequestCaptureImage:fingerBundles:content:"}],"type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult\/init(requestCaptureImage:fingerBundles:content:)"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/Image":{"role":"symbol","title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"url":"\/documentation\/dotfingerscore\/image","abstract":[],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Image"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"role":"symbol","title":"FingersAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"abstract":[{"type":"text","text":"The final result of the fingers auto capture process."}],"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"abstract":[{"type":"text","text":"Bundles of finger images with detection data."}],"url":"\/documentation\/dotfingerscore\/fingerbundles","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"title":"FingerBundles","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithRequestCaptureImage:fingerBundles:content:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequestCaptureImage:fingerBundles:content:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithRequestCaptureImage:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Image"},{"text":" *) ","kind":"text"},{"text":"requestCaptureImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"fingerBundles:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingerBundles","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"},{"text":" *) ","kind":"text"},{"text":"fingerBundles","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"content","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult~1init(requestCaptureImage:fingerBundles:content:)\/title","value":"initWithRequestCaptureImage:fingerBundles:content:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult~1init(requestCaptureImage:fingerBundles:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequestCaptureImage:fingerBundles:content:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/title","value":"DOTImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/fragments","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title","value":"DOTFGFingerBundles"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}]}]}]}