{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDImagePerspectiveWarper) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePerspectiveWarper"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotDocument"}],"title":"ImagePerspectiveWarper","symbolKind":"class","roleHeading":"Class","navigatorTitle":[{"text":"ImagePerspectiveWarper","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDImagePerspectiveWarper"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/imageperspectivewarper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageperspectivewarper"]}],"abstract":[{"text":"Stateless class which can warp the image perspective and create new image as a result.","type":"text"}],"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:detectionPosition:targetImageSize:)"]}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo"}],"seeAlsoSections":[{"generated":true,"title":"Non-UI components","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"]}],"sections":[],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","type":"topic","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentDetector":{"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImageParametersAnalyzer":{"role":"symbol","abstract":[{"text":"Stateless class which can analyze image parameters.","type":"text"}],"kind":"symbol","title":"ImageParametersAnalyzer","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageParametersAnalyzer"}],"url":"\/documentation\/dotdocument\/imageparametersanalyzer","navigatorTitle":[{"text":"ImageParametersAnalyzer","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can warp the image perspective and create new image as a result."}],"kind":"symbol","title":"ImagePerspectiveWarper","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImagePerspectiveWarper","kind":"identifier"}],"url":"\/documentation\/dotdocument\/imageperspectivewarper","navigatorTitle":[{"kind":"identifier","text":"ImagePerspectiveWarper"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DOTDImagePerspectiveWarper/init":{"kind":"symbol","type":"topic","role":"symbol","abstract":[],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}],"title":"init","url":"\/documentation\/dotdocument\/dotdimageperspectivewarper\/init","navigatorTitle":[{"kind":"identifier","text":"init"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDImagePerspectiveWarper\/init"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/ImagePerspectiveWarper/warp(bgraRawImage:detectionPosition:targetImageSize:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"warp"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentDetectionPosition","text":"DetectionPosition"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"targetImageSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTImageSize","text":"ImageSize"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTBgraRawImage"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:detectionPosition:targetImageSize:)","url":"\/documentation\/dotdocument\/imageperspectivewarper\/warp(bgrarawimage:detectionposition:targetimagesize:)","role":"symbol","title":"warp(bgraRawImage:detectionPosition:targetImageSize:)","type":"topic","abstract":[{"type":"text","text":"Warp the image perspective using the document detection result."}],"navigatorTitle":[{"kind":"identifier","text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"DOTDImagePerspectiveWarper","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"DOTDImagePerspectiveWarper"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DOTDImagePerspectiveWarper\/init","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImagePerspectiveWarper\/warp(bgraRawImage:detectionPosition:targetImageSize:)"],"title":"Instance Methods"}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentDetector","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/ImageParametersAnalyzer","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"],"generated":true,"title":"Non-UI components"}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTDImagePerspectiveWarper"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"value":"DOTDImageParametersAnalyzer","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImageParametersAnalyzer\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDImageParametersAnalyzer"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/title","value":"DOTDImagePerspectiveWarper","op":"replace"},{"value":[{"text":"DOTDImagePerspectiveWarper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper\/fragments"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:detectionPosition:targetImageSize:)\/title","op":"replace","value":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1ImagePerspectiveWarper~1warp(bgraRawImage:detectionPosition:targetImageSize:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"warpWithBgraRawImage:detectionPosition:targetImageSize:error:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}