{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTTd1MachineReadableZone) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td1machinereadablezone"]},{"paths":["\/documentation\/dotdocument\/td1machinereadablezone"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","interfaceLanguage":"swift"},"sections":[],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships"}],"kind":"symbol","seeAlsoSections":[{"title":"MRZ reading output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentNumber","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/hasAllChecksumsValid","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/optionalData","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/sex"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/isEqual(_:)"],"title":"Instance Methods"}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd1MachineReadableZone","title":"Td1MachineReadableZone","roleHeading":"Class","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"class"},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.1.0"}]},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)":{"title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}],"abstract":[],"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfBirth"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"dateOfExpiry","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzNameElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"},{"text":"], ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"},{"text":")","kind":"text"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td3MachineReadableZone":{"title":"Td3MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td3MachineReadableZone"}],"navigatorTitle":[{"text":"Td3MachineReadableZone","kind":"identifier"}],"abstract":[{"text":"Result of MRZ reading of TD3.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/td3machinereadablezone","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/sex":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/sex","title":"sex","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sex","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/sex","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"sex"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/dateOfBirth":{"kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/dateofbirth","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfBirth","role":"symbol","abstract":[],"title":"dateOfBirth"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"url":"\/documentation\/dotdocument\/td2machinereadablezone","title":"Td2MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","role":"symbol","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/hasAllChecksumsValid":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hasAllChecksumsValid","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/hasAllChecksumsValid","title":"hasAllChecksumsValid","abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/hasallchecksumsvalid","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/hash":{"title":"hash","abstract":[],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/hash","kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/hash","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"navigatorTitle":[{"text":"hash","kind":"identifier"}]},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/documentNumber":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"documentNumber","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentNumber","abstract":[],"title":"documentNumber","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"documentNumber"}],"type":"topic","url":"\/documentation\/dotdocument\/td1machinereadablezone\/documentnumber"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"title":"MrzElement","kind":"symbol","type":"topic","abstract":[{"text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"MrzElement","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"url":"\/documentation\/dotdocument\/mrzelement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzStringPosition":{"abstract":[{"type":"text","text":"A position of a string in Machine Readable Zone."}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/mrzstringposition","title":"MrzStringPosition","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzStringPosition"}],"navigatorTitle":[{"kind":"identifier","text":"MrzStringPosition"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/nationality":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/nationality","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"nationality"}],"title":"nationality","role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/td1machinereadablezone\/nationality","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"nationality","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/dateOfExpiry":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzDateElementWithCheckDigit"}],"title":"dateOfExpiry","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"dateOfExpiry"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfExpiry","url":"\/documentation\/dotdocument\/td1machinereadablezone\/dateofexpiry"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/optionalData":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionalData"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":"]","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/optionalData","title":"optionalData","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"optionalData"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/optionaldata","type":"topic"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/name":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"name"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzNameElement","text":"MrzNameElement"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/name","title":"name","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"name","kind":"identifier"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/name","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/documentCode":{"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentCode","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}],"navigatorTitle":[{"kind":"identifier","text":"documentCode"}],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/documentcode","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentCode","type":"topic","title":"documentCode","abstract":[]},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ","title":"Swift.Equatable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone":{"title":"Td1MachineReadableZone","abstract":[{"text":"Result of MRZ reading of TD1.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone","kind":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/compositeCheckDigit":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"compositeCheckDigit","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/compositeCheckDigit","title":"compositeCheckDigit","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"compositeCheckDigit"}],"type":"topic","url":"\/documentation\/dotdocument\/td1machinereadablezone\/compositecheckdigit"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/isEqual(_:)":{"title":"isEqual(_:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/isEqual(_:)","url":"\/documentation\/dotdocument\/td1machinereadablezone\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzDate":{"navigatorTitle":[{"text":"MrzDate","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzDate"}],"title":"MrzDate","abstract":[{"text":"Date parsed from Machine Readable Zone.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrzdate"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MachineReadableZone":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","abstract":[{"text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/machinereadablezone","title":"MachineReadableZone"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNameElement":{"abstract":[{"type":"text","text":"A Machine Readable Zone name element."}],"role":"symbol","kind":"symbol","title":"MrzNameElement","url":"\/documentation\/dotdocument\/mrznameelement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNameElement"}],"navigatorTitle":[{"text":"MrzNameElement","kind":"identifier"}]},"doc://com.innovatrics.dot.document/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/issuingStateOrOrganization":{"role":"symbol","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/issuingStateOrOrganization","abstract":[],"url":"\/documentation\/dotdocument\/td1machinereadablezone\/issuingstateororganization","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"text":"MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier"}],"title":"issuingStateOrOrganization","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"title":"MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzReader"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td1MachineReadableZone/description":{"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td1machinereadablezone\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/description"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTTd1MachineReadableZone"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/compositeCheckDigit","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfBirth","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/dateOfExpiry","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentCode","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/documentNumber","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/issuingStateOrOrganization","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/name","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/nationality","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/optionalData","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/sex"],"title":"Instance Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td1MachineReadableZone\/isEqual(_:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":[{"title":"MRZ reading output","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td3MachineReadableZone","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNameElement","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzDate","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzStringPosition"],"generated":true}],"op":"replace"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DOTTd1MachineReadableZone","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/title","op":"replace","value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}]},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td3MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1sex\/title","value":"sex"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1sex\/fragments","value":[{"kind":"identifier","text":"sex"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfBirth\/title","value":"dateOfBirth","op":"replace"},{"op":"replace","value":[{"text":"dateOfBirth","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfBirth\/fragments"},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}]},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1hash\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1hash\/fragments","op":"replace","value":[{"text":"hash","kind":"identifier"}]},{"value":"documentNumber","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1documentNumber\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1documentNumber\/fragments","value":[{"kind":"identifier","text":"documentNumber"}],"op":"replace"},{"op":"replace","value":"DOTMrzElement","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title"},{"value":[{"kind":"identifier","text":"DOTMrzElement"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/title","op":"replace","value":"DOTMrzStringPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzStringPosition\/fragments","value":[{"kind":"identifier","text":"DOTMrzStringPosition"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1nationality\/title","op":"replace","value":"nationality"},{"value":[{"text":"nationality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1nationality\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfExpiry\/title","value":"dateOfExpiry"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1dateOfExpiry\/fragments","value":[{"text":"dateOfExpiry","kind":"identifier"}],"op":"replace"},{"value":"optionalData","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1optionalData\/title"},{"value":[{"text":"optionalData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1optionalData\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1name\/title","value":"name"},{"value":[{"kind":"identifier","text":"name"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1name\/fragments"},{"value":"documentCode","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1documentCode\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1documentCode\/fragments","op":"replace","value":[{"kind":"identifier","text":"documentCode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1compositeCheckDigit\/title","value":"compositeCheckDigit","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1compositeCheckDigit\/fragments","op":"replace","value":[{"text":"compositeCheckDigit","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1isEqual(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/title","value":"DOTMrzDate","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzDate\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTMrzDate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"op":"replace","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MachineReadableZone\/fragments"},{"value":"DOTMrzNameElement","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1issuingStateOrOrganization\/title","value":"issuingStateOrOrganization"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1issuingStateOrOrganization\/fragments","value":[{"kind":"identifier","text":"issuingStateOrOrganization"}]},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1description\/title","value":"description"},{"value":[{"text":"description","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td1MachineReadableZone~1description\/fragments"}]}]}