{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.init(rawValue:)"},{"type":"text","text":"."}],"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/imageformat\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/init(rawValue:)"},"metadata":{"symbolKind":"init","role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":")","kind":"text"}],"externalID":"s:7DotCore11ImageFormatO8rawValueACSgSi_tcfc","title":"init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/init(rawValue:)":{"type":"topic","role":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/imageformat\/init(rawvalue:)","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"title":"ImageFormat","kind":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","url":"\/documentation\/dotpalmcore\/imageformat","type":"topic","abstract":[{"text":"Supported image formats.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","value":"DOTImageFormat","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}