{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/jpeg2000"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/imageformat\/jpeg2000"]}],"abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"case","roleHeading":"Case","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg2000","role":"symbol","title":"ImageFormat.jpeg2000"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg2000","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/jpeg2000":{"kind":"symbol","role":"symbol","abstract":[{"text":"JPEG2000 compressed image format","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/jpeg2000","navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"jpeg2000"}],"url":"\/documentation\/dotpalmcore\/imageformat\/jpeg2000","title":"ImageFormat.jpeg2000"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","type":"topic","url":"\/documentation\/dotpalmcore\/imageformat","title":"ImageFormat","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageFormat"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageFormat"}],"abstract":[{"text":"Supported image formats.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 9.2.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTImageFormatJpeg2000","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg2000\/title","value":"DOTImageFormatJpeg2000"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1jpeg2000\/fragments","value":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","value":"DOTImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","value":[{"kind":"identifier","text":"DOTImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImageFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}