{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The 4 bytes of color image pixel:","type":"text"}]},{"items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"0th byte: BB - blue"}]}]},{"content":[{"inlineContent":[{"text":"1st byte: GG - green","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"2nd byte: RR - red"}]}]},{"content":[{"inlineContent":[{"text":"3rd byte: 0  - alpha","type":"text"}],"type":"paragraph"}]}],"type":"unorderedList"}]}],"abstract":[{"text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha.","type":"text"}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatRawBgra","title":"ImageFormat.rawBgra","roleHeading":"Case","navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"symbolKind":"case"},"sections":[],"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/imageformat\/rawbgra"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgra","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat/rawBgra":{"title":"ImageFormat.rawBgra","role":"symbol","abstract":[{"type":"text","text":"Image with 8-bit BGRA color components with the values Blue, Green, and Red stored in 3 bytes and 1 byte of alpha."}],"navigatorTitle":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/imageformat\/rawbgra","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat\/rawBgra","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rawBgra","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageFormat":{"title":"ImageFormat","kind":"symbol","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageFormat","url":"\/documentation\/dotpalmcore\/imageformat","type":"topic","abstract":[{"text":"Supported image formats.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTImageFormatRawBgra"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTImageFormatRawBgra"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgra\/title","value":"DOTImageFormatRawBgra","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat~1rawBgra\/fragments","value":[{"text":"DOTImageFormatRawBgra","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/title","value":"DOTImageFormat","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/fragments","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageFormat\/navigatorTitle","value":[{"text":"DOTImageFormat","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}