{"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/palm","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]}]}],"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotlibraryid\/palm"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId"]]},"metadata":{"symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"DotLibraryIdPalm","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"title":"DotLibraryId.palm","roleHeading":"Case","externalID":"c:@M@DotCore@E@DotLibraryId@DotLibraryIdPalm","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.3.0"}],"role":"collection"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","type":"topic","title":"DotLibraryId","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotlibraryid","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotLibraryId/palm":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"}],"title":"DotLibraryId.palm","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId\/palm","url":"\/documentation\/dotnfc\/dotlibraryid\/palm","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"abstract":[{"code":"DotPalmLibrary","type":"codeVoice"},{"text":" identifier.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DotLibraryIdPalm"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DotLibraryIdPalm","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"DotLibraryIdPalm"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","op":"replace","value":"DotLibraryId"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/navigatorTitle"},{"value":"DotLibraryIdPalm","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1palm\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId~1palm\/fragments","value":[{"kind":"identifier","text":"DotLibraryIdPalm"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}