{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","text":"DotLibrary","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary"},{"text":"]","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(py)libraries","role":"symbol","title":"libraries","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"libraries"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary","kind":"typeIdentifier","text":"DotLibrary"},{"text":"]","kind":"text"}],"navigatorTitle":[{"text":"libraries","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/libraries"},"abstract":[{"text":"List of ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" libraries to use."}],"sections":[],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdkConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The "},{"type":"codeVoice","code":"DotSdk"},{"text":" configuration.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration","kind":"symbol","url":"\/documentation\/dotnfc\/dotsdkconfiguration","role":"symbol","title":"DotSdkConfiguration","navigatorTitle":[{"text":"DotSdkConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/DotSdkConfiguration/libraries":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"libraries"},{"kind":"text","text":": ["},{"text":"DotLibrary","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotLibrary"},{"kind":"text","text":"]"}],"type":"topic","abstract":[{"type":"text","text":"List of "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" libraries to use."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkConfiguration\/libraries","kind":"symbol","url":"\/documentation\/dotnfc\/dotsdkconfiguration\/libraries","role":"symbol","title":"libraries","navigatorTitle":[{"text":"libraries","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/DotLibrary":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibrary","url":"\/documentation\/dotnfc\/dotlibrary","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"abstract":[],"type":"topic","title":"DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"libraries","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"libraries","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<DotLibrary>>"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"libraries"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DotSdkConfiguration","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotSdkConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration~1libraries\/title","value":"libraries","op":"replace"},{"op":"replace","value":[{"text":"libraries","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkConfiguration~1libraries\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"kind":"identifier","text":"DotLibrary"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibrary\/fragments"}]}]}