{"sections":[],"metadata":{"title":"LocalizedError Implementations","modules":[{"name":"DotFaceCore"}],"roleHeading":"API Collection","role":"collectionGroup"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error"]]},"kind":"article","schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/failureReason","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/helpAnchor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/recoverySuggestion"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/LocalizedError-Implementations"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/localizederror-implementations"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration","abstract":[{"type":"text","text":"Configuration for face library components."}],"role":"symbol","title":"FaceLibraryComponentConfiguration","type":"topic","navigatorTitle":[{"text":"FaceLibraryComponentConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/helpAnchor":{"title":"helpAnchor","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/helpAnchor","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/helpanchor","abstract":[],"role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/failureReason":{"url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/failurereason","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/failureReason","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"failureReason"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"title":"failureReason","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error":{"abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"title":"FaceLibraryComponentConfiguration.Error","role":"symbol","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/FaceLibraryComponentConfiguration/Error/recoverySuggestion":{"role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotfacecore\/facelibrarycomponentconfiguration\/error\/recoverysuggestion","title":"recoverySuggestion","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceLibraryComponentConfiguration\/Error\/recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTFFaceLibraryComponentConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/title"},{"value":[{"text":"DOTFFaceLibraryComponentConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTFFaceLibraryComponentConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceLibraryComponentConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}