{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/camera"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"Default is:","type":"text"}]},{"type":"codeListing","code":[".init(cameraFacing: .front)"],"syntax":null}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class"]]},"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"sections":[],"metadata":{"symbolKind":"property","title":"camera","externalID":"s:11DotFaceCore32MultiRangeLivenessViewControllerC13ConfigurationC6camera0A7Capture06CameraI0Cvp","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"camera"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class/camera":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class\/camera","title":"camera","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class\/camera","kind":"symbol","role":"symbol","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","title":"CameraConfiguration","url":"\/documentation\/dotfacecore\/cameraconfiguration","kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}]},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"navigatorTitle":[{"text":"MultiRangeLivenessViewController","kind":"identifier"}],"title":"MultiRangeLivenessViewController","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController","abstract":[{"type":"text","text":"UI Multi-Range Liveness component."}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"text":"version: 9.3.0","type":"text"}],"type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessViewController/Configuration-swift.class":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"title":"MultiRangeLivenessViewController.Configuration","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/multirangelivenessviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessViewController\/Configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI Multi-Range Liveness component."}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title","value":"DOTCameraConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/title","value":"DOTFMultiRangeLivenessViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFMultiRangeLivenessViewController"}],"op":"replace"}]}]}