{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","text":"DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detection"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","abstract":[{"text":"Fingers library configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","title":"DotFingersDetectionModuleConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class/detection":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/detection","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration"}],"kind":"symbol","role":"symbol","title":"detection","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/detection"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotFingersLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/title","op":"replace"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFingersLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFingersDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}