{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"s:7DotCore0A27FingersLibraryConfigurationC7ModulesC9detection14transformationAeA0ac15DetectionModuleE0C_AA0ac14TransformationjE0CSgtcfc","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"?)"}],"title":"init(detection:transformation:)","role":"symbol","roleHeading":"Initializer"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transformation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersTransformationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration"},{"kind":"text","text":"? = nil)"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration","abstract":[{"text":"Fingers library configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class/init(detection:transformation:)":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class\/init(detection:transformation:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFingersDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration"},{"kind":"text","text":", "},{"text":"transformation","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotFingersTransformationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFingersTransformationModuleConfiguration"},{"text":"?)","kind":"text"}],"kind":"symbol","role":"symbol","title":"init(detection:transformation:)","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class\/init(detection:transformation:)"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfingersdetectionmoduleconfiguration","abstract":[{"text":"Fingers detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersDetectionModuleConfiguration","title":"DotFingersDetectionModuleConfiguration","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersTransformationModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotfingerstransformationmoduleconfiguration","abstract":[{"type":"text","text":"Fingers transformation module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersTransformationModuleConfiguration","title":"DotFingersTransformationModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFingersLibraryConfiguration/Modules-swift.class":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFingersLibraryConfiguration\/Modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"kind":"symbol","role":"symbol","title":"DotFingersLibraryConfiguration.Modules","abstract":[{"text":"Fingers library module configuration.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfingerslibraryconfiguration\/modules-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/title","value":"DotFingersLibraryConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersDetectionModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/title","value":"DotFingersTransformationModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFingersTransformationModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFingersTransformationModuleConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}