{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Generate random corners."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator\/generate(count:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator\/generate(count:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator\/generate(count:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":") -> [","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner"},{"text":"]","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"count","content":[{"inlineContent":[{"type":"text","text":"Number of corners to generate."}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"Generated array of corners.","type":"text"}],"type":"paragraph"}]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"generateWithCount:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"generate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"count"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":") -> ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner"},{"kind":"text","text":"]"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFRandomEyeGazeLivenessCornersGenerator(im)generateWithCount:","title":"generate(count:)","symbolKind":"method"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/WrappedEyeGazeLivenessCorner":{"abstract":[{"text":"Objective-C wrapper of ","type":"text"},{"type":"codeVoice","code":"EyeGazeLivenessCorner"},{"text":".","type":"text"}],"title":"WrappedEyeGazeLivenessCorner","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedEyeGazeLivenessCorner","kind":"symbol","url":"\/documentation\/dotfacecore\/wrappedeyegazelivenesscorner","type":"topic","navigatorTitle":[{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedEyeGazeLivenessCorner","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/RandomEyeGazeLivenessCornersGenerator/generate(count:)":{"title":"generate(count:)","abstract":[{"text":"Generate random corners.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator\/generate(count:)","navigatorTitle":[{"text":"generateWithCount:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"generate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"count","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":") -> [","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFWrappedEyeGazeLivenessCorner","text":"WrappedEyeGazeLivenessCorner","kind":"typeIdentifier"},{"text":"]","kind":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator\/generate(count:)"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/RandomEyeGazeLivenessCornersGenerator":{"role":"symbol","abstract":[{"text":"Generates random corners for the eye gaze liveness process.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/randomeyegazelivenesscornersgenerator","title":"RandomEyeGazeLivenessCornersGenerator","navigatorTitle":[{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RandomEyeGazeLivenessCornersGenerator","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RandomEyeGazeLivenessCornersGenerator","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"generateWithCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateWithCount:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSArray<DOTFWrappedEyeGazeLivenessCorner *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"generateWithCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"text":"count","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Number of corners to generate."}],"type":"paragraph"}],"name":"count"}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"Generated array of corners."}]}],"kind":"content"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/title","value":"DOTFWrappedEyeGazeLivenessCorner"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/fragments","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedEyeGazeLivenessCorner\/navigatorTitle","value":[{"text":"DOTFWrappedEyeGazeLivenessCorner","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator~1generate(count:)\/title","value":"generateWithCount:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator~1generate(count:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"generateWithCount:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/title","value":"DOTFRandomEyeGazeLivenessCornersGenerator"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/fragments","value":[{"kind":"identifier","text":"DOTFRandomEyeGazeLivenessCornersGenerator"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RandomEyeGazeLivenessCornersGenerator\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFRandomEyeGazeLivenessCornersGenerator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}