{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/sizetoosmallvalidator\/dependencyidentifiers"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/dependencyIdentifiers"},"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"DotDocument"}],"title":"dependencyIdentifiers","roleHeading":"Instance Property","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDSizeTooSmallValidator(py)dependencyIdentifiers"},"references":{"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator/dependencyIdentifiers":{"url":"\/documentation\/dotdocument\/sizetoosmallvalidator\/dependencyidentifiers","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator\/dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"type":"topic","kind":"symbol","title":"dependencyIdentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","title":"DotDocument","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","title":"SizeTooSmallValidator","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Validate size of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"title":"DocumentAutoCaptureController","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"dependencyIdentifiers","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"}]}]}},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1dependencyIdentifiers\/title"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator~1dependencyIdentifiers\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","op":"replace","value":"DOTDSizeTooSmallValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}]},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"}]}]}