{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/authenticationstatus\/isequal(_:)"]},{"paths":["\/documentation\/dotnfc\/authenticationstatus\/isequal(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/isEqual(_:)"},"sections":[],"metadata":{"modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false,"name":"iOS"}],"title":"isEqual(_:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNAuthenticationStatus(im)isEqual:","roleHeading":"Instance Method"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus"]]},"references":{"doc://DotNfc/documentation/DotNfc/AuthenticationStatus/isEqual(_:)":{"type":"topic","title":"isEqual(_:)","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"url":"\/documentation\/dotnfc\/authenticationstatus\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus\/isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]},"doc://DotNfc/documentation/DotNfc/AuthenticationStatus":{"title":"AuthenticationStatus","navigatorTitle":[{"kind":"identifier","text":"AuthenticationStatus"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AuthenticationStatus","url":"\/documentation\/dotnfc\/authenticationstatus","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AuthenticationStatus"}],"role":"symbol","abstract":[{"text":"Authentication status of data and chip.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"isEqual:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"isEqual:"},{"kind":"text","text":"("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"object"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1isEqual(_:)\/title","value":"isEqual:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus~1isEqual(_:)\/fragments","op":"replace"},{"value":"DOTNAuthenticationStatus","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/title"},{"value":[{"text":"DOTNAuthenticationStatus","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AuthenticationStatus\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}