{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/brightness","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Overall brightness of the document in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}]}]}],"metadata":{"symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"title":"brightness","externalID":"c:@M@DotDocument@objc(cs)DOTDImageParameters(py)brightness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotdocument\/imageparameters\/brightness"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/imageparameters\/brightness"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"type":"topic","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"title":"ImageParameters","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotdocument\/imageparameters"},"doc://DotDocument/documentation/DotDocument/ImageParameters/brightness":{"kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/imageparameters\/brightness","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/brightness","abstract":[{"type":"text","text":"Overall brightness of the document in range [0, 1.0]. Where 0 means low brightness and 1.0 means high brightness."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"brightness"}],"title":"brightness","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"brightness","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"brightness"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"brightness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDImageParameters","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title"},{"value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments"},{"value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/navigatorTitle"},{"value":"brightness","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1brightness\/title"},{"value":[{"text":"brightness","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1brightness\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}