{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/capturestepid\/mask"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/capturestepid\/mask"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mask","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"}],"title":"CaptureStepId.mask","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@DotFaceCore@E@DOTFCaptureStepId@DOTFCaptureStepIdMask","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFCaptureStepIdMask"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId":{"role":"symbol","title":"CaptureStepId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureStepId"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CaptureStepId"}],"url":"\/documentation\/dotfacecore\/capturestepid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/CaptureStepId/mask":{"role":"symbol","title":"CaptureStepId.mask","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/CaptureStepId\/mask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFCaptureStepIdMask"}],"url":"\/documentation\/dotfacecore\/capturestepid\/mask"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTFCaptureStepIdMask"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFCaptureStepIdMask"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"DOTFCaptureStepIdMask"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId\/title","value":"DOTFCaptureStepId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId\/fragments","value":[{"kind":"identifier","text":"DOTFCaptureStepId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mask\/title","value":"DOTFCaptureStepIdMask"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1CaptureStepId~1mask\/fragments","value":[{"kind":"identifier","text":"DOTFCaptureStepIdMask"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}