{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/hash"},"kind":"symbol","metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview(py)hash"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturepreview\/hash"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturepreview\/hash"]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"abstract":[{"text":"Geometric properties of the preview. All rectangles are defined relative to the preview container.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","role":"symbol","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"title":"DocumentAutoCapturePreview","url":"\/documentation\/dotdocument\/documentautocapturepreview"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/hash":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"title":"hash","url":"\/documentation\/dotdocument\/documentautocapturepreview\/hash"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTDDocumentAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title"},{"value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments"},{"value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle"},{"value":"hash","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1hash\/title"},{"value":[{"text":"hash","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1hash\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}