{"metadata":{"roleHeading":"Initializer","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":")"}],"modules":[{"name":"DotDocument"}],"title":"init(cameraImage:detectionArea:placeholder:)","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview(im)initWithCameraImage:detectionArea:placeholder:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCameraImage:detectionArea:placeholder:"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","text":"RectangleDouble"},{"text":", ","kind":"text"},{"text":"placeholder","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturepreview\/init(cameraimage:detectionarea:placeholder:)"]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturepreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"kind":"symbol","title":"DocumentAutoCapturePreview","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview/init(cameraImage:detectionArea:placeholder:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cameraImage"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"placeholder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(cameraImage:detectionArea:placeholder:)","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview\/init(cameraImage:detectionArea:placeholder:)","url":"\/documentation\/dotdocument\/documentautocapturepreview\/init(cameraimage:detectionarea:placeholder:)","kind":"symbol","navigatorTitle":[{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"abstract":[]},"doc://DotDocument/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleDouble","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}]},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithCameraImage:detectionArea:placeholder:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithCameraImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cameraImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionArea:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"detectionArea","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"placeholder:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTDDocumentAutoCapturePreview","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments"},{"op":"replace","value":[{"text":"DOTDDocumentAutoCapturePreview","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle"},{"op":"replace","value":"initWithCameraImage:detectionArea:placeholder:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCameraImage:detectionArea:placeholder:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview~1init(cameraImage:detectionArea:placeholder:)\/fragments"},{"op":"replace","value":"DOTRectangleDouble","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/title"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/fragments"},{"op":"replace","value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1RectangleDouble\/navigatorTitle"}]}]}