{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"td1","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","text":"Td1MachineReadableZone"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/td1","interfaceLanguage":"swift"},"abstract":[{"text":"Parsed MRZ of TD1.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"td1","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","externalID":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone(py)td1","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":"?"}],"role":"symbol","title":"td1"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotnfc\/machinereadablezone\/td1"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/td1"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone":{"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td1MachineReadableZone"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"url":"\/documentation\/dotnfc\/td1machinereadablezone","title":"Td1MachineReadableZone"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone/td1":{"url":"\/documentation\/dotnfc\/machinereadablezone\/td1","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/td1","type":"topic","navigatorTitle":[{"text":"td1","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"td1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Td1MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone"},{"kind":"text","text":"?"}],"role":"symbol","title":"td1","abstract":[{"type":"text","text":"Parsed MRZ of TD1."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone":{"role":"symbol","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}],"url":"\/documentation\/dotnfc\/machinereadablezone","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MachineReadableZone"}],"title":"MachineReadableZone","navigatorTitle":[{"text":"MachineReadableZone","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"td1","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"td1","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone","text":"DOTTd1MachineReadableZone","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"td1","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"DOTTd1MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","op":"replace","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1td1\/title","value":"td1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1td1\/fragments","value":[{"kind":"identifier","text":"td1"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/title","op":"replace","value":"DOTMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]}]}]}