{"metadata":{"title":"td3","externalID":"c:@M@DotNfc@objc(cs)DOTMachineReadableZone(py)td3","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"td3","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"td3","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Td3MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"td3","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/td3","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/machinereadablezone\/td3"]},{"paths":["\/documentation\/dotnfc\/machinereadablezone\/td3"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"abstract":[{"type":"text","text":"Parsed MRZ of TD3."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone":{"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/machinereadablezone","title":"MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachineReadableZone"}],"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZone"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone","kind":"symbol","abstract":[{"type":"text","text":"Universal Machine Readable Zone object which represents the result of MRZ reading. Contains parsed MRZ of one specific travel document type."}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","type":"topic","abstract":[{"text":"version: 8.3.2","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZone/td3":{"navigatorTitle":[{"kind":"identifier","text":"td3"}],"kind":"symbol","url":"\/documentation\/dotnfc\/machinereadablezone\/td3","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZone\/td3","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"td3"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","text":"Td3MachineReadableZone","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Parsed MRZ of TD3."}],"title":"td3","role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td3MachineReadableZone":{"url":"\/documentation\/dotnfc\/td3machinereadablezone","kind":"symbol","title":"Td3MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Td3MachineReadableZone","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Result of MRZ reading of TD3."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","navigatorTitle":[{"kind":"identifier","text":"Td3MachineReadableZone"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"td3"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"td3"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td3MachineReadableZone","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTTd3MachineReadableZone","kind":"typeIdentifier","text":"DOTTd3MachineReadableZone"},{"kind":"text","text":" * "},{"text":"td3","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/title","value":"DOTMachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTMachineReadableZone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1td3\/title","value":"td3"},{"value":[{"text":"td3","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZone~1td3\/fragments"},{"value":"DOTTd3MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td3MachineReadableZone\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTTd3MachineReadableZone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}