{"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"travelDocument","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","text":"TravelDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"metadata":{"symbolKind":"init","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"travelDocument"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","text":"TravelDocument"},{"kind":"text","text":", "},{"kind":"externalParam","text":"content"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"initWithTravelDocument:content:"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderResult(im)initWithTravelDocument:content:","role":"symbol","title":"init(travelDocument:content:)"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/init(travelDocument:content:)"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/init(traveldocument:content:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/init(traveldocument:content:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","title":"NfcTravelDocumentReader","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"abstract":[{"text":"Machine Readable Travel Document (eMRTD).","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"url":"\/documentation\/dotnfc\/traveldocument","kind":"symbol","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","type":"topic","title":"TravelDocument"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult","abstract":[{"text":"Result of the NFC Travel Document Reader component.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult","navigatorTitle":[{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReaderResult","kind":"identifier"}],"type":"topic","title":"NfcTravelDocumentReaderResult","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReaderResult/init(travelDocument:content:)":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReaderResult\/init(travelDocument:content:)","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderresult\/init(traveldocument:content:)","navigatorTitle":[{"text":"initWithTravelDocument:content:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"travelDocument","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TravelDocument","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"content","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(travelDocument:content:)"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithTravelDocument:content:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTravelDocument:content:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTravelDocument:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","text":"DOTNTravelDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNTravelDocument"},{"text":" *) ","kind":"text"},{"text":"travelDocument","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"content:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"content"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/title","value":"DOTNNfcTravelDocumentReaderResult"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/fragments","value":[{"text":"DOTNNfcTravelDocumentReaderResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1init(travelDocument:content:)\/title","value":"initWithTravelDocument:content:"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReaderResult~1init(travelDocument:content:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTravelDocument:content:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}