{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/wrappeddouble\/value"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/wrappeddouble\/value"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"value","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTWrappedDouble(py)value","modules":[{"name":"DotFaceCore"}],"symbolKind":"property","title":"value"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble\/value"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","title":"DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedDouble/value":{"kind":"symbol","url":"\/documentation\/dotfacecore\/wrappeddouble\/value","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble\/value","abstract":[],"title":"value"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/WrappedDouble":{"title":"WrappedDouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotfacecore\/wrappeddouble","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/WrappedDouble","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"value","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"value","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble~1value\/title","op":"replace","value":"value"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble~1value\/fragments","value":[{"text":"value","kind":"identifier"}]},{"value":"DOTWrappedDouble","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}