{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"text":"backgroundUniformity","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"backgroundUniformity","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)backgroundUniformity","navigatorTitle":[{"text":"backgroundUniformity","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"backgroundUniformity","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/backgrounduniformity"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"url":"\/documentation\/dotfingerscore\/dotfacebackgrounduniformitymoduleconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules/backgroundUniformity":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/backgroundUniformity","fragments":[{"kind":"identifier","text":"backgroundUniformity"}],"kind":"symbol","role":"symbol","title":"backgroundUniformity","abstract":[],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/backgrounduniformity"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]}]}]}