{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"},"metadata":{"fragments":[{"kind":"text","text":"- "},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(im)initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"roleHeading":"Instance Method","symbolKind":"method"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDetection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotFaceDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"detection"},{"text":" ","kind":"text"},{"kind":"identifier","text":"expressionNeutral:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"expressionNeutral"},{"kind":"text","text":" "},{"text":"backgroundUniformity:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundUniformity"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeGazeLiveness:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"eyeGazeLiveness"},{"kind":"text","text":" "},{"kind":"identifier","text":"passiveLiveness:"},{"text":"(","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"passiveLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"verification:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"verification"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","role":"symbol","abstract":[{"type":"text","text":"Face library module configuration."}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFacePassiveLivenessModuleConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFacePassiveLivenessModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFacePassiveLivenessModuleConfiguration","abstract":[{"text":"Face passive liveness module.","type":"text"}],"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacepassivelivenessmoduleconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfaceeyegazelivenessmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceEyeGazeLivenessModuleConfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceVerificationModuleConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfaceverificationmoduleconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceVerificationModuleConfiguration","title":"DotFaceVerificationModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face verification module."}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceDetectionModuleConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/dotfacedetectionmoduleconfiguration","abstract":[{"type":"text","text":"Face detection module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceDetectionModuleConfiguration","title":"DotFaceDetectionModuleConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceExpressionNeutralModuleConfiguration":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"DotFaceExpressionNeutralModuleConfiguration","abstract":[{"type":"text","text":"Face expression neutral module."}],"navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfaceexpressionneutralmoduleconfiguration"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceLibraryConfigurationModules/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","abstract":[],"navigatorTitle":[{"text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","abstract":[{"text":"Face background uniformity module.","type":"text"}],"url":"\/documentation\/dotfingerscore\/dotfacebackgrounduniformitymoduleconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceDetectionModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceExpressionNeutralModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotFaceBackgroundUniformityModuleConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle"}]}]}