{"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"bytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","title":"init(format:bytes:size:)","modules":[{"name":"DotNfc"}],"externalID":"s:7DotCore5ImageC6format5bytes4sizeAcA0C6FormatO_10Foundation4DataVAA0C4SizeCtcfc","symbolKind":"init","roleHeading":"Initializer"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/init(format:bytes:size:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"ImageFormat","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","text":"ImageSize"},{"kind":"text","text":")"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Image"]]},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/image\/init(format:bytes:size:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/ImageFormat":{"kind":"symbol","title":"ImageFormat","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ImageFormat","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageFormat","url":"\/documentation\/dotnfc\/imageformat","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"text":"Supported image formats.","type":"text"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc/Image/init(format:bytes:size:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image\/init(format:bytes:size:)","url":"\/documentation\/dotnfc\/image\/init(format:bytes:size:)","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DOTImageFormat","text":"ImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(format:bytes:size:)"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"navigatorTitle":[{"kind":"identifier","text":"ImageSize"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","url":"\/documentation\/dotnfc\/imagesize","abstract":[{"type":"text","text":"Image size in pixels."}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageSize"}],"type":"topic","title":"ImageSize"},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"text":"version: 9.2.0","type":"text"}],"url":"\/documentation\/dotnfc","role":"collection","type":"topic"},"doc://DotNfc/documentation/DotNfc/Image":{"type":"topic","role":"symbol","title":"Image","url":"\/documentation\/dotnfc\/image","navigatorTitle":[{"text":"Image","kind":"identifier"}],"abstract":[],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Image","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Image"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/fragments","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageFormat\/navigatorTitle","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTImageSize"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/title","op":"replace","value":"DOTImage"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTImage"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Image\/navigatorTitle","op":"replace","value":[{"text":"DOTImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}