{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","interfaceLanguage":"occ"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","text":"DotFaceDetectionModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceDetectionModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"expressionNeutral:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"expressionNeutral"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleConfiguration","text":"DotFaceBackgroundUniformityModuleConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"backgroundUniformity"},{"kind":"text","text":" "},{"text":"eyeGazeLiveness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"eyeGazeLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"passiveLiveness:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFacePassiveLivenessModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"passiveLiveness","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"verification:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration"},{"text":" *) ","kind":"text"},{"text":"verification","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(im)initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceDetectionModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfacedetectionmoduleconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceDetectionModuleConfiguration","type":"topic","title":"DotFaceDetectionModuleConfiguration","role":"symbol","abstract":[{"type":"text","text":"Face detection module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules":{"type":"topic","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules","kind":"symbol","role":"symbol","title":"DotFaceLibraryConfigurationModules","url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules","abstract":[{"text":"Face library module configuration.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceBackgroundUniformityModuleConfiguration":{"type":"topic","title":"DotFaceBackgroundUniformityModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceBackgroundUniformityModuleConfiguration","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceBackgroundUniformityModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacebackgrounduniformitymoduleconfiguration","abstract":[{"type":"text","text":"Face background uniformity module."}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceExpressionNeutralModuleConfiguration":{"kind":"symbol","url":"\/documentation\/dotfacecore\/dotfaceexpressionneutralmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"title":"DotFaceExpressionNeutralModuleConfiguration","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceExpressionNeutralModuleConfiguration","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceLibraryConfigurationModules/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceLibraryConfigurationModules\/initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","type":"topic","title":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:","abstract":[],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}],"url":"\/documentation\/dotfacecore\/dotfacelibraryconfigurationmodules\/initwithdetection:expressionneutral:backgrounduniformity:eyegazeliveness:passiveliveness:verification:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:expressionNeutral:backgroundUniformity:eyeGazeLiveness:passiveLiveness:verification:"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration":{"url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration","navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"title":"DotFaceEyeGazeLivenessModuleConfiguration","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFacePassiveLivenessModuleConfiguration":{"navigatorTitle":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotfacepassivelivenessmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face passive liveness module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFacePassiveLivenessModuleConfiguration","title":"DotFacePassiveLivenessModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceVerificationModuleConfiguration":{"title":"DotFaceVerificationModuleConfiguration","url":"\/documentation\/dotfacecore\/dotfaceverificationmoduleconfiguration","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Face verification module."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/title","value":"DotFaceBackgroundUniformityModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceBackgroundUniformityModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceBackgroundUniformityModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/title","value":"DotFaceExpressionNeutralModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments","value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}]},{"value":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle","op":"replace"},{"value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}