{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTPPalmAutoCaptureDetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":" * ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerProcessingResult(py)detection","role":"symbol","symbolKind":"property","title":"detection","fragments":[{"text":"detection","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"text":"detection","kind":"identifier"}],"roleHeading":"Instance Property"},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult\/detection"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"The result of processing image during the palm auto capture process.","type":"text"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult/detection":{"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult\/detection","role":"symbol","fragments":[{"kind":"identifier","text":"detection"}],"abstract":[{"type":"text","text":"The result of processing image during the palm auto capture process."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult\/detection","title":"detection"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult":{"type":"topic","kind":"symbol","role":"symbol","title":"DOTPPalmAutoCaptureControllerProcessingResult","fragments":[{"text":"DOTPPalmAutoCaptureControllerProcessingResult","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"title":"PalmAutoCaptureDetection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","value":"DOTPPalmAutoCaptureDetection","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}