{"metadata":{"modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:result:phase:","kind":"identifier"}],"title":"initWithDetection:result:phase:","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureControllerProcessingResult(im)initWithDetection:result:phase:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:phase:"}]},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult\/initwithdetection:result:phase:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithDetection:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTPPalmAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureResult","text":"DOTPPalmAutoCaptureResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","text":"DOTPPalmAutoCapturePhase","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"phase"},{"kind":"text","text":";"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"abstract":[{"text":"The final result of the palm auto capture process.","type":"text"}],"kind":"symbol","type":"topic","title":"PalmAutoCaptureResult","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureresult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureResult","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult/initWithDetection:result:phase:":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult\/initWithDetection:result:phase:","title":"initWithDetection:result:phase:","navigatorTitle":[{"kind":"identifier","text":"initWithDetection:result:phase:"}],"abstract":[],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult\/initwithdetection:result:phase:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithDetection:result:phase:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"PalmAutoCapturePhase","abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmautocapturephase","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"title":"PalmAutoCaptureDetection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureControllerProcessingResult":{"type":"topic","kind":"symbol","role":"symbol","title":"DOTPPalmAutoCaptureControllerProcessingResult","fragments":[{"text":"DOTPPalmAutoCaptureControllerProcessingResult","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureControllerProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocapturecontrollerprocessingresult"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.1.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","type":"topic","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","value":"DOTPPalmAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","value":"DOTPPalmAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle","value":[{"text":"DOTPPalmAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title","value":"DOTPPalmAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureDetection","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}