{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","title":"BrightnessTooLowValidator","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPBrightnessTooLowValidator","roleHeading":"Class"},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators","anchor":"Validators","generated":true}],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init(threshold:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/threshold"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/defaultThreshold"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/brightnesstoolowvalidator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/brightnesstoolowvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPBrightnessTooLowValidator) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"inlineContent":[{"type":"text","text":"To use this validator also following validators must be applied: "},{"type":"codeVoice","code":"PalmOutOfBoundsValidator"},{"type":"text","text":"."}],"type":"paragraph"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator"},"sections":[],"abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"references":{"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","kind":"symbol","abstract":[{"text":"Validate whether the size of the detected palm is too large.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","title":"SizeTooLargeValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"abstract":[{"type":"text","text":"Validate minimum brightness of the detected palm."}],"role":"symbol","title":"BrightnessTooLowValidator"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"type":"topic","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"title":"SizeTooSmallValidator","role":"symbol","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/defaultThreshold":{"kind":"symbol","title":"defaultThreshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/defaultThreshold","role":"symbol","type":"topic","abstract":[{"text":"Default threshold.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/defaultthreshold","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"title":"SharpnessTooLowValidator","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","title":"PalmAutoCaptureFrameParametersValidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparametersvalidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureFrameParametersValidator"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParametersValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"type":"text","text":"Validate if the detected palm is within the bounds of the image."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"role":"symbol","title":"PalmOutOfBoundsValidator"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","type":"topic","title":"BrightnessTooHighValidator","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/init()":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"title":"init()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init()","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/dependencyIdentifiers":{"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"kind":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"title":"dependencyIdentifiers","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/dependencyIdentifiers","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/dependencyidentifiers","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/threshold":{"navigatorTitle":[{"kind":"identifier","text":"threshold"}],"kind":"symbol","abstract":[{"type":"text","text":"Current minimal accepted brightness."}],"title":"threshold","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/threshold","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/threshold","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/validate(palmAutoCaptureFrameParameters:)":{"type":"topic","role":"symbol","kind":"symbol","navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/validate(palmautocaptureframeparameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"palmAutoCaptureFrameParameters","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters","text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate brightness of the detected palm."}],"title":"validate(palmAutoCaptureFrameParameters:)"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/init(threshold:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init(threshold:)","kind":"symbol","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"type":"topic","title":"init(threshold:)"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"title":"PalmNotDetectedValidator","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","kind":"symbol","type":"topic","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","title":"PalmAutoCaptureController","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator/identifier":{"title":"identifier","navigatorTitle":[{"kind":"identifier","text":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator\/identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/identifier","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DOTPBrightnessTooLowValidator","path":"\/metadata\/title","op":"replace"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/threshold"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/init(threshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/validate(palmAutoCaptureFrameParameters:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator\/defaultThreshold"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator"]}],"path":"\/relationshipsSections","op":"replace"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParametersValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"anchor":"Validators","generated":true,"title":"Validators"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPSizeTooLargeValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/navigatorTitle","op":"replace"},{"value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTPSizeTooSmallValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/navigatorTitle","op":"replace"},{"value":"defaultThreshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1defaultThreshold\/title","op":"replace"},{"value":[{"text":"defaultThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1defaultThreshold\/fragments","op":"replace"},{"value":"DOTPSharpnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/navigatorTitle","op":"replace"},{"value":"DOTPPalmAutoCaptureFrameParametersValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureFrameParametersValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParametersValidator\/navigatorTitle","op":"replace"},{"value":"DOTPPalmOutOfBoundsValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/navigatorTitle","op":"replace"},{"value":"DOTPBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","op":"replace"},{"value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/navigatorTitle","op":"replace"},{"value":"init","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init()\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init()\/fragments","op":"replace"},{"value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1dependencyIdentifiers\/title","op":"replace"},{"value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1dependencyIdentifiers\/fragments","op":"replace"},{"value":"threshold","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1threshold\/title","op":"replace"},{"value":[{"kind":"identifier","text":"threshold"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1threshold\/fragments","op":"replace"},{"value":"validateWithPalmAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1validate(palmAutoCaptureFrameParameters:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithPalmAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","op":"replace"},{"value":"initWithThreshold:error:","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init(threshold:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithThreshold:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1init(threshold:)\/fragments","op":"replace"},{"value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/navigatorTitle","op":"replace"},{"value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/navigatorTitle","op":"replace"},{"value":"identifier","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1identifier\/title","op":"replace"},{"value":[{"kind":"identifier","text":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator~1identifier\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}