{"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/verification"],"generated":true,"anchor":"Enumeration-Cases"},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/init(rawValue:)"],"generated":true,"anchor":"Initializers"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/description"],"generated":true,"anchor":"Instance-Properties"},{"title":"Default Implementations","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/Equatable-Implementations","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/RawRepresentable-Implementations"],"generated":true,"anchor":"Default-Implementations"}],"metadata":{"modules":[{"name":"DotPalmCore"}],"roleHeading":"Enumeration","externalID":"c:@M@DotCore@E@DotFaceModuleId","symbolKind":"enum","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleId"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"title":"DotFaceModuleId","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH","doc:\/\/DotPalmCore\/SY"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceModuleId"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotfacemoduleid"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","interfaceLanguage":"swift"},"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}],"kind":"symbol","references":{"doc://DotPalmCore/SY":{"title":"Swift.RawRepresentable","identifier":"doc:\/\/DotPalmCore\/SY","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid","title":"DotFaceModuleId","role":"symbol","navigatorTitle":[{"text":"DotFaceModuleId","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"}],"abstract":[{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" feature module identifier."}]},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/Equatable-Implementations":{"abstract":[],"title":"Equatable Implementations","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/Equatable-Implementations","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/equatable-implementations","kind":"article","role":"collectionGroup","type":"topic"},"doc://DotPalmCore/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/init(rawValue:)":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/init(rawvalue:)","type":"topic","role":"symbol","title":"init(rawValue:)"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/verification":{"kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/verification","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"verification"}],"url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/verification","title":"DotFaceModuleId.verification","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdVerification"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/description":{"kind":"symbol","role":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/description","abstract":[],"url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/description"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/expressionNeutral":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/expressionNeutral","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/expressionneutral","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"expressionNeutral"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdExpressionNeutral"}],"title":"DotFaceModuleId.expressionNeutral"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/detectionBalanced":{"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionBalanced"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionbalanced","title":"DotFaceModuleId.detectionBalanced","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionBalanced","kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionBalanced"}]},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/backgroundUniformity":{"title":"DotFaceModuleId.backgroundUniformity","abstract":[],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/backgroundUniformity","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/backgrounduniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdBackgroundUniformity"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/detectionFast":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/detectionfast","navigatorTitle":[{"kind":"identifier","text":"DotFaceModuleIdDetectionFast"}],"title":"DotFaceModuleId.detectionFast","abstract":[],"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionFast"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionFast","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/RawRepresentable-Implementations","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/rawrepresentable-implementations","role":"collectionGroup","abstract":[],"kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/eyeGazeLiveness":{"title":"DotFaceModuleId.eyeGazeLiveness","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/eyeGazeLiveness","type":"topic","url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/eyegazeliveness","abstract":[],"navigatorTitle":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"eyeGazeLiveness","kind":"identifier"}],"kind":"symbol"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/DotFaceModuleId/passiveLiveness":{"url":"\/documentation\/dotpalmcore\/dotfacemoduleid\/passiveliveness","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/passiveLiveness","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}],"type":"topic","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"}],"title":"DotFaceModuleId.passiveLiveness"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DotFaceModuleId","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/metadata\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/backgroundUniformity","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionBalanced","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/detectionFast","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/expressionNeutral","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/eyeGazeLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/passiveLiveness","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotFaceModuleId\/verification"],"title":"Enumeration Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceModuleId","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/title","value":"DotFaceModuleId"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DotFaceModuleId"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1verification\/title","op":"replace","value":"DotFaceModuleIdVerification"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1verification\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdVerification","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1expressionNeutral\/title","op":"replace","value":"DotFaceModuleIdExpressionNeutral"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1expressionNeutral\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdExpressionNeutral","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionBalanced\/title","op":"replace","value":"DotFaceModuleIdDetectionBalanced"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionBalanced\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdDetectionBalanced","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1backgroundUniformity\/title","op":"replace","value":"DotFaceModuleIdBackgroundUniformity"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1backgroundUniformity\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdBackgroundUniformity","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionFast\/title","op":"replace","value":"DotFaceModuleIdDetectionFast"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1detectionFast\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdDetectionFast","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1eyeGazeLiveness\/title","op":"replace","value":"DotFaceModuleIdEyeGazeLiveness"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1eyeGazeLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdEyeGazeLiveness","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1passiveLiveness\/title","op":"replace","value":"DotFaceModuleIdPassiveLiveness"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotFaceModuleId~1passiveLiveness\/fragments","op":"replace","value":[{"text":"DotFaceModuleIdPassiveLiveness","kind":"identifier"}]}]}]}