{"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/detection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/phase","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/preview","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/result"],"generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/isEqual:"],"generated":true,"anchor":"Instance-Methods"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateRunning"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiState","kind":"typeIdentifier","text":"DOTPPalmAutoCaptureUiState"}],"languages":["occ"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","interfaceLanguage":"occ"},"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState"],"type":"inheritsFrom","kind":"relationships"}],"metadata":{"title":"DOTPPalmAutoCaptureUiStateRunning","fragments":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiStateRunning"}],"roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureUiStateRunning","navigatorTitle":[{"text":"DOTPPalmAutoCaptureUiStateRunning","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/initWithPreview:phase:detection:result:":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/initWithPreview:phase:detection:result:","type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/initwithpreview:phase:detection:result:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:result:"}],"title":"initWithPreview:phase:detection:result:"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/detection":{"type":"topic","fragments":[{"kind":"identifier","text":"detection"}],"title":"detection","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/detection","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/detection","abstract":[{"type":"text","text":"Detection information. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/result":{"title":"result","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/result","role":"symbol","fragments":[{"text":"result","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/result","abstract":[{"type":"text","text":"Result. If the process has not finished, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/isEqual:":{"kind":"symbol","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/isequal:","title":"isEqual:","fragments":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/isEqual:"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/preview":{"abstract":[{"type":"text","text":"Preview information."}],"type":"topic","kind":"symbol","fragments":[{"text":"preview","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/preview","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/preview","title":"preview","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureUiState":{"type":"topic","abstract":[{"text":"This class defines the different states that the UI can be in during the process.","type":"text"}],"title":"PalmAutoCaptureUiState","kind":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureUiState","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureuistate","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureUiState"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/hash":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/hash","kind":"symbol","type":"topic","title":"hash","fragments":[{"text":"hash","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/hash","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning":{"abstract":[{"type":"text","text":"Running state."},{"type":"text","text":" "},{"type":"text","text":"This state is active after the "},{"type":"text","text":"start()"},{"type":"text","text":" method is called and before the process finishes."}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning","kind":"symbol","title":"DOTPPalmAutoCaptureUiStateRunning","role":"symbol","fragments":[{"text":"DOTPPalmAutoCaptureUiStateRunning","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/phase":{"title":"phase","abstract":[{"type":"text","text":"Current phase of the process. If the process has just started and no camera image has been processed yet, this will be "},{"type":"text","text":"null"},{"type":"text","text":"."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/phase","kind":"symbol","role":"symbol","fragments":[{"text":"phase","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/phase"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmAutoCaptureUiStateRunning/description":{"type":"topic","title":"description","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmAutoCaptureUiStateRunning\/description","url":"\/documentation\/dotpalmcore\/dotppalmautocaptureuistaterunning\/description","kind":"symbol","role":"symbol","fragments":[{"text":"description","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/title","value":"DOTPPalmAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTPPalmAutoCaptureUiState","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}