{"abstract":[{"text":"Palm quality.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmquality"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmquality"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"PalmQuality","modules":[{"name":"DotPalmCore"}],"roleHeading":"Class","symbolKind":"class","role":"symbol","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmQuality"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPPalmQuality) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}]}]}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/init(imageQuality:templateExtractionQuality:)"],"title":"Initializers","anchor":"Initializers","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/imageQuality","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/templateExtractionQuality"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/isEqual(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality","title":"PalmQuality","kind":"symbol","navigatorTitle":[{"text":"PalmQuality","kind":"identifier"}],"type":"topic","abstract":[{"text":"Palm quality.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmQuality","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmquality"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/hash":{"abstract":[],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"title":"hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/hash","url":"\/documentation\/dotpalmcore\/palmquality\/hash"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/init(imageQuality:templateExtractionQuality:)":{"url":"\/documentation\/dotpalmcore\/palmquality\/init(imagequality:templateextractionquality:)","abstract":[],"title":"init(imageQuality:templateExtractionQuality:)","type":"topic","navigatorTitle":[{"text":"initWithImageQuality:templateExtractionQuality:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/init(imageQuality:templateExtractionQuality:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"imageQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PalmImageQuality","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality"},{"kind":"text","text":", "},{"kind":"externalParam","text":"templateExtractionQuality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"kind":"symbol"},"doc://DotPalmCore/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/imageQuality":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/imageQuality","title":"imageQuality","abstract":[{"type":"text","text":"Image quality."}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"imageQuality","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmquality\/imagequality","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmImageQuality","text":"PalmImageQuality","kind":"typeIdentifier"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"url":"\/documentation\/dotpalmcore","role":"collection","title":"DotPalmCore"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/isEqual(_:)":{"url":"\/documentation\/dotpalmcore\/palmquality\/isequal(_:)","abstract":[],"title":"isEqual(_:)","type":"topic","navigatorTitle":[{"text":"isEqual:","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/isEqual(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"kind":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/templateExtractionQuality":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templateExtractionQuality","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotpalmcore\/palmquality\/templateextractionquality","navigatorTitle":[{"kind":"identifier","text":"templateExtractionQuality"}],"abstract":[{"text":"Quality for the template extraction. Value in interval ","type":"text"},{"code":"[0.0, 1.0]","type":"codeVoice"},{"text":".","type":"text"}],"title":"templateExtractionQuality","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/templateExtractionQuality","type":"topic"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/documentation/DotPalmCore/PalmQuality/description":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmquality\/description","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"description","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"doc://DotPalmCore/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotPalmCore\/SQ"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTPPalmQuality"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTPPalmQuality","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/imageQuality","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/templateExtractionQuality"]},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/init(imageQuality:templateExtractionQuality:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmQuality\/isEqual(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPPalmQuality","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/title","value":"DOTPPalmQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/fragments","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmQuality"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1hash\/title","value":"hash"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1init(imageQuality:templateExtractionQuality:)\/title","value":"initWithImageQuality:templateExtractionQuality:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1init(imageQuality:templateExtractionQuality:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImageQuality:templateExtractionQuality:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1imageQuality\/title","value":"imageQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1imageQuality\/fragments","value":[{"text":"imageQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1isEqual(_:)\/title","value":"isEqual:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1isEqual(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1templateExtractionQuality\/title","value":"templateExtractionQuality"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1templateExtractionQuality\/fragments","value":[{"text":"templateExtractionQuality","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmQuality~1description\/fragments","value":[{"kind":"identifier","text":"description"}]}]}]}