{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrrawimagefactory\/create(ciimage:cicontext:)"]},{"paths":["\/documentation\/dotnfc\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImageFactory"]]},"metadata":{"modules":[{"name":"DotNfc"}],"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTBgrRawImageFactory(cm)createWithCiImage:ciContext:","roleHeading":"Type Method","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(ciImage:ciContext:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return a copy of the "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage"}]}]},{"parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Input image as a "},{"code":"CIImage","type":"codeVoice"},{"type":"text","text":" object."}]}]},{"name":"ciContext","content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}]}],"kind":"content"}],"sections":[],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImageFactory/create(ciImage:ciContext:)":{"kind":"symbol","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"title":"create(ciImage:ciContext:)","url":"\/documentation\/dotnfc\/bgrrawimagefactory\/create(ciimage:cicontext:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImageFactory\/create(ciImage:ciContext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImage":{"abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgrRawImage"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"title":"BgrRawImage","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/bgrrawimage"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"text":"version: 8.4.1","type":"text"}],"role":"collection","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/BgrRawImageFactory":{"url":"\/documentation\/dotnfc\/bgrrawimagefactory","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImageFactory","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"title":"BgrRawImageFactory","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" from iOS native image types.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createWithCiImage:ciContext:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/BgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTBgrRawImage"},{"kind":"text","text":" *) "},{"text":"createWithCiImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciImage"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":" *) "},{"text":"ciContext","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/title","value":"DOTBgrRawImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImage\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]},{"op":"replace","value":"DOTBgrRawImageFactory","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImageFactory\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1BgrRawImageFactory\/fragments"}]}]}