{"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Inherited By","type":"inheritedBy","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/AccessControlError","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/ChipAuthenticationError","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/NotConnectedError"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/10Foundation14LocalizedErrorP","doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/s5ErrorP","doc:\/\/com.innovatrics.dot.nfc\/SH","doc:\/\/com.innovatrics.dot.nfc\/s8SendableP"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"text":"Error","kind":"identifier"}],"extendedModule":"DotNfc","platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"13.0","beta":false}],"role":"symbol","symbolKind":"class","roleHeading":"Class","modules":[{"name":"DotNfc"}],"title":"NfcTravelDocumentReader.Error","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"externalID":"s:6DotNfc0B20TravelDocumentReaderC5ErrorC"},"abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/error"]}],"seeAlsoSections":[{"title":"NFC reading","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CardAccessNumberPassword","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"],"generated":true}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTNNfcTravelDocumentReaderError) ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Error"}],"languages":["swift"],"platforms":["iOS"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/debugInfo","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/errorDescription","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/errorMessage","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/internalError"],"title":"Instance Properties"},{"generated":true,"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/Error-Implementations","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/LocalizedError-Implementations"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"title":"NfcTravelDocumentReader","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/debugInfo":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/debugInfo","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/debuginfo","title":"debugInfo","role":"symbol","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"debugInfo","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNDebugInfo","text":"DebugInfo"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/ChipAuthenticationError":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/ChipAuthenticationError","abstract":[{"text":"If authentication of the chip using the Chip Authentication protocol fails. Secure connection was not established.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/chipauthenticationerror","title":"NfcTravelDocumentReader.ChipAuthenticationError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ChipAuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"ChipAuthenticationError","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/LocalizedError-Implementations":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/LocalizedError-Implementations","abstract":[],"title":"LocalizedError Implementations","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/localizederror-implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/Error-Implementations":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/Error-Implementations","abstract":[],"title":"Error Implementations","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/error-implementations","role":"collectionGroup","kind":"article","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MachineReadableZonePassword":{"navigatorTitle":[{"kind":"identifier","text":"MachineReadableZonePassword"}],"title":"MachineReadableZonePassword","url":"\/documentation\/dotnfc\/machinereadablezonepassword","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MachineReadableZonePassword","kind":"symbol","abstract":[{"text":"Password from Machine Readable Zone.","type":"text"}],"role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MachineReadableZonePassword","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/s5ErrorP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s5ErrorP","title":"Swift.Error","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/AccessControlError":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/AccessControlError","abstract":[{"text":"If access to the chip data is denied either by PACE or BAC protocol.","type":"text"}],"title":"NfcTravelDocumentReader.AccessControlError","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/accesscontrolerror","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AccessControlError"}],"navigatorTitle":[{"text":"AccessControlError","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/NotConnectedError":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/NotConnectedError","abstract":[{"text":"If NFC reading fails due to an NFC tag connection failure.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/notconnectederror","title":"NfcTravelDocumentReader.NotConnectedError","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NotConnectedError","kind":"identifier"}],"navigatorTitle":[{"text":"NotConnectedError","kind":"identifier"}],"type":"topic"},"doc://com.innovatrics.dot.nfc/SQ":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/CardAccessNumberPassword":{"title":"CardAccessNumberPassword","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/CardAccessNumberPassword","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CardAccessNumberPassword"}],"url":"\/documentation\/dotnfc\/cardaccessnumberpassword","type":"topic","role":"symbol","navigatorTitle":[{"text":"CardAccessNumberPassword","kind":"identifier"}],"abstract":[{"type":"text","text":"Card Access Number as a password."}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/internalError":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/internalError","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/internalerror","kind":"symbol","type":"topic","title":"internalError","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":": Swift"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/errorDescription":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/errorDescription","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/errordescription","kind":"symbol","title":"errorDescription","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.4.0"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"deprecated":true,"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcKey"}],"navigatorTitle":[{"text":"NfcKey","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/10Foundation14LocalizedErrorP","type":"unresolvable","title":"Foundation.LocalizedError"},"doc://com.innovatrics.dot.nfc/s8SendableP":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/s8SendableP","type":"unresolvable","title":"Swift.Sendable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error":{"navigatorTitle":[{"kind":"identifier","text":"Error"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"If reading fails due to any other reason."}],"title":"NfcTravelDocumentReader.Error","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/description":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/description","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/description","kind":"symbol","type":"topic","title":"description","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Result of NFC reading."}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TravelDocument","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"title":"ObjectiveC.NSObject","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader/Error/errorMessage":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Error\/errorMessage","abstract":[],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/error\/errormessage","kind":"symbol","type":"topic","title":"errorMessage","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"errorMessage"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.nfc/SH":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH","type":"unresolvable","title":"Swift.Hashable"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZonePassword\/title","value":"DOTNMachineReadableZonePassword"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MachineReadableZonePassword\/fragments","value":[{"text":"DOTNMachineReadableZonePassword","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CardAccessNumberPassword\/title","value":"DOTNCardAccessNumberPassword"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1CardAccessNumberPassword\/fragments","op":"replace","value":[{"text":"DOTNCardAccessNumberPassword","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}