{"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery(py)headPose","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"headPose"}],"symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HeadPoseQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","kind":"typeIdentifier"}],"title":"headPose","modules":[{"name":"DotFaceCore"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Head pose query."}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/headPose","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","text":"HeadPoseQuery","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfacecore\/facequalityquery\/headpose"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/facequalityquery\/headpose"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery/headPose":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":": ","kind":"text"},{"text":"HeadPoseQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/headPose","navigatorTitle":[{"text":"headPose","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Head pose query.","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery\/headpose","kind":"symbol","title":"headPose"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQualityQuery"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","role":"symbol","title":"FaceQualityQuery","type":"topic","url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"role":"symbol","type":"topic","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/headposequery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"kind":"symbol","title":"HeadPoseQuery"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"headPose"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"headPose","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTFHeadPoseQuery","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery"},{"text":" * ","kind":"text"},{"text":"headPose","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1headPose\/title","value":"headPose","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1headPose\/fragments","value":[{"kind":"identifier","text":"headPose"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title","value":"DOTFFaceQualityQuery","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/navigatorTitle","op":"replace","value":[{"text":"DOTFFaceQualityQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title","op":"replace","value":"DOTFHeadPoseQuery"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle","op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}]}]}]}