{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"imageQuality","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"FaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/imagequality"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facequalityquery\/imagequality"]}],"metadata":{"title":"imageQuality","symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceQualityQuery(py)imageQuality","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageQuality"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","text":"FaceImageQualityQuery","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageQuality","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Face image quality query."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/imageQuality"},"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","abstract":[{"text":"version: 8.7.1","type":"text"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery/imageQuality":{"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/facequalityquery\/imagequality","title":"imageQuality","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"imageQuality","kind":"identifier"},{"kind":"text","text":": "},{"text":"FaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery","kind":"typeIdentifier"}],"abstract":[{"text":"Face image quality query.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"imageQuality"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery\/imageQuality"},"doc://DotFaceCore/documentation/DotFaceCore/FaceQualityQuery":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceQualityQuery","kind":"identifier"}],"title":"FaceQualityQuery","url":"\/documentation\/dotfacecore\/facequalityquery","abstract":[{"type":"text","text":"Face quality query specifies which face quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceQualityQuery"}],"type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImageQualityQuery":{"type":"topic","url":"\/documentation\/dotfacecore\/faceimagequalityquery","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageQualityQuery"}],"abstract":[{"type":"text","text":"Face image quality query specifies which face image quality face attributes should be evaluated."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","title":"FaceImageQualityQuery","navigatorTitle":[{"kind":"identifier","text":"FaceImageQualityQuery"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"imageQuality","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"imageQuality","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTFFaceImageQualityQuery","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImageQualityQuery","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImageQualityQuery"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageQuality"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1imageQuality\/title","value":"imageQuality","op":"replace"},{"value":[{"text":"imageQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery~1imageQuality\/fragments"},{"value":"DOTFFaceQualityQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceQualityQuery"}]},{"op":"replace","value":"DOTFFaceImageQualityQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImageQualityQuery\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageQualityQuery"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}