{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/init(image:palm:validatoridentifiers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturedetection\/init(image:palm:validatoridentifiers:)"]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Image","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PalmDetector","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier"},{"text":".","kind":"text"},{"text":"Palm","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"])","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithImage:palm:validatorIdentifiers:"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureDetection(im)initWithImage:palm:validatorIdentifiers:","roleHeading":"Initializer","title":"init(image:palm:validatorIdentifiers:)","symbolKind":"init"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","text":"Image","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":", ","kind":"text"},{"text":"palm","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","text":"PalmDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector"},{"text":".","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","text":"Palm","kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C"},{"text":"?, ","kind":"text"},{"text":"validatorIdentifiers","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"])","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/init(image:palm:validatorIdentifiers:)","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection/init(image:palm:validatorIdentifiers:)":{"title":"init(image:palm:validatorIdentifiers:)","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection\/init(image:palm:validatorIdentifiers:)","kind":"symbol","type":"topic","navigatorTitle":[{"text":"initWithImage:palm:validatorIdentifiers:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection\/init(image:palm:validatoridentifiers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"image"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","kind":"typeIdentifier","text":"Image"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palm"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector","kind":"typeIdentifier","text":"PalmDetector"},{"kind":"text","text":"."},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","kind":"typeIdentifier","text":"Palm"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validatorIdentifiers"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"])"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"url":"\/documentation\/dotpalmcore\/palmdetector","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","kind":"symbol","title":"PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"navigatorTitle":[{"kind":"identifier","text":"Palm"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","type":"topic","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"title":"PalmDetector.Palm","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Image":{"kind":"symbol","url":"\/documentation\/dotpalmcore\/image","abstract":[],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","title":"Image"},"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","role":"collection","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"role":"symbol","title":"PalmAutoCaptureDetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","kind":"symbol","abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"url":"\/documentation\/dotpalmcore\/palmautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPPalmDetectorPalm":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","type":"topic","abstract":[{"text":"Result of the palm detection process.","type":"text"}],"fragments":[{"text":"DOTPPalmDetectorPalm","kind":"identifier"}],"title":"DOTPPalmDetectorPalm","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotppalmdetectorpalm","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithImage:palm:validatorIdentifiers:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:palm:validatorIdentifiers:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Image","text":"DOTImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"palm:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPPalmDetectorPalm","text":"DOTPPalmDetectorPalm","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetectorPalm"},{"text":" *) ","kind":"text"},{"text":"palm","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validatorIdentifiers:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSArray<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"validatorIdentifiers","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"initWithImage:palm:validatorIdentifiers:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1init(image:palm:validatorIdentifiers:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithImage:palm:validatorIdentifiers:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection~1init(image:palm:validatorIdentifiers:)\/fragments"},{"value":"DOTPPalmDetector","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/navigatorTitle"},{"value":"DOTImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/title"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/fragments"},{"value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Image\/navigatorTitle"},{"value":"DOTPPalmAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}