{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/qualityattributethresholds"]}],"sections":[],"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"text","text":".standard"},{"type":"text","text":" preset."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds"},{"kind":"text","text":" * "},{"kind":"identifier","text":"qualityAttributeThresholds"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"qualityAttributeThresholds"}],"title":"qualityAttributeThresholds","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(py)qualityAttributeThresholds","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"qualityAttributeThresholds"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/qualityAttributeThresholds"},"references":{"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"title":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","role":"symbol","fragments":[{"text":"DOTDBaseDocumentAutoCaptureConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","abstract":[{"text":"Configuration options for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/qualityAttributeThresholds":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/qualityAttributeThresholds","fragments":[{"text":"qualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"type":"text","text":".standard"},{"type":"text","text":" preset."}],"role":"symbol","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/qualityattributethresholds","title":"qualityAttributeThresholds","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"title":"DocumentAutoCaptureQualityAttributeThresholds","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds"}],"op":"replace"}]}]}