{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face"]]},"abstract":[{"type":"text","text":"Parameters of the face image."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","text":"ImageParameters"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/face\/imageparameters"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face\/imageParameters","interfaceLanguage":"swift"},"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","text":"ImageParameters"}],"title":"imageParameters","roleHeading":"Instance Property","externalID":"s:11DotFaceLite0B8DetectorC0B0C15imageParametersAA05ImageF0Cvp"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Face/imageParameters":{"url":"\/documentation\/dotfacelite\/facedetector\/face\/imageparameters","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face\/imageParameters","role":"symbol","title":"imageParameters","abstract":[{"type":"text","text":"Parameters of the face image."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLImageParameters","text":"ImageParameters","kind":"typeIdentifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ImageParameters":{"title":"ImageParameters","role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ImageParameters","url":"\/documentation\/dotfacelite\/imageparameters","kind":"symbol","abstract":[{"text":"Parameters of the image which was used for the face detection.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"type":"topic","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","title":"DotFaceLite","abstract":[{"text":"version: 8.3.1","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"navigatorTitle":[{"text":"FaceDetector","kind":"identifier"}],"kind":"symbol","title":"FaceDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceDetector","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/facedetector","type":"topic"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Face":{"url":"\/documentation\/dotfacelite\/facedetector\/face","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Face","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Face"}],"title":"FaceDetector.Face","abstract":[{"type":"text","text":"Detected face."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Face","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/title","value":"DOTFLImageParameters"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ImageParameters\/fragments","value":[{"kind":"identifier","text":"DOTFLImageParameters"}]},{"op":"replace","value":"DOTFLFaceDetector","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}