{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTCorners) ","kind":"text"},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/corners"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/corners"]}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"type":"text","text":"Four detected corners in an image."}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomRight","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topRight"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/from(rectangle:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners"},"kind":"symbol","metadata":{"title":"Corners","symbolKind":"class","externalID":"c:@M@DotCore@objc(cs)DOTCorners","roleHeading":"Class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}]},"references":{"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/mirrored()":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/mirrored()","abstract":[],"type":"topic","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"mirrored()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mirrored","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners"}],"url":"\/documentation\/dotpalmcore\/corners\/mirrored()"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"type":"topic","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"},{"kind":"text","text":")"}],"url":"\/documentation\/dotpalmcore\/corners\/init(topleft:topright:bottomright:bottomleft:)"},"doc://DotPalmCore/documentation/DotPalmCore/Corners":{"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"title":"Corners","url":"\/documentation\/dotpalmcore\/corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners","role":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners/description":{"abstract":[],"url":"\/documentation\/dotpalmcore\/corners\/description","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/description","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/from(rectangle:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/from(rectangle:)","url":"\/documentation\/dotpalmcore\/corners\/from(rectangle:)","abstract":[],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","kind":"typeIdentifier","text":"Corners"}],"title":"from(rectangle:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/isEqual(_:)":{"abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/corners\/isequal(_:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"isEqual(_:)","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/bottomLeft":{"navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}],"url":"\/documentation\/dotpalmcore\/corners\/bottomleft","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomLeft","abstract":[{"text":"Bottom left corner point.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottomLeft"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"type":"topic","title":"bottomLeft"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","abstract":[{"type":"text","text":"version: 8.7.1"}],"kind":"symbol","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/topRight":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topRight","role":"symbol","title":"topRight","abstract":[{"type":"text","text":"Top right corner point."}],"url":"\/documentation\/dotpalmcore\/corners\/topright","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"topRight","kind":"identifier"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"navigatorTitle":[{"text":"topRight","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners/hash":{"navigatorTitle":[{"text":"hash","kind":"identifier"}],"title":"hash","url":"\/documentation\/dotpalmcore\/corners\/hash","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/hash","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://DotPalmCore/documentation/DotPalmCore/Corners/topLeft":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topLeft","type":"topic","abstract":[{"type":"text","text":"Top left corner point."}],"navigatorTitle":[{"kind":"identifier","text":"topLeft"}],"role":"symbol","kind":"symbol","title":"topLeft","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"url":"\/documentation\/dotpalmcore\/corners\/topleft"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/bottomRight":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomRight","abstract":[{"text":"Bottom right corner point.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"bottomRight"}],"role":"symbol","kind":"symbol","title":"bottomRight","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomRight","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"}],"url":"\/documentation\/dotpalmcore\/corners\/bottomright"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/points":{"url":"\/documentation\/dotpalmcore\/corners\/points","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/points","kind":"symbol","abstract":[],"navigatorTitle":[{"text":"points","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"points"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"text":"]","kind":"text"}],"title":"points","role":"symbol","type":"topic"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/Corners/rebased(parentRectangle:)":{"role":"symbol","url":"\/documentation\/dotpalmcore\/corners\/rebased(parentrectangle:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/rebased(parentRectangle:)","type":"topic","title":"rebased(parentRectangle:)","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners","text":"Corners","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"DOTCorners"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/bottomRight","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/points","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topLeft","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/topRight"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/isEqual(_:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/mirrored()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"title":"Type Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/Corners\/from(rectangle:)"]}]},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]}],"op":"replace"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DOTCorners"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1mirrored()\/title","value":"mirrored"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1mirrored()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title","op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments"},{"op":"replace","value":"DOTCorners","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1description\/fragments","value":[{"text":"description","kind":"identifier"}]},{"value":"fromRectangle:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1from(rectangle:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromRectangle:"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1from(rectangle:)\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1isEqual(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomLeft\/title","op":"replace","value":"bottomLeft"},{"value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomLeft\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1topRight\/title","op":"replace","value":"topRight"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1topRight\/fragments","op":"replace","value":[{"text":"topRight","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1hash\/title","value":"hash","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1hash\/fragments","value":[{"text":"hash","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1topLeft\/title","value":"topLeft"},{"value":[{"text":"topLeft","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1topLeft\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomRight\/title","op":"replace","value":"bottomRight"},{"value":[{"kind":"identifier","text":"bottomRight"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1bottomRight\/fragments"},{"value":"points","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1points\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1points\/fragments","value":[{"kind":"identifier","text":"points"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1Corners~1rebased(parentRectangle:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}