{"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/licenseBytes"],"title":"Instance Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol"]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"symbolKind":"protocol","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"title":"DotSdkLicenseProxyProtocol","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","roleHeading":"Protocol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isNfcEnabled":{"role":"symbol","kind":"symbol","title":"isNfcEnabled","abstract":[],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","required":true,"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isnfcenabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isNfcEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"isNfcEnabled"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[],"title":"isFaceMatchingEnabled","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","type":"topic","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceEyeGazeLivenessScoreEnabled":{"navigatorTitle":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"title":"isFaceEyeGazeLivenessScoreEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceeyegazelivenessscoreenabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isPalmEnabled":{"role":"symbol","title":"isPalmEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isPalmEnabled","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"navigatorTitle":[{"kind":"identifier","text":"isPalmEnabled"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/ispalmenabled","required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceLiteEnabled":{"title":"isFaceLiteEnabled","abstract":[],"required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isFaceLiteEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isFaceLiteEnabled","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceliteenabled","type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceEnabled":{"navigatorTitle":[{"text":"isFaceEnabled","kind":"identifier"}],"title":"isFaceEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfaceenabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","abstract":[{"type":"text","text":"version: 8.7.1"}],"kind":"symbol","title":"DotPalmCore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isEvaluation":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEvaluation"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isEvaluation","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isEvaluation","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isevaluation","kind":"symbol","type":"topic","abstract":[],"required":true,"title":"isEvaluation","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/licenseBytes":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/licenseBytes","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/licensebytes","required":true,"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"licenseBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"type":"topic","title":"licenseBytes","abstract":[],"navigatorTitle":[{"text":"licenseBytes","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"title":"isDocumentEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isdocumentenabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFacePassiveLivenessEnabled":{"navigatorTitle":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}],"title":"isFacePassiveLivenessEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfacepassivelivenessenabled","required":true,"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFacePassiveLivenessEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","role":"symbol","abstract":[]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","kind":"symbol","type":"topic","abstract":[],"role":"symbol","title":"DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isRealTimeTransactionReportingEnabled":{"navigatorTitle":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}],"title":"isRealTimeTransactionReportingEnabled","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isrealtimetransactionreportingenabled","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","role":"symbol","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"value":"DotSdkLicenseProxyProtocol","path":"\/metadata\/title","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isEvaluation","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceLiteEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFacePassiveLivenessEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isNfcEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isPalmEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isRealTimeTransactionReportingEnabled","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/licenseBytes"]}],"path":"\/topicSections","op":"replace"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@protocol"},{"text":" ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/title","value":"isNfcEnabled"},{"value":[{"kind":"identifier","text":"isNfcEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isNfcEnabled\/fragments"},{"op":"replace","value":"isFaceMatchingEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title"},{"op":"replace","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"},{"value":"isFaceEyeGazeLivenessScoreEnabled","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/title"},{"op":"replace","value":[{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceEyeGazeLivenessScoreEnabled\/fragments"},{"op":"replace","value":"isPalmEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isPalmEnabled\/fragments","value":[{"text":"isPalmEnabled","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/title","value":"isFaceLiteEnabled"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceLiteEnabled\/fragments","value":[{"kind":"identifier","text":"isFaceLiteEnabled"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/title","op":"replace","value":"isFaceEnabled"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isFaceEnabled"}]},{"op":"replace","value":"isEvaluation","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isEvaluation\/fragments","op":"replace","value":[{"kind":"identifier","text":"isEvaluation"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/title","value":"licenseBytes"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1licenseBytes\/fragments","value":[{"text":"licenseBytes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title","op":"replace","value":"isDocumentEnabled"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments","op":"replace","value":[{"kind":"identifier","text":"isDocumentEnabled"}]},{"value":"isFacePassiveLivenessEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFacePassiveLivenessEnabled\/fragments","op":"replace","value":[{"text":"isFacePassiveLivenessEnabled","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/title","value":"isRealTimeTransactionReportingEnabled"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isRealTimeTransactionReportingEnabled\/fragments","op":"replace","value":[{"text":"isRealTimeTransactionReportingEnabled","kind":"identifier"}]}]}]}