{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute(py)description","symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"description","navigatorTitle":[{"kind":"identifier","text":"description"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"]]},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceattribute\/description"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceattribute\/description"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/description","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 9.5.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"type":"topic","url":"\/documentation\/dotfacecore\/faceattribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","kind":"symbol","title":"FaceAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAttribute"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/description":{"url":"\/documentation\/dotfacecore\/faceattribute\/description","type":"topic","abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/description","kind":"symbol","title":"description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"description","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"description","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAttribute"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/navigatorTitle","op":"replace"},{"value":"description","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1description\/title","op":"replace"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1description\/fragments","op":"replace"}]}]}