{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotlibraryid\/hashvalue"]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"hashValue","roleHeading":"Instance Property","extendedModule":"Swift","modules":[{"relatedModules":["Swift"],"name":"DotPalmCore"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE04hashB0Sivp::SYNTHESIZED::c:@M@DotCore@E@DotLibraryId","role":"symbol","symbolKind":"property"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/RawRepresentable-Implementations"]]},"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/hashValue","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hashValue","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/hashValue":{"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/hashValue","role":"symbol","type":"topic","title":"hashValue","url":"\/documentation\/dotpalmcore\/dotlibraryid\/hashvalue","kind":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId/RawRepresentable-Implementations":{"abstract":[],"url":"\/documentation\/dotpalmcore\/dotlibraryid\/rawrepresentable-implementations","kind":"article","title":"RawRepresentable Implementations","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId\/RawRepresentable-Implementations","role":"collectionGroup"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 8.17.1"}],"role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotLibraryId":{"type":"topic","url":"\/documentation\/dotpalmcore\/dotlibraryid","navigatorTitle":[{"text":"DotLibraryId","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotLibraryId","kind":"symbol","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"title":"DotLibraryId"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DotLibraryId","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/title"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/fragments"},{"op":"replace","value":[{"text":"DotLibraryId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotLibraryId\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}