{"abstract":[{"text":"Candidate selection is running.","type":"text"}],"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"roleHeading":"Case","modules":[{"name":"DotFaceCore"}],"title":"FaceAutoCapturePhase.candidateSelection","externalID":"c:@M@DotFaceCommons@E@DOTFaceAutoCapturePhase@DOTFaceAutoCapturePhaseCandidateSelection","navigatorTitle":[{"text":"DOTFaceAutoCapturePhaseCandidateSelection","kind":"identifier"}],"role":"symbol","symbolKind":"case"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/candidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturephase\/candidateselection"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/candidateSelection"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase/candidateSelection":{"kind":"symbol","abstract":[{"type":"text","text":"Candidate selection is running."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase\/candidateSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturephase\/candidateselection","title":"FaceAutoCapturePhase.candidateSelection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCapturePhase":{"url":"\/documentation\/dotfacecore\/faceautocapturephase","navigatorTitle":[{"text":"FaceAutoCapturePhase","kind":"identifier"}],"title":"FaceAutoCapturePhase","role":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCapturePhase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the face auto capture process.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTFaceAutoCapturePhaseCandidateSelection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTFaceAutoCapturePhaseCandidateSelection"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFaceAutoCapturePhaseCandidateSelection","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1candidateSelection\/title"},{"op":"replace","value":[{"text":"DOTFaceAutoCapturePhaseCandidateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase~1candidateSelection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/title","value":"DOTFaceAutoCapturePhase"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/fragments","value":[{"text":"DOTFaceAutoCapturePhase","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCapturePhase\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFaceAutoCapturePhase"}]}]}]}