{"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone(py)compositeCheckDigit","symbolKind":"property","title":"compositeCheckDigit","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit"}],"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/compositecheckdigit"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/compositecheckdigit"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/compositeCheckDigit","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"type":"topic","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","role":"symbol","title":"MrzReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","abstract":[{"type":"text","text":"version: 8.5.0"}],"title":"DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzCheckDigit":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit","role":"symbol","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"url":"\/documentation\/dotdocument\/mrzcheckdigit","title":"MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzCheckDigit","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","title":"Td2MachineReadableZone","role":"symbol","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotdocument\/td2machinereadablezone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}]},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/compositeCheckDigit":{"abstract":[],"type":"topic","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone\/compositecheckdigit","navigatorTitle":[{"text":"compositeCheckDigit","kind":"identifier"}],"title":"compositeCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/compositeCheckDigit","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"compositeCheckDigit","kind":"identifier"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"compositeCheckDigit","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"compositeCheckDigit","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTMrzCheckDigit","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzCheckDigit"},{"text":" * ","kind":"text"},{"text":"compositeCheckDigit","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"kind":"identifier","text":"DOTDMrzReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/title","value":"DOTMrzCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzCheckDigit\/fragments","value":[{"text":"DOTMrzCheckDigit","kind":"identifier"}]},{"op":"replace","value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1compositeCheckDigit\/title","value":"compositeCheckDigit"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1compositeCheckDigit\/fragments","op":"replace","value":[{"text":"compositeCheckDigit","kind":"identifier"}]}]}]}