{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)dateOfBirth","roleHeading":"Instance Property","title":"dateOfBirth","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"}],"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfBirth","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"variants":[{"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/dateofbirth"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"kind":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"title":"Td2MachineReadableZone","role":"symbol","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone/dateOfBirth":{"abstract":[],"navigatorTitle":[{"text":"dateOfBirth","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dateOfBirth"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone\/dateofbirth","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/dateOfBirth","kind":"symbol","type":"topic","title":"dateOfBirth","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"url":"\/documentation\/dotdocument\/mrzreader","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}]},"doc://DotDocument/documentation/DotDocument/MrzDateElementWithCheckDigit":{"navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","title":"MrzDateElementWithCheckDigit","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"code":"Date","type":"codeVoice"},{"type":"text","text":" value."}],"url":"\/documentation\/dotdocument\/mrzdateelementwithcheckdigit","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"dateOfBirth","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"dateOfBirth"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"DOTMrzDateElementWithCheckDigit"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"dateOfBirth"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments"},{"value":"dateOfBirth","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfBirth\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1dateOfBirth\/fragments","value":[{"kind":"identifier","text":"dateOfBirth"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace","value":"DOTDMrzReader"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/title","value":"DOTMrzDateElementWithCheckDigit"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzDateElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}]}]}]}