{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/documentNumber"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/documentnumber"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/documentnumber"]}],"metadata":{"role":"symbol","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd2MachineReadableZone(py)documentNumber","modules":[{"name":"DotDocument"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"}],"roleHeading":"Instance Property","title":"documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","url":"\/documentation\/dotdocument\/td2machinereadablezone","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Td2MachineReadableZone"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Td2MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone","role":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}],"role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"title":"MrzElementWithCheckDigit","role":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/Td2MachineReadableZone/documentNumber":{"url":"\/documentation\/dotdocument\/td2machinereadablezone\/documentnumber","type":"topic","title":"documentNumber","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Td2MachineReadableZone\/documentNumber","navigatorTitle":[{"text":"documentNumber","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"documentNumber","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"documentNumber","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTMrzElementWithCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"},{"text":" * ","kind":"text"},{"text":"documentNumber","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTTd2MachineReadableZone","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","op":"replace"},{"value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone\/navigatorTitle","op":"replace"},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle","op":"replace"},{"value":"DOTMrzElementWithCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace"},{"value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/navigatorTitle","op":"replace"},{"value":"documentNumber","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1documentNumber\/title","op":"replace"},{"value":[{"text":"documentNumber","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Td2MachineReadableZone~1documentNumber\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}