{"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/issuingStateOrOrganization","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"issuingStateOrOrganization","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"}],"roleHeading":"Instance Property","role":"symbol","title":"issuingStateOrOrganization","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTTd2MachineReadableZone(py)issuingStateOrOrganization","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/issuingstateororganization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/issuingstateororganization"]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzElement":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"kind":"symbol","url":"\/documentation\/dotdocument\/mrzelement","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","title":"MrzElement"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/issuingStateOrOrganization":{"navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"}],"abstract":[],"kind":"symbol","title":"issuingStateOrOrganization","url":"\/documentation\/dotdocument\/td2machinereadablezone\/issuingstateororganization","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/issuingStateOrOrganization","role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"navigatorTitle":[{"kind":"identifier","text":"MrzReader"}],"role":"symbol","title":"MrzReader"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"url":"\/documentation\/dotdocument\/td2machinereadablezone","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Td2MachineReadableZone","kind":"identifier"}],"kind":"symbol","title":"Td2MachineReadableZone","abstract":[{"type":"text","text":"Result of MRZ reading of TD2."}],"navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.3.1"}],"kind":"symbol","title":"DotDocument","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"issuingStateOrOrganization","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzElement","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTMrzElement"},{"kind":"text","text":" * "},{"text":"issuingStateOrOrganization","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1issuingStateOrOrganization\/title","value":"issuingStateOrOrganization"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone~1issuingStateOrOrganization\/fragments","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"op":"replace"},{"value":"DOTDMrzReader","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"value":"DOTTd2MachineReadableZone","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"kind":"identifier","text":"DOTTd2MachineReadableZone"}]}]}]}