{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/init()"]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/init()","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(im)init","title":"init()","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"role":"symbol","symbolKind":"init"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary/init()":{"title":"init()","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"()","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[],"type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/init()","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary\/init()"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DotDocumentLibrary":{"navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"type":"topic","title":"DotDocumentLibrary","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotDocumentLibrary","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DotDocumentLibrary","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/dotdocumentlibrary","abstract":[{"text":"Class responsible for the ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":" library initialization.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"init","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1init()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary~1init()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"value":"DotDocumentLibrary","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/title"},{"value":[{"kind":"identifier","text":"DotDocumentLibrary"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DotDocumentLibrary\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}