{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfacematchingenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfacematchingenabled"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled"},"metadata":{"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceMatchingEnabled","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotNfc"}],"title":"isFaceMatchingEnabled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"required":true},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol":{"role":"symbol","abstract":[],"title":"DotSdkLicenseProxyProtocol","type":"topic","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"url":"\/documentation\/dotnfc\/dotsdklicenseproxyprotocol\/isfacematchingenabled","type":"topic","role":"symbol","abstract":[],"title":"isFaceMatchingEnabled","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","required":true,"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"isFaceMatchingEnabled"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol\/navigatorTitle","op":"replace"},{"value":"isFaceMatchingEnabled","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","op":"replace"},{"value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments","op":"replace"}]}]}