{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"_RawImage.bytes"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytes"},"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytes","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"bytes"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"role":"symbol","title":"bytes","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrarawimage\/bytes"]},{"paths":["\/documentation\/dotfacecore\/bgrarawimage\/bytes"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"lazy","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytes"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage/bytes":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage\/bytes","title":"bytes","url":"\/documentation\/dotfacecore\/bgrarawimage\/bytes","abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"}],"navigatorTitle":[{"kind":"identifier","text":"bytes"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/BgraRawImage":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol","type":"topic","title":"BgraRawImage","url":"\/documentation\/dotfacecore\/bgrarawimage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgraRawImage","role":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"bytes","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"bytes","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readwrite","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bytes"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytes\/title","value":"bytes"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage~1bytes\/fragments","op":"replace","value":[{"kind":"identifier","text":"bytes"}]},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}