{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNNfcTravelDocumentReaderProtocol) "},{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"role":"symbol","title":"NfcTravelDocumentReaderProtocol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"symbolKind":"protocol","externalID":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderProtocol","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:activeAuthenticationChallenge:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:queue:)"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/read(nfcKey:activeAuthenticationChallenge:)":{"navigatorTitle":[{"kind":"identifier","text":"readWithNfcKey:activeAuthenticationChallenge:"}],"role":"symbol","title":"read(nfcKey:activeAuthenticationChallenge:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"kind":"text","text":", "},{"kind":"externalParam","text":"activeAuthenticationChallenge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Read passport using NFC key."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:activeAuthenticationChallenge:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/read(nfckey:activeauthenticationchallenge:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/read(nfcKey:)":{"role":"symbol","title":"read(nfcKey:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"read"},{"kind":"text","text":"("},{"kind":"externalParam","text":"nfcKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcKey","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTNNfcKey"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Read passport using NFC key."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/read(nfckey:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/setDelegate(_:)":{"role":"symbol","title":"setDelegate(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set delegate, "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to it."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:)","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/setdelegate(_:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol":{"role":"symbol","title":"NfcTravelDocumentReaderProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderProtocol"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderProtocol/setDelegate(_:queue:)":{"navigatorTitle":[{"kind":"identifier","text":"setDelegate:queue:"}],"role":"symbol","title":"setDelegate(_:queue:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setDelegate"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderDelegate","preciseIdentifier":"c:@M@DotNfc@objc(pl)DOTNNfcTravelDocumentReaderDelegate"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set delegate and "},{"type":"codeVoice","code":"DispatchQueue"},{"type":"text","text":" on which you want to recieve the delegate callbacks. "},{"type":"codeVoice","code":"NfcTravelDocumentReader"},{"type":"text","text":" will hold weak reference to "},{"type":"codeVoice","code":"delegate"},{"type":"text","text":" and "},{"type":"codeVoice","code":"queue"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:queue:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreaderprotocol\/setdelegate(_:queue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"DOTNNfcTravelDocumentReaderProtocol"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/read(nfcKey:activeAuthenticationChallenge:)","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderProtocol\/setDelegate(_:queue:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol~1read(nfcKey:activeAuthenticationChallenge:)\/title","value":"readWithNfcKey:activeAuthenticationChallenge:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol~1read(nfcKey:activeAuthenticationChallenge:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"readWithNfcKey:activeAuthenticationChallenge:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/title","value":"DOTNNfcTravelDocumentReaderProtocol"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderProtocol"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol~1setDelegate(_:queue:)\/title","value":"setDelegate:queue:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderProtocol~1setDelegate(_:queue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setDelegate:queue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}