{"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPointDouble) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument"]]},"metadata":{"title":"PointDouble","symbolKind":"class","modules":[{"name":"DotDocument"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTPointDouble"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/init(x:y:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/cgPoint","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/x","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/y"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/mirrored()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/rebased(parentRectangle:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/from(cgPoint:)"],"title":"Type Methods"}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"},{"title":"Conforms To","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.document\/SQ","doc:\/\/com.innovatrics.dot.document\/SH"],"type":"conformsTo","kind":"relationships"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointdouble"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/pointdouble"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/isEqual(_:)":{"type":"topic","kind":"symbol","title":"isEqual(_:)","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/isEqual(_:)","url":"\/documentation\/dotdocument\/pointdouble\/isequal(_:)"},"doc://com.innovatrics.dot.document/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject","title":"NSObject"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/hash":{"type":"topic","title":"hash","kind":"symbol","navigatorTitle":[{"text":"hash","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/pointdouble\/hash","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/hash"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/description":{"kind":"symbol","type":"topic","title":"description","navigatorTitle":[{"text":"description","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/pointdouble\/description","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/description"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/cgPoint":{"type":"topic","title":"cgPoint","kind":"symbol","navigatorTitle":[{"text":"cgPoint","kind":"identifier"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgPoint","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotdocument\/pointdouble\/cgpoint","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/cgPoint"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/y":{"kind":"symbol","type":"topic","title":"y","navigatorTitle":[{"text":"y","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"url":"\/documentation\/dotdocument\/pointdouble\/y","abstract":[{"text":"Y coordinate.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/y"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/rebased(parentRectangle:)":{"type":"topic","kind":"symbol","title":"rebased(parentRectangle:)","navigatorTitle":[{"text":"rebasedWithParentRectangle:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/rebased(parentRectangle:)","url":"\/documentation\/dotdocument\/pointdouble\/rebased(parentrectangle:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/from(cgPoint:)":{"kind":"symbol","type":"topic","title":"from(cgPoint:)","navigatorTitle":[{"kind":"identifier","text":"fromCgPoint:"}],"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgPoint","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGPoint","text":"CGPoint","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/pointdouble\/from(cgpoint:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/from(cgPoint:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/x":{"type":"topic","kind":"symbol","title":"x","navigatorTitle":[{"text":"x","kind":"identifier"}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"X coordinate."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/x","url":"\/documentation\/dotdocument\/pointdouble\/x"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/init(x:y:)":{"kind":"symbol","type":"topic","title":"init(x:y:)","navigatorTitle":[{"text":"initWithX:y:","kind":"identifier"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"x","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"y","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/dotdocument\/pointdouble\/init(x:y:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/init(x:y:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","title":"DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","abstract":[{"text":"version: 8.3.2","type":"text"}],"role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble":{"type":"topic","title":"PointDouble","kind":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotdocument\/pointdouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble"},"doc://com.innovatrics.dot.document/SH":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SH","title":"Swift.Hashable"},"doc://com.innovatrics.dot.document/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.innovatrics.dot.document/documentation/DotDocument/PointDouble/mirrored()":{"kind":"symbol","type":"topic","title":"mirrored()","navigatorTitle":[{"text":"mirrored","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"mirrored"},{"text":"() -> ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTPointDouble"}],"url":"\/documentation\/dotdocument\/pointdouble\/mirrored()","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/mirrored()"},"doc://com.innovatrics.dot.document/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.document/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/SQ"},"doc://com.innovatrics.dot.document/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.document\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.document/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.document\/objc(pl)NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"DOTPointDouble","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/cgPoint","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/description","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/hash","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/x","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/y"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/init(x:y:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/isEqual(_:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/mirrored()","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/rebased(parentRectangle:)"]},{"identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/PointDouble\/from(cgPoint:)"],"title":"Type Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.innovatrics.dot.document\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPointDouble"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1isEqual(_:)\/title","op":"replace","value":"isEqual:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"isEqual:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1isEqual(_:)\/fragments","op":"replace"},{"value":"hash","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1hash\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1hash\/fragments","value":[{"kind":"identifier","text":"hash"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1description\/title","value":"description"},{"value":[{"kind":"identifier","text":"description"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1description\/fragments","op":"replace"},{"op":"replace","value":"cgPoint","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1cgPoint\/title"},{"op":"replace","value":[{"text":"cgPoint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1cgPoint\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1y\/title","value":"y"},{"op":"replace","value":[{"text":"y","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1y\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1rebased(parentRectangle:)\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1rebased(parentRectangle:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1from(cgPoint:)\/title","value":"fromCgPoint:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fromCgPoint:"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1from(cgPoint:)\/fragments"},{"op":"replace","value":"x","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1x\/title"},{"op":"replace","value":[{"kind":"identifier","text":"x"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1x\/fragments"},{"value":"initWithX:y:","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1init(x:y:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithX:y:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1init(x:y:)\/fragments"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","value":"mirrored","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1mirrored()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1PointDouble~1mirrored()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"mirrored","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}