{"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp","symbolKind":"property","title":"barcode","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","role":"symbol","type":"topic","kind":"symbol","abstract":[],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","title":"barcode","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentBarcodeModuleConfiguration":{"url":"\/documentation\/dotpalmcore\/dotdocumentbarcodemoduleconfiguration","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotDocumentBarcodeModuleConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentBarcodeModuleConfiguration","type":"topic","title":"DotDocumentBarcodeModuleConfiguration","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotDocumentLibraryConfiguration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"role":"symbol","kind":"symbol","title":"DotDocumentLibraryConfiguration","abstract":[{"type":"text","text":"Document library configuration."}],"url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration"},"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","title":"DotPalmCore","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.2.2"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DotDocumentLibraryConfiguration/Modules-swift.class":{"role":"symbol","type":"topic","title":"DotDocumentLibraryConfiguration.Modules","kind":"symbol","url":"\/documentation\/dotpalmcore\/dotdocumentlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Document library module configuration."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotDocumentLibraryConfiguration\/Modules-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}],"navigatorTitle":[{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/title","value":"DotDocumentBarcodeModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}]},{"value":"DotDocumentLibraryConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotDocumentLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]}]}]}