{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"metadata":{"modules":[{"name":"DotDocument"}],"title":"x","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTPointDouble(py)x","symbolKind":"property","navigatorTitle":[{"text":"x","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"x","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/pointdouble\/x"]},{"paths":["\/documentation\/dotdocument\/pointdouble\/x"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"X coordinate.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble\/x"},"references":{"doc://DotDocument/documentation/DotDocument/PointDouble/x":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble\/x","role":"symbol","kind":"symbol","url":"\/documentation\/dotdocument\/pointdouble\/x","title":"x","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"text":"x","kind":"identifier"}],"abstract":[{"type":"text","text":"X coordinate."}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.16.0"}],"type":"topic","kind":"symbol","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/PointDouble":{"url":"\/documentation\/dotdocument\/pointdouble","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PointDouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointDouble"}],"title":"PointDouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"x"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"x"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"x"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"x","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble~1x\/title"},{"op":"replace","value":[{"text":"x","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble~1x\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PointDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}