{"abstract":[{"text":"Valid palm size interval. Values greater than or equal to ","type":"text"},{"type":"codeVoice","code":"0.0"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"sizeInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","metadata":{"title":"sizeInterval","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sizeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","kind":"typeIdentifier","text":"IntervalDouble"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"externalID":"s:11DotPalmCore0B25AutoCaptureViewControllerC13ConfigurationC26QualityAttributeThresholdsC12sizeInterval0aC00M6DoubleCSgvp"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/sizeInterval","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/sizeinterval"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","role":"collection","type":"topic","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class":{"title":"PalmAutoCaptureViewController.Configuration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"QualityAttributeThresholds","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"QualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the palm auto capture result."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"title":"PalmAutoCaptureViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing palm images using the placeholder.","type":"text"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class/QualityAttributeThresholds-swift.class/sizeInterval":{"title":"sizeInterval","abstract":[{"type":"text","text":"Valid palm size interval. Values greater than or equal to "},{"type":"codeVoice","code":"0.0"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class\/QualityAttributeThresholds-swift.class\/sizeInterval","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"sizeInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble"},{"text":"?","kind":"text"}],"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class\/qualityattributethresholds-swift.class\/sizeinterval","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/Configuration-swift.class":{"title":"PalmAutoCaptureViewController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/configuration-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/Configuration-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalDouble":{"url":"\/documentation\/dotpalmcore\/intervaldouble","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalDouble"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalDouble"}],"type":"topic","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Double","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"type":"codeVoice","code":"max"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalDouble","title":"IntervalDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title","op":"replace","value":"DOTPPalmAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalDouble\/fragments","value":[{"kind":"identifier","text":"DOTIntervalDouble"}]}]}]}