{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomLeft"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/bottomleft"]},{"paths":["\/documentation\/dotnfc\/corners\/bottomleft"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"text":"Bottom left corner point.","type":"text"}],"metadata":{"roleHeading":"Instance Property","title":"bottomLeft","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)bottomLeft","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}],"modules":[{"name":"DotNfc"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bottomLeft","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","text":"PointDouble"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/Corners":{"kind":"symbol","title":"Corners","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}],"url":"\/documentation\/dotnfc\/corners","role":"symbol","abstract":[{"text":"Four detected corners in an image.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/Corners/bottomLeft":{"title":"bottomLeft","url":"\/documentation\/dotnfc\/corners\/bottomleft","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"bottomLeft"}],"abstract":[{"text":"Bottom left corner point.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/bottomLeft","type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bottomLeft","kind":"identifier"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}]},"doc://DotNfc/documentation/DotNfc/PointDouble":{"kind":"symbol","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","title":"PointDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PointDouble"}],"navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"url":"\/documentation\/dotnfc\/pointdouble","role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}]},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotNfc","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"bottomLeft"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bottomLeft"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"DOTPointDouble","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble"},{"text":" * ","kind":"text"},{"text":"bottomLeft","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","value":"DOTCorners"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomLeft\/title","value":"bottomLeft","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1bottomLeft\/fragments","value":[{"text":"bottomLeft","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTPointDouble","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title"},{"value":[{"kind":"identifier","text":"DOTPointDouble"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace"}]}]}