{"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(cm)fromRectangle:","symbolKind":"method","modules":[{"name":"DotNfc","relatedModules":["DotCore"]}],"title":"from(rectangle:)","roleHeading":"Type Method","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"text":"(","kind":"text"},{"text":"rectangle","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":") -> "},{"text":"Corners","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"extendedModule":"DotCore","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/from(rectangle:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotnfc\/corners\/from(rectangle:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners\/from(rectangle:)"]}],"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/Corners/from(rectangle:)":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/from(rectangle:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"from"},{"kind":"text","text":"("},{"text":"rectangle","kind":"externalParam"},{"kind":"text","text":": "},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"}],"kind":"symbol","url":"\/documentation\/dotnfc\/corners\/from(rectangle:)","type":"topic","abstract":[],"title":"from(rectangle:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromRectangle:"}]},"doc://DotNfc/documentation/DotNfc/Corners":{"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","title":"Corners","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Corners"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/corners","role":"symbol","abstract":[{"type":"text","text":"Four detected corners in an image."}]},"doc://DotNfc/documentation/DotNfc/RectangleDouble":{"url":"\/documentation\/dotnfc\/rectangledouble","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"role":"symbol","type":"topic","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value type.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","title":"RectangleDouble"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"fromRectangle:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"fromRectangle:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","text":"DOTCorners","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCorners"},{"text":" *) ","kind":"text"},{"text":"fromRectangle:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"rectangle"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1from(rectangle:)\/title","op":"replace","value":"fromRectangle:"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1from(rectangle:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"fromRectangle:"}]},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1RectangleDouble\/fragments","op":"replace"}]}]}