{"metadata":{"navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"symbolKind":"init","modules":[{"name":"DotNfc"}],"role":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","externalID":"c:@M@DotNfc@objc(cs)DOTCorners(im)initWithTopLeft:topRight:bottomRight:bottomLeft:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"topRight","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bottomRight"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"bottomLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":")"}],"roleHeading":"Initializer"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"kind":"externalParam","text":"topRight"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"kind":"text","text":", "},{"text":"bottomRight","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","interfaceLanguage":"swift"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/init(topleft:topright:bottomright:bottomleft:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners\/init(topleft:topright:bottomright:bottomleft:)"]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners/init(topLeft:topRight:bottomRight:bottomLeft:)":{"url":"\/documentation\/dotnfc\/corners\/init(topleft:topright:bottomright:bottomleft:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"topLeft","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"text":"topRight","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":", "},{"text":"bottomRight","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"bottomLeft"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(topLeft:topRight:bottomRight:bottomLeft:)","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/init(topLeft:topRight:bottomRight:bottomLeft:)","navigatorTitle":[{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}],"role":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","title":"PointDouble","role":"symbol","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"type":"topic","url":"\/documentation\/dotnfc\/pointdouble"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","role":"collection","kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.2.1"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners":{"title":"Corners","type":"topic","role":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","url":"\/documentation\/dotnfc\/corners","abstract":[{"type":"text","text":"Four detected corners in an image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithTopLeft:topRight:bottomRight:bottomLeft:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithTopLeft:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"DOTPointDouble"},{"text":" *) ","kind":"text"},{"text":"topLeft","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble"},{"text":" *) ","kind":"text"},{"text":"topRight","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"bottomRight:"},{"text":"(","kind":"text"},{"text":"DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"text":" *) ","kind":"text"},{"text":"bottomRight","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"bottomLeft:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","text":"DOTPointDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble"},{"kind":"text","text":" *) "},{"text":"bottomLeft","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"op":"replace","value":"initWithTopLeft:topRight:bottomRight:bottomLeft:","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1init(topLeft:topRight:bottomRight:bottomLeft:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTopLeft:topRight:bottomRight:bottomLeft:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/fragments","op":"replace","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}