{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/points"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/corners\/points"]}],"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/points","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"points"}],"title":"points","extendedModule":"DotCore","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":"]"}],"symbolKind":"property","externalID":"c:@CM@DotCore@objc(cs)DOTCorners(py)points","modules":[{"relatedModules":["DotCore"],"name":"DotNfc"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier","text":"PointDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.17.1"}]},"doc://DotNfc/documentation/DotNfc/Corners":{"url":"\/documentation\/dotnfc\/corners","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Corners"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"type":"topic","title":"Corners","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"type":"topic","title":"PointDouble","url":"\/documentation\/dotnfc\/pointdouble","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}],"abstract":[{"type":"text","text":"Two dimensional point with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}]},"doc://DotNfc/documentation/DotNfc/Corners/points":{"url":"\/documentation\/dotnfc\/corners\/points","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/points","title":"points","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"points"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble"},{"kind":"text","text":"]"}],"navigatorTitle":[{"kind":"identifier","text":"points"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"points","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"points"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<DOTPointDouble *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"points"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","op":"replace","value":"DOTCorners"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace","value":[{"text":"DOTCorners","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/navigatorTitle","value":[{"text":"DOTPointDouble","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1points\/title","value":"points"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1points\/fragments","value":[{"kind":"identifier","text":"points"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}