{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/rebased(parentRectangle:)"},"sections":[],"metadata":{"extendedModule":"DotNfc","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"role":"symbol","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"parentRectangle"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners","text":"Corners"}],"roleHeading":"Instance Method","modules":[{"name":"DotNfc"}],"externalID":"c:@CM@DotNfc@objc(cs)DOTCorners(im)rebasedWithParentRectangle:","title":"rebased(parentRectangle:)"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/corners\/rebased(parentrectangle:)"]},{"paths":["\/documentation\/dotnfc\/corners\/rebased(parentrectangle:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"rebased"},{"text":"(","kind":"text"},{"text":"parentRectangle","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners","text":"Corners","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.4.1"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners":{"abstract":[{"type":"text","text":"Four detected corners in an image."}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Corners","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","url":"\/documentation\/dotnfc\/corners","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Corners"}],"title":"Corners"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/RectangleDouble":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","title":"RectangleDouble","abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotnfc\/rectangledouble","kind":"symbol","role":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners/rebased(parentRectangle:)":{"kind":"symbol","title":"rebased(parentRectangle:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"rebased","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"parentRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Corners","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners"}],"role":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/rebased(parentRectangle:)","navigatorTitle":[{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"url":"\/documentation\/dotnfc\/corners\/rebased(parentrectangle:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"rebasedWithParentRectangle:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTCorners","text":"DOTCorners","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"rebasedWithParentRectangle:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/RectangleDouble","kind":"typeIdentifier","text":"DOTRectangleDouble","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTRectangleDouble"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"parentRectangle"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/title","value":"DOTCorners"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/fragments","value":[{"text":"DOTCorners","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/title","op":"replace","value":"DOTRectangleDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1RectangleDouble\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1rebased(parentRectangle:)\/title","value":"rebasedWithParentRectangle:"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"rebasedWithParentRectangle:"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1rebased(parentRectangle:)\/fragments","op":"replace"}]}]}