{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"PointDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/topLeft"},"variants":[{"paths":["\/documentation\/dotnfc\/corners\/topleft"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/corners\/topleft"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"topLeft","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"externalID":"c:@M@DotNfc@objc(cs)DOTCorners(py)topLeft","title":"topLeft","navigatorTitle":[{"text":"topLeft","kind":"identifier"}]},"abstract":[{"text":"Top left corner point.","type":"text"}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/PointDouble":{"title":"PointDouble","type":"topic","navigatorTitle":[{"text":"PointDouble","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","url":"\/documentation\/dotnfc\/pointdouble","abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PointDouble","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners/topLeft":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topLeft"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","kind":"typeIdentifier","text":"PointDouble"}],"kind":"symbol","type":"topic","title":"topLeft","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners\/topLeft","role":"symbol","url":"\/documentation\/dotnfc\/corners\/topleft","abstract":[{"text":"Top left corner point.","type":"text"}],"navigatorTitle":[{"text":"topLeft","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Corners":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"kind":"symbol","type":"topic","title":"Corners","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Corners","role":"symbol","url":"\/documentation\/dotnfc\/corners","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"Corners"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.3.1","type":"text"}],"url":"\/documentation\/dotnfc","type":"topic","role":"collection","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"topLeft","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"topLeft"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTPointDouble","text":"DOTPointDouble","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/PointDouble","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"topLeft","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1PointDouble\/fragments","value":[{"kind":"identifier","text":"DOTPointDouble"}],"op":"replace"},{"value":"topLeft","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1topLeft\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners~1topLeft\/fragments","value":[{"text":"topLeft","kind":"identifier"}],"op":"replace"},{"value":"DOTCorners","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/title"},{"value":[{"text":"DOTCorners","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Corners\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}