{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Top right corner point."}],"variants":[{"paths":["\/documentation\/dotnfc\/corners\/topright"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/corners\/topright"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Corners"]]},"metadata":{"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"title":"topRight","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTCorners(py)topRight","symbolKind":"property","modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"topRight"},{"kind":"text","text":": "},{"text":"PointDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topRight","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc/Corners":{"type":"topic","abstract":[{"text":"Four detected corners in an image.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Corners","kind":"identifier"}],"navigatorTitle":[{"text":"Corners","kind":"identifier"}],"title":"Corners","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners","url":"\/documentation\/dotnfc\/corners"},"doc://DotNfc/documentation/DotNfc/PointDouble":{"title":"PointDouble","navigatorTitle":[{"kind":"identifier","text":"PointDouble"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","url":"\/documentation\/dotnfc\/pointdouble","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PointDouble","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Two dimensional point with "},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"kind":"symbol","type":"topic"},"doc://DotNfc/documentation/DotNfc/Corners/topRight":{"navigatorTitle":[{"text":"topRight","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Top right corner point."}],"title":"topRight","type":"topic","url":"\/documentation\/dotnfc\/corners\/topright","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"topRight"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","text":"PointDouble","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Corners\/topRight","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection","abstract":[{"text":"version: 8.9.0","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"topRight"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"topRight","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointDouble","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/PointDouble","text":"DOTPointDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"topRight"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTCorners","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTCorners"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/title","value":"DOTPointDouble","op":"replace"},{"value":[{"text":"DOTPointDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1PointDouble\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topRight\/title","value":"topRight"},{"op":"replace","value":[{"text":"topRight","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Corners~1topRight\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}