{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/libraries\/face"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/libraries\/face"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/face","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Face library configuration."}],"metadata":{"role":"symbol","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"face","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"face","kind":"identifier"}],"title":"face","externalID":"c:@M@DotCore@objc(cs)Libraries(py)face","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"url":"\/documentation\/dotdocument\/libraries","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries","abstract":[{"text":"Container for library configurations.","type":"text"}],"kind":"symbol","role":"symbol","title":"Libraries"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","title":"DotDocument","type":"topic","abstract":[{"text":"version: 9.1.0","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/Libraries/face":{"abstract":[{"type":"text","text":"Face library configuration."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/Libraries\/face","title":"face","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"face"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"face"}],"url":"\/documentation\/dotdocument\/libraries\/face"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfiguration":{"title":"DotFaceLibraryConfiguration","kind":"symbol","abstract":[{"text":"Face library configuration.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceLibraryConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotfacelibraryconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"face","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"face","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceLibraryConfiguration","text":"DotFaceLibraryConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"face","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/title","value":"Libraries","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1face\/title","value":"face","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1Libraries~1face\/fragments","value":[{"kind":"identifier","text":"face"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/title","value":"DotFaceLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceLibraryConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceLibraryConfiguration"}],"op":"replace"}]}]}