{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/isLibraryActive(libraryId:)"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk"]]},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdk(im)isLibraryActiveWithLibraryId:","title":"isLibraryActive(libraryId:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isLibraryActive"},{"text":"(","kind":"text"},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotLibraryId","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"method","modules":[{"name":"DotNfc"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isLibraryActive"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":" library is active."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotsdk\/islibraryactive(libraryid:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotsdk\/islibraryactive(libraryid:)"]}],"references":{"doc://DotNfc/documentation/DotNfc/DotSdk":{"url":"\/documentation\/dotnfc\/dotsdk","kind":"symbol","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"code":"DotDocument","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"code":"DotPalm","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotLibraryId":{"role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibraryId"}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}],"title":"DotLibraryId","abstract":[{"text":"The ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"text":" library identifier.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/dotlibraryid"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.7.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotSdk/isLibraryActive(libraryId:)":{"title":"isLibraryActive(libraryId:)","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotSdk\/isLibraryActive(libraryId:)","navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"type":"topic","url":"\/documentation\/dotnfc\/dotsdk\/islibraryactive(libraryid:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isLibraryActive","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"libraryId"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"text":" library is active.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"isLibraryActiveWithLibraryId:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"},{"kind":"text","text":"("},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier","text":"DotLibraryId"},{"text":") ","kind":"text"},{"text":"libraryId","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/title","value":"DotLibraryId"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}]},{"value":"isLibraryActiveWithLibraryId:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1isLibraryActive(libraryId:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotSdk~1isLibraryActive(libraryId:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}