{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/imageparametersnormalizedrectangle"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/imageparametersnormalizedrectangle"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/imageParametersNormalizedRectangle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the image parameters analysis."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?"}],"title":"imageParametersNormalizedRectangle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration(py)imageParametersNormalizedRectangle","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"imageParametersNormalizedRectangle"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 5.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotdocument\/rectangledouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration":{"role":"symbol","title":"DocumentAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration/imageParametersNormalizedRectangle":{"role":"symbol","title":"imageParametersNormalizedRectangle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageParametersNormalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the image parameters analysis."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/imageParametersNormalizedRectangle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageParametersNormalizedRectangle"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/imageparametersnormalizedrectangle"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"imageParametersNormalizedRectangle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"imageParametersNormalizedRectangle"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"DOTRectangleDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"imageParametersNormalizedRectangle"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/title","value":"DOTDDocumentAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1imageParametersNormalizedRectangle\/title","value":"imageParametersNormalizedRectangle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1imageParametersNormalizedRectangle\/fragments","value":[{"kind":"identifier","text":"imageParametersNormalizedRectangle"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}