{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/facedetector\/result\/normalizedrectangle"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result\/normalizedRectangle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Normalized rectangle representing the position of the detected face in the image. The rectangle is normalized to image size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLRectangleDouble"},{"kind":"text","text":"?"}],"title":"normalizedRectangle","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"s:11DotFaceLite0B8DetectorC6ResultC19normalizedRectangleAA0G6DoubleCSgvp","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Result/normalizedRectangle":{"role":"symbol","title":"normalizedRectangle","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"normalizedRectangle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLRectangleDouble"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Normalized rectangle representing the position of the detected face in the image. The rectangle is normalized to image size."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result\/normalizedRectangle","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/facedetector\/result\/normalizedrectangle"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/RectangleDouble":{"role":"symbol","title":"RectangleDouble","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"url":"\/documentation\/dotfacelite\/rectangledouble"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"DotFaceLite provides components for face capture and related functionalities which are easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect face in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacelite\/facedetector"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceDetector/Result":{"role":"symbol","title":"FaceDetector.Result","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Result"}],"abstract":[{"type":"text","text":"Result of the face detection operation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceDetector\/Result","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Result"}],"url":"\/documentation\/dotfacelite\/facedetector\/result"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/title","value":"DOTFLRectangleDouble"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1RectangleDouble\/fragments","value":[{"kind":"identifier","text":"DOTFLRectangleDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceDetector"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}