{"kind":"symbol","metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocumentCommons@objc(cs)DOTTd1MachineReadableZone(py)issuingStateOrOrganization","title":"issuingStateOrOrganization","navigatorTitle":[{"kind":"identifier","text":"issuingStateOrOrganization"}],"modules":[{"name":"DotNfc"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement"}],"roleHeading":"Instance Property"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/issuingstateororganization"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/issuingstateororganization"]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"text":": ","kind":"text"},{"text":"MrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"}]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/issuingStateOrOrganization","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"title":"DotNfc","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","type":"topic","role":"collection"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone":{"title":"Td1MachineReadableZone","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Td1MachineReadableZone","kind":"identifier"}],"navigatorTitle":[{"text":"Td1MachineReadableZone","kind":"identifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotnfc\/td1machinereadablezone","abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone"},"doc://DotNfc/documentation/DotNfc/MrzElement":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzElement"}],"navigatorTitle":[{"kind":"identifier","text":"MrzElement"}],"abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","title":"MrzElement","type":"topic","url":"\/documentation\/dotnfc\/mrzelement"},"doc://DotNfc/documentation/DotNfc/Td1MachineReadableZone/issuingStateOrOrganization":{"kind":"symbol","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"}],"title":"issuingStateOrOrganization","navigatorTitle":[{"text":"issuingStateOrOrganization","kind":"identifier"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone\/issuingstateororganization","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Td1MachineReadableZone\/issuingStateOrOrganization","type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"issuingStateOrOrganization"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTMrzElement","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElement"},{"kind":"text","text":" * "},{"kind":"identifier","text":"issuingStateOrOrganization"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","value":"DOTTd1MachineReadableZone"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone\/navigatorTitle","value":[{"text":"DOTTd1MachineReadableZone","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/fragments","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1MrzElement\/navigatorTitle","value":[{"text":"DOTMrzElement","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1issuingStateOrOrganization\/title","value":"issuingStateOrOrganization"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Td1MachineReadableZone~1issuingStateOrOrganization\/fragments","value":[{"text":"issuingStateOrOrganization","kind":"identifier"}]}]}]}