{"metadata":{"title":"dependencyIdentifiers","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator(py)dependencyIdentifiers","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":">","kind":"text"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"role":"symbol","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/dependencyidentifiers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator\/dependencyidentifiers"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":">"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/dependencyIdentifiers"},"sections":[],"kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"type":"topic","url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/dependencyidentifiers","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/dependencyIdentifiers"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","role":"symbol","title":"BrightnessTooHighValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"role":"symbol","title":"DocumentAutoCaptureController","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"abstract":[{"type":"text","text":"version: 8.10.0"}],"title":"DotDocument","type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dependencyIdentifiers"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"value":"DOTDBrightnessTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}]},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"}]}]}