{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","roleHeading":"Instance Method","symbolKind":"method","externalID":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration(im)init"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration\/init","interfaceLanguage":"occ"},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration\/init"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration":{"role":"symbol","abstract":[{"text":"Face verification module.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration","type":"topic","title":"DotFaceVerificationModuleConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.2.3","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFaceVerificationModuleConfiguration/init":{"role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/dotfacelite\/dotfaceverificationmoduleconfiguration\/init","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFaceVerificationModuleConfiguration\/init","type":"topic","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceVerificationModuleConfiguration","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFaceVerificationModuleConfiguration\/navigatorTitle","op":"replace"}]}]}