{"variants":[{"paths":["\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/minconfidence:error:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder(im)minConfidence:error:","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minConfidence:error:"}],"navigatorTitle":[{"kind":"identifier","text":"minConfidence:error:"}],"title":"minConfidence:error:","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:"},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder":{"abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","fragments":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder"}],"kind":"symbol","type":"topic","title":"DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder","url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder/minConfidence:error:":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minConfidence:error:"}],"type":"topic","url":"\/documentation\/dotfacelite\/dotflfaceautocapturequalityattributethresholdsbuilder\/minconfidence:error:","title":"minConfidence:error:","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minConfidence:error:"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLFaceAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"text":"version: 9.1.0","type":"text"}],"title":"DotFaceLite","role":"collection","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/WrappedDouble":{"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotfacelite\/wrappeddouble","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedDouble","title":"WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedDouble\/navigatorTitle","op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]}]}]}