{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/init()","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"title":"init()","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"s:11DotFaceLite0B24AutoCaptureConfigurationC26QualityAttributeThresholdsC7BuilderCAGycfc","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds.Builder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Builder"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Builder"}],"url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class":{"role":"symbol","title":"FaceAutoCaptureConfiguration.QualityAttributeThresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeThresholds"}],"url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","abstract":[{"type":"text","text":"version: 7.2.1"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration":{"role":"symbol","title":"FaceAutoCaptureConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureConfiguration"}],"url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureConfiguration/QualityAttributeThresholds-swift.class/Builder/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureConfiguration\/QualityAttributeThresholds-swift.class\/Builder\/init()","kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureconfiguration\/qualityattributethresholds-swift.class\/builder\/init()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureConfiguration\/title","value":"DOTFLFaceAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}