{"abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator"},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"kind":"symbol","seeAlsoSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"generated":true,"title":"Validators"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTDBrightnessTooHighValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"languages":["swift"]}]},{"kind":"content","content":[{"level":2,"anchor":"overview","type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"text":"To use this validator also following validators must be applied: ","type":"text"},{"code":"DocumentOutOfBoundsValidator","type":"codeVoice"},{"type":"text","text":"."}]}]}],"metadata":{"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"title":"BrightnessTooHighValidator","role":"symbol","roleHeading":"Class","symbolKind":"class","externalID":"c:@M@DotDocument@objc(cs)DOTDBrightnessTooHighValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"modules":[{"name":"DotDocument"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/brightnesstoohighvalidator"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init(threshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/threshold"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/defaultThreshold"],"title":"Type Properties"}],"sections":[],"references":{"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/validate(documentAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/validate(documentautocaptureframeparameters:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/validate(documentAutoCaptureFrameParameters:)","title":"validate(documentAutoCaptureFrameParameters:)","abstract":[{"text":"Validate brightness of the detected document.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","title":"MrzNotValidValidator","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNotValidValidator"}],"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/identifier":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/identifier","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/identifier","title":"identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"kind":"identifier","text":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/init(threshold:)":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/init(threshold:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init(threshold:)","title":"init(threshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","kind":"symbol","title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","title":"DocumentOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"role":"symbol","title":"DocumentNotDetectedValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/dependencyIdentifiers":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/dependencyidentifiers","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/threshold":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/threshold","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/threshold","title":"threshold","abstract":[{"text":"Current maximal accepted brightness.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"threshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"threshold","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","title":"DocumentAutoCaptureDetectionValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"type":"topic","abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator"},"doc://DotDocument/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/init()":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/init()","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init()","title":"init()","abstract":[{"text":"Initialize with default threshold.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator/defaultThreshold":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator\/defaultthreshold","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/defaultThreshold","title":"defaultThreshold","abstract":[{"type":"text","text":"Default threshold is 0.9."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultThreshold"},{"text":": ","kind":"text"},{"text":"Double","preciseIdentifier":"s:Sd","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}],"kind":"symbol","type":"topic"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","title":"HotspotsScoreTooHighValidator","abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"type":"topic","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","title":"DocumentDoesNotFitPlaceholderValidator","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"DOTDBrightnessTooHighValidator","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"}]},{"path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/init(threshold:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/validate(documentAutoCaptureFrameParameters:)"]},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator\/defaultThreshold"],"title":"Type Properties"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"title":"Conforms To"}]},{"value":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"],"title":"Validators"}],"path":"\/seeAlsoSections","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"DOTDBrightnessTooHighValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","value":"DOTDSharpnessTooLowValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"kind":"identifier","text":"DOTDSharpnessTooLowValidator"}],"op":"replace"},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments"},{"value":"DOTDMrzNotValidValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1identifier\/fragments","value":[{"kind":"identifier","text":"identifier"}],"op":"replace"},{"value":"initWithThreshold:error:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init(threshold:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init(threshold:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithThreshold:error:","kind":"identifier"}]},{"value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","value":"DOTDDocumentOutOfBoundsValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentOutOfBoundsValidator"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments"},{"value":"DOTDBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments"},{"op":"replace","value":"DOTDDocumentNotDetectedValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1threshold\/title","value":"threshold"},{"value":[{"text":"threshold","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1threshold\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}]},{"op":"replace","value":"DOTDBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init()\/title","op":"replace","value":"init"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1init()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1defaultThreshold\/title","value":"defaultThreshold"},{"value":[{"kind":"identifier","text":"defaultThreshold"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator~1defaultThreshold\/fragments","op":"replace"},{"op":"replace","value":"DOTDHotspotsScoreTooHighValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTDHotspotsScoreTooHighValidator"}]},{"op":"replace","value":"DOTDDocumentDoesNotFitPlaceholderValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentDoesNotFitPlaceholderValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}