{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTDDocumentNotDetectedValidator) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"title":"Conforms To","kind":"relationships"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentNotDetectedValidator","role":"symbol","modules":[{"name":"DotDocument"}],"symbolKind":"class","roleHeading":"Class","title":"DocumentNotDetectedValidator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}]},"abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"seeAlsoSections":[{"title":"Validators","generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]}],"topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init(minConfidenceThreshold:)"],"title":"Initializers"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/minConfidenceThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/defaultMinConfidenceThreshold"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentnotdetectedvalidator"]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/SharpnessTooLowValidator":{"url":"\/documentation\/dotdocument\/sharpnesstoolowvalidator","role":"symbol","abstract":[{"text":"Validate minimum sharpness of the detected document.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","title":"SharpnessTooLowValidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotDocument/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject","title":"NSObject"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/init(minConfidenceThreshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"role":"symbol","title":"init(minConfidenceThreshold:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init(minConfidenceThreshold:)","kind":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/init(minconfidencethreshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"navigatorTitle":[{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/validate(documentAutoCaptureFrameParameters:)":{"navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"role":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/validate(documentautocaptureframeparameters:)","kind":"symbol","abstract":[{"text":"Validate confidence of the detected document.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/validate(documentAutoCaptureFrameParameters:)","title":"validate(documentAutoCaptureFrameParameters:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/identifier":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/identifier","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/identifier","title":"identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentNotDetectedValidator"}],"role":"symbol","title":"DocumentNotDetectedValidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator","kind":"symbol","abstract":[{"text":"Defines a confidence threshold for document detection.","type":"text"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator","navigatorTitle":[{"text":"DocumentNotDetectedValidator","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","title":"MrzNotValidValidator","abstract":[{"text":"Validate Machine Readable Zone.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzNotValidValidator"}],"navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/defaultMinConfidenceThreshold":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultMinConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"navigatorTitle":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}],"kind":"symbol","title":"defaultMinConfidenceThreshold","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/defaultminconfidencethreshold","abstract":[{"type":"text","text":"Default threshold is 0.9."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/defaultMinConfidenceThreshold","type":"topic","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/init()":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/init()","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init()","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Initialize with default threshold."}],"title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"role":"symbol","title":"DocumentAutoCaptureDetectionValidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"type":"topic","abstract":[{"text":"Use this protocol to create document validators.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator"},"doc://DotDocument/documentation/DotDocument/BrightnessTooLowValidator":{"url":"\/documentation\/dotdocument\/brightnesstoolowvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","title":"BrightnessTooLowValidator","abstract":[{"type":"text","text":"Validate minimum brightness of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooLowValidator","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}],"kind":"symbol","type":"topic"},"doc://DotDocument/SH":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH","title":"Swift.Hashable"},"doc://DotDocument/documentation/DotDocument/DocumentDoesNotFitPlaceholderValidator":{"url":"\/documentation\/dotdocument\/documentdoesnotfitplaceholdervalidator","navigatorTitle":[{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDoesNotFitPlaceholderValidator","kind":"identifier"}],"type":"topic","abstract":[{"text":"Validates position of the detected document relative to the placeholder.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator","title":"DocumentDoesNotFitPlaceholderValidator","kind":"symbol"},"doc://DotDocument/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotDocument/documentation/DotDocument/DocumentOutOfBoundsValidator":{"url":"\/documentation\/dotdocument\/documentoutofboundsvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","title":"DocumentOutOfBoundsValidator","abstract":[{"type":"text","text":"Validate if the detected document is within the bounds of the image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentOutOfBoundsValidator"}],"navigatorTitle":[{"text":"DocumentOutOfBoundsValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/SizeTooSmallValidator":{"url":"\/documentation\/dotdocument\/sizetoosmallvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate size of the detected document."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"navigatorTitle":[{"text":"SizeTooSmallValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","kind":"symbol","title":"DocumentAutoCaptureController","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ","title":"Swift.Equatable"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/dependencyIdentifiers":{"type":"topic","title":"dependencyIdentifiers","kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/dependencyidentifiers"},"doc://DotDocument/documentation/DotDocument/BrightnessTooHighValidator":{"url":"\/documentation\/dotdocument\/brightnesstoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","title":"BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooHighValidator"}],"navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://DotDocument/documentation/DotDocument/DocumentNotDetectedValidator/minConfidenceThreshold":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minConfidenceThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","abstract":[{"type":"text","text":"Current minimal accepted confidence."}],"navigatorTitle":[{"kind":"identifier","text":"minConfidenceThreshold"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/minConfidenceThreshold","kind":"symbol","title":"minConfidenceThreshold","url":"\/documentation\/dotdocument\/documentnotdetectedvalidator\/minconfidencethreshold"},"doc://DotDocument/documentation/DotDocument/HotspotsScoreTooHighValidator":{"url":"\/documentation\/dotdocument\/hotspotsscoretoohighvalidator","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","title":"HotspotsScoreTooHighValidator","abstract":[{"type":"text","text":"Validate hotspots score of the detected document."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HotspotsScoreTooHighValidator"}],"navigatorTitle":[{"text":"HotspotsScoreTooHighValidator","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"DOTDDocumentNotDetectedValidator","op":"replace"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/dependencyIdentifiers","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/identifier","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/minConfidenceThreshold"],"title":"Instance Properties"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init()","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/init(minConfidenceThreshold:)","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/validate(documentAutoCaptureFrameParameters:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentNotDetectedValidator\/defaultMinConfidenceThreshold"],"title":"Type Properties"}]},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"op":"replace"},{"op":"replace","path":"\/seeAlsoSections","value":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentOutOfBoundsValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SizeTooSmallValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/SharpnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooLowValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/BrightnessTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/HotspotsScoreTooHighValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDoesNotFitPlaceholderValidator"]}]},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTDDocumentNotDetectedValidator","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/title","op":"replace","value":"DOTDSharpnessTooLowValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTDSharpnessTooLowValidator","kind":"identifier"}]},{"value":"initWithMinConfidenceThreshold:error:","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init(minConfidenceThreshold:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init(minConfidenceThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}]},{"op":"replace","value":"validateWithDocumentAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1validate(documentAutoCaptureFrameParameters:)\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1identifier\/title","value":"identifier","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1identifier\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/title","op":"replace","value":"DOTDDocumentNotDetectedValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentNotDetectedValidator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","value":"DOTDMrzNotValidValidator"},{"op":"replace","value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments"},{"value":"defaultMinConfidenceThreshold","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1defaultMinConfidenceThreshold\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1defaultMinConfidenceThreshold\/fragments","value":[{"text":"defaultMinConfidenceThreshold","kind":"identifier"}]},{"op":"replace","value":"init","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init()\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"init"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"value":[{"text":"DOTDDocumentAutoCaptureDetectionValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/title","value":"DOTDBrightnessTooLowValidator"},{"value":[{"text":"DOTDBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooLowValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/title","value":"DOTDDocumentDoesNotFitPlaceholderValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDoesNotFitPlaceholderValidator\/fragments","op":"replace","value":[{"text":"DOTDDocumentDoesNotFitPlaceholderValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/title","op":"replace","value":"DOTDDocumentOutOfBoundsValidator"},{"value":[{"text":"DOTDDocumentOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentOutOfBoundsValidator\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/title","value":"DOTDSizeTooSmallValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDSizeTooSmallValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1SizeTooSmallValidator\/fragments"},{"value":"DOTDDocumentAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1dependencyIdentifiers\/title","value":"dependencyIdentifiers","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/title","value":"DOTDBrightnessTooHighValidator"},{"value":[{"kind":"identifier","text":"DOTDBrightnessTooHighValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BrightnessTooHighValidator\/fragments","op":"replace"},{"value":"minConfidenceThreshold","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1minConfidenceThreshold\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentNotDetectedValidator~1minConfidenceThreshold\/fragments","op":"replace","value":[{"text":"minConfidenceThreshold","kind":"identifier"}]},{"value":"DOTDHotspotsScoreTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1HotspotsScoreTooHighValidator\/fragments","value":[{"text":"DOTDHotspotsScoreTooHighValidator","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}