{"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollerdelegate-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/DocumentAutoCaptureControllerDelegate-Implementations","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:captured:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:detected:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureControllerCandidateSelectionStarted(_:)"],"generated":true}],"kind":"article","metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"DocumentAutoCaptureControllerDelegate Implementations"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/documentAutoCaptureControllerCandidateSelectionStarted(_:)":{"role":"symbol","title":"documentAutoCaptureControllerCandidateSelectionStarted(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the candidate selection phase has started."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureControllerCandidateSelectionStarted(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontrollercandidateselectionstarted(_:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/documentAutoCaptureController(_:detected:)":{"role":"symbol","title":"documentAutoCaptureController(_:detected:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detected"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetection","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureDetection"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:detected:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureController:detected:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontroller(_:detected:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 3.7.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController/documentAutoCaptureController(_:captured:)":{"role":"symbol","title":"documentAutoCaptureController(_:captured:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentAutoCaptureController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DocumentAutoCaptureController","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureResult","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDocumentAutoCaptureResult"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Tells the delegate that the document was captured."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:captured:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"documentAutoCaptureController:captured:"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller\/documentautocapturecontroller(_:captured:)"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureViewController":{"role":"symbol","title":"DocumentAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing document images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureViewController"}],"url":"\/documentation\/dotdocument\/documentautocaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:captured:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureController(_:detected:)","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureViewController\/documentAutoCaptureControllerCandidateSelectionStarted(_:)"],"generated":true}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/title","value":"documentAutoCaptureControllerCandidateSelectionStarted:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureControllerCandidateSelectionStarted(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureControllerCandidateSelectionStarted:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureController(_:detected:)\/title","value":"documentAutoCaptureController:detected:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureController(_:detected:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureController:detected:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureController(_:captured:)\/title","value":"documentAutoCaptureController:captured:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController~1documentAutoCaptureController(_:captured:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"documentAutoCaptureController:captured:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/title","value":"DOTDocumentAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTDocumentAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}