{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles\/little","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"]]},"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"little","kind":"identifier"}],"title":"little","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles(py)little","symbolKind":"property"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","text":"FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier"},{"kind":"text","text":"?"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerbundles\/little"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerbundles\/little"]}],"kind":"symbol","sections":[],"abstract":[{"text":"Little finger bundle, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"role":"symbol","title":"FingerBundle","navigatorTitle":[{"text":"FingerBundle","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle","abstract":[{"type":"text","text":"Bundle of a finger image with detection data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerBundle"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"abstract":[{"type":"text","text":"Bundles of finger images with detection data."}],"url":"\/documentation\/dotfingerscore\/fingerbundles","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"title":"FingerBundles","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles/little":{"url":"\/documentation\/dotfingerscore\/fingerbundles\/little","abstract":[{"type":"text","text":"Little finger bundle, or "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if the finger was not detected in the image."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"little","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"little"}],"title":"little","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles\/little"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","value":"little","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"little","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","text":"DOTFGFingerBundle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"little"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title","value":"DOTFGFingerBundle","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}]},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title","value":"DOTFGFingerBundles","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles~1little\/title","value":"little","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles~1little\/fragments","value":[{"kind":"identifier","text":"little"}],"op":"replace"}]}]}