{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles\/middle","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundles(py)middle","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"middle","roleHeading":"Instance Property","navigatorTitle":[{"text":"middle","kind":"identifier"}],"symbolKind":"property","role":"symbol"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"middle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingerBundle","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle"},{"text":"?","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingerbundles\/middle"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingerbundles\/middle"]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Middle finger bundle, or "},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the finger was not detected in the image."}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerBundle":{"role":"symbol","title":"FingerBundle","navigatorTitle":[{"text":"FingerBundle","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerbundle","abstract":[{"type":"text","text":"Bundle of a finger image with detection data."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FingerBundle"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles/middle":{"url":"\/documentation\/dotfingerscore\/fingerbundles\/middle","abstract":[{"type":"text","text":"Middle finger bundle, or "},{"type":"codeVoice","code":"nil"},{"text":" if the finger was not detected in the image.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"middle"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","kind":"typeIdentifier","text":"FingerBundle"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"middle"}],"title":"middle","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles\/middle"},"doc://DotFingersCore/documentation/DotFingersCore/FingerBundles":{"abstract":[{"type":"text","text":"Bundles of finger images with detection data."}],"url":"\/documentation\/dotfingerscore\/fingerbundles","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerBundles"}],"navigatorTitle":[{"kind":"identifier","text":"FingerBundles"}],"title":"FingerBundles","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundles"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"middle"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"middle","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerBundle","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingerBundle","text":"DOTFGFingerBundle"},{"kind":"text","text":" * "},{"kind":"identifier","text":"middle"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFGFingerBundle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundle\/navigatorTitle"},{"op":"replace","value":"middle","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles~1middle\/title"},{"op":"replace","value":[{"kind":"identifier","text":"middle"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles~1middle\/fragments"},{"op":"replace","value":"DOTFGFingerBundles","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingerBundles"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerBundles\/navigatorTitle"}]}]}