{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"Module configuration."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules-swift.property","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"modules"}],"title":"modules","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(py)modules","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules"}],"role":"symbol","symbolKind":"property"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"modules"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.property"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.property"]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfigurationModules":{"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfigurationmodules","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","abstract":[{"type":"text","text":"Palm library module configuration."}],"title":"DotPalmLibraryConfigurationModules"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration":{"role":"symbol","abstract":[{"type":"text","text":"Palm library configuration."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/modules-swift.property":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"modules","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/modules-swift.property","title":"modules","url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.property","abstract":[{"text":"Module configuration.","type":"text"}],"kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotPalmLibraryConfiguration/Modules-swift.class":{"type":"topic","abstract":[{"text":"Palm library module configuration.","type":"text"}],"url":"\/documentation\/dotpalmcore\/dotpalmlibraryconfiguration\/modules-swift.class","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"text":"Modules","kind":"identifier"}],"kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Modules","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"modules","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotPalmLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/title","op":"replace"},{"value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"modules","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules-swift.property\/title","op":"replace"},{"value":[{"text":"modules","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotPalmLibraryConfiguration~1modules-swift.property\/fragments","op":"replace"}]}]}