{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/libraries\/palm"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/libraries\/palm"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"title":"palm","symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)Libraries(py)palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"modules":[{"name":"DotNfc"}],"roleHeading":"Instance Property","role":"symbol"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/palm","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"palm"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","kind":"typeIdentifier","text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"references":{"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Palm library configuration."}],"title":"DotPalmLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc/Libraries/palm":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"palm","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries\/palm","navigatorTitle":[{"text":"palm","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/libraries\/palm","type":"topic","abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol","title":"palm"},"doc://DotNfc/documentation/DotNfc/Libraries":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Libraries","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Libraries","navigatorTitle":[{"text":"Libraries","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotnfc\/libraries","type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}],"role":"symbol","title":"Libraries"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","kind":"symbol","type":"topic","title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.2.1"}],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":null,"path":"\/metadata\/platforms","op":"add"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"palm","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration","text":"DotPalmLibraryConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"palm"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle","op":"replace"},{"value":"palm","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1palm\/title","op":"replace"},{"value":[{"kind":"identifier","text":"palm"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries~1palm\/fragments","op":"replace"},{"value":"Libraries","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/title","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"Libraries"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Libraries\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}