{"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"title":"title","role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)title","platforms":[{"unavailable":false,"name":"iOS","beta":false,"deprecated":false,"introducedAt":"13.0"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"title"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"title"}]},"sections":[],"abstract":[{"text":"Title.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"title"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/title"]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/title"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/title","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AdditionalPersonalDetails"}],"navigatorTitle":[{"text":"AdditionalPersonalDetails","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"AdditionalPersonalDetails"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"title":"NfcTravelDocumentReader","type":"topic","role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/AdditionalPersonalDetails/title":{"title":"title","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/title","type":"topic","abstract":[{"text":"Title.","type":"text"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails\/title","navigatorTitle":[{"kind":"identifier","text":"title"}],"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"title","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"url":"\/documentation\/dotnfc\/traveldocument","title":"TravelDocument","abstract":[{"text":"Result of NFC reading.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"text":"TravelDocument","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TravelDocument","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 8.3.1"}],"url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"title","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"kind":"text","text":" * "},{"text":"title","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace","value":"DOTNAdditionalPersonalDetails"},{"value":[{"text":"DOTNAdditionalPersonalDetails","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1title\/title","value":"title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1title\/fragments","value":[{"text":"title","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","op":"replace","value":"DOTNTravelDocument"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"text":"DOTNTravelDocument","kind":"identifier"}],"op":"replace"}]}]}