{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/Error"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/Error\/internalError"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use MultiRangeLivenessViewController instead."}]}],"sections":[],"metadata":{"modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"s:11DotFaceCore29EyeGazeLivenessViewControllerC13ConfigurationC5ErrorO08internalJ0sAF_pSgvp","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"title":"internalError","symbolKind":"property","role":"symbol","platforms":[]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"DotSdkError.internalError"},{"text":".","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/error\/internalerror"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class":{"role":"symbol","title":"EyeGazeLivenessViewController.Configuration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"deprecated":true,"type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class","abstract":[{"type":"text","text":"Configuration options for the UI Eye Gaze Liveness component."}]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"deprecated":true,"kind":"symbol","title":"EyeGazeLivenessViewController.Configuration.Error","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/Error","role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"deprecated":true,"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","abstract":[{"text":"UI Eye Gaze Liveness component.","type":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","title":"EyeGazeLivenessViewController"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController/Configuration-swift.class/Error/internalError":{"deprecated":true,"kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller\/configuration-swift.class\/error\/internalerror","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController\/Configuration-swift.class\/Error\/internalError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"type":"topic","title":"internalError","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFEyeGazeLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/navigatorTitle"}]}]}