{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate"]]},"metadata":{"title":"eyeGazeLivenessViewController(_:processed:)","navigatorTitle":[{"text":"eyeGazeLivenessViewController:processed:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"eyeGazeLivenessViewController"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","text":"EyeGazeLivenessViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"kind":"text","text":": "},{"text":"FaceAutoCaptureDetection","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection"},{"kind":"text","text":")"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTFEyeGazeLivenessViewControllerDelegate(im)eyeGazeLivenessViewController:processed:","roleHeading":"Instance Method","role":"symbol"},"kind":"symbol","abstract":[{"text":"Tells the delegate that the new detection was processed.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:processed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:processed:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:processed:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewController","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"processed"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"detection"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"title":"EyeGazeLivenessViewController","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontroller","abstract":[{"type":"text","text":"UI component for evaluating liveness by tracking eye gaze."}],"type":"topic","navigatorTitle":[{"text":"EyeGazeLivenessViewController","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate","kind":"symbol","title":"EyeGazeLivenessViewControllerDelegate","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the eye gaze liveness events."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessViewControllerDelegate"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureDetection":{"title":"FaceAutoCaptureDetection","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"abstract":[{"type":"text","text":"The result of processing video frame during the face auto capture process."}],"url":"\/documentation\/dotfacecore\/faceautocapturedetection","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureDetection"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/EyeGazeLivenessViewControllerDelegate/eyeGazeLivenessViewController(_:processed:)":{"url":"\/documentation\/dotfacecore\/eyegazelivenessviewcontrollerdelegate\/eyegazelivenessviewcontroller(_:processed:)","role":"symbol","navigatorTitle":[{"text":"eyeGazeLivenessViewController:processed:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewControllerDelegate\/eyeGazeLivenessViewController(_:processed:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"eyeGazeLivenessViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"EyeGazeLivenessViewController","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController"},{"text":", ","kind":"text"},{"text":"processed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","text":"FaceAutoCaptureDetection","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Tells the delegate that the new detection was processed."}],"title":"eyeGazeLivenessViewController(_:processed:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"eyeGazeLivenessViewController:processed:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"eyeGazeLivenessViewController:processed:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"eyeGazeLivenessViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFEyeGazeLivenessViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/EyeGazeLivenessViewController","kind":"typeIdentifier","text":"DOTFEyeGazeLivenessViewController"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":" "},{"text":"processed:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureDetection","text":"DOTFFaceAutoCaptureDetection","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureDetection","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"detection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/title","value":"DOTFEyeGazeLivenessViewController","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewController\/fragments","value":[{"text":"DOTFEyeGazeLivenessViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/title","value":"DOTFEyeGazeLivenessViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessViewControllerDelegate"}]},{"value":"DOTFFaceAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureDetection\/fragments","value":[{"text":"DOTFFaceAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","value":"eyeGazeLivenessViewController:processed:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:processed:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1EyeGazeLivenessViewControllerDelegate~1eyeGazeLivenessViewController(_:processed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"eyeGazeLivenessViewController:processed:"}]}]}]}