{"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","text":"WrappedFloat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"]}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/maxDevicePitchAngle","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Maximal pitch angle of the device."},{"type":"text","text":" "},{"type":"text","text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/maxdevicepitchangle"]},{"paths":["\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/maxdevicepitchangle"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"DotFaceLite"}],"role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat"},{"text":"?","kind":"text"}],"title":"maxDevicePitchAngle","navigatorTitle":[{"kind":"identifier","text":"maxDevicePitchAngle"}],"externalID":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureQualityAttributeThresholds(py)maxDevicePitchAngle","symbolKind":"property"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds/maxDevicePitchAngle":{"navigatorTitle":[{"text":"maxDevicePitchAngle","kind":"identifier"}],"abstract":[{"text":"Maximal pitch angle of the device.","type":"text"},{"text":" ","type":"text"},{"text":"Valid closed interval of angle values is from 0.0 to 90.0 degrees.","type":"text"}],"type":"topic","title":"maxDevicePitchAngle","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"identifier"},{"text":": ","kind":"text"},{"text":"WrappedFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds\/maxdevicepitchangle","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds\/maxDevicePitchAngle","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureQualityAttributeThresholds":{"navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocapturequalityattributethresholds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/WrappedFloat":{"title":"WrappedFloat","role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/wrappedfloat","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"maxDevicePitchAngle","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"maxDevicePitchAngle"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTWrappedFloat","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/WrappedFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"maxDevicePitchAngle"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"maxDevicePitchAngle","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds~1maxDevicePitchAngle\/title"},{"value":[{"text":"maxDevicePitchAngle","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds~1maxDevicePitchAngle\/fragments"},{"value":"DOTFLFaceAutoCaptureQualityAttributeThresholds","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"value":"DOTWrappedFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/title"},{"value":[{"kind":"identifier","text":"DOTWrappedFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/fragments"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1WrappedFloat\/navigatorTitle"}]}]}