{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/headposequery\/init(evaluateroll:evaluateyaw:evaluatepitch:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/headposequery\/init(evaluateroll:evaluateyaw:evaluatepitch:)"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init(evaluateRoll:evaluateYaw:evaluatePitch:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"evaluateRoll"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"evaluateYaw","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":" = false, "},{"text":"evaluatePitch","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" = false)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"evaluateRoll"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluateYaw","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"evaluatePitch"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery(im)initWithEvaluateRoll:evaluateYaw:evaluatePitch:","symbolKind":"init","title":"init(evaluateRoll:evaluateYaw:evaluatePitch:)","roleHeading":"Initializer","role":"symbol"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"title":"HeadPoseQuery","abstract":[{"type":"text","text":"Head pose query specifies which head pose attributes should be evaluated."}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HeadPoseQuery"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","kind":"symbol","url":"\/documentation\/dotfacecore\/headposequery","navigatorTitle":[{"text":"HeadPoseQuery","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/init(evaluateRoll:evaluateYaw:evaluatePitch:)":{"navigatorTitle":[{"text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:","kind":"identifier"}],"title":"init(evaluateRoll:evaluateYaw:evaluatePitch:)","url":"\/documentation\/dotfacecore\/headposequery\/init(evaluateroll:evaluateyaw:evaluatepitch:)","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/init(evaluateRoll:evaluateYaw:evaluatePitch:)","type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"evaluateRoll","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":", "},{"text":"evaluateYaw","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"evaluatePitch","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"kind":"symbol","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"text":"initWithEvaluateRoll:","kind":"identifier"},{"kind":"text","text":"("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"evaluateRoll","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluateYaw:"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"evaluateYaw","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePitch:"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"evaluatePitch"},{"kind":"text","text":";"}]}]}},{"value":"DOTFHeadPoseQuery","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init(evaluateRoll:evaluateYaw:evaluatePitch:)\/title","value":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1init(evaluateRoll:evaluateYaw:evaluatePitch:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithEvaluateRoll:evaluateYaw:evaluatePitch:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}