{"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","kind":"typeIdentifier","text":"Libraries"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?)"}],"modules":[{"name":"DotFaceLite"}],"externalID":"s:7DotCore0A3SdkC13ConfigurationC12licenseBytes9libraries24transactionCountingTokenAE10Foundation4DataV_AA9LibrariesCSSSgtcfc","roleHeading":"Initializer","role":"symbol","title":"init(licenseBytes:libraries:transactionCountingToken:)","symbolKind":"init"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"licenseBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"libraries","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? = nil)"}]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration":{"title":"DotSdk.Configuration","type":"topic","abstract":[{"type":"text","text":"The "},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" configuration."}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"url":"\/documentation\/dotfacelite\/dotsdk\/configuration","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk":{"navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"type":"topic","role":"symbol","title":"DotSdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotPalm"},{"text":".","type":"text"}],"url":"\/documentation\/dotfacelite\/dotsdk","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdk/Configuration/init(licenseBytes:libraries:transactionCountingToken:)":{"url":"\/documentation\/dotfacelite\/dotsdk\/configuration\/init(licensebytes:libraries:transactioncountingtoken:)","role":"symbol","kind":"symbol","type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"licenseBytes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"libraries"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries","text":"Libraries"},{"kind":"text","text":", "},{"kind":"externalParam","text":"transactionCountingToken"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"title":"init(licenseBytes:libraries:transactionCountingToken:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdk\/Configuration\/init(licenseBytes:libraries:transactionCountingToken:)","abstract":[]},"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"abstract":[{"text":"Container for library configurations.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}],"navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"type":"topic","url":"\/documentation\/dotfacelite\/libraries","kind":"symbol","title":"Libraries","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries"},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.1"}],"url":"\/documentation\/dotfacelite","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"text":"DotSdk","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdk\/navigatorTitle","value":[{"kind":"identifier","text":"DotSdk"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title","value":"Libraries"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments","value":[{"text":"Libraries","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle","value":[{"kind":"identifier","text":"Libraries"}]}]}]}