{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isdocumentenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isdocumentenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol"]]},"metadata":{"title":"isDocumentEnabled","modules":[{"name":"DotFaceCore"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"isDocumentEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}],"required":true,"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isDocumentEnabled"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled","type":"topic","title":"isDocumentEnabled","role":"symbol","url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol\/isdocumentenabled","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"abstract":[],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotSdkLicenseProxyProtocol":{"url":"\/documentation\/dotfacecore\/dotsdklicenseproxyprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","kind":"symbol","role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotSdkLicenseProxyProtocol","navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"isDocumentEnabled"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"isDocumentEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"isDocumentEnabled","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title","op":"replace","value":"isDocumentEnabled"},{"value":[{"kind":"identifier","text":"isDocumentEnabled"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}