{"metadata":{"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"fullFrontalImage","navigatorTitle":[{"kind":"identifier","text":"fullFrontalImage"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)Face(py)fullFrontalImage","fragments":[{"kind":"identifier","text":"fullFrontalImage"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"ICAO full frontal face image. This is evaluated only if it is specified in "},{"type":"text","text":"FaceDetectionQuery"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImage","text":"DOTImage","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image"},{"text":" * ","kind":"text"},{"text":"fullFrontalImage","kind":"identifier"},{"text":";","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/face\/fullfrontalimage"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/fullFrontalImage","interfaceLanguage":"occ"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/Face":{"kind":"symbol","abstract":[{"type":"text","text":"Detected face in the image."}],"url":"\/documentation\/dotfacecore\/face","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face","type":"topic","role":"symbol","title":"Face","fragments":[{"text":"Face","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/Face/fullFrontalImage":{"abstract":[{"text":"ICAO full frontal face image. This is evaluated only if it is specified in ","type":"text"},{"text":"FaceDetectionQuery","type":"text"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/face\/fullfrontalimage","fragments":[{"text":"fullFrontalImage","kind":"identifier"}],"kind":"symbol","title":"fullFrontalImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Face\/fullFrontalImage","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/Image":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Image"}],"title":"Image","navigatorTitle":[{"kind":"identifier","text":"Image"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/Image","url":"\/documentation\/dotfacecore\/image","role":"symbol","type":"topic","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/title","value":"DOTImage","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/fragments","value":[{"text":"DOTImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1Image\/navigatorTitle","value":[{"kind":"identifier","text":"DOTImage"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}