{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"kind":"symbol","metadata":{"role":"symbol","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration(im)init","symbolKind":"method","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration/init":{"title":"init","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration\/init","kind":"symbol","abstract":[],"url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration\/init","type":"topic","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/DotFaceEyeGazeLivenessModuleConfiguration":{"role":"symbol","kind":"symbol","abstract":[{"text":"Face eye gaze liveness module.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceEyeGazeLivenessModuleConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceeyegazelivenessmoduleconfiguration","title":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotFaceEyeGazeLivenessModuleConfiguration"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/title","op":"replace","value":"DotFaceEyeGazeLivenessModuleConfiguration"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments","op":"replace","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle","op":"replace","value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}