{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone"]]},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hasAllChecksumsValid","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"role":"symbol","externalID":"s:11DotDocument22Td2MachineReadableZoneC20hasAllChecksumsValidSbvp","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","extendedModule":"DotDocument","title":"hasAllChecksumsValid","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hasAllChecksumsValid"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/td2machinereadablezone\/hasallchecksumsvalid"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hasAllChecksumsValid","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone":{"title":"Td2MachineReadableZone","navigatorTitle":[{"text":"Td2MachineReadableZone","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td2MachineReadableZone"}],"type":"topic","role":"symbol","url":"\/documentation\/dotdocument\/td2machinereadablezone","abstract":[{"text":"Result of MRZ reading of TD2.","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.3.0"}],"title":"DotDocument","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzReader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzReader","abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"title":"MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/mrzreader","type":"topic"},"doc://com.innovatrics.dot.document/documentation/DotDocument/Td2MachineReadableZone/hasAllChecksumsValid":{"role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/Td2MachineReadableZone\/hasAllChecksumsValid","title":"hasAllChecksumsValid","type":"topic","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hasAllChecksumsValid","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dotdocument\/td2machinereadablezone\/hasallchecksumsvalid"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/title","value":"DOTTd2MachineReadableZone"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1Td2MachineReadableZone\/fragments","value":[{"text":"DOTTd2MachineReadableZone","kind":"identifier"}],"op":"replace"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzReader\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}