{"sections":[],"metadata":{"role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImageFactory"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Class","symbolKind":"class","title":"BgrRawImageFactory"},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"anchor":"Type-Methods","title":"Type Methods"}],"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"identifiers":["doc:\/\/DotDocument\/objc(pl)NSObject","doc:\/\/DotDocument\/s7CVarArgP","doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/SQ","doc:\/\/DotDocument\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"type":"text","text":" from iOS native image types."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTBgrRawImageFactory) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgrRawImageFactory"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/bgrrawimagefactory"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/bgrrawimagefactory"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory"},"references":{"doc://DotDocument/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s28CustomDebugStringConvertibleP"},"doc://DotDocument/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(pl)NSObject"},"doc://DotDocument/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SH"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","abstract":[{"type":"text","text":"version: 8.17.1"}],"kind":"symbol","role":"collection","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/BgrRawImageFactory/create(cgImage:)":{"url":"\/documentation\/dotdocument\/bgrrawimagefactory\/create(cgimage:)","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(cgImage:)","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" object.","type":"text"}],"type":"topic","title":"create(cgImage:)","role":"symbol","navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/BgrRawImageFactory/create(ciImage:ciContext:)":{"navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CIImage","type":"codeVoice"},{"text":" as a ","type":"text"},{"code":"BgrRawImage","type":"codeVoice"},{"text":" object.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/bgrrawimagefactory\/create(ciimage:cicontext:)","title":"create(ciImage:ciContext:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(ciImage:ciContext:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"text":", ","kind":"text"},{"text":"ciContext","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier"}]},"doc://DotDocument/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s7CVarArgP"},"doc://DotDocument/documentation/DotDocument/BgrRawImageFactory":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotdocument\/bgrrawimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"type":"topic","role":"symbol","title":"BgrRawImageFactory","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory","navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}]},"doc://DotDocument/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/DotDocument\/objc(cs)NSObject"},"doc://DotDocument/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/SQ"},"doc://DotDocument/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTBgrRawImageFactory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(cgImage:)","doc:\/\/DotDocument\/documentation\/DotDocument\/BgrRawImageFactory\/create(ciImage:ciContext:)"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/DotDocument\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTBgrRawImageFactory","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory~1create(cgImage:)\/title","value":"createWithCgImage:"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory~1create(cgImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BgrRawImageFactory\/navigatorTitle","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}