{"relationshipsSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","doc:\/\/DotDocument\/s23CustomStringConvertibleP","doc:\/\/DotDocument\/s5ErrorP","doc:\/\/DotDocument\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"metadata":{"externalID":"s:11DotDocument0B21AutoCaptureControllerC5ErrorO","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}],"symbolKind":"enum","modules":[{"name":"DotDocument"}],"roleHeading":"Enumeration","title":"DocumentAutoCaptureController.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]}],"kind":"declarations"}],"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/processSampleFailed(internalError:)"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/errorMessage","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/internalError"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/CustomStringConvertible-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/DotSdkError-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/Error-Implementations","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/LocalizedError-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/processSampleFailed(internalError:)":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"processSampleFailed"},{"kind":"text","text":"("},{"kind":"externalParam","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"kind":"symbol","abstract":[],"type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/processSampleFailed(internalError:)","title":"DocumentAutoCaptureController.Error.processSampleFailed(internalError:)","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/processsamplefailed(internalerror:)"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/Error-Implementations":{"type":"topic","title":"Error Implementations","role":"collectionGroup","kind":"article","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/Error-Implementations","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/error-implementations","abstract":[]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/internalError":{"title":"internalError","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/internalerror","role":"symbol","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/internalError","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/CustomStringConvertible-Implementations":{"type":"topic","role":"collectionGroup","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","kind":"article","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/customstringconvertible-implementations"},"doc://DotDocument/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/DotDocument\/s8SendableP"},"doc://DotDocument/documentation/DotDocument/DotSdkError":{"kind":"symbol","url":"\/documentation\/dotdocument\/dotsdkerror","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkError","navigatorTitle":[{"kind":"identifier","text":"DotSdkError"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkError"}],"title":"DotSdkError","abstract":[],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/LocalizedError-Implementations":{"title":"LocalizedError Implementations","type":"topic","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/LocalizedError-Implementations","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/localizederror-implementations","kind":"article"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/10Foundation14LocalizedErrorP":{"identifier":"doc:\/\/DotDocument\/10Foundation14LocalizedErrorP","title":"Foundation.LocalizedError","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/DotSdkError-Implementations":{"title":"DotSdkError Implementations","role":"collectionGroup","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/DotSdkError-Implementations","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/dotsdkerror-implementations","kind":"article","abstract":[]},"doc://DotDocument/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotDocument\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","url":"\/documentation\/dotdocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"kind":"symbol"},"doc://DotDocument/s5ErrorP":{"identifier":"doc:\/\/DotDocument\/s5ErrorP","type":"unresolvable","title":"Swift.Error"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error/errorMessage":{"kind":"symbol","title":"errorMessage","role":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error\/errormessage","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorMessage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error\/errorMessage"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Error":{"type":"topic","title":"DocumentAutoCaptureController.Error","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/error","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]}]}]}