{"seeAlsoSections":[{"title":"NFC reading","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"role":"symbol","title":"NfcTravelDocumentReaderError","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"symbolKind":"class","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcTravelDocumentReaderError","modules":[{"name":"DotNfc"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"abstract":[{"type":"text","text":"NFC reading error."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/10Foundation14LocalizedErrorP","doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP","doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.nfc\/SQ","doc:\/\/com.innovatrics.dot.nfc\/s5ErrorP","doc:\/\/com.innovatrics.dot.nfc\/SH","doc:\/\/com.innovatrics.dot.nfc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorDescription-7zt98","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorType"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/Error-Implementations","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/LocalizedError-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreadererror"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTNNfcTravelDocumentReaderError) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","abstract":[{"type":"text","text":"version: 5.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://com.innovatrics.dot.nfc/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(pl)NSObject"},"doc://com.innovatrics.dot.nfc/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SQ"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/Error-Implementations":{"role":"collectionGroup","title":"Error Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/Error-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/error-implementations"},"doc://com.innovatrics.dot.nfc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s8SendableP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/errorDescription-7zt98":{"role":"symbol","title":"errorDescription","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorDescription"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorDescription-7zt98","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorDescription"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/errordescription-7zt98"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/description","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"description"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/description"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"role":"symbol","title":"NfcKey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"abstract":[{"type":"text","text":"NFC key created from document number, date of expiry and date of birth."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"url":"\/documentation\/dotnfc\/nfckey"},"doc://com.innovatrics.dot.nfc/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/TravelDocument":{"role":"symbol","title":"TravelDocument","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}],"abstract":[{"type":"text","text":"Result of NFC reading."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"url":"\/documentation\/dotnfc\/traveldocument"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError":{"role":"symbol","title":"NfcTravelDocumentReaderError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"abstract":[{"type":"text","text":"NFC reading error."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReaderError"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"role":"symbol","title":"NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.nfc\/SH"},"doc://com.innovatrics.dot.nfc/10Foundation14LocalizedErrorP":{"type":"unresolvable","title":"Foundation.LocalizedError","identifier":"doc:\/\/com.innovatrics.dot.nfc\/10Foundation14LocalizedErrorP"},"doc://com.innovatrics.dot.nfc/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s7CVarArgP"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/errorType":{"role":"symbol","title":"errorType","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"errorType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NfcTravelDocumentReaderErrorType","preciseIdentifier":"c:@M@DotNfc@E@DOTNNfcTravelDocumentReaderErrorType"}],"abstract":[{"type":"text","text":"Error type."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"errorType"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/errortype"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReaderError/LocalizedError-Implementations":{"role":"collectionGroup","title":"LocalizedError Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/LocalizedError-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreadererror\/localizederror-implementations"},"doc://com.innovatrics.dot.nfc/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s28CustomDebugStringConvertibleP"},"doc://com.innovatrics.dot.nfc/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.nfc/s5ErrorP":{"type":"unresolvable","title":"Swift.Error","identifier":"doc:\/\/com.innovatrics.dot.nfc\/s5ErrorP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"DOTNNfcTravelDocumentReaderError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/description","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorDescription-7zt98","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReaderError\/errorType"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.innovatrics.dot.nfc\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"NFC reading","identifiers":["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/TravelDocument"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderError"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1errorDescription-7zt98\/title","value":"errorDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1errorDescription-7zt98\/fragments","value":[{"kind":"identifier","text":"errorDescription"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1description\/title","value":"description"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1description\/fragments","value":[{"kind":"identifier","text":"description"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"kind":"identifier","text":"DOTNNfcKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1TravelDocument\/fragments","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError\/title","value":"DOTNNfcTravelDocumentReaderError"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReaderError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1errorType\/title","value":"errorType"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReaderError~1errorType\/fragments","value":[{"kind":"identifier","text":"errorType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}