{"metadata":{"externalID":"c:@CM@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController(im)viewWillDisappear:","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"viewWillDisappear(_:)","extendedModule":"DotFaceCore","navigatorTitle":[{"text":"viewWillDisappear:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","modules":[{"name":"DotFaceCore"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/viewwilldisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/viewwilldisappear(_:)"]}],"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/viewWillDisappear(_:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"kind":"attribute","text":"MainActor","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/viewWillDisappear(_:)":{"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/viewWillDisappear(_:)","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/viewwilldisappear(_:)","type":"topic","role":"symbol","kind":"symbol","title":"viewWillDisappear(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillDisappear"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewWillDisappear:"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"title":"BaseFaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewWillDisappear:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"void","preciseIdentifier":"c:v","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"viewWillDisappear:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"animated","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"viewWillDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1viewWillDisappear(_:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillDisappear:"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1viewWillDisappear(_:)\/fragments","op":"replace"},{"value":"DOTFBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}