{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId"]]},"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"externalID":"c:@M@DotCore@E@DotFingersModuleId@DotFingersModuleIdDetection","title":"DotFingersModuleId.detection","symbolKind":"case","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Case"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId\/detection"},"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotfingersmoduleid\/detection"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersModuleId/detection":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"detection","kind":"identifier"}],"kind":"symbol","title":"DotFingersModuleId.detection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId\/detection","navigatorTitle":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotfingersmoduleid\/detection","type":"topic","role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersModuleId":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"title":"DotFingersModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotfacelite\/dotfingersmoduleid","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId","type":"topic","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"DotFingersModuleIdDetection","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"DotFingersModuleIdDetection","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DotFingersModuleIdDetection","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId~1detection\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersModuleIdDetection"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId~1detection\/fragments","op":"replace"},{"value":"DotFingersModuleId","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DotFingersModuleId"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/navigatorTitle"}]}]}