{"topicSections":[{"generated":true,"identifiers":["doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId\/!=(_:_:)"],"anchor":"Operators","title":"Operators"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"Equatable Implementations","roleHeading":"API Collection","modules":[{"name":"DotFaceLite"}],"role":"collectionGroup"},"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/dotfingersmoduleid\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotFingersModuleId":{"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersModuleId","kind":"identifier"}],"title":"DotFingersModuleId","role":"symbol","abstract":[{"type":"codeVoice","code":"DotFingers"},{"type":"text","text":" feature module identifier."}],"url":"\/documentation\/dotfacelite\/dotfingersmoduleid","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId","type":"topic","navigatorTitle":[{"text":"DotFingersModuleId","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotFingersModuleId/!=(_:_:)":{"title":"!=(_:_:)","url":"\/documentation\/dotfacelite\/dotfingersmoduleid\/!=(_:_:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotFingersModuleId\/!=(_:_:)","abstract":[],"kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","role":"collection","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/title","value":"DotFingersModuleId"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/fragments","value":[{"text":"DotFingersModuleId","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotFingersModuleId\/navigatorTitle","value":[{"text":"DotFingersModuleId","kind":"identifier"}]}]}]}