{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration","kind":"typeIdentifier","text":"DotFaceExpressionNeutralModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"expressionNeutral"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/expressionNeutral","interfaceLanguage":"occ"},"metadata":{"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"expressionNeutral","kind":"identifier"}],"fragments":[{"text":"expressionNeutral","kind":"identifier"}],"title":"expressionNeutral","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)expressionNeutral"},"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/expressionneutral"]}],"references":{"doc://DotDocument/documentation/DotDocument/DotFaceExpressionNeutralModuleConfiguration":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceExpressionNeutralModuleConfiguration","abstract":[{"text":"Face expression neutral module.","type":"text"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotdocument\/dotfaceexpressionneutralmoduleconfiguration"},"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","type":"topic","abstract":[{"type":"text","text":"version: 9.2.2"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","kind":"symbol","role":"symbol","title":"DotFaceLibraryConfigurationModules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"abstract":[{"text":"Face library module configuration.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules/expressionNeutral":{"url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/expressionneutral","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/expressionNeutral","kind":"symbol","role":"symbol","title":"expressionNeutral","fragments":[{"kind":"identifier","text":"expressionNeutral"}],"abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DotFaceExpressionNeutralModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/title","op":"replace"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/fragments","op":"replace"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle","op":"replace"}]}]}