{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/eyegazeliveness"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceEyeGazeLivenessModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","text":"DotFaceEyeGazeLivenessModuleConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"eyeGazeLiveness"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"eyeGazeLiveness","kind":"identifier"}],"fragments":[{"text":"eyeGazeLiveness","kind":"identifier"}],"title":"eyeGazeLiveness","modules":[{"name":"DotDocument"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)eyeGazeLiveness"},"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","interfaceLanguage":"occ"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.4.0","type":"text"}],"role":"collection","title":"DotDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules","fragments":[{"kind":"identifier","text":"DotFaceLibraryConfigurationModules"}],"kind":"symbol","title":"DotFaceLibraryConfigurationModules","role":"symbol","abstract":[{"text":"Face library module configuration.","type":"text"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules/eyeGazeLiveness":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/eyeGazeLiveness","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/eyegazeliveness","fragments":[{"text":"eyeGazeLiveness","kind":"identifier"}],"kind":"symbol","title":"eyeGazeLiveness","role":"symbol","abstract":[],"type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceEyeGazeLivenessModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Face eye gaze liveness module."}],"role":"symbol","title":"DotFaceEyeGazeLivenessModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceEyeGazeLivenessModuleConfiguration","url":"\/documentation\/dotdocument\/dotfaceeyegazelivenessmoduleconfiguration","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotFaceEyeGazeLivenessModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/title"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceEyeGazeLivenessModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceEyeGazeLivenessModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}