{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/passiveliveness"]}],"metadata":{"role":"symbol","modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)passiveLiveness","roleHeading":"Instance Property","title":"passiveLiveness","symbolKind":"property","navigatorTitle":[{"text":"passiveLiveness","kind":"identifier"}],"fragments":[{"text":"passiveLiveness","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/passiveLiveness","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFacePassiveLivenessModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"passiveLiveness","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","title":"DotFaceLibraryConfigurationModules","kind":"symbol","type":"topic","abstract":[{"text":"Face library module configuration.","type":"text"}],"fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules"},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules/passiveLiveness":{"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/passiveliveness","title":"passiveLiveness","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/passiveLiveness","fragments":[{"kind":"identifier","text":"passiveLiveness"}],"kind":"symbol","abstract":[]},"doc://DotDocument/documentation/DotDocument/DotFacePassiveLivenessModuleConfiguration":{"role":"symbol","type":"topic","url":"\/documentation\/dotdocument\/dotfacepassivelivenessmoduleconfiguration","title":"DotFacePassiveLivenessModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFacePassiveLivenessModuleConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFacePassiveLivenessModuleConfiguration"}],"kind":"symbol","abstract":[{"type":"text","text":"Face passive liveness module."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotFacePassiveLivenessModuleConfiguration","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/title"},{"op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/fragments"},{"op":"replace","value":[{"text":"DotFacePassiveLivenessModuleConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFacePassiveLivenessModuleConfiguration\/navigatorTitle"}]}]}