{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotFaceVerificationModuleConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration"},{"text":" * ","kind":"text"},{"text":"verification","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotFaceLibraryConfigurationModules(py)verification","navigatorTitle":[{"kind":"identifier","text":"verification"}],"title":"verification","fragments":[{"kind":"identifier","text":"verification"}],"roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/verification"]}],"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/verification","interfaceLanguage":"occ"},"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules/verification":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules\/verification","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules\/verification","title":"verification","kind":"symbol","abstract":[],"role":"symbol","fragments":[{"text":"verification","kind":"identifier"}],"type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/DotFaceLibraryConfigurationModules":{"role":"symbol","url":"\/documentation\/dotdocument\/dotfacelibraryconfigurationmodules","title":"DotFaceLibraryConfigurationModules","fragments":[{"text":"DotFaceLibraryConfigurationModules","kind":"identifier"}],"abstract":[{"text":"Face library module configuration.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceLibraryConfigurationModules","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DotFaceVerificationModuleConfiguration":{"url":"\/documentation\/dotdocument\/dotfaceverificationmoduleconfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFaceVerificationModuleConfiguration","title":"DotFaceVerificationModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"DotFaceVerificationModuleConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Face verification module."}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"value":"DotFaceVerificationModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DotFaceVerificationModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFaceVerificationModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}