{"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"externalID":"s:7DotCore0A32FaceDetectionModuleConfigurationC4FastCAEycfc","symbolKind":"init","role":"symbol","roleHeading":"Initializer","modules":[{"name":"DotNfc"}],"title":"init()"},"sections":[],"variants":[{"paths":["\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/fast\/init()"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast\/init()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","role":"collection","url":"\/documentation\/dotnfc","title":"DotNfc"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Fast/init()":{"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"title":"init()","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/fast\/init()","abstract":[],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast\/init()","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration":{"title":"DotFaceDetectionModuleConfiguration","abstract":[{"text":"Face detection module configuration.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration","navigatorTitle":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/DotFaceDetectionModuleConfiguration/Fast":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotFaceDetectionModuleConfiguration\/Fast","navigatorTitle":[{"text":"Fast","kind":"identifier"}],"type":"topic","role":"symbol","abstract":[{"text":"Face detection fast module.","type":"text"}],"kind":"symbol","title":"DotFaceDetectionModuleConfiguration.Fast","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Fast","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dotfacedetectionmoduleconfiguration\/fast"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/title","value":"DotFaceDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/fragments","value":[{"text":"DotFaceDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotFaceDetectionModuleConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DotFaceDetectionModuleConfiguration"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}