{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/defaultMaxEdgeLengthToImageShorterSideRatioThreshold"},"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooLargeValidator(cpy)defaultMaxEdgeLengthToImageShorterSideRatioThreshold","roleHeading":"Type Property","title":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","symbolKind":"property"},"abstract":[{"type":"text","text":"Default threshold."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/defaultmaxedgelengthtoimageshortersideratiothreshold"]},{"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/defaultmaxedgelengthtoimageshortersideratiothreshold"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","kind":"symbol","title":"SizeTooLargeValidator","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SizeTooLargeValidator"}],"type":"topic","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"kind":"symbol","title":"PalmAutoCaptureController","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/defaultMaxEdgeLengthToImageShorterSideRatioThreshold":{"title":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/defaultmaxedgelengthtoimageshortersideratiothreshold","type":"topic","navigatorTitle":[{"text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/defaultMaxEdgeLengthToImageShorterSideRatioThreshold","abstract":[{"type":"text","text":"Default threshold."}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:d","text":"double"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","value":"DOTPSizeTooLargeValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace"},{"value":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1defaultMaxEdgeLengthToImageShorterSideRatioThreshold\/title"},{"value":[{"text":"defaultMaxEdgeLengthToImageShorterSideRatioThreshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1defaultMaxEdgeLengthToImageShorterSideRatioThreshold\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}