{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator"]]},"kind":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/dependencyidentifiers"]},{"paths":["\/documentation\/dotpalmcore\/sizetoolargevalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/dependencyIdentifiers"},"metadata":{"title":"dependencyIdentifiers","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPSizeTooLargeValidator(py)dependencyIdentifiers","symbolKind":"property","modules":[{"name":"DotPalmCore"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"type":"topic","abstract":[{"type":"text","text":"version: 8.16.0"}],"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator/dependencyIdentifiers":{"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator\/dependencyidentifiers","title":"dependencyIdentifiers","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator\/dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":">"}],"kind":"symbol","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"role":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}],"title":"SizeTooLargeValidator","abstract":[{"text":"Validate whether the size of the detected palm is too large.","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"kind":"symbol","title":"PalmAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCaptureController","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"dependencyIdentifiers","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"dependencyIdentifiers","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1dependencyIdentifiers\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","value":"DOTPSizeTooLargeValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments","op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}]},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}