{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/camera"},"metadata":{"symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMagnifEyeLivenessConfiguration(py)camera","roleHeading":"Instance Property","fragments":[{"kind":"identifier","text":"camera"}],"navigatorTitle":[{"kind":"identifier","text":"camera"}],"role":"symbol","title":"camera"},"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"]]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"DOTCameraConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"camera"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"\\Endcode"}]}]}],"variants":[{"paths":["\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/camera"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/CameraConfiguration":{"url":"\/documentation\/dotfacecore\/cameraconfiguration","title":"CameraConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraConfiguration","kind":"identifier"}],"navigatorTitle":[{"text":"CameraConfiguration","kind":"identifier"}],"abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CameraConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}],"type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration/camera":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration\/camera","abstract":[{"type":"text","text":"Configuration for components utilizing a camera."},{"type":"text","text":" "},{"type":"text","text":"Default is:"},{"type":"text","text":" "},{"type":"text","text":"\\code"},{"type":"text","text":" "},{"type":"text","text":".init(cameraFacing: .front)"}],"kind":"symbol","fragments":[{"kind":"identifier","text":"camera"}],"title":"camera","type":"topic","url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration\/camera","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFMagnifEyeLivenessConfiguration":{"role":"symbol","url":"\/documentation\/dotfacecore\/dotfmagnifeyelivenessconfiguration","abstract":[{"type":"text","text":"Configuration options for the UI MagnifEye Liveness component."}],"kind":"symbol","title":"DOTFMagnifEyeLivenessConfiguration","fragments":[{"kind":"identifier","text":"DOTFMagnifEyeLivenessConfiguration"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFMagnifEyeLivenessConfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CameraConfiguration\/navigatorTitle"}]}]}