{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(im)initWithModules:","modules":[{"name":"DotNfc"}],"symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"title":"init(modules:)","role":"symbol"},"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/init(modules:)"]}],"kind":"symbol","sections":[],"references":{"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/init(modules:)":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithModules:"}],"title":"init(modules:)","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier","text":"Modules"},{"kind":"text","text":")"}],"role":"symbol","url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/init(modules:)"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfigurationModules":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules","fragments":[{"text":"DotPalmLibraryConfigurationModules","kind":"identifier"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/dotpalmlibraryconfigurationmodules","title":"DotPalmLibraryConfigurationModules","abstract":[{"text":"Palm library module configuration.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration\/modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration\/Modules-swift.class","abstract":[{"text":"Palm library module configuration.","type":"text"}],"kind":"symbol","title":"DotPalmLibraryConfiguration.Modules","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotPalmLibraryConfiguration":{"url":"\/documentation\/dotnfc\/dotpalmlibraryconfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfiguration","title":"DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Palm library configuration."}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"type":"text","text":"version: 9.1.1"}],"type":"topic","url":"\/documentation\/dotnfc","role":"collection","kind":"symbol","title":"DotNfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"initWithModules:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"DotPalmLibraryConfigurationModules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modules"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration~1init(modules:)\/title","value":"initWithModules:","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration~1init(modules:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithModules:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"}]}]}