{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minconfidence:error:"]}],"metadata":{"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder(im)minConfidence:error:","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"minConfidence:error:","kind":"identifier"}],"fragments":[{"text":"- ","kind":"text"},{"text":"minConfidence:error:","kind":"identifier"}],"title":"minConfidence:error:"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minConfidence:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"minConfidence","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"symbol","title":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","role":"symbol","fragments":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder"},"doc://DotDocument/documentation/DotDocument/WrappedDouble":{"type":"topic","title":"WrappedDouble","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"navigatorTitle":[{"text":"WrappedDouble","kind":"identifier"}],"url":"\/documentation\/dotdocument\/wrappeddouble","role":"symbol","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/WrappedDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedDouble","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder/minConfidence:error:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"minConfidence:error:"}],"title":"minConfidence:error:","navigatorTitle":[{"kind":"identifier","text":"minConfidence:error:"}],"abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentAutoCaptureQualityAttributeThresholdsBuilder\/minConfidence:error:","url":"\/documentation\/dotdocument\/dotddocumentautocapturequalityattributethresholdsbuilder\/minconfidence:error:","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1WrappedDouble\/navigatorTitle","value":[{"text":"DOTWrappedDouble","kind":"identifier"}]}]}]}