{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration\/common"},"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"common","kind":"identifier"}],"navigatorTitle":[{"text":"common","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"symbolKind":"property","title":"common","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBasePalmAutoCaptureConfiguration(py)common"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration\/common"]}],"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"DOTCommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration"},{"text":" * ","kind":"text"},{"text":"common","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration"]]},"abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"text":".init()","type":"text"},{"text":".","type":"text"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore/CommonConfiguration":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CommonConfiguration","url":"\/documentation\/dotpalmcore\/commonconfiguration","abstract":[{"text":"Common configuration for all components.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 9.0.2"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration/common":{"title":"common","abstract":[{"type":"text","text":"Common configuration for all components. Default is "},{"type":"text","text":".init()"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration\/common","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration\/common","role":"symbol","fragments":[{"kind":"identifier","text":"common"}]},"doc://DotPalmCore/documentation/DotPalmCore/DOTPBasePalmAutoCaptureConfiguration":{"title":"DOTPBasePalmAutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the palm auto capture process."}],"role":"symbol","kind":"symbol","fragments":[{"text":"DOTPBasePalmAutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DOTPBasePalmAutoCaptureConfiguration","url":"\/documentation\/dotpalmcore\/dotpbasepalmautocaptureconfiguration"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CommonConfiguration\/navigatorTitle","value":[{"kind":"identifier","text":"DOTCommonConfiguration"}]}]}]}