{"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","text":"Configuration"}],"modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureViewController(py)baseConfiguration","title":"baseConfiguration","symbolKind":"property","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"attribute","text":"@"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","kind":"typeIdentifier","text":"Configuration"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/baseconfiguration"]},{"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/baseconfiguration"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/baseConfiguration"},"abstract":[{"type":"text","text":"Current configuration."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFBaseFaceAutoCaptureConfiguration":{"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureConfiguration"}],"title":"DOTFBaseFaceAutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/dotfbasefaceautocaptureconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","type":"topic","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/baseConfiguration":{"title":"baseConfiguration","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/baseConfiguration","navigatorTitle":[{"text":"baseConfiguration","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/baseconfiguration","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","kind":"typeIdentifier","text":"Configuration"}],"abstract":[{"type":"text","text":"Current configuration."}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","title":"BaseFaceAutoCaptureViewController.Configuration","kind":"symbol","type":"topic","abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","title":"BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"baseConfiguration","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"baseConfiguration"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFBaseFaceAutoCaptureConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFBaseFaceAutoCaptureConfiguration","kind":"typeIdentifier","text":"DOTFBaseFaceAutoCaptureConfiguration"},{"kind":"text","text":" * "},{"kind":"identifier","text":"baseConfiguration"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"baseConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1baseConfiguration\/title"},{"value":[{"kind":"identifier","text":"baseConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController~1baseConfiguration\/fragments"},{"value":"DOTFBaseFaceAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFBaseFaceAutoCaptureViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}