{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isdocumentenabled"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isdocumentenabled"]}],"metadata":{"symbolKind":"property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isDocumentEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDocumentEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"isDocumentEnabled","modules":[{"name":"DotPalmCore"}],"required":true,"roleHeading":"Instance Property","navigatorTitle":[{"text":"isDocumentEnabled","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isDocumentEnabled":{"type":"topic","required":true,"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDocumentEnabled"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isdocumentenabled","abstract":[],"title":"isDocumentEnabled","navigatorTitle":[{"kind":"identifier","text":"isDocumentEnabled"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isDocumentEnabled"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","abstract":[],"title":"DotSdkLicenseProxyProtocol","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"isDocumentEnabled","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"isDocumentEnabled","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"isDocumentEnabled","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"isDocumentEnabled","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isDocumentEnabled\/fragments","op":"replace","value":[{"text":"isDocumentEnabled","kind":"identifier"}]},{"value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}]}]}]}