{"sections":[],"metadata":{"required":true,"title":"isFaceMatchingEnabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFaceMatchingEnabled","navigatorTitle":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotPalmCore"}]},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfacematchingenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFaceMatchingEnabled"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFaceMatchingEnabled":{"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfacematchingenabled","navigatorTitle":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFaceMatchingEnabled","abstract":[],"type":"topic","kind":"symbol","required":true,"title":"isFaceMatchingEnabled","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isFaceMatchingEnabled","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","abstract":[],"title":"DotSdkLicenseProxyProtocol","type":"topic","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isFaceMatchingEnabled","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"isFaceMatchingEnabled"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isFaceMatchingEnabled"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"isFaceMatchingEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/title","op":"replace"},{"value":[{"text":"isFaceMatchingEnabled","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFaceMatchingEnabled\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title","op":"replace","value":"DotSdkLicenseProxyProtocol"},{"op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments"}]}]}