{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfingersenabled"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfingersenabled"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"role":"symbol","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"externalID":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol(py)isFingersEnabled","title":"isFingersEnabled","roleHeading":"Instance Property","required":true,"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"isFingersEnabled"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol"]]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFingersEnabled","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"role":"collection","kind":"symbol","title":"DotPalmCore","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol/isFingersEnabled":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isFingersEnabled"}],"title":"isFingersEnabled","type":"topic","abstract":[],"url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol\/isfingersenabled","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isFingersEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol\/isFingersEnabled"},"doc://DotPalmCore/documentation/DotPalmCore/DotSdkLicenseProxyProtocol":{"role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"title":"DotSdkLicenseProxyProtocol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotpalmcore\/dotsdklicenseproxyprotocol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"isFingersEnabled","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"isFingersEnabled"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"isFingersEnabled"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"isFingersEnabled","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/title"},{"op":"replace","value":[{"kind":"identifier","text":"isFingersEnabled"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol~1isFingersEnabled\/fragments"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DotSdkLicenseProxyProtocol\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}