{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findQualityAttributeById"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"qualityAttributeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTQualityAttributeId","text":"QualityAttributeId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute","text":"QualityAttribute"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityprovider\/findqualityattributebyid(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityprovider\/findqualityattributebyid(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/findQualityAttributeById(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"findQualityAttributeById:"}],"role":"symbol","title":"findQualityAttributeById(_:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findQualityAttributeById"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTQualityAttributeId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(pl)DOTQualityProvider(im)findQualityAttributeById:","required":true,"modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider":{"role":"symbol","title":"QualityProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}],"url":"\/documentation\/dotfacecore\/qualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider/findQualityAttributeById(_:)":{"navigatorTitle":[{"kind":"identifier","text":"findQualityAttributeById:"}],"role":"symbol","title":"findQualityAttributeById(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"findQualityAttributeById"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTQualityAttributeId"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider\/findQualityAttributeById(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/dotfacecore\/qualityprovider\/findqualityattributebyid(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"findQualityAttributeById:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findQualityAttributeById:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTQualityAttribute","text":"DOTQualityAttribute"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"findQualityAttributeById:"},{"kind":"text","text":"("},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","preciseIdentifier":"c:@M@DotFaceCore@E@DOTQualityAttributeId","text":"DOTQualityAttributeId"},{"kind":"text","text":")"},{"kind":"internalParam","text":"qualityAttributeId"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/title","value":"DOTQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1findQualityAttributeById(_:)\/title","value":"findQualityAttributeById:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider~1findQualityAttributeById(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"findQualityAttributeById:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}