{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateRunning(im)initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","navigatorTitle":[{"text":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithPreview:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview","text":"DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview"},{"text":" *) ","kind":"text"},{"text":"preview","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"phase:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)DOTFGFingersAutoCapturePhaseWrapped","text":"DOTFGFingersAutoCapturePhaseWrapped","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"phase","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"detection:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureDetection","text":"DOTFGFingersAutoCaptureDetection","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection"},{"text":" *) ","kind":"text"},{"text":"detection","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"selectedFingerTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTFGFingerTypeWrapped *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"selectedFingerTypes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"confirmedFingerTypes:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<DOTFGFingerTypeWrapped *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"confirmedFingerTypes","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"result:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult","text":"DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/initwithpreview:phase:detection:selectedfingertypes:confirmedfingertypes:result:"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","title":"FingersAutoCaptureResult","role":"symbol","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"type":"topic","title":"FingersAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureDetection":{"url":"\/documentation\/dotfingerscore\/fingersautocapturedetection","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureDetection","title":"FingersAutoCaptureDetection","role":"symbol","abstract":[{"text":"The result of processing video frame during the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureDetection"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning":{"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFGFingersAutoCaptureUiStateRunning","type":"topic","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"type":"text","text":" method is called and before the process finishes."}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning/initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:":{"fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:"}],"navigatorTitle":[{"kind":"identifier","text":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:"}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/initwithpreview:phase:detection:selectedfingertypes:confirmedfingertypes:result:","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","title":"initWithPreview:phase:detection:selectedFingerTypes:confirmedFingerTypes:result:","role":"symbol","type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title","value":"DOTFGFingersAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title","value":"DOTFGFingersAutoCapturePreview"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments","value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/title","value":"DOTFGFingersAutoCaptureDetection"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/fragments","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureDetection\/navigatorTitle","value":[{"text":"DOTFGFingersAutoCaptureDetection","kind":"identifier"}]}]}]}