{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/preview"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/preview"]}],"abstract":[{"type":"text","text":"Preview information."}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateRunning(py)preview","symbolKind":"property","fragments":[{"text":"preview","kind":"identifier"}],"title":"preview","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"preview","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","text":"DOTFGFingersAutoCapturePreview","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCapturePreview"},{"text":" * ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning/preview":{"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/preview","fragments":[{"kind":"identifier","text":"preview"}],"type":"topic","title":"preview","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/preview","abstract":[{"text":"Preview information.","type":"text"}],"role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning":{"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFGFingersAutoCaptureUiStateRunning","type":"topic","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"type":"text","text":" method is called and before the process finishes."}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCapturePreview":{"type":"topic","title":"FingersAutoCapturePreview","abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"url":"\/documentation\/dotfingerscore\/fingersautocapturepreview","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCapturePreview","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"FingersAutoCapturePreview","kind":"identifier"}],"navigatorTitle":[{"text":"FingersAutoCapturePreview","kind":"identifier"}]},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTFGFingersAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/title"},{"value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/fragments"},{"value":[{"text":"DOTFGFingersAutoCapturePreview","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCapturePreview\/navigatorTitle"}]}]}