{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/result","interfaceLanguage":"occ"},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"result","kind":"identifier"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureUiStateRunning(py)result","symbolKind":"property","roleHeading":"Instance Property","title":"result","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"kind":"identifier","text":"result"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTFGFingersAutoCaptureResult","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureResult"},{"text":" * ","kind":"text"},{"text":"result","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}],"abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/result"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning/result":{"fragments":[{"text":"result","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning\/result","url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning\/result","type":"topic","role":"symbol","kind":"symbol","abstract":[{"text":"Result. If the process has not finished, this will be ","type":"text"},{"text":"null","type":"text"},{"text":".","type":"text"}],"title":"result"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureUiStateRunning":{"kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureUiStateRunning","fragments":[{"text":"DOTFGFingersAutoCaptureUiStateRunning","kind":"identifier"}],"title":"DOTFGFingersAutoCaptureUiStateRunning","type":"topic","abstract":[{"text":"Running state.","type":"text"},{"text":" ","type":"text"},{"text":"This state is active after the ","type":"text"},{"text":"start()","type":"text"},{"type":"text","text":" method is called and before the process finishes."}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureuistaterunning","role":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureResult":{"url":"\/documentation\/dotfingerscore\/fingersautocaptureresult","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureResult"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureResult","title":"FingersAutoCaptureResult","role":"symbol","abstract":[{"text":"The final result of the fingers auto capture process.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureResult"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFGFingersAutoCaptureResult","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/title"},{"value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/fragments","op":"replace"},{"value":[{"text":"DOTFGFingersAutoCaptureResult","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureResult\/navigatorTitle","op":"replace"}]}]}