{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/composeWithInternalError()"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations"]]},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"DotSdkError.composeWithInternalError()"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/composewithinternalerror()"]}],"metadata":{"extendedModule":"DotCore","roleHeading":"Instance Method","symbolKind":"method","externalID":"s:7DotCore0A8SdkErrorPAAE019composeWithInternalD0SSyF::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"title":"composeWithInternalError()","modules":[{"relatedModules":["DotCore"],"name":"DotFaceCore"}],"role":"symbol"},"sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error/composeWithInternalError()":{"role":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/composewithinternalerror()","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/composeWithInternalError()","title":"composeWithInternalError()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error/DotSdkError-Implementations":{"title":"DotSdkError Implementations","type":"topic","role":"collectionGroup","abstract":[],"kind":"article","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/DotSdkError-Implementations","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/dotsdkerror-implementations"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","url":"\/documentation\/dotfacecore\/autocaptureconfiguration","type":"topic","title":"AutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error":{"abstract":[],"kind":"symbol","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"AutoCaptureConfiguration.Error","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title","value":"DOTAutoCaptureConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}