{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error"]]},"metadata":{"role":"symbol","symbolKind":"case","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"roleHeading":"Case","externalID":"s:10DotCapture04AutoB13ConfigurationC5ErrorO39invalidCandidateSelectionDurationMillisyA2EmF"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"title":"AutoCaptureConfiguration.Error","url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error","type":"topic","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error/invalidCandidateSelectionDurationMillis":{"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/invalidcandidateselectiondurationmillis","title":"AutoCaptureConfiguration.Error.invalidCandidateSelectionDurationMillis","role":"symbol","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidCandidateSelectionDurationMillis","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/invalidCandidateSelectionDurationMillis","type":"topic","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"url":"\/documentation\/dotfacecore\/autocaptureconfiguration","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}],"type":"topic","title":"AutoCaptureConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle"}]}]}