{"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"text":".","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error"]]},"metadata":{"extendedModule":"Foundation","modules":[{"name":"DotFaceCore","relatedModules":["Foundation"]}],"platforms":[{"introducedAt":"8.0","deprecated":false,"name":"iOS","beta":false,"unavailable":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false},{"name":"macOS","deprecated":false,"unavailable":false,"introducedAt":"10.10","beta":false},{"name":"tvOS","deprecated":false,"unavailable":false,"introducedAt":"9.0","beta":false},{"name":"watchOS","deprecated":false,"unavailable":false,"introducedAt":"2.0","beta":false}],"title":"recoverySuggestion","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:10DotCapture04AutoB13ConfigurationC5ErrorO","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","symbolKind":"property"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/recoverySuggestion","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/recoverysuggestion"]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error":{"role":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","title":"AutoCaptureConfiguration.Error","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AutoCaptureConfiguration"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"title":"AutoCaptureConfiguration","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/AutoCaptureConfiguration/Error/recoverySuggestion":{"title":"recoverySuggestion","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/AutoCaptureConfiguration\/Error\/recoverySuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/dotfacecore\/autocaptureconfiguration\/error\/recoverysuggestion","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTAutoCaptureConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/title"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/fragments"},{"op":"replace","value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1AutoCaptureConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}