{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"Default is:"}],"type":"paragraph"},{"syntax":null,"code":[".init(","    minValidSamplesInRowToStartCandidateSelection: 2,","    candidateSelectionDurationMillis: 2000",")"],"type":"codeListing"}],"kind":"content"}],"abstract":[{"type":"text","text":"Configuration for auto capture components."}],"sections":[],"metadata":{"externalID":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC04autoD00aD00cdF0Cvp","modules":[{"name":"DotDocument"}],"symbolKind":"property","title":"autoCapture","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"}],"role":"symbol"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/autocapture"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/autoCapture","interfaceLanguage":"swift"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/autoCapture":{"role":"symbol","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"}],"title":"autoCapture","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/autoCapture","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/autocapture","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"title":"DocumentAutoCaptureController.Configuration","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Configuration of the document auto capture non-UI component.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","kind":"symbol","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","kind":"symbol","abstract":[{"text":"version: 9.0.0","type":"text"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/AutoCaptureConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/AutoCaptureConfiguration","abstract":[{"type":"text","text":"Configuration for auto capture components."}],"url":"\/documentation\/dotdocument\/autocaptureconfiguration","type":"topic","role":"symbol","kind":"symbol","title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"AutoCaptureConfiguration"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","op":"replace","value":"DOTDDocumentAutoCaptureController"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/navigatorTitle","op":"replace","value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/title","op":"replace","value":"DOTAutoCaptureConfiguration"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1AutoCaptureConfiguration\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}]}]}]}