{"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/detectionnormalizedrectangle"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"detectionNormalizedRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble"},{"text":"?","kind":"text"}],"languages":["swift"]}]}],"sections":[],"metadata":{"role":"symbol","title":"detectionNormalizedRectangle","externalID":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC28detectionNormalizedRectangleAA0I6DoubleCSgvp","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detectionNormalizedRectangle"},{"text":": ","kind":"text"},{"text":"RectangleDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/detectionNormalizedRectangle","interfaceLanguage":"swift"},"abstract":[{"text":"Normalized rectangle which represents the region in the image which will be used for the document detection.","type":"text"}],"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"title":"DocumentAutoCaptureController","url":"\/documentation\/dotdocument\/documentautocapturecontroller","type":"topic","abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController"},"doc://com.innovatrics.dot.document/documentation/DotDocument":{"type":"topic","title":"DotDocument","kind":"symbol","abstract":[{"type":"text","text":"version: 8.4.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","role":"collection"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","kind":"symbol","title":"DocumentAutoCaptureController.Configuration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/RectangleDouble":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"RectangleDouble"}],"navigatorTitle":[{"text":"RectangleDouble","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value type."}],"url":"\/documentation\/dotdocument\/rectangledouble","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/RectangleDouble","kind":"symbol","title":"RectangleDouble"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/detectionNormalizedRectangle":{"kind":"symbol","title":"detectionNormalizedRectangle","abstract":[{"type":"text","text":"Normalized rectangle which represents the region in the image which will be used for the document detection."}],"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionNormalizedRectangle","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/detectionnormalizedrectangle","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/detectionNormalizedRectangle"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/title","value":"DOTRectangleDouble"},{"op":"replace","value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1RectangleDouble\/fragments"}]}]}