{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validators"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/validators"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/validators","interfaceLanguage":"swift"},"metadata":{"title":"validators","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator","text":"DocumentAutoCaptureDetectionValidator"},{"text":"]","kind":"text"}],"externalID":"s:11DotDocument0B21AutoCaptureControllerC13ConfigurationC10validatorsSayAA0bcD18DetectionValidator_pGvp","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"role":"symbol","symbolKind":"property"},"abstract":[{"text":"Array of validators which will be used to validate input image.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.15.2"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","title":"DocumentAutoCaptureDetectionValidator","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureDetectionValidator","kind":"identifier"}],"type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator","abstract":[{"text":"Use this protocol to create document validators.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class/validators":{"title":"validators","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"validators"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator","kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class\/validators","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class\/validators","type":"topic","abstract":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"title":"DocumentAutoCaptureController","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController/Configuration-swift.class":{"url":"\/documentation\/dotdocument\/documentautocapturecontroller\/configuration-swift.class","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController\/Configuration-swift.class","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration of the document auto capture non-UI component.","type":"text"}],"kind":"symbol","title":"DocumentAutoCaptureController.Configuration","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCaptureDetectionValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}]},{"op":"replace","value":"DOTDDocumentAutoCaptureController","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title"},{"value":[{"text":"DOTDDocumentAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments"}]}]}