{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/waitForRequest","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/capturemode\/waitforrequest"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/capturemode\/waitforrequest"]}],"abstract":[{"text":"Wait for request mode (manual mode).","type":"text"}],"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeWaitForRequest","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"title":"CaptureMode.waitForRequest","role":"symbol","roleHeading":"Case","navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","anchor":"discussion","type":"heading"},{"inlineContent":[{"type":"text","text":"The process remains in a waiting state until the "},{"type":"codeVoice","code":"requestCapture()"},{"type":"text","text":" call is invoked, signaling the request of the capture event."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode":{"url":"\/documentation\/dotfingerscore\/capturemode","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CaptureMode"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode","title":"CaptureMode","role":"symbol","abstract":[{"text":"Capture mode.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/CaptureMode/waitForRequest":{"url":"\/documentation\/dotfingerscore\/capturemode\/waitforrequest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/CaptureMode\/waitForRequest","title":"CaptureMode.waitForRequest","role":"symbol","abstract":[{"text":"Wait for request mode (manual mode).","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTCaptureModeWaitForRequest","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTCaptureMode","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/title"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/fragments","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode\/navigatorTitle","op":"replace"},{"value":"DOTCaptureModeWaitForRequest","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1waitForRequest\/title","op":"replace"},{"value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1CaptureMode~1waitForRequest\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}