{"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite"]]},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP","doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.lite\/SQ","doc:\/\/com.innovatrics.dot.face.lite\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdk"}]}]}],"abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotFaceLite"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"text":", ","type":"text"},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":"."}],"topicSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/bundleId","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isEvaluation","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isFaceEyeGazeLivenessScoreEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isInitialized","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isRealTimeTransactionReportingEnabled","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/licenseCustomer","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/versionName"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/deinitialize()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/shared"]},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/Error"],"title":"Enumerations"}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdk"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotsdk"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@DotFaceLite@objc(cs)DotSdk","navigatorTitle":[{"text":"DotSdk","kind":"identifier"}],"title":"DotSdk","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","modules":[{"name":"DotFaceLite"}]},"sections":[],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/isInitialized":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isInitialized","url":"\/documentation\/dotfacelite\/dotsdk\/isinitialized","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Flag to determine if "},{"type":"codeVoice","code":"DotSdk"},{"text":" is initialized.","type":"text"}],"kind":"symbol","title":"isInitialized","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isInitialized"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"isInitialized","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.innovatrics.dot.face.lite/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SH","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/Error":{"kind":"symbol","title":"DotSdk.Error","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/Error","url":"\/documentation\/dotfacelite\/dotsdk\/error","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Error"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/isEvaluation":{"url":"\/documentation\/dotfacelite\/dotsdk\/isevaluation","role":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isEvaluation","kind":"symbol","title":"isEvaluation","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEvaluation"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/versionName":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"versionName","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"kind":"identifier","text":"versionName"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotsdk\/versionname","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/versionName","title":"versionName","abstract":[{"type":"codeVoice","code":"DotSdk"},{"text":" version.","type":"text"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/bundleId":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/bundleId","type":"topic","navigatorTitle":[{"text":"bundleId","kind":"identifier"}],"title":"bundleId","url":"\/documentation\/dotfacelite\/dotsdk\/bundleid","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"bundleId","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"abstract":[{"text":"Application Bundle ID.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/isRealTimeTransactionReportingEnabled":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isRealTimeTransactionReportingEnabled"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","title":"isRealTimeTransactionReportingEnabled","url":"\/documentation\/dotfacelite\/dotsdk\/isrealtimetransactionreportingenabled","type":"topic","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isRealTimeTransactionReportingEnabled"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/isLibraryActive(libraryId:)":{"navigatorTitle":[{"kind":"identifier","text":"isLibraryActiveWithLibraryId:"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotsdk\/islibraryactive(libraryid:)","abstract":[{"type":"text","text":"Check whether "},{"type":"codeVoice","code":"DotSdk"},{"text":" library is active.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isLibraryActive(libraryId:)","type":"topic","kind":"symbol","title":"isLibraryActive(libraryId:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isLibraryActive","kind":"identifier"},{"kind":"text","text":"("},{"text":"libraryId","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@E@DotLibraryId","text":"DotLibraryId"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.innovatrics.dot.face.lite/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/isFaceEyeGazeLivenessScoreEnabled":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isFaceEyeGazeLivenessScoreEnabled","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isFaceEyeGazeLivenessScoreEnabled","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","title":"isFaceEyeGazeLivenessScoreEnabled","role":"symbol","url":"\/documentation\/dotfacelite\/dotsdk\/isfaceeyegazelivenessscoreenabled","type":"topic"},"doc://com.innovatrics.dot.face.lite/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(pl)NSObject","type":"unresolvable"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/licenseCustomer":{"abstract":[],"type":"topic","role":"symbol","title":"licenseCustomer","url":"\/documentation\/dotfacelite\/dotsdk\/licensecustomer","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"licenseCustomer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/licenseCustomer"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/deinitialize()":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/deinitialize()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"title":"deinitialize()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}],"abstract":[{"text":"Deinitialize ","type":"text"},{"type":"codeVoice","code":"DotSdk"},{"type":"text","text":"."}],"url":"\/documentation\/dotfacelite\/dotsdk\/deinitialize()"},"doc://com.innovatrics.dot.face.lite/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotSdk","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DotSdk"}],"role":"symbol","url":"\/documentation\/dotfacelite\/dotsdk","type":"topic","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk","title":"DotSdk","abstract":[{"text":"Class responsible for the initialization of DOT libraries - ","type":"text"},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":", "},{"code":"DotFaceLite","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotDocument"},{"type":"text","text":", "},{"type":"codeVoice","code":"DotNfc"},{"type":"text","text":"."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/initialize(configuration:)":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/initialize(configuration:)","navigatorTitle":[{"text":"initializeWithConfiguration:error:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"text":"configuration","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DotSdkConfiguration"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"abstract":[{"text":"Initialize ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"text":" with configuration.","type":"text"}],"kind":"symbol","title":"initialize(configuration:)","role":"symbol","url":"\/documentation\/dotfacelite\/dotsdk\/initialize(configuration:)","type":"topic"},"doc://com.innovatrics.dot.face.lite/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/SQ"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotSdk/shared":{"type":"topic","navigatorTitle":[{"text":"shared","kind":"identifier"}],"role":"symbol","abstract":[{"type":"text","text":"Shared singleton instance."}],"url":"\/documentation\/dotfacelite\/dotsdk\/shared","title":"shared","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DotSdk","text":"DotSdk","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/shared","kind":"symbol"},"doc://com.innovatrics.dot.face.lite/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"value":"DotSdk","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DotSdk","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DotSdk","kind":"identifier"}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/bundleId","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isInitialized","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/versionName"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/deinitialize()","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/initialize(configuration:)","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/isLibraryActive(libraryId:)"],"title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotSdk\/shared"]}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.innovatrics.dot.face.lite\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"DotSdk","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"isInitialized","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1isInitialized\/title"},{"value":[{"text":"isInitialized","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1isInitialized\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1versionName\/title","value":"versionName"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1versionName\/fragments","value":[{"text":"versionName","kind":"identifier"}],"op":"replace"},{"value":"bundleId","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1bundleId\/title","op":"replace"},{"value":[{"kind":"identifier","text":"bundleId"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1bundleId\/fragments","op":"replace"},{"op":"replace","value":"isLibraryActiveWithLibraryId:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1isLibraryActive(libraryId:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1isLibraryActive(libraryId:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"isLibraryActiveWithLibraryId:","kind":"identifier"}],"op":"replace"},{"value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1deinitialize()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1deinitialize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"deinitializeAndReturnError:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk\/title","value":"DotSdk"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk\/fragments","value":[{"kind":"identifier","text":"DotSdk"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1initialize(configuration:)\/title","value":"initializeWithConfiguration:error:","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1initialize(configuration:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:error:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1shared\/title","value":"shared"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotSdk~1shared\/fragments","op":"replace","value":[{"text":"shared","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}