{"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","metadata":{"navigatorTitle":[{"text":"min","kind":"identifier"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DOTIntervalFloat(py)min","title":"min","modules":[{"name":"DotNfc"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat"]]},"abstract":[{"type":"text","text":"Minimal interval value."}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/min","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"min"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Float","preciseIdentifier":"s:Sf"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/intervalfloat\/min"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/intervalfloat\/min"]}],"references":{"doc://DotNfc/documentation/DotNfc/IntervalFloat/min":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat\/min","abstract":[{"type":"text","text":"Minimal interval value."}],"type":"topic","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"min","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Float","preciseIdentifier":"s:Sf","kind":"typeIdentifier"}],"title":"min","kind":"symbol","url":"\/documentation\/dotnfc\/intervalfloat\/min","navigatorTitle":[{"kind":"identifier","text":"min"}],"role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.12.1"}],"kind":"symbol","type":"topic","role":"collection","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc"},"doc://DotNfc/documentation/DotNfc/IntervalFloat":{"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/IntervalFloat","url":"\/documentation\/dotnfc\/intervalfloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"type":"topic","title":"IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"IntervalFloat"}],"role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"min","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"min"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"min","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1min\/title","value":"min","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat~1min\/fragments","value":[{"text":"min","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/title","op":"replace","value":"DOTIntervalFloat"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1IntervalFloat\/fragments"}]}]}