{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageformat\/jpeg2000"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageformat\/jpeg2000"]}],"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"title":"ImageFormat.jpeg2000","roleHeading":"Case","externalID":"c:@M@DotCore@E@DOTImageFormat@DOTImageFormatJpeg2000","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg2000"},"kind":"symbol","abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"references":{"doc://DotDocument/documentation/DotDocument/ImageFormat":{"type":"topic","url":"\/documentation\/dotdocument\/imageformat","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat","navigatorTitle":[{"text":"ImageFormat","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Supported image formats."}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ImageFormat"}],"title":"ImageFormat"},"doc://DotDocument/documentation/DotDocument/ImageFormat/jpeg2000":{"type":"topic","navigatorTitle":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}],"title":"ImageFormat.jpeg2000","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"jpeg2000","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageFormat\/jpeg2000","kind":"symbol","abstract":[{"type":"text","text":"JPEG2000 compressed image format"}],"url":"\/documentation\/dotdocument\/imageformat\/jpeg2000","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTImageFormatJpeg2000"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"DOTImageFormatJpeg2000"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/title","op":"replace","value":"DOTImageFormat"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/fragments","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat\/navigatorTitle","op":"replace","value":[{"text":"DOTImageFormat","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg2000\/title","op":"replace","value":"DOTImageFormatJpeg2000"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageFormat~1jpeg2000\/fragments","op":"replace","value":[{"text":"DOTImageFormatJpeg2000","kind":"identifier"}]}]}]}