{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration","text":"DotFaceConfiguration"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"configuration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This parameter specifies how the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework should be configured."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/dotface\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/dotface\/initialize(configuration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/initialize(configuration:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This method will initialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework asynchronously and it will fire delegate callback after it will finish."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:"}],"role":"symbol","title":"initialize(configuration:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:@M@DotFaceCore@objc(cs)DotFace(im)initializeWithConfiguration:","modules":[{"name":"DotFaceCore"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use DotFaceLibrary instead."}]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace":{"deprecated":true,"role":"symbol","title":"DotFace","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFace"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework life cycle."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFace"}],"url":"\/documentation\/dotfacecore\/dotface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFace/initialize(configuration:)":{"deprecated":true,"role":"symbol","title":"initialize(configuration:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotFaceConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"This method will initialize the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework asynchronously and it will fire delegate callback after it will finish."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFace\/initialize(configuration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initializeWithConfiguration:"}],"url":"\/documentation\/dotfacecore\/dotface\/initialize(configuration:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DotFaceConfiguration":{"deprecated":true,"role":"symbol","title":"DotFaceConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotFaceConfiguration"}],"abstract":[{"type":"text","text":"Use this to configure the "},{"type":"codeVoice","code":"DotFace"},{"type":"text","text":" framework."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DotFaceConfiguration"}],"url":"\/documentation\/dotfacecore\/dotfaceconfiguration"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 4.11.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithConfiguration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"initializeWithConfiguration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DotFaceConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DotFaceConfiguration","text":"DotFaceConfiguration"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"configuration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/title","value":"DotFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace\/fragments","value":[{"kind":"identifier","text":"DotFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1initialize(configuration:)\/title","value":"initializeWithConfiguration:"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFace~1initialize(configuration:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initializeWithConfiguration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/title","value":"DotFaceConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DotFaceConfiguration\/fragments","value":[{"kind":"identifier","text":"DotFaceConfiguration"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}