{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/autoCapture","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode"]]},"kind":"symbol","abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/capturemode\/autocapture"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/capturemode\/autocapture"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","roleHeading":"Case","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeAutoCapture","modules":[{"name":"DotDocument"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"navigatorTitle":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}],"title":"CaptureMode.autoCapture","symbolKind":"case"},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"autoCapture","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"Once specified count of consecutive valid frames have been acquired,","type":"text"},{"text":" ","type":"text"},{"text":"the candidate selection process is triggered and continues for specified time in milliseconds.","type":"text"},{"text":" ","type":"text"},{"text":"During this period, the system analyzes the pool of valid images to determine the most suitable result image.","type":"text"}]}],"kind":"content"}],"references":{"doc://DotDocument/documentation/DotDocument/CaptureMode/autoCapture":{"role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/autoCapture","kind":"symbol","abstract":[{"type":"text","text":"Auto capture mode (automatic mode)."}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"autoCapture"}],"url":"\/documentation\/dotdocument\/capturemode\/autocapture","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}],"title":"CaptureMode.autoCapture"},"doc://DotDocument/documentation/DotDocument/CaptureMode":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode","title":"CaptureMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"url":"\/documentation\/dotdocument\/capturemode"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"text":"version: 9.0.2","type":"text"}],"type":"topic","role":"collection","url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"DOTCaptureModeAutoCapture"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"DOTCaptureModeAutoCapture","kind":"identifier"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1autoCapture\/title","value":"DOTCaptureModeAutoCapture"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1autoCapture\/fragments","value":[{"kind":"identifier","text":"DOTCaptureModeAutoCapture"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}]}]}]}