{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode"]]},"metadata":{"modules":[{"name":"DotDocument"}],"role":"collectionGroup","title":"Equatable Implementations","roleHeading":"API Collection"},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/dotdocument\/capturemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","sections":[],"topicSections":[{"anchor":"Operators","title":"Operators","identifiers":["doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/!=(_:_:)"],"generated":true}],"references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","kind":"symbol","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument"},"doc://DotDocument/documentation/DotDocument/CaptureMode/!=(_:_:)":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/!=(_:_:)","url":"\/documentation\/dotdocument\/capturemode\/!=(_:_:)","abstract":[],"title":"!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"kind":"symbol","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/CaptureMode":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode","url":"\/documentation\/dotdocument\/capturemode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}],"title":"CaptureMode","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/title","value":"DOTCaptureMode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/fragments","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/navigatorTitle","value":[{"text":"DOTCaptureMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}