{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/waitForRequest"},"kind":"symbol","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode"]]},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"title":"CaptureMode.waitForRequest","modules":[{"name":"DotDocument"}],"symbolKind":"case","role":"symbol","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeWaitForRequest"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The process remains in a waiting state until the "},{"type":"codeVoice","code":"requestCapture()"},{"type":"text","text":" call is invoked, signaling the request of the capture event."}]}],"kind":"content"}],"references":{"doc://DotDocument/documentation/DotDocument/CaptureMode":{"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode","title":"CaptureMode","type":"topic","abstract":[{"type":"text","text":"Capture mode."}],"kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/capturemode"},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/CaptureMode/waitForRequest":{"navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CaptureMode\/waitForRequest","type":"topic","title":"CaptureMode.waitForRequest","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"role":"symbol","url":"\/documentation\/dotdocument\/capturemode\/waitforrequest"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"DOTCaptureModeWaitForRequest"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/title","op":"replace","value":"DOTCaptureMode"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/fragments","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode\/navigatorTitle","op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1waitForRequest\/title","op":"replace","value":"DOTCaptureModeWaitForRequest"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CaptureMode~1waitForRequest\/fragments","op":"replace","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]}]}]}