{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznotvalidvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/dependencyIdentifiers","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}],"title":"dependencyIdentifiers","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotValidValidator(py)dependencyIdentifiers","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"role":"symbol"},"abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator/dependencyIdentifiers":{"title":"dependencyIdentifiers","kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator\/dependencyIdentifiers","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sh","kind":"typeIdentifier","text":"Set"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":">"}],"abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrznotvalidvalidator\/dependencyidentifiers","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}]},"doc://DotDocument/documentation/DotDocument/MrzNotValidValidator":{"type":"topic","navigatorTitle":[{"text":"MrzNotValidValidator","kind":"identifier"}],"title":"MrzNotValidValidator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MrzNotValidValidator"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotValidValidator","kind":"symbol","abstract":[{"type":"text","text":"Validate Machine Readable Zone."}],"url":"\/documentation\/dotdocument\/mrznotvalidvalidator","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"dependencyIdentifiers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","text":"NSSet<NSString *>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"dependencyIdentifiers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1dependencyIdentifiers\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"value":"DOTDMrzNotValidValidator","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/title","op":"replace"},{"value":[{"text":"DOTDMrzNotValidValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTDMrzNotValidValidator"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotValidValidator\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}