{"sections":[],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/description","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"CustomStringConvertible.description"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/CustomStringConvertible-Implementations"]]},"variants":[{"paths":["\/documentation\/dotpalmcore\/intervalfloat\/error\/description"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"role":"symbol","roleHeading":"Instance Property","title":"description","symbolKind":"property","extendedModule":"DotCore","modules":[{"name":"DotPalmCore","relatedModules":["DotCore"]}],"externalID":"s:7DotCore0A8SdkErrorPAAE11descriptionSSvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat":{"url":"\/documentation\/dotpalmcore\/intervalfloat","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"title":"IntervalFloat","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/description":{"role":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/description","title":"description","type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error/CustomStringConvertible-Implementations":{"type":"topic","title":"CustomStringConvertible Implementations","kind":"article","abstract":[],"role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error\/CustomStringConvertible-Implementations","url":"\/documentation\/dotpalmcore\/intervalfloat\/error\/customstringconvertible-implementations"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 9.1.0"}],"role":"collection","url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/IntervalFloat/Error":{"kind":"symbol","title":"IntervalFloat.Error","abstract":[],"role":"symbol","url":"\/documentation\/dotpalmcore\/intervalfloat\/error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/IntervalFloat\/Error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/title"},{"value":[{"kind":"identifier","text":"DOTIntervalFloat"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/fragments"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1IntervalFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}