{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/facing"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/cameraconfiguration\/facing"]}],"metadata":{"roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","text":"CameraFacing","kind":"typeIdentifier"}],"modules":[{"name":"DotPalmCore"}],"role":"symbol","symbolKind":"property","title":"facing","externalID":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration(py)facing","navigatorTitle":[{"text":"facing","kind":"identifier"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/facing","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Front or back camera facing."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","text":"CameraFacing","kind":"typeIdentifier"}]}],"kind":"declarations"}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration/facing":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"facing"},{"text":": ","kind":"text"},{"text":"CameraFacing","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration\/facing","type":"topic","abstract":[{"type":"text","text":"Front or back camera facing."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/cameraconfiguration\/facing","title":"facing","navigatorTitle":[{"text":"facing","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/CameraConfiguration":{"abstract":[{"type":"text","text":"Configuration for components utilizing a camera."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraConfiguration","url":"\/documentation\/dotpalmcore\/cameraconfiguration","title":"CameraConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CameraConfiguration"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraConfiguration"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/CameraFacing":{"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","url":"\/documentation\/dotpalmcore\/camerafacing","type":"topic","kind":"symbol","title":"CameraFacing","navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"abstract":[{"type":"text","text":"version: 9.2.2"}],"title":"DotPalmCore","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","role":"collection","url":"\/documentation\/dotpalmcore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"facing","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"facing","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CameraFacing","text":"DOTCameraFacing","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"facing","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"facing","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1facing\/title"},{"value":[{"kind":"identifier","text":"facing"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration~1facing\/fragments"},{"value":"DOTCameraConfiguration","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/title"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraConfiguration\/navigatorTitle"},{"value":"DOTCameraFacing","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/title"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/fragments"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CameraFacing\/navigatorTitle"}]}]}