{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Create new "},{"code":"SmileLivenessViewController","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController(im)initWithConfiguration:style:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"text":": ","kind":"text"},{"text":"Configuration","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC"},{"text":", ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC"},{"kind":"text","text":")"}],"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:style:"}],"role":"symbol","modules":[{"name":"DotFaceCore"}],"title":"init(configuration:style:)"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/init(configuration:style:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/init(configuration:style:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/init(configuration:style:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC","text":"Configuration"},{"text":" = .init(), ","kind":"text"},{"text":"style","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC","text":"Style","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class"},{"text":" = .init())","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Configure the smile liveness process.","type":"text"}]}],"name":"configuration"},{"name":"style","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Customize user interface."}]}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class","type":"topic","title":"SmileLivenessViewController.Style","navigatorTitle":[{"text":"Style","kind":"identifier"}],"abstract":[{"text":"Customization options for the smile liveness user interface.","type":"text"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Style","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/init(configuration:style:)":{"title":"init(configuration:style:)","abstract":[{"type":"text","text":"Create new "},{"type":"codeVoice","code":"SmileLivenessViewController"},{"type":"text","text":"."}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/init(configuration:style:)","navigatorTitle":[{"text":"initWithConfiguration:style:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/init(configuration:style:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"configuration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Configuration","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC13ConfigurationC"},{"kind":"text","text":", "},{"text":"style","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC"},{"text":")","kind":"text"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"abstract":[{"type":"text","text":"UI component for evaluating liveness by detecting face expression."}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SmileLivenessViewController"}],"title":"SmileLivenessViewController","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessConfiguration":{"url":"\/documentation\/dotfacecore\/dotfsmilelivenessconfiguration","title":"DOTFSmileLivenessConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"DOTFSmileLivenessConfiguration"}],"abstract":[{"text":"Configuration options for the smile liveness process.","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Configuration-swift.class":{"title":"SmileLivenessViewController.Configuration","type":"topic","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/configuration-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Configuration-swift.class","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the smile liveness process."}],"role":"symbol","navigatorTitle":[{"text":"Configuration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.1"}],"role":"collection","type":"topic","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessStyle":{"url":"\/documentation\/dotfacecore\/dotfsmilelivenessstyle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessStyle","role":"symbol","title":"DOTFSmileLivenessStyle","type":"topic","abstract":[{"text":"Customization options for the smile liveness user interface.","type":"text"}],"fragments":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"initWithConfiguration:style:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfiguration:"},{"kind":"text","text":"("},{"text":"DOTFSmileLivenessConfiguration","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessConfiguration","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"configuration","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"style:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessStyle","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessStyle","text":"DOTFSmileLivenessStyle"},{"text":" *) ","kind":"text"},{"text":"style","kind":"internalParam"},{"kind":"text","text":";"}]}]},"op":"replace"},{"op":"replace","value":"initWithConfiguration:style:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1init(configuration:style:)\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1init(configuration:style:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:style:"}],"op":"replace"},{"value":"DOTFSmileLivenessViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}