{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/style-swift.property"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","text":"Style"}]}]}],"abstract":[{"text":"Current style.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"metadata":{"role":"symbol","navigatorTitle":[{"text":"style","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC","kind":"typeIdentifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessViewController(py)style","title":"style"},"variants":[{"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.property"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/Style-swift.class":{"title":"SmileLivenessViewController.Style","navigatorTitle":[{"text":"Style","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.class","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Style"}],"type":"topic","abstract":[{"text":"Customization options for the smile liveness user interface.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/Style-swift.class","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/DOTFSmileLivenessStyle":{"kind":"symbol","type":"topic","title":"DOTFSmileLivenessStyle","abstract":[{"type":"text","text":"Customization options for the smile liveness user interface."}],"url":"\/documentation\/dotfacecore\/dotfsmilelivenessstyle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessStyle","fragments":[{"kind":"identifier","text":"DOTFSmileLivenessStyle"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"title":"SmileLivenessViewController","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SmileLivenessViewController"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","type":"topic","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/style-swift.property":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"style"}],"type":"topic","abstract":[{"text":"Current style.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/style-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore27SmileLivenessViewControllerC5StyleC"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/style-swift.property","title":"style","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 8.15.2"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"style","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFSmileLivenessStyle","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFSmileLivenessStyle","text":"DOTFSmileLivenessStyle"},{"kind":"text","text":" * "},{"text":"style","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","value":[{"text":"DOTFSmileLivenessViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1style-swift.property\/title","value":"style","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1style-swift.property\/fragments","value":[{"text":"style","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}