{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"metadata":{"extendedModule":"DotFaceCore","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"title":"viewWillAppear(_:)","externalID":"c:@CM@DotFaceCore@objc(cs)DOTFSmileLivenessViewController(im)viewWillAppear:","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"method"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillAppear(_:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillAppear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwillappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwillappear(_:)"]}],"sections":[],"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewWillAppear(_:)":{"role":"symbol","abstract":[],"title":"viewWillAppear(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillAppear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewwillappear(_:)","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewWillAppear(_:)","navigatorTitle":[{"text":"viewWillAppear:","kind":"identifier"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"role":"symbol","abstract":[{"type":"text","text":"UI Smile Liveness component."}],"title":"SmileLivenessViewController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SmileLivenessViewController","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","navigatorTitle":[{"text":"SmileLivenessViewController","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":null,"op":"add","path":"\/metadata\/platforms"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"viewWillAppear:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewWillAppear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"viewWillAppear:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillAppear(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewWillAppear:"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewWillAppear(_:)\/fragments"},{"value":"DOTFSmileLivenessViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title"},{"value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments"},{"value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/navigatorTitle"}]}]}