{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class"]]},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"barcode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotDocumentBarcodeModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"role":"symbol","externalID":"s:7DotCore0A28DocumentLibraryConfigurationC7ModulesC7barcodeAA0ac13BarcodeModuleE0CSgvp","symbolKind":"property","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"title":"barcode"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode"]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","interfaceLanguage":"swift"},"references":{"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class/barcode":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class\/barcode","url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class\/barcode","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"barcode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotDocumentBarcodeModuleConfiguration","kind":"typeIdentifier","text":"DotDocumentBarcodeModuleConfiguration"},{"kind":"text","text":"?"}],"abstract":[],"title":"barcode","role":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentBarcodeModuleConfiguration":{"navigatorTitle":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentBarcodeModuleConfiguration","url":"\/documentation\/dotnfc\/dotdocumentbarcodemoduleconfiguration","role":"symbol","title":"DotDocumentBarcodeModuleConfiguration","type":"topic","abstract":[{"type":"text","text":"Document barcode detection module configuration."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration/Modules-swift.class":{"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration\/modules-swift.class","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"abstract":[{"type":"text","text":"Document library module configuration."}],"kind":"symbol","title":"DotDocumentLibraryConfiguration.Modules","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration\/Modules-swift.class","navigatorTitle":[{"kind":"identifier","text":"Modules"}]},"doc://DotNfc/documentation/DotNfc/DotDocumentLibraryConfiguration":{"url":"\/documentation\/dotnfc\/dotdocumentlibraryconfiguration","role":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"abstract":[{"text":"Document library configuration.","type":"text"}],"kind":"symbol","title":"DotDocumentLibraryConfiguration","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DotDocumentLibraryConfiguration","navigatorTitle":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}]},"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotDocumentBarcodeModuleConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentBarcodeModuleConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentBarcodeModuleConfiguration\/navigatorTitle"},{"op":"replace","value":"DotDocumentLibraryConfiguration","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotDocumentLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DotDocumentLibraryConfiguration\/navigatorTitle"}]}]}