{"kind":"symbol","abstract":[{"type":"text","text":"Wait for request mode (manual mode)."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waitForRequest"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"paragraph","inlineContent":[{"text":"The process remains in a waiting state until the ","type":"text"},{"code":"requestCapture()","type":"codeVoice"},{"text":" call is invoked, signaling the request of the capture event.","type":"text"}]}],"kind":"content"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/capturemode\/waitforrequest"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/capturemode\/waitforrequest"]}],"metadata":{"symbolKind":"case","modules":[{"name":"DotPalmCore"}],"role":"symbol","roleHeading":"Case","externalID":"c:@M@DotCapture@E@DOTCaptureMode@DOTCaptureModeWaitForRequest","title":"CaptureMode.waitForRequest","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitForRequest","kind":"identifier"}],"navigatorTitle":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/waitForRequest","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode"]]},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.2.3"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode/waitForRequest":{"type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTCaptureModeWaitForRequest"}],"kind":"symbol","abstract":[{"text":"Wait for request mode (manual mode).","type":"text"}],"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode\/waitForRequest","url":"\/documentation\/dotpalmcore\/capturemode\/waitforrequest","title":"CaptureMode.waitForRequest","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitForRequest"}]},"doc://DotPalmCore/documentation/DotPalmCore/CaptureMode":{"navigatorTitle":[{"kind":"identifier","text":"CaptureMode"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/CaptureMode","title":"CaptureMode","url":"\/documentation\/dotpalmcore\/capturemode","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CaptureMode"}],"abstract":[{"text":"Capture mode.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTCaptureModeWaitForRequest","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTCaptureModeWaitForRequest","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1waitForRequest\/title","op":"replace"},{"value":[{"text":"DOTCaptureModeWaitForRequest","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode~1waitForRequest\/fragments","op":"replace"},{"value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/title","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/fragments","op":"replace"},{"value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1CaptureMode\/navigatorTitle","op":"replace"}]}]}