{"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"deinitializeAndReturnError:"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","title":"deinitialize()","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:@M@DotFaceLite@objc(pl)DotLibrary(im)deinitializeAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"text":"throws","kind":"keyword"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"deinitialize","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary\/deinitialize()","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibrary\/deinitialize()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotlibrary\/deinitialize()"]}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibrary/deinitialize()":{"url":"\/documentation\/dotfacelite\/dotlibrary\/deinitialize()","kind":"symbol","required":true,"abstract":[],"navigatorTitle":[{"text":"deinitializeAndReturnError:","kind":"identifier"}],"role":"symbol","type":"topic","title":"deinitialize()","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary\/deinitialize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"deinitialize","kind":"identifier"},{"text":"() ","kind":"text"},{"kind":"keyword","text":"throws"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibrary":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibrary","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}],"title":"DotLibrary"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","role":"collection","kind":"symbol","abstract":[{"text":"version: 8.3.0","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"deinitializeAndReturnError:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deinitializeAndReturnError:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"text":"deinitializeAndReturnError:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"kind":"text","text":" * *) "},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"deinitializeAndReturnError:","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary~1deinitialize()\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary~1deinitialize()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"deinitializeAndReturnError:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/title","op":"replace","value":"DotLibrary"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/fragments","op":"replace","value":[{"kind":"identifier","text":"DotLibrary"}]}]}]}