{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/id"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary"]]},"metadata":{"navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"id"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","text":"DotLibraryId","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotCore@objc(pl)DotLibrary(py)id","role":"symbol","title":"id"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibrary\/id"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotlibrary\/id"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary/id":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/id","navigatorTitle":[{"text":"id","kind":"identifier"}],"required":true,"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier"}],"abstract":[],"url":"\/documentation\/dotfacelite\/dotlibrary\/id","kind":"symbol","role":"symbol","title":"id"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibraryId":{"title":"DotLibraryId","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DotLibraryId","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibraryid","type":"topic","role":"symbol","abstract":[{"text":"The ","type":"text"},{"code":"DotSdk","type":"codeVoice"},{"type":"text","text":" library identifier."}],"navigatorTitle":[{"kind":"identifier","text":"DotLibraryId"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","role":"collection","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","abstract":[{"type":"text","text":"version: 8.16.0"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","kind":"symbol","url":"\/documentation\/dotfacelite\/dotlibrary","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"abstract":[],"navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"title":"DotLibrary"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"id","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotLibraryId","preciseIdentifier":"c:@M@DotCore@E@DotLibraryId","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibraryId"},{"text":" ","kind":"text"},{"text":"id","kind":"identifier"}]}]}},{"value":"id","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1id\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1id\/fragments","op":"replace","value":[{"text":"id","kind":"identifier"}]},{"value":"DotLibraryId","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibraryId\/fragments","value":[{"kind":"identifier","text":"DotLibraryId"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title","value":"DotLibrary"},{"value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments"}]}]}