{"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/initialize(license:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","title":"initialize(license:)","modules":[{"name":"DotFaceLite"}],"required":true,"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialize"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"symbolKind":"method","externalID":"c:@M@DotCore@objc(pl)DotLibrary(im)initializeWithLicense:error:"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/dotlibrary\/initialize(license:)"]},{"paths":["\/documentation\/dotfacelite\/dotlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.6.1"}],"role":"collection","url":"\/documentation\/dotfacelite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkLicenseProxyProtocol":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkLicenseProxyProtocol","url":"\/documentation\/dotfacelite\/dotsdklicenseproxyprotocol","title":"DotSdkLicenseProxyProtocol","abstract":[],"type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary":{"type":"topic","url":"\/documentation\/dotfacelite\/dotlibrary","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DotLibrary"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary","title":"DotLibrary","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotLibrary"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotLibrary/initialize(license:)":{"url":"\/documentation\/dotfacelite\/dotlibrary\/initialize(license:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotLibrary\/initialize(license:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"initialize"},{"kind":"text","text":"("},{"text":"license","kind":"externalParam"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"type":"topic","title":"initialize(license:)","required":true,"role":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"initializeWithLicense:error:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"initializeWithLicense:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","text":"id<DotSdkLicenseProxyProtocol>"},{"kind":"text","text":" *) "},{"text":"license","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError","text":"NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/title","value":"DotSdkLicenseProxyProtocol"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotSdkLicenseProxyProtocol\/fragments","op":"replace","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/title","value":"DotLibrary","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary\/fragments","value":[{"text":"DotLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1DotLibrary~1initialize(license:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}