{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","required":true,"externalID":"c:@M@DotFaceLite@objc(pl)DotLibrary(im)verifyIsActiveAndReturnError:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"verifyIsActive()","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary"]]},"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary\/verifyIsActive()","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/dotlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/dotlibrary\/verifyisactive()"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"verifyIsActive","kind":"identifier"},{"kind":"text","text":"() "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibrary/verifyIsActive()":{"kind":"symbol","required":true,"abstract":[],"url":"\/documentation\/dotfacelite\/dotlibrary\/verifyisactive()","role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary\/verifyIsActive()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"verifyIsActive"},{"text":"() ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"verifyIsActive()","type":"topic","navigatorTitle":[{"text":"verifyIsActiveAndReturnError:","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/DotLibrary":{"kind":"symbol","navigatorTitle":[{"text":"DotLibrary","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/dotlibrary","title":"DotLibrary","type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotLibrary"}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/DotLibrary","role":"symbol","abstract":[]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","kind":"symbol","role":"collection","abstract":[{"type":"text","text":"version: 8.0.0"}],"title":"DotFaceLite"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"verifyIsActiveAndReturnError:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"},{"kind":"text","text":"("},{"text":"NSError","preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"verifyIsActiveAndReturnError:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary~1verifyIsActive()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary~1verifyIsActive()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"verifyIsActiveAndReturnError:"}]},{"value":"DotLibrary","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/title","op":"replace"},{"op":"replace","value":[{"text":"DotLibrary","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1DotLibrary\/fragments"}]}]}