{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"preciseIdentifier":"s:s5UInt8V","text":"UInt8","kind":"typeIdentifier"},{"text":">, ","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"ImageSize","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(im)initWithBytesPointer:size:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithBytesPointer:size:","kind":"identifier"}],"title":"init(bytesPointer:size:)","role":"symbol","modules":[{"name":"DotNfc"}],"roleHeading":"Initializer","symbolKind":"init"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/init(bytesPointer:size:)"},"abstract":[{"type":"text","text":"Do not use this, use "},{"type":"codeVoice","code":"BgraRawImageFactory"},{"text":" to create ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/dotnfc\/bgrarawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/bgrarawimage\/init(bytespointer:size:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage"]]},"references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/ImageSize":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize","navigatorTitle":[{"text":"ImageSize","kind":"identifier"}],"abstract":[{"text":"Image size in pixels.","type":"text"}],"kind":"symbol","type":"topic","title":"ImageSize","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ImageSize","kind":"identifier"}],"url":"\/documentation\/dotnfc\/imagesize"},"doc://DotNfc/documentation/DotNfc/BgraRawImage/init(bytesPointer:size:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithBytesPointer:size:"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"bytesPointer","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":">, ","kind":"text"},{"text":"size","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","text":"ImageSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/bgrarawimage\/init(bytespointer:size:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/init(bytesPointer:size:)","kind":"symbol","abstract":[{"text":"Do not use this, use ","type":"text"},{"type":"codeVoice","code":"BgraRawImageFactory"},{"type":"text","text":" to create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":".","type":"text"}],"type":"topic","title":"init(bytesPointer:size:)","role":"symbol"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotnfc\/bgrarawimage","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","kind":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"type":"topic","title":"BgraRawImage","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"initWithBytesPointer:size:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithBytesPointer:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@uint8_t","text":"uint8_t"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bytesPointer"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"kind":"text","text":"("},{"text":"DOTImageSize","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTImageSize","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ImageSize"},{"text":" *) ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/title","op":"replace","value":"DOTImageSize"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ImageSize\/fragments","value":[{"text":"DOTImageSize","kind":"identifier"}],"op":"replace"},{"value":"initWithBytesPointer:size:","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1init(bytesPointer:size:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1init(bytesPointer:size:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBytesPointer:size:"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}