{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat\/init(value:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat\/init(value:)"]}],"metadata":{"title":"init(value:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"modules":[{"name":"DotPalmCore"}],"roleHeading":"Initializer","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(im)initWithValue:","symbolKind":"init"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/init(value:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/init(value:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/init(value:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":")","kind":"text"}],"title":"init(value:)","url":"\/documentation\/dotpalmcore\/wrappedfloat\/init(value:)","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"initWithValue:","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/wrappedfloat","title":"WrappedFloat","role":"symbol","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Float"},{"type":"text","text":" value for Objective-C support."}],"kind":"symbol","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 9.4.1"}],"title":"DotPalmCore","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithValue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:f","text":"float","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"value","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1init(value:)\/title","value":"initWithValue:"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1init(value:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithValue:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/title","value":"DOTWrappedFloat"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/fragments","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/navigatorTitle","value":[{"text":"DOTWrappedFloat","kind":"identifier"}]}]}]}