{"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat\/value"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/wrappedfloat\/value"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"value"}],"role":"symbol","modules":[{"name":"DotPalmCore"}],"title":"value","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"}],"symbolKind":"property","roleHeading":"Instance Property","externalID":"c:@M@DotCore@objc(cs)DOTWrappedFloat(py)value"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/value","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sf","kind":"typeIdentifier","text":"Float"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat","navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}],"abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"url":"\/documentation\/dotpalmcore\/wrappedfloat","title":"WrappedFloat","role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"WrappedFloat"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"title":"DotPalmCore","kind":"symbol","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/WrappedFloat/value":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sf","text":"Float"}],"url":"\/documentation\/dotpalmcore\/wrappedfloat\/value","title":"value","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/WrappedFloat\/value","navigatorTitle":[{"text":"value","kind":"identifier"}],"type":"topic","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"value","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"value"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"float","kind":"typeIdentifier","preciseIdentifier":"c:f"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTWrappedFloat","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/title","op":"replace"},{"op":"replace","value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat\/fragments"},{"value":"value","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1value\/title","op":"replace"},{"value":[{"text":"value","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1WrappedFloat~1value\/fragments","op":"replace"}]}]}