{"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/bgraRawImage","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgraRawImage"},{"text":": ","kind":"text"},{"text":"BgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/bgrarawimage"]}],"abstract":[{"type":"text","text":"Sample image."}],"sections":[],"metadata":{"role":"symbol","modules":[{"name":"DotFaceLite"}],"externalID":"s:11DotFaceLite0B21AutoCaptureControllerC6SampleC12bgraRawImageAA04BgraiJ0Cvp","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"bgraRawImage"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"title":"bgraRawImage","symbolKind":"property"},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/BgraRawImage":{"type":"topic","title":"BgraRawImage","kind":"symbol","role":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/BgraRawImage","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Sample":{"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"type":"topic","abstract":[{"text":"The data sample captured at specific time which serves as an input for the face auto capture process.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample","navigatorTitle":[{"text":"Sample","kind":"identifier"}],"kind":"symbol","title":"FaceAutoCaptureController.Sample"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController":{"type":"topic","kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}],"role":"symbol","title":"FaceAutoCaptureController","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}]},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.4.1","type":"text"}],"url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","title":"DotFaceLite"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/FaceAutoCaptureController/Sample/bgraRawImage":{"type":"topic","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bgraRawImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTBgraRawImage"}],"title":"bgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Sample\/bgraRawImage","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/sample\/bgrarawimage","kind":"symbol","abstract":[{"type":"text","text":"Sample image."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"op":"replace","value":[{"kind":"identifier","text":"DOTBgraRawImage"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title","value":"DOTFLFaceAutoCaptureController","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureController"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments","op":"replace"}]}]}