{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/bgrarawimagefactory\/create(ciimage:cicontext:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/bgrarawimagefactory\/create(ciimage:cicontext:)"]}],"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage"}],"modules":[{"name":"DotFaceCore"}],"title":"create(ciImage:ciContext:)","externalID":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImageFactory(cm)createWithCiImage:ciContext:","roleHeading":"Type Method","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"symbolKind":"method","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","text":"BgraRawImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" object.","type":"text"}]}]},{"name":"ciContext","content":[{"type":"paragraph","inlineContent":[{"text":"CIContext.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" instance."}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImageFactory\/create(ciImage:ciContext:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" object."}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImageFactory"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","type":"topic","title":"DotFaceCore","role":"collection","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgraRawImageFactory":{"abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgraRawImage"},{"text":" from iOS native image types.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgraRawImageFactory","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImageFactory","navigatorTitle":[{"kind":"identifier","text":"BgraRawImageFactory"}],"type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/bgrarawimagefactory","kind":"symbol","title":"BgraRawImageFactory"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgraRawImage":{"type":"topic","url":"\/documentation\/dotfacecore\/bgrarawimage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","role":"symbol","title":"BgraRawImage","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"BgraRawImage"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/BgraRawImageFactory/create(ciImage:ciContext:)":{"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImageFactory\/create(ciImage:ciContext:)","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"}],"title":"create(ciImage:ciContext:)","url":"\/documentation\/dotfacecore\/bgrarawimagefactory\/create(ciimage:cicontext:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"createWithCiImage:ciContext:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"DOTBgraRawImage","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithCiImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CIImage","preciseIdentifier":"c:objc(cs)CIImage"},{"kind":"text","text":" *) "},{"text":"ciImage","kind":"internalParam"},{"kind":"text","text":" "},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIContext","kind":"typeIdentifier","text":"CIContext"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"ciContext"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImageFactory\/title","value":"DOTBgraRawImageFactory","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImageFactory\/fragments","value":[{"text":"DOTBgraRawImageFactory","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImage\/title","op":"replace","value":"DOTBgraRawImage"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/title","value":"createWithCiImage:ciContext:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1BgraRawImageFactory~1create(ciImage:ciContext:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCiImage:ciContext:","kind":"identifier"}]}]}]}