{"metadata":{"externalID":"s:11DotDocument0B8DetectorC0B0C15imageParametersAA05ImageE0Cvp","role":"symbol","modules":[{"name":"DotDocument"}],"title":"imageParameters","roleHeading":"Instance Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"imageParameters","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","text":"ImageParameters","kind":"typeIdentifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/imageParameters"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Image parameters calculated from area of the detected document."}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageParameters","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","text":"ImageParameters"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/document\/imageparameters"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/ImageParameters":{"title":"ImageParameters","url":"\/documentation\/dotdocument\/imageparameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageParameters"}],"kind":"symbol","role":"symbol","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","navigatorTitle":[{"text":"ImageParameters","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/imageParameters":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/imageParameters","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/document\/imageparameters","title":"imageParameters","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageParameters","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDImageParameters","kind":"typeIdentifier","text":"ImageParameters"}],"type":"topic","abstract":[{"type":"text","text":"Image parameters calculated from area of the detected document."}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","kind":"symbol","url":"\/documentation\/dotdocument\/mrzreader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","role":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","type":"topic","abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","url":"\/documentation\/dotdocument\/documentdetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DocumentDetector","kind":"identifier"}],"title":"DocumentDetector","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","abstract":[{"text":"version: 8.7.1","type":"text"}],"type":"topic","role":"collection"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"kind":"symbol","type":"topic","abstract":[{"text":"Result of the document detection process.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","url":"\/documentation\/dotdocument\/documentdetector\/document","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Document","kind":"identifier"}],"title":"DocumentDetector.Document","navigatorTitle":[{"text":"Document","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}