{"metadata":{"navigatorTitle":[{"kind":"identifier","text":"hotspotsScore"}],"title":"hotspotsScore","externalID":"c:@M@DotDocument@objc(cs)DOTDImageParameters(py)hotspotsScore","symbolKind":"property","roleHeading":"Instance Property","role":"symbol","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"hotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}]},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/hotspotsScore","interfaceLanguage":"swift"},"abstract":[{"text":"Overall hotspots score of the document in range [0, 1.0]. Where 0 means low hotspots occurrence and 1.0 means high hotspots occurrence.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hotspotsScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/imageparameters\/hotspotsscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/imageparameters\/hotspotsscore"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument":{"url":"\/documentation\/dotdocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","abstract":[{"text":"version: 8.12.0","type":"text"}],"role":"collection","kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/ImageParameters":{"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters","url":"\/documentation\/dotdocument\/imageparameters","abstract":[{"text":"Result of image parameters analysis.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"ImageParameters","kind":"identifier"}],"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"title":"ImageParameters"},"doc://DotDocument/documentation/DotDocument/ImageParameters/hotspotsScore":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ImageParameters\/hotspotsScore","abstract":[{"text":"Overall hotspots score of the document in range [0, 1.0]. Where 0 means low hotspots occurrence and 1.0 means high hotspots occurrence.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/imageparameters\/hotspotsscore","role":"symbol","title":"hotspotsScore","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"hotspotsScore","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"hotspotsScore"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"hotspotsScore"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"text":"hotspotsScore","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/title","value":"DOTDImageParameters"},{"value":[{"text":"DOTDImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1hotspotsScore\/title","value":"hotspotsScore"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ImageParameters~1hotspotsScore\/fragments","op":"replace","value":[{"text":"hotspotsScore","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}