{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPosition","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/documentdetector\/document\/detectionposition"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/detectionPosition"},"metadata":{"externalID":"s:11DotDocument0B8DetectorC0B0C17detectionPositionAA09DetectionE0Cvp","title":"detectionPosition","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPosition","kind":"identifier"},{"text":": ","kind":"text"},{"text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"sections":[],"abstract":[{"type":"text","text":"Detected corners of the document card."}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentdetector","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"type":"topic","role":"symbol","title":"DocumentDetector","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"title":"DocumentDetector.Document","type":"topic","url":"\/documentation\/dotdocument\/documentdetector\/document","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Document"}],"abstract":[{"type":"text","text":"Result of the document detection process."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Document"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/detectionPosition":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detectionPosition","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DetectionPosition","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDetectionPosition"}],"type":"topic","title":"detectionPosition","abstract":[{"text":"Detected corners of the document card.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/detectionPosition","kind":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/document\/detectionposition","role":"symbol"},"doc://DotDocument/documentation/DotDocument/DetectionPosition":{"title":"DetectionPosition","type":"topic","url":"\/documentation\/dotdocument\/detectionposition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"abstract":[{"text":"Position of the document card in the image.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DetectionPosition","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle","value":[{"text":"DOTDDocumentDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/title","value":"DOTDDetectionPosition"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/fragments","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DetectionPosition\/navigatorTitle","value":[{"text":"DOTDDetectionPosition","kind":"identifier"}]}]}]}