{"kind":"symbol","variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilltransition(to:with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilltransition(to:with:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewWillTransition"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"coordinator","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator","kind":"typeIdentifier"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewWillTransition","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","kind":"typeIdentifier","text":"UIViewControllerTransitionCoordinator"},{"kind":"text","text":")"}],"externalID":"c:@CM@DotPalmCore@objc(cs)DOTPPalmAutoCaptureViewController(im)viewWillTransitionToSize:withTransitionCoordinator:","role":"symbol","symbolKind":"method","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"roleHeading":"Instance Method","title":"viewWillTransition(to:with:)","modules":[{"name":"DotPalmCore"}]},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewWillTransition(to:with:)","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController/viewWillTransition(to:with:)":{"abstract":[],"kind":"symbol","title":"viewWillTransition(to:with:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"viewWillTransition","kind":"identifier"},{"text":"(","kind":"text"},{"text":"to","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)UIViewControllerTransitionCoordinator","text":"UIViewControllerTransitionCoordinator"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller\/viewwilltransition(to:with:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController\/viewWillTransition(to:with:)"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","abstract":[{"type":"text","text":"version: 8.12.1"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing palm images using the placeholder."}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureviewcontroller","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureViewController"}],"title":"PalmAutoCaptureViewController","navigatorTitle":[{"text":"PalmAutoCaptureViewController","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"viewWillTransitionToSize:withTransitionCoordinator:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewWillTransitionToSize:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"withTransitionCoordinator:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)UIViewControllerTransitionCoordinator","text":"id<UIViewControllerTransitionCoordinator>"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"coordinator"},{"text":";","kind":"text"}]}]}},{"value":"viewWillTransitionToSize:withTransitionCoordinator:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewWillTransition(to:with:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"viewWillTransitionToSize:withTransitionCoordinator:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController~1viewWillTransition(to:with:)\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureViewController\/fragments","value":[{"text":"DOTPPalmAutoCaptureViewController","kind":"identifier"}]}]}]}