{"metadata":{"modules":[{"name":"DotFaceCore"}],"role":"collectionGroup","title":"LocalizedError Implementations","roleHeading":"API Collection"},"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/LocalizedError-Implementations","interfaceLanguage":"swift"},"sections":[],"kind":"article","topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/failureReason","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/helpAnchor","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/recoverySuggestion"],"title":"Instance Properties","generated":true}],"variants":[{"paths":["\/documentation\/dotfacecore\/valuerange\/error\/localizederror-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/ValueRange":{"abstract":[{"type":"text","text":"Representation of "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" range, compatible with Objective-C."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"navigatorTitle":[{"kind":"identifier","text":"ValueRange"}],"type":"topic","title":"ValueRange","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValueRange"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange","url":"\/documentation\/dotfacecore\/valuerange"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Error":{"url":"\/documentation\/dotfacecore\/valuerange\/error","type":"topic","role":"symbol","kind":"symbol","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"title":"ValueRange.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error"},"doc://DotFaceCore/documentation/DotFaceCore":{"url":"\/documentation\/dotfacecore","role":"collection","abstract":[{"text":"version: 9.2.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","title":"DotFaceCore","kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Error/recoverySuggestion":{"type":"topic","role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/error\/recoverysuggestion","abstract":[],"title":"recoverySuggestion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/recoverySuggestion"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Error/failureReason":{"type":"topic","abstract":[],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"failureReason","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotfacecore\/valuerange\/error\/failurereason","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/failureReason","title":"failureReason","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/ValueRange/Error/helpAnchor":{"type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dotfacecore\/valuerange\/error\/helpanchor","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/ValueRange\/Error\/helpAnchor","title":"helpAnchor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"helpAnchor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTFValueRange","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/title"},{"op":"replace","value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/fragments"},{"op":"replace","value":[{"text":"DOTFValueRange","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1ValueRange\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}