{"abstract":[{"type":"text","text":"Non-UI component for the palm auto capture process."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"],"kind":"relationships"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(DOTPPalmAutoCaptureController) "},{"text":"final","kind":"keyword"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}]}]},{"kind":"content","content":[{"level":2,"text":"Overview","type":"heading","anchor":"overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"This component requires the "},{"code":"DotPalmDetection","type":"codeVoice"},{"type":"text","text":" module to be active."}]}]}],"topicSections":[{"title":"Configuration","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"]},{"title":"Palm auto capture process","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators"},{"title":"Classes","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample"]},{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/init(configuration:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/configuration-swift.property"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/process(sample:)"],"title":"Instance Methods"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error"],"title":"Enumerations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/palmautocapturecontroller"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore"]]},"kind":"symbol","metadata":{"role":"symbol","title":"PalmAutoCaptureController","symbolKind":"class","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureController"}],"roleHeading":"Class","externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureController","navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}]},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"],"generated":true,"title":"Non-UI components"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Sample":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/sample","abstract":[{"type":"text","text":"The data sample captured at specific time which serves as an input for the palm auto capture process."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Sample"}],"role":"symbol","type":"topic","title":"PalmAutoCaptureController.Sample","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Sample","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Sample"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/init(configuration:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/init(configuration:)","navigatorTitle":[{"kind":"identifier","text":"initWithConfiguration:"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/init(configuration:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"configuration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration"},{"text":")","kind":"text"}],"type":"topic","title":"init(configuration:)","abstract":[{"text":"Create new instance of ","type":"text"},{"type":"codeVoice","code":"PalmAutoCaptureController"},{"text":".","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/configuration-swift.property":{"type":"topic","navigatorTitle":[{"text":"configuration","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"configuration"},{"kind":"text","text":": "},{"preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC13ConfigurationC","text":"Configuration","kind":"typeIdentifier"}],"abstract":[{"text":"Current configuration.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.property","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/configuration-swift.property","title":"configuration"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"kind":"symbol","abstract":[{"text":"Use this protocol to create palm validators.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","type":"topic","title":"PalmAutoCaptureDetectionValidator","role":"symbol","navigatorTitle":[{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureDetectionValidator","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","title":"Swift.CVarArg"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect palm in an image."}],"title":"PalmDetector","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PalmDetector"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetection":{"abstract":[{"type":"text","text":"The result of processing video frame during the palm auto capture process."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturedetection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","role":"symbol","title":"PalmAutoCaptureDetection","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureDetection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetection"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/ProcessingResult":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/processingresult","type":"topic","kind":"symbol","title":"PalmAutoCaptureController.ProcessingResult","abstract":[{"text":"The result returned from the processing of one image during the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/ProcessingResult","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ProcessingResult","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ProcessingResult"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureFrameParameters":{"abstract":[{"type":"text","text":"Information from the detection process about the detected palm."}],"type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureframeparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","role":"symbol","title":"PalmAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureFrameParameters","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureFrameParameters"}]},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","title":"NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","title":"PalmOutOfBoundsValidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmOutOfBoundsValidator","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator"},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"kind":"symbol","abstract":[{"text":"Validates confidence of the detected palm.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator","title":"PalmNotDetectedValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","type":"topic","role":"symbol","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmNotDetectedValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","role":"symbol","title":"PalmAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PalmAutoCaptureController","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureController"}]},"doc://DotPalmCore/SH":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"role":"collection","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Configuration-swift.class":{"type":"topic","navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"abstract":[{"text":"Configuration of the palm auto capture non-UI component.","type":"text"}],"kind":"symbol","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/configuration-swift.class","title":"PalmAutoCaptureController.Configuration","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Configuration-swift.class"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/process(sample:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/process(sample:)","navigatorTitle":[{"text":"processWithSample:error:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/process(sample:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"process","kind":"identifier"},{"text":"(","kind":"text"},{"text":"sample","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC6SampleC","text":"Sample","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B21AutoCaptureControllerC16ProcessingResultC","text":"ProcessingResult"}],"type":"topic","title":"process(sample:)","abstract":[{"type":"text","text":"Process an input sample and update the state."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController/Error":{"title":"PalmAutoCaptureController.Error","navigatorTitle":[{"text":"Error","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller\/error","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/Error"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureResult":{"title":"PalmAutoCaptureResult","role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocaptureresult","abstract":[{"type":"text","text":"The final result of the palm auto capture process."}],"navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureResult"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureResult"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"},"doc://DotPalmCore/documentation/DotPalmCore/DetectionPosition":{"url":"\/documentation\/dotpalmcore\/detectionposition","abstract":[{"text":"Position of the palm in the image.","type":"text"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","role":"symbol","title":"DetectionPosition","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DetectionPosition"}],"navigatorTitle":[{"kind":"identifier","text":"DetectionPosition"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","type":"topic","title":"BrightnessTooHighValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"kind":"symbol","abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","type":"topic","title":"SharpnessTooLowValidator","role":"symbol","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"title":"BrightnessTooLowValidator","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","kind":"symbol","type":"topic","abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"navigatorTitle":[{"text":"BrightnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"kind":"symbol","abstract":[{"text":"Validate whether the size of the detected palm is too small.","type":"text"}],"url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","title":"SizeTooSmallValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SizeTooSmallValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"kind":"symbol","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","type":"topic","title":"SizeTooLargeValidator","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooLargeValidator"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SizeTooLargeValidator","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTPPalmAutoCaptureController","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetection","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/DetectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureFrameParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureResult"],"title":"Palm auto capture process"},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"],"title":"Validators"},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/configuration-swift.property"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/init(configuration:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController\/process(sample:)"]}]},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"],"generated":true,"title":"Non-UI components"}],"path":"\/seeAlsoSections","op":"replace"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTPPalmAutoCaptureController"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1init(configuration:)\/title","value":"initWithConfiguration:","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1init(configuration:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithConfiguration:"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1configuration-swift.property\/title","value":"configuration","op":"replace"},{"value":[{"text":"configuration","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1configuration-swift.property\/fragments","op":"replace"},{"value":"DOTPPalmAutoCaptureDetectionValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetectionValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments"},{"op":"replace","value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments"},{"value":"DOTPPalmAutoCaptureDetection","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetection\/fragments","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetection"}]},{"op":"replace","value":"DOTPPalmAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureFrameParameters\/fragments","value":[{"text":"DOTPPalmAutoCaptureFrameParameters","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","op":"replace","value":"DOTPPalmOutOfBoundsValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","value":[{"kind":"identifier","text":"DOTPPalmOutOfBoundsValidator"}],"op":"replace"},{"op":"replace","value":"DOTPPalmNotDetectedValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title"},{"value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments"},{"value":"DOTPPalmAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureController"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments"},{"value":"processWithSample:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1process(sample:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController~1process(sample:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"processWithSample:error:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/title","op":"replace","value":"DOTPPalmAutoCaptureResult"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureResult"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureResult\/fragments"},{"value":"DOTPDetectionPosition","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1DetectionPosition\/fragments","value":[{"text":"DOTPDetectionPosition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title","value":"DOTPBrightnessTooHighValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments","value":[{"kind":"identifier","text":"DOTPBrightnessTooHighValidator"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title","value":"DOTPSharpnessTooLowValidator","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","op":"replace","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"op":"replace","value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title"},{"value":[{"kind":"identifier","text":"DOTPBrightnessTooLowValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","value":[{"kind":"identifier","text":"DOTPSizeTooSmallValidator"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","op":"replace","value":"DOTPSizeTooLargeValidator"},{"value":[{"kind":"identifier","text":"DOTPSizeTooLargeValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"}]}]}