{"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/init(modules:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/init(modules:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/init(modules:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"]]},"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(im)initWithModules:","symbolKind":"init","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"modules"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules"},{"kind":"text","text":")"}],"title":"init(modules:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/init(modules:)":{"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/init(modules:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"modules","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier"},{"text":")","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/init(modules:)","title":"init(modules:)","role":"symbol","abstract":[],"navigatorTitle":[{"text":"initWithModules:","kind":"identifier"}],"type":"topic","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration","title":"DotPalmLibraryConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules","title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"initWithModules:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithModules:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"modules"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"initWithModules:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration~1init(modules:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithModules:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration~1init(modules:)\/fragments"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/navigatorTitle"}]}]}