{"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/modules-swift.property","interfaceLanguage":"swift"},"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","kind":"typeIdentifier","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC"}],"modules":[{"name":"DotFingersCore"}],"role":"symbol","title":"modules","externalID":"c:@M@DotCore@objc(cs)DotPalmLibraryConfiguration(py)modules","navigatorTitle":[{"text":"modules","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Modules","preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class"}]}],"kind":"declarations"}],"abstract":[{"text":"Module configuration.","type":"text"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration"]]},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"navigatorTitle":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration","abstract":[{"type":"text","text":"Palm library configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration","title":"DotPalmLibraryConfiguration","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/Modules-swift.class":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.class","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/Modules-swift.class","title":"DotPalmLibraryConfiguration.Modules","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfigurationModules":{"fragments":[{"kind":"identifier","text":"DotPalmLibraryConfigurationModules"}],"url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfigurationmodules","abstract":[{"type":"text","text":"Palm library module configuration."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules","title":"DotPalmLibraryConfigurationModules","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/DotPalmLibraryConfiguration/modules-swift.property":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfiguration\/modules-swift.property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC","text":"Modules","kind":"typeIdentifier"}],"kind":"symbol","role":"symbol","title":"modules","abstract":[{"text":"Module configuration.","type":"text"}],"navigatorTitle":[{"text":"modules","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfingerscore\/dotpalmlibraryconfiguration\/modules-swift.property"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"modules","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"modules"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmLibraryConfigurationModules","text":"DotPalmLibraryConfigurationModules","kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotPalmLibraryConfigurationModules"},{"text":" * ","kind":"text"},{"text":"modules","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotPalmLibraryConfiguration","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotPalmLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration\/navigatorTitle"},{"op":"replace","value":"modules","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration~1modules-swift.property\/title"},{"op":"replace","value":[{"kind":"identifier","text":"modules"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotPalmLibraryConfiguration~1modules-swift.property\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}