{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Preview information.","type":"text"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle\/preview"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"externalID":"s:11DotDocument0B18AutoCaptureUiStateC4IdleC7previewAA0bcD7PreviewCvp","title":"preview","modules":[{"name":"DotDocument"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preview","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"variants":[{"paths":["\/documentation\/dotdocument\/documentautocaptureuistate\/idle\/preview"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Idle":{"abstract":[{"text":"Idle state.","type":"text"}],"navigatorTitle":[{"text":"Idle","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/idle","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle","title":"DocumentAutoCaptureUiState.Idle","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Idle","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCapturePreview":{"type":"topic","navigatorTitle":[{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"abstract":[{"type":"text","text":"Geometric properties of the preview. All rectangles are defined relative to the preview container."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCapturePreview","role":"symbol","kind":"symbol","title":"DocumentAutoCapturePreview","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCapturePreview","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturepreview"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"navigatorTitle":[{"text":"DocumentAutoCaptureUiState","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocaptureuistate","title":"DocumentAutoCaptureUiState","type":"topic"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","kind":"symbol","abstract":[{"type":"text","text":"version: 9.3.0"}],"type":"topic","url":"\/documentation\/dotdocument","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureUiState/Idle/preview":{"title":"preview","type":"topic","url":"\/documentation\/dotdocument\/documentautocaptureuistate\/idle\/preview","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preview"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCapturePreview","text":"DocumentAutoCapturePreview"}],"abstract":[{"type":"text","text":"Preview information."}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureUiState\/Idle\/preview","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentAutoCapturePreview","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/title"},{"value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCapturePreview\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDDocumentAutoCapturePreview"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/title","value":"DOTDDocumentAutoCaptureUiState","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureUiState"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureUiState\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureUiState","kind":"identifier"}],"op":"replace"}]}]}