{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ValidationFloat\/validate(value:interval:)"},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"kind":"text","text":", "},{"text":"interval","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"IntervalFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/IntervalFloat"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"languages":["swift"]}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacelite\/validationfloat\/validate(value:interval:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/validationfloat\/validate(value:interval:)"]}],"metadata":{"title":"validate(value:interval:)","role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTValidationFloat(cm)validateWithValue:interval:error:","roleHeading":"Type Method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"text":"value","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sf","text":"Float","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interval"},{"text":": ","kind":"text"},{"text":"IntervalFloat","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTIntervalFloat"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithValue:interval:error:"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ValidationFloat"]]},"references":{"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ValidationFloat":{"title":"ValidationFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"ValidationFloat","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"ValidationFloat","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/validationfloat","kind":"symbol","abstract":[{"type":"text","text":"Validate if a value belongs to an interval."}],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ValidationFloat"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/ValidationFloat/validate(value:interval:)":{"title":"validate(value:interval:)","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"text":"value","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Float","kind":"typeIdentifier","preciseIdentifier":"s:Sf"},{"text":", ","kind":"text"},{"text":"interval","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","text":"IntervalFloat"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","navigatorTitle":[{"text":"validateWithValue:interval:error:","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/validationfloat\/validate(value:interval:)","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/ValidationFloat\/validate(value:interval:)"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 8.1.0"}],"kind":"symbol","role":"collection"},"doc://com.innovatrics.dot.face.lite/documentation/DotFaceLite/IntervalFloat":{"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/IntervalFloat","title":"IntervalFloat","navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"type":"codeVoice","code":"Float"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"type":"text","text":" must be greater than the "},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"validateWithValue:interval:error:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"validateWithValue:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:f","text":"float"},{"kind":"text","text":") "},{"text":"value","kind":"internalParam"},{"kind":"text","text":" "},{"text":"interval:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTIntervalFloat","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.face.lite\/documentation\/DotFaceLite\/IntervalFloat"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"interval"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"kind":"text","text":" * *) "},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ValidationFloat\/title","value":"DOTValidationFloat","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ValidationFloat\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTValidationFloat"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ValidationFloat~1validate(value:interval:)\/title","value":"validateWithValue:interval:error:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"validateWithValue:interval:error:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1ValidationFloat~1validate(value:interval:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1IntervalFloat\/title","value":"DOTIntervalFloat"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.lite~1documentation~1DotFaceLite~1IntervalFloat\/fragments","op":"replace","value":[{"text":"DOTIntervalFloat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}