{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"]]},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"candidateSelection"}],"title":"PalmAutoCapturePhase.candidateSelection","roleHeading":"Case","symbolKind":"case","role":"symbol","navigatorTitle":[{"text":"DOTPPalmAutoCapturePhaseCandidateSelection","kind":"identifier"}],"externalID":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase@DOTPPalmAutoCapturePhaseCandidateSelection","modules":[{"name":"DotPalmCore"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/candidateSelection"},"abstract":[{"text":"Candidate selection is running.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"candidateSelection","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/candidateselection"]},{"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/candidateselection"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/candidateSelection":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/candidateSelection","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelection","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhaseCandidateSelection"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/candidateselection","abstract":[{"text":"Candidate selection is running.","type":"text"}],"title":"PalmAutoCapturePhase.candidateSelection","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase","abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"title":"PalmAutoCapturePhase","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"value":"DOTPPalmAutoCapturePhaseCandidateSelection","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhaseCandidateSelection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhaseCandidateSelection"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"DOTPPalmAutoCapturePhaseCandidateSelection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1candidateSelection\/title","op":"replace"},{"value":[{"text":"DOTPPalmAutoCapturePhaseCandidateSelection","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1candidateSelection\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","value":"DOTPPalmAutoCapturePhase","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}