{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/hash(into:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"metadata":{"role":"symbol","conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"title":"hash(into:)","modules":[{"relatedModules":["Swift"],"name":"DotPalmCore"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"kind":"text","text":")"}],"extendedModule":"Swift","symbolKind":"method"},"abstract":[{"type":"text","text":"Inherited from "},{"code":"RawRepresentable.hash(into:)","type":"codeVoice"},{"type":"text","text":"."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/RawRepresentable-Implementations"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/RawRepresentable-Implementations":{"type":"topic","abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/rawrepresentable-implementations","role":"collectionGroup","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/RawRepresentable-Implementations","kind":"article"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmautocapturephase","title":"PalmAutoCapturePhase","role":"symbol","type":"topic","abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","role":"collection","type":"topic","abstract":[{"type":"text","text":"version: 9.0.1"}],"kind":"symbol","title":"DotPalmCore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/hash(into:)":{"type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturephase\/hash(into:)","title":"hash(into:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","abstract":[],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/hash(into:)"}},"variantOverrides":[{"patch":[{"value":"DOTPPalmAutoCapturePhase","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}