{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/init(rawvalue:)"]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"title":"init(rawValue:)","roleHeading":"Initializer","externalID":"s:11DotPalmCore0B16AutoCapturePhaseO8rawValueACSgSi_tcfc","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/init(rawValue:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","type":"topic","title":"PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/init(rawValue:)":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/init(rawvalue:)","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTPPalmAutoCapturePhase","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}