{"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/preCandidateSelection","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/precandidateselection"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmautocapturephase\/precandidateselection"]}],"sections":[],"metadata":{"title":"PalmAutoCapturePhase.preCandidateSelection","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"navigatorTitle":[{"text":"DOTPPalmAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"roleHeading":"Case","role":"symbol","externalID":"c:@M@DotPalmCore@E@DOTPPalmAutoCapturePhase@DOTPPalmAutoCapturePhasePreCandidateSelection","symbolKind":"case","modules":[{"name":"DotPalmCore"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Pre-candidate selection is running."}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase"]]},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase/preCandidateSelection":{"url":"\/documentation\/dotpalmcore\/palmautocapturephase\/precandidateselection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase\/preCandidateSelection","kind":"symbol","title":"PalmAutoCapturePhase.preCandidateSelection","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"preCandidateSelection"}],"navigatorTitle":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhasePreCandidateSelection"}],"abstract":[{"type":"text","text":"Pre-candidate selection is running."}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCapturePhase":{"role":"symbol","url":"\/documentation\/dotpalmcore\/palmautocapturephase","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PalmAutoCapturePhase","kind":"identifier"}],"abstract":[{"text":"Phase of the palm auto capture process.","type":"text"}],"navigatorTitle":[{"text":"PalmAutoCapturePhase","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCapturePhase","type":"topic","title":"PalmAutoCapturePhase"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","type":"topic","kind":"symbol","role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","title":"DotPalmCore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"DOTPPalmAutoCapturePhasePreCandidateSelection","path":"\/metadata\/title"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhasePreCandidateSelection"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhasePreCandidateSelection"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTPPalmAutoCapturePhasePreCandidateSelection","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1preCandidateSelection\/title"},{"op":"replace","value":[{"text":"DOTPPalmAutoCapturePhasePreCandidateSelection","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase~1preCandidateSelection\/fragments"},{"op":"replace","value":"DOTPPalmAutoCapturePhase","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTPPalmAutoCapturePhase"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCapturePhase\/navigatorTitle"}]}]}