{"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:"},"metadata":{"navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","kind":"identifier"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDBaseDocumentAutoCaptureConfiguration(im)initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","symbolKind":"method","role":"symbol","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","kind":"identifier"}],"modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method"},"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithCommon:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","text":"DOTCommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration"},{"text":" *) ","kind":"text"},{"text":"common","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"camera:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTCameraConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTCameraConfiguration"},{"text":" *) ","kind":"text"},{"text":"camera","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"autoCapture:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)DOTAutoCaptureConfiguration"},{"text":" *) ","kind":"text"},{"text":"autoCapture","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureQualityAttributeThresholds","text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds"},{"text":" *) ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"validationMode:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDValidationMode","text":"DOTDValidationMode","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode"},{"text":") ","kind":"text"},{"text":"validationMode","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"mrzValidation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDMrzValidation","text":"DOTDMrzValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation"},{"text":") ","kind":"text"},{"text":"mrzValidation","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"barcodeValidation:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotDocument@E@DOTDBarcodeValidation","text":"DOTDBarcodeValidation","kind":"typeIdentifier","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"},{"text":") ","kind":"text"},{"text":"barcodeValidation","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:barcodevalidation:"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","url":"\/documentation\/dotdocument","title":"DotDocument","abstract":[{"type":"text","text":"version: 9.2.1"}]},"doc://DotDocument/documentation/DotDocument/CommonConfiguration":{"abstract":[{"type":"text","text":"Common configuration for all components."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic","role":"symbol","title":"CommonConfiguration","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"CommonConfiguration","kind":"identifier"}],"url":"\/documentation\/dotdocument\/commonconfiguration"},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration","title":"DOTDBaseDocumentAutoCaptureConfiguration","fragments":[{"kind":"identifier","text":"DOTDBaseDocumentAutoCaptureConfiguration"}],"abstract":[{"type":"text","text":"Configuration options for the document auto capture process."}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument/ValidationMode":{"navigatorTitle":[{"kind":"identifier","text":"ValidationMode"}],"url":"\/documentation\/dotdocument\/validationmode","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/ValidationMode","title":"ValidationMode","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"ValidationMode"}],"kind":"symbol"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","kind":"symbol","title":"BarcodeValidation","url":"\/documentation\/dotdocument\/barcodevalidation","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BarcodeValidation","kind":"identifier"}],"abstract":[{"type":"text","text":"Mode of barcode validation."}],"role":"symbol","navigatorTitle":[{"text":"BarcodeValidation","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DOTDBaseDocumentAutoCaptureConfiguration/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:":{"abstract":[{"type":"text","text":"Create the document auto capture configuration."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDBaseDocumentAutoCaptureConfiguration\/initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","navigatorTitle":[{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","kind":"identifier"}],"type":"topic","role":"symbol","title":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","kind":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"initWithCommon:camera:autoCapture:qualityAttributeThresholds:validationMode:mrzValidation:barcodeValidation:","kind":"identifier"}],"url":"\/documentation\/dotdocument\/dotdbasedocumentautocaptureconfiguration\/initwithcommon:camera:autocapture:qualityattributethresholds:validationmode:mrzvalidation:barcodevalidation:"},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureQualityAttributeThresholds":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureQualityAttributeThresholds","kind":"symbol","title":"DocumentAutoCaptureQualityAttributeThresholds","type":"topic","url":"\/documentation\/dotdocument\/documentautocapturequalityattributethresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}],"abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the document auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureQualityAttributeThresholds"}]},"doc://DotDocument/documentation/DotDocument/MrzValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzValidation","url":"\/documentation\/dotdocument\/mrzvalidation","abstract":[{"text":"Mode of MRZ (Machine Readable Zone) validation.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzValidation","kind":"identifier"}],"navigatorTitle":[{"text":"MrzValidation","kind":"identifier"}],"type":"topic","kind":"symbol","role":"symbol","title":"MrzValidation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/title","value":"DOTCommonConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/fragments","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CommonConfiguration\/navigatorTitle","value":[{"text":"DOTCommonConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/title","value":"DOTDValidationMode"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/fragments","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1ValidationMode\/navigatorTitle","value":[{"text":"DOTDValidationMode","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","value":"DOTDBarcodeValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/title","value":"DOTDDocumentAutoCaptureQualityAttributeThresholds"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTDDocumentAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/title","value":"DOTDMrzValidation"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/fragments","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzValidation\/navigatorTitle","value":[{"text":"DOTDMrzValidation","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}