{"kind":"symbol","metadata":{"title":"evaluatePitch","externalID":"c:@M@DotFaceCore@objc(cs)DOTFHeadPoseQuery(py)evaluatePitch","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"evaluatePitch","kind":"identifier"}],"symbolKind":"property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"evaluatePitch","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"DotFaceCore"}]},"sections":[],"abstract":[{"type":"text","text":"Pitch evaluation flag."}],"variants":[{"paths":["\/documentation\/dotfacecore\/headposequery\/evaluatepitch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/headposequery\/evaluatepitch"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePitch"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluatePitch","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery/evaluatePitch":{"role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"evaluatePitch"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"title":"evaluatePitch","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery\/evaluatePitch","url":"\/documentation\/dotfacecore\/headposequery\/evaluatepitch","abstract":[{"text":"Pitch evaluation flag.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"evaluatePitch"}],"kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/HeadPoseQuery":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/HeadPoseQuery","type":"topic","role":"symbol","url":"\/documentation\/dotfacecore\/headposequery","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"HeadPoseQuery","kind":"identifier"}],"abstract":[{"text":"Head pose query specifies which head pose attributes should be evaluated.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"HeadPoseQuery"}],"title":"HeadPoseQuery","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"evaluatePitch","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"evaluatePitch","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"evaluatePitch","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"evaluatePitch","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluatePitch\/title","op":"replace"},{"value":[{"text":"evaluatePitch","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery~1evaluatePitch\/fragments","op":"replace"},{"op":"replace","value":"DOTFHeadPoseQuery","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/title"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/fragments"},{"op":"replace","value":[{"text":"DOTFHeadPoseQuery","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1HeadPoseQuery\/navigatorTitle"}]}]}