{"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator"},"seeAlsoSections":[{"generated":true,"title":"Validators","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator"]},{"paths":["\/documentation\/dotpalmcore\/brightnesstoohighvalidator"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships"},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init(threshold:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/defaultThreshold"],"title":"Type Properties"}],"abstract":[{"text":"Validate maximum brightness of the detected palm.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(DOTPBrightnessTooHighValidator) ","kind":"text"},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","type":"heading","level":2,"text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"To use this validator also following validators must be applied: "},{"type":"codeVoice","code":"PalmOutOfBoundsValidator"},{"text":".","type":"text"}]}]}],"metadata":{"modules":[{"name":"DotPalmCore"}],"navigatorTitle":[{"kind":"identifier","text":"BrightnessTooHighValidator"}],"title":"BrightnessTooHighValidator","externalID":"c:@M@DotPalmCore@objc(cs)DOTPBrightnessTooHighValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","role":"symbol"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmOutOfBoundsValidator":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmOutOfBoundsValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","abstract":[{"text":"Validate if the detected palm is within the bounds of the image.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmoutofboundsvalidator","title":"PalmOutOfBoundsValidator","navigatorTitle":[{"text":"PalmOutOfBoundsValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/init()":{"kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init()","abstract":[{"type":"text","text":"Initialize with default threshold."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/init()","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/dependencyIdentifiers":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"dependencyIdentifiers","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":">","kind":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/dependencyIdentifiers","abstract":[{"text":"Set of validator identifiers which represents a set of dependencies for this validator.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/dependencyidentifiers","title":"dependencyIdentifiers","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureController":{"title":"PalmAutoCaptureController","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturecontroller","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmAutoCaptureController"}],"navigatorTitle":[{"text":"PalmAutoCaptureController","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureController","abstract":[{"text":"Non-UI component for the palm auto capture process.","type":"text"}],"role":"symbol","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/defaultThreshold":{"kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultThreshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/defaultThreshold","abstract":[{"type":"text","text":"Default threshold."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/defaultthreshold","title":"defaultThreshold","navigatorTitle":[{"kind":"identifier","text":"defaultThreshold"}]},"doc://DotPalmCore/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmAutoCaptureDetectionValidator":{"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","abstract":[{"type":"text","text":"Use this protocol to create palm validators."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmautocapturedetectionvalidator","title":"PalmAutoCaptureDetectionValidator","navigatorTitle":[{"kind":"identifier","text":"PalmAutoCaptureDetectionValidator"}]},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/SQ":{"type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SQ","title":"Swift.Equatable"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/validate(palmAutoCaptureFrameParameters:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"palmAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"text":"PalmAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/validate(palmAutoCaptureFrameParameters:)","abstract":[{"type":"text","text":"Validate brightness of the detected palm."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/validate(palmautocaptureframeparameters:)","title":"validate(palmAutoCaptureFrameParameters:)","navigatorTitle":[{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/init(threshold:)":{"kind":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"threshold","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init(threshold:)","abstract":[{"text":"Initialize with custom threshold.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/init(threshold:)","title":"init(threshold:)","navigatorTitle":[{"text":"initWithThreshold:error:","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SharpnessTooLowValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SharpnessTooLowValidator"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","role":"symbol","abstract":[{"text":"Validate minimum sharpness of the detected palm.","type":"text"}],"title":"SharpnessTooLowValidator","url":"\/documentation\/dotpalmcore\/sharpnesstoolowvalidator","navigatorTitle":[{"text":"SharpnessTooLowValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmNotDetectedValidator":{"type":"topic","title":"PalmNotDetectedValidator","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","abstract":[{"type":"text","text":"Validates confidence of the detected palm."}],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"PalmNotDetectedValidator","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"PalmNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmnotdetectedvalidator"},"doc://DotPalmCore/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/s7CVarArgP"},"doc://DotPalmCore/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/SH"},"doc://DotPalmCore/documentation/DotPalmCore":{"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","role":"collection","abstract":[{"type":"text","text":"version: 8.13.0"}],"type":"topic","title":"DotPalmCore","url":"\/documentation\/dotpalmcore"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/threshold":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"threshold"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/threshold","abstract":[{"text":"Current maximal accepted brightness.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/threshold","title":"threshold","navigatorTitle":[{"text":"threshold","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooLargeValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SizeTooLargeValidator","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","title":"SizeTooLargeValidator","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too large."}],"url":"\/documentation\/dotpalmcore\/sizetoolargevalidator","navigatorTitle":[{"text":"SizeTooLargeValidator","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/SizeTooSmallValidator":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SizeTooSmallValidator","kind":"identifier"}],"title":"SizeTooSmallValidator","abstract":[{"type":"text","text":"Validate whether the size of the detected palm is too small."}],"role":"symbol","url":"\/documentation\/dotpalmcore\/sizetoosmallvalidator","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SizeTooSmallValidator"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator/identifier":{"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/identifier","abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator\/identifier","title":"identifier","navigatorTitle":[{"text":"identifier","kind":"identifier"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooLowValidator":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BrightnessTooLowValidator"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator","abstract":[{"text":"Validate minimum brightness of the detected palm.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoolowvalidator","title":"BrightnessTooLowValidator","navigatorTitle":[{"kind":"identifier","text":"BrightnessTooLowValidator"}]},"doc://DotPalmCore/documentation/DotPalmCore/BrightnessTooHighValidator":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BrightnessTooHighValidator","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator","abstract":[{"type":"text","text":"Validate maximum brightness of the detected palm."}],"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/brightnesstoohighvalidator","title":"BrightnessTooHighValidator","navigatorTitle":[{"text":"BrightnessTooHighValidator","kind":"identifier"}]},"doc://DotPalmCore/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"DOTPBrightnessTooHighValidator"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}]},{"op":"replace","value":[{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/dependencyIdentifiers","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/identifier","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/threshold"]},{"title":"Instance Methods","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init()","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/init(threshold:)","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/validate(palmAutoCaptureFrameParameters:)"]},{"title":"Type Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooHighValidator\/defaultThreshold"]}],"path":"\/topicSections"},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"]},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator"]}],"op":"replace"},{"path":"\/seeAlsoSections","op":"replace","value":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmAutoCaptureDetectionValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmNotDetectedValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmOutOfBoundsValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooLargeValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SizeTooSmallValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/SharpnessTooLowValidator","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BrightnessTooLowValidator"],"title":"Validators","generated":true}]},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTPPalmOutOfBoundsValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/title","op":"replace"},{"value":[{"text":"DOTPPalmOutOfBoundsValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmOutOfBoundsValidator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1init()\/title","value":"init"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1init()\/fragments","value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"dependencyIdentifiers","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1dependencyIdentifiers\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1dependencyIdentifiers\/fragments","value":[{"kind":"identifier","text":"dependencyIdentifiers"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/title","op":"replace","value":"DOTPPalmAutoCaptureController"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureController\/fragments","op":"replace","value":[{"text":"DOTPPalmAutoCaptureController","kind":"identifier"}]},{"value":"defaultThreshold","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1defaultThreshold\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1defaultThreshold\/fragments","value":[{"kind":"identifier","text":"defaultThreshold"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/title","value":"DOTPPalmAutoCaptureDetectionValidator","op":"replace"},{"value":[{"kind":"identifier","text":"DOTPPalmAutoCaptureDetectionValidator"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmAutoCaptureDetectionValidator\/fragments","op":"replace"},{"value":"validateWithPalmAutoCaptureFrameParameters:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1validate(palmAutoCaptureFrameParameters:)\/title"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1validate(palmAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithPalmAutoCaptureFrameParameters:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1init(threshold:)\/title","value":"initWithThreshold:error:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithThreshold:error:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1init(threshold:)\/fragments"},{"value":"DOTPSharpnessTooLowValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SharpnessTooLowValidator\/fragments","value":[{"text":"DOTPSharpnessTooLowValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/title","value":"DOTPPalmNotDetectedValidator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmNotDetectedValidator\/fragments","value":[{"text":"DOTPPalmNotDetectedValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1threshold\/title","op":"replace","value":"threshold"},{"value":[{"text":"threshold","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1threshold\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/title","value":"DOTPSizeTooLargeValidator"},{"op":"replace","value":[{"text":"DOTPSizeTooLargeValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooLargeValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/title","value":"DOTPSizeTooSmallValidator"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1SizeTooSmallValidator\/fragments","value":[{"text":"DOTPSizeTooSmallValidator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1identifier\/title","value":"identifier"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator~1identifier\/fragments","op":"replace","value":[{"text":"identifier","kind":"identifier"}]},{"value":"DOTPBrightnessTooLowValidator","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/title","op":"replace"},{"value":[{"text":"DOTPBrightnessTooLowValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooLowValidator\/fragments","op":"replace"},{"value":"DOTPBrightnessTooHighValidator","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/title"},{"op":"replace","value":[{"text":"DOTPBrightnessTooHighValidator","kind":"identifier"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BrightnessTooHighValidator\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}