{"abstract":[{"text":"Captured face image.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/bgrrawimage"]},{"paths":["\/documentation\/dotfacecore\/multirangelivenessresult\/bgrrawimage"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/bgrRawImage"},"kind":"symbol","metadata":{"title":"bgrRawImage","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFMultiRangeLivenessResult(py)bgrRawImage","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bgrRawImage"},{"text":": ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"navigatorTitle":[{"text":"bgrRawImage","kind":"identifier"}],"role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgrRawImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"BgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult","title":"MultiRangeLivenessResult","role":"symbol","abstract":[{"type":"text","text":"The final result of the Multi-Range Liveness process."}],"navigatorTitle":[{"kind":"identifier","text":"MultiRangeLivenessResult"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"MultiRangeLivenessResult","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessresult","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/MultiRangeLivenessResult/bgrRawImage":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bgrRawImage","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage"}],"title":"bgrRawImage","kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/MultiRangeLivenessResult\/bgrRawImage","abstract":[{"type":"text","text":"Captured face image."}],"navigatorTitle":[{"text":"bgrRawImage","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/multirangelivenessresult\/bgrrawimage","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BgrRawImage":{"title":"BgrRawImage","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","role":"symbol","url":"\/documentation\/dotfacecore\/bgrrawimage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","abstract":[{"text":"version: 8.17.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","kind":"symbol","url":"\/documentation\/dotfacecore","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"bgrRawImage","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"bgrRawImage"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTBgrRawImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bgrRawImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTFMultiRangeLivenessResult","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult\/fragments","value":[{"text":"DOTFMultiRangeLivenessResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1bgrRawImage\/title","value":"bgrRawImage"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1MultiRangeLivenessResult~1bgrRawImage\/fragments","value":[{"text":"bgrRawImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BgrRawImage\/fragments","value":[{"kind":"identifier","text":"DOTBgrRawImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}