{"metadata":{"role":"collectionGroup","title":"Error Implementations","modules":[{"name":"DotNfc"}]},"kind":"article","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/Error-Implementations"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/localizedDescription"],"generated":true}],"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/error-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"role":"symbol","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"title":"NfcTravelDocumentReader","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/localizedDescription":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"localizedDescription","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic","url":"\/documentation\/dotnfc\/nfckey\/error\/localizeddescription","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/localizedDescription","kind":"symbol","title":"localizedDescription"},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.7.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcKey":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","type":"topic","url":"\/documentation\/dotnfc\/nfckey","title":"NfcKey","deprecated":true,"role":"symbol","abstract":[{"text":"NFC password created from document number, date of expiry and date of birth of MRZ.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}]},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"url":"\/documentation\/dotnfc\/nfckey\/error","title":"NfcKey.Error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","role":"symbol","abstract":[],"deprecated":true,"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"type":"topic","kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}]},{"op":"replace","value":"DOTNNfcKey","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title"},{"value":[{"kind":"identifier","text":"DOTNNfcKey"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments"}]}]}