{"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DotSdkConfiguration(py)libraries","symbolKind":"property","role":"symbol","modules":[{"name":"DotFaceLite"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"libraries"}],"fragments":[{"kind":"identifier","text":"libraries"}],"title":"libraries"},"abstract":[{"type":"text","text":"Libraries configuration."}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"Libraries","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)Libraries"},{"text":" * ","kind":"text"},{"text":"libraries","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}],"variants":[{"paths":["\/documentation\/dotfacelite\/dotsdkconfiguration\/libraries"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/libraries"},"kind":"symbol","references":{"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration","type":"topic","role":"symbol","title":"DotSdkConfiguration","url":"\/documentation\/dotfacelite\/dotsdkconfiguration","kind":"symbol","fragments":[{"kind":"identifier","text":"DotSdkConfiguration"}],"abstract":[{"text":"The ","type":"text"},{"text":"DotSdk","type":"text"},{"text":" configuration.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/Libraries":{"url":"\/documentation\/dotfacelite\/libraries","title":"Libraries","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"Libraries"}],"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Container for library configurations."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/Libraries","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Libraries"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","kind":"symbol","role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite","type":"topic","abstract":[{"type":"text","text":"version: 9.0.2"}]},"doc://DotFaceLite/documentation/DotFaceLite/DotSdkConfiguration/libraries":{"abstract":[{"text":"Libraries configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/dotsdkconfiguration\/libraries","type":"topic","kind":"symbol","fragments":[{"kind":"identifier","text":"libraries"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DotSdkConfiguration\/libraries","role":"symbol","title":"libraries"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"Libraries","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/title"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/fragments"},{"value":[{"kind":"identifier","text":"Libraries"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1Libraries\/navigatorTitle"}]}]}