{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator\/dependencyIdentifiers"},"kind":"symbol","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator"]]},"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"dependencyIdentifiers"}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":">","kind":"text"}],"title":"dependencyIdentifiers","modules":[{"name":"DotDocument"}],"symbolKind":"property","role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotPresentValidator(py)dependencyIdentifiers"},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/dependencyidentifiers"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/dependencyidentifiers"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":">","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator/dependencyIdentifiers":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"dependencyIdentifiers","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sh","text":"Set","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">","kind":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator\/dependencyIdentifiers","title":"dependencyIdentifiers","abstract":[{"type":"text","text":"Set of validator identifiers which represents a set of dependencies for this validator."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/dependencyidentifiers","kind":"symbol","type":"topic","navigatorTitle":[{"text":"dependencyIdentifiers","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotPresentValidator","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","title":"MrzNotPresentValidator","abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"role":"symbol","url":"\/documentation\/dotdocument\/mrznotpresentvalidator","kind":"symbol","type":"topic","navigatorTitle":[{"text":"MrzNotPresentValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"type":"topic","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","kind":"symbol","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"dependencyIdentifiers"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator~1dependencyIdentifiers\/title","op":"replace","value":"dependencyIdentifiers"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator~1dependencyIdentifiers\/fragments","op":"replace","value":[{"text":"dependencyIdentifiers","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/title","op":"replace","value":"DOTDMrzNotPresentValidator"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","op":"replace","value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/navigatorTitle","op":"replace","value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}]}]}]}