{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator\/identifier","interfaceLanguage":"swift"},"abstract":[{"text":"Validator identifier to address failed validation.","type":"text"}],"metadata":{"symbolKind":"property","role":"symbol","title":"identifier","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotPresentValidator(py)identifier","roleHeading":"Instance Property","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"text":"identifier","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator"]]},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/identifier"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/identifier"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"identifier","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["iOS"]}]}],"references":{"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator/identifier":{"kind":"symbol","role":"symbol","title":"identifier","abstract":[{"type":"text","text":"Validator identifier to address failed validation."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator\/identifier","url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/identifier","type":"topic","navigatorTitle":[{"kind":"identifier","text":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzNotPresentValidator":{"type":"topic","abstract":[{"type":"text","text":"Validate if Machine Readable Zone is present."}],"title":"MrzNotPresentValidator","kind":"symbol","role":"symbol","url":"\/documentation\/dotdocument\/mrznotpresentvalidator","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzNotPresentValidator","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"MrzNotPresentValidator","kind":"identifier"}],"navigatorTitle":[{"text":"MrzNotPresentValidator","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.6.0","type":"text"}],"url":"\/documentation\/dotdocument","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"identifier","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"identifier","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"identifier"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"identifier","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator~1identifier\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator~1identifier\/fragments","value":[{"text":"identifier","kind":"identifier"}]},{"value":"DOTDMrzNotPresentValidator","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments","value":[{"kind":"identifier","text":"DOTDMrzNotPresentValidator"}]}]}]}