{"kind":"symbol","identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"text":": ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"modules":[{"name":"DotDocument"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@DotDocument@objc(cs)DOTDMrzNotPresentValidator(im)validateWithDocumentAutoCaptureFrameParameters:","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"title":"validate(documentAutoCaptureFrameParameters:)","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"validate","kind":"identifier"},{"kind":"text","text":"("},{"text":"documentAutoCaptureFrameParameters","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentAutoCaptureFrameParameters","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"documentAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"Returns "},{"type":"codeVoice","code":"false"},{"type":"text","text":" for document with missing MRZ."}],"type":"paragraph"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator"]]},"variants":[{"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrznotpresentvalidator\/validate(documentautocaptureframeparameters:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Validate presence of MRZ on the detected document."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","abstract":[{"text":"version: 8.2.0","type":"text"}],"kind":"symbol","role":"collection","type":"topic","title":"DotDocument","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator/validate(documentAutoCaptureFrameParameters:)":{"url":"\/documentation\/dotdocument\/mrznotpresentvalidator\/validate(documentautocaptureframeparameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"validate","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"documentAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DocumentAutoCaptureFrameParameters","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator\/validate(documentAutoCaptureFrameParameters:)","title":"validate(documentAutoCaptureFrameParameters:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"abstract":[{"text":"Validate presence of MRZ on the detected document.","type":"text"}],"role":"symbol"},"doc://com.innovatrics.dot.document/documentation/DotDocument/MrzNotPresentValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzNotPresentValidator","kind":"identifier"}],"abstract":[{"text":"Validate if Machine Readable Zone is present.","type":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/MrzNotPresentValidator","kind":"symbol","url":"\/documentation\/dotdocument\/mrznotpresentvalidator","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzNotPresentValidator"}],"title":"MrzNotPresentValidator"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureFrameParameters":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureFrameParameters","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Information from the detection process about the detected document."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"symbol","role":"symbol","title":"DocumentAutoCaptureFrameParameters","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureFrameParameters"}],"url":"\/documentation\/dotdocument\/documentautocaptureframeparameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"validateWithDocumentAutoCaptureFrameParameters:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithDocumentAutoCaptureFrameParameters:"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureFrameParameters","text":"DOTDDocumentAutoCaptureFrameParameters"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentAutoCaptureFrameParameters"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/title","value":"validateWithDocumentAutoCaptureFrameParameters:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator~1validate(documentAutoCaptureFrameParameters:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"validateWithDocumentAutoCaptureFrameParameters:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/title","op":"replace","value":"DOTDMrzNotPresentValidator"},{"value":[{"text":"DOTDMrzNotPresentValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1MrzNotPresentValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/title","value":"DOTDDocumentAutoCaptureFrameParameters"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureFrameParameters\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureFrameParameters"}],"op":"replace"}]}]}