{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DotPalmDetectionModuleConfiguration","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"externalID":"s:7DotCore0A24PalmLibraryConfigurationC7ModulesC9detectionAA0ac15DetectionModuleE0Cvp","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"detection","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration","kind":"typeIdentifier"}],"symbolKind":"property","title":"detection","modules":[{"name":"DotFaceCore"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class"]]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"abstract":[{"text":"Palm library configuration.","type":"text"}],"kind":"symbol","title":"DotPalmLibraryConfiguration","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration","role":"symbol","type":"topic","navigatorTitle":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/Modules-swift.class/detection":{"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"detection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DotPalmDetectionModuleConfiguration","text":"DotPalmDetectionModuleConfiguration"}],"type":"topic","abstract":[],"title":"detection","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class\/detection","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class\/detection","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","type":"topic","role":"collection","kind":"symbol","title":"DotFaceCore","abstract":[{"text":"version: 9.0.2","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmDetectionModuleConfiguration":{"kind":"symbol","navigatorTitle":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/dotpalmdetectionmoduleconfiguration","abstract":[{"type":"text","text":"Palm detection module configuration."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmDetectionModuleConfiguration","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"title":"DotPalmDetectionModuleConfiguration"},"doc://DotFaceCore/documentation/DotFaceCore/DotPalmLibraryConfiguration/Modules-swift.class":{"role":"symbol","abstract":[{"type":"text","text":"Palm library module configuration."}],"type":"topic","url":"\/documentation\/dotfacecore\/dotpalmlibraryconfiguration\/modules-swift.class","title":"DotPalmLibraryConfiguration.Modules","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotPalmLibraryConfiguration\/Modules-swift.class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Modules"}],"navigatorTitle":[{"kind":"identifier","text":"Modules"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/title","value":"DotPalmLibraryConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/fragments","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmLibraryConfiguration\/navigatorTitle","value":[{"text":"DotPalmLibraryConfiguration","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/title","value":"DotPalmDetectionModuleConfiguration","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/fragments","value":[{"kind":"identifier","text":"DotPalmDetectionModuleConfiguration"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotPalmDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotPalmDetectionModuleConfiguration","kind":"identifier"}],"op":"replace"}]}]}