{"metadata":{"modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersNotDetectedValidator(im)initWithMinConfidenceThreshold:error:","symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"title":"init(minConfidenceThreshold:)","role":"symbol","roleHeading":"Initializer","navigatorTitle":[{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"minConfidenceThreshold","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/init(minConfidenceThreshold:)","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/init(minconfidencethreshold:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/init(minconfidencethreshold:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FingersNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","title":"FingersNotDetectedValidator","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator/init(minConfidenceThreshold:)":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"minConfidenceThreshold"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"},{"kind":"text","text":") "},{"kind":"keyword","text":"throws"}],"navigatorTitle":[{"kind":"identifier","text":"initWithMinConfidenceThreshold:error:"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/init(minconfidencethreshold:)","abstract":[{"type":"text","text":"Initialize with custom threshold."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/init(minConfidenceThreshold:)","title":"init(minConfidenceThreshold:)","role":"symbol","kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithMinConfidenceThreshold:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"initWithMinConfidenceThreshold:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":") ","kind":"text"},{"text":"minConfidenceThreshold","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title","value":"DOTFGFingersNotDetectedValidator"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments","value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1init(minConfidenceThreshold:)\/title","value":"initWithMinConfidenceThreshold:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1init(minConfidenceThreshold:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMinConfidenceThreshold:error:","kind":"identifier"}]}]}]}