{"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","text":"FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"fingersAutoCaptureFrameParameters","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame parameters to validate."}]}]}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns "},{"code":"false","type":"codeVoice"},{"type":"text","text":" to indicate there were no suitable fingers detected in the image."}]}],"kind":"content"}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Validate confidence of the detected fingers.","type":"text"}],"metadata":{"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"validate(fingersAutoCaptureFrameParameters:)","modules":[{"name":"DotFingersCore"}],"externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersNotDetectedValidator(im)validateWithFingersAutoCaptureFrameParameters:","roleHeading":"Instance Method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}]},"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/validate(fingersAutoCaptureFrameParameters:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/validate(fingersautocaptureframeparameters:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/validate(fingersautocaptureframeparameters:)"]}],"references":{"doc://DotFingersCore/documentation/DotFingersCore":{"title":"DotFingersCore","abstract":[{"type":"text","text":"version: 9.5.0"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","kind":"symbol","role":"collection","url":"\/documentation\/dotfingerscore","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FingersNotDetectedValidator","kind":"identifier"}],"navigatorTitle":[{"text":"FingersNotDetectedValidator","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator","abstract":[{"type":"text","text":"Validates confidence of the detected fingers."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator","title":"FingersNotDetectedValidator","role":"symbol","kind":"symbol","type":"topic"},"doc://DotFingersCore/documentation/DotFingersCore/FingersNotDetectedValidator/validate(fingersAutoCaptureFrameParameters:)":{"type":"topic","abstract":[{"text":"Validate confidence of the detected fingers.","type":"text"}],"title":"validate(fingersAutoCaptureFrameParameters:)","url":"\/documentation\/dotfingerscore\/fingersnotdetectedvalidator\/validate(fingersautocaptureframeparameters:)","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersNotDetectedValidator\/validate(fingersAutoCaptureFrameParameters:)","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"validate"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fingersAutoCaptureFrameParameters"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FingersAutoCaptureFrameParameters","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}]},"doc://DotFingersCore/documentation/DotFingersCore/FingersAutoCaptureFrameParameters":{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"kind":"symbol","role":"symbol","title":"FingersAutoCaptureFrameParameters","abstract":[{"type":"text","text":"Information from the detection process about the detected fingers."}],"navigatorTitle":[{"kind":"identifier","text":"FingersAutoCaptureFrameParameters"}],"type":"topic","url":"\/documentation\/dotfingerscore\/fingersautocaptureframeparameters"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"validateWithFingersAutoCaptureFrameParameters:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"validateWithFingersAutoCaptureFrameParameters:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"DOTFGFingersAutoCaptureFrameParameters","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureFrameParameters","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingersAutoCaptureFrameParameters"},{"text":" *) ","kind":"text"},{"text":"fingersAutoCaptureFrameParameters","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"Frame parameters to validate.","type":"text"}],"type":"paragraph"}],"name":"fingersAutoCaptureFrameParameters"}]},"path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"Returns ","type":"text"},{"type":"codeVoice","code":"false"},{"text":" to indicate there were no suitable fingers detected in the image.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"DOTFGFingersNotDetectedValidator","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersNotDetectedValidator"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator\/navigatorTitle","value":[{"text":"DOTFGFingersNotDetectedValidator","kind":"identifier"}]},{"op":"replace","value":"validateWithFingersAutoCaptureFrameParameters:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1validate(fingersAutoCaptureFrameParameters:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"validateWithFingersAutoCaptureFrameParameters:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersNotDetectedValidator~1validate(fingersAutoCaptureFrameParameters:)\/fragments"},{"op":"replace","value":"DOTFGFingersAutoCaptureFrameParameters","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureFrameParameters"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingersAutoCaptureFrameParameters\/navigatorTitle"}]}]}