{"metadata":{"externalID":"s:11DotFaceLite0B21AutoCaptureControllerC13ConfigurationC6common04autoE013detectionArea10validatorsAE0A4Core06CommonG0C_0aE00deG0CAJ15RectangleDoubleCSgSayAA0bdE24FrameParametersValidator_pGtKcfc","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"common"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"autoCapture"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"FaceAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"modules":[{"name":"DotFaceLite"}],"symbolKind":"init","role":"symbol","title":"init(common:autoCapture:detectionArea:validators:)"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"text":" = .init(), ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"kind":"text","text":" = try! .init(\n                minValidSamplesInRowToStartCandidateSelection: Defaults.minValidSamplesInRowToStartCandidateSelection,\n                candidateSelectionDurationMillis: Defaults.candidateSelectionDurationMillis\n            ), "},{"kind":"externalParam","text":"detectionArea"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","text":"RectangleDouble"},{"kind":"text","text":"? = nil, "},{"kind":"externalParam","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator","text":"FaceAutoCaptureFrameParametersValidator"},{"kind":"text","text":"]) "},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:detectionArea:validators:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/init(common:autocapture:detectionarea:validators:)"]}],"abstract":[{"type":"text","text":"Create face auto capture controller configuration."}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CommonConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CommonConfiguration","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Common configuration for all components."}],"url":"\/documentation\/dotfacelite\/commonconfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"CommonConfiguration"}],"title":"CommonConfiguration","navigatorTitle":[{"kind":"identifier","text":"CommonConfiguration"}],"type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureFrameParametersValidator":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureFrameParametersValidator","role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"Use this protocol to create face validators."}],"title":"FaceAutoCaptureFrameParametersValidator","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"FaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"url":"\/documentation\/dotfacelite\/faceautocaptureframeparametersvalidator"},"doc://DotFaceLite/documentation/DotFaceLite":{"title":"DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.0.0"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController":{"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocapturecontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureController","kind":"identifier"}],"type":"topic","title":"FaceAutoCaptureController","navigatorTitle":[{"text":"FaceAutoCaptureController","kind":"identifier"}],"abstract":[{"text":"Non-UI component for the face auto capture process.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/RectangleDouble":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/RectangleDouble","kind":"symbol","abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value type."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleDouble"}],"title":"RectangleDouble","url":"\/documentation\/dotfacelite\/rectangledouble"},"doc://DotFaceLite/documentation/DotFaceLite/AutoCaptureConfiguration":{"title":"AutoCaptureConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AutoCaptureConfiguration","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"url":"\/documentation\/dotfacelite\/autocaptureconfiguration","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/AutoCaptureConfiguration","type":"topic","role":"symbol","navigatorTitle":[{"text":"AutoCaptureConfiguration","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class/init(common:autoCapture:detectionArea:validators:)":{"title":"init(common:autoCapture:detectionArea:validators:)","role":"symbol","abstract":[{"text":"Create face auto capture controller configuration.","type":"text"}],"url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class\/init(common:autocapture:detectionarea:validators:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class\/init(common:autoCapture:detectionArea:validators:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"autoCapture","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"AutoCaptureConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"detectionArea","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"RectangleDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleDouble","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"validators","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"FaceAutoCaptureFrameParametersValidator","preciseIdentifier":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureFrameParametersValidator","kind":"typeIdentifier"},{"text":"]) ","kind":"text"},{"text":"throws","kind":"keyword"}],"type":"topic","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureController/Configuration-swift.class":{"kind":"symbol","abstract":[{"text":"Configuration of the face auto capture non-UI component.","type":"text"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureController\/Configuration-swift.class","type":"topic","url":"\/documentation\/dotfacelite\/faceautocapturecontroller\/configuration-swift.class","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"title":"FaceAutoCaptureController.Configuration"}},"variantOverrides":[{"patch":[{"value":"DOTCommonConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/title"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/fragments"},{"value":[{"text":"DOTCommonConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CommonConfiguration\/navigatorTitle"},{"value":"DOTFLFaceAutoCaptureFrameParametersValidator","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureFrameParametersValidator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureFrameParametersValidator"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureFrameParametersValidator\/navigatorTitle"},{"value":"DOTFLFaceAutoCaptureController","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/title"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/fragments"},{"value":[{"text":"DOTFLFaceAutoCaptureController","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureController\/navigatorTitle"},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/fragments"},{"value":[{"kind":"identifier","text":"DOTRectangleDouble"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1RectangleDouble\/navigatorTitle"},{"value":"DOTAutoCaptureConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/title"},{"value":[{"text":"DOTAutoCaptureConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/fragments"},{"value":[{"kind":"identifier","text":"DOTAutoCaptureConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1AutoCaptureConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}