{"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher"]]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceFaceImage:probeFaceImage:)","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"match","kind":"identifier"},{"kind":"text","text":"("},{"text":"referenceFaceImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","kind":"typeIdentifier","text":"FaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeFaceImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","text":"FaceImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","text":"Result","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"referenceFaceImage","content":[{"inlineContent":[{"type":"text","text":"Face image"}],"type":"paragraph"}]},{"name":"probeFaceImage","content":[{"inlineContent":[{"type":"text","text":"Face image"}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Result with matching score."}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencefaceimage:probefaceimage:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facematcher\/match(referencefaceimage:probefaceimage:)"]}],"abstract":[{"type":"text","text":"Match face image against reference face image."}],"metadata":{"symbolKind":"method","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Method","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"text":"referenceFaceImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceImage","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"probeFaceImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC","kind":"typeIdentifier"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcher(im)matchWithReferenceFaceImage:probeFaceImage:error:","title":"match(referenceFaceImage:probeFaceImage:)","navigatorTitle":[{"text":"matchWithReferenceFaceImage:probeFaceImage:error:","kind":"identifier"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/match(referenceFaceImage:probeFaceImage:)":{"type":"topic","abstract":[{"text":"Match face image against reference face image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/facematcher\/match(referencefaceimage:probefaceimage:)","role":"symbol","title":"match(referenceFaceImage:probeFaceImage:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceFaceImage"},{"text":": ","kind":"text"},{"text":"FaceImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage"},{"kind":"text","text":", "},{"text":"probeFaceImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","text":"FaceImage"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> "},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B7MatcherC6ResultC"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/match(referenceFaceImage:probeFaceImage:)","navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceFaceImage:probeFaceImage:error:"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher/Result":{"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Face matcher result."}],"url":"\/documentation\/dotfacecore\/facematcher\/result","role":"symbol","title":"FaceMatcher.Result","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Result","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher\/Result","navigatorTitle":[{"text":"Result","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceMatcher":{"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceMatcher","abstract":[{"type":"text","text":"Stateless class which can match face images and templates."}],"title":"FaceMatcher","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceMatcher","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"FaceMatcher"}],"url":"\/documentation\/dotfacecore\/facematcher","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceImage":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImage"}],"type":"topic","title":"FaceImage","url":"\/documentation\/dotfacecore\/faceimage","role":"symbol","navigatorTitle":[{"text":"FaceImage","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","abstract":[{"type":"text","text":"Face image is used for face detection, matching and verification."}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceMatcherResult":{"url":"\/documentation\/dotfacecore\/dotffacematcherresult","kind":"symbol","abstract":[{"type":"text","text":"Face matcher result."}],"title":"DOTFFaceMatcherResult","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","role":"symbol","fragments":[{"text":"DOTFFaceMatcherResult","kind":"identifier"}],"type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"matchWithReferenceFaceImage:probeFaceImage:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceFaceImage:probeFaceImage:error:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceMatcherResult","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceMatcherResult","text":"DOTFFaceMatcherResult"},{"text":" *) ","kind":"text"},{"text":"matchWithReferenceFaceImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","text":"DOTFFaceImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"referenceFaceImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"probeFaceImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceImage","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceImage","text":"DOTFFaceImage"},{"text":" *) ","kind":"text"},{"text":"probeFaceImage","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSError","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceFaceImage:probeFaceImage:)\/title","value":"matchWithReferenceFaceImage:probeFaceImage:error:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher~1match(referenceFaceImage:probeFaceImage:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"matchWithReferenceFaceImage:probeFaceImage:error:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/title","value":"DOTFFaceMatcher"},{"op":"replace","value":[{"text":"DOTFFaceMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceMatcher\/fragments"},{"op":"replace","value":"DOTFFaceImage","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/title"},{"op":"replace","value":[{"text":"DOTFFaceImage","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceImage\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}