{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/hash"]},{"paths":["\/documentation\/dotnfc\/additionalpersonaldetails\/hash"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/hash","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"modules":[{"name":"DotNfc"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"title":"hash","symbolKind":"property","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"hash"}],"platforms":[{"beta":false,"introducedAt":"13.0","name":"iOS","deprecated":false,"unavailable":false}],"role":"symbol","externalID":"c:@M@DotNfc@objc(cs)DOTNAdditionalPersonalDetails(py)hash"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails"]]},"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","abstract":[{"type":"text","text":"version: 8.6.0"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","kind":"symbol","url":"\/documentation\/dotnfc","type":"topic"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"kind":"symbol","title":"hash","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails\/hash","navigatorTitle":[{"text":"hash","kind":"identifier"}],"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/additionalpersonaldetails\/hash","role":"symbol"},"doc://DotNfc/documentation/DotNfc/AdditionalPersonalDetails":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AdditionalPersonalDetails","kind":"identifier"}],"url":"\/documentation\/dotnfc\/additionalpersonaldetails","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AdditionalPersonalDetails"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/AdditionalPersonalDetails","abstract":[{"type":"text","text":"Contents of DG11 - Additional personal details."}],"title":"AdditionalPersonalDetails","role":"symbol","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","kind":"symbol","role":"symbol","title":"NfcTravelDocumentReader","type":"topic"},"doc://DotNfc/documentation/DotNfc/TravelDocument":{"title":"TravelDocument","url":"\/documentation\/dotnfc\/traveldocument","role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/TravelDocument","navigatorTitle":[{"kind":"identifier","text":"TravelDocument"}],"type":"topic","abstract":[{"text":"Result of NFC reading.","type":"text"}],"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"TravelDocument"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"hash","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1hash\/title","value":"hash"},{"value":[{"text":"hash","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails~1hash\/fragments","op":"replace"},{"value":"DOTNAdditionalPersonalDetails","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1AdditionalPersonalDetails\/fragments","value":[{"kind":"identifier","text":"DOTNAdditionalPersonalDetails"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"op":"replace","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/title","value":"DOTNTravelDocument","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1TravelDocument\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNTravelDocument"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}