{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"languages":["swift"]}]}],"abstract":[{"type":"text","text":"Create the finger detector."}],"variants":[{"paths":["\/documentation\/dotfingerscore\/fingerdetector\/init()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/fingerdetector\/init()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector"]]},"sections":[],"metadata":{"title":"init()","roleHeading":"Initializer","symbolKind":"init","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingerDetector(im)init","role":"symbol","modules":[{"name":"DotFingersCore"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"init"}]},"kind":"symbol","identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/init()","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector":{"url":"\/documentation\/dotfingerscore\/fingerdetector","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector","title":"FingerDetector","navigatorTitle":[{"kind":"identifier","text":"FingerDetector"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FingerDetector"}],"kind":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect fingers in an image."}]},"doc://DotFingersCore/documentation/DotFingersCore/FingerDetector/init()":{"role":"symbol","title":"init()","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/fingerdetector\/init()","abstract":[{"type":"text","text":"Create the finger detector."}],"fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/FingerDetector\/init()","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"add","path":"\/metadata\/platforms","value":null},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"init"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/title","value":"DOTFGFingerDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/fragments","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector\/navigatorTitle","value":[{"text":"DOTFGFingerDetector","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector~1init()\/title","value":"init"},{"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1FingerDetector~1init()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}