{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":", "},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"nationality","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"optionalData"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"kind":"text","text":"], "},{"kind":"externalParam","text":"compositeCheckDigit"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone"]]},"kind":"symbol","metadata":{"modules":[{"name":"DotNfc"}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"documentCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"issuingStateOrOrganization","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"documentNumber","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"dateOfBirth","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit"},{"kind":"text","text":", "},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"text":"dateOfExpiry","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"nationality","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"kind":"text","text":": "},{"text":"MrzNameElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement"},{"text":", ","kind":"text"},{"text":"optionalData","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","kind":"typeIdentifier","text":"MrzElement"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"compositeCheckDigit"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit"},{"text":")","kind":"text"}],"symbolKind":"init","title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","externalID":"c:@M@DotNfc@objc(cs)DOTTd1MachineReadableZone(im)initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","navigatorTitle":[{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}],"roleHeading":"Initializer"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)"},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElement":{"url":"\/documentation\/dotnfc\/mrzelement","title":"MrzElement","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElement","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","abstract":[{"type":"text","text":"A Machine Readable Zone element which contains string value and positions of this value in the MRZ."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"MrzElement"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Td1MachineReadableZone"}],"abstract":[{"type":"text","text":"Result of MRZ reading of TD1."}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone","title":"Td1MachineReadableZone","type":"topic","role":"symbol","url":"\/documentation\/dotnfc\/td1machinereadablezone","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Td1MachineReadableZone"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","type":"topic","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","role":"collection","title":"DotNfc","abstract":[{"text":"version: 8.3.0","type":"text"}],"kind":"symbol"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzNameElement":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzNameElement","kind":"identifier"}],"url":"\/documentation\/dotnfc\/mrznameelement","navigatorTitle":[{"kind":"identifier","text":"MrzNameElement"}],"abstract":[{"text":"A Machine Readable Zone name element.","type":"text"}],"kind":"symbol","type":"topic","title":"MrzNameElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzCheckDigit":{"url":"\/documentation\/dotnfc\/mrzcheckdigit","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit","navigatorTitle":[{"kind":"identifier","text":"MrzCheckDigit"}],"type":"topic","abstract":[{"type":"text","text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ."}],"role":"symbol","title":"MrzCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzCheckDigit","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/Td1MachineReadableZone/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"documentCode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement"},{"kind":"text","text":", "},{"kind":"externalParam","text":"issuingStateOrOrganization"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"MrzElement","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"documentNumber"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","text":"MrzElementWithCheckDigit","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"dateOfBirth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier","text":"MrzDateElementWithCheckDigit"},{"text":", ","kind":"text"},{"text":"sex","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"dateOfExpiry"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"nationality"},{"kind":"text","text":": "},{"text":"MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":", ","kind":"text"},{"text":"name","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"optionalData"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":"], ","kind":"text"},{"text":"compositeCheckDigit","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/dotnfc\/td1machinereadablezone\/init(documentcode:issuingstateororganization:documentnumber:dateofbirth:sex:dateofexpiry:nationality:name:optionaldata:compositecheckdigit:)","navigatorTitle":[{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}],"abstract":[],"kind":"symbol","type":"topic","title":"init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/Td1MachineReadableZone\/init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzelementwithcheckdigit","kind":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"MrzElement"},{"type":"text","text":" with check digit and checksum validitity information."}],"role":"symbol","title":"MrzElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/MrzDateElementWithCheckDigit":{"url":"\/documentation\/dotnfc\/mrzdateelementwithcheckdigit","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"MrzElementWithCheckDigit"},{"type":"text","text":" with parsed "},{"type":"codeVoice","code":"Date"},{"text":" value.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"MrzDateElementWithCheckDigit"}],"kind":"symbol","title":"MrzDateElementWithCheckDigit","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzDateElementWithCheckDigit","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDocumentCode:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","text":"DOTMrzElement","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"documentCode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"issuingStateOrOrganization:"},{"kind":"text","text":"("},{"text":"DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"issuingStateOrOrganization"},{"kind":"text","text":" "},{"kind":"identifier","text":"documentNumber:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElementWithCheckDigit","text":"DOTMrzElementWithCheckDigit"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"documentNumber"},{"text":" ","kind":"text"},{"text":"dateOfBirth:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"dateOfBirth"},{"kind":"text","text":" "},{"kind":"identifier","text":"sex:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","kind":"typeIdentifier","text":"DOTMrzElement"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"sex"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dateOfExpiry:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzDateElementWithCheckDigit","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzDateElementWithCheckDigit","text":"DOTMrzDateElementWithCheckDigit","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"dateOfExpiry"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nationality:"},{"text":"(","kind":"text"},{"text":"DOTMrzElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzElement"},{"kind":"text","text":" *) "},{"text":"nationality","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"name:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTMrzNameElement","kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzNameElement","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzNameElement"},{"kind":"text","text":" *) "},{"text":"name","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionalData:"},{"text":"(","kind":"text"},{"text":"NSArray<DOTMrzElement *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *) "},{"text":"optionalData","kind":"internalParam"},{"kind":"text","text":" "},{"text":"compositeCheckDigit:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotNfc@objc(cs)DOTMrzCheckDigit","text":"DOTMrzCheckDigit","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/MrzCheckDigit"},{"kind":"text","text":" *) "},{"text":"compositeCheckDigit","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/title","value":"DOTMrzElement","op":"replace"},{"value":[{"text":"DOTMrzElement","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElement\/fragments"},{"value":"DOTTd1MachineReadableZone","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTTd1MachineReadableZone"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/title","value":"DOTMrzNameElement","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzNameElement\/fragments","value":[{"kind":"identifier","text":"DOTMrzNameElement"}]},{"value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzCheckDigit\/title","op":"replace"},{"value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzCheckDigit\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/title","value":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1Td1MachineReadableZone~1init(documentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithDocumentCode:issuingStateOrOrganization:documentNumber:dateOfBirth:sex:dateOfExpiry:nationality:name:optionalData:compositeCheckDigit:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzElementWithCheckDigit\/fragments","value":[{"text":"DOTMrzElementWithCheckDigit","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"DOTMrzDateElementWithCheckDigit","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/title"},{"value":[{"kind":"identifier","text":"DOTMrzDateElementWithCheckDigit"}],"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1MrzDateElementWithCheckDigit\/fragments"}]}]}