{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/pointint\/y"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/pointint\/y"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/y"},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"symbolKind":"property","role":"symbol","title":"y","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"externalID":"c:@M@DotCore@objc(cs)DOTPointInt(py)y","navigatorTitle":[{"text":"y","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}]},"sections":[],"kind":"symbol","abstract":[{"text":"Y coordinate.","type":"text"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/PointInt/y":{"navigatorTitle":[{"kind":"identifier","text":"y"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt\/y","url":"\/documentation\/dotfacelite\/pointint\/y","title":"y","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"y"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"kind":"symbol","type":"topic","abstract":[{"text":"Y coordinate.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite/PointInt":{"abstract":[{"text":"Two dimensional point with ","type":"text"},{"code":"Int","type":"codeVoice"},{"text":" value type.","type":"text"}],"title":"PointInt","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PointInt"}],"url":"\/documentation\/dotfacelite\/pointint","navigatorTitle":[{"kind":"identifier","text":"PointInt"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/PointInt"},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","type":"topic","url":"\/documentation\/dotfacelite","abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceLite","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/platforms","op":"add","value":null},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"y"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"y","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSInteger","preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"y","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1y\/title","op":"replace","value":"y"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt~1y\/fragments","op":"replace","value":[{"text":"y","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/title","op":"replace","value":"DOTPointInt"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/fragments","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1PointInt\/navigatorTitle","op":"replace","value":[{"text":"DOTPointInt","kind":"identifier"}]}]}]}