{"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/preconditionsMet","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"preconditionsMet","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"type":"paragraph","inlineContent":[{"text":"In case this flag is set to ","type":"text"},{"type":"codeVoice","code":"false"},{"text":", the resulting score is not reliable.","type":"text"}]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/dotfacecore\/faceattribute\/preconditionsmet"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/faceattribute\/preconditionsmet"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute"]]},"metadata":{"navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"role":"symbol","title":"preconditionsMet","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAttribute(py)preconditionsMet","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"preconditionsMet"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"DotFaceCore"}]},"abstract":[{"text":"This is set to ","type":"text"},{"type":"codeVoice","code":"true"},{"type":"text","text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is "},{"code":"false","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","abstract":[{"text":"version: 8.16.0","type":"text"}],"url":"\/documentation\/dotfacecore","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute/preconditionsMet":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute\/preconditionsMet","type":"topic","role":"symbol","title":"preconditionsMet","kind":"symbol","navigatorTitle":[{"text":"preconditionsMet","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute\/preconditionsmet","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preconditionsMet"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"abstract":[{"text":"This is set to ","type":"text"},{"code":"true","type":"codeVoice"},{"text":" when the preconditions for the evaluation of this face attribute were met. If the preconditions were not met, this is ","type":"text"},{"type":"codeVoice","code":"false"},{"text":".","type":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAttribute":{"title":"FaceAttribute","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAttribute","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"FaceAttribute","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceattribute","abstract":[{"text":"The evaluation result of a single face quality attribute, for example sharpness or passive liveness.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAttribute"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"preconditionsMet","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"preconditionsMet","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"preconditionsMet"}]}]},"path":"\/primaryContentSections\/0"},{"value":"preconditionsMet","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1preconditionsMet\/title"},{"op":"replace","value":[{"kind":"identifier","text":"preconditionsMet"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute~1preconditionsMet\/fragments"},{"op":"replace","value":"DOTFFaceAttribute","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAttribute\/fragments","op":"replace","value":[{"text":"DOTFFaceAttribute","kind":"identifier"}]}]}]}