{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/candidateselectiondurationmillis"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"DotFaceCore"}],"symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"candidateSelectionDurationMillis","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"roleHeading":"Type Property","externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV32candidateSelectionDurationMillisSivpZ","title":"candidateSelectionDurationMillis","role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","interfaceLanguage":"swift"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"abstract":[],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"kind":"symbol","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Defaults","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults","title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","title":"BaseFaceAutoCaptureViewController.Configuration","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","abstract":[{"type":"text","text":"Configuration options for the face auto capture process."}],"type":"topic","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore":{"type":"topic","abstract":[{"text":"version: 9.2.2","type":"text"}],"title":"DotFaceCore","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/candidateSelectionDurationMillis":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"candidateSelectionDurationMillis"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/candidateselectiondurationmillis","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/candidateSelectionDurationMillis","type":"topic","title":"candidateSelectionDurationMillis","abstract":[]},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing high quality face images with customizable UI."}],"navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","title":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title","op":"replace","value":"DOTFBaseFaceAutoCaptureViewController"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}]}]}]}