{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","kind":"typeIdentifier"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults"]]},"metadata":{"modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"captureMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CaptureMode","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode"}],"roleHeading":"Type Property","title":"captureMode","symbolKind":"property","role":"symbol","externalID":"s:11DotFaceCore04BaseB25AutoCaptureViewControllerC13ConfigurationC8DefaultsV11captureMode0aF00fL0OvpZ"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode"]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults":{"navigatorTitle":[{"kind":"identifier","text":"Defaults"}],"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults","title":"BaseFaceAutoCaptureViewController.Configuration.Defaults","kind":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration/Defaults/captureMode":{"abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@E@DOTCaptureMode","text":"CaptureMode"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration\/Defaults\/captureMode","title":"captureMode","kind":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration\/defaults\/capturemode","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController/Configuration":{"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"abstract":[{"text":"Configuration options for the face auto capture process.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"Configuration","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController\/Configuration","title":"BaseFaceAutoCaptureViewController.Configuration","kind":"symbol","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller\/configuration","type":"topic","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/BaseFaceAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","url":"\/documentation\/dotfacecore\/basefaceautocaptureviewcontroller","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/BaseFaceAutoCaptureViewController","abstract":[{"text":"UI component for capturing high quality face images with customizable UI.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}]},"doc://DotFaceCore/documentation/DotFaceCore/CaptureMode":{"url":"\/documentation\/dotfacecore\/capturemode","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/CaptureMode","navigatorTitle":[{"text":"CaptureMode","kind":"identifier"}],"type":"topic","title":"CaptureMode","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CaptureMode","kind":"identifier"}],"abstract":[{"type":"text","text":"Capture mode."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DOTFBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/title"},{"op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"text":"DOTFBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1BaseFaceAutoCaptureViewController\/navigatorTitle"},{"op":"replace","value":"DOTCaptureMode","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/title"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/fragments"},{"op":"replace","value":[{"text":"DOTCaptureMode","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1CaptureMode\/navigatorTitle"}]}]}