{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFEyeGazeLivenessState) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/eyegazelivenessstate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooClose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooFar","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lostFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lowQualityFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/noFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/ok"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"title":"EyeGazeLivenessState","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotFaceCore@E@DOTFEyeGazeLivenessState","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessState"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore"]]},"references":{"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/ok":{"role":"symbol","title":"EyeGazeLivenessState.ok","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"ok"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/ok","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateOk"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/ok"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/lowQualityFace":{"role":"symbol","title":"EyeGazeLivenessState.lowQualityFace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowQualityFace"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lowQualityFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateLowQualityFace"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/lowqualityface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/init(rawvalue:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 7.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/lostFace":{"role":"symbol","title":"EyeGazeLivenessState.lostFace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"lostFace"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lostFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateLostFace"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/lostface"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/faceTooClose":{"role":"symbol","title":"EyeGazeLivenessState.faceTooClose","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceTooClose"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooClose","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateFaceTooClose"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/facetooclose"},"doc://com.innovatrics.dot.face.core/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/noFace":{"role":"symbol","title":"EyeGazeLivenessState.noFace","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"noFace"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/noFace","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/noface"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState":{"role":"symbol","title":"EyeGazeLivenessState","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"EyeGazeLivenessState"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EyeGazeLivenessState"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/equatable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/EyeGazeLivenessState/faceTooFar":{"role":"symbol","title":"EyeGazeLivenessState.faceTooFar","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceTooFar"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooFar","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateFaceTooFar"}],"url":"\/documentation\/dotfacecore\/eyegazelivenessstate\/facetoofar"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTFEyeGazeLivenessState"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessState"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessState"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooClose","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/faceTooFar","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lostFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/lowQualityFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/noFace","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/EyeGazeLivenessState\/ok"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTFEyeGazeLivenessState"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1ok\/title","value":"DOTFEyeGazeLivenessStateOk"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1ok\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateOk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lowQualityFace\/title","value":"DOTFEyeGazeLivenessStateLowQualityFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lowQualityFace\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateLowQualityFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lostFace\/title","value":"DOTFEyeGazeLivenessStateLostFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1lostFace\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateLostFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1faceTooClose\/title","value":"DOTFEyeGazeLivenessStateFaceTooClose"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1faceTooClose\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateFaceTooClose"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1noFace\/title","value":"DOTFEyeGazeLivenessStateNoFace"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1noFace\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateNoFace"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/title","value":"DOTFEyeGazeLivenessState"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessState"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1faceTooFar\/title","value":"DOTFEyeGazeLivenessStateFaceTooFar"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1EyeGazeLivenessState~1faceTooFar\/fragments","value":[{"kind":"identifier","text":"DOTFEyeGazeLivenessStateFaceTooFar"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}