{"sections":[],"abstract":[{"type":"text","text":"An object with check digit value and checksum validity flag."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","kind":"typeIdentifier","text":"MrzCheckDigit"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit\/checkdigit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/mrzelementwithcheckdigit\/checkdigit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"checkDigit","kind":"identifier"}],"symbolKind":"property","role":"symbol","modules":[{"name":"DotDocument"}],"title":"checkDigit","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":": "},{"text":"MrzCheckDigit","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"}],"externalID":"c:@M@DotDocumentCommons@objc(cs)DOTMrzElementWithCheckDigit(py)checkDigit"},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/checkDigit","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit":{"url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit","role":"symbol","navigatorTitle":[{"text":"MrzElementWithCheckDigit","kind":"identifier"}],"abstract":[{"text":"A ","type":"text"},{"code":"MrzElement","type":"codeVoice"},{"type":"text","text":" with check digit and checksum validitity information."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit","kind":"symbol","title":"MrzElementWithCheckDigit","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"MrzElementWithCheckDigit","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzReader":{"title":"MrzReader","role":"symbol","url":"\/documentation\/dotdocument\/mrzreader","abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/MrzElementWithCheckDigit/checkDigit":{"abstract":[{"type":"text","text":"An object with check digit value and checksum validity flag."}],"role":"symbol","navigatorTitle":[{"text":"checkDigit","kind":"identifier"}],"title":"checkDigit","kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checkDigit"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit","text":"MrzCheckDigit","kind":"typeIdentifier"}],"type":"topic","url":"\/documentation\/dotdocument\/mrzelementwithcheckdigit\/checkdigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzElementWithCheckDigit\/checkDigit"},"doc://DotDocument/documentation/DotDocument/MrzCheckDigit":{"kind":"symbol","abstract":[{"text":"A check digit belonging to a particular Machine Readable Zone element with a checksum in the MRZ.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzCheckDigit"}],"title":"MrzCheckDigit","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","url":"\/documentation\/dotdocument\/mrzcheckdigit","navigatorTitle":[{"text":"MrzCheckDigit","kind":"identifier"}],"role":"symbol"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 8.6.0","type":"text"}],"url":"\/documentation\/dotdocument","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"checkDigit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"checkDigit","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"DOTMrzCheckDigit","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzCheckDigit","preciseIdentifier":"c:@M@DotDocumentCommons@objc(cs)DOTMrzCheckDigit"},{"text":" * ","kind":"text"},{"text":"checkDigit","kind":"identifier"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/title","op":"replace","value":"DOTMrzElementWithCheckDigit"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzElementWithCheckDigit"}],"op":"replace"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1checkDigit\/title","value":"checkDigit"},{"value":[{"kind":"identifier","text":"checkDigit"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzElementWithCheckDigit~1checkDigit\/fragments"},{"value":"DOTMrzCheckDigit","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzCheckDigit\/fragments","value":[{"kind":"identifier","text":"DOTMrzCheckDigit"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}