{"kind":"symbol","variants":[{"paths":["\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/standard"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/standard"},"abstract":[{"type":"text","text":"Standard polling option which supports detection of almost all travel documents."}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum"]]},"metadata":{"externalID":"s:6DotNfc0B20TravelDocumentReaderC13ConfigurationC13PollingOptionO8standardyA2GmF","roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"symbolKind":"case","modules":[{"name":"DotNfc"}],"role":"symbol","title":"NfcTravelDocumentReader.Configuration.PollingOption.standard"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Configuration"}],"type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class","role":"symbol","abstract":[{"text":"Configuration options for ","type":"text"},{"code":"NfcTravelDocumentReader","type":"codeVoice"},{"text":".","type":"text"}],"title":"NfcTravelDocumentReader.Configuration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum":{"title":"NfcTravelDocumentReader.Configuration.PollingOption","type":"topic","url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum","abstract":[{"text":"Polling option specifies which travel documents can be detected.","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"PollingOption","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"PollingOption","kind":"identifier"}]},"doc://DotNfc/documentation/DotNfc":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"version: 9.5.0"}],"url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader/Configuration-swift.class/PollingOption-swift.enum/standard":{"title":"NfcTravelDocumentReader.Configuration.PollingOption.standard","type":"topic","abstract":[{"text":"Standard polling option which supports detection of almost all travel documents.","type":"text"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader\/configuration-swift.class\/pollingoption-swift.enum\/standard","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader\/Configuration-swift.class\/PollingOption-swift.enum\/standard","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}