{"abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration"]]},"metadata":{"fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"navigatorTitle":[{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"modules":[{"name":"DotFaceLite"}],"role":"symbol","externalID":"c:@M@DotFaceLite@objc(cs)DOTFLMagnifEyeLivenessConfiguration(im)initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","symbolKind":"method","title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","roleHeading":"Instance Method"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithSessionToken:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"sessionToken"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"text":"isTorchEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"isTorchEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"isVideoCaptureEnabled:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"isVideoCaptureEnabled","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraFacing:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@M@DotCamera@E@DOTCameraFacing","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","text":"DOTCameraFacing"},{"kind":"text","text":") "},{"text":"cameraFacing","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cameraPreviewScaleType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"DOTCameraPreviewScaleType","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","preciseIdentifier":"c:@M@DotCamera@E@DOTCameraPreviewScaleType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cameraPreviewScaleType"},{"text":" ","kind":"text"},{"text":"isCameraPreviewVisible:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isCameraPreviewVisible"},{"kind":"text","text":";"}],"languages":["occ"]}]}],"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"references":{"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:":{"title":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","fragments":[{"text":"- ","kind":"text"},{"text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","kind":"identifier"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration\/initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:","role":"symbol","abstract":[{"type":"text","text":"Create the MagnifEye liveness configuration."}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration\/initwithsessiontoken:isdetectionlayervisible:istorchenabled:isvideocaptureenabled:camerafacing:camerapreviewscaletype:iscamerapreviewvisible:","navigatorTitle":[{"kind":"identifier","text":"initWithSessionToken:isDetectionLayerVisible:isTorchEnabled:isVideoCaptureEnabled:cameraFacing:cameraPreviewScaleType:isCameraPreviewVisible:"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","abstract":[{"type":"text","text":"version: 8.14.1"}],"role":"collection","url":"\/documentation\/dotfacelite","title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CameraFacing":{"abstract":[{"type":"text","text":"Facing of the camera on the device."}],"navigatorTitle":[{"kind":"identifier","text":"CameraFacing"}],"role":"symbol","url":"\/documentation\/dotfacelite\/camerafacing","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraFacing","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraFacing"}],"kind":"symbol","title":"CameraFacing"},"doc://DotFaceLite/documentation/DotFaceLite/CameraPreviewScaleType":{"type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"CameraPreviewScaleType"}],"navigatorTitle":[{"kind":"identifier","text":"CameraPreviewScaleType"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CameraPreviewScaleType","title":"CameraPreviewScaleType","url":"\/documentation\/dotfacelite\/camerapreviewscaletype","kind":"symbol","abstract":[{"text":"Indicates how the layer displays video frames.","type":"text"}],"role":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/DOTFLMagnifEyeLivenessConfiguration":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/DOTFLMagnifEyeLivenessConfiguration","type":"topic","url":"\/documentation\/dotfacelite\/dotflmagnifeyelivenessconfiguration","kind":"symbol","abstract":[{"text":"Configuration options for the MagnifEye liveness process.","type":"text"}],"title":"DOTFLMagnifEyeLivenessConfiguration","role":"symbol","fragments":[{"text":"DOTFLMagnifEyeLivenessConfiguration","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/title","op":"replace","value":"DOTCameraFacing"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraFacing\/fragments","value":[{"kind":"identifier","text":"DOTCameraFacing"}]},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/title","op":"replace","value":"DOTCameraPreviewScaleType"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CameraPreviewScaleType\/fragments","value":[{"kind":"identifier","text":"DOTCameraPreviewScaleType"}]}]}]}