{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing"]]},"metadata":{"externalID":"s:9DotCamera0B6FacingO6nativeSo23AVCaptureDevicePositionVvp","modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AVCaptureDevice","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)AVCaptureDevice"},{"text":".","kind":"text"},{"text":"Position","kind":"typeIdentifier","preciseIdentifier":"c:@E@AVCaptureDevicePosition"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","title":"native"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"native"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier","text":"Position"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/camerafacing\/native"]}],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/native","interfaceLanguage":"swift"},"sections":[],"references":{"doc://DotDocument/documentation/DotDocument/CameraFacing":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing","title":"CameraFacing","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CameraFacing","kind":"identifier"}],"abstract":[{"text":"Facing of the camera on the device.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"CameraFacing","kind":"identifier"}],"url":"\/documentation\/dotdocument\/camerafacing"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/CameraFacing/native":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/CameraFacing\/native","title":"native","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"native","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)AVCaptureDevice","kind":"typeIdentifier","text":"AVCaptureDevice"},{"kind":"text","text":"."},{"text":"Position","preciseIdentifier":"c:@E@AVCaptureDevicePosition","kind":"typeIdentifier"}],"abstract":[],"kind":"symbol","url":"\/documentation\/dotdocument\/camerafacing\/native"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/title","value":"DOTCameraFacing"},{"value":[{"kind":"identifier","text":"DOTCameraFacing"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTCameraFacing"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1CameraFacing\/navigatorTitle"}]}]}