{"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/quality","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face"]]},"abstract":[{"type":"text","text":"Face quality attributes."}],"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"s:11DotFaceLite0B8DetectorC0B0C7qualityAA0B7QualityCvp","modules":[{"name":"DotFaceLite"}],"title":"quality","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FaceQuality","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","kind":"typeIdentifier"}],"symbolKind":"property","roleHeading":"Instance Property"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/facedetector\/face\/quality"]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face":{"role":"symbol","abstract":[{"type":"text","text":"Detected face."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Face"}],"navigatorTitle":[{"kind":"identifier","text":"Face"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face","url":"\/documentation\/dotfacelite\/facedetector\/face","kind":"symbol","type":"topic","title":"FaceDetector.Face"},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector/Face/quality":{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector\/Face\/quality","type":"topic","abstract":[{"text":"Face quality attributes.","type":"text"}],"kind":"symbol","title":"quality","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceQuality","kind":"typeIdentifier","text":"FaceQuality"}],"url":"\/documentation\/dotfacelite\/facedetector\/face\/quality"},"doc://DotFaceLite/documentation/DotFaceLite/FaceQuality":{"type":"topic","kind":"symbol","abstract":[{"text":"Face quality.","type":"text"}],"role":"symbol","title":"FaceQuality","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceQuality","url":"\/documentation\/dotfacelite\/facequality","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceQuality"}],"navigatorTitle":[{"kind":"identifier","text":"FaceQuality"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceDetector":{"role":"symbol","abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceDetector","url":"\/documentation\/dotfacelite\/facedetector","kind":"symbol","type":"topic","title":"FaceDetector"},"doc://DotFaceLite/documentation/DotFaceLite":{"type":"topic","abstract":[{"text":"version: 9.4.1","type":"text"}],"title":"DotFaceLite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","kind":"symbol","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/title","value":"DOTFLFaceQuality","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/fragments","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceQuality\/navigatorTitle","value":[{"text":"DOTFLFaceQuality","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/title","value":"DOTFLFaceDetector","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/fragments","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceDetector\/navigatorTitle","value":[{"text":"DOTFLFaceDetector","kind":"identifier"}],"op":"replace"}]}]}