{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(ciImage:ciContext:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"ciImage","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"text":"ciContext","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"ciImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" object."}]}]},{"name":"ciContext","content":[{"inlineContent":[{"type":"text","text":"CIContext."}],"type":"paragraph"}]}]},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"New "},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory(cm)createWithCiImage:ciContext:","navigatorTitle":[{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"role":"symbol","roleHeading":"Type Method","title":"create(ciImage:ciContext:)","modules":[{"name":"DotPalmCore"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"ciImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"ciContext"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CIContext","preciseIdentifier":"c:objc(cs)CIContext"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"symbolKind":"method"},"abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"sections":[],"variants":[{"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(ciimage:cicontext:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","title":"BgrRawImage","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimage","abstract":[{"type":"text","text":"Raw image with BGR888 pixel format."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"BgrRawImage","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"BgrRawImage"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.6.1"}],"title":"DotPalmCore"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory":{"title":"BgrRawImageFactory","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory","abstract":[{"type":"text","text":"Create "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":" from iOS native image types."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory/create(ciImage:ciContext:)":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(ciImage:ciContext:)","title":"create(ciImage:ciContext:)","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(ciimage:cicontext:)","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"CIImage"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"ciImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"ciContext"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIContext","text":"CIContext","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"BgrRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"navigatorTitle":[{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"createWithCiImage:ciContext:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithCiImage:ciContext:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"createWithCiImage:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)CIImage","text":"CIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"ciImage","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"ciContext:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CIContext","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIContext"},{"text":" *) ","kind":"text"},{"text":"ciContext","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"DOTBgrRawImage","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title"},{"value":[{"kind":"identifier","text":"DOTBgrRawImage"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/title","value":"DOTBgrRawImageFactory","op":"replace"},{"value":[{"kind":"identifier","text":"DOTBgrRawImageFactory"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/title","op":"replace","value":"createWithCiImage:ciContext:"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"createWithCiImage:ciContext:"}],"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(ciImage:ciContext:)\/fragments","op":"replace"}]}]}