{"metadata":{"modules":[{"name":"DotNfc"}],"role":"collectionGroup","title":"DotSdkError Implementations"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/DotSdkError-Implementations"},"kind":"article","topicSections":[{"identifiers":["doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/composeWithInternalError()"],"generated":true,"title":"Instance Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/error\/dotsdkerror-implementations"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://DotNfc/documentation/DotNfc":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","abstract":[{"type":"text","text":"version: 8.14.0"}],"type":"topic","role":"collection","url":"\/documentation\/dotnfc","kind":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"kind":"symbol","title":"NfcTravelDocumentReader","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Non-UI component for reading travel documents using NFC technology."}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcTravelDocumentReader"}]},"doc://DotNfc/documentation/DotNfc/NfcKey":{"kind":"symbol","deprecated":true,"title":"NfcKey","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","role":"symbol","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"type":"topic","url":"\/documentation\/dotnfc\/nfckey","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}]},"doc://DotNfc/documentation/DotNfc/NfcKey/Error":{"kind":"symbol","title":"NfcKey.Error","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"Error","kind":"identifier"}],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfckey\/error","role":"symbol","deprecated":true,"type":"topic"},"doc://DotNfc/documentation/DotNfc/NfcKey/Error/composeWithInternalError()":{"kind":"symbol","title":"composeWithInternalError()","abstract":[],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/Error\/composeWithInternalError()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"composeWithInternalError"},{"kind":"text","text":"() -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"url":"\/documentation\/dotnfc\/nfckey\/error\/composewithinternalerror()","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace","value":"DOTNNfcTravelDocumentReader"},{"value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments"},{"value":"DOTNNfcKey","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"text":"DOTNNfcKey","kind":"identifier"}]}]}]}