{"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"LocalizedError.recoverySuggestion"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/recoverySuggestion"},"metadata":{"role":"symbol","title":"recoverySuggestion","platforms":[{"introducedAt":"8.0","beta":false,"unavailable":false,"deprecated":false,"name":"iOS"},{"beta":false,"name":"macOS","unavailable":false,"introducedAt":"10.10","deprecated":false},{"introducedAt":"9.0","deprecated":false,"name":"tvOS","unavailable":false,"beta":false},{"deprecated":false,"beta":false,"introducedAt":"2.0","unavailable":false,"name":"watchOS"}],"extendedModule":"Foundation","roleHeading":"Instance Property","externalID":"s:10Foundation14LocalizedErrorPAAE18recoverySuggestionSSSgvp::SYNTHESIZED::s:6DotNfc0B3KeyC5ErrorO","modules":[{"name":"DotNfc","relatedModules":["Foundation"]}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"recoverySuggestion","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotnfc\/nfckey\/error\/recoverysuggestion"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error","doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/LocalizedError-Implementations"]]},"references":{"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"NfcKey","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"NFC key created from document number, date of expiry and date of birth."}],"url":"\/documentation\/dotnfc\/nfckey","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"NfcKey"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey","title":"NfcKey"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc":{"url":"\/documentation\/dotnfc","abstract":[{"type":"text","text":"version: 8.3.0"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc","kind":"symbol","type":"topic","title":"DotNfc","role":"collection"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error","kind":"symbol","navigatorTitle":[{"text":"Error","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error","title":"NfcKey.Error"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcTravelDocumentReader":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NfcTravelDocumentReader","kind":"identifier"}],"type":"topic","kind":"symbol","title":"NfcTravelDocumentReader","abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcTravelDocumentReader","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"url":"\/documentation\/dotnfc\/nfctraveldocumentreader"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/LocalizedError-Implementations":{"role":"collectionGroup","type":"topic","abstract":[],"url":"\/documentation\/dotnfc\/nfckey\/error\/localizederror-implementations","kind":"article","identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/LocalizedError-Implementations","title":"LocalizedError Implementations"},"doc://com.innovatrics.dot.nfc/documentation/DotNfc/NfcKey/Error/recoverySuggestion":{"type":"topic","abstract":[],"title":"recoverySuggestion","role":"symbol","kind":"symbol","url":"\/documentation\/dotnfc\/nfckey\/error\/recoverysuggestion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"recoverySuggestion"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.innovatrics.dot.nfc\/documentation\/DotNfc\/NfcKey\/Error\/recoverySuggestion"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey","op":"replace"},{"op":"replace","value":[{"text":"DOTNNfcKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcKey\/fragments"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","value":"DOTNNfcTravelDocumentReader","op":"replace"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.nfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","value":[{"text":"DOTNNfcTravelDocumentReader","kind":"identifier"}],"op":"replace"}]}]}