{"abstract":[{"type":"text","text":"Current style."}],"metadata":{"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureViewController(py)style","modules":[{"name":"DotFaceCore"}],"title":"style","symbolKind":"property","role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"style","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC","text":"Style"}],"platforms":[],"navigatorTitle":[{"kind":"identifier","text":"style"}],"roleHeading":"Instance Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"style","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Style","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"deprecationSummary":[{"inlineContent":[{"type":"text","text":"Use FaceAutoCaptureViewController with FaceAutoCaptureViewController.Configuration.Presets.simple instead."}],"type":"paragraph"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/style-swift.property"},"variants":[{"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.property"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/style-swift.property":{"navigatorTitle":[{"text":"style","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/style-swift.property","deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.property","abstract":[{"text":"Current style.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"style"},{"kind":"text","text":": "},{"text":"Style","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore0B27SimpleCaptureViewControllerC5StyleC"}],"kind":"symbol","type":"topic","title":"style"},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController":{"navigatorTitle":[{"text":"FaceSimpleCaptureViewController","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceSimpleCaptureViewController"}],"title":"FaceSimpleCaptureViewController","kind":"symbol","abstract":[{"text":"UI component for capturing face images.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController","type":"topic","deprecated":true},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceSimpleCaptureStyle":{"abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureStyle","kind":"symbol","url":"\/documentation\/dotfacecore\/dotffacesimplecapturestyle","title":"DOTFFaceSimpleCaptureStyle","role":"symbol","fragments":[{"text":"DOTFFaceSimpleCaptureStyle","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceSimpleCaptureViewController/Style-swift.class":{"deprecated":true,"url":"\/documentation\/dotfacecore\/facesimplecaptureviewcontroller\/style-swift.class","abstract":[{"type":"text","text":"Customization options for the face simple capture user interface."}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceSimpleCaptureViewController\/Style-swift.class","title":"FaceSimpleCaptureViewController.Style","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Style"}],"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Style"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","kind":"symbol","abstract":[{"text":"version: 8.6.1","type":"text"}],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"style"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"style","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"DOTFFaceSimpleCaptureStyle","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceSimpleCaptureStyle","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceSimpleCaptureStyle"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"style"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"style","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1style-swift.property\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController~1style-swift.property\/fragments","op":"replace","value":[{"text":"style","kind":"identifier"}]},{"value":"DOTFFaceSimpleCaptureViewController","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceSimpleCaptureViewController\/fragments","value":[{"text":"DOTFFaceSimpleCaptureViewController","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}