{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/contrastinterval"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/contrastinterval"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/contrastInterval","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","navigatorTitle":[{"text":"contrastInterval","kind":"identifier"}],"title":"contrastInterval","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contrastInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"DotFaceCore"}],"role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds(py)contrastInterval","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"]]},"sections":[],"abstract":[{"type":"text","text":"Valid interval of contrast of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low contrast."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents high contrast."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"contrastInterval","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble","text":"IntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","type":"topic","role":"collection","title":"DotFaceCore","abstract":[{"text":"version: 9.1.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","type":"topic","kind":"symbol","title":"FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalDouble":{"role":"symbol","navigatorTitle":[{"text":"IntervalDouble","kind":"identifier"}],"title":"IntervalDouble","url":"\/documentation\/dotfacecore\/intervaldouble","abstract":[{"type":"text","text":"Representation of closed interval with value type "},{"type":"codeVoice","code":"Double"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"max"},{"type":"text","text":" must be greater than the "},{"type":"codeVoice","code":"min"},{"type":"text","text":"."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalDouble","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/contrastInterval":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/contrastInterval","role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/contrastinterval","title":"contrastInterval","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"contrastInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"contrastInterval"}],"abstract":[{"text":"Valid interval of contrast of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low contrast.","type":"text"},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents high contrast.","type":"text"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","value":"contrastInterval","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"contrastInterval"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTIntervalDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"contrastInterval"},{"kind":"text","text":";"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments"},{"op":"replace","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle"},{"op":"replace","value":"DOTIntervalDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTIntervalDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalDouble\/navigatorTitle"},{"op":"replace","value":"contrastInterval","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1contrastInterval\/title"},{"op":"replace","value":[{"kind":"identifier","text":"contrastInterval"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1contrastInterval\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}