{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minbackgrounduniformity"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minbackgrounduniformity"]}],"sections":[],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minBackgroundUniformity","interfaceLanguage":"swift"},"abstract":[{"text":"Minimal valid level of the background uniformity of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low background uniformity.","type":"text"},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents high background uniformity.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minBackgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"property","title":"minBackgroundUniformity","modules":[{"name":"DotFaceCore"}],"externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds(py)minBackgroundUniformity","roleHeading":"Instance Property","navigatorTitle":[{"text":"minBackgroundUniformity","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minBackgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"abstract":[{"text":"Configure thresholds for the quality attributes of the face auto capture result.","type":"text"},{"text":" ","type":"text"},{"text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated.","type":"text"}],"title":"FaceAutoCaptureQualityAttributeThresholds","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.0.2"}],"title":"DotFaceCore","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","role":"collection","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minBackgroundUniformity":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minBackgroundUniformity","title":"minBackgroundUniformity","navigatorTitle":[{"text":"minBackgroundUniformity","kind":"identifier"}],"type":"topic","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/minbackgrounduniformity","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minBackgroundUniformity","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Minimal valid level of the background uniformity of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low background uniformity.","type":"text"},{"text":" ","type":"text"},{"text":"Vaue 1.0 represents high background uniformity.","type":"text"}],"role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"url":"\/documentation\/dotfacecore\/wrappeddouble","kind":"symbol","type":"topic","role":"symbol","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Double","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","title":"WrappedDouble"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"minBackgroundUniformity"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"minBackgroundUniformity","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"DOTWrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"minBackgroundUniformity"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace","value":"DOTFFaceAutoCaptureQualityAttributeThresholds"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minBackgroundUniformity\/title","value":"minBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minBackgroundUniformity\/fragments","value":[{"text":"minBackgroundUniformity","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","value":"DOTWrappedDouble"},{"op":"replace","value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle"}]}]}