{"metadata":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"modules":[{"name":"DotFaceCore"}],"title":"minEyesStatusScore","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"minEyesStatusScore"}],"role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds(py)minEyesStatusScore"},"sections":[],"abstract":[{"type":"text","text":"Minimal valid eyes status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesstatusscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesstatusscore"]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesStatusScore","interfaceLanguage":"swift"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?"}]}]}],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.0.1","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","type":"topic","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"url":"\/documentation\/dotfacecore\/wrappeddouble","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"kind":"symbol","title":"WrappedDouble","abstract":[{"type":"text","text":"Wrapped "},{"code":"Double","type":"codeVoice"},{"type":"text","text":" value for Objective-C support."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"role":"symbol","kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"title":"FaceAutoCaptureQualityAttributeThresholds","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minEyesStatusScore":{"url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesstatusscore","type":"topic","abstract":[{"type":"text","text":"Minimal valid eyes status score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents face with eyes closed."},{"type":"text","text":" "},{"type":"text","text":"Vaue 1.0 represents face with eyes opened."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"minEyesStatusScore"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"WrappedDouble","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble"},{"kind":"text","text":"?"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesStatusScore","role":"symbol","title":"minEyesStatusScore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"minEyesStatusScore","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"minEyesStatusScore"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"minEyesStatusScore"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTWrappedDouble","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","op":"replace"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","op":"replace"},{"value":[{"text":"DOTWrappedDouble","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle","op":"replace"},{"value":"DOTFFaceAutoCaptureQualityAttributeThresholds","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","op":"replace"},{"value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","op":"replace"},{"value":"minEyesStatusScore","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesStatusScore\/title","op":"replace"},{"value":[{"text":"minEyesStatusScore","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesStatusScore\/fragments","op":"replace"}]}]}