{"metadata":{"title":"minEyesDetectionScore","symbolKind":"property","modules":[{"name":"DotFaceCore"}],"roleHeading":"Instance Property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds(py)minEyesDetectionScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesDetectionScore"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"minEyesDetectionScore"}]},"kind":"symbol","abstract":[{"type":"text","text":"Minimal valid eyes detection score of the detected face."},{"type":"text","text":" "},{"type":"text","text":"Value 0.0 represents low eyes detection score."},{"type":"text","text":" "},{"type":"text","text":"Value 1.0 represents high eyes detection score."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesDetectionScore"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"WrappedDouble"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesDetectionScore"},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesdetectionscore"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesdetectionscore"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","kind":"symbol","type":"topic","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureQualityAttributeThresholds"}]},"doc://DotFaceCore/documentation/DotFaceCore/WrappedDouble":{"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedDouble"}],"navigatorTitle":[{"kind":"identifier","text":"WrappedDouble"}],"title":"WrappedDouble","url":"\/documentation\/dotfacecore\/wrappeddouble","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","type":"topic","abstract":[{"type":"text","text":"Wrapped "},{"type":"codeVoice","code":"Double"},{"type":"text","text":" value for Objective-C support."}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/minEyesDetectionScore":{"title":"minEyesDetectionScore","abstract":[{"text":"Minimal valid eyes detection score of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 0.0 represents low eyes detection score.","type":"text"},{"text":" ","type":"text"},{"text":"Value 1.0 represents high eyes detection score.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/mineyesdetectionscore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/minEyesDetectionScore","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"minEyesDetectionScore"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","kind":"typeIdentifier","text":"WrappedDouble"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minEyesDetectionScore"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"minEyesDetectionScore","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"minEyesDetectionScore"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedDouble","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedDouble","text":"DOTWrappedDouble"},{"kind":"text","text":" * "},{"kind":"identifier","text":"minEyesDetectionScore"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFFaceAutoCaptureQualityAttributeThresholds"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/title","value":"DOTWrappedDouble","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/fragments","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedDouble\/navigatorTitle","value":[{"kind":"identifier","text":"DOTWrappedDouble"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesDetectionScore\/title","value":"minEyesDetectionScore","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1minEyesDetectionScore\/fragments","value":[{"kind":"identifier","text":"minEyesDetectionScore"}],"op":"replace"}]}]}