{"abstract":[{"text":"Valid interval of rotation of the pitch of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value -90.0 represents down rotated pitch of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 90.0 represents up rotated pitch of the detected face.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitchAngleInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalFloat","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/pitchangleinterval"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/pitchangleinterval"]}],"kind":"symbol","metadata":{"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"text":"pitchAngleInterval","kind":"identifier"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholds(py)pitchAngleInterval","title":"pitchAngleInterval","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pitchAngleInterval","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IntervalFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/pitchAngleInterval","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds"]]},"references":{"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds/pitchAngleInterval":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"pitchAngleInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat","kind":"typeIdentifier","text":"IntervalFloat"},{"kind":"text","text":"?"}],"title":"pitchAngleInterval","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds\/pitchangleinterval","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds\/pitchAngleInterval","abstract":[{"text":"Valid interval of rotation of the pitch of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value -90.0 represents down rotated pitch of the detected face.","type":"text"},{"text":" ","type":"text"},{"text":"Value 90.0 represents up rotated pitch of the detected face.","type":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"pitchAngleInterval"}]},"doc://DotFaceCore/documentation/DotFaceCore/FaceAutoCaptureQualityAttributeThresholds":{"role":"symbol","url":"\/documentation\/dotfacecore\/faceautocapturequalityattributethresholds","abstract":[{"type":"text","text":"Configure thresholds for the quality attributes of the face auto capture result."},{"type":"text","text":" "},{"type":"text","text":"If the threshold property is set to nil, the corresponding quality attribute will not be validated."}],"navigatorTitle":[{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/FaceAutoCaptureQualityAttributeThresholds","title":"FaceAutoCaptureQualityAttributeThresholds","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"type":"text","text":"version: 9.3.0"}],"title":"DotFaceCore","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","role":"collection","url":"\/documentation\/dotfacecore"},"doc://DotFaceCore/documentation/DotFaceCore/IntervalFloat":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IntervalFloat"}],"type":"topic","url":"\/documentation\/dotfacecore\/intervalfloat","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","title":"IntervalFloat","abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"IntervalFloat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"pitchAngleInterval","op":"replace"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"pitchAngleInterval","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/IntervalFloat","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTIntervalFloat","text":"DOTIntervalFloat"},{"kind":"text","text":" * "},{"kind":"identifier","text":"pitchAngleInterval"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1pitchAngleInterval\/title","value":"pitchAngleInterval","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds~1pitchAngleInterval\/fragments","value":[{"text":"pitchAngleInterval","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/title","value":"DOTFFaceAutoCaptureQualityAttributeThresholds","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/fragments","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1FaceAutoCaptureQualityAttributeThresholds\/navigatorTitle","value":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholds","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1IntervalFloat\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"}]}]}