{"kind":"symbol","metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"roleHeading":"Initializer","title":"init(rawValue:)","role":"symbol","externalID":"s:11DotDocument17BarcodeValidationO8rawValueACSgSi_tcfc","symbolKind":"init","modules":[{"name":"DotDocument"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/init(rawValue:)"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/barcodevalidation\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"text":".","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","url":"\/documentation\/dotdocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","title":"DotDocument","abstract":[{"text":"version: 9.2.3","type":"text"}]},"doc://DotDocument/documentation/DotDocument/BarcodeValidation/init(rawValue:)":{"abstract":[],"url":"\/documentation\/dotdocument\/barcodevalidation\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","kind":"symbol","title":"init(rawValue:)","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation\/init(rawValue:)"},"doc://DotDocument/documentation/DotDocument/BarcodeValidation":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/BarcodeValidation","type":"topic","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"BarcodeValidation"}],"navigatorTitle":[{"kind":"identifier","text":"BarcodeValidation"}],"url":"\/documentation\/dotdocument\/barcodevalidation","abstract":[{"text":"Mode of barcode validation.","type":"text"}],"title":"BarcodeValidation","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"DOTDBarcodeValidation","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/title","op":"replace"},{"value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/fragments","op":"replace"},{"value":[{"text":"DOTDBarcodeValidation","kind":"identifier"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1BarcodeValidation\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}