{"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/maxdevicepitchangle:error:"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"]]},"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxDevicePitchAngle:error:"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder"},{"text":" *) ","kind":"text"},{"text":"maxDevicePitchAngle:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTWrappedFloat","text":"DOTWrappedFloat","kind":"typeIdentifier","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat"},{"text":" *) ","kind":"text"},{"text":"maxDevicePitchAngle","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"maxDevicePitchAngle:error:","kind":"identifier"}],"modules":[{"name":"DotFaceCore"}],"symbolKind":"method","navigatorTitle":[{"text":"maxDevicePitchAngle:error:","kind":"identifier"}],"roleHeading":"Instance Method","title":"maxDevicePitchAngle:error:","externalID":"c:@M@DotFaceCore@objc(cs)DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder(im)maxDevicePitchAngle:error:"},"kind":"symbol","references":{"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder/maxDevicePitchAngle:error:":{"navigatorTitle":[{"text":"maxDevicePitchAngle:error:","kind":"identifier"}],"title":"maxDevicePitchAngle:error:","url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder\/maxdevicepitchangle:error:","abstract":[],"kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder\/maxDevicePitchAngle:error:","fragments":[{"text":"- ","kind":"text"},{"text":"maxDevicePitchAngle:error:","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"abstract":[{"text":"version: 9.4.1","type":"text"}],"type":"topic","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","kind":"symbol","title":"DotFaceCore","role":"collection"},"doc://DotFaceCore/documentation/DotFaceCore/WrappedFloat":{"type":"topic","url":"\/documentation\/dotfacecore\/wrappedfloat","abstract":[{"text":"Wrapped ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":" value for Objective-C support.","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/WrappedFloat","kind":"symbol","title":"WrappedFloat","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"WrappedFloat","kind":"identifier"}],"navigatorTitle":[{"text":"WrappedFloat","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder":{"title":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","abstract":[],"url":"\/documentation\/dotfacecore\/dotffaceautocapturequalityattributethresholdsbuilder","role":"symbol","fragments":[{"text":"DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DOTFFaceAutoCaptureQualityAttributeThresholdsBuilder","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTWrappedFloat","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/title"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/fragments"},{"value":[{"text":"DOTWrappedFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1WrappedFloat\/navigatorTitle"}]}]}