{"variants":[{"paths":["\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol\/isequal(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol\/isEqual(_:)"},"metadata":{"roleHeading":"Instance Method","title":"isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"modules":[{"name":"DotNfc"}],"role":"symbol","externalID":"s:6DotNfc24ChipAuthenticationStatusC15WrappedProtocolC7isEqualySbypSgF","symbolKind":"method"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"?) -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}]}],"references":{"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol/isEqual(_:)":{"abstract":[],"type":"topic","url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol\/isequal(_:)","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol\/isEqual(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"isEqual"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"isEqual(_:)","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus":{"title":"ChipAuthenticationStatus","url":"\/documentation\/dotnfc\/chipauthenticationstatus","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus","abstract":[{"type":"text","text":"Authentication status of the chip and protocol used for that purpose."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ChipAuthenticationStatus"}],"navigatorTitle":[{"kind":"identifier","text":"ChipAuthenticationStatus"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","abstract":[{"text":"version: 9.1.0","type":"text"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","title":"DotNfc","kind":"symbol","type":"topic","url":"\/documentation\/dotnfc"},"doc://DotNfc/documentation/DotNfc/ChipAuthenticationStatus/WrappedProtocol":{"type":"topic","title":"ChipAuthenticationStatus.WrappedProtocol","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/ChipAuthenticationStatus\/WrappedProtocol","abstract":[{"type":"text","text":"Objective-C wrapper of "},{"type":"codeVoice","code":"AuthenticationProtocol"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"WrappedProtocol"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"WrappedProtocol"}],"url":"\/documentation\/dotnfc\/chipauthenticationstatus\/wrappedprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/title","value":"DOTNChipAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNChipAuthenticationStatus"}]},{"op":"replace","value":[{"text":"DOTNChipAuthenticationStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1ChipAuthenticationStatus\/navigatorTitle"}]}]}