{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTFGBaseFingersAutoCaptureConfiguration) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"]]},"variants":[{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration"],"traits":[{"interfaceLanguage":"swift"}]}],"topicSections":[{"title":"Structures","generated":true,"anchor":"Structures","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults"]},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/init()","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:)"]},{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/autoCapture","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/camera","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/common","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/description","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/qualityAttributeThresholds"]}],"metadata":{"title":"BaseFingersAutoCaptureViewController.Configuration","roleHeading":"Class","externalID":"s:14DotFingersCore04BaseB25AutoCaptureViewControllerC13ConfigurationC","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Configuration","kind":"identifier"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"class","extendedModule":"DotFingersCore"},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(cs)NSObject"]},{"title":"Conforms To","type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/DotFingersCore\/objc(pl)NSObject","doc:\/\/DotFingersCore\/s7CVarArgP","doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","doc:\/\/DotFingersCore\/SQ","doc:\/\/DotFingersCore\/SH"]}],"abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/init()":{"type":"topic","kind":"symbol","title":"init()","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/init()","abstract":[{"type":"text","text":"Create the fingers auto capture configuration with default values."}],"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/init()"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/Defaults":{"abstract":[],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/defaults","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Defaults"}],"navigatorTitle":[{"text":"Defaults","kind":"identifier"}],"title":"BaseFingersAutoCaptureViewController.Configuration.Defaults","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/Defaults"},"doc://DotFingersCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFingersCore/s7CVarArgP":{"identifier":"doc:\/\/DotFingersCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/common":{"title":"common","kind":"symbol","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/common","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"common"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration","kind":"typeIdentifier","text":"CommonConfiguration"}],"role":"symbol","type":"topic","abstract":[{"text":"Common configuration for all components. Default is ","type":"text"},{"code":".init()","type":"codeVoice"},{"text":".","type":"text"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/common"},"doc://DotFingersCore/SQ":{"identifier":"doc:\/\/DotFingersCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/description":{"title":"description","kind":"symbol","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","type":"topic","abstract":[],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/description"},"doc://DotFingersCore/SH":{"identifier":"doc:\/\/DotFingersCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/autoCapture":{"type":"topic","kind":"symbol","title":"autoCapture","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/autocapture","abstract":[{"text":"Configuration for auto capture components.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"autoCapture","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration","text":"AutoCaptureConfiguration","kind":"typeIdentifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/autoCapture"},"doc://DotFingersCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotFingersCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/qualityAttributeThresholds":{"role":"symbol","title":"qualityAttributeThresholds","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/qualityattributethresholds","abstract":[{"type":"text","text":"Customize thresholds for the quality attributes of the capture result. Default is "},{"code":".standard","type":"codeVoice"},{"type":"text","text":" preset."}],"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"qualityAttributeThresholds","kind":"identifier"},{"text":": ","kind":"text"},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/qualityAttributeThresholds","kind":"symbol"},"doc://DotFingersCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/camera":{"role":"symbol","title":"camera","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/camera","abstract":[{"text":"Configuration for components utilizing a camera.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"camera","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","text":"CameraConfiguration","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/camera","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration/init(common:camera:autoCapture:qualityAttributeThresholds:)":{"title":"init(common:camera:autoCapture:qualityAttributeThresholds:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"common","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CommonConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTCommonConfiguration"},{"kind":"text","text":", "},{"kind":"externalParam","text":"camera"},{"text":": ","kind":"text"},{"text":"CameraConfiguration","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTCameraConfiguration","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"autoCapture","kind":"externalParam"},{"kind":"text","text":": "},{"text":"AutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCapture@objc(cs)DOTAutoCaptureConfiguration"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"qualityAttributeThresholds"},{"kind":"text","text":": "},{"text":"FingersAutoCaptureQualityAttributeThresholds","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureQualityAttributeThresholds"},{"text":")","kind":"text"}],"abstract":[{"text":"Create the fingers auto capture configuration.","type":"text"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration\/init(common:camera:autocapture:qualityattributethresholds:)","type":"topic","kind":"symbol","role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration\/init(common:camera:autoCapture:qualityAttributeThresholds:)"},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/Configuration":{"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/Configuration","title":"BaseFingersAutoCaptureViewController.Configuration","url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/configuration","abstract":[{"text":"Configuration options for the fingers auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Configuration"}],"navigatorTitle":[{"text":"Configuration","kind":"identifier"}],"kind":"symbol"},"doc://DotFingersCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotFingersCore\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title","value":"DOTFGBaseFingersAutoCaptureViewController","op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"op":"replace"}]}]}