{"metadata":{"role":"symbol","modules":[{"name":"DotFingersCore"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"title":"viewDidDisappear(_:)","externalID":"c:@CM@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureViewController(im)viewDidDisappear:","symbolKind":"method","extendedModule":"DotFingersCore"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","kind":"attribute","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdiddisappear(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidDisappear(_:)","interfaceLanguage":"swift"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController/viewDidDisappear(_:)":{"role":"symbol","title":"viewDidDisappear(_:)","navigatorTitle":[{"text":"viewDidDisappear:","kind":"identifier"}],"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller\/viewdiddisappear(_:)","abstract":[],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController\/viewDidDisappear(_:)","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/BaseFingersAutoCaptureViewController":{"url":"\/documentation\/dotfingerscore\/basefingersautocaptureviewcontroller","abstract":[{"type":"text","text":"UI component for capturing fingers images with customizable UI."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"BaseFingersAutoCaptureViewController"}],"title":"BaseFingersAutoCaptureViewController","type":"topic","kind":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/BaseFingersAutoCaptureViewController"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"add","value":null,"path":"\/metadata\/platforms"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"viewDidDisappear:","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"viewDidDisappear:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"animated"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidDisappear(_:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController~1viewDidDisappear(_:)\/fragments"},{"op":"replace","value":"DOTFGBaseFingersAutoCaptureViewController","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DOTFGBaseFingersAutoCaptureViewController"}],"path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1BaseFingersAutoCaptureViewController\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}