{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator","text":"DocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/validators"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/validators"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/validators","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}],"title":"validators","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureControllerConfiguration(py)validators","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"validators"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration"]]},"references":{"doc://com.innovatrics.dot.document/documentation/DotDocument":{"role":"collection","title":"DotDocument","abstract":[{"type":"text","text":"version: 7.5.0"}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument","kind":"symbol","type":"topic","url":"\/documentation\/dotdocument"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration/validators":{"role":"symbol","title":"validators","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"validators"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"DocumentAutoCaptureDetectionValidator","preciseIdentifier":"c:@M@DotDocument@objc(pl)DOTDDocumentAutoCaptureDetectionValidator"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"Array of validators which will be used to validate input image."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration\/validators","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"validators"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration\/validators"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureControllerConfiguration":{"role":"symbol","title":"DocumentAutoCaptureControllerConfiguration","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"abstract":[{"type":"text","text":"Configuration of the document auto capture non-UI component."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureControllerConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureControllerConfiguration"}],"url":"\/documentation\/dotdocument\/documentautocapturecontrollerconfiguration"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureController":{"role":"symbol","title":"DocumentAutoCaptureController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureController"}],"abstract":[{"type":"text","text":"Non-UI component for the document auto capture process."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureController"}],"url":"\/documentation\/dotdocument\/documentautocapturecontroller"},"doc://com.innovatrics.dot.document/documentation/DotDocument/DocumentAutoCaptureDetectionValidator":{"role":"symbol","title":"DocumentAutoCaptureDetectionValidator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"abstract":[{"type":"text","text":"Use this protocol to create document validators."}],"identifier":"doc:\/\/com.innovatrics.dot.document\/documentation\/DotDocument\/DocumentAutoCaptureDetectionValidator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DocumentAutoCaptureDetectionValidator"}],"url":"\/documentation\/dotdocument\/documentautocapturedetectionvalidator"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"validators"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"validators"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<DOTDDocumentAutoCaptureDetectionValidator>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"validators"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1validators\/title","value":"validators"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration~1validators\/fragments","value":[{"kind":"identifier","text":"validators"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/title","value":"DOTDDocumentAutoCaptureControllerConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureControllerConfiguration\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureControllerConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/title","value":"DOTDDocumentAutoCaptureDetectionValidator"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.document~1documentation~1DotDocument~1DocumentAutoCaptureDetectionValidator\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetectionValidator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}