{"kind":"symbol","metadata":{"role":"symbol","title":"create(cgImage:)","modules":[{"name":"DotPalmCore"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"create"},{"text":"(","kind":"text"},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage"}],"navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTBgrRawImageFactory(cm)createWithCgImage:","symbolKind":"method","roleHeading":"Type Method"},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(cgImage:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return a copy of the "},{"type":"codeVoice","code":"CGImage"},{"text":" as a ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":"object.","type":"text"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(cgimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(cgimage:)"]}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"BgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage"}],"platforms":["iOS"]}]},{"parameters":[{"name":"cgImage","content":[{"type":"paragraph","inlineContent":[{"text":"Input image as a ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}]}]}],"kind":"parameters"},{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"New ","type":"text"},{"type":"codeVoice","code":"BgrRawImage"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotPalmCore/documentation/DotPalmCore":{"url":"\/documentation\/dotpalmcore","title":"DotPalmCore","type":"topic","kind":"symbol","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","abstract":[{"text":"version: 8.7.0","type":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory":{"role":"symbol","title":"BgrRawImageFactory","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgrRawImageFactory","kind":"identifier"}],"navigatorTitle":[{"text":"BgrRawImageFactory","kind":"identifier"}],"abstract":[{"type":"text","text":"Create "},{"code":"BgrRawImage","type":"codeVoice"},{"text":" from iOS native image types.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImageFactory/create(cgImage:)":{"role":"symbol","title":"create(cgImage:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"create","kind":"identifier"},{"kind":"text","text":"("},{"text":"cgImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"text":"BgrRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithCgImage:","kind":"identifier"}],"abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"object."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImageFactory\/create(cgImage:)","type":"topic","kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimagefactory\/create(cgimage:)"},"doc://DotPalmCore/documentation/DotPalmCore/BgrRawImage":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage","title":"BgrRawImage","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"BgrRawImage","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/bgrrawimage","abstract":[{"text":"Raw image with BGR888 pixel format.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"BgrRawImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"createWithCgImage:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithCgImage:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgrRawImage","text":"DOTBgrRawImage","kind":"typeIdentifier","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgrRawImage"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"createWithCgImage:"},{"text":"(","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/title","op":"replace","value":"DOTBgrRawImageFactory"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory\/fragments","value":[{"text":"DOTBgrRawImageFactory","kind":"identifier"}],"op":"replace"},{"value":"createWithCgImage:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(cgImage:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"createWithCgImage:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImageFactory~1create(cgImage:)\/fragments"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/title","value":"DOTBgrRawImage","op":"replace"},{"value":[{"text":"DOTBgrRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgrRawImage\/fragments"}]}]}