{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/placeholdertype\/cornersandmrzfillers"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/placeholdertype\/cornersandmrzfillers"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersAndMrzFillers"},"metadata":{"externalID":"c:@M@DotDocument@E@DOTDPlaceholderType@DOTDPlaceholderTypeCornersAndMrzFillers","roleHeading":"Case","role":"symbol","modules":[{"name":"DotDocument"}],"navigatorTitle":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersAndMrzFillers"}],"title":"PlaceholderType.cornersAndMrzFillers","symbolKind":"case","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornersAndMrzFillers"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"cornersAndMrzFillers"}]}]}],"sections":[],"kind":"symbol","abstract":[{"text":"Placeholder with corners and MRZ (Machine Readable Zone) filler characters.","type":"text"}],"references":{"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","abstract":[{"type":"text","text":"version: 9.0.0"}],"type":"topic","title":"DotDocument","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/PlaceholderType/cornersAndMrzFillers":{"type":"topic","role":"symbol","navigatorTitle":[{"text":"DOTDPlaceholderTypeCornersAndMrzFillers","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType\/cornersAndMrzFillers","abstract":[{"text":"Placeholder with corners and MRZ (Machine Readable Zone) filler characters.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotdocument\/placeholdertype\/cornersandmrzfillers","title":"PlaceholderType.cornersAndMrzFillers","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cornersAndMrzFillers","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/PlaceholderType":{"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/PlaceholderType","type":"topic","abstract":[{"text":"Type of placeholder.","type":"text"}],"navigatorTitle":[{"text":"PlaceholderType","kind":"identifier"}],"title":"PlaceholderType","url":"\/documentation\/dotdocument\/placeholdertype","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"PlaceholderType","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"DOTDPlaceholderTypeCornersAndMrzFillers","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersAndMrzFillers"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"DOTDPlaceholderTypeCornersAndMrzFillers","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTDPlaceholderTypeCornersAndMrzFillers","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersAndMrzFillers\/title"},{"value":[{"kind":"identifier","text":"DOTDPlaceholderTypeCornersAndMrzFillers"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType~1cornersAndMrzFillers\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/title","value":"DOTDPlaceholderType"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/fragments","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1PlaceholderType\/navigatorTitle","value":[{"kind":"identifier","text":"DOTDPlaceholderType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}