{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"instancetype"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBaseConfiguration:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGBaseFingersAutoCaptureConfiguration","text":"DOTFGBaseFingersAutoCaptureConfiguration"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"baseConfiguration"},{"kind":"text","text":" "},{"kind":"identifier","text":"isDetectionLayerVisible:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"kind":"internalParam","text":"isDetectionLayerVisible"},{"kind":"text","text":" "},{"kind":"identifier","text":"placeholder:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFingersCore@objc(cs)DOTFGPlaceholder","text":"DOTFGPlaceholder"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"placeholder"},{"kind":"text","text":";"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration"]]},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfingerscore\/dotfgfingersautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:"]}],"metadata":{"title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","externalID":"c:@M@DotFingersCore@objc(cs)DOTFGFingersAutoCaptureConfiguration(im)initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","roleHeading":"Instance Method","role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}],"navigatorTitle":[{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"modules":[{"name":"DotFingersCore"}],"symbolKind":"method"},"abstract":[{"type":"text","text":"Create the fingers auto capture configuration."}],"identifier":{"url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","interfaceLanguage":"occ"},"references":{"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureConfiguration/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:":{"role":"symbol","title":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","type":"topic","abstract":[{"text":"Create the fingers auto capture configuration.","type":"text"}],"kind":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"}],"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureconfiguration\/initwithbaseconfiguration:isdetectionlayervisible:placeholder:","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration\/initWithBaseConfiguration:isDetectionLayerVisible:placeholder:"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGFingersAutoCaptureConfiguration":{"url":"\/documentation\/dotfingerscore\/dotfgfingersautocaptureconfiguration","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGFingersAutoCaptureConfiguration","title":"DOTFGFingersAutoCaptureConfiguration","type":"topic","role":"symbol","fragments":[{"kind":"identifier","text":"DOTFGFingersAutoCaptureConfiguration"}],"kind":"symbol","abstract":[{"text":"Configuration options for the UI Fingers Auto Capture component.","type":"text"}]},"doc://DotFingersCore/documentation/DotFingersCore/Placeholder":{"role":"symbol","title":"Placeholder","navigatorTitle":[{"kind":"identifier","text":"Placeholder"}],"abstract":[{"type":"text","text":"Placeholder."}],"url":"\/documentation\/dotfingerscore\/placeholder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Placeholder"}],"type":"topic","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/Placeholder","kind":"symbol"},"doc://DotFingersCore/documentation/DotFingersCore/DOTFGBaseFingersAutoCaptureConfiguration":{"role":"symbol","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DOTFGBaseFingersAutoCaptureConfiguration","type":"topic","fragments":[{"text":"DOTFGBaseFingersAutoCaptureConfiguration","kind":"identifier"}],"title":"DOTFGBaseFingersAutoCaptureConfiguration","url":"\/documentation\/dotfingerscore\/dotfgbasefingersautocaptureconfiguration","kind":"symbol","abstract":[{"type":"text","text":"Configuration options for the fingers auto capture process."}]},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]}},"variantOverrides":[{"patch":[{"value":"DOTFGPlaceholder","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/title"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/fragments"},{"value":[{"kind":"identifier","text":"DOTFGPlaceholder"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1Placeholder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}