{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration\/init","interfaceLanguage":"occ"},"metadata":{"title":"init","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"symbolKind":"method","role":"symbol","externalID":"c:@M@DotCore@objc(cs)DotFingersDetectionModuleConfiguration(im)init"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration\/init"]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration"]]},"references":{"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration/init":{"type":"topic","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration\/init","abstract":[],"kind":"symbol","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"title":"init","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration\/init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DotFingersDetectionModuleConfiguration":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}],"title":"DotFingersDetectionModuleConfiguration","url":"\/documentation\/dotdocument\/dotfingersdetectionmoduleconfiguration","kind":"symbol","type":"topic","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotFingersDetectionModuleConfiguration","abstract":[{"type":"text","text":"Fingers detection module configuration."}],"navigatorTitle":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","title":"DotDocument","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 9.5.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/title","value":"DotFingersDetectionModuleConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/fragments","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotFingersDetectionModuleConfiguration\/navigatorTitle","value":[{"text":"DotFingersDetectionModuleConfiguration","kind":"identifier"}]}]}]}