{"metadata":{"symbolKind":"method","roleHeading":"Instance Method","modules":[{"name":"DotFaceCore"}],"title":"match(referenceTemplate:probeTemplate:)","role":"symbol","externalID":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcher(im)matchWithReferenceTemplate:probeTemplate:error:","navigatorTitle":[{"kind":"identifier","text":"matchWithReferenceTemplate:probeTemplate:error:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplate"},{"text":": ","kind":"text"},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":", ","kind":"text"},{"text":"probeTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> "},{"preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC","kind":"typeIdentifier","text":"Result"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplate:probeTemplate:)"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Match reference and probe face templates.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"match","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"referenceTemplate"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","text":"Template","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"probeTemplate"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier","text":"Template"},{"kind":"text","text":") "},{"text":"throws","kind":"keyword"},{"text":" -> ","kind":"text"},{"text":"Result","kind":"typeIdentifier","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/Result"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Template"}]}],"name":"referenceTemplate"},{"content":[{"inlineContent":[{"type":"text","text":"Template"}],"type":"paragraph"}],"name":"probeTemplate"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"Result with matching score.","type":"text"}],"type":"paragraph"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher"]]},"variants":[{"paths":["\/documentation\/dotfacecore\/templatematcher\/match(referencetemplate:probetemplate:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/templatematcher\/match(referencetemplate:probetemplate:)"]}],"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TemplateMatcher","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"TemplateMatcher","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Stateless class which can match templates.","type":"text"}],"title":"TemplateMatcher","url":"\/documentation\/dotfacecore\/templatematcher","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","role":"collection","type":"topic","title":"DotFaceCore","kind":"symbol","url":"\/documentation\/dotfacecore","abstract":[{"text":"version: 8.2.1","type":"text"}]},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DOTFTemplateMatcherResult":{"type":"topic","url":"\/documentation\/dotfacecore\/dotftemplatematcherresult","fragments":[{"text":"DOTFTemplateMatcherResult","kind":"identifier"}],"title":"DOTFTemplateMatcherResult","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateMatcherResult","abstract":[{"type":"text","text":"Template matcher result."}],"role":"symbol","kind":"symbol"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher/Result":{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/Result","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Result","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"Result","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Template matcher result.","type":"text"}],"title":"TemplateMatcher.Result","url":"\/documentation\/dotfacecore\/templatematcher\/result","type":"topic"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/Template":{"role":"symbol","abstract":[{"type":"text","text":"Face template."}],"type":"topic","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Template"}],"navigatorTitle":[{"kind":"identifier","text":"Template"}],"title":"Template","url":"\/documentation\/dotfacecore\/template"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/TemplateMatcher/match(referenceTemplate:probeTemplate:)":{"abstract":[{"type":"text","text":"Match reference and probe face templates."}],"kind":"symbol","title":"match(referenceTemplate:probeTemplate:)","url":"\/documentation\/dotfacecore\/templatematcher\/match(referencetemplate:probetemplate:)","navigatorTitle":[{"text":"matchWithReferenceTemplate:probeTemplate:error:","kind":"identifier"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/TemplateMatcher\/match(referenceTemplate:probeTemplate:)","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"match"},{"text":"(","kind":"text"},{"text":"referenceTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Template","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate"},{"text":", ","kind":"text"},{"text":"probeTemplate","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier","text":"Template"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> ","kind":"text"},{"text":"Result","preciseIdentifier":"s:11DotFaceCore15TemplateMatcherC6ResultC","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"matchWithReferenceTemplate:probeTemplate:error:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"matchWithReferenceTemplate:probeTemplate:error:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DOTFTemplateMatcherResult","text":"DOTFTemplateMatcherResult","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplateMatcherResult","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"matchWithReferenceTemplate:","kind":"identifier"},{"kind":"text","text":"("},{"text":"DOTFTemplate","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"referenceTemplate"},{"kind":"text","text":" "},{"kind":"identifier","text":"probeTemplate:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/Template","preciseIdentifier":"c:@M@DotFaceCore@objc(cs)DOTFTemplate","kind":"typeIdentifier","text":"DOTFTemplate"},{"kind":"text","text":" *) "},{"text":"probeTemplate","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"DOTFTemplateMatcher","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/title"},{"op":"replace","value":[{"text":"DOTFTemplateMatcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/title","value":"DOTFTemplate"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1Template\/fragments","op":"replace","value":[{"text":"DOTFTemplate","kind":"identifier"}]},{"value":"matchWithReferenceTemplate:probeTemplate:error:","op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplate:probeTemplate:)\/title"},{"path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1TemplateMatcher~1match(referenceTemplate:probeTemplate:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"matchWithReferenceTemplate:probeTemplate:error:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}