{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgraRawImage:)"},"kind":"symbol","abstract":[{"text":"Return a copy of the ","type":"text"},{"code":"BgraRawImage","type":"codeVoice"},{"type":"text","text":" as a "},{"type":"codeVoice","code":"CGImage"},{"type":"text","text":" object."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","symbolKind":"method","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"}],"roleHeading":"Type Method","title":"create(bgraRawImage:)","navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"externalID":"c:@M@DotCore@objc(cs)DOTCGImageFactory(cm)createWithBgraRawImage:","modules":[{"name":"DotFaceLite"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"bgraRawImage","content":[{"inlineContent":[{"type":"text","text":"Input image as a "},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" object."}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"New "},{"code":"CGImage","type":"codeVoice"},{"text":" instance.","type":"text"}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"paths":["\/documentation\/dotfacelite\/cgimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacelite\/cgimagefactory\/create(bgrarawimage:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory":{"navigatorTitle":[{"text":"CGImageFactory","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"CGImageFactory"}],"role":"symbol","abstract":[{"text":"Create ","type":"text"},{"code":"CGImage","type":"codeVoice"},{"text":" from ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" or "},{"type":"codeVoice","code":"BgrRawImage"},{"type":"text","text":"."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/cgimagefactory","type":"topic","title":"CGImageFactory","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory"},"doc://DotFaceLite/documentation/DotFaceLite/BgraRawImage":{"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite\/bgrarawimage","type":"topic","title":"BgraRawImage","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage"},"doc://DotFaceLite/documentation/DotFaceLite":{"url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","role":"collection","kind":"symbol","type":"topic","abstract":[{"text":"version: 8.15.1","type":"text"}],"title":"DotFaceLite"},"doc://DotFaceLite/documentation/DotFaceLite/CGImageFactory/create(bgraRawImage:)":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"create"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"BgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage"},{"kind":"text","text":") -> "},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"createWithBgraRawImage:","kind":"identifier"}],"type":"topic","abstract":[{"text":"Return a copy of the ","type":"text"},{"type":"codeVoice","code":"BgraRawImage"},{"type":"text","text":" as a "},{"code":"CGImage","type":"codeVoice"},{"text":" object.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/CGImageFactory\/create(bgraRawImage:)","url":"\/documentation\/dotfacelite\/cgimagefactory\/create(bgrarawimage:)","title":"create(bgraRawImage:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"createWithBgraRawImage:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"createWithBgraRawImage:"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"text":"createWithBgraRawImage:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BgraRawImage","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"DOTBgraRawImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"bgraRawImage"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/title","value":"DOTCGImageFactory","op":"replace"},{"op":"replace","value":[{"text":"DOTCGImageFactory","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory\/fragments"},{"value":"DOTBgraRawImage","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/title"},{"value":[{"text":"DOTBgraRawImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BgraRawImage\/fragments"},{"op":"replace","value":"createWithBgraRawImage:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgraRawImage:)\/title"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1CGImageFactory~1create(bgraRawImage:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"createWithBgraRawImage:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}