{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdiddisappear(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdiddisappear(_:)"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"roleHeading":"Instance Method","extendedModule":"DotFaceCore","modules":[{"name":"DotFaceCore"}],"title":"viewDidDisappear(_:)","role":"symbol","externalID":"c:@CM@DotFaceCore@objc(cs)DOTFSmileLivenessViewController(im)viewDidDisappear:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"kind":"text","text":"("},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"viewDidDisappear"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"animated","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidDisappear(_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","role":"collection","abstract":[{"text":"version: 8.11.0","type":"text"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","url":"\/documentation\/dotfacecore","title":"DotFaceCore"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController/viewDidDisappear(_:)":{"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController\/viewDidDisappear(_:)","title":"viewDidDisappear(_:)","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller\/viewdiddisappear(_:)","abstract":[],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"viewDidDisappear","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"viewDidDisappear:"}],"kind":"symbol","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/SmileLivenessViewController":{"kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SmileLivenessViewController"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SmileLivenessViewController","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/SmileLivenessViewController","url":"\/documentation\/dotfacecore\/smilelivenessviewcontroller","title":"SmileLivenessViewController","abstract":[{"text":"UI component for evaluating liveness by detecting face expression.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"viewDidDisappear:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"viewDidDisappear:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"kind":"text","text":") "},{"text":"animated","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"op":"replace","value":"viewDidDisappear:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidDisappear(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"viewDidDisappear:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController~1viewDidDisappear(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/title","value":"DOTFSmileLivenessViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1SmileLivenessViewController\/fragments","value":[{"kind":"identifier","text":"DOTFSmileLivenessViewController"}]}]}]}