{"identifier":{"interfaceLanguage":"occ","url":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration\/init"},"variants":[{"paths":["\/documentation\/dotfingerscore\/dotfaceexpressionneutralmoduleconfiguration\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFingersCore\/documentation\/DotFingersCore","doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration"]]},"metadata":{"title":"init","roleHeading":"Instance Method","externalID":"c:@M@DotCore@objc(cs)DotFaceExpressionNeutralModuleConfiguration(im)init","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotFingersCore"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"instancetype","kind":"keyword"},{"text":") ","kind":"text"},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}],"sections":[],"kind":"symbol","references":{"doc://DotFingersCore/documentation/DotFingersCore/DotFaceExpressionNeutralModuleConfiguration/init":{"type":"topic","kind":"symbol","title":"init","url":"\/documentation\/dotfingerscore\/dotfaceexpressionneutralmoduleconfiguration\/init","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration\/init"},"doc://DotFingersCore/documentation/DotFingersCore":{"role":"collection","identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore","type":"topic","title":"DotFingersCore","url":"\/documentation\/dotfingerscore","kind":"symbol","abstract":[{"type":"text","text":"version: 9.5.0"}]},"doc://DotFingersCore/documentation/DotFingersCore/DotFaceExpressionNeutralModuleConfiguration":{"kind":"symbol","title":"DotFaceExpressionNeutralModuleConfiguration","url":"\/documentation\/dotfingerscore\/dotfaceexpressionneutralmoduleconfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Face expression neutral module."}],"identifier":"doc:\/\/DotFingersCore\/documentation\/DotFingersCore\/DotFaceExpressionNeutralModuleConfiguration"}},"variantOverrides":[{"patch":[{"value":"DotFaceExpressionNeutralModuleConfiguration","op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/title"},{"value":[{"kind":"identifier","text":"DotFaceExpressionNeutralModuleConfiguration"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/fragments"},{"value":[{"text":"DotFaceExpressionNeutralModuleConfiguration","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFingersCore~1documentation~1DotFingersCore~1DotFaceExpressionNeutralModuleConfiguration\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}