{"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/description"},"sections":[],"metadata":{"platforms":[{"introducedAt":"13.0","beta":false,"deprecated":false,"name":"iOS","unavailable":false}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","externalID":"c:@M@DotNfc@objc(cs)DOTNNfcKey(py)description","roleHeading":"Instance Property","modules":[{"name":"DotNfc"}],"role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"description"}]},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/nfckey\/description"]},{"paths":["\/documentation\/dotnfc\/nfckey\/description"],"traits":[{"interfaceLanguage":"occ"}]}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use classes of `TravelDocumentReaderPassword` protocol instead.)"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"override"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}]}],"kind":"symbol","references":{"doc://DotNfc/documentation/DotNfc":{"type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","abstract":[{"text":"version: 8.14.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotnfc","title":"DotNfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/NfcTravelDocumentReader":{"title":"NfcTravelDocumentReader","kind":"symbol","url":"\/documentation\/dotnfc\/nfctraveldocumentreader","type":"topic","role":"symbol","navigatorTitle":[{"text":"NfcTravelDocumentReader","kind":"identifier"}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcTravelDocumentReader","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"NfcTravelDocumentReader"}],"abstract":[{"text":"Non-UI component for reading travel documents using NFC technology.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/NfcKey":{"abstract":[{"type":"text","text":"NFC password created from document number, date of expiry and date of birth of MRZ."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"NfcKey"}],"deprecated":true,"url":"\/documentation\/dotnfc\/nfckey","navigatorTitle":[{"text":"NfcKey","kind":"identifier"}],"title":"NfcKey","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey","kind":"symbol","role":"symbol"},"doc://DotNfc/documentation/DotNfc/NfcKey/description":{"url":"\/documentation\/dotnfc\/nfckey\/description","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"title":"description","kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/NfcKey\/description","type":"topic","deprecated":true,"role":"symbol","abstract":[],"navigatorTitle":[{"text":"description","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"value":"description","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"description","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"description"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTNNfcTravelDocumentReader","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcTravelDocumentReader\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTNNfcTravelDocumentReader"}]},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/title","value":"DOTNNfcKey"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey\/fragments","value":[{"text":"DOTNNfcKey","kind":"identifier"}],"op":"replace"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1description\/title"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1NfcKey~1description\/fragments","op":"replace","value":[{"text":"description","kind":"identifier"}]}]}]}