{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/document"},"sections":[],"kind":"symbol","abstract":[{"text":"Detected document, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the document was not detected in the image."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"document","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector","kind":"typeIdentifier","text":"DocumentDetector"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Document","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/document"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotdocument\/documentautocapturedetection\/document"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"modules":[{"name":"DotDocument"}],"externalID":"c:@M@DotDocument@objc(cs)DOTDDocumentAutoCaptureDetection(py)document","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"document","kind":"identifier"}],"title":"document","roleHeading":"Instance Property","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"document"},{"text":": ","kind":"text"},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"kind":"text","text":"."},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"]]},"references":{"doc://DotDocument/documentation/DotDocument":{"role":"collection","abstract":[{"text":"version: 8.13.0","type":"text"}],"title":"DotDocument","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","type":"topic","url":"\/documentation\/dotdocument\/documentdetector","title":"DocumentDetector","abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentDetector","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection":{"abstract":[{"text":"The result of processing video frame during the document auto capture process.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DocumentAutoCaptureDetection","navigatorTitle":[{"text":"DocumentAutoCaptureDetection","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentautocapturedetection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection"},"doc://DotDocument/documentation/DotDocument/DOTDDocumentDetectorDocument":{"abstract":[{"type":"text","text":"Result of the document detection process."}],"title":"DOTDDocumentDetectorDocument","url":"\/documentation\/dotdocument\/dotddocumentdetectordocument","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument","fragments":[{"text":"DOTDDocumentDetectorDocument","kind":"identifier"}],"kind":"symbol","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"abstract":[{"text":"Result of the document detection process.","type":"text"}],"kind":"symbol","title":"DocumentDetector.Document","url":"\/documentation\/dotdocument\/documentdetector\/document","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"Document","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureDetection/document":{"url":"\/documentation\/dotdocument\/documentautocapturedetection\/document","type":"topic","kind":"symbol","abstract":[{"text":"Detected document, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"type":"text","text":" if the document was not detected in the image."}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureDetection\/document","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"document","kind":"identifier"},{"kind":"text","text":": "},{"text":"DocumentDetector","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetector"},{"text":".","kind":"text"},{"text":"Document","preciseIdentifier":"s:11DotDocument0B8DetectorC0B0C","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"document","role":"symbol","navigatorTitle":[{"text":"document","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/DocumentAutoCaptureController":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentAutoCaptureController","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentAutoCaptureController","kind":"identifier"}],"title":"DocumentAutoCaptureController","type":"topic","kind":"symbol","url":"\/documentation\/dotdocument\/documentautocapturecontroller","navigatorTitle":[{"text":"DocumentAutoCaptureController","kind":"identifier"}],"role":"symbol","abstract":[{"text":"Non-UI component for the document auto capture process.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"document","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"document","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"DOTDDocumentDetectorDocument","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentDetectorDocument","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DOTDDocumentDetectorDocument"},{"text":" * ","kind":"text"},{"text":"document","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","value":"DOTDDocumentDetector","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentDetector"}]},{"value":"DOTDDocumentAutoCaptureDetection","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureDetection"}],"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1document\/title","value":"document"},{"value":[{"kind":"identifier","text":"document"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureDetection~1document\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/title","value":"DOTDDocumentAutoCaptureController"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentAutoCaptureController\/fragments","value":[{"kind":"identifier","text":"DOTDDocumentAutoCaptureController"}]}]}]}