{"seeAlsoSections":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"title":"QualityAttributeId","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@M@DotFaceCore@E@DOTQualityAttributeId","modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}]},"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"sections":[],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.innovatrics.dot.face.core\/s12CaseIterableP","doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP","doc:\/\/com.innovatrics.dot.face.core\/SQ","doc:\/\/com.innovatrics.dot.face.core\/SH","doc:\/\/com.innovatrics.dot.face.core\/SY"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/backgroundUniformity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/brightness","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/contrast","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/eyeStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/faceConfidence","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/glassStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/light","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mask","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mouthStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/pitchAngle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/position","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/proximity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/shadow","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/sharpness","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/uniqueIntensityLevels","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/yawAngle"]},{"title":"Initializers","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/init(rawValue:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/description"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/Equatable-Implementations","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/RawRepresentable-Implementations"],"generated":true}],"variants":[{"paths":["\/documentation\/dotfacecore\/qualityattributeid"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotfacecore\/qualityattributeid"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTQualityAttributeId) "},{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.innovatrics.dot.face.core/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SQ"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/glassStatus":{"role":"symbol","title":"QualityAttributeId.glassStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"glassStatus"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/glassStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdGlassStatus"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/glassstatus"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId":{"role":"symbol","title":"QualityAttributeId","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttributeId"}],"abstract":[{"type":"text","text":"A value identifying the quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttributeId"}],"url":"\/documentation\/dotfacecore\/qualityattributeid"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/PassiveLivenessQualityProvider":{"role":"symbol","title":"PassiveLivenessQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for passive liveness evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PassiveLivenessQualityProvider"}],"url":"\/documentation\/dotfacecore\/passivelivenessqualityprovider"},"doc://com.innovatrics.dot.face.core/s12CaseIterableP":{"type":"unresolvable","title":"Swift.CaseIterable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s12CaseIterableP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/brightness":{"role":"symbol","title":"QualityAttributeId.brightness","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"brightness"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/brightness","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdBrightness"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/brightness"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/qualityattributeid\/init(rawvalue:)"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/uniqueIntensityLevels":{"role":"symbol","title":"QualityAttributeId.uniqueIntensityLevels","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uniqueIntensityLevels"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/uniqueIntensityLevels","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdUniqueIntensityLevels"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/uniqueintensitylevels"},"doc://com.innovatrics.dot.face.core/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.innovatrics.dot.face.core\/s23CustomStringConvertibleP"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/IcaoQualityProvider":{"role":"symbol","title":"IcaoQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"IcaoQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for ICAO evaluation."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IcaoQualityProvider"}],"url":"\/documentation\/dotfacecore\/icaoqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttribute":{"role":"symbol","title":"QualityAttribute","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityAttribute"}],"abstract":[{"type":"text","text":"Quality attribute of the face auto capture result."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityAttribute"}],"url":"\/documentation\/dotfacecore\/qualityattribute"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/mask":{"role":"symbol","title":"QualityAttributeId.mask","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mask"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mask","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdMask"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/mask"},"doc://com.innovatrics.dot.face.core/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SY"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/DefaultQualityAttributeRegistry":{"role":"symbol","title":"DefaultQualityAttributeRegistry","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"abstract":[{"type":"text","text":"This class contains default "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" for every "},{"type":"codeVoice","code":"QualityAttributeId"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DefaultQualityAttributeRegistry"}],"url":"\/documentation\/dotfacecore\/defaultqualityattributeregistry"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/qualityattributeid\/rawrepresentable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/eyeStatus":{"role":"symbol","title":"QualityAttributeId.eyeStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"eyeStatus"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/eyeStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdEyeStatus"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/eyestatus"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/mouthStatus":{"role":"symbol","title":"QualityAttributeId.mouthStatus","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"mouthStatus"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mouthStatus","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdMouthStatus"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/mouthstatus"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/pitchAngle":{"role":"symbol","title":"QualityAttributeId.pitchAngle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"pitchAngle"}],"abstract":[{"type":"text","text":"Valid values are in range [-180.0, 180.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/pitchAngle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdPitchAngle"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/pitchangle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceAutoCaptureViewController":{"role":"symbol","title":"FaceAutoCaptureViewController","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"abstract":[{"type":"text","text":"UI component for capturing high quality face images using the placeholder."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceAutoCaptureViewController","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"url":"\/documentation\/dotfacecore\/faceautocaptureviewcontroller"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/sharpness":{"role":"symbol","title":"QualityAttributeId.sharpness","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"sharpness"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/sharpness","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdSharpness"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/sharpness"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/light":{"role":"symbol","title":"QualityAttributeId.light","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"light"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/light","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdLight"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/light"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/MatchingQualityProvider":{"role":"symbol","title":"MatchingQualityProvider","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"MatchingQualityProvider"}],"abstract":[{"type":"text","text":"This class provides set of "},{"type":"codeVoice","code":"QualityAttribute"},{"type":"text","text":" objects recommended for matching."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MatchingQualityProvider"}],"url":"\/documentation\/dotfacecore\/matchingqualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/shadow":{"role":"symbol","title":"QualityAttributeId.shadow","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"shadow"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/shadow","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdShadow"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/shadow"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/proximity":{"role":"symbol","title":"QualityAttributeId.proximity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"proximity"}],"abstract":[{"type":"text","text":"Valid values are in [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/proximity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdProximity"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/proximity"},"doc://com.innovatrics.dot.face.core/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.innovatrics.dot.face.core\/SH"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/position":{"role":"symbol","title":"QualityAttributeId.position","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"position"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/position","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdPosition"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/position"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/contrast":{"role":"symbol","title":"QualityAttributeId.contrast","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"contrast"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/contrast","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdContrast"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/contrast"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/yawAngle":{"role":"symbol","title":"QualityAttributeId.yawAngle","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"yawAngle"}],"abstract":[{"type":"text","text":"Valid values are in range [-180.0, 180.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/yawAngle","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdYawAngle"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/yawangle"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/description":{"role":"symbol","title":"description","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/description","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/qualityattributeid\/description"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityProvider":{"role":"symbol","title":"QualityProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"QualityProvider"}],"abstract":[{"type":"text","text":"Provider of quality attributes configured for specific use case."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"QualityProvider"}],"url":"\/documentation\/dotfacecore\/qualityprovider"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/dotfacecore\/qualityattributeid\/equatable-implementations"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/faceConfidence":{"role":"symbol","title":"QualityAttributeId.faceConfidence","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceConfidence"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/faceConfidence","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdFaceConfidence"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/faceconfidence"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"DotFaceCore is a part of DotFace framework group which provides components for the digital onboarding process using the latest Innovatrics IFace image processing library. It wraps the core functionality of IFace library to a higher-level module which is easy to integrate into an iOS application."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/QualityAttributeId/backgroundUniformity":{"role":"symbol","title":"QualityAttributeId.backgroundUniformity","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"backgroundUniformity"}],"abstract":[{"type":"text","text":"Valid values are in range [0.0, 1.0]."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/backgroundUniformity","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}],"url":"\/documentation\/dotfacecore\/qualityattributeid\/backgrounduniformity"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"DOTQualityAttributeId"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/backgroundUniformity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/brightness","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/contrast","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/eyeStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/faceConfidence","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/glassStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/light","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mask","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/mouthStatus","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/pitchAngle","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/position","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/proximity","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/shadow","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/sharpness","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/uniqueIntensityLevels","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttributeId\/yawAngle"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"replace","path":"\/seeAlsoSections","value":[{"title":"Quality attributes configuration","identifiers":["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityAttribute","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/DefaultQualityAttributeRegistry","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/QualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/MatchingQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/PassiveLivenessQualityProvider","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/IcaoQualityProvider"],"generated":true}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTQualityAttributeId"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1glassStatus\/title","value":"DOTQualityAttributeIdGlassStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1glassStatus\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdGlassStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/title","value":"DOTQualityAttributeId"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeId"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/title","value":"DOTPassiveLivenessQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1PassiveLivenessQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTPassiveLivenessQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1brightness\/title","value":"DOTQualityAttributeIdBrightness"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1brightness\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdBrightness"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1uniqueIntensityLevels\/title","value":"DOTQualityAttributeIdUniqueIntensityLevels"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1uniqueIntensityLevels\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdUniqueIntensityLevels"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/title","value":"DOTIcaoQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1IcaoQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTIcaoQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/title","value":"DOTQualityAttribute"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttribute\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttribute"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1mask\/title","value":"DOTQualityAttributeIdMask"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1mask\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdMask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/title","value":"DOTDefaultQualityAttributeRegistry"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1DefaultQualityAttributeRegistry\/fragments","value":[{"kind":"identifier","text":"DOTDefaultQualityAttributeRegistry"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1eyeStatus\/title","value":"DOTQualityAttributeIdEyeStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1eyeStatus\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdEyeStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1mouthStatus\/title","value":"DOTQualityAttributeIdMouthStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1mouthStatus\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdMouthStatus"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1pitchAngle\/title","value":"DOTQualityAttributeIdPitchAngle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1pitchAngle\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdPitchAngle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/title","value":"DOTFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFaceAutoCaptureViewController"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1sharpness\/title","value":"DOTQualityAttributeIdSharpness"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1sharpness\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdSharpness"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1light\/title","value":"DOTQualityAttributeIdLight"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1light\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdLight"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/title","value":"DOTMatchingQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1MatchingQualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTMatchingQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1shadow\/title","value":"DOTQualityAttributeIdShadow"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1shadow\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdShadow"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1proximity\/title","value":"DOTQualityAttributeIdProximity"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1proximity\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdProximity"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1position\/title","value":"DOTQualityAttributeIdPosition"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1position\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdPosition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1contrast\/title","value":"DOTQualityAttributeIdContrast"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1contrast\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdContrast"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1yawAngle\/title","value":"DOTQualityAttributeIdYawAngle"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1yawAngle\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdYawAngle"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/title","value":"DOTQualityProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityProvider\/fragments","value":[{"kind":"identifier","text":"DOTQualityProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1faceConfidence\/title","value":"DOTQualityAttributeIdFaceConfidence"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1faceConfidence\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdFaceConfidence"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1backgroundUniformity\/title","value":"DOTQualityAttributeIdBackgroundUniformity"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1QualityAttributeId~1backgroundUniformity\/fragments","value":[{"kind":"identifier","text":"DOTQualityAttributeIdBackgroundUniformity"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}