{"metadata":{"externalID":"c:@M@DotCore@objc(cs)DOTBgraRawImage(py)bytesPointer","role":"symbol","title":"bytesPointer","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bytesPointer"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sp","text":"UnsafeMutablePointer"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V","text":"UInt8"},{"text":">","kind":"text"}],"roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"symbolKind":"property","modules":[{"name":"DotNfc"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointer"},"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotnfc\/bgrarawimage\/bytespointer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/bgrarawimage\/bytespointer"]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/BgraRawImage/bytesPointer":{"kind":"symbol","abstract":[],"role":"symbol","title":"bytesPointer","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"bytesPointer","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UnsafeMutablePointer","kind":"typeIdentifier","preciseIdentifier":"s:Sp"},{"text":"<","kind":"text"},{"text":"UInt8","kind":"typeIdentifier","preciseIdentifier":"s:s5UInt8V"},{"text":">","kind":"text"}],"url":"\/documentation\/dotnfc\/bgrarawimage\/bytespointer","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage\/bytesPointer","navigatorTitle":[{"kind":"identifier","text":"bytesPointer"}],"type":"topic"},"doc://DotNfc/documentation/DotNfc/BgraRawImage":{"abstract":[{"text":"Raw image with BGRA8888 pixel format.","type":"text"}],"title":"BgraRawImage","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"BgraRawImage"}],"type":"topic","navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/BgraRawImage","url":"\/documentation\/dotnfc\/bgrarawimage"},"doc://DotNfc/documentation/DotNfc":{"role":"collection","title":"DotNfc","type":"topic","abstract":[{"text":"version: 8.6.1","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","url":"\/documentation\/dotnfc"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"bytesPointer","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@T@uint8_t","kind":"typeIdentifier","text":"uint8_t"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"bytesPointer"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointer\/title","op":"replace","value":"bytesPointer"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage~1bytesPointer\/fragments","value":[{"text":"bytesPointer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/title","value":"DOTBgraRawImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1BgraRawImage\/fragments","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}