{"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary"]]},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/initialize(license:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"text":"Initialize library with license.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":""},{"type":"codeVoice","code":"DotSdk"},{"text":" license.","type":"text"}],"type":"paragraph"}],"name":"license"}]}],"metadata":{"title":"initialize(license:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"initialize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"license","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DotSdkLicenseProxyProtocol","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"}],"navigatorTitle":[{"text":"initializeWithLicense:error:","kind":"identifier"}],"role":"symbol","externalID":"c:@M@DotDocument@objc(cs)DotDocumentLibrary(im)initializeWithLicense:error:","modules":[{"name":"DotDocument"}],"symbolKind":"method"},"variants":[{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotdocument\/dotdocumentlibrary\/initialize(license:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://DotDocument/documentation/DotDocument/DotSdkLicenseProxyProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DotSdkLicenseProxyProtocol"}],"url":"\/documentation\/dotdocument\/dotsdklicenseproxyprotocol","abstract":[],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotSdkLicenseProxyProtocol","type":"topic","navigatorTitle":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"DotSdkLicenseProxyProtocol"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary":{"url":"\/documentation\/dotdocument\/dotdocumentlibrary","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"DotDocumentLibrary","kind":"identifier"}],"title":"DotDocumentLibrary","type":"topic","navigatorTitle":[{"text":"DotDocumentLibrary","kind":"identifier"}],"abstract":[{"type":"text","text":"Class responsible for the "},{"code":"DotDocument","type":"codeVoice"},{"text":" library initialization.","type":"text"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary","kind":"symbol"},"doc://DotDocument/documentation/DotDocument":{"title":"DotDocument","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","role":"collection","abstract":[{"type":"text","text":"version: 8.9.0"}],"kind":"symbol","url":"\/documentation\/dotdocument"},"doc://DotDocument/documentation/DotDocument/DotDocumentLibrary/initialize(license:)":{"navigatorTitle":[{"kind":"identifier","text":"initializeWithLicense:error:"}],"title":"initialize(license:)","kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"initialize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"license"},{"kind":"text","text":": "},{"text":"DotSdkLicenseProxyProtocol","preciseIdentifier":"c:@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DotDocumentLibrary\/initialize(license:)","abstract":[{"text":"Initialize library with license.","type":"text"}],"type":"topic","url":"\/documentation\/dotdocument\/dotdocumentlibrary\/initialize(license:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initializeWithLicense:error:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initializeWithLicense:"},{"text":"(","kind":"text"},{"text":"id<DotSdkLicenseProxyProtocol>","preciseIdentifier":"c:Qo@M@DotCore@objc(pl)DotSdkLicenseProxyProtocol","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"license"},{"text":" ","kind":"text"},{"kind":"identifier","text":"error:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"DotSdkLicenseProxyProtocol","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotSdkLicenseProxyProtocol\/fragments","value":[{"text":"DotSdkLicenseProxyProtocol","kind":"identifier"}]},{"value":"DotDocumentLibrary","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/title"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary\/fragments","value":[{"text":"DotDocumentLibrary","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1initialize(license:)\/title","value":"initializeWithLicense:error:"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DotDocumentLibrary~1initialize(license:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initializeWithLicense:error:","kind":"identifier"}]}]}]}