{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/detect(bgrarawimage:limit:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/detect(bgrarawimage:limit:)"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"detect","kind":"identifier"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","text":"BgraRawImage"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" = 1) ","kind":"text"},{"kind":"keyword","text":"throws"},{"text":" -> [","kind":"text"},{"preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"typeIdentifier","text":"Palm"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Image on which is performed the detection."}],"type":"paragraph"}],"name":"bgraRawImage"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Limit the number of palms to detect. Currently is supported to detect only one palm."}]}],"name":"limit"}]},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Array of detected palms."}]}],"kind":"content"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"inlineContent":[{"text":"This method should be called on the background thread.","type":"text"}],"type":"paragraph"},{"name":"Throws","type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"Throws an error if "},{"type":"codeVoice","code":"PalmDetector"},{"type":"text","text":" fails to execute palm detection."}],"type":"paragraph"}]}],"kind":"content"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"text":"bgraRawImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","kind":"typeIdentifier","text":"BgraRawImage"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limit"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"text":") ","kind":"text"},{"text":"throws","kind":"keyword"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm"},{"text":"]","kind":"text"}],"title":"detect(bgraRawImage:limit:)","navigatorTitle":[{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"symbolKind":"method","modules":[{"name":"DotPalmCore"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector(im)detectWithBgraRawImage:limit:error:","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"abstract":[{"text":"Detect palms in an image.","type":"text"}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(bgraRawImage:limit:)","interfaceLanguage":"swift"},"kind":"symbol","references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore":{"title":"DotPalmCore","abstract":[{"type":"text","text":"version: 8.14.0"}],"kind":"symbol","url":"\/documentation\/dotpalmcore","role":"collection","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/BgraRawImage":{"role":"symbol","title":"BgraRawImage","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"BgraRawImage"}],"url":"\/documentation\/dotpalmcore\/bgrarawimage","abstract":[{"type":"text","text":"Raw image with BGRA8888 pixel format."}],"navigatorTitle":[{"text":"BgraRawImage","kind":"identifier"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/detect(bgraRawImage:limit:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"detect"},{"kind":"text","text":"("},{"kind":"externalParam","text":"bgraRawImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","text":"BgraRawImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"limit","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"text":") ","kind":"text"},{"kind":"keyword","text":"throws"},{"kind":"text","text":" -> ["},{"kind":"typeIdentifier","preciseIdentifier":"s:11DotPalmCore0B8DetectorC0B0C","text":"Palm"},{"kind":"text","text":"]"}],"type":"topic","abstract":[{"text":"Detect palms in an image.","type":"text"}],"title":"detect(bgraRawImage:limit:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/detect(bgraRawImage:limit:)","navigatorTitle":[{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/detect(bgrarawimage:limit:)","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"Palm"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","role":"symbol","type":"topic","title":"PalmDetector.Palm","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"detectWithBgraRawImage:limit:error:","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"detectWithBgraRawImage:limit:error:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"NSArray<DOTPPalmDetectorPalm *>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" *) ","kind":"text"},{"text":"detectWithBgraRawImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTBgraRawImage","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTBgraRawImage","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/BgraRawImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"bgraRawImage"},{"text":" ","kind":"text"},{"kind":"identifier","text":"limit:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSInteger","text":"NSInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"limit","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","text":"NSError","kind":"typeIdentifier"},{"text":" * *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"value":"DOTBgraRawImage","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1BgraRawImage\/fragments","op":"replace","value":[{"text":"DOTBgraRawImage","kind":"identifier"}]},{"value":"detectWithBgraRawImage:limit:error:","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(bgraRawImage:limit:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1detect(bgraRawImage:limit:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"detectWithBgraRawImage:limit:error:","kind":"identifier"}]}]}]}