{"abstract":[{"text":"Create the palm detector.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/init()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotpalmcore\/palmdetector\/init()"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"override"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"()"}],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"init"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"externalID":"c:@M@DotPalmCore@objc(cs)DOTPPalmDetector(im)init","role":"symbol","title":"init()","modules":[{"name":"DotPalmCore"}],"symbolKind":"init"},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/init()","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"type":"topic","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector","title":"PalmDetector","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PalmDetector"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/init()":{"type":"topic","navigatorTitle":[{"text":"init","kind":"identifier"}],"url":"\/documentation\/dotpalmcore\/palmdetector\/init()","abstract":[{"type":"text","text":"Create the palm detector."}],"kind":"symbol","title":"init()","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/init()","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}]},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","kind":"symbol","title":"DotPalmCore","url":"\/documentation\/dotpalmcore","type":"topic","role":"collection","abstract":[{"type":"text","text":"version: 8.15.1"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"init","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"identifier","text":"init"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"DOTPPalmDetector","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","op":"replace","value":[{"kind":"identifier","text":"DOTPPalmDetector"}]},{"path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1init()\/title","op":"replace","value":"init"},{"value":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector~1init()\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}