{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotPalmCore\/documentation\/DotPalmCore","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector"]]},"seeAlsoSections":[{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble"],"generated":true,"title":"Palm detection output"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTPPalmDetectorPalm) "},{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Palm"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/dotpalmcore\/palmdetector\/palm"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}],"externalID":"s:11DotPalmCore0B8DetectorC0B0C","symbolKind":"class","roleHeading":"Class","title":"PalmDetector.Palm","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"role":"symbol","modules":[{"name":"DotPalmCore"}]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/confidence","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/description","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/detectionPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handOrientation","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handPosition","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/hash","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/imageParameters","doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/palmQuality"]},{"identifiers":["doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/isEqual(_:)"],"title":"Instance Methods"}],"abstract":[{"type":"text","text":"Result of the palm detection process."}],"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/DotPalmCore\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From"},{"title":"Conforms To","kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/DotPalmCore\/objc(pl)NSObject","doc:\/\/DotPalmCore\/s7CVarArgP","doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","doc:\/\/DotPalmCore\/SQ","doc:\/\/DotPalmCore\/SH"]}],"identifier":{"url":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","interfaceLanguage":"swift"},"references":{"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/imageParameters":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageParameters","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters","text":"ImageParameters","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","title":"imageParameters","abstract":[{"type":"text","text":"Image parameters calculated from the area of the detected palm."}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/imageparameters","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/imageParameters","role":"symbol"},"doc://DotPalmCore/objc(cs)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(cs)NSObject","type":"unresolvable","title":"ObjectiveC.NSObject"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/confidence":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/confidence","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/confidence","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"kind":"text","text":": "},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"Palm detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence."}],"title":"confidence","type":"topic","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/hash":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"kind":"symbol","role":"symbol","title":"hash","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/hash","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/hash","type":"topic"},"doc://DotPalmCore/SQ":{"identifier":"doc:\/\/DotPalmCore\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://DotPalmCore/SH":{"identifier":"doc:\/\/DotPalmCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/handOrientation":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/handorientation","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handOrientation","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"handOrientation","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","text":"HandOrientation","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Hand orientation, either palmar or dorsal."}],"title":"handOrientation","type":"topic","kind":"symbol","role":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/handPosition":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/handposition","role":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/handPosition","abstract":[{"text":"Hand position, either left or right.","type":"text"}],"kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"handPosition"},{"kind":"text","text":": "},{"text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","kind":"typeIdentifier"}],"title":"handPosition","type":"topic"},"doc://DotPalmCore/documentation/DotPalmCore/ImageParameters":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"ImageParameters","kind":"identifier"}],"title":"ImageParameters","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"ImageParameters"}],"url":"\/documentation\/dotpalmcore\/imageparameters","abstract":[{"type":"text","text":"Result of image parameters analysis."}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/ImageParameters"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)":{"type":"topic","kind":"symbol","role":"symbol","title":"init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/init(detectionPosition:confidence:imageParameters:palmQuality:handPosition:handOrientation:)","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/init(detectionposition:confidence:imageparameters:palmquality:handposition:handorientation:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"detectionPosition","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"DetectionPosition","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition"},{"text":", ","kind":"text"},{"text":"confidence","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"imageParameters"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"ImageParameters","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPImageParameters"},{"kind":"text","text":", "},{"kind":"externalParam","text":"palmQuality"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality","text":"PalmQuality"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"handPosition"},{"kind":"text","text":": "},{"text":"HandPosition","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandPosition","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"handOrientation","kind":"externalParam"},{"kind":"text","text":": "},{"text":"HandOrientation","preciseIdentifier":"c:@M@DotPalmCore@E@DOTPHandOrientation","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/isEqual(_:)":{"role":"symbol","type":"topic","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/isequal(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/isEqual(_:)","title":"isEqual(_:)","kind":"symbol"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm":{"abstract":[{"text":"Result of the palm detection process.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Palm"}],"role":"symbol","navigatorTitle":[{"text":"Palm","kind":"identifier"}],"title":"PalmDetector.Palm","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm","kind":"symbol","url":"\/documentation\/dotpalmcore\/palmdetector\/palm"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector":{"abstract":[{"text":"Stateless class which can detect palm in an image.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector","url":"\/documentation\/dotpalmcore\/palmdetector","kind":"symbol","navigatorTitle":[{"text":"PalmDetector","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PalmDetector"}],"title":"PalmDetector"},"doc://DotPalmCore/documentation/DotPalmCore":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore","url":"\/documentation\/dotpalmcore","kind":"symbol","title":"DotPalmCore","type":"topic","abstract":[{"type":"text","text":"version: 8.17.0"}],"role":"collection"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/detectionPosition":{"abstract":[{"text":"Detected corners of the palm.","type":"text"}],"kind":"symbol","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/detectionPosition","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"detectionPosition"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPDetectionPosition","text":"DetectionPosition","kind":"typeIdentifier"}],"title":"detectionPosition","url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/detectionposition"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/palmQuality":{"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/palmQuality","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"palmQuality"},{"text":": ","kind":"text"},{"text":"PalmQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotPalmCore@objc(cs)DOTPPalmQuality"}],"type":"topic","role":"symbol","abstract":[{"type":"text","text":"Palm quality."}],"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/palmquality","title":"palmQuality","kind":"symbol"},"doc://DotPalmCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotPalmCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotPalmCore/s7CVarArgP":{"identifier":"doc:\/\/DotPalmCore\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://DotPalmCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/PalmDetector/Palm/description":{"url":"\/documentation\/dotpalmcore\/palmdetector\/palm\/description","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"role":"symbol","title":"description","type":"topic","identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/PalmDetector\/Palm\/description","kind":"symbol","abstract":[]},"doc://DotPalmCore/s23CustomStringConvertibleP":{"identifier":"doc:\/\/DotPalmCore\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://DotPalmCore/documentation/DotPalmCore/RectangleDouble":{"abstract":[{"text":"Rectangle area defined by the edges with ","type":"text"},{"type":"codeVoice","code":"Double"},{"text":" value type.","type":"text"}],"identifier":"doc:\/\/DotPalmCore\/documentation\/DotPalmCore\/RectangleDouble","url":"\/documentation\/dotpalmcore\/rectangledouble","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleDouble"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"RectangleDouble","kind":"identifier"}],"title":"RectangleDouble"}},"variantOverrides":[{"patch":[{"value":"DOTPImageParameters","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/title"},{"value":[{"text":"DOTPImageParameters","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1ImageParameters\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/title","value":"DOTPPalmDetector"},{"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1PalmDetector\/fragments","value":[{"text":"DOTPPalmDetector","kind":"identifier"}]},{"value":"DOTRectangleDouble","op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/title"},{"value":[{"text":"DOTRectangleDouble","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotPalmCore~1documentation~1DotPalmCore~1RectangleDouble\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}