{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioTooSmall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requiredMin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/dotfacecore\/faceimagefactory\/error\/minfacesizeratiotoosmall(requiredmin:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooSmall(requiredMin:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioTooSmall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requiredMin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"title":"FaceImageFactory.Error.minFaceSizeRatioTooSmall(requiredMin:)","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"s:11DotFaceCore0B12ImageFactoryC5ErrorO03minB17SizeRatioTooSmallyAESd_tcAEmF","modules":[{"name":"DotFaceCore"}]},"hierarchy":{"paths":[["doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory","doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error"]]},"references":{"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore":{"role":"collection","title":"DotFaceCore","abstract":[{"type":"text","text":"version: 5.0.0"}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceDetector":{"role":"symbol","title":"FaceDetector","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect faces in an image."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceDetector","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceDetector"}],"url":"\/documentation\/dotfacecore\/facedetector"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory":{"role":"symbol","title":"FaceImageFactory","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceImageFactory"}],"abstract":[{"type":"text","text":"Factory which creates face images."}],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"FaceImageFactory"}],"url":"\/documentation\/dotfacecore\/faceimagefactory"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error":{"role":"symbol","title":"FaceImageFactory.Error","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Error"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Error"}],"url":"\/documentation\/dotfacecore\/faceimagefactory\/error"},"doc://com.innovatrics.dot.face.core/documentation/DotFaceCore/FaceImageFactory/Error/minFaceSizeRatioTooSmall(requiredMin:)":{"role":"symbol","title":"FaceImageFactory.Error.minFaceSizeRatioTooSmall(requiredMin:)","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"minFaceSizeRatioTooSmall"},{"kind":"text","text":"("},{"kind":"externalParam","text":"requiredMin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.innovatrics.dot.face.core\/documentation\/DotFaceCore\/FaceImageFactory\/Error\/minFaceSizeRatioTooSmall(requiredMin:)","kind":"symbol","type":"topic","url":"\/documentation\/dotfacecore\/faceimagefactory\/error\/minfacesizeratiotoosmall(requiredmin:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/title","value":"DOTFFaceDetector"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceDetector\/fragments","value":[{"kind":"identifier","text":"DOTFFaceDetector"}]},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageFactory\/title","value":"DOTFFaceImageFactory"},{"op":"replace","path":"\/references\/doc:~1~1com.innovatrics.dot.face.core~1documentation~1DotFaceCore~1FaceImageFactory\/fragments","value":[{"kind":"identifier","text":"DOTFFaceImageFactory"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}