{"metadata":{"title":"faceAutoCaptureViewControllerNoCameraPermission(_:)","externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate(im)faceLiteAutoCaptureViewControllerNoCameraPermission:","symbolKind":"method","navigatorTitle":[{"text":"faceLiteAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}],"roleHeading":"Instance Method","modules":[{"name":"DotFaceLite"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerNoCameraPermission","kind":"identifier"},{"kind":"text","text":"("},{"text":"FaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController"},{"kind":"text","text":")"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerNoCameraPermission(_:)"},"abstract":[{"text":"Tells the delegate that you have no permission for camera usage.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":"(faceLiteAutoCaptureViewControllerNoCameraPermission:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewControllerNoCameraPermission","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"viewController","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","text":"FaceAutoCaptureViewController","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollernocamerapermission(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollernocamerapermission(_:)"]}],"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]]},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"title":"FaceAutoCaptureViewController","abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","type":"topic","role":"symbol","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite":{"abstract":[{"text":"version: 8.10.0","type":"text"}],"role":"collection","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","url":"\/documentation\/dotfacelite","type":"topic","title":"DotFaceLite","kind":"symbol"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate","type":"topic","title":"FaceAutoCaptureViewControllerDelegate","abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewControllerNoCameraPermission(_:)":{"title":"faceAutoCaptureViewControllerNoCameraPermission(_:)","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontrollernocamerapermission(_:)","type":"topic","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewControllerNoCameraPermission(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewControllerNoCameraPermission"},{"kind":"text","text":"("},{"text":"FaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerNoCameraPermission:"}],"kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that you have no permission for camera usage."}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"faceLiteAutoCaptureViewControllerNoCameraPermission:"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"faceLiteAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"faceLiteAutoCaptureViewControllerNoCameraPermission:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewController"}],"op":"replace"},{"value":"DOTFLFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","value":"faceLiteAutoCaptureViewControllerNoCameraPermission:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerNoCameraPermission(_:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewControllerNoCameraPermission:"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewControllerNoCameraPermission(_:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}