{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]]},"identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:captured:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Tells the delegate that the face was captured. This callback is called after the component has stopped."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:captured:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:captured:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate(im)faceLiteAutoCaptureViewController:captured:","roleHeading":"Instance Method","title":"faceAutoCaptureViewController(_:captured:)","modules":[{"name":"DotFaceLite"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","kind":"typeIdentifier","text":"FaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","kind":"typeIdentifier","text":"FaceAutoCaptureResult"},{"kind":"text","text":")"}],"required":true,"navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewController:captured:"}],"role":"symbol","symbolKind":"method"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(faceLiteAutoCaptureViewController:captured:) "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":" "},{"kind":"internalParam","text":"result"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"FaceAutoCaptureResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"abstract":[{"type":"text","text":"UI component for capturing face images using the placeholder."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewController"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","title":"FaceAutoCaptureViewController","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureResult":{"abstract":[{"text":"The final result of the face auto capture process.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureResult"}],"role":"symbol","title":"FaceAutoCaptureResult","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureresult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","navigatorTitle":[{"kind":"identifier","text":"FaceAutoCaptureResult"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:captured:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"faceAutoCaptureViewController"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","text":"FaceAutoCaptureViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"captured"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","text":"FaceAutoCaptureResult"},{"kind":"text","text":")"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Tells the delegate that the face was captured. This callback is called after the component has stopped."}],"navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewController:captured:"}],"required":true,"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:captured:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:captured:)","title":"faceAutoCaptureViewController(_:captured:)"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"abstract":[{"type":"text","text":"Implement this delegate to handle the face auto capture events."}],"kind":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate","title":"FaceAutoCaptureViewControllerDelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","role":"collection","abstract":[{"type":"text","text":"version: 8.17.1"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"faceLiteAutoCaptureViewController:captured:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewController:captured:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"faceLiteAutoCaptureViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureViewController","kind":"typeIdentifier","text":"DOTFLFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"viewController"},{"kind":"text","text":" "},{"kind":"identifier","text":"captured:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureResult","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureResult","text":"DOTFLFaceAutoCaptureResult","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"result","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","value":"DOTFLFaceAutoCaptureViewController"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/title","value":"DOTFLFaceAutoCaptureResult"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/fragments","value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureResult"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureResult\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureResult","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:captured:)\/title","value":"faceLiteAutoCaptureViewController:captured:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:captured:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewController:captured:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title","value":"DOTFLFaceAutoCaptureViewControllerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments","value":[{"text":"DOTFLFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/navigatorTitle","value":[{"text":"DOTFLFaceAutoCaptureViewControllerDelegate","kind":"identifier"}]}]}]}