{"hierarchy":{"paths":[["doc:\/\/DotFaceLite\/documentation\/DotFaceLite","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate"]]},"abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(faceLiteAutoCaptureViewController:uiStateUpdated:) ","kind":"text"},{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"uiState","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:uiStateUpdated:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"title":"faceAutoCaptureViewController(_:uiStateUpdated:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","text":"BaseFaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState","text":"FaceAutoCaptureUiState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"faceLiteAutoCaptureViewController:uiStateUpdated:"}],"modules":[{"name":"DotFaceLite"}],"externalID":"c:@M@DotFaceLite@objc(pl)DOTFLFaceAutoCaptureViewControllerDelegate(im)faceLiteAutoCaptureViewController:uiStateUpdated:","role":"symbol","symbolKind":"method","roleHeading":"Instance Method"},"references":{"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate":{"title":"FaceAutoCaptureViewControllerDelegate","type":"topic","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate","navigatorTitle":[{"text":"FaceAutoCaptureViewControllerDelegate","kind":"identifier"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"FaceAutoCaptureViewControllerDelegate"}],"role":"symbol","abstract":[{"text":"Implement this delegate to handle the face auto capture events.","type":"text"}]},"doc://DotFaceLite/documentation/DotFaceLite":{"role":"collection","abstract":[{"text":"version: 9.0.0","type":"text"}],"kind":"symbol","url":"\/documentation\/dotfacelite","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite","title":"DotFaceLite","type":"topic"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureUiState":{"type":"topic","abstract":[{"type":"text","text":"This class defines the different states that the UI can be in during the process."}],"url":"\/documentation\/dotfacelite\/faceautocaptureuistate","kind":"symbol","title":"FaceAutoCaptureUiState","navigatorTitle":[{"text":"FaceAutoCaptureUiState","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureUiState","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewController":{"abstract":[{"text":"UI Face Auto Capture component.","type":"text"}],"role":"symbol","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontroller","title":"FaceAutoCaptureViewController","kind":"symbol","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewController","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"FaceAutoCaptureViewController","kind":"identifier"}],"navigatorTitle":[{"text":"FaceAutoCaptureViewController","kind":"identifier"}]},"doc://DotFaceLite/documentation/DotFaceLite/BaseFaceAutoCaptureViewController":{"abstract":[{"text":"UI component for capturing face images with customizable UI.","type":"text"}],"kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/dotfacelite\/basefaceautocaptureviewcontroller","navigatorTitle":[{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BaseFaceAutoCaptureViewController"}],"title":"BaseFaceAutoCaptureViewController","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController"},"doc://DotFaceLite/documentation/DotFaceLite/FaceAutoCaptureViewControllerDelegate/faceAutoCaptureViewController(_:uiStateUpdated:)":{"type":"topic","kind":"symbol","title":"faceAutoCaptureViewController(_:uiStateUpdated:)","url":"\/documentation\/dotfacelite\/faceautocaptureviewcontrollerdelegate\/faceautocaptureviewcontroller(_:uistateupdated:)","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureViewControllerDelegate\/faceAutoCaptureViewController(_:uiStateUpdated:)","abstract":[{"type":"text","text":"Tells the delegate that the UI state was updated."}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"faceAutoCaptureViewController","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"uiStateUpdated","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"FaceAutoCaptureUiState","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState","kind":"typeIdentifier"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"faceLiteAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"faceLiteAutoCaptureViewController:uiStateUpdated:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"faceLiteAutoCaptureViewController:uiStateUpdated:"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"faceLiteAutoCaptureViewController:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/BaseFaceAutoCaptureViewController","preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLBaseFaceAutoCaptureViewController","text":"DOTFLBaseFaceAutoCaptureViewController","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"uiStateUpdated:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@M@DotFaceLite@objc(cs)DOTFLFaceAutoCaptureUiState","text":"DOTFLFaceAutoCaptureUiState","identifier":"doc:\/\/DotFaceLite\/documentation\/DotFaceLite\/FaceAutoCaptureUiState","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"uiState","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"DOTFLFaceAutoCaptureViewControllerDelegate","op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/title"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewControllerDelegate"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureViewControllerDelegate"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceAutoCaptureUiState","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureUiState","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"DOTFLFaceAutoCaptureUiState"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureUiState\/navigatorTitle","op":"replace"},{"value":"DOTFLFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFLFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"DOTFLBaseFaceAutoCaptureViewController","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/title","op":"replace"},{"value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/fragments","op":"replace"},{"value":[{"text":"DOTFLBaseFaceAutoCaptureViewController","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1BaseFaceAutoCaptureViewController\/navigatorTitle","op":"replace"},{"value":"faceLiteAutoCaptureViewController:uiStateUpdated:","path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:uiStateUpdated:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"faceLiteAutoCaptureViewController:uiStateUpdated:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceLite~1documentation~1DotFaceLite~1FaceAutoCaptureViewControllerDelegate~1faceAutoCaptureViewController(_:uiStateUpdated:)\/fragments","op":"replace"}]}]}