{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/confidence","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}]}]}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/document\/confidence"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"type":"text","text":"Document detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence."}],"sections":[],"kind":"symbol","metadata":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"confidence","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"symbolKind":"property","title":"confidence","externalID":"s:11DotDocument0B8DetectorC0B0C10confidenceSdvp","role":"symbol","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property"},"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","navigatorTitle":[{"text":"DocumentDetector","kind":"identifier"}],"kind":"symbol","type":"topic","title":"DocumentDetector","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"type":"text","text":"Stateless class which can detect document in an image."}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://DotDocument/documentation/DotDocument":{"role":"collection","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 8.11.0"}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","kind":"symbol","title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"abstract":[{"text":"Stateless class which can read MRZ using image and document detection result.","type":"text"}],"navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"title":"MrzReader","url":"\/documentation\/dotdocument\/mrzreader","role":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"MrzReader"}],"type":"topic","kind":"symbol"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"url":"\/documentation\/dotdocument\/documentdetector\/document","abstract":[{"text":"Result of the document detection process.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"Document","kind":"identifier"}],"title":"DocumentDetector.Document"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/confidence":{"kind":"symbol","url":"\/documentation\/dotdocument\/documentdetector\/document\/confidence","title":"confidence","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/confidence","abstract":[{"type":"text","text":"Document detection confidence in range [0, 1.0]. Where 0 means low confidence and 1.0 means high confidence."}],"role":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"confidence"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title","op":"replace","value":"DOTDDocumentDetector"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title","value":"DOTDMrzReader"},{"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments","value":[{"text":"DOTDMrzReader","kind":"identifier"}]}]}]}