{"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument"}],"roleHeading":"Instance Property","title":"quality","externalID":"s:11DotDocument0B8DetectorC0B0C7qualityAA0B7QualityCvp","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality","text":"DocumentQuality"}]},"sections":[],"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/quality","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Document quality attributes."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"],["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"quality","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality","text":"DocumentQuality","kind":"typeIdentifier","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality"}]}]}],"variants":[{"paths":["\/documentation\/dotdocument\/documentdetector\/document\/quality"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://DotDocument/documentation/DotDocument/DocumentDetector":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector","role":"symbol","kind":"symbol","type":"topic","title":"DocumentDetector","navigatorTitle":[{"kind":"identifier","text":"DocumentDetector"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DocumentDetector"}],"abstract":[{"text":"Stateless class which can detect document in an image.","type":"text"}],"url":"\/documentation\/dotdocument\/documentdetector"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document/quality":{"url":"\/documentation\/dotdocument\/documentdetector\/document\/quality","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document\/quality","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"quality"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DocumentQuality","preciseIdentifier":"c:@M@DotDocument@objc(cs)DOTDDocumentQuality"}],"abstract":[{"type":"text","text":"Document quality attributes."}],"title":"quality"},"doc://DotDocument/documentation/DotDocument/MrzReader":{"url":"\/documentation\/dotdocument\/mrzreader","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/MrzReader","kind":"symbol","navigatorTitle":[{"text":"MrzReader","kind":"identifier"}],"abstract":[{"type":"text","text":"Stateless class which can read MRZ using image and document detection result."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"MrzReader","kind":"identifier"}],"role":"symbol","title":"MrzReader","type":"topic"},"doc://DotDocument/documentation/DotDocument/DocumentQuality":{"role":"symbol","navigatorTitle":[{"text":"DocumentQuality","kind":"identifier"}],"url":"\/documentation\/dotdocument\/documentquality","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DocumentQuality","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Document quality."}],"title":"DocumentQuality","kind":"symbol","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentQuality"},"doc://DotDocument/documentation/DotDocument":{"kind":"symbol","role":"collection","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","type":"topic","url":"\/documentation\/dotdocument","abstract":[{"type":"text","text":"version: 9.0.1"}],"title":"DotDocument"},"doc://DotDocument/documentation/DotDocument/DocumentDetector/Document":{"url":"\/documentation\/dotdocument\/documentdetector\/document","abstract":[{"type":"text","text":"Result of the document detection process."}],"type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/DocumentDetector\/Document","kind":"symbol","title":"DocumentDetector.Document","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Document","kind":"identifier"}],"navigatorTitle":[{"text":"Document","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"DOTDDocumentDetector","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/title"},{"value":[{"text":"DOTDDocumentDetector","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/fragments"},{"value":[{"kind":"identifier","text":"DOTDDocumentDetector"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentDetector\/navigatorTitle"},{"value":"DOTDMrzReader","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/title"},{"value":[{"text":"DOTDMrzReader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/fragments"},{"value":[{"kind":"identifier","text":"DOTDMrzReader"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1MrzReader\/navigatorTitle"},{"value":"DOTDDocumentQuality","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/title"},{"value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/fragments"},{"value":[{"text":"DOTDDocumentQuality","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1DocumentQuality\/navigatorTitle"}]}]}