{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore"]]},"metadata":{"symbolKind":"class","title":"RectangleInt","role":"symbol","modules":[{"name":"DotFaceCore"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"roleHeading":"Class","externalID":"c:@M@DotCore@objc(cs)DOTRectangleInt"},"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"type":"codeVoice","code":"Int"},{"type":"text","text":" value type."}],"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/init(left:top:right:bottom:)"],"anchor":"Initializers"},{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/bottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/cgRect","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/height","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/left","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/origin","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/right","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/top","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/width","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/widthToHeightRatio"],"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/isEqual(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/from(cgRect:)"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":"(DOTRectangleInt) "},{"kind":"keyword","text":"final"},{"text":" ","kind":"text"},{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"RectangleInt","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotfacecore\/rectangleint"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/rectangleint"]}],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"kind":"relationships"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/DotFaceCore\/objc(pl)NSObject","doc:\/\/DotFaceCore\/s7CVarArgP","doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","doc:\/\/DotFaceCore\/SQ","doc:\/\/DotFaceCore\/SH"],"type":"conformsTo"}],"references":{"doc://DotFaceCore/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/hash":{"title":"hash","url":"\/documentation\/dotfacecore\/rectangleint\/hash","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"hash"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"abstract":[],"type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/hash"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/bottom":{"kind":"symbol","abstract":[{"type":"text","text":"Bottom edge."}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/bottom","title":"bottom","role":"symbol","url":"\/documentation\/dotfacecore\/rectangleint\/bottom","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"bottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"bottom"}],"type":"topic"},"doc://DotFaceCore/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/DotFaceCore\/SQ"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/right":{"abstract":[{"text":"Right edge.","type":"text"}],"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"right"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"right"}],"title":"right","role":"symbol","url":"\/documentation\/dotfacecore\/rectangleint\/right","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/right","type":"topic"},"doc://DotFaceCore/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/DotFaceCore\/objc(cs)NSObject","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/width":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"width","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/width","navigatorTitle":[{"text":"width","kind":"identifier"}],"kind":"symbol","type":"topic","title":"width","url":"\/documentation\/dotfacecore\/rectangleint\/width","role":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/origin":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"origin"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PointInt","preciseIdentifier":"c:@M@DotCore@objc(cs)DOTPointInt"}],"navigatorTitle":[{"kind":"identifier","text":"origin"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/origin","url":"\/documentation\/dotfacecore\/rectangleint\/origin","abstract":[],"kind":"symbol","type":"topic","title":"origin"},"doc://DotFaceCore/s7CVarArgP":{"identifier":"doc:\/\/DotFaceCore\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/from(cgRect:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/from(cgRect:)","title":"from(cgRect:)","abstract":[],"url":"\/documentation\/dotfacecore\/rectangleint\/from(cgrect:)","role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"fromCgRect:"}],"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"from","kind":"identifier"},{"text":"(","kind":"text"},{"text":"cgRect","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGRect","text":"CGRect","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@DotCore@objc(cs)DOTRectangleInt","text":"RectangleInt","kind":"typeIdentifier"}]},"doc://DotFaceCore/SH":{"identifier":"doc:\/\/DotFaceCore\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/description":{"url":"\/documentation\/dotfacecore\/rectangleint\/description","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"description"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/description","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"description","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"title":"description","kind":"symbol"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/top":{"title":"top","url":"\/documentation\/dotfacecore\/rectangleint\/top","abstract":[{"text":"Top edge.","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"top"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"top"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/top"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/height":{"title":"height","url":"\/documentation\/dotfacecore\/rectangleint\/height","abstract":[],"kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"height"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"height"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/height"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/widthToHeightRatio":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"widthToHeightRatio","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"navigatorTitle":[{"text":"widthToHeightRatio","kind":"identifier"}],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/widthToHeightRatio","url":"\/documentation\/dotfacecore\/rectangleint\/widthtoheightratio","abstract":[],"kind":"symbol","type":"topic","title":"widthToHeightRatio"},"doc://DotFaceCore/objc(pl)NSObject":{"identifier":"doc:\/\/DotFaceCore\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://DotFaceCore/documentation/DotFaceCore":{"kind":"symbol","url":"\/documentation\/dotfacecore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","abstract":[{"type":"text","text":"version: 9.2.2"}],"role":"collection","title":"DotFaceCore","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/isEqual(_:)":{"title":"isEqual(_:)","url":"\/documentation\/dotfacecore\/rectangleint\/isequal(_:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"isEqual:"}],"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEqual","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/isEqual(_:)","type":"topic"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt":{"abstract":[{"type":"text","text":"Rectangle area defined by the edges with "},{"code":"Int","type":"codeVoice"},{"type":"text","text":" value type."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"RectangleInt"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"RectangleInt"}],"title":"RectangleInt","role":"symbol","url":"\/documentation\/dotfacecore\/rectangleint","type":"topic","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/init(left:top:right:bottom:)":{"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/init(left:top:right:bottom:)","title":"init(left:top:right:bottom:)","url":"\/documentation\/dotfacecore\/rectangleint\/init(left:top:right:bottom:)","abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"initWithLeft:top:right:bottom:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"left"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"top","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"right","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":", ","kind":"text"},{"text":"bottom","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}]},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/left":{"title":"left","role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/left","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"left","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"left","kind":"identifier"}],"abstract":[{"type":"text","text":"Left edge."}],"kind":"symbol","url":"\/documentation\/dotfacecore\/rectangleint\/left","type":"topic"},"doc://DotFaceCore/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/DotFaceCore\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://DotFaceCore/documentation/DotFaceCore/RectangleInt/cgRect":{"kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"cgRect"}],"role":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/cgRect","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgRect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"title":"cgRect","url":"\/documentation\/dotfacecore\/rectangleint\/cgrect"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","value":null,"op":"add"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"path":"\/metadata\/title","value":"DOTRectangleInt","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/bottom","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/cgRect","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/description","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/hash","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/height","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/left","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/origin","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/right","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/top","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/width","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/widthToHeightRatio"],"generated":true},{"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/init(left:top:right:bottom:)","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/isEqual(_:)"],"generated":true},{"title":"Type Methods","generated":true,"identifiers":["doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/RectangleInt\/from(cgRect:)"],"anchor":"Type-Methods"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/DotFaceCore\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DOTRectangleInt"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]},"op":"replace"},{"op":"replace","value":"hash","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1hash\/title"},{"value":[{"kind":"identifier","text":"hash"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1hash\/fragments"},{"op":"replace","value":"bottom","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1bottom\/title"},{"op":"replace","value":[{"text":"bottom","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1bottom\/fragments"},{"op":"replace","value":"right","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1right\/title"},{"op":"replace","value":[{"kind":"identifier","text":"right"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1right\/fragments"},{"op":"replace","value":"width","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1width\/title"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1width\/fragments","value":[{"text":"width","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1origin\/title","value":"origin"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1origin\/fragments","op":"replace","value":[{"text":"origin","kind":"identifier"}]},{"value":"fromCgRect:","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1from(cgRect:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"fromCgRect:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1from(cgRect:)\/fragments"},{"value":"description","op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1description\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1description\/fragments","value":[{"text":"description","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1top\/title","value":"top","op":"replace"},{"op":"replace","value":[{"text":"top","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1top\/fragments"},{"op":"replace","value":"height","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1height\/title"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1height\/fragments","op":"replace","value":[{"text":"height","kind":"identifier"}]},{"op":"replace","value":"widthToHeightRatio","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1widthToHeightRatio\/title"},{"op":"replace","value":[{"kind":"identifier","text":"widthToHeightRatio"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1widthToHeightRatio\/fragments"},{"op":"replace","value":"isEqual:","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1isEqual(_:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"isEqual:","kind":"identifier"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1isEqual(_:)\/fragments"},{"value":"DOTRectangleInt","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/title","op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/fragments","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt\/navigatorTitle","value":[{"text":"DOTRectangleInt","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1init(left:top:right:bottom:)\/title","value":"initWithLeft:top:right:bottom:"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1init(left:top:right:bottom:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithLeft:top:right:bottom:"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1left\/title","value":"left"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1left\/fragments","value":[{"kind":"identifier","text":"left"}]},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1cgRect\/title","value":"cgRect"},{"op":"replace","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1RectangleInt~1cgRect\/fragments","value":[{"kind":"identifier","text":"cgRect"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}