{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dg15"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg15"},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg15"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotnfc\/lds1elementaryfileid\/dg15"]}],"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg15"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","platforms":[{"name":"iOS","beta":false,"introducedAt":"13.0","unavailable":false,"deprecated":false}],"externalID":"c:@M@DotNfc@E@DOTNLds1ElementaryFileId@DOTNLds1ElementaryFileIdDg15","modules":[{"name":"DotNfc"}],"title":"Lds1ElementaryFileId.dg15","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dg15","kind":"identifier"}]},"kind":"symbol","abstract":[{"type":"text","text":"File identifier for data group 15. Data group 15 contains the public key used for Active Authentication."}],"references":{"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId/dg15":{"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId\/dg15","title":"Lds1ElementaryFileId.dg15","role":"symbol","abstract":[{"type":"text","text":"File identifier for data group 15. Data group 15 contains the public key used for Active Authentication."}],"url":"\/documentation\/dotnfc\/lds1elementaryfileid\/dg15","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"dg15"}],"navigatorTitle":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg15"}]},"doc://DotNfc/documentation/DotNfc":{"title":"DotNfc","role":"collection","url":"\/documentation\/dotnfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","abstract":[{"type":"text","text":"version: 8.7.0"}],"kind":"symbol"},"doc://DotNfc/documentation/DotNfc/Lds1ElementaryFileId":{"navigatorTitle":[{"text":"Lds1ElementaryFileId","kind":"identifier"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Lds1ElementaryFileId"}],"type":"topic","kind":"symbol","abstract":[{"type":"text","text":"Identifier of the LDS1 Elementary File."}],"identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/Lds1ElementaryFileId","title":"Lds1ElementaryFileId","role":"symbol","url":"\/documentation\/dotnfc\/lds1elementaryfileid"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"DOTNLds1ElementaryFileIdDg15","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"DOTNLds1ElementaryFileIdDg15"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"DOTNLds1ElementaryFileIdDg15","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg15\/title","value":"DOTNLds1ElementaryFileIdDg15"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFileIdDg15","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId~1dg15\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/title","op":"replace","value":"DOTNLds1ElementaryFileId"},{"op":"replace","value":[{"text":"DOTNLds1ElementaryFileId","kind":"identifier"}],"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1Lds1ElementaryFileId\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}