{"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/helpAnchor","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/error\/helpanchor"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"LocalizedError.helpAnchor","type":"codeVoice"},{"type":"text","text":"."}],"sections":[],"metadata":{"symbolKind":"property","modules":[{"name":"DotDocument","relatedModules":["Foundation"]}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"roleHeading":"Instance Property","extendedModule":"Foundation","title":"helpAnchor","platforms":[{"unavailable":false,"introducedAt":"8.0","name":"iOS","beta":false,"deprecated":false},{"introducedAt":"8.0","beta":false,"name":"iPadOS","deprecated":false,"unavailable":false},{"unavailable":false,"introducedAt":"8.0","name":"Mac Catalyst","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"10.10","name":"macOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"9.0","name":"tvOS","beta":false,"deprecated":false},{"unavailable":false,"introducedAt":"2.0","name":"watchOS","beta":false,"deprecated":false}],"role":"symbol","externalID":"s:10Foundation14LocalizedErrorPAAE10helpAnchorSSSgvp::SYNTHESIZED::s:7DotCore13IntervalFloatC5ErrorO"},"references":{"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"},"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error":{"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"IntervalFloat.Error","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error","url":"\/documentation\/dotdocument\/intervalfloat\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error/helpAnchor":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/helpAnchor","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"helpAnchor","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"helpAnchor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/intervalfloat\/error\/helpanchor"},"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"IntervalFloat","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","url":"\/documentation\/dotdocument\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"DOTIntervalFloat","op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments"},{"value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}