{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/dotdocument\/intervalfloat\/error\/internalerror"]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"DotSdkError.internalError","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/internalError","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/DotDocument\/documentation\/DotDocument","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error"]]},"kind":"symbol","metadata":{"modules":[{"name":"DotDocument"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"internalError","roleHeading":"Instance Property","externalID":"s:7DotCore13IntervalFloatC5ErrorO08internalE0sAD_pSgvp","role":"symbol","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":": Swift","kind":"text"},{"text":".","kind":"text"},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotDocument/documentation/DotDocument/IntervalFloat":{"abstract":[{"text":"Representation of closed interval with value type ","type":"text"},{"code":"Float","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"The ","type":"text"},{"code":"max","type":"codeVoice"},{"text":" must be greater than the ","type":"text"},{"code":"min","type":"codeVoice"},{"text":".","type":"text"}],"navigatorTitle":[{"text":"IntervalFloat","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"IntervalFloat","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat","url":"\/documentation\/dotdocument\/intervalfloat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IntervalFloat","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error":{"abstract":[],"navigatorTitle":[{"text":"Error","kind":"identifier"}],"kind":"symbol","role":"symbol","title":"IntervalFloat.Error","type":"topic","identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error","url":"\/documentation\/dotdocument\/intervalfloat\/error","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Error","kind":"identifier"}]},"doc://DotDocument/documentation/DotDocument/IntervalFloat/Error/internalError":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument\/IntervalFloat\/Error\/internalError","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"internalError","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":": Swift"},{"kind":"text","text":"."},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"url":"\/documentation\/dotdocument\/intervalfloat\/error\/internalerror"},"doc://DotDocument/documentation/DotDocument":{"identifier":"doc:\/\/DotDocument\/documentation\/DotDocument","url":"\/documentation\/dotdocument","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.4.0"}],"title":"DotDocument","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/title","value":"DOTIntervalFloat","op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/fragments","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1DotDocument~1documentation~1DotDocument~1IntervalFloat\/navigatorTitle","value":[{"text":"DOTIntervalFloat","kind":"identifier"}],"op":"replace"}]}]}