{"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dotfacecore\/dotnfclibraryconfiguration\/init"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"init"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/DotFaceCore\/documentation\/DotFaceCore","doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotNfcLibraryConfiguration"]]},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"symbolKind":"method","title":"init","externalID":"c:@M@DotCore@objc(cs)DotNfcLibraryConfiguration(im)init","roleHeading":"Instance Method","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"modules":[{"name":"DotFaceCore"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"role":"symbol"},"identifier":{"url":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotNfcLibraryConfiguration\/init","interfaceLanguage":"occ"},"references":{"doc://DotFaceCore/documentation/DotFaceCore/DotNfcLibraryConfiguration":{"url":"\/documentation\/dotfacecore\/dotnfclibraryconfiguration","role":"symbol","navigatorTitle":[{"text":"DotNfcLibraryConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"text":"NFC library configuration.","type":"text"}],"title":"DotNfcLibraryConfiguration","kind":"symbol","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotNfcLibraryConfiguration","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DotNfcLibraryConfiguration","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore/DotNfcLibraryConfiguration/init":{"url":"\/documentation\/dotfacecore\/dotnfclibraryconfiguration\/init","role":"symbol","navigatorTitle":[{"text":"init","kind":"identifier"}],"type":"topic","kind":"symbol","abstract":[],"identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore\/DotNfcLibraryConfiguration\/init","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"doc://DotFaceCore/documentation/DotFaceCore":{"title":"DotFaceCore","identifier":"doc:\/\/DotFaceCore\/documentation\/DotFaceCore","type":"topic","kind":"symbol","abstract":[{"type":"text","text":"version: 9.2.0"}],"role":"collection","url":"\/documentation\/dotfacecore"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"DotNfcLibraryConfiguration","path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotNfcLibraryConfiguration\/title"},{"op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotNfcLibraryConfiguration\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"DotNfcLibraryConfiguration"}],"path":"\/references\/doc:~1~1DotFaceCore~1documentation~1DotFaceCore~1DotNfcLibraryConfiguration\/navigatorTitle"}]}]}