{"metadata":{"role":"symbol","title":"status","modules":[{"name":"DotNfc"}],"platforms":[{"unavailable":false,"introducedAt":"13.0","deprecated":false,"beta":false,"name":"iOS"}],"externalID":"c:@M@DotNfc@objc(cs)DOTNDataAuthenticationStatus(py)status","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"status","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Status","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O"}],"roleHeading":"Instance Property","symbolKind":"property","navigatorTitle":[{"text":"status","kind":"identifier"}]},"abstract":[{"type":"text","text":"Status of the authentication process."}],"sections":[],"identifier":{"url":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/status-swift.property","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/DotNfc\/documentation\/DotNfc","doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus"]]},"variants":[{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.property"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.property"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"Status","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/status-swift.property":{"abstract":[{"type":"text","text":"Status of the authentication process."}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:6DotNfc24DataAuthenticationStatusC0E0O","text":"Status"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.property","title":"status","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/status-swift.property","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"status"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus/Status-swift.enum":{"role":"symbol","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus\/Status-swift.enum","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"Status","kind":"identifier"}],"url":"\/documentation\/dotnfc\/dataauthenticationstatus\/status-swift.enum","title":"DataAuthenticationStatus.Status","navigatorTitle":[{"kind":"identifier","text":"Status"}],"type":"topic","abstract":[{"text":"Authentication status of the data.","type":"text"}]},"doc://DotNfc/documentation/DotNfc/DataAuthenticationStatus":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DataAuthenticationStatus"}],"abstract":[{"type":"text","text":"Authentication status of the data and protocol used for that purpose."}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DataAuthenticationStatus"}],"title":"DataAuthenticationStatus","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DataAuthenticationStatus","role":"symbol","url":"\/documentation\/dotnfc\/dataauthenticationstatus"},"doc://DotNfc/documentation/DotNfc":{"abstract":[{"type":"text","text":"version: 8.12.0"}],"title":"DotNfc","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc","type":"topic","kind":"symbol","url":"\/documentation\/dotnfc","role":"collection"},"doc://DotNfc/documentation/DotNfc/DOTNDataAuthenticationStatusStatus":{"fragments":[{"kind":"identifier","text":"DOTNDataAuthenticationStatusStatus"}],"abstract":[{"type":"text","text":"Authentication status of the data."}],"kind":"symbol","title":"DOTNDataAuthenticationStatusStatus","type":"topic","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus","role":"symbol","url":"\/documentation\/dotnfc\/dotndataauthenticationstatusstatus"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"status"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DOTNDataAuthenticationStatusStatus","preciseIdentifier":"c:@M@DotNfc@E@DOTNDataAuthenticationStatusStatus","kind":"typeIdentifier","identifier":"doc:\/\/DotNfc\/documentation\/DotNfc\/DOTNDataAuthenticationStatusStatus"},{"kind":"text","text":" "},{"kind":"identifier","text":"status"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1status-swift.property\/title","value":"status"},{"value":[{"kind":"identifier","text":"status"}],"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus~1status-swift.property\/fragments"},{"path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/title","op":"replace","value":"DOTNDataAuthenticationStatus"},{"op":"replace","path":"\/references\/doc:~1~1DotNfc~1documentation~1DotNfc~1DataAuthenticationStatus\/fragments","value":[{"kind":"identifier","text":"DOTNDataAuthenticationStatus"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}